define(
	({
		REPORT_WHEN : "den",
		RESOURCES_ON : "Ressurser på",
		PLAYER_BANNED : "b",
		PLAYER_VACATION_MODE : "v",
		PLAYER_NOOB : "n",
		PLAYER_INACTIVE : "i",
		PLAYER_LONG_INACTIVE : "I",
		PLAYER_OUTLAW : "o",
		L_USERNAME : "Brukernavn",
		L_PASSWORD : "Passord",
		L_LOGINFAILURE : "Brukernavn eller passord var feil, din konto er ikke altivert ennå.",
		L_TOKENFAILURE : "Your logon key is wrong or your account is not activated yet.",
		L_LOGINTEXT : "Login.",
		L_LANGUAGE : "Språk:",
		L_TIMEOUT : "Session timed out!",
		L_REGISTER : "Registrer",
		L_PWLOST : "glemt passord",
		INDEX_TITLE : "OGame Galaxietool - Oversikt",
		INDEX_INFO : "Informasjon",
		INDEX_ENTRIES : "Antall Systemer",
		INDEX_ENTRIES_LASTWEEK : "Nye systemer sist uke",
		INDEX_ENTRIES_TO_OLD : "Systemer eldre enn en måned",
		INDEX_REGISTERED_USERS : "Registrer Bruker",
		INDEX_PAGEFORWARD : "Vist din nettleser ikke sender deg videre, klikk her.",
		INDEX_NOTICES : "Notater",
		INDEX_PLAYERS : "Spiller Statistikker",
		INDEX_ALLIES : "Allianse Statistikker",
		INDEX_REPORTS : "Spionasje Rapporter",
		INDEX_VERSION : "Siste versjon for nedlasting",
		INDEX_LATEST_VERSION : "Ingen nye versjoner tilgjenglig",
		INDEX_SHOUTBOX : "Meldingsboks",
		INDEX_NOENTRY : "Ingen meldinger ennå",
		INDEX_COMMENT : "Din melding",
		INDEX_INSERT : "Sett inn",
		INDEX_UMOD : "Spillere i ferie modus",
		INDEX_NO_MOONS : "Antall måner",
		INDEX_NO_EMPTY_SYSTEMS : "Antall tomme systemer",
		INDEX_NO_FULL_SYSTEMS : "Antall Fulle systemer",
		INDEX_NO_TARGETS : "Antall mulige mål",
		INDEX_USERINFO : "Antall brukere",
		INDEX_ONLINE : "Online nå",
		INDEX_TODAY : "Online i dag",
		INDEX_ALL : "Antall login",
		GENERAL_LOAD_FORM : "Åpne fra data",
		GENERAL_SAVE_FORM : "Lagre fra data",
		GENERAL_SAVE_AS_TEXT : "Lagre som",
		GENERAL_SAVE : "Lagre",
		INDEX_USERMANAGEMENT : "Activation Overview",
		INDEX_NEEDADMIN : "Accounts to unlock",
		INDEX_NEEDEMAIL : "Unvalidated Accounts",
		INDEX_TOOLBAR_INFO : "Galaxytool plugin information",
		INDEX_TOOLBAR_URL : "Galaxytool URL",
		INDEX_TOOLBAR_VERSION_REQUIRED : "Requires at least Galaxytool plugin version",
		INDEX_TOOLBAR_INSTALL_GUIDE : "Installation instructions for plugin",
		INDEX_TOOLBAR_TOKEN : "Logon key",
		INDEX_TOOLBAR_NEW_TOKEN : "Get new key",
		INDEX_PLAYERS_WITH_N_PLANETS : "Players with more than &1 planets",
		INDEX_GETTING_STARTED : "Getting started with the Galaxytool",
		INDEX_GETTING_STARTED1 : "Welcome to the Galaxytool!",
		INDEX_GETTING_STARTED2 : "The Galaxytool will help you to analyze what is going on in your OGame universe &1",
		INDEX_GETTING_STARTED3 : "Before you can actually analyze data you have to insert it first. For this you require a browser plugin like the &1 for Firefox.",
		INDEX_GETTING_STARTED4 : "After you installed the plugin, you navigate through your OGame pages as usual and you will see a small status window whenever something was sent to your Galaxytool.",
		INDEX_GETTING_STARTED5 : "Once the plugin inserted data into the Galaxytool, you can start to analyze where the players have their colonies, how many colonies they have, what reports exist or when they are active the most.",
		INDEX_GETTING_STARTED6 : "But it will also help you to analyze how you are progressing if you compare yourself against your competitors or by analyzing your combat reports to see how much you raided during the last days or weeks.",
		INDEX_GETTING_WIKIPAGE : "There are many more features within the Galaxytool.",
		INDEX_GETTING_WIKIPAGE2 : "Check them out at our wiki page.",
		INDEX_GETTING_BOARD : "For feedback or ideas you can use our board:",
		INDEX_GETTING_CHAT1 : "Or visit us at the chatroom:",
		INDEX_GETTING_CHAT2 : "We are not online 24/7 but spare a lot of our free time there, so be patient.",
		INDEX_CLOSE : "Close",
		INDEX_LOGIN : "Login",
		GENERAL_REQUIRED_FIELDS : "Please fill all required fields",
		INDEX_MESSAGES : "Messages",
		INDEX_EXAMPLE : "Example",
		INDEX_INVALID_DATA : "Invalid data",
		GENERAL_COLUMN_HIDE_TITLE : "Manage columns",
		GENERAL_COLUMN_HIDE_INFO : "Please select which columns you want to see in the table.",
		GENERAL_ENTRIES_DELETED : "&1 entries deleted",
		GENERAL_APPLY : "Apply",
		STARTPAGE_GALAXYTOOL_DESCR : "<em>Galaxytool</em> is a tool for the browser game OGame.",
		GENERAL_OVERWRITE : "Overwrite duplicate entry",
		GENERAL_OVERWRITE_QUESTION : "Overwrite?",
		INDEX_OWN_LOGINS : "Your logins",
		GENERAL_OPEN_IN_NEW_WINDOW : "Åpne lenke i nytt vindu",
		GENERAL_UNIT_OF_MEASURE_DAYS : "Days",
		PROGRAM_NAME : "OGame Galaxytool",
		SHORTNAME : "Galaxytool",
		BACK_INDEX : "Tilbake til hoved siden",
		UNIVERSE : "Univers",
		MENU_INFO_LINKS : "Informasjon",
		MENU_PAGE : "Oversikt",
		MENU_DB_SEARCH : "Søk i database",
		MENU_DB_NOTICES : "Søk i notater",
		MENU_DB_REPORTS : "Søk i rapporter",
		MENU_GALAXYVIEW : "se galakse",
		MENU_STATISTICS : "Statistikk",
		MENU_ALLYHISTORY : "Historisk Oversikt",
		MENU_FLEET_MOVEMENTS : "Fleet movements",
		MENU_COMBAT_REPORTS : "Combat reports",
		MENU_MESSAGES : "Ingame messages",
		MENU_OPTION_LINKS : "Valg",
		MENU_DB_REFRESH : "Sett inn i database",
		MENU_NOTICES : "Notater",
		MENU_DB_STATUS : "Status av Database",
		MENU_USEROPTIONS : "Bruker Admin",
		MENU_USEROPTIONS2 : "Bruker instillinger",
		MENU_USEROPTIONS3 : "Bruker Informasjon",
		MENU_ADMIN : "Administrasjon",
		MENU_LOGOUT : "Logout",
		MENU_STUFF : "Forskjellig",
		MENU_FORUM_THREAD : "Utvikler Forum",
		MENU_DOWNLOADPAGE : "Nedlastings side",
		MENU_LANGUAGE : "Språk",
		MENU_HELP : "Hjelp",
		MENU_TOOLOPTIONS : "Galaxytool Instillinger",
		PARSER_INFO1 : "Var lagt til i databasen",
		PARSER_ERROR1 : "Feil oppstod når de følgende kordinatene skulle lastes opp: ",
		PARSER_ERROR2 : "Fant ikke databasen!",
		PARSER_ERROR3 : "Fant ikke serveren til databasen!",
		PARSER_WRONG_UNIVERSE : "Feil univers -nåværende: \"&1\" forventet: \"&2\"",
		SHOW_TITLE : "OGame Galaxytool - Searchpage",
		SHOW_SEARCH : "Søk i database",
		SHOW_ALLYSYMBOL : "Allianse Navn",
		SHOW_PLAYERNAME : "Spiller Navn",
		SHOW_MOONS : "Kun planeter med måne",
		SHOW_NOTICES : "Kun planeter med notater",
		SHOW_COLONIES : "Kun planeter som kan koloniseres",
		SHOW_YES : "Ja",
		SHOW_NO : "Nei",
		SHOW_SEARCHRANGE : "Avstand",
		SHOW_SEARCH_IN : "Søk i galakse",
		SHOW_FROM_SYSTEM : "fra solsystem",
		SHOW_FROM_PLANET : "fra Planet Posisjon",
		SHOW_TO : "til",
		SHOW_DESCRIPTION : "You can use wildcards * for player or alliance names. So you can find all players with &quot;name&quot; in their name.<br />Only fill those fields you want to specify.",
		SHOW_SORT_BY : "Sorter Etter",
		SHOW_GALASYSTEM : "Galakse/System",
		SHOW_ALLYNAME : "Allianse Navn",
		SHOW_SEARCHBUTTON : "Søk",
		SHOW_ADDRESS : "Adresse",
		SHOW_ALLYSORT : "Allianse",
		SHOW_PLANET : "Planet Navn",
		SHOW_STATUS : "Status",
		SHOW_CURRENTNESS : "Sist Oppdatert",
		SHOW_PLAYER_STATUS : "Spiller Status",
		SHOW_PLAYER_STATUS1 : "alle",
		SHOW_PLAYER_STATUS2 : "mulige mål",
		SHOW_PLAYER_STATUS3 : "inaktive",
		SHOW_HITS : "Treff",
		SHOW_OF : "av",
		SHOW_ASC : "økende",
		SHOW_DESC : "minkende",
		SHOW_RESULTS : "treff pr. side",
		SHOW_MOON : "Måne",
		SHOW_UKMOONSIZE : "ukjent",
		SHOW_DF : "DF",
		SHOW_DF_LONG : "Skrapfelt",
		SHOW_METAL : "M",
		SHOW_METAL_LONG : "Metall",
		SHOW_CRYSTAL : "K",
		SHOW_CRYSTAL_LONG : "Krystall",
		SHOW_BOTH : "begge tilsammen",
		SHOW_AT_LEAST : "(minst)",
		SHOW_DATE : "Dato",
		SHOW_DATE_0 : "glem det",
		SHOW_DATE_1 : "eldre enn",
		SHOW_DATE_2 : "nyere enn",
		SHOW_RANK : "Rang",
		SHOW_FRANK : "Flåte rang",
		SHOW_MEMBERS : "Medlemmer",
		SHOW_NOTRANKED : "ingen data",
		SHOW_NOTICERES : "Notater",
		SHOW_REPORTS : "kun planeter med notater",
		SHOW_REPORTS_SHORT : "Rapporter",
		SHOW_NOTHING : "Ingen funnet",
		SHOW_ALLIANCE_STATUS : "Allianse status",
		SHOW_NO_STATUS : "ingen Status",
		SHOW_NAP : "NAP",
		SHOW_ALLIED : "Alliert",
		SHOW_WAR : "Krig",
		SHOW_BOYCOTT : "Boykott",
		SHOW_NEUTRAL : "Nøytral",
		SHOW_OWN : "Egen Allianse",
		SHOW_WING : "Wing",
		SHOW_EXT_OPTIONS1 : "Vis flere instillinger for rekkevidde, rank dato eller DF søk.",
		SHOW_EXT_OPTIONS2 : "Vis flere instillinger kolonier, måner, raporter, notater, spillerstatus og diplomatisk status.",
		SHOW_EXT_OPTIONS3 : "Vis flere instillinger for sortering av resultatene.",
		SHOW_EXTENDED : "advanced search",
		SHOW_MOON_SELECTION : "Planet with moon",
		SHOW_REPORT_SELECTION : "Planet with report",
		SHOW_FILTER_BY : "Exclude from the list",
		SHOW_FILTER_NONE : "ingen",
		SHOW_PLAYERS_WITHOUT_PROGRESS : "Show players without score changes within the last few days",
		STATUS_TITLE : "OGame Galaxytool - Statuspage",
		STATUS_DB_STATUS : "Status for Databasen",
		STATUS_COLOR : "Farge",
		STATUS_AGE1 : "Innlegg 1 dag gammel.",
		STATUS_AGE2 : "Innlegg 2 - 4 dager gammel.",
		STATUS_AGE3 : "Innlegg 4 - 7 dager gammel.",
		STATUS_AGE4 : "Innlegg 1 - 2 uker gammel.",
		STATUS_AGE5 : "Innlegg 2 - 4 uker gammel.",
		STATUS_AGE6 : "Innlegg eldre enn 1 måned!",
		STATUS_AGE7 : "ingen innlegg tilgjenglig.",
		STATUS_ON : "på",
		STYLES_COLOR1 : "Farge1",
		STYLES_COLOR2 : "Farge2",
		STYLES_COLOR3 : "Farge3",
		STYLES_COLOR4 : "Farge4",
		STYLES_COLOR5 : "Farge5",
		STYLES_COLOR6 : "Farge6",
		STYLES_COLOR7 : "Farge7",
		STATUS_DB_LEGEND : "Legend",
		STATUS_GALAXY : "Galaxy Overview",
		USER_TITLE : "Bruker administrasjon",
		USER_NAMES : "Bruker",
		USER_ERROR : "Feil",
		USER_NEWUSER : "Ny Bruker",
		USER_OPTIONS : "Valg",
		USER_USERNAME : "Brukernavn",
		USER_PASSWORD : "Passord",
		USER_PASSWORD_CONFIRM : "Bekreft Passord",
		USER_GALAXY : "Galaxe",
		USER_SEARCH : "Søk",
		USER_INSERT : "Sett Inn",
		USER_DELETE : "Slett",
		USER_DELETE_ENTRY : "Vil du slette bruker: ",
		USER_STATUS : "Se Status",
		USER_STYLES : "modifiser utseende",
		USER_SUBMIT : "Legg til",
		USER_RESET : "Nullstill",
		USER_YES : "Ja",
		USER_NO : "Nei",
		USER_STYLEPATH : "Path to styles.css",
		USER_PROBES : "Legg til Espionage Reports",
		USER_EMAIL : "Epost",
		USER_ERROR1 : "Feil Passord eller ugyldig epost.",
		USER_ERROR2 : "Epost Ugyldig.",
		USER_INGAME : "OGame Brukernavn",
		USER_ALLYTAG : "Allianse Navn",
		USER_ALLYHISTORY : "Historisk Oversikt",
		USER_DIPLOMATIC : "Forandre diplomatisk status",
		USER_STATSPAGE : "Antall innlegg på statistikk siden",
		USER_LINKS : "Linker",
		USER_LINKS2 : "Format:<br>text;url<br>text2;url2<br>text3;url3",
		USER_EXPORT_TITLE : "Eksporter Farger(BB Codes)",
		USER_BB_COORDINATES : "Koordinater",
		USER_BB_MOON : "Måne",
		USER_BB_DEBRIS : "Skrap felt",
		USER_BB_ALLY : "Allianse navn",
		USER_BB_ALLYDETAILS : "Allianse detaljer",
		USER_BB_PLAYERNAME : "Spiller navn",
		USER_BB_BANNED : "ban",
		USER_BB_VACATION : "ferie modus",
		USER_BB_NOOB : "nybegynner",
		USER_BB_INACTIVE : "Inaktiv",
		USER_BB_LONGINACTIVE : "Iang Inaktiv",
		USER_DELETION : "Delete",
		USER_FLEETINFO : "Fleet movements",
		USER_ACTIVITIES : "Player activities",
		USER_MAINTENANCE : "Galaxytool maintenance",
		USER_MANAGEMENT : "Bruker Admin",
		USER_DELETE_MY_COMBAT_REPORTS : "Delete my combat reports",
		USER_DELETE_MY_MESSAGES : "Delete my messages",
		USER_DELETE_MY_FLEETMOVES : "Delete my fleet movements",
		USER_DELETE_MY_COMBAT_REPORTS_LIMITED : "Delete my combat reports older than &1 days",
		USER_DELETE_MY_MESSAGES_LIMITED : "Delete my messages older than &1 days",
		USER_TABLE_ENTRIES : "Number of search results for each page",
		USER_EXISTS : "User already exists",
		USER_BB_OUTLAW : "Outlaw",
		USER_INVALID_URL : "URL &1 seems to be invalid - URL will be ignored",
		VIEW_TITLE : "OGame Galaxytool - Galaxyview",
		VIEW_NODATA : "Ingen data tilgjenglig.",
		VIEW_GALAXY : "Galakse",
		VIEW_SYSTEM : "Sol system",
		VIEW_POSITION : "Posisjon.",
		VIEW_PLANET : "Planet",
		VIEW_MOON : "Måne",
		VIEW_TF : "Deb",
		VIEW_PLAYER : "Spiller",
		VIEW_PLAYER_ADD : "(Rang / Status)",
		VIEW_ALLY : "Allianse",
		VIEW_ALLY_ADD : "(Rang / Medlem)",
		VIEW_METAL : "M",
		VIEW_CRYSTAL : "K",
		VIEW_COLONISED : "Ubebodde Planeter",
		VIEW_UKMOONSIZE : "ukjent",
		VIEW_BACK : "tilbake",
		VIEW_NOTICE : "Notater",
		VIEW_REPORTS : "Reporter",
		VIEW_MOONPHALANX : "Følgende Måner kan skanne galakse",
		VIEW_NOMOONS : "Ingen måner funnet",
		VIEW_IRAKS : "Følgende planeter kan bli truffet med interplanetarisk Missil",
		VIEW_NOIRAKS : "Ingen Interplanetarisk Missil Funnet",
		VIEW_MOON_DESTROY_CHANCE : "Mulighet for å ødelegge måne",
		VIEW_CHANCE_WITH_ONE : "Mulighet med 1 dødsstjerne",
		VIEW_CHANCE_WITH_N : "Mulighet med ",
		VIEW_DEATH_STARS : "dødsstjerne",
		VIEW_DS_DESTROY_CHANCE : "Mulighet for å miste dødsstjerne(s)",
		VIEW_TOP : "Toppen",
		VIEW_GO : "Go",
		VIEW_DIAMETER : "Diameter",
		PW_TITLE : "OGame Galaxytool - skifte passord",
		OLD_PASSWORD : "gammelt passord",
		NEW_PASSWORD : "nytt passord",
		CONFIRM_NEW_PASSWORD : "bekreft nytt passord",
		PW_MISMATCH : "Passords er ikke likt!",
		PW_ERROR : "Old passord er ikke korrekt!",
		UPDATE_DONE : "Oppdatering suksess.",
		TIMEZONE_OFFSET : "Tids-sone forsjeld fra server",
		DELETE_ACCOUNT : "Slett denne Galaxytool kontoen",
		DELETE_ACCOUNT_SAFETY_REQUEST : "Er du sikker på du vil slette denne Galaxytool kontoen?",
		CH_PASSWD_AUTHORIZATION : "Autoritet",
		CH_PASSWD_ADMIN : "Admin",
		TIMEZONE_OGAME_OFFSET : "Timezone offset to OGame server",
		CH_PASSWD_USER_LANGUAGE : "Change to this language after logon",
		CH_PASSWD_USER_LANGUAGE_NO_CHANGE : "No change",
		CH_PASSWD_EXPAND : "Expanded",
		CH_PASSWD_COLLAPSE : "Collapsed",
		CH_PASSWD_HIDDEN : "Hidden",
		CH_PASSWD_GETTING_STARTED : "Show Getting Started Info after logon",
		CH_PASSWD_PLUGIN : "Show Plugin Info after logon",
		NOTICE_TITLE : "OGame Galaxytool - Notater",
		NOTICE_HEADER : "editer notater",
		NOTICE_HEADER2 : "Editer egne notater",
		NOTICE_PUBLIC : "Tilgjenglig for andre ?",
		NOTICE_YES : "Ja",
		NOTICE_NO : "nei",
		NOTICE_TEXT : "Notat Tekst",
		NOTICE_SAVE : "Lagre",
		NOTICE_DELETED : "Innlegg slettet",
		NOTICE_SAVED : "Innlegg lagret.",
		NOTICE_RESULTS : "Alle resultat",
		NOTICE_USER : "Bruker",
		NOTICE_DATE : "Dato",
		NOTICE_EDIT : "Editer",
		NOTICE_DELETE : "slett",
		NOTICE_NEW : "Lag eget innlegg",
		NOTICE_NOTPUBLIC : "Notat ikke publisert.",
		NOTICE_ALL : "alle",
		NOTICE_NONE : "ingen",
		NOTICE_SEARCH : "Søk i notater",
		NOTICE_SEARCH_SHORT : "Søk",
		NOTICE_HITS : "Treff",
		NOTICE_SHOWRESULTS : "treff per side",
		NOTICE_OF : "av",
		NOTICE_NOTHING : "ingen innlegg funnet",
		NOTICE_CHARS : "Karakter",
		NOTICE_PLAYERNAME : "Spiller",
		NOTICE_SHOWALL : "Vis alle notater",
		REPORTS_TITLE : "OGame Galaxytool - Spionasje  Rapporter",
		REPORTS_RESOURCES : "Resursser",
		REPORTS_FLEET : "Flåte",
		REPORTS_DEFENCE : "Forsvar",
		REPORTS_BUILDINGS : "Byggninger",
		REPORTS_TECHNOLOGY : "Forskning",
		REPORTS_MOON : "Måne",
		REPORTS_SEARCH : "Søk i spionajse rapport",
		REPORTS_SEARCH_SHORT : "Søk",
		REPORTS_HITS : "Treff",
		REPORTS_NOTHING : "Ingen treff",
		REPORTS_ADDRESS : "Adresse",
		REPORTS_CURRENTNESS : "Tilgjenglighet",
		REPORTS_PLAYERNAME : "Spillernavn",
		REPORTS_ALLY : "Allianse",
		REPORTS_VIEW : "se Raporter",
		REPORTS_SEARCH_IN : "Søk i galakse",
		REPORTS_FROM_SYSTEM : "fra System",
		REPORTS_TO : "til",
		REPORTS_DELETE : "slett",
		REPORTS_DELETED : "innlegg slettet",
		REPORTS_RESULTS : "treff per side",
		REPORTS_OF : "av",
		REPORTS_DATE : "Dato",
		REPORTS_DATE_0 : "glem",
		REPORTS_DATE_1 : "eldre enn",
		REPORTS_DATE_2 : "nyere enn",
		REPORTS_NOTICES : "Notater",
		REPORTS_AT_LEAST_RESOURCES : "Resursser (minimum)",
		REPORTS_SEARCH_EXTENDED : "utvid søk",
		REPORTS_FLEET_RESIS : "Flåte- poeng",
		REPORTS_DEFENCE_RESIS : "Forsvar- poeng",
		REPORTS_ALL_RESIS : "sum poeng",
		REPORTS_TECHS : "Teknologi",
		REPORTS_UNKNOWN_ENTRIES : "ukjent",
		REPORTS_PARTLY_INSERTED : "delvis innlegg",
		REPORTS_FOR_ALL_RES : "alle resursser",
		REPORTS_FOR_TF : "for skrapfelt",
		REPORTS_KT : "Lite Lasteskip",
		REPORTS_GT : "Stort Lasteskip",
		REPORTS_SS : "Slagskip",
		REPORTS_REC : "Resirkulerer",
		REPORTS_RAIDABLE : "kun mål jeg kan ta",
		REPORTS_ALL_RESOURCES : "alle Resursser",
		REPORTS_STUFF : "Forskjellig",
		REPORTS_SPEEDSIM : "Simuler med Speedsim",
		REPORTS_DRAGOSIM : "Simuler med Dragosim",
		REPORTS_STATUS : "Status",
		REPORTS_ERROR : "En feil har oppstått",
		REPORTS_OWN_REPORTS : "kun mine rapporter",
		REPORTS_UPLOAD_BY : "Raport lastet opp av",
		REPORTS_DEPTH : "Raport dybde",
		REPORTS_FLEET_SCORE : "Flåte score",
		REPORTS_DEFENCE_SCORE : "Forsvar score",
		REPORTS_HOURS : "hours",
		REPORTS_MAX_RESULTS_HIT : "Your query returned more than &1 hits. Only the first &1 results are show. Please adjust your search request to get less results.",
		REPORTS_OSIMULATE : "Simulate with OSimulate",
		REPORTS_SHOW_ONLY : "Show only",
		REPORTS_SHOW_PLANETS : "Planets",
		REPORTS_SHOW_MOONS : "Moons",
		REPORTS_OWNER : "Reports owned by",
		STATS_TITLE : "OGame Galaxytool - Statistikk",
		STATS_TBLHEAD : "Statistikk",
		STATS_RANK : "Rang",
		STATS_PLAYERNAME : "Spiller Navn",
		STATS_ALLYNAME : "Allianse Navn",
		STATS_SCORE : "Poeng",
		STATS_FLEET : "Flåte",
		STATS_RESEARCH : "Forskning",
		STATS_MEMBERS : "Medlem",
		STATS_STATUS : "Status",
		STATS_NOTHING : "Ingen Status",
		STATS_NAP : "NAP",
		STATS_ALLIED : "Allierte",
		STATS_WAR : "Krig",
		STATS_BOYCOTT : "Boykott",
		STATS_NEUTRAL : "Nøytral",
		STATS_OWN : "Egen Allianse",
		STATS_WING : "Wing",
		STATS_UPDATE : "Innlegg fra",
		STATS_PLAYERSTATS : "Spiller status",
		STATS_ALLYSTATS : "Allianse Status",
		STATS_DELETE : "Vil du slette dette innlegg ?",
		STATS_CONFIRM_DELETE : "Vil du virkelig slette dette innlegg?",
		STATS_CHANGE_PLAYER_STATUS : "Spiler status",
		STATS_CHANGE_ALLIANCE_STATUS : "Allianse status",
		STATS_CHANGE_ALLIANCE_STATUS_HINT : "Alle medlemmer av denne alliansen vil få denne status. Tidligere status vil bli overskrevet. Du kan skifte status på spillere senere.",
		STATS_UNKNOWN : "Reset",
		STATS_DETAILS : "Detaljer for",
		STATS_PLAYERSTATUS : "Spiller Status",
		STATS_IGNORE_STATUS : "alle",
		STATS_ACTIVE : "active",
		STATS_INACTIVE : "Inaktiv",
		STATS_BANNED : "ban",
		STATS_VACATION : "ferie modus",
		STATS_NOOB : "nybegynner",
		STATS_YES : "Ja",
		STATS_NO : "Kun planeter med notater",
		STATS_SEARCH : "Søk",
		STATS_SHOW_GRAPH : "Show details for score distribution",
		STATS_LONG_INACTIVE : "Iang Inaktiv",
		STATS_STANDARD : "Standard Points",
		STATS_MILITARY : "Military Points",
		STATS_ECONOMY : "Economy",
		STATS_HONOUR : "Honour points",
		STATS_MILITARY_BUILD : "Military build",
		STATS_MILITARY_DESTROYED : "Military destroyed",
		STATS_MILITARY_LOST : "Military lost",
		REGISTER_REGISTRATE : "Registrer",
		REGISTER_LOGINNAME : "Login-Navn",
		REGISTER_PASSWORD : "Passord",
		REGISTER_PASSWORD_CONFIRM : "Bekreft Passord",
		REGISTER_EMAIL : "Epostl",
		REGISTER_INGAME : "OGame navn",
		REGISTER_ALLYTAG : "Allianse Navn",
		REGISTER_EMAILVERIFICATION : "Epost sjekk",
		REGISTER_EMAILTEXT : "Vennligst følg denne link for å registrere din galaxytool.",
		REGISTER_ERROR1 : "Login-navn allerede brukt already used.",
		REGISTER_ERROR2 : "Feil ved forsøk på å sende epost. Kontakt din admin.",
		REGISTER_ERROR3 : "Feil ved forsøk på å sende data til databsen!",
		REGISTER_INFO1 : "Din konto er opprettet.",
		REGISTER_INFO2 : "Følg denne link for å fullføre di registrering.",
		REGISTER_INFO3 : "Konto Registrert. Din admin må nå godkjenne din registrering.",
		REGISTER_BUTTON : "Tilbake til hovedsiden",
		REGISTER_NEW_SUBJECT : "En ny bruker har registrert konto",
		REGISTER_NEW_MAILTEXT : "En ny bruker er registrert.",
		REGISTER_BACK : "Tilbake til førstesiden",
		REGISTER_MISSING_FIELDS : "Fyll alle feltene som er krav",
		REGISTER_ERROR4 : "Email address is not valid.",
		REGISTER_ERROR5 : "Passwords don't match.",
		REGISTER_PWS : "Password strength",
		REGISTER_PWS0 : "very weak",
		REGISTER_PWS1 : "weak",
		REGISTER_PWS2 : "good",
		REGISTER_PWS3 : "strong",
		REGISTER_PWS4 : "very strong",
		REGISTER_EMAIL_USED : "Email Address is already used",
		LOSTPW_TITLE : "Glemt passord",
		LOSTPW_INFO2 : "Et nytt passord ble sendt til din epost.",
		LOSTPW_BUTTON1 : "Få nytt passord",
		LOSTPW_BUTTON2 : "Tilbake til hovedsiden",
		LOSTPW_LOGINNAME : "Brukernavn",
		LOSTPW_EMAIL : "Epost",
		LOSTPW_ERROR1 : "Feil ved forsøk på å sende data til databasen!",
		LOSTPW_ERROR2 : "Feil!",
		LOSTPW_ERROR3 : "Feil ved forsøk på å sende epost. Kontakt din admin.",
		LOSTPW_EMAIL_SUBJECT : "Ditt nye passord som du bestillte",
		LOSTPW_EMAIL_TEXT1 : "Her er din nye login til Galaxytool",
		LOSTPW_EMAIL_TEXT2 : "Brukernavn",
		LOSTPW_EMAIL_TEXT3 : "Passord",
		LOSTPW_INFO1 : "You will receive an email to verify your password reset request.",
		LOSTPW_CONFIRM_RESET_SUBJECT : "Lost password?",
		LOSTPW_CONFIRM_RESET_MESSAGE : "Hello,\n\nyou requested a password reset for the Galaxytool. To generate a new password, click the following link:",
		USERINFO_TITLE : "OGame Galaxytool - User information",
		USERINFO_NAMES : "Alle brukere av dette verktøy",
		USERINFO_DETAIL : "detaljert informasjon",
		USERINFO_ERROR1 : "Ingen bruker med denne ID!",
		USERINFO_USERNAME : "Brukernavn",
		USERINFO_INGAME : "Spillernavn",
		USERINFO_EMAIL : "Epost",
		USERINFO_ALLYTAG : "Allianse",
		USERINFO_STYLEPATH : "Skin",
		USERINFO_STATUS : "Status",
		USERINFO_ACTIVATE : "Aktiv spiller",
		USERINFO_LOGINS : "Antall login",
		USERINFO_LASTLOGIN : "Sist Login",
		USERINFO_DATA : "Informasjon om systemer",
		USERINFO_NODATA : "Denne bruker har ikke lagt til noen system!",
		USERINFO_GALAXY : "Galakse",
		USERINFO_SYSTEMS : "Antall systemer",
		USERINFO_IP : "IP adresse",
		USERINFO_LOGINTIME : "Login",
		USERINFO_NOLOGIN : "Spiller har aldri logget inn.",
		USERINFO_LAST_GALAXYUPDATE : "lagt til sist i galakse oversikt",
		USERINFO_LAST_PUBLIC_NOTICE : "Siste publiserte notat",
		USERINFO_LAST_PRIVATE_NOTICE : "Siste private notat",
		USERINFO_NUMBEROF_PUBLIC_NOTICE : "Antall publiserte notater",
		USERINFO_NUMBEROF_PRIVATE_NOTICE : "Antall private notater",
		USERINFO_ACTIVATED : "konto Aktivert",
		USERINFO_ACTIVATIONTEXT : "Admin har aktivert din konto.\n\nHa det gøy med Galaxytool!",
		USERINFO_LAST_SUBMIT : "Inserted last data",
		ALLYHISTORY_TITLE : "OGame Galaxytool - Allianse Historie",
		ALLYHISTORY_TBLHEAD : "Historisk Oversikt",
		ALLYHISTORY_PLAYERNAME : "Spiller navn",
		ALLYHISTORY_ALLYNAME : "Allianse",
		ALLYHISTORY_LASTMONTH : "Sist måned",
		ALLYHISTORY_ALL_DATA : "All tilgjenglig informasjon",
		ALLYHISTORY_SHOW : "vis statistikk",
		ALLYHISTORY_TIMESPAN : "Tidsperspektiv",
		ALLYHISTORY_PROGESS : "Fremskritt",
		ALLYHISTORY_SCORE : "Poeng",
		ALLYHISTORY_FSCORE : "Flåte poeng",
		ALLYHISTORY_RSCORE : "Forsknings  poeng",
		ALLYHISTORY_MEMBER : "Medlemmer",
		ALLYHISTORY_NOTHING : "ingen data funnet",
		ALLYHISTORY_DETAILS : "Detaljer",
		ALLYHISTORY_SHOW_ADDRESS : "koordinater",
		ALLYHISTORY_ESCORE : "Economy",
		ALLYHISTORY_MSCORE : "Military Points",
		DETAILEDINFO_PLAYERINFO_TITLE : "Spiller Informasjon",
		DETAILEDINFO_ALLYINFO_TITLE : "Allianse informasjon",
		DETAILEDINFO_PLAYERINFO_TBLHEAD : "Detaljert info om spiller",
		DETAILEDINFO_ALLYINFO_TBLHEAD : "Detaljert info om Allianse",
		DETAILEDINFO_NO_ALLIANCE : "ingen",
		DETAILEDINFO_SCORE : "Poeng Statistikk",
		DETAILEDINFO_FLEET : "Flåte Statistikk",
		DETAILEDINFO_RESEARCH : "Forsknings Statistikk",
		DETAILEDINFO_RANK : "Rang",
		DETAILEDINFO_POINTS : "Poeng",
		DETAILEDINFO_KNOWN_PLANETS : "Kjente planeter",
		DETAILEDINFO_MOONS : "Kjente måner",
		DETAILEDINFO_PHALANX_AREA : "Phalanx område",
		DETAILEDINFO_NO_PHALANX_AREA : "Ingen Phalanx funnet",
		DETAILEDINFO_NOTICES : "Notater",
		DETAILEDINFO_NO_NOTICES : "Ingen Notater funnet",
		DETAILEDINFO_PREVIOUS_ALLIANCES : "Tidligere Allianse",
		DETAILEDINFO_RESOURCES_PER_HOUR : "Resursser per time",
		DETAILEDINFO_RESOURCES_PER_DAY : "Resursser per dag per day",
		DETAILEDINFO_RESOURCES_PER_WEEK : "resursser per uke",
		DETAILEDINFO_RESOURCES_PER_MONTH : "Resursser per måned (30 dager)",
		DETAILEDINFO_METAL : "Metall",
		DETAILEDINFO_CRYSTAL : "Krystall",
		DETAILEDINFO_DEUTERIUM : "Deuterium",
		DETAILEDINFO_UNKNOWN : "ukjent",
		DETAILEDINFO_SCORE_DISTRIBUTION : "Poeng distribusjon",
		DETAILEDINFO_GENERAL : "Detaljer",
		DETAILEDINFO_MEMBERS : "Medlemmer",
		DETAILEDINFO_GRAPHS : "Grafikk",
		DETAILEDINFO_RESOURCES : "Resursser",
		DETAILEDINFO_FLEET_TAB : "Flåte",
		DETAILEDINFO_TECH : "Forskning",
		DETAILEDINFO_FLEET_DETAIL : "Sum / (spiller gjennomsnitt) av alle tilgjenglige detaljer",
		DETAILEDINFO_TECH_DETAIL : "gjennomsnitt av all tilgjenglig informasjon",
		DETAILEDINFO_PLANET_TAB : "Planets",
		DETAILEDINFO_MOON_TAB : "Moons",
		DETAILEDINFO_ACTIVITIES : "Activities",
		DETAILEDINFO_NODATA : "Ingen data tilgjenglig.",
		DETAILEDINFO_ACTIVITY_DESCRIPTION : "Show activities of &1 collected from:",
		DETAILEDINFO_GALAXYVIEWS : "Galaxy views",
		DETAILEDINFO_SCANS : "Espionage actions",
		DETAILEDINFO_MESSAGES : "Player messages",
		DETAILEDINFO_COMBATS : "Combat reports",
		DETAILEDINFO_ALLYPAGE : "Alliance overview",
		DETAILEDINFO_MANUAL : "Manual insertions",
		DETAILEDINFO_START : "Beginning",
		DETAILEDINFO_TO : "to",
		DETAILEDINFO_TODAY : "Today",
		DETAILEDINFO_DATA_RESTRICTION : "restricted to:",
		DETAILEDINFO_WEEKDAY_WEEKEND : "Weekend",
		DETAILEDINFO_WEEKDAY_WORKINGDAY : "Weekday",
		DETAILEDINFO_WEEKDAY_MONDAY : "Monday",
		DETAILEDINFO_WEEKDAY_TUESDAY : "Tuesday",
		DETAILEDINFO_WEEKDAY_WEDNESDAY : "Wednesday",
		DETAILEDINFO_WEEKDAY_THURSDAY : "Thursday",
		DETAILEDINFO_WEEKDAY_FRIDAY : "Friday",
		DETAILEDINFO_WEEKDAY_SATURDAY : "Saturday",
		DETAILEDINFO_WEEKDAY_SUNDAY : "Sunday",
		DETAILEDINFO_WEEKDAY_SHORTLENGTH : 3,
		DETAILEDINFO_PLAYER_CURRENTLY_ACTIVE : "The player is currently active",
		DETAILEDINFO_PLAYER_MESSAGES : "available player messages",
		DETAILEDINFO_SHOW : "show",
		DETAILEDINFO_NONE : "none available",
		DETAILEDINFO_ENTER_MANUALLY : "Enter activities for this player",
		DETAILEDINFO_PLAYER_SEEN_ON : "Player was online on",
		DETAILEDINFO_INSERT : "Insert",
		DETAILEDINFO_OGAME_SERVERTIMES : "Please note: All dates and times refer to OGame server times !",
		DETAILEDINFO_DAY_VIEW : "24 hours view",
		DETAILEDINFO_WEEK_VIEW : "weekly view",
		DETAILEDINFO_HOME_PLANET : "Homeworld",
		DETAILEDINFO_PLANETNAME : "Name",
		DETAILEDINFO_DEFENCE_SCORE : "Defence score",
		DETAILEDINFO_DEFENCE_SCORE_TOOLTIP : "Defence score = Fleet - Score + Research + Economy.<br/>All those statistics must be up to date to have a meaningful result!",
		DETAILEDINFO_SCORE_PER_SHIP : "Scores per ship",
		DETAILEDINFO_SHIPS : "Number of ships",
		DETAILEDINFO_DATE_IN_FUTURE : "Do not maintain times which are not in the past.",
		ADMIN_TITLE : "Administrasjon av Galaxytool",
		ADMIN_DISCLAMER : "Advarsel: Bruk av disse script er på egen risiko. De fleste av dem sletter data.",
		ADMIN_INCONSISTENCIES : "Uregelmentær data i databasen",
		ADMIN_PLANETS : "Plantetr ved posisjon 0 or eller mer enn 15",
		ADMIN_GALAXIES : "Slett galakser større enn &1 ",
		ADMIN_PLAYERS : "Slett spillere uten OGame spillerid - fører til duplikate spiller kontoer",
		ADMIN_REPORTS : "Slett rapporter når det ikke eksisterer planeter lenger",
		ADMIN_MISC : "Diverse",
		ADMIN_RESET : "Null still Galaxytool (Kun bruker og ip tabeller som ikke blir slettet)",
		ADMIN_OLD_PLAYERS : "Slett spiller rapporter eldre enn &1 dag",
		ADMIN_OLD_REPORTS : "Slett rapporter eldre enn &1 dag",
		ADMIN_LOADING : "Ikke steng dette vindu menst side laster.",
		ADMIN_STATUS : "Status på din forespørsel",
		ADMIN_SELECTION : "Minimum et valg må bli valgt",
		ADMIN_SAFETY : "Er du sikker på at du vil kjøre dette scriptet(s) ?",
		ADMIN_DONE : "ferdig",
		ADMIN_NOTBD : "ingenting må gjøres",
		ADMIN_OLD_GALAXIES : "Fjerner galaxy views som er eldre enn &1 dag",
		ADMIN_UNUSED_PLAYERS : "Fjerner spillere som ikke er i galaxy view",
		ADMIN_OLD_ACTIVITIES : "Remove player activities older than &1 days",
		ADMIN_OLD_COMBATS : "Remove combat reports older than &1 days",
		ADMIN_OLD_INGAME_MSG : "Remove ingame messages older than &1 days",
		ADMIN_OGAME_API : "Load public data from OGame into the Galaxytool",
		ADMIN_OGAME_ALL_DATA : "All tilgjenglig informasjon",
		ADMIN_OGAME_GALAXY_DATA : "se galakse",
		ADMIN_OGAME_STATISTICS_DATA : "Statistikk",
		ERRORPAGE_PAGEFORWARD : "Trykk here vis browseren ikke støtter videre sending av siden",
		ERRORPAGE_PERMISSION_DENIED : "Du har ikke tilatelse til å åpne denne siden, trykk for å gå tilbake.",
		FLEETS_TITLE : "OGame Galaxytool - Fleet movements",
		FLEETS_ACTUAL_FLEETS : "Current fleet movements",
		FLEETS_YES : "Ja",
		FLEETS_NO : "Kun planeter med notater",
		FLEETS_DETAILS : "Details",
		FLEETS_MISSION_EXPEDITION : "Expedition",
		FLEETS_MISSION_COLONIZATION : "Colonize",
		FLEETS_MISSION_RECYCLE : "Harvest",
		FLEETS_MISSION_TRANSPORT : "Transport",
		FLEETS_MISSION_DEPLOYMENT : "Deploy",
		FLEETS_MISSION_ESPIONAGE : "Espionage",
		FLEETS_MISSION_ACS_DEFEND : "ACS Defend",
		FLEETS_MISSION_ATTACK : "Attack",
		FLEETS_MISSION_ACS_ATTACK : "ACS Attack",
		FLEETS_MISSION_MOON_DESTRUCTION : "Moon Destruction",
		FLEETS_MISSION_MISSILE_ATTACK : "Missile Attack",
		FLEETS_NO_DATA : "No applicable data found",
		FLEETS_FLEET : "Fleet",
		FLEETS_ALL_FLEETS : "Show all fleet movements",
		COMBAT_REPORT_OUDATED_GALAXYVIEW : "Your galaxy data is outdated. Please visit combat origin and target coordinates first!",
		MESSAGES_TITLE : "OGame Galaxytool - OGame Messages",
		MESSAGES_PLAYERNAME : "Playername",
		MESSAGES_SUBJECT : "Subject",
		MESSAGES_DATE : "Date",
		MESSAGES_FILTER : "Filter",
		MESSAGES_DELETE : "Delete message",
		MESSAGES_PUBLISH_DETAIL : "Publish message by adding the message content to notice text of that player.",
		MESSAGES_PUBLISH_HEADER : "&sender sent a message to &recipient on &date:\n\n &message",
		MESSAGES_PLAYER_FILTER : "Messages for player:",
		MESSAGES_CONTENT : "Content",
		COMBATS_TITLE : "OGame Galaxytool - Combat reports",
		COMBATS_ATTACKER : "Attacker",
		COMBATS_DEFENDER : "Defender",
		COMBATS_DATE : "Date",
		COMBATS_OWNER : "Owner",
		COMBATS_WINNER : "Winner",
		COMBATS_COMBATREPORT : "Combat Report",
		COMBATS_COMBAT_AT : "Combat at",
		COMBATS_LOST_UNITS : "Lost units",
		COMBATS_LOOT : "Loot",
		COMBATS_DEBRIS : "Debris",
		COMBATS_AND : "and",
		COMBATS_PUBLISH : "Make this report public",
		COMBATS_UNPUBLISH : "Unshare this report (makes it private again)",
		COMBATS_DELETE : "Delete report",
		COMBATS_CHECK_ALL : "Check All",
		COMBATS_UNCHECK_ALL : "Uncheck All",
		COMBATS_WITH_SELECTED : "With selected",
		COMBATS_PUBLIC_REPORTS : "Public reports",
		COMBATS_YES : "Ja",
		COMBATS_NO : "Kun planeter med notater",
		COMBATS_SEARCH_OPTIONS : "Search options",
		COMBATS_SEARCH : "Go",
		COMBATS_RESET : "Reset",
		COMBATS_COORDINATES : "Koordinater",
		COMBATS_INVALID_GALAXY_ENTERED : "Invalid Galaxy entered",
		COMBATS_INVALID_SYSTEM_ENTERED : "Invalid System entered",
		COMBATS_INVALID_PLANET_ENTERED : "Invalid Planet entered",
		COMBATS_GALAXY_FROM_TO : "Galaxy",
		COMBATS_SYSTEM_FROM_TO : "System",
		COMBATS_PLANET_FROM_TO : "Planet",
		COMBATS_APPLY : "Apply",
		COMBATS_COMBAT_SUMMARY : "Combat report summary",
		COMBATS_DOWNLOAD_CSV : "Download as CSV file",
		REPORT_ARCHIVE_TITLE : "Report archive",
		REPORT_ARCHIVE_COORDINATES : "Coordinates",
		REPORT_ARCHIVE_SCANTIME : "Scan time",
		REPORT_ARCHIVE_DELETE : "Delete these entries",
		REPORT_ARCHIVE_CONFIRM_DELETE : "Do you really want to delete these entries?",
		REPORT_ARCHIVE_GALAXY : "Galaxy",
		REPORT_ARCHIVE_SYSTEM : "System",
		REPORT_ARCHIVE_PLANET : "Planet",
		REPORT_ARCHIVE_MOON : "Moon",
		REPORT_ARCHIVE_DETAILS : "Details",
		REPORT_ARCHIVE_RESOURCES : "Resursser per time",
		REPORT_ARCHIVE_HEADER_RESOURCES : "Resursser",
		REPORT_ARCHIVE_DETAILS_FOR : "Report archive for &1 [&2] (&3)",
		REPORT_ARCHIVE_FLEET_CARGO : "Fleet cargo capacity",
		REPORT_ARCHIVE_IRAK_RANGE : "Interplanetary Missiles range",
		REPORT_ARCHIVE_CHART_TYPE : "Chart type",
		INSTALL_TITLE : "Galaxytool installation for version",
		INSTALL_PROGRESS : "Overall progress",
		INSTALL_STEP : "Step",
		INSTALL_CONTINUE : "Continue",
		INSTALL_VALIDATE : "Validate",
		INSTALL_STEP1 : "Welcome",
		INSTALL_STEP2 : "Writeable check",
		INSTALL_STEP3 : "Database settings",
		INSTALL_STEP4 : "OGame settings",
		INSTALL_STEP5 : "Galaxytool settings",
		INSTALL_STEP6 : "Admin password",
		INSTALL_STEP7 : "Install Galaxytool",
		INSTALL_STEP8 : "Finalize install",
		INSTALL_FILE_DELETE_CHECK : "Please delete install.php and update.php from your webserver.",
		INSTALL_STEP1_PHP_FAILED : "Your PHP version &1 is not working with this Galaxytool version",
		INSTALL_STEP1_FOPEN_FAILED : "Your PHP version does not allow to open webpages with FOPEN() command. This is required to consume the OGame API.",
		INSTALL_STEP1_WELCOME : "Welcome to the installation wizard of the Galaxytool. You will be guided through the installation of the Galaxytool.",
		INSTALL_STEP2_DESCRIPTION : "Make sure your config.php and attributes.php files have write permissions enabled.",
		INSTALL_STEP2_DESCRIPTION2 : "If you don't know, how to achieve this, please take a look here: &1",
		INSTALL_STEP2_FILE_NOT_WRITEABLE : "File is not writeable",
		INSTALL_STEP3_SERVER : "Database server",
		INSTALL_STEP3_USERNAME : "Brukernavn",
		INSTALL_STEP3_PASSWORD : "Passord",
		INSTALL_STEP3_DBNAME : "Database name",
		INSTALL_STEP3_PREFIX : "Tablename prefix",
		INSTALL_STEP3_ENTER_PREFIX : "E.g. mytool_",
		INSTALL_STEP3_ENTER_SERVER : "Enter the server address. Contact your system admin if necessary. Usually the correct value is localhost.",
		INSTALL_STEP3_ENTER_USERNAME : "Enter the username for database access",
		INSTALL_STEP3_ENTER_PASSWORD : "Enter the password for database access",
		INSTALL_STEP3_ENTER_DBNAME : "Enter the database name which shall be used for installation (must exist)",
		INSTALL_STEP3_CONNECT_FAILED : "Could not establish connection to database server",
		INSTALL_STEP3_DB_FAILED : "Database &1 not found",
		INSTALL_STEP3_MYSQL_VERSION_FAILED : "MySQL version &1 is not working with this Galaxytool version",
		INSTALL_STEP4_URL : "OGame URL",
		OGAME_URL_DETAILS : "Please enter any URL you see when you are logged on to OGame. Based on that URL the tool will derive the OGame API address which can be used to fill data into the Galaxytool without the Galaxytoolbar. This API was introduced with OGame version 4.1.",
		INSTALL_STEP4_UNIVERSE : "OGame Universe",
		INSTALL_STEP4_DEF_TO_DEBRIS : "Defense to debris",
		INSTALL_STEP4_DEBRIS_RATE : "Debris rate",
		INSTALL_STEP4_SPEED_RATE : "Speed rate",
		INSTALL_STEP4_ENTER_UNIVERSE : "Enter your OGame universe name or number (case sensitive).",
		INSTALL_STEP4_UNIVERSE_MISSING : "You must define your universe",
		INSTALL_STEP4_ENTER_URL : "Enter your OGame universe address",
		INSTALL_STEP4_URL_MISSING : "You must define your OGame address",
		INSTALL_STEP4_URL_CHECK_FAILED : "Could not find OGame API at &1",
		INSTALL_STEP4_GETSETTINGS : "Fetch settings",
		INSTALL_STEP5_TOOLNAME : "Galaxytool name",
		INSTALL_STEP5_ENTER_TOOLNAME : "This is the name which will be shown at logon page to identify your Galaxytool",
		INSTALL_STEP5_LANGUAGE : "Default language",
		INSTALL_STEP5_EMAIL_TO : "Email To",
		INSTALL_STEP5_ENTER_EMAIL_TO : "Enter the email address where you would like to receive notifications about registrations",
		INSTALL_STEP5_EMAIL_FROM : "Email From",
		INSTALL_STEP5_ENTER_EMAIL_FROM : "This email address is shown as REPLY for all mails sent from the Galaxytool",
		INSTALL_STEP5_USE_PHPMAILER : "Use PHPMailer",
		INSTALL_STEP5_MAXSHOUTS : "Maximum number of shoutbox entries",
		INSTALL_STEP5_ENTER_USE_PHPMAILER : "Use PHPMailer if your server does not support sending emails by default",
		INSTALL_PHPMAILER_HOST : "SMPT Host",
		INSTALL_PHPMAILER_HOST_EXAMPLE : "e.g. smtp.provider.com",
		INSTALL_PHPMAILER_USER : "SMPT Username",
		INSTALL_PHPMAILER_USER_EXAMPLE : "e.g. user@provider.dcom",
		INSTALL_PHPMAILER_PASS : "SMPT password",
		INSTALL_PHPMAILER_SECURE : "Authentification method (e.g. ssl)",
		INSTALL_PHPMAILER_PORT : "SMTP Port",
		INSTALL_STEP6_INTRO : "Please define a password for the <strong>admin</strong> account which you have to use for your first logon to the Galaxytool after the installation.",
		INSTALL_STEP7_CONFIG : "Configuration file created",
		INSTALL_STEP7_CONFIG_FAILED : "Configuration file not created",
		INSTALL_STEP7_ATTRIBUTES : "Attributes file created",
		INSTALL_STEP7_ATTRIBUTES_FAILED : "Attributes file not created",
		INSTALL_STEP7_CREATED_TABLES : "Database tables created",
		INSTALL_STEP8_INTRO : "You have successfully installed the Galaxytool!",
		INSTALL_STEP8_LOAD_DATA : "Downloading OGame data ...",
		INSTALL_STEP8_LOAD_DATA_FINISHED : "Download of OGame data finished",
		INSTALL_STEP8_DELETE_FILE : "You should now delete the installation files install.php and update.php from your webserver.",
		INSTALL_STEP8_LOGON : "Please logon with the <strong>admin</strong> user and the password you defined earlier.",
		UPDATE_START : "Starting update to version &1",
		UPDATE_STEP_DONE : "Done",
		UPDATE_TITLE : "Galaxytool update for version",
		UPDATE_STEP1_WELCOME : "Welcome to the update wizard of the Galaxytool. You will be guided through the update of the Galaxytool.",
		UPDATE_STEP1_BACKUP_FILES : "As a first step, make a backup of your <strong>config</strong> folder! You will have to replace the configuration content in case of errors.",
		UPDATE_STEP1_BACKUP_DB : "Then make a <a href=\"http://www.ehow.com/how_2036600_create-database-php.html\">backup</a> of your database.",
		UPDATE_STEP1_PROCEED : "Once the backups have been done, you can proceed with your update.",
		UPDATE_STEP1 : "Welcome",
		UPDATE_STEP2 : "Galaxytool settings",
		UPDATE_STEP2_OLD_VERSION : "Previous Galaxytool version",
		UPDATE_STEP3 : "Update Galaxytool",
		UPDATE_STEP3_UPDATE_RUNNING : "Update running, please wait...",
		UPDATE_STEP4 : "Finalize Update",
		UPDATE_STEP4_INTRO : "You have successfully updated the Galaxytool!",
		UPDATE_STEP4_UPDATE_DONE : "Update steps performed.",
		UPDATE_FAILED : "Update failed.",
		GALAXYTOOL_DUMMY_TEXT : "dummy"
	})
);