define(
	({
		REPORT_WHEN : "in",
		RESOURCES_ON : "Resurse la",
		PLAYER_BANNED : "b",
		PLAYER_VACATION_MODE : "v",
		PLAYER_NOOB : "n",
		PLAYER_INACTIVE : "i",
		PLAYER_LONG_INACTIVE : "I",
		PLAYER_OUTLAW : "o",
		L_USERNAME : "Utilizator",
		L_PASSWORD : "Parola",
		L_LOGINFAILURE : "Username sau parola sunt gresitesau contul tau inca nu este activat.",
		L_TOKENFAILURE : "Cheia ta de logare e gresita sau contul nu este inca activat.",
		L_LOGINTEXT : "Te rog conecteaza-te.",
		L_LANGUAGE : "Limbi disponibile:",
		L_TIMEOUT : "Sesiunea ta a expirat!",
		L_REGISTER : "Inregistrare",
		L_PWLOST : "Parola pierduta",
		INDEX_TITLE : "OGame Galaxietool - General",
		INDEX_INFO : "Informatii",
		INDEX_ENTRIES : "Numarul de sisteme",
		INDEX_ENTRIES_LASTWEEK : "Sisteme noi introduse in ultima saptamana",
		INDEX_ENTRIES_TO_OLD : "Sisteme mai vechi de o luna",
		INDEX_REGISTERED_USERS : "Useri inregistrati",
		INDEX_PAGEFORWARD : "Daca browser-ul tau nu suporta redirectarea te rog apasa aici.",
		INDEX_NOTICES : "Notite",
		INDEX_PLAYERS : "Statisticile jucatorilor",
		INDEX_ALLIES : "Statisticile aliatilor",
		INDEX_REPORTS : "Rapoarte de spionare",
		INDEX_VERSION : "Ultima versiune pentru descarcare",
		INDEX_LATEST_VERSION : "Nici o veriune noua disponibila",
		INDEX_SHOUTBOX : "Casuta cu mesaje",
		INDEX_NOENTRY : "Nici un mesaj , inca",
		INDEX_COMMENT : "Mesajul tau ",
		INDEX_INSERT : "Introduce",
		INDEX_UMOD : "Jucator in modul vacanta",
		INDEX_NO_MOONS : "Numarul de luni",
		INDEX_NO_EMPTY_SYSTEMS : "Numarul de sisteme goale , virgine",
		INDEX_NO_FULL_SYSTEMS : "Numarul de sisteme pline",
		INDEX_NO_TARGETS : "Numarul de posibile tinte",
		INDEX_USERINFO : "Numarul de utilizatori",
		INDEX_ONLINE : "Acum conectati",
		INDEX_TODAY : "Azi conectati",
		INDEX_ALL : "Numarul total de conectari",
		GENERAL_LOAD_FORM : "Incarcare date",
		GENERAL_SAVE_FORM : "Salvare date",
		GENERAL_SAVE_AS_TEXT : "Salveaza ca",
		GENERAL_SAVE : "Salveaza",
		INDEX_USERMANAGEMENT : "Vederea Activarii",
		INDEX_NEEDADMIN : "Conturi de deblocat",
		INDEX_NEEDEMAIL : "Conturi Nevalidate",
		INDEX_TOOLBAR_INFO : "Informatiile pluginului Galaxytool",
		INDEX_TOOLBAR_URL : "Galaxytool URL",
		INDEX_TOOLBAR_VERSION_REQUIRED : "Necesita cel putin versiunea pluginului Galaxytool",
		INDEX_TOOLBAR_INSTALL_GUIDE : "Instructiuni de instalare pentru plugin",
		INDEX_TOOLBAR_TOKEN : "Cheie de Logare",
		INDEX_TOOLBAR_NEW_TOKEN : "Obtine noua cheie",
		INDEX_PLAYERS_WITH_N_PLANETS : "Jucatori cu mai mult de &1 planeta",
		INDEX_GETTING_STARTED : "Notiuni de baza despre Galaxytool",
		INDEX_GETTING_STARTED1 : "Bun venit la Galaxytool!",
		INDEX_GETTING_STARTED2 : "Galaxytool te va ajuta sa analizezi ce se intampla in universul tau &1 din OGame",
		INDEX_GETTING_STARTED3 : "Inainte sa analizezi cu adevarat informatiile trebuie sa le inserezi mai intai. Pentru asta ai nevoie de un plugin pentru browser ca &1 pentru Firefox.",
		INDEX_GETTING_STARTED4 : "Dupa ce ai instalat pluginul, navighezi prin paginile tale de OGame ca de obicei si vei vedea o mica fereastra de status de fiecare data cand ceva a fost trimis spre Galaxytool.",
		INDEX_GETTING_STARTED5 : "Imediat ce informatiile au fost inserate in Galaxytool, poti incepe sa analizezi unde jucatorii isi au coloniile, cate colonii au, ce rapoarte exista sau cand is cel mai activi.",
		INDEX_GETTING_STARTED6 : "Dar te ajuta deasemenea sa analizezi prograsul propriu si sa te compari impotriva altor jucatori sau prin analizarea rapoartelor de lupta sa vezi cate raiduri ai facut in ultimele zile sau saptamani",
		INDEX_GETTING_WIKIPAGE : "Sunt multe alte caracteristici in Galaxytool.",
		INDEX_GETTING_WIKIPAGE2 : "Verifica-le pe pagina noastra wiki.",
		INDEX_GETTING_BOARD : "Pentru feedback sau idei puteti folosi board-ul nostru:",
		INDEX_GETTING_CHAT1 : "Sau vizitatine pe chatroom-ul nostru:",
		INDEX_GETTING_CHAT2 : "Nu suntem online 24/7 dar petrecem mult timp liber acolo, asa ca ai rabdare.",
		INDEX_CLOSE : "Inchide",
		INDEX_LOGIN : "Conectare",
		GENERAL_REQUIRED_FIELDS : "Completati toate campurile necesare",
		INDEX_MESSAGES : "Mesaje",
		INDEX_EXAMPLE : "Exemplu",
		INDEX_INVALID_DATA : "Date invalide",
		GENERAL_COLUMN_HIDE_TITLE : "Administreaza coloanele",
		GENERAL_COLUMN_HIDE_INFO : "Selectati ce coloane doriti sa vedeti in tabel.",
		GENERAL_ENTRIES_DELETED : "&1 intrari sterse",
		GENERAL_APPLY : "Aplica",
		STARTPAGE_GALAXYTOOL_DESCR : "<em>Galaxytool</em> este o unealta pentru jocul in browser OGame.",
		GENERAL_OVERWRITE : "Suprascrie intrarea duplicata",
		GENERAL_OVERWRITE_QUESTION : "Suprascrie?",
		INDEX_OWN_LOGINS : "Conectarile dumneavoastra",
		GENERAL_OPEN_IN_NEW_WINDOW : "Deschide legătura în fereastră nouă",
		GENERAL_UNIT_OF_MEASURE_DAYS : "Days",
		PROGRAM_NAME : "OGame Galaxytool",
		SHORTNAME : "Galaxytool",
		BACK_INDEX : "Inapoi la pagina principala",
		UNIVERSE : "HUHA Universul",
		MENU_INFO_LINKS : "Informatii",
		MENU_PAGE : "Vedere larga",
		MENU_DB_SEARCH : "Cautare in baza de date",
		MENU_DB_NOTICES : "Cautare in notite",
		MENU_DB_REPORTS : "Cautare in rapoarte de spionaj",
		MENU_GALAXYVIEW : "Vezi galaxia",
		MENU_STATISTICS : "Statistici",
		MENU_ALLYHISTORY : "Istoricul vederii largi",
		MENU_FLEET_MOVEMENTS : "Miscarile flotelor",
		MENU_COMBAT_REPORTS : "Rapoarte de lupta",
		MENU_MESSAGES : "Mesaje din joc",
		MENU_OPTION_LINKS : "Optiuni",
		MENU_DB_REFRESH : "Introdu in baza de date",
		MENU_NOTICES : "Notite",
		MENU_DB_STATUS : "Statusul bazei de date",
		MENU_USEROPTIONS : "Control utilizatori",
		MENU_USEROPTIONS2 : "Optiunile utilizatorului",
		MENU_USEROPTIONS3 : "Informatii despre utilizatori",
		MENU_ADMIN : "Administratia",
		MENU_LOGOUT : "Logout",
		MENU_STUFF : "Ajutator",
		MENU_FORUM_THREAD : "Pagina producatorului",
		MENU_DOWNLOADPAGE : "Pagina de download",
		MENU_LANGUAGE : "Limba",
		MENU_HELP : "Ajutor",
		MENU_TOOLOPTIONS : "Optiunile Galaxytool",
		PARSER_INFO1 : " a fost introdus in baza de date",
		PARSER_ERROR1 : "A aparut o eroare incercand sa introduc datele pentru coordonatele :",
		PARSER_ERROR2 : "Nu am gasit baza de date!",
		PARSER_ERROR3 : "Nu am gasit serverul cu baza de date!",
		PARSER_WRONG_UNIVERSE : "Univers gresit - actual: \"&1\"  neasteptat: \"&2\"",
		SHOW_TITLE : "OGame Galaxytool - Pagina de cautare",
		SHOW_SEARCH : "Cauta in baza de date",
		SHOW_ALLYSYMBOL : "Numele Aliantelor",
		SHOW_PLAYERNAME : "Numele Jucatorului",
		SHOW_MOONS : "Doar planete cu luni",
		SHOW_NOTICES : "Doar planete cu mesaje",
		SHOW_COLONIES : "Doar planete pentru colonizare",
		SHOW_YES : "DA",
		SHOW_NO : "NU",
		SHOW_SEARCHRANGE : "Intervalul",
		SHOW_SEARCH_IN : "Cauta in galaxia",
		SHOW_FROM_SYSTEM : "de la sistemul solar",
		SHOW_FROM_PLANET : "de la pozitia planetei",
		SHOW_TO : "la",
		SHOW_DESCRIPTION : "Poti folosi wildcards * pentru jucator sau numele aliatilor. Ca sa poti gasi toti jucatorii cu \"name\" in numele lor.<br />Scrie in campurile pe care vrei sa le specifici.",
		SHOW_SORT_BY : "Aranjare dupa",
		SHOW_GALASYSTEM : "Galaxie/Sistem",
		SHOW_ALLYNAME : "Numele aliantei",
		SHOW_SEARCHBUTTON : "Cauta",
		SHOW_ADDRESS : "Adresa",
		SHOW_ALLYSORT : "Alianta",
		SHOW_PLANET : "Numele planetei",
		SHOW_STATUS : "Status",
		SHOW_CURRENTNESS : "Ultima actualizare",
		SHOW_PLAYER_STATUS : "Statutul jucatorului",
		SHOW_PLAYER_STATUS1 : "tot",
		SHOW_PLAYER_STATUS2 : "posibile tinte",
		SHOW_PLAYER_STATUS3 : "inactiv",
		SHOW_HITS : "Lovituri",
		SHOW_OF : "de",
		SHOW_ASC : "crescator",
		SHOW_DESC : "descrescator",
		SHOW_RESULTS : "afisari pe pagina",
		SHOW_MOON : "Luna",
		SHOW_UKMOONSIZE : "necunoscut",
		SHOW_DF : "CR",
		SHOW_DF_LONG : "Camp de ramasite",
		SHOW_METAL : "M",
		SHOW_METAL_LONG : "Metal",
		SHOW_CRYSTAL : "C",
		SHOW_CRYSTAL_LONG : "Cristal",
		SHOW_BOTH : "amandoua impreuna",
		SHOW_AT_LEAST : "(cel putin)",
		SHOW_DATE : "Data",
		SHOW_DATE_0 : "nu conteaza",
		SHOW_DATE_1 : "mai vechi de",
		SHOW_DATE_2 : "mai nou de",
		SHOW_RANK : "Locul dupa puncte",
		SHOW_FRANK : "Locul flotei",
		SHOW_MEMBERS : "Membri",
		SHOW_NOTRANKED : "Nu este in top 1500.",
		SHOW_NOTICERES : "Mesaje",
		SHOW_REPORTS : "Doar planete cu rapoarte de spionare",
		SHOW_REPORTS_SHORT : "Rapoarte",
		SHOW_NOTHING : "Nu sa gasit nimica",
		SHOW_ALLIANCE_STATUS : "Statusul Aliantei",
		SHOW_NO_STATUS : "nici un status",
		SHOW_NAP : "NAP",
		SHOW_ALLIED : "Aliati",
		SHOW_WAR : "Razboi",
		SHOW_BOYCOTT : "Boicot",
		SHOW_NEUTRAL : "Neutrii",
		SHOW_OWN : "Alianta proprie",
		SHOW_WING : "Prieten",
		SHOW_EXT_OPTIONS1 : "Arata mai multe optiuni de cautari pentru raza , ranc , data sau campuri de ramasite.",
		SHOW_EXT_OPTIONS2 : "Arata mai multe optiuni de cautari pentru colonii , luni , rapoarte de spionare , mesaje , statutul jucatorilor sau relatiile diplomatice.",
		SHOW_EXT_OPTIONS3 : "Arata mai multe optiuni de cautari pentru sortarea rezultatelor cautarii.",
		SHOW_EXTENDED : "cautare avansata",
		SHOW_MOON_SELECTION : "Planeta cu luna",
		SHOW_REPORT_SELECTION : "Planeta cu raport",
		SHOW_FILTER_BY : "Exclude din lista",
		SHOW_FILTER_NONE : "niciuna",
		SHOW_PLAYERS_WITHOUT_PROGRESS : "Show players without score changes within the last few days",
		STATUS_TITLE : "OGame Galaxytool - pagina cu statistici",
		STATUS_DB_STATUS : "Starea bazei de date",
		STATUS_COLOR : "Culoare",
		STATUS_AGE1 : "Date cu 1 zi vechime.",
		STATUS_AGE2 : "Date cu 2 - 4 zile vechime.",
		STATUS_AGE3 : "Date cu 4 - 7 zile vechime.",
		STATUS_AGE4 : "Date cu 1 - 2 saptamani vechime.",
		STATUS_AGE5 : "Date cu 2 - 4 saptamani vechime.",
		STATUS_AGE6 : "Date mai vechi de 1 luna!",
		STATUS_AGE7 : "Nici o data disponibila.",
		STATUS_ON : "Activ",
		STYLES_COLOR1 : "Culoarea1",
		STYLES_COLOR2 : "Culoarea2",
		STYLES_COLOR3 : "Culoarea3",
		STYLES_COLOR4 : "Culoarea4",
		STYLES_COLOR5 : "Culoarea5",
		STYLES_COLOR6 : "Culoarea6",
		STYLES_COLOR7 : "Culoarea7",
		STATUS_DB_LEGEND : "Legenda",
		STATUS_GALAXY : "Vederea Galaxiei",
		USER_TITLE : "Controlul Utilizatorilor",
		USER_NAMES : "Utilizator",
		USER_ERROR : "Eroare",
		USER_NEWUSER : "Utilizator nou",
		USER_OPTIONS : "Optiuni",
		USER_USERNAME : "Numele utilizatorului",
		USER_PASSWORD : "Parola",
		USER_PASSWORD_CONFIRM : "Confirma parola",
		USER_GALAXY : "Galaxia",
		USER_SEARCH : "Cauta",
		USER_INSERT : "Inserare",
		USER_DELETE : "Stergere",
		USER_DELETE_ENTRY : "Vrei sa stergi utilizatorul: ",
		USER_STATUS : "Vezi statistici",
		USER_STYLES : "Modificare in pagina",
		USER_SUBMIT : "Trimite",
		USER_RESET : "Reset",
		USER_YES : "DA",
		USER_NO : "NU",
		USER_STYLEPATH : "Calea catre styles.css",
		USER_PROBES : "Vezi/trimite rapoarte de spionare",
		USER_EMAIL : "Email",
		USER_ERROR1 : "Parola gresita sau email invalid.",
		USER_ERROR2 : "Email invalid.",
		USER_INGAME : "Numele in joc",
		USER_ALLYTAG : "Numele aliantei",
		USER_ALLYHISTORY : "Vedere istoric",
		USER_DIPLOMATIC : "Schimbare statut diplomatic",
		USER_STATSPAGE : "Numar de afisari pe pagina de statistica",
		USER_LINKS : "Links",
		USER_LINKS2 : "Format:<br>text;url<br>text2;url2<br>text3;url3",
		USER_EXPORT_TITLE : "Export culori (BB Codes)",
		USER_BB_COORDINATES : "Coordonate",
		USER_BB_MOON : "Luna",
		USER_BB_DEBRIS : "Camp de ramasite",
		USER_BB_ALLY : "Numele Aliantei",
		USER_BB_ALLYDETAILS : "Detaliile aliantei",
		USER_BB_PLAYERNAME : "Numele jucatorului",
		USER_BB_BANNED : "banat",
		USER_BB_VACATION : "in mod vacanta",
		USER_BB_NOOB : "noob",
		USER_BB_INACTIVE : "Inactiv",
		USER_BB_LONGINACTIVE : "Inactiv lung",
		USER_DELETION : "Sterge",
		USER_FLEETINFO : "Miscarile flotelor",
		USER_ACTIVITIES : "Activitatile jucatorului",
		USER_MAINTENANCE : "Intretinerea Galaxytool",
		USER_MANAGEMENT : "Control utilizatori",
		USER_DELETE_MY_COMBAT_REPORTS : "Sterge rapoartele mele de lupta",
		USER_DELETE_MY_MESSAGES : "Sterge mesajele mele",
		USER_DELETE_MY_FLEETMOVES : "Sterge miscarile flotei mele",
		USER_DELETE_MY_COMBAT_REPORTS_LIMITED : "Sterge rapoartele mele de lupta mai vechi de &1 zile",
		USER_DELETE_MY_MESSAGES_LIMITED : "Sterge mesajele mele mai vechi de &1 zile",
		USER_TABLE_ENTRIES : "Numarul de rezultate de cautare pe fiecare pagina",
		USER_EXISTS : "Utilizatorul deja exista",
		USER_BB_OUTLAW : "Proscris",
		USER_INVALID_URL : "URL &1 pare a fi invalid - URLva fi ignorat",
		VIEW_TITLE : "OGame Galaxytool - Vederea galaxiei",
		VIEW_NODATA : "Nici o data disponibila.",
		VIEW_GALAXY : "Galaxie",
		VIEW_SYSTEM : "Sistemul solar",
		VIEW_POSITION : "Poz.",
		VIEW_PLANET : "Planeta",
		VIEW_MOON : "Luna",
		VIEW_TF : "CR",
		VIEW_PLAYER : "Jucator",
		VIEW_PLAYER_ADD : "(Rank / Status)",
		VIEW_ALLY : "Alianta",
		VIEW_ALLY_ADD : "(Rank / Membru)",
		VIEW_METAL : "M",
		VIEW_CRYSTAL : "C",
		VIEW_COLONISED : "Planete locuite",
		VIEW_UKMOONSIZE : "necunoscut",
		VIEW_BACK : "inapoi",
		VIEW_NOTICE : "Mesaje",
		VIEW_REPORTS : "Rapoarte",
		VIEW_MOONPHALANX : "Urmatoarele luni pot scana sistemul",
		VIEW_NOMOONS : "Nici o luna gasita",
		VIEW_IRAKS : "Urmatoarele planete pot lovi sistemul acesta cu rachete interpalnetare",
		VIEW_NOIRAKS : "Nici o racheta interplanetara gasita",
		VIEW_MOON_DESTROY_CHANCE : "Sanse de distrugere a lunii",
		VIEW_CHANCE_WITH_ONE : "Sanse cu un RIP",
		VIEW_CHANCE_WITH_N : "Sanse cu ",
		VIEW_DEATH_STARS : "RIP-uri",
		VIEW_DS_DESTROY_CHANCE : "Sanse de a pierde RIP",
		VIEW_TOP : "SUS",
		VIEW_GO : "go",
		VIEW_DIAMETER : "Diametru",
		PW_TITLE : "OGame Galaxytool - schimbare parola",
		OLD_PASSWORD : "parola veche",
		NEW_PASSWORD : "parola noua",
		CONFIRM_NEW_PASSWORD : "confirmare parola noua",
		PW_MISMATCH : "parola noua nu este la fel cu confirmarea parolei noi!",
		PW_ERROR : "Parola veche incorecta!",
		UPDATE_DONE : "Schimbarea parolei cu succes.",
		TIMEZONE_OFFSET : "Ora locala nu este setata in server",
		DELETE_ACCOUNT : "Stergere cont Galaxytool",
		DELETE_ACCOUNT_SAFETY_REQUEST : "Sunteti siguri ca doriti sa stergeti contul Galaxytool?",
		CH_PASSWD_AUTHORIZATION : "Autorizare",
		CH_PASSWD_ADMIN : "Admin",
		TIMEZONE_OGAME_OFFSET : "Compensarea fusului orar la serverul OGame",
		CH_PASSWD_USER_LANGUAGE : "Schimba la aceasta limba dupa conectare",
		CH_PASSWD_USER_LANGUAGE_NO_CHANGE : "Nicio schimbare",
		CH_PASSWD_EXPAND : "Extins",
		CH_PASSWD_COLLAPSE : "Prabusit",
		CH_PASSWD_HIDDEN : "Ascuns",
		CH_PASSWD_GETTING_STARTED : "Arata Informatiile despre Notiunile de baza dupa conectare",
		CH_PASSWD_PLUGIN : "Arata Informatiile despre Plugin dupa conectare",
		NOTICE_TITLE : "OGame Galaxytool - Notite",
		NOTICE_HEADER : "editare notita",
		NOTICE_HEADER2 : "editare notita proprie",
		NOTICE_PUBLIC : "Accesibil pentru altii ?",
		NOTICE_YES : "da",
		NOTICE_NO : "nu",
		NOTICE_TEXT : "textul notitei",
		NOTICE_SAVE : "Salvare",
		NOTICE_DELETED : "Intrare stearsa",
		NOTICE_SAVED : "Intrare salvata",
		NOTICE_RESULTS : "Toate rezultatele",
		NOTICE_USER : "Utilizator",
		NOTICE_DATE : "Data",
		NOTICE_EDIT : "Editeaza",
		NOTICE_DELETE : "Sterge",
		NOTICE_NEW : "Creare intrare proprie",
		NOTICE_NOTPUBLIC : "Notita privata.",
		NOTICE_ALL : "tot",
		NOTICE_NONE : "niciuna",
		NOTICE_SEARCH : "Cautare in notite",
		NOTICE_SEARCH_SHORT : "Cautare",
		NOTICE_HITS : "Rezultate",
		NOTICE_SHOWRESULTS : "rezultate pe pagina",
		NOTICE_OF : "de",
		NOTICE_NOTHING : "Nici un rezultat gasit",
		NOTICE_CHARS : "Caractere",
		NOTICE_PLAYERNAME : "Jucator",
		NOTICE_SHOWALL : "Arata toate notitele",
		REPORTS_TITLE : "OGame Galaxytool - Rapoarte de Spionare",
		REPORTS_RESOURCES : "Resurse",
		REPORTS_FLEET : "Flote",
		REPORTS_DEFENCE : "Aparare",
		REPORTS_BUILDINGS : "Cladiri",
		REPORTS_TECHNOLOGY : "Cercetari",
		REPORTS_MOON : "Luna",
		REPORTS_SEARCH : "Cautare in rapoarte de spionare",
		REPORTS_SEARCH_SHORT : "Cauta",
		REPORTS_HITS : "Rezulate",
		REPORTS_NOTHING : "Nici o data gasita",
		REPORTS_ADDRESS : "Adresa",
		REPORTS_CURRENTNESS : "Currentness",
		REPORTS_PLAYERNAME : "Numele jucatorului",
		REPORTS_ALLY : "Aliat",
		REPORTS_VIEW : "vezi raport",
		REPORTS_SEARCH_IN : "Cauta in galaxia",
		REPORTS_FROM_SYSTEM : "de la sistemul",
		REPORTS_TO : "la",
		REPORTS_DELETE : "sterge",
		REPORTS_DELETED : "Intrare stearsa",
		REPORTS_RESULTS : "rezultate pe pagina",
		REPORTS_OF : "de",
		REPORTS_DATE : "data",
		REPORTS_DATE_0 : "nu conteaza",
		REPORTS_DATE_1 : "mai vechi de",
		REPORTS_DATE_2 : "mai noi de",
		REPORTS_NOTICES : "Notite",
		REPORTS_AT_LEAST_RESOURCES : "Resurse (cel putin)",
		REPORTS_SEARCH_EXTENDED : "cautare extinsa",
		REPORTS_FLEET_RESIS : "Flota- scor",
		REPORTS_DEFENCE_RESIS : "Aparare- scor",
		REPORTS_ALL_RESIS : "suma scoruri",
		REPORTS_TECHS : "Tehnologii",
		REPORTS_UNKNOWN_ENTRIES : "introduceri necunoscute",
		REPORTS_PARTLY_INSERTED : "partial introdus",
		REPORTS_FOR_ALL_RES : "pentru toate resursele",
		REPORTS_FOR_TF : "pentru campul de ramasite",
		REPORTS_KT : "Transportoare mici",
		REPORTS_GT : "Transportoare mari",
		REPORTS_SS : "Nave de razboi",
		REPORTS_REC : "Reciclator",
		REPORTS_RAIDABLE : "Doar tinte pentru atac",
		REPORTS_ALL_RESOURCES : "toate Resursele",
		REPORTS_STUFF : "Altele",
		REPORTS_SPEEDSIM : "Simuleaza cu Speedsim",
		REPORTS_DRAGOSIM : "Simuleaza cu Dragosim",
		REPORTS_STATUS : "Status",
		REPORTS_ERROR : "o eroare sa produs",
		REPORTS_OWN_REPORTS : "Doar rapoartele mele",
		REPORTS_UPLOAD_BY : "Raport incarcat de",
		REPORTS_DEPTH : "Adancime raport",
		REPORTS_FLEET_SCORE : "Scor flota",
		REPORTS_DEFENCE_SCORE : "Scor aparare",
		REPORTS_HOURS : "ore",
		REPORTS_MAX_RESULTS_HIT : "Interogarea dumneavoastra cu mai mult de &1 hituri. Numai primele &1 rezultate sunt aratate. Ajustati cererea de cautare pentru a primii mai putine rezultate.",
		REPORTS_OSIMULATE : "Simuleaza cu OSimulate",
		REPORTS_SHOW_ONLY : "Arata doar",
		REPORTS_SHOW_PLANETS : "Planete",
		REPORTS_SHOW_MOONS : "Luni",
		REPORTS_OWNER : "Rapoarte detinute de catre",
		STATS_TITLE : "OGame Galaxytool - Statistici",
		STATS_TBLHEAD : "Statistici",
		STATS_RANK : "Rank",
		STATS_PLAYERNAME : "Numele Jucatorului",
		STATS_ALLYNAME : "Numele Aliantei",
		STATS_SCORE : "Scor",
		STATS_FLEET : "Flota",
		STATS_RESEARCH : "Cercetari",
		STATS_MEMBERS : "Membri",
		STATS_STATUS : "Status",
		STATS_NOTHING : "fara Status",
		STATS_NAP : "NAP",
		STATS_ALLIED : "Aliati",
		STATS_WAR : "Razboi",
		STATS_BOYCOTT : "Boicot",
		STATS_NEUTRAL : "Neutri",
		STATS_OWN : "Alianta Proprie",
		STATS_WING : "Ajutor",
		STATS_UPDATE : "Intrare de la",
		STATS_PLAYERSTATS : "Statisticile Jucatorului",
		STATS_ALLYSTATS : "Statisticile Aliantei",
		STATS_DELETE : "Vrei sa stergi intrarea aceasta ?",
		STATS_CONFIRM_DELETE : "Chiar vrei sa stergi intrarea aceasta?",
		STATS_CHANGE_PLAYER_STATUS : "Statistica Jucatorului",
		STATS_CHANGE_ALLIANCE_STATUS : "Statistica Aliantei",
		STATS_CHANGE_ALLIANCE_STATUS_HINT : "Toti membrii acestei aliantei primesc acelasi statut.Orice alt statut va fi sters.Poti schimba statutul unor jucatori dupa aceeea.",
		STATS_UNKNOWN : "Restul",
		STATS_DETAILS : "Detalii pentru",
		STATS_PLAYERSTATUS : "Statutul jucatorului",
		STATS_IGNORE_STATUS : "tot",
		STATS_ACTIVE : "activ",
		STATS_INACTIVE : "Inactiv",
		STATS_BANNED : "banat",
		STATS_VACATION : "in mod vacanta",
		STATS_NOOB : "noob",
		STATS_YES : "DA",
		STATS_NO : "Doar planete cu mesaje",
		STATS_SEARCH : "Cauta",
		STATS_SHOW_GRAPH : "Arata detalii pentru distribuirea punctajului",
		STATS_LONG_INACTIVE : "Inactiv lung",
		STATS_STANDARD : "Puncte Standard",
		STATS_MILITARY : "Puncte de armata",
		STATS_ECONOMY : "Economie",
		STATS_HONOUR : "Puncte de Onoare",
		STATS_MILITARY_BUILD : "Armata construita",
		STATS_MILITARY_DESTROYED : "Armata distrusa",
		STATS_MILITARY_LOST : "Armata pierduta",
		REGISTER_REGISTRATE : "Inregistrare",
		REGISTER_LOGINNAME : "Nume utilizator",
		REGISTER_PASSWORD : "Parola",
		REGISTER_PASSWORD_CONFIRM : "Confirmare parola",
		REGISTER_EMAIL : "Email",
		REGISTER_INGAME : "Numele in joc",
		REGISTER_ALLYTAG : "Numele aliantei",
		REGISTER_EMAILVERIFICATION : "Verificare email",
		REGISTER_EMAILTEXT : "Te rog urmareste link-ul acesta pentru confirmarea inregistrarii la galaxytool.",
		REGISTER_ERROR1 : "Numele de utilizator deja exista.",
		REGISTER_ERROR2 : "Eroare incercand sa trimit email. Te rog contacteaza-l pe administrator.",
		REGISTER_ERROR3 : "Eroare incercand sa trimit date catre baza de date!",
		REGISTER_INFO1 : "Contul tau a fost creat.",
		REGISTER_INFO2 : "Te rog viziteaza link-ul din email pentru a confirma inregistrarea .",
		REGISTER_INFO3 : "Cont confirmat. Administratorul trebuie sa mai activeze contul tau.",
		REGISTER_BUTTON : "Inapoi la pagina principala",
		REGISTER_NEW_SUBJECT : "Un nou utilizator sa inregistrat la galaxytool",
		REGISTER_NEW_MAILTEXT : "Un nou utilizator sa inregistrat.",
		REGISTER_BACK : "Inapoi pe prima pagina",
		REGISTER_MISSING_FIELDS : "Completati toate casutele",
		REGISTER_ERROR4 : "Adresa de E-mail nu este valida.",
		REGISTER_ERROR5 : "Parolele nu se potrivesc.",
		REGISTER_PWS : "Rezistenta parolei",
		REGISTER_PWS0 : "foarte slaba",
		REGISTER_PWS1 : "slaba",
		REGISTER_PWS2 : "buna",
		REGISTER_PWS3 : "tare",
		REGISTER_PWS4 : "foarte tare",
		REGISTER_EMAIL_USED : "Adresa de Email este deja folosita",
		LOSTPW_TITLE : "Parola pierduta",
		LOSTPW_INFO2 : "O parola noua a fost generata si trimisa in email-ul tau.",
		LOSTPW_BUTTON1 : "Obtine parola noua",
		LOSTPW_BUTTON2 : "Inapoi la pagina principala",
		LOSTPW_LOGINNAME : "Nume Utilizator",
		LOSTPW_EMAIL : "Email",
		LOSTPW_ERROR1 : "Eroare incercand sa trimit date la baza de date!",
		LOSTPW_ERROR2 : "Nu sa gasit nimica!",
		LOSTPW_ERROR3 : "Eroare incercand sa trimit email. Te rog contacteaza administratorul tau.",
		LOSTPW_EMAIL_SUBJECT : "Parola ta cea noua pe care ai cerut-o",
		LOSTPW_EMAIL_TEXT1 : "Aici sunt datele noi pentru Galaxytool",
		LOSTPW_EMAIL_TEXT2 : "Nume utilizator",
		LOSTPW_EMAIL_TEXT3 : "Parola",
		LOSTPW_INFO1 : "Veti primit un email ca sa va verificati cererea deresetare a parolei.",
		LOSTPW_CONFIRM_RESET_SUBJECT : "A-ti pierdut parola?",
		LOSTPW_CONFIRM_RESET_MESSAGE : "Buna,\n\na-ti cerut resetarea parolei pentru Galaxytool. Pentru a genera o noua parola, apasati pe urmatorul link:",
		USERINFO_TITLE : "OGame Galaxytool - Informatii Utilizator",
		USERINFO_NAMES : "Toti userii",
		USERINFO_DETAIL : "informatii detaliate despre",
		USERINFO_ERROR1 : "Nici un user cunoscut cu acest ID!",
		USERINFO_USERNAME : "Nume Utilizator",
		USERINFO_INGAME : "Nume in joc",
		USERINFO_EMAIL : "Email",
		USERINFO_ALLYTAG : "Alianta",
		USERINFO_STYLEPATH : "Culoare imagine",
		USERINFO_STATUS : "Status",
		USERINFO_ACTIVATE : "Activeaza jucator",
		USERINFO_LOGINS : "Numarul de conectari",
		USERINFO_LASTLOGIN : "Ultima conectare",
		USERINFO_DATA : "Informatii despre sistemul introdus",
		USERINFO_NODATA : "Acel utilizator nu a introdus nici un sistem inca!",
		USERINFO_GALAXY : "Galaxie",
		USERINFO_SYSTEMS : "Numarul de sisteme",
		USERINFO_IP : "Adresa IP",
		USERINFO_LOGINTIME : "Conectare",
		USERINFO_NOLOGIN : "Jucatorul nu sa conectat niciodata.",
		USERINFO_LAST_GALAXYUPDATE : "Ultima introducere a unui sistem",
		USERINFO_LAST_PUBLIC_NOTICE : "Ultima notita publica",
		USERINFO_LAST_PRIVATE_NOTICE : "Last private notice",
		USERINFO_NUMBEROF_PUBLIC_NOTICE : "Numarul de notite publice",
		USERINFO_NUMBEROF_PRIVATE_NOTICE : "Numarul de notite private",
		USERINFO_ACTIVATED : "Cont activat",
		USERINFO_ACTIVATIONTEXT : "Administratorul The Galaxytool ti-a activat contul.nnDistractie placuta cu Galaxytool!",
		USERINFO_LAST_SUBMIT : "Inserate ultimele informatii",
		ALLYHISTORY_TITLE : "OGame Galaxytool - Istoricul Aliantei",
		ALLYHISTORY_TBLHEAD : "Istoric",
		ALLYHISTORY_PLAYERNAME : "Numele Jucatorului",
		ALLYHISTORY_ALLYNAME : "Alianta",
		ALLYHISTORY_LASTMONTH : "Ultima luna",
		ALLYHISTORY_ALL_DATA : "toate informatiile disponibile",
		ALLYHISTORY_SHOW : "arata statistica",
		ALLYHISTORY_TIMESPAN : "Timpul",
		ALLYHISTORY_PROGESS : "Progres",
		ALLYHISTORY_SCORE : "Scoruri",
		ALLYHISTORY_FSCORE : "Scorurile flotei",
		ALLYHISTORY_RSCORE : "Scorurile Cercetarilor",
		ALLYHISTORY_MEMBER : "Membrii",
		ALLYHISTORY_NOTHING : "nu sa gasit nimic",
		ALLYHISTORY_DETAILS : "Detalii",
		ALLYHISTORY_SHOW_ADDRESS : "Coordonate",
		ALLYHISTORY_ESCORE : "Economie",
		ALLYHISTORY_MSCORE : "Puncte de armata",
		DETAILEDINFO_PLAYERINFO_TITLE : "Informatiile jucatorului",
		DETAILEDINFO_ALLYINFO_TITLE : "Informatiile aliantei",
		DETAILEDINFO_PLAYERINFO_TBLHEAD : "Informatii detaliate despre jucator",
		DETAILEDINFO_ALLYINFO_TBLHEAD : "Informatii detaliate despre alianta",
		DETAILEDINFO_NO_ALLIANCE : "niciuna",
		DETAILEDINFO_SCORE : "Statistici dupa scor",
		DETAILEDINFO_FLEET : "Statistici dupa flota",
		DETAILEDINFO_RESEARCH : "Statistici dupa cercetari",
		DETAILEDINFO_RANK : "Rank",
		DETAILEDINFO_POINTS : "Scor",
		DETAILEDINFO_KNOWN_PLANETS : "planete cunoscute",
		DETAILEDINFO_MOONS : "luni cunoscute",
		DETAILEDINFO_PHALANX_AREA : "Aria Phalanx",
		DETAILEDINFO_NO_PHALANX_AREA : "nici un Phalanx gasit",
		DETAILEDINFO_NOTICES : "Notite",
		DETAILEDINFO_NO_NOTICES : "Nici o notita gasita",
		DETAILEDINFO_PREVIOUS_ALLIANCES : "Alianta dinainte",
		DETAILEDINFO_RESOURCES_PER_HOUR : "Resurse pe ora",
		DETAILEDINFO_RESOURCES_PER_DAY : "Resurse pe zi",
		DETAILEDINFO_RESOURCES_PER_WEEK : "Resurse pe saptamana",
		DETAILEDINFO_RESOURCES_PER_MONTH : "Resurse pe luna (30 zile)",
		DETAILEDINFO_METAL : "Metal",
		DETAILEDINFO_CRYSTAL : "Cristal",
		DETAILEDINFO_DEUTERIUM : "Deuteriu",
		DETAILEDINFO_UNKNOWN : "necunoscut",
		DETAILEDINFO_SCORE_DISTRIBUTION : "Distribuirea scorului",
		DETAILEDINFO_GENERAL : "Detalii",
		DETAILEDINFO_MEMBERS : "Membru",
		DETAILEDINFO_GRAPHS : "Grafice",
		DETAILEDINFO_RESOURCES : "Resurse",
		DETAILEDINFO_FLEET_TAB : "Flota",
		DETAILEDINFO_TECH : "Cercetari",
		DETAILEDINFO_FLEET_DETAIL : "Suma / (media jucatorilor) provenit din toate rapoartele",
		DETAILEDINFO_TECH_DETAIL : "Media tuturor informatiilor despre jucator",
		DETAILEDINFO_PLANET_TAB : "Planete",
		DETAILEDINFO_MOON_TAB : "Luni",
		DETAILEDINFO_ACTIVITIES : "Activities",
		DETAILEDINFO_NODATA : "Nici o data disponibila.",
		DETAILEDINFO_ACTIVITY_DESCRIPTION : "Arata activitatile din &1 colectate din:",
		DETAILEDINFO_GALAXYVIEWS : "Vizualizari Galaxie",
		DETAILEDINFO_SCANS : "Actiune de spionare",
		DETAILEDINFO_MESSAGES : "Mesajele jucatorului",
		DETAILEDINFO_COMBATS : "Rapoarte de lupta",
		DETAILEDINFO_ALLYPAGE : "Vizualizare alianta",
		DETAILEDINFO_MANUAL : "Insertii manuale",
		DETAILEDINFO_START : "Inceperea",
		DETAILEDINFO_TO : "la",
		DETAILEDINFO_TODAY : "Astazi",
		DETAILEDINFO_DATA_RESTRICTION : "restrictionat:",
		DETAILEDINFO_WEEKDAY_WEEKEND : "Weekend",
		DETAILEDINFO_WEEKDAY_WORKINGDAY : "Zile din saptamana",
		DETAILEDINFO_WEEKDAY_MONDAY : "Luni",
		DETAILEDINFO_WEEKDAY_TUESDAY : "Marti",
		DETAILEDINFO_WEEKDAY_WEDNESDAY : "Miercuri",
		DETAILEDINFO_WEEKDAY_THURSDAY : "Joi",
		DETAILEDINFO_WEEKDAY_FRIDAY : "Vineri",
		DETAILEDINFO_WEEKDAY_SATURDAY : "Sambata",
		DETAILEDINFO_WEEKDAY_SUNDAY : "Duminica",
		DETAILEDINFO_WEEKDAY_SHORTLENGTH : 3,
		DETAILEDINFO_PLAYER_CURRENTLY_ACTIVE : "The player is currently active",
		DETAILEDINFO_PLAYER_MESSAGES : "mesajele valabile ale jucatorului",
		DETAILEDINFO_SHOW : "arata",
		DETAILEDINFO_NONE : "niciuna valabila",
		DETAILEDINFO_ENTER_MANUALLY : "Introdu activitati pentru acest jucator",
		DETAILEDINFO_PLAYER_SEEN_ON : "Jucatorul a fost online la",
		DETAILEDINFO_INSERT : "Introdu",
		DETAILEDINFO_OGAME_SERVERTIMES : "Nota: Toate datele si orele se refera la ora serverului OGame!",
		DETAILEDINFO_DAY_VIEW : "vizualizare de 24 de ore",
		DETAILEDINFO_WEEK_VIEW : "vizualizare saptamanala",
		DETAILEDINFO_HOME_PLANET : "Planeta Principala",
		DETAILEDINFO_PLANETNAME : "Nume",
		DETAILEDINFO_DEFENCE_SCORE : "Puncte de aparare",
		DETAILEDINFO_DEFENCE_SCORE_TOOLTIP : "Puncte de aparare = Puncte - Flota + Cercetari + Economie.<br/>Toate acele statistici trebuiesc actualizate pentru a avea un rezultat cu sens!",
		DETAILEDINFO_SCORE_PER_SHIP : "Puncte pe nava",
		DETAILEDINFO_SHIPS : "Numar de nave",
		DETAILEDINFO_DATE_IN_FUTURE : "Nu mentine datile care nu se afla in trecut.",
		ADMIN_TITLE : "Administratia Galaxytool",
		ADMIN_DISCLAMER : "Atentie: Folositi aceste scripturi pe proprie raspundere! Multe dintre ele sterg date.",
		ADMIN_INCONSISTENCIES : "Neconcordante in date",
		ADMIN_PLANETS : "Planete pe pozitia 0 sau mai mare de 15",
		ADMIN_GALAXIES : "Stergere galaxii mai mari de &1 ",
		ADMIN_PLAYERS : "Sterge jucatori fara OGame playerid - rezulta intrari identice ale jucatorilor",
		ADMIN_REPORTS : "Stergere rapoarte daca nu mai exista planeta",
		ADMIN_MISC : "Amestecare",
		ADMIN_RESET : "Resetare Galaxytool (doar ip-urile si userii nu se sterg)",
		ADMIN_OLD_PLAYERS : "Sterge intrarile jucatorului mai vechi de &1 zile",
		ADMIN_OLD_REPORTS : "Sterge rapaorte mai vechi de",
		ADMIN_LOADING : "Nu inchide pagina in timp ce se incarca.",
		ADMIN_STATUS : "Stadiul in care se afla cererea ta",
		ADMIN_SELECTION : "Cel putin o intrare trebuie selectata",
		ADMIN_SAFETY : "Esti sigur ca vrei sa utilizezi acest/e script/uri ?",
		ADMIN_DONE : "Terminat",
		ADMIN_NOTBD : "Nimic de facut",
		ADMIN_OLD_GALAXIES : "Sterge vizualizarea galaxiilor mai vechi de &1 zile",
		ADMIN_UNUSED_PLAYERS : "Stergere jucatorii ce nu mai exista in nicio vizualizare a galaxiei",
		ADMIN_OLD_ACTIVITIES : "Inlatura activitatile mai vechi de &1 zile ale jucatorilor",
		ADMIN_OLD_COMBATS : "Sterge rapoartele de lupta mai vechi de &1 zi",
		ADMIN_OLD_INGAME_MSG : "Sterge mesajele din joc mai vechi de &1 zile",
		ADMIN_OGAME_API : "Incarca date publice din OGame in Galaxytool",
		ADMIN_OGAME_ALL_DATA : "toate informatiile disponibile",
		ADMIN_OGAME_GALAXY_DATA : "Vezi galaxia",
		ADMIN_OGAME_STATISTICS_DATA : "Statistici",
		ERRORPAGE_PAGEFORWARD : "Apasa aici daca browser-ul tau nu suporta redirectionarea",
		ERRORPAGE_PERMISSION_DENIED : "Nu ai permisiunea de a intra pe aceasta pagina. Click pentru a te intoarce.",
		FLEETS_TITLE : "Miscarile flotei",
		FLEETS_ACTUAL_FLEETS : "Miscarile curente ale flotei",
		FLEETS_YES : "DA",
		FLEETS_NO : "Doar planete cu mesaje",
		FLEETS_DETAILS : "Details",
		FLEETS_MISSION_EXPEDITION : "Expeditie",
		FLEETS_MISSION_COLONIZATION : "Colonizare",
		FLEETS_MISSION_RECYCLE : "Recicleaza",
		FLEETS_MISSION_TRANSPORT : "Transport",
		FLEETS_MISSION_DEPLOYMENT : "Desfasurare",
		FLEETS_MISSION_ESPIONAGE : "Spionare",
		FLEETS_MISSION_ACS_DEFEND : "Aparare ACS",
		FLEETS_MISSION_ATTACK : "Atac",
		FLEETS_MISSION_ACS_ATTACK : "Atac ACS",
		FLEETS_MISSION_MOON_DESTRUCTION : "Distrugere luna",
		FLEETS_MISSION_MISSILE_ATTACK : "Atac cu Rachete",
		FLEETS_NO_DATA : "Nicio informatie aplicabila gasita",
		FLEETS_FLEET : "Flota",
		FLEETS_ALL_FLEETS : "Arata toate miscarile flotei",
		COMBAT_REPORT_OUDATED_GALAXYVIEW : "Informatiile galaxiei sunt invechite. Va rog vizitati prima data originea luptei si coordonatele tintei!",
		MESSAGES_TITLE : "OGame Galaxytool - Mesaje OGame",
		MESSAGES_PLAYERNAME : "Numele jucatorului",
		MESSAGES_SUBJECT : "Subiect",
		MESSAGES_DATE : "Data",
		MESSAGES_FILTER : "Filtru",
		MESSAGES_DELETE : "Sterge mesaj",
		MESSAGES_PUBLISH_DETAIL : "Publica mesajul adaugand mesajul la continutul textului notitei jucatorului.",
		MESSAGES_PUBLISH_HEADER : "&sender a trimis un mesaj lui &recipient pe &date:\n\n &message",
		MESSAGES_PLAYER_FILTER : "Mesaje pentru jucatori:",
		MESSAGES_CONTENT : "Continut",
		COMBATS_TITLE : "OGame Galaxytool - Rapoarte de lupta",
		COMBATS_ATTACKER : "Atacator",
		COMBATS_DEFENDER : "Aparator",
		COMBATS_DATE : "Data",
		COMBATS_OWNER : "Detinator",
		COMBATS_WINNER : "Castigator",
		COMBATS_COMBATREPORT : "Raport de Lupta",
		COMBATS_COMBAT_AT : "Lupta la",
		COMBATS_LOST_UNITS : "Unitati pierdute",
		COMBATS_LOOT : "Prada",
		COMBATS_DEBRIS : "Camp de Ramasite",
		COMBATS_AND : "si",
		COMBATS_PUBLISH : "Partajeaza acest raport",
		COMBATS_UNPUBLISH : "Anulati partajarea acestui raport(fa-l din nou privat)",
		COMBATS_DELETE : "Sterge raportul",
		COMBATS_CHECK_ALL : "Bifeaza Tot",
		COMBATS_UNCHECK_ALL : "Debifeaza Tot",
		COMBATS_WITH_SELECTED : "Cu selectate",
		COMBATS_PUBLIC_REPORTS : "Rapoarte publice",
		COMBATS_YES : "DA",
		COMBATS_NO : "Doar planete cu mesaje",
		COMBATS_SEARCH_OPTIONS : "Optiuni de cautare",
		COMBATS_SEARCH : "Du-te",
		COMBATS_RESET : "Reseteaza",
		COMBATS_COORDINATES : "Coordonate",
		COMBATS_INVALID_GALAXY_ENTERED : "Galaxie invalida introdusa",
		COMBATS_INVALID_SYSTEM_ENTERED : "Sistem invalid introdus",
		COMBATS_INVALID_PLANET_ENTERED : "Planeta invalida introdusa",
		COMBATS_GALAXY_FROM_TO : "Galaxie",
		COMBATS_SYSTEM_FROM_TO : "Sistem",
		COMBATS_PLANET_FROM_TO : "Planeta",
		COMBATS_APPLY : "Aplica",
		COMBATS_COMBAT_SUMMARY : "Sumarul rapoartelor de lupta",
		COMBATS_DOWNLOAD_CSV : "Descarca ca fisiers CSV",
		REPORT_ARCHIVE_TITLE : "Arhiva Rapoartelor",
		REPORT_ARCHIVE_COORDINATES : "Coordonate",
		REPORT_ARCHIVE_SCANTIME : "Timp de Scanare",
		REPORT_ARCHIVE_DELETE : "Sterge aceste intrari",
		REPORT_ARCHIVE_CONFIRM_DELETE : "Esti sigur ca vrei sa stergi aceste intrari?",
		REPORT_ARCHIVE_GALAXY : "Galaxie",
		REPORT_ARCHIVE_SYSTEM : "Sistem",
		REPORT_ARCHIVE_PLANET : "Planeta",
		REPORT_ARCHIVE_MOON : "Luna",
		REPORT_ARCHIVE_DETAILS : "Detalii",
		REPORT_ARCHIVE_RESOURCES : "Resurse pe ora",
		REPORT_ARCHIVE_HEADER_RESOURCES : "Resurse",
		REPORT_ARCHIVE_DETAILS_FOR : "Arhiva rapoartelor pentru &1 [&2] (&3)",
		REPORT_ARCHIVE_FLEET_CARGO : "Capacitatea de transporta flotei ",
		REPORT_ARCHIVE_IRAK_RANGE : "Raza Rachetelor Interplanetare",
		REPORT_ARCHIVE_CHART_TYPE : "Tipul graficului",
		INSTALL_TITLE : "Instalarea Galaxytool pentru versiunea",
		INSTALL_PROGRESS : "Progres",
		INSTALL_STEP : "Pas",
		INSTALL_CONTINUE : "Continua",
		INSTALL_VALIDATE : "Valideaza",
		INSTALL_STEP1 : "Bine ai venit",
		INSTALL_STEP2 : "Bifa inscriptibila",
		INSTALL_STEP3 : "Setarile bazi de date",
		INSTALL_STEP4 : "Setari OGame",
		INSTALL_STEP5 : "Setari Galaxytool",
		INSTALL_STEP6 : "Parola administratorului",
		INSTALL_STEP7 : "Instaleaza Galaxytool",
		INSTALL_STEP8 : "Finalizeaza instalarea",
		INSTALL_FILE_DELETE_CHECK : "Va rugam stergeti install.php si update.php de pe serverul dumneavoastra.",
		INSTALL_STEP1_PHP_FAILED : "Versiunea dumneavoastra PHP &1 nu este compatibila cu aceasta versiunea de Galaxytool",
		INSTALL_STEP1_FOPEN_FAILED : "Versiunea dumneavoastra PHP nu permite sa deschideti pagini web cu comanda FOPEN() . Aceasta este necesara pentru a consuma OGame API.",
		INSTALL_STEP1_WELCOME : "Bun venit la vrajitorul de instalare Galaxytool. Veti fi ghidat prin instalarea Galaxytool.",
		INSTALL_STEP2_DESCRIPTION : "Asigurativa ca fisierele config.php si attributes.php au permisiunea de scriere activata.",
		INSTALL_STEP2_DESCRIPTION2 : "Daca nu stiti cum sa reusiti acest lucru, va rog sa va uitati aici: &1",
		INSTALL_STEP2_FILE_NOT_WRITEABLE : "Fisierul nu este inscriptionabil",
		INSTALL_STEP3_SERVER : "Serverul bazei de date",
		INSTALL_STEP3_USERNAME : "Utilizator",
		INSTALL_STEP3_PASSWORD : "Parola",
		INSTALL_STEP3_DBNAME : "Numele bazei de date",
		INSTALL_STEP3_PREFIX : "Prefixul numelui tabelului",
		INSTALL_STEP3_ENTER_PREFIX : "Ex. mytool_",
		INSTALL_STEP3_ENTER_SERVER : "Introduceti adresa serverului. Contactati administratorul dumneavoastra de sistem daca este necesar. In mod normal valoarea corecta este localhost..",
		INSTALL_STEP3_ENTER_USERNAME : "Introduceti utilizatorul pentru acces la baza de date",
		INSTALL_STEP3_ENTER_PASSWORD : "Introduceti parola pentru acces la baza de date",
		INSTALL_STEP3_ENTER_DBNAME : "Introduceti numele bazei de date care va fi folosit pentru instalare ( trebuie sa existe )",
		INSTALL_STEP3_CONNECT_FAILED : "Nu s-a putut realiza conectarea la serverul cu baza de date",
		INSTALL_STEP3_DB_FAILED : "Baza de date &1 nu a fost gasita",
		INSTALL_STEP3_MYSQL_VERSION_FAILED : "MySQL versiunea &1 nu este compatibila cu aceasta versiunea de Galaxytool",
		INSTALL_STEP4_URL : "OGame URL",
		OGAME_URL_DETAILS : "Introduceti orice URL vedeti cand va logati in OGame. Bazat pe acel URL Galaxytool va deriva adresa API OGame care care poate fi folosit la completarea datelor Galaxytool fara Galaxytoolbar. Acest API a fost introdus cu versiunea OGame 4.1",
		INSTALL_STEP4_UNIVERSE : "Universul OGame",
		INSTALL_STEP4_DEF_TO_DEBRIS : "Apararea la camp de ramasite",
		INSTALL_STEP4_DEBRIS_RATE : "Debris rate",
		INSTALL_STEP4_SPEED_RATE : "Viteza",
		INSTALL_STEP4_ENTER_UNIVERSE : "Introduceti numele sau numarul universului dumneavoastra OGame .",
		INSTALL_STEP4_UNIVERSE_MISSING : "Trebuie sa definiti universul dumneavoastra",
		INSTALL_STEP4_ENTER_URL : "Introduceti adresa universului dumneavoastra OGame",
		INSTALL_STEP4_URL_MISSING : "Trebuie sa definiti adresa dumneavoastra OGame",
		INSTALL_STEP4_URL_CHECK_FAILED : "Nu s-a putut gasi OGame API la &1",
		INSTALL_STEP4_GETSETTINGS : "Fetch settings",
		INSTALL_STEP5_TOOLNAME : "Nume Galaxytool",
		INSTALL_STEP5_ENTER_TOOLNAME : "Acesta este numele care va fi afisat pe pagina de conectare pentru a va putea identifica Galaxytool-ul",
		INSTALL_STEP5_LANGUAGE : "Limba implicita",
		INSTALL_STEP5_EMAIL_TO : "Email La",
		INSTALL_STEP5_ENTER_EMAIL_TO : "Introduceti adresa de Email unde a-ti dori sa primiti notificari in legatura cu noile inregistrari",
		INSTALL_STEP5_EMAIL_FROM : "Email de la",
		INSTALL_STEP5_ENTER_EMAIL_FROM : "Acest Email este aratat ca RASPUNS pentru toate email-urile trimise de Galaxytool",
		INSTALL_STEP5_USE_PHPMAILER : "Foloseste PHPMailer",
		INSTALL_STEP5_MAXSHOUTS : "Numarul maxim de intrari in shoutboxMaximum number of shoutbox entries",
		INSTALL_STEP5_ENTER_USE_PHPMAILER : "Folositi PHPMailer daca serverul nu suporta trimiterea emailurilor implicit",
		INSTALL_PHPMAILER_HOST : "SMPT Host",
		INSTALL_PHPMAILER_HOST_EXAMPLE : "ex. smtp.provider.com",
		INSTALL_PHPMAILER_USER : "SMPT Utilizator",
		INSTALL_PHPMAILER_USER_EXAMPLE : "ex. user@provider.dcom",
		INSTALL_PHPMAILER_PASS : "SMPT parola",
		INSTALL_PHPMAILER_SECURE : "Metoda de autentificare (ex. ssl)",
		INSTALL_PHPMAILER_PORT : "SMTP Port",
		INSTALL_STEP6_INTRO : "Definiti parola pentru contul <strong>admin</strong> care trebuie sa-l folositi pentru prima conectare la galaxytool dupa instalare.",
		INSTALL_STEP7_CONFIG : "Fisier de configurare creat",
		INSTALL_STEP7_CONFIG_FAILED : "Fisierul de configurare nu a fost creat",
		INSTALL_STEP7_ATTRIBUTES : "Fisierul de atribute creat",
		INSTALL_STEP7_ATTRIBUTES_FAILED : "Fisierul de atribute nu a fost creat",
		INSTALL_STEP7_CREATED_TABLES : "Tabelurile bazei de date create",
		INSTALL_STEP8_INTRO : "A-ti instalat cu succes Galaxytool!",
		INSTALL_STEP8_LOAD_DATA : "Descarcare date OGame...",
		INSTALL_STEP8_LOAD_DATA_FINISHED : "Descarcarea datelor OGame finalizata",
		INSTALL_STEP8_DELETE_FILE : "Acum ar trebui sa stergeti fisierele install.php si update.php de pe serverul dumneavoastra.",
		INSTALL_STEP8_LOGON : "Conectati-va cu utilizatorul <strong>admin</strong> si parola definita mai devreme.",
		UPDATE_START : "Se porneste actualizarea la versiunea &1",
		UPDATE_STEP_DONE : "Terminat",
		UPDATE_TITLE : "Galaxytool actualizare pentru versiune",
		UPDATE_STEP1_WELCOME : "Bun venit la vrajitorul de actualizare Galaxytool. Veti fi ghidat prin actualizarea Galaxytool.",
		UPDATE_STEP1_BACKUP_FILES : "Un prim pas este sa faceti o salvare de tip backup a fisierului  <strong>config</strong> ! Veti fi nevoit sa inlocuiti continutul configurarii in cazul unei erori.",
		UPDATE_STEP1_BACKUP_DB : "Apoi faceti o salvare de tip <a href=\"http://www.ehow.com/how_2036600_create-database-php.html\">backup</a> a bazei de date.",
		UPDATE_STEP1_PROCEED : "Dupa ce salvarile au fost reusite, puteti continua cu actualizarea dumneavoastra.",
		UPDATE_STEP1 : "Bine ai venit",
		UPDATE_STEP2 : "Setari Galaxytool",
		UPDATE_STEP2_OLD_VERSION : "Versiunea precedenta de Galaxytool",
		UPDATE_STEP3 : "Update Galaxytool",
		UPDATE_STEP3_UPDATE_RUNNING : "Actualizarea ruleaza, va rugam asteptati...",
		UPDATE_STEP4 : "Finalizeaza Actualizare",
		UPDATE_STEP4_INTRO : "A-ti actualizat cu succes Galaxytool!",
		UPDATE_STEP4_UPDATE_DONE : "Pasi de actualizare realizati.",
		UPDATE_FAILED : "Actualizarea a esuat.",
		GALAXYTOOL_DUMMY_TEXT : "dummy"
	})
);