define(
	({
		REPORT_WHEN : ":lla",
		RESOURCES_ON : "Resurssit",
		PLAYER_BANNED : "b",
		PLAYER_VACATION_MODE : "v",
		PLAYER_NOOB : "n",
		PLAYER_INACTIVE : "i",
		PLAYER_LONG_INACTIVE : "I",
		PLAYER_OUTLAW : "o",
		L_USERNAME : "Käyttäjänimi",
		L_PASSWORD : "Salasana",
		L_LOGINFAILURE : "Käyttäjänimi tai salasana väärin tai tiliäsi ei ole aktivoitu!",
		L_TOKENFAILURE : "Väärät käyttäjätiedot tai tiliäsi ei ole vielä aktivoitu.",
		L_LOGINTEXT : "Kirjaudu.",
		L_LANGUAGE : "Kielet:",
		L_TIMEOUT : "Yhteys aikakatkaistu!",
		L_REGISTER : "Rekisteröidy",
		L_PWLOST : "Kadonnut salasana",
		INDEX_TITLE : "OGame Galaxytool - Yleiskuva",
		INDEX_INFO : "Tiedot",
		INDEX_ENTRIES : "Aurinkokuntien määrä",
		INDEX_ENTRIES_LASTWEEK : "Alle viikon vanhat aurinkokunnat",
		INDEX_ENTRIES_TO_OLD : "Kuukautta vanhemmat aurinkokunnat",
		INDEX_REGISTERED_USERS : "Rekisteröityneet käyttäjät",
		INDEX_PAGEFORWARD : "Jos selaimesi ei tue sivun uudelleenohjausta, klikkaa tästä.",
		INDEX_NOTICES : "Merkinnät",
		INDEX_PLAYERS : "Pelaajatilastot",
		INDEX_ALLIES : "Liittoumatilastot",
		INDEX_REPORTS : "Vakoiluraportit",
		INDEX_VERSION : "Uusin ladattava versio",
		INDEX_LATEST_VERSION : "Ei uudempaa versiota saatavilla.",
		INDEX_SHOUTBOX : "Hölinäboxi",
		INDEX_NOENTRY : "Ei hölinöitä",
		INDEX_COMMENT : "Hölinäsi",
		INDEX_INSERT : "Lähetä",
		INDEX_UMOD : "Pelaajia lomamuodossa",
		INDEX_NO_MOONS : "Kuita",
		INDEX_NO_EMPTY_SYSTEMS : "Tyhjät aurinkokunnat",
		INDEX_NO_FULL_SYSTEMS : "Täydet aurinkokunnat",
		INDEX_NO_TARGETS : "Mahdollisten kohteiden määrä",
		INDEX_USERINFO : "Käyttäjät",
		INDEX_ONLINE : "Nyt paikalla",
		INDEX_TODAY : "Tänään paikalla",
		INDEX_ALL : "Kirjautumisia kaikkiaan",
		GENERAL_LOAD_FORM : "Avaa tallennettu lomake",
		GENERAL_SAVE_FORM : "Tallenna lomakkeen tiedot",
		GENERAL_SAVE_AS_TEXT : "Tallenna nimellä",
		GENERAL_SAVE : "Tallenna",
		INDEX_USERMANAGEMENT : "Aktivoinnin yleiskatsaus",
		INDEX_NEEDADMIN : "Aktivoitavat tilit",
		INDEX_NEEDEMAIL : "Tarkastamattomat tilit",
		INDEX_TOOLBAR_INFO : "Galaxytoolin lisäosan tiedot",
		INDEX_TOOLBAR_URL : "Galaxytoolin URL",
		INDEX_TOOLBAR_VERSION_REQUIRED : "Vaatii vähintään Galaxytool lisäosan versio",
		INDEX_TOOLBAR_INSTALL_GUIDE : "Asennusohjeet lisäosalle",
		INDEX_TOOLBAR_TOKEN : "Kirjautumisavain",
		INDEX_TOOLBAR_NEW_TOKEN : "Hanki uusi avain",
		INDEX_PLAYERS_WITH_N_PLANETS : "Pelaajat, joilla on enemmän kuin &1 planeettaa",
		INDEX_GETTING_STARTED : "Opas Galaxytoolin käyttöön",
		INDEX_GETTING_STARTED1 : "Tervetuloa Galaxytooliin!",
		INDEX_GETTING_STARTED2 : "Galaxytool auttaa sinua analysoimaan tapahtumia universumissa &1",
		INDEX_GETTING_STARTED3 : "Sinun täytyy syöttää dataa ennen kun voit analysoida sitä. Tätä varten tarvitset lisäosan selaimeesi kuten &1 Firerefoxille.",
		INDEX_GETTING_STARTED4 : "Lisäosan asennuksen jälkeen, selatessasi OGamen sivuja, huomaat aina pienen status-ikkunan, kun tietoa siirtyy Galaxytooliin.",
		INDEX_GETTING_STARTED5 : "Kun lisäosa on lähettänyt tietoa Galaxytooliin, pystyt analysoimaan missä pelaajilla on siirtokuntia, kuinka monta siirtokuntaa heillä on, mitä raportteja heistä löytyy tai mihin aikaan he ovat aktiivisimmillaan.",
		INDEX_GETTING_STARTED6 : "Sinua auttaa myös, kun seuraat omaa kehitystäsi ja vertaat itseäsi vastustajiisi, tai kun analysoit kuinka taisteluraporteista kuinka paljon olet ryöstellyt saaliita viimeisimpien päivien tai viikkojen aikana.",
		INDEX_GETTING_WIKIPAGE : "Galaxytoolissa on myös monia muita ominaisuuksia.",
		INDEX_GETTING_WIKIPAGE2 : "Ota niistä selvää wiki-sivultamme.",
		INDEX_GETTING_BOARD : "Palautteet ja ehdotukset keskustelupastalle:",
		INDEX_GETTING_CHAT1 : "Tai vieraile luonamme chat-huoneessamme:",
		INDEX_GETTING_CHAT2 : "Emme ole paikalla 24/7, mutta käytämme kuitenkin paljon vapaa-aikaamme siellä, joten olkaa kärsivällisiä.",
		INDEX_CLOSE : "Close",
		INDEX_LOGIN : "Login",
		GENERAL_REQUIRED_FIELDS : "Please fill all required fields",
		INDEX_MESSAGES : "Messages",
		INDEX_EXAMPLE : "Example",
		INDEX_INVALID_DATA : "Invalid data",
		GENERAL_COLUMN_HIDE_TITLE : "Manage columns",
		GENERAL_COLUMN_HIDE_INFO : "Please select which columns you want to see in the table.",
		GENERAL_ENTRIES_DELETED : "&1 entries deleted",
		GENERAL_APPLY : "Käytä",
		STARTPAGE_GALAXYTOOL_DESCR : "<em>Galaxytool</em> is a tool for the browser game OGame.",
		GENERAL_OVERWRITE : "Overwrite duplicate entry",
		GENERAL_OVERWRITE_QUESTION : "Overwrite?",
		INDEX_OWN_LOGINS : "Your logins",
		GENERAL_OPEN_IN_NEW_WINDOW : "Koppeling openen in nieuw venster",
		GENERAL_UNIT_OF_MEASURE_DAYS : "Days",
		PROGRAM_NAME : "OGame Galaxytool",
		SHORTNAME : "Galaxytool",
		BACK_INDEX : "Takaisin pääsivulle",
		UNIVERSE : "Universumi",
		MENU_INFO_LINKS : "Informaatio",
		MENU_PAGE : "Yleiskuva",
		MENU_DB_SEARCH : "Etsi tietokannasta",
		MENU_DB_NOTICES : "Etsi merkinnöistä",
		MENU_DB_REPORTS : "Etsi raporteista",
		MENU_GALAXYVIEW : "Näytä galaksi",
		MENU_STATISTICS : "Tilastot",
		MENU_ALLYHISTORY : "Historia",
		MENU_FLEET_MOVEMENTS : "Laivueliikenteet",
		MENU_COMBAT_REPORTS : "Taisteluraportit",
		MENU_MESSAGES : "Pelin sisäiset viestit",
		MENU_OPTION_LINKS : "Työkalut",
		MENU_DB_REFRESH : "Lisää tietokantaan",
		MENU_NOTICES : "Huomiot",
		MENU_DB_STATUS : "Tietokannan tila",
		MENU_USEROPTIONS : "Käyttäjien hallinta",
		MENU_USEROPTIONS2 : "Käyttäjän asetukset",
		MENU_USEROPTIONS3 : "Käyttäjätiedot",
		MENU_ADMIN : "Pääkäyttäjä",
		MENU_LOGOUT : "Kirjaudu ulos",
		MENU_STUFF : "Linkit",
		MENU_FORUM_THREAD : "Developer forum",
		MENU_DOWNLOADPAGE : "Download page",
		MENU_LANGUAGE : "Kieli",
		MENU_HELP : "Help!",
		MENU_TOOLOPTIONS : "Galaxytool asetukset",
		PARSER_INFO1 : " lisättiin tietokantaan",
		PARSER_ERROR1 : "Virhe yritettäessä lisätä seuraavia koordinaatteja:",
		PARSER_ERROR2 : "Tietokantaa ei löydetty!",
		PARSER_ERROR3 : "Tietokantaserveriä ei löydy!",
		PARSER_WRONG_UNIVERSE : "Väärä universumi - nykyinen: \"&1\" odotettu: \"&2\"",
		SHOW_TITLE : "OGame Galaxytool - Etsintäsivu",
		SHOW_SEARCH : "Etsi tietokannasta",
		SHOW_ALLYSYMBOL : "Liittouma",
		SHOW_PLAYERNAME : "Pelaajan nimi",
		SHOW_MOONS : "Ainoastaan planeetat missä kuu",
		SHOW_NOTICES : "Ainoastaan planeetat missä huomioita",
		SHOW_COLONIES : "Kolonisaation paikkoja",
		SHOW_YES : "Kyllä",
		SHOW_NO : "Ei",
		SHOW_SEARCHRANGE : "Väliltä",
		SHOW_SEARCH_IN : "Etsi galaksista",
		SHOW_FROM_SYSTEM : "Aurinkokunta",
		SHOW_FROM_PLANET : "Planeetta paikasta",
		SHOW_TO : "-",
		SHOW_DESCRIPTION : "Muuttujat ovat sallittuja. Täytä vain ne kentät, jotka näet tarpeelliseksi.",
		SHOW_SORT_BY : "Järjestä",
		SHOW_GALASYSTEM : "Aurinkokunta",
		SHOW_ALLYNAME : "Liittouman nimi",
		SHOW_SEARCHBUTTON : "Etsi",
		SHOW_ADDRESS : "Koordinaatit",
		SHOW_ALLYSORT : "Liittouma",
		SHOW_PLANET : "Planeetta",
		SHOW_STATUS : "Status",
		SHOW_CURRENTNESS : "Päivitetty",
		SHOW_PLAYER_STATUS : "Pelaajan status",
		SHOW_PLAYER_STATUS1 : "kaikki",
		SHOW_PLAYER_STATUS2 : "mahdolliset kohteet",
		SHOW_PLAYER_STATUS3 : "inaktiivinen",
		SHOW_HITS : "Löydetyt",
		SHOW_OF : ",",
		SHOW_ASC : "nouseva",
		SHOW_DESC : "laskeva",
		SHOW_RESULTS : "Tuloksia sivulla",
		SHOW_MOON : "Kuu",
		SHOW_UKMOONSIZE : "tuntematon",
		SHOW_DF : "RK",
		SHOW_DF_LONG : "Rauniokenttä",
		SHOW_METAL : "M",
		SHOW_METAL_LONG : "Metalli",
		SHOW_CRYSTAL : "K",
		SHOW_CRYSTAL_LONG : "Kristalli",
		SHOW_BOTH : "Molemmat yhdessä",
		SHOW_AT_LEAST : "(vähintään)",
		SHOW_DATE : "Päiväys",
		SHOW_DATE_0 : "ei haussa",
		SHOW_DATE_1 : "vanhempi kuin",
		SHOW_DATE_2 : "uudempi kuin",
		SHOW_RANK : "Arvoasteikko",
		SHOW_FRANK : "Laivueen arvo",
		SHOW_MEMBERS : "Jäsenet",
		SHOW_NOTRANKED : "Ei tietoa saatavilla",
		SHOW_NOTICERES : "Huomiot",
		SHOW_REPORTS : "Ainoastaan planeetat joissa raportteja",
		SHOW_REPORTS_SHORT : "Raportit",
		SHOW_NOTHING : "Ei löytynyt mitään",
		SHOW_ALLIANCE_STATUS : "Liittouman status",
		SHOW_NO_STATUS : "ei statusta",
		SHOW_NAP : "Ei saa hyökätä",
		SHOW_ALLIED : "Liitossa",
		SHOW_WAR : "SOTA",
		SHOW_BOYCOTT : "Boikotissa",
		SHOW_NEUTRAL : "Neutraali",
		SHOW_OWN : "Oma liittouma",
		SHOW_WING : "Siipi",
		SHOW_EXT_OPTIONS1 : "Lisää hakuvaihtoehtoja: kantama, arvo, päiväys ja rauniokenttä.",
		SHOW_EXT_OPTIONS2 : "Lisää hakuvaihtoehtoja: siirtokunnat, kuut, raportit, huomiot, pelaaja- ja diplomatiastatukset.",
		SHOW_EXT_OPTIONS3 : "Lisää vaihtoehtoja hakutulosten järjestämiseen.",
		SHOW_EXTENDED : "advanced search",
		SHOW_MOON_SELECTION : "Planet with moon",
		SHOW_REPORT_SELECTION : "Planet with report",
		SHOW_FILTER_BY : "Exclude from the list",
		SHOW_FILTER_NONE : "ei yhtään",
		SHOW_PLAYERS_WITHOUT_PROGRESS : "Show players without score changes within the last few days",
		STATUS_TITLE : "OGame Galaxytool - Status-sivu",
		STATUS_DB_STATUS : "Tietokannan tila ",
		STATUS_COLOR : "Väri ",
		STATUS_AGE1 : "Lisäys 1 vrk vanha.",
		STATUS_AGE2 : "Lisäys 2 - 4 vrk vanha.",
		STATUS_AGE3 : "Lisäys 4 - 7 vrk vanha.",
		STATUS_AGE4 : "Lisäys 1 - 2 viikkoa vanha.",
		STATUS_AGE5 : "Lisäys 2 - 4 viikkoa vanha.",
		STATUS_AGE6 : "Lisäys vanhempi kuin 1 kuukauden!",
		STATUS_AGE7 : "Ei saatavilla olevaa tietoa.",
		STATUS_ON : "päivitti",
		STYLES_COLOR1 : "Color1",
		STYLES_COLOR2 : "Color2",
		STYLES_COLOR3 : "Color3",
		STYLES_COLOR4 : "Color4",
		STYLES_COLOR5 : "Color5",
		STYLES_COLOR6 : "Color6",
		STYLES_COLOR7 : "Color7",
		STATUS_DB_LEGEND : "Värien merkitys",
		STATUS_GALAXY : "Galaksin yleiskatsaus",
		USER_TITLE : "Käyttäjien hallinta",
		USER_NAMES : "Käyttäjä",
		USER_ERROR : "Virhe",
		USER_NEWUSER : "Uusi käyttäjä",
		USER_OPTIONS : "Asetukset",
		USER_USERNAME : "Käyttäjänimi",
		USER_PASSWORD : "Salasana",
		USER_PASSWORD_CONFIRM : "Salasanan varmistus",
		USER_GALAXY : "Galaksi",
		USER_SEARCH : "Etsi",
		USER_INSERT : "Lisää",
		USER_DELETE : "Poista",
		USER_DELETE_ENTRY : "Haluatko poistaa käyttäjän?: ",
		USER_STATUS : "Näytä tiedot",
		USER_STYLES : "Muunna ulkoasua",
		USER_SUBMIT : "Tallenna",
		USER_RESET : "Peruuta",
		USER_YES : "Kyllä",
		USER_NO : "Ei",
		USER_STYLEPATH : "Ulkoasu \"styles.css\"",
		USER_PROBES : "Näytä/Lisää vakoiluraportteja",
		USER_EMAIL : "Sähköposti",
		USER_ERROR1 : "Salasana tai sähköpostiosoite väärin.",
		USER_ERROR2 : "Väärä sähköpostiosoite.",
		USER_INGAME : "Nimi pelissä",
		USER_ALLYTAG : "Liittouma",
		USER_ALLYHISTORY : "Historianäkymä",
		USER_DIPLOMATIC : "Vaihda diplomaatti-statusta",
		USER_STATSPAGE : "Lisäysten määrä tilastosivulla",
		USER_LINKS : "Linkit",
		USER_LINKS2 : "Muoto:<br>teksti;url<br>teksti2;url2<br>teksti3;url3",
		USER_EXPORT_TITLE : "Värit (BB Codes)",
		USER_BB_COORDINATES : "Koordinaatit",
		USER_BB_MOON : "Kuu",
		USER_BB_DEBRIS : "Romukenttä",
		USER_BB_ALLY : "Liitouman nimi",
		USER_BB_ALLYDETAILS : "Liittouman lisätiedot",
		USER_BB_PLAYERNAME : "Pelaaja",
		USER_BB_BANNED : "Estetty",
		USER_BB_VACATION : "Lomamuoto",
		USER_BB_NOOB : "(Heikompi pelaaja)",
		USER_BB_INACTIVE : "7 päivää inaktiivinen",
		USER_BB_LONGINACTIVE : "28 päivää inaktiivinen",
		USER_DELETION : "Poista",
		USER_FLEETINFO : "Laivueliikenteet",
		USER_ACTIVITIES : "Pelaajan aktiivisuus",
		USER_MAINTENANCE : "Galaxytoolin huolto",
		USER_MANAGEMENT : "Käyttäjien hallinta",
		USER_DELETE_MY_COMBAT_REPORTS : "Poista omat taisteluraportit",
		USER_DELETE_MY_MESSAGES : "Poista omat viestit",
		USER_DELETE_MY_FLEETMOVES : "Poista omat laivueliikenteet",
		USER_DELETE_MY_COMBAT_REPORTS_LIMITED : "Poista taisteluraportit, jotka ovat vanhempia kuin &1 päivää",
		USER_DELETE_MY_MESSAGES_LIMITED : "Poista viestit, jotka ovat vanhempia kuin &1 päivää",
		USER_TABLE_ENTRIES : "Hakutulosten määrä per sivu",
		USER_EXISTS : "User already exists",
		USER_BB_OUTLAW : "Outlaw",
		USER_INVALID_URL : "URL &1 seems to be invalid - URL will be ignored",
		VIEW_TITLE : "OGame Galaxytool - Galaksi",
		VIEW_NODATA : "Ei tietoa saatavilla!",
		VIEW_GALAXY : "Galaksi",
		VIEW_SYSTEM : "Aurinkokunta",
		VIEW_POSITION : "Paikka",
		VIEW_PLANET : "Planeetta",
		VIEW_MOON : "Kuu",
		VIEW_TF : "RK",
		VIEW_PLAYER : "Pelaaja",
		VIEW_PLAYER_ADD : "(Status)",
		VIEW_ALLY : "Liittouma",
		VIEW_ALLY_ADD : "(Arvoasteikko / Jäseniä)",
		VIEW_METAL : "M",
		VIEW_CRYSTAL : "K",
		VIEW_COLONISED : "planeettaa vallattu",
		VIEW_UKMOONSIZE : "ei tiedossa",
		VIEW_BACK : "Takaisin",
		VIEW_NOTICE : "Merkinnät",
		VIEW_REPORTS : "Raportit",
		VIEW_MOONPHALANX : "Kuut, jotka voivat skannata tämän aurinkokunnan",
		VIEW_NOMOONS : "Kuita ei löydetty",
		VIEW_IRAKS : "Planeetat, joista voidaan ampua ohjuksia tähän aurinkokuntaan",
		VIEW_NOIRAKS : "Ohjuksia ei löydetty",
		VIEW_MOON_DESTROY_CHANCE : "Mahdollisuus tuhota kuu",
		VIEW_CHANCE_WITH_ONE : "Mahdollisuus yhdellä RIP:llä",
		VIEW_CHANCE_WITH_N : "Mahdollisuus ",
		VIEW_DEATH_STARS : ":lla RIP:llä",
		VIEW_DS_DESTROY_CHANCE : "Mahdollisuus menettää RIP ",
		VIEW_TOP : "Ylös",
		VIEW_GO : "Siirry",
		VIEW_DIAMETER : "Diameter",
		PW_TITLE : "OGame Galaxytool - vaihda salasana",
		OLD_PASSWORD : "Vanha salasana",
		NEW_PASSWORD : "Uusi salasana",
		CONFIRM_NEW_PASSWORD : "Vahvista uusi salasana",
		PW_MISMATCH : "Salasanat eivät olleet samoja",
		PW_ERROR : "Vanha salasana oli väärin!",
		UPDATE_DONE : "Vaihto onnistui",
		TIMEZONE_OFFSET : "Aikaero palvelimeen",
		DELETE_ACCOUNT : "Poista tämä käyttäjä",
		DELETE_ACCOUNT_SAFETY_REQUEST : "Haluatko varmasti poistaa Galaxytool käyttäjän?",
		CH_PASSWD_AUTHORIZATION : "Oikeudet",
		CH_PASSWD_ADMIN : "Pääkäyttäjä",
		TIMEZONE_OGAME_OFFSET : "Aikahyöhykkeen poikkeama OGame palvelimeen",
		CH_PASSWD_USER_LANGUAGE : "Vaihda tähän kieleen kirjautumisen jälkeen",
		CH_PASSWD_USER_LANGUAGE_NO_CHANGE : "Ei vaihtoa",
		CH_PASSWD_EXPAND : "Laajennettu",
		CH_PASSWD_COLLAPSE : "Supistettu",
		CH_PASSWD_HIDDEN : "Piilotettu",
		CH_PASSWD_GETTING_STARTED : "Näytä Galaxytoolin opas kirjautumisen jälkeen",
		CH_PASSWD_PLUGIN : "Näytä lisäosan tiedot kirjautumisen jälkeen",
		NOTICE_TITLE : "OGame Galaxytool - Merkinnät",
		NOTICE_HEADER : "editoi merkintöjä",
		NOTICE_HEADER2 : "Editoi omaa merkintää",
		NOTICE_PUBLIC : "Muiden käyttäjien muokattavissa?",
		NOTICE_YES : "Kyllä",
		NOTICE_NO : "Ei",
		NOTICE_TEXT : "Teksti",
		NOTICE_SAVE : "Tallenna",
		NOTICE_DELETED : "Teksti poistettu",
		NOTICE_SAVED : "Teksti tallennettu.",
		NOTICE_RESULTS : "Kaikki tulokset",
		NOTICE_USER : "Käyttäjä",
		NOTICE_DATE : "Päivämäärä",
		NOTICE_EDIT : "Editoi",
		NOTICE_DELETE : "Poista",
		NOTICE_NEW : "Lisää oma merkintä",
		NOTICE_NOTPUBLIC : "Merkintä ei muiden saatavilla.",
		NOTICE_ALL : "kaikki",
		NOTICE_NONE : "ei yhtään",
		NOTICE_SEARCH : "Etsi merkinnöistä",
		NOTICE_SEARCH_SHORT : "Etsi",
		NOTICE_HITS : "Löydettyjä",
		NOTICE_SHOWRESULTS : "Listaa sivulle",
		NOTICE_OF : ",",
		NOTICE_NOTHING : "Ei merkintöjä",
		NOTICE_CHARS : "Merkit",
		NOTICE_PLAYERNAME : "Pelaaja",
		NOTICE_SHOWALL : "näytä kaikki merkinnät",
		REPORTS_TITLE : "OGame Galaxytool - Vakoiluraportit",
		REPORTS_RESOURCES : "Resurssit",
		REPORTS_FLEET : "Laivueet",
		REPORTS_DEFENCE : "Puolustus",
		REPORTS_BUILDINGS : "Rakennukset",
		REPORTS_TECHNOLOGY : "Tutkimus",
		REPORTS_MOON : "Kuu",
		REPORTS_SEARCH : "Etsi vakoiluraporteista",
		REPORTS_SEARCH_SHORT : "Etsi",
		REPORTS_HITS : "Löydetyt",
		REPORTS_NOTHING : "Ei löytynyt mitään",
		REPORTS_ADDRESS : "Osoite",
		REPORTS_CURRENTNESS : "Päivitetty",
		REPORTS_PLAYERNAME : "Pelaaja",
		REPORTS_ALLY : "Liitto",
		REPORTS_VIEW : "Näytä raportti",
		REPORTS_SEARCH_IN : "Etsi galaksista",
		REPORTS_FROM_SYSTEM : "Aurinkokunta",
		REPORTS_TO : "-",
		REPORTS_DELETE : "Poista",
		REPORTS_DELETED : "Poistettu",
		REPORTS_RESULTS : "Tuloksia sivulla",
		REPORTS_OF : ",",
		REPORTS_DATE : "Päivämäärä",
		REPORTS_DATE_0 : "älä huomioi",
		REPORTS_DATE_1 : "Vanhempi kuin",
		REPORTS_DATE_2 : "Uudempi kuin",
		REPORTS_NOTICES : "Merkinnät",
		REPORTS_AT_LEAST_RESOURCES : "Resursseja (vähintään)",
		REPORTS_SEARCH_EXTENDED : "Laajennettu haku",
		REPORTS_FLEET_RESIS : "Laivueen arvo",
		REPORTS_DEFENCE_RESIS : "Puolustuksen arvo",
		REPORTS_ALL_RESIS : "Arvo yhteens&auml;",
		REPORTS_TECHS : "Tutkimus",
		REPORTS_UNKNOWN_ENTRIES : "Tuntematon tietue",
		REPORTS_PARTLY_INSERTED : "Osittain lisätty",
		REPORTS_FOR_ALL_RES : "Kaikkien resurssien ryöstö",
		REPORTS_FOR_TF : "Romukenttä",
		REPORTS_KT : "Pienet Rahtialukset",
		REPORTS_GT : "Suuret Rahtialukset",
		REPORTS_SS : "Taistelualukset",
		REPORTS_REC : "Kierrättäjä",
		REPORTS_RAIDABLE : "Ainoastaan raidattavat kohteet",
		REPORTS_ALL_RESOURCES : "Kaikki resurssit",
		REPORTS_STUFF : "Muut",
		REPORTS_SPEEDSIM : "Simuloi SpeedSimillä",
		REPORTS_DRAGOSIM : "Simuloi Dragosim",
		REPORTS_STATUS : "Status",
		REPORTS_ERROR : "Virhe",
		REPORTS_OWN_REPORTS : "Ainoastaan omat raportit",
		REPORTS_UPLOAD_BY : "Raportin lähetti",
		REPORTS_DEPTH : "Raportin laajuus",
		REPORTS_FLEET_SCORE : "Laivueiden määrä",
		REPORTS_DEFENCE_SCORE : "Puolustuksen määrä",
		REPORTS_HOURS : "hours",
		REPORTS_MAX_RESULTS_HIT : "Your query returned more than &1 hits. Only the first &1 results are show. Please adjust your search request to get less results.",
		REPORTS_OSIMULATE : "Simulate with OSimulate",
		REPORTS_SHOW_ONLY : "Show only",
		REPORTS_SHOW_PLANETS : "Planeetat",
		REPORTS_SHOW_MOONS : "Kuut",
		REPORTS_OWNER : "Reports owned by",
		STATS_TITLE : "OGame Galaxytool - Tilastot",
		STATS_TBLHEAD : "Tilastot",
		STATS_RANK : "Arvoasteikko",
		STATS_PLAYERNAME : "Pelaaja",
		STATS_ALLYNAME : "Liittouma",
		STATS_SCORE : "Pisteet",
		STATS_FLEET : "Laivue",
		STATS_RESEARCH : "Tutkimus",
		STATS_MEMBERS : "Jäsenet",
		STATS_STATUS : "Status",
		STATS_NOTHING : "Ei statusta",
		STATS_NAP : "Ei saa hyökätä",
		STATS_ALLIED : "Liitossa",
		STATS_WAR : "Sodassa",
		STATS_BOYCOTT : "Boikotissa",
		STATS_NEUTRAL : "Neutraali",
		STATS_OWN : "Oma liitto",
		STATS_WING : "Siipi",
		STATS_UPDATE : "Lisätty",
		STATS_PLAYERSTATS : "Pelaajatilastot",
		STATS_ALLYSTATS : "Liittoumatilastot",
		STATS_DELETE : "Haluatko poistaa tämän lisäyksen?",
		STATS_CONFIRM_DELETE : "Haluatko VARMASTI poistaa tämän lisäyksen?",
		STATS_CHANGE_PLAYER_STATUS : "Pelaajan status",
		STATS_CHANGE_ALLIANCE_STATUS : "Liittouman status",
		STATS_CHANGE_ALLIANCE_STATUS_HINT : "Kaikki tämän liiton jäsenet saavat tämän statuksen. Kaikki edelliset statukset korvataan.",
		STATS_UNKNOWN : "Loput",
		STATS_DETAILS : "Lisätiedot",
		STATS_PLAYERSTATUS : "Pelaajan status",
		STATS_IGNORE_STATUS : "kaikki",
		STATS_ACTIVE : "aktiivinen",
		STATS_INACTIVE : "7 päivää inaktiivinen",
		STATS_BANNED : "Estetty",
		STATS_VACATION : "Lomamuoto",
		STATS_NOOB : "(Heikompi pelaaja)",
		STATS_YES : "Kyllä",
		STATS_NO : "Ainoastaan planeetat missä huomioita",
		STATS_SEARCH : "Etsi",
		STATS_SHOW_GRAPH : "Näytä tiedot pisteiden jakautumiseen",
		STATS_LONG_INACTIVE : "28 päivää inaktiivinen",
		STATS_STANDARD : "Pisteet",
		STATS_MILITARY : "Sotilaspisteet",
		STATS_ECONOMY : "Taloudellisuus",
		STATS_HONOUR : "Kunniapisteet",
		STATS_MILITARY_BUILD : "Sotilaspisteiden rakentuminen",
		STATS_MILITARY_DESTROYED : "Sotilaspisteiden tuhoaminen",
		STATS_MILITARY_LOST : "Sotilaspisteiden häviäminen",
		REGISTER_REGISTRATE : "Rekisteröidy",
		REGISTER_LOGINNAME : "Käyttäjänimi",
		REGISTER_PASSWORD : "Salasana",
		REGISTER_PASSWORD_CONFIRM : "Varmista salasana",
		REGISTER_EMAIL : "Email",
		REGISTER_INGAME : "Pelinimi",
		REGISTER_ALLYTAG : "Liittouma",
		REGISTER_EMAILVERIFICATION : "Galaxytool - rekisteröinti",
		REGISTER_EMAILTEXT : "Varmista rekisteröinti käymällä seuraavassa osoitteessa:",
		REGISTER_ERROR1 : "käyttäjänimi jo varattu",
		REGISTER_ERROR2 : "Virhe sähköpostin lähetyksessä. Ota yhteys adminiin.",
		REGISTER_ERROR3 : "Virhe tietojen tallennuksessa tietokantaan!",
		REGISTER_INFO1 : "Tilisi on luotu.",
		REGISTER_INFO2 : "Aktivoi tilisi sähköpostistasi löytyvällä linkillä.",
		REGISTER_INFO3 : "Rekisteröinti on varmistettu. Adminin täytyy vielä hyväksyä se ennen kun saat sen käyttöösi.",
		REGISTER_BUTTON : "Takaisin aloitussivulle",
		REGISTER_NEW_SUBJECT : "Uusi käyttäjä on rekisteröitynyt",
		REGISTER_NEW_MAILTEXT : "Uusi käyttäjä on rekisteröitynyt.",
		REGISTER_BACK : "Takaisin edelliselle sivulle",
		REGISTER_MISSING_FIELDS : "Täytä kaikki kentät",
		REGISTER_ERROR4 : "Sähköpostia ei ole tarkistettu.",
		REGISTER_ERROR5 : "Salasanat eivät ole samat.",
		REGISTER_PWS : "Salasanan vahvuus",
		REGISTER_PWS0 : "erittäin heikko",
		REGISTER_PWS1 : "heikko",
		REGISTER_PWS2 : "hyvä",
		REGISTER_PWS3 : "vahva",
		REGISTER_PWS4 : "erittäin vahva",
		REGISTER_EMAIL_USED : "Email Address is already used",
		LOSTPW_TITLE : "Kadotin salasanani",
		LOSTPW_INFO2 : "Uusi salasana luotu ja lähetetty sähköpostiisi.",
		LOSTPW_BUTTON1 : "Uusi salasana",
		LOSTPW_BUTTON2 : "Takaisin pääsivulle",
		LOSTPW_LOGINNAME : "Login-Name",
		LOSTPW_EMAIL : "Email",
		LOSTPW_ERROR1 : "Virhe tiedon tallentamisessa tietokantaan!",
		LOSTPW_ERROR2 : "Haettuja käyttäjätietoja ei löydy!",
		LOSTPW_ERROR3 : "Virhe sähköpostin lähettämisessä. Ota yhteys adminiin.",
		LOSTPW_EMAIL_SUBJECT : "Tilaamasi salasana",
		LOSTPW_EMAIL_TEXT1 : "Tässä on uusi salasanasi Galaxytooliin",
		LOSTPW_EMAIL_TEXT2 : "Käyttäjänimi",
		LOSTPW_EMAIL_TEXT3 : "Salasana",
		LOSTPW_INFO1 : "You will receive an email to verify your password reset request.",
		LOSTPW_CONFIRM_RESET_SUBJECT : "Lost password?",
		LOSTPW_CONFIRM_RESET_MESSAGE : "Hello,\n\nyou requested a password reset for the Galaxytool. To generate a new password, click the following link:",
		USERINFO_TITLE : "OGame Galaxytool - Käyttäjätiedot",
		USERINFO_NAMES : "Kaikki käyttäjät tässä työkalussa",
		USERINFO_DETAIL : "tarkempi informaatio",
		USERINFO_ERROR1 : "Ei tunnettua käyttäjää tällä tunnuksella!",
		USERINFO_USERNAME : "Käyttäjänimi",
		USERINFO_INGAME : "Nimi pelissä",
		USERINFO_EMAIL : "Email",
		USERINFO_ALLYTAG : "Liittouma",
		USERINFO_STYLEPATH : "Ulkoasu",
		USERINFO_STATUS : "Status",
		USERINFO_ACTIVATE : "Aktivoi pelaaja",
		USERINFO_LOGINS : "Kirjautumisten määrä",
		USERINFO_LASTLOGIN : "Viimeisin kirjautuminen",
		USERINFO_DATA : "Informaatio lisätyistä aurinkokunnista",
		USERINFO_NODATA : "Tämä käyttäjä ei ole vielä lisännyt aurinkokuntia",
		USERINFO_GALAXY : "Galaksi",
		USERINFO_SYSTEMS : "Aurinkokuntien määrä",
		USERINFO_IP : "IP-osoite",
		USERINFO_LOGINTIME : "Kirjautuneena",
		USERINFO_NOLOGIN : "Pelaaja ei ole koskaan kirjautunut!",
		USERINFO_LAST_GALAXYUPDATE : "Viimeksi lisätty galaksinäkymä",
		USERINFO_LAST_PUBLIC_NOTICE : "Viimeisin yleinen merkintä",
		USERINFO_LAST_PRIVATE_NOTICE : "Viimeisin yksityinen merkintä",
		USERINFO_NUMBEROF_PUBLIC_NOTICE : "Yleisten merkintöjen määrä",
		USERINFO_NUMBEROF_PRIVATE_NOTICE : "Yksityisten merkintöjen määrä",
		USERINFO_ACTIVATED : "Tili aktivoitu",
		USERINFO_ACTIVATIONTEXT : "Galaxytoolin admin on aktivoinut tunnuksesi.\n\nPidä hauskaa Galaxytoolilla!",
		USERINFO_LAST_SUBMIT : "Viimeisin syöttö",
		ALLYHISTORY_TITLE : "OGame Galaxytool - Historia",
		ALLYHISTORY_TBLHEAD : "Historia",
		ALLYHISTORY_PLAYERNAME : "Pelaaja",
		ALLYHISTORY_ALLYNAME : "Liittouma",
		ALLYHISTORY_LASTMONTH : "Viime kuussa",
		ALLYHISTORY_ALL_DATA : "Kaikki saatava tieto",
		ALLYHISTORY_SHOW : "Luo historia",
		ALLYHISTORY_TIMESPAN : "Aikaväli",
		ALLYHISTORY_PROGESS : "Kehitys",
		ALLYHISTORY_SCORE : "Pisteet",
		ALLYHISTORY_FSCORE : "Laivuepisteet",
		ALLYHISTORY_RSCORE : "Tutkimuspisteet",
		ALLYHISTORY_MEMBER : "Jäsenet",
		ALLYHISTORY_NOTHING : "Tietoja ei löytynyt",
		ALLYHISTORY_DETAILS : "Lisätiedot",
		ALLYHISTORY_SHOW_ADDRESS : "Koordinaatit",
		ALLYHISTORY_ESCORE : "Taloudellisuus",
		ALLYHISTORY_MSCORE : "Sotilaspisteet",
		DETAILEDINFO_PLAYERINFO_TITLE : "Pelaajatiedot",
		DETAILEDINFO_ALLYINFO_TITLE : "Liittoumatiedot",
		DETAILEDINFO_PLAYERINFO_TBLHEAD : "Lisätiedot pelaajasta",
		DETAILEDINFO_ALLYINFO_TBLHEAD : "Lisätiedot liittoumasta",
		DETAILEDINFO_NO_ALLIANCE : "ei liittoumaa",
		DETAILEDINFO_SCORE : "Pistetilastot",
		DETAILEDINFO_FLEET : "Laivuetilastot",
		DETAILEDINFO_RESEARCH : "Tutkimustilastot",
		DETAILEDINFO_RANK : "Arvoasteikko",
		DETAILEDINFO_POINTS : "Pisteet",
		DETAILEDINFO_KNOWN_PLANETS : "Tiedossa olevat planeetat",
		DETAILEDINFO_MOONS : "Tiedossa olevat kuut",
		DETAILEDINFO_PHALANX_AREA : "Sensorialue",
		DETAILEDINFO_NO_PHALANX_AREA : "Sensoriryhmittymää ei löydetty",
		DETAILEDINFO_NOTICES : "Merkinnät",
		DETAILEDINFO_NO_NOTICES : "Ei löydettyjä merkintojä",
		DETAILEDINFO_PREVIOUS_ALLIANCES : "Edellinen liittouma",
		DETAILEDINFO_RESOURCES_PER_HOUR : "Resursseja tunnissa",
		DETAILEDINFO_RESOURCES_PER_DAY : "Resursseja vuorokaudessa",
		DETAILEDINFO_RESOURCES_PER_WEEK : "Resursseja viikossa",
		DETAILEDINFO_RESOURCES_PER_MONTH : "Resursseja kuukaudessa",
		DETAILEDINFO_METAL : "Metalli",
		DETAILEDINFO_CRYSTAL : "Kristalli",
		DETAILEDINFO_DEUTERIUM : "Deuterium",
		DETAILEDINFO_UNKNOWN : "Tuntematon",
		DETAILEDINFO_SCORE_DISTRIBUTION : "Pisteiden julkaisu",
		DETAILEDINFO_GENERAL : "Lisätiedot",
		DETAILEDINFO_MEMBERS : "Jäsenet",
		DETAILEDINFO_GRAPHS : "Kuvaajat",
		DETAILEDINFO_RESOURCES : "Resurssit",
		DETAILEDINFO_FLEET_TAB : "Alukset",
		DETAILEDINFO_TECH : "Tutkimus",
		DETAILEDINFO_FLEET_DETAIL : "Yhteens&auml; / (pelaajan keskiarvo) kaikista saatavista raporteista",
		DETAILEDINFO_TECH_DETAIL : "Keskiarvo kaikista saatavilla olevasta pelaajatiedoista",
		DETAILEDINFO_PLANET_TAB : "Planeetat",
		DETAILEDINFO_MOON_TAB : "Kuut",
		DETAILEDINFO_ACTIVITIES : "Aktiivisuus",
		DETAILEDINFO_NODATA : "Ei tietoa saatavilla!",
		DETAILEDINFO_ACTIVITY_DESCRIPTION : "Näytä aktiivisuus &1 ajalta:",
		DETAILEDINFO_GALAXYVIEWS : "Galaksinäkymät",
		DETAILEDINFO_SCANS : "Vakoilutoiminnat",
		DETAILEDINFO_MESSAGES : "Viestit",
		DETAILEDINFO_COMBATS : "Taisteluraportit",
		DETAILEDINFO_ALLYPAGE : "Liittouman yleisnäkymä",
		DETAILEDINFO_MANUAL : "Manuaalinen syöttö",
		DETAILEDINFO_START : "Aloitus",
		DETAILEDINFO_TO : "",
		DETAILEDINFO_TODAY : "Lopetus",
		DETAILEDINFO_DATA_RESTRICTION : "Rajoitettu:",
		DETAILEDINFO_WEEKDAY_WEEKEND : "Viikonloppu",
		DETAILEDINFO_WEEKDAY_WORKINGDAY : "Arkipäivä",
		DETAILEDINFO_WEEKDAY_MONDAY : "Maanantai",
		DETAILEDINFO_WEEKDAY_TUESDAY : "Tiistai",
		DETAILEDINFO_WEEKDAY_WEDNESDAY : "Keskiviikko",
		DETAILEDINFO_WEEKDAY_THURSDAY : "Torstai",
		DETAILEDINFO_WEEKDAY_FRIDAY : "Perjantai",
		DETAILEDINFO_WEEKDAY_SATURDAY : "Lauantai",
		DETAILEDINFO_WEEKDAY_SUNDAY : "Sunnuntai",
		DETAILEDINFO_WEEKDAY_SHORTLENGTH : 2,
		DETAILEDINFO_PLAYER_CURRENTLY_ACTIVE : "Pelaaja on tällä hetkellä aktiivinen",
		DETAILEDINFO_PLAYER_MESSAGES : "saatavilla olevat pelaajan viestit",
		DETAILEDINFO_SHOW : "näytä",
		DETAILEDINFO_NONE : "ei saatavilla",
		DETAILEDINFO_ENTER_MANUALLY : "Syötä aktiivisuus pelaajalle",
		DETAILEDINFO_PLAYER_SEEN_ON : "Pelaaja oli aktiivinen",
		DETAILEDINFO_INSERT : "Syötä",
		DETAILEDINFO_OGAME_SERVERTIMES : "Huomio: Kaikki päiväykset ja ajat viittaavat OGamen palvelimen aikoihin!",
		DETAILEDINFO_DAY_VIEW : "päivittäinen näkymä",
		DETAILEDINFO_WEEK_VIEW : "viikottainen näkymä",
		DETAILEDINFO_HOME_PLANET : "Kotimaailma",
		DETAILEDINFO_PLANETNAME : "Name",
		DETAILEDINFO_DEFENCE_SCORE : "Defence score",
		DETAILEDINFO_DEFENCE_SCORE_TOOLTIP : "Defence score = Fleet - Score + Research + Economy.<br/>All those statistics must be up to date to have a meaningful result!",
		DETAILEDINFO_SCORE_PER_SHIP : "Scores per ship",
		DETAILEDINFO_SHIPS : "Number of ships",
		DETAILEDINFO_DATE_IN_FUTURE : "Do not maintain times which are not in the past.",
		ADMIN_TITLE : "Galaxytoolin hallinta",
		ADMIN_DISCLAMER : "Huom! Skriptien suoritus omalla vastuulla. Suurin osa poistaa tietoa tietokannasta.",
		ADMIN_INCONSISTENCIES : "Ristiriidat tietokannassa",
		ADMIN_PLANETS : "Poista planeetat sijainnissa 0 tai suuremmassa kuin 15",
		ADMIN_GALAXIES : "Poista yli &1 olevat galaksit",
		ADMIN_PLAYERS : "Poista pelaajat ilman OGamen playerid:tä - aiheuttaa päällekkäisyyksiä pelaajatiedoissa",
		ADMIN_REPORTS : "Poista raportit sijainneista, joissa ei ole enää planeettaa",
		ADMIN_MISC : "Sekalaiset",
		ADMIN_RESET : "Nollaa Galaxytool (vain käyttäjä- ja ip-taulut jäävät entiselleen)",
		ADMIN_OLD_PLAYERS : "Poista yli &1 päivää vanhat pelaajatiedot",
		ADMIN_OLD_REPORTS : "Poista yli &1 päivää vanhat raportit",
		ADMIN_LOADING : "Älä sulje tätä ikkunaa kun sivua ladataan.",
		ADMIN_STATUS : "Pyyntöjesi tila",
		ADMIN_SELECTION : "Valitse ainakin yksi kohta",
		ADMIN_SAFETY : "Haluatko varmasti suorittaa nämä skriptit?",
		ADMIN_DONE : "Valmis",
		ADMIN_NOTBD : "Ei mitään tehtävää",
		ADMIN_OLD_GALAXIES : "Poista yli &1 päivää vanhat galaksinäkymät",
		ADMIN_UNUSED_PLAYERS : "Poista pelaajat, jotka eivät esiinny missään galaksinäkymässä",
		ADMIN_OLD_ACTIVITIES : "Poista pelaajien aktiivisuus, joka on vanhempaa kuin &1 päivää",
		ADMIN_OLD_COMBATS : "Poista taisteluraportit, jotka ovat vanhempia kuin &1 päivää",
		ADMIN_OLD_INGAME_MSG : "Poista pelin sisäiset viestit, jotka ovat vanhempia kuin &1 päivää",
		ADMIN_OGAME_API : "Load public data from OGame into the Galaxytool",
		ADMIN_OGAME_ALL_DATA : "Kaikki saatava tieto",
		ADMIN_OGAME_GALAXY_DATA : "Näytä galaksi",
		ADMIN_OGAME_STATISTICS_DATA : "Tilastot",
		ERRORPAGE_PAGEFORWARD : "Jos selaimesi ei tue sivun uudelleenohjausta, klikkaa tästä.",
		ERRORPAGE_PERMISSION_DENIED : "Sinulla ei ole oikeutta tarkastella tätä sivua. Klikkaa tästä päästäksesi takaisin.",
		FLEETS_TITLE : "Laivueliikenteet",
		FLEETS_ACTUAL_FLEETS : "Nykyiset laivueliikenteet",
		FLEETS_YES : "Kyllä",
		FLEETS_NO : "Ainoastaan planeetat missä huomioita",
		FLEETS_DETAILS : "Tiedot",
		FLEETS_MISSION_EXPEDITION : "Retkikunta",
		FLEETS_MISSION_COLONIZATION : "Kolonisaatio",
		FLEETS_MISSION_RECYCLE : "Kierrätys",
		FLEETS_MISSION_TRANSPORT : "Kuljetus",
		FLEETS_MISSION_DEPLOYMENT : "Siirto",
		FLEETS_MISSION_ESPIONAGE : "Vakoilu",
		FLEETS_MISSION_ACS_DEFEND : "LTS puolustus",
		FLEETS_MISSION_ATTACK : "Hyökkäys",
		FLEETS_MISSION_ACS_ATTACK : "LTS hyökkäys",
		FLEETS_MISSION_MOON_DESTRUCTION : "Kuun tuhoaminen",
		FLEETS_MISSION_MISSILE_ATTACK : "Ohjushyökkäys",
		FLEETS_NO_DATA : "Sopivaa tietoa ei löydy",
		FLEETS_FLEET : "Fleet",
		FLEETS_ALL_FLEETS : "Show all fleet movements",
		COMBAT_REPORT_OUDATED_GALAXYVIEW : "Galaksin tieto on vanhentunutta. Ole hyvä ja ensin vieraile hyökkäyksen lähtöpaikan ja hyökkäyskohteen koordinaateissa!",
		MESSAGES_TITLE : "OGame Galaxytool - OGame Viestit",
		MESSAGES_PLAYERNAME : "Pelaaja",
		MESSAGES_SUBJECT : "Aihe",
		MESSAGES_DATE : "Päiväys",
		MESSAGES_FILTER : "Suodatin",
		MESSAGES_DELETE : "Poista viesti",
		MESSAGES_PUBLISH_DETAIL : "Julkaise viesti lisäämällä sisältö ko. pelaajan merkintöihin.",
		MESSAGES_PUBLISH_HEADER : "&sender lähetä viesti &recipient &date:\n\n &message",
		MESSAGES_PLAYER_FILTER : "Pelaajan viestit:",
		MESSAGES_CONTENT : "Content",
		COMBATS_TITLE : "OGame Galaxytool - Taisteluraportit",
		COMBATS_ATTACKER : "Hyökkääjä",
		COMBATS_DEFENDER : "Puolustaja",
		COMBATS_DATE : "Päiväys",
		COMBATS_OWNER : "Omistaja",
		COMBATS_WINNER : "Voittaja",
		COMBATS_COMBATREPORT : "Taisteluraportti",
		COMBATS_COMBAT_AT : "Taistelu koordinaateissa",
		COMBATS_LOST_UNITS : "Menetetyt yksiköt",
		COMBATS_LOOT : "Saalis",
		COMBATS_DEBRIS : "Romukenttä",
		COMBATS_AND : "ja",
		COMBATS_PUBLISH : "Julkaise raportti",
		COMBATS_UNPUBLISH : "Poista julkisista raporteista (muuttaa yksityiseksi)",
		COMBATS_DELETE : "Poista raportti",
		COMBATS_CHECK_ALL : "Valitse kaikki",
		COMBATS_UNCHECK_ALL : "Poista valinnat",
		COMBATS_WITH_SELECTED : "Valituilla",
		COMBATS_PUBLIC_REPORTS : "Julkiset raportit",
		COMBATS_YES : "Kyllä",
		COMBATS_NO : "Ainoastaan planeetat missä huomioita",
		COMBATS_SEARCH_OPTIONS : "Hakuasetukset",
		COMBATS_SEARCH : "Etsi",
		COMBATS_RESET : "Resetoi",
		COMBATS_COORDINATES : "Koordinaatit",
		COMBATS_INVALID_GALAXY_ENTERED : "Virheellinen galaksi syötetty",
		COMBATS_INVALID_SYSTEM_ENTERED : "Virheellinen aurinkokunta syötetty",
		COMBATS_INVALID_PLANET_ENTERED : "Virheellinen planeetta syötetty",
		COMBATS_GALAXY_FROM_TO : "Galaksi",
		COMBATS_SYSTEM_FROM_TO : "Aurinkokunta",
		COMBATS_PLANET_FROM_TO : "Planeetta",
		COMBATS_APPLY : "Käytä",
		COMBATS_COMBAT_SUMMARY : "Lyhyt taisteluraportti",
		COMBATS_DOWNLOAD_CSV : "Lataa CSV-tiedostona",
		REPORT_ARCHIVE_TITLE : "Raporttiarkisto",
		REPORT_ARCHIVE_COORDINATES : "Koordinaatit",
		REPORT_ARCHIVE_SCANTIME : "Päiväys",
		REPORT_ARCHIVE_DELETE : "Poista merkinnät",
		REPORT_ARCHIVE_CONFIRM_DELETE : "Haluatko varmasti poistaa nämä merkinnät?",
		REPORT_ARCHIVE_GALAXY : "Galaksi",
		REPORT_ARCHIVE_SYSTEM : "Aurinkokunta",
		REPORT_ARCHIVE_PLANET : "Planeetta",
		REPORT_ARCHIVE_MOON : "Kuu",
		REPORT_ARCHIVE_DETAILS : "Tiedot",
		REPORT_ARCHIVE_RESOURCES : "Resursseja tunnissa",
		REPORT_ARCHIVE_HEADER_RESOURCES : "Resurssit",
		REPORT_ARCHIVE_DETAILS_FOR : "Raporttiarkisto kohteesta &1 [&2] (&3)",
		REPORT_ARCHIVE_FLEET_CARGO : "Laivueen lastiruuman kapasiteetti",
		REPORT_ARCHIVE_IRAK_RANGE : "Planeettojen välisten ohjusten kantama",
		REPORT_ARCHIVE_CHART_TYPE : "Taulukon tyyppi",
		INSTALL_TITLE : "Galaxytool installation for version",
		INSTALL_PROGRESS : "Overall progress",
		INSTALL_STEP : "Step",
		INSTALL_CONTINUE : "Continue",
		INSTALL_VALIDATE : "Validate",
		INSTALL_STEP1 : "Welcome",
		INSTALL_STEP2 : "Writeable check",
		INSTALL_STEP3 : "Database settings",
		INSTALL_STEP4 : "OGame settings",
		INSTALL_STEP5 : "Galaxytool settings",
		INSTALL_STEP6 : "Admin password",
		INSTALL_STEP7 : "Install Galaxytool",
		INSTALL_STEP8 : "Finalize install",
		INSTALL_FILE_DELETE_CHECK : "Please delete install.php and update.php from your webserver.",
		INSTALL_STEP1_PHP_FAILED : "Your PHP version &1 is not working with this Galaxytool version",
		INSTALL_STEP1_FOPEN_FAILED : "Your PHP version does not allow to open webpages with FOPEN() command. This is required to consume the OGame API.",
		INSTALL_STEP1_WELCOME : "Welcome to the installation wizard of the Galaxytool. You will be guided through the installation of the Galaxytool.",
		INSTALL_STEP2_DESCRIPTION : "Make sure your config.php and attributes.php files have write permissions enabled.",
		INSTALL_STEP2_DESCRIPTION2 : "If you don't know, how to achieve this, please take a look here: &1",
		INSTALL_STEP2_FILE_NOT_WRITEABLE : "File is not writeable",
		INSTALL_STEP3_SERVER : "Database server",
		INSTALL_STEP3_USERNAME : "Käyttäjänimi",
		INSTALL_STEP3_PASSWORD : "Salasana",
		INSTALL_STEP3_DBNAME : "Database name",
		INSTALL_STEP3_PREFIX : "Tablename prefix",
		INSTALL_STEP3_ENTER_PREFIX : "E.g. mytool_",
		INSTALL_STEP3_ENTER_SERVER : "Enter the server address. Contact your system admin if necessary. Usually the correct value is localhost.",
		INSTALL_STEP3_ENTER_USERNAME : "Enter the username for database access",
		INSTALL_STEP3_ENTER_PASSWORD : "Enter the password for database access",
		INSTALL_STEP3_ENTER_DBNAME : "Enter the database name which shall be used for installation (must exist)",
		INSTALL_STEP3_CONNECT_FAILED : "Could not establish connection to database server",
		INSTALL_STEP3_DB_FAILED : "Database &1 not found",
		INSTALL_STEP3_MYSQL_VERSION_FAILED : "MySQL version &1 is not working with this Galaxytool version",
		INSTALL_STEP4_URL : "OGame URL",
		OGAME_URL_DETAILS : "Please enter any URL you see when you are logged on to OGame. Based on that URL the tool will derive the OGame API address which can be used to fill data into the Galaxytool without the Galaxytoolbar. This API was introduced with OGame version 4.1.",
		INSTALL_STEP4_UNIVERSE : "OGame Universe",
		INSTALL_STEP4_DEF_TO_DEBRIS : "Defense to debris",
		INSTALL_STEP4_DEBRIS_RATE : "Debris rate",
		INSTALL_STEP4_SPEED_RATE : "Speed rate",
		INSTALL_STEP4_ENTER_UNIVERSE : "Enter your OGame universe name or number (case sensitive).",
		INSTALL_STEP4_UNIVERSE_MISSING : "You must define your universe",
		INSTALL_STEP4_ENTER_URL : "Enter your OGame universe address",
		INSTALL_STEP4_URL_MISSING : "You must define your OGame address",
		INSTALL_STEP4_URL_CHECK_FAILED : "Could not find OGame API at &1",
		INSTALL_STEP4_GETSETTINGS : "Fetch settings",
		INSTALL_STEP5_TOOLNAME : "Galaxytool name",
		INSTALL_STEP5_ENTER_TOOLNAME : "This is the name which will be shown at logon page to identify your Galaxytool",
		INSTALL_STEP5_LANGUAGE : "Default language",
		INSTALL_STEP5_EMAIL_TO : "Email To",
		INSTALL_STEP5_ENTER_EMAIL_TO : "Enter the email address where you would like to receive notifications about registrations",
		INSTALL_STEP5_EMAIL_FROM : "Email From",
		INSTALL_STEP5_ENTER_EMAIL_FROM : "This email address is shown as REPLY for all mails sent from the Galaxytool",
		INSTALL_STEP5_USE_PHPMAILER : "Use PHPMailer",
		INSTALL_STEP5_MAXSHOUTS : "Maximum number of shoutbox entries",
		INSTALL_STEP5_ENTER_USE_PHPMAILER : "Use PHPMailer if your server does not support sending emails by default",
		INSTALL_PHPMAILER_HOST : "SMPT Host",
		INSTALL_PHPMAILER_HOST_EXAMPLE : "e.g. smtp.provider.com",
		INSTALL_PHPMAILER_USER : "SMPT Username",
		INSTALL_PHPMAILER_USER_EXAMPLE : "e.g. user@provider.dcom",
		INSTALL_PHPMAILER_PASS : "SMPT password",
		INSTALL_PHPMAILER_SECURE : "Authentification method (e.g. ssl)",
		INSTALL_PHPMAILER_PORT : "SMTP Port",
		INSTALL_STEP6_INTRO : "Please define a password for the <strong>admin</strong> account which you have to use for your first logon to the Galaxytool after the installation.",
		INSTALL_STEP7_CONFIG : "Configuration file created",
		INSTALL_STEP7_CONFIG_FAILED : "Configuration file not created",
		INSTALL_STEP7_ATTRIBUTES : "Attributes file created",
		INSTALL_STEP7_ATTRIBUTES_FAILED : "Attributes file not created",
		INSTALL_STEP7_CREATED_TABLES : "Database tables created",
		INSTALL_STEP8_INTRO : "You have successfully installed the Galaxytool!",
		INSTALL_STEP8_LOAD_DATA : "Downloading OGame data ...",
		INSTALL_STEP8_LOAD_DATA_FINISHED : "Download of OGame data finished",
		INSTALL_STEP8_DELETE_FILE : "You should now delete the installation files install.php and update.php from your webserver.",
		INSTALL_STEP8_LOGON : "Please logon with the <strong>admin</strong> user and the password you defined earlier.",
		UPDATE_START : "Starting update to version &1",
		UPDATE_STEP_DONE : "Done",
		UPDATE_TITLE : "Galaxytool update for version",
		UPDATE_STEP1_WELCOME : "Welcome to the update wizard of the Galaxytool. You will be guided through the update of the Galaxytool.",
		UPDATE_STEP1_BACKUP_FILES : "As a first step, make a backup of your <strong>config</strong> folder! You will have to replace the configuration content in case of errors.",
		UPDATE_STEP1_BACKUP_DB : "Then make a <a href=\"http://www.ehow.com/how_2036600_create-database-php.html\">backup</a> of your database.",
		UPDATE_STEP1_PROCEED : "Once the backups have been done, you can proceed with your update.",
		UPDATE_STEP1 : "Welcome",
		UPDATE_STEP2 : "Galaxytool settings",
		UPDATE_STEP2_OLD_VERSION : "Previous Galaxytool version",
		UPDATE_STEP3 : "Update Galaxytool",
		UPDATE_STEP3_UPDATE_RUNNING : "Update running, please wait...",
		UPDATE_STEP4 : "Finalize Update",
		UPDATE_STEP4_INTRO : "You have successfully updated the Galaxytool!",
		UPDATE_STEP4_UPDATE_DONE : "Update steps performed.",
		UPDATE_FAILED : "Update failed.",
		GALAXYTOOL_DUMMY_TEXT : "dummy"
	})
);