define(
	({
		REPORT_WHEN : "στις",
		RESOURCES_ON : "Πόροι στο",
		PLAYER_BANNED : "b",
		PLAYER_VACATION_MODE : "v",
		PLAYER_NOOB : "n",
		PLAYER_INACTIVE : "i",
		PLAYER_LONG_INACTIVE : "I",
		PLAYER_OUTLAW : "α",
		L_USERNAME : "Όνομα Χρήστη",
		L_PASSWORD : "Κωδικός",
		L_LOGINFAILURE : "Το όνομα χρήστη ή ο κωδικός είναι λάθος, ή ο λογαριασμός σας δέν έχει ενεργοποιηθεί ακόμα.",
		L_TOKENFAILURE : "Το κλειδί εισόδου είναι λάθος ή ο λογαριασμός δεν έχει ενεργοποιηθεί ακόμα.",
		L_LOGINTEXT : "Είσοδος.",
		L_LANGUAGE : "Διαθέσιμες Γλώσσες:",
		L_TIMEOUT : "Τέλος χρόνου συνεδρίας!",
		L_REGISTER : "Εγγραφή",
		L_PWLOST : "Ξεχάσατε τον κωδικό σας?",
		INDEX_TITLE : "Περίληψη",
		INDEX_INFO : "Πληροφορίες",
		INDEX_ENTRIES : "Συνολικός Αριθμός Συστημάτων",
		INDEX_ENTRIES_LASTWEEK : "Νέα συστήματα την περασμένη εβδομάδα",
		INDEX_ENTRIES_TO_OLD : "Συστήματα παλιότερα απο 1 μήνα",
		INDEX_REGISTERED_USERS : "Εγγεγραμμένοι χρήστες",
		INDEX_PAGEFORWARD : "Αν ο browser σας δέν υποστηρίζει page forwarding πατήστε εδώ.",
		INDEX_NOTICES : "Σημειώσεις",
		INDEX_PLAYERS : "Στατιστικά Παικτών",
		INDEX_ALLIES : "Στατιστικά Συμμαχιών",
		INDEX_REPORTS : "Κατασκοπευτικές Αναφορές",
		INDEX_VERSION : "Νεότερη έκδοση για κατέβασμα",
		INDEX_LATEST_VERSION : "Καμία νεότερη έκδοση διαθέσιμη",
		INDEX_SHOUTBOX : "Shoutbox",
		INDEX_NOENTRY : "Κανένα κείμενο μέχρι στιγμής",
		INDEX_COMMENT : "Το δικό σου Shout",
		INDEX_INSERT : "Εισαγωγή",
		INDEX_UMOD : "Παίκτες σε κατάσταση διακοπών",
		INDEX_NO_MOONS : "Συνολικός αριθμός Φεγγαριών",
		INDEX_NO_EMPTY_SYSTEMS : "Συνολικός αριθμός ’δειων Συστημάτων",
		INDEX_NO_FULL_SYSTEMS : "Συνολικός αριθμός Γεμάτων Συστημάτων",
		INDEX_NO_TARGETS : "Συνολικός αριθμός πιθανών στόχων",
		INDEX_USERINFO : "Αριθμός Χρηστών",
		INDEX_ONLINE : "Συνδεδεμένοι τώρα",
		INDEX_TODAY : "Συνδέθηκαν Σήμερα",
		INDEX_ALL : "Συνολικός αριθμός συνδέσεων",
		GENERAL_LOAD_FORM : "Φόρτωσε από τα δεδομένα",
		GENERAL_SAVE_FORM : "Σώσε δεδομένα",
		GENERAL_SAVE_AS_TEXT : "Σώσε σαν",
		GENERAL_SAVE : "Σώσε",
		INDEX_USERMANAGEMENT : "Επισκόπηση ενεργοποίησης",
		INDEX_NEEDADMIN : "Λογαριασμοί για ξεκλείδωμα",
		INDEX_NEEDEMAIL : "Ανεπικύρωτοι Λογαριασμοί",
		INDEX_TOOLBAR_INFO : "Galaxytool plugin πληροφορίες",
		INDEX_TOOLBAR_URL : "Galaxytool URL",
		INDEX_TOOLBAR_VERSION_REQUIRED : "Απαραίτητη ή έκδοση του Galaxytool plugin",
		INDEX_TOOLBAR_INSTALL_GUIDE : "Οδηγίες εγκατάστασης του plugin",
		INDEX_TOOLBAR_TOKEN : "Κλειδί Εισόδου",
		INDEX_TOOLBAR_NEW_TOKEN : "Ζητήστε νέο κλειδί",
		INDEX_PLAYERS_WITH_N_PLANETS : "Παίκτες με περισσότερους από  &1 πλανήτες",
		INDEX_GETTING_STARTED : "Ξεκινήστε με το  Galaxytool",
		INDEX_GETTING_STARTED1 : "Καλως ήλθατε στο Galaxytool!",
		INDEX_GETTING_STARTED2 : "Το Galaxytool θα σας βοηθήσει να αναλύσετε τα γεγονότα στο OGame Σύμπαν &1",
		INDEX_GETTING_STARTED3 : "Πριν αρχίσετε να αναλύετε δεδομένα πρεπει να τα εισάγετε πρώτα. Για αυτό σας χρειάζετε το plugin &1 για τον Firefox.",
		INDEX_GETTING_STARTED4 : "Εφόσον εκγαταστήσετε το plugin, μπορείτε να πλοηγηθείτε στισ σελίδες του OGame ως συνήθως και θα παρατηρήσετε ένα μικρό παράθυρο κατάστασεων κάθε φορά που κάτι αποστέλεται στο Galaxytool.",
		INDEX_GETTING_STARTED5 : "Απο την στιγμή που έχουν εισαχθεί δεδομένα στο Galaxytool, μπορείτε να αναλύσετε που έχουν οι παίκτες τις αποικίες τους, πόσες αποικίες κατέχουν, τι αναφορές υπάρχουν και κάθε πότε είναι ενεργοί.",
		INDEX_GETTING_STARTED6 : "Αλλά θα σας βοηθήσει να αναλύσετε πως πορεύεστε συγκρινόμενος με τους ανταγωνιστές σας ή αναλύοντας τις αναφορές μάχης παρακολουθώντας την προόδό σας τις τελευταίες μέρες ή εβδομάδες.",
		INDEX_GETTING_WIKIPAGE : "Υπάχρουν περισσότερα χαρακτιριστικά εντός του Galaxytool.",
		INDEX_GETTING_WIKIPAGE2 : "Ενημερωθείτε στην σελίδα wiki.",
		INDEX_GETTING_BOARD : "Γία τις απορίες και καινούργιες ιδέες μπορείτε να χρησιμοποιήσετε τον φόρουμ μας:",
		INDEX_GETTING_CHAT1 : "Ή επισκευτείτε το  chatroom μας:",
		INDEX_GETTING_CHAT2 : "Δεν είμαστε ενεργοί 24/7 αλλά περνάμε αρκετό απο τον ελεύθερο μας χρόνο εκεί, οπότε παραμείνετε υπομονετικοί.",
		INDEX_CLOSE : "Close",
		INDEX_LOGIN : "Login",
		GENERAL_REQUIRED_FIELDS : "Please fill all required fields",
		INDEX_MESSAGES : "Messages",
		INDEX_EXAMPLE : "Example",
		INDEX_INVALID_DATA : "Invalid data",
		GENERAL_COLUMN_HIDE_TITLE : "Manage columns",
		GENERAL_COLUMN_HIDE_INFO : "Please select which columns you want to see in the table.",
		GENERAL_ENTRIES_DELETED : "&1 entries deleted",
		GENERAL_APPLY : "Εφαρμογή",
		STARTPAGE_GALAXYTOOL_DESCR : "<em>Galaxytool</em> is a tool for the browser game OGame.",
		GENERAL_OVERWRITE : "Overwrite duplicate entry",
		GENERAL_OVERWRITE_QUESTION : "Overwrite?",
		INDEX_OWN_LOGINS : "Your logins",
		GENERAL_OPEN_IN_NEW_WINDOW : "Άνοιγμα δεσμού σε νέο παράθυρο",
		GENERAL_UNIT_OF_MEASURE_DAYS : "Days",
		PROGRAM_NAME : "OGame Galaxytool",
		SHORTNAME : "Galaxytool",
		BACK_INDEX : "Πίσω στην κεντρική σελίδα",
		UNIVERSE : "Γαλαξίας",
		MENU_INFO_LINKS : "Πληροφορίες",
		MENU_PAGE : "Περίληψη",
		MENU_DB_SEARCH : "Έρευνα στην βάση δεδομένων",
		MENU_DB_NOTICES : "Έρευνα στις σημειώσεις",
		MENU_DB_REPORTS : "Έρευνα στις Αναφορές",
		MENU_GALAXYVIEW : "Προβολή Γαλαξία",
		MENU_STATISTICS : "Στατιστικά",
		MENU_ALLYHISTORY : "Ιστορικό Συμμαχίας",
		MENU_FLEET_MOVEMENTS : "Κινήσεις Στόλου",
		MENU_COMBAT_REPORTS : "Αναφορές μάχης",
		MENU_MESSAGES : "Μηνύματα παιχνιδιού",
		MENU_OPTION_LINKS : "Επιλογές",
		MENU_DB_REFRESH : "Εισαγωγή στη βάση δεδομένων",
		MENU_NOTICES : "Σημειώσεις",
		MENU_DB_STATUS : "Κατάσταση της βάσης δεδομένων",
		MENU_USEROPTIONS : "Διαχείρηση Χρηστών",
		MENU_USEROPTIONS2 : "Επιλογές χρηστών",
		MENU_USEROPTIONS3 : "Πληροφορίες Χρηστών",
		MENU_ADMIN : "Διαχείριση",
		MENU_LOGOUT : "Αποσύνδεση",
		MENU_STUFF : "Διάφορα",
		MENU_FORUM_THREAD : "Φορουμ Ανάπτυξης",
		MENU_DOWNLOADPAGE : "Σελίδα Download",
		MENU_LANGUAGE : "Γλώσσα",
		MENU_HELP : "Βοήθεια",
		MENU_TOOLOPTIONS : "Επιλογές Galaxytool",
		PARSER_INFO1 : " εισήχθη στην βάση δεδομένων",
		PARSER_ERROR1 : "Λάθος προσπαθώντας να εισαχθούν οι παρακάτω συντεταγμένες:",
		PARSER_ERROR2 : "Δέν βρέθηκε η βάση δεδομένων!",
		PARSER_ERROR3 : "Δέν βρέθηκε ο server της βάσης δεδομένων!",
		PARSER_WRONG_UNIVERSE : "Λάθος Σύμπαν - πραγματικό: \"&1\" αναμενόμενο: \"&2\"",
		SHOW_TITLE : "OGame Galaxytool - Σελίδα αναζήτησης",
		SHOW_SEARCH : "Αναζήτηση στη βάση δεδομένων",
		SHOW_ALLYSYMBOL : "Tag Συμμαχίας",
		SHOW_PLAYERNAME : "Όνομα Παίκτη",
		SHOW_MOONS : "Μόνο πλανήτες με φεγγάρι",
		SHOW_NOTICES : "Μόνο πλανήτες με σημειώσεις",
		SHOW_COLONIES : "Μόνο πλανήτες για Αποικιοποίηση",
		SHOW_YES : "Ναι",
		SHOW_NO : "Όχι",
		SHOW_SEARCHRANGE : "Περιοχή",
		SHOW_SEARCH_IN : "Αναζήτηση στον Γαλαξία",
		SHOW_FROM_SYSTEM : "απο το ηλιακό σύστημα",
		SHOW_FROM_PLANET : "απο την θέση πλανήτη",
		SHOW_TO : "ώς",
		SHOW_DESCRIPTION : "Μπορείτε να χρησιμοποιήσετε wildcards * για ονόματα παικτών ή συμμαχιών. Δηλαδή μπορείτε να βρείτε όλους τους παίκτες με &quot;όνομα&quot; στο όνομά τους.<br />Συμπληρώστε μόνο τα πεδία που θέλετε να καθορίσετε.",
		SHOW_SORT_BY : "Στοίχηση με",
		SHOW_GALASYSTEM : "Γαλαξίας/Σύστημα",
		SHOW_ALLYNAME : "Όνομα Συμμαχίας",
		SHOW_SEARCHBUTTON : "Αναζήτηση",
		SHOW_ADDRESS : "Διεύθυνση",
		SHOW_ALLYSORT : "Συμμαχία",
		SHOW_PLANET : "Όνομα Πλανήτη",
		SHOW_STATUS : "Κατάσταση",
		SHOW_CURRENTNESS : "Τελευταία ενημέρωση",
		SHOW_PLAYER_STATUS : "Κατάσταση Παίκτη",
		SHOW_PLAYER_STATUS1 : "όλοι",
		SHOW_PLAYER_STATUS2 : "πιθανοί στόχοι",
		SHOW_PLAYER_STATUS3 : "ανενεργός",
		SHOW_HITS : "Hits",
		SHOW_OF : "του",
		SHOW_ASC : "ανοδικά",
		SHOW_DESC : "καθοδικά",
		SHOW_RESULTS : "χτυπήματα ανα σελίδα",
		SHOW_MOON : "Φεγγάρι",
		SHOW_UKMOONSIZE : "άγνωστο",
		SHOW_DF : "DF",
		SHOW_DF_LONG : "πεδίο συντρημιών",
		SHOW_METAL : "Μ",
		SHOW_METAL_LONG : "Μέταλλο",
		SHOW_CRYSTAL : "Κ",
		SHOW_CRYSTAL_LONG : "Κρύσταλλο",
		SHOW_BOTH : "όλα μαζί",
		SHOW_AT_LEAST : "(το λιγότερο)",
		SHOW_DATE : "Ημερομηνία",
		SHOW_DATE_0 : "δεν με ενδιαφέρει",
		SHOW_DATE_1 : "παλίοτερο απο",
		SHOW_DATE_2 : "νεότερο απο",
		SHOW_RANK : "Βαθμολογία",
		SHOW_FRANK : "Βαθμολογία Στόλου",
		SHOW_MEMBERS : "Μέλη",
		SHOW_NOTRANKED : "Όχι μέσα στους πρώτους 1500.",
		SHOW_NOTICERES : "Σημειώσεις",
		SHOW_REPORTS : "Μόνο πλανήτες με αναφορές",
		SHOW_REPORTS_SHORT : "Αναφορές",
		SHOW_NOTHING : "Δεν βρέθηκε καμία καταχώρηση",
		SHOW_ALLIANCE_STATUS : "Θέση Συμμαχίας",
		SHOW_NO_STATUS : "Χωρίς κατάσταση",
		SHOW_NAP : "NAP",
		SHOW_ALLIED : "Συμμαχοι",
		SHOW_WAR : "Σε πόλεμο",
		SHOW_BOYCOTT : "Μποϊκοτάζ",
		SHOW_NEUTRAL : "Αδιάφορος",
		SHOW_OWN : "Δική μου Συμμαχία",
		SHOW_WING : "Wing",
		SHOW_EXT_OPTIONS1 : "Εμφάνιση περισσότερων επιλογών για  περιοχή, βαθμολογία, ημερομηνία ή πεδία συντριμιών στην αναζήτηση.",
		SHOW_EXT_OPTIONS2 : "Εμφάνιση περισσότερων επιλογών για αποικίες, φεγγάρια, αναφορές, σημειώσεις, κατάσταση παίκτη ή διπλωματική κατάσταση.",
		SHOW_EXT_OPTIONS3 : "Εμφάνιση περισσότερων επιλογών για ταξινόμηση των αποτελεσμάτων αναζήτησης.",
		SHOW_EXTENDED : "advanced search",
		SHOW_MOON_SELECTION : "Planet with moon",
		SHOW_REPORT_SELECTION : "Planet with report",
		SHOW_FILTER_BY : "Exclude from the list",
		SHOW_FILTER_NONE : "κανένας",
		SHOW_PLAYERS_WITHOUT_PROGRESS : "Show players without score changes within the last few days",
		STATUS_TITLE : "OGame Galaxytool - Σελίδα Κατάστασης",
		STATUS_DB_STATUS : "Κατάσταση Βάσης Δεδομένων",
		STATUS_COLOR : "Χρώμα",
		STATUS_AGE1 : "Εισαγωγή 1 ημέρας.",
		STATUS_AGE2 : "Εισαγωγή 2 - 4 ημερών.",
		STATUS_AGE3 : "Εισαγωγή 4 - 7 ημερών.",
		STATUS_AGE4 : "Εισαγωγή 1 - 2 εβδομάδων.",
		STATUS_AGE5 : "Εισαγωγή 2 - 4 εβδομάδων.",
		STATUS_AGE6 : "Εισαγωγή παλιότερη απο 1 μήνα!",
		STATUS_AGE7 : "Καμία εισαγωγή διαθέσιμη.",
		STATUS_ON : "στις",
		STYLES_COLOR1 : "Χρώμα 1",
		STYLES_COLOR2 : "Χρώμα 2",
		STYLES_COLOR3 : "Χρώμα 3",
		STYLES_COLOR4 : "Χρώμα 4",
		STYLES_COLOR5 : "Χρώμα 5",
		STYLES_COLOR6 : "Χρώμα 6",
		STYLES_COLOR7 : "Χρώμα 7",
		STATUS_DB_LEGEND : "Ήρωας",
		STATUS_GALAXY : "Επισκόπηση Γαλαξία",
		USER_TITLE : "Διαχείρηση Χρηστών",
		USER_NAMES : "Χρήστης",
		USER_ERROR : "Λάθος",
		USER_NEWUSER : "Νέος Χρήστης",
		USER_OPTIONS : "Επιλογές",
		USER_USERNAME : "Όνομα Χρήστη",
		USER_PASSWORD : "Κωδικός",
		USER_PASSWORD_CONFIRM : "Επαλήθευση Κωδικού",
		USER_GALAXY : "Γαλαξίας",
		USER_SEARCH : "Αναζήτηση",
		USER_INSERT : "Εισαγωγή",
		USER_DELETE : "Διαγραφή",
		USER_DELETE_ENTRY : "Θέλετε να διαγράψετε τον χρήστη: ",
		USER_STATUS : "Προβολή κατάστασης",
		USER_STYLES : "Τροποποίηση διάταξης",
		USER_SUBMIT : "Υποβολή",
		USER_RESET : "Reset",
		USER_YES : "Ναί",
		USER_NO : "Όχι",
		USER_STYLEPATH : "Διαδρομή του styles.css",
		USER_PROBES : "Προβολή/Υποβολή Κατασκοπευτικής Αναφοράς",
		USER_EMAIL : "Email",
		USER_ERROR1 : "Λάθος κωδικός ή άκυρο email.",
		USER_ERROR2 : "’κυρο Email.",
		USER_INGAME : "Όνομα στο παιχνίδι",
		USER_ALLYTAG : "Tag Συμμαχίας",
		USER_ALLYHISTORY : "Προβολή/Υποβολή Ιστορικού Συμμαχίας",
		USER_DIPLOMATIC : "Αλλαγή Διπλοματικής Κατάστασης",
		USER_STATSPAGE : "Συνολικός αριθμός καταχωρήσεων στη σελίδα στατιστικών",
		USER_LINKS : "Σύνδεσμοι",
		USER_LINKS2 : "Διάταξη:<br>text;url<br>text2;url2<br>text3;url3",
		USER_EXPORT_TITLE : "Εξαγωγή Χρωμάτων (BB Codes)",
		USER_BB_COORDINATES : "Συντεταγμένες",
		USER_BB_MOON : "Φεγγάρι",
		USER_BB_DEBRIS : "Πεδίο Συντρημιών",
		USER_BB_ALLY : "Όνομα Συμμαχίας",
		USER_BB_ALLYDETAILS : "Λεπτομέρειες Συμμαχίας",
		USER_BB_PLAYERNAME : "Όνομα Πάικτη",
		USER_BB_BANNED : "τιμορημένος",
		USER_BB_VACATION : "κατάσταση διακοπών",
		USER_BB_NOOB : "νέος παίκτης",
		USER_BB_INACTIVE : "ανενεργός",
		USER_BB_LONGINACTIVE : "ανενεργός για πολύ καιρό",
		USER_DELETION : "Διέγραψε",
		USER_FLEETINFO : "Κινήσεις Στόλου",
		USER_ACTIVITIES : "Δραστηριότητες Παίκτη",
		USER_MAINTENANCE : "Συντήρηση Galaxytool",
		USER_MANAGEMENT : "Διαχείρηση Χρηστών",
		USER_DELETE_MY_COMBAT_REPORTS : "Διέγραψε τις αναφορές μάχης",
		USER_DELETE_MY_MESSAGES : "Διέγραψε τα μηνύματά μου",
		USER_DELETE_MY_FLEETMOVES : "Διέγραψε τις κινήσεις στόλου μου",
		USER_DELETE_MY_COMBAT_REPORTS_LIMITED : "Διαγραφή των δικών μου αναφορών μάχης, παλιοτέρων από &1 ημερών",
		USER_DELETE_MY_MESSAGES_LIMITED : "Διαγραφή των δικών μου μυνημάτων, παλιοτέρων από &1 ημερών",
		USER_TABLE_ENTRIES : "Αριθμός αποτελεσμάτων αναζήτησης ανά σελίδα",
		USER_EXISTS : "User already exists",
		USER_BB_OUTLAW : "Outlaw",
		USER_INVALID_URL : "URL &1 seems to be invalid - URL will be ignored",
		VIEW_TITLE : "OGame Galaxytool - Λεπτομέρειες",
		VIEW_NODATA : "Χωρίς στοιχεία.",
		VIEW_GALAXY : "Γαλαξίας",
		VIEW_SYSTEM : "Ηλιακό σύστημα",
		VIEW_POSITION : "Θέση",
		VIEW_PLANET : "Πλανήτης",
		VIEW_MOON : "Φεγγάρι",
		VIEW_TF : "DF",
		VIEW_PLAYER : "Πάικτης",
		VIEW_PLAYER_ADD : "(βαθμολογία/ Κατάσταση)",
		VIEW_ALLY : "Συμμαχία",
		VIEW_ALLY_ADD : "(Βαθμολογία / Μέλος)",
		VIEW_METAL : "M",
		VIEW_CRYSTAL : "C",
		VIEW_COLONISED : "Κατοικημένοι πλανήτες",
		VIEW_UKMOONSIZE : "αγνωστο",
		VIEW_BACK : "πίσω",
		VIEW_NOTICE : "Σημειώσεις",
		VIEW_REPORTS : "Αναφορές",
		VIEW_MOONPHALANX : "Τα παρακάτω φεγγάρια μπορούν να σαρώσουν αυτό το σύστημα",
		VIEW_NOMOONS : "Δεν βρέθηκαν φεγγάρια",
		VIEW_IRAKS : "Ο παρακάτω πλανήτης μπορεί να φτάσει αυτό το σύστημα με Διαπλανητικούς πυραύλους",
		VIEW_NOIRAKS : "Δέν βρέθηκαν Διαπλανητικοί Πύραυλοι",
		VIEW_MOON_DESTROY_CHANCE : "Πιθανότητα για καταστροφή φεγγαριού",
		VIEW_CHANCE_WITH_ONE : "Πιθανότητα με ένα Deathstar",
		VIEW_CHANCE_WITH_N : "Πιθανότητα με ",
		VIEW_DEATH_STARS : "Deathstars",
		VIEW_DS_DESTROY_CHANCE : "Πιθανότητα να χαθεί το(τα) Death star(s)",
		VIEW_TOP : "Top",
		VIEW_GO : "go",
		VIEW_DIAMETER : "Diameter",
		PW_TITLE : "OGame Galaxytool - αλλαγή κωδικού",
		OLD_PASSWORD : "παλιός κωδικός",
		NEW_PASSWORD : "νέος κωδικός",
		CONFIRM_NEW_PASSWORD : "επαλήθευση κωδικού",
		PW_MISMATCH : "Ο κωδικός δέν είναι ίδιος!",
		PW_ERROR : "Ο παλιός κωδικός δέν είναι σωστός!",
		UPDATE_DONE : "επιτυχήςενημέρωση.",
		TIMEZONE_OFFSET : "Αντιστάθμιση ζώνης ώρας στον σερβερ",
		DELETE_ACCOUNT : "Διέγραψε αυτόν το λογαριασμό Galaxytool",
		DELETE_ACCOUNT_SAFETY_REQUEST : "Θέλεις πραγματικά να διαγράψεις αυτόν το λογαριασμό Galaxytool?",
		CH_PASSWD_AUTHORIZATION : "Εγκρίσεις",
		CH_PASSWD_ADMIN : "Διαχείριση",
		TIMEZONE_OGAME_OFFSET : "Αντιστάθμιση ζώνης ώρας στον OGame σερβερ",
		CH_PASSWD_USER_LANGUAGE : "Αλαγή σε αυτή την γλώσσα μετά απο την σύνδεση",
		CH_PASSWD_USER_LANGUAGE_NO_CHANGE : "Καμία αλλαγή",
		CH_PASSWD_EXPAND : "Διευρυμένο",
		CH_PASSWD_COLLAPSE : "Ανεπτυγμένο",
		CH_PASSWD_HIDDEN : "Κρυφό",
		CH_PASSWD_GETTING_STARTED : "Εμφάνιση Ξεκινώντας μετά την σύνδεση",
		CH_PASSWD_PLUGIN : "Εμφάνιση πληροφορίες Plugin μετά απο την σύνδεση",
		NOTICE_TITLE : "OGame Galaxytool - Σημειώσεις",
		NOTICE_HEADER : "διόρθωση σημείωσης",
		NOTICE_HEADER2 : "Διόρθωση των δικών μου σημειώσεων",
		NOTICE_PUBLIC : "Ανοιχτές σε άλλους ?",
		NOTICE_YES : "ναι",
		NOTICE_NO : "όχι",
		NOTICE_TEXT : "Κείμενο σημείωσης",
		NOTICE_SAVE : "Σώσιμο",
		NOTICE_DELETED : "Η Καταχώρηση διαγράφηκε",
		NOTICE_SAVED : "Η Καταχώρηση σώθηκε.",
		NOTICE_RESULTS : "Όλα τα αποτελέσματα",
		NOTICE_USER : "Χρήστης",
		NOTICE_DATE : "Ημερομηνία",
		NOTICE_EDIT : "Διόρθωση",
		NOTICE_DELETE : "Διαγραφή",
		NOTICE_NEW : "Δημιουργία καταχώρησης",
		NOTICE_NOTPUBLIC : "Σημείωση όχι ανοιχτη σε όλους.",
		NOTICE_ALL : "όλοι",
		NOTICE_NONE : "κανένας",
		NOTICE_SEARCH : "Αναζήτηση στις Σημειώσεις",
		NOTICE_SEARCH_SHORT : "Αναζήτηση",
		NOTICE_HITS : "Hits",
		NOTICE_SHOWRESULTS : "hits ανα σελίδα",
		NOTICE_OF : "του",
		NOTICE_NOTHING : "Δέν βρέθηκε καταχώρηση",
		NOTICE_CHARS : "Χαρακτήρες",
		NOTICE_PLAYERNAME : "Παίκτης",
		NOTICE_SHOWALL : "Προβολή όλων των σημειώσεων",
		REPORTS_TITLE : "OGame Galaxytool - Κατασκοπευτικές Αναφορές",
		REPORTS_RESOURCES : "Πόροι",
		REPORTS_FLEET : "Στόλοι",
		REPORTS_DEFENCE : "’μυνα",
		REPORTS_BUILDINGS : "Κτίρια",
		REPORTS_TECHNOLOGY : "Έρευνα",
		REPORTS_MOON : "Φεγγάρι",
		REPORTS_SEARCH : "Αναζήτηση στις κατασκοπευτικές αναφορές",
		REPORTS_SEARCH_SHORT : "Αναζήτηση",
		REPORTS_HITS : "Hits",
		REPORTS_NOTHING : "Δέν βρέθηκε εισαγωγή",
		REPORTS_ADDRESS : "Διεύθυνση",
		REPORTS_CURRENTNESS : "Currentness",
		REPORTS_PLAYERNAME : "Όνομα Παίκτη",
		REPORTS_ALLY : "Συμμαχία",
		REPORTS_VIEW : "εμφάνιση Αναφοράς",
		REPORTS_SEARCH_IN : "Αναζήτηση στον Γαλαξία",
		REPORTS_FROM_SYSTEM : "απο το Σύστημα",
		REPORTS_TO : "έως",
		REPORTS_DELETE : "διαγραφή",
		REPORTS_DELETED : "Η εισαγωγή διαγράφηκε",
		REPORTS_RESULTS : "hits ανα σελίδα",
		REPORTS_OF : "του",
		REPORTS_DATE : "Ημερομηνία",
		REPORTS_DATE_0 : "χωρίς κατάσταση",
		REPORTS_DATE_1 : "παλιότερο απο",
		REPORTS_DATE_2 : "νεότερο απο",
		REPORTS_NOTICES : "Σημειώσεις",
		REPORTS_AT_LEAST_RESOURCES : "Πόροι (το λιγότερο)",
		REPORTS_SEARCH_EXTENDED : "εκτεταμένη αναζήτηση",
		REPORTS_FLEET_RESIS : "Στόλος- σκόρ",
		REPORTS_DEFENCE_RESIS : "’μυνα- σκόρ",
		REPORTS_ALL_RESIS : "πρόσθεση σκόρ",
		REPORTS_TECHS : "Τεχνολογία",
		REPORTS_UNKNOWN_ENTRIES : "άγνωστες εισαγωγές",
		REPORTS_PARTLY_INSERTED : "εν μέρει εισαγώμενες",
		REPORTS_FOR_ALL_RES : "για όλους τους πόρους",
		REPORTS_FOR_TF : "για το πεδίο συντρημιών",
		REPORTS_KT : "Μικρά Μεταγωγικά",
		REPORTS_GT : "Μεγάλα Μεταγωγικά",
		REPORTS_SS : "Καταδιωκτικά",
		REPORTS_REC : "Ανακυκλωτής",
		REPORTS_RAIDABLE : "Μόνο στόχοι για επιδρομή",
		REPORTS_ALL_RESOURCES : "όλοι οι Ππόροι",
		REPORTS_STUFF : "Διάφορα",
		REPORTS_SPEEDSIM : "Εξομοίωση με το Speedsim",
		REPORTS_DRAGOSIM : "Εξομοίωση με το Dragosim",
		REPORTS_STATUS : "Κατάσταση",
		REPORTS_ERROR : "Συνέβη ένα λάθος",
		REPORTS_OWN_REPORTS : "Μονο οι αναφορές μου",
		REPORTS_UPLOAD_BY : "Αναφορά φορτώθηκε από",
		REPORTS_DEPTH : "Βάθος Αναφοράς",
		REPORTS_FLEET_SCORE : "Σκορ Στόλου",
		REPORTS_DEFENCE_SCORE : "Σκορ Άμυνας",
		REPORTS_HOURS : "hours",
		REPORTS_MAX_RESULTS_HIT : "Your query returned more than &1 hits. Only the first &1 results are show. Please adjust your search request to get less results.",
		REPORTS_OSIMULATE : "Simulate with OSimulate",
		REPORTS_SHOW_ONLY : "Show only",
		REPORTS_SHOW_PLANETS : "Πλανήτες",
		REPORTS_SHOW_MOONS : "Φεγγάρια",
		REPORTS_OWNER : "Reports owned by",
		STATS_TITLE : "OGame Galaxytool - Στατιστικά",
		STATS_TBLHEAD : "Στατιστικά",
		STATS_RANK : "Βαθμολογία",
		STATS_PLAYERNAME : "Όνομα Παίκτη",
		STATS_ALLYNAME : "Tag Συμμαχίας",
		STATS_SCORE : "Σκόρ",
		STATS_FLEET : "Στόλος",
		STATS_RESEARCH : "Έρευνα",
		STATS_MEMBERS : "Μέλη",
		STATS_STATUS : "Κατάσταση",
		STATS_NOTHING : "χωρίς Κατάσταση",
		STATS_NAP : "NAP",
		STATS_ALLIED : "Σύμμαχοι",
		STATS_WAR : "Σε πόλεμο",
		STATS_BOYCOTT : "Μποϊκοτάζ",
		STATS_NEUTRAL : "Αδιάφοροι",
		STATS_OWN : "Δική μου Συμμαχία",
		STATS_WING : "Wing",
		STATS_UPDATE : "Εισαγωγή απο",
		STATS_PLAYERSTATS : "Στατιστικά Παίκτη",
		STATS_ALLYSTATS : "Στατιστικά Συμμαχίας",
		STATS_DELETE : "Θέλετε να διαγράψετε αυτή την καταχώρηση ?",
		STATS_CONFIRM_DELETE : "Θέλετε σίγουρα να διαγραφεί αυτή η εισαγωγή Παίκτη?",
		STATS_CHANGE_PLAYER_STATUS : "Κατάσταση Παίκτη",
		STATS_CHANGE_ALLIANCE_STATUS : "Κατάσταση Συμμαχίας",
		STATS_CHANGE_ALLIANCE_STATUS_HINT : "Όλα τα μέλη αυτής της συμμαχίας παίρνουν αυτή την κατάσταση. Όλες οι προηγούμενες καταστάσεις θα διαγραφούν. Ωστόσο μπορείτε να αλλάξετε την κατάσταση κάποιων παικτών αργότερα.",
		STATS_UNKNOWN : "Υπόλοιποι",
		STATS_DETAILS : "Λεπτομέρειες για",
		STATS_PLAYERSTATUS : "Κατάσταση Παίκτη",
		STATS_IGNORE_STATUS : "όλοι",
		STATS_ACTIVE : "ενεργός",
		STATS_INACTIVE : "ανενεργός",
		STATS_BANNED : "τιμορημένος",
		STATS_VACATION : "κατάσταση διακοπών",
		STATS_NOOB : "νέος παίκτης",
		STATS_YES : "Ναι",
		STATS_NO : "Μόνο πλανήτες με σημειώσεις",
		STATS_SEARCH : "Αναζήτηση",
		STATS_SHOW_GRAPH : "Εμφάνισε λεπτομέρειες για την κατανομή Βαθμολογίας",
		STATS_LONG_INACTIVE : "ανενεργός για πολύ καιρό",
		STATS_STANDARD : "Standard Points",
		STATS_MILITARY : "Military Points",
		STATS_ECONOMY : "Economy",
		STATS_HONOUR : "Honour points",
		STATS_MILITARY_BUILD : "Military build",
		STATS_MILITARY_DESTROYED : "Military destroyed",
		STATS_MILITARY_LOST : "Military lost",
		REGISTER_REGISTRATE : "Εγγραφή",
		REGISTER_LOGINNAME : "Όνομα χρήστη",
		REGISTER_PASSWORD : "Κωδικός",
		REGISTER_PASSWORD_CONFIRM : "Επαλήθευση Κωδικού",
		REGISTER_EMAIL : "Email",
		REGISTER_INGAME : "Όνομα στο παιχνίδι",
		REGISTER_ALLYTAG : "Tag Συμμαχίας",
		REGISTER_EMAILVERIFICATION : "Έλεγχος Email",
		REGISTER_EMAILTEXT : "Παρακαλώ επισκεφθείτε το παρακάτω link για επλάθευσή της εγγραφής σας.",
		REGISTER_ERROR1 : "Το όνομα χρήστη χρησιμοποιήται ήδη.",
		REGISTER_ERROR2 : "Υπήρξε λάθος κατα την αποστολή του email. Παρακαλώ επικοινωνήστε με τον διαχειριστή.",
		REGISTER_ERROR3 : "Υπήρξε λάθος κατα την αποστολή των δεδομένων στην βάση δεδομένων!",
		REGISTER_INFO1 : "Ο λογαριασμός σας δημιουργήθηκε επιτυχώς.",
		REGISTER_INFO2 : "Παρακαλώ επισκεφθείτε το link στο email σας για επαλήθευση της εγγραφής.",
		REGISTER_INFO3 : "Ο λογαριασμός επαληθεύτηκε. Για να μπορείτε να τον χρησιμοποιήσετε πρέπει να ενεργοποιηθεί απο το διαχειριστή.",
		REGISTER_BUTTON : "Πίσω στην αρχική σελίδα",
		REGISTER_NEW_SUBJECT : "Υπάρχει μία νέα εγγραφή χρήστη.",
		REGISTER_NEW_MAILTEXT : "Ένας νέος χρήστης εγγράφηκε.",
		REGISTER_BACK : "Πίσω στην πρώτη σελίδα",
		REGISTER_MISSING_FIELDS : "Συμπλήρωσε όλα τα απαιτούμενα πεδία",
		REGISTER_ERROR4 : "Διεύθυνση Email address δεν είναι έγκυρη.",
		REGISTER_ERROR5 : "Οι κωδικοί δεν ταιριάζουν",
		REGISTER_PWS : "Ισχυρότητα κωδικού",
		REGISTER_PWS0 : "Πολύ αδύναμο ",
		REGISTER_PWS1 : "Αδύναμο",
		REGISTER_PWS2 : "Ικανοποιητικό",
		REGISTER_PWS3 : "καλό",
		REGISTER_PWS4 : "Εξαιρετικό",
		REGISTER_EMAIL_USED : "Email Address is already used",
		LOSTPW_TITLE : "Χαμένο password",
		LOSTPW_INFO2 : "Ένα νέο password στάλθηκε στην διεύθυνση email σας.",
		LOSTPW_BUTTON1 : "νέο password",
		LOSTPW_BUTTON2 : "Πίσω στην αρχική σελίδα",
		LOSTPW_LOGINNAME : "Όνομα χρήστη",
		LOSTPW_EMAIL : "Email",
		LOSTPW_ERROR1 : "Υπήρξε λάθος κατα την αποστολή των δεδομένων στην βάση δεδομένων!",
		LOSTPW_ERROR2 : "Δεν βρέθηκε ταιριαστή εισαγωγή !",
		LOSTPW_ERROR3 : "Υπήρξε λάθος κατα την αποστολή του email. Παρακαλώ επικοινωνήστε με τον διαχειριστή.",
		LOSTPW_EMAIL_SUBJECT : "Το νέο password που ζητήσατε",
		LOSTPW_EMAIL_TEXT1 : "Τα νέα στοιχεία εισόδου",
		LOSTPW_EMAIL_TEXT2 : "Όνομα χρήστη",
		LOSTPW_EMAIL_TEXT3 : "Κωδικός",
		LOSTPW_INFO1 : "You will receive an email to verify your password reset request.",
		LOSTPW_CONFIRM_RESET_SUBJECT : "Lost password?",
		LOSTPW_CONFIRM_RESET_MESSAGE : "Hello,\n\nyou requested a password reset for the Galaxytool. To generate a new password, click the following link:",
		USERINFO_TITLE : "OGame Galaxytool - Πληροφορίες Χρήστη",
		USERINFO_NAMES : "Όλοι οι χρήστες",
		USERINFO_DETAIL : "Λεπτομερείς πληροφορίες για",
		USERINFO_ERROR1 : "Κανένας χρήστης με αυτό το ID!",
		USERINFO_USERNAME : "Όνομα χρήστη",
		USERINFO_INGAME : "Όνομα στο παιχνίδι",
		USERINFO_EMAIL : "Email",
		USERINFO_ALLYTAG : "Συμμαχία",
		USERINFO_STYLEPATH : "Skin",
		USERINFO_STATUS : "Κατάσταση",
		USERINFO_ACTIVATE : "Ενεργοποίηση Παίκτη",
		USERINFO_LOGINS : "Συνολικός αριθμός εισόδων",
		USERINFO_LASTLOGIN : "Τελευταία είσοδος",
		USERINFO_DATA : "Πληροφορίες για τα εισαγώμενα συστήματα",
		USERINFO_NODATA : "Αυτός ο χρήστης δέν έχει εισάγει κανένα σύστημα μέχρι στιγμής!",
		USERINFO_GALAXY : "Γαλαξίας",
		USERINFO_SYSTEMS : "Αριθμός Συστημάτων",
		USERINFO_IP : "Διεύθυνση IP",
		USERINFO_LOGINTIME : "Είσοδος",
		USERINFO_NOLOGIN : "Ο παίκτης δέν έχει εισέλθει ποτέ.",
		USERINFO_LAST_GALAXYUPDATE : "Τελευταία εισαγώμενη προβολή Γαλαξία",
		USERINFO_LAST_PUBLIC_NOTICE : "Τελευταία δημόσια σημείωση",
		USERINFO_LAST_PRIVATE_NOTICE : "Τελευταία προσωπική σημείωση",
		USERINFO_NUMBEROF_PUBLIC_NOTICE : "Συνολικός αριθμός δημόσιων σημειώσεων",
		USERINFO_NUMBEROF_PRIVATE_NOTICE : "Συνολικός αριθμός προσωπικών σημειώσεων",
		USERINFO_ACTIVATED : "Ο λογαριασμός ενεργοποιήθηκε",
		USERINFO_ACTIVATIONTEXT : "Ο διαχειριστής ενεργοποίησε το λογαριασμό σας.\n\nΚαλή διασκέδαση!",
		USERINFO_LAST_SUBMIT : "Τελευταία εισαγωγή δεδομένων",
		ALLYHISTORY_TITLE : "OGame Galaxytool - Ιστορικό Συμμαχίας",
		ALLYHISTORY_TBLHEAD : "Περίληψη Ιστορικού",
		ALLYHISTORY_PLAYERNAME : "Όνομα παίκτη",
		ALLYHISTORY_ALLYNAME : "Συμμαχία",
		ALLYHISTORY_LASTMONTH : "Τελευταίος Μήνας",
		ALLYHISTORY_ALL_DATA : "Σύνολο διαθέσιμων πληροφοριών",
		ALLYHISTORY_SHOW : "προβολή στατιστικών",
		ALLYHISTORY_TIMESPAN : "Διάστημα ημερομηνίας",
		ALLYHISTORY_PROGESS : "Εξέλιξη",
		ALLYHISTORY_SCORE : "Σκόρ",
		ALLYHISTORY_FSCORE : "Σκόρ Στόλου",
		ALLYHISTORY_RSCORE : "Σκόρ Έρευνας",
		ALLYHISTORY_MEMBER : "Μέλη",
		ALLYHISTORY_NOTHING : "δέν βρέθηκαν καταχωρήσεις",
		ALLYHISTORY_DETAILS : "Λεπτομέρειες",
		ALLYHISTORY_SHOW_ADDRESS : "Συντεταγμένες",
		ALLYHISTORY_ESCORE : "Economy",
		ALLYHISTORY_MSCORE : "Military Points",
		DETAILEDINFO_PLAYERINFO_TITLE : "Πληροφορίες Παίκτη",
		DETAILEDINFO_ALLYINFO_TITLE : "Πληροφορίες Συμμαχίας",
		DETAILEDINFO_PLAYERINFO_TBLHEAD : "Λεπτομέρεις πληροφορίες για τον παίκτη",
		DETAILEDINFO_ALLYINFO_TBLHEAD : "Λεπτομέρεις πληροφορίες για την συμμαχία",
		DETAILEDINFO_NO_ALLIANCE : "καμία",
		DETAILEDINFO_SCORE : "Στατιστικά Σκόρ",
		DETAILEDINFO_FLEET : "Στατιστικά Στόλου",
		DETAILEDINFO_RESEARCH : "Στατιστικά Έρευνας",
		DETAILEDINFO_RANK : "Βαθμολογία",
		DETAILEDINFO_POINTS : "Σκόρ",
		DETAILEDINFO_KNOWN_PLANETS : "γνωστοί πλανήτες",
		DETAILEDINFO_MOONS : "γνωστά φεγγάρια",
		DETAILEDINFO_PHALANX_AREA : "Πεδίο φάλαγγας",
		DETAILEDINFO_NO_PHALANX_AREA : "δέν βρέθηκε καμία φάλαγγα",
		DETAILEDINFO_NOTICES : "Σημειώσεις",
		DETAILEDINFO_NO_NOTICES : "Δέν βρέθηκαν σημειώσεις",
		DETAILEDINFO_PREVIOUS_ALLIANCES : "προηγούμενες Συμμαχίες",
		DETAILEDINFO_RESOURCES_PER_HOUR : "Πόροι ανα ώρα",
		DETAILEDINFO_RESOURCES_PER_DAY : "Πόροι ανα ημέρα",
		DETAILEDINFO_RESOURCES_PER_WEEK : "Πόροι ανα εβδομάδα",
		DETAILEDINFO_RESOURCES_PER_MONTH : "Πόροι ανα μήνα (30 ημέρες)",
		DETAILEDINFO_METAL : "Μέταλλο",
		DETAILEDINFO_CRYSTAL : "Κρύσταλλο",
		DETAILEDINFO_DEUTERIUM : "Δευτέριο",
		DETAILEDINFO_UNKNOWN : "άγνωστο",
		DETAILEDINFO_SCORE_DISTRIBUTION : "Μοίρασμα σκόρ",
		DETAILEDINFO_GENERAL : "Λεπτομέρειες",
		DETAILEDINFO_MEMBERS : "Μελος",
		DETAILEDINFO_GRAPHS : "Γραφικά",
		DETAILEDINFO_RESOURCES : "Πόροι",
		DETAILEDINFO_FLEET_TAB : "Στόλος",
		DETAILEDINFO_TECH : "Έρευνα",
		DETAILEDINFO_FLEET_DETAIL : "Ποσοστό / (Μέσος όροςπαικτών) ανάμεσα σε όλες τις διαθέσιμες αναφορές",
		DETAILEDINFO_TECH_DETAIL : " Μέσος όρος από όλες τις πληροφορίες παικτών",
		DETAILEDINFO_PLANET_TAB : "Πλανήτες",
		DETAILEDINFO_MOON_TAB : "Φεγγάρια",
		DETAILEDINFO_ACTIVITIES : "Δραστηριότητες",
		DETAILEDINFO_NODATA : "Χωρίς στοιχεία.",
		DETAILEDINFO_ACTIVITY_DESCRIPTION : "Δείξε δραστηριότητες &1 συλλέχθηκαν από:",
		DETAILEDINFO_GALAXYVIEWS : "Όψεις Γαλαξία",
		DETAILEDINFO_SCANS : "Δράσεις κατασκοπείας",
		DETAILEDINFO_MESSAGES : "Μηνύματα παίκτη",
		DETAILEDINFO_COMBATS : "Αναφορές Μάχης",
		DETAILEDINFO_ALLYPAGE : "Επισκόπηση Συμμαχίας",
		DETAILEDINFO_MANUAL : "Χειροκίνητες εισαγωγές",
		DETAILEDINFO_START : "Αρχή",
		DETAILEDINFO_TO : "στο",
		DETAILEDINFO_TODAY : "Σήμερα",
		DETAILEDINFO_DATA_RESTRICTION : "περιορίζετε στο:",
		DETAILEDINFO_WEEKDAY_WEEKEND : "Σαββατοκύριακο",
		DETAILEDINFO_WEEKDAY_WORKINGDAY : "Εργάσιμη μέρα",
		DETAILEDINFO_WEEKDAY_MONDAY : "Δευτέρα",
		DETAILEDINFO_WEEKDAY_TUESDAY : "Τρίτη",
		DETAILEDINFO_WEEKDAY_WEDNESDAY : "Τετάρτη",
		DETAILEDINFO_WEEKDAY_THURSDAY : "Πέμπτη",
		DETAILEDINFO_WEEKDAY_FRIDAY : "Παρασκευή",
		DETAILEDINFO_WEEKDAY_SATURDAY : "Σαββάτο",
		DETAILEDINFO_WEEKDAY_SUNDAY : "Κυριακή",
		DETAILEDINFO_WEEKDAY_SHORTLENGTH : 3,
		DETAILEDINFO_PLAYER_CURRENTLY_ACTIVE : "Ο παίκτης είναι ενεργός",
		DETAILEDINFO_PLAYER_MESSAGES : "διαθέσιμα μηνύματα παίκτη",
		DETAILEDINFO_SHOW : "δείξε",
		DETAILEDINFO_NONE : "κανένα διαθέσιμο",
		DETAILEDINFO_ENTER_MANUALLY : "Δώστε δραστηριότητες για αυτόν τον παίκτη",
		DETAILEDINFO_PLAYER_SEEN_ON : "Ο παίκτης ήταν ενεργός στις",
		DETAILEDINFO_INSERT : "Τοποθέτησε",
		DETAILEDINFO_OGAME_SERVERTIMES : "Παρακαλώ σημειώστε: Όλες οι ημερομηνίες και οι χρόνοι αναφέρονται στους χρόνους OGame server!",
		DETAILEDINFO_DAY_VIEW : "όψη 24 ωρών",
		DETAILEDINFO_WEEK_VIEW : "εβδομαδιαία όψη",
		DETAILEDINFO_HOME_PLANET : "Μητρικός Πλανήτης",
		DETAILEDINFO_PLANETNAME : "Name",
		DETAILEDINFO_DEFENCE_SCORE : "Defence score",
		DETAILEDINFO_DEFENCE_SCORE_TOOLTIP : "Defence score = Fleet - Score + Research + Economy.<br/>All those statistics must be up to date to have a meaningful result!",
		DETAILEDINFO_SCORE_PER_SHIP : "Scores per ship",
		DETAILEDINFO_SHIPS : "Number of ships",
		DETAILEDINFO_DATE_IN_FUTURE : "Do not maintain times which are not in the past.",
		ADMIN_TITLE : "Διαχείριση του Galaxytool",
		ADMIN_DISCLAMER : "Προσοχή: Τρέξτε οποιοδήποτε από αυτά τα σκριπτ με δικό σας ρίσκο! Τα περισσότερα από αυτά διαγράφουν δεδομένα.",
		ADMIN_INCONSISTENCIES : "Ασυνέπειες στη βάση δεδομένων",
		ADMIN_PLANETS : "Πλανήτες στη θέση 0 η περισσότερο απο 15",
		ADMIN_GALAXIES : "Διαγράψτε γαλαξίες μεγαλύτερους απο &1 ",
		ADMIN_PLAYERS : "Διαγράψτε παίκτες χωρίς OGame ID παίκτη - οδηγεί σε διπλές εγγραφές παικτών",
		ADMIN_REPORTS : "Διαγράψτε τις αναφορές από πλανήτες που δεν υπάρχουν πλέον",
		ADMIN_MISC : "Διάφορα",
		ADMIN_RESET : "Reset Galaxytool (μόνο οι καταστάσεις παικτών και IP δεν διαγράφονται)",
		ADMIN_OLD_PLAYERS : "Διαγράψτε εγγραφές παικτών μεγαλύτερες από &1 μέρες",
		ADMIN_OLD_REPORTS : "Διαγράψτε αναφορές μεγαλύτερες από &1 μέρες",
		ADMIN_LOADING : "Μην κλείσετε αυτό το παράθυρο ενώ η σελίδα φορτώνει.",
		ADMIN_STATUS : "Θέση των αιτημάτων σας",
		ADMIN_SELECTION : "Τουλάχιστον μια είσοδος πρέπει να επιλεχτεί",
		ADMIN_SAFETY : "Είστε βέβαιοι ότι θέλετε να τρέξετε αυτό(α) το(α) script(s) ?",
		ADMIN_DONE : "έγινε",
		ADMIN_NOTBD : "τίποτα να γίνει",
		ADMIN_OLD_GALAXIES : "Διαγράψτε ενημερώσεις γαλαξία που είναι μεγαλύτερες από &1 μέρες",
		ADMIN_UNUSED_PLAYERS : "Διαγράψτε παίκτες που δεν εμφανίζονται σε κανένα γαλαξία",
		ADMIN_OLD_ACTIVITIES : "Διαγράψτε δραστηριότητες παίκτη μεγαλύτερες από &1 μέρες",
		ADMIN_OLD_COMBATS : "Αφαίρεση αναφορών μάχης παλαιότερες από &1 ημέρες",
		ADMIN_OLD_INGAME_MSG : "Αφαίρεση μυνήματα παιχνιδιού παλαιότερα από &1 ημέρες",
		ADMIN_OGAME_API : "Load public data from OGame into the Galaxytool",
		ADMIN_OGAME_ALL_DATA : "Σύνολο διαθέσιμων πληροφοριών",
		ADMIN_OGAME_GALAXY_DATA : "Προβολή Γαλαξία",
		ADMIN_OGAME_STATISTICS_DATA : "Στατιστικά",
		ERRORPAGE_PAGEFORWARD : "Πατήστε εδώ εάν ο φυλλομετρητής δεν υποστηρίζει page forwarding",
		ERRORPAGE_PERMISSION_DENIED : "Δεν έχετε άδεια να εισέλθετε σε αυτήν την σελίδα. Κάντε κλίκ για να επιστρέψετε.",
		FLEETS_TITLE : "OGame Galaxytool - Κινήσεις Στόλου",
		FLEETS_ACTUAL_FLEETS : "Τρέχων κινήσεις στόλου",
		FLEETS_YES : "Ναι",
		FLEETS_NO : "Μόνο πλανήτες με σημειώσεις",
		FLEETS_DETAILS : "Λεπτομέρειες",
		FLEETS_MISSION_EXPEDITION : "Αποστολή",
		FLEETS_MISSION_COLONIZATION : "Αποίκιση",
		FLEETS_MISSION_RECYCLE : "Ανακύκλωση Πεδίου Συντριμιών",
		FLEETS_MISSION_TRANSPORT : "Μεταφορά",
		FLEETS_MISSION_DEPLOYMENT : "Παράταξη",
		FLEETS_MISSION_ESPIONAGE : "Κατασκοπεία",
		FLEETS_MISSION_ACS_DEFEND : "Άμυνα ACS",
		FLEETS_MISSION_ATTACK : "Επίθεση",
		FLEETS_MISSION_ACS_ATTACK : "Επίθεση ACS",
		FLEETS_MISSION_MOON_DESTRUCTION : "Καταστροφή Φεγγαριού",
		FLEETS_MISSION_MISSILE_ATTACK : "Πυραυλική Επίθεση",
		FLEETS_NO_DATA : "Δεν βρέθηκαν δεδομένα",
		FLEETS_FLEET : "Fleet",
		FLEETS_ALL_FLEETS : "Show all fleet movements",
		COMBAT_REPORT_OUDATED_GALAXYVIEW : "Τα δεδομένα του Γαλαξία ειναι ετεροχρονισμένα. Παρακαλώ επισκεφτείτε την προέλευση της μάχης και συντεταγμένες στόχου πρώτα!",
		MESSAGES_TITLE : "OGame Galaxytool - OGame Μυνήματα",
		MESSAGES_PLAYERNAME : "Όνομα Παίκτη",
		MESSAGES_SUBJECT : "Θέμα",
		MESSAGES_DATE : "Ημερομηνία",
		MESSAGES_FILTER : "Φίλτρο",
		MESSAGES_DELETE : "Διαγραφή μυνήματος",
		MESSAGES_PUBLISH_DETAIL : "Δημοσιοποίηση μυνήματος προσθέτοντας το περιεχόμενο του μυνήματος στο κείμενο αναφοράς του παίκτη.",
		MESSAGES_PUBLISH_HEADER : "&sender έστειλε ένα μύνημα στον &recipient στίς &date:\n\n &message",
		MESSAGES_PLAYER_FILTER : "Μυνήματα για τον παίκτη:",
		MESSAGES_CONTENT : "Content",
		COMBATS_TITLE : "OGame Galaxytool - Αναφορές μάχης",
		COMBATS_ATTACKER : "Επιτιθέμενος",
		COMBATS_DEFENDER : "Αμυνόμενος",
		COMBATS_DATE : "Ημερομηνία",
		COMBATS_OWNER : "Ιδιοκτήτης",
		COMBATS_WINNER : "Νικητής",
		COMBATS_COMBATREPORT : "Αναφορά Μάχης",
		COMBATS_COMBAT_AT : "Μάχη στο",
		COMBATS_LOST_UNITS : "Απώλειες",
		COMBATS_LOOT : "Λάφυρα",
		COMBATS_DEBRIS : "Πεδίο Συντριμιών",
		COMBATS_AND : "και",
		COMBATS_PUBLISH : "Κάνε αυτή την αναφορά Δημόσια",
		COMBATS_UNPUBLISH : "Απέσυρε την δημόσια αναφορά (γίνεται προσωπική και πάλι)",
		COMBATS_DELETE : "Διαγραφή αναφοράς",
		COMBATS_CHECK_ALL : "Επιλογή Όλων",
		COMBATS_UNCHECK_ALL : "Αποεπιλογή Όλων",
		COMBATS_WITH_SELECTED : "Με τις επιλεγμένες",
		COMBATS_PUBLIC_REPORTS : "Δημόσιες αναφορές",
		COMBATS_YES : "Ναι",
		COMBATS_NO : "Μόνο πλανήτες με σημειώσεις",
		COMBATS_SEARCH_OPTIONS : "Ρυθμίσεις Αναζήτησης",
		COMBATS_SEARCH : "Αναζήτηση",
		COMBATS_RESET : "Καθαρισμός",
		COMBATS_COORDINATES : "Συντεταγμένες",
		COMBATS_INVALID_GALAXY_ENTERED : "Εισάγατε Άκυρο Γαλαξία",
		COMBATS_INVALID_SYSTEM_ENTERED : "Εισάγατε Άκυρο Σύστημα",
		COMBATS_INVALID_PLANET_ENTERED : "Εισάγατε Άκυρο Πλανήτη",
		COMBATS_GALAXY_FROM_TO : "Γαλαξίας",
		COMBATS_SYSTEM_FROM_TO : "Σύστημα",
		COMBATS_PLANET_FROM_TO : "Πλανήτης",
		COMBATS_APPLY : "Εφαρμογή",
		COMBATS_COMBAT_SUMMARY : "Σύνοψη αναφοράς μάχης",
		COMBATS_DOWNLOAD_CSV : "Κατεβάστε σαν CSV αρχείο",
		REPORT_ARCHIVE_TITLE : "Κατάλογος αναφορών",
		REPORT_ARCHIVE_COORDINATES : "Συντεταγμένες",
		REPORT_ARCHIVE_SCANTIME : "Ώρα Σάρωσης",
		REPORT_ARCHIVE_DELETE : "Διαγραφή των καταχωρήσεων",
		REPORT_ARCHIVE_CONFIRM_DELETE : "Είστε σίγουροι ότι θέλετε να διαγράψετε τις καταχωρήσεις?",
		REPORT_ARCHIVE_GALAXY : "Γαλαξίας",
		REPORT_ARCHIVE_SYSTEM : "Σύστημα",
		REPORT_ARCHIVE_PLANET : "Πλανήτης",
		REPORT_ARCHIVE_MOON : "Φεγγάρι",
		REPORT_ARCHIVE_DETAILS : "Λεπτομέρειες",
		REPORT_ARCHIVE_RESOURCES : "Πόροι ανα ώρα",
		REPORT_ARCHIVE_HEADER_RESOURCES : "Πόροι",
		REPORT_ARCHIVE_DETAILS_FOR : "Κατάλογος αναφορών για &1 [&2] (&3)",
		REPORT_ARCHIVE_FLEET_CARGO : "Χωριτικότητα φορτίου του στόλου",
		REPORT_ARCHIVE_IRAK_RANGE : "Βεληνεκές Διαγαλαξιακών Πυραύλων",
		REPORT_ARCHIVE_CHART_TYPE : "Τύπος Γραφήματος",
		INSTALL_TITLE : "Galaxytool installation for version",
		INSTALL_PROGRESS : "Overall progress",
		INSTALL_STEP : "Step",
		INSTALL_CONTINUE : "Continue",
		INSTALL_VALIDATE : "Validate",
		INSTALL_STEP1 : "Welcome",
		INSTALL_STEP2 : "Writeable check",
		INSTALL_STEP3 : "Database settings",
		INSTALL_STEP4 : "OGame settings",
		INSTALL_STEP5 : "Galaxytool settings",
		INSTALL_STEP6 : "Admin password",
		INSTALL_STEP7 : "Install Galaxytool",
		INSTALL_STEP8 : "Finalize install",
		INSTALL_FILE_DELETE_CHECK : "Please delete install.php and update.php from your webserver.",
		INSTALL_STEP1_PHP_FAILED : "Your PHP version &1 is not working with this Galaxytool version",
		INSTALL_STEP1_FOPEN_FAILED : "Your PHP version does not allow to open webpages with FOPEN() command. This is required to consume the OGame API.",
		INSTALL_STEP1_WELCOME : "Welcome to the installation wizard of the Galaxytool. You will be guided through the installation of the Galaxytool.",
		INSTALL_STEP2_DESCRIPTION : "Make sure your config.php and attributes.php files have write permissions enabled.",
		INSTALL_STEP2_DESCRIPTION2 : "If you don't know, how to achieve this, please take a look here: &1",
		INSTALL_STEP2_FILE_NOT_WRITEABLE : "File is not writeable",
		INSTALL_STEP3_SERVER : "Database server",
		INSTALL_STEP3_USERNAME : "Όνομα Χρήστη",
		INSTALL_STEP3_PASSWORD : "Κωδικός",
		INSTALL_STEP3_DBNAME : "Database name",
		INSTALL_STEP3_PREFIX : "Tablename prefix",
		INSTALL_STEP3_ENTER_PREFIX : "E.g. mytool_",
		INSTALL_STEP3_ENTER_SERVER : "Enter the server address. Contact your system admin if necessary. Usually the correct value is localhost.",
		INSTALL_STEP3_ENTER_USERNAME : "Enter the username for database access",
		INSTALL_STEP3_ENTER_PASSWORD : "Enter the password for database access",
		INSTALL_STEP3_ENTER_DBNAME : "Enter the database name which shall be used for installation (must exist)",
		INSTALL_STEP3_CONNECT_FAILED : "Could not establish connection to database server",
		INSTALL_STEP3_DB_FAILED : "Database &1 not found",
		INSTALL_STEP3_MYSQL_VERSION_FAILED : "MySQL version &1 is not working with this Galaxytool version",
		INSTALL_STEP4_URL : "OGame URL",
		OGAME_URL_DETAILS : "Please enter any URL you see when you are logged on to OGame. Based on that URL the tool will derive the OGame API address which can be used to fill data into the Galaxytool without the Galaxytoolbar. This API was introduced with OGame version 4.1.",
		INSTALL_STEP4_UNIVERSE : "OGame Universe",
		INSTALL_STEP4_DEF_TO_DEBRIS : "Defense to debris",
		INSTALL_STEP4_DEBRIS_RATE : "Debris rate",
		INSTALL_STEP4_SPEED_RATE : "Speed rate",
		INSTALL_STEP4_ENTER_UNIVERSE : "Enter your OGame universe name or number (case sensitive).",
		INSTALL_STEP4_UNIVERSE_MISSING : "You must define your universe",
		INSTALL_STEP4_ENTER_URL : "Enter your OGame universe address",
		INSTALL_STEP4_URL_MISSING : "You must define your OGame address",
		INSTALL_STEP4_URL_CHECK_FAILED : "Could not find OGame API at &1",
		INSTALL_STEP4_GETSETTINGS : "Fetch settings",
		INSTALL_STEP5_TOOLNAME : "Galaxytool name",
		INSTALL_STEP5_ENTER_TOOLNAME : "This is the name which will be shown at logon page to identify your Galaxytool",
		INSTALL_STEP5_LANGUAGE : "Default language",
		INSTALL_STEP5_EMAIL_TO : "Email To",
		INSTALL_STEP5_ENTER_EMAIL_TO : "Enter the email address where you would like to receive notifications about registrations",
		INSTALL_STEP5_EMAIL_FROM : "Email From",
		INSTALL_STEP5_ENTER_EMAIL_FROM : "This email address is shown as REPLY for all mails sent from the Galaxytool",
		INSTALL_STEP5_USE_PHPMAILER : "Use PHPMailer",
		INSTALL_STEP5_MAXSHOUTS : "Maximum number of shoutbox entries",
		INSTALL_STEP5_ENTER_USE_PHPMAILER : "Use PHPMailer if your server does not support sending emails by default",
		INSTALL_PHPMAILER_HOST : "SMPT Host",
		INSTALL_PHPMAILER_HOST_EXAMPLE : "e.g. smtp.provider.com",
		INSTALL_PHPMAILER_USER : "SMPT Username",
		INSTALL_PHPMAILER_USER_EXAMPLE : "e.g. user@provider.dcom",
		INSTALL_PHPMAILER_PASS : "SMPT password",
		INSTALL_PHPMAILER_SECURE : "Authentification method (e.g. ssl)",
		INSTALL_PHPMAILER_PORT : "SMTP Port",
		INSTALL_STEP6_INTRO : "Please define a password for the <strong>admin</strong> account which you have to use for your first logon to the Galaxytool after the installation.",
		INSTALL_STEP7_CONFIG : "Configuration file created",
		INSTALL_STEP7_CONFIG_FAILED : "Configuration file not created",
		INSTALL_STEP7_ATTRIBUTES : "Attributes file created",
		INSTALL_STEP7_ATTRIBUTES_FAILED : "Attributes file not created",
		INSTALL_STEP7_CREATED_TABLES : "Database tables created",
		INSTALL_STEP8_INTRO : "You have successfully installed the Galaxytool!",
		INSTALL_STEP8_LOAD_DATA : "Downloading OGame data ...",
		INSTALL_STEP8_LOAD_DATA_FINISHED : "Download of OGame data finished",
		INSTALL_STEP8_DELETE_FILE : "You should now delete the installation files install.php and update.php from your webserver.",
		INSTALL_STEP8_LOGON : "Please logon with the <strong>admin</strong> user and the password you defined earlier.",
		UPDATE_START : "Starting update to version &1",
		UPDATE_STEP_DONE : "Done",
		UPDATE_TITLE : "Galaxytool update for version",
		UPDATE_STEP1_WELCOME : "Welcome to the update wizard of the Galaxytool. You will be guided through the update of the Galaxytool.",
		UPDATE_STEP1_BACKUP_FILES : "As a first step, make a backup of your <strong>config</strong> folder! You will have to replace the configuration content in case of errors.",
		UPDATE_STEP1_BACKUP_DB : "Then make a <a href=\"http://www.ehow.com/how_2036600_create-database-php.html\">backup</a> of your database.",
		UPDATE_STEP1_PROCEED : "Once the backups have been done, you can proceed with your update.",
		UPDATE_STEP1 : "Welcome",
		UPDATE_STEP2 : "Galaxytool settings",
		UPDATE_STEP2_OLD_VERSION : "Previous Galaxytool version",
		UPDATE_STEP3 : "Update Galaxytool",
		UPDATE_STEP3_UPDATE_RUNNING : "Update running, please wait...",
		UPDATE_STEP4 : "Finalize Update",
		UPDATE_STEP4_INTRO : "You have successfully updated the Galaxytool!",
		UPDATE_STEP4_UPDATE_DONE : "Update steps performed.",
		UPDATE_FAILED : "Update failed.",
		GALAXYTOOL_DUMMY_TEXT : "dummy"
	})
);