define(
	({
		REPORT_WHEN : "v",
		RESOURCES_ON : "Suroviny na",
		PLAYER_BANNED : "b",
		PLAYER_VACATION_MODE : "z",
		PLAYER_NOOB : "n",
		PLAYER_INACTIVE : "i",
		PLAYER_LONG_INACTIVE : "I",
		PLAYER_OUTLAW : "o",
		L_USERNAME : "Uživatelské jméno",
		L_PASSWORD : "Heslo",
		L_LOGINFAILURE : "Uživatelské jméno nebo heslo je nesprávné, nebo nemáte dosud aktivován účet.",
		L_TOKENFAILURE : "Your logon key is wrong or your account is not activated yet.",
		L_LOGINTEXT : "Prosím, přihlašte se.",
		L_LANGUAGE : "Dostupné jazyky:",
		L_TIMEOUT : "Čas spojení vypršel!",
		L_REGISTER : "Registrace",
		L_PWLOST : "Zapomenuté heslo",
		INDEX_TITLE : "OGame Galaxietool - Přehled",
		INDEX_INFO : "Informace",
		INDEX_ENTRIES : "Počet všech systémů",
		INDEX_ENTRIES_LASTWEEK : "Nové systémy za minulý týden",
		INDEX_ENTRIES_TO_OLD : "Systémy starší než jeden měsíc",
		INDEX_REGISTERED_USERS : "Registrovaní uživatelé",
		INDEX_PAGEFORWARD : "Jestliže Váš prohlížeč nepodporuje přesměrovávání stránek, klikněte prosím zde.",
		INDEX_NOTICES : "Poznámky",
		INDEX_PLAYERS : "Statistika hráčů",
		INDEX_ALLIES : "Statistika spojenců",
		INDEX_REPORTS : "Špionážní zprávy",
		INDEX_VERSION : "Kontrola nové verze ke stažení",
		INDEX_LATEST_VERSION : "Novější verze není dostupná",
		INDEX_SHOUTBOX : "Shoutbox",
		INDEX_NOENTRY : "Žádný vzkaz",
		INDEX_COMMENT : "Váš vzkaz",
		INDEX_INSERT : "Vložit",
		INDEX_UMOD : "Hráčů se Zmraženým účtem",
		INDEX_NO_MOONS : "Počet Měsíců",
		INDEX_NO_EMPTY_SYSTEMS : "Počet prázdných systémů",
		INDEX_NO_FULL_SYSTEMS : "Počet zcela zaplněných systémů",
		INDEX_NO_TARGETS : "Počet možných cílů",
		INDEX_USERINFO : "Uživatelé",
		INDEX_ONLINE : "Nyní online",
		INDEX_TODAY : "Dnes online",
		INDEX_ALL : "Celkový počet přihlášení",
		GENERAL_LOAD_FORM : "Načíst formulář",
		GENERAL_SAVE_FORM : "Uložit formulář",
		GENERAL_SAVE_AS_TEXT : "Uložit jako",
		GENERAL_SAVE : "Uložit",
		INDEX_USERMANAGEMENT : "Activation Overview",
		INDEX_NEEDADMIN : "Accounts to unlock",
		INDEX_NEEDEMAIL : "Unvalidated Accounts",
		INDEX_TOOLBAR_INFO : "Galaxytool plugin information",
		INDEX_TOOLBAR_URL : "Galaxytool URL",
		INDEX_TOOLBAR_VERSION_REQUIRED : "Requires at least Galaxytool plugin version",
		INDEX_TOOLBAR_INSTALL_GUIDE : "Installation instructions for plugin",
		INDEX_TOOLBAR_TOKEN : "Logon key",
		INDEX_TOOLBAR_NEW_TOKEN : "Get new key",
		INDEX_PLAYERS_WITH_N_PLANETS : "Players with more than &1 planets",
		INDEX_GETTING_STARTED : "Getting started with the Galaxytool",
		INDEX_GETTING_STARTED1 : "Welcome to the Galaxytool!",
		INDEX_GETTING_STARTED2 : "The Galaxytool will help you to analyze what is going on in your OGame universe &1",
		INDEX_GETTING_STARTED3 : "Before you can actually analyze data you have to insert it first. For this you require a browser plugin like the &1 for Firefox.",
		INDEX_GETTING_STARTED4 : "After you installed the plugin, you navigate through your OGame pages as usual and you will see a small status window whenever something was sent to your Galaxytool.",
		INDEX_GETTING_STARTED5 : "Once the plugin inserted data into the Galaxytool, you can start to analyze where the players have their colonies, how many colonies they have, what reports exist or when they are active the most.",
		INDEX_GETTING_STARTED6 : "But it will also help you to analyze how you are progressing if you compare yourself against your competitors or by analyzing your combat reports to see how much you raided during the last days or weeks.",
		INDEX_GETTING_WIKIPAGE : "There are many more features within the Galaxytool.",
		INDEX_GETTING_WIKIPAGE2 : "Check them out at our wiki page.",
		INDEX_GETTING_BOARD : "For feedback or ideas you can use our board:",
		INDEX_GETTING_CHAT1 : "Or visit us at the chatroom:",
		INDEX_GETTING_CHAT2 : "We are not online 24/7 but spare a lot of our free time there, so be patient.",
		INDEX_CLOSE : "Close",
		INDEX_LOGIN : "Login",
		GENERAL_REQUIRED_FIELDS : "Please fill all required fields",
		INDEX_MESSAGES : "Messages",
		INDEX_EXAMPLE : "Example",
		INDEX_INVALID_DATA : "Invalid data",
		GENERAL_COLUMN_HIDE_TITLE : "Manage columns",
		GENERAL_COLUMN_HIDE_INFO : "Please select which columns you want to see in the table.",
		GENERAL_ENTRIES_DELETED : "&1 entries deleted",
		GENERAL_APPLY : "Apply",
		STARTPAGE_GALAXYTOOL_DESCR : "<em>Galaxytool</em> is a tool for the browser game OGame.",
		GENERAL_OVERWRITE : "Overwrite duplicate entry",
		GENERAL_OVERWRITE_QUESTION : "Overwrite?",
		INDEX_OWN_LOGINS : "Your logins",
		GENERAL_OPEN_IN_NEW_WINDOW : "Otevřít odkaz v novém okně",
		GENERAL_UNIT_OF_MEASURE_DAYS : "Days",
		PROGRAM_NAME : "OGame Galaxytool",
		SHORTNAME : "Galaxytool",
		BACK_INDEX : "Zpět na hlavní stranu",
		UNIVERSE : "Vesmír",
		MENU_INFO_LINKS : "Informace",
		MENU_PAGE : "Přehled",
		MENU_DB_SEARCH : "Vyhledat v databázi",
		MENU_DB_NOTICES : "Vyhledat v poznámkách",
		MENU_DB_REPORTS : "Vyhledat ve zprávách",
		MENU_GALAXYVIEW : "Prohlédnout Galaxie",
		MENU_STATISTICS : "Statistiky",
		MENU_ALLYHISTORY : "Historický přehled",
		MENU_FLEET_MOVEMENTS : "Pohyby letek",
		MENU_COMBAT_REPORTS : "Bitevní zprávy",
		MENU_MESSAGES : "Herní zprávy",
		MENU_OPTION_LINKS : "Možnosti",
		MENU_DB_REFRESH : "Vložit do databáze",
		MENU_NOTICES : "Poznámky",
		MENU_DB_STATUS : "Stav databáze",
		MENU_USEROPTIONS : "Správa uživatelů",
		MENU_USEROPTIONS2 : "Uživatelské volby",
		MENU_USEROPTIONS3 : "Informace o uživateli",
		MENU_ADMIN : "Administrace",
		MENU_LOGOUT : "Odhlášení",
		MENU_STUFF : "Různé",
		MENU_FORUM_THREAD : "Vývojářské fórum",
		MENU_DOWNLOADPAGE : "Download",
		MENU_LANGUAGE : "Jazyk",
		MENU_HELP : "Nápověda",
		MENU_TOOLOPTIONS : "Volby Galaxytool",
		PARSER_INFO1 : " bylo vloženo do databáze",
		PARSER_ERROR1 : "Nepodařilo se vložit následující souřadnice:",
		PARSER_ERROR2 : "Nelze nalézt v databázi!",
		PARSER_ERROR3 : "Nelze nalézt databázový server!",
		PARSER_WRONG_UNIVERSE : "Špatný Vesmír - aktuální: \"&1\" očekávaný: \"&2\"",
		SHOW_TITLE : "OGame Galaxytool - Vyhledánání",
		SHOW_SEARCH : "Vyhledat v databázi",
		SHOW_ALLYSYMBOL : "Alianční značka",
		SHOW_PLAYERNAME : "Jméno hráče",
		SHOW_MOONS : "Pouze planety s Měsícem",
		SHOW_NOTICES : "Pouze planety s poznámkami",
		SHOW_COLONIES : "Pouze planety vhodné ke kolonizaci",
		SHOW_YES : "Ano",
		SHOW_NO : "Ne",
		SHOW_SEARCHRANGE : "Vzdálenost",
		SHOW_SEARCH_IN : "Vyhledat v galaxii",
		SHOW_FROM_SYSTEM : "od systému",
		SHOW_FROM_PLANET : "od pozice planety",
		SHOW_TO : "do",
		SHOW_DESCRIPTION : "Můžete použít zástupné znaky pro jména aliancí a hráčů. Tak můžete vyhledat všechny hráče jejichž jméno obsahuje &quot;název&quot; .<br />Vyplňte pouze ta pole, která potřebujete.",
		SHOW_SORT_BY : "Seřadit podle",
		SHOW_GALASYSTEM : "Galaxie/Systému",
		SHOW_ALLYNAME : "Jména Aliance",
		SHOW_SEARCHBUTTON : "Vyhledat",
		SHOW_ADDRESS : "Adresa",
		SHOW_ALLYSORT : "Aliance",
		SHOW_PLANET : "Jméno planety",
		SHOW_STATUS : "Stav",
		SHOW_CURRENTNESS : "Poslední aktualizace",
		SHOW_PLAYER_STATUS : "Stav hráče",
		SHOW_PLAYER_STATUS1 : "vše",
		SHOW_PLAYER_STATUS2 : "možné cíle",
		SHOW_PLAYER_STATUS3 : "neaktivní",
		SHOW_HITS : "Záznamů",
		SHOW_OF : "na",
		SHOW_ASC : "vzestupně",
		SHOW_DESC : "sestupně",
		SHOW_RESULTS : "záznamů na stránku",
		SHOW_MOON : "Měsíc",
		SHOW_UKMOONSIZE : "neznámo",
		SHOW_DF : "DF",
		SHOW_DF_LONG : "Pole trosek",
		SHOW_METAL : "M",
		SHOW_METAL_LONG : "Kov",
		SHOW_CRYSTAL : "C",
		SHOW_CRYSTAL_LONG : "Krystaly",
		SHOW_BOTH : "obojí dohromady",
		SHOW_AT_LEAST : "(nejméně)",
		SHOW_DATE : "Datum",
		SHOW_DATE_0 : "nezáleží",
		SHOW_DATE_1 : "starší než",
		SHOW_DATE_2 : "novější než",
		SHOW_RANK : "Pořadí",
		SHOW_FRANK : "Pořadí letky",
		SHOW_MEMBERS : "Členové",
		SHOW_NOTRANKED : "Není mezi prvními 1500.",
		SHOW_NOTICERES : "Poznámky",
		SHOW_REPORTS : "Pouze planety se zprávami",
		SHOW_REPORTS_SHORT : "Zprávy",
		SHOW_NOTHING : "Nenalezen žádný záznam",
		SHOW_ALLIANCE_STATUS : "Stav Aliance",
		SHOW_NO_STATUS : "Stav není k dispozici",
		SHOW_NAP : "NAP",
		SHOW_ALLIED : "Spojenec",
		SHOW_WAR : "Válka",
		SHOW_BOYCOTT : "Bojkot",
		SHOW_NEUTRAL : "Neutrál",
		SHOW_OWN : "Vlastní Aliance",
		SHOW_WING : "Wing",
		SHOW_EXT_OPTIONS1 : "Ukázat více možností pro vyhledávání podle vzdálenosti, pořadí, data nebo pole trosek.",
		SHOW_EXT_OPTIONS2 : "Ukázat více možností pro vyhledávání podle kolonií, Měsíců, zpráv, poznámek, stavu hráčů a diplomacie.",
		SHOW_EXT_OPTIONS3 : "Ukázat více možností pro třídění nalezených výsledků.",
		SHOW_EXTENDED : "advanced search",
		SHOW_MOON_SELECTION : "Planet with moon",
		SHOW_REPORT_SELECTION : "Planet with report",
		SHOW_FILTER_BY : "Exclude from the list",
		SHOW_FILTER_NONE : "nic",
		SHOW_PLAYERS_WITHOUT_PROGRESS : "Show players without score changes within the last few days",
		STATUS_TITLE : "OGame Galaxytool - Stav",
		STATUS_DB_STATUS : "Stav databáze",
		STATUS_COLOR : "Barva",
		STATUS_AGE1 : "Záznamy 1 den staré.",
		STATUS_AGE2 : "Záznamy 2 - 4 dny staré.",
		STATUS_AGE3 : "Záznamy 4 - 7 dní staré.",
		STATUS_AGE4 : "Záznamy 1 - 2 týdny staré.",
		STATUS_AGE5 : "Záznamy 2 - 4 týdny staré.",
		STATUS_AGE6 : "Záznamy starší než 1 měsíc!",
		STATUS_AGE7 : "Žádné dostupné záznamy.",
		STATUS_ON : "on",
		STYLES_COLOR1 : "Barva 1",
		STYLES_COLOR2 : "Barva 2",
		STYLES_COLOR3 : "Barva 3",
		STYLES_COLOR4 : "Barva 4",
		STYLES_COLOR5 : "Barva 5",
		STYLES_COLOR6 : "Barva 6",
		STYLES_COLOR7 : "Barva 7",
		STATUS_DB_LEGEND : "Legend",
		STATUS_GALAXY : "Galaxy Overview",
		USER_TITLE : "Správa uživatelů",
		USER_NAMES : "Uživatel",
		USER_ERROR : "Chyba",
		USER_NEWUSER : "Nový uživatel",
		USER_OPTIONS : "Volby",
		USER_USERNAME : "Uživatelské jméno",
		USER_PASSWORD : "Heslo",
		USER_PASSWORD_CONFIRM : "Potvrdit heslo",
		USER_GALAXY : "Galaxie",
		USER_SEARCH : "Vyhledat",
		USER_INSERT : "Vložit",
		USER_DELETE : "Smazat",
		USER_DELETE_ENTRY : "Chcete smazat tohoto uživatele: ",
		USER_STATUS : "Prohlédnout statistiky",
		USER_STYLES : "Upravit vzhled",
		USER_SUBMIT : "Odeslat",
		USER_RESET : "Resetovat",
		USER_YES : "Ano",
		USER_NO : "Ne",
		USER_STYLEPATH : "Cesta k styles.css",
		USER_PROBES : "Prohlédnout/Odeslat špionážní zprávy",
		USER_EMAIL : "Email",
		USER_ERROR1 : "Chybné heslo nebo neplatný email.",
		USER_ERROR2 : "Neplatný Email.",
		USER_INGAME : "Jméno ve hře",
		USER_ALLYTAG : "Alianční značka",
		USER_ALLYHISTORY : "Historický přehled",
		USER_DIPLOMATIC : "Změnit Diplomatický stav",
		USER_STATSPAGE : "počet záznamů na statistické stránce",
		USER_LINKS : "Odkazy",
		USER_LINKS2 : "Format:<br>text;url<br>text2;url2<br>text3;url3",
		USER_EXPORT_TITLE : "Export barev (BB Codes)",
		USER_BB_COORDINATES : "Souřadnice",
		USER_BB_MOON : "Měsíc",
		USER_BB_DEBRIS : "Pole trosek",
		USER_BB_ALLY : "Alianční jméno",
		USER_BB_ALLYDETAILS : "Detaily Aliance",
		USER_BB_PLAYERNAME : "Jméno hráče",
		USER_BB_BANNED : "bann",
		USER_BB_VACATION : "zmrazený účet",
		USER_BB_NOOB : "noob",
		USER_BB_INACTIVE : "Neaktivní",
		USER_BB_LONGINACTIVE : "Dlouho neaktivní",
		USER_DELETION : "Smaž",
		USER_FLEETINFO : "Pohyby letek",
		USER_ACTIVITIES : "Aktivity hráče",
		USER_MAINTENANCE : "Údržba Galaxytoolu",
		USER_MANAGEMENT : "Správa uživatelů",
		USER_DELETE_MY_COMBAT_REPORTS : "Smazat mé bitevní zprávy",
		USER_DELETE_MY_MESSAGES : "Smazat mé zprávy",
		USER_DELETE_MY_FLEETMOVES : "Smazat mé pohyby letek",
		USER_DELETE_MY_COMBAT_REPORTS_LIMITED : "Delete my combat reports older than &1 days",
		USER_DELETE_MY_MESSAGES_LIMITED : "Delete my messages older than &1 days",
		USER_TABLE_ENTRIES : "Number of search results for each page",
		USER_EXISTS : "User already exists",
		USER_BB_OUTLAW : "Outlaw",
		USER_INVALID_URL : "URL &1 seems to be invalid - URL will be ignored",
		VIEW_TITLE : "OGame Galaxytool - Přehled Galaxie",
		VIEW_NODATA : "Data nejsou dostupná.",
		VIEW_GALAXY : "Galaxie",
		VIEW_SYSTEM : "Systém",
		VIEW_POSITION : "Poz.",
		VIEW_PLANET : "Planeta",
		VIEW_MOON : "Měsíc",
		VIEW_TF : "DF",
		VIEW_PLAYER : "Hráč",
		VIEW_PLAYER_ADD : "(Pořadí / Stav)",
		VIEW_ALLY : "Aliance",
		VIEW_ALLY_ADD : "(Pořadí / Člen)",
		VIEW_METAL : "M",
		VIEW_CRYSTAL : "C",
		VIEW_COLONISED : "Planet obsazeno",
		VIEW_UKMOONSIZE : "neznámo",
		VIEW_BACK : "zpět",
		VIEW_NOTICE : "Poznámky",
		VIEW_REPORTS : "Zprávy",
		VIEW_MOONPHALANX : "Následující měsíce mohou skenovat tento systém",
		VIEW_NOMOONS : "Žádný Měsíc nenalezen",
		VIEW_IRAKS : "Následující planety mohou být zasaženy meziplanetárními raketami",
		VIEW_NOIRAKS : "Nenalezeny žádné meziplanetární rakety",
		VIEW_MOON_DESTROY_CHANCE : "Šance na zničení Měsíce",
		VIEW_CHANCE_WITH_ONE : "Šance s jednou Hvězdou smrti",
		VIEW_CHANCE_WITH_N : "Šance s",
		VIEW_DEATH_STARS : "Hvězda smrti",
		VIEW_DS_DESTROY_CHANCE : "Šance na ztrátu Hvězdy smrti",
		VIEW_TOP : "Nahoru",
		VIEW_GO : "go",
		VIEW_DIAMETER : "Diameter",
		PW_TITLE : "OGame Galaxytool - změna hesla",
		OLD_PASSWORD : "staré heslo",
		NEW_PASSWORD : "nové heslo",
		CONFIRM_NEW_PASSWORD : "potvrdit nové heslo",
		PW_MISMATCH : "Hesla se neshodují!",
		PW_ERROR : "Staré heslo bylo chybně zadané!",
		UPDATE_DONE : "Změna úspěšná.",
		TIMEZONE_OFFSET : "Vyrovnat časové pásmo se serverem",
		DELETE_ACCOUNT : "Smazat tento Galaxytool účet",
		DELETE_ACCOUNT_SAFETY_REQUEST : "Opravdu chcete smazat tento Galaxytool účet?",
		CH_PASSWD_AUTHORIZATION : "Autorizace",
		CH_PASSWD_ADMIN : "Admin",
		TIMEZONE_OGAME_OFFSET : "Časové pásmo OGame serveru",
		CH_PASSWD_USER_LANGUAGE : "Change to this language after logon",
		CH_PASSWD_USER_LANGUAGE_NO_CHANGE : "No change",
		CH_PASSWD_EXPAND : "Expanded",
		CH_PASSWD_COLLAPSE : "Collapsed",
		CH_PASSWD_HIDDEN : "Hidden",
		CH_PASSWD_GETTING_STARTED : "Show Getting Started Info after logon",
		CH_PASSWD_PLUGIN : "Show Plugin Info after logon",
		NOTICE_TITLE : "OGame Galaxytool - Poznámky",
		NOTICE_HEADER : "upravit poznámky",
		NOTICE_HEADER2 : "Upravit vlastní poznámky",
		NOTICE_PUBLIC : "Přístupné pro ostatní?",
		NOTICE_YES : "ano",
		NOTICE_NO : "ne",
		NOTICE_TEXT : "Text poznámky",
		NOTICE_SAVE : "Uložit",
		NOTICE_DELETED : "Záznam smazán",
		NOTICE_SAVED : "Záznam uložen.",
		NOTICE_RESULTS : "Všechny výsledky",
		NOTICE_USER : "Uživatel",
		NOTICE_DATE : "Datum",
		NOTICE_EDIT : "Upravit",
		NOTICE_DELETE : "Smazat",
		NOTICE_NEW : "Vytvořit vlastní záznam",
		NOTICE_NOTPUBLIC : "Poznámka není veřejná.",
		NOTICE_ALL : "vše",
		NOTICE_NONE : "nic",
		NOTICE_SEARCH : "Vyhledat v Poznámkách",
		NOTICE_SEARCH_SHORT : "Vyhledat",
		NOTICE_HITS : "Záznamů",
		NOTICE_SHOWRESULTS : "záznamů na stránku",
		NOTICE_OF : "vyp",
		NOTICE_NOTHING : "Nenalezen žádný záznam",
		NOTICE_CHARS : "Characters",
		NOTICE_PLAYERNAME : "Hráč",
		NOTICE_SHOWALL : "Ukázat všechny poznámky",
		REPORTS_TITLE : "OGame Galaxytool - Špionážní zprávy",
		REPORTS_RESOURCES : "Suroviny",
		REPORTS_FLEET : "Letky",
		REPORTS_DEFENCE : "Obrana",
		REPORTS_BUILDINGS : "Budovy",
		REPORTS_TECHNOLOGY : "Výzkum",
		REPORTS_MOON : "Měsíc",
		REPORTS_SEARCH : "Vyhledat ve špionážních zprávách",
		REPORTS_SEARCH_SHORT : "Vyhledat",
		REPORTS_HITS : "Záznamů",
		REPORTS_NOTHING : "Nenalezen žádný záznam",
		REPORTS_ADDRESS : "Adresa",
		REPORTS_CURRENTNESS : "Currentness",
		REPORTS_PLAYERNAME : "Jméno hráče",
		REPORTS_ALLY : "Spojenec",
		REPORTS_VIEW : "Prohlédnout zprávu",
		REPORTS_SEARCH_IN : "Vyhledat v Galaxii",
		REPORTS_FROM_SYSTEM : "od Systému",
		REPORTS_TO : "do",
		REPORTS_DELETE : "smazat",
		REPORTS_DELETED : "Záznam smazán",
		REPORTS_RESULTS : "záznamů na stránku",
		REPORTS_OF : "z",
		REPORTS_DATE : "Datum",
		REPORTS_DATE_0 : "nezáleží",
		REPORTS_DATE_1 : "starší než",
		REPORTS_DATE_2 : "novější než",
		REPORTS_NOTICES : "Poznámky",
		REPORTS_AT_LEAST_RESOURCES : "Suroviny (nejméně)",
		REPORTS_SEARCH_EXTENDED : "rozšířené vyhledávání",
		REPORTS_FLEET_RESIS : "Letka - skóre",
		REPORTS_DEFENCE_RESIS : "Obrana - skóre",
		REPORTS_ALL_RESIS : "celkem skóre",
		REPORTS_TECHS : "Technologie",
		REPORTS_UNKNOWN_ENTRIES : "neznámý záznam",
		REPORTS_PARTLY_INSERTED : "částečně vloženo",
		REPORTS_FOR_ALL_RES : "pro všechny suroviny",
		REPORTS_FOR_TF : "pro pole trosek",
		REPORTS_KT : "Malých transportérů",
		REPORTS_GT : "Velkých transportérů",
		REPORTS_SS : "Bitevních lodí",
		REPORTS_REC : "Recyklátorů",
		REPORTS_RAIDABLE : "poze cíle vhodné k útoku",
		REPORTS_ALL_RESOURCES : "všechny suroviny",
		REPORTS_STUFF : "Různé",
		REPORTS_SPEEDSIM : "Simulace pomocí Speedsim",
		REPORTS_DRAGOSIM : "Simulace pomocí Dragosim",
		REPORTS_STATUS : "Stav",
		REPORTS_ERROR : "Vyskytla se chyba",
		REPORTS_OWN_REPORTS : "Pouze mé zprávy",
		REPORTS_UPLOAD_BY : "Zprávy nahrál",
		REPORTS_DEPTH : "Podrobná zpráva",
		REPORTS_FLEET_SCORE : "Body letky",
		REPORTS_DEFENCE_SCORE : "Body obrany",
		REPORTS_HOURS : "hours",
		REPORTS_MAX_RESULTS_HIT : "Your query returned more than &1 hits. Only the first &1 results are show. Please adjust your search request to get less results.",
		REPORTS_OSIMULATE : "Simulate with OSimulate",
		REPORTS_SHOW_ONLY : "Show only",
		REPORTS_SHOW_PLANETS : "Planety",
		REPORTS_SHOW_MOONS : "Měsíce",
		REPORTS_OWNER : "Reports owned by",
		STATS_TITLE : "OGame Galaxytool - Statistiky",
		STATS_TBLHEAD : "Statistiky",
		STATS_RANK : "Pořadí",
		STATS_PLAYERNAME : "Jméno hráče",
		STATS_ALLYNAME : "Alianční značka Tag",
		STATS_SCORE : "Skóre",
		STATS_FLEET : "Letka",
		STATS_RESEARCH : "Výzkum",
		STATS_MEMBERS : "Členové",
		STATS_STATUS : "Stav",
		STATS_NOTHING : "Stav není k dispozici",
		STATS_NAP : "NAP",
		STATS_ALLIED : "Spojenec",
		STATS_WAR : "Válka",
		STATS_BOYCOTT : "Bojkot",
		STATS_NEUTRAL : "Neutrál",
		STATS_OWN : "Vlastní Aliance",
		STATS_WING : "Wing",
		STATS_UPDATE : "Záznam z",
		STATS_PLAYERSTATS : "Stav hráče",
		STATS_ALLYSTATS : "Stav Aliance",
		STATS_DELETE : "Chcete smazat tento záznam ?",
		STATS_CONFIRM_DELETE : "Opravdu chcete smazat tento záznam ?",
		STATS_CHANGE_PLAYER_STATUS : "Stav hráče",
		STATS_CHANGE_ALLIANCE_STATUS : "Stav Aliance",
		STATS_CHANGE_ALLIANCE_STATUS_HINT : "Všem členům této aliance byl vybrán stejný stav. Jakýkoli jiný předchozí stav bude změněn. Stav jednotlivých hráčů můžete měnit dodatečně.",
		STATS_UNKNOWN : "Zbytek",
		STATS_DETAILS : "Detaily pro",
		STATS_PLAYERSTATUS : "Stav hráče",
		STATS_IGNORE_STATUS : "vše",
		STATS_ACTIVE : "aktivní",
		STATS_INACTIVE : "Neaktivní",
		STATS_BANNED : "bann",
		STATS_VACATION : "zmrazený účet",
		STATS_NOOB : "noob",
		STATS_YES : "Ano",
		STATS_NO : "Pouze planety s poznámkami",
		STATS_SEARCH : "Vyhledat",
		STATS_SHOW_GRAPH : "Show details for score distribution",
		STATS_LONG_INACTIVE : "Dlouho neaktivní",
		STATS_STANDARD : "Standard Points",
		STATS_MILITARY : "Military Points",
		STATS_ECONOMY : "Economy",
		STATS_HONOUR : "Honour points",
		STATS_MILITARY_BUILD : "Military build",
		STATS_MILITARY_DESTROYED : "Military destroyed",
		STATS_MILITARY_LOST : "Military lost",
		REGISTER_REGISTRATE : "Registrace",
		REGISTER_LOGINNAME : "Přihlašovací jméno",
		REGISTER_PASSWORD : "Heslo",
		REGISTER_PASSWORD_CONFIRM : "Potvrzení hesla",
		REGISTER_EMAIL : "Email",
		REGISTER_INGAME : "Jméno ve hře",
		REGISTER_ALLYTAG : "Alianční značka",
		REGISTER_EMAILVERIFICATION : "Kontrola Emailu",
		REGISTER_EMAILTEXT : "Prosím, klikněte na tento odkaz k potvrzení Vaší registrace do programu Galaxytool.",
		REGISTER_ERROR1 : "Přihlašovací jméno již někdo používá.",
		REGISTER_ERROR2 : "Chyba při zasílání emailu. Prosím, kontaktujte administrátora.",
		REGISTER_ERROR3 : "Chyba při zasílání dat do databáze!",
		REGISTER_INFO1 : "Váš účet byl vytvořen.",
		REGISTER_INFO2 : "Prosím, klikněte na odkaz v emailu pro potvrzení Vaší registrace.",
		REGISTER_INFO3 : "Zřízení účtu potvrzeno. Administrátor Vám ho nyní aktivuje.",
		REGISTER_BUTTON : "Zpět na hlavní stranu",
		REGISTER_NEW_SUBJECT : "Nový uživatel byl zaregistrován",
		REGISTER_NEW_MAILTEXT : "Nový uživatel se zaregistroval.",
		REGISTER_BACK : "Zpět na první stránku",
		REGISTER_MISSING_FIELDS : "Vyplňte všechna požadovaná pole",
		REGISTER_ERROR4 : "Email address is not valid.",
		REGISTER_ERROR5 : "Passwords don't match.",
		REGISTER_PWS : "Password strength",
		REGISTER_PWS0 : "very weak",
		REGISTER_PWS1 : "weak",
		REGISTER_PWS2 : "good",
		REGISTER_PWS3 : "strong",
		REGISTER_PWS4 : "very strong",
		REGISTER_EMAIL_USED : "Email Address is already used",
		LOSTPW_TITLE : "Ztracené heslo",
		LOSTPW_INFO2 : "Nové heslo bylo vygenerováno a bylo Vám zasláno na Váš email.",
		LOSTPW_BUTTON1 : "dostat nové heslo",
		LOSTPW_BUTTON2 : "Zpět na hlavní stranu",
		LOSTPW_LOGINNAME : "Přihlašovací jméno",
		LOSTPW_EMAIL : "Email",
		LOSTPW_ERROR1 : "Chyba při zasílání dat do databáze!",
		LOSTPW_ERROR2 : "Nenalezen žádný shodný záznam!",
		LOSTPW_ERROR3 : "Chyba při zasílání emailu. Prosím, kontaktujte administrátora.",
		LOSTPW_EMAIL_SUBJECT : "Vyžadováno Vaše nové heslo",
		LOSTPW_EMAIL_TEXT1 : "Zde jsou Vaše nové přihlašovací údaje do Galaxytool",
		LOSTPW_EMAIL_TEXT2 : "Uživatelské jméno",
		LOSTPW_EMAIL_TEXT3 : "Heslo",
		LOSTPW_INFO1 : "You will receive an email to verify your password reset request.",
		LOSTPW_CONFIRM_RESET_SUBJECT : "Lost password?",
		LOSTPW_CONFIRM_RESET_MESSAGE : "Hello,\n\nyou requested a password reset for the Galaxytool. To generate a new password, click the following link:",
		USERINFO_TITLE : "OGame Galaxytool - Informace o uživateli",
		USERINFO_NAMES : "Všichni uživatelé tohoto nástroje",
		USERINFO_DETAIL : "detailní informace o",
		USERINFO_ERROR1 : "Žádný uživatel s tímto ID!",
		USERINFO_USERNAME : "Přihlašovací jméno",
		USERINFO_INGAME : "Jméno ve hře",
		USERINFO_EMAIL : "Email",
		USERINFO_ALLYTAG : "Aliance",
		USERINFO_STYLEPATH : "Skin",
		USERINFO_STATUS : "Stav",
		USERINFO_ACTIVATE : "Aktivovat hráče",
		USERINFO_LOGINS : "Počet přihlášení",
		USERINFO_LASTLOGIN : "Poslední přihlášení",
		USERINFO_DATA : "Informace o zadaných Systémech",
		USERINFO_NODATA : "Tento uživatel zatím nevložil žádný Systém!",
		USERINFO_GALAXY : "Galaxie",
		USERINFO_SYSTEMS : "Počet Systémů",
		USERINFO_IP : "IP adresa",
		USERINFO_LOGINTIME : "přihlášení",
		USERINFO_NOLOGIN : "Uživatel se zatím nepřihlásil.",
		USERINFO_LAST_GALAXYUPDATE : "Poslední vložený Přehled Galaxie",
		USERINFO_LAST_PUBLIC_NOTICE : "Poslední veřejná poznámka",
		USERINFO_LAST_PRIVATE_NOTICE : "Poslední soukromá poznámka",
		USERINFO_NUMBEROF_PUBLIC_NOTICE : "Počet veřejných poznámek",
		USERINFO_NUMBEROF_PRIVATE_NOTICE : "Počet soukromých poznámek",
		USERINFO_ACTIVATED : "Aktivováno účtů",
		USERINFO_ACTIVATIONTEXT : "Administrátor Galaxytool aktivoval Váš účet.\n\nUžijte si nástroj Galaxytool!",
		USERINFO_LAST_SUBMIT : "Inserted last data",
		ALLYHISTORY_TITLE : "OGame Galaxytool - Historie Aliance",
		ALLYHISTORY_TBLHEAD : "Historický přehled",
		ALLYHISTORY_PLAYERNAME : "Jméno hráče",
		ALLYHISTORY_ALLYNAME : "Aliance",
		ALLYHISTORY_LASTMONTH : "Minulý měsíc",
		ALLYHISTORY_ALL_DATA : "Všechny dostupné informace",
		ALLYHISTORY_SHOW : "Ukázat statistiky",
		ALLYHISTORY_TIMESPAN : "Období",
		ALLYHISTORY_PROGESS : "Vývoj",
		ALLYHISTORY_SCORE : "Body",
		ALLYHISTORY_FSCORE : "Bodů za letky",
		ALLYHISTORY_RSCORE : "Bodů za výzkum",
		ALLYHISTORY_MEMBER : "Členové",
		ALLYHISTORY_NOTHING : "žádné záznamy",
		ALLYHISTORY_DETAILS : "Detaily",
		ALLYHISTORY_SHOW_ADDRESS : "Souřadnice",
		ALLYHISTORY_ESCORE : "Economy",
		ALLYHISTORY_MSCORE : "Military Points",
		DETAILEDINFO_PLAYERINFO_TITLE : "Informace o hráči",
		DETAILEDINFO_ALLYINFO_TITLE : "Informace o alianci",
		DETAILEDINFO_PLAYERINFO_TBLHEAD : "Detailní informace o hráči",
		DETAILEDINFO_ALLYINFO_TBLHEAD : "Detailní informace o alianci",
		DETAILEDINFO_NO_ALLIANCE : "nic",
		DETAILEDINFO_SCORE : "Statistika bodů",
		DETAILEDINFO_FLEET : "Statistika letky",
		DETAILEDINFO_RESEARCH : "Statistika výzkumu",
		DETAILEDINFO_RANK : "Pořadí",
		DETAILEDINFO_POINTS : "Body",
		DETAILEDINFO_KNOWN_PLANETS : "známé planety",
		DETAILEDINFO_MOONS : "známých Měsíců",
		DETAILEDINFO_PHALANX_AREA : "Oblast Falangy",
		DETAILEDINFO_NO_PHALANX_AREA : "Senzor Falangy nenalezen",
		DETAILEDINFO_NOTICES : "Poznámky",
		DETAILEDINFO_NO_NOTICES : "Nenalezena žádná poznámka",
		DETAILEDINFO_PREVIOUS_ALLIANCES : "předchozí Aliance",
		DETAILEDINFO_RESOURCES_PER_HOUR : "Surovin za hodinu",
		DETAILEDINFO_RESOURCES_PER_DAY : "Surovin za den",
		DETAILEDINFO_RESOURCES_PER_WEEK : "Surovin za týden",
		DETAILEDINFO_RESOURCES_PER_MONTH : "Surovin za měsíc (30 dní)",
		DETAILEDINFO_METAL : "Kov",
		DETAILEDINFO_CRYSTAL : "Krystaly",
		DETAILEDINFO_DEUTERIUM : "Deuterium",
		DETAILEDINFO_UNKNOWN : "neznámý",
		DETAILEDINFO_SCORE_DISTRIBUTION : "Rozdělení bodů",
		DETAILEDINFO_GENERAL : "Detail",
		DETAILEDINFO_MEMBERS : "Člen",
		DETAILEDINFO_GRAPHS : "Grafy",
		DETAILEDINFO_RESOURCES : "Zdroje",
		DETAILEDINFO_FLEET_TAB : "Letka",
		DETAILEDINFO_TECH : "Výzkum",
		DETAILEDINFO_FLEET_DETAIL : "Součet / (hráči-průměr) ze všech dostupných zpráv",
		DETAILEDINFO_TECH_DETAIL : "Průměr všech dostupných informací o hráčích",
		DETAILEDINFO_PLANET_TAB : "Planety",
		DETAILEDINFO_MOON_TAB : "Měsíce",
		DETAILEDINFO_ACTIVITIES : "Aktivity",
		DETAILEDINFO_NODATA : "Data nejsou dostupná.",
		DETAILEDINFO_ACTIVITY_DESCRIPTION : "Ukaž aktivity o &1 shromážděné z:",
		DETAILEDINFO_GALAXYVIEWS : "Přehled Galaxie",
		DETAILEDINFO_SCANS : "Špionážní akce",
		DETAILEDINFO_MESSAGES : "Zprávy hráčů",
		DETAILEDINFO_COMBATS : "Bitevní zprávy",
		DETAILEDINFO_ALLYPAGE : "Přehled aliance",
		DETAILEDINFO_MANUAL : "Manuální vstupy",
		DETAILEDINFO_START : "Začátek",
		DETAILEDINFO_TO : "do",
		DETAILEDINFO_TODAY : "Dnes",
		DETAILEDINFO_DATA_RESTRICTION : "zakázáno pro:",
		DETAILEDINFO_WEEKDAY_WEEKEND : "Víkend",
		DETAILEDINFO_WEEKDAY_WORKINGDAY : "Všední den",
		DETAILEDINFO_WEEKDAY_MONDAY : "Pondělí",
		DETAILEDINFO_WEEKDAY_TUESDAY : "Úterý",
		DETAILEDINFO_WEEKDAY_WEDNESDAY : "Středa",
		DETAILEDINFO_WEEKDAY_THURSDAY : "Čtvrtek",
		DETAILEDINFO_WEEKDAY_FRIDAY : "Pátek",
		DETAILEDINFO_WEEKDAY_SATURDAY : "Sobota",
		DETAILEDINFO_WEEKDAY_SUNDAY : "Neděle",
		DETAILEDINFO_WEEKDAY_SHORTLENGTH : 3,
		DETAILEDINFO_PLAYER_CURRENTLY_ACTIVE : "Hráč je momentálně aktivní",
		DETAILEDINFO_PLAYER_MESSAGES : "dostupné zprávy hráčů",
		DETAILEDINFO_SHOW : "ukaž",
		DETAILEDINFO_NONE : "žádný k dispozici",
		DETAILEDINFO_ENTER_MANUALLY : "Zadejte aktivity tohoto hráče",
		DETAILEDINFO_PLAYER_SEEN_ON : "Hráč byl online v",
		DETAILEDINFO_INSERT : "Vlož",
		DETAILEDINFO_OGAME_SERVERTIMES : "Upozornění: Všechna data a časy se týkají času OGame serveru !",
		DETAILEDINFO_DAY_VIEW : "24-hodinový přehled",
		DETAILEDINFO_WEEK_VIEW : "týdenní přehled",
		DETAILEDINFO_HOME_PLANET : "Homeworld",
		DETAILEDINFO_PLANETNAME : "Name",
		DETAILEDINFO_DEFENCE_SCORE : "Defence score",
		DETAILEDINFO_DEFENCE_SCORE_TOOLTIP : "Defence score = Fleet - Score + Research + Economy.<br/>All those statistics must be up to date to have a meaningful result!",
		DETAILEDINFO_SCORE_PER_SHIP : "Scores per ship",
		DETAILEDINFO_SHIPS : "Number of ships",
		DETAILEDINFO_DATE_IN_FUTURE : "Do not maintain times which are not in the past.",
		ADMIN_TITLE : "Administrace Galaxytoolu",
		ADMIN_DISCLAMER : "Pozor:Spuštění jakéhokoliv z těchto skriptů na vlastní nebezpečí! Většina z nich maže data.",
		ADMIN_INCONSISTENCIES : "Nesrovnalosti v databázi",
		ADMIN_PLANETS : "Planety na pozici 0 nebo větší než 15",
		ADMIN_GALAXIES : "Smazat přehled galaxií od &1 ",
		ADMIN_PLAYERS : "Odstranit hráče bez OGame playerid- vede k duplicitní záměně hráčů",
		ADMIN_REPORTS : "Odstranit zpávy, ve kterých už planety neexistují",
		ADMIN_MISC : "Různé",
		ADMIN_RESET : "Resetovat Galaxytool (uživatel a IP se neodstraní)",
		ADMIN_OLD_PLAYERS : "Odstranit hráče starší než &1 dny",
		ADMIN_OLD_REPORTS : "Odstranit zprávy starší než &1 dny",
		ADMIN_LOADING : "Nezavírejte toto okno zatímco se stránka načítá.",
		ADMIN_STATUS : "Stav vašeho požadavku",
		ADMIN_SELECTION : "Nejméně jedna položka musí být vybrána",
		ADMIN_SAFETY : "Jste si opravdu jistý, že chcete pustit tento skript?",
		ADMIN_DONE : "hotovo",
		ADMIN_NOTBD : "nic co by mělo být uděláno",
		ADMIN_OLD_GALAXIES : "Odstranit předledy galaxií starší než &1 dny",
		ADMIN_UNUSED_PLAYERS : "Odstranit hráče, kteří se nevyskytují v žádném přehledu galaxie",
		ADMIN_OLD_ACTIVITIES : "Odstraň aktivity hráče starší než &1 dnů",
		ADMIN_OLD_COMBATS : "Remove combat reports older than &1 days",
		ADMIN_OLD_INGAME_MSG : "Remove ingame messages older than &1 days",
		ADMIN_OGAME_API : "Load public data from OGame into the Galaxytool",
		ADMIN_OGAME_ALL_DATA : "Všechny dostupné informace",
		ADMIN_OGAME_GALAXY_DATA : "Prohlédnout Galaxie",
		ADMIN_OGAME_STATISTICS_DATA : "Statistiky",
		ERRORPAGE_PAGEFORWARD : "Klikněte zde, pokud váš prohlížeč stránku ještě nepřesměroval",
		ERRORPAGE_PERMISSION_DENIED : "Nemáte povolení ke vstupu na tuto stránku. Klikněte pro návrat zpět.",
		FLEETS_TITLE : "OGame Galaxytool - Pohyby letek",
		FLEETS_ACTUAL_FLEETS : "Probíhající pohyby letek",
		FLEETS_YES : "Ano",
		FLEETS_NO : "Pouze planety s poznámkami",
		FLEETS_DETAILS : "Detaily",
		FLEETS_MISSION_EXPEDITION : "Expedice",
		FLEETS_MISSION_COLONIZATION : "Kolonizace",
		FLEETS_MISSION_RECYCLE : "Těžba",
		FLEETS_MISSION_TRANSPORT : "Transport",
		FLEETS_MISSION_DEPLOYMENT : "Rozmístění",
		FLEETS_MISSION_ESPIONAGE : "Špionáž",
		FLEETS_MISSION_ACS_DEFEND : "APP obrana",
		FLEETS_MISSION_ATTACK : "Útok",
		FLEETS_MISSION_ACS_ATTACK : "APP útok",
		FLEETS_MISSION_MOON_DESTRUCTION : "Zničení měsíce",
		FLEETS_MISSION_MISSILE_ATTACK : "Raketový útok",
		FLEETS_NO_DATA : "Data nenalezena",
		FLEETS_FLEET : "Fleet",
		FLEETS_ALL_FLEETS : "Show all fleet movements",
		COMBAT_REPORT_OUDATED_GALAXYVIEW : "Vaše data o galaxii jsou zastaralá. Prosím navštivte nejdřív výchozí a cílový systém!",
		MESSAGES_TITLE : "OGame Galaxytool - OGame Zprávy",
		MESSAGES_PLAYERNAME : "Jméno hráče",
		MESSAGES_SUBJECT : "Předmět",
		MESSAGES_DATE : "Datum",
		MESSAGES_FILTER : "Filtr",
		MESSAGES_DELETE : "Smazat zprávu",
		MESSAGES_PUBLISH_DETAIL : "Publikuj zprávu přidáním obsahu zprávy do upozornění pro hráče.",
		MESSAGES_PUBLISH_HEADER : "&sender poslal zprávu &recipient v &date:\n\n &message",
		MESSAGES_PLAYER_FILTER : "Zprávy pro hráče",
		MESSAGES_CONTENT : "Content",
		COMBATS_TITLE : "OGame Galaxytool - Bitevní zprávy",
		COMBATS_ATTACKER : "Útočník",
		COMBATS_DEFENDER : "Obránce",
		COMBATS_DATE : "Datum",
		COMBATS_OWNER : "Vlastník",
		COMBATS_WINNER : "Vítěž",
		COMBATS_COMBATREPORT : "Bitevní zpráva",
		COMBATS_COMBAT_AT : "Bitva na",
		COMBATS_LOST_UNITS : "Ztracené jednotky",
		COMBATS_LOOT : "Kořist",
		COMBATS_DEBRIS : "Trosky",
		COMBATS_AND : "a",
		COMBATS_PUBLISH : "Zveřejnit zprávu",
		COMBATS_UNPUBLISH : "Odveřejnit zprávu (opět soukromá)",
		COMBATS_DELETE : "Smazat zprávu",
		COMBATS_CHECK_ALL : "Označit vše",
		COMBATS_UNCHECK_ALL : "Odznačit vše",
		COMBATS_WITH_SELECTED : "S vybranými",
		COMBATS_PUBLIC_REPORTS : "Veřejné zprávy",
		COMBATS_YES : "Ano",
		COMBATS_NO : "Pouze planety s poznámkami",
		COMBATS_SEARCH_OPTIONS : "Možnosti hledání",
		COMBATS_SEARCH : "Hledej",
		COMBATS_RESET : "Reset",
		COMBATS_COORDINATES : "Souřadnice",
		COMBATS_INVALID_GALAXY_ENTERED : "Invalid Galaxy entered",
		COMBATS_INVALID_SYSTEM_ENTERED : "Invalid System entered",
		COMBATS_INVALID_PLANET_ENTERED : "Invalid Planet entered",
		COMBATS_GALAXY_FROM_TO : "Galaxy",
		COMBATS_SYSTEM_FROM_TO : "System",
		COMBATS_PLANET_FROM_TO : "Planet",
		COMBATS_APPLY : "Apply",
		COMBATS_COMBAT_SUMMARY : "Combat report summary",
		COMBATS_DOWNLOAD_CSV : "Download as CSV file",
		REPORT_ARCHIVE_TITLE : "Report archive",
		REPORT_ARCHIVE_COORDINATES : "Coordinates",
		REPORT_ARCHIVE_SCANTIME : "Scan time",
		REPORT_ARCHIVE_DELETE : "Delete these entries",
		REPORT_ARCHIVE_CONFIRM_DELETE : "Do you really want to delete these entries?",
		REPORT_ARCHIVE_GALAXY : "Galaxy",
		REPORT_ARCHIVE_SYSTEM : "System",
		REPORT_ARCHIVE_PLANET : "Planet",
		REPORT_ARCHIVE_MOON : "Moon",
		REPORT_ARCHIVE_DETAILS : "Details",
		REPORT_ARCHIVE_RESOURCES : "Surovin za hodinu",
		REPORT_ARCHIVE_HEADER_RESOURCES : "Suroviny",
		REPORT_ARCHIVE_DETAILS_FOR : "Report archive for &1 [&2] (&3)",
		REPORT_ARCHIVE_FLEET_CARGO : "Fleet cargo capacity",
		REPORT_ARCHIVE_IRAK_RANGE : "Interplanetary Missiles range",
		REPORT_ARCHIVE_CHART_TYPE : "Chart type",
		INSTALL_TITLE : "Galaxytool installation for version",
		INSTALL_PROGRESS : "Overall progress",
		INSTALL_STEP : "Step",
		INSTALL_CONTINUE : "Continue",
		INSTALL_VALIDATE : "Validate",
		INSTALL_STEP1 : "Welcome",
		INSTALL_STEP2 : "Writeable check",
		INSTALL_STEP3 : "Database settings",
		INSTALL_STEP4 : "OGame settings",
		INSTALL_STEP5 : "Galaxytool settings",
		INSTALL_STEP6 : "Admin password",
		INSTALL_STEP7 : "Install Galaxytool",
		INSTALL_STEP8 : "Finalize install",
		INSTALL_FILE_DELETE_CHECK : "Please delete install.php and update.php from your webserver.",
		INSTALL_STEP1_PHP_FAILED : "Your PHP version &1 is not working with this Galaxytool version",
		INSTALL_STEP1_FOPEN_FAILED : "Your PHP version does not allow to open webpages with FOPEN() command. This is required to consume the OGame API.",
		INSTALL_STEP1_WELCOME : "Welcome to the installation wizard of the Galaxytool. You will be guided through the installation of the Galaxytool.",
		INSTALL_STEP2_DESCRIPTION : "Make sure your config.php and attributes.php files have write permissions enabled.",
		INSTALL_STEP2_DESCRIPTION2 : "If you don't know, how to achieve this, please take a look here: &1",
		INSTALL_STEP2_FILE_NOT_WRITEABLE : "File is not writeable",
		INSTALL_STEP3_SERVER : "Database server",
		INSTALL_STEP3_USERNAME : "Uživatelské jméno",
		INSTALL_STEP3_PASSWORD : "Heslo",
		INSTALL_STEP3_DBNAME : "Database name",
		INSTALL_STEP3_PREFIX : "Tablename prefix",
		INSTALL_STEP3_ENTER_PREFIX : "E.g. mytool_",
		INSTALL_STEP3_ENTER_SERVER : "Enter the server address. Contact your system admin if necessary. Usually the correct value is localhost.",
		INSTALL_STEP3_ENTER_USERNAME : "Enter the username for database access",
		INSTALL_STEP3_ENTER_PASSWORD : "Enter the password for database access",
		INSTALL_STEP3_ENTER_DBNAME : "Enter the database name which shall be used for installation (must exist)",
		INSTALL_STEP3_CONNECT_FAILED : "Could not establish connection to database server",
		INSTALL_STEP3_DB_FAILED : "Database &1 not found",
		INSTALL_STEP3_MYSQL_VERSION_FAILED : "MySQL version &1 is not working with this Galaxytool version",
		INSTALL_STEP4_URL : "OGame URL",
		OGAME_URL_DETAILS : "Please enter any URL you see when you are logged on to OGame. Based on that URL the tool will derive the OGame API address which can be used to fill data into the Galaxytool without the Galaxytoolbar. This API was introduced with OGame version 4.1.",
		INSTALL_STEP4_UNIVERSE : "OGame Universe",
		INSTALL_STEP4_DEF_TO_DEBRIS : "Defense to debris",
		INSTALL_STEP4_DEBRIS_RATE : "Debris rate",
		INSTALL_STEP4_SPEED_RATE : "Speed rate",
		INSTALL_STEP4_ENTER_UNIVERSE : "Enter your OGame universe name or number (case sensitive).",
		INSTALL_STEP4_UNIVERSE_MISSING : "You must define your universe",
		INSTALL_STEP4_ENTER_URL : "Enter your OGame universe address",
		INSTALL_STEP4_URL_MISSING : "You must define your OGame address",
		INSTALL_STEP4_URL_CHECK_FAILED : "Could not find OGame API at &1",
		INSTALL_STEP4_GETSETTINGS : "Fetch settings",
		INSTALL_STEP5_TOOLNAME : "Galaxytool name",
		INSTALL_STEP5_ENTER_TOOLNAME : "This is the name which will be shown at logon page to identify your Galaxytool",
		INSTALL_STEP5_LANGUAGE : "Default language",
		INSTALL_STEP5_EMAIL_TO : "Email To",
		INSTALL_STEP5_ENTER_EMAIL_TO : "Enter the email address where you would like to receive notifications about registrations",
		INSTALL_STEP5_EMAIL_FROM : "Email From",
		INSTALL_STEP5_ENTER_EMAIL_FROM : "This email address is shown as REPLY for all mails sent from the Galaxytool",
		INSTALL_STEP5_USE_PHPMAILER : "Use PHPMailer",
		INSTALL_STEP5_MAXSHOUTS : "Maximum number of shoutbox entries",
		INSTALL_STEP5_ENTER_USE_PHPMAILER : "Use PHPMailer if your server does not support sending emails by default",
		INSTALL_PHPMAILER_HOST : "SMPT Host",
		INSTALL_PHPMAILER_HOST_EXAMPLE : "e.g. smtp.provider.com",
		INSTALL_PHPMAILER_USER : "SMPT Username",
		INSTALL_PHPMAILER_USER_EXAMPLE : "e.g. user@provider.dcom",
		INSTALL_PHPMAILER_PASS : "SMPT password",
		INSTALL_PHPMAILER_SECURE : "Authentification method (e.g. ssl)",
		INSTALL_PHPMAILER_PORT : "SMTP Port",
		INSTALL_STEP6_INTRO : "Please define a password for the <strong>admin</strong> account which you have to use for your first logon to the Galaxytool after the installation.",
		INSTALL_STEP7_CONFIG : "Configuration file created",
		INSTALL_STEP7_CONFIG_FAILED : "Configuration file not created",
		INSTALL_STEP7_ATTRIBUTES : "Attributes file created",
		INSTALL_STEP7_ATTRIBUTES_FAILED : "Attributes file not created",
		INSTALL_STEP7_CREATED_TABLES : "Database tables created",
		INSTALL_STEP8_INTRO : "You have successfully installed the Galaxytool!",
		INSTALL_STEP8_LOAD_DATA : "Downloading OGame data ...",
		INSTALL_STEP8_LOAD_DATA_FINISHED : "Download of OGame data finished",
		INSTALL_STEP8_DELETE_FILE : "You should now delete the installation files install.php and update.php from your webserver.",
		INSTALL_STEP8_LOGON : "Please logon with the <strong>admin</strong> user and the password you defined earlier.",
		UPDATE_START : "Starting update to version &1",
		UPDATE_STEP_DONE : "Done",
		UPDATE_TITLE : "Galaxytool update for version",
		UPDATE_STEP1_WELCOME : "Welcome to the update wizard of the Galaxytool. You will be guided through the update of the Galaxytool.",
		UPDATE_STEP1_BACKUP_FILES : "As a first step, make a backup of your <strong>config</strong> folder! You will have to replace the configuration content in case of errors.",
		UPDATE_STEP1_BACKUP_DB : "Then make a <a href=\"http://www.ehow.com/how_2036600_create-database-php.html\">backup</a> of your database.",
		UPDATE_STEP1_PROCEED : "Once the backups have been done, you can proceed with your update.",
		UPDATE_STEP1 : "Welcome",
		UPDATE_STEP2 : "Galaxytool settings",
		UPDATE_STEP2_OLD_VERSION : "Previous Galaxytool version",
		UPDATE_STEP3 : "Update Galaxytool",
		UPDATE_STEP3_UPDATE_RUNNING : "Update running, please wait...",
		UPDATE_STEP4 : "Finalize Update",
		UPDATE_STEP4_INTRO : "You have successfully updated the Galaxytool!",
		UPDATE_STEP4_UPDATE_DONE : "Update steps performed.",
		UPDATE_FAILED : "Update failed.",
		GALAXYTOOL_DUMMY_TEXT : "dummy"
	})
);