define(
	({
		REPORT_WHEN : "på",
		RESOURCES_ON : "Ressurcer på",
		PLAYER_BANNED : "s",
		PLAYER_VACATION_MODE : "f",
		PLAYER_NOOB : "n",
		PLAYER_INACTIVE : "i",
		PLAYER_LONG_INACTIVE : "I",
		PLAYER_OUTLAW : "o",
		L_USERNAME : "Brugernavn",
		L_PASSWORD : "Kodeord",
		L_LOGINFAILURE : "Brugernavn eller kodeord er forkert eller din konto er ikke blevet aktiveret endnu.",
		L_TOKENFAILURE : "Din Logon Key er forkert eller din konto er ikke aktiveret endnu.",
		L_LOGINTEXT : "Log venligst ind",
		L_LANGUAGE : "Tilgængelige sprog:",
		L_TIMEOUT : "Session er løbet ud!",
		L_REGISTER : "Registrer",
		L_PWLOST : "Glemt kodeord",
		INDEX_TITLE : "Oversigt",
		INDEX_INFO : "Information",
		INDEX_ENTRIES : "Antal af hele systemer",
		INDEX_ENTRIES_LASTWEEK : "Nye systemer i sidste uge",
		INDEX_ENTRIES_TO_OLD : "Systemer ældre end en uge",
		INDEX_REGISTERED_USERS : "Registrerede bruger",
		INDEX_PAGEFORWARD : "Klik her, hvis din browser ikke fortsætter automatisk!",
		INDEX_NOTICES : "Notitser",
		INDEX_PLAYERS : "Spiller statistikker",
		INDEX_ALLIES : "Alliance statistikker",
		INDEX_REPORTS : "Spionrapporter",
		INDEX_VERSION : "Sidste ny version til download",
		INDEX_LATEST_VERSION : "Ingen nyere version tilgængelig",
		INDEX_SHOUTBOX : "Beskedboks",
		INDEX_NOENTRY : "Ingen beskeder!",
		INDEX_COMMENT : "Din besked",
		INDEX_INSERT : "Send",
		INDEX_UMOD : "Spillere i feriemodus",
		INDEX_NO_MOONS : "Antal måner",
		INDEX_NO_EMPTY_SYSTEMS : "Antal tomme systemer",
		INDEX_NO_FULL_SYSTEMS : "Antal fyldte systemer",
		INDEX_NO_TARGETS : "Antal mulige mål",
		INDEX_USERINFO : "Brugerstats",
		INDEX_ONLINE : "Online",
		INDEX_TODAY : "Online idag",
		INDEX_ALL : "Antal logins i alt",
		GENERAL_LOAD_FORM : "Hent form data",
		GENERAL_SAVE_FORM : "Gem form data",
		GENERAL_SAVE_AS_TEXT : "Gem som",
		GENERAL_SAVE : "Gem",
		INDEX_USERMANAGEMENT : "Aktiverings Oversigt",
		INDEX_NEEDADMIN : "Kontoer til oplåsning",
		INDEX_NEEDEMAIL : "Ikke-Validerede Kontoer",
		INDEX_TOOLBAR_INFO : "Galaxytool plugin information",
		INDEX_TOOLBAR_URL : "Galaxytool URL",
		INDEX_TOOLBAR_VERSION_REQUIRED : "Kræver mindst Galaxytool plugin version",
		INDEX_TOOLBAR_INSTALL_GUIDE : "Installation instruktioner for plugin",
		INDEX_TOOLBAR_TOKEN : "Logon Key",
		INDEX_TOOLBAR_NEW_TOKEN : "Hent ny Logon Key",
		INDEX_PLAYERS_WITH_N_PLANETS : "Spillere der har mere end &1 planeter",
		INDEX_GETTING_STARTED : "Kom godt i gang med Galaxytool",
		INDEX_GETTING_STARTED1 : "Velkommen til Galaxytool!",
		INDEX_GETTING_STARTED2 : "Galaxytool vil hjælpe dig med at analysere, hvad der foregår i dit OGame univers &1",
		INDEX_GETTING_STARTED3 : "Før du rent faktisk kan analysere data, er du nød til at indsætte det først. Til dette har du brug for et browser-plugin som denne &1 til Firefox.",
		INDEX_GETTING_STARTED4 : "Når du har installeret et plugin, kan du navigere gennem dine OGame sider, som du plejer, og du vil se et lille status vindue, når noget bliver sendt til din Galaxytool.",
		INDEX_GETTING_STARTED5 : "Når pluginet har indsat data i din Galaxytool, kan du begynde at analysere, hvor spillerne har deres kolonier, hvor mange kolonier de har, hvilke rapporter eksisterer, eller hvornår de er mest aktive.",
		INDEX_GETTING_STARTED6 : "Men det vil også hjælpe dig med at analysere, hvordan din konto udvikler sig, hvis du sammenligner dig med dine konkurrenter eller ved at analysere dine kamprapporter for at se, hvor meget du har raided i løbet af de sidste dage eller uger.",
		INDEX_GETTING_WIKIPAGE : "Der er mange flere funktioner i Galaxytool.",
		INDEX_GETTING_WIKIPAGE2 : "Tjek dem ud på vores wiki-side.",
		INDEX_GETTING_BOARD : "For feedback eller ideer, du kan bruge vores board:",
		INDEX_GETTING_CHAT1 : "Eller besøg os på vores chatroom:",
		INDEX_GETTING_CHAT2 : "Vi er ikke online 24/7, men bruger en masse af vores fritid der, så vær tålmodig.",
		INDEX_CLOSE : "Luk",
		INDEX_LOGIN : "Login",
		GENERAL_REQUIRED_FIELDS : "Venligs udfyld alle nødvendige felter",
		INDEX_MESSAGES : "Beskeder",
		INDEX_EXAMPLE : "Eksempel",
		INDEX_INVALID_DATA : "Invalid data",
		GENERAL_COLUMN_HIDE_TITLE : "Administrer kolonner",
		GENERAL_COLUMN_HIDE_INFO : "Vælg hvilke kolonner du ønsker at se i tabellen.",
		GENERAL_ENTRIES_DELETED : "&1 poster slettet",
		GENERAL_APPLY : "Anvend",
		STARTPAGE_GALAXYTOOL_DESCR : "<em>Galaxytool</em> er et værktøj til browser spillet OGame.",
		GENERAL_OVERWRITE : "Overskriv kopi af posten",
		GENERAL_OVERWRITE_QUESTION : "Overskriv?",
		INDEX_OWN_LOGINS : "Dine logins",
		GENERAL_OPEN_IN_NEW_WINDOW : "Åbn link i nyt vindue",
		GENERAL_UNIT_OF_MEASURE_DAYS : "Days",
		PROGRAM_NAME : "OGame Galaxytool",
		SHORTNAME : "Galaxytool",
		BACK_INDEX : "Tilbage til hovedsiden",
		UNIVERSE : "Univers",
		MENU_INFO_LINKS : "Information",
		MENU_PAGE : "Oversigt",
		MENU_DB_SEARCH : "Søg i Databse",
		MENU_DB_NOTICES : "Søg i Notitser",
		MENU_DB_REPORTS : "Søg i Rapporter",
		MENU_GALAXYVIEW : "Galakse",
		MENU_STATISTICS : "Statistikker",
		MENU_ALLYHISTORY : "Alliance historie",
		MENU_FLEET_MOVEMENTS : "Flåde bevægelser",
		MENU_COMBAT_REPORTS : "Kamprapporter",
		MENU_MESSAGES : "Ingame beskeder",
		MENU_OPTION_LINKS : "Indstillinger",
		MENU_DB_REFRESH : "Indsæt i Database",
		MENU_NOTICES : "Notitser",
		MENU_DB_STATUS : "Databasens status",
		MENU_USEROPTIONS : "Brugerkontrol",
		MENU_USEROPTIONS2 : "Brugerindstillinger",
		MENU_USEROPTIONS3 : "Brugerinformation",
		MENU_ADMIN : "Administration",
		MENU_LOGOUT : "Logout",
		MENU_STUFF : "Blandet",
		MENU_FORUM_THREAD : "Udviklerforum",
		MENU_DOWNLOADPAGE : "Downloadside",
		MENU_LANGUAGE : "Sprog",
		MENU_HELP : "Hjælp",
		MENU_TOOLOPTIONS : "Galaxytool Indstillinger",
		PARSER_INFO1 : " er indsat i databasen",
		PARSER_ERROR1 : "Fejl under indførslen af de følgende koordinater:",
		PARSER_ERROR2 : "Kunne ikke finde databasen!",
		PARSER_ERROR3 : "Kunne ikke finde databaseserveren!",
		PARSER_WRONG_UNIVERSE : "Forkert univers - Faktisk: \"&1\" Forventet: \"&2\"",
		SHOW_TITLE : "OGame Galaxytool - Søgeside",
		SHOW_SEARCH : "Søg i database",
		SHOW_ALLYSYMBOL : "Alliance Tag",
		SHOW_PLAYERNAME : "Spiller",
		SHOW_MOONS : "Kun planeter med måne",
		SHOW_NOTICES : "Kun planeter med Notitser",
		SHOW_COLONIES : "Kun planeter til kolonisering",
		SHOW_YES : "Ja",
		SHOW_NO : "Nej",
		SHOW_SEARCHRANGE : "Rækkevidde",
		SHOW_SEARCH_IN : "Søg i galakse",
		SHOW_FROM_SYSTEM : "fra solsystem",
		SHOW_FROM_PLANET : "fra planet position",
		SHOW_TO : "til",
		SHOW_DESCRIPTION : "Du kan bruge * som joker for spiller- eller alliancenavne. Så du kan finde alle spillere med \"navn\" i deres navn.<br />Udfyld kun de felter, du ønsker specificeret.",
		SHOW_SORT_BY : "Sorter efter",
		SHOW_GALASYSTEM : "Galakse/System",
		SHOW_ALLYNAME : "Alliancenavn",
		SHOW_SEARCHBUTTON : "Søg",
		SHOW_ADDRESS : "Adresse",
		SHOW_ALLYSORT : "Alliance",
		SHOW_PLANET : "Spillernavn",
		SHOW_STATUS : "Status",
		SHOW_CURRENTNESS : "Sidst opdateret",
		SHOW_PLAYER_STATUS : "Spillerstatus",
		SHOW_PLAYER_STATUS1 : "alle",
		SHOW_PLAYER_STATUS2 : "mulige mål",
		SHOW_PLAYER_STATUS3 : "inaktive",
		SHOW_HITS : "Hits",
		SHOW_OF : "of",
		SHOW_ASC : "stigende",
		SHOW_DESC : "faldende",
		SHOW_RESULTS : "Resultater pr. side",
		SHOW_MOON : "Måne",
		SHOW_UKMOONSIZE : "ukendt",
		SHOW_DF : "RM",
		SHOW_DF_LONG : "Ruinmark",
		SHOW_METAL : "M",
		SHOW_METAL_LONG : "Metal",
		SHOW_CRYSTAL : "K",
		SHOW_CRYSTAL_LONG : "Krystal",
		SHOW_BOTH : "Tilsammen",
		SHOW_AT_LEAST : "(mindst)",
		SHOW_DATE : "Dato",
		SHOW_DATE_0 : "ingen betydning",
		SHOW_DATE_1 : "ældre end",
		SHOW_DATE_2 : "nyere end",
		SHOW_RANK : "Rang",
		SHOW_FRANK : "Flåderang",
		SHOW_MEMBERS : "Medlemmer",
		SHOW_NOTRANKED : "Ikke indenfor top 1500.",
		SHOW_NOTICERES : "Notitser",
		SHOW_REPORTS : "Kun planeter med rapporter",
		SHOW_REPORTS_SHORT : "Rapporter",
		SHOW_NOTHING : "Ingen data fundet",
		SHOW_ALLIANCE_STATUS : "Alliancestatus",
		SHOW_NO_STATUS : "ingen status",
		SHOW_NAP : "IAP",
		SHOW_ALLIED : "Allierede",
		SHOW_WAR : "Krig",
		SHOW_BOYCOTT : "Boycott",
		SHOW_NEUTRAL : "Neutral",
		SHOW_OWN : "Egen alliance",
		SHOW_WING : "Wing",
		SHOW_EXT_OPTIONS1 : "Vis flere søgemuligheder for søgning på rækkevidde, rang, dato eller Ruinmark.",
		SHOW_EXT_OPTIONS2 : "Vis flere muligheder for søgning på kolonier, måner, rapporter, notitser, spillerstatus eller diplomatisk status.",
		SHOW_EXT_OPTIONS3 : "Vis flere søgemuligheder for sortering af søgeresultater.",
		SHOW_EXTENDED : "avanceret søgning",
		SHOW_MOON_SELECTION : "Planet med måne",
		SHOW_REPORT_SELECTION : "Planet med rapport",
		SHOW_FILTER_BY : "Udeluk fra listen",
		SHOW_FILTER_NONE : "ingen",
		SHOW_PLAYERS_WITHOUT_PROGRESS : "Show players without score changes within the last few days",
		STATUS_TITLE : "OGame Galaxytool - Statusside",
		STATUS_DB_STATUS : "Status på database",
		STATUS_COLOR : "Farve",
		STATUS_AGE1 : "Data 1 dag gammel.",
		STATUS_AGE2 : "Data 2 - 4 dage gammelt.",
		STATUS_AGE3 : "Data 4 - 7 dage gammelt.",
		STATUS_AGE4 : "Data 1 - 2 uger gammelt.",
		STATUS_AGE5 : "Data 2 - 4 uger gammelt.",
		STATUS_AGE6 : "Data ældre end 1 måned!",
		STATUS_AGE7 : "Ingen data tilgængelig.",
		STATUS_ON : "on",
		STYLES_COLOR1 : "Farve1",
		STYLES_COLOR2 : "Farve2",
		STYLES_COLOR3 : "Farve3",
		STYLES_COLOR4 : "Farve4",
		STYLES_COLOR5 : "Farve5",
		STYLES_COLOR6 : "Farve6",
		STYLES_COLOR7 : "Farve7",
		STATUS_DB_LEGEND : "Farvekoder",
		STATUS_GALAXY : "Galaxy Oversigt",
		USER_TITLE : "Brugerkontrol",
		USER_NAMES : "Bruger",
		USER_ERROR : "Fejl",
		USER_NEWUSER : "Ny bruger",
		USER_OPTIONS : "Indstillinger",
		USER_USERNAME : "Brugernavn",
		USER_PASSWORD : "Kodeord",
		USER_PASSWORD_CONFIRM : "Bekræft kodeord",
		USER_GALAXY : "Galakse",
		USER_SEARCH : "Søg",
		USER_INSERT : "Indsæt",
		USER_DELETE : "Slet",
		USER_DELETE_ENTRY : "Vil du slette bruger: ",
		USER_STATUS : "Se statistik",
		USER_STYLES : "Modificer layout",
		USER_SUBMIT : "Send",
		USER_RESET : "Nulstil",
		USER_YES : "Ja",
		USER_NO : "Nej",
		USER_STYLEPATH : "Stil til styles.css",
		USER_PROBES : "Se/Send spionrapporter",
		USER_EMAIL : "Email",
		USER_ERROR1 : "Kodeordet eller emailadressen er forkert.",
		USER_ERROR2 : "Emailadressen er forkert.",
		USER_INGAME : "In-game navn",
		USER_ALLYTAG : "Alliance Tag",
		USER_ALLYHISTORY : "Se/Send Alliance Historie",
		USER_DIPLOMATIC : "Ændr Diplomatisk Status",
		USER_STATSPAGE : "Antal datapakker tilføjet ved statistiksiden",
		USER_LINKS : "Links",
		USER_LINKS2 : "Format:<br>tekst;url<br>tekst2;url2<br>tekst3;url3",
		USER_EXPORT_TITLE : "Eksporter farver (BB Codes)",
		USER_BB_COORDINATES : "Koordinater",
		USER_BB_MOON : "Måne",
		USER_BB_DEBRIS : "Ruinmark",
		USER_BB_ALLY : "Alliancenavn",
		USER_BB_ALLYDETAILS : "Alliance detaljer",
		USER_BB_PLAYERNAME : "Spillernavn",
		USER_BB_BANNED : "spærret",
		USER_BB_VACATION : "feriemodus",
		USER_BB_NOOB : "noob",
		USER_BB_INACTIVE : "Inaktiv",
		USER_BB_LONGINACTIVE : "Langtids inaktiv",
		USER_DELETION : "Slet",
		USER_FLEETINFO : "Flåde bevægelser",
		USER_ACTIVITIES : "Spiller aktiviteter",
		USER_MAINTENANCE : "Galaxytool vedligeholdelse",
		USER_MANAGEMENT : "Brugerkontrol",
		USER_DELETE_MY_COMBAT_REPORTS : "Slet mine kamprapporter",
		USER_DELETE_MY_MESSAGES : "Slet mine beskeder",
		USER_DELETE_MY_FLEETMOVES : "Slet mine flådebevægelser",
		USER_DELETE_MY_COMBAT_REPORTS_LIMITED : "Slet mine kamprapporter ældre end &1 dage",
		USER_DELETE_MY_MESSAGES_LIMITED : "Slet mine beskeder ældre end &1 dage",
		USER_TABLE_ENTRIES : "Antal søgeresultater pr. side",
		USER_EXISTS : "Bruger eksisterer allerede",
		USER_BB_OUTLAW : "Slyngel",
		USER_INVALID_URL : "URL &1 synes at være ugyldig - URL vil blive ignoreret",
		VIEW_TITLE : "OGame Galaxytool - Detaljer",
		VIEW_NODATA : "Ingen data tilgængelig.",
		VIEW_GALAXY : "Galakse",
		VIEW_SYSTEM : "Solsystem",
		VIEW_POSITION : "Pos.",
		VIEW_PLANET : "Planet",
		VIEW_MOON : "Måne",
		VIEW_TF : "RM",
		VIEW_PLAYER : "Spiller",
		VIEW_PLAYER_ADD : "(Rang / Status)",
		VIEW_ALLY : "Alliance",
		VIEW_ALLY_ADD : "(Rang / Medlem)",
		VIEW_METAL : "M",
		VIEW_CRYSTAL : "K",
		VIEW_COLONISED : "Ikke-koloniserede planeter",
		VIEW_UKMOONSIZE : "ukendt",
		VIEW_BACK : "tilbage",
		VIEW_NOTICE : "Notitser",
		VIEW_REPORTS : "Rapporter",
		VIEW_MOONPHALANX : "De følgende måner kan skanne dette system",
		VIEW_NOMOONS : "Ingen måner fundet",
		VIEW_IRAKS : "De følgende planeter kan nå dette system med IPR",
		VIEW_NOIRAKS : "Ingen IPR fundet",
		VIEW_MOON_DESTROY_CHANCE : "Chance for at ødelægge en måne",
		VIEW_CHANCE_WITH_ONE : "Chance med én dødsstjerne",
		VIEW_CHANCE_WITH_N : "Chance med ",
		VIEW_DEATH_STARS : "dødsstjerner",
		VIEW_DS_DESTROY_CHANCE : "Chance for at miste dødsstjerne(rne)",
		VIEW_TOP : "Top",
		VIEW_GO : "go",
		VIEW_DIAMETER : "Diameter",
		PW_TITLE : "OGame Galaxytool - skift kodeord",
		OLD_PASSWORD : "gammelt kodeord",
		NEW_PASSWORD : "nyt kodeord",
		CONFIRM_NEW_PASSWORD : "bekræft nyt kodeord",
		PW_MISMATCH : "Kodeordene passede ikke sammen!",
		PW_ERROR : "Gammelt kodeord var ikke korrekt!",
		PW_DONE : "Opdateret!.",
		TIMEZONE_OFFSET : "Tidszone forskel til server",
		DELETE_ACCOUNT : "Slet denne Galaxytool konto",
		DELETE_ACCOUNT_SAFETY_REQUEST : "Vil du virkelig slette denne Galaxytool konto?",
		CH_PASSWD_AUTHORIZATION : "Godkendelse",
		CH_PASSWD_ADMIN : "Admin",
		TIMEZONE_OGAME_OFFSET : "Tidszone forskel til OGame server",
		CH_PASSWD_USER_LANGUAGE : "Skift til dette sprog efter logon",
		CH_PASSWD_USER_LANGUAGE_NO_CHANGE : "Ingen ændring",
		CH_PASSWD_EXPAND : "Udvidet",
		CH_PASSWD_COLLAPSE : "Kollapset",
		CH_PASSWD_HIDDEN : "Skjult",
		CH_PASSWD_GETTING_STARTED : "Vis Kom godt i gang info efter logon",
		CH_PASSWD_PLUGIN : "Vis Plugin Info efter logon",
		NOTICE_TITLE : "OGame Galaxytool - Notitser",
		NOTICE_HEADER : "rediger notits",
		NOTICE_HEADER2 : "Rediger egen notits",
		NOTICE_PUBLIC : "Tilgængelig for andre ?",
		NOTICE_YES : "ja",
		NOTICE_NO : "nej",
		NOTICE_TEXT : "Notits tekst",
		NOTICE_SAVE : "Gem",
		NOTICE_DELETED : "Data slettet",
		NOTICE_SAVED : "Data gemt.",
		NOTICE_RESULTS : "Alle resultater",
		NOTICE_USER : "Bruger",
		NOTICE_DATE : "Dato",
		NOTICE_EDIT : "Rediger",
		NOTICE_DELETE : "Slet",
		NOTICE_NEW : "Lav egen notits",
		NOTICE_NOTPUBLIC : "Notits ikke offentlig.",
		NOTICE_ALL : "alle",
		NOTICE_NONE : "ingen",
		NOTICE_SEARCH : "Søg i notitser",
		NOTICE_SEARCH_SHORT : "Søg",
		NOTICE_HITS : "Resultater",
		NOTICE_SHOWRESULTS : "resultater pr. side",
		NOTICE_OF : "af",
		NOTICE_NOTHING : "Ingen data fundet",
		NOTICE_CHARS : "Karakterer",
		NOTICE_PLAYERNAME : "Spiller",
		NOTICE_SHOWALL : "Vis alle notitser",
		REPORTS_TITLE : "OGame Galaxytool - Spionagerapporter",
		REPORTS_RESOURCES : "Ressourcer",
		REPORTS_FLEET : "Flåder",
		REPORTS_DEFENCE : "Forsvar",
		REPORTS_BUILDINGS : "Bygninger",
		REPORTS_TECHNOLOGY : "Forskning",
		REPORTS_MOON : "Måne",
		REPORTS_SEARCH : "Søg i spionagerapporter",
		REPORTS_SEARCH_SHORT : "Søg",
		REPORTS_HITS : "Resultater",
		REPORTS_NOTHING : "Ingen data fundet",
		REPORTS_ADDRESS : "Adresse",
		REPORTS_CURRENTNESS : "Currentness",
		REPORTS_PLAYERNAME : "Spillernavn",
		REPORTS_ALLY : "Ally",
		REPORTS_VIEW : "se rapport",
		REPORTS_SEARCH_IN : "Søg i galakse",
		REPORTS_FROM_SYSTEM : "fra system",
		REPORTS_TO : "til",
		REPORTS_DELETE : "slet",
		REPORTS_DELETED : "Data slettet",
		REPORTS_RESULTS : "resultater pr. side",
		REPORTS_OF : "af",
		REPORTS_DATE : "Dato",
		REPORTS_DATE_0 : "ingen betydning",
		REPORTS_DATE_1 : "ældre end",
		REPORTS_DATE_2 : "nyere end",
		REPORTS_NOTICES : "Notitser",
		REPORTS_AT_LEAST_RESOURCES : "Ressourcer (mindst)",
		REPORTS_SEARCH_EXTENDED : "Se alle",
		REPORTS_FLEET_RESIS : "Flåde - score",
		REPORTS_DEFENCE_RESIS : "Forsvar - score",
		REPORTS_ALL_RESIS : "sum scores",
		REPORTS_TECHS : "Teknologier",
		REPORTS_UNKNOWN_ENTRIES : "ukendt data",
		REPORTS_PARTLY_INSERTED : "delvist indsat",
		REPORTS_FOR_ALL_RES : "for alle ressourcer",
		REPORTS_FOR_TF : "for ruinmarken",
		REPORTS_KT : "Små Transportere",
		REPORTS_GT : "Store Transportere",
		REPORTS_SS : "Slagskibe",
		REPORTS_REC : "Recycler",
		REPORTS_RAIDABLE : "Kun mål der kan raides",
		REPORTS_ALL_RESOURCES : "alle ressourcer",
		REPORTS_STUFF : "Blandet",
		REPORTS_SPEEDSIM : "Simuler med SpeedSim",
		REPORTS_DRAGOSIM : "Simuler med Dragosim",
		REPORTS_STATUS : "Status",
		REPORTS_ERROR : "En fejl er opstået",
		REPORTS_OWN_REPORTS : "Kun mine rapporter",
		REPORTS_UPLOAD_BY : "Report uploaded by",
		REPORTS_DEPTH : "Report depth",
		REPORTS_FLEET_SCORE : "Fleet score",
		REPORTS_DEFENCE_SCORE : "Defence score",
		REPORTS_HOURS : "timer",
		REPORTS_MAX_RESULTS_HIT : "Din forespørgsel returnerede mere end &1 hits. Kun de første &1 resultater er viste. Juster din søgning for at få færre resultater.",
		REPORTS_OSIMULATE : "Simuler med OSimulate",
		REPORTS_SHOW_ONLY : "Vis kun",
		REPORTS_SHOW_PLANETS : "Planeter",
		REPORTS_SHOW_MOONS : "Måner",
		REPORTS_OWNER : "Rapporter ejes af",
		STATS_TITLE : "OGame Galaxytool - Statistik",
		STATS_TBLHEAD : "Statistiks",
		STATS_RANK : "Rang",
		STATS_PLAYERNAME : "Spillernavn",
		STATS_ALLYNAME : "Alliance Tag",
		STATS_SCORE : "Score",
		STATS_FLEET : "Flåde",
		STATS_RESEARCH : "Forskning",
		STATS_MEMBERS : "Medlemmer",
		STATS_STATUS : "Status",
		STATS_NOTHING : "ingen Status",
		STATS_NAP : "NAP",
		STATS_ALLIED : "Allierede ",
		STATS_WAR : "Krig",
		STATS_BOYCOTT : "Boycott",
		STATS_NEUTRAL : "Neutral",
		STATS_OWN : "Egen Alliance",
		STATS_WING : "Wing",
		STATS_UPDATE : "Data fra",
		STATS_PLAYERSTATS : "Spiller statistikker",
		STATS_ALLYSTATS : "Alliance statistikker",
		STATS_DELETE : "Vil du slette denne datapakke ?",
		STATS_CONFIRM_DELETE : "Er du sikker på at du vil slette informationen om denne spiller ?",
		STATS_CHANGE_PLAYER_STATUS : "Spiller status",
		STATS_CHANGE_ALLIANCE_STATUS : "Alliance status",
		STATS_CHANGE_ALLIANCE_STATUS_HINT : "Alle medlemmer i denne alliance får tildelt den valgte status. Enhver tidligere status vil blive overskrevet. Du kan ændre status på nogle af spillerne bagefter.",
		STATS_UNKNOWN : "Rest",
		STATS_DETAILS : "Detaljer for",
		STATS_PLAYERSTATUS : "Spillerstatus",
		STATS_IGNORE_STATUS : "alle",
		STATS_ACTIVE : "active",
		STATS_INACTIVE : "Inaktiv",
		STATS_BANNED : "spærret",
		STATS_VACATION : "feriemodus",
		STATS_NOOB : "noob",
		STATS_YES : "Ja",
		STATS_NO : "Kun planeter med Notitser",
		STATS_SEARCH : "Søg",
		STATS_SHOW_GRAPH : "Vis detaljer for score fordeling",
		STATS_LONG_INACTIVE : "Langtids inaktiv",
		STATS_STANDARD : "Points",
		STATS_MILITARY : "Militær points",
		STATS_ECONOMY : "Økonomi points",
		STATS_HONOUR : "Honour points",
		STATS_MILITARY_BUILD : "Militær points bygget",
		STATS_MILITARY_DESTROYED : "Militær point ødelagt",
		STATS_MILITARY_LOST : "Militær points tabt",
		REGISTER_REGISTRATE : "Registrer",
		REGISTER_LOGINNAME : "Login-Navn",
		REGISTER_PASSWORD : "Kodeord",
		REGISTER_PASSWORD_CONFIRM : "Bekræft kodeord",
		REGISTER_EMAIL : "Email",
		REGISTER_INGAME : "Ingame-Navn",
		REGISTER_ALLYTAG : "Alliancetag",
		REGISTER_EMAILVERIFICATION : "Emailcheck",
		REGISTER_EMAILTEXT : "Tryk venligst på linket for at bekræfte din registrering i GalaxyTool'et.",
		REGISTER_ERROR1 : "Brugernavnet er allerede i brug.",
		REGISTER_ERROR2 : "Fejl ved afsendelse af email. Kontakt venligst din administrator.",
		REGISTER_ERROR3 : "Fejl ved afsendelse af data til databasen!",
		REGISTER_INFO1 : "Din bruger er oprettet.",
		REGISTER_INFO2 : "Tryk venligst på linket i mailen, der er sendt til dig, for at bekræfte din registrering.",
		REGISTER_INFO3 : "Bruger bekræftet. Din administrator skal aktivere den.",
		REGISTER_BUTTON : "Tilbage til hovedsiden",
		REGISTER_NEW_SUBJECT : "En ny bruger i GalaxyTool'et",
		REGISTER_NEW_MAILTEXT : "En ny bruger har registreret sig selv.",
		REGISTER_BACK : "Tilbage til side 1",
		REGISTER_MISSING_FIELDS : "Indtast alle obligatoriske felter",
		REGISTER_ERROR4 : "E-mail-adresse er ikke gyldig.",
		REGISTER_ERROR5 : "Passwords stemmer ikke overens.",
		REGISTER_PWS : "Password styrke",
		REGISTER_PWS0 : "meget svag",
		REGISTER_PWS1 : "svag",
		REGISTER_PWS2 : "god",
		REGISTER_PWS3 : "stærk",
		REGISTER_PWS4 : "meget stærk",
		REGISTER_EMAIL_USED : "Email er allerede brugt",
		LOSTPW_TITLE : "Glemt kodeord?",
		LOSTPW_INFO2 : "Et nyt kodeord er genereret og sendt til din mailadresse.",
		LOSTPW_BUTTON1 : "send nyt kodeord",
		LOSTPW_BUTTON2 : "Tilbage til hovedsiden",
		LOSTPW_LOGINNAME : "Login-Navn",
		LOSTPW_EMAIL : "Mail",
		LOSTPW_ERROR1 : "Fejl ved afsendelse af data til databasen!",
		LOSTPW_ERROR2 : "Ingen match fundet!",
		LOSTPW_ERROR3 : "Fejl ved afsendelse af mail. Kontakt venligst din administrator.",
		LOSTPW_EMAIL_SUBJECT : "Dit nye kodeord, du bestilte",
		LOSTPW_EMAIL_TEXT1 : "Her er dit nye login for GalaxyTool'et",
		LOSTPW_EMAIL_TEXT2 : "Brugernavn",
		LOSTPW_EMAIL_TEXT3 : "Kodeord",
		LOSTPW_INFO1 : "Du vil modtage en e-mail for at bekræfte nulstilling af din adgangskode.",
		LOSTPW_CONFIRM_RESET_SUBJECT : "Glemt adgangskode?",
		LOSTPW_CONFIRM_RESET_MESSAGE : "Hej,\n\ndu har anmodet om en nulstilling af adgangskoden til Galaxytool. For at generere en ny adgangskode, skal du klikke på følgende link:",
		USERINFO_TITLE : "OGame Galaxytool - Bruger Information",
		USERINFO_NAMES : "Alle brugere af dette tool",
		USERINFO_DETAIL : "detaljeret information om",
		USERINFO_ERROR1 : "Ingen bruger med dette ID!",
		USERINFO_USERNAME : "Login navn",
		USERINFO_INGAME : "Ingame navn",
		USERINFO_EMAIL : "Mail",
		USERINFO_ALLYTAG : "Alliance",
		USERINFO_STYLEPATH : "Skin",
		USERINFO_STATUS : "Status",
		USERINFO_ACTIVATE : "Aktiver spiller",
		USERINFO_LOGINS : "Antal logins",
		USERINFO_LASTLOGIN : "Sidste login",
		USERINFO_DATA : "Information om indsatte systemer",
		USERINFO_NODATA : "Denne bruger har ikke indsat nogle systemer endnu!",
		USERINFO_GALAXY : "Galakse",
		USERINFO_SYSTEMS : "Antal systemer",
		USERINFO_IP : "IP-adresse",
		USERINFO_LOGINTIME : "Login",
		USERINFO_NOLOGIN : "Denne bruger har aldrig logget ind.",
		USERINFO_LAST_GALAXYUPDATE : "Indsatte sidste galakseoversigt",
		USERINFO_LAST_PUBLIC_NOTICE : "Sidste offentlige notits",
		USERINFO_LAST_PRIVATE_NOTICE : "Sidste private notits",
		USERINFO_NUMBEROF_PUBLIC_NOTICE : "Antal offentlige notitser",
		USERINFO_NUMBEROF_PRIVATE_NOTICE : "Antal private notitser",
		USERINFO_ACTIVATED : "Konto aktiveret",
		USERINFO_ACTIVATIONTEXT : "Administratoren af dette Galaxytool har aktiveret din konto.\n\nHa' det sjovt med Galaxytool!",
		USERINFO_LAST_SUBMIT : "Indsat sidste data",
		ALLYHISTORY_TITLE : "OGame Galaxytool - Alliance Historie",
		ALLYHISTORY_TBLHEAD : "Historisk oversigt",
		ALLYHISTORY_PLAYERNAME : "Spillernavn",
		ALLYHISTORY_ALLYNAME : "Alliance",
		ALLYHISTORY_LASTMONTH : "Sidste måned",
		ALLYHISTORY_ALL_DATA : "alt tilgængelig information",
		ALLYHISTORY_SHOW : "vis statistik",
		ALLYHISTORY_TIMESPAN : "Timespan",
		ALLYHISTORY_PROGESS : "Process",
		ALLYHISTORY_SCORE : "Point",
		ALLYHISTORY_FSCORE : "Flådepoint",
		ALLYHISTORY_RSCORE : "Forskningspoint",
		ALLYHISTORY_MEMBER : "Medlemmer",
		ALLYHISTORY_NOTHING : "ingen data fundet",
		ALLYHISTORY_DETAILS : "Detaljer",
		ALLYHISTORY_SHOW_ADDRESS : "Koordinater",
		ALLYHISTORY_ESCORE : "Økonomi points",
		ALLYHISTORY_MSCORE : "Militær points",
		DETAILEDINFO_PLAYERINFO_TITLE : "Spillerinformation",
		DETAILEDINFO_ALLYINFO_TITLE : "Allianceinformation",
		DETAILEDINFO_PLAYERINFO_TBLHEAD : "Detaljeret information om spiller",
		DETAILEDINFO_ALLYINFO_TBLHEAD : "Detaljeret information on alliance",
		DETAILEDINFO_NO_ALLIANCE : "ingen",
		DETAILEDINFO_SCORE : "Pointstatistik",
		DETAILEDINFO_FLEET : "Flådestatistik",
		DETAILEDINFO_RESEARCH : "Forskningsstatistik",
		DETAILEDINFO_RANK : "Rang",
		DETAILEDINFO_POINTS : "Point",
		DETAILEDINFO_KNOWN_PLANETS : "kendte planeter",
		DETAILEDINFO_MOONS : "kendte måner",
		DETAILEDINFO_PHALANX_AREA : "Phalanxområde",
		DETAILEDINFO_NO_PHALANX_AREA : "ingen Phalanx fundet",
		DETAILEDINFO_NOTICES : "Notitser",
		DETAILEDINFO_NO_NOTICES : "Ingen notitser fundet",
		DETAILEDINFO_PREVIOUS_ALLIANCES : "forrige Alliancer",
		DETAILEDINFO_RESOURCES_PER_HOUR : "Ressourcer pr. time",
		DETAILEDINFO_RESOURCES_PER_DAY : "Ressourcer pr. dag",
		DETAILEDINFO_RESOURCES_PER_WEEK : "Ressourcer pr. uge",
		DETAILEDINFO_RESOURCES_PER_MONTH : "Ressourcer pr. måned (30 dage)",
		DETAILEDINFO_METAL : "Metal",
		DETAILEDINFO_CRYSTAL : "Krystal",
		DETAILEDINFO_DEUTERIUM : "Deuterium",
		DETAILEDINFO_UNKNOWN : "ukendt",
		DETAILEDINFO_SCORE_DISTRIBUTION : "Point fordeling",
		DETAILEDINFO_GENERAL : "Detaljer",
		DETAILEDINFO_MEMBERS : "Medlem",
		DETAILEDINFO_GRAPHS : "Grafer",
		DETAILEDINFO_RESOURCES : "Resourcer",
		DETAILEDINFO_FLEET_TAB : "Flåde",
		DETAILEDINFO_TECH : "Forskning",
		DETAILEDINFO_FLEET_DETAIL : "Sum / (Spiller gennemsnit) I alle tilgængelige rapporter",
		DETAILEDINFO_TECH_DETAIL : "Gennemsnit af alle tilgængelige spiller informationer",
		DETAILEDINFO_PLANET_TAB : "Planeter",
		DETAILEDINFO_MOON_TAB : "Måner",
		DETAILEDINFO_ACTIVITIES : "Aktiviteter",
		DETAILEDINFO_NODATA : "Ingen data tilgængelig.",
		DETAILEDINFO_ACTIVITY_DESCRIPTION : "Vis aktiviteter &1 indsamlet fra:",
		DETAILEDINFO_GALAXYVIEWS : "Galakse visninger",
		DETAILEDINFO_SCANS : "Spionage handlinger",
		DETAILEDINFO_MESSAGES : "Spiller beskeder",
		DETAILEDINFO_COMBATS : "Kamprapporter",
		DETAILEDINFO_ALLYPAGE : "Alliance oversigt",
		DETAILEDINFO_MANUAL : "Mmanuele indsætninger",
		DETAILEDINFO_START : "Begyndelsen",
		DETAILEDINFO_TO : "til",
		DETAILEDINFO_TODAY : "Idag",
		DETAILEDINFO_DATA_RESTRICTION : "begrænset til:",
		DETAILEDINFO_WEEKDAY_WEEKEND : "Weekend",
		DETAILEDINFO_WEEKDAY_WORKINGDAY : "Hverdag",
		DETAILEDINFO_WEEKDAY_MONDAY : "Mandag",
		DETAILEDINFO_WEEKDAY_TUESDAY : "Tirsdag",
		DETAILEDINFO_WEEKDAY_WEDNESDAY : "Onsdag",
		DETAILEDINFO_WEEKDAY_THURSDAY : "Torsdag",
		DETAILEDINFO_WEEKDAY_FRIDAY : "Fredag",
		DETAILEDINFO_WEEKDAY_SATURDAY : "Lørdag",
		DETAILEDINFO_WEEKDAY_SUNDAY : "Søndag",
		DETAILEDINFO_WEEKDAY_SHORTLENGTH : 3,
		DETAILEDINFO_PLAYER_CURRENTLY_ACTIVE : "Spilleren er i øjeblikket aktiv",
		DETAILEDINFO_PLAYER_MESSAGES : "tilgængelige spiller beskeder",
		DETAILEDINFO_SHOW : "vis",
		DETAILEDINFO_NONE : "ingen tilgængelige",
		DETAILEDINFO_ENTER_MANUALLY : "Indtast aktiviteter for denne spiller",
		DETAILEDINFO_PLAYER_SEEN_ON : "Spiller var online på",
		DETAILEDINFO_INSERT : "Indsæt",
		DETAILEDINFO_OGAME_SERVERTIMES : "Bemærk venligst: Alle datoer og tidspunkter henvises til OGame server tider!",
		DETAILEDINFO_DAY_VIEW : "24 timers oversigt",
		DETAILEDINFO_WEEK_VIEW : "uge oversigt",
		DETAILEDINFO_HOME_PLANET : "Hjemmeplanet",
		DETAILEDINFO_PLANETNAME : "Navn",
		DETAILEDINFO_DEFENCE_SCORE : "Forsvar score",
		DETAILEDINFO_DEFENCE_SCORE_TOOLTIP : "Forsvar score = Flåde - Score + Forskning + Økonomi.<br/>Alle disse statistikker skal være up to date for at få et meningsfuldt resultat!",
		DETAILEDINFO_SCORE_PER_SHIP : "Scores pr. skib",
		DETAILEDINFO_SHIPS : "Antal skibe",
		DETAILEDINFO_DATE_IN_FUTURE : "Vedligehold ikke tider som ikke er i fortiden.",
		ADMIN_TITLE : "Administration af Galaxytool",
		ADMIN_DISCLAMER : "Bemærk: Kør scripts på eget ansvar ! De fleste sletter data.",
		ADMIN_INCONSISTENCIES : "Uoverensstemmelser i databasen",
		ADMIN_PLANETS : "Planetter på position 0 eller størrere end 15",
		ADMIN_GALAXIES : "Slet galaxer størrere end &1 ",
		ADMIN_PLAYERS : "Slet spillere uden OGame playerid - Som kan duplikere spillere",
		ADMIN_REPORTS : "Slet reporter om planetter der ikke længere findes",
		ADMIN_MISC : "Div.",
		ADMIN_RESET : "Nulstil Galaxytool (Kun brugere, ip table bliver ikke slettet)",
		ADMIN_OLD_PLAYERS : "Slet spiller entries older than &1 days",
		ADMIN_OLD_REPORTS : "Slet rapporter ældre end &1 days",
		ADMIN_LOADING : "Luk ikke vinduet mens siden loader.",
		ADMIN_STATUS : "Status på dine forespørgelser",
		ADMIN_SELECTION : "Mindst et valg skal vælges",
		ADMIN_SAFETY : "Er du sikker på du vil køre dette script(s) ?",
		ADMIN_DONE : "Udført",
		ADMIN_NOTBD : "Intet at gøre ",
		ADMIN_OLD_GALAXIES : "Slet galaxa informationer ældre end &1 days",
		ADMIN_UNUSED_PLAYERS : "Slet spillere som ikke er i galaxe informationen",
		ADMIN_OLD_ACTIVITIES : "Slet spiller aktiviteter ældre end &1 dage",
		ADMIN_OLD_COMBATS : "Slet kamprapporter ældre end &1 dage",
		ADMIN_OLD_INGAME_MSG : "Slet ingame beskeder ældre end &1 dage",
		ADMIN_OGAME_API : "Indlæs offentlige data fra OGame i Galaxytool",
		ADMIN_OGAME_ALL_DATA : "alt tilgængelig information",
		ADMIN_OGAME_GALAXY_DATA : "Galakse",
		ADMIN_OGAME_STATISTICS_DATA : "Statistikker",
		ERRORPAGE_PAGEFORWARD : "Klik her, hvis din browser ikke understøtter videresendelse!",
		ERRORPAGE_PERMISSION_DENIED : "Du har ikke tilladelse til at gå ind på denne side. Klik for at gå tilbage.",
		FLEETS_TITLE : "OGame Galaxytool - Flåde bevægelse",
		FLEETS_ACTUAL_FLEETS : "Nuværende flåde bevægelser",
		FLEETS_YES : "Ja",
		FLEETS_NO : "Kun planeter med Notitser",
		FLEETS_DETAILS : "Detailer",
		FLEETS_MISSION_EXPEDITION : "Ekspeditio",
		FLEETS_MISSION_COLONIZATION : "Kolonisere",
		FLEETS_MISSION_RECYCLE : "Recycle Ruinmark",
		FLEETS_MISSION_TRANSPORT : "Transport",
		FLEETS_MISSION_DEPLOYMENT : "Stationere",
		FLEETS_MISSION_ESPIONAGE : "Spionage",
		FLEETS_MISSION_ACS_DEFEND : "Holde",
		FLEETS_MISSION_ATTACK : "Angrib",
		FLEETS_MISSION_ACS_ATTACK : "AKS Angribe",
		FLEETS_MISSION_MOON_DESTRUCTION : "Måne ødelæggelse",
		FLEETS_MISSION_MISSILE_ATTACK : "Raket Angreb",
		FLEETS_NO_DATA : "Ingen tilgængelige data fundet",
		FLEETS_FLEET : "Flåde",
		FLEETS_ALL_FLEETS : "Vis alle flåde bevægelser",
		COMBAT_REPORT_OUDATED_GALAXYVIEW : "Din Galaxy data er forældet. Besøg mål koordinaterne først!",
		MESSAGES_TITLE : "OGame Galaxytool - OGame Beskeder",
		MESSAGES_PLAYERNAME : "Spillernavn",
		MESSAGES_SUBJECT : "Emne",
		MESSAGES_DATE : "Dato",
		MESSAGES_FILTER : "Filter",
		MESSAGES_DELETE : "Slet besked",
		MESSAGES_PUBLISH_DETAIL : "Offentliggør meddelelsen ved at tilføje meddelelsens indhold i notitser på den pågældende spiller.",
		MESSAGES_PUBLISH_HEADER : "&sender sendte en besked til &recipient den &date:\n\n &message",
		MESSAGES_PLAYER_FILTER : "Besked til spiller:",
		MESSAGES_CONTENT : "Indhold",
		COMBATS_TITLE : "OGame Galaxytool - Kamprapporter",
		COMBATS_ATTACKER : "Angriber",
		COMBATS_DEFENDER : "Forsvarer",
		COMBATS_DATE : "Dato",
		COMBATS_OWNER : "Ejer",
		COMBATS_WINNER : "Vinner",
		COMBATS_COMBATREPORT : "Kamprapport",
		COMBATS_COMBAT_AT : "Kamp på",
		COMBATS_LOST_UNITS : "Mistede enheder",
		COMBATS_LOOT : "Bytte",
		COMBATS_DEBRIS : "Debris",
		COMBATS_AND : "og",
		COMBATS_PUBLISH : "Gør denne rapport offentlige",
		COMBATS_UNPUBLISH : "Stop delingen af denne rapport (gør det private igen)",
		COMBATS_DELETE : "Slet rapport",
		COMBATS_CHECK_ALL : "Vælg Alle",
		COMBATS_UNCHECK_ALL : "Fravælg Alle",
		COMBATS_WITH_SELECTED : "Med valgte",
		COMBATS_PUBLIC_REPORTS : "Offentlige rapporter",
		COMBATS_YES : "Ja",
		COMBATS_NO : "Kun planeter med Notitser",
		COMBATS_SEARCH_OPTIONS : "Søgemuligheder",
		COMBATS_SEARCH : "Go",
		COMBATS_RESET : "Reset",
		COMBATS_COORDINATES : "Koordinater",
		COMBATS_INVALID_GALAXY_ENTERED : "Invalid Galaxy indtastet",
		COMBATS_INVALID_SYSTEM_ENTERED : "Invalid System indtastet",
		COMBATS_INVALID_PLANET_ENTERED : "Invalid Planet indtastet",
		COMBATS_GALAXY_FROM_TO : "Galaxy",
		COMBATS_SYSTEM_FROM_TO : "System",
		COMBATS_PLANET_FROM_TO : "Planet",
		COMBATS_APPLY : "Anvend",
		COMBATS_COMBAT_SUMMARY : "Kamprapport resum",
		COMBATS_DOWNLOAD_CSV : "Download som CSV fil",
		REPORT_ARCHIVE_TITLE : "Rapport arkiv",
		REPORT_ARCHIVE_COORDINATES : "Koordinater",
		REPORT_ARCHIVE_SCANTIME : "Scan tidspunkt",
		REPORT_ARCHIVE_DELETE : "Slet disse poster",
		REPORT_ARCHIVE_CONFIRM_DELETE : "Vil du virkelig slette disse poster?",
		REPORT_ARCHIVE_GALAXY : "Galaxy",
		REPORT_ARCHIVE_SYSTEM : "System",
		REPORT_ARCHIVE_PLANET : "Planet",
		REPORT_ARCHIVE_MOON : "Måne",
		REPORT_ARCHIVE_DETAILS : "Detaljer",
		REPORT_ARCHIVE_RESOURCES : "Ressourcer pr. time",
		REPORT_ARCHIVE_HEADER_RESOURCES : "Ressourcer",
		REPORT_ARCHIVE_DETAILS_FOR : "Rapport arkiv for &1 [&2] (&3)",
		REPORT_ARCHIVE_FLEET_CARGO : "Flåde fragtkapacitet",
		REPORT_ARCHIVE_IRAK_RANGE : "IPR rækkevidden",
		REPORT_ARCHIVE_CHART_TYPE : "Chart type",
		INSTALL_TITLE : "Galaxytool installation af version",
		INSTALL_PROGRESS : "Samlet fremgang",
		INSTALL_STEP : "Trin",
		INSTALL_CONTINUE : "Fortsæt",
		INSTALL_VALIDATE : "Valider",
		INSTALL_STEP1 : "Velkommen",
		INSTALL_STEP2 : "Skriverettigheds kontrol",
		INSTALL_STEP3 : "Database indstillinger",
		INSTALL_STEP4 : "OGame indstillinger",
		INSTALL_STEP5 : "Galaxytool indstillinger",
		INSTALL_STEP6 : "Admin kodeord",
		INSTALL_STEP7 : "Installer Galaxytool",
		INSTALL_STEP8 : "Færdiggør installation",
		INSTALL_FILE_DELETE_CHECK : "Venligst slet install.php og update.php fra din webserver.",
		INSTALL_STEP1_PHP_FAILED : "Din PHP-version &1 fungerer ikke med denne Galaxytool udgave",
		INSTALL_STEP1_FOPEN_FAILED : "Din PHP-version tillader ikke at åbne websider med FOPEN() kommando'en. Dette er nødvendigt for at bruge OGame API.",
		INSTALL_STEP1_WELCOME : "Velkommen til installationsguiden af Galaxytool. Du vil blive guidet igennem installationen af ​​Galaxytool.",
		INSTALL_STEP2_DESCRIPTION : "Sørg for, at din config.php og attributes.php filer har skriverettigheder aktiveret.",
		INSTALL_STEP2_DESCRIPTION2 : "Hvis du ikke ved, hvordan man kan opnå dette, skal du tage et kig her: &1",
		INSTALL_STEP2_FILE_NOT_WRITEABLE : "Filen er ikke skrivbar",
		INSTALL_STEP3_SERVER : "Database server",
		INSTALL_STEP3_USERNAME : "Brugernavn",
		INSTALL_STEP3_PASSWORD : "Kodeord",
		INSTALL_STEP3_DBNAME : "Database navn",
		INSTALL_STEP3_PREFIX : "Tabel prefix",
		INSTALL_STEP3_ENTER_PREFIX : "Eks. mytool_",
		INSTALL_STEP3_ENTER_SERVER : "Indtast serveradresse. Kontakt din system administrator hvis det er nødvendigt. Normalt er den korrekte værdi localhost.",
		INSTALL_STEP3_ENTER_USERNAME : "Indtast brugernavn til databasen",
		INSTALL_STEP3_ENTER_PASSWORD : "Indtast kodeord til databasen",
		INSTALL_STEP3_ENTER_DBNAME : "Indtast databasen navn, der skal anvendes til installation (skal eksisterer)",
		INSTALL_STEP3_CONNECT_FAILED : "Kunne ikke etablere forbindelse til databaseserveren",
		INSTALL_STEP3_DB_FAILED : "Database &1 ikke fundet",
		INSTALL_STEP3_MYSQL_VERSION_FAILED : "MySQL version &1 fungerer ikke med denne Galaxytool udgave",
		INSTALL_STEP4_URL : "OGame URL",
		OGAME_URL_DETAILS : "Indtast venligst den URL du ser, når du er logget på OGame. Baseret på denne URL vil værktøjet finde OGame API adressen, som kan anvendes til at fylde data i Galaxytool uden Galaxytoolbar. Denne API blev indført med OGame-version 4,1.",
		INSTALL_STEP4_UNIVERSE : "OGame Univers",
		INSTALL_STEP4_DEF_TO_DEBRIS : "Forsvar til ruinmark",
		INSTALL_STEP4_DEBRIS_RATE : "Flåde til ruinmark",
		INSTALL_STEP4_SPEED_RATE : "Speed rate",
		INSTALL_STEP4_ENTER_UNIVERSE : "Indtast dit OGame univers navn eller nummer (case sensitive).",
		INSTALL_STEP4_UNIVERSE_MISSING : "Du skal definere din univers",
		INSTALL_STEP4_ENTER_URL : "Indtast din OGame univers adresse",
		INSTALL_STEP4_URL_MISSING : "Du skal definere din OGame adresse",
		INSTALL_STEP4_URL_CHECK_FAILED : "Kunne ikke finde OGame API på &1",
		INSTALL_STEP4_GETSETTINGS : "Fetch settings",
		INSTALL_STEP5_TOOLNAME : "Galaxytool navn",
		INSTALL_STEP5_ENTER_TOOLNAME : "Dette er det navn, der vil blive vist på logon side for at identificere din Galaxytool",
		INSTALL_STEP5_LANGUAGE : "Default sprog",
		INSTALL_STEP5_EMAIL_TO : "Email til",
		INSTALL_STEP5_ENTER_EMAIL_TO : "Indtast den e-mail-adresse, hvor du gerne vil modtage meddelelser om registreringer",
		INSTALL_STEP5_EMAIL_FROM : "Email fra",
		INSTALL_STEP5_ENTER_EMAIL_FROM : "Denne e-mail-adresse vises som svar til alle mails sendt fra Galaxytool",
		INSTALL_STEP5_USE_PHPMAILER : "BrugPHPMailer",
		INSTALL_STEP5_MAXSHOUTS : "Maksimalt antal Shoutbox poster",
		INSTALL_STEP5_ENTER_USE_PHPMAILER : "Brug PHPMailer hvis din server ikke understøtter at sende e-mails som standard",
		INSTALL_PHPMAILER_HOST : "SMPT Host",
		INSTALL_PHPMAILER_HOST_EXAMPLE : "Eks. smtp.udbyder.dk",
		INSTALL_PHPMAILER_USER : "SMPT Brugernavn",
		INSTALL_PHPMAILER_USER_EXAMPLE : "Eks. bruger@udbyder.dk",
		INSTALL_PHPMAILER_PASS : "SMPT kodeord",
		INSTALL_PHPMAILER_SECURE : "Autentificering (eks. SSL)",
		INSTALL_PHPMAILER_PORT : "SMTP Port",
		INSTALL_STEP6_INTRO : "Angiv en adgangskode for <strong>admin</ strong> konto, som du skal bruge til din første logon til Galaxytool efter installationen.",
		INSTALL_STEP7_CONFIG : "Konfigurations fil oprettet",
		INSTALL_STEP7_CONFIG_FAILED : "Konfigurations fil ikke oprettet",
		INSTALL_STEP7_ATTRIBUTES : "Attributter fil oprettet",
		INSTALL_STEP7_ATTRIBUTES_FAILED : "Attributter fil ikke oprettet",
		INSTALL_STEP7_CREATED_TABLES : "Database tabeller oprettet",
		INSTALL_STEP8_INTRO : "Du har med succes installeret Galaxytool!",
		INSTALL_STEP8_LOAD_DATA : "Downloader OGame data ...",
		INSTALL_STEP8_LOAD_DATA_FINISHED : "Download af OGame data færdig",
		INSTALL_STEP8_DELETE_FILE : "Du skal nu slette installationsfilerne install.php og update.php fra din webserver.",
		INSTALL_STEP8_LOGON : "Venligst logon med <strong>admin</ strong> bruger og den adgangskode, du definerede tidligere.",
		UPDATE_START : "Starter opdatering til version &1",
		UPDATE_STEP_DONE : "Færdig",
		UPDATE_TITLE : "Galaxytool opdatering af version",
		UPDATE_STEP1_WELCOME : "Velkommen til opdateringsguiden af Galaxytool. Du vil blive guidet igennem opdatering af Galaxytool.",
		UPDATE_STEP1_BACKUP_FILES : "Som et første skridt, lave en backup af din <strong>config</ strong> mappe! Du bliver nødt til at erstatte den konfigurationen i tilfælde af fejl.",
		UPDATE_STEP1_BACKUP_DB : "Lav en <a href=\"http://www.ehow.com/how_2036600_create-database-php.html\">backup</ a> af din database.",
		UPDATE_STEP1_PROCEED : "Når backup er færdig, kan du gå videre med din opdatering.",
		UPDATE_STEP1 : "Velkommen",
		UPDATE_STEP2 : "Galaxytool indstillinger",
		UPDATE_STEP2_OLD_VERSION : "Tidligere Galaxytool version",
		UPDATE_STEP3 : "Update Galaxytool",
		UPDATE_STEP3_UPDATE_RUNNING : "Update kører, vent venligst...",
		UPDATE_STEP4 : "Færdiggør Update",
		UPDATE_STEP4_INTRO : "Du har opdateret Galaxytool!",
		UPDATE_STEP4_UPDATE_DONE : "Opdaterings trin udført.",
		UPDATE_FAILED : "Update fejlede.",
		GALAXYTOOL_DUMMY_TEXT : "dummy"
	})
);