function handle_day_change(a){try{switch(a){case "monday":case "tuesday":case "wednesday":case "thursday":case "friday":!1==dijit.byId(a).get("checked")?dijit.byId("workingday").set("checked",!1):!0==dijit.byId("monday").get("checked")&&(!0==dijit.byId("tuesday").get("checked")&&!0==dijit.byId("wednesday").get("checked")&&!0==dijit.byId("thursday").get("checked")&&!0==dijit.byId("friday").get("checked"))&&dijit.byId("workingday").set("checked",!0);break;case "saturday":case "sunday":!1==dijit.byId(a).get("checked")?
dijit.byId("weekend").set("checked",!1):!0==dijit.byId("saturday").get("checked")&&!0==dijit.byId("sunday").get("checked")&&dijit.byId("weekend").set("checked",!0);break;case "weekend":dijit.byId("saturday").set("checked",!1);dijit.byId("sunday").set("checked",!1);!0==dijit.byId(a).get("checked")&&(dijit.byId("saturday").set("checked",!0),dijit.byId("sunday").set("checked",!0));break;case "workingday":dijit.byId("monday").set("checked",!1),dijit.byId("tuesday").set("checked",!1),dijit.byId("wednesday").set("checked",
!1),dijit.byId("thursday").set("checked",!1),dijit.byId("friday").set("checked",!1),!0==dijit.byId(a).get("checked")&&(dijit.byId("monday").set("checked",!0),dijit.byId("tuesday").set("checked",!0),dijit.byId("wednesday").set("checked",!0),dijit.byId("thursday").set("checked",!0),dijit.byId("friday").set("checked",!0))}}catch(b){alert("handle_day_change: "+b)}}
function reload_url(){try{var a=dijit.byId("view").get("value");if(1>parseInt(player_id))return!1;var b=!0==dijit.byId("act_galaxyview").get("checked")?1:0,c=!0==dijit.byId("act_scans").get("checked")?1:0,d=!0==dijit.byId("act_messages").get("checked")?1:0,e=!0==dijit.byId("act_combat_reports").get("checked")?1:0,f=!0==dijit.byId("act_allypage").get("checked")?1:0,g=!0==dijit.byId("act_manual").get("checked")?1:0;if("day"==a){var h=!0==dijit.byId("monday").get("checked")?!0:!1,k=!0==dijit.byId("tuesday").get("checked")?
!0:!1,l=!0==dijit.byId("wednesday").get("checked")?!0:!1,m=!0==dijit.byId("thursday").get("checked")?!0:!1,n=!0==dijit.byId("friday").get("checked")?!0:!1,p=!0==dijit.byId("saturday").get("checked")?!0:!1,q=!0==dijit.byId("sunday").get("checked")?!0:!1;dijit.byId("weekend").get("checked");dijit.byId("workingday").get("checked")}var r=dojo.date.locale.format(dijit.byId("date_from").get("value"),{datePattern:"yyyy-MM-dd",selector:"date"}),s=dojo.date.locale.format(dijit.byId("date_to").get("value"),
{datePattern:"yyyy-MM-dd",selector:"date"}),b="ajax/ajax_activity_graph.php?playerid="+player_id+"&galaxy="+b+"&scans="+c+"&messages="+d+"&combats="+e+"&allypage="+f+"&manual="+g+"&time_from="+r+"&time_to="+s;"day"==a?(a="",!0==h&&(a+="1"),!0==k&&(a+="2"),!0==l&&(a+="3"),!0==m&&(a+="4"),!0==n&&(a+="5"),!0==p&&(a+="6"),!0==q&&(a+="7"),b+="&days="+a):b+="&weekview=true";dijit.byId("act_graph").set("href",b)}catch(t){alert("unexpected error at reload_url: "+t)}}
function set_player_active(a){dojo.xhrPost({url:"ajax/ajax_activities.php",content:{playerid:a,set_active:"true"},handleAs:"json",load:function(a){null!=a.messages?showMessages(a.messages):reload_url()},error:function(a){console.log("Error:");console.log(a)}})}
function set_player_activity(a){var b=dojo.date.locale.format(dijit.byId("date").get("value"),{datePattern:"yyyy-MM-dd",selector:"date"}),c=dijit.byId("time_h").get("value"),d=dijit.byId("time_m").get("value");""==b||(""==c||""==d)||dojo.xhrPost({url:"ajax/ajax_activities.php",content:{playerid:a,date:b,time_h:c,time_m:d},handleAs:"json",load:function(a){null!=a.messages?showMessages(a.messages):reload_url()},error:function(a){console.log("Error:");console.log(a)}})}
function selection_changed(a){"week"==dijit.byId("view").get("value")?dojo.byId("day_selection").style.display="none":dojo.byId("day_selection").style.display="inline";reload_url()};
