var FormSaveIDs=[];function showSaveScreen(c){FormSaveIDs=[];dojo.xhrPost({url:"ajax/ajax_forms_noAMD.php?type=get_save_ids&form_id="+c,handleAs:"json",load:function(c){dojo.forEach(c,function(a){null!==a&&FormSaveIDs.push(a.save_id)})},error:function(c){console.log("Error:");console.log(c)}});dijit.byId("SaveDialogContent").set("href","ajax/ajax_forms_noAMD.php?type=save_UI&form_id="+c);dijit.byId("SaveDialog").set("title",TEXT_GENERAL_SAVE_FORM);dijit.byId("SaveDialog").show()}
function showLoadScreen(c){dijit.byId("SaveDialogContent").set("href","ajax/ajax_forms_noAMD.php?type=load_UI&form_id="+c);dijit.byId("SaveDialog").set("title",TEXT_GENERAL_LOAD_FORM);dijit.byId("SaveDialog").show()}
function validateSaveScreen(c){dojo.byId("formsave_button").style.display="none";dojo.byId("formsave_loading_icon").style.display="";var e=dijit.byId("save_id").get("value"),a=!1;if(!0!==dijit.byId("formsave_overwrite").get("checked"))for(var d=0;d<FormSaveIDs.length;d++)if(FormSaveIDs[d]==e){a=!0;break}!1==a?saveFormData(c,e):(dojo.byId("formsave_overwrite_content").style.display="",dojo.byId("formsave_button").style.display="",dojo.byId("formsave_loading_icon").style.display="none")}
function saveFormData(c,e){var a,d,f=[];try{var h=dojo.byId(c);if(null==h)return alert("Wrong ID!"),!1;var b=h.getElementsByTagName("input");for(a=0;a<b.length;a++)if(!0!=b[a].hasAttribute("wairole")&&!0!=b[a].hasAttribute("readonly")&&"button"!=b[a].getAttribute("type"))if("radio"==b[a].getAttribute("type"))!0==b[a].checked&&f.push([b[a].name,b[a].value,"checked"]);else if("checkbox"==b[a].getAttribute("type")){try{var l=dijit.byId(b[a].id).get("checked")}catch(q){l=!1}!0==b[a].checked||b[a].hasAttribute("value")&&
!0==l?f.push([[b[a].id,b[a].name],"checked"]):f.push([[b[a].id,b[a].name],""])}else"submit"!=b[a].getAttribute("type")&&("userman1"==c?"id"!=b[a].name&&("username"!=b[a].name&&"ingameusername"!=b[a].name&&"email"!=b[a].name)&&f.push([[b[a].id,b[a].name],b[a].value]):f.push([[b[a].id,b[a].name],b[a].value]));var n=h.getElementsByTagName("textarea");for(a=0;a<n.length;a++)f.push([[b[a].id,b[a].name],n[a].value]);var g=h.getElementsByTagName("select"),m;for(a=0;a<g.length;a++){m=g[a].getElementsByTagName("option");
for(d=0;d<m.length;d++)!0==m[d].selected&&f.push([g[a].name,m[d].value])}var g=h.getElementsByTagName("table"),p;for(a=0;a<g.length;a++)p=g[a].getAttribute("class"),null!=p&&0<p.indexOf("dijitSelect")&&f.push([[g[a].id,""],dijit.byId(g[a].id).get("value")]);saveData(c,e,f)}catch(r){console.log("error:"),console.log(r)}dojo.byId("formsave_overwrite_content").style.display="none";dojo.byId("formsave_button").style.display="";dojo.byId("formsave_loading_icon").style.display="none";dijit.byId("SaveDialog").hide()}
function loadFormData(c,e){var a;dojo.xhrPost({url:"ajax/ajax_forms_noAMD.php?type=load_data&form_id="+c+"&save_id="+e,handleAs:"json",load:function(d){null!=d.messages&&showMessages(d.messages);if(0!=d.form_content.length){content=d.form_content;for(d=0;d<content.length;++d)try{var c=content[d][0]instanceof Array?""!=content[d][0][0]?document.getElementById(content[d][0][0]):document.getElementsByName(content[d][0][1]):document.getElementsByName(content[d][0]);if(1==c.length)a=c[0];else if((c instanceof
Array||c instanceof Object)&&1<c.length){for(k=0;k<c.length;++k)if(a=c[k],"radio"==a.getAttribute("type"))if(a.value==content[d][1]&&"checked"==content[d][2])if(-1<a.className.indexOf("dijit"))dijit.byId(content[d][0]+""+a.value).set("checked",!0);else{var e=document.createAttribute("checked");a.setAttributeNode(e);a.checked=!0}else a.checked=!1;else console.log("unexpected else path");continue}else a=c;if("SELECT"==a.nodeName)for(var b=0;b<a.childNodes.length;++b)if(a.childNodes[b].value==content[d][1]){var l=
document.createAttribute("selected");a.childNodes[b].setAttributeNode(l);a.childNodes[b].selected=!0}else a.childNodes[b].selected=!1;else if("TABLE"==a.nodeName)dijit.byId(a.id).set("value",content[d][1]);else if("radio"==a.getAttribute("type"))console.log("Radiobuttons must be handled via NAME but not ID");else if("checkbox"==a.getAttribute("type"))if("checked"==content[d][1]){a.checked=!0;try{dijit.byId(a.id).set("checked",!0)}catch(q){}}else{a.checked=!1;try{dijit.byId(a.id).set("checked",!1)}catch(n){}}else a.value=
content[d][1]}catch(g){}}dijit.byId("SaveDialog").hide()},error:function(a){console.log("Error:");console.log(a)}})}function deleteFormData(c,e){dojo.xhrPost({url:"ajax/ajax_forms_noAMD.php?type=delete_data&form_id="+c+"&save_id="+e,handleAs:"json",load:function(a){showMessages(a);dijit.byId("SaveDialog").hide()},error:function(a){console.log("Error:");console.log(a)}})}
function saveData(c,e,a){c={url:"ajax/ajax_forms_noAMD.php?type=save_data&form_id="+c+"&save_id="+e,handleAs:"json",content:{form_content:dojo.toJson(a)},load:function(a){showMessages(a)},error:function(a){console.log("Error:");console.log(a)}};dojo.xhrPost(c)};
