var galaxytool=window.galaxytool||{};
galaxytool.PlayerInfo={moonReportFormatter:function(a,b,c){return galaxytool.PlayerInfo.reportFormatter(a,b,c,moonstore,moongrid)},planetReportFormatter:function(a,b,c){return galaxytool.PlayerInfo.reportFormatter(a,b,c,planetstore,planetgrid)},moonReportFormatter2:function(a,b,c){return galaxytool.PlayerInfo.reportFormatter2(a,b,c,moonstore,moongrid,!0)},planetReportFormatter2:function(a,b,c){return galaxytool.PlayerInfo.reportFormatter2(a,b,c,planetstore,planetgrid,!1)},reportFormatter:function(a,
b,c,e,d){b=d.getItem(b).key[0];if("id"==b||"h1"==b||"h3"==b||"h4"==b)c.customClasses.push("public"),"msg_id"!=b&&(a='<div style="height:16px;">'+a+"</div>");"coordinates"==b&&(a='<div style="height:16px;">'+a+"</div>");if("res_sum"==b||"def_sum"==b)a="&sum; "+a,c.customClasses.push("sum_row");return a},reportFormatter2:function(a,b,c,e,d,f){c.customClasses.push("centered_text");if(0==b)return f?"<img onclick=\"galaxytool.ReportFetch.showReport('"+a+'\',true)" src="../images/magnifier2.png" style="cursor: pointer;">':
"<img onclick=\"galaxytool.ReportFetch.showReport('"+a+'\',false)" src="../images/magnifier2.png" style="cursor: pointer;">';b=d.getItem(b).key[0];if("res_sum"==b||"fleet_sum"==b||"def_sum"==b)c.customClasses.push("sum_row");else if(("metal"==b||"crystal"==b||"deuterium"==b)&&0<a){e=0;var g=d.getItem(10)[c.field][0];"h4"!=d.getItem(10).key[0]&&console.log("h4 new lines added - adjust playerinformation.js!");if("ok"==g)if(!1==f){switch(b){case "metal":e=d.getItem(19)[c.field][0];break;case "crystal":e=
d.getItem(20)[c.field][0];break;case "deuterium":e=d.getItem(21)[c.field][0]}"mesp"!=d.getItem(19).key[0]&&console.log("13 new lines added - adjust playerinformation.js!")}else{switch(b){case "metal":e=d.getItem(13)[c.field][0];break;case "crystal":e=d.getItem(14)[c.field][0];break;case "deuterium":e=d.getItem(15)[c.field][0]}"mesp"!=d.getItem(13).key[0]&&console.log("20 new lines added - adjust playerinformation.js!")}if("ok"==g||!0==f)d=galaxytool.General.getStorageCapacity(parseInt(e)),f=parseInt(a),
d<=f?c.customClasses.push("traffic_light_red"):0.9*d<=f&&c.customClasses.push("traffic_light_yellow")}else if("h1"==b||"h3"==b||"h4"==b)return"";return!isNaN(parseFloat(a))&&isFinite(a)?galaxytool.General.numberFormat(a):a},createMoonTable:function(){require(["dojo/data/ItemFileReadStore"],function(a){"object"==typeof player_moon_data.items&&(a=new a({data:player_moon_data}),moongrid.setStore(a),a=galaxytool.PlayerInfo.getLayout(galaxytool.PlayerInfo.moonReportFormatter,galaxytool.PlayerInfo.moonReportFormatter2,
player_moon_data.items[0]),moongrid.set("structure",a))})},createPlanetTable:function(){require(["dojo/data/ItemFileReadStore"],function(a){"object"==typeof player_planet_data.items&&(a=new a({data:player_planet_data}),planetgrid.setStore(a),a=galaxytool.PlayerInfo.getLayout(galaxytool.PlayerInfo.planetReportFormatter,galaxytool.PlayerInfo.planetReportFormatter2,player_planet_data.items[0]),planetgrid.set("structure",a))})},getLayout:function(a,b,c){var e=0,d;for(d in c)0==d.indexOf("c")&&e++;a={noscroll:!0,
cells:[{field:"c0",name:"c0",width:"150px",formatter:a}]};c=Array(e);for(d=1;d<e;d++)c[d-1]={field:"c"+d,name:"",width:"85px",formatter:b};return[a,c]},deletePlayer:function(a){require(["dojo/request","galaxytool/MessageHandling","dojo/i18n!./nls/galaxytool.js"],function(b,c,e){!0==confirm(e.ADMIN_SAFETY)&&(e=parseInt(a),1>e||b.post("ajax/ajax_stats.php?type=player_delete&player_id="+e,{handleAs:"json"}).then(function(a){null!=a.messages&&(new c(a.messages,"../images")).showMessages();!0==a.result&&
(window.location.href="index.php")},function(a){console.log("Error:");console.log(a)}))})},changePlayerStatus:function(a,b){var c=parseInt(a);1>c||require(["dojo/request","dojo/dom-class","galaxytool/MessageHandling"],function(a,d,f){a.post("ajax/ajax_stats.php?type=change_player&player_id="+c+"&new_status="+b,{handleAs:"json"}).then(function(a){null!=a.messages&&(new f(a.messages,"../images")).showMessages();!0==a.result&&d.add("pn_"+c,b)},function(a){console.log("Error:");console.log(a)})})}};
require("dojo/parser dojo/ready dojo/on dojo/dom dojo/dom-attr dijit/registry dojo/dom-style dojo/query dojo/NodeList-dom dijit/Dialog dijit/TooltipDialog dijit/TitlePane dijit/layout/ContentPane dijit/layout/BorderContainer dijit/layout/TabContainer dijit/Calendar dijit/form/DropDownButton dijit/form/CheckBox dijit/form/DateTextBox dijit/form/Select dijit/form/Textarea dojox/grid/DataGrid dojo/data/ItemFileReadStore".split(" "),function(a,b,c,e,d,f,g,h){b(function(){c(f.byId("reporttooltip"),"MouseLeave",
galaxytool.ReportFetch.closeReportTooltip);c(f.byId("reporttooltip"),"MouseOver",galaxytool.ReportFetch.reportTooltipMouseOver);var a=window.location.hash;if(""!=a)try{a=a.replace(/#select_/,""),f.byId("tabcontainer").selectChild(f.byId(a))}catch(b){}tabcontainer.watch("selectedChildWidget",function(a,b,c){window.location.hash="#select_"+c.id;g.set("messageArea","display","none");("tab5"==c.id||"tab6"==c.id)&&h(".dojoxGridMasterHeader").style("display","none")});null!=e.byId("tab5")&&galaxytool.PlayerInfo.createPlanetTable();
null!=e.byId("tab6")&&galaxytool.PlayerInfo.createMoonTable();("tab5"==a||"tab6"==a)&&h(".dojoxGrid-header").style("display","none")})});
