var galaxytool=window.galaxytool||{};
galaxytool.StartPage={register_visible:!1,login_errors:!1,registerFade:function(){require(["dojo/dom","dojo/_base/fx","dojo/i18n!./secret/nls/galaxytool.js","dojo/domReady!"],function(b,a,d){!1==galaxytool.StartPage.register_visible?(b.byId("login").style.display="block",a.fadeIn({node:"login"}).play(),b.byId("loginBtn").innerHTML=d.INDEX_CLOSE,galaxytool.StartPage.register_visible=!0):(a.fadeOut({node:"login"}).play(),b.byId("loginBtn").innerHTML=d.L_REGISTER,b.byId("login").style.display="none",
galaxytool.StartPage.register_visible=!1)})},show:function(b){require(["dojo/dom-style"],function(a){a.set("mainContent","display","none");a.set("messageArea","display","none");a.set("passwordLost","display","none");a.set("loadingArea","display","none");"mainContent"==b&&a.set("mainContent","display","block");"messageArea"==b&&a.set("messageArea","display","block");"passwordLost"==b&&a.set("passwordLost","display","block");"loadingArea"==b&&a.set("loadingArea","display","block")})},showLostPassword:function(){galaxytool.StartPage.show("passwordLost")},
showMainContent:function(){galaxytool.StartPage.show("mainContent")},resetPassword:function(){galaxytool.StartPage.show("loadingArea");require(["dojo/dom","dojo/request","dojo/dom-form","galaxytool/MessageHandling"],function(b,a,d,c){a.post("secret/ajax/ajax_startpage.php?type=reset",{data:d.toObject(b.byId("pwLostForm")),handleAs:"json"}).then(function(a){a=new c(a,"images");galaxytool.StartPage.show("messageArea");a.showMessages()},function(a){console.log("Error:");console.log(a)})})},validateAndSubmit:function(){require(["dojo/dom",
"dojo/dom-class","dojox/validate/web"],function(b,a,d){var c=!1;""==b.byId("loginusername").value?(c=!0,a.add("loginusername","formError")):a.remove("loginusername","formError");""==b.byId("password1").value?(c=!0,a.add("password1","formError")):a.remove("password1","formError");""==b.byId("password2").value?(c=!0,a.add("password2","formError")):a.remove("password2","formError");""==b.byId("email").value?(c=!0,a.add("email","formError")):a.remove("email","formError");c||(b.byId("password1").value!=
b.byId("password2").value&&(a.add("password1","formError"),a.add("password2","formError"),c=!0),!0!=d.isEmailAddress(b.byId("email").value)&&(a.add("email","formError"),c=!0),c||document.forms.subscribeForm.submit())});return!1},checkPasswordStrength:function(){require(["dojo/dom","dojo/dom-class","dojo/_base/lang"],function(b,a,d){d=d.trim(b.byId("password1").value);a.remove("password_strength","password_strength_weak");a.remove("password_strength","password_strength_good");a.remove("password_strength",
"password_strength_strong");a.remove("password_strength","password_strength_very_strong");b.byId("password_strength").title="";if(""!=d)if(5<d.length){var c=0;d.match(/\d{1,}/)&&c++;d.match(/[a-z\u00e4\u00f6\u00fc]{1,}/)&&c++;d.match(/[A-Z\u00c4\u00dc\u00d6]{1,}/)&&c++;d.match(/\W/)&&c++;7<d.length&&3<c?(a.add("password_strength","password_strength_very_strong"),b.byId("password_strength").title=register_vstrong):2<c?(a.add("password_strength","password_strength_strong"),b.byId("password_strength").title=
register_strong):1<c?(a.add("password_strength","password_strength_good"),b.byId("password_strength").title=register_good):(a.add("password_strength","password_strength_weak"),b.byId("password_strength").title=register_weak)}else a.add("password_strength","password_strength_weak"),b.byId("password_strength").title=register_weak})}};
require("dojo/parser dojo/ready dojo/query dojo/on dojo/dom dojo/dom-style dijit/form/Select galaxytool/MessageHandling dojo/NodeList-dom".split(" "),function(b,a,d,c,e,g,h,f){a(function(){b.parse();var a=e.byId("password1");c(a,"change",galaxytool.StartPage.checkPasswordStrength);c(a,"keyup",galaxytool.StartPage.checkPasswordStrength);d(".startsHidden").style("opacity",100).removeClass("startsHidden");!1!=galaxytool.StartPage.login_errors&&(a=new f(galaxytool.StartPage.login_errors,"images"),galaxytool.StartPage.show("messageArea"),
a.showMessages())})});
