dojo.require("dojox.grid.EnhancedGrid");dojo.require("dojox.grid.enhanced.plugins.Pagination");dojo.require("dojo.parser");var stats_show_tooltip=!1,stats_tooltip_requested=!1,stats_current_timeout=null,stats_graph_buffer={},stats_first_tab=null,stats_suffix="1";
function galaxytool_showTooltip(a){if(!(0>a.cellIndex)&&0==a.cellIndex){var c=a.grid.store.getValue(a.grid.getItem(a.rowIndex),"username"),c=c+(" @ "+a.grid.store.getValue(a.grid.getItem(a.rowIndex),"last_update"));dijit.showTooltip(c,a.cellNode)}}function galaxytool_hideTooltip(a){dijit.hideTooltip(a.cellNode)}function galaxytool_centered_formatter(a,c,b){b.customClasses.push("centered_text");return a}
function galaxytool_pstats_rank1(a,c,b){return galaxytool_stats_rank(a,c,b,playergrid1,playerstore1,"p_status")}function galaxytool_pstats_rank2(a,c,b){return galaxytool_stats_rank(a,c,b,playergrid2,playerstore2,"p_status")}function galaxytool_astats_rank1(a,c,b){return galaxytool_stats_rank(a,c,b,allygrid1,allystore1,"a_status")}function galaxytool_astats_rank2(a,c,b){return galaxytool_stats_rank(a,c,b,allygrid2,allystore2,"a_status")}
function galaxytool_stats_rank(a,c,b,d,e,f){b.customClasses.push("centered_text");"nothing"!=e.getValues(d.getItem(c),f)&&b.customClasses.push("bg_"+f);return a}function galaxytool_pstats_name1(a,c,b){return galaxytool_pstats_name(a,c,b,playergrid1,playerstore1,"p_status")}function galaxytool_pstats_name2(a,c,b){return galaxytool_pstats_name(a,c,b,playergrid2,playerstore2,"p_status")}
function galaxytool_pstats_name(a,c,b,d,e,f){b.customClasses.push("centered_text");b.customClasses.push("hyperlink");b.customClasses.push("stats_text");b=e.getValues(d.getItem(c),f);return a='<a href="playerinformation.php?id='+e.getValues(d.getItem(c),"id")+'" class="'+b+'">'+a+"</a>"}function galaxytool_astats_name1(a,c,b){return galaxytool_astats_name(a,c,b,allygrid1,allystore1)}function galaxytool_astats_name2(a,c,b){return galaxytool_astats_name(a,c,b,allygrid2,allystore2)}
function galaxytool_astats_name(a,c,b,d,e){b.customClasses.push("centered_text");b.customClasses.push("hyperlink");b.customClasses.push("stats_text");b=e.getValues(d.getItem(c),"a_status");if(""==b)return a;c=e.getValues(d.getItem(c),"id");return 0==c?'<span class="'+b+'">'+a+"</span>":'<a href="allyinformation.php?id='+c+'" class="'+b+'">'+a+"</a>"}function galaxytool_pstats_ally1(a,c,b){return galaxytool_pstats_ally(a,c,b,playergrid1,playerstore1,"a_status")}
function galaxytool_pstats_ally2(a,c,b){return galaxytool_pstats_ally(a,c,b,playergrid2,playerstore2,"a_status")}function galaxytool_pstats_ally(a,c,b,d,e,f){b.customClasses.push("centered_text");b.customClasses.push("hyperlink");b.customClasses.push("stats_text");b=e.getValues(d.getItem(c),f);if(""==b)return a;c=e.getValues(d.getItem(c),"a_id");return 0==c?'<span class="'+b+'">'+a+"</span>":'<a href="allyinformation.php?id='+c+'" class="'+b+'">'+a+"</a>"}
function galaxytool_pstats_status(a,c,b){b=c="";for(var d=0;d<a.length;d++)switch(c=a.substr(d,1),c){case stats_banned:b+='<span class="banned">'+stats_banned+"</span>";break;case stats_vacation:b+='<span class="vacation">'+stats_vacation+"</span>";break;case stats_noob:b+='<span class="noob">'+stats_noob+"</span>";break;case stats_inactive:b+='<span class="inactive">'+stats_inactive+"</span>";break;case stats_long_inactive:b+='<span class="longinactive">'+stats_long_inactive+"</span>";break;case stats_outlaw:b+=
'<span class="outlaw">'+stats_outlaw+"</span>"}return b}function galaxytool_stats_score(a,c,b){b.customClasses.push("centered_text");b.customClasses.push("stats_text");return NumberFormat(a)}function galaxytool_pstats_research1(a,c,b){return galaxytool_stats(a,c,b,playergrid1,playerstore1,"rrank")}function galaxytool_pstats_research2(a,c,b){return galaxytool_stats(a,c,b,playergrid2,playerstore2,"rrank")}
function galaxytool_pstats_fleet1(a,c,b){return galaxytool_stats(a,c,b,playergrid1,playerstore1,"frank")}function galaxytool_pstats_fleet2(a,c,b){return galaxytool_stats(a,c,b,playergrid2,playerstore2,"frank")}function galaxytool_pstats_economy1(a,c,b){return galaxytool_stats(a,c,b,playergrid1,playerstore1,"erank")}function galaxytool_pstats_economy2(a,c,b){return galaxytool_stats(a,c,b,playergrid2,playerstore2,"erank")}
function galaxytool_pstats_honour1(a,c,b){return galaxytool_stats(a,c,b,playergrid1,playerstore1,"hrank")}function galaxytool_pstats_honour2(a,c,b){return galaxytool_stats(a,c,b,playergrid2,playerstore2,"hrank")}function galaxytool_pstats_md1(a,c,b){return galaxytool_stats(a,c,b,playergrid1,playerstore1,"fdrank")}function galaxytool_pstats_md2(a,c,b){return galaxytool_stats(a,c,b,playergrid2,playerstore2,"fdrank")}
function galaxytool_pstats_ml1(a,c,b){return galaxytool_stats(a,c,b,playergrid1,playerstore1,"flrank")}function galaxytool_pstats_ml2(a,c,b){return galaxytool_stats(a,c,b,playergrid2,playerstore2,"flrank")}function galaxytool_astats_research1(a,c,b){return galaxytool_stats(a,c,b,allygrid1,allystore1,"rrank")}function galaxytool_astats_research2(a,c,b){return galaxytool_stats(a,c,b,allygrid2,allystore2,"rrank")}
function galaxytool_astats_fleet1(a,c,b){return galaxytool_stats(a,c,b,allygrid1,allystore1,"frank")}function galaxytool_astats_fleet2(a,c,b){return galaxytool_stats(a,c,b,allygrid2,allystore2,"frank")}function galaxytool_astats_economy1(a,c,b){return galaxytool_stats(a,c,b,allygrid1,allystore1,"erank")}function galaxytool_astats_economy2(a,c,b){return galaxytool_stats(a,c,b,allygrid2,allystore2,"erank")}
function galaxytool_astats_honour1(a,c,b){return galaxytool_stats(a,c,b,allygrid1,allystore1,"hrank")}function galaxytool_astats_honour2(a,c,b){return galaxytool_stats(a,c,b,allygrid2,allystore2,"hrank")}function galaxytool_astats_md1(a,c,b){return galaxytool_stats(a,c,b,allygrid1,allystore1,"fdrank")}function galaxytool_astats_md2(a,c,b){return galaxytool_stats(a,c,b,allygrid2,allystore2,"fdrank")}
function galaxytool_astats_ml1(a,c,b){return galaxytool_stats(a,c,b,allygrid1,allystore1,"flrank")}function galaxytool_astats_ml2(a,c,b){return galaxytool_stats(a,c,b,allygrid2,allystore2,"flrank")}function galaxytool_stats(a,c,b,d,e,f){b.customClasses.push("centered_text");b.customClasses.push("stats_text");c=e.getValues(d.getItem(c),f);a=NumberFormat(a);return a+" ("+c+")"}function galaxytool_compare_float(a,c){return parseFloat(a)<parseFloat(c)?-1:parseFloat(a)>parseFloat(c)?1:0}
function galaxytool_load_new_stats(a,c,b,d){var e=dijit.byId("select_inactive"+c).get("value"),f=dijit.byId("select_vacation"+c).get("value");c=dijit.byId("select_noob"+c).get("value");a="ajax/ajax_stats.php?type="+a;"inactive"==e?a+="&inactive=i":"long_inactive"==e?a+="&inactive=I":"yes"==e?a+="&inactive=true":"no"==e&&(a+="&inactive=false");"yes"==f?a+="&vacation=true":"no"==f&&(a+="&vacation=false");"yes"==c?a+="&noob=true":"no"==c&&(a+="&noob=false");d.url=a;d.close();b.setStore(d)}
function galaxytool_playerstats_select_row(a){dijit.byId("playerstatus_button"+stats_suffix).set("disabled",!1);try{dijit.byId("delete_player_button"+stats_suffix).set("disabled",!1)}catch(c){}}function galaxytool_playerstats_unselect_row(a){dijit.byId("playerstatus_button"+stats_suffix).set("disabled",!0);try{dijit.byId("delete_player_button"+stats_suffix).set("disabled",!0)}catch(c){}}
function galaxytool_allystats_select_row(a){dijit.byId("details_button"+stats_suffix).set("disabled",!1);try{dijit.byId("allystatus_button"+stats_suffix).set("disabled",!1),dijit.byId("delete_ally_button"+stats_suffix).set("disabled",!1)}catch(c){}}function galaxytool_allystats_unselect_row(a){dijit.byId("details_button"+stats_suffix).set("disabled",!0);try{dijit.byId("allystatus_button"+stats_suffix).set("disabled",!0),dijit.byId("delete_ally_button"+stats_suffix).set("disabled",!0)}catch(c){}}
function galaxytool_playerstatus(a,c,b){a={url:"ajax/ajax_stats.php?type=change_player&player_id="+c.store.getValue(c.selection.getFirstSelected(),"id")+"&new_status="+a,handleAs:"json",load:function(a){null!=a.messages?showMessages(a.messages):(b.close(),c.setStore(b))},error:function(a){console.log("Error:");console.log(a)}};dojo.xhrPost(a)}
function galaxytool_delete_player(a,c){if(!0==confirm(stats_confirm_delete)){var b={url:"ajax/ajax_stats.php?type=player_delete&player_id="+a.store.getValue(a.selection.getFirstSelected(),"id"),handleAs:"json",load:function(b){null!=b.messages?showMessages(b.messages):(c.close(),a.setStore(c))},error:function(a){console.log("Error:");console.log(a)}};dojo.xhrPost(b)}}
function galaxytool_allystatus(a,c,b){a={url:"ajax/ajax_stats.php?type=change_alliance&alliance_id="+c.store.getValue(c.selection.getFirstSelected(),"id")+"&new_status="+a,handleAs:"json",load:function(a){null!=a.messages?showMessages(a.messages):(b.close(),c.setStore(b))},error:function(a){console.log("Error:");console.log(a)}};dojo.xhrPost(a)}
function galaxytool_delete_ally(a,c){if(!0==confirm(stats_confirm_delete)){var b={url:"ajax/ajax_stats.php?type=alliance_delete&alliance_id="+a.store.getValue(a.selection.getFirstSelected(),"id"),handleAs:"json",load:function(b){null!=b.messages?showMessages(b.messages):(c.close(),a.setStore(c))},error:function(a){console.log("Error:");console.log(a)}};dojo.xhrPost(b)}}
function galaxytool_ally_info(a,c,b){var d=c.store.getValue(c.selection.getFirstSelected(),"id");b="ajax/ajax_stats.php?type=graph&id="+d;c=stats_graph_buffer["ag_"+d];"undefined"!==typeof c&&null!=c?(b=dijit.byId("AllyDetailsDialog"),b.set("content",c),b.show()):dojo.xhrPost({url:b,handleAs:"text",load:function(b){stats_graph_buffer["ag_"+d]=b;var c=dijit.byId("AllyDetailsDialog"+a);c.set("content",b);c.show()},error:function(a){console.log("Error:");console.log(a)}})}
function galaxytool_player_tab_loaded(a){dojo.connect(playergrid1,"onRowMouseOver",galaxytool_showTooltip);dojo.connect(playergrid1,"onRowMouseOut",galaxytool_hideTooltip);dojo.connect(playergrid1,"onSelected",galaxytool_playerstats_select_row);dojo.connect(playergrid1,"onDeselected",galaxytool_playerstats_unselect_row)}
function galaxytool_player_tab_b_loaded(a){dojo.connect(playergrid2,"onRowMouseOver",galaxytool_showTooltip);dojo.connect(playergrid2,"onRowMouseOut",galaxytool_hideTooltip);dojo.connect(playergrid2,"onSelected",galaxytool_playerstats_select_row);dojo.connect(playergrid2,"onDeselected",galaxytool_playerstats_unselect_row)}
function galaxytool_ally_tab_loaded(a){dojo.connect(allygrid1,"onRowMouseOver",galaxytool_showTooltip);dojo.connect(allygrid1,"onRowMouseOut",galaxytool_hideTooltip);dojo.connect(allygrid1,"onSelected",galaxytool_allystats_select_row);dojo.connect(allygrid1,"onDeselected",galaxytool_allystats_unselect_row)}
function galaxytool_ally_tab_b_loaded(a){dojo.connect(allygrid2,"onRowMouseOver",galaxytool_showTooltip);dojo.connect(allygrid2,"onRowMouseOut",galaxytool_hideTooltip);dojo.connect(allygrid2,"onSelected",galaxytool_allystats_select_row);dojo.connect(allygrid2,"onDeselected",galaxytool_allystats_unselect_row)}
function galaxytool_stats_init(){var a=window.location.hash;stats_first_tab=a;if(""!=a)try{a=a.replace(/#select_/,""),dijit.byId("tabcontainer").selectChild(dijit.byId(a))}catch(c){console.log("error: "),console.log(c)}dojo.subscribe("tabcontainer-selectChild",function(a){a=a.get("id");window.location.hash="#select_"+a;"tab1"==a&&(null!=stats_first_tab&&"tab1"!=stats_first_tab)&&(dijit.byId("playergrid1").render(),stats_first_tab=null)});dojo.connect(dijit.byId("tab1"),"onLoad",galaxytool_player_tab_loaded);
dojo.connect(dijit.byId("tab1b"),"onLoad",galaxytool_player_tab_b_loaded);dojo.connect(dijit.byId("tab2"),"onLoad",galaxytool_ally_tab_loaded);dojo.connect(dijit.byId("tab2b"),"onLoad",galaxytool_ally_tab_b_loaded)}dojo.ready(galaxytool_stats_init);
