var Galaxytool_install_step=1,nextButtonHandler=null,PW_mismatch_tooltip=null;
function update_tool(){var a=dijit.byId("url").get("value"),a={url:"secret/ajax/ajax_update.php?step=3",handleAs:"json",content:{old_version:dijit.byId("old_galaxytool").get("value"),url:a},load:function(b){null!=b.messages&&showMessages(b.messages,"./images",!1);!0==b.result?dojo.byId("step3update").innerHTML=TEXT_UPDATE_DONE:dojo.byId("step3update").innerHTML=TEXT_UPDATE_FAILED;!0==b.result&&(dijit.byId("nextButton").set("label",TEXT_INSTALL_CONTINUE),dojo.disconnect(nextButtonHandler),nextButtonHandler=
dojo.connect(dijit.byId("nextButton"),"onClick",next))},error:function(b){console.log("Error:");console.log(b)}};dojo.xhrPost(a)}
function download_data(){""!=dijit.byId("url").get("value")&&dojo.xhrPost({url:"secret/ajax/ajax_update.php?step=4",handleAs:"json",load:function(a){null!=a.messages&&showMessages(a.messages,"./images",!1);!0==a.result?dojo.byId("step4download").innerHTML=TEXT_UPDATE_DONE:dojo.byId("step4download").innerHTML=TEXT_UPDATE_FAILED},error:function(a){console.log("Error:");console.log(a)}})}
function validate_step2(){dojo.byId("messageArea").style.display="none";var a=dijit.byId("url").get("value");!1==dijit.byId("url").isValid()?dijit.byId("url").set("state","Error"):(a={url:"secret/ajax/ajax_update.php?step=2",content:{old_version:dijit.byId("old_galaxytool").get("value"),url:a},handleAs:"json",load:function(b){var a=!1;null!=b.messages&&(showMessages(b.messages,"./images"),a=!0);!1==a?(dijit.byId("nextButton").set("label",TEXT_INSTALL_CONTINUE),dojo.disconnect(nextButtonHandler),nextButtonHandler=
dojo.connect(dijit.byId("nextButton"),"onClick",next)):(dijit.byId("nextButton").set("label",TEXT_INSTALL_VALIDATE),dojo.disconnect(nextButtonHandler),nextButtonHandler=dojo.connect(dijit.byId("nextButton"),"onClick",validate))},error:function(a){console.log("Error:");console.log(a)}},dojo.xhrPost(a))}
function show_step(a,b,c){dojo.byId("update_progress_title").innerHTML=TEXT_UPDATE_STEPS[b];dojo.byId("progress_step"+a).className="step_disabled";dojo.byId("progress_step"+b).className="step_enabled";!0==c?(dijit.byId("nextButton").set("label",TEXT_INSTALL_VALIDATE),dojo.disconnect(nextButtonHandler),nextButtonHandler=dojo.connect(dijit.byId("nextButton"),"onClick",validate)):(dijit.byId("nextButton").set("label",TEXT_INSTALL_CONTINUE),dojo.disconnect(nextButtonHandler),nextButtonHandler=dojo.connect(dijit.byId("nextButton"),
"onClick",next));Galaxytool_install_step=b;switch(b){case 3:update_tool();break;case 4:dojo.disconnect(nextButtonHandler),dojo.byId("nextButton").style.display="none",download_data()}}function validate(){step=parseInt(Galaxytool_install_step);if(!(2>step||8<step))switch(step){case 2:validate_step2()}}
function next(){dijit.byId("nextButton").set("disabled",!0);dojo.byId("messageArea").style.display="none";step=parseInt(Galaxytool_install_step);if(!(1>step||7<step)){switch(step){case 1:show_step(1,2,!0);break;case 2:show_step(2,3,!1);break;case 3:show_step(3,4,!1);break;default:console.log("To be implemented for step "+step);return}dojo.fx.wipeOut({node:dojo.byId("step"+step)}).play();dojo.fx.wipeIn({node:dojo.byId("step"+(step+1))}).play();dijit.byId("nextButton").set("disabled",!1)}}
function galaxytool_update_init(){dojo.disconnect(nextButtonHandler);nextButtonHandler=dojo.connect(dijit.byId("nextButton"),"onClick",next)}dojo.ready(galaxytool_update_init);
