define(
	({
		REPORT_WHEN : "z dnia",
		RESOURCES_ON : "Surowce na",
		PLAYER_BANNED : "g",
		PLAYER_VACATION_MODE : "u",
		PLAYER_NOOB : "s",
		PLAYER_INACTIVE : "i",
		PLAYER_LONG_INACTIVE : "I",
		PLAYER_OUTLAW : "o",
		L_USERNAME : "Nazwa użytkownika",
		L_PASSWORD : "Hasło",
		L_LOGINFAILURE : "Niepoprawna nazwa użytkownika lub hasło albo twoje konto nie zostało jeszcze aktywowane.",
		L_TOKENFAILURE : "Twój klucz logowania jest błędny albo twoje konto nie jest jeszcze aktywne.",
		L_LOGINTEXT : "Proszę się zalogować.",
		L_LANGUAGE : "Dostępne języki:",
		L_TIMEOUT : "Czas sesji przekroczony!",
		L_REGISTER : "Rejestracja",
		L_PWLOST : "Przypomnienie hasła",
		INDEX_TITLE : "OGame Galaxytool - Przegląd",
		INDEX_INFO : "Informacje",
		INDEX_ENTRIES : "Ilość wszystkich dodanych układów",
		INDEX_ENTRIES_LASTWEEK : "Nowe układy w ostatnim tygodniu",
		INDEX_ENTRIES_TO_OLD : "Układy starsze niż jeden miesiąc",
		INDEX_REGISTERED_USERS : "Zarejestrowani użytkownicy",
		INDEX_PAGEFORWARD : "Kliknij tutaj, jeśli twoja przeglądarka nie obsługuje przekierowań strony.",
		INDEX_NOTICES : "Notatki",
		INDEX_PLAYERS : "Statystyki graczy",
		INDEX_ALLIES : "Statystyki sojuszy",
		INDEX_REPORTS : "Raporty szpiegowskie",
		INDEX_VERSION : "Ostatnia wersja do pobrania",
		INDEX_LATEST_VERSION : "Brak nowszej wersji",
		INDEX_SHOUTBOX : "ShoutBox",
		INDEX_NOENTRY : "Brak wpisów",
		INDEX_COMMENT : "Twój wpis",
		INDEX_INSERT : "Wstaw",
		INDEX_UMOD : "Gracze na urlopie",
		INDEX_NO_MOONS : "Liczba Księżycy",
		INDEX_NO_EMPTY_SYSTEMS : "Liczba pustych systemów",
		INDEX_NO_FULL_SYSTEMS : "Liczba pełnych systemów",
		INDEX_NO_TARGETS : "Liczba potencjalnych celów",
		INDEX_USERINFO : "użytkownicy w liczbach",
		INDEX_ONLINE : "Aktualnie online",
		INDEX_TODAY : "Dziś online",
		INDEX_ALL : "Całkowita ilość logowań",
		GENERAL_LOAD_FORM : "Ładowanie danych formularza",
		GENERAL_SAVE_FORM : "Zapisywanie danych formularza",
		GENERAL_SAVE_AS_TEXT : "Zapisz jako...",
		GENERAL_SAVE : "Zapisz",
		INDEX_USERMANAGEMENT : "Aktywacje - Informacje",
		INDEX_NEEDADMIN : "Konta do odblokowania",
		INDEX_NEEDEMAIL : "Niezweryfikowane Konta",
		INDEX_TOOLBAR_INFO : "Informacje wtyczki Galaxytool",
		INDEX_TOOLBAR_URL : "Adres Galaxytool",
		INDEX_TOOLBAR_VERSION_REQUIRED : "Wymaga co najmniej wersji wtyczki Galaxytool",
		INDEX_TOOLBAR_INSTALL_GUIDE : "Instrukcje instalacji wtyczki",
		INDEX_TOOLBAR_TOKEN : "Klucz logowania",
		INDEX_TOOLBAR_NEW_TOKEN : "Pobierz nowy klucz",
		INDEX_PLAYERS_WITH_N_PLANETS : "Gracze z planetami powyżej &1",
		INDEX_GETTING_STARTED : "Wprowadzenie do Galaxytool",
		INDEX_GETTING_STARTED1 : "Witamy w Galaxytool!",
		INDEX_GETTING_STARTED2 : "Galaxytool pomoże Ci przeanalizować to, co dzieje się na twoim &1 uniwersum OGame",
		INDEX_GETTING_STARTED3 : "Przed rozpoczęciem analizy, należy umieścić dane w bazie. Do tego potrzebujesz wtyczkę do przeglądarki, jak &1 dla Firefox.",
		INDEX_GETTING_STARTED4 : "Po zainstalowaniu wtyczki, po stronach OGame można poruszać się jak zwykle, a po wysłaniu danych do Galaxytool pojawi się małe okno statusu.",
		INDEX_GETTING_STARTED5 : "Po umieszczeniu przez wtyczkę danych w Galaxytool można rozpocząć analizowanie graczy. Można się dowiedzieć gdzie gracz ma kolonie, ile koloni ma, jakie raporty istnieją albo kiedy gracz jest najbardziej aktywny.",
		INDEX_GETTING_STARTED6 : "Galaxytool również pomoże Ci przeanalizować jakie masz postępy w porównaniu z konkurencją albo po przez analizę raportów bojowych możesz zobaczyć ilu nalotów dokonałeś w ostatnich dniach lub ostatnim tygodniu.",
		INDEX_GETTING_WIKIPAGE : "W Galaxytool istnieje jeszcze wiele innych funkcji.",
		INDEX_GETTING_WIKIPAGE2 : "Sprawdź je na naszej stronie wiki.",
		INDEX_GETTING_BOARD : "W razie pomysłów możesz skorzystać z naszego forum:",
		INDEX_GETTING_CHAT1 : "Lub odwiedź nas na czacie:",
		INDEX_GETTING_CHAT2 : "Nie jesteś online 24/7 ale spędzamy tam dużo naszego wolnego czasu, więc uzbroj się w cierpliwość.",
		INDEX_CLOSE : "Close",
		INDEX_LOGIN : "Login",
		GENERAL_REQUIRED_FIELDS : "Please fill all required fields",
		INDEX_MESSAGES : "Messages",
		INDEX_EXAMPLE : "Example",
		INDEX_INVALID_DATA : "Invalid data",
		GENERAL_COLUMN_HIDE_TITLE : "Manage columns",
		GENERAL_COLUMN_HIDE_INFO : "Please select which columns you want to see in the table.",
		GENERAL_ENTRIES_DELETED : "&1 entries deleted",
		GENERAL_APPLY : "Apply",
		STARTPAGE_GALAXYTOOL_DESCR : "<em>Galaxytool</em> is a tool for the browser game OGame.",
		GENERAL_OVERWRITE : "Overwrite duplicate entry",
		GENERAL_OVERWRITE_QUESTION : "Overwrite?",
		INDEX_OWN_LOGINS : "Your logins",
		GENERAL_OPEN_IN_NEW_WINDOW : "Otwórz odnośnik w nowym oknie",
		GENERAL_UNIT_OF_MEASURE_DAYS : "Days",
		PROGRAM_NAME : "OGame Galaxytool",
		SHORTNAME : "Galaxytool",
		BACK_INDEX : "Powrót do strony głównej",
		UNIVERSE : "Uniwersum",
		MENU_INFO_LINKS : "Informacja",
		MENU_PAGE : "Podgląd",
		MENU_DB_SEARCH : "Szukaj w bazie danych",
		MENU_DB_NOTICES : "Szukaj w notatkach",
		MENU_DB_REPORTS : "Szukaj w raportach",
		MENU_GALAXYVIEW : "Przeglądaj galaktykę",
		MENU_STATISTICS : "Statystyki",
		MENU_ALLYHISTORY : "Historia sojuszu",
		MENU_FLEET_MOVEMENTS : "Ruchy flot",
		MENU_COMBAT_REPORTS : "Raporty wojenne",
		MENU_MESSAGES : "Wiadomości w grze",
		MENU_OPTION_LINKS : "Opcje",
		MENU_DB_REFRESH : "Wstaw do bazy danych",
		MENU_NOTICES : "Notatki",
		MENU_DB_STATUS : "Status bazy danych",
		MENU_USEROPTIONS : "Zarządzanie użytkownikami",
		MENU_USEROPTIONS2 : "Ustawienia użytkowników",
		MENU_USEROPTIONS3 : "Informacje o użytkownikach",
		MENU_ADMIN : "Zarządzanie",
		MENU_LOGOUT : "Wyloguj",
		MENU_STUFF : "Inne",
		MENU_FORUM_THREAD : "Forum developerów",
		MENU_DOWNLOADPAGE : "Do pobrania",
		MENU_LANGUAGE : "Język",
		MENU_HELP : "Pomoc",
		MENU_TOOLOPTIONS : "Ustawienia Galaxytool",
		PARSER_INFO1 : " dodano do bazy danych",
		PARSER_ERROR1 : "Wystąpił błąd podczas próby dodania:",
		PARSER_ERROR2 : "Nie znaleziono bazy danych!",
		PARSER_ERROR3 : "Nie znaleziono serwera z bazą danych!",
		PARSER_WRONG_UNIVERSE : "Złe uniwersum- aktualne: \"&1\" oczekiwane: \"&2\"",
		SHOW_TITLE : "OGame Galaxytool - Przeszukiwanie",
		SHOW_SEARCH : "Szukaj w bazie danych",
		SHOW_ALLYSYMBOL : "Tag sojuszu",
		SHOW_PLAYERNAME : "Nazwa gracza",
		SHOW_MOONS : "Tylko planety z księżycem",
		SHOW_NOTICES : "Tylko planety z notatkami",
		SHOW_COLONIES : "Tylko planety do kolonizacji",
		SHOW_YES : "Tak",
		SHOW_NO : "Nie",
		SHOW_SEARCHRANGE : "Zakres",
		SHOW_SEARCH_IN : "Przeszukaj galaktykę",
		SHOW_FROM_SYSTEM : "od układu",
		SHOW_FROM_PLANET : "od planety na pozycji",
		SHOW_TO : "do",
		SHOW_DESCRIPTION : "Możesz użyć gwiazdki * w polu z nazwą gracza lub tagiem sojuszu. W ten sposób znajdziesz wszystkie sojusze lub graczy z wybranymi &quot;znakami&quot; w nazwie.<br />Wypełnij wszystkie wymagane pola tylko jeśli chcesz zawężyć wyszukiwanie.",
		SHOW_SORT_BY : "Sortuj według",
		SHOW_GALASYSTEM : "Galaktyka/Układ",
		SHOW_ALLYNAME : "Nazwa sojuszu",
		SHOW_SEARCHBUTTON : "Szukaj",
		SHOW_ADDRESS : "Koordynaty",
		SHOW_ALLYSORT : "Sojusz",
		SHOW_PLANET : "Planeta",
		SHOW_STATUS : "Status",
		SHOW_CURRENTNESS : "ostatnio aktualizowany",
		SHOW_PLAYER_STATUS : "Status gracza",
		SHOW_PLAYER_STATUS1 : "wszyscy",
		SHOW_PLAYER_STATUS2 : "potencjalne cele",
		SHOW_PLAYER_STATUS3 : "nieaktywni",
		SHOW_HITS : "Wyświetleń",
		SHOW_OF : "z",
		SHOW_ASC : "rosnąco",
		SHOW_DESC : "malejąco",
		SHOW_RESULTS : "Wyświetleń na stronę",
		SHOW_MOON : "Księżyc",
		SHOW_UKMOONSIZE : "brak danych",
		SHOW_DF : "PZ",
		SHOW_DF_LONG : "Pola zniszczeń",
		SHOW_METAL : "M",
		SHOW_METAL_LONG : "Metal",
		SHOW_CRYSTAL : "K",
		SHOW_CRYSTAL_LONG : "Kryształ",
		SHOW_BOTH : "W sumie",
		SHOW_AT_LEAST : "(conajmniej)",
		SHOW_DATE : "Data",
		SHOW_DATE_0 : "nieistotne",
		SHOW_DATE_1 : "starsze niż",
		SHOW_DATE_2 : "nowsze niż",
		SHOW_RANK : "Miejsce",
		SHOW_FRANK : "Miejsce Floty",
		SHOW_MEMBERS : "Członków",
		SHOW_NOTRANKED : "Nie ma w top 1500.",
		SHOW_NOTICERES : "Notatki",
		SHOW_REPORTS : "Wyłącznie planety z raportami",
		SHOW_REPORTS_SHORT : "Raporty",
		SHOW_NOTHING : "Nie znaleziono wpisu",
		SHOW_ALLIANCE_STATUS : "Status sojuszu",
		SHOW_NO_STATUS : "brak",
		SHOW_NAP : "NAP",
		SHOW_ALLIED : "Sojusznik",
		SHOW_WAR : "Wojna",
		SHOW_BOYCOTT : "Bojkot",
		SHOW_NEUTRAL : "Neutralny",
		SHOW_OWN : "Własny sojusz",
		SHOW_WING : "Skrzydłowy",
		SHOW_EXT_OPTIONS1 : "Pokaż więcej opcji wyszukiwania dla zakresu, miejsca, daty lub pola zniszczeń.",
		SHOW_EXT_OPTIONS2 : "Pokaż więcej opcji wyszukiwania dla kolonii, księżycy, raportów, notatek, statusu graczy lub statusu dyplomatycznego.",
		SHOW_EXT_OPTIONS3 : "Pokaż więcej opcji wyszukiwania dla sortowania wyników.",
		SHOW_EXTENDED : "advanced search",
		SHOW_MOON_SELECTION : "Planet with moon",
		SHOW_REPORT_SELECTION : "Planet with report",
		SHOW_FILTER_BY : "Exclude from the list",
		SHOW_FILTER_NONE : "Żadne",
		SHOW_PLAYERS_WITHOUT_PROGRESS : "Show players without score changes within the last few days",
		STATUS_TITLE : "OGame Galaxytool - Statusy",
		STATUS_DB_STATUS : "Status bazy danych",
		STATUS_COLOR : "Kolor",
		STATUS_AGE1 : "Wpis z ostatnich 24 godzin.",
		STATUS_AGE2 : "Wpis 2-4 dniowy.",
		STATUS_AGE3 : "Wpis 5-7 dniowy.",
		STATUS_AGE4 : "Wpis 1-2 tygodniowy.",
		STATUS_AGE5 : "Wpis 3-4 tygodniowy.",
		STATUS_AGE6 : "Wpis starszy niż 1 miesiąc!",
		STATUS_AGE7 : "Brak wpisów.",
		STATUS_ON : "w",
		STYLES_COLOR1 : "Kolor1",
		STYLES_COLOR2 : "Kolor2",
		STYLES_COLOR3 : "Kolor3",
		STYLES_COLOR4 : "Kolor4",
		STYLES_COLOR5 : "Kolor5",
		STYLES_COLOR6 : "Kolor6",
		STYLES_COLOR7 : "Kolor7",
		STATUS_DB_LEGEND : "Legenda",
		STATUS_GALAXY : "Podgląd galaktyki",
		USER_TITLE : "OGame Galaxytool - Zarządzanie użytkownikami",
		USER_NAMES : "Użytkownik",
		USER_ERROR : "Błąd",
		USER_NEWUSER : "Nowy użytkownik",
		USER_OPTIONS : "Opcje",
		USER_USERNAME : "Nazwa użytkownika",
		USER_PASSWORD : "Hasło",
		USER_PASSWORD_CONFIRM : "Potwierdź hasło",
		USER_GALAXY : "Galaktyka",
		USER_SEARCH : "Wyszukiwanie",
		USER_INSERT : "Dodawanie wpisów",
		USER_DELETE : "usuń",
		USER_DELETE_ENTRY : "Czy chcesz usunąć użytkownika: ",
		USER_STATUS : "Przeglądanie statystyk",
		USER_STYLES : "Zmień wygląd",
		USER_SUBMIT : "Zatwierdź",
		USER_RESET : "Reset",
		USER_YES : "Tak",
		USER_NO : "Nie",
		USER_STYLEPATH : "Ścieżka do styles.css",
		USER_PROBES : "Raporty szpiegowskie",
		USER_EMAIL : "Email",
		USER_ERROR1 : "Niepoprawne hasło lub email.",
		USER_ERROR2 : "Niepoprawny email.",
		USER_INGAME : "Nazwa w grze",
		USER_ALLYTAG : "Tag sojuszu",
		USER_ALLYHISTORY : "Pokaż/aktualizuj historię sojuszu",
		USER_DIPLOMATIC : "Zmień status dyplomatyczny",
		USER_STATSPAGE : "Ilość wpisów na stronie statystyk",
		USER_LINKS : "Linki",
		USER_LINKS2 : "Format:<br>text;url<br>text2;url2<br>text3;url3",
		USER_EXPORT_TITLE : "Eksportuj kolory (BB Code)",
		USER_BB_COORDINATES : "Koordynaty",
		USER_BB_MOON : "Księżyc",
		USER_BB_DEBRIS : "Pole Zniszczeń",
		USER_BB_ALLY : "Nazwa sojuszu ",
		USER_BB_ALLYDETAILS : "Szczegóły sojuszu",
		USER_BB_PLAYERNAME : "Nazwa gracza",
		USER_BB_BANNED : "Zbanowany",
		USER_BB_VACATION : "Urlop",
		USER_BB_NOOB : "Noob",
		USER_BB_INACTIVE : "nieaktywny",
		USER_BB_LONGINACTIVE : "długo nieaktywny",
		USER_DELETION : "Skasuj",
		USER_FLEETINFO : "Ruchy flot",
		USER_ACTIVITIES : "Aktywność gracza",
		USER_MAINTENANCE : "Galaxytool konserwacja",
		USER_MANAGEMENT : "Zarządzanie użytkownikami",
		USER_DELETE_MY_COMBAT_REPORTS : "Skasuj moje raporty wojenne",
		USER_DELETE_MY_MESSAGES : "Skasuj moje wiadomości",
		USER_DELETE_MY_FLEETMOVES : "Skasuj ruchy mojej floty",
		USER_DELETE_MY_COMBAT_REPORTS_LIMITED : "Skasuj moje raporty wojenne starsze niż &1 dni",
		USER_DELETE_MY_MESSAGES_LIMITED : "Skasuj moje wiadomości starsze niż &1 dni",
		USER_TABLE_ENTRIES : "Liczba wyników wyszukiwania dla każdej strony",
		USER_EXISTS : "User already exists",
		USER_BB_OUTLAW : "Outlaw",
		USER_INVALID_URL : "URL &1 seems to be invalid - URL will be ignored",
		VIEW_TITLE : "OGame Galaxytool - Szczegóły",
		VIEW_NODATA : "Brak danych.",
		VIEW_GALAXY : "Galaktyka",
		VIEW_SYSTEM : "Układ słoneczny",
		VIEW_POSITION : "Pozycja",
		VIEW_PLANET : "Planeta",
		VIEW_MOON : "Księżyc",
		VIEW_TF : "PZ",
		VIEW_PLAYER : "Gracz",
		VIEW_PLAYER_ADD : "(Miejsce / Status)",
		VIEW_ALLY : "Sojusz",
		VIEW_ALLY_ADD : "(Miejsce / Członków)",
		VIEW_METAL : "M",
		VIEW_CRYSTAL : "K",
		VIEW_COLONISED : "zasiedlonych planet",
		VIEW_UKMOONSIZE : "brak danych",
		VIEW_BACK : "wstecz",
		VIEW_NOTICE : "Notatki",
		VIEW_REPORTS : "Raporty",
		VIEW_MOONPHALANX : "Nastepujacy księżyc moze zeskanowac ten system",
		VIEW_NOMOONS : "Nie znaleziono księżycy",
		VIEW_IRAKS : "Ta planeta jest w zasięgu rakiet międzyplanetarnych",
		VIEW_NOIRAKS : "Nie znaleziono rakiet międzyplanetarnych",
		VIEW_MOON_DESTROY_CHANCE : "Szansa na zniszczenie księżyca ",
		VIEW_CHANCE_WITH_ONE : "Szansa zniszczenia jedną Gwiazdą Śmierci ",
		VIEW_CHANCE_WITH_N : "Szansa zniszczenia ",
		VIEW_DEATH_STARS : "Gwiazdami Śmierci",
		VIEW_DS_DESTROY_CHANCE : "Szansa na zniszczenie Gwiazd(y) Śmierci",
		VIEW_TOP : "Top",
		VIEW_GO : "go",
		VIEW_DIAMETER : "Diameter",
		PW_TITLE : "OGame Galaxytool - Zmiana hasła",
		OLD_PASSWORD : "Obecne hasło",
		NEW_PASSWORD : "Nowe hasło",
		CONFIRM_NEW_PASSWORD : "Powtórz nowe hasło",
		PW_MISMATCH : "Wpisane hasła różnią się!",
		PW_ERROR : "Obecne hasło nie zgadza się z zapisanym w bazie danych!",
		UPDATE_DONE : "Zaktualizowano.",
		TIMEZONE_OFFSET : "Przesunięcie czasu względem serwera",
		DELETE_ACCOUNT : "Skasuj to konto na Galaxytool",
		DELETE_ACCOUNT_SAFETY_REQUEST : "Czy na pewno chcesz skasować konto na Galaxytool?",
		CH_PASSWD_AUTHORIZATION : "Uprawnienia",
		CH_PASSWD_ADMIN : "Admin",
		TIMEZONE_OGAME_OFFSET : "Strefa czasowa na serwerze OGame",
		CH_PASSWD_USER_LANGUAGE : "Zmień na ten język po zalogowaniu",
		CH_PASSWD_USER_LANGUAGE_NO_CHANGE : "Bez zmian",
		CH_PASSWD_EXPAND : "Rozwiniętą",
		CH_PASSWD_COLLAPSE : "Zwiniętą",
		CH_PASSWD_HIDDEN : "Ukrytą",
		CH_PASSWD_GETTING_STARTED : "Pokaż informację powitalną po zalogowaniu",
		CH_PASSWD_PLUGIN : "Pokaż informację o wtyczce po zalogowaniu",
		NOTICE_TITLE : "OGame Galaxytool - Notatki",
		NOTICE_HEADER : "Edytuj notatkę",
		NOTICE_HEADER2 : "Edytuj własne notatki",
		NOTICE_PUBLIC : "Dostępne dla wszystkich?",
		NOTICE_YES : "tak",
		NOTICE_NO : "nie",
		NOTICE_TEXT : "Treść notatki",
		NOTICE_SAVE : "Zapisz",
		NOTICE_DELETED : "Wpis usunięty",
		NOTICE_SAVED : "Wpis zachowany.",
		NOTICE_RESULTS : "Wszystkie wyniki",
		NOTICE_USER : "Użytkownik",
		NOTICE_DATE : "Data",
		NOTICE_EDIT : "Edytuj",
		NOTICE_DELETE : "Usuń",
		NOTICE_NEW : "Utwórz własny wpis",
		NOTICE_NOTPUBLIC : "Notaka prywatna.",
		NOTICE_ALL : "Wszystkie",
		NOTICE_NONE : "Żadne",
		NOTICE_SEARCH : "Szukaj w notatkach",
		NOTICE_SEARCH_SHORT : "Szukaj",
		NOTICE_HITS : "Wyświetleń",
		NOTICE_SHOWRESULTS : "Wyświetleń na stronę",
		NOTICE_OF : "z",
		NOTICE_NOTHING : "Brak wpisów",
		NOTICE_CHARS : "znaki",
		NOTICE_PLAYERNAME : "Gracz",
		NOTICE_SHOWALL : "Pokaż wszystkie notatki",
		REPORTS_TITLE : "OGame Galaxytool - Raporty szpiegowskie",
		REPORTS_RESOURCES : "Surowce",
		REPORTS_FLEET : "Floty",
		REPORTS_DEFENCE : "Obrona",
		REPORTS_BUILDINGS : "Budynki",
		REPORTS_TECHNOLOGY : "Badania",
		REPORTS_MOON : "Księżyc",
		REPORTS_SEARCH : "Szukaj w raportach szpiegowskich",
		REPORTS_SEARCH_SHORT : "Szukaj",
		REPORTS_HITS : "Wyświetleń",
		REPORTS_NOTHING : "Nie znaleziono",
		REPORTS_ADDRESS : "Koordynaty",
		REPORTS_CURRENTNESS : "Aktualność",
		REPORTS_PLAYERNAME : "Nazwa gracza",
		REPORTS_ALLY : "Sojusz",
		REPORTS_VIEW : "Obejrzyj raport",
		REPORTS_SEARCH_IN : "Przeszukaj galaktykę",
		REPORTS_FROM_SYSTEM : "od układu",
		REPORTS_TO : "do",
		REPORTS_DELETE : "usuń",
		REPORTS_DELETED : "Wpis usunięty",
		REPORTS_RESULTS : "Wyświetleń na stronę",
		REPORTS_OF : "z",
		REPORTS_DATE : "Data",
		REPORTS_DATE_0 : "nieistotne",
		REPORTS_DATE_1 : "starsze niż",
		REPORTS_DATE_2 : "nowsze niż",
		REPORTS_NOTICES : "Notatki",
		REPORTS_AT_LEAST_RESOURCES : "Surowce (co najmniej)",
		REPORTS_SEARCH_EXTENDED : "szukanie rozszerzone",
		REPORTS_FLEET_RESIS : "Flota - wynik",
		REPORTS_DEFENCE_RESIS : "Obrona - wynik",
		REPORTS_ALL_RESIS : "Ogólny wynik",
		REPORTS_TECHS : "Technologie",
		REPORTS_UNKNOWN_ENTRIES : "nieznane wpisy",
		REPORTS_PARTLY_INSERTED : "częściowo dodane",
		REPORTS_FOR_ALL_RES : "dla wszystkich surowców",
		REPORTS_FOR_TF : "dla pola zniszczeń",
		REPORTS_KT : "Mały Transporter",
		REPORTS_GT : "Duży Transporter",
		REPORTS_SS : "Okręt Wojenny",
		REPORTS_REC : "Recykler",
		REPORTS_RAIDABLE : "Tylko nadające się do ataku",
		REPORTS_ALL_RESOURCES : "wszystkie surowce",
		REPORTS_STUFF : "Inne",
		REPORTS_SPEEDSIM : "symulacja w Speedsim",
		REPORTS_DRAGOSIM : "symulacja w Dragosim",
		REPORTS_STATUS : "Status",
		REPORTS_ERROR : "Wystąpił błąd",
		REPORTS_OWN_REPORTS : "Tylko własne raporty",
		REPORTS_UPLOAD_BY : "Raport wysłany przez",
		REPORTS_DEPTH : "Szczegółowe sprawozdanie",
		REPORTS_FLEET_SCORE : "Punkty floty",
		REPORTS_DEFENCE_SCORE : "Punkty obrony",
		REPORTS_HOURS : "hours",
		REPORTS_MAX_RESULTS_HIT : "Your query returned more than &1 hits. Only the first &1 results are show. Please adjust your search request to get less results.",
		REPORTS_OSIMULATE : "Simulate with OSimulate",
		REPORTS_SHOW_ONLY : "Show only",
		REPORTS_SHOW_PLANETS : "Planety",
		REPORTS_SHOW_MOONS : "Księżyce",
		REPORTS_OWNER : "Reports owned by",
		STATS_TITLE : "OGame Galaxytool - Statystyki",
		STATS_TBLHEAD : "Statystyki",
		STATS_RANK : "Miejsce",
		STATS_PLAYERNAME : "Nazwa gracza",
		STATS_ALLYNAME : "Tag sojuszu",
		STATS_SCORE : "Punkty",
		STATS_FLEET : "Flota",
		STATS_RESEARCH : "Badania",
		STATS_MEMBERS : "Członków",
		STATS_STATUS : "Status",
		STATS_NOTHING : "Brak",
		STATS_NAP : "Pakt",
		STATS_ALLIED : "Sojusznik",
		STATS_WAR : "Wojna",
		STATS_BOYCOTT : "Bojkot",
		STATS_NEUTRAL : "Neutralni",
		STATS_OWN : "Własny sojusz",
		STATS_WING : "Akademia",
		STATS_UPDATE : "Wpisy z",
		STATS_PLAYERSTATS : "Statystyki graczy",
		STATS_ALLYSTATS : "Statystyki sojuszy",
		STATS_DELETE : "Czy chcesz usunąć ten wpis ?",
		STATS_CONFIRM_DELETE : "Na pewno chcesz usunąć ten wpis gracza?",
		STATS_CHANGE_PLAYER_STATUS : "Status gracza",
		STATS_CHANGE_ALLIANCE_STATUS : "Status sojuszu",
		STATS_CHANGE_ALLIANCE_STATUS_HINT : "Wszyscy członkowie tego sojuszu uzyskają wybrany status. Status poprzedni będzie zastąpiony. Możesz później ręcznie zmienić statusy poszczególnym graczom",
		STATS_UNKNOWN : "Reszta",
		STATS_DETAILS : "Szczegóły dla",
		STATS_PLAYERSTATUS : "Status gracza",
		STATS_IGNORE_STATUS : "wszyscy",
		STATS_ACTIVE : "aktywny",
		STATS_INACTIVE : "nieaktywny",
		STATS_BANNED : "Zbanowany",
		STATS_VACATION : "Urlop",
		STATS_NOOB : "Noob",
		STATS_YES : "Tak",
		STATS_NO : "Tylko planety z notatkami",
		STATS_SEARCH : "Wyszukiwanie",
		STATS_SHOW_GRAPH : "Szczegóły na temat punktów dystrybucji",
		STATS_LONG_INACTIVE : "długo nieaktywny",
		STATS_STANDARD : "Punkty standardowe",
		STATS_MILITARY : "Punkty militarne",
		STATS_ECONOMY : "Ekonomia",
		STATS_HONOUR : "Punkty honoru",
		STATS_MILITARY_BUILD : "Zbudowane militarne",
		STATS_MILITARY_DESTROYED : "Zniszczone militarne",
		STATS_MILITARY_LOST : "Stracone militarne",
		REGISTER_REGISTRATE : "Rejestracja",
		REGISTER_LOGINNAME : "Nazwa użytkownika",
		REGISTER_PASSWORD : "Hasło",
		REGISTER_PASSWORD_CONFIRM : "Potwierdź hasło",
		REGISTER_EMAIL : "Email",
		REGISTER_INGAME : "Nazwa w grze",
		REGISTER_ALLYTAG : "Tag sojuszu",
		REGISTER_EMAILVERIFICATION : "Weryfikacja adresu email",
		REGISTER_EMAILTEXT : "Odwiedź następujący link aby potwierdzić swoją rejestrację na Galaxytool.",
		REGISTER_ERROR1 : "Wybrana nazwa użytkownika już istnieje.",
		REGISTER_ERROR2 : "Nie powiodło się wysłanie emaila. Skontaktuj się z administratorem.",
		REGISTER_ERROR3 : "Nie powiodło się przesyłanie informacji do bazy danych!",
		REGISTER_INFO1 : "Twoje konto zostało utworzone.",
		REGISTER_INFO2 : "Odwiedź link podany w emailu aby potwierdzić swoją rejestrację.",
		REGISTER_INFO3 : "Rejestracja potwierdzona. Zaczekaj teraz na aktywację konta przez administratora.",
		REGISTER_BUTTON : "Wróć do strony głównej",
		REGISTER_NEW_SUBJECT : "Galaxytool - dołączył nowy użytkownik",
		REGISTER_NEW_MAILTEXT : "Zarejestrował się nowy użytkownik.",
		REGISTER_BACK : "Wróć do pierwszej strony",
		REGISTER_MISSING_FIELDS : "Wprowadź wszystkie wymagane pola",
		REGISTER_ERROR4 : "Adres e-mail nie jest prawidłowy.",
		REGISTER_ERROR5 : "Hasła nie pasują.",
		REGISTER_PWS : "Siła hasła",
		REGISTER_PWS0 : "bardzo słabe",
		REGISTER_PWS1 : "słabe",
		REGISTER_PWS2 : "średnie",
		REGISTER_PWS3 : "mocne",
		REGISTER_PWS4 : "bardzo mocne",
		REGISTER_EMAIL_USED : "Email Address is already used",
		LOSTPW_TITLE : "Przypomnienie hasła",
		LOSTPW_INFO2 : "Wygenerowano nowe hasło i wysłano je na twój adres email.",
		LOSTPW_BUTTON1 : "Wygeneruj nowe hasło",
		LOSTPW_BUTTON2 : "Wróć do strony głównej",
		LOSTPW_LOGINNAME : "Nazwa użytkownika",
		LOSTPW_EMAIL : "Email",
		LOSTPW_ERROR1 : "Nie powiodło się przesyłanie informacji do bazy danych!",
		LOSTPW_ERROR2 : "Nie znaleziono wpisu!",
		LOSTPW_ERROR3 : "Nie powiodło się wysłanie emaila. Skontaktuj się z administratorem.",
		LOSTPW_EMAIL_SUBJECT : "Twoje nowe hasło o które prosiłeś",
		LOSTPW_EMAIL_TEXT1 : "Twoja nazwa użytkownika do Galaxytool",
		LOSTPW_EMAIL_TEXT2 : "Nazwa użytkownika",
		LOSTPW_EMAIL_TEXT3 : "Hasło",
		LOSTPW_INFO1 : "You will receive an email to verify your password reset request.",
		LOSTPW_CONFIRM_RESET_SUBJECT : "Lost password?",
		LOSTPW_CONFIRM_RESET_MESSAGE : "Hello,\n\nyou requested a password reset for the Galaxytool. To generate a new password, click the following link:",
		USERINFO_TITLE : "OGame Galaxytool - Informacja o użytkowniku",
		USERINFO_NAMES : "Wszyscy użytkownicy",
		USERINFO_DETAIL : "Szczegółowe informacje o",
		USERINFO_ERROR1 : "Nie istnieje użytkownik z takim ID!",
		USERINFO_USERNAME : "Nazwa użytkownika",
		USERINFO_INGAME : "Nazwa w grze",
		USERINFO_EMAIL : "Email",
		USERINFO_ALLYTAG : "Sojusz",
		USERINFO_STYLEPATH : "Wygląd",
		USERINFO_STATUS : "Status",
		USERINFO_ACTIVATE : "Aktywuj użytkownika",
		USERINFO_LOGINS : "Ilość logowań",
		USERINFO_LASTLOGIN : "Ostatnie logowanie",
		USERINFO_DATA : "Informacja o dodanych układach",
		USERINFO_NODATA : "Użytkownik nie dodał żadnych układów!",
		USERINFO_GALAXY : "Galaktyka",
		USERINFO_SYSTEMS : "Ilość układów",
		USERINFO_IP : "Adres IP",
		USERINFO_LOGINTIME : "Nazwa użytkownika",
		USERINFO_NOLOGIN : "Użytkownik nie logował się.",
		USERINFO_LAST_GALAXYUPDATE : "Ostatni dodany podgląd galaktyki",
		USERINFO_LAST_PUBLIC_NOTICE : "Ostatnia publiczna notatka",
		USERINFO_LAST_PRIVATE_NOTICE : "Ostatnia prywatna notatka",
		USERINFO_NUMBEROF_PUBLIC_NOTICE : "Ilośc publicznych notatek",
		USERINFO_NUMBEROF_PRIVATE_NOTICE : "Ilość prywatnych notatek",
		USERINFO_ACTIVATED : "Konto Aktywne",
		USERINFO_ACTIVATIONTEXT : "Admin Galaxytool aktywowal Twoje konto.\n\nMiłej zabawy z Galaxytool",
		USERINFO_LAST_SUBMIT : "Ostatnio wstawione dane",
		ALLYHISTORY_TITLE : "OGame Galaxytool - Historia sojuszu",
		ALLYHISTORY_TBLHEAD : "Przegląd historyczny",
		ALLYHISTORY_PLAYERNAME : "Nazwa gracza",
		ALLYHISTORY_ALLYNAME : "Sojusz",
		ALLYHISTORY_LASTMONTH : "ostatni miesiąc",
		ALLYHISTORY_ALL_DATA : "wszystkie dostępne iformacje",
		ALLYHISTORY_SHOW : "pokaż statystykę",
		ALLYHISTORY_TIMESPAN : "Przedział czasowy",
		ALLYHISTORY_PROGESS : "Postęp",
		ALLYHISTORY_SCORE : "Punkty",
		ALLYHISTORY_FSCORE : "Floty",
		ALLYHISTORY_RSCORE : "Badania",
		ALLYHISTORY_MEMBER : "Członków",
		ALLYHISTORY_NOTHING : "nie znaleziono wpisów",
		ALLYHISTORY_DETAILS : "Szczegóły",
		ALLYHISTORY_SHOW_ADDRESS : "Koordynaty",
		ALLYHISTORY_ESCORE : "Ekonomia",
		ALLYHISTORY_MSCORE : "Punkty militarne",
		DETAILEDINFO_PLAYERINFO_TITLE : "Informacje o graczu",
		DETAILEDINFO_ALLYINFO_TITLE : "Informacje o sojuszu",
		DETAILEDINFO_PLAYERINFO_TBLHEAD : "Szczegółowe informacje o graczu",
		DETAILEDINFO_ALLYINFO_TBLHEAD : "Szczegółowe informacje o sojuszu",
		DETAILEDINFO_NO_ALLIANCE : "brak",
		DETAILEDINFO_SCORE : "Statystyki punktowe",
		DETAILEDINFO_FLEET : "Statystyki flot",
		DETAILEDINFO_RESEARCH : "Statystyki badań",
		DETAILEDINFO_RANK : "Miejsce",
		DETAILEDINFO_POINTS : "Punkty",
		DETAILEDINFO_KNOWN_PLANETS : "Znane planety",
		DETAILEDINFO_MOONS : "Znane księżyce",
		DETAILEDINFO_PHALANX_AREA : "Zasięg falangi",
		DETAILEDINFO_NO_PHALANX_AREA : "nie znaleziono falangi",
		DETAILEDINFO_NOTICES : "Notatki",
		DETAILEDINFO_NO_NOTICES : "nie znaleziono notatek",
		DETAILEDINFO_PREVIOUS_ALLIANCES : "poprzednie sojusze",
		DETAILEDINFO_RESOURCES_PER_HOUR : "Surowce na godzinę",
		DETAILEDINFO_RESOURCES_PER_DAY : "Surowce na dobę",
		DETAILEDINFO_RESOURCES_PER_WEEK : "Surowce na tydzień",
		DETAILEDINFO_RESOURCES_PER_MONTH : "Surowce na miesiąc (30 dni)",
		DETAILEDINFO_METAL : "Metal",
		DETAILEDINFO_CRYSTAL : "Kryształ",
		DETAILEDINFO_DEUTERIUM : "Deuter",
		DETAILEDINFO_UNKNOWN : "nieznane",
		DETAILEDINFO_SCORE_DISTRIBUTION : "przyrost punktowy",
		DETAILEDINFO_GENERAL : "Szczegóły",
		DETAILEDINFO_MEMBERS : "Członkowie",
		DETAILEDINFO_GRAPHS : "Wykresy",
		DETAILEDINFO_RESOURCES : "Wydobycie",
		DETAILEDINFO_FLEET_TAB : "Flota",
		DETAILEDINFO_TECH : "Badania",
		DETAILEDINFO_FLEET_DETAIL : "Suma / (średnio na gracza) z wszystkich dostępnych raportów",
		DETAILEDINFO_TECH_DETAIL : "Średnia ze wszystkich dostępnych informacji o graczach",
		DETAILEDINFO_PLANET_TAB : "Planety",
		DETAILEDINFO_MOON_TAB : "Księżyce",
		DETAILEDINFO_ACTIVITIES : "Aktywność",
		DETAILEDINFO_NODATA : "Brak danych.",
		DETAILEDINFO_ACTIVITY_DESCRIPTION : "Pokaż aktywność &1 zaczynająć od:",
		DETAILEDINFO_GALAXYVIEWS : "Podgląd galaktyki",
		DETAILEDINFO_SCANS : "Działania szpiegowskie",
		DETAILEDINFO_MESSAGES : "Wiadomości gracza",
		DETAILEDINFO_COMBATS : "Raporty wojenne",
		DETAILEDINFO_ALLYPAGE : "Podgląd sojuszu",
		DETAILEDINFO_MANUAL : "Ręczne wstawienie",
		DETAILEDINFO_START : "Od",
		DETAILEDINFO_TO : "do",
		DETAILEDINFO_TODAY : "Dzisiaj",
		DETAILEDINFO_DATA_RESTRICTION : "ogranicz do:",
		DETAILEDINFO_WEEKDAY_WEEKEND : "Weekend",
		DETAILEDINFO_WEEKDAY_WORKINGDAY : "Dni robocze",
		DETAILEDINFO_WEEKDAY_MONDAY : "Poniedziałek",
		DETAILEDINFO_WEEKDAY_TUESDAY : "Wtorek",
		DETAILEDINFO_WEEKDAY_WEDNESDAY : "Środa",
		DETAILEDINFO_WEEKDAY_THURSDAY : "Czwartek",
		DETAILEDINFO_WEEKDAY_FRIDAY : "Piątek",
		DETAILEDINFO_WEEKDAY_SATURDAY : "Sobota",
		DETAILEDINFO_WEEKDAY_SUNDAY : "Niedziela",
		DETAILEDINFO_WEEKDAY_SHORTLENGTH : 3,
		DETAILEDINFO_PLAYER_CURRENTLY_ACTIVE : "Gracz jest obecnie aktywny",
		DETAILEDINFO_PLAYER_MESSAGES : "dostępne wiadomości gracza",
		DETAILEDINFO_SHOW : "pokaż",
		DETAILEDINFO_NONE : "niedostępne",
		DETAILEDINFO_ENTER_MANUALLY : "Wprowadź aktywność dla tego gracza",
		DETAILEDINFO_PLAYER_SEEN_ON : "Gracz jest dostępny od",
		DETAILEDINFO_INSERT : "Wstaw",
		DETAILEDINFO_OGAME_SERVERTIMES : "Uwaga: Wszystkie daty i godziny odnoszą się do czasu serwera OGame !",
		DETAILEDINFO_DAY_VIEW : "24 godzinny podgląd",
		DETAILEDINFO_WEEK_VIEW : "tygodniowy podgląd",
		DETAILEDINFO_HOME_PLANET : "Planeta główna",
		DETAILEDINFO_PLANETNAME : "Name",
		DETAILEDINFO_DEFENCE_SCORE : "Defence score",
		DETAILEDINFO_DEFENCE_SCORE_TOOLTIP : "Defence score = Fleet - Score + Research + Economy.<br/>All those statistics must be up to date to have a meaningful result!",
		DETAILEDINFO_SCORE_PER_SHIP : "Scores per ship",
		DETAILEDINFO_SHIPS : "Number of ships",
		DETAILEDINFO_DATE_IN_FUTURE : "Do not maintain times which are not in the past.",
		ADMIN_TITLE : "Zarządzanie Galaxytool",
		ADMIN_DISCLAMER : "Uwaga: Uruchamiasz skrypty na własne ryzyko ! Większość z nich usuwa dane.",
		ADMIN_INCONSISTENCIES : "Niespójność w bazie danych",
		ADMIN_PLANETS : "Planety na pozycji 0 lub większej niż 15",
		ADMIN_GALAXIES : "Usuń galaktyki większe niż &1 ",
		ADMIN_PLAYERS : "Usuń graczy bez OGame playerid - prowadzi do zdublowania graczy ",
		ADMIN_REPORTS : "Skasuj raporty powiązane z nieistniejącą planetą",
		ADMIN_MISC : "Różne",
		ADMIN_RESET : "Skasuj wszystkie dane (tylko użytkownicy oraz ip table nie zostaną skasowane)",
		ADMIN_OLD_PLAYERS : "Usuń informacje o graczach starsze niż &1 dni",
		ADMIN_OLD_REPORTS : "Usuń raporty starsze niż &1 dni",
		ADMIN_LOADING : "Nie zamykaj tego okna dopóki strona nie zostanie załadowana",
		ADMIN_STATUS : "Status Twoich próśb",
		ADMIN_SELECTION : "Co najmniej jedna opcja musi być wybrana",
		ADMIN_SAFETY : "Czy jesteś pewien, że chcesz uruchomić ten skrypt(y) ?",
		ADMIN_DONE : "zrobione",
		ADMIN_NOTBD : "nie ma nic do zrobienia",
		ADMIN_OLD_GALAXIES : "Usuń widoki galaktyk, które są starsze niż &1 dni",
		ADMIN_UNUSED_PLAYERS : "Skasuj graczy, których nie ma w żadnym widoku galaktyki",
		ADMIN_OLD_ACTIVITIES : "Usuń działania gracza starsze niż &1 dni",
		ADMIN_OLD_COMBATS : "Usuń raporty wojenne starsze niż &1 dni",
		ADMIN_OLD_INGAME_MSG : "Usuń wiadomości w grze starsze niż &1 dni",
		ADMIN_OGAME_API : "Load public data from OGame into the Galaxytool",
		ADMIN_OGAME_ALL_DATA : "wszystkie dostępne iformacje",
		ADMIN_OGAME_GALAXY_DATA : "Przeglądaj galaktykę",
		ADMIN_OGAME_STATISTICS_DATA : "Statystyki",
		ERRORPAGE_PAGEFORWARD : "Kliknij tutaj jeśli Twoja przeglądarka nie obsługuje przekierowania strony",
		ERRORPAGE_PERMISSION_DENIED : "Nie masz uprawnień do wejścia na tą stronę. Kliknij na powrót.",
		FLEETS_TITLE : "OGame Galaxytool - Ruchy flot",
		FLEETS_ACTUAL_FLEETS : "Obecne ruchy floty",
		FLEETS_YES : "Tak",
		FLEETS_NO : "Tylko planety z notatkami",
		FLEETS_DETAILS : "Szczegóły",
		FLEETS_MISSION_EXPEDITION : "Ekspedycja",
		FLEETS_MISSION_COLONIZATION : "Kolonizuj",
		FLEETS_MISSION_RECYCLE : "Zbieraj",
		FLEETS_MISSION_TRANSPORT : "Transportuj",
		FLEETS_MISSION_DEPLOYMENT : "Stacjonuj",
		FLEETS_MISSION_ESPIONAGE : "Szpieguj",
		FLEETS_MISSION_ACS_DEFEND : "Obrona związku",
		FLEETS_MISSION_ATTACK : "Atak",
		FLEETS_MISSION_ACS_ATTACK : "Atak związku",
		FLEETS_MISSION_MOON_DESTRUCTION : "Zniszcz księżyc",
		FLEETS_MISSION_MISSILE_ATTACK : "Atak rakietowy",
		FLEETS_NO_DATA : "Nie znaleziono odpowiednich danych",
		FLEETS_FLEET : "Fleet",
		FLEETS_ALL_FLEETS : "Show all fleet movements",
		COMBAT_REPORT_OUDATED_GALAXYVIEW : "Twoje dane galaktyki są nieaktualne. Proszę odwiedź najpierw koordynaty miejsca bitwy!",
		MESSAGES_TITLE : "OGame Galaxytool - OGame Wiadomości",
		MESSAGES_PLAYERNAME : "Nazwa gracza",
		MESSAGES_SUBJECT : "Temat",
		MESSAGES_DATE : "Data",
		MESSAGES_FILTER : "Filter",
		MESSAGES_DELETE : "Usuń wiadomość",
		MESSAGES_PUBLISH_DETAIL : "Publikuj wiadomość poprzez dodanie jej do notatek na temat tego gracza.",
		MESSAGES_PUBLISH_HEADER : "&sender wysłał wiadomość do &recipient &date:\n\n &message",
		MESSAGES_PLAYER_FILTER : "Wiadomość od gracza:",
		MESSAGES_CONTENT : "Content",
		COMBATS_TITLE : "OGame Galaxytool - Raporty wojenne",
		COMBATS_ATTACKER : "Agresor",
		COMBATS_DEFENDER : "Obrońca",
		COMBATS_DATE : "Data",
		COMBATS_OWNER : "Właściciel",
		COMBATS_WINNER : "Zwycięzca",
		COMBATS_COMBATREPORT : "Raporty wojenne",
		COMBATS_COMBAT_AT : "Bitwa na",
		COMBATS_LOST_UNITS : "Stracone jednostki",
		COMBATS_LOOT : "Łup",
		COMBATS_DEBRIS : "Pole zniszczeń",
		COMBATS_AND : "i",
		COMBATS_PUBLISH : "Udostępnij raport",
		COMBATS_UNPUBLISH : "Ukryj raport (zrób z niego prywatny)",
		COMBATS_DELETE : "Usuń raport",
		COMBATS_CHECK_ALL : "Zaznacz wszystko",
		COMBATS_UNCHECK_ALL : "Odznacz wszystko",
		COMBATS_WITH_SELECTED : "Wykonaj dla zaznaczonych",
		COMBATS_PUBLIC_REPORTS : "Raporty publiczne",
		COMBATS_YES : "Tak",
		COMBATS_NO : "Tylko planety z notatkami",
		COMBATS_SEARCH_OPTIONS : "Opcje szukania",
		COMBATS_SEARCH : "Go",
		COMBATS_RESET : "Reset",
		COMBATS_COORDINATES : "Koordynaty",
		COMBATS_INVALID_GALAXY_ENTERED : "Wprowadzono niepoprawną galaktykę",
		COMBATS_INVALID_SYSTEM_ENTERED : "Wprowadzono niepoprawny system",
		COMBATS_INVALID_PLANET_ENTERED : "Wprowadzono niepoprawną planetę",
		COMBATS_GALAXY_FROM_TO : "Galaktyka",
		COMBATS_SYSTEM_FROM_TO : "Układ",
		COMBATS_PLANET_FROM_TO : "Planeta",
		COMBATS_APPLY : "Apply",
		COMBATS_COMBAT_SUMMARY : "Podsumowanie raportów wojennych",
		COMBATS_DOWNLOAD_CSV : "Pobierz jako plik CSV",
		REPORT_ARCHIVE_TITLE : "Archiwum raportów",
		REPORT_ARCHIVE_COORDINATES : "Współrzędne ",
		REPORT_ARCHIVE_SCANTIME : "Czas skanowania",
		REPORT_ARCHIVE_DELETE : "Usuń te wpisy",
		REPORT_ARCHIVE_CONFIRM_DELETE : "Czy na pewno chcesz usunąć te wpisy?",
		REPORT_ARCHIVE_GALAXY : "Galaktyka",
		REPORT_ARCHIVE_SYSTEM : "Układ",
		REPORT_ARCHIVE_PLANET : "Planeta",
		REPORT_ARCHIVE_MOON : "Księżyc",
		REPORT_ARCHIVE_DETAILS : "Szczegóły",
		REPORT_ARCHIVE_RESOURCES : "Surowce na godzinę",
		REPORT_ARCHIVE_HEADER_RESOURCES : "Surowce",
		REPORT_ARCHIVE_DETAILS_FOR : "Archiwum raportów dla &1 [&2] (&3)",
		REPORT_ARCHIVE_FLEET_CARGO : "Pojemność ładunkowa floty",
		REPORT_ARCHIVE_IRAK_RANGE : "Zasięg rakiet Międzyplanetarnych",
		REPORT_ARCHIVE_CHART_TYPE : "Typ wykresu",
		INSTALL_TITLE : "Galaxytool installation for version",
		INSTALL_PROGRESS : "Overall progress",
		INSTALL_STEP : "Step",
		INSTALL_CONTINUE : "Continue",
		INSTALL_VALIDATE : "Validate",
		INSTALL_STEP1 : "Welcome",
		INSTALL_STEP2 : "Writeable check",
		INSTALL_STEP3 : "Database settings",
		INSTALL_STEP4 : "OGame settings",
		INSTALL_STEP5 : "Galaxytool settings",
		INSTALL_STEP6 : "Admin password",
		INSTALL_STEP7 : "Install Galaxytool",
		INSTALL_STEP8 : "Finalize install",
		INSTALL_FILE_DELETE_CHECK : "Please delete install.php and update.php from your webserver.",
		INSTALL_STEP1_PHP_FAILED : "Your PHP version &1 is not working with this Galaxytool version",
		INSTALL_STEP1_FOPEN_FAILED : "Your PHP version does not allow to open webpages with FOPEN() command. This is required to consume the OGame API.",
		INSTALL_STEP1_WELCOME : "Welcome to the installation wizard of the Galaxytool. You will be guided through the installation of the Galaxytool.",
		INSTALL_STEP2_DESCRIPTION : "Make sure your config.php and attributes.php files have write permissions enabled.",
		INSTALL_STEP2_DESCRIPTION2 : "If you don't know, how to achieve this, please take a look here: &1",
		INSTALL_STEP2_FILE_NOT_WRITEABLE : "File is not writeable",
		INSTALL_STEP3_SERVER : "Database server",
		INSTALL_STEP3_USERNAME : "Nazwa użytkownika",
		INSTALL_STEP3_PASSWORD : "Hasło",
		INSTALL_STEP3_DBNAME : "Database name",
		INSTALL_STEP3_PREFIX : "Tablename prefix",
		INSTALL_STEP3_ENTER_PREFIX : "E.g. mytool_",
		INSTALL_STEP3_ENTER_SERVER : "Enter the server address. Contact your system admin if necessary. Usually the correct value is localhost.",
		INSTALL_STEP3_ENTER_USERNAME : "Enter the username for database access",
		INSTALL_STEP3_ENTER_PASSWORD : "Enter the password for database access",
		INSTALL_STEP3_ENTER_DBNAME : "Enter the database name which shall be used for installation (must exist)",
		INSTALL_STEP3_CONNECT_FAILED : "Could not establish connection to database server",
		INSTALL_STEP3_DB_FAILED : "Database &1 not found",
		INSTALL_STEP3_MYSQL_VERSION_FAILED : "MySQL version &1 is not working with this Galaxytool version",
		INSTALL_STEP4_URL : "OGame URL",
		OGAME_URL_DETAILS : "Please enter any URL you see when you are logged on to OGame. Based on that URL the tool will derive the OGame API address which can be used to fill data into the Galaxytool without the Galaxytoolbar. This API was introduced with OGame version 4.1.",
		INSTALL_STEP4_UNIVERSE : "OGame Universe",
		INSTALL_STEP4_DEF_TO_DEBRIS : "Defense to debris",
		INSTALL_STEP4_DEBRIS_RATE : "Debris rate",
		INSTALL_STEP4_SPEED_RATE : "Speed rate",
		INSTALL_STEP4_ENTER_UNIVERSE : "Enter your OGame universe name or number (case sensitive).",
		INSTALL_STEP4_UNIVERSE_MISSING : "You must define your universe",
		INSTALL_STEP4_ENTER_URL : "Enter your OGame universe address",
		INSTALL_STEP4_URL_MISSING : "You must define your OGame address",
		INSTALL_STEP4_URL_CHECK_FAILED : "Could not find OGame API at &1",
		INSTALL_STEP4_GETSETTINGS : "Fetch settings",
		INSTALL_STEP5_TOOLNAME : "Galaxytool name",
		INSTALL_STEP5_ENTER_TOOLNAME : "This is the name which will be shown at logon page to identify your Galaxytool",
		INSTALL_STEP5_LANGUAGE : "Default language",
		INSTALL_STEP5_EMAIL_TO : "Email To",
		INSTALL_STEP5_ENTER_EMAIL_TO : "Enter the email address where you would like to receive notifications about registrations",
		INSTALL_STEP5_EMAIL_FROM : "Email From",
		INSTALL_STEP5_ENTER_EMAIL_FROM : "This email address is shown as REPLY for all mails sent from the Galaxytool",
		INSTALL_STEP5_USE_PHPMAILER : "Use PHPMailer",
		INSTALL_STEP5_MAXSHOUTS : "Maximum number of shoutbox entries",
		INSTALL_STEP5_ENTER_USE_PHPMAILER : "Use PHPMailer if your server does not support sending emails by default",
		INSTALL_PHPMAILER_HOST : "SMPT Host",
		INSTALL_PHPMAILER_HOST_EXAMPLE : "e.g. smtp.provider.com",
		INSTALL_PHPMAILER_USER : "SMPT Username",
		INSTALL_PHPMAILER_USER_EXAMPLE : "e.g. user@provider.dcom",
		INSTALL_PHPMAILER_PASS : "SMPT password",
		INSTALL_PHPMAILER_SECURE : "Authentification method (e.g. ssl)",
		INSTALL_PHPMAILER_PORT : "SMTP Port",
		INSTALL_STEP6_INTRO : "Please define a password for the <strong>admin</strong> account which you have to use for your first logon to the Galaxytool after the installation.",
		INSTALL_STEP7_CONFIG : "Configuration file created",
		INSTALL_STEP7_CONFIG_FAILED : "Configuration file not created",
		INSTALL_STEP7_ATTRIBUTES : "Attributes file created",
		INSTALL_STEP7_ATTRIBUTES_FAILED : "Attributes file not created",
		INSTALL_STEP7_CREATED_TABLES : "Database tables created",
		INSTALL_STEP8_INTRO : "You have successfully installed the Galaxytool!",
		INSTALL_STEP8_LOAD_DATA : "Downloading OGame data ...",
		INSTALL_STEP8_LOAD_DATA_FINISHED : "Download of OGame data finished",
		INSTALL_STEP8_DELETE_FILE : "You should now delete the installation files install.php and update.php from your webserver.",
		INSTALL_STEP8_LOGON : "Please logon with the <strong>admin</strong> user and the password you defined earlier.",
		UPDATE_START : "Starting update to version &1",
		UPDATE_STEP_DONE : "Done",
		UPDATE_TITLE : "Galaxytool update for version",
		UPDATE_STEP1_WELCOME : "Welcome to the update wizard of the Galaxytool. You will be guided through the update of the Galaxytool.",
		UPDATE_STEP1_BACKUP_FILES : "As a first step, make a backup of your <strong>config</strong> folder! You will have to replace the configuration content in case of errors.",
		UPDATE_STEP1_BACKUP_DB : "Then make a <a href=\"http://www.ehow.com/how_2036600_create-database-php.html\">backup</a> of your database.",
		UPDATE_STEP1_PROCEED : "Once the backups have been done, you can proceed with your update.",
		UPDATE_STEP1 : "Welcome",
		UPDATE_STEP2 : "Galaxytool settings",
		UPDATE_STEP2_OLD_VERSION : "Previous Galaxytool version",
		UPDATE_STEP3 : "Update Galaxytool",
		UPDATE_STEP3_UPDATE_RUNNING : "Update running, please wait...",
		UPDATE_STEP4 : "Finalize Update",
		UPDATE_STEP4_INTRO : "You have successfully updated the Galaxytool!",
		UPDATE_STEP4_UPDATE_DONE : "Update steps performed.",
		UPDATE_FAILED : "Update failed.",
		GALAXYTOOL_DUMMY_TEXT : "dummy"
	})
);