define(
	({
		REPORT_WHEN : "de",
		RESOURCES_ON : "üzerinde bulunan hammaddeler",
		PLAYER_BANNED : "c",
		PLAYER_VACATION_MODE : "t",
		PLAYER_NOOB : "z",
		PLAYER_INACTIVE : "i",
		PLAYER_LONG_INACTIVE : "I",
		PLAYER_OUTLAW : "k",
		L_USERNAME : "Kullanıcı Adı",
		L_PASSWORD : "Şifre",
		L_LOGINFAILURE : "Kullanıcı Adı ya da Şifreniz yanlış veya hesabınız henüz etkinleştirilmemiş.",
		L_TOKENFAILURE : "Your logon key is wrong or your account is not activated yet.",
		L_LOGINTEXT : "Lütfen sisteme giriş yapın.",
		L_LANGUAGE : "Mevcut diller:",
		L_TIMEOUT : "Oturum süresi doldu!",
		L_REGISTER : "Kayıt",
		L_PWLOST : "Şifremi Unuttum",
		INDEX_TITLE : "Genel Durum",
		INDEX_INFO : "Bilgi",
		INDEX_ENTRIES : "Toplam Kayıtlı Sistem",
		INDEX_ENTRIES_LASTWEEK : "Geçen Hafta Güncellenen Sistemler",
		INDEX_ENTRIES_TO_OLD : "Güncel Olmayan Sistemler (1 aydan daha eski)",
		INDEX_REGISTERED_USERS : "Kayıtlı Kullanıcılar",
		INDEX_PAGEFORWARD : "Tarayıcınız yönlendirmeyi desteklemiyorsa lütfen burayı tıklayın.",
		INDEX_NOTICES : "Notlar",
		INDEX_PLAYERS : "Oyuncu İstatistikleri",
		INDEX_ALLIES : "İttifak İstatistikleri",
		INDEX_REPORTS : "Casusluk Raporları",
		INDEX_VERSION : "İndirilebilir en son sürüm",
		INDEX_LATEST_VERSION : "Daha yeni bir sürüm bulunmamaktadır.",
		INDEX_SHOUTBOX : "Duyurular",
		INDEX_NOENTRY : "Henüz duyuru yapılmamış.",
		INDEX_COMMENT : "Duyuru Mesajınız",
		INDEX_INSERT : "Ekle",
		INDEX_UMOD : "Tatildeki Oyuncular",
		INDEX_NO_MOONS : "Toplam AY",
		INDEX_NO_EMPTY_SYSTEMS : "Boş Güneş Sistemleri",
		INDEX_NO_FULL_SYSTEMS : "Tamamen Dolu Güneş Sistemleri",
		INDEX_NO_TARGETS : "Olası Hedefler",
		INDEX_USERINFO : "Kullanıcı Sayısı",
		INDEX_ONLINE : "Çevrimiçi Kullanıcı(lar)",
		INDEX_TODAY : "Bugün Çevrimiçi Olan(lar)",
		INDEX_ALL : "Sisteme Giriş Toplamı",
		GENERAL_LOAD_FORM : "Form verisini yükle",
		GENERAL_SAVE_FORM : "Form verisini kaydet",
		GENERAL_SAVE_AS_TEXT : "farklı kaydet",
		GENERAL_SAVE : "Kaydet",
		INDEX_USERMANAGEMENT : "Activation Overview",
		INDEX_NEEDADMIN : "Accounts to unlock",
		INDEX_NEEDEMAIL : "Unvalidated Accounts",
		INDEX_TOOLBAR_INFO : "Galaxytool plugin information",
		INDEX_TOOLBAR_URL : "Galaxytool URL",
		INDEX_TOOLBAR_VERSION_REQUIRED : "Requires at least Galaxytool plugin version",
		INDEX_TOOLBAR_INSTALL_GUIDE : "Installation instructions for plugin",
		INDEX_TOOLBAR_TOKEN : "Logon key",
		INDEX_TOOLBAR_NEW_TOKEN : "Get new key",
		INDEX_PLAYERS_WITH_N_PLANETS : "Players with more than &1 planets",
		INDEX_GETTING_STARTED : "Getting started with the Galaxytool",
		INDEX_GETTING_STARTED1 : "Welcome to the Galaxytool!",
		INDEX_GETTING_STARTED2 : "The Galaxytool will help you to analyze what is going on in your OGame universe &1",
		INDEX_GETTING_STARTED3 : "Before you can actually analyze data you have to insert it first. For this you require a browser plugin like the &1 for Firefox.",
		INDEX_GETTING_STARTED4 : "After you installed the plugin, you navigate through your OGame pages as usual and you will see a small status window whenever something was sent to your Galaxytool.",
		INDEX_GETTING_STARTED5 : "Once the plugin inserted data into the Galaxytool, you can start to analyze where the players have their colonies, how many colonies they have, what reports exist or when they are active the most.",
		INDEX_GETTING_STARTED6 : "But it will also help you to analyze how you are progressing if you compare yourself against your competitors or by analyzing your combat reports to see how much you raided during the last days or weeks.",
		INDEX_GETTING_WIKIPAGE : "There are many more features within the Galaxytool.",
		INDEX_GETTING_WIKIPAGE2 : "Check them out at our wiki page.",
		INDEX_GETTING_BOARD : "For feedback or ideas you can use our board:",
		INDEX_GETTING_CHAT1 : "Or visit us at the chatroom:",
		INDEX_GETTING_CHAT2 : "We are not online 24/7 but spare a lot of our free time there, so be patient.",
		INDEX_CLOSE : "Close",
		INDEX_LOGIN : "Login",
		GENERAL_REQUIRED_FIELDS : "Please fill all required fields",
		INDEX_MESSAGES : "Messages",
		INDEX_EXAMPLE : "Example",
		INDEX_INVALID_DATA : "Invalid data",
		GENERAL_COLUMN_HIDE_TITLE : "Manage columns",
		GENERAL_COLUMN_HIDE_INFO : "Please select which columns you want to see in the table.",
		GENERAL_ENTRIES_DELETED : "&1 entries deleted",
		GENERAL_APPLY : "Apply",
		STARTPAGE_GALAXYTOOL_DESCR : "<em>Galaxytool</em> is a tool for the browser game OGame.",
		GENERAL_OVERWRITE : "Overwrite duplicate entry",
		GENERAL_OVERWRITE_QUESTION : "Overwrite?",
		INDEX_OWN_LOGINS : "Your logins",
		GENERAL_OPEN_IN_NEW_WINDOW : "Yeni pencerede aç",
		GENERAL_UNIT_OF_MEASURE_DAYS : "Days",
		PROGRAM_NAME : "OGame Galaksi Veritabanı",
		SHORTNAME : "Galaksi Veritabanı",
		BACK_INDEX : "Ana Sayfaya Geri Dön",
		UNIVERSE : "Evren",
		MENU_INFO_LINKS : "Bilgi",
		MENU_PAGE : "Genel Durum",
		MENU_DB_SEARCH : "Veritabanında Ara",
		MENU_DB_NOTICES : "Notlarda Ara",
		MENU_DB_REPORTS : "Raporlarda Ara",
		MENU_GALAXYVIEW : "Galaksi İncele",
		MENU_STATISTICS : "İstatistikler",
		MENU_ALLYHISTORY : "İttifak Tarihçesi",
		MENU_FLEET_MOVEMENTS : "Filo Hareketleri",
		MENU_COMBAT_REPORTS : "Savaş raporları",
		MENU_MESSAGES : "Mesajlar",
		MENU_OPTION_LINKS : "Seçenekler",
		MENU_DB_REFRESH : "Veritabanına Ekle",
		MENU_NOTICES : "Notlar",
		MENU_DB_STATUS : "Veritabanı Durumu",
		MENU_USEROPTIONS : "Kullanıcı Yönetimi",
		MENU_USEROPTIONS2 : "Kullanıcı Seçenekleri",
		MENU_USEROPTIONS3 : "Kullanıcı Bilgileri",
		MENU_ADMIN : "Administration",
		MENU_LOGOUT : "Oturumu Kapat",
		MENU_STUFF : "Diğer",
		MENU_FORUM_THREAD : "Yazılımcı Forumu",
		MENU_DOWNLOADPAGE : "İndirme Sayfası",
		MENU_LANGUAGE : "Dil Seçenekleri",
		MENU_HELP : "Yardım",
		MENU_TOOLOPTIONS : "Galaksi Veritabanı Seçenekleri",
		PARSER_INFO1 : " Veritabanına eklendi.",
		PARSER_ERROR1 : "Aşağıdaki koordinatlar veritabanına kaydedilirken hata oluştu:",
		PARSER_ERROR2 : "Veritabanı bulunamadı!",
		PARSER_ERROR3 : "Veritabanı sunucusu bulunamadı!",
		PARSER_WRONG_UNIVERSE : "Yanlış evren - şu anki: \"&1\"  beklendi: \"&2\"",
		SHOW_TITLE : "OGame Galaksi Veritabanı - Arama Sayfası",
		SHOW_SEARCH : "Veritabanında Ara",
		SHOW_ALLYSYMBOL : "İttifak Etiketi",
		SHOW_PLAYERNAME : "Oyuncu Adı",
		SHOW_MOONS : "Yalnızca AY'ı bulunan gezegenler",
		SHOW_NOTICES : "Yalnızca not kaydedilmis gezegenler",
		SHOW_COLONIES : "Yalnızca sömürgeleştirilebilecek gezegenler",
		SHOW_YES : "Evet",
		SHOW_NO : "Hayır",
		SHOW_SEARCHRANGE : "Arama Menzili",
		SHOW_SEARCH_IN : "Galaksi",
		SHOW_FROM_SYSTEM : "Güneş Sistemi Aralığı",
		SHOW_FROM_PLANET : "Gezegen Pozisyonu Aralığı",
		SHOW_TO : "ile",
		SHOW_DESCRIPTION : "Oyuncu ve ittifak isimleri için * joker karakterini kullanabilirsiniz.<br />Böylece isminin içerisinde belli bir kelime bulunanları listeleyebilirsiniz.<br /><br />Yalnızca ihtiyacınız olan arama kriterlerini doldurun.",
		SHOW_SORT_BY : "Sıralama",
		SHOW_GALASYSTEM : "Galaksi/Sistem",
		SHOW_ALLYNAME : "İttifak Adı",
		SHOW_SEARCHBUTTON : "Ara",
		SHOW_ADDRESS : "Adres",
		SHOW_ALLYSORT : "İttifak",
		SHOW_PLANET : "Gezegen Adı",
		SHOW_STATUS : "Durum",
		SHOW_CURRENTNESS : "Güncellik",
		SHOW_PLAYER_STATUS : "Oyuncu Durumu",
		SHOW_PLAYER_STATUS1 : "hepsi",
		SHOW_PLAYER_STATUS2 : "olası hedefler",
		SHOW_PLAYER_STATUS3 : "pasif",
		SHOW_HITS : "Listelenen Sonuçlar",
		SHOW_OF : " Toplam Sonuç:",
		SHOW_ASC : "Dogrusal Sıralama",
		SHOW_DESC : "Tersten Sıralama",
		SHOW_RESULTS : "Sayfa Başına Sonuç",
		SHOW_MOON : "AY",
		SHOW_UKMOONSIZE : "Bilgi Yok",
		SHOW_DF : "HA",
		SHOW_DF_LONG : "Harabe Alanı",
		SHOW_METAL : "M",
		SHOW_METAL_LONG : "Metal",
		SHOW_CRYSTAL : "K",
		SHOW_CRYSTAL_LONG : "Kristal",
		SHOW_BOTH : "Toplam Harabe",
		SHOW_AT_LEAST : "(en az)",
		SHOW_DATE : "Tarih",
		SHOW_DATE_0 : "herhangi",
		SHOW_DATE_1 : "tarihinden önce",
		SHOW_DATE_2 : "tarihinden sonra",
		SHOW_RANK : "Sıralama",
		SHOW_FRANK : "Filo Sıralaması",
		SHOW_MEMBERS : "Üye Sayısı",
		SHOW_NOTRANKED : "İlk 1500'de degil.",
		SHOW_NOTICERES : "Notlar",
		SHOW_REPORTS : "Yalnızca casusluk raporu olan gezegenler",
		SHOW_REPORTS_SHORT : "Raporlar",
		SHOW_NOTHING : "Kayıt Bulunamadı",
		SHOW_ALLIANCE_STATUS : "İttifak Durumu",
		SHOW_NO_STATUS : "Durum Bilgisi Yok",
		SHOW_NAP : "Saldırmazlık Antlaşması",
		SHOW_ALLIED : "Müttefik",
		SHOW_WAR : "Savaş",
		SHOW_BOYCOTT : "Boykot",
		SHOW_NEUTRAL : "Tarafsız",
		SHOW_OWN : "İttifakım",
		SHOW_WING : "Alt İttifak",
		SHOW_EXT_OPTIONS1 : "Aralık, sıralama, tarih veya harabe aramaları için daha fazla arama seçeneği göster.",
		SHOW_EXT_OPTIONS2 : "Sömürgeler, AY'lar, raporlar, notlar ve diplomatik durumlar için daha fazla arama seçeneği göster.",
		SHOW_EXT_OPTIONS3 : "Arama sonuçlarını sıralamak için daha fazla arama seçeneği göster.",
		SHOW_EXTENDED : "advanced search",
		SHOW_MOON_SELECTION : "Planet with moon",
		SHOW_REPORT_SELECTION : "Planet with report",
		SHOW_FILTER_BY : "Exclude from the list",
		SHOW_FILTER_NONE : "Hiçbiri",
		SHOW_PLAYERS_WITHOUT_PROGRESS : "Show players without score changes within the last few days",
		STATUS_TITLE : "OGame Galaksi Veritabanı - Durum Sayfası",
		STATUS_DB_STATUS : "Veritabanı Durumu",
		STATUS_COLOR : "Renk",
		STATUS_AGE1 : "1 günlük bilgi",
		STATUS_AGE2 : "2 - 4 günlük bilgi",
		STATUS_AGE3 : "4 - 7 günlük bilgi",
		STATUS_AGE4 : "1 - 2 haftalık bilgi",
		STATUS_AGE5 : "2 - 4 haftalık bilgi",
		STATUS_AGE6 : "4 haftadan daha eski bilgi",
		STATUS_AGE7 : "Bilgi kaydı yok",
		STATUS_ON : "on",
		STYLES_COLOR1 : "Renk1",
		STYLES_COLOR2 : "Renk2",
		STYLES_COLOR3 : "Renk3",
		STYLES_COLOR4 : "Renk4",
		STYLES_COLOR5 : "Renk5",
		STYLES_COLOR6 : "Renk6",
		STYLES_COLOR7 : "Renk7",
		STATUS_DB_LEGEND : "Legend",
		STATUS_GALAXY : "Galaxy Overview",
		USER_TITLE : "Kullanıcı Yönetimi",
		USER_NAMES : "Kullanıcı",
		USER_ERROR : "Hata",
		USER_NEWUSER : "Yeni Kullanıcı",
		USER_OPTIONS : "Seçenekler",
		USER_USERNAME : "Kullanıcı Adı",
		USER_PASSWORD : "Şifre",
		USER_PASSWORD_CONFIRM : "Şifre (tekrar)",
		USER_GALAXY : "Galaksi",
		USER_SEARCH : "Arama Yetkisi",
		USER_INSERT : "Ekleme Yetkisi",
		USER_DELETE : "Sil",
		USER_DELETE_ENTRY : "Kullanıcıyı silmek istiyor musunuz ?",
		USER_STATUS : "İstatistikleri Görebilir",
		USER_STYLES : "Düzenle",
		USER_SUBMIT : "Gönder",
		USER_RESET : "Temizle",
		USER_YES : "Evet",
		USER_NO : "Hayır",
		USER_STYLEPATH : "Styles.css dosya yolu",
		USER_PROBES : "Rapor Okuma/Kaydetme Yetkisi",
		USER_EMAIL : "E-Posta",
		USER_ERROR1 : "Şifre yanlış ya da e-posta geçersiz.",
		USER_ERROR2 : "E-Posta geçersiz.",
		USER_INGAME : "Oyundaki Adı",
		USER_ALLYTAG : "İttifak Etiketi",
		USER_ALLYHISTORY : "İttifak Tarihçesi Okuma/Kaydetme Yetkisi",
		USER_DIPLOMATIC : "Diplomatik Durum Tanımlama Yetkisi",
		USER_STATSPAGE : "İstatistiklerde Sayfa Başına Sonuç",
		USER_LINKS : "Linkler",
		USER_LINKS2 : "Format:<br>text;url<br>text2;url2<br>text3;url3",
		USER_EXPORT_TITLE : "Renklendirme (BB Kodları)",
		USER_BB_COORDINATES : "Koordinatlar",
		USER_BB_MOON : "AY",
		USER_BB_DEBRIS : "Harabe Alanı",
		USER_BB_ALLY : "İttifak Adı",
		USER_BB_ALLYDETAILS : "İttifak Detayları",
		USER_BB_PLAYERNAME : "Oyuncu Adı",
		USER_BB_BANNED : "Cezalı",
		USER_BB_VACATION : "Tatilde",
		USER_BB_NOOB : "Zayıf Oyuncu",
		USER_BB_INACTIVE : "Pasif Oyuncu",
		USER_BB_LONGINACTIVE : "Uzun Süreli Pasif Oyuncu",
		USER_DELETION : "Sil",
		USER_FLEETINFO : "Filo Hareketleri",
		USER_ACTIVITIES : "Oyuncu Aktivitesi",
		USER_MAINTENANCE : "Galaxytool Bakımı",
		USER_MANAGEMENT : "Kullanıcı Yönetimi",
		USER_DELETE_MY_COMBAT_REPORTS : "Savaş raporlarını sil",
		USER_DELETE_MY_MESSAGES : "Kendi Mesajlarını Sil",
		USER_DELETE_MY_FLEETMOVES : "Kendi filo hareketlerini sil",
		USER_DELETE_MY_COMBAT_REPORTS_LIMITED : "Delete my combat reports older than &1 days",
		USER_DELETE_MY_MESSAGES_LIMITED : "Delete my messages older than &1 days",
		USER_TABLE_ENTRIES : "Number of search results for each page",
		USER_EXISTS : "User already exists",
		USER_BB_OUTLAW : "Outlaw",
		USER_INVALID_URL : "URL &1 seems to be invalid - URL will be ignored",
		VIEW_TITLE : "OGame Galaksi Veritabanı - Detaylar",
		VIEW_NODATA : "Veri bulunamadı.",
		VIEW_GALAXY : "Galaksi",
		VIEW_SYSTEM : "Güneş Sistemi",
		VIEW_POSITION : "Poz.",
		VIEW_PLANET : "Gezegen",
		VIEW_MOON : "AY",
		VIEW_TF : "HA",
		VIEW_PLAYER : "Oyuncu",
		VIEW_PLAYER_ADD : "(Sıra / Durum)",
		VIEW_ALLY : "İttifak",
		VIEW_ALLY_ADD : "(Sıra / Üye)",
		VIEW_METAL : "M",
		VIEW_CRYSTAL : "K",
		VIEW_COLONISED : "Yerleşilmiş Gezegenler",
		VIEW_UKMOONSIZE : "Bilgi Yok",
		VIEW_BACK : "Geri",
		VIEW_NOTICE : "Notlar",
		VIEW_REPORTS : "Raporlar",
		VIEW_MOONPHALANX : "Bu sistem şu koordinatlardaki AY'lar tarafından radarlanabilir",
		VIEW_NOMOONS : "AY tespit edilemedi",
		VIEW_IRAKS : "Bu sisteme şu gezegenler GAR atabilir",
		VIEW_NOIRAKS : "GAR tespit edilemedi",
		VIEW_MOON_DESTROY_CHANCE : "AY Yoketme İhtimali",
		VIEW_CHANCE_WITH_ONE : "Tek bir Ölüm Yıldızı ile ",
		VIEW_CHANCE_WITH_N : "",
		VIEW_DEATH_STARS : " Ölüm Yıldızı ile ",
		VIEW_DS_DESTROY_CHANCE : "Ölüm Yıldız(lar)ını Kaybetme İhtimali",
		VIEW_TOP : "Aralık",
		VIEW_GO : "Git",
		VIEW_DIAMETER : "Diameter",
		PW_TITLE : "OGame Galaksi Veritabanı - Şifre Değiştirme",
		OLD_PASSWORD : "Eski Şifre",
		NEW_PASSWORD : "Yeni Şifre",
		CONFIRM_NEW_PASSWORD : "Yeni Şifre (tekrar)",
		PW_MISMATCH : "Şifreler Uyumsuz!",
		PW_ERROR : "Eski Şifreniz Doğru Değil!",
		UPDATE_DONE : "Şifreniz Degiştirildi.",
		TIMEZONE_OFFSET : "Saat Dilimi",
		DELETE_ACCOUNT : "Kullanıcıyı Sil",
		DELETE_ACCOUNT_SAFETY_REQUEST : "Bu Kullanıcıyı Gerçekten Silmek istiyormusunuz?",
		CH_PASSWD_AUTHORIZATION : "Yetki Verme",
		CH_PASSWD_ADMIN : "Yönetici",
		TIMEZONE_OGAME_OFFSET : "OGame server saat dilimi",
		CH_PASSWD_USER_LANGUAGE : "Change to this language after logon",
		CH_PASSWD_USER_LANGUAGE_NO_CHANGE : "No change",
		CH_PASSWD_EXPAND : "Expanded",
		CH_PASSWD_COLLAPSE : "Collapsed",
		CH_PASSWD_HIDDEN : "Hidden",
		CH_PASSWD_GETTING_STARTED : "Show Getting Started Info after logon",
		CH_PASSWD_PLUGIN : "Show Plugin Info after logon",
		NOTICE_TITLE : "OGame Galaksi Veritabanı - Notlar",
		NOTICE_HEADER : "Notu Düzenle",
		NOTICE_HEADER2 : "Notlarınızı Düzenleyin",
		NOTICE_PUBLIC : "Diğer kullanıcılar okuyabilir mi ?",
		NOTICE_YES : "Evet",
		NOTICE_NO : "Hayır",
		NOTICE_TEXT : "Not Metni",
		NOTICE_SAVE : "Kaydet",
		NOTICE_DELETED : "Kayıt Silindi",
		NOTICE_SAVED : "Kaydedildi.",
		NOTICE_RESULTS : "Tüm Sonuçlar",
		NOTICE_USER : "Kullanıcı",
		NOTICE_DATE : "Tarih",
		NOTICE_EDIT : "Düzenle",
		NOTICE_DELETE : "Sil",
		NOTICE_NEW : "Özel Not Oluştur",
		NOTICE_NOTPUBLIC : "Özel Not",
		NOTICE_ALL : "Tümü",
		NOTICE_NONE : "Hiçbiri",
		NOTICE_SEARCH : "Notlarda Ara",
		NOTICE_SEARCH_SHORT : "Ara",
		NOTICE_HITS : "Sonuçlar",
		NOTICE_SHOWRESULTS : "Sayfa Başına Sonuç",
		NOTICE_OF : "Toplam Sonuç: ",
		NOTICE_NOTHING : "Kayıt Bulunamadı",
		NOTICE_CHARS : "Toplam Karakter",
		NOTICE_PLAYERNAME : "Oyuncu",
		NOTICE_SHOWALL : "Tüm Notları Göster",
		REPORTS_TITLE : "OGame Galaksi Veritabanı - Casusluk Raporları",
		REPORTS_RESOURCES : "Hammadde",
		REPORTS_FLEET : "Filolar",
		REPORTS_DEFENCE : "Savunma",
		REPORTS_BUILDINGS : "Bina",
		REPORTS_TECHNOLOGY : "Bilimsel Araştırma",
		REPORTS_MOON : "AY",
		REPORTS_SEARCH : "Casusluk Raporlarında Ara",
		REPORTS_SEARCH_SHORT : "Ara",
		REPORTS_HITS : "Sonuçlar",
		REPORTS_NOTHING : "Kayıt Bulunamadı",
		REPORTS_ADDRESS : "Adres",
		REPORTS_CURRENTNESS : "Güncellik",
		REPORTS_PLAYERNAME : "Oyuncu Adı",
		REPORTS_ALLY : "İttifak",
		REPORTS_VIEW : "Raporu İncele",
		REPORTS_SEARCH_IN : "Arama Menzili - Galaksi",
		REPORTS_FROM_SYSTEM : "Güneş Sistemi Aralığı",
		REPORTS_TO : "ile",
		REPORTS_DELETE : "Sil",
		REPORTS_DELETED : "Kayıt Silindi",
		REPORTS_RESULTS : "Sayfa Başına Sonuç",
		REPORTS_OF : "Toplam Sonuç: ",
		REPORTS_DATE : "Tarih",
		REPORTS_DATE_0 : "herhangi",
		REPORTS_DATE_1 : "tarihinden önce",
		REPORTS_DATE_2 : "tarihinden sonra",
		REPORTS_NOTICES : "Notlar",
		REPORTS_AT_LEAST_RESOURCES : "Hammadde Toplamı (en az)",
		REPORTS_SEARCH_EXTENDED : "Genişletilmiş Arama",
		REPORTS_FLEET_RESIS : "Filo Puanı",
		REPORTS_DEFENCE_RESIS : "Savunma Puanı",
		REPORTS_ALL_RESIS : "Toplam Puan",
		REPORTS_TECHS : "Teknikler",
		REPORTS_UNKNOWN_ENTRIES : "Bilinmeyen Alan",
		REPORTS_PARTLY_INSERTED : "Kısmen Kaydedildi",
		REPORTS_FOR_ALL_RES : "tüm hammadde için",
		REPORTS_FOR_TF : "harabe alanı için",
		REPORTS_KT : "Küçük Nakliye Gemileri",
		REPORTS_GT : "Büyük Nakliye Gemileri",
		REPORTS_SS : "Savaş Gemileri",
		REPORTS_REC : "Geri Dönüşümcü",
		REPORTS_RAIDABLE : "Yalnızca hücum edilebilir hedefler",
		REPORTS_ALL_RESOURCES : "tum hammaddeler",
		REPORTS_STUFF : "Diğer",
		REPORTS_SPEEDSIM : "SpeedSim ile Hesapla",
		REPORTS_DRAGOSIM : "Dragosim ile Hesapla",
		REPORTS_STATUS : "Durum",
		REPORTS_ERROR : "Bir hata oluştu",
		REPORTS_OWN_REPORTS : "Casus Sondasi Raporlarım",
		REPORTS_UPLOAD_BY : "Raporu Yükleyen",
		REPORTS_DEPTH : "Sonda Raporu Detayı",
		REPORTS_FLEET_SCORE : "Filo Puanı",
		REPORTS_DEFENCE_SCORE : "Savunma Puanı",
		REPORTS_HOURS : "hours",
		REPORTS_MAX_RESULTS_HIT : "Your query returned more than &1 hits. Only the first &1 results are show. Please adjust your search request to get less results.",
		REPORTS_OSIMULATE : "Simulate with OSimulate",
		REPORTS_SHOW_ONLY : "Show only",
		REPORTS_SHOW_PLANETS : "Gezegenler",
		REPORTS_SHOW_MOONS : "Aylar",
		REPORTS_OWNER : "Reports owned by",
		STATS_TITLE : "OGame Galaksi Veritabanı - İstatistikler",
		STATS_TBLHEAD : "İstatistikler",
		STATS_RANK : "Sıralama",
		STATS_PLAYERNAME : "Oyuncu Adı",
		STATS_ALLYNAME : "İttifak Etiketi",
		STATS_SCORE : "Puan",
		STATS_FLEET : "Filo",
		STATS_RESEARCH : "Araştırma",
		STATS_MEMBERS : "Üye Sayısı",
		STATS_STATUS : "Durum",
		STATS_NOTHING : "Belirsiz",
		STATS_NAP : "Saldırmazlık Antlaşması",
		STATS_ALLIED : "Müttefik",
		STATS_WAR : "Savaş",
		STATS_BOYCOTT : "Boykot",
		STATS_NEUTRAL : "Tarafsız",
		STATS_OWN : "İttifakım",
		STATS_WING : "Alt İttifak",
		STATS_UPDATE : "Güncelleme",
		STATS_PLAYERSTATS : "Oyuncu İstatistikleri",
		STATS_ALLYSTATS : "İttifak İstatistikleri",
		STATS_DELETE : "Bu kaydı silmek istiyor musunuz ?",
		STATS_CONFIRM_DELETE : "Bu kullanıcı kaydını gerçekten silmek istiyor musunuz ?",
		STATS_CHANGE_PLAYER_STATUS : "Oyuncu Durumu",
		STATS_CHANGE_ALLIANCE_STATUS : "İttifak Durumu",
		STATS_CHANGE_ALLIANCE_STATUS_HINT : "Bu ittifakin tüm üyeleri seçilen diplomatik durum ile tanımlanırlar. Önceden yapılan tanımlamaların üstüne kaydedilir. Oyuncu bazında diplomatik durum bilgisini (gerekiyorsa) tekrar tanımlamanız gerekmektedir.",
		STATS_UNKNOWN : "Diğerleri",
		STATS_DETAILS : "Detaylar",
		STATS_PLAYERSTATUS : "Oyuncu Durumu",
		STATS_IGNORE_STATUS : "hepsi",
		STATS_ACTIVE : "Aktif",
		STATS_INACTIVE : "Pasif Oyuncu",
		STATS_BANNED : "Cezalı",
		STATS_VACATION : "Tatilde",
		STATS_NOOB : "Zayıf Oyuncu",
		STATS_YES : "Evet",
		STATS_NO : "Yalnızca not kaydedilmis gezegenler",
		STATS_SEARCH : "Arama Yetkisi",
		STATS_SHOW_GRAPH : "Show details for score distribution",
		STATS_LONG_INACTIVE : "Uzun Süreli Pasif Oyuncu",
		STATS_STANDARD : "Standard Points",
		STATS_MILITARY : "Military Points",
		STATS_ECONOMY : "Economy",
		STATS_HONOUR : "Honour points",
		STATS_MILITARY_BUILD : "Military build",
		STATS_MILITARY_DESTROYED : "Military destroyed",
		STATS_MILITARY_LOST : "Military lost",
		REGISTER_REGISTRATE : "Kayıt",
		REGISTER_LOGINNAME : "Kullanıcı Adı",
		REGISTER_PASSWORD : "Şifre",
		REGISTER_PASSWORD_CONFIRM : "Şifre (tekrar)",
		REGISTER_EMAIL : "E-Posta",
		REGISTER_INGAME : "Oyundaki Ad",
		REGISTER_ALLYTAG : "İttifak Etiketi",
		REGISTER_EMAILVERIFICATION : "E-Posta Doğrulama",
		REGISTER_EMAILTEXT : "Lütfen linki tıklayarak Galaksi Veritabanı kayıt işleminizi onaylayınız.",
		REGISTER_ERROR1 : "Kullanıcı Adı daha önceden alınmış.",
		REGISTER_ERROR2 : "E-Posta gönderilirken bir hata oluştu. Lütfen yöneticiniz ile irtibat kurun.",
		REGISTER_ERROR3 : "Veritabanına bilgi gönderirken hata oluştu!",
		REGISTER_INFO1 : "Hesabınız oluşturuldu.",
		REGISTER_INFO2 : "Lütfen size gönderilen e-posta'da bulunan linki tıklayarak kayıt işleminizi tamamlayın..",
		REGISTER_INFO3 : "E-Posta adresiniz doğrulandı. Hesabınızın yönetici tarafından etkinleştirilmesi gerekiyor.",
		REGISTER_BUTTON : "Ana Sayfaya Geri Dön",
		REGISTER_NEW_SUBJECT : "Galaksi Veritabanına yeni kullanıcı kaydedildi.",
		REGISTER_NEW_MAILTEXT : "Yeni kullanıcı kayıt işlemlerini tamamladı.",
		REGISTER_BACK : "Ilk sayfaya dön",
		REGISTER_MISSING_FIELDS : "Zorunlu alanları doldurun ",
		REGISTER_ERROR4 : "Email address is not valid.",
		REGISTER_ERROR5 : "Passwords don't match.",
		REGISTER_PWS : "Password strength",
		REGISTER_PWS0 : "very weak",
		REGISTER_PWS1 : "weak",
		REGISTER_PWS2 : "good",
		REGISTER_PWS3 : "strong",
		REGISTER_PWS4 : "very strong",
		REGISTER_EMAIL_USED : "Email Address is already used",
		LOSTPW_TITLE : "Şifremi Unuttum",
		LOSTPW_INFO2 : "Yeni şifreniz oluşturuldu ve e-posta adresinize gönderildi.",
		LOSTPW_BUTTON1 : "Yeni Şifre Al",
		LOSTPW_BUTTON2 : "Ana Sayfaya Geri Dön",
		LOSTPW_LOGINNAME : "Kullanıcı Adı",
		LOSTPW_EMAIL : "E-Posta",
		LOSTPW_ERROR1 : "Veritabanına bilgi gönderirken hata oluştu!",
		LOSTPW_ERROR2 : "Eslesen hicbir kayit bulunamadı!",
		LOSTPW_ERROR3 : "E-Posta gönderilirken bir hata oluştu. Lütfen yöneticiniz ile irtibat kurun.",
		LOSTPW_EMAIL_SUBJECT : "Talep etmiş olduğunuz yeni şifreniz...",
		LOSTPW_EMAIL_TEXT1 : "Galaksi Veritabanı için yeni giriş bilgileriniz",
		LOSTPW_EMAIL_TEXT2 : "Kullanıcı Adı",
		LOSTPW_EMAIL_TEXT3 : "Şifre",
		LOSTPW_INFO1 : "You will receive an email to verify your password reset request.",
		LOSTPW_CONFIRM_RESET_SUBJECT : "Lost password?",
		LOSTPW_CONFIRM_RESET_MESSAGE : "Hello,\n\nyou requested a password reset for the Galaxytool. To generate a new password, click the following link:",
		USERINFO_TITLE : "OGame Galaksi Veritabanı - Kullanıcı Bilgisi",
		USERINFO_NAMES : "Sisteme Kayıtlı Tüm Kullanıcılar",
		USERINFO_DETAIL : "Ayrıntılı Bilgi",
		USERINFO_ERROR1 : "Bu isimde kayıtlı bir kullanıcı yok!",
		USERINFO_USERNAME : "Kullanıcı Adı",
		USERINFO_INGAME : "Oyundaki Ad",
		USERINFO_EMAIL : "E-Posta",
		USERINFO_ALLYTAG : "İttifak",
		USERINFO_STYLEPATH : "Tema",
		USERINFO_STATUS : "Durum",
		USERINFO_ACTIVATE : "Hesabı Etkinleştir",
		USERINFO_LOGINS : "Sisteme Toplam Giriş Sayısı",
		USERINFO_LASTLOGIN : "Son Giriş Zamanı",
		USERINFO_DATA : "Kaydedilmiş Sistemler Hakkında Bilgi",
		USERINFO_NODATA : "Kullanıcı Henüz Hiçbir Sistem Kaydetmemiştir!",
		USERINFO_GALAXY : "Galaksi",
		USERINFO_SYSTEMS : "Güneş Sistemleri",
		USERINFO_IP : "IP Adresi",
		USERINFO_LOGINTIME : "Giriş Zamanı",
		USERINFO_NOLOGIN : "Oyuncu Sisteme Hiç Giriş Yapmadı.",
		USERINFO_LAST_GALAXYUPDATE : "En Son Kaydedilen Galaksi Ekranı",
		USERINFO_LAST_PUBLIC_NOTICE : "En Son Kaydedilen Genel Not",
		USERINFO_LAST_PRIVATE_NOTICE : "En Son Kaydedilen Özel Not",
		USERINFO_NUMBEROF_PUBLIC_NOTICE : "Toplam Genel Not",
		USERINFO_NUMBEROF_PRIVATE_NOTICE : "Toplam Özel Not",
		USERINFO_ACTIVATED : "Hesap Etkinleştirildi",
		USERINFO_ACTIVATIONTEXT : "Galaksi Veritabanı Yöneticisi hesabınızı etkinleştirdi.\n\nİyi eğlenceler!",
		USERINFO_LAST_SUBMIT : "Inserted last data",
		ALLYHISTORY_TITLE : "OGame Galaksi Veritabanı - İttifak Tarihçesi",
		ALLYHISTORY_TBLHEAD : "İttifak Tarihçesi - Genel Durum",
		ALLYHISTORY_PLAYERNAME : "Oyuncu Adı",
		ALLYHISTORY_ALLYNAME : "İttifak",
		ALLYHISTORY_LASTMONTH : "Geçen Ay",
		ALLYHISTORY_ALL_DATA : "Mevcut Tüm Bilgi",
		ALLYHISTORY_SHOW : "İstatistikleri Göster",
		ALLYHISTORY_TIMESPAN : "Zaman Aralığı",
		ALLYHISTORY_PROGESS : "Süreç",
		ALLYHISTORY_SCORE : "Puanlar",
		ALLYHISTORY_FSCORE : "Filo Puanları",
		ALLYHISTORY_RSCORE : "Araştırma Puanları",
		ALLYHISTORY_MEMBER : "Üye Sayısı",
		ALLYHISTORY_NOTHING : "Kayıt Bulunamadı",
		ALLYHISTORY_DETAILS : "Detaylar",
		ALLYHISTORY_SHOW_ADDRESS : "Koordinatlar",
		ALLYHISTORY_ESCORE : "Economy",
		ALLYHISTORY_MSCORE : "Military Points",
		DETAILEDINFO_PLAYERINFO_TITLE : "Kullanıcı Bilgisi",
		DETAILEDINFO_ALLYINFO_TITLE : "İttifak Bilgisi",
		DETAILEDINFO_PLAYERINFO_TBLHEAD : "Oyuncu Hakkında Ayrıntılı Bilgi",
		DETAILEDINFO_ALLYINFO_TBLHEAD : "İttifak Hakkında Ayrıntılı Bilgi",
		DETAILEDINFO_NO_ALLIANCE : "İttifak Yok",
		DETAILEDINFO_SCORE : "Puan İstatistiği",
		DETAILEDINFO_FLEET : "Filo İstatistiği",
		DETAILEDINFO_RESEARCH : "Araştırma İstatistiği",
		DETAILEDINFO_RANK : "Sıralama",
		DETAILEDINFO_POINTS : "Puan",
		DETAILEDINFO_KNOWN_PLANETS : "Bilinen Gezegenler",
		DETAILEDINFO_MOONS : "Bilinen AY'lar",
		DETAILEDINFO_PHALANX_AREA : "Radar Menzil Alanı",
		DETAILEDINFO_NO_PHALANX_AREA : "Radar Tespit Edilemedi",
		DETAILEDINFO_NOTICES : "Notlar",
		DETAILEDINFO_NO_NOTICES : "Kayıtlı Not Bulunamadı",
		DETAILEDINFO_PREVIOUS_ALLIANCES : "Önceki İttifak Üyelikleri",
		DETAILEDINFO_RESOURCES_PER_HOUR : "Saatlik Hammadde",
		DETAILEDINFO_RESOURCES_PER_DAY : "Günlük Hammadde",
		DETAILEDINFO_RESOURCES_PER_WEEK : "Haftalık Hammadde",
		DETAILEDINFO_RESOURCES_PER_MONTH : "Aylık Hammadde (30 gün)",
		DETAILEDINFO_METAL : "Metal",
		DETAILEDINFO_CRYSTAL : "Kristal",
		DETAILEDINFO_DEUTERIUM : "Deuterium",
		DETAILEDINFO_UNKNOWN : "Bilgi Yok",
		DETAILEDINFO_SCORE_DISTRIBUTION : "Puan Dağılımı",
		DETAILEDINFO_GENERAL : "Ayrıntılar",
		DETAILEDINFO_MEMBERS : "üye",
		DETAILEDINFO_GRAPHS : "Grafikler",
		DETAILEDINFO_RESOURCES : "Kaynaklar",
		DETAILEDINFO_FLEET_TAB : "Filo",
		DETAILEDINFO_TECH : "Araştırma",
		DETAILEDINFO_FLEET_DETAIL : "Toplam / (oyuncu ortalaması) Mevcut Raporlardan",
		DETAILEDINFO_TECH_DETAIL : "Oyuncu bilgilerinin ortalaması",
		DETAILEDINFO_PLANET_TAB : "Gezegenler",
		DETAILEDINFO_MOON_TAB : "Aylar",
		DETAILEDINFO_ACTIVITIES : "Faaliyetler",
		DETAILEDINFO_NODATA : "Veri bulunamadı.",
		DETAILEDINFO_ACTIVITY_DESCRIPTION : "Faaliyetleri göster &1 bu dönemde:",
		DETAILEDINFO_GALAXYVIEWS : "Galaxy izleme",
		DETAILEDINFO_SCANS : "Casusluk raporları",
		DETAILEDINFO_MESSAGES : "Oyuncu mesajları",
		DETAILEDINFO_COMBATS : "Savaş raporları",
		DETAILEDINFO_ALLYPAGE : "İttifak genel bakış",
		DETAILEDINFO_MANUAL : "Manual ekleme",
		DETAILEDINFO_START : "Başlangıç",
		DETAILEDINFO_TO : "kadar",
		DETAILEDINFO_TODAY : "Bugün",
		DETAILEDINFO_DATA_RESTRICTION : "ile sınırlıdır:",
		DETAILEDINFO_WEEKDAY_WEEKEND : "Haftalık",
		DETAILEDINFO_WEEKDAY_WORKINGDAY : "Bugün",
		DETAILEDINFO_WEEKDAY_MONDAY : "Pazartesi",
		DETAILEDINFO_WEEKDAY_TUESDAY : "Salı",
		DETAILEDINFO_WEEKDAY_WEDNESDAY : "Çarşamba",
		DETAILEDINFO_WEEKDAY_THURSDAY : "Perşembe",
		DETAILEDINFO_WEEKDAY_FRIDAY : "Cuma",
		DETAILEDINFO_WEEKDAY_SATURDAY : "Cumartesi",
		DETAILEDINFO_WEEKDAY_SUNDAY : "Pazar",
		DETAILEDINFO_WEEKDAY_SHORTLENGTH : 3,
		DETAILEDINFO_PLAYER_CURRENTLY_ACTIVE : "Oyuncu şu anda etkin",
		DETAILEDINFO_PLAYER_MESSAGES : "Uygun oyuncu mesajları",
		DETAILEDINFO_SHOW : "göster",
		DETAILEDINFO_NONE : "Uygun değil",
		DETAILEDINFO_ENTER_MANUALLY : "Bu Oyuncu için faaliyetler girin",
		DETAILEDINFO_PLAYER_SEEN_ON : "Oyuncu online oldu",
		DETAILEDINFO_INSERT : "Eklemek",
		DETAILEDINFO_OGAME_SERVERTIMES : "Bilgi: Bütün burada gösterilken zamanlar OGame sunucu zamanlarıdır!",
		DETAILEDINFO_DAY_VIEW : "24 saat izle",
		DETAILEDINFO_WEEK_VIEW : "Haftalık izle",
		DETAILEDINFO_HOME_PLANET : "Homeworld",
		DETAILEDINFO_PLANETNAME : "Name",
		DETAILEDINFO_DEFENCE_SCORE : "Defence score",
		DETAILEDINFO_DEFENCE_SCORE_TOOLTIP : "Defence score = Fleet - Score + Research + Economy.<br/>All those statistics must be up to date to have a meaningful result!",
		DETAILEDINFO_SCORE_PER_SHIP : "Scores per ship",
		DETAILEDINFO_SHIPS : "Number of ships",
		DETAILEDINFO_DATE_IN_FUTURE : "Do not maintain times which are not in the past.",
		ADMIN_TITLE : "Galaxytool Yönetimi",
		ADMIN_DISCLAMER : "Dikkat: Herhangi bir sikripti calıştırmanız sizin sorumluluğunuzdadır. Bunların birçoğu verinizi silebilir.",
		ADMIN_INCONSISTENCIES : "Veri tabanınındaki tutarsızlıklar",
		ADMIN_PLANETS : "0 ve 15'den büyük konumlarda bulunan gezegenleri sil.",
		ADMIN_GALAXIES : "&1 'den büyük numaralı galaksileri sil",
		ADMIN_PLAYERS : "Silinen Oyuncu Hesaplarini Temizle - Veri tabanında oyuncu numarası olmayan kayıtları temizle",
		ADMIN_REPORTS : "Silinen gezegenlere ait sonda raporlarını temizle",
		ADMIN_MISC : "çeşitli",
		ADMIN_RESET : "Galaxytool'u Sıfırla (Sadece kullanıcı ve ip tabloları silinmez)",
		ADMIN_OLD_PLAYERS : "&1 Günden eski oyuncu girişlerini sil",
		ADMIN_OLD_REPORTS : "&1 Günden eski sonda raporlarını sil",
		ADMIN_LOADING : "Sayfa yüklenmeden pencereyi kapatmayınız.",
		ADMIN_STATUS : "Isteklerinizin Durumu",
		ADMIN_SELECTION : "En azından bir komut seçilmelidir.",
		ADMIN_SAFETY : "Bu sikriptleri çalıştırmak istediğinize emin misiniz?",
		ADMIN_DONE : "Işlem Tamamlandı.",
		ADMIN_NOTBD : "Yapılacak bir iş bulunamadı.",
		ADMIN_OLD_GALAXIES : "&1 Günden eski olan galaksi verisini sil",
		ADMIN_UNUSED_PLAYERS : "Hesabı silinen oyuncuları veri tabanından temizle.",
		ADMIN_OLD_ACTIVITIES : "&1 günden eski olan oyuncu faaliyetlerini sil",
		ADMIN_OLD_COMBATS : "Remove combat reports older than &1 days",
		ADMIN_OLD_INGAME_MSG : "Remove ingame messages older than &1 days",
		ADMIN_OGAME_API : "Load public data from OGame into the Galaxytool",
		ADMIN_OGAME_ALL_DATA : "Mevcut Tüm Bilgi",
		ADMIN_OGAME_GALAXY_DATA : "Galaksi İncele",
		ADMIN_OGAME_STATISTICS_DATA : "İstatistikler",
		ERRORPAGE_PAGEFORWARD : "Tarayıcınız otomatik yönlendirmeyi desteklemiyorsa, Lütfen buraya tıklayın.",
		ERRORPAGE_PERMISSION_DENIED : "Bu sayfaya giriş izniniz yoktur. Buraya tıklayarak geri gidiniz.",
		FLEETS_TITLE : "OGame Galaxytool – Filo Hareketleri",
		FLEETS_ACTUAL_FLEETS : "Mevcut filo hareketleri",
		FLEETS_YES : "Evet",
		FLEETS_NO : "Yalnızca not kaydedilmis gezegenler",
		FLEETS_DETAILS : "Detaylar",
		FLEETS_MISSION_EXPEDITION : "Kesif",
		FLEETS_MISSION_COLONIZATION : "Sömürgelestirmek",
		FLEETS_MISSION_RECYCLE : "Harabe alanını sök",
		FLEETS_MISSION_TRANSPORT : "Nakliye",
		FLEETS_MISSION_DEPLOYMENT : "Konuslandırmak",
		FLEETS_MISSION_ESPIONAGE : "Casusluk",
		FLEETS_MISSION_ACS_DEFEND : "Durmak",
		FLEETS_MISSION_ATTACK : "Saldirmak",
		FLEETS_MISSION_ACS_ATTACK : "İttifak saldırısı",
		FLEETS_MISSION_MOON_DESTRUCTION : "Yok etmek",
		FLEETS_MISSION_MISSILE_ATTACK : "Füze Saldırısı",
		FLEETS_NO_DATA : "Uygulana bilir veri bulunamadı",
		FLEETS_FLEET : "Fleet",
		FLEETS_ALL_FLEETS : "Show all fleet movements",
		COMBAT_REPORT_OUDATED_GALAXYVIEW : "Verileriniz eski tekrar inçeleyin! Lütfen önce saldıran ve savunanın galaksigörüntülerini  ziyaret ediniz.",
		MESSAGES_TITLE : "OGame Galaxytool - OGame Messages",
		MESSAGES_PLAYERNAME : "Oyuncu adı",
		MESSAGES_SUBJECT : "Konu",
		MESSAGES_DATE : "Tarih",
		MESSAGES_FILTER : "Filtre",
		MESSAGES_DELETE : "Mesajı sil",
		MESSAGES_PUBLISH_DETAIL : "Bu mesaji içeriğini oyuncu Notlarına ekleyerek yayınlanabilirsiniz.",
		MESSAGES_PUBLISH_HEADER : "&sender &recipient(alan) am &date bu mesajı yolladı:\n\n &message",
		MESSAGES_PLAYER_FILTER : "Oyuncuda gelen mesajlar:",
		MESSAGES_CONTENT : "Content",
		COMBATS_TITLE : "OGame Galaxytool – Savaş raporu",
		COMBATS_ATTACKER : "Attack",
		COMBATS_DEFENDER : "Defans",
		COMBATS_DATE : "Tarih",
		COMBATS_OWNER : "Kullanıcı",
		COMBATS_WINNER : "Kazanan",
		COMBATS_COMBATREPORT : "Savaş raporu",
		COMBATS_COMBAT_AT : "Için savaş",
		COMBATS_LOST_UNITS : "Kaybedilen üniteler",
		COMBATS_LOOT : "Ele Geçirilen",
		COMBATS_DEBRIS : "Harabe",
		COMBATS_AND : "ve",
		COMBATS_PUBLISH : "Raporu paylaş",
		COMBATS_UNPUBLISH : "Raporu paylasma (tekrar özel kılar)",
		COMBATS_DELETE : "Raporu sil",
		COMBATS_CHECK_ALL : "hepsini seç",
		COMBATS_UNCHECK_ALL : "hepsini kaldır",
		COMBATS_WITH_SELECTED : "seçme ile",
		COMBATS_PUBLIC_REPORTS : "ortak SR´lar",
		COMBATS_YES : "Evet",
		COMBATS_NO : "Yalnızca not kaydedilmis gezegenler",
		COMBATS_SEARCH_OPTIONS : "Arama Parametreleri",
		COMBATS_SEARCH : "Aramak",
		COMBATS_RESET : "Sıfırlamak",
		COMBATS_COORDINATES : "Koordinatlar",
		COMBATS_INVALID_GALAXY_ENTERED : "Invalid Galaxy entered",
		COMBATS_INVALID_SYSTEM_ENTERED : "Invalid System entered",
		COMBATS_INVALID_PLANET_ENTERED : "Invalid Planet entered",
		COMBATS_GALAXY_FROM_TO : "Galaxy",
		COMBATS_SYSTEM_FROM_TO : "System",
		COMBATS_PLANET_FROM_TO : "Planet",
		COMBATS_APPLY : "Apply",
		COMBATS_COMBAT_SUMMARY : "Combat report summary",
		COMBATS_DOWNLOAD_CSV : "Download as CSV file",
		REPORT_ARCHIVE_TITLE : "Report archive",
		REPORT_ARCHIVE_COORDINATES : "Coordinates",
		REPORT_ARCHIVE_SCANTIME : "Scan time",
		REPORT_ARCHIVE_DELETE : "Delete these entries",
		REPORT_ARCHIVE_CONFIRM_DELETE : "Do you really want to delete these entries?",
		REPORT_ARCHIVE_GALAXY : "Galaxy",
		REPORT_ARCHIVE_SYSTEM : "System",
		REPORT_ARCHIVE_PLANET : "Planet",
		REPORT_ARCHIVE_MOON : "Moon",
		REPORT_ARCHIVE_DETAILS : "Details",
		REPORT_ARCHIVE_RESOURCES : "Saatlik Hammadde",
		REPORT_ARCHIVE_HEADER_RESOURCES : "Hammadde",
		REPORT_ARCHIVE_DETAILS_FOR : "Report archive for &1 [&2] (&3)",
		REPORT_ARCHIVE_FLEET_CARGO : "Fleet cargo capacity",
		REPORT_ARCHIVE_IRAK_RANGE : "Interplanetary Missiles range",
		REPORT_ARCHIVE_CHART_TYPE : "Chart type",
		INSTALL_TITLE : "Galaxytool installation for version",
		INSTALL_PROGRESS : "Overall progress",
		INSTALL_STEP : "Step",
		INSTALL_CONTINUE : "Continue",
		INSTALL_VALIDATE : "Validate",
		INSTALL_STEP1 : "Welcome",
		INSTALL_STEP2 : "Writeable check",
		INSTALL_STEP3 : "Database settings",
		INSTALL_STEP4 : "OGame settings",
		INSTALL_STEP5 : "Galaxytool settings",
		INSTALL_STEP6 : "Admin password",
		INSTALL_STEP7 : "Install Galaxytool",
		INSTALL_STEP8 : "Finalize install",
		INSTALL_FILE_DELETE_CHECK : "Please delete install.php and update.php from your webserver.",
		INSTALL_STEP1_PHP_FAILED : "Your PHP version &1 is not working with this Galaxytool version",
		INSTALL_STEP1_FOPEN_FAILED : "Your PHP version does not allow to open webpages with FOPEN() command. This is required to consume the OGame API.",
		INSTALL_STEP1_WELCOME : "Welcome to the installation wizard of the Galaxytool. You will be guided through the installation of the Galaxytool.",
		INSTALL_STEP2_DESCRIPTION : "Make sure your config.php and attributes.php files have write permissions enabled.",
		INSTALL_STEP2_DESCRIPTION2 : "If you don't know, how to achieve this, please take a look here: &1",
		INSTALL_STEP2_FILE_NOT_WRITEABLE : "File is not writeable",
		INSTALL_STEP3_SERVER : "Database server",
		INSTALL_STEP3_USERNAME : "Kullanıcı Adı",
		INSTALL_STEP3_PASSWORD : "Şifre",
		INSTALL_STEP3_DBNAME : "Database name",
		INSTALL_STEP3_PREFIX : "Tablename prefix",
		INSTALL_STEP3_ENTER_PREFIX : "E.g. mytool_",
		INSTALL_STEP3_ENTER_SERVER : "Enter the server address. Contact your system admin if necessary. Usually the correct value is localhost.",
		INSTALL_STEP3_ENTER_USERNAME : "Enter the username for database access",
		INSTALL_STEP3_ENTER_PASSWORD : "Enter the password for database access",
		INSTALL_STEP3_ENTER_DBNAME : "Enter the database name which shall be used for installation (must exist)",
		INSTALL_STEP3_CONNECT_FAILED : "Could not establish connection to database server",
		INSTALL_STEP3_DB_FAILED : "Database &1 not found",
		INSTALL_STEP3_MYSQL_VERSION_FAILED : "MySQL version &1 is not working with this Galaxytool version",
		INSTALL_STEP4_URL : "OGame URL",
		OGAME_URL_DETAILS : "Please enter any URL you see when you are logged on to OGame. Based on that URL the tool will derive the OGame API address which can be used to fill data into the Galaxytool without the Galaxytoolbar. This API was introduced with OGame version 4.1.",
		INSTALL_STEP4_UNIVERSE : "OGame Universe",
		INSTALL_STEP4_DEF_TO_DEBRIS : "Defense to debris",
		INSTALL_STEP4_DEBRIS_RATE : "Debris rate",
		INSTALL_STEP4_SPEED_RATE : "Speed rate",
		INSTALL_STEP4_ENTER_UNIVERSE : "Enter your OGame universe name or number (case sensitive).",
		INSTALL_STEP4_UNIVERSE_MISSING : "You must define your universe",
		INSTALL_STEP4_ENTER_URL : "Enter your OGame universe address",
		INSTALL_STEP4_URL_MISSING : "You must define your OGame address",
		INSTALL_STEP4_URL_CHECK_FAILED : "Could not find OGame API at &1",
		INSTALL_STEP4_GETSETTINGS : "Fetch settings",
		INSTALL_STEP5_TOOLNAME : "Galaxytool name",
		INSTALL_STEP5_ENTER_TOOLNAME : "This is the name which will be shown at logon page to identify your Galaxytool",
		INSTALL_STEP5_LANGUAGE : "Default language",
		INSTALL_STEP5_EMAIL_TO : "Email To",
		INSTALL_STEP5_ENTER_EMAIL_TO : "Enter the email address where you would like to receive notifications about registrations",
		INSTALL_STEP5_EMAIL_FROM : "Email From",
		INSTALL_STEP5_ENTER_EMAIL_FROM : "This email address is shown as REPLY for all mails sent from the Galaxytool",
		INSTALL_STEP5_USE_PHPMAILER : "Use PHPMailer",
		INSTALL_STEP5_MAXSHOUTS : "Maximum number of shoutbox entries",
		INSTALL_STEP5_ENTER_USE_PHPMAILER : "Use PHPMailer if your server does not support sending emails by default",
		INSTALL_PHPMAILER_HOST : "SMPT Host",
		INSTALL_PHPMAILER_HOST_EXAMPLE : "e.g. smtp.provider.com",
		INSTALL_PHPMAILER_USER : "SMPT Username",
		INSTALL_PHPMAILER_USER_EXAMPLE : "e.g. user@provider.dcom",
		INSTALL_PHPMAILER_PASS : "SMPT password",
		INSTALL_PHPMAILER_SECURE : "Authentification method (e.g. ssl)",
		INSTALL_PHPMAILER_PORT : "SMTP Port",
		INSTALL_STEP6_INTRO : "Please define a password for the <strong>admin</strong> account which you have to use for your first logon to the Galaxytool after the installation.",
		INSTALL_STEP7_CONFIG : "Configuration file created",
		INSTALL_STEP7_CONFIG_FAILED : "Configuration file not created",
		INSTALL_STEP7_ATTRIBUTES : "Attributes file created",
		INSTALL_STEP7_ATTRIBUTES_FAILED : "Attributes file not created",
		INSTALL_STEP7_CREATED_TABLES : "Database tables created",
		INSTALL_STEP8_INTRO : "You have successfully installed the Galaxytool!",
		INSTALL_STEP8_LOAD_DATA : "Downloading OGame data ...",
		INSTALL_STEP8_LOAD_DATA_FINISHED : "Download of OGame data finished",
		INSTALL_STEP8_DELETE_FILE : "You should now delete the installation files install.php and update.php from your webserver.",
		INSTALL_STEP8_LOGON : "Please logon with the <strong>admin</strong> user and the password you defined earlier.",
		UPDATE_START : "Starting update to version &1",
		UPDATE_STEP_DONE : "Done",
		UPDATE_TITLE : "Galaxytool update for version",
		UPDATE_STEP1_WELCOME : "Welcome to the update wizard of the Galaxytool. You will be guided through the update of the Galaxytool.",
		UPDATE_STEP1_BACKUP_FILES : "As a first step, make a backup of your <strong>config</strong> folder! You will have to replace the configuration content in case of errors.",
		UPDATE_STEP1_BACKUP_DB : "Then make a <a href=\"http://www.ehow.com/how_2036600_create-database-php.html\">backup</a> of your database.",
		UPDATE_STEP1_PROCEED : "Once the backups have been done, you can proceed with your update.",
		UPDATE_STEP1 : "Welcome",
		UPDATE_STEP2 : "Galaxytool settings",
		UPDATE_STEP2_OLD_VERSION : "Previous Galaxytool version",
		UPDATE_STEP3 : "Update Galaxytool",
		UPDATE_STEP3_UPDATE_RUNNING : "Update running, please wait...",
		UPDATE_STEP4 : "Finalize Update",
		UPDATE_STEP4_INTRO : "You have successfully updated the Galaxytool!",
		UPDATE_STEP4_UPDATE_DONE : "Update steps performed.",
		UPDATE_FAILED : "Update failed.",
		GALAXYTOOL_DUMMY_TEXT : "dummy"
	})
);