define(
	({
		REPORT_WHEN : "le",
		RESOURCES_ON : "Ressources sur",
		PLAYER_BANNED : "b",
		PLAYER_VACATION_MODE : "v",
		PLAYER_NOOB : "d",
		PLAYER_INACTIVE : "i",
		PLAYER_LONG_INACTIVE : "I",
		PLAYER_OUTLAW : "o",
		L_USERNAME : "Nom d'utilisateur",
		L_PASSWORD : "Mot de passe",
		L_LOGINFAILURE : "Le nom d'utilisateur ou le mot de passe est invalide, ou votre compte n'est pas encore activé.",
		L_TOKENFAILURE : "Votre logon key est invalide, ou votre compte n'est pas encore activé.",
		L_LOGINTEXT : "Veuillez vous identifier.",
		L_LANGUAGE : "langues disponibles:",
		L_TIMEOUT : "Votre session a expiré!",
		L_REGISTER : "S'enregistrer",
		L_PWLOST : "Mot de passe oublié ?",
		INDEX_TITLE : "Vue générale",
		INDEX_INFO : "Informations",
		INDEX_ENTRIES : "Nombre total de systèmes",
		INDEX_ENTRIES_LASTWEEK : "Nouveaux systèmes de la semaine dernière",
		INDEX_ENTRIES_TO_OLD : "Systèmes ayant plus d'un mois",
		INDEX_REGISTERED_USERS : "Utilisateurs enregistrés",
		INDEX_PAGEFORWARD : "Si votre navigateur ne vous redirige pas automatiquement, cliquez ici.",
		INDEX_NOTICES : "Notes",
		INDEX_PLAYERS : "Statistiques de Joueur",
		INDEX_ALLIES : "Statistiques de l'Alliance",
		INDEX_REPORTS : "Rapports",
		INDEX_VERSION : "Dernière version téléchargeable",
		INDEX_LATEST_VERSION : "Aucune nouvelle version disponible",
		INDEX_SHOUTBOX : "Messages",
		INDEX_NOENTRY : "Aucun message pour l'instant",
		INDEX_COMMENT : "Votre message",
		INDEX_INSERT : "Envoyer",
		INDEX_UMOD : "Joueur en Mode vacances",
		INDEX_NO_MOONS : "Nombre de lunes",
		INDEX_NO_EMPTY_SYSTEMS : "Nombre de systèmes vides",
		INDEX_NO_FULL_SYSTEMS : "Nombre de systèmes pleins",
		INDEX_NO_TARGETS : "Nombre de cibles possibles",
		INDEX_USERINFO : "Utilisateurs",
		INDEX_ONLINE : "En ligne actuellement",
		INDEX_TODAY : "Connectés aujourd'hui",
		INDEX_ALL : "Nombre total de connexions",
		GENERAL_LOAD_FORM : "Charger les données des formulaires",
		GENERAL_SAVE_FORM : "Enregistrer les données des formulaires",
		GENERAL_SAVE_AS_TEXT : "Enregistrer sous",
		GENERAL_SAVE : "Enregistrer",
		INDEX_USERMANAGEMENT : "Activation en attente",
		INDEX_NEEDADMIN : "Comptes à activer",
		INDEX_NEEDEMAIL : "Comptes invalides",
		INDEX_TOOLBAR_INFO : "Information du plugin Galaxytool",
		INDEX_TOOLBAR_URL : "URL Galaxytool",
		INDEX_TOOLBAR_VERSION_REQUIRED : "Version du plugin Galaxytool requise",
		INDEX_TOOLBAR_INSTALL_GUIDE : "Guide d'installation du plugin",
		INDEX_TOOLBAR_TOKEN : "Clé de connexion",
		INDEX_TOOLBAR_NEW_TOKEN : "Obtenir une nouvelle clé",
		INDEX_PLAYERS_WITH_N_PLANETS : "Joueur avec plus de &1 planètes",
		INDEX_GETTING_STARTED : "Premiers pas avec Galaxytool",
		INDEX_GETTING_STARTED1 : "Bienvenu sur le serveur Galaxytool!",
		INDEX_GETTING_STARTED2 : "Galaxytool va vous aider à analyser ce qui se passe sur votre univers &1",
		INDEX_GETTING_STARTED3 : "Avant de pouvoir analyser des données, il faut les insérer à la base. Pour cela, vous devez utiliser un plugin pour votre navigateur internet comme &1 pour Firefox.",
		INDEX_GETTING_STARTED4 : "Après l'installation, il vous suffit de naviguer sur vos pages Ogame. Une petite fenêtre apparaîtra dès qu'une information est envoyée vers le serveur.",
		INDEX_GETTING_STARTED5 : "Une fois que le plugin aura inséré des données dans votre Galaxytool, vous pourrez chercher la position des colonies d'un joueur, combien il en possède, s'il existe des rapports les concernant ainsi que leurs activités.",
		INDEX_GETTING_STARTED6 : "Mais Galaxytool vous permet aussi d'analyser votre progression en la comparant avec d'autres joueurs ou d'analyser vos rapports de combat et ainsi voir dans quelle mesure vous avez raidé ces derniers jours ou semaines.",
		INDEX_GETTING_WIKIPAGE : "Galaxytool possède bien d'autres fonctionnalités.",
		INDEX_GETTING_WIKIPAGE2 : "Regardez sur le Wiki.",
		INDEX_GETTING_BOARD : "Vous pouvez utilisez le forum pour le feedback et les suggestions :",
		INDEX_GETTING_CHAT1 : "Ou rejoignez nous sur le tchat :",
		INDEX_GETTING_CHAT2 : "Nous ne sommes pas connectés 24/7 mais nous y passons la plupart de notre temps libre donc soyez patient.",
		INDEX_CLOSE : "Fermer",
		INDEX_LOGIN : "Login",
		GENERAL_REQUIRED_FIELDS : "Vous devez remplir tous les champs",
		INDEX_MESSAGES : "Messages",
		INDEX_EXAMPLE : "Exemple",
		INDEX_INVALID_DATA : "Données invalides",
		GENERAL_COLUMN_HIDE_TITLE : "Gérer les colonnes",
		GENERAL_COLUMN_HIDE_INFO : "Selectionnez les colonnes que vous voulez voir dans le tableau.",
		GENERAL_ENTRIES_DELETED : "&1 entrées supprimées",
		GENERAL_APPLY : "Appliquer",
		STARTPAGE_GALAXYTOOL_DESCR : "<em>Galaxytool</em> est un outil pour le jeu par navigateur OGame.",
		GENERAL_OVERWRITE : "Supprimer les doublons",
		GENERAL_OVERWRITE_QUESTION : "Remplacer ?",
		INDEX_OWN_LOGINS : "Vos connexions",
		GENERAL_OPEN_IN_NEW_WINDOW : "Ouvrir le lien dans une nouvelle fenêtre",
		GENERAL_UNIT_OF_MEASURE_DAYS : "Days",
		PROGRAM_NAME : "OGame Galaxytool",
		SHORTNAME : "Galaxytool",
		BACK_INDEX : "Retour à la page principale",
		UNIVERSE : "Univers",
		MENU_INFO_LINKS : "Information",
		MENU_PAGE : "Vue générale",
		MENU_DB_SEARCH : "Rechercher dans la BDD",
		MENU_DB_NOTICES : "Rechercher dans les Notes",
		MENU_DB_REPORTS : "Rechercher dans les Rapports",
		MENU_GALAXYVIEW : "Voir les Galaxies",
		MENU_STATISTICS : "Statistiques",
		MENU_ALLYHISTORY : "Historique d'alliance",
		MENU_FLEET_MOVEMENTS : "Activités de flotte",
		MENU_COMBAT_REPORTS : "Rapports de combat",
		MENU_MESSAGES : "Messages privés",
		MENU_OPTION_LINKS : "Options",
		MENU_DB_REFRESH : "Inssérer dans la BDD",
		MENU_NOTICES : "Notes",
		MENU_DB_STATUS : "État de la BDD",
		MENU_USEROPTIONS : "Gestion des Utilisateurs",
		MENU_USEROPTIONS2 : "Options des Utilisateurs",
		MENU_USEROPTIONS3 : "Informations sur les Utilisateurs",
		MENU_ADMIN : "Administration",
		MENU_LOGOUT : "Déconnexion",
		MENU_STUFF : "Divers",
		MENU_FORUM_THREAD : "Forum de Galaxytool",
		MENU_DOWNLOADPAGE : "Téléchargement",
		MENU_LANGUAGE : "Langue",
		MENU_HELP : "Aide",
		MENU_TOOLOPTIONS : "Galaxytool Options",
		PARSER_INFO1 : " a été inséré dans la BDD",
		PARSER_ERROR1 : "Erreur pendant l'insertion des coordonnées suivantes:",
		PARSER_ERROR2 : "Impossible de trouver la BDD!",
		PARSER_ERROR3 : "Impossible de trouver le serveur de la BDD!",
		PARSER_WRONG_UNIVERSE : "Mauvais univers - actuel : \"&1\" attendu: \"&2\"",
		SHOW_TITLE : "OGame Galaxytool - Rechercher dans la BDD",
		SHOW_SEARCH : "Rechercher dans la BDD",
		SHOW_ALLYSYMBOL : "TAG Alliance",
		SHOW_PLAYERNAME : "Nom du Joueur",
		SHOW_MOONS : "Seulement les Planètes avec une lune",
		SHOW_NOTICES : "Seulement les Planètes annotées",
		SHOW_COLONIES : "Seulement les Planètes à coloniser",
		SHOW_YES : "Oui",
		SHOW_NO : "Non",
		SHOW_SEARCHRANGE : "Portée",
		SHOW_SEARCH_IN : "Rechercher dans la Galaxie",
		SHOW_FROM_SYSTEM : "du Système",
		SHOW_FROM_PLANET : "de la Position",
		SHOW_TO : "à",
		SHOW_DESCRIPTION : "Vous pouvez utiliser le caractère joker * pour les noms de joueur ou d'alliance. Ainsi vous pourrez trouver tous les joueurs avec &quot;nom&quot; dans leur nom. Remplissez uniquement les champs que vous voulez spécifier.",
		SHOW_SORT_BY : "Ordre de tri",
		SHOW_GALASYSTEM : "Galaxie/Système",
		SHOW_ALLYNAME : "Alliance",
		SHOW_SEARCHBUTTON : "Rechercher",
		SHOW_ADDRESS : "Coordonnées",
		SHOW_ALLYSORT : "Alliance",
		SHOW_PLANET : "Planète",
		SHOW_STATUS : "Statut",
		SHOW_CURRENTNESS : "Actualisé le",
		SHOW_PLAYER_STATUS : "Statut",
		SHOW_PLAYER_STATUS1 : "tout",
		SHOW_PLAYER_STATUS2 : "cibles potentielles",
		SHOW_PLAYER_STATUS3 : "inactif",
		SHOW_HITS : "Résultats",
		SHOW_OF : "sur",
		SHOW_ASC : "croissant",
		SHOW_DESC : "décroissant",
		SHOW_RESULTS : "Résultats par page",
		SHOW_MOON : "Lune",
		SHOW_UKMOONSIZE : "inconnue",
		SHOW_DF : "Débris",
		SHOW_DF_LONG : "Champ de débris",
		SHOW_METAL : "M",
		SHOW_METAL_LONG : "Métal",
		SHOW_CRYSTAL : "C",
		SHOW_CRYSTAL_LONG : "Cristal",
		SHOW_BOTH : "les deux",
		SHOW_AT_LEAST : "(au moins)",
		SHOW_DATE : "Date",
		SHOW_DATE_0 : "peu importe",
		SHOW_DATE_1 : "avant le",
		SHOW_DATE_2 : "après le",
		SHOW_RANK : "Classement",
		SHOW_FRANK : "Classement des Flottes",
		SHOW_MEMBERS : "Membres",
		SHOW_NOTRANKED : "Pas dans le top 1500.",
		SHOW_NOTICERES : "Notes",
		SHOW_REPORTS : "Seulement les planètes avec rapport(s)",
		SHOW_REPORTS_SHORT : "Rapports",
		SHOW_NOTHING : "Aucun résultat n'a été trouvé",
		SHOW_ALLIANCE_STATUS : "Statut de l'alliance",
		SHOW_NO_STATUS : "Pas de statut",
		SHOW_NAP : "PNA",
		SHOW_ALLIED : "Allié",
		SHOW_WAR : "en Guerre",
		SHOW_BOYCOTT : "Boycott",
		SHOW_NEUTRAL : "Neutre",
		SHOW_OWN : "Propre Alliance",
		SHOW_WING : "Wing",
		SHOW_EXT_OPTIONS1 : "Afficher plus d'options sur la portée, le classement, la date ou les champs de débris.",
		SHOW_EXT_OPTIONS2 : "Afficher plus d'options sur les colonies, les lunes, les rapports, les notes, les statuts de joueur ou diplomatiques.",
		SHOW_EXT_OPTIONS3 : "Afficher plus d'options sur le tri des résultats.",
		SHOW_EXTENDED : "Recherche avancée",
		SHOW_MOON_SELECTION : "Planète lunée",
		SHOW_REPORT_SELECTION : "Planète avec un rapport",
		SHOW_FILTER_BY : "Exclure de la liste",
		SHOW_FILTER_NONE : "aucune",
		SHOW_PLAYERS_WITHOUT_PROGRESS : "Show players without score changes within the last few days",
		STATUS_TITLE : "OGame Galaxytool - État de la BDD",
		STATUS_DB_STATUS : "État de la BDD",
		STATUS_COLOR : "Couleur",
		STATUS_AGE1 : "Donnée du jour.",
		STATUS_AGE2 : "Donnée de 2 - 4 jours.",
		STATUS_AGE3 : "Donnée de 4 - 7 jours.",
		STATUS_AGE4 : "Donnée de 1 - 2 semaines.",
		STATUS_AGE5 : "Donnée de 2 - 4 semaines.",
		STATUS_AGE6 : "Donnée vieille d'un mois !",
		STATUS_AGE7 : "Aucune donnée disponible.",
		STATUS_ON : "le",
		STYLES_COLOR1 : "Couleur1",
		STYLES_COLOR2 : "Couleur2",
		STYLES_COLOR3 : "Couleur3",
		STYLES_COLOR4 : "Couleur4",
		STYLES_COLOR5 : "Couleur5",
		STYLES_COLOR6 : "Couleur6",
		STYLES_COLOR7 : "Couleur7",
		STATUS_DB_LEGEND : "Légende",
		STATUS_GALAXY : "Galaxie",
		USER_TITLE : "OGame Galaxytool - Gestion des Utilisateurs",
		USER_NAMES : "Utilisateur",
		USER_ERROR : "Erreur",
		USER_NEWUSER : "Ajouter un Utilisateur",
		USER_OPTIONS : "Options",
		USER_USERNAME : "Nom d'utilisateur",
		USER_PASSWORD : "Mot de passe",
		USER_PASSWORD_CONFIRM : "Confirmer le mot de passe",
		USER_GALAXY : "Galaxie",
		USER_SEARCH : "Recherche",
		USER_INSERT : "Insertion",
		USER_DELETE : "Suppression",
		USER_DELETE_ENTRY : "Voulez-vous supprimer cet utilisateur: ",
		USER_STATUS : "Voir les stats",
		USER_STYLES : "Modifier disposition",
		USER_SUBMIT : "Envoyer",
		USER_RESET : "Réinitialiser",
		USER_YES : "Oui",
		USER_NO : "Non",
		USER_STYLEPATH : "Chemin vers styles.css",
		USER_PROBES : "Affichage/soumission de rapports d'espionnage",
		USER_EMAIL : "Email",
		USER_ERROR1 : "Mauvais mot de passe ou email invalide.",
		USER_ERROR2 : "Email invalide.",
		USER_INGAME : "Nom Ingame",
		USER_ALLYTAG : "TAG d'Alliance",
		USER_ALLYHISTORY : "Historique d'alliance",
		USER_DIPLOMATIC : "Diplomatie",
		USER_STATSPAGE : "Nombre d'entrées sur la page de statistiques",
		USER_LINKS : "Liens",
		USER_LINKS2 : "Format:<br>texte;url<br>texte2;url2<br>texte3;url3",
		USER_EXPORT_TITLE : "Exporter les couleurs (BB Codes)",
		USER_BB_COORDINATES : "Coordonnées",
		USER_BB_MOON : "Lune",
		USER_BB_DEBRIS : "Champ de débris",
		USER_BB_ALLY : "Nom d'alliance",
		USER_BB_ALLYDETAILS : "Détails de l'alliance",
		USER_BB_PLAYERNAME : "Nom du joueur",
		USER_BB_BANNED : "Banni",
		USER_BB_VACATION : "Mmode vacances",
		USER_BB_NOOB : "Débutant",
		USER_BB_INACTIVE : "Inactif 7 jours",
		USER_BB_LONGINACTIVE : "Inactif 28 jours",
		USER_DELETION : "Suprimer",
		USER_FLEETINFO : "Activités de flotte",
		USER_ACTIVITIES : "Activités du joueur",
		USER_MAINTENANCE : "Entretien du Galaxytool",
		USER_MANAGEMENT : "Gestion des Utilisateurs",
		USER_DELETE_MY_COMBAT_REPORTS : "Supprimer mes rapports de combat",
		USER_DELETE_MY_MESSAGES : "Supprimer mes messages",
		USER_DELETE_MY_FLEETMOVES : "Supprimer mes mouvements de flottes",
		USER_DELETE_MY_COMBAT_REPORTS_LIMITED : "Supprimer mes rapports de combats vieux de &1 jours",
		USER_DELETE_MY_MESSAGES_LIMITED : "Supprimer mes messages vieux de &1 jours",
		USER_TABLE_ENTRIES : "Résultats par page",
		USER_EXISTS : "L'utilisateur existe déjà",
		USER_BB_OUTLAW : "Hors la loi",
		USER_INVALID_URL : "L'URL &1 semble invalide - L'URL sera ignoré",
		VIEW_TITLE : "OGame Galaxytool - Détails des Galaxies",
		VIEW_NODATA : "Pas de données.",
		VIEW_GALAXY : "Galaxie",
		VIEW_SYSTEM : "Système solaire",
		VIEW_POSITION : "Pos.",
		VIEW_PLANET : "Planète",
		VIEW_MOON : "Lune",
		VIEW_TF : "Débris",
		VIEW_PLAYER : "Joueur",
		VIEW_PLAYER_ADD : "(Classement / Statut)",
		VIEW_ALLY : "Alliance",
		VIEW_ALLY_ADD : "(Classement / Membre)",
		VIEW_METAL : "M",
		VIEW_CRYSTAL : "C",
		VIEW_COLONISED : "planètes colonisées",
		VIEW_UKMOONSIZE : "inconnu",
		VIEW_BACK : "retour",
		VIEW_NOTICE : "Notes",
		VIEW_REPORTS : "Rapports",
		VIEW_MOONPHALANX : "Les lunes suivantes peuvent scanner ce système",
		VIEW_NOMOONS : "Pas de lune trouvée",
		VIEW_IRAKS : "Les planètes suivantes peuvent atteindre ce système avec des missiles interplanétaires",
		VIEW_NOIRAKS : "Pas de missile interplanétaire trouvé",
		VIEW_MOON_DESTROY_CHANCE : "Chances de détruire la lune",
		VIEW_CHANCE_WITH_ONE : "Chances avec une EDLM",
		VIEW_CHANCE_WITH_N : "Chances avec ",
		VIEW_DEATH_STARS : "EDLM",
		VIEW_DS_DESTROY_CHANCE : "Chances de perdre la/les EDLM",
		VIEW_TOP : "Top",
		VIEW_GO : "go",
		VIEW_DIAMETER : "Diamètre",
		PW_TITLE : "OGame Galaxytool - Changement de mot de passe",
		OLD_PASSWORD : "Ancien mot de passe",
		NEW_PASSWORD : "Nouveau mot de passe",
		CONFIRM_NEW_PASSWORD : "Confirmer le mot de passe",
		PW_MISMATCH : "Les mots de passe que vous avez entrés sont différents!",
		PW_ERROR : "L'ancien mot de passe est incorrect!",
		UPDATE_DONE : "Changement effectué.",
		TIMEZONE_OFFSET : "Différence d'horaire avec ce serveur",
		DELETE_ACCOUNT : "Supprimer ce compte",
		DELETE_ACCOUNT_SAFETY_REQUEST : "Etes vous sûr de vouloir supprimer votre compte?",
		CH_PASSWD_AUTHORIZATION : "Autorisations",
		CH_PASSWD_ADMIN : "Administrateur",
		TIMEZONE_OGAME_OFFSET : "Différence d'horaire avec le serveur OGame",
		CH_PASSWD_USER_LANGUAGE : "Langue à la prochaine connexion",
		CH_PASSWD_USER_LANGUAGE_NO_CHANGE : "Pas de changement",
		CH_PASSWD_EXPAND : "Déplié",
		CH_PASSWD_COLLAPSE : "Réduit",
		CH_PASSWD_HIDDEN : "Caché",
		CH_PASSWD_GETTING_STARTED : "Premiers pas ",
		CH_PASSWD_PLUGIN : "Informations du plugin Galaxytool ",
		NOTICE_TITLE : "OGame Galaxytool - Notes",
		NOTICE_HEADER : "Éditer une note",
		NOTICE_HEADER2 : "Éditer ses propres notes",
		NOTICE_PUBLIC : "Accessible aux autres ?",
		NOTICE_YES : "oui",
		NOTICE_NO : "non",
		NOTICE_TEXT : "Note",
		NOTICE_SAVE : "Sauvegarder",
		NOTICE_DELETED : "Note supprimée",
		NOTICE_SAVED : "Note sauvegardée",
		NOTICE_RESULTS : "Tous les résultats",
		NOTICE_USER : "Utilisateur",
		NOTICE_DATE : "Date",
		NOTICE_EDIT : "Éditer",
		NOTICE_DELETE : "Supprimer",
		NOTICE_NEW : "Créer une note",
		NOTICE_NOTPUBLIC : "Note non publique",
		NOTICE_ALL : "toutes",
		NOTICE_NONE : "aucune",
		NOTICE_SEARCH : "Rechercher dans les Notes",
		NOTICE_SEARCH_SHORT : "Rechercher",
		NOTICE_HITS : "Résultats",
		NOTICE_SHOWRESULTS : "Résultats par page",
		NOTICE_OF : "sur",
		NOTICE_NOTHING : "Aucun résultat n'a été trouvé",
		NOTICE_CHARS : "Caractères",
		NOTICE_PLAYERNAME : "Joueur",
		NOTICE_SHOWALL : "Afficher toutes les notes",
		REPORTS_TITLE : "OGame Galaxytool - Rapports d'espionnage",
		REPORTS_RESOURCES : "Ressources",
		REPORTS_FLEET : "Flottes",
		REPORTS_DEFENCE : "Défense",
		REPORTS_BUILDINGS : "Bâtiments",
		REPORTS_TECHNOLOGY : "Recherche",
		REPORTS_MOON : "Lune",
		REPORTS_SEARCH : "Rechercher dans les rapports d'espionnage",
		REPORTS_SEARCH_SHORT : "Rechercher",
		REPORTS_HITS : "Résultats",
		REPORTS_NOTHING : "Aucun résultat n'a été trouvé",
		REPORTS_ADDRESS : "Coordonnées",
		REPORTS_CURRENTNESS : "Actualisé le",
		REPORTS_PLAYERNAME : "Joueur",
		REPORTS_ALLY : "Alliance",
		REPORTS_VIEW : "voir le Rapport",
		REPORTS_SEARCH_IN : "Rechercher dans la Galaxie",
		REPORTS_FROM_SYSTEM : "du Système",
		REPORTS_TO : "à",
		REPORTS_DELETE : "supprimer",
		REPORTS_DELETED : "Rapport supprimé",
		REPORTS_RESULTS : "Résultats par page",
		REPORTS_OF : "sur",
		REPORTS_DATE : "Date",
		REPORTS_DATE_0 : "peu importe",
		REPORTS_DATE_1 : "moins récente que",
		REPORTS_DATE_2 : "plus récente que",
		REPORTS_NOTICES : "Notes",
		REPORTS_AT_LEAST_RESOURCES : "Ressources ( au moins )",
		REPORTS_SEARCH_EXTENDED : "Recherche étendue",
		REPORTS_FLEET_RESIS : "Flotte - points",
		REPORTS_DEFENCE_RESIS : "Défense - points",
		REPORTS_ALL_RESIS : "Sommes des points",
		REPORTS_TECHS : "Technologies",
		REPORTS_UNKNOWN_ENTRIES : "Entrées inconnues",
		REPORTS_PARTLY_INSERTED : "Inséré partiellement",
		REPORTS_FOR_ALL_RES : "Pour toute les ressources",
		REPORTS_FOR_TF : "Pour le champs de débris",
		REPORTS_KT : "Petits transporteurs",
		REPORTS_GT : "Grands transporteurs",
		REPORTS_SS : "Vaisseaux de bataille",
		REPORTS_REC : "Recycleur",
		REPORTS_RAIDABLE : "Seulement des cibles attaquables",
		REPORTS_ALL_RESOURCES : "toutes les ressources",
		REPORTS_STUFF : "Divers",
		REPORTS_SPEEDSIM : "Simuler avec Speedsim",
		REPORTS_DRAGOSIM : "Simuler avec Dragosim",
		REPORTS_STATUS : "Statut",
		REPORTS_ERROR : "Une erreur s'est produite",
		REPORTS_OWN_REPORTS : "Seulement mes rapports",
		REPORTS_UPLOAD_BY : "Rapport téléchargé par",
		REPORTS_DEPTH : "Rapports d'espionnages approfondis",
		REPORTS_FLEET_SCORE : "Nombre de vaisseaux",
		REPORTS_DEFENCE_SCORE : "Nombre de défense",
		REPORTS_HOURS : "heures",
		REPORTS_MAX_RESULTS_HIT : "Plus de &1 entrées correspondent à votre demande. Seuls les &1 résultats sont affichés. Ajustez votre recherche pour avoir moins de réusltat.",
		REPORTS_OSIMULATE : "Simulater avec OSimulate",
		REPORTS_SHOW_ONLY : "Montrer uniquement ",
		REPORTS_SHOW_PLANETS : "Planètes",
		REPORTS_SHOW_MOONS : "Lunes",
		REPORTS_OWNER : "Rapports de ",
		STATS_TITLE : "OGame Galaxytool - Statistiques",
		STATS_TBLHEAD : "Statistiques",
		STATS_RANK : "Place",
		STATS_PLAYERNAME : "Joueur",
		STATS_ALLYNAME : "Alliance",
		STATS_SCORE : "Points",
		STATS_FLEET : "Vaisseaux",
		STATS_RESEARCH : "Recherche",
		STATS_MEMBERS : "Membres",
		STATS_STATUS : "Statut",
		STATS_NOTHING : "pas de Statut",
		STATS_NAP : "PNA",
		STATS_ALLIED : "Allié",
		STATS_WAR : "en Guerre",
		STATS_BOYCOTT : "Boycott",
		STATS_NEUTRAL : "Neutre",
		STATS_OWN : "Propre Allié",
		STATS_WING : "Wing",
		STATS_UPDATE : "Données de",
		STATS_PLAYERSTATS : "Joueurs",
		STATS_ALLYSTATS : "Alliances",
		STATS_DELETE : "Voulez-vous supprimer cette entrée?",
		STATS_CONFIRM_DELETE : "Voulez-vous vraiment supprimer ce joueur?",
		STATS_CHANGE_PLAYER_STATUS : "Statut du joueur",
		STATS_CHANGE_ALLIANCE_STATUS : "Statut",
		STATS_CHANGE_ALLIANCE_STATUS_HINT : "Tous les membres de cette alliance auront le statut choisi. Tous les statuts définis aupravant seront supprimés. Vous pourrez à nouveau changer les statuts individuels des joueurs après.",
		STATS_UNKNOWN : "Pas de Statut",
		STATS_DETAILS : "Details pour",
		STATS_PLAYERSTATUS : "Statut",
		STATS_IGNORE_STATUS : "tout",
		STATS_ACTIVE : "actif/active",
		STATS_INACTIVE : "Inactif 7 jours",
		STATS_BANNED : "Banni",
		STATS_VACATION : "Mmode vacances",
		STATS_NOOB : "Débutant",
		STATS_YES : "Oui",
		STATS_NO : "Seulement les Planètes annotées",
		STATS_SEARCH : "Recherche",
		STATS_SHOW_GRAPH : "Montrer la distribution des points",
		STATS_LONG_INACTIVE : "Inactif 28 jours",
		STATS_STANDARD : "Classement général",
		STATS_MILITARY : "Points militaires",
		STATS_ECONOMY : "Points économiques",
		STATS_HONOUR : "Points honorifiques",
		STATS_MILITARY_BUILD : "Points militaires construits",
		STATS_MILITARY_DESTROYED : "Points militaires  détruits",
		STATS_MILITARY_LOST : "Points militaires perdus",
		REGISTER_REGISTRATE : "S'enregistrer",
		REGISTER_LOGINNAME : "Nom d'utilisateur",
		REGISTER_PASSWORD : "Mot de passe",
		REGISTER_PASSWORD_CONFIRM : "Confirmer le mot de passe",
		REGISTER_EMAIL : "Email",
		REGISTER_INGAME : "Nom Ingame",
		REGISTER_ALLYTAG : "TAG Alliance",
		REGISTER_EMAILVERIFICATION : "Vérification de l'adresse email",
		REGISTER_EMAILTEXT : "Pour valider votre inscription à galaxytool, veuillez vous rendre à la page suivante.",
		REGISTER_ERROR1 : "Ce nom d'utilisateur est déjà utilisé.",
		REGISTER_ERROR2 : "Erreur lors de l'envoi de l'email. Veuillez contacter un administateur.",
		REGISTER_ERROR3 : "Erreur lors de l'accès à la BDD!",
		REGISTER_INFO1 : "Votre compte a été crée.",
		REGISTER_INFO2 : "Veuillez utiliser le lien qui vous a été envoyé par email pour confirmer votre inscription.",
		REGISTER_INFO3 : "Inscription confirmée. Votre administrateur doit maintenant activer votre compte.",
		REGISTER_BUTTON : "Retour à l'accueil",
		REGISTER_NEW_SUBJECT : "Un nouvel utilisateur s'est enregistré dans galaxytool",
		REGISTER_NEW_MAILTEXT : "Un nouvel utilisateur s'est enregistré.",
		REGISTER_BACK : "Retour à la première page",
		REGISTER_MISSING_FIELDS : "Entrer tous les champs exigés",
		REGISTER_ERROR4 : "E-mail invalide.",
		REGISTER_ERROR5 : "Mots de passe différents.",
		REGISTER_PWS : "Sécurité",
		REGISTER_PWS0 : "très faible",
		REGISTER_PWS1 : "faible",
		REGISTER_PWS2 : "bonne",
		REGISTER_PWS3 : "forte",
		REGISTER_PWS4 : "très forte",
		REGISTER_EMAIL_USED : "E-mail déjà utilisé",
		LOSTPW_TITLE : "Mot de passe perdu",
		LOSTPW_INFO2 : "Un nouveau mot de passe a été généré et envoyé à votre adresse email.",
		LOSTPW_BUTTON1 : "recevoir nouveau mot de passe",
		LOSTPW_BUTTON2 : "Retour à l'acceuil",
		LOSTPW_LOGINNAME : "Nom d'utilisateur",
		LOSTPW_EMAIL : "Email",
		LOSTPW_ERROR1 : "Erreur lors de l'accès à la BDD!",
		LOSTPW_ERROR2 : "Aucun compte ne correspond à votre demande!",
		LOSTPW_ERROR3 : "Erreur lors de l'envoi de l'email. Veuillez contacter un administateur.",
		LOSTPW_EMAIL_SUBJECT : "Votre nouveau mot de passe",
		LOSTPW_EMAIL_TEXT1 : "Voici vos nouvelles informations de connexion à galaxytool",
		LOSTPW_EMAIL_TEXT2 : "Nom d'utilisateur",
		LOSTPW_EMAIL_TEXT3 : "Mot de passe",
		LOSTPW_INFO1 : "Un message de confirmation de réinitialisation de mot de passe vous a été envoyé.",
		LOSTPW_CONFIRM_RESET_SUBJECT : "Mot de passe oublié ?",
		LOSTPW_CONFIRM_RESET_MESSAGE : "Bonjour,\n\nVous avez demander à réinitialiser votre mot de passe. Pour créer un nouveau mot de passe, cliquez sur le lien suivant :",
		USERINFO_TITLE : "OGame Galaxytool - Informations sur les Utilisateurs",
		USERINFO_NAMES : "Tous les utilisateurs de cet outil",
		USERINFO_DETAIL : "Informations détaillées sur",
		USERINFO_ERROR1 : "Pas d'utilisateur avec cet ID!",
		USERINFO_USERNAME : "Nom d'utilisateur",
		USERINFO_INGAME : "Nom Ingame",
		USERINFO_EMAIL : "Email",
		USERINFO_ALLYTAG : "Alliance",
		USERINFO_STYLEPATH : "Skin",
		USERINFO_STATUS : "État",
		USERINFO_ACTIVATE : "Activer le joueur",
		USERINFO_LOGINS : "Nombre de connexions",
		USERINFO_LASTLOGIN : "Dernière connexion",
		USERINFO_DATA : "Nombre de Systèmes ajoutés",
		USERINFO_NODATA : "Cet utilisateur n'a rien ajouté pour le moment!",
		USERINFO_GALAXY : "Galaxie",
		USERINFO_SYSTEMS : "Nombre de Systèmes",
		USERINFO_IP : "Adresse IP",
		USERINFO_LOGINTIME : "Connexion",
		USERINFO_NOLOGIN : "Le joueur ne s'est jamais connecté.",
		USERINFO_LAST_GALAXYUPDATE : "Dernier ajout à la BDD",
		USERINFO_LAST_PUBLIC_NOTICE : "Dernière note publique",
		USERINFO_LAST_PRIVATE_NOTICE : "Dernière note privée",
		USERINFO_NUMBEROF_PUBLIC_NOTICE : "Nombre de notes publiques",
		USERINFO_NUMBEROF_PRIVATE_NOTICE : "Nombre de notes privées",
		USERINFO_ACTIVATED : "Compte activé",
		USERINFO_ACTIVATIONTEXT : "L'administrateur galaxytool a activé votre compte.\n\nAmusez vous bien avec Galaxytool!",
		USERINFO_LAST_SUBMIT : "Dernière insersion",
		ALLYHISTORY_TITLE : "OGame Galaxietool - Historique d'alliance",
		ALLYHISTORY_TBLHEAD : "Historique",
		ALLYHISTORY_PLAYERNAME : "Joueur",
		ALLYHISTORY_ALLYNAME : "Alliance",
		ALLYHISTORY_LASTMONTH : "Dernier mois",
		ALLYHISTORY_ALL_DATA : "Toutes les informations disponibles",
		ALLYHISTORY_SHOW : "Afficher les statistiques",
		ALLYHISTORY_TIMESPAN : "Période",
		ALLYHISTORY_PROGESS : "Progression",
		ALLYHISTORY_SCORE : "Points",
		ALLYHISTORY_FSCORE : "Points de vaisseaux",
		ALLYHISTORY_RSCORE : "Points de recherche",
		ALLYHISTORY_MEMBER : "Membres",
		ALLYHISTORY_NOTHING : "Aucune entrée trouvée",
		ALLYHISTORY_DETAILS : "Détails",
		ALLYHISTORY_SHOW_ADDRESS : "Coordonnées",
		ALLYHISTORY_ESCORE : "Points économiques",
		ALLYHISTORY_MSCORE : "Points militaires",
		DETAILEDINFO_PLAYERINFO_TITLE : "Informations sur le joueur",
		DETAILEDINFO_ALLYINFO_TITLE : "Informations sur l'alliance",
		DETAILEDINFO_PLAYERINFO_TBLHEAD : "Informations détaillées sur le joueur",
		DETAILEDINFO_ALLYINFO_TBLHEAD : "Informations détaillées sur l'alliance",
		DETAILEDINFO_NO_ALLIANCE : "Aucune",
		DETAILEDINFO_SCORE : "Classement points",
		DETAILEDINFO_FLEET : "Classement vaisseaux",
		DETAILEDINFO_RESEARCH : "Classement recherche",
		DETAILEDINFO_RANK : "Place",
		DETAILEDINFO_POINTS : "Points",
		DETAILEDINFO_KNOWN_PLANETS : "Planètes connues",
		DETAILEDINFO_MOONS : "Lunes connues",
		DETAILEDINFO_PHALANX_AREA : "Zone de phalange",
		DETAILEDINFO_NO_PHALANX_AREA : "Aucune phalange trouvée",
		DETAILEDINFO_NOTICES : "Notes",
		DETAILEDINFO_NO_NOTICES : "Aucune note trouvée",
		DETAILEDINFO_PREVIOUS_ALLIANCES : "Alliances précédentes",
		DETAILEDINFO_RESOURCES_PER_HOUR : "Ressources par heure",
		DETAILEDINFO_RESOURCES_PER_DAY : "Resources par jour",
		DETAILEDINFO_RESOURCES_PER_WEEK : "Resources par semaine",
		DETAILEDINFO_RESOURCES_PER_MONTH : "Resources par mois (30 jours)",
		DETAILEDINFO_METAL : "Métal",
		DETAILEDINFO_CRYSTAL : "Cristal",
		DETAILEDINFO_DEUTERIUM : "Deutérium",
		DETAILEDINFO_UNKNOWN : "inconnu",
		DETAILEDINFO_SCORE_DISTRIBUTION : "Distribution des points",
		DETAILEDINFO_GENERAL : "Détails",
		DETAILEDINFO_MEMBERS : "Membres",
		DETAILEDINFO_GRAPHS : "Graphiques",
		DETAILEDINFO_RESOURCES : "Ressources",
		DETAILEDINFO_FLEET_TAB : "Flottes",
		DETAILEDINFO_TECH : "Recherche",
		DETAILEDINFO_FLEET_DETAIL : "Somme / (moyenne des joueurs) parmi tous les rapports disponibles",
		DETAILEDINFO_TECH_DETAIL : "Moyenne de tous les informations sur les joueurs disponibles",
		DETAILEDINFO_PLANET_TAB : "Planètes",
		DETAILEDINFO_MOON_TAB : "Lunes",
		DETAILEDINFO_ACTIVITIES : "Activités",
		DETAILEDINFO_NODATA : "Pas de données.",
		DETAILEDINFO_ACTIVITY_DESCRIPTION : "Montrer activités de &1 trouvés pour:",
		DETAILEDINFO_GALAXYVIEWS : "Vues de galaxies",
		DETAILEDINFO_SCANS : "Action d'espionnage",
		DETAILEDINFO_MESSAGES : "Messages privés",
		DETAILEDINFO_COMBATS : "Rapports de combat",
		DETAILEDINFO_ALLYPAGE : "Vue Alliance",
		DETAILEDINFO_MANUAL : "Insertion manuelle",
		DETAILEDINFO_START : "Début",
		DETAILEDINFO_TO : "jusqu'a",
		DETAILEDINFO_TODAY : "Aujourd'hui",
		DETAILEDINFO_DATA_RESTRICTION : "Limité jusqu'a:",
		DETAILEDINFO_WEEKDAY_WEEKEND : "Weekend",
		DETAILEDINFO_WEEKDAY_WORKINGDAY : "Jour de la semaine",
		DETAILEDINFO_WEEKDAY_MONDAY : "Lundi",
		DETAILEDINFO_WEEKDAY_TUESDAY : "Mardi",
		DETAILEDINFO_WEEKDAY_WEDNESDAY : "Mercredi",
		DETAILEDINFO_WEEKDAY_THURSDAY : "Jeudi",
		DETAILEDINFO_WEEKDAY_FRIDAY : "Vendredi",
		DETAILEDINFO_WEEKDAY_SATURDAY : "Samedi",
		DETAILEDINFO_WEEKDAY_SUNDAY : "Dimanche",
		DETAILEDINFO_WEEKDAY_SHORTLENGTH : 3,
		DETAILEDINFO_PLAYER_CURRENTLY_ACTIVE : "Le joueur est active en ce moment",
		DETAILEDINFO_PLAYER_MESSAGES : "messages disponible du joueur",
		DETAILEDINFO_SHOW : "montrer",
		DETAILEDINFO_NONE : "aucun message disponibles",
		DETAILEDINFO_ENTER_MANUALLY : "Entrez l'activité de ce joueur",
		DETAILEDINFO_PLAYER_SEEN_ON : "Le joueur était connecté à",
		DETAILEDINFO_INSERT : "Insérer",
		DETAILEDINFO_OGAME_SERVERTIMES : "Remarque: Les dates et les temps sont relatives au serveur OGame !",
		DETAILEDINFO_DAY_VIEW : "Vue sur 24 heures",
		DETAILEDINFO_WEEK_VIEW : "Vue sur une semaine",
		DETAILEDINFO_HOME_PLANET : "Planète mère",
		DETAILEDINFO_PLANETNAME : "Nom",
		DETAILEDINFO_DEFENCE_SCORE : "Points dans la défense",
		DETAILEDINFO_DEFENCE_SCORE_TOOLTIP : "Défense = Militaire - Points totaux + Recherches + Economie.<br/>Ces statistiques doivent être à jour pour avoir un sens!",
		DETAILEDINFO_SCORE_PER_SHIP : "Points par vaisseau",
		DETAILEDINFO_SHIPS : "Vaisseaux",
		DETAILEDINFO_DATE_IN_FUTURE : "Ne proposez pas des dates futures!",
		ADMIN_TITLE : "Administration du Galaxytool",
		ADMIN_DISCLAMER : "Attention: Utilisez ces scripts à vos propres risques! La plupart effacent les données.",
		ADMIN_INCONSISTENCIES : "Incohérences dans la base de données",
		ADMIN_PLANETS : "Planètes en position 0 ou supérieures à 15",
		ADMIN_GALAXIES : "Effacer galaxies supérieures à &1 ",
		ADMIN_PLAYERS : "Effacer joueurs sans OGame playerid - peut mener à dupliquer des entrées de joueurs",
		ADMIN_REPORTS : "Effacer des rapports où aucune planète n'existe",
		ADMIN_MISC : "Faits divers",
		ADMIN_RESET : "Remettre à zéro Galaxytool (seuls les utilisateurs et les tables d'ip ne sont pas effacés)",
		ADMIN_OLD_PLAYERS : "Effacer entrées de joueurs plus anciennes que &1 jours",
		ADMIN_OLD_REPORTS : "Effacer rapports plus anciens que &1 jours",
		ADMIN_LOADING : "Ne pas fermer cette fenêtre tant que la page se charge.",
		ADMIN_STATUS : "Status de vos requêtes",
		ADMIN_SELECTION : "Au moins une entrée doit être sélectionnée",
		ADMIN_SAFETY : "Etes-vous sûr de vouloir lancer ce(s) script(s) ",
		ADMIN_DONE : "fait",
		ADMIN_NOTBD : "rien à faire",
		ADMIN_OLD_GALAXIES : "Effacer des vues de galaxie qui sont plus anciennes que &1 jours",
		ADMIN_UNUSED_PLAYERS : "Effacer les joueurs qui n'ont aucune entrée dans la partie galaxie",
		ADMIN_OLD_ACTIVITIES : "Supprimer l'activité des joueurs de plus de &1 jours",
		ADMIN_OLD_COMBATS : "Supprimer les rapports de combat vieux de &1 jours",
		ADMIN_OLD_INGAME_MSG : "Supprimer les messages vieux de &1 jours",
		ADMIN_OGAME_API : "Charger les données public d'OGame sur le serveur Galaxytool",
		ADMIN_OGAME_ALL_DATA : "Toutes les informations disponibles",
		ADMIN_OGAME_GALAXY_DATA : "Voir les Galaxies",
		ADMIN_OGAME_STATISTICS_DATA : "Statistiques",
		ERRORPAGE_PAGEFORWARD : "Cliquer ici si votre navigateur ne soutient pas l'expédition de la page",
		ERRORPAGE_PERMISSION_DENIED : "Vous n'avez pas l'autorisation d'entrer sur cette page. Cliquer pour revenir en arrière",
		FLEETS_TITLE : "Activités de flotte",
		FLEETS_ACTUAL_FLEETS : "Flottes en mouvement",
		FLEETS_YES : "Oui",
		FLEETS_NO : "Seulement les Planètes annotées",
		FLEETS_DETAILS : "Détails",
		FLEETS_MISSION_EXPEDITION : "Expédition",
		FLEETS_MISSION_COLONIZATION : "Coloniser",
		FLEETS_MISSION_RECYCLE : "Exploitage",
		FLEETS_MISSION_TRANSPORT : "Transport",
		FLEETS_MISSION_DEPLOYMENT : "Déploiement",
		FLEETS_MISSION_ESPIONAGE : "Espionnage",
		FLEETS_MISSION_ACS_DEFEND : "Stationnement",
		FLEETS_MISSION_ATTACK : "Attaquer",
		FLEETS_MISSION_ACS_ATTACK : "Attaque groupée",
		FLEETS_MISSION_MOON_DESTRUCTION : "Destruction de lune",
		FLEETS_MISSION_MISSILE_ATTACK : "Attaque de missile",
		FLEETS_NO_DATA : "Pas d'informations utiles",
		FLEETS_FLEET : "Flottes",
		FLEETS_ALL_FLEETS : "Montrer toutes les flottes",
		COMBAT_REPORT_OUDATED_GALAXYVIEW : "Vos systèmes galaxies sont trop vieux. Veuillez revisiter les systèmes origine de l'attaque et de la cible!",
		MESSAGES_TITLE : "OGame Galaxytool - Messages OGame",
		MESSAGES_PLAYERNAME : "Nom joueur",
		MESSAGES_SUBJECT : "Objet",
		MESSAGES_DATE : "Date",
		MESSAGES_FILTER : "Filtre",
		MESSAGES_DELETE : "Effacer message",
		MESSAGES_PUBLISH_DETAIL : "Ajouter le contenu du message a la note du joueur..",
		MESSAGES_PUBLISH_HEADER : "&sender a envoyé un message à &recipient le &date:\n\n &message",
		MESSAGES_PLAYER_FILTER : "Messages pour le joueur:",
		MESSAGES_CONTENT : "Contenu",
		COMBATS_TITLE : "OGame Galaxytool - Rapports de combat",
		COMBATS_ATTACKER : "Attaquant",
		COMBATS_DEFENDER : "Defenseur",
		COMBATS_DATE : "Date",
		COMBATS_OWNER : "Propriétaire",
		COMBATS_WINNER : "Gagnant",
		COMBATS_COMBATREPORT : "Rapport de combat",
		COMBATS_COMBAT_AT : "Combat sur",
		COMBATS_LOST_UNITS : "Unités perdues",
		COMBATS_LOOT : "Butin",
		COMBATS_DEBRIS : "Débris",
		COMBATS_AND : "et",
		COMBATS_PUBLISH : "Rendre ce rapport public",
		COMBATS_UNPUBLISH : "Rendre ce rapport privé",
		COMBATS_DELETE : "Supprimer le rapport",
		COMBATS_CHECK_ALL : "Sélectionner tout ",
		COMBATS_UNCHECK_ALL : "Désélectionner tout.",
		COMBATS_WITH_SELECTED : "Avec les sélectionnés",
		COMBATS_PUBLIC_REPORTS : "Rapports publics",
		COMBATS_YES : "Oui",
		COMBATS_NO : "Seulement les Planètes annotées",
		COMBATS_SEARCH_OPTIONS : "Options de recherche",
		COMBATS_SEARCH : "Chercher",
		COMBATS_RESET : "Mise à zéro",
		COMBATS_COORDINATES : "Coordonnées",
		COMBATS_INVALID_GALAXY_ENTERED : "Galaxie invalide",
		COMBATS_INVALID_SYSTEM_ENTERED : "System invalide",
		COMBATS_INVALID_PLANET_ENTERED : "Planète invalide",
		COMBATS_GALAXY_FROM_TO : "Galaxie",
		COMBATS_SYSTEM_FROM_TO : "Système",
		COMBATS_PLANET_FROM_TO : "Planète",
		COMBATS_APPLY : "Appliquer",
		COMBATS_COMBAT_SUMMARY : "Rapport de combat réduit",
		COMBATS_DOWNLOAD_CSV : "Télécharger en CSV",
		REPORT_ARCHIVE_TITLE : "Rapports archivés",
		REPORT_ARCHIVE_COORDINATES : "Coordonnées",
		REPORT_ARCHIVE_SCANTIME : "Date",
		REPORT_ARCHIVE_DELETE : "Supprimer ces entrées",
		REPORT_ARCHIVE_CONFIRM_DELETE : "Êtes vous sûr de vouloir supprimer ces entrées ?",
		REPORT_ARCHIVE_GALAXY : "Galaxie",
		REPORT_ARCHIVE_SYSTEM : "Système",
		REPORT_ARCHIVE_PLANET : "Planète",
		REPORT_ARCHIVE_MOON : "Lune",
		REPORT_ARCHIVE_DETAILS : "Détails",
		REPORT_ARCHIVE_RESOURCES : "Ressources par heure",
		REPORT_ARCHIVE_HEADER_RESOURCES : "Ressources",
		REPORT_ARCHIVE_DETAILS_FOR : "Rapport archivé de &1 [&2] (&3)",
		REPORT_ARCHIVE_FLEET_CARGO : "Capacité de fret",
		REPORT_ARCHIVE_IRAK_RANGE : "Portée des missiles interplanétaires",
		REPORT_ARCHIVE_CHART_TYPE : "Diagramme",
		INSTALL_TITLE : "Version de Galaxytool",
		INSTALL_PROGRESS : "Progression de l'installation",
		INSTALL_STEP : "Etape",
		INSTALL_CONTINUE : "Continuer",
		INSTALL_VALIDATE : "Valider",
		INSTALL_STEP1 : "Bienvenu",
		INSTALL_STEP2 : "Test d'écriture",
		INSTALL_STEP3 : "Configuration de la base de données",
		INSTALL_STEP4 : "Paramètre d'Ogame",
		INSTALL_STEP5 : "Configuration de Galaxytool",
		INSTALL_STEP6 : "Mot de passe administrateur",
		INSTALL_STEP7 : "Installer Galaxytool",
		INSTALL_STEP8 : "Terminer l'installation",
		INSTALL_FILE_DELETE_CHECK : "Veuillez supprimer install.php et update.php de votre serveur.",
		INSTALL_STEP1_PHP_FAILED : "Votre version &1 de PHP ne fonctionne pas avec cette version de Galaxytool",
		INSTALL_STEP1_FOPEN_FAILED : "Votre version de PHP ne permet pas l'utilisation de FOPEN(). Cette fonction est nécessaire pour utiliser l'API d'Ogame.",
		INSTALL_STEP1_WELCOME : "Bienvenu sur l'assistant d'installation de Galaxytool. Vous allez être guidé tout le long de l'installation.",
		INSTALL_STEP2_DESCRIPTION : "Vérifiez que les fichiers config.php et attributes.php sont accessibles en écriture.",
		INSTALL_STEP2_DESCRIPTION2 : "Si vous ne savez pas comment faire, suivez ce lien : &1",
		INSTALL_STEP2_FILE_NOT_WRITEABLE : "Les fichiers ne sont pas accessible en écriture",
		INSTALL_STEP3_SERVER : "Serveur BDD",
		INSTALL_STEP3_USERNAME : "Nom d'utilisateur",
		INSTALL_STEP3_PASSWORD : "Mot de passe",
		INSTALL_STEP3_DBNAME : "Nom de la BDD",
		INSTALL_STEP3_PREFIX : "Préfixe",
		INSTALL_STEP3_ENTER_PREFIX : "Ex: mytool_",
		INSTALL_STEP3_ENTER_SERVER : "Entrez l'adresse du serveur. Contacter l'administrateur système si besoin. En général, la valeur correct est localhost.",
		INSTALL_STEP3_ENTER_USERNAME : "Entrez le nom d'utilisateur de la BDD",
		INSTALL_STEP3_ENTER_PASSWORD : "Entrez le mot de passe de la BD",
		INSTALL_STEP3_ENTER_DBNAME : "Entrez le nom de la BDD qui sera utilisé pour l'installation (doit exister)",
		INSTALL_STEP3_CONNECT_FAILED : "Echec de la connexion avec le serveur BDD",
		INSTALL_STEP3_DB_FAILED : "La BDD $1 n'existe pas.",
		INSTALL_STEP3_MYSQL_VERSION_FAILED : "MySQL version &1 ne fonctionne pas avec cette version de Galaxytool",
		INSTALL_STEP4_URL : "URL d'OGame",
		OGAME_URL_DETAILS : "Veuillez entrer l'URL d'une page Ogame quelconque après connexion. Galaxytool va utiliser cette url pour trouver l'URL de l'API d'Ogame afin de rajouter les informations publiques de votre serveur sans utiliser Galaxytoolbar. Cette API a été introduite avec la version 4.1 d'Ogame.",
		INSTALL_STEP4_UNIVERSE : "Univers d'OGame",
		INSTALL_STEP4_DEF_TO_DEBRIS : "Défense dans le champs de ruines",
		INSTALL_STEP4_DEBRIS_RATE : "Débris (%)",
		INSTALL_STEP4_SPEED_RATE : "Vitesse",
		INSTALL_STEP4_ENTER_UNIVERSE : "Entrez le nom ou numéro de votre univers Ogame (sensible à la casse).",
		INSTALL_STEP4_UNIVERSE_MISSING : "Vous devez définir l'univers",
		INSTALL_STEP4_ENTER_URL : "Entrez l'adresse de votre univers",
		INSTALL_STEP4_URL_MISSING : "Vous devez définir l'adresse de votre univers",
		INSTALL_STEP4_URL_CHECK_FAILED : "Impossible de trouver l'API à &1",
		INSTALL_STEP4_GETSETTINGS : "Fetch settings",
		INSTALL_STEP5_TOOLNAME : "Nom du Galaxytool",
		INSTALL_STEP5_ENTER_TOOLNAME : "Ceci est le nom qui sera affiché sur la page de connexion de Galaxytool",
		INSTALL_STEP5_LANGUAGE : "Langue par défaut",
		INSTALL_STEP5_EMAIL_TO : "Email à",
		INSTALL_STEP5_ENTER_EMAIL_TO : "Entrez l'adresse mail à laquelle vous souhaitez recevoir les notifications d'enregistrement",
		INSTALL_STEP5_EMAIL_FROM : "Email d'envoi",
		INSTALL_STEP5_ENTER_EMAIL_FROM : "Cette adresse sera considéré comme l'adresse émettrice pour tous les messages envoyés depuis Galaxytool",
		INSTALL_STEP5_USE_PHPMAILER : "Utiliser PHPMailer",
		INSTALL_STEP5_MAXSHOUTS : "Nombre maximal de messages dans la shoutbox",
		INSTALL_STEP5_ENTER_USE_PHPMAILER : "Utiliser PHPMailer si votre serveur ne supporte pas par défaut l'envoi de message ",
		INSTALL_PHPMAILER_HOST : "Hôte SMPT",
		INSTALL_PHPMAILER_HOST_EXAMPLE : "ex: smtp.provider.com",
		INSTALL_PHPMAILER_USER : "Utilisateur",
		INSTALL_PHPMAILER_USER_EXAMPLE : "ex: user@provider.dcom",
		INSTALL_PHPMAILER_PASS : "Mot de ",
		INSTALL_PHPMAILER_SECURE : "Authentification (ex: ssl)",
		INSTALL_PHPMAILER_PORT : "Port SMTP",
		INSTALL_STEP6_INTRO : "Veuillez définir un mot de passe pour le compte <strong>admin</strong> que vous devrez utiliser à la première connexion.",
		INSTALL_STEP7_CONFIG : "Fichier de configuration créé",
		INSTALL_STEP7_CONFIG_FAILED : "Fichier de configuration non créé",
		INSTALL_STEP7_ATTRIBUTES : "Fichier des attributs créé",
		INSTALL_STEP7_ATTRIBUTES_FAILED : "Fichier des attributs non créé",
		INSTALL_STEP7_CREATED_TABLES : "Tables de la BDD créées",
		INSTALL_STEP8_INTRO : "Vous avez installé Galaxytool!",
		INSTALL_STEP8_LOAD_DATA : "Téléchargement des données OGame ...",
		INSTALL_STEP8_LOAD_DATA_FINISHED : "Téléchargement des données OGame terminé",
		INSTALL_STEP8_DELETE_FILE : "Vous devriez supprimer les fichiers install.php et update.php de votre serveur.",
		INSTALL_STEP8_LOGON : "Veuillez vous connecter avec le compte <strong>admin</strong> et le mot de passe que vous avez défini plus tôt.",
		UPDATE_START : "Mise à jour vers la version &1",
		UPDATE_STEP_DONE : "Fait",
		UPDATE_TITLE : "Mise à jour de Galaxytool",
		UPDATE_STEP1_WELCOME : "Bienvenu sur l'assistant de mise à jour de Galaxytool. Vous allez être guider tout le long de la mise à jour.",
		UPDATE_STEP1_BACKUP_FILES : "Faites dans un premiers temps une sauvegarde de dossier <strong>config</strong>! Vous devrez restorer son contenu en cas d'erreur.",
		UPDATE_STEP1_BACKUP_DB : "Puis faites un <a href=\"http://www.ehow.com/how_2036600_create-database-php.html\">backup</a> de votre base de données.",
		UPDATE_STEP1_PROCEED : "Une fois ces sauvegardes réalisées, vous pouvez mettre à jour Galaxytool.",
		UPDATE_STEP1 : "Bienvenu",
		UPDATE_STEP2 : "Configuration de Galaxytool",
		UPDATE_STEP2_OLD_VERSION : "Version précédente de Galaxytool",
		UPDATE_STEP3 : "Mettre à jour Galaxytool",
		UPDATE_STEP3_UPDATE_RUNNING : "Mise à jour en cours, veuillez patienter...",
		UPDATE_STEP4 : "Terminer la mise à jour",
		UPDATE_STEP4_INTRO : "Galaxytool a été mis à jour !",
		UPDATE_STEP4_UPDATE_DONE : "Etapes de mise à jour réussis.",
		UPDATE_FAILED : "Echec de la mise à jour.",
		GALAXYTOOL_DUMMY_TEXT : "dummy"
	})
);