define("dojo/dom dojo/_base/array dojo/json dojo/i18n!./nls/galaxytool.js dojo/request dijit/registry ./MessageHandling dojo/domReady!".split(" "),function(k,t,u,r,q,e,p){function g(e){l=e}var l=null,m=[];g.prototype.showSaveScreen=function(){m=[];q.post("ajax/ajax_forms.php?type=get_save_ids&formID="+l,{handleAs:"json"}).then(function(h){t.forEach(h,function(a){null!==a&&m.push(a.save_id)});e.byId("SaveDialogContent").set("href","ajax/ajax_forms.php?type=save_UI&formID="+l);e.byId("SaveDialog").set("title",
r.GENERAL_SAVE_FORM);e.byId("SaveDialog").show()},function(e){console.log("Error:");console.log(e)})};g.prototype.showLoadScreen=function(){e.byId("SaveDialogContent").set("href","ajax/ajax_forms.php?type=load_UI&formID="+l);e.byId("SaveDialog").set("title",r.GENERAL_LOAD_FORM);e.byId("SaveDialog").show()};g.prototype.validateSaveScreen=function(){k.byId("formsave_button").style.display="none";k.byId("formsave_loading_icon").style.display="";var h=e.byId("save_id").get("value"),a=!1;if(!0!==e.byId("formsave_overwrite").get("checked"))for(var c=
0;c<m.length;c++)if(m[c]==h){a=!0;break}!1==a?this.saveFormData(h):(k.byId("formsave_overwrite_content").style.display="",k.byId("formsave_button").style.display="",k.byId("formsave_loading_icon").style.display="none")};g.prototype.saveFormData=function(h){var a,c,d=[];try{var f=k.byId(l);if(null==f)return alert("Wrong ID!"),!1;var b=f.getElementsByTagName("input");for(a=0;a<b.length;a++)if(!0!=b[a].hasAttribute("wairole")&&!0!=b[a].hasAttribute("readonly")&&"button"!=b[a].getAttribute("type"))if("radio"==
b[a].getAttribute("type"))!0==b[a].checked&&d.push([b[a].name,b[a].value,"checked"]);else if("checkbox"==b[a].getAttribute("type")){try{var g=e.byId(b[a].id).get("checked")}catch(q){g=!1}!0==b[a].checked||b[a].hasAttribute("value")&&!0==g?d.push([[b[a].id,b[a].name],"checked"]):d.push([[b[a].id,b[a].name],""])}else"submit"!=b[a].getAttribute("type")&&("userman1"==l?"id"!=b[a].name&&("username"!=b[a].name&&"ingameusername"!=b[a].name&&"email"!=b[a].name)&&d.push([[b[a].id,b[a].name],b[a].value]):d.push([[b[a].id,
b[a].name],b[a].value]));var m=f.getElementsByTagName("textarea");for(a=0;a<m.length;a++)d.push([[b[a].id,b[a].name],m[a].value]);var n=f.getElementsByTagName("select"),s;for(a=0;a<n.length;a++){s=n[a].getElementsByTagName("option");for(c=0;c<s.length;c++)!0==s[c].selected&&d.push([n[a].name,s[c].value])}var n=f.getElementsByTagName("table"),p;for(a=0;a<n.length;a++)p=n[a].getAttribute("class"),null!=p&&0<p.indexOf("dijitSelect")&&d.push([[n[a].id,""],e.byId(n[a].id).get("value")]);this.saveData(h,
d)}catch(r){console.log("error:"),console.log(r)}k.byId("formsave_overwrite_content").style.display="none";k.byId("formsave_button").style.display="";k.byId("formsave_loading_icon").style.display="none";e.byId("SaveDialog").hide()};g.prototype.loadFormData=function(h){var a;q.post("ajax/ajax_forms.php?type=load_data&formID="+l+"&save_id="+h,{handleAs:"json"}).then(function(c){null!=c.messages&&(new p(c,"../images")).showMessages();if(0!=c.form_content.length){c=c.form_content;for(var d=0;d<c.length;++d)try{var f=
c[d][0]instanceof Array?""!=c[d][0][0]?document.getElementById(c[d][0][0]):document.getElementsByName(c[d][0][1]):document.getElementsByName(c[d][0]);if(1==f.length)a=f[0];else if((f instanceof Array||f instanceof Object)&&1<f.length){for(var b=0;b<f.length;++b)if(a=f[b],"radio"==a.getAttribute("type"))if(a.value==c[d][1]&&"checked"==c[d][2])if(-1<a.className.indexOf("dijit"))e.byId(c[d][0]+""+a.value).set("checked",!0);else{var h=document.createAttribute("checked");a.setAttributeNode(h);a.checked=
!0}else a.checked=!1;else console.log("unexpected else path");continue}else a=f;if("SELECT"==a.nodeName)for(b=0;b<a.childNodes.length;++b)if(a.childNodes[b].value==c[d][1]){var g=document.createAttribute("selected");a.childNodes[b].setAttributeNode(g);a.childNodes[b].selected=!0}else a.childNodes[b].selected=!1;else if("TABLE"==a.nodeName)e.byId(a.id).set("value",c[d][1]);else if("radio"==a.getAttribute("type"))console.log("Radiobuttons must be handled via NAME but not ID");else if("checkbox"==a.getAttribute("type"))if("checked"==
c[d][1]){a.checked=!0;try{e.byId(a.id).set("checked",!0)}catch(k){}}else{a.checked=!1;try{e.byId(a.id).set("checked",!1)}catch(l){}}else a.value=c[d][1]}catch(m){}}e.byId("SaveDialog").hide()},function(a){console.log("Error:");console.log(a)})};g.prototype.deleteFormData=function(h){q.post("ajax/ajax_forms.php?type=delete_data&formID="+l+"&save_id="+h,{handleAs:"json"}).then(function(a){(new p(a,"../images")).showMessages();e.byId("SaveDialog").hide()},function(a){console.log("Error:");console.log(a)})};
g.prototype.saveData=function(e,a){q.post("ajax/ajax_forms.php?type=save_data&formID="+l+"&save_id="+e,{handleAs:"json",data:{form_content:u.stringify(a)}}).then(function(a){(new p(a.messages,"../images")).showMessages()},function(a){console.log("Error:");console.log(a)})};return g});
