define(
	({
		REPORT_WHEN : "",
		RESOURCES_ON : "Resursi na",
		PLAYER_BANNED : "k",
		PLAYER_VACATION_MODE : "o",
		PLAYER_NOOB : "s",
		PLAYER_INACTIVE : "i",
		PLAYER_LONG_INACTIVE : "I",
		PLAYER_OUTLAW : "o",
		L_USERNAME : "Korisnicko Ime",
		L_PASSWORD : "Šifra",
		L_LOGINFAILURE : "Korisnicko Ime ili šifra su pogrešni ili vaš account nije još aktiviran.",
		L_TOKENFAILURE : "Vaš pristupni ključ nije točan ili vaš račun još nije aktiviran",
		L_LOGINTEXT : "Molimo vas prijavite se.",
		L_LANGUAGE : "Dostupni jezici:",
		L_TIMEOUT : "Sesija je istekla!",
		L_REGISTER : "Registracija",
		L_PWLOST : "Zaboravljena Šifra",
		INDEX_TITLE : "Pregled",
		INDEX_INFO : "Informacije",
		INDEX_ENTRIES : "Broj svih sistema",
		INDEX_ENTRIES_LASTWEEK : "Novi sistemi od prošle sedmice",
		INDEX_ENTRIES_TO_OLD : "Sistemi stariji od mjesec dana",
		INDEX_REGISTERED_USERS : "Registrirani korisnici",
		INDEX_PAGEFORWARD : "Ako vaš browser ne podržava automatsko preusmjeravanje stranica molim vas kliknite ovdje.",
		INDEX_NOTICES : "Objave",
		INDEX_PLAYERS : "Statistike igraca",
		INDEX_ALLIES : "Statistike saveza",
		INDEX_REPORTS : "Izvještaji špijunaže",
		INDEX_VERSION : "Zadnja dostupna verzija za download",
		INDEX_SHOUTBOX : "Shoutbox",
		INDEX_NOUnos : "Nema trenutno poruka",
		INDEX_COMMENT : "Vaša poruka",
		INDEX_INSERT : "Unesi",
		INDEX_UMOD : "Igrac u modusu odustva",
		INDEX_LATEST_VERSION : "Nema novije dostupne verzije",
		INDEX_NO_MOONS : "Broj mjeseci",
		INDEX_NO_EMPTY_SYSTEMS : "Broj praznih sistema",
		INDEX_NO_FULL_SYSTEMS : "Broj potpuno punih sistema",
		INDEX_NO_TARGETS : "Broj mogucih meta",
		INDEX_USERINFO : "Broj Korisnika",
		INDEX_ONLINE : "Trenutno online",
		INDEX_TODAY : "Danas online",
		INDEX_ALL : "Ukupan broj prijava",
		GENERAL_LOAD_FORM : "Učitaj iz podataka",
		GENERAL_SAVE_FORM : "Spremi iz podataka",
		GENERAL_SAVE_AS_TEXT : "Spremi kao",
		GENERAL_SAVE : "Spremi",
		INDEX_USERMANAGEMENT : "Pregled aktivacije",
		INDEX_NEEDADMIN : "Otključaj račune",
		INDEX_NEEDEMAIL : "Nepotvrđeni računi",
		INDEX_TOOLBAR_INFO : "Informacije o Galaxytool pluginu",
		INDEX_TOOLBAR_URL : "Galaxytool URL",
		INDEX_TOOLBAR_VERSION_REQUIRED : "Zahtjeva Galaxytool plugin verziju najmanje ",
		INDEX_TOOLBAR_INSTALL_GUIDE : "Upute za instalaciju plugina",
		INDEX_TOOLBAR_TOKEN : "Pristupni ključ",
		INDEX_TOOLBAR_NEW_TOKEN : "Zatraži novi ključ",
		INDEX_PLAYERS_WITH_N_PLANETS : "Igrači sa više od &1 planeta",
		INDEX_GETTING_STARTED : "Započni sa korištenjem Galaxytoola",
		INDEX_GETTING_STARTED1 : "Dobrodošli na Galaxytool!",
		INDEX_GETTING_STARTED2 : "Galaxytool će vam pomoći da analizirate što se događa u vašem OGame univerzumu &1",
		INDEX_GETTING_STARTED3 : "Prije nego što možete analizirati podatke, morate ih prvo unijeti. Za to vam treba dodatak za browser kao &1 za Firefox.",
		INDEX_GETTING_STARTED4 : "Nakon instalacije plugina, prolazite kroz stranice OGamea kao i obično i vidjeti ćete mali statusni prozor kad god je nešto poslano na vaš Galaxytool.",
		INDEX_GETTING_STARTED5 : "Kada je plugin ubacio podatke u Galaxytool, možete početi analizirati gdje igrači imaju svoje kolonije, koliko kolonija imaju, koji reporti postoje ili kada su najviše aktivni.",
		INDEX_GETTING_STARTED6 : "Također će vam pomoći da analizirate vlastiti napredak kroz usporedbu sa drugin igračima ili kroz analizu vaših izvještaja o borbi možete pratiti koliko ste opljačkali zadnjih dana ili tjedana.",
		INDEX_GETTING_WIKIPAGE : "Postoji još mnogo mogućnosti unutar Galaxytoola.",
		INDEX_GETTING_WIKIPAGE2 : "Pregledajte ih na našoj wiki stranici.",
		INDEX_GETTING_BOARD : "Za vaša zapažanja i ideje možete korisititi naš forum:",
		INDEX_GETTING_CHAT1 : "Ili nas posjetiti na chatu:",
		INDEX_GETTING_CHAT2 : "Mi nismo online 24/7 ali provodimo puno slobodnog vremena tamo, pa budite strpljivi.",
		INDEX_CLOSE : "Close",
		INDEX_LOGIN : "Login",
		GENERAL_REQUIRED_FIELDS : "Please fill all required fields",
		INDEX_MESSAGES : "Messages",
		INDEX_EXAMPLE : "Example",
		INDEX_INVALID_DATA : "Invalid data",
		GENERAL_COLUMN_HIDE_TITLE : "Manage columns",
		GENERAL_COLUMN_HIDE_INFO : "Please select which columns you want to see in the table.",
		GENERAL_ENTRIES_DELETED : "&1 entries deleted",
		GENERAL_APPLY : "potvrdi",
		STARTPAGE_GALAXYTOOL_DESCR : "<em>Galaxytool</em> is a tool for the browser game OGame.",
		GENERAL_OVERWRITE : "Overwrite duplicate entry",
		GENERAL_OVERWRITE_QUESTION : "Overwrite?",
		INDEX_OWN_LOGINS : "Your logins",
		GENERAL_OPEN_IN_NEW_WINDOW : "Open Link in New Window",
		GENERAL_UNIT_OF_MEASURE_DAYS : "Days",
		PROGRAM_NAME : "OGame Galaxytool",
		SHORTNAME : "Galaxytool",
		BACK_INDEX : "Nazad na pocetnu stranicu",
		UNIVERSE : "Univerzum",
		MENU_INFO_LINKS : "Informacije",
		MENU_PAGE : "Pregled",
		MENU_DB_SEARCH : "Traži u bazi",
		MENU_DB_NOTICES : "Traži u objavama",
		MENU_DB_REPORTS : "Traži u izvještajima",
		MENU_GALAXYVIEW : "Pregled galaksije",
		MENU_STATISTICS : "Statistike",
		MENU_ALLYHISTORY : "Povijest Saveza",
		MENU_FLEET_MOVEMENTS : "Kretanja flote",
		MENU_COMBAT_REPORTS : "Izvještaji borbe",
		MENU_MESSAGES : "Poruke u igri",
		MENU_OPTION_LINKS : "Opcije",
		MENU_DB_REFRESH : "Ubaci u bazu",
		MENU_NOTICES : "Objave",
		MENU_DB_STATUS : "Stanje Baze",
		MENU_USEROPTIONS : "Upravljanje korisnicima",
		MENU_USEROPTIONS2 : "Opcije korisnika",
		MENU_USEROPTIONS3 : "Informacije o korisniku",
		MENU_ADMIN : "Administracija",
		MENU_LOGOUT : "Odjava",
		MENU_STUFF : "Ostalo",
		MENU_FORUM_THREAD : "Forum razvojnog tima",
		MENU_DOWNLOADPAGE : "Stranica za download",
		MENU_LANGUAGE : "Jezik",
		MENU_HELP : "Pomoc",
		MENU_TOOLOPTIONS : "Galaxytool Opcije",
		PARSER_INFO1 : " je ubaceno u bazu",
		PARSER_ERROR1 : "Greška prilikom ubacivanja ovih koordinata u bazu:",
		PARSER_ERROR2 : "Baza nije pronadena!",
		PARSER_ERROR3 : "Server baze nije pronaden!",
		PARSER_WRONG_UNIVERSE : "Krivi univerzum - stvarni: \"&1\"  očekivani: \"&2\"",
		SHOW_TITLE : "OGame Galaxytool - Stranica za pretragu",
		SHOW_SEARCH : "Traži u bazi",
		SHOW_ALLYSYMBOL : "Tag saveza",
		SHOW_PLAYERNAME : "Ime igraca",
		SHOW_MOONS : "Samo planete sa mjesecom",
		SHOW_NOTICES : "Samo planete sa objavama",
		SHOW_COLONIES : "Samo planete za kolonizaciju",
		SHOW_YES : "Da",
		SHOW_NO : "Ne",
		SHOW_SEARCHRANGE : "Domet",
		SHOW_SEARCH_IN : "Traži u galaksiji",
		SHOW_FROM_SYSTEM : "od sistema",
		SHOW_FROM_PLANET : "od pozicije planete",
		SHOW_TO : "do",
		SHOW_DESCRIPTION : "Možete koristiti * za imena igraca i saveza. <br />Popunite samo ona polja koja želite da specificarate.",
		SHOW_SORT_BY : "Sortiraj po ",
		SHOW_GALASYSTEM : "Galaksija/Sistem",
		SHOW_ALLYNAME : "Ime saveza",
		SHOW_SEARCHBUTTON : "Traži",
		SHOW_ADDRESS : "Koordiante",
		SHOW_ALLYSORT : "Savez",
		SHOW_PLANET : "Ime planete",
		SHOW_STATUS : "Status",
		SHOW_CURRENTNESS : "Starost",
		SHOW_PLAYER_STATUS : "Status igraca",
		SHOW_PLAYER_STATUS1 : "svi",
		SHOW_PLAYER_STATUS2 : "moguce mete",
		SHOW_PLAYER_STATUS3 : "inaktivni",
		SHOW_HITS : "Rezultata",
		SHOW_OF : "od",
		SHOW_ASC : "abecedni poredak",
		SHOW_DESC : "obrnuti abecedni poredak",
		SHOW_RESULTS : "Rezultata po stranici",
		SHOW_MOON : "Mjesec",
		SHOW_UKMOONSIZE : "nepoznato",
		SHOW_DF : "RU",
		SHOW_DF_LONG : "Ruševina",
		SHOW_METAL : "M",
		SHOW_METAL_LONG : "Metal",
		SHOW_CRYSTAL : "K",
		SHOW_CRYSTAL_LONG : "Kristal",
		SHOW_BOTH : "oboje zajedno",
		SHOW_AT_LEAST : "(najmanje)",
		SHOW_DATE : "Datum",
		SHOW_DATE_0 : "nije važno",
		SHOW_DATE_1 : "starije od",
		SHOW_DATE_2 : "novije od",
		SHOW_RANK : "Mjesto",
		SHOW_FRANK : "Mjesto Flote",
		SHOW_MEMBERS : "Clanovi",
		SHOW_NOTRANKED : "Nije u top 1500",
		SHOW_NOTICERES : "Objave",
		SHOW_REPORTS : "Samo planete sa izvještajima",
		SHOW_REPORTS_SHORT : "Izvještaji",
		SHOW_NOTHING : "Nema rezultata",
		SHOW_ALLIANCE_STATUS : "Status saveza",
		SHOW_NO_STATUS : "bez Statusa",
		SHOW_NAP : "NAP",
		SHOW_ALLIED : "Savezni",
		SHOW_WAR : "Rat",
		SHOW_BOYCOTT : "Bojkotirati",
		SHOW_NEUTRAL : "Neutralni",
		SHOW_OWN : "Vlastiti Savez",
		SHOW_WING : "Wing",
		SHOW_EXT_OPTIONS1 : "Prikazi vise opcija za traziti domet, rang, datum ili rusevine.",
		SHOW_EXT_OPTIONS2 : "Prikazi vise opcija za traziti kolonije, mjesece, izvjestaje, biljeske, statistike igraca ili diplomatski status.",
		SHOW_EXT_OPTIONS3 : "Prikazi vise opcija za traziti sortirano od pretrazivanih rezultata.",
		SHOW_EXTENDED : "advanced search",
		SHOW_MOON_SELECTION : "Planet with moon",
		SHOW_REPORT_SELECTION : "Planet with report",
		SHOW_FILTER_BY : "Exclude from the list",
		SHOW_FILTER_NONE : "nijedna",
		SHOW_PLAYERS_WITHOUT_PROGRESS : "Show players without score changes within the last few days",
		STATUS_TITLE : "OGame Galaxytool - Statusna stranica",
		STATUS_DB_STATUS : "Status baze",
		STATUS_COLOR : "Boja",
		STATUS_AGE1 : "Unos 1 dan star.",
		STATUS_AGE2 : "Unos 2 - 4 dana star.",
		STATUS_AGE3 : "Unos 4 - 7 dana star.",
		STATUS_AGE4 : "Unos 1 - 2 tjedna star.",
		STATUS_AGE5 : "Unos 2 - 4 tjedna star.",
		STATUS_AGE6 : "Unos stariji od 1 mjeseca!",
		STATUS_AGE7 : "Unos nije dostupan.",
		STATUS_ON : "ukljuceno",
		STYLES_COLOR1 : "Boja1",
		STYLES_COLOR2 : "Boja2",
		STYLES_COLOR3 : "Boja3",
		STYLES_COLOR4 : "Boja4",
		STYLES_COLOR5 : "Boja5",
		STYLES_COLOR6 : "Boja6",
		STYLES_COLOR7 : "Boja7",
		STATUS_DB_LEGEND : "Legenda",
		STATUS_GALAXY : "Pregled galaksije",
		USER_TITLE : "OGame Galaxytool - Upravljanje korisnicima",
		USER_NAMES : "Korisnik",
		USER_ERROR : "Greška",
		USER_NEWUSER : "Novi korisnik",
		USER_GALAXY : "Galaksija",
		USER_OPTIONS : "Opcije",
		USER_USERNAME : "Korisnicko Ime",
		USER_PASSWORD : "Šifra",
		USER_PASSWORD_CONFIRM : "Potvrdi šifru",
		USER_SEARCH : "Pretraga",
		USER_INSERT : "Unosi",
		USER_DELETE : "obriši",
		USER_DELETE_Unos : "Da li želite izbrisati korisnika: ",
		USER_STATUS : "Vidi statistiku",
		USER_STYLES : "Izmjeni izgled",
		USER_SUBMIT : "Pošalji",
		USER_RESET : "Poništi",
		USER_YES : "Da",
		USER_NO : "Ne",
		USER_STYLEPATH : "Putanja do styles.css",
		USER_PROBES : "Pregledaj/Pošalji Izvještaj Špijunaže",
		USER_EMAIL : "Email",
		USER_ERROR1 : "Šifra netocna ili je Email neispravan.",
		USER_ERROR2 : "Email neispravan.",
		USER_INGAME : "Ime u igri",
		USER_ALLYTAG : "Savez",
		USER_ALLYHISTORY : "Pregledaj/Pošalji Povijest Saveza",
		USER_DIPLOMATIC : "Promijeni Diplomatski Status",
		USER_STATSPAGE : "Broj unosa na statistici",
		USER_LINKS : "Linkovi",
		USER_LINKS2 : "Format:<br>text;url<br>text2;url2<br>text3;url3",
		USER_EXPORT_TITLE : "Izvezi boje (BB Kodove)",
		USER_BB_COORDINATES : "Koordinate",
		USER_BB_MOON : "Mjesec",
		USER_BB_DEBRIS : "Ruševine",
		USER_BB_ALLY : "Ime Saveza",
		USER_BB_ALLYDETAILS : "Detalji Saveza",
		USER_BB_PLAYERNAME : "Igrac",
		USER_BB_BANNED : "kažnjen",
		USER_BB_VACATION : "modus odsustva",
		USER_BB_NOOB : "noob",
		USER_BB_INACTIVE : "Inaktivan",
		USER_BB_LONGINACTIVE : "Dugo inaktivan",
		USER_DELETION : "Obriši",
		USER_FLEETINFO : "Kretanja flote",
		USER_ACTIVITIES : "Aktivnosti igrača",
		USER_MAINTENANCE : "Galaxytool održavanje",
		USER_MANAGEMENT : "Upravljanje korisnicima",
		USER_DELETE_MY_COMBAT_REPORTS : "Obriši moje izvještaje o borbi",
		USER_DELETE_MY_MESSAGES : "Obriši moje poruke",
		USER_DELETE_MY_FLEETMOVES : "Obriši moja kretanja flote",
		USER_DELETE_MY_COMBAT_REPORTS_LIMITED : "Izbriši moje izvještaje o borbi starije od &1 dana",
		USER_DELETE_MY_MESSAGES_LIMITED : "Izbriši moje poruke starije od &1 dana",
		USER_TABLE_ENTRIES : "Broj rezultata po stranici",
		USER_EXISTS : "User already exists",
		USER_BB_OUTLAW : "Outlaw",
		USER_INVALID_URL : "URL &1 seems to be invalid - URL will be ignored",
		VIEW_TITLE : "OGame Galaxytool - Detalji",
		VIEW_NODATA : "Podaci nisu dostupni.",
		VIEW_GALAXY : "Galaksija",
		VIEW_SYSTEM : "Solarni sistem",
		VIEW_POSITION : "Pos.",
		VIEW_PLANET : "Planeta.",
		VIEW_MOON : "Mjesec",
		VIEW_TF : "RU",
		VIEW_PLAYER : "Igrac",
		VIEW_PLAYER_ADD : "(Mjesto / Status)",
		VIEW_ALLY : "Savez",
		VIEW_ALLY_ADD : "(Mjesto / Clanova)",
		VIEW_METAL : "M",
		VIEW_CRYSTAL : "K",
		VIEW_COLONISED : "Planeta naseljena",
		VIEW_UKMOONSIZE : "nepoznato",
		VIEW_BACK : "nazad",
		VIEW_NOTICE : "Objave",
		VIEW_REPORTS : "Izvještaji",
		VIEW_MOONPHALANX : "Sljedeci mjeseci mogu skenirati ovaj sistem",
		VIEW_NOMOONS : "Nema Mjeseca",
		VIEW_IRAKS : "Sljdece planete mogu dosegnuti ovaj sistem sa Interplanetarnim Raketama",
		VIEW_NOIRAKS : "Nije pronadena ni jedna Interplanetarna raketa",
		VIEW_MOON_DESTROY_CHANCE : "Šansa za uništiti mjesec",
		VIEW_CHANCE_WITH_ONE : "Šansa sa jednom zvijezdom smrti",
		VIEW_CHANCE_WITH_N : "Šansa sa ",
		VIEW_DEATH_STARS : "zvijezda smrti",
		VIEW_DS_DESTROY_CHANCE : "Šanse za izgubiti zvijezdu(e) smrti",
		VIEW_TOP : "Top",
		VIEW_GO : "go",
		VIEW_DIAMETER : "Diameter",
		PW_TITLE : "OGame Galaxytool - promjena šifre",
		OLD_PASSWORD : "stara šifra",
		NEW_PASSWORD : "nova šifra",
		CONFIRM_NEW_PASSWORD : "potvrdi novu šifru",
		PW_MISMATCH : "Šifre se ne poklapaju!",
		PW_ERROR : "Stara šifra nije tocna!",
		UPDATE_DONE : "Update uspješan.",
		TIMEZONE_OFFSET : "Odstupanje vremenske zone prema serveru",
		DELETE_ACCOUNT : "Obriši ovaj Galaxytool račun",
		DELETE_ACCOUNT_SAFETY_REQUEST : "Želite li doista obrisati ovaj Galaxytool račun?",
		CH_PASSWD_AUTHORIZATION : "Dozvole",
		CH_PASSWD_ADMIN : "Admin",
		TIMEZONE_OGAME_OFFSET : "Odstupanje vremenske zone prema OGame serveru",
		CH_PASSWD_USER_LANGUAGE : "Promijeni na ovaj jezik nakon logiranja",
		CH_PASSWD_USER_LANGUAGE_NO_CHANGE : "Bez promijene",
		CH_PASSWD_EXPAND : "Prošireno",
		CH_PASSWD_COLLAPSE : "Stisnuto",
		CH_PASSWD_HIDDEN : "Skriveno",
		CH_PASSWD_GETTING_STARTED : "Pokaži upute nakon ulaska",
		CH_PASSWD_PLUGIN : "Pokaži informacije o pluginu nakon ulaska",
		NOTICE_TITLE : "OGame Galaxytool - Objave",
		NOTICE_HEADER : "izmjena objava",
		NOTICE_HEADER2 : "Izmjeni svoje objave",
		NOTICE_PUBLIC : "Dostupno drugima ?",
		NOTICE_YES : "da",
		NOTICE_NO : "ne",
		NOTICE_TEXT : "Tekst objave",
		NOTICE_SAVE : "Spasi",
		NOTICE_DELETED : "Unos obrisan",
		NOTICE_SAVED : "Unos spašen.",
		NOTICE_RESULTS : "Svi rezultati",
		NOTICE_USER : "Korisnik",
		NOTICE_DATE : "Datum",
		NOTICE_EDIT : "Izmjeni",
		NOTICE_DELETE : "Obriši",
		NOTICE_NEW : "Kreiraj novi unos",
		NOTICE_NOTPUBLIC : "Objava nije javna.",
		NOTICE_ALL : "sve",
		NOTICE_NONE : "nijedna",
		NOTICE_SEARCH : "Traži u objavama",
		NOTICE_SEARCH_SHORT : "Traži",
		NOTICE_HITS : "Rezultati",
		NOTICE_SHOWRESULTS : "Rezultata po stranici",
		NOTICE_OF : "od",
		NOTICE_NOTHING : "Ni jedan rezultat nije pronaden",
		NOTICE_CHARS : "Znakovi",
		NOTICE_PLAYERNAME : "Igrac",
		NOTICE_SHOWALL : "Prikaži sve objave",
		REPORTS_TITLE : "OGame Galaxytool - Izvještaj špijunaže",
		REPORTS_RESOURCES : "Resursi",
		REPORTS_FLEET : "Flote",
		REPORTS_DEFENCE : "Odbrana",
		REPORTS_BUILDINGS : "Zgrade",
		REPORTS_TECHNOLOGY : "Istraživanje",
		REPORTS_MOON : "Mjesec",
		REPORTS_SEARCH : "Traži u izvještajima špijunaže",
		REPORTS_SEARCH_SHORT : "Traži",
		REPORTS_HITS : "Rezultata",
		REPORTS_NOTHING : "Unos nije pronaden",
		REPORTS_ADDRESS : "Adresa",
		REPORTS_CURRENTNESS : "Starost",
		REPORTS_PLAYERNAME : "Ime igraca",
		REPORTS_ALLY : "Savez",
		REPORTS_VIEW : "Pogledaj Izvještaj",
		REPORTS_SEARCH_IN : "Traži u galaskiji",
		REPORTS_FROM_SYSTEM : "od sistema",
		REPORTS_TO : "do",
		REPORTS_DELETE : "obriši",
		REPORTS_DELETED : "Unos izbrisan",
		REPORTS_RESULTS : "Rezultata po stranici",
		REPORTS_OF : "od",
		REPORTS_DATE : "Datum",
		REPORTS_DATE_0 : "nije važno",
		REPORTS_DATE_1 : "starije od",
		REPORTS_DATE_2 : "novije od",
		REPORTS_NOTICES : "Objave",
		REPORTS_AT_LEAST_RESOURCES : "Resursi (barem)",
		REPORTS_SEARCH_EXTENDED : "Prošireno Pretraživanje",
		REPORTS_FLEET_RESIS : "Bodovi flote",
		REPORTS_DEFENCE_RESIS : "Bodovi odbrane",
		REPORTS_ALL_RESIS : "ukupno bodova",
		REPORTS_TECHS : "Tehnologije",
		REPORTS_UNKNOWN_ENTRIES : "nepoznati unosi",
		REPORTS_PARTLY_INSERTED : "djelomicno uneseno",
		REPORTS_FOR_ALL_RES : "za sve resurse",
		REPORTS_FOR_TF : "za ruševine",
		REPORTS_KT : "Mali transporter",
		REPORTS_GT : "Veliki transporter",
		REPORTS_SS : "Borbeni brodovi",
		REPORTS_REC : "Recikler",
		REPORTS_RAIDABLE : "Jedino mete za raid",
		REPORTS_ALL_RESOURCES : "svi Resursi",
		REPORTS_STUFF : "Ostalo",
		REPORTS_SPEEDSIM : "Simuliraj sa Speedsimom",
		REPORTS_DRAGOSIM : "Simuliraj sa Dragosim",
		REPORTS_STATUS : "Status",
		REPORTS_ERROR : "Greška",
		REPORTS_OWN_REPORTS : "Samo moji izvještaji",
		REPORTS_UPLOAD_BY : "Izvještaji koje je učitao",
		REPORTS_DEPTH : "Dubina izvještaja",
		REPORTS_FLEET_SCORE : "Bodovi flote",
		REPORTS_DEFENCE_SCORE : "Bodovi obrane",
		REPORTS_HOURS : "hours",
		REPORTS_MAX_RESULTS_HIT : "Your query returned more than &1 hits. Only the first &1 results are show. Please adjust your search request to get less results.",
		REPORTS_OSIMULATE : "Simulate with OSimulate",
		REPORTS_SHOW_ONLY : "Show only",
		REPORTS_SHOW_PLANETS : "Planeti",
		REPORTS_SHOW_MOONS : "Mjeseci",
		REPORTS_OWNER : "Reports owned by",
		STATS_TITLE : "OGame Galaxytool - Statistike",
		STATS_TBLHEAD : "Statistike",
		STATS_RANK : "Mjesto",
		STATS_PLAYERNAME : "Ime igraca",
		STATS_ALLYNAME : "Tag Saveza",
		STATS_SCORE : "Bodovi",
		STATS_FLEET : "Flota",
		STATS_RESEARCH : "Istraživanje",
		STATS_MEMBERS : "Clanovi",
		STATS_STATUS : "Status",
		STATS_NOTHING : "nema Statusa",
		STATS_NAP : "NAP",
		STATS_ALLIED : "Saveznik",
		STATS_WAR : "Rat",
		STATS_BOYCOTT : "Bojkot",
		STATS_NEUTRAL : "Neutralan",
		STATS_OWN : "Vlastiti Savez",
		STATS_WING : "Wing",
		STATS_UPDATE : "Unos od",
		STATS_PLAYERSTATS : "Statistika igraca",
		STATS_ALLYSTATS : "Statistika Saveza",
		STATS_DELETE : "Da li želite izbrisati ovaj Unos?",
		STATS_CONFIRM_DELETE : "Da li stvarno želite izbrisati ovaj Igracev unos?",
		STATS_CHANGE_PLAYER_STATUS : "Statistika igraca",
		STATS_CHANGE_ALLIANCE_STATUS : "Statistika Saveza",
		STATS_CHANGE_ALLIANCE_STATUS_HINT : "Svi clanovi ovog saveza dobivaju izabrani status. Svaki prijašnji status ce biti promijenjen. Možete promijeniti status nekih igraca naknadno.",
		STATS_UNKNOWN : "Ostatak",
		STATS_DETAILS : "Detalji za",
		STATS_PLAYERSTATUS : "Status igraca",
		STATS_IGNORE_STATUS : "svi",
		STATS_ACTIVE : "aktivan",
		STATS_INACTIVE : "Inaktivan",
		STATS_BANNED : "kažnjen",
		STATS_VACATION : "modus odsustva",
		STATS_NOOB : "noob",
		STATS_YES : "Da",
		STATS_NO : "Samo planete sa objavama",
		STATS_SEARCH : "Pretraga",
		STATS_SHOW_GRAPH : "Pokaži detalje o rasporedu bodova",
		STATS_LONG_INACTIVE : "Dugo inaktivan",
		STATS_STANDARD : "Standard Points",
		STATS_MILITARY : "Military Points",
		STATS_ECONOMY : "Economy",
		STATS_HONOUR : "Honour points",
		STATS_MILITARY_BUILD : "Military build",
		STATS_MILITARY_DESTROYED : "Military destroyed",
		STATS_MILITARY_LOST : "Military lost",
		REGISTER_REGISTRATE : "Registracija",
		REGISTER_LOGINNAME : "Korisnicko Ime",
		REGISTER_PASSWORD : "Šifra",
		REGISTER_PASSWORD_CONFIRM : "Potvrdi šifru",
		REGISTER_EMAIL : "Email",
		REGISTER_INGAME : "Ime u igri",
		REGISTER_ALLYTAG : "Tag saveza",
		REGISTER_EMAILVERIFICATION : "Provjera Emaila",
		REGISTER_EMAILTEXT : "Molimo vas da otvorite ovu stranicu kako bi potvrdili vaš Email na Galaxietool-u.",
		REGISTER_ERROR1 : "Korisnicko Ime se vec koristi!",
		REGISTER_ERROR2 : "Greška prilikom slanja Emaila! Molimo vas da kontaktirate administratora.",
		REGISTER_ERROR3 : "Greška prilikom slanja podataka u bazu!",
		REGISTER_INFO1 : "Vaš account je uspješno kreiran.",
		REGISTER_INFO2 : "Molimo vas posjetite link u vašem mailu da završite registraciju.",
		REGISTER_INFO3 : "Account je potrvden, vaš administrator ga sada mora aktivirati!",
		REGISTER_BUTTON : "Nazad na pocetnu stranicu",
		REGISTER_NEW_SUBJECT : "Novi korisnik registriran na galaxytoolu",
		REGISTER_NEW_MAILTEXT : "Novi korisnik se registrirao.",
		REGISTER_BACK : "Natrag na prvu stranicu",
		REGISTER_MISSING_FIELDS : "Unesite sva potrebna polja",
		REGISTER_ERROR4 : "Neispravna email adresa.",
		REGISTER_ERROR5 : "Lozinke nisu jednake.",
		REGISTER_PWS : "Snaga lozinke",
		REGISTER_PWS0 : "vrlo slaba",
		REGISTER_PWS1 : "slaba",
		REGISTER_PWS2 : "dobra",
		REGISTER_PWS3 : "jaka",
		REGISTER_PWS4 : "vrlo jaka",
		REGISTER_EMAIL_USED : "Email Address is already used",
		LOSTPW_TITLE : "Šifra zaboravljena",
		LOSTPW_INFO2 : "Nova šifra je generisana i poslana na vaš mail!",
		LOSTPW_BUTTON1 : "napravi novu šifru",
		LOSTPW_BUTTON2 : "Nazad na pocetnu stranicu",
		LOSTPW_LOGINNAME : "Korisnicko Ime",
		LOSTPW_EMAIL : "Email",
		LOSTPW_ERROR1 : "Greška prilikom slanja podataka u bazu!",
		LOSTPW_ERROR2 : "Krivo uneseni podaci!",
		LOSTPW_ERROR3 : "Greška prilikom slanja Emaila! Molimo vas da kontaktirate administratora",
		LOSTPW_EMAIL_SUBJECT : "Vaša nova šifra koju ste zatražili",
		LOSTPW_EMAIL_TEXT1 : "Vaš novi login za Galaxytool",
		LOSTPW_EMAIL_TEXT2 : "Korisnicko Ime",
		LOSTPW_EMAIL_TEXT3 : "Šifra",
		LOSTPW_INFO1 : "You will receive an email to verify your password reset request.",
		LOSTPW_CONFIRM_RESET_SUBJECT : "Lost password?",
		LOSTPW_CONFIRM_RESET_MESSAGE : "Hello,\n\nyou requested a password reset for the Galaxytool. To generate a new password, click the following link:",
		USERINFO_TITLE : "OGame Galaxietool - Informacije o korisniku",
		USERINFO_NAMES : "Svi korisnici",
		USERINFO_DETAIL : "detaljne informacije o",
		USERINFO_ERROR1 : "Ne postoji korisnik sa ovim ID!",
		USERINFO_USERNAME : "Korisnicko Ime",
		USERINFO_INGAME : "Ime u igri",
		USERINFO_EMAIL : "Email",
		USERINFO_ALLYTAG : "Savez",
		USERINFO_STYLEPATH : "Skin",
		USERINFO_STATUS : "Status",
		USERINFO_ACTIVATE : "Aktiviraj igraca",
		USERINFO_LOGINS : "Broj prijava",
		USERINFO_LASTLOGIN : "Zadnja prijava",
		USERINFO_DATA : "Informacije o sistemima koje je korisnik unio",
		USERINFO_NODATA : "Ovaj korisnik još uvjek nije unio niti jedan sistem!",
		USERINFO_GALAXY : "Galaksija",
		USERINFO_SYSTEMS : "Broj sistema",
		USERINFO_IP : "IP adresa",
		USERINFO_LOGINTIME : "Prijava",
		USERINFO_NOLOGIN : "Ovaj korisnik se do sada nije nikada prijavio.",
		USERINFO_LAST_GALAXYUPDATE : "Zadnji unos u izgled galaksije",
		USERINFO_LAST_PUBLIC_NOTICE : "Zadnja javna objava",
		USERINFO_LAST_PRIVATE_NOTICE : "Zadnja privatna objava",
		USERINFO_NUMBEROF_PUBLIC_NOTICE : "Broj javnih objava",
		USERINFO_NUMBEROF_PRIVATE_NOTICE : "Broj privatnih objava",
		USERINFO_ACTIVATED : "Korisnicki racun aktiviran",
		USERINFO_ACTIVATIONTEXT : "Galaxytool administrator je aktivirao vaš korisnicki racun. Uživajte u Galaxytool-u!",
		USERINFO_LAST_SUBMIT : "Zadnji uneseni podaci",
		ALLYHISTORY_TITLE : "OGame Galaxytool - Povijest Saveza",
		ALLYHISTORY_TBLHEAD : "Povijesni pregled",
		ALLYHISTORY_PLAYERNAME : "Igrac",
		ALLYHISTORY_ALLYNAME : "Savez",
		ALLYHISTORY_LASTMONTH : "Prošli mjesec",
		ALLYHISTORY_ALL_DATA : "sve dostupne informacije",
		ALLYHISTORY_SHOW : "prikaži statistiku",
		ALLYHISTORY_TIMESPAN : "Vremenski Interval",
		ALLYHISTORY_PROGESS : "Napredak",
		ALLYHISTORY_SCORE : "Bodovi",
		ALLYHISTORY_FSCORE : "Bodovi Flote",
		ALLYHISTORY_RSCORE : "Bodovi Istraživanja",
		ALLYHISTORY_MEMBER : "Clanovi",
		ALLYHISTORY_NOTHING : "ništa nije pronadeno",
		ALLYHISTORY_DETAILS : "Detalji",
		ALLYHISTORY_SHOW_ADDRESS : "Koordinate",
		ALLYHISTORY_ESCORE : "Economy",
		ALLYHISTORY_MSCORE : "Military Points",
		DETAILEDINFO_PLAYERINFO_TITLE : "Informacije igraca",
		DETAILEDINFO_ALLYINFO_TITLE : "Informacije Saveza",
		DETAILEDINFO_PLAYERINFO_TBLHEAD : "Detaljne informacije o Igracu",
		DETAILEDINFO_ALLYINFO_TBLHEAD : "Detaljne informacije o savezu",
		DETAILEDINFO_NO_ALLIANCE : "ništa",
		DETAILEDINFO_SCORE : "Statistike bodova",
		DETAILEDINFO_FLEET : "Statistike flote",
		DETAILEDINFO_RESEARCH : "Statistike istraživanja",
		DETAILEDINFO_RANK : "Pozicija",
		DETAILEDINFO_POINTS : "Bodovi",
		DETAILEDINFO_KNOWN_PLANETS : "poznate planete",
		DETAILEDINFO_MOONS : "poznati mjeseci",
		DETAILEDINFO_PHALANX_AREA : "Podrucje za Falangiranje",
		DETAILEDINFO_NO_PHALANX_AREA : "Falanga nije pronadena",
		DETAILEDINFO_NOTICES : "Objave",
		DETAILEDINFO_NO_NOTICES : "Nema pronadenih Objava",
		DETAILEDINFO_PREVIOUS_ALLIANCES : "prošli Savez",
		DETAILEDINFO_RESOURCES_PER_HOUR : "Resursa po satu",
		DETAILEDINFO_RESOURCES_PER_DAY : "Resursa po danu",
		DETAILEDINFO_RESOURCES_PER_WEEK : "Resursa po tjednu",
		DETAILEDINFO_RESOURCES_PER_MONTH : "Resursa po mjesecu (30 dana)",
		DETAILEDINFO_METAL : "Metal",
		DETAILEDINFO_CRYSTAL : "Kristal",
		DETAILEDINFO_DEUTERIUM : "Deuterij",
		DETAILEDINFO_UNKNOWN : "nepoznato",
		DETAILEDINFO_SCORE_DISTRIBUTION : "Raspodjela Bodova",
		DETAILEDINFO_GENERAL : "Detalji",
		DETAILEDINFO_MEMBERS : "Član",
		DETAILEDINFO_GRAPHS : "Grafovi",
		DETAILEDINFO_RESOURCES : "Resursi",
		DETAILEDINFO_FLEET_TAB : "Flota",
		DETAILEDINFO_TECH : "Istraživanja",
		DETAILEDINFO_FLEET_DETAIL : "Zbroj / (prosjek igrača) među svim dostupnim izvještajima",
		DETAILEDINFO_TECH_DETAIL : "Prosjek svih dostupnih informacija o igračima",
		DETAILEDINFO_PLANET_TAB : "Planeti",
		DETAILEDINFO_MOON_TAB : "Mjeseci",
		DETAILEDINFO_ACTIVITIES : "Aktivnosti",
		DETAILEDINFO_NODATA : "Podaci nisu dostupni.",
		DETAILEDINFO_ACTIVITY_DESCRIPTION : "Pokaži aktivnosti od &1 učitane od:",
		DETAILEDINFO_GALAXYVIEWS : "Pogledi galaksije",
		DETAILEDINFO_SCANS : "Akcije špijunaže",
		DETAILEDINFO_MESSAGES : "Poruke igrača",
		DETAILEDINFO_COMBATS : "Izvještaji o borbi",
		DETAILEDINFO_ALLYPAGE : "Pregled saveza",
		DETAILEDINFO_MANUAL : "Ručni unosi",
		DETAILEDINFO_START : "Početak",
		DETAILEDINFO_TO : "prema",
		DETAILEDINFO_TODAY : "Danas",
		DETAILEDINFO_DATA_RESTRICTION : "ograničeno do:",
		DETAILEDINFO_WEEKDAY_WEEKEND : "Vikend",
		DETAILEDINFO_WEEKDAY_WORKINGDAY : "Radni dan",
		DETAILEDINFO_WEEKDAY_MONDAY : "Ponedjeljak",
		DETAILEDINFO_WEEKDAY_TUESDAY : "Utorak",
		DETAILEDINFO_WEEKDAY_WEDNESDAY : "Srijeda",
		DETAILEDINFO_WEEKDAY_THURSDAY : "Četvrtak",
		DETAILEDINFO_WEEKDAY_FRIDAY : "Petak",
		DETAILEDINFO_WEEKDAY_SATURDAY : "Subota",
		DETAILEDINFO_WEEKDAY_SUNDAY : "Nedjelja",
		DETAILEDINFO_WEEKDAY_SHORTLENGTH : 3,
		DETAILEDINFO_PLAYER_CURRENTLY_ACTIVE : "Igrač je trenutno aktivan",
		DETAILEDINFO_PLAYER_MESSAGES : "dostupne poruke igrača",
		DETAILEDINFO_SHOW : "pokaži",
		DETAILEDINFO_NONE : "neije dostupno",
		DETAILEDINFO_ENTER_MANUALLY : "Unesi aktivnosti ovog igrača",
		DETAILEDINFO_PLAYER_SEEN_ON : "Igrač je bio online u",
		DETAILEDINFO_INSERT : "Unesi",
		DETAILEDINFO_OGAME_SERVERTIMES : "Molimo uočite: Svi datumi i vremena se odnose na vrijeme OGame servera !",
		DETAILEDINFO_DAY_VIEW : "Pregled 24h",
		DETAILEDINFO_WEEK_VIEW : "Tjedni pregled",
		DETAILEDINFO_HOME_PLANET : "Matična planeta",
		DETAILEDINFO_PLANETNAME : "Name",
		DETAILEDINFO_DEFENCE_SCORE : "Defence score",
		DETAILEDINFO_DEFENCE_SCORE_TOOLTIP : "Defence score = Fleet - Score + Research + Economy.<br/>All those statistics must be up to date to have a meaningful result!",
		DETAILEDINFO_SCORE_PER_SHIP : "Scores per ship",
		DETAILEDINFO_SHIPS : "Number of ships",
		DETAILEDINFO_DATE_IN_FUTURE : "Do not maintain times which are not in the past.",
		ADMIN_TITLE : "Galaxytool administriranje",
		ADMIN_DISCLAMER : "Pažnja: Pokrečite bilo koju od ovih skripti na vlastitu odgovornost, većina ih briše podatke",
		ADMIN_INCONSISTENCIES : "Nedosljednosti u bazi podataka",
		ADMIN_PLANETS : "Planeti na poziciji 0 ili većoj od 15",
		ADMIN_GALAXIES : "Izbriši galaksije veće od &1 ",
		ADMIN_PLAYERS : "Obriši igrače bez OGame playerid - vodi do duplih unosa igrača",
		ADMIN_REPORTS : "Obriši izvještaje od planeta koji više ne postoje",
		ADMIN_MISC : "Različito",
		ADMIN_RESET : "Resetiraj Galaxytool (Samo tablice korisnika i IP adresa neće biti obrisane)",
		ADMIN_OLD_PLAYERS : "Obriši unose igrača starije od &1 dana",
		ADMIN_OLD_REPORTS : "Obriši izvještaje starije od &1 dana",
		ADMIN_LOADING : "Ne zatvarajte ovaj prozor dok se stranica ne učita.",
		ADMIN_STATUS : "Stanje tvojih zahtjeva",
		ADMIN_SELECTION : "Barem jedan unos mora biti označen",
		ADMIN_SAFETY : "Jeste li sigurni da želite pokrenuti ovu/e skriptu/e?",
		ADMIN_DONE : "gotovo",
		ADMIN_NOTBD : "nema ništa za napraviti",
		ADMIN_OLD_GALAXIES : "Obrišite poglede galaksije starije od &1 dana",
		ADMIN_UNUSED_PLAYERS : "Uklonite igrače koji se ne pojavljuju niti u jednom pogledu galaksije",
		ADMIN_OLD_ACTIVITIES : "Uklonite aktivnosti igrača statije od &1 dana",
		ADMIN_OLD_COMBATS : "Obriši izvještaje o borbi starije od &1 dana",
		ADMIN_OLD_INGAME_MSG : "Obriši poruke u igri starije od &1 dana",
		ADMIN_OGAME_API : "Load public data from OGame into the Galaxytool",
		ADMIN_OGAME_ALL_DATA : "sve dostupne informacije",
		ADMIN_OGAME_GALAXY_DATA : "Pregled galaksije",
		ADMIN_OGAME_STATISTICS_DATA : "Statistike",
		ERRORPAGE_PAGEFORWARD : "Kliknite ovdje ako vaš preglednik (browser) ne podržava automatsko prosljeđivanje.",
		ERRORPAGE_PERMISSION_DENIED : "Nemate dozvolu posjetiti ovu stranicu. Kliknite ovdje da se vratite natrag.",
		FLEETS_TITLE : "OGame Galaxytool - Kretanja flote",
		FLEETS_ACTUAL_FLEETS : "Trenutna kretanja flote",
		FLEETS_YES : "Da",
		FLEETS_NO : "Samo planete sa objavama",
		FLEETS_DETAILS : "Detalji",
		FLEETS_MISSION_EXPEDITION : "Ekspedicija",
		FLEETS_MISSION_COLONIZATION : "Kolonizacija",
		FLEETS_MISSION_RECYCLE : "Vaditi",
		FLEETS_MISSION_TRANSPORT : "Transport",
		FLEETS_MISSION_DEPLOYMENT : "Stacionaža",
		FLEETS_MISSION_ESPIONAGE : "Špijunaža",
		FLEETS_MISSION_ACS_DEFEND : "Pauziraj",
		FLEETS_MISSION_ATTACK : "Napad",
		FLEETS_MISSION_ACS_ATTACK : "AkS Napad",
		FLEETS_MISSION_MOON_DESTRUCTION : "Uništenje mjeseca",
		FLEETS_MISSION_MISSILE_ATTACK : "Napad raketama",
		FLEETS_NO_DATA : "Nema primjenjivih podataka",
		FLEETS_FLEET : "Fleet",
		FLEETS_ALL_FLEETS : "Show all fleet movements",
		COMBAT_REPORT_OUDATED_GALAXYVIEW : "Podaci o galaksiji su vam zastarili. Molimo prvo posjetite izvornu planetu napada i metu napada!",
		MESSAGES_TITLE : "OGame Galaxytool - OGame Poruke",
		MESSAGES_PLAYERNAME : "Ime igrača",
		MESSAGES_SUBJECT : "Naslov",
		MESSAGES_DATE : "Datum",
		MESSAGES_FILTER : "Filter",
		MESSAGES_DELETE : "Obriši poruku",
		MESSAGES_PUBLISH_DETAIL : "Objavi poruku tako da ju dodaš u napomene o tom igraču.",
		MESSAGES_PUBLISH_HEADER : "&sender je poslao poruku igraču &recipient dana &date:\n\n &message",
		MESSAGES_PLAYER_FILTER : "Poruke za igrača:",
		MESSAGES_CONTENT : "Content",
		COMBATS_TITLE : "OGame Galaxytool - Izvještaji o borbi",
		COMBATS_ATTACKER : "Napadač",
		COMBATS_DEFENDER : "Obranioc",
		COMBATS_DATE : "Datum",
		COMBATS_OWNER : "Vlasnik",
		COMBATS_WINNER : "Pobjednik",
		COMBATS_COMBATREPORT : "Izvještaj o borbi",
		COMBATS_COMBAT_AT : "Borba na",
		COMBATS_LOST_UNITS : "Izgubljene jedinice",
		COMBATS_LOOT : "Plijen",
		COMBATS_DEBRIS : "Ruševine",
		COMBATS_AND : "i",
		COMBATS_PUBLISH : "Označi izvještaj kao javni",
		COMBATS_UNPUBLISH : "Označi izvještaj ponovno kao privatni",
		COMBATS_DELETE : "Obriši izvještaj",
		COMBATS_CHECK_ALL : "Označi sve",
		COMBATS_UNCHECK_ALL : "Odznači sve",
		COMBATS_WITH_SELECTED : "Sa odabranima",
		COMBATS_PUBLIC_REPORTS : "Javni izvještaji",
		COMBATS_YES : "Da",
		COMBATS_NO : "Samo planete sa objavama",
		COMBATS_SEARCH_OPTIONS : "Opcije pretrage",
		COMBATS_SEARCH : "Napravi",
		COMBATS_RESET : "Ponovno postavi",
		COMBATS_COORDINATES : "Koordinate",
		COMBATS_INVALID_GALAXY_ENTERED : "Unesena pogrešna galaksija",
		COMBATS_INVALID_SYSTEM_ENTERED : "Unesen pogrešan sistem",
		COMBATS_INVALID_PLANET_ENTERED : "Unesena pogrešna planeta",
		COMBATS_GALAXY_FROM_TO : "Galaksija",
		COMBATS_SYSTEM_FROM_TO : "Sistem",
		COMBATS_PLANET_FROM_TO : "Planeta",
		COMBATS_APPLY : "potvrdi",
		COMBATS_COMBAT_SUMMARY : "Sažetak izvještaja o borbi",
		COMBATS_DOWNLOAD_CSV : "Preuzmi CSV datoteku",
		REPORT_ARCHIVE_TITLE : "Arhiva izvještaja",
		REPORT_ARCHIVE_COORDINATES : "Koordinate",
		REPORT_ARCHIVE_SCANTIME : "Vrijeme skeniranja",
		REPORT_ARCHIVE_DELETE : "Izbriši ove uonse",
		REPORT_ARCHIVE_CONFIRM_DELETE : "Da li zaista želite izbrisati ove unose?",
		REPORT_ARCHIVE_GALAXY : "Galaksija",
		REPORT_ARCHIVE_SYSTEM : "Sistem",
		REPORT_ARCHIVE_PLANET : "Planeta",
		REPORT_ARCHIVE_MOON : "Mjesec",
		REPORT_ARCHIVE_DETAILS : "Detalji",
		REPORT_ARCHIVE_RESOURCES : "Resursa po satu",
		REPORT_ARCHIVE_HEADER_RESOURCES : "Resursi",
		REPORT_ARCHIVE_DETAILS_FOR : "Arhiva izvještaja za &1 [&2] (&3)",
		REPORT_ARCHIVE_FLEET_CARGO : "Kapacitet tereta flote",
		REPORT_ARCHIVE_IRAK_RANGE : "Doseg interplanetarnih raketa",
		REPORT_ARCHIVE_CHART_TYPE : "Tip grafa",
		INSTALL_TITLE : "Galaxytool installation for version",
		INSTALL_PROGRESS : "Overall progress",
		INSTALL_STEP : "Step",
		INSTALL_CONTINUE : "Continue",
		INSTALL_VALIDATE : "Validate",
		INSTALL_STEP1 : "Welcome",
		INSTALL_STEP2 : "Writeable check",
		INSTALL_STEP3 : "Database settings",
		INSTALL_STEP4 : "OGame settings",
		INSTALL_STEP5 : "Galaxytool settings",
		INSTALL_STEP6 : "Admin password",
		INSTALL_STEP7 : "Install Galaxytool",
		INSTALL_STEP8 : "Finalize install",
		INSTALL_FILE_DELETE_CHECK : "Please delete install.php and update.php from your webserver.",
		INSTALL_STEP1_PHP_FAILED : "Your PHP version &1 is not working with this Galaxytool version",
		INSTALL_STEP1_FOPEN_FAILED : "Your PHP version does not allow to open webpages with FOPEN() command. This is required to consume the OGame API.",
		INSTALL_STEP1_WELCOME : "Welcome to the installation wizard of the Galaxytool. You will be guided through the installation of the Galaxytool.",
		INSTALL_STEP2_DESCRIPTION : "Make sure your config.php and attributes.php files have write permissions enabled.",
		INSTALL_STEP2_DESCRIPTION2 : "If you don't know, how to achieve this, please take a look here: &1",
		INSTALL_STEP2_FILE_NOT_WRITEABLE : "File is not writeable",
		INSTALL_STEP3_SERVER : "Database server",
		INSTALL_STEP3_USERNAME : "Korisnicko Ime",
		INSTALL_STEP3_PASSWORD : "Šifra",
		INSTALL_STEP3_DBNAME : "Database name",
		INSTALL_STEP3_PREFIX : "Tablename prefix",
		INSTALL_STEP3_ENTER_PREFIX : "E.g. mytool_",
		INSTALL_STEP3_ENTER_SERVER : "Enter the server address. Contact your system admin if necessary. Usually the correct value is localhost.",
		INSTALL_STEP3_ENTER_USERNAME : "Enter the username for database access",
		INSTALL_STEP3_ENTER_PASSWORD : "Enter the password for database access",
		INSTALL_STEP3_ENTER_DBNAME : "Enter the database name which shall be used for installation (must exist)",
		INSTALL_STEP3_CONNECT_FAILED : "Could not establish connection to database server",
		INSTALL_STEP3_DB_FAILED : "Database &1 not found",
		INSTALL_STEP3_MYSQL_VERSION_FAILED : "MySQL version &1 is not working with this Galaxytool version",
		INSTALL_STEP4_URL : "OGame URL",
		OGAME_URL_DETAILS : "Please enter any URL you see when you are logged on to OGame. Based on that URL the tool will derive the OGame API address which can be used to fill data into the Galaxytool without the Galaxytoolbar. This API was introduced with OGame version 4.1.",
		INSTALL_STEP4_UNIVERSE : "OGame Universe",
		INSTALL_STEP4_DEF_TO_DEBRIS : "Defense to debris",
		INSTALL_STEP4_DEBRIS_RATE : "Debris rate",
		INSTALL_STEP4_SPEED_RATE : "Speed rate",
		INSTALL_STEP4_ENTER_UNIVERSE : "Enter your OGame universe name or number (case sensitive).",
		INSTALL_STEP4_UNIVERSE_MISSING : "You must define your universe",
		INSTALL_STEP4_ENTER_URL : "Enter your OGame universe address",
		INSTALL_STEP4_URL_MISSING : "You must define your OGame address",
		INSTALL_STEP4_URL_CHECK_FAILED : "Could not find OGame API at &1",
		INSTALL_STEP4_GETSETTINGS : "Fetch settings",
		INSTALL_STEP5_TOOLNAME : "Galaxytool name",
		INSTALL_STEP5_ENTER_TOOLNAME : "This is the name which will be shown at logon page to identify your Galaxytool",
		INSTALL_STEP5_LANGUAGE : "Default language",
		INSTALL_STEP5_EMAIL_TO : "Email To",
		INSTALL_STEP5_ENTER_EMAIL_TO : "Enter the email address where you would like to receive notifications about registrations",
		INSTALL_STEP5_EMAIL_FROM : "Email From",
		INSTALL_STEP5_ENTER_EMAIL_FROM : "This email address is shown as REPLY for all mails sent from the Galaxytool",
		INSTALL_STEP5_USE_PHPMAILER : "Use PHPMailer",
		INSTALL_STEP5_MAXSHOUTS : "Maximum number of shoutbox entries",
		INSTALL_STEP5_ENTER_USE_PHPMAILER : "Use PHPMailer if your server does not support sending emails by default",
		INSTALL_PHPMAILER_HOST : "SMPT Host",
		INSTALL_PHPMAILER_HOST_EXAMPLE : "e.g. smtp.provider.com",
		INSTALL_PHPMAILER_USER : "SMPT Username",
		INSTALL_PHPMAILER_USER_EXAMPLE : "e.g. user@provider.dcom",
		INSTALL_PHPMAILER_PASS : "SMPT password",
		INSTALL_PHPMAILER_SECURE : "Authentification method (e.g. ssl)",
		INSTALL_PHPMAILER_PORT : "SMTP Port",
		INSTALL_STEP6_INTRO : "Please define a password for the <strong>admin</strong> account which you have to use for your first logon to the Galaxytool after the installation.",
		INSTALL_STEP7_CONFIG : "Configuration file created",
		INSTALL_STEP7_CONFIG_FAILED : "Configuration file not created",
		INSTALL_STEP7_ATTRIBUTES : "Attributes file created",
		INSTALL_STEP7_ATTRIBUTES_FAILED : "Attributes file not created",
		INSTALL_STEP7_CREATED_TABLES : "Database tables created",
		INSTALL_STEP8_INTRO : "You have successfully installed the Galaxytool!",
		INSTALL_STEP8_LOAD_DATA : "Downloading OGame data ...",
		INSTALL_STEP8_LOAD_DATA_FINISHED : "Download of OGame data finished",
		INSTALL_STEP8_DELETE_FILE : "You should now delete the installation files install.php and update.php from your webserver.",
		INSTALL_STEP8_LOGON : "Please logon with the <strong>admin</strong> user and the password you defined earlier.",
		UPDATE_START : "Starting update to version &1",
		UPDATE_STEP_DONE : "Done",
		UPDATE_TITLE : "Galaxytool update for version",
		UPDATE_STEP1_WELCOME : "Welcome to the update wizard of the Galaxytool. You will be guided through the update of the Galaxytool.",
		UPDATE_STEP1_BACKUP_FILES : "As a first step, make a backup of your <strong>config</strong> folder! You will have to replace the configuration content in case of errors.",
		UPDATE_STEP1_BACKUP_DB : "Then make a <a href=\"http://www.ehow.com/how_2036600_create-database-php.html\">backup</a> of your database.",
		UPDATE_STEP1_PROCEED : "Once the backups have been done, you can proceed with your update.",
		UPDATE_STEP1 : "Welcome",
		UPDATE_STEP2 : "Galaxytool settings",
		UPDATE_STEP2_OLD_VERSION : "Previous Galaxytool version",
		UPDATE_STEP3 : "Update Galaxytool",
		UPDATE_STEP3_UPDATE_RUNNING : "Update running, please wait...",
		UPDATE_STEP4 : "Finalize Update",
		UPDATE_STEP4_INTRO : "You have successfully updated the Galaxytool!",
		UPDATE_STEP4_UPDATE_DONE : "Update steps performed.",
		UPDATE_FAILED : "Update failed.",
		GALAXYTOOL_DUMMY_TEXT : "dummy"
	})
);