define(
	({
		REPORT_WHEN : "更新日:",
		RESOURCES_ON : "資力：",
		PLAYER_BANNED : "b",
		PLAYER_VACATION_MODE : "v",
		PLAYER_NOOB : "n",
		PLAYER_INACTIVE : "i",
		PLAYER_LONG_INACTIVE : "I",
		PLAYER_OUTLAW : "o",
		L_USERNAME : "ユーザ名",
		L_PASSWORD : "パスワード",
		L_LOGINFAILURE : "ユーザ名あるいはパスワードがが間違っているか，そのアカウントは有効化されていません．",
		L_TOKENFAILURE : "あなたのログオンキーが間違っているか、そのアカウントは有効化されていません.",
		L_LOGINTEXT : "ログインして下さい．",
		L_LANGUAGE : "利用可能な言語:",
		L_TIMEOUT : "セッションがタイムアウトしました．",
		L_REGISTER : "登録",
		L_PWLOST : "パスワード忘れ",
		INDEX_TITLE : "OGame Galaxytool - 概要",
		INDEX_INFO : "インフォメーション",
		INDEX_ENTRIES : "全システム数",
		INDEX_ENTRIES_LASTWEEK : "先週更新されたシステム数",
		INDEX_ENTRIES_TO_OLD : "一カ月以上更新されていないシステム数",
		INDEX_REGISTERED_USERS : "登録ユーザ数",
		INDEX_PAGEFORWARD : "自動的にジャンプできなければ，ここをクリックして下さい．",
		INDEX_NOTICES : "メモ",
		INDEX_PLAYERS : "ランキング（プレーヤー）",
		INDEX_ALLIES : "ランキング（同盟）",
		INDEX_REPORTS : "スパイレポート",
		INDEX_VERSION : "最新版ダウンロード",
		INDEX_LATEST_VERSION : "最新のバージョンをお使いです",
		INDEX_SHOUTBOX : "メッセージボックス",
		INDEX_NOENTRY : "まだメッセージはありません",
		INDEX_COMMENT : "メッセージ入力",
		INDEX_INSERT : "追加",
		INDEX_UMOD : "休暇モード中のユーザ数",
		INDEX_NO_MOONS : "月の数",
		INDEX_NO_EMPTY_SYSTEMS : "空いているシステム数",
		INDEX_NO_FULL_SYSTEMS : "全て埋まったシステム数",
		INDEX_NO_TARGETS : "攻撃可能な惑星数",
		INDEX_USERINFO : "ユーザ数",
		INDEX_ONLINE : "オンライン中のユーザ数",
		INDEX_TODAY : "本日ログインしたユーザ数",
		INDEX_ALL : "ログインした全ユーザ数の合計",
		GENERAL_LOAD_FORM : "フォームデータを開く",
		GENERAL_SAVE_FORM : "フォームデータを保存",
		GENERAL_SAVE_AS_TEXT : "ファイル名",
		GENERAL_SAVE : "保存",
		INDEX_USERMANAGEMENT : "アクティベーション概要",
		INDEX_NEEDADMIN : "アカウントロック解除",
		INDEX_NEEDEMAIL : "アカウント未検証",
		INDEX_TOOLBAR_INFO : "Galaxytool プラグイン情報",
		INDEX_TOOLBAR_URL : "Galaxytool URL",
		INDEX_TOOLBAR_VERSION_REQUIRED : "プラグインは右記のバージョン以降が必要.",
		INDEX_TOOLBAR_INSTALL_GUIDE : "プラグインのインストール手順",
		INDEX_TOOLBAR_TOKEN : "ログオンキー",
		INDEX_TOOLBAR_NEW_TOKEN : "新しいキーを取得",
		INDEX_PLAYERS_WITH_N_PLANETS : "&1 以上の惑星を持つプレーヤー",
		INDEX_GETTING_STARTED : "Galaxytoolの入門",
		INDEX_GETTING_STARTED1 : "Galaxytoolへようこそ!",
		INDEX_GETTING_STARTED2 : "GalaxytoolはあなたのOGameの宇宙 &1 で何が起こっているかを分析するのに役に立つでしょう.",
		INDEX_GETTING_STARTED3 : "あなたが実際にデータを分析する前に、まずデータを挿入する必要があります。このためには、Firefox用の &1 のようなブラウザプラグインが必要となります.",
		INDEX_GETTING_STARTED4 : "あなたがプラグインをインストールしたら、通常どおりOGameページ内を移動し、何かがあなたのGalaxytoolに送信されるたびに、小さなステータスウィンドウが表示されます.",
		INDEX_GETTING_STARTED5 : "いったんプラグインが、Galaxytoolにデータを挿入すると、彼らのコロニーがある場所、彼らが所持しているコロニーの数、彼らが最もアクティブな時間帯の分析を開始することができます.",
		INDEX_GETTING_STARTED6 : "それはまた、過去数日または数週間の間、あなたと競争相手に対してコンバットリポートを確認し分析することによりあなたがどのようなプロセスをとればいいか？を助けます.",
		INDEX_GETTING_WIKIPAGE : "Galaxytoolの中にはより多くのさまざまな機能があります.",
		INDEX_GETTING_WIKIPAGE2 : "それらは私たちのwikiページでチェックしてください.",
		INDEX_GETTING_BOARD : "フィードバックやアイデアは私たちの掲示板を御利用ください.:",
		INDEX_GETTING_CHAT1 : "またはチャットルームをご参照ください.:",
		INDEX_GETTING_CHAT2 : "我々開発者は24時間/7日オンラインではありませんが、そこに私たちの自由時間の多くを割くので、辛抱強く待ってください.",
		INDEX_CLOSE : "閉じる",
		INDEX_LOGIN : "ログイン",
		GENERAL_REQUIRED_FIELDS : "すべての必須フィールドを入力してください",
		INDEX_MESSAGES : "メッセージ",
		INDEX_EXAMPLE : "例",
		INDEX_INVALID_DATA : "データ無効",
		GENERAL_COLUMN_HIDE_TITLE : "列の管理",
		GENERAL_COLUMN_HIDE_INFO : "あなたがテーブルに表示する列を選択してください.",
		GENERAL_ENTRIES_DELETED : "&1 エントリが削除",
		GENERAL_APPLY : "適用",
		STARTPAGE_GALAXYTOOL_DESCR : "<em>Galaxytool</em> は、ブラウザゲームOGameのためのツールです",
		GENERAL_OVERWRITE : "エントリが重複し上書きされます",
		GENERAL_OVERWRITE_QUESTION : "上書きしますか?",
		INDEX_OWN_LOGINS : "あなたのログイン名",
		GENERAL_OPEN_IN_NEW_WINDOW : "リンクを新しいウィンドウで開く",
		GENERAL_UNIT_OF_MEASURE_DAYS : "Days",
		PROGRAM_NAME : "OGame Galaxytool",
		SHORTNAME : "Galaxytool",
		BACK_INDEX : "メインページに戻ります",
		UNIVERSE : "宇宙",
		MENU_INFO_LINKS : "インフォメーション",
		MENU_PAGE : "概要",
		MENU_DB_SEARCH : "データベースの検索",
		MENU_DB_NOTICES : "メモの検索",
		MENU_DB_REPORTS : "スパイレポートの検索",
		MENU_GALAXYVIEW : "銀河の閲覧",
		MENU_STATISTICS : "ランキング",
		MENU_ALLYHISTORY : "過去の概要",
		MENU_FLEET_MOVEMENTS : "艦隊動向",
		MENU_COMBAT_REPORTS : "コンバットレポート",
		MENU_MESSAGES : "ゲーム内メッセージ",
		MENU_OPTION_LINKS : "オプション",
		MENU_DB_REFRESH : "データベースに追加",
		MENU_NOTICES : "メモ",
		MENU_DB_STATUS : "データベースステータス",
		MENU_USEROPTIONS : "ユーザ管理",
		MENU_USEROPTIONS2 : "ユーザオプション",
		MENU_USEROPTIONS3 : "ユーザ情報",
		MENU_ADMIN : "管理用",
		MENU_LOGOUT : "ログアウト",
		MENU_STUFF : "その他",
		MENU_FORUM_THREAD : "開発者用フォーラム",
		MENU_DOWNLOADPAGE : "ダウンロードページ",
		MENU_LANGUAGE : "言語",
		MENU_HELP : "ヘルプ",
		MENU_TOOLOPTIONS : "Galaxytoolオプション",
		PARSER_INFO1 : "をデータベースに追加",
		PARSER_ERROR1 : "下記の座標を追加中にエラーが発生:",
		PARSER_ERROR2 : "データベースが見つかりません！",
		PARSER_ERROR3 : "データベースサーバが見つかりません！",
		PARSER_WRONG_UNIVERSE : "宇宙が違います。 - 入力値: \"&1\" 予想: \"&2\"",
		SHOW_TITLE : "OGame Galaxytool - 検索ページ",
		SHOW_SEARCH : "データベースを検索",
		SHOW_ALLYSYMBOL : "同盟タグ",
		SHOW_PLAYERNAME : "プレーヤー名",
		SHOW_MOONS : "月がある惑星のみ表示",
		SHOW_NOTICES : "メモ付きの惑星のみ表示",
		SHOW_COLONIES : "コロニーのみ表示",
		SHOW_YES : "はい",
		SHOW_NO : "いいえ",
		SHOW_SEARCHRANGE : "範囲",
		SHOW_SEARCH_IN : "銀河を検索",
		SHOW_FROM_SYSTEM : "システムから",
		SHOW_FROM_PLANET : "惑星の位置から",
		SHOW_TO : "へ",
		SHOW_DESCRIPTION : "プレーヤー名または同盟名に対し，ワイルドカードとして*を使うことができます．つまり，&quot;name&quot;を名前に含む全てのプレーヤーを検索できます．<br />以下の項目のうち指定したい項目のみ埋めて下さい",
		SHOW_SORT_BY : "並び替え",
		SHOW_GALASYSTEM : "銀河/システム",
		SHOW_ALLYNAME : "同盟名",
		SHOW_SEARCHBUTTON : "検索",
		SHOW_ADDRESS : "座標",
		SHOW_ALLYSORT : "同盟",
		SHOW_PLANET : "惑星名",
		SHOW_STATUS : "ステータス",
		SHOW_CURRENTNESS : "更新時間",
		SHOW_PLAYER_STATUS : "プレーヤーステータス",
		SHOW_PLAYER_STATUS1 : "全て",
		SHOW_PLAYER_STATUS2 : "攻撃可能",
		SHOW_PLAYER_STATUS3 : "7日以上不在",
		SHOW_HITS : "検索結果",
		SHOW_OF : "/",
		SHOW_ASC : "昇順",
		SHOW_DESC : "降順",
		SHOW_RESULTS : "件（ページ当たり）",
		SHOW_MOON : "月",
		SHOW_UKMOONSIZE : "不明",
		SHOW_DF : "DF",
		SHOW_DF_LONG : "デブリフィールド",
		SHOW_METAL : "M",
		SHOW_METAL_LONG : "メタル",
		SHOW_CRYSTAL : "C",
		SHOW_CRYSTAL_LONG : "クリスタル",
		SHOW_BOTH : "合計",
		SHOW_AT_LEAST : "(最少)",
		SHOW_DATE : "日付",
		SHOW_DATE_0 : "設定しない",
		SHOW_DATE_1 : "より古い",
		SHOW_DATE_2 : "より新しい",
		SHOW_RANK : "ランク",
		SHOW_FRANK : "艦隊ランク",
		SHOW_MEMBERS : "メンバー",
		SHOW_NOTRANKED : "利用可能なデータはありません",
		SHOW_NOTICERES : "メモ",
		SHOW_REPORTS : "レポートのある惑星のみ表示",
		SHOW_REPORTS_SHORT : "レポート",
		SHOW_NOTHING : "該当するエントリは見つかりませんでした",
		SHOW_ALLIANCE_STATUS : "対外同盟情報",
		SHOW_NO_STATUS : "対外同盟情報はありません",
		SHOW_NAP : "不戦同盟",
		SHOW_ALLIED : "攻守協力同盟",
		SHOW_WAR : "敵対同盟",
		SHOW_BOYCOTT : "不干渉同盟",
		SHOW_NEUTRAL : "中立同盟",
		SHOW_OWN : "所属同盟",
		SHOW_WING : "下部同盟",
		SHOW_EXT_OPTIONS1 : "範囲，ランク，日付またはデブリフィールドに関するより詳細な検索オプションを表示．",
		SHOW_EXT_OPTIONS2 : "コロニー，月，スパイレポート，メモ，プレーヤーステータスまたは対外同盟情報に関するより詳細な検索オプションを表示．",
		SHOW_EXT_OPTIONS3 : "検索結果の並び替えに関するより詳細な検索オプションを表示．",
		SHOW_EXTENDED : "高度な検索",
		SHOW_MOON_SELECTION : "月をもつ惑星",
		SHOW_REPORT_SELECTION : "レポートのある惑星",
		SHOW_FILTER_BY : "リストから除外",
		SHOW_FILTER_NONE : "無し",
		SHOW_PLAYERS_WITHOUT_PROGRESS : "Show players without score changes within the last few days",
		STATUS_TITLE : "OGame Galaxytool - ステータスページ",
		STATUS_DB_STATUS : "データベースステータス",
		STATUS_COLOR : "カラー",
		STATUS_AGE1 : "1日前のエントリ．",
		STATUS_AGE2 : "2-4日前のエントリ．",
		STATUS_AGE3 : "4-7日前のエントリ．",
		STATUS_AGE4 : "1-2週間前のエントリ．",
		STATUS_AGE5 : "2-4週間前のエントリ．",
		STATUS_AGE6 : "1ヶ月以上前のエントリ！",
		STATUS_AGE7 : "利用可能なエントリはありません．",
		STATUS_ON : "オン",
		STYLES_COLOR1 : "カラー1",
		STYLES_COLOR2 : "カラー2",
		STYLES_COLOR3 : "カラー3",
		STYLES_COLOR4 : "カラー4",
		STYLES_COLOR5 : "カラー5",
		STYLES_COLOR6 : "カラー6",
		STYLES_COLOR7 : "カラー7",
		STATUS_DB_LEGEND : "凡例",
		STATUS_GALAXY : "銀河の概要",
		USER_TITLE : "ユーザ管理",
		USER_NAMES : "ユーザ",
		USER_ERROR : "エラー",
		USER_NEWUSER : "新ユーザ",
		USER_OPTIONS : "オプション",
		USER_USERNAME : "ユーザ名",
		USER_PASSWORD : "パスワード",
		USER_PASSWORD_CONFIRM : "パスワード（確認用）",
		USER_GALAXY : "銀河",
		USER_SEARCH : "検索",
		USER_INSERT : "追加",
		USER_DELETE : "消去",
		USER_DELETE_ENTRY : "ユーザを消去しますか: ",
		USER_STATUS : "ユーザステータス",
		USER_STYLES : "レイアウト変更",
		USER_SUBMIT : "登録",
		USER_RESET : "リセット",
		USER_YES : "はい",
		USER_NO : "いいえ",
		USER_STYLEPATH : "styles.cssのパス",
		USER_PROBES : "スパイレポートを見る／登録する",
		USER_EMAIL : "Eメール",
		USER_ERROR1 : "パスワードが間違っているか有効なEメールアドレスではありません．",
		USER_ERROR2 : "無効なEメールアドレスです．",
		USER_INGAME : "ゲーム内のユーザ名",
		USER_ALLYTAG : "同盟タグ",
		USER_ALLYHISTORY : "過去の概要",
		USER_DIPLOMATIC : "外交関係を変更",
		USER_STATSPAGE : "ランキングのエントリ数",
		USER_LINKS : "リンク",
		USER_LINKS2 : "フォーマット:<br>テキスト;url<br>テキスト2;url2<br>テキスト3;url3",
		USER_EXPORT_TITLE : "カラー情報をエクスポート（BBコード）",
		USER_BB_COORDINATES : "座標",
		USER_BB_MOON : "月",
		USER_BB_DEBRIS : "デブリフィールド",
		USER_BB_ALLY : "同盟名",
		USER_BB_ALLYDETAILS : "同盟の詳細",
		USER_BB_PLAYERNAME : "プレーヤー名",
		USER_BB_BANNED : "アカウント停止",
		USER_BB_VACATION : "休暇モード",
		USER_BB_NOOB : "初心者",
		USER_BB_INACTIVE : "7日間不在",
		USER_BB_LONGINACTIVE : "28日間不在",
		USER_DELETION : "削除",
		USER_FLEETINFO : "艦隊動向",
		USER_ACTIVITIES : "プレイヤーの活動",
		USER_MAINTENANCE : "Galaxytoolのメンテナンス",
		USER_MANAGEMENT : "ユーザ管理",
		USER_DELETE_MY_COMBAT_REPORTS : "自分のコンバットレポートを削除",
		USER_DELETE_MY_MESSAGES : "自分のメッセージを削除",
		USER_DELETE_MY_FLEETMOVES : "自分の艦隊動向を削除",
		USER_DELETE_MY_COMBAT_REPORTS_LIMITED : "自分のコンバットレポートの &1 日以上経過したものを削除",
		USER_DELETE_MY_MESSAGES_LIMITED : "自分のメッセージの &1 日以上経過したものを削除",
		USER_TABLE_ENTRIES : "各ページの検索結果の数",
		USER_EXISTS : "ユーザーはすでに存在しています",
		USER_BB_OUTLAW : "アウトロー",
		USER_INVALID_URL : "URL &1 が無効であると思われる - URLは無視されます",
		VIEW_TITLE : "OGame Galaxytool - 銀河ビュー",
		VIEW_NODATA : "利用可能なデータはありません．",
		VIEW_GALAXY : "銀河",
		VIEW_SYSTEM : "システム",
		VIEW_POSITION : "位置",
		VIEW_PLANET : "惑星",
		VIEW_MOON : "月",
		VIEW_TF : "DF",
		VIEW_PLAYER : "プレーヤー",
		VIEW_PLAYER_ADD : "（ランク / ステータス）",
		VIEW_ALLY : "同盟",
		VIEW_ALLY_ADD : "（ランク / メンバー数）",
		VIEW_METAL : "M",
		VIEW_CRYSTAL : "C",
		VIEW_COLONISED : "植民地化されたスロット数",
		VIEW_UKMOONSIZE : "不明",
		VIEW_BACK : "戻る",
		VIEW_NOTICE : "メモ",
		VIEW_REPORTS : "レポート",
		VIEW_MOONPHALANX : "以下に挙げる月はこのシステムをスキャン可能です",
		VIEW_NOMOONS : "月は一つも見つかりませんでした",
		VIEW_IRAKS : "以下に挙げる惑星はこのシステムまで星間ミサイルが到達可能です",
		VIEW_NOIRAKS : "星間ミサイルは一つも見つかりませんでした",
		VIEW_MOON_DESTROY_CHANCE : "月を破壊できる確率",
		VIEW_CHANCE_WITH_ONE : "デススター一機での確率",
		VIEW_CHANCE_WITH_N : "次の確率",
		VIEW_DEATH_STARS : "デススター",
		VIEW_DS_DESTROY_CHANCE : "デススターが負ける確率",
		VIEW_TOP : "トップ",
		VIEW_GO : "go",
		VIEW_DIAMETER : "直径",
		PW_TITLE : "OGame Galaxytool - パスワード変更",
		OLD_PASSWORD : "古いパスワード",
		NEW_PASSWORD : "新しいパスワード",
		CONFIRM_NEW_PASSWORD : "新しいパスワード（確認用）",
		PW_MISMATCH : "パスワードが一致しません！",
		PW_ERROR : "古いパスワードが正しくありません！",
		UPDATE_DONE : "パスワードは変更されました．",
		TIMEZONE_OFFSET : "サーバとの時差",
		DELETE_ACCOUNT : "Galaxytoolのアカウントを削除",
		DELETE_ACCOUNT_SAFETY_REQUEST : "本当にアカウントを削除しますか？",
		CH_PASSWD_AUTHORIZATION : "承認",
		CH_PASSWD_ADMIN : "管理者",
		TIMEZONE_OGAME_OFFSET : "OGameサーバとの時差",
		CH_PASSWD_USER_LANGUAGE : "ログオン後にこの言語に変更",
		CH_PASSWD_USER_LANGUAGE_NO_CHANGE : "変更なし",
		CH_PASSWD_EXPAND : "拡張版",
		CH_PASSWD_COLLAPSE : "簡易版",
		CH_PASSWD_HIDDEN : "非表示",
		CH_PASSWD_GETTING_STARTED : "ログオン後にスタートアップ情報を表示",
		CH_PASSWD_PLUGIN : "ログオン後にプラグイン情報を表示",
		NOTICE_TITLE : "OGame Galaxytool - メモ",
		NOTICE_HEADER : "メモの編集",
		NOTICE_HEADER2 : "自分のメモを編集",
		NOTICE_PUBLIC : "公開しますか？",
		NOTICE_YES : "はい",
		NOTICE_NO : "いいえ",
		NOTICE_TEXT : "メモ",
		NOTICE_SAVE : "保存",
		NOTICE_DELETED : "エントリは消去されました",
		NOTICE_SAVED : "エントリは保存されました．",
		NOTICE_RESULTS : "全ての結果",
		NOTICE_USER : "ユーザ",
		NOTICE_DATE : "日付",
		NOTICE_EDIT : "編集",
		NOTICE_DELETE : "消去",
		NOTICE_NEW : "自分のエントリを作成",
		NOTICE_NOTPUBLIC : "メモは非公開．",
		NOTICE_ALL : "全て",
		NOTICE_NONE : "無し",
		NOTICE_SEARCH : "メモを検索",
		NOTICE_SEARCH_SHORT : "検索",
		NOTICE_HITS : "検索結果",
		NOTICE_SHOWRESULTS : "件（ページ当たり）",
		NOTICE_OF : "/",
		NOTICE_NOTHING : "該当するエントリは見つかりませんでした",
		NOTICE_CHARS : "キャラクタ",
		NOTICE_PLAYERNAME : "プレーヤー",
		NOTICE_SHOWALL : "全てのメモを表示",
		REPORTS_TITLE : "OGame Galaxytool - スパイレポート",
		REPORTS_RESOURCES : "資源",
		REPORTS_FLEET : "艦隊",
		REPORTS_DEFENCE : "防衛",
		REPORTS_BUILDINGS : "建造物",
		REPORTS_TECHNOLOGY : "リサーチ",
		REPORTS_MOON : "月",
		REPORTS_SEARCH : "スパイレポートを検索",
		REPORTS_SEARCH_SHORT : "検索",
		REPORTS_HITS : "検索結果",
		REPORTS_NOTHING : "該当するエントリは見つかりませんでした",
		REPORTS_ADDRESS : "座標",
		REPORTS_CURRENTNESS : "最新",
		REPORTS_PLAYERNAME : "プレーヤー名",
		REPORTS_ALLY : "同盟",
		REPORTS_VIEW : "レポートを見る",
		REPORTS_SEARCH_IN : "検索: 銀河",
		REPORTS_FROM_SYSTEM : "システム",
		REPORTS_TO : "-",
		REPORTS_DELETE : "消去",
		REPORTS_DELETED : "エントリは消去されました",
		REPORTS_RESULTS : "件（ページ当たり）",
		REPORTS_OF : "/",
		REPORTS_DATE : "日付",
		REPORTS_DATE_0 : "設定しない",
		REPORTS_DATE_1 : "より古い",
		REPORTS_DATE_2 : "より新しい",
		REPORTS_NOTICES : "メモ",
		REPORTS_AT_LEAST_RESOURCES : "資源（最少）",
		REPORTS_SEARCH_EXTENDED : "詳細検索",
		REPORTS_FLEET_RESIS : "艦隊- スコア",
		REPORTS_DEFENCE_RESIS : "防衛- スコア",
		REPORTS_ALL_RESIS : "スコア合計",
		REPORTS_TECHS : "武/シ/ア",
		REPORTS_UNKNOWN_ENTRIES : "不明なエントリ",
		REPORTS_PARTLY_INSERTED : "一部のみ追加",
		REPORTS_FOR_ALL_RES : "全資源に対する",
		REPORTS_FOR_TF : "デブリフィールドに対する",
		REPORTS_KT : "小型輸送機",
		REPORTS_GT : "大型輸送機",
		REPORTS_SS : "バトルシップ",
		REPORTS_REC : "残骸回収船",
		REPORTS_RAIDABLE : "攻撃可能な惑星のみ表示",
		REPORTS_ALL_RESOURCES : "全ての資源",
		REPORTS_STUFF : "その他",
		REPORTS_SPEEDSIM : "Speedsim を使ってシミュレート",
		REPORTS_DRAGOSIM : "Dragosim を使ってシミュレート",
		REPORTS_STATUS : "ステータス",
		REPORTS_ERROR : "エラー発生",
		REPORTS_OWN_REPORTS : "自分のレポートのみ",
		REPORTS_UPLOAD_BY : "レポートアップロード",
		REPORTS_DEPTH : "レポートの深度",
		REPORTS_FLEET_SCORE : "艦隊ポイント",
		REPORTS_DEFENCE_SCORE : "防衛ポイント",
		REPORTS_HOURS : "時間",
		REPORTS_MAX_RESULTS_HIT : "クエリが &1 以上のヒットを返しました 最初の &1 の結果のみ表示 以下の結果を得るために検索要求を調整してください",
		REPORTS_OSIMULATE : "OSimulateでシミュレート",
		REPORTS_SHOW_ONLY : "絞込み対象",
		REPORTS_SHOW_PLANETS : "惑星",
		REPORTS_SHOW_MOONS : "月",
		REPORTS_OWNER : "レポート所有者",
		STATS_TITLE : "OGame Galaxytool - ランキング",
		STATS_TBLHEAD : "ランキング",
		STATS_RANK : "ランク",
		STATS_PLAYERNAME : "プレーヤー名",
		STATS_ALLYNAME : "同盟タグ",
		STATS_SCORE : "ポイント",
		STATS_FLEET : "艦隊",
		STATS_RESEARCH : "リサーチ",
		STATS_MEMBERS : "メンバー",
		STATS_STATUS : "ステータス",
		STATS_NOTHING : "ステータスはありません",
		STATS_NAP : "不戦同盟",
		STATS_ALLIED : "攻守協力同盟",
		STATS_WAR : "敵対同盟",
		STATS_BOYCOTT : "不干渉同盟",
		STATS_NEUTRAL : "中立同盟",
		STATS_OWN : "所属同盟",
		STATS_WING : "下部同盟",
		STATS_UPDATE : "エントリから",
		STATS_PLAYERSTATS : "プレーヤーランキング",
		STATS_ALLYSTATS : "同盟ランキング",
		STATS_DELETE : "このエントリを消去しますか？",
		STATS_CONFIRM_DELETE : "このエントリを本当に消去しますか？",
		STATS_CHANGE_PLAYER_STATUS : "プレーヤーステータス",
		STATS_CHANGE_ALLIANCE_STATUS : "同盟ステータス",
		STATS_CHANGE_ALLIANCE_STATUS_HINT : "この同盟の全てのメンバに選択したステータスを設定します．以前に設定されたステータスは上書きされます．プレーヤーのステータスはあとで変更可能です．",
		STATS_UNKNOWN : "その他",
		STATS_DETAILS : "詳細",
		STATS_PLAYERSTATUS : "プレーヤーステータス",
		STATS_IGNORE_STATUS : "全て",
		STATS_ACTIVE : "アクティブ",
		STATS_INACTIVE : "7日間不在",
		STATS_BANNED : "アカウント停止",
		STATS_VACATION : "休暇モード",
		STATS_NOOB : "初心者",
		STATS_YES : "はい",
		STATS_NO : "メモ付きの惑星のみ表示",
		STATS_SEARCH : "検索",
		STATS_SHOW_GRAPH : "スコアの分布詳細を表示",
		STATS_LONG_INACTIVE : "28日間不在",
		STATS_STANDARD : "ポイント",
		STATS_MILITARY : "ミリタリーポイント ",
		STATS_ECONOMY : "エコノミーポイント",
		STATS_HONOUR : "名誉ポイント",
		STATS_MILITARY_BUILD : "総合ミリタリーポイント",
		STATS_MILITARY_DESTROYED : "破壊した分のミリタリーポイント ",
		STATS_MILITARY_LOST : "喪失した分のミリタリーポイント ",
		REGISTER_REGISTRATE : "登録",
		REGISTER_LOGINNAME : "ログイン名",
		REGISTER_PASSWORD : "パスワード",
		REGISTER_PASSWORD_CONFIRM : "パスワード（確認用）",
		REGISTER_EMAIL : "Eメール",
		REGISTER_INGAME : "ゲーム内のユーザ名",
		REGISTER_ALLYTAG : "同盟タグ",
		REGISTER_EMAILVERIFICATION : "Eメールアドレス確認",
		REGISTER_EMAILTEXT : "以下のリンクをクリックし，galaxytoolへの登録を確認して下さい．",
		REGISTER_ERROR1 : "そのログイン名は既に使われています．",
		REGISTER_ERROR2 : "Eメールの送付中にエラーが発生しました．管理者に連絡して下さい．",
		REGISTER_ERROR3 : "データベースにデータを送ろうとする最中にエラーが発生しました！",
		REGISTER_INFO1 : "アカウントが生成されました．",
		REGISTER_INFO2 : "登録確認のため，Eメール中のリンクをクリックして下さい．",
		REGISTER_INFO3 : "アカウント確認．管理者は今すぐ有効化して下さい．",
		REGISTER_BUTTON : "メインページに戻る",
		REGISTER_NEW_SUBJECT : "galaxytoolに新ユーザが登録されました",
		REGISTER_NEW_MAILTEXT : "新ユーザが自分自身で登録しました．",
		REGISTER_BACK : "最初のページに戻る",
		REGISTER_MISSING_FIELDS : "全ての項目を入力してください.",
		REGISTER_ERROR4 : "電子メールアドレスが有効ではありません.",
		REGISTER_ERROR5 : "パスワードが一致しません.",
		REGISTER_PWS : "パスワードの複雑性",
		REGISTER_PWS0 : "非常に弱い",
		REGISTER_PWS1 : "弱い",
		REGISTER_PWS2 : "良い",
		REGISTER_PWS3 : "強い",
		REGISTER_PWS4 : "非常に強い",
		REGISTER_EMAIL_USED : "メールアドレスは既に使用されています",
		LOSTPW_TITLE : "パスワード忘れ",
		LOSTPW_INFO2 : "新しいパスワードを生成し，Eメールアドレスに送付しました．",
		LOSTPW_BUTTON1 : "新パスワード発行",
		LOSTPW_BUTTON2 : "メインページに戻る",
		LOSTPW_LOGINNAME : "ログイン名",
		LOSTPW_EMAIL : "Eメール",
		LOSTPW_ERROR1 : "データベースにデータを送ろうとする最中にエラーが発生しました！",
		LOSTPW_ERROR2 : "条件に合うエントリは見つかりませんでした！",
		LOSTPW_ERROR3 : "Eメールの送付中にエラーが発生しました．管理者に連絡して下さい．",
		LOSTPW_EMAIL_SUBJECT : "新しいパスワード",
		LOSTPW_EMAIL_TEXT1 : "Galaxytoolの新しいアカウント",
		LOSTPW_EMAIL_TEXT2 : "ユーザ名",
		LOSTPW_EMAIL_TEXT3 : "パスワード",
		LOSTPW_INFO1 : "あなたのパスワードの再設定リクエストを確認するには電子メールを受信してください.",
		LOSTPW_CONFIRM_RESET_SUBJECT : "パスワードをお忘れですか?",
		LOSTPW_CONFIRM_RESET_MESSAGE : "こんにちわ,\n\nあなたはGalaxytoolのパスワードのリセットをリクエストされた. 新しいパスワードを生成するには次のリンクをクリックしてください:",
		USERINFO_TITLE : "OGame Galaxytool - ユーザ情報",
		USERINFO_NAMES : "全ユーザ",
		USERINFO_DETAIL : "詳細な情報",
		USERINFO_ERROR1 : "そのIDのユーザは存在しません！",
		USERINFO_USERNAME : "ログイン名",
		USERINFO_INGAME : "ゲーム内のユーザ名",
		USERINFO_EMAIL : "Eメール",
		USERINFO_ALLYTAG : "同盟",
		USERINFO_STYLEPATH : "スキン",
		USERINFO_STATUS : "ステータス",
		USERINFO_ACTIVATE : "プレーヤーを有効化",
		USERINFO_LOGINS : "ログイン者数",
		USERINFO_LASTLOGIN : "最後のログイン",
		USERINFO_DATA : "入力されたシステムの情報",
		USERINFO_NODATA : "そのユーザはどのシステムにも入っていません！",
		USERINFO_GALAXY : "銀河",
		USERINFO_SYSTEMS : "システム数",
		USERINFO_IP : "IPアドレス",
		USERINFO_LOGINTIME : "ログイン",
		USERINFO_NOLOGIN : "そのプレーヤーは一度もログインしていません",
		USERINFO_LAST_GALAXYUPDATE : "最近の銀河ビューを更新",
		USERINFO_LAST_PUBLIC_NOTICE : "最近の公開メモ",
		USERINFO_LAST_PRIVATE_NOTICE : "最近の非公開メモ",
		USERINFO_NUMBEROF_PUBLIC_NOTICE : "公開メモ数",
		USERINFO_NUMBEROF_PRIVATE_NOTICE : "非公開メモ数",
		USERINFO_ACTIVATED : "有効アカウント数",
		USERINFO_ACTIVATIONTEXT : "Galaxytoolの管理者があなたのアカウントを有効化しました．\n\nGalaxytoolで楽しんでね！",
		USERINFO_LAST_SUBMIT : "最後のデータを挿入",
		ALLYHISTORY_TITLE : "OGame Galaxytool - 同盟の歴史",
		ALLYHISTORY_TBLHEAD : "過去の概要",
		ALLYHISTORY_PLAYERNAME : "プレーヤー名",
		ALLYHISTORY_ALLYNAME : "同盟",
		ALLYHISTORY_LASTMONTH : "先月",
		ALLYHISTORY_ALL_DATA : "全ての利用可能な情報",
		ALLYHISTORY_SHOW : "ランキングを表示",
		ALLYHISTORY_TIMESPAN : "タイムスパン",
		ALLYHISTORY_PROGESS : "進捗",
		ALLYHISTORY_SCORE : "ポイント",
		ALLYHISTORY_FSCORE : "艦隊ポイント",
		ALLYHISTORY_RSCORE : "リサーチポイント",
		ALLYHISTORY_MEMBER : "メンバ",
		ALLYHISTORY_NOTHING : "該当するエントリは見つかりませんでした",
		ALLYHISTORY_DETAILS : "詳細",
		ALLYHISTORY_SHOW_ADDRESS : "座標",
		ALLYHISTORY_ESCORE : "エコノミーポイント",
		ALLYHISTORY_MSCORE : "ミリタリーポイント ",
		DETAILEDINFO_PLAYERINFO_TITLE : "プレーヤー情報",
		DETAILEDINFO_ALLYINFO_TITLE : "同盟情報",
		DETAILEDINFO_PLAYERINFO_TBLHEAD : "プレーヤー詳細情報",
		DETAILEDINFO_ALLYINFO_TBLHEAD : "同盟詳細情報",
		DETAILEDINFO_NO_ALLIANCE : "なし",
		DETAILEDINFO_SCORE : "ポイント",
		DETAILEDINFO_FLEET : "艦隊ポイント",
		DETAILEDINFO_RESEARCH : "リサーチポイント",
		DETAILEDINFO_RANK : "ランク",
		DETAILEDINFO_POINTS : "ポイント",
		DETAILEDINFO_KNOWN_PLANETS : "判明しているコロニー",
		DETAILEDINFO_MOONS : "判明している月",
		DETAILEDINFO_PHALANX_AREA : "センサー軍団スキャンエリア",
		DETAILEDINFO_NO_PHALANX_AREA : "センサー軍団は一つも見つかりませんでした",
		DETAILEDINFO_NOTICES : "メモ",
		DETAILEDINFO_NO_NOTICES : "メモは一つも見つかりませんでした",
		DETAILEDINFO_PREVIOUS_ALLIANCES : "前の同盟",
		DETAILEDINFO_RESOURCES_PER_HOUR : "1時間の生産量",
		DETAILEDINFO_RESOURCES_PER_DAY : "1日の生産量",
		DETAILEDINFO_RESOURCES_PER_WEEK : "1週間の生産量",
		DETAILEDINFO_RESOURCES_PER_MONTH : "1ヶ月(30日)の生産量",
		DETAILEDINFO_METAL : "メタル",
		DETAILEDINFO_CRYSTAL : "クリスタル",
		DETAILEDINFO_DEUTERIUM : "デューテリウム",
		DETAILEDINFO_UNKNOWN : "不明",
		DETAILEDINFO_SCORE_DISTRIBUTION : "ポイント分配",
		DETAILEDINFO_GENERAL : "詳細",
		DETAILEDINFO_MEMBERS : "メンバ",
		DETAILEDINFO_GRAPHS : "グラフ",
		DETAILEDINFO_RESOURCES : "資源",
		DETAILEDINFO_FLEET_TAB : "艦隊",
		DETAILEDINFO_TECH : "リサーチ",
		DETAILEDINFO_FLEET_DETAIL : "合計値 / 利用可能な全てのレポートにおける（プレーヤーの平均値）",
		DETAILEDINFO_TECH_DETAIL : "全ての利用可能なプレーヤー情報の平均",
		DETAILEDINFO_PLANET_TAB : "惑星",
		DETAILEDINFO_MOON_TAB : "月",
		DETAILEDINFO_ACTIVITIES : "アクティビティ",
		DETAILEDINFO_NODATA : "利用可能なデータはありません．",
		DETAILEDINFO_ACTIVITY_DESCRIPTION : "&1 のアクティビティを表示　集計範囲:",
		DETAILEDINFO_GALAXYVIEWS : "銀河ビュー",
		DETAILEDINFO_SCANS : "スパイ調査",
		DETAILEDINFO_MESSAGES : "プレイヤーメッセージ",
		DETAILEDINFO_COMBATS : "コンバットレポート",
		DETAILEDINFO_ALLYPAGE : "同盟一般情報",
		DETAILEDINFO_MANUAL : "手動挿入",
		DETAILEDINFO_START : "開始日",
		DETAILEDINFO_TO : "から",
		DETAILEDINFO_TODAY : "本日",
		DETAILEDINFO_DATA_RESTRICTION : "まで",
		DETAILEDINFO_WEEKDAY_WEEKEND : "週末",
		DETAILEDINFO_WEEKDAY_WORKINGDAY : "平日",
		DETAILEDINFO_WEEKDAY_MONDAY : "月曜日",
		DETAILEDINFO_WEEKDAY_TUESDAY : "火曜日",
		DETAILEDINFO_WEEKDAY_WEDNESDAY : "水曜日",
		DETAILEDINFO_WEEKDAY_THURSDAY : "木曜日",
		DETAILEDINFO_WEEKDAY_FRIDAY : "金曜日",
		DETAILEDINFO_WEEKDAY_SATURDAY : "土曜日",
		DETAILEDINFO_WEEKDAY_SUNDAY : "日曜日",
		DETAILEDINFO_WEEKDAY_SHORTLENGTH : 3,
		DETAILEDINFO_PLAYER_CURRENTLY_ACTIVE : "プレーヤーが現在アクティブです",
		DETAILEDINFO_PLAYER_MESSAGES : "利用可能なプレイヤーのメッセージ",
		DETAILEDINFO_SHOW : "表示",
		DETAILEDINFO_NONE : "使用不可能",
		DETAILEDINFO_ENTER_MANUALLY : "このプレーヤーのアクティビティを入力してください",
		DETAILEDINFO_PLAYER_SEEN_ON : "プレーヤーはオンラインです",
		DETAILEDINFO_INSERT : "挿入",
		DETAILEDINFO_OGAME_SERVERTIMES : "ご注意：すべての日付と時刻は、OGame Serverの時間（GMT+1）を参照してください!",
		DETAILEDINFO_DAY_VIEW : "24時間表示",
		DETAILEDINFO_WEEK_VIEW : "週単位表示",
		DETAILEDINFO_HOME_PLANET : "ホームワールド",
		DETAILEDINFO_PLANETNAME : "名前",
		DETAILEDINFO_DEFENCE_SCORE : "防衛スコア",
		DETAILEDINFO_DEFENCE_SCORE_TOOLTIP : "防衛スコア = 艦隊 - スコア + リサーチ + エコノミー.<br/>すべてのこれらの統計は、意味のある結果を得るために最新の状態になければなりません!",
		DETAILEDINFO_SCORE_PER_SHIP : "スコア/艦隊",
		DETAILEDINFO_SHIPS : "艦隊の数",
		DETAILEDINFO_DATE_IN_FUTURE : "過去に存在しない時間を維持しない",
		ADMIN_TITLE : "Galaxytoolの管理",
		ADMIN_DISCLAMER : "注意: これらのスクリプトは全て自己責任で動かして下さい！大半のスクリプトはデータの消去を行ないます．",
		ADMIN_INCONSISTENCIES : "データベース上に不整合が発生",
		ADMIN_PLANETS : "スロット0または16以上に惑星が存在",
		ADMIN_GALAXIES : "&1よりも大きい銀河を削除",
		ADMIN_PLAYERS : "OGameのプレーヤーIDを持たないプレーヤーを削除 - これはプレーヤーエントリの重複を引き起こします",
		ADMIN_REPORTS : "既に惑星が存在しない座標のスパイレポートを削除",
		ADMIN_MISC : "その他",
		ADMIN_RESET : "Galaxytoolをリセット（ユーザおよびIPテーブル以外は削除されます）",
		ADMIN_OLD_PLAYERS : "&1日よりも古いプレーヤーのエントリを削除",
		ADMIN_OLD_REPORTS : "&1日よりも古いスパイレポートを削除",
		ADMIN_LOADING : "ページがロードされるまでこのウィンドウを閉じないで下さい．",
		ADMIN_STATUS : "リクエストステータス",
		ADMIN_SELECTION : "最低限一つのエントリを選択して下さい",
		ADMIN_SAFETY : "本当にこれらのスクリプトを動かしますか？",
		ADMIN_DONE : "完了",
		ADMIN_NOTBD : "何も行なわれません",
		ADMIN_OLD_GALAXIES : "&1日よりも古い銀河ビューを削除",
		ADMIN_UNUSED_PLAYERS : "一つも銀河ビューを生成しないプレーヤーを削除",
		ADMIN_OLD_ACTIVITIES : "&1 日よりも古いプレーヤーのアクティビティを削除",
		ADMIN_OLD_COMBATS : "&1 日よりも古いコンバットレポートを削除",
		ADMIN_OLD_INGAME_MSG : "&1 日よりも古いゲーム内メッセージを削除",
		ADMIN_OGAME_API : "GalaxytoolにOGameから公開データをロードします",
		ADMIN_OGAME_ALL_DATA : "全ての利用可能な情報",
		ADMIN_OGAME_GALAXY_DATA : "銀河の閲覧",
		ADMIN_OGAME_STATISTICS_DATA : "ランキング",
		ERRORPAGE_PAGEFORWARD : "自動的にジャンプできなければ，ここをクリックして下さい．",
		ERRORPAGE_PERMISSION_DENIED : "このページに入る権限がありません。ここをクリックして戻ってください。",
		FLEETS_TITLE : "OGame Galaxytool - 艦隊動向",
		FLEETS_ACTUAL_FLEETS : "現在の艦隊動向",
		FLEETS_YES : "はい",
		FLEETS_NO : "メモ付きの惑星のみ表示",
		FLEETS_DETAILS : "詳細",
		FLEETS_MISSION_EXPEDITION : "探索",
		FLEETS_MISSION_COLONIZATION : "植民地化",
		FLEETS_MISSION_RECYCLE : "回収",
		FLEETS_MISSION_TRANSPORT : "輸送",
		FLEETS_MISSION_DEPLOYMENT : "配備",
		FLEETS_MISSION_ESPIONAGE : "スパイ活動",
		FLEETS_MISSION_ACS_DEFEND : "ACS防御",
		FLEETS_MISSION_ATTACK : "攻撃",
		FLEETS_MISSION_ACS_ATTACK : "ACS攻撃",
		FLEETS_MISSION_MOON_DESTRUCTION : "月破壊",
		FLEETS_MISSION_MISSILE_ATTACK : "ミサイル攻撃",
		FLEETS_NO_DATA : "該当するデータは見つかりませんでした.",
		FLEETS_FLEET : "艦隊",
		FLEETS_ALL_FLEETS : "すべての艦隊動向を表示",
		COMBAT_REPORT_OUDATED_GALAXYVIEW : "あなたの銀河データは古いです. 戦闘の起点と目標は、最初の座標をアクセスしてください!",
		MESSAGES_TITLE : "OGame Galaxytool - OGameメッセージ",
		MESSAGES_PLAYERNAME : "プレーヤーの名前",
		MESSAGES_SUBJECT : "件名",
		MESSAGES_DATE : "日付",
		MESSAGES_FILTER : "フィルタ",
		MESSAGES_DELETE : "メッセージを削除",
		MESSAGES_PUBLISH_DETAIL : "そのプレイヤーの注意事項を追加して、メッセージを公開する.",
		MESSAGES_PUBLISH_HEADER : "&sender は、&date に &recipient へメッセージを送信します：\n\n &message ",
		MESSAGES_PLAYER_FILTER : "プレイヤーのためのメッセージ:",
		MESSAGES_CONTENT : "コンテンツ",
		COMBATS_TITLE : "OGame Galaxytool - コンバットレポート",
		COMBATS_ATTACKER : "攻撃側",
		COMBATS_DEFENDER : "防御側",
		COMBATS_DATE : "日付",
		COMBATS_OWNER : "所有者",
		COMBATS_WINNER : "勝者",
		COMBATS_COMBATREPORT : "コンバットレポート",
		COMBATS_COMBAT_AT : "戦闘で対戦しました",
		COMBATS_LOST_UNITS : "消失ユニット",
		COMBATS_LOOT : "略奪",
		COMBATS_DEBRIS : "残骸フィールド",
		COMBATS_AND : "と",
		COMBATS_PUBLISH : "このレポートを公開する",
		COMBATS_UNPUBLISH : "この報告書の共有解除（再びそれは非公開になります）",
		COMBATS_DELETE : "レポートの削除",
		COMBATS_CHECK_ALL : "すべて選択",
		COMBATS_UNCHECK_ALL : "すべて解除",
		COMBATS_WITH_SELECTED : "選択された状態",
		COMBATS_PUBLIC_REPORTS : "公開レポート",
		COMBATS_YES : "はい",
		COMBATS_NO : "メモ付きの惑星のみ表示",
		COMBATS_SEARCH_OPTIONS : "検索オプション",
		COMBATS_SEARCH : "実行",
		COMBATS_RESET : "リセット",
		COMBATS_COORDINATES : "座標",
		COMBATS_INVALID_GALAXY_ENTERED : "無効な銀河が入力されました",
		COMBATS_INVALID_SYSTEM_ENTERED : "無効なシステムが入力されました",
		COMBATS_INVALID_PLANET_ENTERED : "無効な惑星が入力されました",
		COMBATS_GALAXY_FROM_TO : "銀河",
		COMBATS_SYSTEM_FROM_TO : "システム",
		COMBATS_PLANET_FROM_TO : "惑星",
		COMBATS_APPLY : "適用",
		COMBATS_COMBAT_SUMMARY : "コンバットレポートの要約",
		COMBATS_DOWNLOAD_CSV : "CSVファイルとしてダウンロード",
		REPORT_ARCHIVE_TITLE : "レポートアーカイブ",
		REPORT_ARCHIVE_COORDINATES : "座標",
		REPORT_ARCHIVE_SCANTIME : "時間をスキャン",
		REPORT_ARCHIVE_DELETE : "これらのエントリを削除",
		REPORT_ARCHIVE_CONFIRM_DELETE : "あなたは本当にこれらのエントリを削除しますか?",
		REPORT_ARCHIVE_GALAXY : "銀河",
		REPORT_ARCHIVE_SYSTEM : "システム",
		REPORT_ARCHIVE_PLANET : "惑星",
		REPORT_ARCHIVE_MOON : "月",
		REPORT_ARCHIVE_DETAILS : "詳細",
		REPORT_ARCHIVE_RESOURCES : "1時間の生産量",
		REPORT_ARCHIVE_HEADER_RESOURCES : "資源",
		REPORT_ARCHIVE_DETAILS_FOR : "&1 [&2] (&3) に対するレポートアーカイブ",
		REPORT_ARCHIVE_FLEET_CARGO : "艦隊の貨物輸送能力",
		REPORT_ARCHIVE_IRAK_RANGE : "星間ミサイルの範囲",
		REPORT_ARCHIVE_CHART_TYPE : "グラフの種類",
		INSTALL_TITLE : "インストールを行うGalaxytoolのバージョン",
		INSTALL_PROGRESS : "全体の進行状況",
		INSTALL_STEP : "手順",
		INSTALL_CONTINUE : "続ける",
		INSTALL_VALIDATE : "検証",
		INSTALL_STEP1 : "ようこそ",
		INSTALL_STEP2 : "書き込み可能チェック",
		INSTALL_STEP3 : "データベースの設定",
		INSTALL_STEP4 : "OGameの設定",
		INSTALL_STEP5 : "Galaxytoolの設定",
		INSTALL_STEP6 : "管理者パスワード",
		INSTALL_STEP7 : "Galaxytoolをインストールします",
		INSTALL_STEP8 : "インストール完了",
		INSTALL_FILE_DELETE_CHECK : "あなたのウェブサーバからinstall.phpとupdate.phpを削除してください",
		INSTALL_STEP1_PHP_FAILED : "あなたのPHPバージョン &1は、このGalaxytoolバージョンで動作しません",
		INSTALL_STEP1_FOPEN_FAILED : "あなたのPHPのバージョンは、FOPEN() コマンドを使用してWebページを開くことはできません これはOGame APIには必須となります",
		INSTALL_STEP1_WELCOME : "Galaxytoolのインストールウィザードへようこそ あなたにはGalaxytoolのインストールに関する案内が提供されます",
		INSTALL_STEP2_DESCRIPTION : "あなたのconfig.phpとattributes.phpファイルは書き込み権限が有効になっていることを確認してください",
		INSTALL_STEP2_DESCRIPTION2 : "あなたがわからない場合は、実現する方法をここで見てご確認ください: &1",
		INSTALL_STEP2_FILE_NOT_WRITEABLE : "ファイルが書込み不可能",
		INSTALL_STEP3_SERVER : "データベースサーバ",
		INSTALL_STEP3_USERNAME : "ユーザ名",
		INSTALL_STEP3_PASSWORD : "パスワード",
		INSTALL_STEP3_DBNAME : "データベース名",
		INSTALL_STEP3_PREFIX : "テーブル名 prefix",
		INSTALL_STEP3_ENTER_PREFIX : "例 mytool_",
		INSTALL_STEP3_ENTER_SERVER : "サーバのアドレスを入力します システム管理者を必要に応じてお問い合わせください 通常正しい値はlocalhostです",
		INSTALL_STEP3_ENTER_USERNAME : "データベースアクセス用のユーザ名を入力してください",
		INSTALL_STEP3_ENTER_PASSWORD : "データベースアクセス用のパスワードを入力してください",
		INSTALL_STEP3_ENTER_DBNAME : "インストールに使用されなければならないデータベース名(存在しなければなりません)を入力してください",
		INSTALL_STEP3_CONNECT_FAILED : "データベースサーバーへの接続を確立できませんでした",
		INSTALL_STEP3_DB_FAILED : "データベース &1 がみつかりません",
		INSTALL_STEP3_MYSQL_VERSION_FAILED : "MySQL バージョン &1 は、このGalaxytoolバージョンで動作しません",
		INSTALL_STEP4_URL : "OGameのURL",
		OGAME_URL_DETAILS : "あなたがOGameにログオンしているときに表示される任意のURLを入力してください そのURLに基づいてツールがGalaxytoolbarなしにGalaxytoolにデータを埋めるために使用することができますOGame APIのアドレスを取得します このAPIはOGameのバージョン4.1で導入されました",
		INSTALL_STEP4_UNIVERSE : "OGameの宇宙",
		INSTALL_STEP4_DEF_TO_DEBRIS : "防衛のデブリ化",
		INSTALL_STEP4_DEBRIS_RATE : "デブリレート",
		INSTALL_STEP4_SPEED_RATE : "速度レート",
		INSTALL_STEP4_ENTER_UNIVERSE : "あなたのOGameの宇宙の名前または番号を(大文字小文字を区別)を入力します",
		INSTALL_STEP4_UNIVERSE_MISSING : "あなたの宇宙を定義する必要があります",
		INSTALL_STEP4_ENTER_URL : "あなたのOGame宇宙アドレスを入力してください",
		INSTALL_STEP4_URL_MISSING : "あなたのOGameアドレスを定義する必要があります",
		INSTALL_STEP4_URL_CHECK_FAILED : "&1 でOGame APIを見つけることができませんでした",
		INSTALL_STEP4_GETSETTINGS : "Fetch settings",
		INSTALL_STEP5_TOOLNAME : "Galaxytool名",
		INSTALL_STEP5_ENTER_TOOLNAME : "これはあなたのGalaxytoolを識別するためのログオンページで表示される名前です",
		INSTALL_STEP5_LANGUAGE : "既定の言語",
		INSTALL_STEP5_EMAIL_TO : "Emailの送信先",
		INSTALL_STEP5_ENTER_EMAIL_TO : "あなたが登録に関する通知を受信したいメールアドレスを入力します",
		INSTALL_STEP5_EMAIL_FROM : "Emailの送信元",
		INSTALL_STEP5_ENTER_EMAIL_FROM : "このメールアドレスはGalaxytoolから送信されるすべてのメールに返信として表示されます",
		INSTALL_STEP5_USE_PHPMAILER : "PHPMailerを使用する",
		INSTALL_STEP5_MAXSHOUTS : "シャウトボックスの最大エントリ数",
		INSTALL_STEP5_ENTER_USE_PHPMAILER : "サーバは、デフォルトで電子メールを送信するサポートされていない場合はPHPMailerを使用します",
		INSTALL_PHPMAILER_HOST : "SMPTホスト",
		INSTALL_PHPMAILER_HOST_EXAMPLE : "例 smtp.provider.com",
		INSTALL_PHPMAILER_USER : "SMPTユーザー名",
		INSTALL_PHPMAILER_USER_EXAMPLE : "例 user@provider.dcom",
		INSTALL_PHPMAILER_PASS : "SMPTパスワード",
		INSTALL_PHPMAILER_SECURE : "認証方法 (例 ssl)",
		INSTALL_PHPMAILER_PORT : "SMTPポート",
		INSTALL_STEP6_INTRO : "インストール後Galaxytoolに最初のログオンに使用する必要があります<strong>admin</strong> アカウントのパスワードを定義してくださいい",
		INSTALL_STEP7_CONFIG : "Configuration fileが作成されました",
		INSTALL_STEP7_CONFIG_FAILED : "Configuration fileが作成できません",
		INSTALL_STEP7_ATTRIBUTES : "Attributes fileが作成されました",
		INSTALL_STEP7_ATTRIBUTES_FAILED : "Attributes fileが作成できません",
		INSTALL_STEP7_CREATED_TABLES : "データーベーステーブルが作成されました",
		INSTALL_STEP8_INTRO : "あなたは正常にGalaxytoolをインストールしました!",
		INSTALL_STEP8_LOAD_DATA : "OGameデータをダウンロード中...",
		INSTALL_STEP8_LOAD_DATA_FINISHED : "OGameデータのダウンロードが終了しました",
		INSTALL_STEP8_DELETE_FILE : "今、あなたのWebサーバからインストールファイル install.php と update.phpを削除する必要があります",
		INSTALL_STEP8_LOGON : "<strong>admin</strong>ユーザーは、以前に定義したパスワードでログインしてください",
		UPDATE_START : "バージョン &1へのアップデートの開始",
		UPDATE_STEP_DONE : "完了",
		UPDATE_TITLE : "Galaxytoolの更新 バージョン",
		UPDATE_STEP1_WELCOME : "Galaxytoolの更新ウィザードへようこそ あなたにはGalaxytoolアップデートの案内が提供されます",
		UPDATE_STEP1_BACKUP_FILES : "最初のステップとして、あなたの <strong>config</strong> フォルダーのバックアップを作成! あなたはエラーの場合には設定内容を入れなおす必要があります",
		UPDATE_STEP1_BACKUP_DB : "次に、データベースの <a href=\"http://www.ehow.com/how_2036600_create-database-php.html\">backup</a> を作成",
		UPDATE_STEP1_PROCEED : "バックアップが行われたら、アップデートを続行することができます",
		UPDATE_STEP1 : "ようこそ",
		UPDATE_STEP2 : "Galaxytoolの設定",
		UPDATE_STEP2_OLD_VERSION : "以前のGalaxytoolバージョン",
		UPDATE_STEP3 : "Galaxytoolを更新",
		UPDATE_STEP3_UPDATE_RUNNING : "実行を更新中 しばらくお待ちください...",
		UPDATE_STEP4 : "アップデート完了",
		UPDATE_STEP4_INTRO : "Galaxytoolが正常に更新されました!",
		UPDATE_STEP4_UPDATE_DONE : "アップデートの手順が行われました",
		UPDATE_FAILED : "更新に失敗",
		GALAXYTOOL_DUMMY_TEXT : "dummy"
	})
);