define(
	({
		REPORT_WHEN : "في",
		RESOURCES_ON : "موارد على الكوكب الأصلي",
		PLAYER_BANNED : "م",
		PLAYER_VACATION_MODE : "ع",
		PLAYER_NOOB : "ض",
		PLAYER_INACTIVE : "خ",
		PLAYER_LONG_INACTIVE : "خا",
		PLAYER_OUTLAW : "ق",
		L_USERNAME : "اسم التسجيل",
		L_PASSWORD : "كلمة السر",
		L_LOGINFAILURE : ".اسم التسجيل أو كلمة السر خطأ أو لم يتم تفعيل حسابك ",
		L_TOKENFAILURE : "مفتاح التسجيل خطأ أو لم يتم تفعيل حسابك",
		L_LOGINTEXT : "الرجاء التسجيل",
		L_LANGUAGE : ": اللغات المتوفرة",
		L_TIMEOUT : "! تم تسجيل الخروج",
		L_REGISTER : "تسجيل لاول مرة",
		L_PWLOST : "كلمة السر مفقودة",
		INDEX_TITLE : "أوجيم جالكسيتول - النظرة العامة",
		INDEX_INFO : "معلومات",
		INDEX_ENTRIES : "مجموع الأنظمة",
		INDEX_ENTRIES_LASTWEEK : "أنظمة جديدة الأسبوع السابق",
		INDEX_ENTRIES_TO_OLD : "أنظمة قديمة أكثر من شهر",
		INDEX_REGISTERED_USERS : "اللاعبين المسجلين",
		INDEX_PAGEFORWARD : "إذا كان المتصفح لا يقبل تغير الصفحة التلقائي الرجاء استعمال هذا الرابط",
		INDEX_NOTICES : "ملاحظات",
		INDEX_PLAYERS : "احصائيات اللاعبين",
		INDEX_ALLIES : "احصائيات التحالفات",
		INDEX_REPORTS : "تقارير التجسس",
		INDEX_VERSION : "أحدث نسخة للتحميل",
		INDEX_LATEST_VERSION : "لا توجد نسخة أحدث",
		INDEX_SHOUTBOX : "صندوق الدردشة",
		INDEX_NOENTRY : "لا توجد محادثات حتى الآن",
		INDEX_COMMENT : "Chat",
		INDEX_INSERT : "أضافة بيانات",
		INDEX_UMOD : "لاعب في عطلة",
		INDEX_NO_MOONS : "عدد الأقمار",
		INDEX_NO_EMPTY_SYSTEMS : "عدد الأنظمة الفارغة",
		INDEX_NO_FULL_SYSTEMS : "عدد الأنظمة المكتملة",
		INDEX_NO_TARGETS : "عدد الأهداف المحتملة",
		INDEX_USERINFO : "أرقام المستخدمين",
		INDEX_ONLINE : "متصل الآن",
		INDEX_TODAY : "أتصل اليوم",
		INDEX_ALL : "مجموع الاتصال",
		GENERAL_LOAD_FORM : "تحميل البيانات",
		GENERAL_SAVE_FORM : "تسجيل البيانات",
		GENERAL_SAVE_AS_TEXT : "سجل بإسم",
		GENERAL_SAVE : "سجل",
		INDEX_USERMANAGEMENT : "النظرة العامة للتفعيل",
		INDEX_NEEDADMIN : "حسابات لم يتم قبولها",
		INDEX_NEEDEMAIL : "حسابات لم يتم تفعيلها",
		INDEX_TOOLBAR_INFO : "معلومات عن جالكسيتول",
		INDEX_TOOLBAR_URL : "رابط جالكسيتول",
		INDEX_TOOLBAR_VERSION_REQUIRED : "يتطلب نسخة جالكسيتول",
		INDEX_TOOLBAR_INSTALL_GUIDE : "ارشادات تنصيب الأداة",
		INDEX_TOOLBAR_TOKEN : "مفتاح التسجيل",
		INDEX_TOOLBAR_NEW_TOKEN : "أحصل على مفتاح تسجيل جديد",
		INDEX_PLAYERS_WITH_N_PLANETS : "لاعبون يمتلكون أكثر من  &1 كوكب",
		INDEX_GETTING_STARTED : "التعرف على الأداة",
		INDEX_GETTING_STARTED1 : "مرحبا بك في الأداة جالكسيتول",
		INDEX_GETTING_STARTED2 : "الأداة ستساعدك على تحليل كل ما يجري في عالمك  &1",
		INDEX_GETTING_STARTED3 : "قبل البدء فعلا في تحليل المعلومات يجب اضافتها أولا لقاعدة البيانات . حتى يتم ذلك أنت تحتاج بلجين لمتصفحك مثل &1 لفيرفوكس .",
		INDEX_GETTING_STARTED4 : "بعد تنصيب البلجين، يمكنك تصفح اللعبة كالعادة عندها سترى نافذة صغيرة تخبرك أنه تم تقل البيانات و ارسالها لجالكسيتول ",
		INDEX_GETTING_STARTED5 : "عندما يتم أرسل البيانات بنجاح يمكنك البدء بتحليل معلومات اللاعبين ، أين تقع كواكبهم ، كم عددها ، تقارير التجسس لكواكبهم ، يمكنك أيضا متابعة أوقات اتصالهم",
		INDEX_GETTING_STARTED6 : ".كما يمكنك أيضا متابعة تطورك عندما تقارن نفسك مع منافسيك أو بمراقبة تقارير هجماتك لتعرف ما تحصلت عليه من الموارد في فترة معينة",
		INDEX_GETTING_WIKIPAGE : "هناك العديد من المميزات الأخرى لأداة جالكسيتول.",
		INDEX_GETTING_WIKIPAGE2 : "يمكنك التعرف عليهم في صفحة ويكي .",
		INDEX_GETTING_BOARD : ": لأي أفكار أو أقتراحات تفضل بزيارة منتدانا",
		INDEX_GETTING_CHAT1 : "أو زرنا على غرفة الشات",
		INDEX_GETTING_CHAT2 : "لا يمكننا التواجد على مدار اليوم لكننا نقضي معظم أوقات فرغنا هناك",
		INDEX_CLOSE : "أغلق",
		INDEX_LOGIN : "تسجيل الدخول",
		GENERAL_REQUIRED_FIELDS : "الرجاء ملء جميع الخانات المطلوبة",
		INDEX_MESSAGES : "الرسائل",
		INDEX_EXAMPLE : "مثال",
		INDEX_INVALID_DATA : "خطأ في البيانات",
		GENERAL_COLUMN_HIDE_TITLE : "التحكم بالأعمدة",
		GENERAL_COLUMN_HIDE_INFO : "الرجاء اختيار الأعمدة التي تود أن تراها في الجدول",
		GENERAL_ENTRIES_DELETED : "&1 تم حذف المعلومات",
		GENERAL_APPLY : "تفعيل",
		STARTPAGE_GALAXYTOOL_DESCR : "<em>جالكسيتول</em> هي أداة للعبة المتصفح الشهيرة أوجيم.",
		GENERAL_OVERWRITE : "إعادة ادخال البيانات المكررة ؟",
		GENERAL_OVERWRITE_QUESTION : "أهل أنت متأكد ؟",
		INDEX_OWN_LOGINS : "عدد مرات دخولك",
		GENERAL_OPEN_IN_NEW_WINDOW : "افتح الرابط في نافذة جديدة",
		GENERAL_UNIT_OF_MEASURE_DAYS : "Days",
		PROGRAM_NAME : "أداة جالكسيتول أوجيم",
		SHORTNAME : "جالكسيتول",
		BACK_INDEX : "العودة للصفحة الأساسية",
		UNIVERSE : "عالم",
		MENU_INFO_LINKS : "معلومات",
		MENU_PAGE : "النظرة العامة",
		MENU_DB_SEARCH : "البحث في قاعدة البيانات",
		MENU_DB_NOTICES : "البحث في الملاحظات",
		MENU_DB_REPORTS : "البحث في التقارير",
		MENU_GALAXYVIEW : "المجره",
		MENU_STATISTICS : "ترتيب اللاعبين",
		MENU_ALLYHISTORY : "متابعة التطور",
		MENU_FLEET_MOVEMENTS : "تحركات الأساطيل",
		MENU_COMBAT_REPORTS : "تقارير المعارك",
		MENU_MESSAGES : "الرسائل الخاصة",
		MENU_OPTION_LINKS : "خيارات",
		MENU_DB_REFRESH : "أضف لقاعدة البيانات",
		MENU_NOTICES : "ملاحظات",
		MENU_DB_STATUS : "حالة قاعدة البيانات",
		MENU_USEROPTIONS : "التصرف بالمستخدمين",
		MENU_USEROPTIONS2 : "اختيارات المستخدمين",
		MENU_USEROPTIONS3 : "معلومات المستخدم",
		MENU_ADMIN : "قسم الادارة",
		MENU_LOGOUT : "الخروج من الموقع",
		MENU_STUFF : "متنوعات",
		MENU_FORUM_THREAD : "منتدى المصممين",
		MENU_DOWNLOADPAGE : "صفحة تحميل البرنامج",
		MENU_LANGUAGE : "اللغة",
		MENU_HELP : "المساعدة",
		MENU_TOOLOPTIONS : "خيارات جالكسيتول",
		PARSER_INFO1 : "تم أضافته لقاعدة البيانات",
		PARSER_ERROR1 : "خطأ في محاولة ادخال الاحداثيات التاليه:",
		PARSER_ERROR2 : "لا يمكن ايجاد قاعدة البيانات !",
		PARSER_ERROR3 : "لا يمكن التواصل مع السرفر !",
		PARSER_WRONG_UNIVERSE : "عالم خاطيء - حاليا: \"&1\"  المتوقع: \"&2\"",
		SHOW_TITLE : "صفحة البحث لجالكسيتول",
		SHOW_SEARCH : "البحث في قاعدة البيانات",
		SHOW_ALLYSYMBOL : "رمز التحالف",
		SHOW_PLAYERNAME : "اسم اللاعب",
		SHOW_MOONS : "فقط الكواكب بالاقمار",
		SHOW_NOTICES : "فقط الكواكب بملاحظات",
		SHOW_COLONIES : "فقط الكواكب الصالحة للاستعمار",
		SHOW_YES : "نعم",
		SHOW_NO : "لا",
		SHOW_SEARCHRANGE : "المدى",
		SHOW_SEARCH_IN : "البحث في المجرة",
		SHOW_FROM_SYSTEM : "من النظام",
		SHOW_FROM_PLANET : "من الكوكب خانة",
		SHOW_TO : "الى",
		SHOW_DESCRIPTION : "You can use wildcards * for player or alliance names. So you can find all players with &quot;name&quot; in their name.<br />Only fill those fields you want to specify.",
		SHOW_SORT_BY : "رتب حسب",
		SHOW_GALASYSTEM : "مجرة / نظام",
		SHOW_ALLYNAME : "اسم التحالف",
		SHOW_SEARCHBUTTON : "ابحث",
		SHOW_ADDRESS : "العنوان",
		SHOW_ALLYSORT : "تحالف",
		SHOW_PLANET : "اسم الكوكب",
		SHOW_STATUS : "حالة",
		SHOW_CURRENTNESS : "حدث لاخر مرة",
		SHOW_PLAYER_STATUS : "حالة اللاعب",
		SHOW_PLAYER_STATUS1 : "الكل",
		SHOW_PLAYER_STATUS2 : "أهداف محتملة",
		SHOW_PLAYER_STATUS3 : "خامل",
		SHOW_HITS : "النتائج",
		SHOW_OF : "ل ",
		SHOW_ASC : "تصاعديا",
		SHOW_DESC : "تنازليا",
		SHOW_RESULTS : "عدد النتائج في الصفحة",
		SHOW_MOON : "قمر",
		SHOW_UKMOONSIZE : "مجهول",
		SHOW_DF : "أنقاض",
		SHOW_DF_LONG : "ميدان أنقاض",
		SHOW_METAL : "م",
		SHOW_METAL_LONG : "معدن",
		SHOW_CRYSTAL : "ب",
		SHOW_CRYSTAL_LONG : "بلور",
		SHOW_BOTH : "الأثنين معا",
		SHOW_AT_LEAST : "(على الأقل)",
		SHOW_DATE : "تاريخ",
		SHOW_DATE_0 : "غير مهم",
		SHOW_DATE_1 : "أقدم من",
		SHOW_DATE_2 : "أجدد من",
		SHOW_RANK : "ترتيب",
		SHOW_FRANK : "ترتيب الأسطول",
		SHOW_MEMBERS : "الأعضاء",
		SHOW_NOTRANKED : "معلومات غير موجودة",
		SHOW_NOTICERES : "ملاحظات",
		SHOW_REPORTS : "فقط كوكب باقمار",
		SHOW_REPORTS_SHORT : "تقارير التجسس",
		SHOW_NOTHING : "لا نتائج موجودة",
		SHOW_ALLIANCE_STATUS : "حالة التحالف",
		SHOW_NO_STATUS : "بدون حالة",
		SHOW_NAP : "لا هجوم",
		SHOW_ALLIED : "حليف",
		SHOW_WAR : "في حرب",
		SHOW_BOYCOTT : "مقاطع",
		SHOW_NEUTRAL : "محايد",
		SHOW_OWN : "تحالفك",
		SHOW_WING : "جناح",
		SHOW_EXT_OPTIONS1 : "المزيد من الخيارات للمدى، الترتيب ، التاريخ ، أو ميدان الأنقاض",
		SHOW_EXT_OPTIONS2 : "المزيد من الخيارات للمستعمرات ، الأقمار، التقارير ، الملاحظات ، حالة اللاعبين أو الحالة الدبلوماسية",
		SHOW_EXT_OPTIONS3 : "المزيد من الخيارات لتنظيم النتائج",
		SHOW_EXTENDED : "بحث متقدم",
		SHOW_MOON_SELECTION : "كوكب بقمر",
		SHOW_REPORT_SELECTION : "كوكب بتقرير تجسس",
		SHOW_FILTER_BY : "اقصاء من القائمة",
		SHOW_FILTER_NONE : "لا أحد",
		SHOW_PLAYERS_WITHOUT_PROGRESS : "Show players without score changes within the last few days",
		STATUS_TITLE : "أوجيم جالكسيتول - الحالة العامة",
		STATUS_DB_STATUS : "حالة القاعدة",
		STATUS_COLOR : "الألوان",
		STATUS_AGE1 : "بيانات من يوم",
		STATUS_AGE2 : "بيانات من يومين",
		STATUS_AGE3 : "بيانات من ٤ لسبعة أيام",
		STATUS_AGE4 : "بيانات من أسبوع لأسبوعين",
		STATUS_AGE5 : "بيانات من أسبوعين لشهر",
		STATUS_AGE6 : "بيانات قديمة أكثر من شهر",
		STATUS_AGE7 : "بدون بيانات",
		STATUS_ON : "مفعل",
		STYLES_COLOR1 : "لون ١",
		STYLES_COLOR2 : "لون ٢",
		STYLES_COLOR3 : "لون ٣",
		STYLES_COLOR4 : "لون ٤",
		STYLES_COLOR5 : "لون ٥",
		STYLES_COLOR6 : "لون ٦",
		STYLES_COLOR7 : "لون ٧",
		STATUS_DB_LEGEND : "معلومات",
		STATUS_GALAXY : "نظرة المجرة",
		USER_TITLE : "التصرف بالأعضاء",
		USER_NAMES : "عضو",
		USER_ERROR : "خطأ",
		USER_NEWUSER : "عضو جديد",
		USER_OPTIONS : "خيارات",
		USER_USERNAME : "اسم العضو",
		USER_PASSWORD : "كلمة السر",
		USER_PASSWORD_CONFIRM : "تأكيد كلمة السر",
		USER_GALAXY : "مجرة",
		USER_SEARCH : "بحث",
		USER_INSERT : "أضف",
		USER_DELETE : "حذف",
		USER_DELETE_ENTRY : "هل تريد حذف العضو",
		USER_STATUS : "رؤية الحالة",
		USER_STYLES : "تعديل التصميم",
		USER_SUBMIT : "تفعيل",
		USER_RESET : "أفرغ الخانات",
		USER_YES : "نعم",
		USER_NO : "لا",
		USER_STYLEPATH : "رابط styles.css",
		USER_PROBES : "شاهد أو أضف تقرير التجسس",
		USER_EMAIL : "بريد إلكتروني",
		USER_ERROR1 : "خطأ في كلمة السر أو بريد خاطيء",
		USER_ERROR2 : "بريد ألكتوني خاطيء",
		USER_INGAME : "الأسم في اللعبة",
		USER_ALLYTAG : "رمز التحالف",
		USER_ALLYHISTORY : "متابعة التطور",
		USER_DIPLOMATIC : "تغير الحالة الدبلوماسية",
		USER_STATSPAGE : "عدد البيانات في صفحة الترتيب",
		USER_LINKS : "روابط",
		USER_LINKS2 : "شكل:<br>text;url<br>text2;url2<br>text3;url3",
		USER_EXPORT_TITLE : "استعمال ألوان (BB Codes)",
		USER_BB_COORDINATES : "احداثيات",
		USER_BB_MOON : "قمر",
		USER_BB_DEBRIS : "ميدان أنقاض",
		USER_BB_ALLY : "اسم التحالف",
		USER_BB_ALLYDETAILS : "تفاصيل التحالف",
		USER_BB_PLAYERNAME : "اسم اللاعب",
		USER_BB_BANNED : "محظور",
		USER_BB_VACATION : "وضع عطله",
		USER_BB_NOOB : "ضعيف",
		USER_BB_INACTIVE : "خامل",
		USER_BB_LONGINACTIVE : "خامل لمدة طويلة",
		USER_DELETION : "حذف",
		USER_FLEETINFO : "معلومات الأسطول",
		USER_ACTIVITIES : "نشاطات اللاعب",
		USER_MAINTENANCE : "صيانة الأداة",
		USER_MANAGEMENT : "التصرف بالمستخدمين",
		USER_DELETE_MY_COMBAT_REPORTS : "حذف تقارير هجومك",
		USER_DELETE_MY_MESSAGES : "حذف رسائلك الخاصة",
		USER_DELETE_MY_FLEETMOVES : "حذف حركات أسطولك",
		USER_DELETE_MY_COMBAT_REPORTS_LIMITED : "حذف تقارير هجومك القديمة لاكثر من &1 يوم",
		USER_DELETE_MY_MESSAGES_LIMITED : "حذف رسائلك القديمة لاكثر من &1 يوم",
		USER_TABLE_ENTRIES : "عدد النتائج بالصفحة",
		USER_EXISTS : "العضو موجود",
		USER_BB_OUTLAW : "قطع طريق",
		USER_INVALID_URL : "الرابط &1 لايعمل  - سيتم اهماله",
		VIEW_TITLE : "أوجيم جالكسيتول - رؤية المجرة",
		VIEW_NODATA : "لا تواجد أي بيانات",
		VIEW_GALAXY : "Galaxy",
		VIEW_SYSTEM : "النظام الشمسي",
		VIEW_POSITION : "الخانة",
		VIEW_PLANET : "كوكب",
		VIEW_MOON : "قمر",
		VIEW_TF : "أنقاض",
		VIEW_PLAYER : "اللاعب",
		VIEW_PLAYER_ADD : "(ترتيب/حالة)",
		VIEW_ALLY : "تحالف",
		VIEW_ALLY_ADD : "(ترتيب/عضو)",
		VIEW_METAL : "م",
		VIEW_CRYSTAL : "ب",
		VIEW_COLONISED : "كواكب غير مستعمرة",
		VIEW_UKMOONSIZE : "مجهول",
		VIEW_BACK : "عودة",
		VIEW_NOTICE : "ملاحظات",
		VIEW_REPORTS : "تقارير",
		VIEW_MOONPHALANX : "هذا النظام مكشوف من الأقمار التالية",
		VIEW_NOMOONS : "لا توجد أقمار",
		VIEW_IRAKS : "الكواكب التالية تصل صواريخها العابرة لهذا النظام",
		VIEW_NOIRAKS : "لا توجد صواريخ عابرة",
		VIEW_MOON_DESTROY_CHANCE : "احتمال تدمير القمر",
		VIEW_CHANCE_WITH_ONE : "احتمال التدمير بنجمة واحدة",
		VIEW_CHANCE_WITH_N : "الاحتمال ب",
		VIEW_DEATH_STARS : "نجوم الموت",
		VIEW_DS_DESTROY_CHANCE : "احتمال تدمر نجمات الموت",
		VIEW_TOP : "الاعلى",
		VIEW_GO : "انطلق",
		VIEW_DIAMETER : "قطر",
		PW_TITLE : " أوجيم جالكسيتول - تبديل كلمة السر",
		OLD_PASSWORD : "كلمة السر القديمة",
		NEW_PASSWORD : "كلمة السر الجديدة",
		CONFIRM_NEW_PASSWORD : "أكد كلمة السر",
		PW_MISMATCH : "كلمتي السر مختلفتين",
		PW_ERROR : "كلمة السر القديمة خاطئه",
		PW_DONE : "تم التحديث بنجاح",
		TIMEZONE_OFFSET : "طابق التوقيت مع السرفر",
		DELETE_ACCOUNT : "حذف حساب جالكسيتول",
		DELETE_ACCOUNT_SAFETY_REQUEST : "هل تود فعلا حذف هذا الحساب?",
		CH_PASSWD_AUTHORIZATION : "صلاحيات",
		CH_PASSWD_ADMIN : "أدمين",
		TIMEZONE_OGAME_OFFSET : "طابق التوقيت العالمي مع السرفر",
		CH_PASSWD_USER_LANGUAGE : "تبديل اللغة بعد تسجيل الدخول",
		CH_PASSWD_USER_LANGUAGE_NO_CHANGE : "لا تغيير",
		CH_PASSWD_EXPAND : "مدد",
		CH_PASSWD_COLLAPSE : "أختصر",
		CH_PASSWD_HIDDEN : "مختفي",
		CH_PASSWD_GETTING_STARTED : "اظهار المساعدة بعد الاتصال",
		CH_PASSWD_PLUGIN : "اظهار معلومات الأداة بعد الاتصال",
		NOTICE_TITLE : "أوجيم جالكسيتول - الملاحظات",
		NOTICE_HEADER : "تعديل الملاحظة",
		NOTICE_HEADER2 : "عدل ملاحظاتك",
		NOTICE_PUBLIC : "يمكن للأعضاء تعديلها ؟",
		NOTICE_YES : "نعم",
		NOTICE_NO : "لا",
		NOTICE_TEXT : "نص الملاحظة",
		NOTICE_SAVE : "سجل",
		NOTICE_DELETED : "تم حذف الملاحظة",
		NOTICE_SAVED : "تم تسجيل أ الملاحظة",
		NOTICE_RESULTS : "جميع النتائج",
		NOTICE_USER : "أسم العضو",
		NOTICE_DATE : "التاريخ",
		NOTICE_EDIT : "عدل",
		NOTICE_DELETE : "حذف",
		NOTICE_NEW : "أضف ملاحظتك",
		NOTICE_NOTPUBLIC : "ملاحظة خفية",
		NOTICE_ALL : "الجميع",
		NOTICE_NONE : "لا أحد",
		NOTICE_SEARCH : "البحث في الملاحظات",
		NOTICE_SEARCH_SHORT : "ابحث",
		NOTICE_HITS : "النتائج",
		NOTICE_SHOWRESULTS : "عدد النتائج في الصفحة",
		NOTICE_OF : "على",
		NOTICE_NOTHING : "البحث لم يعطي نتيجة",
		NOTICE_CHARS : "الحروف",
		NOTICE_PLAYERNAME : "أسم اللاعب",
		NOTICE_SHOWALL : "أظهر كل الملاحظات",
		REPORTS_TITLE : "أوجيم جالكسيتول - تقارير التجسس",
		REPORTS_RESOURCES : "الموارد",
		REPORTS_FLEET : "الأساطيل",
		REPORTS_DEFENCE : "الدفاع",
		REPORTS_BUILDINGS : "المباني",
		REPORTS_TECHNOLOGY : "الأبحاث",
		REPORTS_MOON : "قمر",
		REPORTS_SEARCH : "ابحث في تقارير التجسس",
		REPORTS_SEARCH_SHORT : "ابحث",
		REPORTS_HITS : "النتائج",
		REPORTS_NOTHING : "البحث لم يعطي نتيجة",
		REPORTS_ADDRESS : "عنوان",
		REPORTS_CURRENTNESS : "النشاط",
		REPORTS_PLAYERNAME : "أسم اللاعب",
		REPORTS_ALLY : "تحالف",
		REPORTS_VIEW : "أطلع على التقرير",
		REPORTS_SEARCH_IN : "ابحث في المجرة",
		REPORTS_FROM_SYSTEM : "من نظام",
		REPORTS_TO : "الى",
		REPORTS_DELETE : "احذف",
		REPORTS_DELETED : "تم حذف التقرير",
		REPORTS_RESULTS : "عدد النتائج بالصفحة",
		REPORTS_OF : "على",
		REPORTS_DATE : "التاريخ",
		REPORTS_DATE_0 : "غير مهم",
		REPORTS_DATE_1 : "أقدم من",
		REPORTS_DATE_2 : "أحدث من",
		REPORTS_NOTICES : "ملاحظات",
		REPORTS_AT_LEAST_RESOURCES : "(موارد (على الأقل",
		REPORTS_SEARCH_EXTENDED : "بحث معمق",
		REPORTS_FLEET_RESIS : "أسطول - ترتيب",
		REPORTS_DEFENCE_RESIS : "دفاع - ترتيب",
		REPORTS_ALL_RESIS : "مجموع الترتيب",
		REPORTS_TECHS : "أبحاث",
		REPORTS_UNKNOWN_ENTRIES : "نتيجة غير معروفة",
		REPORTS_PARTLY_INSERTED : "أضيف جزئيا",
		REPORTS_FOR_ALL_RES : "لكل الموارد الممكن نهبها",
		REPORTS_FOR_TF : "لميدان الأنقاض",
		REPORTS_KT : "نواقل صغيرة",
		REPORTS_GT : "نواقل كبيرة",
		REPORTS_SS : "مركبة الحرب",
		REPORTS_REC : "تدوير",
		REPORTS_RAIDABLE : "فقط أهداف يمكن نهبها",
		REPORTS_ALL_RESOURCES : "كل الموارد",
		REPORTS_STUFF : "متفرقات",
		REPORTS_SPEEDSIM : "حاكي باستخدام Speedsim",
		REPORTS_DRAGOSIM : "حاكي باستخدام Dragosim",
		REPORTS_STATUS : "حالة اللاعب",
		REPORTS_ERROR : "حدث خطأ",
		REPORTS_OWN_REPORTS : "تقاريري فقط",
		REPORTS_UPLOAD_BY : "تقرير مرسل من",
		REPORTS_DEPTH : "عمق التقرير",
		REPORTS_FLEET_SCORE : "نقاط الأسطول",
		REPORTS_DEFENCE_SCORE : "نقاط الدفاع",
		REPORTS_HOURS : "ساعات",
		REPORTS_MAX_RESULTS_HIT : "البحث أعطى أكثر من &1 نتيجة . لايمكن اظهار أكثر من  &1 نتيجة الأولى . الرجاء تعديل البحث للحصول على نتائج أدق.",
		REPORTS_OSIMULATE : "حاكي باستخدام OSimulate",
		REPORTS_SHOW_ONLY : "أظهر فقط",
		REPORTS_SHOW_PLANETS : "كواكب",
		REPORTS_SHOW_MOONS : "أقمار",
		REPORTS_OWNER : "تقارير مرسلة من",
		STATS_TITLE : "أوجيم جالكسيتول - الترتيب العا م",
		STATS_TBLHEAD : "الترتيب العام",
		STATS_RANK : "ترتيب",
		STATS_PLAYERNAME : "أسم اللاعب",
		STATS_ALLYNAME : "رمز التحالف",
		STATS_SCORE : "نقاط",
		STATS_FLEET : "أسطول",
		STATS_RESEARCH : "أبحاث",
		STATS_MEMBERS : "أعضاء",
		STATS_STATUS : "حالة",
		STATS_NOTHING : "بدون حالة",
		STATS_NAP : "لا هجوم",
		STATS_ALLIED : "حليف",
		STATS_WAR : "حرب",
		STATS_BOYCOTT : "مقاطع",
		STATS_NEUTRAL : "محايد",
		STATS_OWN : "تحالفك",
		STATS_WING : "جناح",
		STATS_UPDATE : "بيانات من طرف",
		STATS_PLAYERSTATS : "حالة اللاعبين",
		STATS_ALLYSTATS : "حالة التحالف",
		STATS_DELETE : "هل تود حذف هذه البيانات",
		STATS_CONFIRM_DELETE : "هل تود فعلا حذف هذه البيانات",
		STATS_CHANGE_PLAYER_STATUS : "حالة اللاعب",
		STATS_CHANGE_ALLIANCE_STATUS : "حالة التحالف",
		STATS_CHANGE_ALLIANCE_STATUS_HINT : "  سيتم تغير حالة جميع أعضاء التحالف ، أي حالة سابقة سيتم تعديلها . بعد ذلك يمكن تعديل كل لاعب على حدة.",
		STATS_UNKNOWN : "متبقي",
		STATS_DETAILS : "التفاصيل ل",
		STATS_PLAYERSTATUS : "حالة اللاعب",
		STATS_IGNORE_STATUS : "الكل",
		STATS_ACTIVE : "active",
		STATS_INACTIVE : "خامل",
		STATS_BANNED : "محظور",
		STATS_VACATION : "وضع عطله",
		STATS_NOOB : "ضعيف",
		STATS_YES : "نعم",
		STATS_NO : "فقط الكواكب بملاحظات",
		STATS_SEARCH : "بحث",
		STATS_SHOW_GRAPH : "أظهر تفاصيل النقاط",
		STATS_LONG_INACTIVE : "خامل لمدة طويلة",
		STATS_STANDARD : "نقاط الترتيب العام",
		STATS_MILITARY : "نقاط عسكرية",
		STATS_ECONOMY : "اقتصاد",
		STATS_HONOUR : "نقاط الشرف",
		STATS_MILITARY_BUILD : "انتاج عسكري",
		STATS_MILITARY_DESTROYED : "نقاط التدمير",
		STATS_MILITARY_LOST : "مجموع الخسائر",
		REGISTER_REGISTRATE : "تسجيل",
		REGISTER_LOGINNAME : "أسم الدخول",
		REGISTER_PASSWORD : "كلمة السر",
		REGISTER_PASSWORD_CONFIRM : "أعد كلمة السر",
		REGISTER_EMAIL : "البريد الأكتروني",
		REGISTER_INGAME : "الأسم في اللعبة",
		REGISTER_ALLYTAG : "رمز التحالف",
		REGISTER_EMAILVERIFICATION : "تأكيد البريد الأكتروني",
		REGISTER_EMAILTEXT : "الرجاء زيارة الرابط التالي لتأكيد عمل البريد الأكتروني",
		REGISTER_ERROR1 : "أسم الدخول مستعمل لعضو آخر",
		REGISTER_ERROR2 : "حدث خلل عند الأرسال . الرجاء الاتصال بادمين الصفحة",
		REGISTER_ERROR3 : "حدث خلل في ارسال البيانات لموقع",
		REGISTER_INFO1 : "لم يتم إنشاء حسابك",
		REGISTER_INFO2 : " لتفعيل حسابك الرجاء زيارة الرابط الموجود في الرسالة على بريدك الأكتروني",
		REGISTER_INFO3 : "تم التسجيل بنجاح . أتصل بمدير الصفحة لتفعيل حسابك و اعطائك صلاحيات الاستعمال",
		REGISTER_BUTTON : "العودة للصفحة الرئيسية",
		REGISTER_NEW_SUBJECT : "مستخدم جديد قام بالتسجيل في الصفحة",
		REGISTER_NEW_MAILTEXT : "مستخدم جديد قام بالتسجيل في الصفحة",
		REGISTER_BACK : "عد إلى الصفحة الأولى",
		REGISTER_MISSING_FIELDS : "أكمل جميع الخانات ألمتوبت",
		REGISTER_ERROR4 : "خطأ في عنوان البريد الأكتروني",
		REGISTER_ERROR5 : "كلمات السر لم تتطابق",
		REGISTER_PWS : "قوة كلمة السر",
		REGISTER_PWS0 : "ضعيفة جدا",
		REGISTER_PWS1 : "ضعيفة",
		REGISTER_PWS2 : "جيدة",
		REGISTER_PWS3 : "قوية",
		REGISTER_PWS4 : "قوية جدا",
		REGISTER_EMAIL_USED : "البريد الأكتروني مستخدم من قبل",
		LOSTPW_TITLE : "نسيت كلمة السر",
		LOSTPW_INFO2 : "تم منحك كلمة سر جديدة. راجع بريدك الأكتروني",
		LOSTPW_BUTTON1 : "الحصول على كلمة سر جديدة",
		LOSTPW_BUTTON2 : "العودة للصفحة الرئيسية",
		LOSTPW_LOGINNAME : "أسم الدخول",
		LOSTPW_EMAIL : "البريد الأكتروني",
		LOSTPW_ERROR1 : "حدث خلل عند محاولة ارسال البيانات",
		LOSTPW_ERROR2 : "لا توجد نتائج",
		LOSTPW_ERROR3 : "خلل في الارسال لبريدك . الرجاء الاتصال بمدير الصفحة",
		LOSTPW_EMAIL_SUBJECT : "طلب كلمة سر جديدة",
		LOSTPW_EMAIL_TEXT1 : "إليك معلومات الدخول الجديدة لموقع جالكسيتول",
		LOSTPW_EMAIL_TEXT2 : "أسم الدخول",
		LOSTPW_EMAIL_TEXT3 : "كلمة السر",
		LOSTPW_INFO1 : "راجع بريدك لتأكيد طلب الحصول على كلمة سر جديدة",
		LOSTPW_CONFIRM_RESET_SUBJECT : "نسيت كلمة السر ؟",
		LOSTPW_CONFIRM_RESET_MESSAGE : "مرحبا,\n\n لقد طلبت تجديد كلمة السر . للحصول على كلمة سر جديدة الرجاء زيارة الرابط التالي:",
		USERINFO_TITLE : "OGame Galaxytool - User information",
		USERINFO_NAMES : "All users of this tool",
		USERINFO_DETAIL : "detailled information about",
		USERINFO_ERROR1 : "No user known with this ID!",
		USERINFO_USERNAME : "Login name",
		USERINFO_INGAME : "In-game name",
		USERINFO_EMAIL : "Email",
		USERINFO_ALLYTAG : "Alliance",
		USERINFO_STYLEPATH : "Skin",
		USERINFO_STATUS : "Status",
		USERINFO_ACTIVATE : "Activate player",
		USERINFO_LOGINS : "Number of Logins",
		USERINFO_LASTLOGIN : "Last Login",
		USERINFO_DATA : "Information about entered systems",
		USERINFO_NODATA : "That user has entered no systems yet!",
		USERINFO_GALAXY : "Galaxy",
		USERINFO_SYSTEMS : "Number of Systems",
		USERINFO_IP : "IP address",
		USERINFO_LOGINTIME : "Login",
		USERINFO_NOLOGIN : "The player has never logged in.",
		USERINFO_LAST_GALAXYUPDATE : "Inserted last galaxy view",
		USERINFO_LAST_PUBLIC_NOTICE : "Last public notice",
		USERINFO_LAST_PRIVATE_NOTICE : "Last private notice",
		USERINFO_NUMBEROF_PUBLIC_NOTICE : "Number of public notices",
		USERINFO_NUMBEROF_PRIVATE_NOTICE : "Number of private notices",
		USERINFO_ACTIVATED : "Account activated",
		USERINFO_ACTIVATIONTEXT : "The Galaxytool admin has activated your account.\n\nHave fun with the Galaxytool!",
		USERINFO_LAST_SUBMIT : "Inserted last data",
		ALLYHISTORY_TITLE : "OGame Galaxytool - Alliance History",
		ALLYHISTORY_TBLHEAD : "Historical overview",
		ALLYHISTORY_PLAYERNAME : "Player Name",
		ALLYHISTORY_ALLYNAME : "Alliance",
		ALLYHISTORY_LASTMONTH : "Last month",
		ALLYHISTORY_ALL_DATA : "all data",
		ALLYHISTORY_SHOW : "show statistic",
		ALLYHISTORY_TIMESPAN : "Timespan",
		ALLYHISTORY_PROGESS : "Progress",
		ALLYHISTORY_SCORE : "Scores",
		ALLYHISTORY_FSCORE : "Fleet scores",
		ALLYHISTORY_RSCORE : "Research scores",
		ALLYHISTORY_MEMBER : "Members",
		ALLYHISTORY_NOTHING : "no entries found",
		ALLYHISTORY_DETAILS : "Details",
		ALLYHISTORY_SHOW_ADDRESS : "Coordinates",
		ALLYHISTORY_ESCORE : "اقتصاد",
		ALLYHISTORY_MSCORE : "نقاط عسكرية",
		DETAILEDINFO_PLAYERINFO_TITLE : "Player information",
		DETAILEDINFO_ALLYINFO_TITLE : "Alliance information",
		DETAILEDINFO_PLAYERINFO_TBLHEAD : "Detailed information about player",
		DETAILEDINFO_ALLYINFO_TBLHEAD : "Detailed information about alliance",
		DETAILEDINFO_NO_ALLIANCE : "none",
		DETAILEDINFO_SCORE : "Score statistic",
		DETAILEDINFO_FLEET : "Fleet statistic",
		DETAILEDINFO_RESEARCH : "Research statistic",
		DETAILEDINFO_RANK : "Rank",
		DETAILEDINFO_POINTS : "Score",
		DETAILEDINFO_KNOWN_PLANETS : "known planets",
		DETAILEDINFO_MOONS : "known moons",
		DETAILEDINFO_PHALANX_AREA : "Phalanx area",
		DETAILEDINFO_NO_PHALANX_AREA : "no Phalanx found",
		DETAILEDINFO_NOTICES : "Notices",
		DETAILEDINFO_NO_NOTICES : "No Notices found",
		DETAILEDINFO_PREVIOUS_ALLIANCES : "previous Alliances",
		DETAILEDINFO_RESOURCES_PER_HOUR : "Resources per hour",
		DETAILEDINFO_RESOURCES_PER_DAY : "Resources per day",
		DETAILEDINFO_RESOURCES_PER_WEEK : "Resources per week",
		DETAILEDINFO_RESOURCES_PER_MONTH : "Resourcen per month (30 days)",
		DETAILEDINFO_METAL : "Metal",
		DETAILEDINFO_CRYSTAL : "Crystal",
		DETAILEDINFO_DEUTERIUM : "Deuterium",
		DETAILEDINFO_UNKNOWN : "unknown",
		DETAILEDINFO_SCORE_DISTRIBUTION : "Score distribution",
		DETAILEDINFO_GENERAL : "Details",
		DETAILEDINFO_MEMBERS : "Members",
		DETAILEDINFO_GRAPHS : "Graphs",
		DETAILEDINFO_RESOURCES : "Resources",
		DETAILEDINFO_FLEET_TAB : "Fleet",
		DETAILEDINFO_TECH : "Research",
		DETAILEDINFO_FLEET_DETAIL : "Sum / (players average) among all available reports",
		DETAILEDINFO_TECH_DETAIL : "Average of all available playerinformation",
		DETAILEDINFO_PLANET_TAB : "كواكب",
		DETAILEDINFO_MOON_TAB : "أقمار",
		DETAILEDINFO_ACTIVITIES : "Activities",
		DETAILEDINFO_NODATA : "لا تواجد أي بيانات",
		DETAILEDINFO_ACTIVITY_DESCRIPTION : "Show activities of &1 collected from:",
		DETAILEDINFO_GALAXYVIEWS : "Galaxy views",
		DETAILEDINFO_SCANS : "Espionage actions",
		DETAILEDINFO_MESSAGES : "Player messages",
		DETAILEDINFO_COMBATS : "Combat reports",
		DETAILEDINFO_ALLYPAGE : "Alliance overview",
		DETAILEDINFO_MANUAL : "Manual insertions",
		DETAILEDINFO_START : "Beginning",
		DETAILEDINFO_TO : "to",
		DETAILEDINFO_TODAY : "Today",
		DETAILEDINFO_DATA_RESTRICTION : "restricted to:",
		DETAILEDINFO_WEEKDAY_WEEKEND : "Weekend",
		DETAILEDINFO_WEEKDAY_WORKINGDAY : "Weekday",
		DETAILEDINFO_WEEKDAY_MONDAY : "Monday",
		DETAILEDINFO_WEEKDAY_TUESDAY : "Tuesday",
		DETAILEDINFO_WEEKDAY_WEDNESDAY : "Wednesday",
		DETAILEDINFO_WEEKDAY_THURSDAY : "Thursday",
		DETAILEDINFO_WEEKDAY_FRIDAY : "Friday",
		DETAILEDINFO_WEEKDAY_SATURDAY : "Saturday",
		DETAILEDINFO_WEEKDAY_SUNDAY : "Sunday",
		DETAILEDINFO_WEEKDAY_SHORTLENGTH : 3,
		DETAILEDINFO_PLAYER_CURRENTLY_ACTIVE : "The player is currently active",
		DETAILEDINFO_PLAYER_MESSAGES : "available player messages",
		DETAILEDINFO_SHOW : "show",
		DETAILEDINFO_NONE : "none available",
		DETAILEDINFO_ENTER_MANUALLY : "Enter activities for this player",
		DETAILEDINFO_PLAYER_SEEN_ON : "Player was online on",
		DETAILEDINFO_INSERT : "Insert",
		DETAILEDINFO_OGAME_SERVERTIMES : "Please note: All dates and times refer to OGame server times !",
		DETAILEDINFO_DAY_VIEW : "24 hours view",
		DETAILEDINFO_WEEK_VIEW : "weekly view",
		DETAILEDINFO_HOME_PLANET : "Homeworld",
		DETAILEDINFO_PLANETNAME : "Name",
		DETAILEDINFO_DEFENCE_SCORE : "Defence score",
		DETAILEDINFO_DEFENCE_SCORE_TOOLTIP : "Defence score = Fleet - Score + Research + Economy.<br/>All those statistics must be up to date to have a meaningful result!",
		DETAILEDINFO_SCORE_PER_SHIP : "Scores per ship",
		DETAILEDINFO_SHIPS : "Number of ships",
		DETAILEDINFO_DATE_IN_FUTURE : "Do not maintain times which are not in the past.",
		ADMIN_TITLE : "Administration of the Galaxytool",
		ADMIN_DISCLAMER : "Attention: Run any of those scripts at your own risk! Most of them are deleting data.",
		ADMIN_INCONSISTENCIES : "Inconsistencies at the database",
		ADMIN_PLANETS : "Delete planets at position 0 or greater than 15",
		ADMIN_GALAXIES : "Delete galaxies greater than &1 ",
		ADMIN_PLAYERS : "Delete players without OGame playerid - this will remove duplicate player entries",
		ADMIN_REPORTS : "Delete reports where no planet exists anymore",
		ADMIN_MISC : "Miscellaneous",
		ADMIN_RESET : "Reset Galaxytool (only user and ip table are not deleted)",
		ADMIN_OLD_PLAYERS : "Delete player entries older than &1 days",
		ADMIN_OLD_REPORTS : "Delete reports older than &1 days",
		ADMIN_LOADING : "Do not close this window while the page is loaded.",
		ADMIN_STATUS : "Status of your requests",
		ADMIN_SELECTION : "At least one entry must be selected",
		ADMIN_SAFETY : "Are you sure that you want to run these script(s) ?",
		ADMIN_DONE : "done",
		ADMIN_NOTBD : "nothing to be done",
		ADMIN_OLD_GALAXIES : "Remove galaxy views which are older than &1 days",
		ADMIN_UNUSED_PLAYERS : "Remove players who do not occur in any galaxy view",
		ADMIN_OLD_ACTIVITIES : "Remove player activities older than &1 days",
		ADMIN_OLD_COMBATS : "Remove combat reports older than &1 days",
		ADMIN_OLD_INGAME_MSG : "Remove ingame messages older than &1 days",
		ADMIN_OGAME_API : "Load public data from OGame into the Galaxytool",
		ADMIN_OGAME_ALL_DATA : "all data",
		ADMIN_OGAME_GALAXY_DATA : "المجره",
		ADMIN_OGAME_STATISTICS_DATA : "ترتيب اللاعبين",
		ERRORPAGE_PAGEFORWARD : "Click here if your browser does not support page forwarding",
		ERRORPAGE_PERMISSION_DENIED : "You don't have the permission to enter this page. Click to go back.",
		FLEETS_TITLE : "OGame Galaxytool - Fleet movements",
		FLEETS_ACTUAL_FLEETS : "Current fleet movements",
		FLEETS_YES : "نعم",
		FLEETS_NO : "فقط الكواكب بملاحظات",
		FLEETS_DETAILS : "Details",
		FLEETS_MISSION_EXPEDITION : "Expedition",
		FLEETS_MISSION_COLONIZATION : "Colonize",
		FLEETS_MISSION_RECYCLE : "Harvest",
		FLEETS_MISSION_TRANSPORT : "Transport",
		FLEETS_MISSION_DEPLOYMENT : "Deploy",
		FLEETS_MISSION_ESPIONAGE : "Espionage",
		FLEETS_MISSION_ACS_DEFEND : "ACS Defend",
		FLEETS_MISSION_ATTACK : "Attack",
		FLEETS_MISSION_ACS_ATTACK : "ACS Attack",
		FLEETS_MISSION_MOON_DESTRUCTION : "Moon Destruction",
		FLEETS_MISSION_MISSILE_ATTACK : "Missile Attack",
		FLEETS_NO_DATA : "No applicable data found",
		FLEETS_FLEET : "Fleet",
		FLEETS_ALL_FLEETS : "Show all fleet movements",
		COMBAT_REPORT_OUDATED_GALAXYVIEW : "Your galaxy data is outdated. Please visit combat origin and target coordinates first!",
		MESSAGES_TITLE : "OGame Galaxytool - OGame Messages",
		MESSAGES_PLAYERNAME : "Playername",
		MESSAGES_SUBJECT : "Subject",
		MESSAGES_DATE : "Date",
		MESSAGES_FILTER : "Filter",
		MESSAGES_DELETE : "Delete message",
		MESSAGES_PUBLISH_DETAIL : "Publish message by adding the message content to notice text of that player.",
		MESSAGES_PUBLISH_HEADER : "&sender sent a message to &recipient on &date:\n\n &message",
		MESSAGES_PLAYER_FILTER : "Messages for player:",
		MESSAGES_CONTENT : "Content",
		COMBATS_TITLE : "OGame Galaxytool - Combat reports",
		COMBATS_ATTACKER : "Attacker",
		COMBATS_DEFENDER : "Defender",
		COMBATS_DATE : "Date",
		COMBATS_OWNER : "Owner",
		COMBATS_WINNER : "Winner",
		COMBATS_COMBATREPORT : "Combat Report",
		COMBATS_COMBAT_AT : "Combat at",
		COMBATS_LOST_UNITS : "Lost units",
		COMBATS_LOOT : "Loot",
		COMBATS_DEBRIS : "Debris",
		COMBATS_AND : "and",
		COMBATS_PUBLISH : "Make this report public",
		COMBATS_UNPUBLISH : "Unshare this report (makes it private again)",
		COMBATS_DELETE : "Delete report",
		COMBATS_CHECK_ALL : "Check All",
		COMBATS_UNCHECK_ALL : "Uncheck All",
		COMBATS_WITH_SELECTED : "With selected",
		COMBATS_PUBLIC_REPORTS : "Public reports",
		COMBATS_YES : "نعم",
		COMBATS_NO : "فقط الكواكب بملاحظات",
		COMBATS_SEARCH_OPTIONS : "Search options",
		COMBATS_SEARCH : "Go",
		COMBATS_RESET : "Reset",
		COMBATS_COORDINATES : "احداثيات",
		COMBATS_INVALID_GALAXY_ENTERED : "Invalid Galaxy entered",
		COMBATS_INVALID_SYSTEM_ENTERED : "Invalid System entered",
		COMBATS_INVALID_PLANET_ENTERED : "Invalid Planet entered",
		COMBATS_GALAXY_FROM_TO : "Galaxy",
		COMBATS_SYSTEM_FROM_TO : "System",
		COMBATS_PLANET_FROM_TO : "Planet",
		COMBATS_APPLY : "تفعيل",
		COMBATS_COMBAT_SUMMARY : "Combat report summary",
		COMBATS_DOWNLOAD_CSV : "Download as CSV file",
		REPORT_ARCHIVE_TITLE : "Report archive",
		REPORT_ARCHIVE_COORDINATES : "Coordinates",
		REPORT_ARCHIVE_SCANTIME : "Scan time",
		REPORT_ARCHIVE_DELETE : "Delete these entries",
		REPORT_ARCHIVE_CONFIRM_DELETE : "Do you really want to delete these entries?",
		REPORT_ARCHIVE_GALAXY : "Galaxy",
		REPORT_ARCHIVE_SYSTEM : "System",
		REPORT_ARCHIVE_PLANET : "Planet",
		REPORT_ARCHIVE_MOON : "Moon",
		REPORT_ARCHIVE_DETAILS : "Details",
		REPORT_ARCHIVE_RESOURCES : "Resources per hour",
		REPORT_ARCHIVE_HEADER_RESOURCES : "الموارد",
		REPORT_ARCHIVE_DETAILS_FOR : "Report archive for &1 [&2] (&3)",
		REPORT_ARCHIVE_FLEET_CARGO : "Fleet cargo capacity",
		REPORT_ARCHIVE_IRAK_RANGE : "Interplanetary Missiles range",
		REPORT_ARCHIVE_CHART_TYPE : "Chart type",
		INSTALL_TITLE : "Galaxytool installation for version",
		INSTALL_PROGRESS : "Overall progress",
		INSTALL_STEP : "Step",
		INSTALL_CONTINUE : "Continue",
		INSTALL_VALIDATE : "Validate",
		INSTALL_STEP1 : "Welcome",
		INSTALL_STEP2 : "Writeable check",
		INSTALL_STEP3 : "Database settings",
		INSTALL_STEP4 : "OGame settings",
		INSTALL_STEP5 : "Galaxytool settings",
		INSTALL_STEP6 : "Admin password",
		INSTALL_STEP7 : "Install Galaxytool",
		INSTALL_STEP8 : "Finalize install",
		INSTALL_FILE_DELETE_CHECK : "Please delete install.php and update.php from your webserver.",
		INSTALL_STEP1_PHP_FAILED : "Your PHP version &1 is not working with this Galaxytool version",
		INSTALL_STEP1_FOPEN_FAILED : "Your PHP version does not allow to open webpages with FOPEN() command. This is required to consume the OGame API.",
		INSTALL_STEP1_WELCOME : "Welcome to the installation wizard of the Galaxytool. You will be guided through the installation of the Galaxytool.",
		INSTALL_STEP2_DESCRIPTION : "Make sure your config.php and attributes.php files have write permissions enabled.",
		INSTALL_STEP2_DESCRIPTION2 : "If you don't know, how to achieve this, please take a look here: &1",
		INSTALL_STEP2_FILE_NOT_WRITEABLE : "File is not writeable",
		INSTALL_STEP3_SERVER : "Database server",
		INSTALL_STEP3_USERNAME : "اسم التسجيل",
		INSTALL_STEP3_PASSWORD : "كلمة السر",
		INSTALL_STEP3_DBNAME : "Database name",
		INSTALL_STEP3_PREFIX : "Tablename prefix",
		INSTALL_STEP3_ENTER_PREFIX : "E.g. mytool_",
		INSTALL_STEP3_ENTER_SERVER : "Enter the server address. Contact your system admin if necessary. Usually the correct value is localhost.",
		INSTALL_STEP3_ENTER_USERNAME : "Enter the username for database access",
		INSTALL_STEP3_ENTER_PASSWORD : "Enter the password for database access",
		INSTALL_STEP3_ENTER_DBNAME : "Enter the database name which shall be used for installation (must exist)",
		INSTALL_STEP3_CONNECT_FAILED : "Could not establish connection to database server",
		INSTALL_STEP3_DB_FAILED : "Database &1 not found",
		INSTALL_STEP3_MYSQL_VERSION_FAILED : "MySQL version &1 is not working with this Galaxytool version",
		INSTALL_STEP4_URL : "OGame URL",
		OGAME_URL_DETAILS : "Please enter any URL you see when you are logged on to OGame. Based on that URL the tool will derive the OGame API address which can be used to fill data into the Galaxytool without the Galaxytoolbar. This API was introduced with OGame version 4.1.",
		INSTALL_STEP4_UNIVERSE : "OGame Universe",
		INSTALL_STEP4_DEF_TO_DEBRIS : "Defense to debris",
		INSTALL_STEP4_DEBRIS_RATE : "Debris rate",
		INSTALL_STEP4_SPEED_RATE : "Speed rate",
		INSTALL_STEP4_ENTER_UNIVERSE : "Enter your OGame universe name or number (case sensitive).",
		INSTALL_STEP4_UNIVERSE_MISSING : "You must define your universe",
		INSTALL_STEP4_ENTER_URL : "Enter your OGame universe address",
		INSTALL_STEP4_URL_MISSING : "You must define your OGame address",
		INSTALL_STEP4_URL_CHECK_FAILED : "Could not find OGame API at &1",
		INSTALL_STEP4_GETSETTINGS : "Fetch settings",
		INSTALL_STEP5_TOOLNAME : "Galaxytool name",
		INSTALL_STEP5_ENTER_TOOLNAME : "This is the name which will be shown at logon page to identify your Galaxytool",
		INSTALL_STEP5_LANGUAGE : "Default language",
		INSTALL_STEP5_EMAIL_TO : "Email To",
		INSTALL_STEP5_ENTER_EMAIL_TO : "Enter the email address where you would like to receive notifications about registrations",
		INSTALL_STEP5_EMAIL_FROM : "Email From",
		INSTALL_STEP5_ENTER_EMAIL_FROM : "This email address is shown as REPLY for all mails sent from the Galaxytool",
		INSTALL_STEP5_USE_PHPMAILER : "Use PHPMailer",
		INSTALL_STEP5_MAXSHOUTS : "Maximum number of shoutbox entries",
		INSTALL_STEP5_ENTER_USE_PHPMAILER : "Use PHPMailer if your server does not support sending emails by default",
		INSTALL_PHPMAILER_HOST : "SMPT Host",
		INSTALL_PHPMAILER_HOST_EXAMPLE : "e.g. smtp.provider.com",
		INSTALL_PHPMAILER_USER : "SMPT Username",
		INSTALL_PHPMAILER_USER_EXAMPLE : "e.g. user@provider.dcom",
		INSTALL_PHPMAILER_PASS : "SMPT password",
		INSTALL_PHPMAILER_SECURE : "Authentification method (e.g. ssl)",
		INSTALL_PHPMAILER_PORT : "SMTP Port",
		INSTALL_STEP6_INTRO : "Please define a password for the <strong>admin</strong> account which you have to use for your first logon to the Galaxytool after the installation.",
		INSTALL_STEP7_CONFIG : "Configuration file created",
		INSTALL_STEP7_CONFIG_FAILED : "Configuration file not created",
		INSTALL_STEP7_ATTRIBUTES : "Attributes file created",
		INSTALL_STEP7_ATTRIBUTES_FAILED : "Attributes file not created",
		INSTALL_STEP7_CREATED_TABLES : "Database tables created",
		INSTALL_STEP8_INTRO : "You have successfully installed the Galaxytool!",
		INSTALL_STEP8_LOAD_DATA : "Downloading OGame data ...",
		INSTALL_STEP8_LOAD_DATA_FINISHED : "Download of OGame data finished",
		INSTALL_STEP8_DELETE_FILE : "You should now delete the installation files install.php and update.php from your webserver.",
		INSTALL_STEP8_LOGON : "Please logon with the <strong>admin</strong> user and the password you defined earlier.",
		UPDATE_START : "Starting update to version &1",
		UPDATE_STEP_DONE : "Done",
		UPDATE_TITLE : "Galaxytool update for version",
		UPDATE_STEP1_WELCOME : "Welcome to the update wizard of the Galaxytool. You will be guided through the update of the Galaxytool.",
		UPDATE_STEP1_BACKUP_FILES : "As a first step, make a backup of your <strong>config</strong> folder! You will have to replace the configuration content in case of errors.",
		UPDATE_STEP1_BACKUP_DB : "Then make a <a href=\"http://www.ehow.com/how_2036600_create-database-php.html\">backup</a> of your database.",
		UPDATE_STEP1_PROCEED : "Once the backups have been done, you can proceed with your update.",
		UPDATE_STEP1 : "Welcome",
		UPDATE_STEP2 : "Galaxytool settings",
		UPDATE_STEP2_OLD_VERSION : "Previous Galaxytool version",
		UPDATE_STEP3 : "Update Galaxytool",
		UPDATE_STEP3_UPDATE_RUNNING : "Update running, please wait...",
		UPDATE_STEP4 : "Finalize Update",
		UPDATE_STEP4_INTRO : "You have successfully updated the Galaxytool!",
		UPDATE_STEP4_UPDATE_DONE : "Update steps performed.",
		UPDATE_FAILED : "Update failed.",
		GALAXYTOOL_DUMMY_TEXT : "dummy"
	})
);