define(
	({
		REPORT_WHEN : "",
		RESOURCES_ON : "Resursi uz",
		PLAYER_BANNED : "b",
		PLAYER_VACATION_MODE : "a",
		PLAYER_NOOB : "n",
		PLAYER_INACTIVE : "i",
		PLAYER_LONG_INACTIVE : "I",
		PLAYER_OUTLAW : "o",
		L_USERNAME : "Lietotājvārds",
		L_PASSWORD : "Parole",
		L_LOGINFAILURE : "Tavs lietotājvārds vai parole ievadīti nepareizi, vai arī tavs konts nav aktivizēts.",
		L_TOKENFAILURE : "Your logon key is wrong or your account is not activated yet.",
		L_LOGINTEXT : "Ievadiet lietotāja datus.",
		L_LANGUAGE : "Pieejamās valodas:",
		L_TIMEOUT : "Sesijas laiks ir beidzies",
		L_REGISTER : "Reģistrācija",
		L_PWLOST : "Aizmirsi paroli?",
		INDEX_TITLE : "Pārskats",
		INDEX_INFO : "Informācija",
		INDEX_ENTRIES : "Pavisam sistēmas",
		INDEX_ENTRIES_LASTWEEK : "Sistēmas, kas pievienotas nedēļas laikā ",
		INDEX_ENTRIES_TO_OLD : "Sistēmas kas vecākas par mēnesi",
		INDEX_REGISTERED_USERS : "Reģistrēts lietotājs",
		INDEX_PAGEFORWARD : "Spied šeit, ja tavs brauzeris nepārvieto tevi automātiski!.",
		INDEX_NOTICES : "Piezīmes",
		INDEX_PLAYERS : "Spēlētāju statistika",
		INDEX_ALLIES : "Alianšu statistika",
		INDEX_REPORTS : "Spiegošanas atskaites",
		INDEX_VERSION : "Lejuplādēt jauno versiju",
		INDEX_LATEST_VERSION : "Jums ir janākā versija",
		INDEX_SHOUTBOX : "Pēdējais paziņojums",
		INDEX_NOENTRY : "Pašlaik nav paziņojumu",
		INDEX_COMMENT : "Tavs paziņojums:",
		INDEX_INSERT : "Pievienot",
		INDEX_UMOD : "Spēlētājs ir a",
		INDEX_NO_MOONS : "Mēness skaits",
		INDEX_NO_EMPTY_SYSTEMS : "Tukšās sistēmas",
		INDEX_NO_FULL_SYSTEMS : "Pilnībā aizpildītās sistēmas",
		INDEX_NO_TARGETS : "Iespējamo mērķu skaits",
		INDEX_USERINFO : "Info par lietotājiem",
		INDEX_ONLINE : "Pašlaik OnLine",
		INDEX_TODAY : "Šodien OnLine",
		INDEX_ALL : "Apmeklējumi kopā",
		GENERAL_LOAD_FORM : "Load form data",
		GENERAL_SAVE_FORM : "Save form data",
		GENERAL_SAVE_AS_TEXT : "Save as",
		GENERAL_SAVE : "Save",
		INDEX_USERMANAGEMENT : "Activation Overview",
		INDEX_NEEDADMIN : "Accounts to unlock",
		INDEX_NEEDEMAIL : "Unvalidated Accounts",
		INDEX_TOOLBAR_INFO : "Galaxytool plugin information",
		INDEX_TOOLBAR_URL : "Galaxytool URL",
		INDEX_TOOLBAR_VERSION_REQUIRED : "Requires at least Galaxytool plugin version",
		INDEX_TOOLBAR_INSTALL_GUIDE : "Installation instructions for plugin",
		INDEX_TOOLBAR_TOKEN : "Logon key",
		INDEX_TOOLBAR_NEW_TOKEN : "Get new key",
		INDEX_PLAYERS_WITH_N_PLANETS : "Players with more than &1 planets",
		INDEX_GETTING_STARTED : "Getting started with the Galaxytool",
		INDEX_GETTING_STARTED1 : "Welcome to the Galaxytool!",
		INDEX_GETTING_STARTED2 : "The Galaxytool will help you to analyze what is going on in your OGame universe &1",
		INDEX_GETTING_STARTED3 : "Before you can actually analyze data you have to insert it first. For this you require a browser plugin like the &1 for Firefox.",
		INDEX_GETTING_STARTED4 : "After you installed the plugin, you navigate through your OGame pages as usual and you will see a small status window whenever something was sent to your Galaxytool.",
		INDEX_GETTING_STARTED5 : "Once the plugin inserted data into the Galaxytool, you can start to analyze where the players have their colonies, how many colonies they have, what reports exist or when they are active the most.",
		INDEX_GETTING_STARTED6 : "But it will also help you to analyze how you are progressing if you compare yourself against your competitors or by analyzing your combat reports to see how much you raided during the last days or weeks.",
		INDEX_GETTING_WIKIPAGE : "There are many more features within the Galaxytool.",
		INDEX_GETTING_WIKIPAGE2 : "Check them out at our wiki page.",
		INDEX_GETTING_BOARD : "For feedback or ideas you can use our board:",
		INDEX_GETTING_CHAT1 : "Or visit us at the chatroom:",
		INDEX_GETTING_CHAT2 : "We are not online 24/7 but spare a lot of our free time there, so be patient.",
		INDEX_CLOSE : "Close",
		INDEX_LOGIN : "Login",
		GENERAL_REQUIRED_FIELDS : "Please fill all required fields",
		INDEX_MESSAGES : "Messages",
		INDEX_EXAMPLE : "Example",
		INDEX_INVALID_DATA : "Invalid data",
		GENERAL_COLUMN_HIDE_TITLE : "Manage columns",
		GENERAL_COLUMN_HIDE_INFO : "Please select which columns you want to see in the table.",
		GENERAL_ENTRIES_DELETED : "&1 entries deleted",
		GENERAL_APPLY : "Apply",
		STARTPAGE_GALAXYTOOL_DESCR : "<em>Galaxytool</em> is a tool for the browser game OGame.",
		GENERAL_OVERWRITE : "Overwrite duplicate entry",
		GENERAL_OVERWRITE_QUESTION : "Overwrite?",
		INDEX_OWN_LOGINS : "Your logins",
		GENERAL_OPEN_IN_NEW_WINDOW : "Atvērt saiti jaunā logā",
		GENERAL_UNIT_OF_MEASURE_DAYS : "Days",
		PROGRAM_NAME : "OGame Galaxytool",
		SHORTNAME : "Galaxytool",
		BACK_INDEX : "Uz sākumu",
		UNIVERSE : "Visums",
		MENU_INFO_LINKS : "INFO",
		MENU_PAGE : "Pārskats",
		MENU_DB_SEARCH : "Meklēt datu bāzē",
		MENU_DB_NOTICES : "Meklēt piezīmēs",
		MENU_DB_REPORTS : "Meklēt spiegošanas atskaitēs",
		MENU_GALAXYVIEW : "Galaktikas pārskats",
		MENU_STATISTICS : "Statistika",
		MENU_ALLYHISTORY : "Vēstures statistika",
		MENU_FLEET_MOVEMENTS : "Fleet movements",
		MENU_COMBAT_REPORTS : "Combat reports",
		MENU_MESSAGES : "Ingame messages",
		MENU_OPTION_LINKS : "Opcijas",
		MENU_DB_REFRESH : "Atjaunot datu bāzi",
		MENU_NOTICES : "Piezīmes",
		MENU_DB_STATUS : "Datu bāzes status",
		MENU_USEROPTIONS : "Lietotāju pārskats",
		MENU_USEROPTIONS2 : "Akounta opcijas",
		MENU_USEROPTIONS3 : "Info par akountiem",
		MENU_ADMIN : "Administrācija",
		MENU_LOGOUT : "Iziet",
		MENU_STUFF : "Pārējais",
		MENU_FORUM_THREAD : "Izstrādātāju forums",
		MENU_DOWNLOADPAGE : "Lejuplādēt",
		MENU_LANGUAGE : "Valodas izvēle",
		MENU_HELP : "Palidzība",
		MENU_TOOLOPTIONS : " Galaxietool uzstādīšana",
		PARSER_INFO1 : "Pievienots datubāzei",
		PARSER_ERROR1 : "Kļūda mēģinot pievienot datu bāzi:",
		PARSER_ERROR2 : "Neizdevās izvēlēties datu bāzi!",
		PARSER_ERROR3 : "Neizdevās atrast datu bāzi!",
		PARSER_WRONG_UNIVERSE : "Nepareizs visums - faktiskais: \"&1\" gaidītais: \"&2\"",
		SHOW_TITLE : "OGame Galaxietool - Datu apskates lapa",
		SHOW_SEARCH : "Meklēt datu bāzē",
		SHOW_ALLYSYMBOL : "Alianses abreviatūra",
		SHOW_PLAYERNAME : "Spēlētāja vārds",
		SHOW_MOONS : "Meklēt tikai mēnešus",
		SHOW_NOTICES : "Meklēt tikai planētas ar piezīmēm",
		SHOW_COLONIES : "Tikai planētas kolonizēšanai",
		SHOW_YES : "Jā",
		SHOW_NO : "Nē",
		SHOW_SEARCHRANGE : "Meklēšanas rādiuss",
		SHOW_SEARCH_IN : "Meklēt galaktikā",
		SHOW_FROM_SYSTEM : "No sistēmas",
		SHOW_FROM_PLANET : "No planētas Nr",
		SHOW_TO : "Līdz",
		SHOW_DESCRIPTION : "Meklējot spēlētājus vai alianses ir pieļaujams izmantot simbolu *, piemēram *nick* - atradīs visus spēlētājus, kam vārdā ir &quot;nick&quot;.<br />Nav nepieciešams aizpildīt visus laukus, var meklēt tikai alianses koordinātes, kā ārī visus mēnēšus kādai noteiktai aliansei.",
		SHOW_SORT_BY : "Šķirot pēc",
		SHOW_GALASYSTEM : "Galaktikas/Sistēmas",
		SHOW_ALLYNAME : "Alianses nosaukuma",
		SHOW_SEARCHBUTTON : "Meklēt",
		SHOW_ADDRESS : "Adrese",
		SHOW_ALLYSORT : "Alianse",
		SHOW_PLANET : "Planētas nosaukums",
		SHOW_STATUS : "Status",
		SHOW_CURRENTNESS : "Aktualitāte",
		SHOW_PLAYER_STATUS : "Spēlētāja status",
		SHOW_PLAYER_STATUS1 : "Viss",
		SHOW_PLAYER_STATUS2 : "Var uzbrukt",
		SHOW_PLAYER_STATUS3 : "Neaktīvs",
		SHOW_HITS : "Rezultāti",
		SHOW_OF : "No",
		SHOW_ASC : "Augšanas kārtībā",
		SHOW_DESC : "Dilšanas kārtībā",
		SHOW_RESULTS : "Rezultāti",
		SHOW_MOON : "Mēness",
		SHOW_UKMOONSIZE : "Nezināms",
		SHOW_DF : "Atlūzas",
		SHOW_DF_LONG : "Atkritumu lauks",
		SHOW_METAL : "M",
		SHOW_METAL_LONG : "Metāls",
		SHOW_CRYSTAL : "K",
		SHOW_CRYSTAL_LONG : "Kristāls",
		SHOW_BOTH : "Kopā",
		SHOW_AT_LEAST : "(min.)",
		SHOW_DATE : "Datums",
		SHOW_DATE_0 : "Visi",
		SHOW_DATE_1 : "Vecs",
		SHOW_DATE_2 : "Jauns",
		SHOW_RANK : "Vieta",
		SHOW_FRANK : "Vieta pēc flotēm",
		SHOW_MEMBERS : "Biedri",
		SHOW_NOTRANKED : "Nav top - 1500.",
		SHOW_NOTICERES : "Piezīmes",
		SHOW_REPORTS : "Rādīt tikai planētas ar spiegošanas atskaitēm",
		SHOW_REPORTS_SHORT : "Spiegošana",
		SHOW_NOTHING : "Neizdevās neko atrast",
		SHOW_ALLIANCE_STATUS : "Alianses status",
		SHOW_NO_STATUS : "Nav statusa",
		SHOW_NAP : "NAP",
		SHOW_ALLIED : "Sabiedrotie",
		SHOW_WAR : "Karš",
		SHOW_BOYCOTT : "Boikots",
		SHOW_NEUTRAL : "Neitrals",
		SHOW_OWN : "Sava alianse",
		SHOW_WING : "Spārns",
		SHOW_EXT_OPTIONS1 : "Rādīt papildus opcijas - meklēšanai pēc vietas, laika un atlūzu meklēšanas.",
		SHOW_EXT_OPTIONS2 : "Rādīt papildus opcijas - Jaunas kolonijas meklēšanai, mēnešu, atskaišu, piezīmju, spēlētāju statusa un diplomātijas.",
		SHOW_EXT_OPTIONS3 : "Rādīt papildus opcijas - atrasto meklējumu kārtošanas veids.",
		SHOW_EXTENDED : "advanced search",
		SHOW_MOON_SELECTION : "Planet with moon",
		SHOW_REPORT_SELECTION : "Planet with report",
		SHOW_FILTER_BY : "Exclude from the list",
		SHOW_FILTER_NONE : "Nekas",
		SHOW_PLAYERS_WITHOUT_PROGRESS : "Show players without score changes within the last few days",
		STATUS_TITLE : "OGame Galaxietool - Statusa lappuse",
		STATUS_DB_STATUS : "Datu bāzes status",
		STATUS_COLOR : "Krāsa",
		STATUS_AGE1 : "Datu pieaugums pa 1 dienu.",
		STATUS_AGE2 : "Aktualitāte 2 - 4 dienas.",
		STATUS_AGE3 : "Aktualitāte 4 - 7 dienas.",
		STATUS_AGE4 : "Aktualitāte 1 - 2 nedēļas.",
		STATUS_AGE5 : "Aktualitāte 2 - 4 nedēļas.",
		STATUS_AGE6 : "Dati ir vecāki par mēnesi!",
		STATUS_AGE7 : "Vēl nav datu.",
		STATUS_ON : "Iekšā",
		STYLES_COLOR1 : "Krāsa1",
		STYLES_COLOR2 : "Krāsa1",
		STYLES_COLOR3 : "Krāsa3",
		STYLES_COLOR4 : "Krāsa4",
		STYLES_COLOR5 : "Krāsa5",
		STYLES_COLOR6 : "Krāsa6",
		STYLES_COLOR7 : "Krāsa7",
		STATUS_DB_LEGEND : "Legend",
		STATUS_GALAXY : "Galaxy Overview",
		USER_TITLE : "OGame Galaxietool - Lietotāju vadība",
		USER_NAMES : "Lietotājs",
		USER_ERROR : "Kļūda",
		USER_NEWUSER : "Pievienot lietotāju",
		USER_OPTIONS : "Opcijas",
		USER_USERNAME : "Lietotāja vārds",
		USER_PASSWORD : "Parole",
		USER_PASSWORD_CONFIRM : "Atkārtot paroli",
		USER_GALAXY : "Galaktika",
		USER_SEARCH : "Meklēt",
		USER_INSERT : "Pievienot",
		USER_DELETE : "Dzēst",
		USER_DELETE_ENTRY : "Jūs tiešam vēlaties dzēst šo lietotāju: ",
		USER_STATUS : "Status",
		USER_STYLES : "Stila opcijas",
		USER_SUBMIT : "Nosūtīt",
		USER_RESET : "Atcelt",
		USER_YES : "Jā",
		USER_NO : "Nē",
		USER_STYLEPATH : "Uz failu  styles.css",
		USER_PROBES : "Spiegošanas atskaite",
		USER_EMAIL : "E-pasts",
		USER_ERROR1 : "Nepareiza parole vai nederīgs e-past.",
		USER_ERROR2 : "E-pasta adrese ir nederīga.",
		USER_INGAME : "Niks spēlē",
		USER_ALLYTAG : "Alianses abreviatūra",
		USER_ALLYHISTORY : "Vēstures statistika",
		USER_DIPLOMATIC : "Diplomātija",
		USER_STATSPAGE : "Ierakstu skaits statistikā",
		USER_LINKS : "Links",
		USER_LINKS2 : "Formats:<br>teksts;url<br>teksts2;url2<br>teksts3;url3",
		USER_EXPORT_TITLE : "Krāsu eksportēšana (BB Codes)",
		USER_BB_COORDINATES : "Koordinātes",
		USER_BB_MOON : "Mēness",
		USER_BB_DEBRIS : "Atlūzu lauki",
		USER_BB_ALLY : "Alianses nosaukums",
		USER_BB_ALLYDETAILS : "Alianses detaļas",
		USER_BB_PLAYERNAME : "Spēlētāja vārds",
		USER_BB_BANNED : "Bloķēts",
		USER_BB_VACATION : "Atvaļinājuma režīms",
		USER_BB_NOOB : "Iesācēju aizsardzība",
		USER_BB_INACTIVE : "Neaktīvs",
		USER_BB_LONGINACTIVE : "Neaktīvie 4 nedēļas",
		USER_DELETION : "Delete",
		USER_FLEETINFO : "Fleet movements",
		USER_ACTIVITIES : "Player activities",
		USER_MAINTENANCE : "Galaxytool maintenance",
		USER_MANAGEMENT : "Lietotāju pārskats",
		USER_DELETE_MY_COMBAT_REPORTS : "Delete my combat reports",
		USER_DELETE_MY_MESSAGES : "Delete my messages",
		USER_DELETE_MY_FLEETMOVES : "Delete my fleet movements",
		USER_DELETE_MY_COMBAT_REPORTS_LIMITED : "Delete my combat reports older than &1 days",
		USER_DELETE_MY_MESSAGES_LIMITED : "Delete my messages older than &1 days",
		USER_TABLE_ENTRIES : "Number of search results for each page",
		USER_EXISTS : "User already exists",
		USER_BB_OUTLAW : "Outlaw",
		USER_INVALID_URL : "URL &1 seems to be invalid - URL will be ignored",
		VIEW_TITLE : "OGame Galaxietool - Sīkāks apskats",
		VIEW_NODATA : "Pagaidām nav datu.",
		VIEW_GALAXY : "Galaktika",
		VIEW_SYSTEM : "Saules sistēma",
		VIEW_POSITION : "Poz.",
		VIEW_PLANET : "Planēta",
		VIEW_MOON : "Mēness",
		VIEW_TF : "Atlūzas",
		VIEW_PLAYER : "Spēlētājs",
		VIEW_PLAYER_ADD : "(Ranks/Status)",
		VIEW_ALLY : "Alianse",
		VIEW_ALLY_ADD : "Ranks/Biedri",
		VIEW_METAL : "M",
		VIEW_CRYSTAL : "K",
		VIEW_COLONISED : "Kolonizētas planētas",
		VIEW_UKMOONSIZE : "Nav zināms",
		VIEW_BACK : "Atpakaļ",
		VIEW_NOTICE : "Piezīmes",
		VIEW_REPORTS : "Spiegošana",
		VIEW_MOONPHALANX : "Šī mēness falangas spēj noskanēt līdz šai sistēmai:",
		VIEW_NOMOONS : "Mēneši  netika atrasti",
		VIEW_IRAKS : "Šīs sistēmas planētu raķetes spēj aizlidot līdz šai sistēmai",
		VIEW_NOIRAKS : "netika atrastas Interplanetārās raķetes",
		VIEW_MOON_DESTROY_CHANCE : "Mēness iznīcināšanas iespēja",
		VIEW_CHANCE_WITH_ONE : "Iespēja ar vienu Nāves Zvaigzn",
		VIEW_CHANCE_WITH_N : "Iespēja ar ",
		VIEW_DEATH_STARS : "Nāves zvaigznes",
		VIEW_DS_DESTROY_CHANCE : "Iespēja zaudēt Nāves Zvaigzni",
		VIEW_TOP : "Top",
		VIEW_GO : "Parādīt",
		VIEW_DIAMETER : "Diameter",
		PW_TITLE : "OGame Galaxietool - Nomainīt paroli",
		OLD_PASSWORD : "Vecā parole",
		NEW_PASSWORD : "Jaunā parole",
		CONFIRM_NEW_PASSWORD : "Apstiprināt jauno paroli",
		PW_MISMATCH : "Ievadītās jaunās paroles nav vienādas!",
		PW_ERROR : "Vecā parole nav derīga!",
		UPDATE_DONE : "Gatavs.",
		TIMEZONE_OFFSET : "Laika zonas nobīde ar serveri",
		DELETE_ACCOUNT : "Dzēst šo Galaxytool lietotāju",
		DELETE_ACCOUNT_SAFETY_REQUEST : "Vai tu tiešām vēlaties dzēt šo Galaxytool akountu?",
		CH_PASSWD_AUTHORIZATION : "Autorizācija",
		CH_PASSWD_ADMIN : "Admin",
		TIMEZONE_OGAME_OFFSET : "Timezone offset to OGame server",
		CH_PASSWD_USER_LANGUAGE : "Change to this language after logon",
		CH_PASSWD_USER_LANGUAGE_NO_CHANGE : "No change",
		CH_PASSWD_EXPAND : "Expanded",
		CH_PASSWD_COLLAPSE : "Collapsed",
		CH_PASSWD_HIDDEN : "Hidden",
		CH_PASSWD_GETTING_STARTED : "Show Getting Started Info after logon",
		CH_PASSWD_PLUGIN : "Show Plugin Info after logon",
		NOTICE_TITLE : "OGame Galaxietool - Piezīmes",
		NOTICE_HEADER : "Rediģēt piezīmi",
		NOTICE_HEADER2 : "Rediģēt savas piezīmes",
		NOTICE_PUBLIC : "Vai ļaut visiem redzēt tavas piezīmes?",
		NOTICE_YES : "Jā",
		NOTICE_NO : "Nē",
		NOTICE_TEXT : "Piezīmes teksts",
		NOTICE_SAVE : "Saglabāt",
		NOTICE_DELETED : "Ieraksts dzēsts.",
		NOTICE_SAVED : "Ieraksts saglabāts.",
		NOTICE_RESULTS : "Visas piezīmes",
		NOTICE_USER : "Lietotājs",
		NOTICE_DATE : "Datums",
		NOTICE_EDIT : "Rediģēt",
		NOTICE_DELETE : "Dzēst",
		NOTICE_NEW : "Dzēst savu ierakstu",
		NOTICE_NOTPUBLIC : "Piezīme nav visiem pieejama.",
		NOTICE_ALL : "Viss",
		NOTICE_NONE : "Nekas",
		NOTICE_SEARCH : "Meklēt Piezīmēs",
		NOTICE_SEARCH_SHORT : "Meklēt",
		NOTICE_HITS : "Rezultāti",
		NOTICE_SHOWRESULTS : "Rezultāti vienā lapā",
		NOTICE_OF : "No",
		NOTICE_NOTHING : "Meklēšana neko nedeva.",
		NOTICE_CHARS : "Zīmes",
		NOTICE_PLAYERNAME : "Spēlētājs",
		NOTICE_SHOWALL : "Parādīt visas piezīmes.",
		REPORTS_TITLE : "OGame Galaxietool - Spiegošanas atskaites",
		REPORTS_RESOURCES : "Resursi",
		REPORTS_FLEET : "Flotes",
		REPORTS_DEFENCE : "Aizsardzība",
		REPORTS_BUILDINGS : "Celtnes",
		REPORTS_TECHNOLOGY : "Pētniecība",
		REPORTS_MOON : "Mēness",
		REPORTS_SEARCH : "Meklēt atskaitēs",
		REPORTS_SEARCH_SHORT : "Meklēt",
		REPORTS_HITS : "Rezultāti",
		REPORTS_NOTHING : "Meklēšana ne priekš rezultātiem.",
		REPORTS_ADDRESS : "Adrese",
		REPORTS_CURRENTNESS : "Aktualitātes",
		REPORTS_PLAYERNAME : "Spēlētāja vārds",
		REPORTS_ALLY : "Alianse",
		REPORTS_VIEW : "Apskatīt atskaiti",
		REPORTS_SEARCH_IN : "Meklēt galaktikā",
		REPORTS_FROM_SYSTEM : "No sistēmas",
		REPORTS_TO : "Līdz",
		REPORTS_DELETE : "Dzēst",
		REPORTS_DELETED : "Ieraksts dzēsts",
		REPORTS_RESULTS : "Rezultāti lappusē",
		REPORTS_OF : "No",
		REPORTS_DATE : "Datums",
		REPORTS_DATE_0 : "Visi",
		REPORTS_DATE_1 : "Vecāki par",
		REPORTS_DATE_2 : "Jaunāki par",
		REPORTS_NOTICES : "Piezīmes",
		REPORTS_AT_LEAST_RESOURCES : "Pavisam resursi (min.)",
		REPORTS_SEARCH_EXTENDED : "Advancētā meklēšana",
		REPORTS_FLEET_RESIS : "Punkti par floti",
		REPORTS_DEFENCE_RESIS : "Punkti par aizsardzību",
		REPORTS_ALL_RESIS : "Kopējais punktu zaudējums",
		REPORTS_TECHS : "Tehnoloģijas",
		REPORTS_UNKNOWN_ENTRIES : "Nezināmie ieraksti",
		REPORTS_PARTLY_INSERTED : "Ievietots daļēji",
		REPORTS_FOR_ALL_RES : "Visiem resursiem",
		REPORTS_FOR_TF : "Atlūzām",
		REPORTS_KT : "Mazais kravas kuģis",
		REPORTS_GT : "Lielais kravas kuģis ",
		REPORTS_SS : "Kaujas kuģis",
		REPORTS_REC : "Pārstrādātājs",
		REPORTS_RAIDABLE : "Tikai mērķus kurus var aplaupīt",
		REPORTS_ALL_RESOURCES : "Kopā resursi",
		REPORTS_STUFF : "Cits",
		REPORTS_SPEEDSIM : "Izskaitļot Speedsim",
		REPORTS_DRAGOSIM : "Izskaitļot Dragosim",
		REPORTS_STATUS : "Status",
		REPORTS_ERROR : "Radusies kļūda",
		REPORTS_OWN_REPORTS : "Tikai mani pārskati",
		REPORTS_UPLOAD_BY : "Pārskatu atjaunoja",
		REPORTS_DEPTH : "Ziņojuma platums",
		REPORTS_FLEET_SCORE : "Flotes punkti",
		REPORTS_DEFENCE_SCORE : "Aizsardzības punkti",
		REPORTS_HOURS : "hours",
		REPORTS_MAX_RESULTS_HIT : "Your query returned more than &1 hits. Only the first &1 results are show. Please adjust your search request to get less results.",
		REPORTS_OSIMULATE : "Simulate with OSimulate",
		REPORTS_SHOW_ONLY : "Show only",
		REPORTS_SHOW_PLANETS : "Planētas",
		REPORTS_SHOW_MOONS : "Mēneši",
		REPORTS_OWNER : "Reports owned by",
		STATS_TITLE : "OGame Galaxietool - Statistika",
		STATS_TBLHEAD : "Statistika",
		STATS_RANK : "Vieta",
		STATS_PLAYERNAME : "Spēlētājs",
		STATS_SCORE : "Punkti",
		STATS_FLEET : "Flote",
		STATS_RESEARCH : "Pētniecība",
		STATS_ALLYNAME : "Alianse",
		STATS_MEMBERS : "Biedri",
		STATS_STATUS : "Status",
		STATS_NOTHING : "Bez statusa",
		STATS_NAP : "Pakts",
		STATS_ALLIED : "Sabiedrotie",
		STATS_WAR : "Karš",
		STATS_BOYCOTT : "Boikots",
		STATS_NEUTRAL : "Neitr. attiecības",
		STATS_OWN : "Mana alianse",
		STATS_WING : "Spārns",
		STATS_UPDATE : "Dati no",
		STATS_PLAYERSTATS : "Spēlētāju statistika",
		STATS_ALLYSTATS : "Alianšu statistika",
		STATS_DELETE : "Dzēs spēlētāju",
		STATS_CONFIRM_DELETE : "Vai jūs tiešām vēlaties dzēst spēlētāju no statistikas?",
		STATS_CHANGE_PLAYER_STATUS : "Spēlētāja statistika",
		STATS_CHANGE_ALLIANCE_STATUS : "Alianses statistika",
		STATS_CHANGE_ALLIANCE_STATUS_HINT : "Visi šis alianses biedri saņem izvēlēto statusu. Iepriekšējais status tiksizmainīts. ir iespējams spēlētājam pēc tam piešķirt atsevišķu statusu.",
		STATS_UNKNOWN : "Pārējie",
		STATS_DETAILS : "Sīkāk priekš",
		STATS_PLAYERSTATUS : "Spēlētāja status",
		STATS_IGNORE_STATUS : "Viss",
		STATS_ACTIVE : "active",
		STATS_INACTIVE : "Neaktīvs",
		STATS_BANNED : "Bloķēts",
		STATS_VACATION : "Atvaļinājuma režīms",
		STATS_NOOB : "Iesācēju aizsardzība",
		STATS_YES : "Jā",
		STATS_NO : "Meklēt tikai planētas ar piezīmēm",
		STATS_SEARCH : "Meklēt",
		STATS_SHOW_GRAPH : "Show details for score distribution",
		STATS_LONG_INACTIVE : "Neaktīvie 4 nedēļas",
		STATS_STANDARD : "Standard Points",
		STATS_MILITARY : "Military Points",
		STATS_ECONOMY : "Economy",
		STATS_HONOUR : "Honour points",
		STATS_MILITARY_BUILD : "Military build",
		STATS_MILITARY_DESTROYED : "Military destroyed",
		STATS_MILITARY_LOST : "Military lost",
		REGISTER_REGISTRATE : "Reģistrācija",
		REGISTER_LOGINNAME : "Logins",
		REGISTER_PASSWORD : "Parole",
		REGISTER_PASSWORD_CONFIRM : "Atkārtot paroli",
		REGISTER_EMAIL : "E-pasts",
		REGISTER_INGAME : "Vārds spēlē",
		REGISTER_ALLYTAG : "Alianses abreviatūra",
		REGISTER_EMAILVERIFICATION : "E-pasta pārbaude",
		REGISTER_EMAILTEXT : "Spied uz šī linka lai beigtu reģistrāciju Galaxietool:",
		REGISTER_ERROR1 : "Šis logins ir jau aizņemts.",
		REGISTER_ERROR2 : "Kļūda nosūtot vēstuli! Sazinieties ar administratoru.",
		REGISTER_ERROR3 : "Kļūda savienojoties ar datu bāzi!",
		REGISTER_INFO1 : "Akounts veiksmīgi izveidots.",
		REGISTER_INFO2 : "Lai pabeigtu reģistrāciju nospiediet uz saites kas tika nosūtīts uz jūsu e - pastu.",
		REGISTER_INFO3 : "E-pasta adrese apstiprināta.Tagad jāgaida kad admins Jūs apstiprinās.",
		REGISTER_BUTTON : "Atpakaļ uz sākumlapu",
		REGISTER_NEW_SUBJECT : "Reģistrēts jauns spēlētājs",
		REGISTER_NEW_MAILTEXT : "Jauns lietotājs piereģistrēts Galaxietool.",
		REGISTER_BACK : "Back to first page",
		REGISTER_MISSING_FIELDS : "Enter all required Fields",
		REGISTER_ERROR4 : "Email address is not valid.",
		REGISTER_ERROR5 : "Passwords don't match.",
		REGISTER_PWS : "Password strength",
		REGISTER_PWS0 : "very weak",
		REGISTER_PWS1 : "weak",
		REGISTER_PWS2 : "good",
		REGISTER_PWS3 : "strong",
		REGISTER_PWS4 : "very strong",
		REGISTER_EMAIL_USED : "Email Address is already used",
		LOSTPW_TITLE : "Paroles atjaunošana",
		LOSTPW_INFO2 : "Jaunā parole tika izveidota un nosūtīta uz norādīto e-pastu.",
		LOSTPW_BUTTON1 : "Pieprasīt paroli",
		LOSTPW_BUTTON2 : "Atpakaļ uz sākumlapu",
		LOSTPW_LOGINNAME : "Logins",
		LOSTPW_EMAIL : "E-pasts",
		LOSTPW_ERROR1 : "Kļūda pieprasot datus!",
		LOSTPW_ERROR2 : "Piemērots ieraksts netika atrasts!",
		LOSTPW_ERROR3 : "Kļūda nosūtot vēstuli! Sazinieties ar administratoru.",
		LOSTPW_EMAIL_SUBJECT : "Paroles atjaunošana",
		LOSTPW_EMAIL_TEXT1 : "Pieprasītie dati lai ieietu Galaxietool",
		LOSTPW_EMAIL_TEXT2 : "Logins",
		LOSTPW_EMAIL_TEXT3 : "Parole",
		LOSTPW_INFO1 : "You will receive an email to verify your password reset request.",
		LOSTPW_CONFIRM_RESET_SUBJECT : "Lost password?",
		LOSTPW_CONFIRM_RESET_MESSAGE : "Hello,\n\nyou requested a password reset for the Galaxytool. To generate a new password, click the following link:",
		USERINFO_TITLE : "OGame Galaxietool - Lietotāja informācija",
		USERINFO_NAMES : "Visi lapas lietotāji",
		USERINFO_DETAIL : "Sīkāk par",
		USERINFO_ERROR1 : "Lietotājs ar tādu ID nav!",
		USERINFO_USERNAME : "Logins",
		USERINFO_INGAME : "Niks spēlē",
		USERINFO_EMAIL : "E-pasts",
		USERINFO_ALLYTAG : "Alianse",
		USERINFO_STYLEPATH : "Skins",
		USERINFO_STATUS : "Status",
		USERINFO_ACTIVATE : "Aktivizēt lietotāju",
		USERINFO_LOGINS : "Ieiešanu skaits lapā",
		USERINFO_LASTLOGIN : "Pēdējā ieiešana lapā",
		USERINFO_DATA : "Info par ievadītajām sistēmām",
		USERINFO_NODATA : "Lietotājs vēl nav ievadījis datus!",
		USERINFO_GALAXY : "Galaktika",
		USERINFO_SYSTEMS : "Sistēmu skaits",
		USERINFO_IP : "IP adrese",
		USERINFO_LOGINTIME : "Ieiešanas laiks sistēmā",
		USERINFO_NOLOGIN : "Lietotājs vēl nav iegājis.",
		USERINFO_LAST_GALAXYUPDATE : "Pēdējais ievadītais galaktikas pārskats",
		USERINFO_LAST_PUBLIC_NOTICE : "Pēdējā publiskā piezīme",
		USERINFO_LAST_PRIVATE_NOTICE : "Pēdējā personīgā piezīme",
		USERINFO_NUMBEROF_PUBLIC_NOTICE : "Publisko piezīmju skaits",
		USERINFO_NUMBEROF_PRIVATE_NOTICE : "Personīgo piezīmju skaits",
		USERINFO_ACTIVATED : "Akaunts aktivizēts",
		USERINFO_ACTIVATIONTEXT : "Galaxietools aktivizēja tavu akauntu.\n\n Veiksmi izmantojot Galaxietool!",
		USERINFO_LAST_SUBMIT : "Inserted last data",
		ALLYHISTORY_TITLE : "OGame Galaxietool - Online statistika",
		ALLYHISTORY_TBLHEAD : "Pārskats",
		ALLYHISTORY_PLAYERNAME : "Spēlētājs",
		ALLYHISTORY_ALLYNAME : "Alianse",
		ALLYHISTORY_LASTMONTH : "Pēdējā mēneša laikā",
		ALLYHISTORY_ALL_DATA : "Visi esošie dati",
		ALLYHISTORY_SHOW : "Parādīt statistiku",
		ALLYHISTORY_TIMESPAN : "Ilgums",
		ALLYHISTORY_PROGESS : "Pieaugums",
		ALLYHISTORY_SCORE : "Punkti",
		ALLYHISTORY_FSCORE : "Punkti par flotēm",
		ALLYHISTORY_RSCORE : "Punkti par pētniecību",
		ALLYHISTORY_MEMBER : "Biedri",
		ALLYHISTORY_NOTHING : "Neko neizdevās atrast",
		ALLYHISTORY_DETAILS : "Detaļas",
		ALLYHISTORY_SHOW_ADDRESS : "Kordinātes",
		ALLYHISTORY_ESCORE : "Economy",
		ALLYHISTORY_MSCORE : "Military Points",
		DETAILEDINFO_PLAYERINFO_TITLE : "Info par spēlētājiem",
		DETAILEDINFO_ALLYINFO_TITLE : "Info par aliansēm",
		DETAILEDINFO_PLAYERINFO_TBLHEAD : "Sīkāka informācija par spēlētāju",
		DETAILEDINFO_ALLYINFO_TBLHEAD : "Sīkāka informācija par aliansi",
		DETAILEDINFO_NO_ALLIANCE : "Nav",
		DETAILEDINFO_SCORE : "Statistika pa punktiem",
		DETAILEDINFO_FLEET : "Statistika pa flotēm",
		DETAILEDINFO_RESEARCH : "Statistika pa pētniecībām",
		DETAILEDINFO_RANK : "Vieta",
		DETAILEDINFO_POINTS : "Punkti",
		DETAILEDINFO_KNOWN_PLANETS : "Zināmās planētas",
		DETAILEDINFO_MOONS : "Zināmie mēneši",
		DETAILEDINFO_PHALANX_AREA : "Falangas atskaite",
		DETAILEDINFO_NO_PHALANX_AREA : "Neizdevās atrast falangu",
		DETAILEDINFO_NOTICES : "Piezīmes",
		DETAILEDINFO_NO_NOTICES : "Nav piezīmju",
		DETAILEDINFO_PREVIOUS_ALLIANCES : "Zināmās iepriekšējās spēlētāja alianses",
		DETAILEDINFO_RESOURCES_PER_HOUR : "Resusrsi stundā",
		DETAILEDINFO_RESOURCES_PER_DAY : "Resursi dienā",
		DETAILEDINFO_RESOURCES_PER_WEEK : "Resursi nedēļā",
		DETAILEDINFO_RESOURCES_PER_MONTH : "resursi mēnesī (30 dienās)",
		DETAILEDINFO_METAL : "Metāls",
		DETAILEDINFO_CRYSTAL : "Kristāls",
		DETAILEDINFO_DEUTERIUM : "Deitērijs",
		DETAILEDINFO_UNKNOWN : "Nezināms",
		DETAILEDINFO_SCORE_DISTRIBUTION : "Punktu sadalījums",
		DETAILEDINFO_GENERAL : "Detaļas",
		DETAILEDINFO_MEMBERS : "Biedri",
		DETAILEDINFO_GRAPHS : "Grafiks",
		DETAILEDINFO_RESOURCES : "Resursi",
		DETAILEDINFO_FLEET_TAB : "Flotes",
		DETAILEDINFO_TECH : "Pētniecība",
		DETAILEDINFO_FLEET_DETAIL : "Sum / (spēlētāji vidēji) starp visām pieejamajamajām atskaitēm",
		DETAILEDINFO_TECH_DETAIL : "Vidēji no visas pieejamās lietotajinformācijas",
		DETAILEDINFO_PLANET_TAB : "Planētas",
		DETAILEDINFO_MOON_TAB : "Mēneši",
		DETAILEDINFO_ACTIVITIES : "Activities",
		DETAILEDINFO_NODATA : "Pagaidām nav datu.",
		DETAILEDINFO_ACTIVITY_DESCRIPTION : "Show activities of &1 collected from:",
		DETAILEDINFO_GALAXYVIEWS : "Galaxy views",
		DETAILEDINFO_SCANS : "Espionage actions",
		DETAILEDINFO_MESSAGES : "Player messages",
		DETAILEDINFO_COMBATS : "Combat reports",
		DETAILEDINFO_ALLYPAGE : "Alliance overview",
		DETAILEDINFO_MANUAL : "Manual insertions",
		DETAILEDINFO_START : "Beginning",
		DETAILEDINFO_TO : "to",
		DETAILEDINFO_TODAY : "Today",
		DETAILEDINFO_DATA_RESTRICTION : "restricted to:",
		DETAILEDINFO_WEEKDAY_WEEKEND : "Weekend",
		DETAILEDINFO_WEEKDAY_WORKINGDAY : "Weekday",
		DETAILEDINFO_WEEKDAY_MONDAY : "Monday",
		DETAILEDINFO_WEEKDAY_TUESDAY : "Tuesday",
		DETAILEDINFO_WEEKDAY_WEDNESDAY : "Wednesday",
		DETAILEDINFO_WEEKDAY_THURSDAY : "Thursday",
		DETAILEDINFO_WEEKDAY_FRIDAY : "Friday",
		DETAILEDINFO_WEEKDAY_SATURDAY : "Saturday",
		DETAILEDINFO_WEEKDAY_SUNDAY : "Sunday",
		DETAILEDINFO_WEEKDAY_SHORTLENGTH : 3,
		DETAILEDINFO_PLAYER_CURRENTLY_ACTIVE : "The player is currently active",
		DETAILEDINFO_PLAYER_MESSAGES : "available player messages",
		DETAILEDINFO_SHOW : "show",
		DETAILEDINFO_NONE : "none available",
		DETAILEDINFO_ENTER_MANUALLY : "Enter activities for this player",
		DETAILEDINFO_PLAYER_SEEN_ON : "Player was online on",
		DETAILEDINFO_INSERT : "Insert",
		DETAILEDINFO_OGAME_SERVERTIMES : "Please note: All dates and times refer to OGame server times !",
		DETAILEDINFO_DAY_VIEW : "24 hours view",
		DETAILEDINFO_WEEK_VIEW : "weekly view",
		DETAILEDINFO_HOME_PLANET : "Homeworld",
		DETAILEDINFO_PLANETNAME : "Name",
		DETAILEDINFO_DEFENCE_SCORE : "Defence score",
		DETAILEDINFO_DEFENCE_SCORE_TOOLTIP : "Defence score = Fleet - Score + Research + Economy.<br/>All those statistics must be up to date to have a meaningful result!",
		DETAILEDINFO_SCORE_PER_SHIP : "Scores per ship",
		DETAILEDINFO_SHIPS : "Number of ships",
		DETAILEDINFO_DATE_IN_FUTURE : "Do not maintain times which are not in the past.",
		ADMIN_TITLE : "Galaxytool administrēšana",
		ADMIN_DISCLAMER : "Uzmanību: Lietot jebkuru no šiem scriptiem ir uz Jūsu atbildību! Vairums no tiem dzēš datus.",
		ADMIN_INCONSISTENCIES : "Neatbilstība datubāzē",
		ADMIN_PLANETS : "Planētas 0 slotā vai planētas slotos kas lielāki par 15",
		ADMIN_GALAXIES : "Dzēst galaktikas lielākas par &1 ",
		ADMIN_PLAYERS : "Dzēst spēlētājus bez OGame playerid - kopēt spēlētāja ievadītos datus",
		ADMIN_REPORTS : "Dzēst ziņojumus kuros vaira nav planētas",
		ADMIN_MISC : "Dažādi",
		ADMIN_RESET : "Reset Galaxytool (Tikai lietotāji un Iptabulas netiks dzēstas)",
		ADMIN_OLD_PLAYERS : "Dzēst spēlētāju ievades kas vecākas par &1 dienām",
		ADMIN_OLD_REPORTS : "Dzēst atskaites kas vecākas par &1 dienām",
		ADMIN_LOADING : "Neaizve šo lapu kamēr lapa pārlādējas.",
		ADMIN_STATUS : "Tavu pieprasījumu status",
		ADMIN_SELECTION : "Vsimaz vienai ievadei jābut aktivizētai",
		ADMIN_SAFETY : "Vai esi pārliecināts ka vēlies palaist  scriptu(us) ?",
		ADMIN_DONE : "Darīts",
		ADMIN_NOTBD : "Nekas netika izdarīts",
		ADMIN_OLD_GALAXIES : "Dzēst galaktikas pārskatus kas vecākas par &1 dienām",
		ADMIN_UNUSED_PLAYERS : "Dzēst spēlētāju kurš neatjauno galaktikas pārskatus",
		ADMIN_OLD_ACTIVITIES : "Remove player activities older than &1 days",
		ADMIN_OLD_COMBATS : "Remove combat reports older than &1 days",
		ADMIN_OLD_INGAME_MSG : "Remove ingame messages older than &1 days",
		ADMIN_OGAME_API : "Load public data from OGame into the Galaxytool",
		ADMIN_OGAME_ALL_DATA : "Visi esošie dati",
		ADMIN_OGAME_GALAXY_DATA : "Galaktikas pārskats",
		ADMIN_OGAME_STATISTICS_DATA : "Statistika",
		ERRORPAGE_PAGEFORWARD : "Click here if your browser does not support page forwarding",
		ERRORPAGE_PERMISSION_DENIED : "You don't have the permission to enter this page. Click to go back.",
		FLEETS_TITLE : "OGame Galaxytool - Fleet movements",
		FLEETS_ACTUAL_FLEETS : "Current fleet movements",
		FLEETS_YES : "Jā",
		FLEETS_NO : "Meklēt tikai planētas ar piezīmēm",
		FLEETS_DETAILS : "Details",
		FLEETS_MISSION_EXPEDITION : "Expedition",
		FLEETS_MISSION_COLONIZATION : "Colonize",
		FLEETS_MISSION_RECYCLE : "Harvest",
		FLEETS_MISSION_TRANSPORT : "Transport",
		FLEETS_MISSION_DEPLOYMENT : "Deploy",
		FLEETS_MISSION_ESPIONAGE : "Espionage",
		FLEETS_MISSION_ACS_DEFEND : "ACS Defend",
		FLEETS_MISSION_ATTACK : "Attack",
		FLEETS_MISSION_ACS_ATTACK : "ACS Attack",
		FLEETS_MISSION_MOON_DESTRUCTION : "Moon Destruction",
		FLEETS_MISSION_MISSILE_ATTACK : "Missile Attack",
		FLEETS_NO_DATA : "No applicable data found",
		FLEETS_FLEET : "Fleet",
		FLEETS_ALL_FLEETS : "Show all fleet movements",
		COMBAT_REPORT_OUDATED_GALAXYVIEW : "Your galaxy data is outdated. Please visit combat origin and target coordinates first!",
		MESSAGES_TITLE : "OGame Galaxytool - OGame Messages",
		MESSAGES_PLAYERNAME : "Playername",
		MESSAGES_SUBJECT : "Subject",
		MESSAGES_DATE : "Date",
		MESSAGES_FILTER : "Filter",
		MESSAGES_DELETE : "Delete message",
		MESSAGES_PUBLISH_DETAIL : "Publish message by adding the message content to notice text of that player.",
		MESSAGES_PUBLISH_HEADER : "&sender sent a message to &recipient on &date:\n\n &message",
		MESSAGES_PLAYER_FILTER : "Messages for player:",
		MESSAGES_CONTENT : "Content",
		COMBATS_TITLE : "OGame Galaxytool - Combat reports",
		COMBATS_ATTACKER : "Attacker",
		COMBATS_DEFENDER : "Defender",
		COMBATS_DATE : "Date",
		COMBATS_OWNER : "Owner",
		COMBATS_WINNER : "Winner",
		COMBATS_COMBATREPORT : "Combat Report",
		COMBATS_COMBAT_AT : "Combat at",
		COMBATS_LOST_UNITS : "Lost units",
		COMBATS_LOOT : "Loot",
		COMBATS_DEBRIS : "Debris",
		COMBATS_AND : "and",
		COMBATS_PUBLISH : "Make this report public",
		COMBATS_UNPUBLISH : "Unshare this report (makes it private again)",
		COMBATS_DELETE : "Delete report",
		COMBATS_CHECK_ALL : "Check All",
		COMBATS_UNCHECK_ALL : "Uncheck All",
		COMBATS_WITH_SELECTED : "With selected",
		COMBATS_PUBLIC_REPORTS : "Public reports",
		COMBATS_YES : "Jā",
		COMBATS_NO : "Meklēt tikai planētas ar piezīmēm",
		COMBATS_SEARCH_OPTIONS : "Search options",
		COMBATS_SEARCH : "Go",
		COMBATS_RESET : "Reset",
		COMBATS_COORDINATES : "Koordinātes",
		COMBATS_INVALID_GALAXY_ENTERED : "Invalid Galaxy entered",
		COMBATS_INVALID_SYSTEM_ENTERED : "Invalid System entered",
		COMBATS_INVALID_PLANET_ENTERED : "Invalid Planet entered",
		COMBATS_GALAXY_FROM_TO : "Galaxy",
		COMBATS_SYSTEM_FROM_TO : "System",
		COMBATS_PLANET_FROM_TO : "Planet",
		COMBATS_APPLY : "Apply",
		COMBATS_COMBAT_SUMMARY : "Combat report summary",
		COMBATS_DOWNLOAD_CSV : "Download as CSV file",
		REPORT_ARCHIVE_TITLE : "Report archive",
		REPORT_ARCHIVE_COORDINATES : "Coordinates",
		REPORT_ARCHIVE_SCANTIME : "Scan time",
		REPORT_ARCHIVE_DELETE : "Delete these entries",
		REPORT_ARCHIVE_CONFIRM_DELETE : "Do you really want to delete these entries?",
		REPORT_ARCHIVE_GALAXY : "Galaxy",
		REPORT_ARCHIVE_SYSTEM : "System",
		REPORT_ARCHIVE_PLANET : "Planet",
		REPORT_ARCHIVE_MOON : "Moon",
		REPORT_ARCHIVE_DETAILS : "Details",
		REPORT_ARCHIVE_RESOURCES : "Resusrsi stundā",
		REPORT_ARCHIVE_HEADER_RESOURCES : "Resursi",
		REPORT_ARCHIVE_DETAILS_FOR : "Report archive for &1 [&2] (&3)",
		REPORT_ARCHIVE_FLEET_CARGO : "Fleet cargo capacity",
		REPORT_ARCHIVE_IRAK_RANGE : "Interplanetary Missiles range",
		REPORT_ARCHIVE_CHART_TYPE : "Chart type",
		INSTALL_TITLE : "Galaxytool installation for version",
		INSTALL_PROGRESS : "Overall progress",
		INSTALL_STEP : "Step",
		INSTALL_CONTINUE : "Continue",
		INSTALL_VALIDATE : "Validate",
		INSTALL_STEP1 : "Welcome",
		INSTALL_STEP2 : "Writeable check",
		INSTALL_STEP3 : "Database settings",
		INSTALL_STEP4 : "OGame settings",
		INSTALL_STEP5 : "Galaxytool settings",
		INSTALL_STEP6 : "Admin password",
		INSTALL_STEP7 : "Install Galaxytool",
		INSTALL_STEP8 : "Finalize install",
		INSTALL_FILE_DELETE_CHECK : "Please delete install.php and update.php from your webserver.",
		INSTALL_STEP1_PHP_FAILED : "Your PHP version &1 is not working with this Galaxytool version",
		INSTALL_STEP1_FOPEN_FAILED : "Your PHP version does not allow to open webpages with FOPEN() command. This is required to consume the OGame API.",
		INSTALL_STEP1_WELCOME : "Welcome to the installation wizard of the Galaxytool. You will be guided through the installation of the Galaxytool.",
		INSTALL_STEP2_DESCRIPTION : "Make sure your config.php and attributes.php files have write permissions enabled.",
		INSTALL_STEP2_DESCRIPTION2 : "If you don't know, how to achieve this, please take a look here: &1",
		INSTALL_STEP2_FILE_NOT_WRITEABLE : "File is not writeable",
		INSTALL_STEP3_SERVER : "Database server",
		INSTALL_STEP3_USERNAME : "Lietotājvārds",
		INSTALL_STEP3_PASSWORD : "Parole",
		INSTALL_STEP3_DBNAME : "Database name",
		INSTALL_STEP3_PREFIX : "Tablename prefix",
		INSTALL_STEP3_ENTER_PREFIX : "E.g. mytool_",
		INSTALL_STEP3_ENTER_SERVER : "Enter the server address. Contact your system admin if necessary. Usually the correct value is localhost.",
		INSTALL_STEP3_ENTER_USERNAME : "Enter the username for database access",
		INSTALL_STEP3_ENTER_PASSWORD : "Enter the password for database access",
		INSTALL_STEP3_ENTER_DBNAME : "Enter the database name which shall be used for installation (must exist)",
		INSTALL_STEP3_CONNECT_FAILED : "Could not establish connection to database server",
		INSTALL_STEP3_DB_FAILED : "Database &1 not found",
		INSTALL_STEP3_MYSQL_VERSION_FAILED : "MySQL version &1 is not working with this Galaxytool version",
		INSTALL_STEP4_URL : "OGame URL",
		OGAME_URL_DETAILS : "Please enter any URL you see when you are logged on to OGame. Based on that URL the tool will derive the OGame API address which can be used to fill data into the Galaxytool without the Galaxytoolbar. This API was introduced with OGame version 4.1.",
		INSTALL_STEP4_UNIVERSE : "OGame Universe",
		INSTALL_STEP4_DEF_TO_DEBRIS : "Defense to debris",
		INSTALL_STEP4_DEBRIS_RATE : "Debris rate",
		INSTALL_STEP4_SPEED_RATE : "Speed rate",
		INSTALL_STEP4_ENTER_UNIVERSE : "Enter your OGame universe name or number (case sensitive).",
		INSTALL_STEP4_UNIVERSE_MISSING : "You must define your universe",
		INSTALL_STEP4_ENTER_URL : "Enter your OGame universe address",
		INSTALL_STEP4_URL_MISSING : "You must define your OGame address",
		INSTALL_STEP4_URL_CHECK_FAILED : "Could not find OGame API at &1",
		INSTALL_STEP4_GETSETTINGS : "Fetch settings",
		INSTALL_STEP5_TOOLNAME : "Galaxytool name",
		INSTALL_STEP5_ENTER_TOOLNAME : "This is the name which will be shown at logon page to identify your Galaxytool",
		INSTALL_STEP5_LANGUAGE : "Default language",
		INSTALL_STEP5_EMAIL_TO : "Email To",
		INSTALL_STEP5_ENTER_EMAIL_TO : "Enter the email address where you would like to receive notifications about registrations",
		INSTALL_STEP5_EMAIL_FROM : "Email From",
		INSTALL_STEP5_ENTER_EMAIL_FROM : "This email address is shown as REPLY for all mails sent from the Galaxytool",
		INSTALL_STEP5_USE_PHPMAILER : "Use PHPMailer",
		INSTALL_STEP5_MAXSHOUTS : "Maximum number of shoutbox entries",
		INSTALL_STEP5_ENTER_USE_PHPMAILER : "Use PHPMailer if your server does not support sending emails by default",
		INSTALL_PHPMAILER_HOST : "SMPT Host",
		INSTALL_PHPMAILER_HOST_EXAMPLE : "e.g. smtp.provider.com",
		INSTALL_PHPMAILER_USER : "SMPT Username",
		INSTALL_PHPMAILER_USER_EXAMPLE : "e.g. user@provider.dcom",
		INSTALL_PHPMAILER_PASS : "SMPT password",
		INSTALL_PHPMAILER_SECURE : "Authentification method (e.g. ssl)",
		INSTALL_PHPMAILER_PORT : "SMTP Port",
		INSTALL_STEP6_INTRO : "Please define a password for the <strong>admin</strong> account which you have to use for your first logon to the Galaxytool after the installation.",
		INSTALL_STEP7_CONFIG : "Configuration file created",
		INSTALL_STEP7_CONFIG_FAILED : "Configuration file not created",
		INSTALL_STEP7_ATTRIBUTES : "Attributes file created",
		INSTALL_STEP7_ATTRIBUTES_FAILED : "Attributes file not created",
		INSTALL_STEP7_CREATED_TABLES : "Database tables created",
		INSTALL_STEP8_INTRO : "You have successfully installed the Galaxytool!",
		INSTALL_STEP8_LOAD_DATA : "Downloading OGame data ...",
		INSTALL_STEP8_LOAD_DATA_FINISHED : "Download of OGame data finished",
		INSTALL_STEP8_DELETE_FILE : "You should now delete the installation files install.php and update.php from your webserver.",
		INSTALL_STEP8_LOGON : "Please logon with the <strong>admin</strong> user and the password you defined earlier.",
		UPDATE_START : "Starting update to version &1",
		UPDATE_STEP_DONE : "Done",
		UPDATE_TITLE : "Galaxytool update for version",
		UPDATE_STEP1_WELCOME : "Welcome to the update wizard of the Galaxytool. You will be guided through the update of the Galaxytool.",
		UPDATE_STEP1_BACKUP_FILES : "As a first step, make a backup of your <strong>config</strong> folder! You will have to replace the configuration content in case of errors.",
		UPDATE_STEP1_BACKUP_DB : "Then make a <a href=\"http://www.ehow.com/how_2036600_create-database-php.html\">backup</a> of your database.",
		UPDATE_STEP1_PROCEED : "Once the backups have been done, you can proceed with your update.",
		UPDATE_STEP1 : "Welcome",
		UPDATE_STEP2 : "Galaxytool settings",
		UPDATE_STEP2_OLD_VERSION : "Previous Galaxytool version",
		UPDATE_STEP3 : "Update Galaxytool",
		UPDATE_STEP3_UPDATE_RUNNING : "Update running, please wait...",
		UPDATE_STEP4 : "Finalize Update",
		UPDATE_STEP4_INTRO : "You have successfully updated the Galaxytool!",
		UPDATE_STEP4_UPDATE_DONE : "Update steps performed.",
		UPDATE_FAILED : "Update failed.",
		GALAXYTOOL_DUMMY_TEXT : "dummy"
	})
);