define(
	({
		REPORT_WHEN : "a las",
		RESOURCES_ON : "Recursos en",
		PLAYER_BANNED : "s",
		PLAYER_VACATION_MODE : "v",
		PLAYER_NOOB : "d",
		PLAYER_INACTIVE : "i",
		PLAYER_LONG_INACTIVE : "I",
		PLAYER_OUTLAW : "o",
		L_USERNAME : "Usuario",
		L_PASSWORD : "Contraseña",
		L_LOGINFAILURE : "Su nombre de usuario o contraseña son incorrectos o su cuenta no ha sido activada aún.",
		L_TOKENFAILURE : "Su llave de Login es errónea o aún no está activado.",
		L_LOGINTEXT : "Por favor introduzca sus datos de acceso:",
		L_LANGUAGE : "Idiomas disponibles:",
		L_TIMEOUT : "¡Su sesión ha expirado!",
		L_REGISTER : "Registrarse",
		L_PWLOST : "Contraseña olvidada",
		INDEX_TITLE : "Visión General",
		INDEX_INFO : "Información",
		INDEX_ENTRIES : "Sistemas en total",
		INDEX_ENTRIES_LASTWEEK : "Nuevos sistemas en la última semana",
		INDEX_ENTRIES_TO_OLD : "Sistemas con antigüedad superior al mes",
		INDEX_REGISTERED_USERS : "Usuarios registrados",
		INDEX_PAGEFORWARD : "Si su navegador no soporta la redirección automática haga clic aquí.",
		INDEX_NOTICES : "Notas",
		INDEX_PLAYERS : "Estadísticas de Jugadores",
		INDEX_ALLIES : "Estadísticas de Alianzas",
		INDEX_REPORTS : "Informes de Espionaje",
		INDEX_VERSION : "Última versión para descargar",
		INDEX_LATEST_VERSION : "No hay una nueva versión disponible",
		INDEX_SHOUTBOX : "Mensajes actuales",
		INDEX_NOENTRY : "Sin mensajes",
		INDEX_COMMENT : "Tu comentario",
		INDEX_INSERT : "Introducir",
		INDEX_UMOD : "Jugadores en modo vacaciones",
		INDEX_NO_MOONS : "Cantidad de Lunas",
		INDEX_NO_EMPTY_SYSTEMS : "Cantidad de sistemas vacíos",
		INDEX_NO_FULL_SYSTEMS : "Cantidad de sistemas llenos",
		INDEX_NO_TARGETS : "Cantidad de planetas atacables",
		INDEX_USERINFO : "Usuarios",
		INDEX_ONLINE : "Ahora conectados",
		INDEX_TODAY : "Hoy conectados",
		INDEX_ALL : "Entradas totales",
		GENERAL_LOAD_FORM : "Cargar datos formulario",
		GENERAL_SAVE_FORM : "Guardar datos formulario",
		GENERAL_SAVE_AS_TEXT : "Guardar como",
		GENERAL_SAVE : "Guardar",
		INDEX_USERMANAGEMENT : "Visión de Activación",
		INDEX_NEEDADMIN : "Cuentas para activar",
		INDEX_NEEDEMAIL : "Cuentas aún no validadas",
		INDEX_TOOLBAR_INFO : "Informaciones sobre el Plugin Galaxytool",
		INDEX_TOOLBAR_URL : "URL Galaxytool",
		INDEX_TOOLBAR_VERSION_REQUIRED : "Versión mínima del Plugin de Galaxytool",
		INDEX_TOOLBAR_INSTALL_GUIDE : "Instrucciones de Instalación para el Plugin",
		INDEX_TOOLBAR_TOKEN : "Llave Login",
		INDEX_TOOLBAR_NEW_TOKEN : "Generar nueva Llave",
		INDEX_PLAYERS_WITH_N_PLANETS : "Jugador con más de &1 planetas",
		INDEX_GETTING_STARTED : "Primeros pasos con el Galaxytool",
		INDEX_GETTING_STARTED1 : "¡Bienvenido en el Galaxytool!",
		INDEX_GETTING_STARTED2 : "El Galaxytool te ayudará a averiguar lo que ocurre en tu Universo &1.",
		INDEX_GETTING_STARTED3 : "Para poder analizar los datos, es preciso integrar estos en el Tool. Para ello necesitas de un Plugin como el &1 para Firefox.",
		INDEX_GETTING_STARTED4 : "Tras instalar y configurar el Plugin navegas por las distintas páginas de OGame como de costumbre. Aparecerá una pequeña ventana de status adicional, cada vez que se transmitan datos al Galaxytool.",
		INDEX_GETTING_STARTED5 : "Una vez que haya suficientes datos en el Galaxytool, puede comenzar el análisis. Así se puede mirar, donde los Jugadores tienen sus Colonias, de cuántas disponen, los informes de espionaje que existen de ellos y cuándo se encuentran conectados.",
		INDEX_GETTING_STARTED6 : "El Galaxytool también puede servir para analizar tu propio progreso, comparándote con otros jugadores y analizando tus propios informes de batalla para ver lo que has capturado en los últimos días/semanas",
		INDEX_GETTING_WIKIPAGE : "Esto sólo eran unos ejemplos de las funciones del Galaxytool.",
		INDEX_GETTING_WIKIPAGE2 : "En nuestra página de Wiki encontrarás recogidas todas las funciones.",
		INDEX_GETTING_BOARD : "En nuestro Foro puedes plantear consultas o sugerencias:",
		INDEX_GETTING_CHAT1 : "O visítanos directamente en el canal de chat:",
		INDEX_GETTING_CHAT2 : "No estamos las 24 horas / 7 días a la semana conectados, pero sí que nos puedes encontrar la mayor parte del tiempo allí. Por favor, no seas impaciente si tras 30 segundos no respondemos.",
		INDEX_CLOSE : "Cerrar",
		INDEX_LOGIN : "Login",
		GENERAL_REQUIRED_FIELDS : "Por favor rellena todos los campos",
		INDEX_MESSAGES : "Mensajes",
		INDEX_EXAMPLE : "Ejemplo",
		INDEX_INVALID_DATA : "Entrada inválida",
		GENERAL_COLUMN_HIDE_TITLE : "Gestion columnas",
		GENERAL_COLUMN_HIDE_INFO : "Aquí puedes elegir qué columnas mostrar en la tabla.",
		GENERAL_ENTRIES_DELETED : "&1 Entradas borradas",
		GENERAL_APPLY : "Aplicar",
		STARTPAGE_GALAXYTOOL_DESCR : "<em>Galaxytool</em> es una herramienta para el conocido Juego OGame.",
		GENERAL_OVERWRITE : "Sobreescribir entrada",
		GENERAL_OVERWRITE_QUESTION : "¿Sobreescribir?",
		INDEX_OWN_LOGINS : "Cantidad de tus logins",
		GENERAL_OPEN_IN_NEW_WINDOW : "Abrir enlace en una ventana nueva",
		GENERAL_UNIT_OF_MEASURE_DAYS : "Days",
		PROGRAM_NAME : "OGame Galaxytool",
		SHORTNAME : "Galaxytool",
		BACK_INDEX : "Volver a la página principal",
		UNIVERSE : "Universo",
		MENU_INFO_LINKS : "Información",
		MENU_PAGE : "Visión General",
		MENU_DB_SEARCH : "Buscar en la base de datos",
		MENU_DB_NOTICES : "Buscar Notas",
		MENU_DB_REPORTS : "Buscar informes de espionaje",
		MENU_GALAXYVIEW : "Galaxia",
		MENU_STATISTICS : "Estadísticas",
		MENU_ALLYHISTORY : "Estadísticas temporales",
		MENU_FLEET_MOVEMENTS : "Movimientos de flotas",
		MENU_COMBAT_REPORTS : "Informes de Batalla",
		MENU_MESSAGES : "Mensajes de Jugador",
		MENU_OPTION_LINKS : "Opciones",
		MENU_DB_REFRESH : "Actualizar la base de datos",
		MENU_NOTICES : "Notas",
		MENU_DB_STATUS : "Estado de la base de datos",
		MENU_USEROPTIONS : "Gestión usuarios",
		MENU_USEROPTIONS2 : "Opciones de usuario",
		MENU_USEROPTIONS3 : "Información de usuarios",
		MENU_ADMIN : "Administración",
		MENU_LOGOUT : "Desconectarse",
		MENU_STUFF : "Otros",
		MENU_FORUM_THREAD : "Foro desarrolladores",
		MENU_DOWNLOADPAGE : "Página de descarga",
		MENU_LANGUAGE : "Elegir idioma",
		MENU_HELP : "Ayuda",
		MENU_TOOLOPTIONS : "Opciones del Galaxytool",
		PARSER_INFO1 : "ha sido añadido a la base de datos",
		PARSER_ERROR1 : "Error al intentar añadir las siguientes coordenadas:",
		PARSER_ERROR2 : "¡Error al seleccionar la base de datos!",
		PARSER_ERROR3 : "¡No se ha podido encontrar el servidor de la base de datos!",
		PARSER_WRONG_UNIVERSE : "Universo incorrecto - actual: \"&1\" esperado: \"&2\"",
		SHOW_TITLE : "OGame Galaxietool - Página de consulta",
		SHOW_SEARCH : "Búsqueda en la base de datos",
		SHOW_ALLYSYMBOL : "Etiqueta de Alianza",
		SHOW_PLAYERNAME : "Nombre del Jugador",
		SHOW_MOONS : "Sólo buscar Lunas",
		SHOW_NOTICES : "Sólo buscar planetas con Notas",
		SHOW_COLONIES : "Sólo planetas Colonizables",
		SHOW_YES : "Sí",
		SHOW_NO : "No",
		SHOW_SEARCHRANGE : "Rango de Búsqueda",
		SHOW_SEARCH_IN : "Búsqueda en la Galaxia",
		SHOW_FROM_SYSTEM : "del sistema",
		SHOW_FROM_PLANET : "de la posición",
		SHOW_TO : "hasta el",
		SHOW_DESCRIPTION : "En el caso de jugadores y etiquetas de alianza se pueden utilizar * como comodines, de tal forma que *Jugador* busca a todos los jugadores cuyo nombre incluya &quot;Jugador&quot;.<br />No hay que rellenar todos los campos, de forma que se pueden buscar las coordenadas de una alianza, o de todas las lunas de una alianza.",
		SHOW_SORT_BY : "Ordenar por",
		SHOW_GALASYSTEM : "Galaxia/Sistemas",
		SHOW_ALLYNAME : "Nombre de la Alianza",
		SHOW_SEARCHBUTTON : "Buscar",
		SHOW_ADDRESS : "Coordenadas",
		SHOW_ALLYSORT : "Alianza",
		SHOW_PLANET : "Nombre planeta",
		SHOW_STATUS : "Estado",
		SHOW_CURRENTNESS : "Actualizado",
		SHOW_PLAYER_STATUS : "Estado jugador",
		SHOW_PLAYER_STATUS1 : "todos",
		SHOW_PLAYER_STATUS2 : "atacable",
		SHOW_PLAYER_STATUS3 : "inactivo",
		SHOW_HITS : "Resultados",
		SHOW_OF : "de",
		SHOW_ASC : "ascendente",
		SHOW_DESC : "descendente",
		SHOW_RESULTS : "Coincidencias a mostrar",
		SHOW_MOON : "Luna",
		SHOW_UKMOONSIZE : "desconocido",
		SHOW_DF : "Escombros",
		SHOW_DF_LONG : "Escombros",
		SHOW_METAL : "M",
		SHOW_METAL_LONG : "Metal",
		SHOW_CRYSTAL : "C",
		SHOW_CRYSTAL_LONG : "Cristal",
		SHOW_BOTH : "Juntos",
		SHOW_AT_LEAST : "(min.)",
		SHOW_DATE : "Fecha",
		SHOW_DATE_0 : "igual",
		SHOW_DATE_1 : "más antiguo que",
		SHOW_DATE_2 : "más nuevo que",
		SHOW_RANK : "Rank en Puntos",
		SHOW_FRANK : "Rank en Flotas",
		SHOW_MEMBERS : "Miembros",
		SHOW_NOTRANKED : "Fuera del Top 1500.",
		SHOW_NOTICERES : "Notas",
		SHOW_REPORTS : "Sólo planetas con informes",
		SHOW_REPORTS_SHORT : "Espionaje",
		SHOW_NOTHING : "No se han encontrado coincidencias",
		SHOW_ALLIANCE_STATUS : "Estado Alianza",
		SHOW_NO_STATUS : "Sin Estado",
		SHOW_NAP : "PNA",
		SHOW_ALLIED : "Aliado",
		SHOW_WAR : "Guerra",
		SHOW_BOYCOTT : "Boikot",
		SHOW_NEUTRAL : "Neutral",
		SHOW_OWN : "Propia Alianza",
		SHOW_WING : "Cantera",
		SHOW_EXT_OPTIONS1 : "Muestra opciones de búsqueda avanzadas para búsquedas de alcance, de rangos, fechas así como de campos de escombros.",
		SHOW_EXT_OPTIONS2 : "Muestra opciones de búsqueda avanzadas para búsquedas de sitios colonizables, Lunas, Informes, Notas, Estado de jugadores o diplomacia.",
		SHOW_EXT_OPTIONS3 : "Muestra opciones de búsqueda avanzadas para ordenar los resultados de la búsqueda.",
		SHOW_EXTENDED : "Búsqueda ampliada",
		SHOW_MOON_SELECTION : "Planeta con Luna",
		SHOW_REPORT_SELECTION : "Planeta con Informe de Espionaje",
		SHOW_FILTER_BY : "excluir de los filtros de búsqueda",
		SHOW_FILTER_NONE : "ninguno",
		SHOW_PLAYERS_WITHOUT_PROGRESS : "Show players without score changes within the last few days",
		STATUS_TITLE : "OGame Galaxietool - Página Estado",
		STATUS_DB_STATUS : "Estado de la base de datos",
		STATUS_COLOR : "Color",
		STATUS_AGE1 : "Entrada con un día de antigüedad.",
		STATUS_AGE2 : "Entrada con 2-4 días de antigüedad.",
		STATUS_AGE3 : "Entrada con 4-7 días de antigüedad.",
		STATUS_AGE4 : "Entrada con 1-2 semanas de antigüedad.",
		STATUS_AGE5 : "Entrada con 2-4 semanas de antigüedad.",
		STATUS_AGE6 : "¡Entrada con antigüedad superior a un mes!",
		STATUS_AGE7 : "Sin entradas existentes.",
		STATUS_ON : "Activo",
		STYLES_COLOR1 : "Color1",
		STYLES_COLOR2 : "Color2",
		STYLES_COLOR3 : "Color3",
		STYLES_COLOR4 : "Color4",
		STYLES_COLOR5 : "Color5",
		STYLES_COLOR6 : "Color6",
		STYLES_COLOR7 : "Color7",
		STATUS_DB_LEGEND : "Leyenda",
		STATUS_GALAXY : "Visión de Galaxia",
		USER_TITLE : "OGame Galaxietool - Gestión de usuarios",
		USER_NAMES : "Usuarios",
		USER_ERROR : "Error",
		USER_NEWUSER : "Nuevo usuario",
		USER_OPTIONS : "Opciones",
		USER_USERNAME : "Nombre del usuario",
		USER_PASSWORD : "Contraseña",
		USER_PASSWORD_CONFIRM : "Repetir contraseña",
		USER_GALAXY : "Galaxia",
		USER_SEARCH : "Buscar",
		USER_INSERT : "Añadir",
		USER_DELETE : "Borrar",
		USER_DELETE_ENTRY : "Realmente quiere borrar al jugador: ",
		USER_STATUS : "Visión Estado",
		USER_STYLES : "Adaptar Estilos",
		USER_SUBMIT : "Enviar",
		USER_RESET : "Resetear",
		USER_YES : "Sí",
		USER_NO : "No",
		USER_STYLEPATH : "Ruta hacia el styles.css",
		USER_PROBES : "Informe de espionaje",
		USER_EMAIL : "Email",
		USER_ERROR1 : "Contraseña incorrecta o Email inválido.",
		USER_ERROR2 : "Dirección Email inválida.",
		USER_INGAME : "Nombre en OGame",
		USER_ALLYTAG : "Etiqueta de la Alianza",
		USER_ALLYHISTORY : "Historia de la Alianza",
		USER_DIPLOMATIC : "Diplomático",
		USER_STATSPAGE : "Cantidad de entradas en las estadísticas",
		USER_LINKS : "Enlaces",
		USER_LINKS2 : "Formato:<br>texto;url<br>texto2;url2<br>texto3;url3",
		USER_EXPORT_TITLE : "Colores (BB Codes)",
		USER_BB_COORDINATES : "Coordenadas",
		USER_BB_MOON : "Luna",
		USER_BB_DEBRIS : "Escombros",
		USER_BB_ALLY : "Nombre de la Alianza",
		USER_BB_ALLYDETAILS : "Detalles de la Alianza",
		USER_BB_PLAYERNAME : "Nombre del jugador",
		USER_BB_BANNED : "Baneado",
		USER_BB_VACATION : "Modo vacaciones",
		USER_BB_NOOB : "Protección de novatos",
		USER_BB_INACTIVE : "Inactivo",
		USER_BB_LONGINACTIVE : "Inactivo",
		USER_DELETION : "Borrar",
		USER_FLEETINFO : "Movimientos de flotas",
		USER_ACTIVITIES : "Actividades Jugador",
		USER_MAINTENANCE : "Mantenimiento",
		USER_MANAGEMENT : "Gestión usuarios",
		USER_DELETE_MY_COMBAT_REPORTS : "Borrar mis Informes de Batalla",
		USER_DELETE_MY_MESSAGES : "Borrar mis Mensajes de Jugador",
		USER_DELETE_MY_FLEETMOVES : "Borrar mis Movimientos de Flotas",
		USER_DELETE_MY_COMBAT_REPORTS_LIMITED : "Borrar mis informes de batalla que sean más antiguos que &1 días",
		USER_DELETE_MY_MESSAGES_LIMITED : "Borrar mis mensajes de jugadores que sean más antiguos que &1 días",
		USER_TABLE_ENTRIES : "Cantidad de resultados de búsqueda por página",
		USER_EXISTS : "Ya existe un usuario con este nombre",
		USER_BB_OUTLAW : "proscrito",
		USER_INVALID_URL : "La dirección &1 no parece ser válida. Por favor modifícala o será ignorada.",
		VIEW_TITLE : "OGame Galaxietool - Vista detallada",
		VIEW_NODATA : "No hay datos disponibles.",
		VIEW_GALAXY : "Galaxia",
		VIEW_SYSTEM : "Sistema",
		VIEW_POSITION : "Pos.",
		VIEW_PLANET : "Planeta",
		VIEW_MOON : "Luna",
		VIEW_TF : "Escombros",
		VIEW_PLAYER : "Jugador",
		VIEW_PLAYER_ADD : "(Estado)",
		VIEW_ALLY : "Alianza",
		VIEW_ALLY_ADD : "",
		VIEW_METAL : "M",
		VIEW_CRYSTAL : "C",
		VIEW_COLONISED : "Planeta colonizado",
		VIEW_UKMOONSIZE : "desconocido",
		VIEW_BACK : "atrás",
		VIEW_NOTICE : "Notas",
		VIEW_REPORTS : "Espionaje",
		VIEW_MOONPHALANX : "Las siguientes lunas tienen este sistema en el Phalanx",
		VIEW_NOMOONS : "No se han encontrado Lunas",
		VIEW_IRAKS : "Los siguientes planetas tienen estos sistemas al alcance de sus misiles interplanetarios",
		VIEW_NOIRAKS : "No se han encontrado misiles",
		VIEW_MOON_DESTROY_CHANCE : "Probabilidad destrucción Luna",
		VIEW_CHANCE_WITH_ONE : "Probabilidad con una EDLM",
		VIEW_CHANCE_WITH_N : "Probabilidad con ",
		VIEW_DEATH_STARS : "EDLM",
		VIEW_DS_DESTROY_CHANCE : "Probabilidad pérdida de EDLM",
		VIEW_TOP : "Top",
		VIEW_GO : "go",
		VIEW_DIAMETER : "Diámetro",
		PW_TITLE : "OGame Galaxietool - Cambiar contraseña",
		OLD_PASSWORD : "Contraseña anterior",
		NEW_PASSWORD : "Nueva contraseña",
		CONFIRM_NEW_PASSWORD : "Repetir contraseña nueva",
		PW_MISMATCH : "¡Las contraseñas no coinciden!",
		PW_ERROR : "¡La contraseña anterior es incorrecta!",
		UPDATE_DONE : "Contraseña cambiada.",
		TIMEZONE_OFFSET : "Diferencia horaria con el servidor",
		DELETE_ACCOUNT : "Borrar esta cuenta Galaxytool",
		DELETE_ACCOUNT_SAFETY_REQUEST : "¿Estas seguro de querer borrar esta cuenta?",
		CH_PASSWD_AUTHORIZATION : "Permisos",
		CH_PASSWD_ADMIN : "Admin",
		TIMEZONE_OGAME_OFFSET : "Diferencia horaria al Servidor OGame",
		CH_PASSWD_USER_LANGUAGE : "Cambiar a este idioma tras el Login",
		CH_PASSWD_USER_LANGUAGE_NO_CHANGE : "Sin cambio",
		CH_PASSWD_EXPAND : "Visible",
		CH_PASSWD_COLLAPSE : "Colapsado",
		CH_PASSWD_HIDDEN : "No visible",
		CH_PASSWD_GETTING_STARTED : "Mostrar Información de entrada en la Página Inicial",
		CH_PASSWD_PLUGIN : "Mostrar Información de Plugin en la Página Inicial",
		NOTICE_TITLE : "OGame Galaxietool - Notas",
		NOTICE_HEADER : "Editar Notas",
		NOTICE_HEADER2 : "Editar notas propias",
		NOTICE_PUBLIC : "¿Visible para otros?",
		NOTICE_YES : "Sí",
		NOTICE_NO : "No",
		NOTICE_TEXT : "Nota Texto",
		NOTICE_SAVE : "Guardar",
		NOTICE_DELETED : "Entrada borrada",
		NOTICE_SAVED : "Entrada guardada.",
		NOTICE_RESULTS : "Todas las entradas",
		NOTICE_USER : "Usuario",
		NOTICE_DATE : "Fecha",
		NOTICE_EDIT : "Editar",
		NOTICE_DELETE : "Borrar",
		NOTICE_NEW : "Crear nota",
		NOTICE_NOTPUBLIC : "Nota no pública.",
		NOTICE_ALL : "todas",
		NOTICE_NONE : "ninguno",
		NOTICE_SEARCH : "Buscar nota",
		NOTICE_SEARCH_SHORT : "Buscar",
		NOTICE_HITS : "Resultados",
		NOTICE_SHOWRESULTS : "Coincidencias por página",
		NOTICE_OF : "de",
		NOTICE_NOTHING : "No se han encontrado entradas",
		NOTICE_CHARS : "Carácter",
		NOTICE_PLAYERNAME : "Jugador",
		NOTICE_SHOWALL : "Mostrar todas las notas.",
		REPORTS_TITLE : "OGame Galaxietool - Informes de Espionaje",
		REPORTS_RESOURCES : "Recursos",
		REPORTS_FLEET : "Flotas",
		REPORTS_DEFENCE : "Defensas",
		REPORTS_BUILDINGS : "Edificios",
		REPORTS_TECHNOLOGY : "Investigaciones",
		REPORTS_MOON : "Luna",
		REPORTS_SEARCH : "Buscar informe",
		REPORTS_SEARCH_SHORT : "Buscar",
		REPORTS_HITS : "Resultados",
		REPORTS_NOTHING : "No se han encontrado entradas",
		REPORTS_ADDRESS : "Coordenadas",
		REPORTS_CURRENTNESS : "Antigüedad",
		REPORTS_PLAYERNAME : "Nombre del jugador",
		REPORTS_ALLY : "Alianza",
		REPORTS_VIEW : "Ver Informe",
		REPORTS_SEARCH_IN : "Búsqueda en Galaxia",
		REPORTS_FROM_SYSTEM : "del sistema",
		REPORTS_TO : "hasta el",
		REPORTS_DELETE : "borrar",
		REPORTS_DELETED : "Entrada borrada",
		REPORTS_RESULTS : "Coincidencias por página",
		REPORTS_OF : "de",
		REPORTS_DATE : "Fecha",
		REPORTS_DATE_0 : "igual",
		REPORTS_DATE_1 : "más antiguo que",
		REPORTS_DATE_2 : "más nuevo que",
		REPORTS_NOTICES : "Notas",
		REPORTS_AT_LEAST_RESOURCES : "Recursos totales (min.)",
		REPORTS_SEARCH_EXTENDED : "Búsqueda avanzada",
		REPORTS_FLEET_RESIS : "Flotas- puntos",
		REPORTS_DEFENCE_RESIS : "Defensas- puntos",
		REPORTS_ALL_RESIS : "Pérdida puntos totales",
		REPORTS_TECHS : "Tecnologías",
		REPORTS_UNKNOWN_ENTRIES : "entradas desconocidas",
		REPORTS_PARTLY_INSERTED : "introducir parcialmente",
		REPORTS_FOR_ALL_RES : "para todos los recursos",
		REPORTS_FOR_TF : "Para los escombros",
		REPORTS_KT : "Nave pequeña de carga",
		REPORTS_GT : "Nave grande de carga",
		REPORTS_SS : "Nave de Batalla",
		REPORTS_REC : "Reciclador",
		REPORTS_RAIDABLE : "Sólo objetivos atacables",
		REPORTS_ALL_RESOURCES : "Recursos Totales",
		REPORTS_STUFF : "Otros",
		REPORTS_SPEEDSIM : "Simular con Speedsim",
		REPORTS_DRAGOSIM : "Simular con Dragosim",
		REPORTS_STATUS : "Estado",
		REPORTS_ERROR : "Ha ocurrido un error",
		REPORTS_OWN_REPORTS : "Sólo mis informes",
		REPORTS_UPLOAD_BY : "Informe introducido por",
		REPORTS_DEPTH : "Profundidad Informe",
		REPORTS_FLEET_SCORE : "Puntos Flota",
		REPORTS_DEFENCE_SCORE : "Puntos Defensa",
		REPORTS_HOURS : "Horas",
		REPORTS_MAX_RESULTS_HIT : "La búsqueda obtuvo más de &1 resultados. Sólo se muestran los primeros &1. Ajusta los parámetros de búsqueda para obtener menos resultados.",
		REPORTS_OSIMULATE : "Simular con OSimulate",
		REPORTS_SHOW_ONLY : "Mostrar sólo",
		REPORTS_SHOW_PLANETS : "Planetas",
		REPORTS_SHOW_MOONS : "Lunas",
		REPORTS_OWNER : "Informe de Espionaje de",
		STATS_TITLE : "OGame Galaxietool - Estadísticas",
		STATS_TBLHEAD : "Estadísticas",
		STATS_RANK : "Posición",
		STATS_PLAYERNAME : "Jugador",
		STATS_SCORE : "Puntos",
		STATS_FLEET : "Flota",
		STATS_RESEARCH : "Investigación",
		STATS_ALLYNAME : "Alianza",
		STATS_MEMBERS : "Miembros",
		STATS_STATUS : "Estado",
		STATS_NOTHING : "Sin Estado",
		STATS_NAP : "PNA",
		STATS_ALLIED : "Aliado",
		STATS_WAR : "Guerra",
		STATS_BOYCOTT : "Boikot",
		STATS_NEUTRAL : "Neutral",
		STATS_OWN : "Propia Alianza",
		STATS_WING : "Cantera",
		STATS_UPDATE : "datos del",
		STATS_PLAYERSTATS : "Estadística jugadores",
		STATS_ALLYSTATS : "Estadística alianza",
		STATS_DELETE : "borrar entrada",
		STATS_CONFIRM_DELETE : "¿Realmente desear borrar la entrada?",
		STATS_CHANGE_PLAYER_STATUS : "Status Jugador",
		STATS_CHANGE_ALLIANCE_STATUS : "Status Alianza",
		STATS_CHANGE_ALLIANCE_STATUS_HINT : "Todos los jugadores de la alianza reciben el estado elegido. Los estados existentes son reemplazados, aunque es posible darle a jugadores concretos después otro estados.",
		STATS_UNKNOWN : "Desconocido",
		STATS_DETAILS : "Detalles para",
		STATS_PLAYERSTATUS : "Estado jugador",
		STATS_IGNORE_STATUS : "todos",
		STATS_ACTIVE : "activo",
		STATS_INACTIVE : "Inactivo",
		STATS_BANNED : "Baneado",
		STATS_VACATION : "Modo vacaciones",
		STATS_NOOB : "Protección de novatos",
		STATS_YES : "Sí",
		STATS_NO : "Sólo buscar planetas con Notas",
		STATS_SEARCH : "Buscar",
		STATS_SHOW_GRAPH : "Detalles sobre el reparto de puntos",
		STATS_LONG_INACTIVE : "Inactivo",
		STATS_STANDARD : "Puntos estándar",
		STATS_MILITARY : "Puntos militares",
		STATS_ECONOMY : "Economía",
		STATS_HONOUR : "Puntos honor",
		STATS_MILITARY_BUILD : "Puntos militares construidos",
		STATS_MILITARY_DESTROYED : "Puntos militares destruidos",
		STATS_MILITARY_LOST : "Puntos militares perdidos",
		REGISTER_REGISTRATE : "Registrarse",
		REGISTER_LOGINNAME : "Nombre",
		REGISTER_PASSWORD : "Contraseña",
		REGISTER_PASSWORD_CONFIRM : "Repetir contraseña",
		REGISTER_EMAIL : "Email",
		REGISTER_INGAME : "Nombre en el Juego",
		REGISTER_ALLYTAG : "Etiqueta de Alianza",
		REGISTER_EMAILVERIFICATION : "Repetir Email",
		REGISTER_EMAILTEXT : "Haga clic en el siguiente enlace para completar el registro en Galaxietool.",
		REGISTER_ERROR1 : "El nombre ya está siendo utilizado por otra persona.",
		REGISTER_ERROR2 : "¡Error al intentar enviar el email! Contacte al administrador.",
		REGISTER_ERROR3 : "Error al consultar la base de datos!",
		REGISTER_INFO1 : "La cuenta ha sido creada.",
		REGISTER_INFO2 : "Haga clic en el enlace que viene junto al Email para completar el proceso de registro.",
		REGISTER_INFO3 : "Cuenta confirmada. Ahora el administrador debe de validar su cuenta.",
		REGISTER_BUTTON : "Hacia la página principal",
		REGISTER_NEW_SUBJECT : "Nuevo usuario en Galaxietool registrado",
		REGISTER_NEW_MAILTEXT : "Un nuevo usuario se ha registrado en el Galaxietool.",
		REGISTER_BACK : "Volver a primera página",
		REGISTER_MISSING_FIELDS : "Rellena todos los campos requeridos",
		REGISTER_ERROR4 : "Dirección email no válida.",
		REGISTER_ERROR5 : "Las contraseñas no coinciden.",
		REGISTER_PWS : "Seguridad contraseña",
		REGISTER_PWS0 : "muy débil",
		REGISTER_PWS1 : "débil",
		REGISTER_PWS2 : "buena",
		REGISTER_PWS3 : "fuerte",
		REGISTER_PWS4 : "muy fuerte",
		REGISTER_EMAIL_USED : "Dirección email ya en uso",
		LOSTPW_TITLE : "Contraseña olvidada",
		LOSTPW_INFO2 : "La nueva contraseña ha sido creada y enviada al email correspondiente.",
		LOSTPW_BUTTON1 : "Pedir contraseña",
		LOSTPW_BUTTON2 : "Hacia la página principal",
		LOSTPW_LOGINNAME : "Usuario",
		LOSTPW_EMAIL : "Email",
		LOSTPW_ERROR1 : "¡Error al consultar la base de datos!",
		LOSTPW_ERROR2 : "¡No se ha encontrado una entrada que corresponda!",
		LOSTPW_ERROR3 : "¡Error al intentar enviar el Email! Contacte con el administrador.",
		LOSTPW_EMAIL_SUBJECT : "Petición de Contraseña",
		LOSTPW_EMAIL_TEXT1 : "Datos de acceso para el Galaxietool",
		LOSTPW_EMAIL_TEXT2 : "Usuario",
		LOSTPW_EMAIL_TEXT3 : "Contraseña",
		LOSTPW_INFO1 : "Vas a recibir un Email de confirmación para restablecer la contraseña.",
		LOSTPW_CONFIRM_RESET_SUBJECT : "¿Contraseña olvidada?",
		LOSTPW_CONFIRM_RESET_MESSAGE : "Hola,\n\ntú has solicitado restablecer tu contraseña de Galaxytool. Para generar una nueva contraseña haz clic en el siguiente enlace:",
		USERINFO_TITLE : "OGame Galaxietool - Información de usuario",
		USERINFO_NAMES : "Todos los usuarios del tool",
		USERINFO_DETAIL : "Información detallada acerca de",
		USERINFO_ERROR1 : "¡Ningun usuario bajo esta ID!",
		USERINFO_USERNAME : "Usuario",
		USERINFO_INGAME : "Nombre Juego",
		USERINFO_EMAIL : "Email",
		USERINFO_ALLYTAG : "Alianza",
		USERINFO_STYLEPATH : "Skin",
		USERINFO_STATUS : "Estado",
		USERINFO_ACTIVATE : "Activar al jugador",
		USERINFO_LOGINS : "Cantidad Accesos",
		USERINFO_LASTLOGIN : "Último Acceso",
		USERINFO_DATA : "Información acerca de sistemas introducidos",
		USERINFO_NODATA : "¡El usuario nunca ha introducido datos!",
		USERINFO_GALAXY : "Galaxia",
		USERINFO_SYSTEMS : "Cantidad sistemas",
		USERINFO_IP : "IP",
		USERINFO_LOGINTIME : "Hora Acceso",
		USERINFO_NOLOGIN : "El usuario nunca se ha logado.",
		USERINFO_LAST_GALAXYUPDATE : "Última visión de galaxia introducida el",
		USERINFO_LAST_PUBLIC_NOTICE : "Última nota pública el",
		USERINFO_LAST_PRIVATE_NOTICE : "Última nota privada el",
		USERINFO_NUMBEROF_PUBLIC_NOTICE : "Cantidad de notas públicas",
		USERINFO_NUMBEROF_PRIVATE_NOTICE : "Cantidad notas privadas",
		USERINFO_ACTIVATED : "Cuenta activada",
		USERINFO_ACTIVATIONTEXT : "El administrador ha activado tu cuenta.\n\n¡Que disfrutes del Galaxietool!",
		USERINFO_LAST_SUBMIT : "Última transmisión de datos",
		ALLYHISTORY_TITLE : "OGame Galaxietool - Historia de la Alianza",
		ALLYHISTORY_TBLHEAD : "Visión General",
		ALLYHISTORY_PLAYERNAME : "Nombre",
		ALLYHISTORY_ALLYNAME : "Alianza",
		ALLYHISTORY_LASTMONTH : "Mes actual",
		ALLYHISTORY_ALL_DATA : "todos los datos disponibles",
		ALLYHISTORY_SHOW : "mostrar estadística",
		ALLYHISTORY_TIMESPAN : "espacio de tiempo",
		ALLYHISTORY_PROGESS : "Avance",
		ALLYHISTORY_SCORE : "Puntos",
		ALLYHISTORY_FSCORE : "Puntos Flotas",
		ALLYHISTORY_RSCORE : "Puntos investigación",
		ALLYHISTORY_MEMBER : "Miembros",
		ALLYHISTORY_NOTHING : "No se han encontrado entradas",
		ALLYHISTORY_DETAILS : "Detalles",
		ALLYHISTORY_SHOW_ADDRESS : "Coordenadas",
		ALLYHISTORY_ESCORE : "Economía",
		ALLYHISTORY_MSCORE : "Puntos militares",
		DETAILEDINFO_PLAYERINFO_TITLE : "Información Jugador",
		DETAILEDINFO_ALLYINFO_TITLE : "Información Alianza",
		DETAILEDINFO_PLAYERINFO_TBLHEAD : "Información detallada del Jugador",
		DETAILEDINFO_ALLYINFO_TBLHEAD : "Información detallada de la Alianza",
		DETAILEDINFO_NO_ALLIANCE : "ninguna",
		DETAILEDINFO_SCORE : "Estadísticas Puntos",
		DETAILEDINFO_FLEET : "Estadísticas Flota",
		DETAILEDINFO_RESEARCH : "Estadísticas investigaciones",
		DETAILEDINFO_RANK : "Posición",
		DETAILEDINFO_POINTS : "Puntos",
		DETAILEDINFO_KNOWN_PLANETS : "Planetas conocidos",
		DETAILEDINFO_MOONS : "Lunas conocidas",
		DETAILEDINFO_PHALANX_AREA : "Área del Phalanx",
		DETAILEDINFO_NO_PHALANX_AREA : "No se han encontrado Phalanx",
		DETAILEDINFO_NOTICES : "Notas",
		DETAILEDINFO_NO_NOTICES : "No hay notas",
		DETAILEDINFO_PREVIOUS_ALLIANCES : "Alianzas Previas",
		DETAILEDINFO_RESOURCES_PER_HOUR : "Recursos por hora",
		DETAILEDINFO_RESOURCES_PER_DAY : "Recursos por día",
		DETAILEDINFO_RESOURCES_PER_WEEK : "Recursos por semana",
		DETAILEDINFO_RESOURCES_PER_MONTH : "Recursos por mes (30 días)",
		DETAILEDINFO_METAL : "Metal",
		DETAILEDINFO_CRYSTAL : "Cristal",
		DETAILEDINFO_DEUTERIUM : "Deuterio",
		DETAILEDINFO_UNKNOWN : "desconocido",
		DETAILEDINFO_SCORE_DISTRIBUTION : "Distribución Puntos",
		DETAILEDINFO_GENERAL : "Detalles",
		DETAILEDINFO_MEMBERS : "Miembros",
		DETAILEDINFO_GRAPHS : "Gráficos",
		DETAILEDINFO_RESOURCES : "Recursos",
		DETAILEDINFO_FLEET_TAB : "Flota",
		DETAILEDINFO_TECH : "Investigación",
		DETAILEDINFO_FLEET_DETAIL : "Suma / (Media por jugador) entre todos los informes disponibles",
		DETAILEDINFO_TECH_DETAIL : "Media de toda la información de jugadores disponible",
		DETAILEDINFO_PLANET_TAB : "Planetas",
		DETAILEDINFO_MOON_TAB : "Lunas",
		DETAILEDINFO_ACTIVITIES : "Actividades",
		DETAILEDINFO_NODATA : "No hay datos disponibles.",
		DETAILEDINFO_ACTIVITY_DESCRIPTION : "Mostrar actividades de &1 en el espacio de tiempo:",
		DETAILEDINFO_GALAXYVIEWS : "Visiones de Galaxia",
		DETAILEDINFO_SCANS : "Acciones de espionaje",
		DETAILEDINFO_MESSAGES : "Mensajes de jugadores",
		DETAILEDINFO_COMBATS : "Informes de Batalla",
		DETAILEDINFO_ALLYPAGE : "Visión Alianza",
		DETAILEDINFO_MANUAL : "Entradas manuales",
		DETAILEDINFO_START : "Comienzo",
		DETAILEDINFO_TO : "hasta",
		DETAILEDINFO_TODAY : "Hoy",
		DETAILEDINFO_DATA_RESTRICTION : "restringido a:",
		DETAILEDINFO_WEEKDAY_WEEKEND : "Fin de semana",
		DETAILEDINFO_WEEKDAY_WORKINGDAY : "Día semanal",
		DETAILEDINFO_WEEKDAY_MONDAY : "Lunes",
		DETAILEDINFO_WEEKDAY_TUESDAY : "Martes",
		DETAILEDINFO_WEEKDAY_WEDNESDAY : "Miércoles",
		DETAILEDINFO_WEEKDAY_THURSDAY : "Jueves",
		DETAILEDINFO_WEEKDAY_FRIDAY : "Viernes",
		DETAILEDINFO_WEEKDAY_SATURDAY : "Sábado",
		DETAILEDINFO_WEEKDAY_SUNDAY : "Domingo",
		DETAILEDINFO_WEEKDAY_SHORTLENGTH : 2,
		DETAILEDINFO_PLAYER_CURRENTLY_ACTIVE : "El jugador está activo ahora mismo",
		DETAILEDINFO_PLAYER_MESSAGES : "Mensajes de jugadores disponibles",
		DETAILEDINFO_SHOW : "Mostrar",
		DETAILEDINFO_NONE : "no existen disponibles",
		DETAILEDINFO_ENTER_MANUALLY : "Recoger más tiempos online de este Jugador",
		DETAILEDINFO_PLAYER_SEEN_ON : "Jugador estuvo Online el",
		DETAILEDINFO_INSERT : "Insertar",
		DETAILEDINFO_OGAME_SERVERTIMES : "Nota: ¡Todos los tiempos recogidos aquí se refieren al horario servidor !",
		DETAILEDINFO_DAY_VIEW : "Visión 24 horas",
		DETAILEDINFO_WEEK_VIEW : "Visión semanal",
		DETAILEDINFO_HOME_PLANET : "Planeta Principal",
		DETAILEDINFO_PLANETNAME : "Nombre",
		DETAILEDINFO_DEFENCE_SCORE : "Puntos de defensa",
		DETAILEDINFO_DEFENCE_SCORE_TOOLTIP : "Los puntos de defensa se componen de Puntos de flota - Puntos totales+ Economía + Investigación<br/>¡Todas esas estadísticas deben ser actuales para obtener una búsqueda fiable!",
		DETAILEDINFO_SCORE_PER_SHIP : "Puntos por nave",
		DETAILEDINFO_SHIPS : "Cantidad naves",
		DETAILEDINFO_DATE_IN_FUTURE : "No recoger datos en el futuro",
		ADMIN_TITLE : "Administración del Galaxytool",
		ADMIN_DISCLAMER : "Atención: ¡La ejecucion de cualquiera de estos scrpts es bajo vuestro propio riesgo! Muchos de ellos borran datos.",
		ADMIN_INCONSISTENCIES : "Inconsistencias en la Base de datos",
		ADMIN_PLANETS : "Planetas en posición 0 o mayor que 15",
		ADMIN_GALAXIES : "Borrado de galaxias mayor que &1 ",
		ADMIN_PLAYERS : "Borrado jugadores sin OGame playerid - Permitir entradas duplicadas de jugador",
		ADMIN_REPORTS : "Borrado de informes de planetas que ya no existen",
		ADMIN_MISC : "Varios",
		ADMIN_RESET : "Reiniciar Galaxytool (solo las tablas usertable e iptable no serán borradas)",
		ADMIN_OLD_PLAYERS : "Borrado de entradas de jugadores con más de &1 días",
		ADMIN_OLD_REPORTS : "Borrado de informes con más de &1 días",
		ADMIN_LOADING : "No cerrar esta ventana mientras se carga la página.",
		ADMIN_STATUS : "Estado de sus peticiones",
		ADMIN_SELECTION : "debe seleccionar una entrada al menos",
		ADMIN_SAFETY : "¿Está seguro de querer ejecutar este(os) script(s)?",
		ADMIN_DONE : "Hecho",
		ADMIN_NOTBD : "Nada que hacer",
		ADMIN_OLD_GALAXIES : "Borrar visión de galaxia más antiguas que &1 días",
		ADMIN_UNUSED_PLAYERS : "Borrar jugadores que no aparezcan en ninguna visión de galaxia",
		ADMIN_OLD_ACTIVITIES : "Eliminar actividades de jugador más antiguas que &1 días",
		ADMIN_OLD_COMBATS : "Eliminar informes de batalla que sean más antiguos que &1 días",
		ADMIN_OLD_INGAME_MSG : "Eliminar mensajes de jugadores que sean más antiguos que &1 días",
		ADMIN_OGAME_API : "Cargando datos disponibles de OGame en el Galaxytool",
		ADMIN_OGAME_ALL_DATA : "todos los datos disponibles",
		ADMIN_OGAME_GALAXY_DATA : "Galaxia",
		ADMIN_OGAME_STATISTICS_DATA : "Estadísticas",
		ERRORPAGE_PAGEFORWARD : "Haz clic aquí si tu navegador no soporta la redirección de páginas",
		ERRORPAGE_PERMISSION_DENIED : "No tienes permiso para entrar a esta página. Haz clic para volver.",
		FLEETS_TITLE : "Movimientos de flotas",
		FLEETS_ACTUAL_FLEETS : "Movimientos de flotas actuales",
		FLEETS_YES : "Sí",
		FLEETS_NO : "Sólo buscar planetas con Notas",
		FLEETS_DETAILS : "Detalles Flota",
		FLEETS_MISSION_EXPEDITION : "Expedición",
		FLEETS_MISSION_COLONIZATION : "Colonización",
		FLEETS_MISSION_RECYCLE : "Reciclar",
		FLEETS_MISSION_TRANSPORT : "Transporte",
		FLEETS_MISSION_DEPLOYMENT : "Estacionar",
		FLEETS_MISSION_ESPIONAGE : "Espionaje",
		FLEETS_MISSION_ACS_DEFEND : "Defensa SAC",
		FLEETS_MISSION_ATTACK : "Ataque",
		FLEETS_MISSION_ACS_ATTACK : "Ataque SAC",
		FLEETS_MISSION_MOON_DESTRUCTION : "Destrucción Luna",
		FLEETS_MISSION_MISSILE_ATTACK : "Ataque Misiles",
		FLEETS_NO_DATA : "Sin información",
		FLEETS_FLEET : "Flota",
		FLEETS_ALL_FLEETS : "mostrar todos los movimientos de flota",
		COMBAT_REPORT_OUDATED_GALAXYVIEW : "Las visiones de galaxia están anticuadas. Por favor visitar primero las visiones de galaxia de los atacantes y defensores.",
		MESSAGES_TITLE : "OGame Galaxytool - OGame Mensajes",
		MESSAGES_PLAYERNAME : "Nombre Jugador",
		MESSAGES_SUBJECT : "Asunto",
		MESSAGES_DATE : "Fecha",
		MESSAGES_FILTER : "Filtro",
		MESSAGES_DELETE : "Borrar mensaje",
		MESSAGES_PUBLISH_DETAIL : "Publicar el mensaje, añadiendo el contenido del mensaje a las notas del jugador.",
		MESSAGES_PUBLISH_HEADER : "&sender ha enviado a &recipient el &date el siguiente mensaje:\n\n &message",
		MESSAGES_PLAYER_FILTER : "Mensajes de Jugador:",
		MESSAGES_CONTENT : "Contenido",
		COMBATS_TITLE : "OGame Galaxytool - Informes Batalla",
		COMBATS_ATTACKER : "Atacante",
		COMBATS_DEFENDER : "Defensor",
		COMBATS_DATE : "Fecha",
		COMBATS_OWNER : "Dueño",
		COMBATS_WINNER : "Ganador",
		COMBATS_COMBATREPORT : "Informe Batalla",
		COMBATS_COMBAT_AT : "Batalla el",
		COMBATS_LOST_UNITS : "Unidades perdidas",
		COMBATS_LOOT : "Recompensa",
		COMBATS_DEBRIS : "Campo escombros",
		COMBATS_AND : "y",
		COMBATS_PUBLISH : "Publicar Informe Batalla",
		COMBATS_UNPUBLISH : "Retirar publicación Informe de Batalla (volver a poner como privado)",
		COMBATS_DELETE : "Borrar Informe de Batalla",
		COMBATS_CHECK_ALL : "Marcar todos",
		COMBATS_UNCHECK_ALL : "Desmarcar todos",
		COMBATS_WITH_SELECTED : "Con selección",
		COMBATS_PUBLIC_REPORTS : "Informes Públicos",
		COMBATS_YES : "Sí",
		COMBATS_NO : "Sólo buscar planetas con Notas",
		COMBATS_SEARCH_OPTIONS : "Parámetros de búsqueda",
		COMBATS_SEARCH : "Buscar",
		COMBATS_RESET : "Restablecer",
		COMBATS_COORDINATES : "Coordenadas",
		COMBATS_INVALID_GALAXY_ENTERED : "Introducida galaxia no válida",
		COMBATS_INVALID_SYSTEM_ENTERED : "Introducido sistema no válido",
		COMBATS_INVALID_PLANET_ENTERED : "Introducidos planetas no válidos",
		COMBATS_GALAXY_FROM_TO : "Galaxia",
		COMBATS_SYSTEM_FROM_TO : "Sistema",
		COMBATS_PLANET_FROM_TO : "Planeta",
		COMBATS_APPLY : "Aplicar",
		COMBATS_COMBAT_SUMMARY : "Resumen Informes de Batalla",
		COMBATS_DOWNLOAD_CSV : "Descargar como fichero CSV",
		REPORT_ARCHIVE_TITLE : "Archivo Informes Scan",
		REPORT_ARCHIVE_COORDINATES : "Coordenadas",
		REPORT_ARCHIVE_SCANTIME : "Hora de Scan",
		REPORT_ARCHIVE_DELETE : "Eliminar Registros",
		REPORT_ARCHIVE_CONFIRM_DELETE : "¿Realmente eliminar registros?",
		REPORT_ARCHIVE_GALAXY : "Galaxia",
		REPORT_ARCHIVE_SYSTEM : "Sistema",
		REPORT_ARCHIVE_PLANET : "Planeta",
		REPORT_ARCHIVE_MOON : "Luna",
		REPORT_ARCHIVE_DETAILS : "Detalles",
		REPORT_ARCHIVE_RESOURCES : "Recursos por hora",
		REPORT_ARCHIVE_HEADER_RESOURCES : "Recursos",
		REPORT_ARCHIVE_DETAILS_FOR : "Archivo Informes Scan para &1 [&2] (&3)",
		REPORT_ARCHIVE_FLEET_CARGO : "Capacidad de carga de la Flota",
		REPORT_ARCHIVE_IRAK_RANGE : "Alcance misiles interplanetarios",
		REPORT_ARCHIVE_CHART_TYPE : "Tipo Diagrama",
		INSTALL_TITLE : "Instalación de la Version de Galaxytool",
		INSTALL_PROGRESS : "Progreso de Instalación",
		INSTALL_STEP : "Paso",
		INSTALL_CONTINUE : "Continuar",
		INSTALL_VALIDATE : "Comprobar",
		INSTALL_STEP1 : "Bienvenido",
		INSTALL_STEP2 : "Comprobación escritura",
		INSTALL_STEP3 : "Configuración Base de datos",
		INSTALL_STEP4 : "Opciones OGame",
		INSTALL_STEP5 : "Opciones Galaxytool",
		INSTALL_STEP6 : "Contraseña Admin",
		INSTALL_STEP7 : "Instalación del Galaxytool",
		INSTALL_STEP8 : "Fin de la Instalación",
		INSTALL_FILE_DELETE_CHECK : "Por favor elimina el install.php y update.php del servidor.",
		INSTALL_STEP1_PHP_FAILED : "Tu version PHP &1 no es compatible con esta version de Galaxytool",
		INSTALL_STEP1_FOPEN_FAILED : "Tu version de PHP no admite abrir páginas webs con el comando FOPEN(). Esta funcionalidad es requerida para usar el API de OGame.",
		INSTALL_STEP1_WELCOME : "Bienvenido a la instalación del Galaxytool. Serás guíado paso a paso durante la instalación y en cada paso tendrás enlaces con información adicional.",
		INSTALL_STEP2_DESCRIPTION : "Por favor, asegúrate que los archivos config.php y attributes.php no estén protegidos contra escritura en el servidor.",
		INSTALL_STEP2_DESCRIPTION2 : "Si no sabes como modificar la protección de escritura de estos archivos o carpetas haz clic aquí: &1",
		INSTALL_STEP2_FILE_NOT_WRITEABLE : "El archivo no es editable",
		INSTALL_STEP3_SERVER : "Servidor base de datos",
		INSTALL_STEP3_USERNAME : "Usuario",
		INSTALL_STEP3_PASSWORD : "Contraseña",
		INSTALL_STEP3_DBNAME : "Nombre Base de datos",
		INSTALL_STEP3_PREFIX : "Prefijo para nombre de las tablas",
		INSTALL_STEP3_ENTER_PREFIX : "ejemplo. MiTool_",
		INSTALL_STEP3_ENTER_SERVER : "Dirección del servidor, si tienes dudas pregunta al administrador del servidor. Normalmente el valor por defecto será localhost.",
		INSTALL_STEP3_ENTER_USERNAME : "Usuario para el acceso a la base de datos",
		INSTALL_STEP3_ENTER_PASSWORD : "Contraseña para acceder a la base de datos",
		INSTALL_STEP3_ENTER_DBNAME : "Nombre de la base de datos en la que debe instalarse Galaxytool. (La base de datos debe existir)",
		INSTALL_STEP3_CONNECT_FAILED : "No ha sido posible establecer una conexión con el servidor de la base de datos.",
		INSTALL_STEP3_DB_FAILED : "Base de datos &1 no encontrada",
		INSTALL_STEP3_MYSQL_VERSION_FAILED : "La version de MySQL &1 no es compatible con esta version de Galaxytool",
		INSTALL_STEP4_URL : "URL OGame",
		OGAME_URL_DETAILS : "Introduce aquí la dirección de tu servidor de OGame. Puedes usar la dirección de cualquier página de OGame, una vez que estés logueado. El Galaxytool obtendrá a partir de esa dirección la dirección API de OGame. El API fue introducido con la version 4.1 de OGame.",
		INSTALL_STEP4_UNIVERSE : "Universo de OGame",
		INSTALL_STEP4_DEF_TO_DEBRIS : "Defensa a los escombros",
		INSTALL_STEP4_DEBRIS_RATE : "Tasa defensa a escombros",
		INSTALL_STEP4_SPEED_RATE : "Velocidad",
		INSTALL_STEP4_ENTER_UNIVERSE : "Introduce aquí el nombre del Universo. En Universos antiguos es un número. (Atención a mayúsculas y minúsculas)",
		INSTALL_STEP4_UNIVERSE_MISSING : "Falta el Universo",
		INSTALL_STEP4_ENTER_URL : "Introduce la URL de tu servidor de OGame",
		INSTALL_STEP4_URL_MISSING : "Falta la URL de OGame",
		INSTALL_STEP4_URL_CHECK_FAILED : "No se ha podido encontrar el API de OGame en &1",
		INSTALL_STEP4_GETSETTINGS : "Fetch settings",
		INSTALL_STEP5_TOOLNAME : "Nombre Galaxytool",
		INSTALL_STEP5_ENTER_TOOLNAME : "Este nombre será visible en la página inicial de tu Galaxytool.",
		INSTALL_STEP5_LANGUAGE : "Idioma estándar",
		INSTALL_STEP5_EMAIL_TO : "Destinatario Email",
		INSTALL_STEP5_ENTER_EMAIL_TO : "A esta dirección de email se enviarán los emails de los nuevos usuarios que se registren.",
		INSTALL_STEP5_EMAIL_FROM : "Remitente Email",
		INSTALL_STEP5_ENTER_EMAIL_FROM : "Esta dirección de Email será el Remitente de los emails enviados por parte del Galaxytool",
		INSTALL_STEP5_USE_PHPMAILER : "Usar PHPMailer",
		INSTALL_STEP5_MAXSHOUTS : "Cantidad máxima de entradas en la Bandeja",
		INSTALL_STEP5_ENTER_USE_PHPMAILER : "Usa el PHPMailer si tu servidor no soporta enviar emails via PHP.",
		INSTALL_PHPMAILER_HOST : "Host SMPT",
		INSTALL_PHPMAILER_HOST_EXAMPLE : "ejemplo: smtp.proveedor.es",
		INSTALL_PHPMAILER_USER : "Usuario SMPT",
		INSTALL_PHPMAILER_USER_EXAMPLE : "ejemplo. usuario@proveedor.es",
		INSTALL_PHPMAILER_PASS : "Contraseña SMPT",
		INSTALL_PHPMAILER_SECURE : "Método identificación, ejemplo. ssl",
		INSTALL_PHPMAILER_PORT : "Puerto SMTP",
		INSTALL_STEP6_INTRO : "Por favor establece la contraseña de la cuenta <strong>admin</strong> para loguearte después de la instalación en Galaxytool.",
		INSTALL_STEP7_CONFIG : "Archivo de configuración generado",
		INSTALL_STEP7_CONFIG_FAILED : "El archivo de configuración no fue creado",
		INSTALL_STEP7_ATTRIBUTES : "Archivo de atributos generado",
		INSTALL_STEP7_ATTRIBUTES_FAILED : "Archivo de atributos no creado",
		INSTALL_STEP7_CREATED_TABLES : "Creadas las tablas de la base de datos",
		INSTALL_STEP8_INTRO : "¡Has finalizado la instalación del Galaxytool con éxito!",
		INSTALL_STEP8_LOAD_DATA : "Importando los datos de OGame a través de OGame API ...",
		INSTALL_STEP8_LOAD_DATA_FINISHED : "Finalizado la importación de los datos de OGame",
		INSTALL_STEP8_DELETE_FILE : "Ahora debes eliminar los archivos install.php y update.php del servidor.",
		INSTALL_STEP8_LOGON : "Ahora identifícate con el usuario <strong>admin</strong> y la contraseña que has creado antes.",
		UPDATE_START : "Iniciando Update a la version &1",
		UPDATE_STEP_DONE : "Finalizado",
		UPDATE_TITLE : "Update de Galaxytool para version",
		UPDATE_STEP1_WELCOME : "Bienvenido al asistente de actualización de Galaxytool. Serás guíado paso a paso durante la actualización.",
		UPDATE_STEP1_BACKUP_FILES : "En primer lugar crea una copia de seguridad de la carpeta <strong>config</strong>. En caso de error, debes restaurar esa copia de seguridad.",
		UPDATE_STEP1_BACKUP_DB : "Después crea una <a href=\"http://www.ehow.com/how_2036600_create-database-php.html\">Copia de Seguridad</a>  de la Base de datos.",
		UPDATE_STEP1_PROCEED : "Una vez creadas las copias de seguridad ya puedes comenzar el Update.",
		UPDATE_STEP1 : "Bienvenido",
		UPDATE_STEP2 : "Opciones Galaxytool",
		UPDATE_STEP2_OLD_VERSION : "Version de Galaxytool anterior",
		UPDATE_STEP3 : "Update del Galaxytool",
		UPDATE_STEP3_UPDATE_RUNNING : "Ejecutando Update. Por favor espera...",
		UPDATE_STEP4 : "Finalizar Update",
		UPDATE_STEP4_INTRO : "¡Has finalizado el Update con éxito!",
		UPDATE_STEP4_UPDATE_DONE : "Finalizados todos los pasos del Update.",
		UPDATE_FAILED : "Update fallado.",
		GALAXYTOOL_DUMMY_TEXT : "dummy"
	})
);