define(
	({
		REPORT_WHEN : "op",
		RESOURCES_ON : "Grondstoffen op",
		PLAYER_BANNED : "g",
		PLAYER_VACATION_MODE : "v",
		PLAYER_NOOB : "z",
		PLAYER_INACTIVE : "i",
		PLAYER_LONG_INACTIVE : "I",
		PLAYER_OUTLAW : "o",
		L_USERNAME : "Gebruikersnaam",
		L_PASSWORD : "Wachtwoord",
		L_LOGINFAILURE : "Incorrecte gebruikersnaam of wachtwoord!",
		L_TOKENFAILURE : "Je verificatie sleutel is fout of je account is nog niet geactiveerd.",
		L_LOGINTEXT : "Login aub.",
		L_LANGUAGE : "Beschikbare talen:",
		L_TIMEOUT : "Sessie afgelopen!",
		L_REGISTER : "Registreer",
		L_PWLOST : "Wachtwoord vergeten",
		INDEX_TITLE : "OGame Galaxytool - Database overzicht",
		INDEX_INFO : "Database overzicht",
		INDEX_ENTRIES : "Aantal zonnestelsels",
		INDEX_ENTRIES_LASTWEEK : "Nieuwe zonnestelsels deze week",
		INDEX_ENTRIES_TO_OLD : "Zonnestelsels ouder dan een maand",
		INDEX_REGISTERED_USERS : "Geregistreerde gebruikers",
		INDEX_PAGEFORWARD : "Als je browser je niet automatisch doorstuurt, klik dan hier.",
		INDEX_NOTICES : "Notities",
		INDEX_PLAYERS : "Speler statistieken",
		INDEX_ALLIES : "Alliantie statistieken",
		INDEX_REPORTS : "Spionage rapporten",
		INDEX_VERSION : "Download de nieuwste versie",
		INDEX_LATEST_VERSION : "Geen nieuwere versie beschikbaar",
		INDEX_SHOUTBOX : "Shoutbox",
		INDEX_NOENTRY : "Nog geen berichten",
		INDEX_COMMENT : "Jouw bericht",
		INDEX_INSERT : "Verzend",
		INDEX_UMOD : "Spelers in Vakantiemodus",
		INDEX_NO_MOONS : "Aantal manen",
		INDEX_NO_EMPTY_SYSTEMS : "Aantal lege zonnestelsels",
		INDEX_NO_FULL_SYSTEMS : "Aantal totaal gevulde zonnestelsels",
		INDEX_NO_TARGETS : "Aantal potentieele doelen",
		INDEX_USERINFO : "Gebruikers statistieken",
		INDEX_ONLINE : "Nu online",
		INDEX_TODAY : "Vandaag online",
		INDEX_ALL : "Totaal aantal logins",
		GENERAL_LOAD_FORM : "Laad data formulier",
		GENERAL_SAVE_FORM : "Opslaan data formulier",
		GENERAL_SAVE_AS_TEXT : "Opslaan als",
		GENERAL_SAVE : "Opslaan",
		INDEX_USERMANAGEMENT : "Activatie Overzicht",
		INDEX_NEEDADMIN : "Accounts om te activeren",
		INDEX_NEEDEMAIL : "Ongevalideerde Accounts",
		INDEX_TOOLBAR_INFO : "Galaxytool plugin informatie",
		INDEX_TOOLBAR_URL : "Galaxytool URL",
		INDEX_TOOLBAR_VERSION_REQUIRED : "Heeft tenminste deze versie van Galaxytool nodig",
		INDEX_TOOLBAR_INSTALL_GUIDE : "Installatie instructies voor de plugin",
		INDEX_TOOLBAR_TOKEN : "Verificatie sleutel",
		INDEX_TOOLBAR_NEW_TOKEN : "Ontvang een nieuwe sleutel",
		INDEX_PLAYERS_WITH_N_PLANETS : "Spelers met meer dan &1 planeten",
		INDEX_GETTING_STARTED : "Begin met Galaxytool",
		INDEX_GETTING_STARTED1 : "Welkom op Galaxytool!",
		INDEX_GETTING_STARTED2 : "Galaxytool helpt je met het analyseren van jou OGame universum &1",
		INDEX_GETTING_STARTED3 : "Voordat je data kan analyzeren moet je het eerst toevoegen in de galaxytool. Voor dit is er een brouwser plugin &1 voor Firefox.",
		INDEX_GETTING_STARTED4 : "Nadat je de plugin geinstaleerd hebt, navigeer je door de melkwegen zoals normaal en je zult status informatie zien waneer er iets verzonden is naar jouw Galaxytool.",
		INDEX_GETTING_STARTED5 : "nadat de plugin data verzonden heeft naar Galaxytool, kan je zien waar mensen kolonies hebben, hoeveel koloniën ze hebben, welke spionage rapporten bestaan or of wanneer mensen actief zijn.",
		INDEX_GETTING_STARTED6 : "Maar het helpt je ook om je progressie te zien ten opzichte van andere spelers, of met het analyzeren van gevechtsraporten om te zien hoeveel je de intotaal geraid hebt.",
		INDEX_GETTING_WIKIPAGE : "Er zijn veel meer functies in onze Galaxytool.",
		INDEX_GETTING_WIKIPAGE2 : "Check ze uit op onze wiki pagina.",
		INDEX_GETTING_BOARD : "Voor feedback of ideeën kan je ons forum gebruiken:",
		INDEX_GETTING_CHAT1 : "Of bezoek onze chatroom:",
		INDEX_GETTING_CHAT2 : "We zijn niet 24/7 online maar we zijn er vaak in onze vrije tijd, dus wees geduldig.",
		INDEX_CLOSE : "Sluiten",
		INDEX_LOGIN : "Inloggen",
		GENERAL_REQUIRED_FIELDS : "Vul aub alle benodigde velden in",
		INDEX_MESSAGES : "Berichten",
		INDEX_EXAMPLE : "Voorbeeld",
		INDEX_INVALID_DATA : "Ongeldige gegevens",
		GENERAL_COLUMN_HIDE_TITLE : "Beheer kolommen",
		GENERAL_COLUMN_HIDE_INFO : "Selecteer de kolommen die getoond moeten worden in de tabel.",
		GENERAL_ENTRIES_DELETED : "&1 items verwijderd.",
		GENERAL_APPLY : "Toepassen",
		STARTPAGE_GALAXYTOOL_DESCR : "<em>Galaxytool</em> is een tool voor het online spel OGame.",
		GENERAL_OVERWRITE : "Overschrijf dubbele invoer.",
		GENERAL_OVERWRITE_QUESTION : "Overschrijven?",
		INDEX_OWN_LOGINS : "Uw logins",
		GENERAL_OPEN_IN_NEW_WINDOW : "Koppeling openen in nieuw venster",
		GENERAL_UNIT_OF_MEASURE_DAYS : "Days",
		PROGRAM_NAME : "OGame Galaxytool",
		SHORTNAME : "Galaxytool",
		BACK_INDEX : "Terug naar hoofdpagina",
		UNIVERSE : "Universum",
		MENU_INFO_LINKS : "Informatie",
		MENU_PAGE : "Overzicht",
		MENU_DB_SEARCH : "Zoek in database",
		MENU_DB_NOTICES : "Zoek in notities",
		MENU_DB_REPORTS : "Zoek in spionagerapporten",
		MENU_GALAXYVIEW : "Melkweg overzicht",
		MENU_STATISTICS : "Statistieken",
		MENU_ALLYHISTORY : "Alliantie historie",
		MENU_FLEET_MOVEMENTS : "Vlootbewegingen",
		MENU_COMBAT_REPORTS : "Gevechtsrapporten",
		MENU_MESSAGES : "Ingame berichten",
		MENU_OPTION_LINKS : "Opties",
		MENU_DB_REFRESH : "Gegevens toevoegen",
		MENU_NOTICES : "Notities",
		MENU_DB_STATUS : "Universum overzicht",
		MENU_USEROPTIONS : "Gebruikersbeheer",
		MENU_USEROPTIONS2 : "Gebruikersopties",
		MENU_USEROPTIONS3 : "Gebruikersinformatie",
		MENU_ADMIN : "Administratie",
		MENU_LOGOUT : "Uitloggen",
		MENU_STUFF : "Overige",
		MENU_FORUM_THREAD : "Ontwerpers forum",
		MENU_DOWNLOADPAGE : "Download pagina",
		MENU_LANGUAGE : "Taal",
		MENU_HELP : "Help",
		MENU_TOOLOPTIONS : "Galaxytool Opties",
		PARSER_INFO1 : " is toegevoegd aan de database",
		PARSER_ERROR1 : "Probleem tijdens het toevoegen van de volgende co&ouml;rdinaten:",
		PARSER_ERROR2 : "De database kan niet worden gevonden!",
		PARSER_ERROR3 : "De database server kan niet worden gevonden!",
		PARSER_WRONG_UNIVERSE : "Verkeerd universum - kreeg \"&1\"  maar verwachtte \"&2\"",
		SHOW_TITLE : "OGame Galaxytool - Zoekpagina",
		SHOW_SEARCH : "Zoeken in Database",
		SHOW_ALLYSYMBOL : "Alliantie label",
		SHOW_PLAYERNAME : "Speler",
		SHOW_MOONS : "Alleen planeten met maan",
		SHOW_NOTICES : "Alleen planeten met een notitie",
		SHOW_COLONIES : "Alleen koloniseerbare planeten",
		SHOW_YES : "Ja",
		SHOW_NO : "Nee",
		SHOW_SEARCHRANGE : "Bereik",
		SHOW_SEARCH_IN : "Zoek in melkweg",
		SHOW_FROM_SYSTEM : "van zonnestelsel",
		SHOW_FROM_PLANET : "Van planeetpositie",
		SHOW_TO : "tot",
		SHOW_DESCRIPTION : "Je kan wildcards (*) gebruiken voor spelers en alliantie namen, bijvoorbeeld: &quot;naam*&quot; dan vind je alle spelers met &quot;naam&quot; in hun naam.<br />Alleen de velden invullen die je wilt specificeren",
		SHOW_SORT_BY : "Sorteren op",
		SHOW_GALASYSTEM : "Melkweg/zonnestelsel",
		SHOW_ALLYNAME : "Alliantienaam",
		SHOW_SEARCHBUTTON : "Zoeken",
		SHOW_ADDRESS : "Coords",
		SHOW_ALLYSORT : "Alliantie",
		SHOW_PLANET : "Planeetnaam",
		SHOW_STATUS : "Status",
		SHOW_CURRENTNESS : "Huidigheid",
		SHOW_PLAYER_STATUS : "Spelerstatus",
		SHOW_PLAYER_STATUS1 : "iedereen",
		SHOW_PLAYER_STATUS2 : "mogelijke doelwitten",
		SHOW_PLAYER_STATUS3 : "inactief",
		SHOW_HITS : "Resultaten",
		SHOW_OF : "van",
		SHOW_ASC : "Oplopend",
		SHOW_DESC : "Aflopend",
		SHOW_RESULTS : "Aantal resultaten per pagina",
		SHOW_MOON : "Maan",
		SHOW_UKMOONSIZE : "onbekend",
		SHOW_DF : "PV",
		SHOW_DF_LONG : "Puin veld",
		SHOW_METAL : "M",
		SHOW_METAL_LONG : "Metaal",
		SHOW_CRYSTAL : "K",
		SHOW_CRYSTAL_LONG : "Kristal",
		SHOW_BOTH : "Metaal en kristal samen",
		SHOW_AT_LEAST : "(op z&#39;n minst)",
		SHOW_DATE : "Datum",
		SHOW_DATE_0 : "alles",
		SHOW_DATE_1 : "ouder dan",
		SHOW_DATE_2 : "nieuwer dan",
		SHOW_RANK : "Rank",
		SHOW_FRANK : "Vloot rank",
		SHOW_MEMBERS : "Leden",
		SHOW_NOTRANKED : "Niet in de top 1500.",
		SHOW_NOTICERES : "Notities",
		SHOW_REPORTS : "Alleen planeten met rapport",
		SHOW_REPORTS_SHORT : "Rapporten",
		SHOW_NOTHING : "Geen resultaten",
		SHOW_ALLIANCE_STATUS : "Alliantie status",
		SHOW_NO_STATUS : "Geen status",
		SHOW_NAP : "NAP",
		SHOW_ALLIED : "Bondgenoot",
		SHOW_WAR : "Oorlog",
		SHOW_BOYCOTT : "Boycot",
		SHOW_NEUTRAL : "Neutraal",
		SHOW_OWN : "Eigen Alliantie",
		SHOW_WING : "Wing",
		SHOW_EXT_OPTIONS1 : "Laat meer zoek opties voor bereik, rank, datum of puinvelden zien.",
		SHOW_EXT_OPTIONS2 : "Laat meer zoek opties voor kolonies, manen, rapporten, notities, spelerstatus of diplomatie status zien.",
		SHOW_EXT_OPTIONS3 : "Laat meer opties voor het sorteren van zoek resultaten zien.",
		SHOW_EXTENDED : "Uitgebreid zoeken",
		SHOW_MOON_SELECTION : "Planeet met een maan",
		SHOW_REPORT_SELECTION : "Planeet met een rapport",
		SHOW_FILTER_BY : "Uitsluiten van de lijst",
		SHOW_FILTER_NONE : "geen",
		SHOW_PLAYERS_WITHOUT_PROGRESS : "Show players without score changes within the last few days",
		STATUS_TITLE : "OGame Galaxytool - Status pagina",
		STATUS_DB_STATUS : "Status van database",
		STATUS_COLOR : "Kleur",
		STATUS_AGE1 : "Toevoeging 1 dag oud.",
		STATUS_AGE2 : "Toevoeging 2 - 4 dagen oud.",
		STATUS_AGE3 : "Toevoeging 4 - 7 dagen oud.",
		STATUS_AGE4 : "Toevoeging 1 - 2 weken oud.",
		STATUS_AGE5 : "Toevoeging 2 - 4 weken oud.",
		STATUS_AGE6 : "Toevoeging ouder dan 1 maand!",
		STATUS_AGE7 : "Geen gegevens beschikbaar.",
		STATUS_ON : "aan",
		STYLES_COLOR1 : "Kleur1",
		STYLES_COLOR2 : "Kleur2",
		STYLES_COLOR3 : "Kleur3",
		STYLES_COLOR4 : "Kleur4",
		STYLES_COLOR5 : "Kleur5",
		STYLES_COLOR6 : "Kleur6",
		STYLES_COLOR7 : "Kleur7",
		STATUS_DB_LEGEND : "Legenda",
		STATUS_GALAXY : "Melkweg overzicht",
		USER_TITLE : "OGame Galaxytool - Gebruikers beheer",
		USER_NAMES : "Gebruiker",
		USER_ERROR : "Fout",
		USER_NEWUSER : "Nieuwe gebruiker",
		USER_OPTIONS : "Opties",
		USER_USERNAME : "Gebruiker",
		USER_PASSWORD : "Wachtwoord",
		USER_PASSWORD_CONFIRM : "Bevestig wachtwoord",
		USER_GALAXY : "Melkweg",
		USER_SEARCH : "Zoek",
		USER_INSERT : "Toevoegen",
		USER_DELETE : "Verwijderen",
		USER_DELETE_ENTRY : "Verwijder deze gebruiker: ",
		USER_STATUS : "Bekijk status",
		USER_STYLES : "Wijzig layout",
		USER_SUBMIT : "Verzenden",
		USER_RESET : "Terug naar standaard",
		USER_YES : "Ja",
		USER_NO : "Nee",
		USER_STYLEPATH : "Pad naar styles.css",
		USER_PROBES : "Spionage Raporten",
		USER_EMAIL : "E-mail",
		USER_ERROR1 : "Wachtwoord of e-mail ongeldig.",
		USER_ERROR2 : "E-mail ongeldig.",
		USER_INGAME : "In-game Naam",
		USER_ALLYTAG : "Alliantie label",
		USER_ALLYHISTORY : "Alliantie historie",
		USER_DIPLOMATIC : "Diplomaat",
		USER_STATSPAGE : "Aantal statistieken per pagina",
		USER_LINKS : "Links",
		USER_LINKS2 : "Opmaak:<br>tekst;url<br>tekst2;url2<br>tekst3;url3",
		USER_EXPORT_TITLE : "Export kleuren (BB Codes)",
		USER_BB_COORDINATES : "Co&ouml;rdinaten",
		USER_BB_MOON : "Maan",
		USER_BB_DEBRIS : "Puin veld",
		USER_BB_ALLY : "Alliantie naam",
		USER_BB_ALLYDETAILS : "Alliantie informatie",
		USER_BB_PLAYERNAME : "Speler naam",
		USER_BB_BANNED : "geblokkeerd",
		USER_BB_VACATION : "vakatie mode",
		USER_BB_NOOB : "Zwak",
		USER_BB_INACTIVE : "Inactief",
		USER_BB_LONGINACTIVE : "Lang inactief",
		USER_DELETION : "Verwijderen",
		USER_FLEETINFO : "Vlootbewegingen",
		USER_ACTIVITIES : "Spelersactiviteiten",
		USER_MAINTENANCE : "Galaxytool onderhoud",
		USER_MANAGEMENT : "Gebruikersbeheer",
		USER_DELETE_MY_COMBAT_REPORTS : "Verwijder mijn evechtsrapporten",
		USER_DELETE_MY_MESSAGES : "Verwijder mijn berichten",
		USER_DELETE_MY_FLEETMOVES : "Verwijder mijn vloot bewegingen",
		USER_DELETE_MY_COMBAT_REPORTS_LIMITED : "Verwijder mijn gevechtsrapporten ouder dan &1 dagen",
		USER_DELETE_MY_MESSAGES_LIMITED : "Verwijder mijn berichten ouder dan &1 dagen",
		USER_TABLE_ENTRIES : "Aantal zoekresultaten per pagina",
		USER_EXISTS : "Gebruiker bestaat al!",
		USER_BB_OUTLAW : "Vogelvrij",
		USER_INVALID_URL : "De URL &1 lijkt ongeldig en zal worden genegeerd.",
		VIEW_TITLE : "OGame Galaxytool - Details",
		VIEW_NODATA : "Geen gegevens beschikbaar.",
		VIEW_GALAXY : "Melkweg",
		VIEW_SYSTEM : "Zonnestelsel",
		VIEW_POSITION : "Pos.",
		VIEW_PLANET : "Planeet",
		VIEW_MOON : "Maan",
		VIEW_TF : "PV",
		VIEW_PLAYER : "Speler",
		VIEW_PLAYER_ADD : "(Rang / Status)",
		VIEW_ALLY : "Alliantie",
		VIEW_ALLY_ADD : "(Rank / Leden)",
		VIEW_METAL : "M",
		VIEW_CRYSTAL : "K",
		VIEW_COLONISED : "Planeten bewoond",
		VIEW_UKMOONSIZE : "onbekend",
		VIEW_BACK : "terug",
		VIEW_NOTICE : "Notities",
		VIEW_REPORTS : "Rapporten",
		VIEW_MOONPHALANX : "De volgende manen kunnen dit zonnestelsel scannen",
		VIEW_NOMOONS : "Geen manen gevonden",
		VIEW_IRAKS : "De volgende planeet kan dit zonnestelsel bereiken met Interplanetaire Raketten",
		VIEW_NOIRAKS : "Geen Interplanetaire Raketten gevonden",
		VIEW_MOON_DESTROY_CHANCE : "Kans op maan vernietiging",
		VIEW_CHANCE_WITH_ONE : "Kans met 1 Ster des Doods",
		VIEW_CHANCE_WITH_N : "Kans met ",
		VIEW_DEATH_STARS : " Sterren des Doods",
		VIEW_DS_DESTROY_CHANCE : "Kans op ster vernietiging",
		VIEW_TOP : "Top",
		VIEW_GO : "go",
		VIEW_DIAMETER : "Diameter",
		PW_TITLE : "OGame Galaxytool - wijzig wachtwoord",
		OLD_PASSWORD : "oud wachtwoord",
		NEW_PASSWORD : "nieuw wachtwoord",
		CONFIRM_NEW_PASSWORD : "bevestig nieuw wachtwoord",
		PW_MISMATCH : "Wachtwoorden zijn niet hetzelfde!",
		PW_ERROR : "Je oude wachtwoord was niet juist!",
		UPDATE_DONE : "Wachtwoord gewijzigd.",
		TIMEZONE_OFFSET : "Verschil tijdszone met server",
		DELETE_ACCOUNT : "Verwijder dit Galaxytool account",
		DELETE_ACCOUNT_SAFETY_REQUEST : "Weet u het zeker?",
		CH_PASSWD_AUTHORIZATION : "Authorizatie",
		CH_PASSWD_ADMIN : "Admin",
		TIMEZONE_OGAME_OFFSET : "Verschil tijdszone met OGame server",
		CH_PASSWD_USER_LANGUAGE : "Verander naar deze taal nadat je hebt ingelogd",
		CH_PASSWD_USER_LANGUAGE_NO_CHANGE : "Geen verandering",
		CH_PASSWD_EXPAND : "Uitgeklapt",
		CH_PASSWD_COLLAPSE : "Ingeklapt",
		CH_PASSWD_HIDDEN : "Verborgen",
		CH_PASSWD_GETTING_STARTED : "Toon de beginners instructies  na inlogen",
		CH_PASSWD_PLUGIN : "Toon Plugin Info na het inloggen",
		NOTICE_TITLE : "OGame Galaxytool - Notities",
		NOTICE_HEADER : "wijzig notitie",
		NOTICE_HEADER2 : "Wijzig eigen notities",
		NOTICE_PUBLIC : "Beschikbaar voor publiek ?",
		NOTICE_YES : "Ja",
		NOTICE_NO : "Nee",
		NOTICE_TEXT : "Notitie",
		NOTICE_SAVE : "Bewaar",
		NOTICE_DELETED : "Gegevens verwijderd.",
		NOTICE_SAVED : "Gegevens opgeslagen.",
		NOTICE_RESULTS : "Alle resultaten",
		NOTICE_USER : "Gebruiker",
		NOTICE_DATE : "Datum",
		NOTICE_EDIT : "Wijzig",
		NOTICE_DELETE : "Verwijder",
		NOTICE_NEW : "Creeer een nieuwe toevoeging",
		NOTICE_NOTPUBLIC : "Notitie niet publiek",
		NOTICE_ALL : "alles",
		NOTICE_NONE : "geen",
		NOTICE_SEARCH : "Zoek in notities",
		NOTICE_SEARCH_SHORT : "Zoek",
		NOTICE_HITS : "Resultaten",
		NOTICE_SHOWRESULTS : "Aantal resultaten per pagina",
		NOTICE_OF : "van",
		NOTICE_NOTHING : "Geen resultaten",
		NOTICE_CHARS : "Tekens",
		NOTICE_PLAYERNAME : "Speler",
		NOTICE_SHOWALL : "Laat alle notities zien",
		REPORTS_TITLE : "OGame Galaxytool - Spionage rapporten",
		REPORTS_RESOURCES : "Grondstoffen",
		REPORTS_FLEET : "Vloten",
		REPORTS_DEFENCE : "Verdediging",
		REPORTS_BUILDINGS : "Gebouwen",
		REPORTS_TECHNOLOGY : "Onderzoek",
		REPORTS_MOON : "Maan",
		REPORTS_SEARCH : "Zoek in spionage rapporten",
		REPORTS_SEARCH_SHORT : "Zoek",
		REPORTS_HITS : "Resultaten",
		REPORTS_NOTHING : "Geen Resultaten gevonden",
		REPORTS_ADDRESS : "Coords",
		REPORTS_CURRENTNESS : "Laatste scan",
		REPORTS_PLAYERNAME : "Speler",
		REPORTS_ALLY : "Alliantie",
		REPORTS_VIEW : "bekijk rapport",
		REPORTS_SEARCH_IN : "Zoek in melkweg",
		REPORTS_FROM_SYSTEM : "van zonnestelsel",
		REPORTS_TO : "naar",
		REPORTS_DELETE : "verwijder",
		REPORTS_DELETED : "Gegevens verwijdert",
		REPORTS_RESULTS : "Resultaten per pagina",
		REPORTS_OF : "van",
		REPORTS_DATE : "Datum",
		REPORTS_DATE_0 : "alles",
		REPORTS_DATE_1 : "ouder dan",
		REPORTS_DATE_2 : "nieuwer dan",
		REPORTS_NOTICES : "Notities",
		REPORTS_AT_LEAST_RESOURCES : "Grondstoffen (op zijn minst)",
		REPORTS_SEARCH_EXTENDED : "uitgebreide zoekopdracht",
		REPORTS_FLEET_RESIS : "Vloot- score",
		REPORTS_DEFENCE_RESIS : "Verdediging- score",
		REPORTS_ALL_RESIS : "totale scores",
		REPORTS_TECHS : "Technologieën",
		REPORTS_UNKNOWN_ENTRIES : "onbekende rapporten",
		REPORTS_PARTLY_INSERTED : "gedeeltelijk toegevoegd",
		REPORTS_FOR_ALL_RES : "voor alle grondstoffen",
		REPORTS_FOR_TF : "voor het puin veld",
		REPORTS_KT : "Kleine vrachtschepen",
		REPORTS_GT : "Grote vrachtschepen",
		REPORTS_SS : "Slagschepen",
		REPORTS_REC : "Recycler",
		REPORTS_RAIDABLE : "Alleen raidbare doelwitten",
		REPORTS_ALL_RESOURCES : "Alle grondstoffen",
		REPORTS_STUFF : "Overige",
		REPORTS_SPEEDSIM : "Simuleer met Speedsim",
		REPORTS_DRAGOSIM : "Simuleer met Dragosim",
		REPORTS_STATUS : "Status",
		REPORTS_ERROR : "Er is een fout opgetreden",
		REPORTS_OWN_REPORTS : "Alleen mijn rapporten",
		REPORTS_UPLOAD_BY : "Rapport verzonden door",
		REPORTS_DEPTH : "Rapport bereik",
		REPORTS_FLEET_SCORE : "Vlootpunten",
		REPORTS_DEFENCE_SCORE : "Verdedigingspunten",
		REPORTS_HOURS : "uren",
		REPORTS_MAX_RESULTS_HIT : "Uw zoekopdracht bevatte meer dan &1 uitkomsten. Enkel de eerste &1 uitkomsten zullen worden getoond. Pas uw zoekopdracht aan om minder uitkomsten te krijgen.",
		REPORTS_OSIMULATE : "Simuleer met OSimulate",
		REPORTS_SHOW_ONLY : "Toon alleen",
		REPORTS_SHOW_PLANETS : "Planeten",
		REPORTS_SHOW_MOONS : "Manen",
		REPORTS_OWNER : "Rapporten beheerd door",
		STATS_TITLE : "OGame Galaxytool - Statistieken",
		STATS_TBLHEAD : "Statistieken",
		STATS_RANK : "Rank",
		STATS_PLAYERNAME : "Speler Naam",
		STATS_ALLYNAME : "Alliantie label",
		STATS_SCORE : "Score",
		STATS_FLEET : "Vloot",
		STATS_RESEARCH : "Onderzoek",
		STATS_MEMBERS : "Leden",
		STATS_STATUS : "Status",
		STATS_NOTHING : "geen Status",
		STATS_NAP : "NAP",
		STATS_ALLIED : "Allied",
		STATS_WAR : "Oorlog",
		STATS_BOYCOTT : "Boycot",
		STATS_NEUTRAL : "Neutraal",
		STATS_OWN : "Eigen Alliantie",
		STATS_WING : "Wing",
		STATS_UPDATE : "ingevuld op",
		STATS_PLAYERSTATS : "Speler Stats",
		STATS_ALLYSTATS : "Alliantie Stats",
		STATS_DELETE : "Wil je deze toevoeging verwijderen?",
		STATS_CONFIRM_DELETE : "Weet je zeker dat je deze toevoeging wilt verwijderen?",
		STATS_CHANGE_PLAYER_STATUS : "Speler status",
		STATS_CHANGE_ALLIANCE_STATUS : "Alliantie status",
		STATS_CHANGE_ALLIANCE_STATUS_HINT : "Alle leden van deze alliantie krijgen de gekozen status. Elke vorige status wordt overschreven. Je kan de status van spelers later veranderen.",
		STATS_UNKNOWN : "Rest",
		STATS_DETAILS : "Details voor",
		STATS_PLAYERSTATUS : "Spelerstatus",
		STATS_IGNORE_STATUS : "iedereen",
		STATS_ACTIVE : "Actief",
		STATS_INACTIVE : "Inactief",
		STATS_BANNED : "geblokkeerd",
		STATS_VACATION : "vakatie mode",
		STATS_NOOB : "Zwak",
		STATS_YES : "Ja",
		STATS_NO : "Alleen planeten met een notitie",
		STATS_SEARCH : "Zoek",
		STATS_SHOW_GRAPH : "Toon details van score verdeling",
		STATS_LONG_INACTIVE : "Lang inactief",
		STATS_STANDARD : "Standaard punten",
		STATS_MILITARY : "Militaire punten",
		STATS_ECONOMY : "Economie",
		STATS_HONOUR : "Erepunten",
		STATS_MILITARY_BUILD : "Militaire punten opgebouwd",
		STATS_MILITARY_DESTROYED : "Militaire punten vernietigd",
		STATS_MILITARY_LOST : "Militaire punten verloren",
		REGISTER_REGISTRATE : "Registreer",
		REGISTER_LOGINNAME : "Login-Naam",
		REGISTER_PASSWORD : "Wachtwoord",
		REGISTER_PASSWORD_CONFIRM : "Bevestig wachtwoord",
		REGISTER_EMAIL : "E-mail",
		REGISTER_INGAME : "Ingame-Naam",
		REGISTER_ALLYTAG : "Alliantie label",
		REGISTER_EMAILVERIFICATION : "E-mailcheck",
		REGISTER_EMAILTEXT : "Klik op de volgende link om je registratie te bevestigingen.",
		REGISTER_ERROR1 : "Login-gebruikersnaam bestaat al.",
		REGISTER_ERROR2 : "Fout tijdens het verzenden. Neem contact op met een admin.",
		REGISTER_ERROR3 : "Fout tijdens de communicatie met de database!",
		REGISTER_INFO1 : "Je account is aangemaakt.",
		REGISTER_INFO2 : "Klik op de link in de e-mail om je registratie te bevestigingen.",
		REGISTER_INFO3 : "Account bevestigd. De admin zal hem nu activeren.",
		REGISTER_BUTTON : "Terug naar de beginpagina",
		REGISTER_NEW_SUBJECT : "Een nieuwe gebruiker heeft zich geregistreerd bij galaxytool.",
		REGISTER_NEW_MAILTEXT : "Een nieuwe gebruiker heeft zich geregistreed.",
		REGISTER_BACK : "Terug naar de beginpagina",
		REGISTER_MISSING_FIELDS : "Niet alle velden zijn ingevuld",
		REGISTER_ERROR4 : "ongeldig Email adres",
		REGISTER_ERROR5 : "Wachtwoorden komen niet overeen.",
		REGISTER_PWS : "Wachtwoord sterkte",
		REGISTER_PWS0 : "zeer zwak",
		REGISTER_PWS1 : "zwak",
		REGISTER_PWS2 : "goed",
		REGISTER_PWS3 : "sterk",
		REGISTER_PWS4 : "zeer sterk",
		REGISTER_EMAIL_USED : "Het opgegeven e-mailadres wordt al gebruikt.",
		LOSTPW_TITLE : "Wachtwoord vergeten",
		LOSTPW_INFO2 : "Een nieuw wachtwoord is aangemaakt en naar je e-mail adres gestuurd.",
		LOSTPW_BUTTON1 : "nieuw wachtwoord",
		LOSTPW_BUTTON2 : "Terug naar de beginpagina",
		LOSTPW_LOGINNAME : "Login-Naam",
		LOSTPW_EMAIL : "Email",
		LOSTPW_ERROR1 : "Fout tijdens de communicatie met de database!",
		LOSTPW_ERROR2 : "Niets gevonden!",
		LOSTPW_ERROR3 : "Fout tijdens het verzenden. Neem contact op met een admin.",
		LOSTPW_EMAIL_SUBJECT : "Je nieuwe wachtwoord",
		LOSTPW_EMAIL_TEXT1 : "Hier is je nieuwe login voor de Galaxytool",
		LOSTPW_EMAIL_TEXT2 : "Gebruikersnaam",
		LOSTPW_EMAIL_TEXT3 : "Wachtwoord",
		LOSTPW_INFO1 : "U zult een email ontvangen om te controleren of u daadwerkelijk een wachtwoordreset heeft aangevraagd.",
		LOSTPW_CONFIRM_RESET_SUBJECT : "Wachtwoord verloren?",
		LOSTPW_CONFIRM_RESET_MESSAGE : "Hallo,\n\nu heeft een wachtwoordreset aangevraagd voor de Galaxytool. Om een nieuw wachtwoord te genereren, klikt u op de volgende link:",
		USERINFO_TITLE : "OGame Galaxytool - Gebruikers informatie",
		USERINFO_NAMES : "Alle gebruikers van deze tool",
		USERINFO_DETAIL : "gedetailleerde informatie over",
		USERINFO_ERROR1 : "Geen gebruiker met dit ID!",
		USERINFO_USERNAME : "Login naam",
		USERINFO_INGAME : "In-game naam",
		USERINFO_EMAIL : "Email",
		USERINFO_ALLYTAG : "Alliantie",
		USERINFO_STYLEPATH : "Skin",
		USERINFO_STATUS : "Status",
		USERINFO_ACTIVATE : "Activeer speler",
		USERINFO_LOGINS : "Aantal keer ingelogd",
		USERINFO_LASTLOGIN : "Laatste Login",
		USERINFO_DATA : "Informatie over deze melkwegen",
		USERINFO_NODATA : "Deze gebruiker heeft nog geen melkwegen toegevoegd!",
		USERINFO_GALAXY : "Melkweg",
		USERINFO_SYSTEMS : "Aantal melkwegen",
		USERINFO_IP : "IP adres",
		USERINFO_LOGINTIME : "Login",
		USERINFO_NOLOGIN : "De speler is nog nooit ingelogd.",
		USERINFO_LAST_GALAXYUPDATE : "Laatste ingevoerde melkweg",
		USERINFO_LAST_PUBLIC_NOTICE : "Laatste publieke notitie",
		USERINFO_LAST_PRIVATE_NOTICE : "Laatste prive notitie",
		USERINFO_NUMBEROF_PUBLIC_NOTICE : "Aantal plublieke notities",
		USERINFO_NUMBEROF_PRIVATE_NOTICE : "Aantal prive notities",
		USERINFO_ACTIVATED : "Account geactiveerd",
		USERINFO_ACTIVATIONTEXT : "De Galaxytool admin je account geactiveerd.\n\nVeel plezier met de Galaxytool!",
		USERINFO_LAST_SUBMIT : "Laatst toegevoegde data",
		ALLYHISTORY_TITLE : "OGame Galaxytool - Alliantie Geschiedenis",
		ALLYHISTORY_TBLHEAD : "Historisch overzicht",
		ALLYHISTORY_PLAYERNAME : "Speler Naam",
		ALLYHISTORY_ALLYNAME : "Alliantie",
		ALLYHISTORY_LASTMONTH : "Afgelopen maand",
		ALLYHISTORY_ALL_DATA : "alle beschikbare informatie",
		ALLYHISTORY_SHOW : "laat statistieken zien",
		ALLYHISTORY_TIMESPAN : "Tijdsbereik",
		ALLYHISTORY_PROGESS : "Voortgang",
		ALLYHISTORY_SCORE : "Scores",
		ALLYHISTORY_FSCORE : "Vloot scores",
		ALLYHISTORY_RSCORE : "Onderzoeks scores",
		ALLYHISTORY_MEMBER : "Leden",
		ALLYHISTORY_NOTHING : "niets gevonden",
		ALLYHISTORY_DETAILS : "Details",
		ALLYHISTORY_SHOW_ADDRESS : "Coördinaten",
		ALLYHISTORY_ESCORE : "Economie",
		ALLYHISTORY_MSCORE : "Militaire punten",
		DETAILEDINFO_PLAYERINFO_TITLE : "Speler informatie",
		DETAILEDINFO_ALLYINFO_TITLE : "Alliantie informatie",
		DETAILEDINFO_PLAYERINFO_TBLHEAD : "Gedetailleerde speler informatie",
		DETAILEDINFO_ALLYINFO_TBLHEAD : "Gedetailleerde alliantie informatie",
		DETAILEDINFO_NO_ALLIANCE : "geen",
		DETAILEDINFO_SCORE : "Score statistieken",
		DETAILEDINFO_FLEET : "Vloot statistieken",
		DETAILEDINFO_RESEARCH : "Onderzoeks statistieken",
		DETAILEDINFO_RANK : "Rank",
		DETAILEDINFO_POINTS : "Score",
		DETAILEDINFO_KNOWN_PLANETS : "bekende planeten",
		DETAILEDINFO_MOONS : "bekende manen",
		DETAILEDINFO_PHALANX_AREA : "Phalanx bereik",
		DETAILEDINFO_NO_PHALANX_AREA : "Geen Phalanx gevonden",
		DETAILEDINFO_NOTICES : "Notities",
		DETAILEDINFO_NO_NOTICES : "Geen notities gevonden",
		DETAILEDINFO_PREVIOUS_ALLIANCES : "Vorige Allianties",
		DETAILEDINFO_RESOURCES_PER_HOUR : "Grondstoffen per uur",
		DETAILEDINFO_RESOURCES_PER_DAY : "Grondstoffen per dag",
		DETAILEDINFO_RESOURCES_PER_WEEK : "Grondstoffen per week",
		DETAILEDINFO_RESOURCES_PER_MONTH : "Grondstoffen per maand (30 dagen)",
		DETAILEDINFO_METAL : "Metaal",
		DETAILEDINFO_CRYSTAL : "Kristal",
		DETAILEDINFO_DEUTERIUM : "Deuterium",
		DETAILEDINFO_UNKNOWN : "onbekend",
		DETAILEDINFO_SCORE_DISTRIBUTION : "Punten verdeling",
		DETAILEDINFO_GENERAL : "Informatie",
		DETAILEDINFO_MEMBERS : "lid",
		DETAILEDINFO_GRAPHS : "Grafieken",
		DETAILEDINFO_RESOURCES : "Grondstoffen",
		DETAILEDINFO_FLEET_TAB : "Vloot",
		DETAILEDINFO_TECH : "Onderzoek",
		DETAILEDINFO_FLEET_DETAIL : "Som / (Spelers gemiddelde) beschikbaar uit rapporten",
		DETAILEDINFO_TECH_DETAIL : "gemiddelde van alle beschikbare informatie v/d speler",
		DETAILEDINFO_PLANET_TAB : "Planeten",
		DETAILEDINFO_MOON_TAB : "Manen",
		DETAILEDINFO_ACTIVITIES : "Activiteiten",
		DETAILEDINFO_NODATA : "Geen gegevens beschikbaar.",
		DETAILEDINFO_ACTIVITY_DESCRIPTION : "Toon de activiteiten van &1 verzameld uit:",
		DETAILEDINFO_GALAXYVIEWS : "Melkweg bekijken",
		DETAILEDINFO_SCANS : "Spionage berichten",
		DETAILEDINFO_MESSAGES : "Privé berichten",
		DETAILEDINFO_COMBATS : "Gevechtsrapporten",
		DETAILEDINFO_ALLYPAGE : "Alliantie overzicht",
		DETAILEDINFO_MANUAL : "Handmatige invoer",
		DETAILEDINFO_START : "Begin",
		DETAILEDINFO_TO : "tot",
		DETAILEDINFO_TODAY : "Vandaag",
		DETAILEDINFO_DATA_RESTRICTION : "beperkt tot:",
		DETAILEDINFO_WEEKDAY_WEEKEND : "Weekend",
		DETAILEDINFO_WEEKDAY_WORKINGDAY : "Weekdag",
		DETAILEDINFO_WEEKDAY_MONDAY : "Maandag",
		DETAILEDINFO_WEEKDAY_TUESDAY : "Dinsdag",
		DETAILEDINFO_WEEKDAY_WEDNESDAY : "Woensdag",
		DETAILEDINFO_WEEKDAY_THURSDAY : "Donderdag",
		DETAILEDINFO_WEEKDAY_FRIDAY : "Vrijdag",
		DETAILEDINFO_WEEKDAY_SATURDAY : "Zaterdag",
		DETAILEDINFO_WEEKDAY_SUNDAY : "Zondag",
		DETAILEDINFO_WEEKDAY_SHORTLENGTH : 3,
		DETAILEDINFO_PLAYER_CURRENTLY_ACTIVE : "De speler is momenteel actief",
		DETAILEDINFO_PLAYER_MESSAGES : "beschikbare privé berichten",
		DETAILEDINFO_SHOW : "tonen",
		DETAILEDINFO_NONE : "geen berichten beschikbaar",
		DETAILEDINFO_ENTER_MANUALLY : "Voer activiteiten voor deze speler in",
		DETAILEDINFO_PLAYER_SEEN_ON : "Speler was online op",
		DETAILEDINFO_INSERT : "invoeren",
		DETAILEDINFO_OGAME_SERVERTIMES : "Let op: Alle data en tijden verwijzen naar server de OGame server!",
		DETAILEDINFO_DAY_VIEW : "24 uurs overzicht",
		DETAILEDINFO_WEEK_VIEW : "weekoverzicht",
		DETAILEDINFO_HOME_PLANET : "Thuis planeet",
		DETAILEDINFO_PLANETNAME : "Naam",
		DETAILEDINFO_DEFENCE_SCORE : "Verdedigingsscore",
		DETAILEDINFO_DEFENCE_SCORE_TOOLTIP : "Verdedigingsscore = Vloot - Score + Onderzoek + Economie.<br/>Alle statistieken moeten up-to-date zijn en moeten geldige invoer bevatten!",
		DETAILEDINFO_SCORE_PER_SHIP : "Scores per schip",
		DETAILEDINFO_SHIPS : "Aantal schepen",
		DETAILEDINFO_DATE_IN_FUTURE : "Vul geen tijden in die zich in de toekomst afspelen.",
		ADMIN_TITLE : "Administratie van de Galaxytool",
		ADMIN_DISCLAMER : "OPGELET: Het uitvoeren van deze scripts geschied op eigen risico! Het meeste van deze scripts verwijderdt gegevens.",
		ADMIN_INCONSISTENCIES : "Inconsistentie in de database",
		ADMIN_PLANETS : "Planeten bij positie 0 of groter dan 15",
		ADMIN_GALAXIES : "Verwijder galaxies groter dan &1 ",
		ADMIN_PLAYERS : "Verwijder spelers zonder een OGame playerID (Dit leidt tot dubbele records",
		ADMIN_REPORTS : "Verwijder rapporten van niet bestaande planeten",
		ADMIN_MISC : "Diversen",
		ADMIN_RESET : "Reset Galaxytool (Gebruiker en IP tabel blijven in tact)",
		ADMIN_OLD_PLAYERS : "Verwijder spelergegevens ouder dan &1 dagen",
		ADMIN_OLD_REPORTS : "Verwijder rapporten ouder dan &1 dagen",
		ADMIN_LOADING : "Het venster niet sluiten wanneer de pagina is geladen.",
		ADMIN_STATUS : "Status van je aanvraag",
		ADMIN_SELECTION : "Er moet op zijn minst 1 selectie worden gekozen",
		ADMIN_SAFETY : "Weet u het zeker?(voor het uitvoeren van de scripts)",
		ADMIN_DONE : "klaar",
		ADMIN_NOTBD : "niets uitgevoerd",
		ADMIN_OLD_GALAXIES : "Verwijder galaxy bezichtigingen die ouder zijn dan &1 dagen",
		ADMIN_UNUSED_PLAYERS : "Verwijder spelers die niet bestaan in de galaxy overzicht",
		ADMIN_OLD_ACTIVITIES : "Verwijder spelers activiteiten ouder dan &1 dag/dagen",
		ADMIN_OLD_COMBATS : "Verwijder gevechtsrapporten ouder dan &1 dagen",
		ADMIN_OLD_INGAME_MSG : "Verwijder berichten ouder dan &1 dagen",
		ADMIN_OGAME_API : "Laad publieke data van OGame in de Galaxytool",
		ADMIN_OGAME_ALL_DATA : "alle beschikbare informatie",
		ADMIN_OGAME_GALAXY_DATA : "Melkweg overzicht",
		ADMIN_OGAME_STATISTICS_DATA : "Statistieken",
		ERRORPAGE_PAGEFORWARD : "Klik hier als uw browser page forwarding niet ondersteund",
		ERRORPAGE_PERMISSION_DENIED : "U heeft niet de juiste machtigingen om deze pagina te bezichtigen. Klik hier om terug te gaan.",
		FLEETS_TITLE : "Vlootbeweging",
		FLEETS_ACTUAL_FLEETS : "Huidige vlootbeweging",
		FLEETS_YES : "Ja",
		FLEETS_NO : "Alleen planeten met een notitie",
		FLEETS_DETAILS : "Details",
		FLEETS_MISSION_EXPEDITION : "Expeditie",
		FLEETS_MISSION_COLONIZATION : "Kolonisatie",
		FLEETS_MISSION_RECYCLE : "Puinruimen",
		FLEETS_MISSION_TRANSPORT : "Transporteren",
		FLEETS_MISSION_DEPLOYMENT : "Verplaatsing",
		FLEETS_MISSION_ESPIONAGE : "Spionage",
		FLEETS_MISSION_ACS_DEFEND : "AGS Verdediging",
		FLEETS_MISSION_ATTACK : "Aanval",
		FLEETS_MISSION_ACS_ATTACK : "AGS Aanval",
		FLEETS_MISSION_MOON_DESTRUCTION : "Vernietiging maan",
		FLEETS_MISSION_MISSILE_ATTACK : "Raket aanval",
		FLEETS_NO_DATA : "Geen relevante data gevonden",
		FLEETS_FLEET : "Vloot",
		FLEETS_ALL_FLEETS : "Toon alle vlootbewegingen",
		COMBAT_REPORT_OUDATED_GALAXYVIEW : "Uw galaxy data is verouderd. Gelieve de sytemen van de aanvalsoorsprong en het doel opnieuw te bekijken.",
		MESSAGES_TITLE : "OGame Galaxytool - OGame berichten",
		MESSAGES_PLAYERNAME : "Naam speler",
		MESSAGES_SUBJECT : "Onderwerp",
		MESSAGES_DATE : "Datum",
		MESSAGES_FILTER : "Filter",
		MESSAGES_DELETE : "Verwijder bericht",
		MESSAGES_PUBLISH_DETAIL : "Voeg inhoud bericht toe aan de notitie van die speler.",
		MESSAGES_PUBLISH_HEADER : "&sender verzond een bericht aan &recipient op &date:\n\n &message",
		MESSAGES_PLAYER_FILTER : "Berichten voor speler:",
		MESSAGES_CONTENT : "Inhoud",
		COMBATS_TITLE : "OGame Galaxytool - gevechtsrapporten",
		COMBATS_ATTACKER : "Aanvaller",
		COMBATS_DEFENDER : "Verdediger",
		COMBATS_DATE : "Datum",
		COMBATS_OWNER : "Eigenaar",
		COMBATS_WINNER : "Winaar",
		COMBATS_COMBATREPORT : "Gevechtsrapport",
		COMBATS_COMBAT_AT : "Gevecht op",
		COMBATS_LOST_UNITS : "Verloren eenheden",
		COMBATS_LOOT : "Buit",
		COMBATS_DEBRIS : "Puin",
		COMBATS_AND : "en",
		COMBATS_PUBLISH : "Maak dit rapport openbaar",
		COMBATS_UNPUBLISH : "Stop met het delen van dit rapport (maak het weer privé)",
		COMBATS_DELETE : "Verwijder rapport",
		COMBATS_CHECK_ALL : "Selecteer alles",
		COMBATS_UNCHECK_ALL : "Deselecteer alles",
		COMBATS_WITH_SELECTED : "Met geselecteerde",
		COMBATS_PUBLIC_REPORTS : "Openbare rapporten",
		COMBATS_YES : "Ja",
		COMBATS_NO : "Alleen planeten met een notitie",
		COMBATS_SEARCH_OPTIONS : "Zoek opties",
		COMBATS_SEARCH : "Zoeken",
		COMBATS_RESET : "Reset",
		COMBATS_COORDINATES : "Co&ouml;rdinaten",
		COMBATS_INVALID_GALAXY_ENTERED : "ongeldige Melkweg ingevoerd",
		COMBATS_INVALID_SYSTEM_ENTERED : "ongeldig Zonnestelsel ingevoerd",
		COMBATS_INVALID_PLANET_ENTERED : "ongeldig Planeet ingevoerd",
		COMBATS_GALAXY_FROM_TO : "Melkweg",
		COMBATS_SYSTEM_FROM_TO : "Zonne stelsel",
		COMBATS_PLANET_FROM_TO : "Planeet",
		COMBATS_APPLY : "Toepassen",
		COMBATS_COMBAT_SUMMARY : "Gevechtsrapporten overzicht",
		COMBATS_DOWNLOAD_CSV : "Downloaden als CSV bestand",
		REPORT_ARCHIVE_TITLE : "Rapporten archief",
		REPORT_ARCHIVE_COORDINATES : "Coördinaten",
		REPORT_ARCHIVE_SCANTIME : "Scantijd",
		REPORT_ARCHIVE_DELETE : "Verwijder deze invoer",
		REPORT_ARCHIVE_CONFIRM_DELETE : "Weet je zeker dat je het wilt verwijderen?",
		REPORT_ARCHIVE_GALAXY : "Melkweg",
		REPORT_ARCHIVE_SYSTEM : "Zonnestelsel",
		REPORT_ARCHIVE_PLANET : "Planeet",
		REPORT_ARCHIVE_MOON : "Maan",
		REPORT_ARCHIVE_DETAILS : "Details",
		REPORT_ARCHIVE_RESOURCES : "Grondstoffen per uur",
		REPORT_ARCHIVE_HEADER_RESOURCES : "Grondstoffen",
		REPORT_ARCHIVE_DETAILS_FOR : "Rapporten archief voor &1 [&2] (&3)",
		REPORT_ARCHIVE_FLEET_CARGO : "Vloot laadruimte",
		REPORT_ARCHIVE_IRAK_RANGE : "interplanetaire raketten bereik",
		REPORT_ARCHIVE_CHART_TYPE : "Grafiektype",
		INSTALL_TITLE : "Galaxytool installatie voor versie",
		INSTALL_PROGRESS : "Totale voortgang",
		INSTALL_STEP : "Stap",
		INSTALL_CONTINUE : "Doorgaan",
		INSTALL_VALIDATE : "Controleer",
		INSTALL_STEP1 : "Welkom",
		INSTALL_STEP2 : "Schrijfbaarheidscontrolere",
		INSTALL_STEP3 : "Database instellingen",
		INSTALL_STEP4 : "OGame instellingen",
		INSTALL_STEP5 : "Galaxytool instellingen",
		INSTALL_STEP6 : "Administrator wachtwoord",
		INSTALL_STEP7 : "Galaxytool installeren",
		INSTALL_STEP8 : "Installatie afronden",
		INSTALL_FILE_DELETE_CHECK : "Verwijderd aub install.php en update.php van uw webserver.",
		INSTALL_STEP1_PHP_FAILED : "Uw PHP versie &1 werkt niet met deze Galaxytool versie",
		INSTALL_STEP1_FOPEN_FAILED : "Uw PHP versie staat het gebruik van het FOPEN() commandniet toe. Dit is nodig om de OGame API te kunnen gebruiken.",
		INSTALL_STEP1_WELCOME : "Welkom bij de installatie wizard van de Galaxytool. U zult worden begeleid door de installatie van de Galaxytool.",
		INSTALL_STEP2_DESCRIPTION : "Controleer dat config.php en attributes.php schrijfbaar zijn.",
		INSTALL_STEP2_DESCRIPTION2 : "Indien u niet weet hoe dit moet, kijk dan op: &1",
		INSTALL_STEP2_FILE_NOT_WRITEABLE : "Bestand is niet schrijfbaar",
		INSTALL_STEP3_SERVER : "Database server",
		INSTALL_STEP3_USERNAME : "Gebruikersnaam",
		INSTALL_STEP3_PASSWORD : "Wachtwoord",
		INSTALL_STEP3_DBNAME : "Databasenaam",
		INSTALL_STEP3_PREFIX : "Tabel voorvoegsel",
		INSTALL_STEP3_ENTER_PREFIX : "b.v. mytool_",
		INSTALL_STEP3_ENTER_SERVER : "Vul het server adres in. Neem indien contact op met uw serverbeheerder. Meestal is localhost de juiste waarde.",
		INSTALL_STEP3_ENTER_USERNAME : "Vul de gebruikersnaam in voor databasetoegang (bijvoorbeeld root or galaxytool)",
		INSTALL_STEP3_ENTER_PASSWORD : "Vul het wachtwoord in voor databasetoegang",
		INSTALL_STEP3_ENTER_DBNAME : "Vul de database naam in die gebruikt moet worden voor de installatie (Deze database moet wel bestaan)",
		INSTALL_STEP3_CONNECT_FAILED : "Kon geen verbinding maken met de database server",
		INSTALL_STEP3_DB_FAILED : "Database &1 niet gevonden",
		INSTALL_STEP3_MYSQL_VERSION_FAILED : "MySQL versie &1 werkt niet met deze Galaxytool versie",
		INSTALL_STEP4_URL : "OGame URL",
		OGAME_URL_DETAILS : "Vul een URL in die u ziet als u ingelogd bent op OGame. Gebasseerd op die URL zal de Galaxytool informatie ophalen vanuit de OGame API, die kan worden gebruikt om de database te vullen zonder gebruik van de Galaxytoolbar. Deze API is geïntroduceerd tijdens OGame versie 4.1.",
		INSTALL_STEP4_UNIVERSE : "OGame universum",
		INSTALL_STEP4_DEF_TO_DEBRIS : "Verdediging naar puin",
		INSTALL_STEP4_DEBRIS_RATE : "Puin ratio",
		INSTALL_STEP4_SPEED_RATE : "Snelheidsratio",
		INSTALL_STEP4_ENTER_UNIVERSE : "Vul de naam of nummer van uw OGame universum in (hoofdlettergevoelig).",
		INSTALL_STEP4_UNIVERSE_MISSING : "U moet uw universum invullen",
		INSTALL_STEP4_ENTER_URL : "Vul uw OGame universum adres in",
		INSTALL_STEP4_URL_MISSING : "U moet uw OGame adres invullen",
		INSTALL_STEP4_URL_CHECK_FAILED : "Kon geen OGame API vinden op &1",
		INSTALL_STEP4_GETSETTINGS : "Fetch settings",
		INSTALL_STEP5_TOOLNAME : "Galaxytool naam",
		INSTALL_STEP5_ENTER_TOOLNAME : "Dit is de naam die zal worden getoond op de login pagina van uw Galaxytool",
		INSTALL_STEP5_LANGUAGE : "Standaardtaal",
		INSTALL_STEP5_EMAIL_TO : "E-mail naar",
		INSTALL_STEP5_ENTER_EMAIL_TO : "Vul het e-mailadres in waar notificaties heen moeten worden heen gestuurd over registraties",
		INSTALL_STEP5_EMAIL_FROM : "E-mail van",
		INSTALL_STEP5_ENTER_EMAIL_FROM : "Dit e-mailadres wordt getoond als het adres waar je naar beantwoord in alle emails die worden gestuuurd door de GalaxyTool",
		INSTALL_STEP5_USE_PHPMAILER : "Gebruik PHPMailer",
		INSTALL_STEP5_MAXSHOUTS : "Maximaal aantal shoutbox berichten",
		INSTALL_STEP5_ENTER_USE_PHPMAILER : "Gebruik PHPMailer als uw server het versturen van e-mails niet ondersteund",
		INSTALL_PHPMAILER_HOST : "SMPT Host",
		INSTALL_PHPMAILER_HOST_EXAMPLE : "b.v. smtp.provider.com",
		INSTALL_PHPMAILER_USER : "SMPT Gebruikersnaam",
		INSTALL_PHPMAILER_USER_EXAMPLE : "b.v. user@provider.dcom",
		INSTALL_PHPMAILER_PASS : "SMPT Wachtwoord",
		INSTALL_PHPMAILER_SECURE : "Authenticatiemethode (b.v. ssl)",
		INSTALL_PHPMAILER_PORT : "SMTP Poort",
		INSTALL_STEP6_INTRO : "Vul hier een wachtwoord in voor het <strong>administrator</strong> account, waarmee je voor de eerste keer in kan loggen op de Galaxytool na de installatie.",
		INSTALL_STEP7_CONFIG : "Configuratiebestand aangemaakt",
		INSTALL_STEP7_CONFIG_FAILED : "Configuratiebestand niet aangemaakt",
		INSTALL_STEP7_ATTRIBUTES : "Attributen bestand aangemaakt",
		INSTALL_STEP7_ATTRIBUTES_FAILED : "Attributen bestand niet aangemaakt",
		INSTALL_STEP7_CREATED_TABLES : "Database tabellen aangemaakt",
		INSTALL_STEP8_INTRO : "U heeft de Galaxytool successvol geïnstalleerd!",
		INSTALL_STEP8_LOAD_DATA : "OGame data downloaden...",
		INSTALL_STEP8_LOAD_DATA_FINISHED : "Het downloaden van OGame data is voltooid",
		INSTALL_STEP8_DELETE_FILE : "U moet nu de installatiebestanden install.php en update.php van uw webserver verwijderen.",
		INSTALL_STEP8_LOGON : "Log nu in met de <strong>administrator</strong> en het daarbij horende wachtwoord die u eerder heeft opgegeven.",
		UPDATE_START : "Update starten naar versie &1",
		UPDATE_STEP_DONE : "Gelukt",
		UPDATE_TITLE : "Galaxytool update voor versie",
		UPDATE_STEP1_WELCOME : "Wellkom bij de updatewizard van de Galaxytool. U zult begeleid worden door de update van de Galaxytool.",
		UPDATE_STEP1_BACKUP_FILES : "Als eerste step moet u een backup maken van uw <strong>configuratie</strong> map! U zult mogelijk de configuratiebestanden moeten vervangen indien er fouten optreden.",
		UPDATE_STEP1_BACKUP_DB : "Maak daarna een <a href=\"http://www.ehow.com/how_2036600_create-database-php.html\">backup</a> van uw database.",
		UPDATE_STEP1_PROCEED : "Als de backups zijn gemaakt, kunt u doorgaan met de update.",
		UPDATE_STEP1 : "Welkom",
		UPDATE_STEP2 : "Galaxytool instellingen",
		UPDATE_STEP2_OLD_VERSION : "Vorige Galaxytool versie",
		UPDATE_STEP3 : "Update Galaxytool",
		UPDATE_STEP3_UPDATE_RUNNING : "Update in uitvoering, even geduld aub...",
		UPDATE_STEP4 : "Update afronden",
		UPDATE_STEP4_INTRO : "U heeft de Galaxytool met succes geüpdate!",
		UPDATE_STEP4_UPDATE_DONE : "Update uitgevoerd.",
		UPDATE_FAILED : "Update mislukt.",
		GALAXYTOOL_DUMMY_TEXT : "dummy"
	})
);