define(
	({
		REPORT_WHEN : "ob",
		RESOURCES_ON : "Surovine na",
		PLAYER_BANNED : "b",
		PLAYER_VACATION_MODE : "v",
		PLAYER_NOOB : "n",
		PLAYER_INACTIVE : "i",
		PLAYER_LONG_INACTIVE : "I",
		PLAYER_OUTLAW : "o",
		L_USERNAME : "Uporabniško ime",
		L_PASSWORD : "Geslo",
		L_LOGINFAILURE : "Uporabniško ime ali geslo je napačno ali pa vaš račun še ni aktiven",
		L_TOKENFAILURE : "Vnesili ste napačno geslo, ali pa vaš račun še ni aktiviran",
		L_LOGINTEXT : "Prosimo prijavite se.",
		L_LANGUAGE : "Izberi jezik:",
		L_TIMEOUT : "Seja je potekla!",
		L_REGISTER : "Registracija",
		L_PWLOST : "Pozabljeno geslo",
		INDEX_TITLE : "Pregled",
		INDEX_INFO : "Informacije",
		INDEX_ENTRIES : "Število sistemov",
		INDEX_ENTRIES_LASTWEEK : "Novi sistemi od prejšnjega tedna",
		INDEX_ENTRIES_TO_OLD : "Stari sistem od prejšnjega meseca",
		INDEX_REGISTERED_USERS : "Registriranih uporabnikov",
		INDEX_PAGEFORWARD : "Če vas brskalnik ne podpira avtomatske preusmeritve, prosimo kliknite tukaj",
		INDEX_NOTICES : "Objave",
		INDEX_PLAYERS : "Znanih igralcev",
		INDEX_ALLIES : "Znanih alians",
		INDEX_REPORTS : "Vohunsko poročilo",
		INDEX_VERSION : "Zadnja verzija za download",
		INDEX_SHOUTBOX : "Kričač",
		INDEX_NOENTRY : "Trenutno ni sporočil",
		INDEX_COMMENT : "Vaše sporočilo",
		INDEX_INSERT : "Vnesi",
		INDEX_UMOD : "Igralci na dopustu",
		INDEX_LATEST_VERSION : "Ni novejše verzije",
		INDEX_NO_MOONS : "Število lun",
		INDEX_NO_EMPTY_SYSTEMS : "Število praznih sistemov",
		INDEX_NO_FULL_SYSTEMS : "Število popolnoma polnih sistemov",
		INDEX_NO_TARGETS : "Število možnih tarč",
		INDEX_USERINFO : "Uporabniki",
		INDEX_ONLINE : "Trenutno online",
		INDEX_TODAY : "Danes prisotni",
		INDEX_ALL : "Skupno število prijav",
		GENERAL_LOAD_FORM : "Naloži podatke",
		GENERAL_SAVE_FORM : "Shrani podatke",
		GENERAL_SAVE_AS_TEXT : "Shrani kot",
		GENERAL_SAVE : "Shrani",
		INDEX_USERMANAGEMENT : "Aktivacije",
		INDEX_NEEDADMIN : "Še neaktivirani računi",
		INDEX_NEEDEMAIL : "Zavrjeni računi",
		INDEX_TOOLBAR_INFO : "Galaxytool plugin informacije",
		INDEX_TOOLBAR_URL : "Galaxytool URL",
		INDEX_TOOLBAR_VERSION_REQUIRED : "Zahteva zadnjo verzijo Galaxytool plugin",
		INDEX_TOOLBAR_INSTALL_GUIDE : "Navodila za nameščaje plugin",
		INDEX_TOOLBAR_TOKEN : "Ključ",
		INDEX_TOOLBAR_NEW_TOKEN : "Naredi nov ključ",
		INDEX_PLAYERS_WITH_N_PLANETS : "Igralci z več kot &1 planetov",
		INDEX_GETTING_STARTED : "Začnimo",
		INDEX_GETTING_STARTED1 : "Dobrodošli na Galaxytool strani",
		INDEX_GETTING_STARTED2 : "Galaxytool vam bo pomagal nadzirati kaj se dogaja v vesolju &1",
		INDEX_GETTING_STARTED3 : "Preden začnete z brskanjem informacij, morate vnesti le te. Za to potrebujete plugin &1 , vendar deluje le na brskalniku Firefox.",
		INDEX_GETTING_STARTED4 : "Po namestitvi plugin-a, začnete brskati po galaksiji kot to delate ponavadi, z tem da boste videli majhen okvirček v katemem bo pisalo da je bilo nekaj poslano v GalaxyTool. Več galaksij ko boste pregledali, več in bolj točne informacije vam bo na voljo kasneje, zato je pripročeno da preisčete čim več menijev in sončnih sistemov",
		INDEX_GETTING_STARTED5 : "Ko so podatki vnešeni, lahko začnete brskati po informacijah, kot so recimo na primer število in pozicija planetov od določenega igralca, prej vnešena  vohunska poročila, aktivnost igralcev in veliko drugih filtrov ter iskalnikov in grafov.",
		INDEX_GETTING_STARTED6 : "Lahko pa boste tudi primerjali svoj napredek z drugimi igralci, in si iskali konkurenco, Med prijatelji tekmovali kdo naredi več bitk itd...",
		INDEX_GETTING_WIKIPAGE : "Galaxytool vsebuje vse to in zelo veliko več funkcij ter pripomočkov.",
		INDEX_GETTING_WIKIPAGE2 : "Vsako funkcijo lahko posebej preverite kako deluje in čemu je navoljo, na uradni GalaxyTool wiki strani (stran za pomoč)",
		INDEX_GETTING_BOARD : "Za mnenja in ideje glede GalaxyTool-a lahko uporabite naš forum:",
		INDEX_GETTING_CHAT1 : "Ali pa obiščete naš chatroom:",
		INDEX_GETTING_CHAT2 : "Nismo online 24/7 ampak smo vseeno veliko prostega časa tam.",
		INDEX_CLOSE : "Zapri",
		INDEX_LOGIN : "Vpis",
		GENERAL_REQUIRED_FIELDS : "Prosimo, izpolnite vsa polja",
		INDEX_MESSAGES : "Sporočila",
		INDEX_EXAMPLE : "Primer",
		INDEX_INVALID_DATA : "Neveljavni podatki",
		GENERAL_COLUMN_HIDE_TITLE : "Uredi stolpce",
		GENERAL_COLUMN_HIDE_INFO : "Prosimo izberite katere stolpce želite videti.",
		GENERAL_ENTRIES_DELETED : "&1 brisanih vnosov",
		GENERAL_APPLY : "Uporabi",
		STARTPAGE_GALAXYTOOL_DESCR : "<em>Galaxytool</em> je orodje za spletno igro OGame.",
		GENERAL_OVERWRITE : "OPrepiši podvojene vnose.",
		GENERAL_OVERWRITE_QUESTION : "Prepišem?",
		INDEX_OWN_LOGINS : "Vaše prijave",
		GENERAL_OPEN_IN_NEW_WINDOW : "Odpri povezavo v novem oknu",
		GENERAL_UNIT_OF_MEASURE_DAYS : "Days",
		PROGRAM_NAME : "OGame Galaxytool",
		SHORTNAME : "Galaxytool",
		BACK_INDEX : "Nazaj na začetno stran",
		UNIVERSE : "Galaksija",
		MENU_INFO_LINKS : "Informacije",
		MENU_PAGE : "Pregled",
		MENU_DB_SEARCH : "Išči v bazi",
		MENU_DB_NOTICES : "Išči v objavi",
		MENU_DB_REPORTS : "Išči v poročilih",
		MENU_GALAXYVIEW : "Pregled Galaksije",
		MENU_STATISTICS : "Statistike",
		MENU_ALLYHISTORY : "Grafi napredkov",
		MENU_FLEET_MOVEMENTS : "Premiki flot",
		MENU_COMBAT_REPORTS : "Poročila bitk",
		MENU_MESSAGES : "Zasebna sporočila",
		MENU_OPTION_LINKS : "Možnosti",
		MENU_DB_REFRESH : "Dodaj v bazo",
		MENU_NOTICES : "Objave",
		MENU_DB_STATUS : "Stanje baze",
		MENU_USEROPTIONS : "Upravljanje uporabnikov",
		MENU_USEROPTIONS2 : "Urejanje profila",
		MENU_USEROPTIONS3 : "Seznam uporabnikov",
		MENU_ADMIN : "Administracija",
		MENU_LOGOUT : "Odjavi se",
		MENU_STUFF : "Ostalo",
		MENU_FORUM_THREAD : "Forum razvojne ekipe",
		MENU_DOWNLOADPAGE : "Stran za download",
		MENU_LANGUAGE : "Jezik",
		MENU_HELP : "Pomoč",
		MENU_TOOLOPTIONS : "Galaxytool Možnosti",
		PARSER_INFO1 : " je shranjeno v bazo",
		PARSER_ERROR1 : "Napaka pri vnosu teh koordinat v bazo:",
		PARSER_ERROR2 : "Baza ni najdena!",
		PARSER_ERROR3 : "Strežnik ni najden!",
		PARSER_WRONG_UNIVERSE : "Napačno vesolje - actual: \"&1\"  pričakovano: \"&2\"",
		SHOW_TITLE : "OGame Galaxytool - Stran za iskanje",
		SHOW_SEARCH : "Išči v bazi",
		SHOW_ALLYSYMBOL : "Tag alianse",
		SHOW_PLAYERNAME : "Ime igralca",
		SHOW_MOONS : "Samo planeti z luno",
		SHOW_NOTICES : "Samo planeti z opombo",
		SHOW_COLONIES : "Samo planeti za kolonizacijo",
		SHOW_YES : "Da",
		SHOW_NO : "Ne",
		SHOW_SEARCHRANGE : "Domet",
		SHOW_SEARCH_IN : "Išči v galaksiji",
		SHOW_FROM_SYSTEM : "od sistema",
		SHOW_FROM_PLANET : "od pozicija planeta",
		SHOW_TO : "do",
		SHOW_DESCRIPTION : "Lahko uporabljate * za imena igralcev in alianse. <br />Izpolnite samo tista polja ki ji želite specificirati.",
		SHOW_SORT_BY : "Razvrsti po ",
		SHOW_GALASYSTEM : "Galaksija/Sistem",
		SHOW_ALLYNAME : "Ime alians",
		SHOW_SEARCHBUTTON : "Išči",
		SHOW_ADDRESS : "Koordinate",
		SHOW_ALLYSORT : "Aliansa",
		SHOW_PLANET : "Ime planeta",
		SHOW_STATUS : "Status",
		SHOW_CURRENTNESS : "Starost",
		SHOW_PLAYER_STATUS : "Status igralca",
		SHOW_PLAYER_STATUS1 : "vsi",
		SHOW_PLAYER_STATUS2 : "možne tarče",
		SHOW_PLAYER_STATUS3 : "neaktiven",
		SHOW_HITS : "Rezultatov",
		SHOW_OF : "od",
		SHOW_ASC : "abecedno zaporedje",
		SHOW_DESC : "obrnjeno abecedno zaporedje",
		SHOW_RESULTS : "Rezultati po straneh",
		SHOW_MOON : "Luna",
		SHOW_UKMOONSIZE : "nepoznano",
		SHOW_DF : "RU",
		SHOW_DF_LONG : "Ruševin",
		SHOW_METAL : "M",
		SHOW_METAL_LONG : "Metal",
		SHOW_CRYSTAL : "K",
		SHOW_CRYSTAL_LONG : "Kristal",
		SHOW_BOTH : "oboje skupaj",
		SHOW_AT_LEAST : "(najmanjše)",
		SHOW_DATE : "Datum",
		SHOW_DATE_0 : "ni pomembno",
		SHOW_DATE_1 : "starejše od",
		SHOW_DATE_2 : "novejše od",
		SHOW_RANK : "Mesto",
		SHOW_FRANK : "Mesto Flote",
		SHOW_MEMBERS : "Člani",
		SHOW_NOTRANKED : "Ni v top 1500",
		SHOW_NOTICERES : "Objave",
		SHOW_REPORTS : "Samo planeti s poročilom",
		SHOW_REPORTS_SHORT : "Poročila",
		SHOW_NOTHING : "Ni rezultatov",
		SHOW_ALLIANCE_STATUS : "Status alians",
		SHOW_NO_STATUS : "brez Statusa",
		SHOW_NAP : "NAP",
		SHOW_ALLIED : "Aliansa",
		SHOW_WAR : "vojna",
		SHOW_BOYCOTT : "Bojkotirati",
		SHOW_NEUTRAL : "Neutralni",
		SHOW_OWN : "Lastna aliansa",
		SHOW_WING : "Krilo",
		SHOW_EXT_OPTIONS1 : "Prikaži več opcij za iskanje dometa, rang, datum ali ruševine.",
		SHOW_EXT_OPTIONS2 : "Prikaži več opcij za iskanje kolonije, Lune, poročila, belježke, statistike igralcev ali diplomatski status.",
		SHOW_EXT_OPTIONS3 : "Prikaži več opcij iskanja razvrščenih od preiskanih rezultatov.",
		SHOW_EXTENDED : "Napredno iskanje",
		SHOW_MOON_SELECTION : "Planet z luno",
		SHOW_REPORT_SELECTION : "Planet z poročilom",
		SHOW_FILTER_BY : "Izkluči z seznama",
		SHOW_FILTER_NONE : "nihče",
		SHOW_PLAYERS_WITHOUT_PROGRESS : "Show players without score changes within the last few days",
		STATUS_TITLE : "OGame Galaxytool - Statistična stran",
		STATUS_DB_STATUS : "Statistična baza",
		STATUS_COLOR : "Barva",
		STATUS_AGE1 : "Vnos 1 dan star.",
		STATUS_AGE2 : "Vnos 2 - 4 dni star.",
		STATUS_AGE3 : "Vnos 4 - 7 dni star.",
		STATUS_AGE4 : "Vnos 1 - 2 tedna star.",
		STATUS_AGE5 : "Vnos 2 - 4 tednov star.",
		STATUS_AGE6 : "Vnos starejši od 1 meseca!",
		STATUS_AGE7 : "Ni vnosa.",
		STATUS_ON : "vključeno",
		STYLES_COLOR1 : "Barva1",
		STYLES_COLOR2 : "Barva2",
		STYLES_COLOR3 : "Barva3",
		STYLES_COLOR4 : "Barva4",
		STYLES_COLOR5 : "Barva5",
		STYLES_COLOR6 : "Barva6",
		STYLES_COLOR7 : "Barva7",
		STATUS_DB_LEGEND : "Legenda",
		STATUS_GALAXY : "Pregled galaksije",
		USER_TITLE : "OGame Galaxytool - Uporabljanje z uporabniki",
		USER_NAMES : "Uporabnik",
		USER_ERROR : "Napaka",
		USER_NEWUSER : "Nov uporabnik",
		USER_GALAXY : "Galaksija",
		USER_OPTIONS : "Možnosti",
		USER_USERNAME : "Uporabniško ime",
		USER_PASSWORD : "Geslo",
		USER_PASSWORD_CONFIRM : "Potrdi geslo",
		USER_SEARCH : "Išči",
		USER_INSERT : "Vnesi",
		USER_DELETE : "Briši",
		USER_DELETE_ENTRY : "Želite izbrisati uporabnika: ",
		USER_STATUS : "Poglej statistiko",
		USER_STYLES : "Spremeni pogled",
		USER_SUBMIT : "Pošlji",
		USER_RESET : "Uniči",
		USER_YES : "Da",
		USER_NO : "Ne",
		USER_STYLEPATH : "Pot do styles.css",
		USER_PROBES : "Preglej/Pošlji Vohunsko Poročilo",
		USER_EMAIL : "Email",
		USER_ERROR1 : "Geslo ni pravo ali Email ne dela.",
		USER_ERROR2 : "Email nepravilen.",
		USER_INGAME : "Ime v igri",
		USER_ALLYTAG : "Aliansa",
		USER_ALLYHISTORY : "Preglej/Pošlji Zgodovino Alians",
		USER_DIPLOMATIC : "Spremeni Diplomatski Status",
		USER_STATSPAGE : "Število vnosov na statistiko",
		USER_LINKS : "Linki",
		USER_LINKS2 : "Format:<br>text;url<br>text2;url2<br>text3;url3",
		USER_EXPORT_TITLE : "Uporabi barve (BB Kode)",
		USER_BB_COORDINATES : "Koordinate",
		USER_BB_MOON : "Luna",
		USER_BB_DEBRIS : "Ruševine",
		USER_BB_ALLY : "Ime alianse",
		USER_BB_ALLYDETAILS : "Podrobnosti alianse",
		USER_BB_PLAYERNAME : "Igralec",
		USER_BB_BANNED : "Bannan",
		USER_BB_VACATION : "Čas dopusta",
		USER_BB_NOOB : "Začetnik",
		USER_BB_INACTIVE : "Neaktiven",
		USER_BB_LONGINACTIVE : "Dolgo neaktiven",
		USER_DELETION : "Izbriši",
		USER_FLEETINFO : "Premiki flot",
		USER_ACTIVITIES : "Aktivnost igralca",
		USER_MAINTENANCE : "Galaxytool vzdrževanje",
		USER_MANAGEMENT : "Upravljanje uporabnikov",
		USER_DELETE_MY_COMBAT_REPORTS : "Izbriši moja poročila bitk",
		USER_DELETE_MY_MESSAGES : "Izbriši moja zasebna sporočila",
		USER_DELETE_MY_FLEETMOVES : "Izbriši moje premike flot",
		USER_DELETE_MY_COMBAT_REPORTS_LIMITED : "Izbriši moja poročila bitk starejša od &1 dni",
		USER_DELETE_MY_MESSAGES_LIMITED : "Izbriši moja sporočila starejša od &1 dni",
		USER_TABLE_ENTRIES : "Število zadetkov po strani",
		USER_EXISTS : "Uporabnik že obstaja",
		USER_BB_OUTLAW : "Prepovedano",
		USER_INVALID_URL : "Oblika URL &1 je neveljavna - URL nebo upoštevan",
		VIEW_TITLE : "OGame Galaxytool - Podrobno",
		VIEW_NODATA : "Podatki niso dostopni.",
		VIEW_GALAXY : "Galaksija",
		VIEW_SYSTEM : "Solarni sistem",
		VIEW_POSITION : "Poz.",
		VIEW_PLANET : "Planet.",
		VIEW_MOON : "Luna",
		VIEW_TF : "RU",
		VIEW_PLAYER : "Igralec",
		VIEW_PLAYER_ADD : "(Mesto / Status)",
		VIEW_ALLY : "Aliansa",
		VIEW_ALLY_ADD : "(Mesto / Člani)",
		VIEW_METAL : "M",
		VIEW_CRYSTAL : "K",
		VIEW_COLONISED : "Planet naseljen",
		VIEW_UKMOONSIZE : "neznano",
		VIEW_BACK : "nazaj",
		VIEW_NOTICE : "Objave",
		VIEW_REPORTS : "Poročilo",
		VIEW_MOONPHALANX : "Naslednje lune lahko falangirajo ta sistem",
		VIEW_NOMOONS : "Ni najdenih falang",
		VIEW_IRAKS : "Naslednje Medplanetarne rakete lahko dosežejo ta sistem",
		VIEW_NOIRAKS : "Ni najdenih medplanetarnih raket",
		VIEW_MOON_DESTROY_CHANCE : "Možnost za uničenje lune",
		VIEW_CHANCE_WITH_ONE : "Možnost z eno zvezdo smrti",
		VIEW_CHANCE_WITH_N : "Možnost z ",
		VIEW_DEATH_STARS : "zvezdami smrti",
		VIEW_DS_DESTROY_CHANCE : "Možnost za uničenje zvezde smrti",
		VIEW_TOP : "Top",
		VIEW_GO : "go",
		VIEW_DIAMETER : "Premer",
		PW_TITLE : "OGame Galaxytool - menjava gesla",
		OLD_PASSWORD : "staro geslo",
		NEW_PASSWORD : "novo geslo",
		CONFIRM_NEW_PASSWORD : "potrdi novo geslo",
		PW_MISMATCH : "Gesli se ne ujemata!",
		PW_ERROR : "Staro geslo ni pravilno!",
		UPDATE_DONE : "Geslo spremenjeno.",
		TIMEZONE_OFFSET : "Časovni pas",
		DELETE_ACCOUNT : "Izbriši račun",
		DELETE_ACCOUNT_SAFETY_REQUEST : "Ali res želite izbrisati ta račun?",
		CH_PASSWD_AUTHORIZATION : "Autorizacija",
		CH_PASSWD_ADMIN : "Admin",
		TIMEZONE_OGAME_OFFSET : "Časovni pas OGame serverja",
		CH_PASSWD_USER_LANGUAGE : "Spremeni na ta jezik po prijavi",
		CH_PASSWD_USER_LANGUAGE_NO_CHANGE : "Ne spremeni",
		CH_PASSWD_EXPAND : "Razširjeno",
		CH_PASSWD_COLLAPSE : "Zloženo",
		CH_PASSWD_HIDDEN : "Skrito",
		CH_PASSWD_GETTING_STARTED : "Pokaži meni Začnimo po prijavi",
		CH_PASSWD_PLUGIN : "Pokaži meni plugin informacije po prijavi",
		NOTICE_TITLE : "OGame Galaxytool - Poročilo",
		NOTICE_HEADER : "menjava poročila",
		NOTICE_HEADER2 : "Zamenjaj svoje poročilo",
		NOTICE_PUBLIC : "Dostopno drugim ?",
		NOTICE_YES : "da",
		NOTICE_NO : "ne",
		NOTICE_TEXT : "Tekst objave",
		NOTICE_SAVE : "Shrani",
		NOTICE_DELETED : "Brisano",
		NOTICE_SAVED : "Uspešno shranjeno",
		NOTICE_RESULTS : "Vsi rezultati",
		NOTICE_USER : "Uporabnik",
		NOTICE_DATE : "Datum",
		NOTICE_EDIT : "Uredi",
		NOTICE_DELETE : "Briši",
		NOTICE_NEW : "Nov vnos",
		NOTICE_NOTPUBLIC : "Objava ni javna.",
		NOTICE_ALL : "vsi",
		NOTICE_NONE : "nihče",
		NOTICE_SEARCH : "Išči v poročilu",
		NOTICE_SEARCH_SHORT : "Išči",
		NOTICE_HITS : "Rezultati",
		NOTICE_SHOWRESULTS : "Rezultati po straneh",
		NOTICE_OF : "od",
		NOTICE_NOTHING : "Ni najdenih rezultatov",
		NOTICE_CHARS : "Znaki",
		NOTICE_PLAYERNAME : "Igralec",
		NOTICE_SHOWALL : "Prikaži vsa poročila",
		REPORTS_TITLE : "OGame Galaxytool - Vohunsko poročilo",
		REPORTS_RESOURCES : "Surovine",
		REPORTS_FLEET : "Flota",
		REPORTS_DEFENCE : "Obramba",
		REPORTS_BUILDINGS : "Zgradbe",
		REPORTS_TECHNOLOGY : "Laboratorij",
		REPORTS_MOON : "Luna",
		REPORTS_SEARCH : "Išči v poročilu vohunjenja",
		REPORTS_SEARCH_SHORT : "Išči",
		REPORTS_HITS : "Rezultati",
		REPORTS_NOTHING : "Vnos ni najden",
		REPORTS_ADDRESS : "Koordinati",
		REPORTS_CURRENTNESS : "Starost",
		REPORTS_PLAYERNAME : "Ime igralca",
		REPORTS_ALLY : "Aliansa",
		REPORTS_VIEW : "Poglej poročilo",
		REPORTS_SEARCH_IN : "Išči v galaskiji",
		REPORTS_FROM_SYSTEM : "od sistema",
		REPORTS_TO : "do",
		REPORTS_DELETE : "Briši",
		REPORTS_DELETED : "Vnos zbrisan",
		REPORTS_RESULTS : "Rezultati po straneh",
		REPORTS_OF : "od",
		REPORTS_DATE : "Datum",
		REPORTS_DATE_0 : "ni pomembno",
		REPORTS_DATE_1 : "starejši od",
		REPORTS_DATE_2 : "novejši od",
		REPORTS_NOTICES : "Objave",
		REPORTS_AT_LEAST_RESOURCES : "Produkcija (vsaj)",
		REPORTS_SEARCH_EXTENDED : "Razširjeno iskanje",
		REPORTS_FLEET_RESIS : "Točke flote",
		REPORTS_DEFENCE_RESIS : "Točke obrambe",
		REPORTS_ALL_RESIS : "skupno točk",
		REPORTS_TECHS : "Tehnologije",
		REPORTS_UNKNOWN_ENTRIES : "neznani vnosi",
		REPORTS_PARTLY_INSERTED : "delno vneseno",
		REPORTS_FOR_ALL_RES : "za vse surovine",
		REPORTS_FOR_TF : "za ruševine",
		REPORTS_KT : "Mali transporter",
		REPORTS_GT : "Veliki transporter",
		REPORTS_SS : "Bojne ladje",
		REPORTS_REC : "Recikler",
		REPORTS_RAIDABLE : "Edina tarča za raid",
		REPORTS_ALL_RESOURCES : "vsa produkcija",
		REPORTS_STUFF : "Ostalo",
		REPORTS_SPEEDSIM : "Simuliraj z Speedsimom",
		REPORTS_DRAGOSIM : "Simuliraj z Dragosim",
		REPORTS_STATUS : "Status",
		REPORTS_ERROR : "Napaka",
		REPORTS_OWN_REPORTS : "Moja poročila",
		REPORTS_UPLOAD_BY : "Poročilo vnesel",
		REPORTS_DEPTH : "Pordobno poročilo",
		REPORTS_FLEET_SCORE : "Točke flote",
		REPORTS_DEFENCE_SCORE : "Točke obrambe",
		REPORTS_HOURS : "ure",
		REPORTS_MAX_RESULTS_HIT : "Vaša poizvedba ima več kot &1 zadetkov. Le prvih &1 rezultatov je pokazanih. Prosimo opišite iskalje bolj podrobno za manj rezultatov.",
		REPORTS_OSIMULATE : "Simuliraj v OSimulate",
		REPORTS_SHOW_ONLY : "Pokaži le",
		REPORTS_SHOW_PLANETS : "Planeti",
		REPORTS_SHOW_MOONS : "Lune",
		REPORTS_OWNER : "Poročila si lasti",
		STATS_TITLE : "OGame Galaxytool - Statistike",
		STATS_TBLHEAD : "Statistike",
		STATS_RANK : "Mesto",
		STATS_PLAYERNAME : "Ime igralca",
		STATS_ALLYNAME : "Tag alianse",
		STATS_SCORE : "Točke",
		STATS_FLEET : "Flota",
		STATS_RESEARCH : "Laboratorij",
		STATS_MEMBERS : "Člani",
		STATS_STATUS : "Status",
		STATS_NOTHING : "Ni Statusa",
		STATS_NAP : "NAP",
		STATS_ALLIED : "Zaveznik",
		STATS_WAR : "Vojna",
		STATS_BOYCOTT : "Bojkot",
		STATS_NEUTRAL : "Neutralen",
		STATS_OWN : "Lastna aliansa",
		STATS_WING : "Krilo",
		STATS_UPDATE : "Vnos od",
		STATS_PLAYERSTATS : "Statistika igralcev",
		STATS_ALLYSTATS : "Statistika alians",
		STATS_DELETE : "Ali želite zbrisati ta vnos?",
		STATS_CONFIRM_DELETE : "Ali res želite izbrisati ta vnos igralca?",
		STATS_CHANGE_PLAYER_STATUS : "Statistika igralca",
		STATS_CHANGE_ALLIANCE_STATUS : "Statistika Alianse",
		STATS_CHANGE_ALLIANCE_STATUS_HINT : "Vsi člani te alianse dobijo izbran status. Vsak prejšnji status bo spremenjen. lahko spremenite status igralcev naknadno.",
		STATS_UNKNOWN : "Preostanek",
		STATS_DETAILS : "Podrobno za",
		STATS_PLAYERSTATUS : "Status igralca",
		STATS_IGNORE_STATUS : "vsi",
		STATS_ACTIVE : "active",
		STATS_INACTIVE : "Neaktiven",
		STATS_BANNED : "Bannan",
		STATS_VACATION : "Čas dopusta",
		STATS_NOOB : "Začetnik",
		STATS_YES : "Da",
		STATS_NO : "Samo planeti z opombo",
		STATS_SEARCH : "Išči",
		STATS_SHOW_GRAPH : "Pokaži podrobnosti proizvodnje točk",
		STATS_LONG_INACTIVE : "Dolgo neaktiven",
		STATS_STANDARD : "Točke",
		STATS_MILITARY : "Vojaške točke",
		STATS_ECONOMY : "Ekonomija",
		STATS_HONOUR : "Častne točke",
		STATS_MILITARY_BUILD : "Zgrajene vojaške točke",
		STATS_MILITARY_DESTROYED : "Vojaške točke uničene",
		STATS_MILITARY_LOST : "Izgubljene vojaške točke",
		REGISTER_REGISTRATE : "Registracija",
		REGISTER_LOGINNAME : "Ime Uporabnika",
		REGISTER_PASSWORD : "Geslo",
		REGISTER_PASSWORD_CONFIRM : "Potrdi geslo",
		REGISTER_EMAIL : "Email",
		REGISTER_INGAME : "Ime v igri",
		REGISTER_ALLYTAG : "Tag alianse",
		REGISTER_EMAILVERIFICATION : "Preverjanje Emaila",
		REGISTER_EMAILTEXT : "Prosimo vas da odprete to stran in s tem potrdite vaš Email naslov na Galaxietool-u.",
		REGISTER_ERROR1 : "Uporabniško ime že obstaja!",
		REGISTER_ERROR2 : "Napaka pri pošiljanju Emaila! Prosimo, kontaktirate administratorja.",
		REGISTER_ERROR3 : "Napaka pri pošiljanju podatkov v bazo!",
		REGISTER_INFO1 : "Vaš račun je uspešno ustvarjen.",
		REGISTER_INFO2 : "Po elektronski pošti smo vam poslali podatke za aktivacijo računa. Prosimo preverite vašo elektronsko pošto.",
		REGISTER_INFO3 : "Vaš račun je potrjen. Administrator ga mora še aktivirati!",
		REGISTER_BUTTON : "Nazaj na začetno stran",
		REGISTER_NEW_SUBJECT : "Nov uporabnik registriran na galaxytoolu",
		REGISTER_NEW_MAILTEXT : "Nov uporabnik se je registriral.",
		REGISTER_BACK : "Nazaj na prvo stran",
		REGISTER_MISSING_FIELDS : "Prosimo izpolnite vsa potrebna polja.",
		REGISTER_ERROR4 : "Email naslov ni veljaven.",
		REGISTER_ERROR5 : "Gesli se ne ujemata.",
		REGISTER_PWS : "Moč gesla",
		REGISTER_PWS0 : "zelo slabo",
		REGISTER_PWS1 : "slabo",
		REGISTER_PWS2 : "dobro",
		REGISTER_PWS3 : "močno",
		REGISTER_PWS4 : "zelo močno",
		REGISTER_EMAIL_USED : "Email naslov je že v uporabi",
		LOSTPW_TITLE : "Geslo pozabljeno",
		LOSTPW_INFO2 : "Novo geslo je obnovljeno in poslano na vaš mail!",
		LOSTPW_BUTTON1 : "naredi novo geslo",
		LOSTPW_BUTTON2 : "Nazaj na začetno stran",
		LOSTPW_LOGINNAME : "Uporabniško Ime",
		LOSTPW_EMAIL : "Email",
		LOSTPW_ERROR1 : "Napaka pri pošiljanju podatkov v bazo!",
		LOSTPW_ERROR2 : "Napačno vnešeni podatki!",
		LOSTPW_ERROR3 : "Napaka pri pošiljanju Emaila! Prosimo vas da kontaktirate administratorja",
		LOSTPW_EMAIL_SUBJECT : "Vaše novo geslo ki ste ga zahtevali",
		LOSTPW_EMAIL_TEXT1 : "Vaš novi login za Galaxytool",
		LOSTPW_EMAIL_TEXT2 : "Uporabniško Ime",
		LOSTPW_EMAIL_TEXT3 : "Geslo",
		LOSTPW_INFO1 : "Prejeli boste Email, da potrdite zahtevek novega gesla",
		LOSTPW_CONFIRM_RESET_SUBJECT : "Pozabljeno geslo?",
		LOSTPW_CONFIRM_RESET_MESSAGE : "Pozdravljeni,\n\nyou je zahteval ponastavitev gesla za Galaxytool. Za generacijo novega gesla, kliknite na naslednjo povezavo:",
		USERINFO_TITLE : "OGame Galaxietool - Informacije o uporabniku",
		USERINFO_NAMES : "Vsi uporabniki",
		USERINFO_DETAIL : "podrobne informacije o",
		USERINFO_ERROR1 : "Ni uporabnika z takim ID!",
		USERINFO_USERNAME : "Uporabniško Ime",
		USERINFO_INGAME : "Ime v igri",
		USERINFO_EMAIL : "Email",
		USERINFO_ALLYTAG : "Aliansa",
		USERINFO_STYLEPATH : "Skin",
		USERINFO_STATUS : "Status",
		USERINFO_ACTIVATE : "Aktiviraj igralca",
		USERINFO_LOGINS : "Število prijav",
		USERINFO_LASTLOGIN : "Zadnja prijava",
		USERINFO_DATA : "Informacije o sistemu , ki jih je vnesel uporabnik",
		USERINFO_NODATA : "Ta uporabnik ni vnesel še noben sistem",
		USERINFO_GALAXY : "Galaksija",
		USERINFO_SYSTEMS : "Število sistemov",
		USERINFO_IP : "IP naslov",
		USERINFO_LOGINTIME : "Prijava",
		USERINFO_NOLOGIN : "Ta uporabnik se do sedaj še ni prijavil",
		USERINFO_LAST_GALAXYUPDATE : "Zadnji vnos v izgled galaksije",
		USERINFO_LAST_PUBLIC_NOTICE : "Zadnja javna objava",
		USERINFO_LAST_PRIVATE_NOTICE : "Zadnja privatna objava",
		USERINFO_NUMBEROF_PUBLIC_NOTICE : "Število javnih objav",
		USERINFO_NUMBEROF_PRIVATE_NOTICE : "Število privatnih objav",
		USERINFO_ACTIVATED : "Uporabni račun aktiviran",
		USERINFO_ACTIVATIONTEXT : "Galaxytool administrator je aktiviral vaš uporabni račun. Uživajte u Galaxytool-u!",
		USERINFO_LAST_SUBMIT : "Nazadnje vnešeni podatki",
		ALLYHISTORY_TITLE : "OGame Galaxytool - Grafi",
		ALLYHISTORY_TBLHEAD : "Grafi",
		ALLYHISTORY_PLAYERNAME : "Igralec",
		ALLYHISTORY_ALLYNAME : "Aliansa",
		ALLYHISTORY_LASTMONTH : "Prejšnji mesec",
		ALLYHISTORY_ALL_DATA : "vse dostopne informacije",
		ALLYHISTORY_SHOW : "prikaži statistiko",
		ALLYHISTORY_TIMESPAN : "Časovni interval",
		ALLYHISTORY_PROGESS : "Napredek",
		ALLYHISTORY_SCORE : "Točke",
		ALLYHISTORY_FSCORE : "Točke flote",
		ALLYHISTORY_RSCORE : "Točke raziskav",
		ALLYHISTORY_MEMBER : "Člani",
		ALLYHISTORY_NOTHING : "nič ni najdeno",
		ALLYHISTORY_DETAILS : "Podrobno",
		ALLYHISTORY_SHOW_ADDRESS : "Koordinati",
		ALLYHISTORY_ESCORE : "Ekonomija",
		ALLYHISTORY_MSCORE : "Vojaške točke",
		DETAILEDINFO_PLAYERINFO_TITLE : "Informacija o igralcu",
		DETAILEDINFO_ALLYINFO_TITLE : "Informacije o aliansi",
		DETAILEDINFO_PLAYERINFO_TBLHEAD : "Natančne informacije o igralcu",
		DETAILEDINFO_ALLYINFO_TBLHEAD : "Natančne informacije o aliansi",
		DETAILEDINFO_NO_ALLIANCE : "nič",
		DETAILEDINFO_SCORE : "Točke",
		DETAILEDINFO_FLEET : "Flota",
		DETAILEDINFO_RESEARCH : "Laboratorij",
		DETAILEDINFO_RANK : "Pozicija",
		DETAILEDINFO_POINTS : "Točke",
		DETAILEDINFO_KNOWN_PLANETS : "znani planeti",
		DETAILEDINFO_MOONS : "znane lune",
		DETAILEDINFO_PHALANX_AREA : "Področje za Falangiranje",
		DETAILEDINFO_NO_PHALANX_AREA : "Igralec nima falange",
		DETAILEDINFO_NOTICES : "Opombe",
		DETAILEDINFO_NO_NOTICES : "Ni opomb",
		DETAILEDINFO_PREVIOUS_ALLIANCES : "prejšnje alianse",
		DETAILEDINFO_RESOURCES_PER_HOUR : "Produkcija na uro",
		DETAILEDINFO_RESOURCES_PER_DAY : "Produkcija na dan",
		DETAILEDINFO_RESOURCES_PER_WEEK : "Produkcija na teden",
		DETAILEDINFO_RESOURCES_PER_MONTH : "Produkcija na mesec (30 dni)",
		DETAILEDINFO_METAL : "Metal",
		DETAILEDINFO_CRYSTAL : "Kristal",
		DETAILEDINFO_DEUTERIUM : "Deuterij",
		DETAILEDINFO_UNKNOWN : "nepoznano",
		DETAILEDINFO_SCORE_DISTRIBUTION : "Razporeditev točk",
		DETAILEDINFO_GENERAL : "Podrobnosti",
		DETAILEDINFO_MEMBERS : "Član",
		DETAILEDINFO_GRAPHS : "Graf",
		DETAILEDINFO_RESOURCES : "Surovine",
		DETAILEDINFO_FLEET_TAB : "Flota",
		DETAILEDINFO_TECH : "Laboratorij",
		DETAILEDINFO_FLEET_DETAIL : "Sum / (povprečno) število iz vseh poročil ki so na voljo",
		DETAILEDINFO_TECH_DETAIL : "Povprečje od vseh informacij igralca ki so na voljo",
		DETAILEDINFO_PLANET_TAB : "Planeti",
		DETAILEDINFO_MOON_TAB : "Lune",
		DETAILEDINFO_ACTIVITIES : "Aktivnost",
		DETAILEDINFO_NODATA : "Podatki niso dostopni.",
		DETAILEDINFO_ACTIVITY_DESCRIPTION : "Pokaži aktivnost od &1 od:",
		DETAILEDINFO_GALAXYVIEWS : "Iz pogleda galaksije",
		DETAILEDINFO_SCANS : "Iz vohunskih poročil",
		DETAILEDINFO_MESSAGES : "Iz sporočil igralca",
		DETAILEDINFO_COMBATS : "Iz poročil bitk",
		DETAILEDINFO_ALLYPAGE : "Pregled Alianse",
		DETAILEDINFO_MANUAL : "Ročno vnešeno",
		DETAILEDINFO_START : "Začetek",
		DETAILEDINFO_TO : "za",
		DETAILEDINFO_TODAY : "Danes",
		DETAILEDINFO_DATA_RESTRICTION : "Omejeno na:",
		DETAILEDINFO_WEEKDAY_WEEKEND : "Vikend",
		DETAILEDINFO_WEEKDAY_WORKINGDAY : "Delavnik",
		DETAILEDINFO_WEEKDAY_MONDAY : "Ponedeljek",
		DETAILEDINFO_WEEKDAY_TUESDAY : "Torek",
		DETAILEDINFO_WEEKDAY_WEDNESDAY : "Sreda",
		DETAILEDINFO_WEEKDAY_THURSDAY : "Četrtek",
		DETAILEDINFO_WEEKDAY_FRIDAY : "Petek",
		DETAILEDINFO_WEEKDAY_SATURDAY : "Sobota",
		DETAILEDINFO_WEEKDAY_SUNDAY : "Nedelja",
		DETAILEDINFO_WEEKDAY_SHORTLENGTH : 3,
		DETAILEDINFO_PLAYER_CURRENTLY_ACTIVE : "Igralec je trenutno aktiven",
		DETAILEDINFO_PLAYER_MESSAGES : "vnešena sporočila igralca",
		DETAILEDINFO_SHOW : "pokaži",
		DETAILEDINFO_NONE : "ni vnosa",
		DETAILEDINFO_ENTER_MANUALLY : "Vstavi aktivnost tega igralca",
		DETAILEDINFO_PLAYER_SEEN_ON : "Igralec je bil online",
		DETAILEDINFO_INSERT : "Vstavi",
		DETAILEDINFO_OGAME_SERVERTIMES : "Opozorilo: Vsi datumi in časi se nanašajo na čas OGame strežnika!",
		DETAILEDINFO_DAY_VIEW : "pogled 24 ur",
		DETAILEDINFO_WEEK_VIEW : "pogled tedna",
		DETAILEDINFO_HOME_PLANET : "Glavni planet",
		DETAILEDINFO_PLANETNAME : "Ime",
		DETAILEDINFO_DEFENCE_SCORE : "Toče obrambe",
		DETAILEDINFO_DEFENCE_SCORE_TOOLTIP : "Točke obrambe = Flota - Skupne točke + Raziskovanja + Ekonomija.<br/>Vsa statistika mora biti posodobljena za pravilne rezultate!",
		DETAILEDINFO_SCORE_PER_SHIP : "Točke na ladjo",
		DETAILEDINFO_SHIPS : "Število flote",
		DETAILEDINFO_DATE_IN_FUTURE : "Do not maintain times which are not in the past.",
		ADMIN_TITLE : "Administracija GalaxyToola",
		ADMIN_DISCLAMER : "Opozorilo: Zaganjanje teh skript je na lastno odgovornost! Večina od njih brišejo podatke.",
		ADMIN_INCONSISTENCIES : "Napake v bazi",
		ADMIN_PLANETS : "Planete na poziciji 0 ali več kot 15",
		ADMIN_GALAXIES : "Izbriši galaksije naprej od &1 ",
		ADMIN_PLAYERS : "Izbriši igralce brez OGame playerid - Vodi do podvojenih igralcev",
		ADMIN_REPORTS : "Izbriši poročila kjer ni več planetov",
		ADMIN_MISC : "Drugo",
		ADMIN_RESET : "Reset Galaxytool (le uporabniki in IP zapisi nebojo izbrisani)",
		ADMIN_OLD_PLAYERS : "Izbriši vnose igralcev stare več kot &1 dni",
		ADMIN_OLD_REPORTS : "Izbriši poročila starejša od &1 dni",
		ADMIN_LOADING : "Ne zapirajte tega okna dokler se stran nalaga.",
		ADMIN_STATUS : "Status od vaših zahtev",
		ADMIN_SELECTION : "Vsaj en vnos mora biti izbran",
		ADMIN_SAFETY : "Ali ste prepričani da želite izvršiti skripte(s) ?",
		ADMIN_DONE : "končano",
		ADMIN_NOTBD : "Nič ni za izvršiti",
		ADMIN_OLD_GALAXIES : "Izbriši sisteme, ki so starejše od &1 dni",
		ADMIN_UNUSED_PLAYERS : "Izbriši igralce, ki ne obstajajo v pogledu galaksije",
		ADMIN_OLD_ACTIVITIES : "Izbriši aktivnosti igralcev ki so starejše od &1 dni",
		ADMIN_OLD_COMBATS : "Odstrani poročila bitk starejše od &1 dni",
		ADMIN_OLD_INGAME_MSG : "Izbriši sporočila starejše od &1 dni",
		ADMIN_OGAME_API : "Naloži javne podatke iz OGame v Galaxytool",
		ADMIN_OGAME_ALL_DATA : "vse dostopne informacije",
		ADMIN_OGAME_GALAXY_DATA : "Pregled Galaksije",
		ADMIN_OGAME_STATISTICS_DATA : "Statistike",
		ERRORPAGE_PAGEFORWARD : "Kliknite tukaj, če vaš brskalnik ne podpira  samodejnega usmerjenja",
		ERRORPAGE_PERMISSION_DENIED : "Nimate dovoljenj za vstop na to stran. Kliknite za nazaj.",
		FLEETS_TITLE : "Premiki flot",
		FLEETS_ACTUAL_FLEETS : "Trenutni premiki flot",
		FLEETS_YES : "Da",
		FLEETS_NO : "Samo planeti z opombo",
		FLEETS_DETAILS : "Podrobnosti",
		FLEETS_MISSION_EXPEDITION : "Ekspedicija",
		FLEETS_MISSION_COLONIZATION : "Koloniziraj",
		FLEETS_MISSION_RECYCLE : "Recikliraj",
		FLEETS_MISSION_TRANSPORT : "Transport",
		FLEETS_MISSION_DEPLOYMENT : "Premik",
		FLEETS_MISSION_ESPIONAGE : "Vohuni",
		FLEETS_MISSION_ACS_DEFEND : "ACS Obramba",
		FLEETS_MISSION_ATTACK : "Napad",
		FLEETS_MISSION_ACS_ATTACK : "ACS Napad",
		FLEETS_MISSION_MOON_DESTRUCTION : "Uničenje lune",
		FLEETS_MISSION_MISSILE_ATTACK : "Raketni napad",
		FLEETS_NO_DATA : "Noben uporaben podatek ni najden",
		FLEETS_FLEET : "Flota",
		FLEETS_ALL_FLEETS : "Pokaži vse premike flot",
		COMBAT_REPORT_OUDATED_GALAXYVIEW : "Baza GalaxyTool-a je zastarela. Prosimo ponovno pojdite čez galaksijo!",
		MESSAGES_TITLE : "OGame Galaxytool - OGame Sporočila",
		MESSAGES_PLAYERNAME : "Igralec",
		MESSAGES_SUBJECT : "Zadeva",
		MESSAGES_DATE : "Datum",
		MESSAGES_FILTER : "Filter",
		MESSAGES_DELETE : "Izbriši sporočilo",
		MESSAGES_PUBLISH_DETAIL : "Objavi vsebino sporočila, ki bo veljal kot opomba igralca.",
		MESSAGES_PUBLISH_HEADER : "&sender Poslano &recipient na &date:\n\n &message",
		MESSAGES_PLAYER_FILTER : "Sporočila za igralca:",
		MESSAGES_CONTENT : "Vsebina",
		COMBATS_TITLE : "OGame Galaxytool - Poročila bitk",
		COMBATS_ATTACKER : "Napadalec",
		COMBATS_DEFENDER : "Branilec",
		COMBATS_DATE : "Datum",
		COMBATS_OWNER : "Lastnik",
		COMBATS_WINNER : "Zmagovalec",
		COMBATS_COMBATREPORT : "Poročilo bitke",
		COMBATS_COMBAT_AT : "Bitka na",
		COMBATS_LOST_UNITS : "Izgubljene enote",
		COMBATS_LOOT : "Plen",
		COMBATS_DEBRIS : "Ruševine",
		COMBATS_AND : "in",
		COMBATS_PUBLISH : "Označi kot javno",
		COMBATS_UNPUBLISH : "Označi kot zasebno (skrije sporočilo pred drugim)",
		COMBATS_DELETE : "Izbriši bitko",
		COMBATS_CHECK_ALL : "Izberi vse",
		COMBATS_UNCHECK_ALL : "Izberi nič",
		COMBATS_WITH_SELECTED : "Označi",
		COMBATS_PUBLIC_REPORTS : "Javna poročila",
		COMBATS_YES : "Da",
		COMBATS_NO : "Samo planeti z opombo",
		COMBATS_SEARCH_OPTIONS : "Možnosti iskanja",
		COMBATS_SEARCH : "Pojdi",
		COMBATS_RESET : "Reset",
		COMBATS_COORDINATES : "Koordinate",
		COMBATS_INVALID_GALAXY_ENTERED : "Neveljavna galaksija",
		COMBATS_INVALID_SYSTEM_ENTERED : "Neveljavni sistem",
		COMBATS_INVALID_PLANET_ENTERED : "Neveljavni planet",
		COMBATS_GALAXY_FROM_TO : "Galaksija",
		COMBATS_SYSTEM_FROM_TO : "Sistem",
		COMBATS_PLANET_FROM_TO : "Planet",
		COMBATS_APPLY : "Uporabi",
		COMBATS_COMBAT_SUMMARY : "Povzetek poročila bitke",
		COMBATS_DOWNLOAD_CSV : "Shrani kot CSV datoteko",
		REPORT_ARCHIVE_TITLE : "Arhiv poročil",
		REPORT_ARCHIVE_COORDINATES : "Koordinati",
		REPORT_ARCHIVE_SCANTIME : "Čas vohunjenja",
		REPORT_ARCHIVE_DELETE : "Izbriši vnose",
		REPORT_ARCHIVE_CONFIRM_DELETE : "Si res želite izbrisati vnose?",
		REPORT_ARCHIVE_GALAXY : "Galaksija",
		REPORT_ARCHIVE_SYSTEM : "Sistem",
		REPORT_ARCHIVE_PLANET : "Planet",
		REPORT_ARCHIVE_MOON : "Luna",
		REPORT_ARCHIVE_DETAILS : "Podrobnosti",
		REPORT_ARCHIVE_RESOURCES : "Produkcija na uro",
		REPORT_ARCHIVE_HEADER_RESOURCES : "Surovine",
		REPORT_ARCHIVE_DETAILS_FOR : "Arhiv poročil za &1 [&2] (&3)",
		REPORT_ARCHIVE_FLEET_CARGO : "Prostor na floti",
		REPORT_ARCHIVE_IRAK_RANGE : "Doseg medplanetarnih planet",
		REPORT_ARCHIVE_CHART_TYPE : "Vrsta grafa",
		INSTALL_TITLE : "Galaxytool namestitev za verzijo",
		INSTALL_PROGRESS : "Napredek",
		INSTALL_STEP : "Korak",
		INSTALL_CONTINUE : "Nadaljuj",
		INSTALL_VALIDATE : "Potrditev",
		INSTALL_STEP1 : "Dobrodošli",
		INSTALL_STEP2 : "Writeable check",
		INSTALL_STEP3 : "Database settings",
		INSTALL_STEP4 : "OGame settings",
		INSTALL_STEP5 : "Galaxytool settings",
		INSTALL_STEP6 : "Admin password",
		INSTALL_STEP7 : "Install Galaxytool",
		INSTALL_STEP8 : "Zaključi namestitev",
		INSTALL_FILE_DELETE_CHECK : "Prosimo, izbrišite datoteki install.php in update.php z strežnika.",
		INSTALL_STEP1_PHP_FAILED : "Your PHP version &1 is not working with this Galaxytool version",
		INSTALL_STEP1_FOPEN_FAILED : "Your PHP version does not allow to open webpages with FOPEN() command. This is required to consume the OGame API.",
		INSTALL_STEP1_WELCOME : "Dobrodošli v namestitev Galaxytool-a. Vodeni boste po namestitvi Galaxytool-a.",
		INSTALL_STEP2_DESCRIPTION : "Prepričajte se da imata datoteki config.php in attributes.php pravico do pisanja.",
		INSTALL_STEP2_DESCRIPTION2 : "Če neveste kako priti do tega, prosimo poglejte tukaj: &1",
		INSTALL_STEP2_FILE_NOT_WRITEABLE : "Datoteka ni pisljiva",
		INSTALL_STEP3_SERVER : "Database server",
		INSTALL_STEP3_USERNAME : "Uporabniško ime",
		INSTALL_STEP3_PASSWORD : "Geslo",
		INSTALL_STEP3_DBNAME : "Database name",
		INSTALL_STEP3_PREFIX : "Tablename prefix",
		INSTALL_STEP3_ENTER_PREFIX : "E.g. mytool_",
		INSTALL_STEP3_ENTER_SERVER : "Enter the server address. Contact your system admin if necessary. Usually the correct value is localhost.",
		INSTALL_STEP3_ENTER_USERNAME : "Enter the username for database access",
		INSTALL_STEP3_ENTER_PASSWORD : "Enter the password for database access",
		INSTALL_STEP3_ENTER_DBNAME : "Enter the database name which shall be used for installation (must exist)",
		INSTALL_STEP3_CONNECT_FAILED : "Could not establish connection to database server",
		INSTALL_STEP3_DB_FAILED : "Database &1 not found",
		INSTALL_STEP3_MYSQL_VERSION_FAILED : "MySQL version &1 is not working with this Galaxytool version",
		INSTALL_STEP4_URL : "OGame URL",
		OGAME_URL_DETAILS : "Please enter any URL you see when you are logged on to OGame. Based on that URL the tool will derive the OGame API address which can be used to fill data into the Galaxytool without the Galaxytoolbar. This API was introduced with OGame version 4.1.",
		INSTALL_STEP4_UNIVERSE : "OGame Universe",
		INSTALL_STEP4_DEF_TO_DEBRIS : "Defense to debris",
		INSTALL_STEP4_DEBRIS_RATE : "Debris rate",
		INSTALL_STEP4_SPEED_RATE : "Speed rate",
		INSTALL_STEP4_ENTER_UNIVERSE : "Enter your OGame universe name or number (case sensitive).",
		INSTALL_STEP4_UNIVERSE_MISSING : "You must define your universe",
		INSTALL_STEP4_ENTER_URL : "Enter your OGame universe address",
		INSTALL_STEP4_URL_MISSING : "You must define your OGame address",
		INSTALL_STEP4_URL_CHECK_FAILED : "Could not find OGame API at &1",
		INSTALL_STEP4_GETSETTINGS : "Fetch settings",
		INSTALL_STEP5_TOOLNAME : "Ime Galaxytool-a",
		INSTALL_STEP5_ENTER_TOOLNAME : "To ime bo vidno na prijavni strani Galaxytool, kot identifikacija",
		INSTALL_STEP5_LANGUAGE : "Prevzeti jezik",
		INSTALL_STEP5_EMAIL_TO : "Email To",
		INSTALL_STEP5_ENTER_EMAIL_TO : "Vnesite Email naslov, kjer želite prejemati sporočila o novih registracijah",
		INSTALL_STEP5_EMAIL_FROM : "Email From",
		INSTALL_STEP5_ENTER_EMAIL_FROM : "This email address is shown as REPLY for all mails sent from the Galaxytool",
		INSTALL_STEP5_USE_PHPMAILER : "Use PHPMailer",
		INSTALL_STEP5_MAXSHOUTS : "Maximum number of shoutbox entries",
		INSTALL_STEP5_ENTER_USE_PHPMAILER : "Use PHPMailer if your server does not support sending emails by default",
		INSTALL_PHPMAILER_HOST : "SMPT Host",
		INSTALL_PHPMAILER_HOST_EXAMPLE : "e.g. smtp.provider.com",
		INSTALL_PHPMAILER_USER : "SMPT Username",
		INSTALL_PHPMAILER_USER_EXAMPLE : "e.g. user@provider.dcom",
		INSTALL_PHPMAILER_PASS : "SMPT password",
		INSTALL_PHPMAILER_SECURE : "Authentification method (e.g. ssl)",
		INSTALL_PHPMAILER_PORT : "SMTP Port",
		INSTALL_STEP6_INTRO : "Prosimo, izberite geslo za <strong>admin</strong> račun, katerega potrebujete za prvo prijavo v Galaxytool po namestitvi.",
		INSTALL_STEP7_CONFIG : "Configuration file created",
		INSTALL_STEP7_CONFIG_FAILED : "Configuration file not created",
		INSTALL_STEP7_ATTRIBUTES : "Attributes file created",
		INSTALL_STEP7_ATTRIBUTES_FAILED : "Attributes file not created",
		INSTALL_STEP7_CREATED_TABLES : "Database tables created",
		INSTALL_STEP8_INTRO : "You have successfully installed the Galaxytool!",
		INSTALL_STEP8_LOAD_DATA : "Downloading OGame data ...",
		INSTALL_STEP8_LOAD_DATA_FINISHED : "Download of OGame data finished",
		INSTALL_STEP8_DELETE_FILE : "Sedaj izbrišite datoteki install.php in update.php z strežnika.",
		INSTALL_STEP8_LOGON : "Prosimo, prijavite se z <strong>admin</strong> računom in izbranim geslom",
		UPDATE_START : "Starting update to version &1",
		UPDATE_STEP_DONE : "Done",
		UPDATE_TITLE : "Galaxytool update for version",
		UPDATE_STEP1_WELCOME : "Welcome to the update wizard of the Galaxytool. You will be guided through the update of the Galaxytool.",
		UPDATE_STEP1_BACKUP_FILES : "As a first step, make a backup of your <strong>config</strong> folder! You will have to replace the configuration content in case of errors.",
		UPDATE_STEP1_BACKUP_DB : "Then make a <a href=\"http://www.ehow.com/how_2036600_create-database-php.html\">backup</a> of your database.",
		UPDATE_STEP1_PROCEED : "Once the backups have been done, you can proceed with your update.",
		UPDATE_STEP1 : "Dobrodošli",
		UPDATE_STEP2 : "Galaxytool settings",
		UPDATE_STEP2_OLD_VERSION : "Previous Galaxytool version",
		UPDATE_STEP3 : "Update Galaxytool",
		UPDATE_STEP3_UPDATE_RUNNING : "Update running, please wait...",
		UPDATE_STEP4 : "Finalize Update",
		UPDATE_STEP4_INTRO : "You have successfully updated the Galaxytool!",
		UPDATE_STEP4_UPDATE_DONE : "Update steps performed.",
		UPDATE_FAILED : "Update failed.",
		GALAXYTOOL_DUMMY_TEXT : "dummy"
	})
);