define(
	({
		REPORT_WHEN : "在",
		RESOURCES_ON : "資源在",
		PLAYER_BANNED : "b",
		PLAYER_VACATION_MODE : "v",
		PLAYER_NOOB : "n",
		PLAYER_INACTIVE : "i",
		PLAYER_LONG_INACTIVE : "I",
		PLAYER_OUTLAW : "o",
		L_USERNAME : "帳號",
		L_PASSWORD : "密碼",
		L_LOGINFAILURE : "帳號或密碼錯誤，或者你的帳號沒有啟動。",
		L_TOKENFAILURE : "Your logon key is wrong or your account is not activated yet.",
		L_LOGINTEXT : "請登入。",
		L_LANGUAGE : "允許的語言：",
		L_TIMEOUT : "等待時間過久！",
		L_REGISTER : "註冊",
		L_PWLOST : "密碼遺失",
		INDEX_TITLE : "OGame Galaxietool - 總覽",
		INDEX_INFO : "資料庫資訊",
		INDEX_ENTRIES : "太陽系數目",
		INDEX_ENTRIES_LASTWEEK : "最近一週更新的太陽系",
		INDEX_ENTRIES_TO_OLD : "一個月前更新的太陽系",
		INDEX_REGISTERED_USERS : "註冊的使用者數目",
		INDEX_PAGEFORWARD : "如果你的瀏覽器無法自動進入下一頁, 請按這裡！",
		INDEX_NOTICES : "訊息數目",
		INDEX_PLAYERS : "玩家數目",
		INDEX_ALLIES : "聯盟數目",
		INDEX_REPORTS : "間諜報告數目",
		INDEX_VERSION : "下載最新的版本！",
		INDEX_LATEST_VERSION : "你使用的已是最新版本！",
		INDEX_SHOUTBOX : "留言簿",
		INDEX_NOENTRY : "沒有留言！",
		INDEX_COMMENT : "輸入你的留言",
		INDEX_INSERT : "送出",
		INDEX_UMOD : "假期模式中的玩家",
		INDEX_NO_MOONS : "月球的數目",
		INDEX_NO_EMPTY_SYSTEMS : "空太陽系的數目",
		INDEX_NO_FULL_SYSTEMS : "滿太陽系的數目",
		INDEX_NO_TARGETS : "可以被攻擊的星球",
		INDEX_USERINFO : "使用者人數",
		INDEX_ONLINE : "線上人數",
		INDEX_TODAY : "今天登入的使用者",
		INDEX_ALL : "總登入次數",
		GENERAL_LOAD_FORM : "載入數據",
		GENERAL_SAVE_FORM : "保存數據",
		GENERAL_SAVE_AS_TEXT : "保存為",
		GENERAL_SAVE : "保存",
		INDEX_USERMANAGEMENT : "Activation Overview",
		INDEX_NEEDADMIN : "Accounts to unlock",
		INDEX_NEEDEMAIL : "Unvalidated Accounts",
		INDEX_TOOLBAR_INFO : "Galaxytool plugin information",
		INDEX_TOOLBAR_URL : "Galaxytool URL",
		INDEX_TOOLBAR_VERSION_REQUIRED : "Requires at least Galaxytool plugin version",
		INDEX_TOOLBAR_INSTALL_GUIDE : "Installation instructions for plugin",
		INDEX_TOOLBAR_TOKEN : "Logon key",
		INDEX_TOOLBAR_NEW_TOKEN : "Get new key",
		INDEX_PLAYERS_WITH_N_PLANETS : "Players with more than &1 planets",
		INDEX_GETTING_STARTED : "Getting started with the Galaxytool",
		INDEX_GETTING_STARTED1 : "Welcome to the Galaxytool!",
		INDEX_GETTING_STARTED2 : "The Galaxytool will help you to analyze what is going on in your OGame universe &1",
		INDEX_GETTING_STARTED3 : "Before you can actually analyze data you have to insert it first. For this you require a browser plugin like the &1 for Firefox.",
		INDEX_GETTING_STARTED4 : "After you installed the plugin, you navigate through your OGame pages as usual and you will see a small status window whenever something was sent to your Galaxytool.",
		INDEX_GETTING_STARTED5 : "Once the plugin inserted data into the Galaxytool, you can start to analyze where the players have their colonies, how many colonies they have, what reports exist or when they are active the most.",
		INDEX_GETTING_STARTED6 : "But it will also help you to analyze how you are progressing if you compare yourself against your competitors or by analyzing your combat reports to see how much you raided during the last days or weeks.",
		INDEX_GETTING_WIKIPAGE : "There are many more features within the Galaxytool.",
		INDEX_GETTING_WIKIPAGE2 : "Check them out at our wiki page.",
		INDEX_GETTING_BOARD : "For feedback or ideas you can use our board:",
		INDEX_GETTING_CHAT1 : "Or visit us at the chatroom:",
		INDEX_GETTING_CHAT2 : "We are not online 24/7 but spare a lot of our free time there, so be patient.",
		INDEX_CLOSE : "Close",
		INDEX_LOGIN : "Login",
		GENERAL_REQUIRED_FIELDS : "Please fill all required fields",
		INDEX_MESSAGES : "Messages",
		INDEX_EXAMPLE : "Example",
		INDEX_INVALID_DATA : "Invalid data",
		GENERAL_COLUMN_HIDE_TITLE : "Manage columns",
		GENERAL_COLUMN_HIDE_INFO : "Please select which columns you want to see in the table.",
		GENERAL_ENTRIES_DELETED : "&1 entries deleted",
		GENERAL_APPLY : "Apply",
		STARTPAGE_GALAXYTOOL_DESCR : "<em>Galaxytool</em> is a tool for the browser game OGame.",
		GENERAL_OVERWRITE : "Overwrite duplicate entry",
		GENERAL_OVERWRITE_QUESTION : "Overwrite?",
		INDEX_OWN_LOGINS : "Your logins",
		GENERAL_OPEN_IN_NEW_WINDOW : "用新視窗開啟鏈結",
		GENERAL_UNIT_OF_MEASURE_DAYS : "Days",
		PROGRAM_NAME : "OGame Galaxytool",
		SHORTNAME : "Galaxytool",
		BACK_INDEX : "回到首頁",
		UNIVERSE : "宇宙",
		MENU_INFO_LINKS : "資料",
		MENU_PAGE : "總覽",
		MENU_DB_SEARCH : "搜尋玩家或聯盟",
		MENU_DB_NOTICES : "搜尋訊息",
		MENU_DB_REPORTS : "搜尋間諜報告",
		MENU_GALAXYVIEW : "查看星系",
		MENU_STATISTICS : "統計",
		MENU_ALLYHISTORY : "歷史統計",
		MENU_FLEET_MOVEMENTS : "移動中艦隊",
		MENU_COMBAT_REPORTS : "戰鬥報告",
		MENU_MESSAGES : "遊戲訊息",
		MENU_OPTION_LINKS : "選項",
		MENU_DB_REFRESH : "匯入資料",
		MENU_NOTICES : "訊息",
		MENU_DB_STATUS : "資料庫狀況",
		MENU_USEROPTIONS : "管理使用者",
		MENU_USEROPTIONS2 : "使用者資料",
		MENU_USEROPTIONS3 : "帳號管理",
		MENU_ADMIN : "管理維護",
		MENU_LOGOUT : "登出",
		MENU_STUFF : "雜項",
		MENU_FORUM_THREAD : "GalaxyTool開發論譠",
		MENU_DOWNLOADPAGE : "下載點",
		MENU_LANGUAGE : "語言",
		MENU_HELP : "求助",
		MENU_TOOLOPTIONS : "Galaxytool 設置",
		PARSER_INFO1 : " 被匯入資料庫",
		PARSER_ERROR1 : "試圖匯入以下坐標時產生錯誤:",
		PARSER_ERROR2 : "無法找到資料庫！",
		PARSER_ERROR3 : "無法找到資料庫伺服器！",
		PARSER_WRONG_UNIVERSE : "Wrong universe - actual: \"&1\"  expected: \"&2\"",
		SHOW_TITLE : "OGame Galaxytool - Searchpage",
		SHOW_SEARCH : "搜尋玩家或聯盟",
		SHOW_ALLYSYMBOL : "聯盟",
		SHOW_PLAYERNAME : "玩家",
		SHOW_MOONS : "有月球的星球",
		SHOW_NOTICES : "有訊息的星球",
		SHOW_COLONIES : "依星球位置",
		SHOW_YES : "是",
		SHOW_NO : "否",
		SHOW_SEARCHRANGE : "範圍",
		SHOW_SEARCH_IN : "搜尋銀河系(1~9)",
		SHOW_FROM_SYSTEM : "從太陽系(1~499)",
		SHOW_FROM_PLANET : "從星球(1~15)",
		SHOW_TO : "到",
		SHOW_DESCRIPTION : "你可以在聯盟或玩家欄使用萬用字元&quot;*&quot;. 如此，你可以找到所有名字相似的玩家！<br />請僅填寫你想指定的區域.",
		SHOW_SORT_BY : "排列標準",
		SHOW_GALASYSTEM : "銀河系/太陽系",
		SHOW_ALLYNAME : "聯盟名",
		SHOW_SEARCHBUTTON : "開始搜尋",
		SHOW_ADDRESS : "位置",
		SHOW_ALLYSORT : "聯盟",
		SHOW_PLANET : "星球名",
		SHOW_STATUS : "狀況",
		SHOW_CURRENTNESS : "更新時間",
		SHOW_PLAYER_STATUS : "玩家狀況",
		SHOW_PLAYER_STATUS1 : "全部",
		SHOW_PLAYER_STATUS2 : "可被攻擊的",
		SHOW_PLAYER_STATUS3 : "Ｉ羊",
		SHOW_HITS : "第",
		SHOW_OF : "of",
		SHOW_ASC : "升冪排列",
		SHOW_DESC : "降冪排列",
		SHOW_RESULTS : "一頁顯示幾筆資料",
		SHOW_MOON : "月球",
		SHOW_UKMOONSIZE : "大小未知",
		SHOW_DF : "殘骸",
		SHOW_DF_LONG : "殘骸",
		SHOW_METAL : "金屬",
		SHOW_METAL_LONG : "金屬",
		SHOW_CRYSTAL : "晶",
		SHOW_CRYSTAL_LONG : "晶體",
		SHOW_BOTH : "兩者一起",
		SHOW_AT_LEAST : "(至少)",
		SHOW_DATE : "日期",
		SHOW_DATE_0 : "不介意",
		SHOW_DATE_1 : "之後",
		SHOW_DATE_2 : "之前",
		SHOW_RANK : "排名",
		SHOW_FRANK : "艦隊數排名",
		SHOW_MEMBERS : "盟員",
		SHOW_NOTRANKED : "不在前1500名內！.",
		SHOW_NOTICERES : "訊息",
		SHOW_REPORTS : "有間諜報告的星球",
		SHOW_REPORTS_SHORT : "間諜報告",
		SHOW_NOTHING : "沒有找到資料",
		SHOW_ALLIANCE_STATUS : "聯盟關係",
		SHOW_NO_STATUS : "無關係",
		SHOW_NAP : "互不侵犯",
		SHOW_ALLIED : "結盟",
		SHOW_WAR : "宣戰",
		SHOW_BOYCOTT : "抵制",
		SHOW_NEUTRAL : "中立",
		SHOW_OWN : "所在聯盟",
		SHOW_WING : "子盟",
		SHOW_EXT_OPTIONS1 : "顯示更多的搜尋選項（範圍、排名、日期或殘骸）",
		SHOW_EXT_OPTIONS2 : "顯示更多的搜尋選項（位置、月球、間諜報告、訊息、玩家狀況或外交狀況）",
		SHOW_EXT_OPTIONS3 : "顯示更多的搜尋選項（排列規則）",
		SHOW_EXTENDED : "advanced search",
		SHOW_MOON_SELECTION : "Planet with moon",
		SHOW_REPORT_SELECTION : "Planet with report",
		SHOW_FILTER_BY : "Exclude from the list",
		SHOW_FILTER_NONE : "沒有",
		SHOW_PLAYERS_WITHOUT_PROGRESS : "Show players without score changes within the last few days",
		STATUS_TITLE : "OGame Galaxytool - Statuspage",
		STATUS_DB_STATUS : "資料庫狀態",
		STATUS_COLOR : "顏色",
		STATUS_AGE1 : "1 天內更新.",
		STATUS_AGE2 : "2 - 4 天內更新.",
		STATUS_AGE3 : "4 - 7 天內更新.",
		STATUS_AGE4 : "1 - 2 星期內更新.",
		STATUS_AGE5 : "2 - 4 星期內更新.",
		STATUS_AGE6 : "1個月前更新的!",
		STATUS_AGE7 : "未有記錄.",
		STATUS_ON : "開啟",
		STYLES_COLOR1 : "顏色1",
		STYLES_COLOR2 : "顏色2",
		STYLES_COLOR3 : "顏色3",
		STYLES_COLOR4 : "顏色4",
		STYLES_COLOR5 : "顏色5",
		STYLES_COLOR6 : "顏色6",
		STYLES_COLOR7 : "顏色7",
		STATUS_DB_LEGEND : "Legend",
		STATUS_GALAXY : "Galaxy Overview",
		USER_TITLE : "管理使用者",
		USER_NAMES : "帳號",
		USER_ERROR : "錯誤",
		USER_NEWUSER : "新使用者",
		USER_OPTIONS : "選項",
		USER_USERNAME : "帳號",
		USER_PASSWORD : "密碼",
		USER_PASSWORD_CONFIRM : "密碼確認",
		USER_GALAXY : "銀河系",
		USER_SEARCH : "搜尋權",
		USER_INSERT : "資料匯入權",
		USER_DELETE : "刪除",
		USER_DELETE_ENTRY : "你想要刪除使用者： ",
		USER_STATUS : "查看所有狀況權",
		USER_STYLES : "修改界面",
		USER_SUBMIT : "送出",
		USER_RESET : "重新輸入",
		USER_YES : "是",
		USER_NO : "否",
		USER_STYLEPATH : "styles.css的位置",
		USER_PROBES : "觀看/輸入間諜報告",
		USER_EMAIL : "E-mail",
		USER_ERROR1 : "密碼錯誤 或 無效的E-mail！",
		USER_ERROR2 : "無效的E-mail！",
		USER_INGAME : "OGame的帳號",
		USER_ALLYTAG : "聯盟",
		USER_ALLYHISTORY : "歷史統計",
		USER_DIPLOMATIC : "更改外交狀態",
		USER_STATSPAGE : "狀況頁資料數目設定",
		USER_LINKS : "Links",
		USER_LINKS2 : "格式:<br>text;url<br>text2;url2<br>text3;url3",
		USER_EXPORT_TITLE : "顏色設定 (BB Codes)",
		USER_BB_COORDINATES : "座標",
		USER_BB_MOON : "月球",
		USER_BB_DEBRIS : "殘骸",
		USER_BB_ALLY : "聯盟",
		USER_BB_ALLYDETAILS : "聯盟詳細資料",
		USER_BB_PLAYERNAME : "玩家名稱",
		USER_BB_BANNED : "被封的玩家",
		USER_BB_VACATION : "假期模式",
		USER_BB_NOOB : "實力弱的玩家",
		USER_BB_INACTIVE : "Ｉ羊",
		USER_BB_LONGINACTIVE : "Ｉｉ羊",
		USER_DELETION : "刪除",
		USER_FLEETINFO : "移動中艦隊",
		USER_ACTIVITIES : "活動",
		USER_MAINTENANCE : "Galaxytool 管理維護",
		USER_MANAGEMENT : "管理使用者",
		USER_DELETE_MY_COMBAT_REPORTS : "刪除我的戰鬥報告",
		USER_DELETE_MY_MESSAGES : "刪除我的訊息",
		USER_DELETE_MY_FLEETMOVES : "刪除我移動中的艦隊",
		USER_DELETE_MY_COMBAT_REPORTS_LIMITED : "Delete my combat reports older than &1 days",
		USER_DELETE_MY_MESSAGES_LIMITED : "Delete my messages older than &1 days",
		USER_TABLE_ENTRIES : "Number of search results for each page",
		USER_EXISTS : "User already exists",
		USER_BB_OUTLAW : "Outlaw",
		USER_INVALID_URL : "URL &1 seems to be invalid - URL will be ignored",
		VIEW_TITLE : "OGame Galaxytool - Galaxyview",
		VIEW_NODATA : "沒有資料登錄！",
		VIEW_GALAXY : "銀河系",
		VIEW_SYSTEM : "太陽系",
		VIEW_POSITION : "位置",
		VIEW_PLANET : "星球",
		VIEW_MOON : "月球",
		VIEW_TF : "殘骸",
		VIEW_PLAYER : "玩家",
		VIEW_PLAYER_ADD : "(排名 / 狀況)",
		VIEW_ALLY : "聯盟",
		VIEW_ALLY_ADD : "(排名 / 人數)",
		VIEW_METAL : "金屬",
		VIEW_CRYSTAL : "晶體",
		VIEW_COLONISED : "星球有人居住",
		VIEW_UKMOONSIZE : "未知",
		VIEW_BACK : "back",
		VIEW_NOTICE : "訊息",
		VIEW_REPORTS : "間諜報告",
		VIEW_MOONPHALANX : "下列 月球 可掃瞄到這個 太陽系",
		VIEW_NOMOONS : "未知",
		VIEW_IRAKS : "下列 星球 的導彈可攻擊到這個 太陽系",
		VIEW_NOIRAKS : "未知",
		VIEW_MOON_DESTROY_CHANCE : "毀滅月球的機率",
		VIEW_CHANCE_WITH_ONE : "當派一顆死星時",
		VIEW_CHANCE_WITH_N : "派 ",
		VIEW_DEATH_STARS : "死星時",
		VIEW_DS_DESTROY_CHANCE : "死星一起毀滅的機率",
		VIEW_TOP : "Top",
		VIEW_GO : "go",
		VIEW_DIAMETER : "Diameter",
		PW_TITLE : "OGame Galaxytool - 修改密碼",
		OLD_PASSWORD : "目前密碼",
		NEW_PASSWORD : "新密碼",
		CONFIRM_NEW_PASSWORD : "確認新密碼",
		PW_MISMATCH : "兩次輸入的密碼不同！",
		PW_ERROR : "目前密碼不正確！",
		UPDATE_DONE : "修改成功！",
		TIMEZONE_OFFSET : "設定系統時間",
		DELETE_ACCOUNT : "刪除帳號",
		DELETE_ACCOUNT_SAFETY_REQUEST : "你確定要刪除帳號嗎？",
		CH_PASSWD_AUTHORIZATION : "授權",
		CH_PASSWD_ADMIN : "管理員",
		TIMEZONE_OGAME_OFFSET : "OGame伺服器時差",
		CH_PASSWD_USER_LANGUAGE : "Change to this language after logon",
		CH_PASSWD_USER_LANGUAGE_NO_CHANGE : "No change",
		CH_PASSWD_EXPAND : "Expanded",
		CH_PASSWD_COLLAPSE : "Collapsed",
		CH_PASSWD_HIDDEN : "Hidden",
		CH_PASSWD_GETTING_STARTED : "Show Getting Started Info after logon",
		CH_PASSWD_PLUGIN : "Show Plugin Info after logon",
		NOTICE_TITLE : "OGame Galaxytool - Notices",
		NOTICE_HEADER : "編輯訊息",
		NOTICE_HEADER2 : "編輯自己的訊息麼?",
		NOTICE_PUBLIC : "是否公開?",
		NOTICE_YES : "是",
		NOTICE_NO : "否",
		NOTICE_TEXT : "訊息內容",
		NOTICE_SAVE : "儲存",
		NOTICE_DELETED : "已刪除",
		NOTICE_SAVED : "已儲存.",
		NOTICE_RESULTS : "所有結果",
		NOTICE_USER : "使用者",
		NOTICE_DATE : "日期",
		NOTICE_EDIT : "編輯",
		NOTICE_DELETE : "刪除",
		NOTICE_NEW : "創建自己的條目",
		NOTICE_NOTPUBLIC : "此訊息不公開.",
		NOTICE_ALL : "所有",
		NOTICE_NONE : "沒有",
		NOTICE_SEARCH : "搜尋訊息",
		NOTICE_SEARCH_SHORT : "開始搜尋",
		NOTICE_HITS : "第",
		NOTICE_SHOWRESULTS : "顯示的資料筆數",
		NOTICE_OF : "的",
		NOTICE_NOTHING : "沒有找到符合的！",
		NOTICE_CHARS : "字元",
		NOTICE_PLAYERNAME : "玩家",
		NOTICE_SHOWALL : "顯示所有訊息",
		REPORTS_TITLE : "OGame Galaxytool - Espionage Reports",
		REPORTS_RESOURCES : "資源",
		REPORTS_FLEET : "艦隊",
		REPORTS_DEFENCE : "防禦",
		REPORTS_BUILDINGS : "建築",
		REPORTS_TECHNOLOGY : "研究",
		REPORTS_MOON : "月球",
		REPORTS_SEARCH : "搜尋間諜報告",
		REPORTS_SEARCH_SHORT : "開始搜尋",
		REPORTS_HITS : "第",
		REPORTS_NOTHING : "沒有找到符合的！",
		REPORTS_ADDRESS : "位置",
		REPORTS_CURRENTNESS : "更新時間",
		REPORTS_PLAYERNAME : "玩家名稱",
		REPORTS_ALLY : "聯盟",
		REPORTS_VIEW : "間諜報告",
		REPORTS_SEARCH_IN : "搜尋銀河系(1~9)",
		REPORTS_FROM_SYSTEM : "從太陽系",
		REPORTS_TO : "到",
		REPORTS_DELETE : "刪除",
		REPORTS_DELETED : "已刪除",
		REPORTS_RESULTS : "顯示的資料筆數",
		REPORTS_OF : "of",
		REPORTS_DATE : "日期",
		REPORTS_DATE_0 : "不介意",
		REPORTS_DATE_1 : "之前",
		REPORTS_DATE_2 : "之後",
		REPORTS_NOTICES : "訊息",
		REPORTS_AT_LEAST_RESOURCES : "資源(至少)",
		REPORTS_SEARCH_EXTENDED : "搜尋後展開",
		REPORTS_FLEET_RESIS : "艦隊分",
		REPORTS_DEFENCE_RESIS : "防禦分",
		REPORTS_ALL_RESIS : "總積分",
		REPORTS_TECHS : "三圍",
		REPORTS_UNKNOWN_ENTRIES : "unknown entries",
		REPORTS_PARTLY_INSERTED : "部分匯入",
		REPORTS_FOR_ALL_RES : "所有資源需",
		REPORTS_FOR_TF : "殘骸需",
		REPORTS_KT : "小型運輸船",
		REPORTS_GT : "大型運輸船",
		REPORTS_SS : "戰列艦",
		REPORTS_REC : "回收船",
		REPORTS_RAIDABLE : "只有我的間諜報告",
		REPORTS_ALL_RESOURCES : "所有資源",
		REPORTS_STUFF : "範圍",
		REPORTS_SPEEDSIM : "Online 戰鬥模擬器 Speedsim",
		REPORTS_DRAGOSIM : "Online 戰鬥模擬器 Dragosim",
		REPORTS_STATUS : "狀態",
		REPORTS_ERROR : "有錯誤產生!",
		REPORTS_OWN_REPORTS : "自己的間諜報告",
		REPORTS_UPLOAD_BY : "間諜報告上傳者為",
		REPORTS_DEPTH : "報告深度",
		REPORTS_FLEET_SCORE : "艦隊分",
		REPORTS_DEFENCE_SCORE : "防御分",
		REPORTS_HOURS : "hours",
		REPORTS_MAX_RESULTS_HIT : "Your query returned more than &1 hits. Only the first &1 results are show. Please adjust your search request to get less results.",
		REPORTS_OSIMULATE : "Simulate with OSimulate",
		REPORTS_SHOW_ONLY : "Show only",
		REPORTS_SHOW_PLANETS : "星球",
		REPORTS_SHOW_MOONS : "月球",
		REPORTS_OWNER : "Reports owned by",
		STATS_TITLE : "OGame Galaxytool - Statistics",
		STATS_TBLHEAD : "統計",
		STATS_RANK : "排名",
		STATS_PLAYERNAME : "玩家名稱",
		STATS_ALLYNAME : "聯盟",
		STATS_SCORE : "分數",
		STATS_FLEET : "艦隊數",
		STATS_RESEARCH : "研究等級",
		STATS_MEMBERS : "盟員",
		STATS_STATUS : "Status",
		STATS_NOTHING : "no Status",
		STATS_NAP : "互不侵犯",
		STATS_ALLIED : "結盟",
		STATS_WAR : "宣戰",
		STATS_BOYCOTT : "抵制",
		STATS_NEUTRAL : "中立",
		STATS_OWN : "自己所在的聯盟",
		STATS_WING : "子盟",
		STATS_UPDATE : "資料由",
		STATS_PLAYERSTATS : "玩家積分",
		STATS_ALLYSTATS : "聯盟積分",
		STATS_DELETE : "你要刪除這設定嗎？",
		STATS_CONFIRM_DELETE : "你確定要刪除嗎？",
		STATS_CHANGE_PLAYER_STATUS : "玩家的外交",
		STATS_CHANGE_ALLIANCE_STATUS : "聯盟的外交",
		STATS_CHANGE_ALLIANCE_STATUS_HINT : "該聯盟的所有成員將使用這個關係設定！任何個人的關係設定將會被覆蓋！之後你必需去更改其他玩家的關係設定！",
		STATS_UNKNOWN : "其他的",
		STATS_DETAILS : "細節 關於",
		STATS_PLAYERSTATUS : "玩家狀況",
		STATS_IGNORE_STATUS : "全部",
		STATS_ACTIVE : "活躍",
		STATS_INACTIVE : "Ｉ羊",
		STATS_BANNED : "被封的玩家",
		STATS_VACATION : "假期模式",
		STATS_NOOB : "實力弱的玩家",
		STATS_YES : "是",
		STATS_NO : "有訊息的星球",
		STATS_SEARCH : "搜尋權",
		STATS_SHOW_GRAPH : "Show details for score distribution",
		STATS_LONG_INACTIVE : "Ｉｉ羊",
		STATS_STANDARD : "Standard Points",
		STATS_MILITARY : "Military Points",
		STATS_ECONOMY : "Economy",
		STATS_HONOUR : "Honour points",
		STATS_MILITARY_BUILD : "Military build",
		STATS_MILITARY_DESTROYED : "Military destroyed",
		STATS_MILITARY_LOST : "Military lost",
		REGISTER_REGISTRATE : "註冊",
		REGISTER_LOGINNAME : "帳號",
		REGISTER_PASSWORD : "密碼",
		REGISTER_PASSWORD_CONFIRM : "確認密碼",
		REGISTER_EMAIL : "E-mail",
		REGISTER_INGAME : "OGame的帳號",
		REGISTER_ALLYTAG : "聯盟",
		REGISTER_EMAILVERIFICATION : "E-mail查詢",
		REGISTER_EMAILTEXT : "請點擊這個鏈結來確認你在 GalaxyTool 的註冊！",
		REGISTER_ERROR1 : "註冊的帳號已被使用。",
		REGISTER_ERROR2 : "傳送E-mail時發生錯誤！請連絡管理者！",
		REGISTER_ERROR3 : "資料傳送到資料庫時發生錯誤！",
		REGISTER_INFO1 : "你的帳號已經建立。",
		REGISTER_INFO2 : "請查看你的E-mai並點擊鏈結來確認你的申請。",
		REGISTER_INFO3 : "帳號已被確認！但你仍需等GalaxyTool的管理者幫你開通！",
		REGISTER_BUTTON : "回到首頁",
		REGISTER_NEW_SUBJECT : "一個新使用者註冊到GalaxyTool",
		REGISTER_NEW_MAILTEXT : "一個新使用者已經自己註冊",
		REGISTER_BACK : "回到第一頁",
		REGISTER_MISSING_FIELDS : "請填寫所有必須的項!",
		REGISTER_ERROR4 : "Email address is not valid.",
		REGISTER_ERROR5 : "Passwords don't match.",
		REGISTER_PWS : "Password strength",
		REGISTER_PWS0 : "very weak",
		REGISTER_PWS1 : "weak",
		REGISTER_PWS2 : "good",
		REGISTER_PWS3 : "strong",
		REGISTER_PWS4 : "very strong",
		REGISTER_EMAIL_USED : "Email Address is already used",
		LOSTPW_TITLE : "密碼遺失",
		LOSTPW_INFO2 : "新的密碼已產生，並已寄到你的E-mail！",
		LOSTPW_BUTTON1 : "取得新密碼",
		LOSTPW_BUTTON2 : "回首頁",
		LOSTPW_LOGINNAME : "帳號",
		LOSTPW_EMAIL : "E-mail",
		LOSTPW_ERROR1 : "資料傳送到資料庫時發生錯誤！",
		LOSTPW_ERROR2 : "沒有找到符答的資料！",
		LOSTPW_ERROR3 : "傳送E-mail時發生錯誤！請連絡管理者！",
		LOSTPW_EMAIL_SUBJECT : "你申請的新密碼",
		LOSTPW_EMAIL_TEXT1 : "這是 GalaxyTool 新的登入資料",
		LOSTPW_EMAIL_TEXT2 : "帳號",
		LOSTPW_EMAIL_TEXT3 : "密碼",
		LOSTPW_INFO1 : "You will receive an email to verify your password reset request.",
		LOSTPW_CONFIRM_RESET_SUBJECT : "Lost password?",
		LOSTPW_CONFIRM_RESET_MESSAGE : "Hello,\n\nyou requested a password reset for the Galaxytool. To generate a new password, click the following link:",
		USERINFO_TITLE : "OGame Galaxytool - User information",
		USERINFO_NAMES : "GalaxyTool的所有使用者",
		USERINFO_DETAIL : "使用者詳細資料",
		USERINFO_ERROR1 : "沒有這個ID的使用者!",
		USERINFO_USERNAME : "帳號",
		USERINFO_INGAME : "OGame的帳號",
		USERINFO_EMAIL : "E-mail",
		USERINFO_ALLYTAG : "聯盟",
		USERINFO_STYLEPATH : "使用的面版",
		USERINFO_STATUS : "狀態",
		USERINFO_ACTIVATE : "開通",
		USERINFO_LOGINS : "登入次數",
		USERINFO_LASTLOGIN : "最近一次的登入時間",
		USERINFO_DATA : "匯入的資料",
		USERINFO_NODATA : "該使用者沒有匯入任何資料！",
		USERINFO_GALAXY : "銀河系",
		USERINFO_SYSTEMS : "資料數",
		USERINFO_IP : "IP 位置",
		USERINFO_LOGINTIME : "登入時間",
		USERINFO_NOLOGIN : "這個使用者重未登入！",
		USERINFO_LAST_GALAXYUPDATE : "最後匯入資料的時間",
		USERINFO_LAST_PUBLIC_NOTICE : "最後的公共訊息",
		USERINFO_LAST_PRIVATE_NOTICE : "最後的私人訊息",
		USERINFO_NUMBEROF_PUBLIC_NOTICE : "公共訊息數目",
		USERINFO_NUMBEROF_PRIVATE_NOTICE : "私人訊息數目",
		USERINFO_ACTIVATED : "註冊的帳號已被啟用",
		USERINFO_ACTIVATIONTEXT : "Galaxytool的管理者已開通你的帳號！\n\n祝你（妳）使用Galaxytool愉快 !",
		USERINFO_LAST_SUBMIT : "Inserted last data",
		ALLYHISTORY_TITLE : "OGame Galaxytool - Alliance History",
		ALLYHISTORY_TBLHEAD : "歷史統計",
		ALLYHISTORY_PLAYERNAME : "玩家",
		ALLYHISTORY_ALLYNAME : "聯盟",
		ALLYHISTORY_LASTMONTH : "上個月",
		ALLYHISTORY_ALL_DATA : "所有有效的資訊",
		ALLYHISTORY_SHOW : "顯示統計數值",
		ALLYHISTORY_TIMESPAN : "時間跨度",
		ALLYHISTORY_PROGESS : "發展狀況",
		ALLYHISTORY_SCORE : "分數",
		ALLYHISTORY_FSCORE : "艦隊數",
		ALLYHISTORY_RSCORE : "研究等級",
		ALLYHISTORY_MEMBER : "盟員",
		ALLYHISTORY_NOTHING : "未找到符合的",
		ALLYHISTORY_DETAILS : "詳情",
		ALLYHISTORY_SHOW_ADDRESS : "座標",
		ALLYHISTORY_ESCORE : "Economy",
		ALLYHISTORY_MSCORE : "Military Points",
		DETAILEDINFO_PLAYERINFO_TITLE : "玩家資訊",
		DETAILEDINFO_ALLYINFO_TITLE : "聯盟咨詢",
		DETAILEDINFO_PLAYERINFO_TBLHEAD : "玩家詳細資訊",
		DETAILEDINFO_ALLYINFO_TBLHEAD : "聯盟詳細資訊",
		DETAILEDINFO_NO_ALLIANCE : "none",
		DETAILEDINFO_SCORE : "分數",
		DETAILEDINFO_FLEET : "艦隊數",
		DETAILEDINFO_RESEARCH : "研究等級",
		DETAILEDINFO_RANK : "排名",
		DETAILEDINFO_POINTS : "分數",
		DETAILEDINFO_KNOWN_PLANETS : "已知的星球",
		DETAILEDINFO_MOONS : "已知的月球",
		DETAILEDINFO_PHALANX_AREA : "感應範圍",
		DETAILEDINFO_NO_PHALANX_AREA : "未知或沒有感應範圍",
		DETAILEDINFO_NOTICES : "訊息",
		DETAILEDINFO_NO_NOTICES : "沒有訊息",
		DETAILEDINFO_PREVIOUS_ALLIANCES : "先前的聯盟",
		DETAILEDINFO_RESOURCES_PER_HOUR : "每小時的資源量",
		DETAILEDINFO_RESOURCES_PER_DAY : "每天的資源量",
		DETAILEDINFO_RESOURCES_PER_WEEK : "每週的資源量",
		DETAILEDINFO_RESOURCES_PER_MONTH : "每30天的資源量",
		DETAILEDINFO_METAL : "金屬",
		DETAILEDINFO_CRYSTAL : "晶體",
		DETAILEDINFO_DEUTERIUM : "重氫",
		DETAILEDINFO_UNKNOWN : "未知",
		DETAILEDINFO_SCORE_DISTRIBUTION : "分數分佈圖",
		DETAILEDINFO_GENERAL : "詳情",
		DETAILEDINFO_MEMBERS : "盟員",
		DETAILEDINFO_GRAPHS : "圖表",
		DETAILEDINFO_RESOURCES : "資源",
		DETAILEDINFO_FLEET_TAB : "艦隊",
		DETAILEDINFO_TECH : "研究",
		DETAILEDINFO_FLEET_DETAIL : "加總 / (盟員平均數) 所有可用的間諜報告",
		DETAILEDINFO_TECH_DETAIL : "平均所有可用的玩家資訊",
		DETAILEDINFO_PLANET_TAB : "星球",
		DETAILEDINFO_MOON_TAB : "月球",
		DETAILEDINFO_ACTIVITIES : "Activities",
		DETAILEDINFO_NODATA : "沒有資料登錄！",
		DETAILEDINFO_ACTIVITY_DESCRIPTION : "Show activities of &1 collected from:",
		DETAILEDINFO_GALAXYVIEWS : "Galaxy views",
		DETAILEDINFO_SCANS : "Espionage actions",
		DETAILEDINFO_MESSAGES : "Player messages",
		DETAILEDINFO_COMBATS : "Combat reports",
		DETAILEDINFO_ALLYPAGE : "Alliance overview",
		DETAILEDINFO_MANUAL : "Manual insertions",
		DETAILEDINFO_START : "Beginning",
		DETAILEDINFO_TO : "to",
		DETAILEDINFO_TODAY : "Today",
		DETAILEDINFO_DATA_RESTRICTION : "restricted to:",
		DETAILEDINFO_WEEKDAY_WEEKEND : "Weekend",
		DETAILEDINFO_WEEKDAY_WORKINGDAY : "Weekday",
		DETAILEDINFO_WEEKDAY_MONDAY : "Monday",
		DETAILEDINFO_WEEKDAY_TUESDAY : "Tuesday",
		DETAILEDINFO_WEEKDAY_WEDNESDAY : "Wednesday",
		DETAILEDINFO_WEEKDAY_THURSDAY : "Thursday",
		DETAILEDINFO_WEEKDAY_FRIDAY : "Friday",
		DETAILEDINFO_WEEKDAY_SATURDAY : "Saturday",
		DETAILEDINFO_WEEKDAY_SUNDAY : "Sunday",
		DETAILEDINFO_WEEKDAY_SHORTLENGTH : 3,
		DETAILEDINFO_PLAYER_CURRENTLY_ACTIVE : "The player is currently active",
		DETAILEDINFO_PLAYER_MESSAGES : "available player messages",
		DETAILEDINFO_SHOW : "show",
		DETAILEDINFO_NONE : "none available",
		DETAILEDINFO_ENTER_MANUALLY : "Enter activities for this player",
		DETAILEDINFO_PLAYER_SEEN_ON : "Player was online on",
		DETAILEDINFO_INSERT : "Insert",
		DETAILEDINFO_OGAME_SERVERTIMES : "Please note: All dates and times refer to OGame server times !",
		DETAILEDINFO_DAY_VIEW : "24 hours view",
		DETAILEDINFO_WEEK_VIEW : "weekly view",
		DETAILEDINFO_HOME_PLANET : "Homeworld",
		DETAILEDINFO_PLANETNAME : "Name",
		DETAILEDINFO_DEFENCE_SCORE : "Defence score",
		DETAILEDINFO_DEFENCE_SCORE_TOOLTIP : "Defence score = Fleet - Score + Research + Economy.<br/>All those statistics must be up to date to have a meaningful result!",
		DETAILEDINFO_SCORE_PER_SHIP : "Scores per ship",
		DETAILEDINFO_SHIPS : "Number of ships",
		DETAILEDINFO_DATE_IN_FUTURE : "Do not maintain times which are not in the past.",
		ADMIN_TITLE : "Administration of the Galaxytool",
		ADMIN_DISCLAMER : "注意: 運行腳本的風險自己承擔, 大多數腳本都會刪除數據.",
		ADMIN_INCONSISTENCIES : "數據庫裡的不一致",
		ADMIN_PLANETS : "在0號或者大於15號位的星球",
		ADMIN_GALAXIES : "刪除大於 &1 的銀河系 ",
		ADMIN_PLAYERS : "刪除沒有OGame ID的使用者-導致復數的登錄者",
		ADMIN_REPORTS : "刪除不存在的星球的間諜報告",
		ADMIN_MISC : "雜項",
		ADMIN_RESET : "重置 Galaxytool (只有使用者與ip表不被刪除)",
		ADMIN_OLD_PLAYERS : "刪除匯入大於 &1 天的玩家信息",
		ADMIN_OLD_REPORTS : "刪除匯入大於 &1 天的間諜報告",
		ADMIN_LOADING : "加載頁面的時候不要關閉窗口.",
		ADMIN_STATUS : "你的請求的狀態",
		ADMIN_SELECTION : "至少要選中一項!",
		ADMIN_SAFETY : "確定要運行所選腳本麼?",
		ADMIN_DONE : "完成",
		ADMIN_NOTBD : "沒有執行操作",
		ADMIN_OLD_GALAXIES : "刪除匯入大於 &1 天的銀河系",
		ADMIN_UNUSED_PLAYERS : "刪除在銀河系視圖中未出現的玩家",
		ADMIN_OLD_ACTIVITIES : "刪除匯入大於 &1 天未活動的玩家",
		ADMIN_OLD_COMBATS : "Remove combat reports older than &1 days",
		ADMIN_OLD_INGAME_MSG : "Remove ingame messages older than &1 days",
		ADMIN_OGAME_API : "Load public data from OGame into the Galaxytool",
		ADMIN_OGAME_ALL_DATA : "所有有效的資訊",
		ADMIN_OGAME_GALAXY_DATA : "查看星系",
		ADMIN_OGAME_STATISTICS_DATA : "統計",
		ERRORPAGE_PAGEFORWARD : "如果你的瀏覽器沒有自動跳轉請點擊這裡",
		ERRORPAGE_PERMISSION_DENIED : "你沒有權限查看此頁 點擊返回.",
		FLEETS_TITLE : "OGame Galaxytool - Fleet movements",
		FLEETS_ACTUAL_FLEETS : "Current fleet movements",
		FLEETS_YES : "是",
		FLEETS_NO : "有訊息的星球",
		FLEETS_DETAILS : "Details",
		FLEETS_MISSION_EXPEDITION : "Expedition",
		FLEETS_MISSION_COLONIZATION : "Colonize",
		FLEETS_MISSION_RECYCLE : "Harvest",
		FLEETS_MISSION_TRANSPORT : "Transport",
		FLEETS_MISSION_DEPLOYMENT : "Deploy",
		FLEETS_MISSION_ESPIONAGE : "Espionage",
		FLEETS_MISSION_ACS_DEFEND : "ACS Defend",
		FLEETS_MISSION_ATTACK : "Attack",
		FLEETS_MISSION_ACS_ATTACK : "ACS Attack",
		FLEETS_MISSION_MOON_DESTRUCTION : "Moon Destruction",
		FLEETS_MISSION_MISSILE_ATTACK : "Missile Attack",
		FLEETS_NO_DATA : "No applicable data found",
		FLEETS_FLEET : "Fleet",
		FLEETS_ALL_FLEETS : "Show all fleet movements",
		COMBAT_REPORT_OUDATED_GALAXYVIEW : "您的銀河資料已經過期，請優先瀏覽戰報來源和目標座標!",
		MESSAGES_TITLE : "OGame Galaxytool - OGame Messages",
		MESSAGES_PLAYERNAME : "Playername",
		MESSAGES_SUBJECT : "Subject",
		MESSAGES_DATE : "Date",
		MESSAGES_FILTER : "Filter",
		MESSAGES_DELETE : "Delete message",
		MESSAGES_PUBLISH_DETAIL : "Publish message by adding the message content to notice text of that player.",
		MESSAGES_PUBLISH_HEADER : "&sender sent a message to &recipient on &date:\n\n &message",
		MESSAGES_PLAYER_FILTER : "Messages for player:",
		MESSAGES_CONTENT : "Content",
		COMBATS_TITLE : "OGame Galaxytool - Combat reports",
		COMBATS_ATTACKER : "Attacker",
		COMBATS_DEFENDER : "Defender",
		COMBATS_DATE : "Date",
		COMBATS_OWNER : "Owner",
		COMBATS_WINNER : "Winner",
		COMBATS_COMBATREPORT : "Combat Report",
		COMBATS_COMBAT_AT : "Combat at",
		COMBATS_LOST_UNITS : "Lost units",
		COMBATS_LOOT : "Loot",
		COMBATS_DEBRIS : "Debris",
		COMBATS_AND : "and",
		COMBATS_PUBLISH : "Make this report public",
		COMBATS_UNPUBLISH : "Unshare this report (makes it private again)",
		COMBATS_DELETE : "Delete report",
		COMBATS_CHECK_ALL : "Check All",
		COMBATS_UNCHECK_ALL : "Uncheck All",
		COMBATS_WITH_SELECTED : "With selected",
		COMBATS_PUBLIC_REPORTS : "Public reports",
		COMBATS_YES : "是",
		COMBATS_NO : "有訊息的星球",
		COMBATS_SEARCH_OPTIONS : "Search options",
		COMBATS_SEARCH : "Go",
		COMBATS_RESET : "Reset",
		COMBATS_COORDINATES : "座標",
		COMBATS_INVALID_GALAXY_ENTERED : "Invalid Galaxy entered",
		COMBATS_INVALID_SYSTEM_ENTERED : "Invalid System entered",
		COMBATS_INVALID_PLANET_ENTERED : "Invalid Planet entered",
		COMBATS_GALAXY_FROM_TO : "Galaxy",
		COMBATS_SYSTEM_FROM_TO : "System",
		COMBATS_PLANET_FROM_TO : "Planet",
		COMBATS_APPLY : "Apply",
		COMBATS_COMBAT_SUMMARY : "Combat report summary",
		COMBATS_DOWNLOAD_CSV : "Download as CSV file",
		REPORT_ARCHIVE_TITLE : "Report archive",
		REPORT_ARCHIVE_COORDINATES : "Coordinates",
		REPORT_ARCHIVE_SCANTIME : "Scan time",
		REPORT_ARCHIVE_DELETE : "Delete these entries",
		REPORT_ARCHIVE_CONFIRM_DELETE : "Do you really want to delete these entries?",
		REPORT_ARCHIVE_GALAXY : "Galaxy",
		REPORT_ARCHIVE_SYSTEM : "System",
		REPORT_ARCHIVE_PLANET : "Planet",
		REPORT_ARCHIVE_MOON : "Moon",
		REPORT_ARCHIVE_DETAILS : "Details",
		REPORT_ARCHIVE_RESOURCES : "每小時的資源量",
		REPORT_ARCHIVE_HEADER_RESOURCES : "資源",
		REPORT_ARCHIVE_DETAILS_FOR : "Report archive for &1 [&2] (&3)",
		REPORT_ARCHIVE_FLEET_CARGO : "Fleet cargo capacity",
		REPORT_ARCHIVE_IRAK_RANGE : "Interplanetary Missiles range",
		REPORT_ARCHIVE_CHART_TYPE : "Chart type",
		INSTALL_TITLE : "Galaxytool installation for version",
		INSTALL_PROGRESS : "Overall progress",
		INSTALL_STEP : "Step",
		INSTALL_CONTINUE : "Continue",
		INSTALL_VALIDATE : "Validate",
		INSTALL_STEP1 : "Welcome",
		INSTALL_STEP2 : "Writeable check",
		INSTALL_STEP3 : "Database settings",
		INSTALL_STEP4 : "OGame settings",
		INSTALL_STEP5 : "Galaxytool settings",
		INSTALL_STEP6 : "Admin password",
		INSTALL_STEP7 : "Install Galaxytool",
		INSTALL_STEP8 : "Finalize install",
		INSTALL_FILE_DELETE_CHECK : "Please delete install.php and update.php from your webserver.",
		INSTALL_STEP1_PHP_FAILED : "Your PHP version &1 is not working with this Galaxytool version",
		INSTALL_STEP1_FOPEN_FAILED : "Your PHP version does not allow to open webpages with FOPEN() command. This is required to consume the OGame API.",
		INSTALL_STEP1_WELCOME : "Welcome to the installation wizard of the Galaxytool. You will be guided through the installation of the Galaxytool.",
		INSTALL_STEP2_DESCRIPTION : "Make sure your config.php and attributes.php files have write permissions enabled.",
		INSTALL_STEP2_DESCRIPTION2 : "If you don't know, how to achieve this, please take a look here: &1",
		INSTALL_STEP2_FILE_NOT_WRITEABLE : "File is not writeable",
		INSTALL_STEP3_SERVER : "Database server",
		INSTALL_STEP3_USERNAME : "帳號",
		INSTALL_STEP3_PASSWORD : "密碼",
		INSTALL_STEP3_DBNAME : "Database name",
		INSTALL_STEP3_PREFIX : "Tablename prefix",
		INSTALL_STEP3_ENTER_PREFIX : "E.g. mytool_",
		INSTALL_STEP3_ENTER_SERVER : "Enter the server address. Contact your system admin if necessary. Usually the correct value is localhost.",
		INSTALL_STEP3_ENTER_USERNAME : "Enter the username for database access",
		INSTALL_STEP3_ENTER_PASSWORD : "Enter the password for database access",
		INSTALL_STEP3_ENTER_DBNAME : "Enter the database name which shall be used for installation (must exist)",
		INSTALL_STEP3_CONNECT_FAILED : "Could not establish connection to database server",
		INSTALL_STEP3_DB_FAILED : "Database &1 not found",
		INSTALL_STEP3_MYSQL_VERSION_FAILED : "MySQL version &1 is not working with this Galaxytool version",
		INSTALL_STEP4_URL : "OGame URL",
		OGAME_URL_DETAILS : "Please enter any URL you see when you are logged on to OGame. Based on that URL the tool will derive the OGame API address which can be used to fill data into the Galaxytool without the Galaxytoolbar. This API was introduced with OGame version 4.1.",
		INSTALL_STEP4_UNIVERSE : "OGame Universe",
		INSTALL_STEP4_DEF_TO_DEBRIS : "Defense to debris",
		INSTALL_STEP4_DEBRIS_RATE : "Debris rate",
		INSTALL_STEP4_SPEED_RATE : "Speed rate",
		INSTALL_STEP4_ENTER_UNIVERSE : "Enter your OGame universe name or number (case sensitive).",
		INSTALL_STEP4_UNIVERSE_MISSING : "You must define your universe",
		INSTALL_STEP4_ENTER_URL : "Enter your OGame universe address",
		INSTALL_STEP4_URL_MISSING : "You must define your OGame address",
		INSTALL_STEP4_URL_CHECK_FAILED : "Could not find OGame API at &1",
		INSTALL_STEP4_GETSETTINGS : "Fetch settings",
		INSTALL_STEP5_TOOLNAME : "Galaxytool name",
		INSTALL_STEP5_ENTER_TOOLNAME : "This is the name which will be shown at logon page to identify your Galaxytool",
		INSTALL_STEP5_LANGUAGE : "Default language",
		INSTALL_STEP5_EMAIL_TO : "Email To",
		INSTALL_STEP5_ENTER_EMAIL_TO : "Enter the email address where you would like to receive notifications about registrations",
		INSTALL_STEP5_EMAIL_FROM : "Email From",
		INSTALL_STEP5_ENTER_EMAIL_FROM : "This email address is shown as REPLY for all mails sent from the Galaxytool",
		INSTALL_STEP5_USE_PHPMAILER : "Use PHPMailer",
		INSTALL_STEP5_MAXSHOUTS : "Maximum number of shoutbox entries",
		INSTALL_STEP5_ENTER_USE_PHPMAILER : "Use PHPMailer if your server does not support sending emails by default",
		INSTALL_PHPMAILER_HOST : "SMPT Host",
		INSTALL_PHPMAILER_HOST_EXAMPLE : "e.g. smtp.provider.com",
		INSTALL_PHPMAILER_USER : "SMPT Username",
		INSTALL_PHPMAILER_USER_EXAMPLE : "e.g. user@provider.dcom",
		INSTALL_PHPMAILER_PASS : "SMPT password",
		INSTALL_PHPMAILER_SECURE : "Authentification method (e.g. ssl)",
		INSTALL_PHPMAILER_PORT : "SMTP Port",
		INSTALL_STEP6_INTRO : "Please define a password for the <strong>admin</strong> account which you have to use for your first logon to the Galaxytool after the installation.",
		INSTALL_STEP7_CONFIG : "Configuration file created",
		INSTALL_STEP7_CONFIG_FAILED : "Configuration file not created",
		INSTALL_STEP7_ATTRIBUTES : "Attributes file created",
		INSTALL_STEP7_ATTRIBUTES_FAILED : "Attributes file not created",
		INSTALL_STEP7_CREATED_TABLES : "Database tables created",
		INSTALL_STEP8_INTRO : "You have successfully installed the Galaxytool!",
		INSTALL_STEP8_LOAD_DATA : "Downloading OGame data ...",
		INSTALL_STEP8_LOAD_DATA_FINISHED : "Download of OGame data finished",
		INSTALL_STEP8_DELETE_FILE : "You should now delete the installation files install.php and update.php from your webserver.",
		INSTALL_STEP8_LOGON : "Please logon with the <strong>admin</strong> user and the password you defined earlier.",
		UPDATE_START : "Starting update to version &1",
		UPDATE_STEP_DONE : "Done",
		UPDATE_TITLE : "Galaxytool update for version",
		UPDATE_STEP1_WELCOME : "Welcome to the update wizard of the Galaxytool. You will be guided through the update of the Galaxytool.",
		UPDATE_STEP1_BACKUP_FILES : "As a first step, make a backup of your <strong>config</strong> folder! You will have to replace the configuration content in case of errors.",
		UPDATE_STEP1_BACKUP_DB : "Then make a <a href=\"http://www.ehow.com/how_2036600_create-database-php.html\">backup</a> of your database.",
		UPDATE_STEP1_PROCEED : "Once the backups have been done, you can proceed with your update.",
		UPDATE_STEP1 : "Welcome",
		UPDATE_STEP2 : "Galaxytool settings",
		UPDATE_STEP2_OLD_VERSION : "Previous Galaxytool version",
		UPDATE_STEP3 : "Update Galaxytool",
		UPDATE_STEP3_UPDATE_RUNNING : "Update running, please wait...",
		UPDATE_STEP4 : "Finalize Update",
		UPDATE_STEP4_INTRO : "You have successfully updated the Galaxytool!",
		UPDATE_STEP4_UPDATE_DONE : "Update steps performed.",
		UPDATE_FAILED : "Update failed.",
		GALAXYTOOL_DUMMY_TEXT : "dummy"
	})
);