define(
	({
		REPORT_WHEN : "am",
		RESOURCES_ON : "Rohstoffe auf",
		PLAYER_BANNED : "g",
		PLAYER_VACATION_MODE : "u",
		PLAYER_NOOB : "n",
		PLAYER_INACTIVE : "i",
		PLAYER_LONG_INACTIVE : "I",
		PLAYER_OUTLAW : "o",
		L_USERNAME : "Nutzername",
		L_PASSWORD : "Passwort",
		L_LOGINFAILURE : "Benutzername oder Passwort war falsch oder du bist noch nicht freigeschaltet.",
		L_TOKENFAILURE : "Dein Loginschlüssel war falsch oder du bist noch nicht freigeschaltet.",
		L_LOGINTEXT : "Bitte gib deine Nutzerdaten ein.",
		L_LANGUAGE : "verfügbare Sprachen:",
		L_TIMEOUT : "Session Timeout!",
		L_REGISTER : "Registrieren",
		L_PWLOST : "Passwort vergessen",
		INDEX_TITLE : "OGame Galaxietool - Übersicht",
		INDEX_INFO : "Informationen",
		INDEX_ENTRIES : "Systeme insgesamt",
		INDEX_ENTRIES_LASTWEEK : "Neue Systeme in der letzten Woche",
		INDEX_ENTRIES_TO_OLD : "Systeme älter als ein Monat",
		INDEX_REGISTERED_USERS : "Registrierte Benutzer",
		INDEX_PAGEFORWARD : "Sollte dein Browser keine Weiterleitung unterstützen klicken bitte hier.",
		INDEX_NOTICES : "Notizen",
		INDEX_PLAYERS : "Spieler Statistiken",
		INDEX_ALLIES : "Allianz Statistiken",
		INDEX_REPORTS : "Spionageberichte",
		INDEX_VERSION : "Neueste Version zum Download",
		INDEX_LATEST_VERSION : "Keine neuere Version vorhanden",
		INDEX_SHOUTBOX : "Aktuelle Mitteilungen",
		INDEX_NOENTRY : "Bisher keine Einträge",
		INDEX_COMMENT : "Dein Beitrag",
		INDEX_INSERT : "Eintragen",
		INDEX_UMOD : "Spieler im Urlaubsmodus",
		INDEX_NO_MOONS : "Anzahl Monde",
		INDEX_NO_EMPTY_SYSTEMS : "Anzahl leerer Systeme",
		INDEX_NO_FULL_SYSTEMS : "Anzahl vollständig gefüllter Systeme",
		INDEX_NO_TARGETS : "Anzahl angreifbarer Planeten",
		INDEX_USERINFO : "Userzahlen",
		INDEX_ONLINE : "Jetzt Online",
		INDEX_TODAY : "Heute Online",
		INDEX_ALL : "Gesamtlogins",
		GENERAL_LOAD_FORM : "Formulardaten laden",
		GENERAL_SAVE_FORM : "Formulardaten speichern",
		GENERAL_SAVE_AS_TEXT : "Speichern unter",
		GENERAL_SAVE : "Speichern",
		INDEX_USERMANAGEMENT : "Aktivierungsübersicht",
		INDEX_NEEDADMIN : "Freizuschaltende Accounts",
		INDEX_NEEDEMAIL : "Noch nicht validierte Accounts",
		INDEX_TOOLBAR_INFO : "Informationen zum Galaxietool Plugin",
		INDEX_TOOLBAR_URL : "Galaxietool URL",
		INDEX_TOOLBAR_VERSION_REQUIRED : "Mindestversion des Galaxietool Plugin",
		INDEX_TOOLBAR_INSTALL_GUIDE : "Installationsanweisung für das Plugin",
		INDEX_TOOLBAR_TOKEN : "Loginschlüssel",
		INDEX_TOOLBAR_NEW_TOKEN : "Neuen Schlüssel erzeugen",
		INDEX_PLAYERS_WITH_N_PLANETS : "Spieler mit mehr als &1 Planeten",
		INDEX_GETTING_STARTED : "Erste Schritte mit dem Galaxietool",
		INDEX_GETTING_STARTED1 : "Willkommen im Galaxietool!",
		INDEX_GETTING_STARTED2 : "Das Galaxietool wird dich dabei unterstützen herauszufinden, was in deinem Universum &1 vorgeht.",
		INDEX_GETTING_STARTED3 : "Um aber überhaupt Daten analysieren zu können, müssen diese erst in das Tool integriert werden. Dazu benötigst du ein Plugin wie die &1 für Firefox.",
		INDEX_GETTING_STARTED4 : "Nachdem das Plugin installiert und eingerichtet wurde, surfst du durch die einzelnen OGameseiten wie sonst auch. Zusätzlich wird aber ein kleines Statusfenster erscheinen, wann immer Daten ins Galaxietool eingetragen wurden.",
		INDEX_GETTING_STARTED5 : "Sobald genügend Daten im Galaxietool vorhanden sind, kann die Analyse beginnen. So kann geschaut werden, wo Mitspieler ihre Kolonien haben, wie viele Kolonien sie besitzen, welche Spionageberichte von ihnen existieren und wann sie am häufigsten online sind.",
		INDEX_GETTING_STARTED6 : "Das Galaxietool kann aber auch zur Analyse des eigenen Fortschritts genutzt werden, indem Vergleiche mit anderen Mitspielern gezogen werden oder durch die Analyse der eigenen Kampfberichte um zu sehen was in den letzten Tagen / Wochen erbeutet wurde.",
		INDEX_GETTING_WIKIPAGE : "Das war aber nur ein kleiner Auszug der Features des Galaxietools.",
		INDEX_GETTING_WIKIPAGE2 : "Sämtliche Features findest du auf unserer Wikiseite.",
		INDEX_GETTING_BOARD : "Über Feedback oder Ideen freuen wir uns in unserem Board:",
		INDEX_GETTING_CHAT1 : "Oder besuche uns direkt in unserem Chatraum:",
		INDEX_GETTING_CHAT2 : "Wir sind nicht 24 Stunden / 7 Tage die Woche online, verbringen aber sehr viel Freizeit dort. Seid also bitte nicht ungeduldig, wenn ihr nach 30 Sekunden noch keine Antwort erhalten habt.",
		INDEX_CLOSE : "Schließen",
		INDEX_LOGIN : "Einloggen",
		GENERAL_REQUIRED_FIELDS : "Bitte alle Pflichtangaben pflegen",
		INDEX_MESSAGES : "Meldungen",
		INDEX_EXAMPLE : "Beispiel",
		INDEX_INVALID_DATA : "Ungültige Eingabe",
		GENERAL_COLUMN_HIDE_TITLE : "Spaltenverwaltung",
		GENERAL_COLUMN_HIDE_INFO : "Hier kannst du auswählen welche Spalten in der Tabelle angezeigt werden sollen.",
		GENERAL_ENTRIES_DELETED : "&1 Einträge gelöscht",
		GENERAL_APPLY : "Übernehmen",
		STARTPAGE_GALAXYTOOL_DESCR : "<em>Galaxytool</em> ist ein Tool für das bekannte Browserspiel OGame.",
		GENERAL_OVERWRITE : "Identischen Eintrag überschreiben",
		GENERAL_OVERWRITE_QUESTION : "Überschreiben?",
		INDEX_OWN_LOGINS : "Anzahl deiner Logins",
		GENERAL_OPEN_IN_NEW_WINDOW : "Link in neuem Fenster öffnen",
		GENERAL_UNIT_OF_MEASURE_DAYS : "Tage",
		PROGRAM_NAME : "OGame Galaxietool",
		SHORTNAME : "Galaxietool",
		BACK_INDEX : "Zurück zur Hauptseite",
		UNIVERSE : "Universum",
		MENU_INFO_LINKS : "Informationen",
		MENU_PAGE : "Übersicht",
		MENU_DB_SEARCH : "Datenbank durchsuchen",
		MENU_DB_NOTICES : "Notizen durchsuchen",
		MENU_DB_REPORTS : "SpioReports durchsuchen",
		MENU_GALAXYVIEW : "Galaxieansicht",
		MENU_STATISTICS : "Statistiken",
		MENU_ALLYHISTORY : "zeitliche Statistiken",
		MENU_FLEET_MOVEMENTS : "Flottenbewegungen",
		MENU_COMBAT_REPORTS : "Kampfberichte",
		MENU_MESSAGES : "Spielernachrichten",
		MENU_OPTION_LINKS : "Optionen",
		MENU_DB_REFRESH : "Datenbank aktualisieren",
		MENU_NOTICES : "Notizen",
		MENU_DB_STATUS : "Status der Datenbank",
		MENU_USEROPTIONS : "Benutzerverwaltung",
		MENU_USEROPTIONS2 : "Benutzeroptionen",
		MENU_USEROPTIONS3 : "Benutzerinformationen",
		MENU_ADMIN : "Verwaltung",
		MENU_LOGOUT : "Ausloggen",
		MENU_STUFF : "Sonstiges",
		MENU_FORUM_THREAD : "Entwicklerforum",
		MENU_DOWNLOADPAGE : "Downloadseite",
		MENU_LANGUAGE : "Sprachauswahl",
		MENU_HELP : "Hilfe",
		MENU_TOOLOPTIONS : "Galaxietool Optionen",
		PARSER_INFO1 : " wurde in die Datenbank eingetragen",
		PARSER_ERROR1 : "Fehler beim Versuch die folgenden Koordinaten einzutragen:",
		PARSER_ERROR2 : "Auswahl der Datenbank fehlgeschlagen!",
		PARSER_ERROR3 : "Konnte den Datenbankserver nicht finden!",
		PARSER_WRONG_UNIVERSE : "Falsches Universum - aktuell: \"&1\"  erwartet: \"&2\"",
		SHOW_TITLE : "OGame Galaxietool - Abfrageseite",
		SHOW_SEARCH : "Suche in der Datenbank",
		SHOW_ALLYSYMBOL : "Allytag",
		SHOW_PLAYERNAME : "Spielername",
		SHOW_MOONS : "Nur Monde suchen",
		SHOW_NOTICES : "Nur Planeten mit Notizen suchen",
		SHOW_COLONIES : "nur besiedelbare Planeten",
		SHOW_YES : "Ja",
		SHOW_NO : "Nein",
		SHOW_SEARCHRANGE : "Suchreichweite",
		SHOW_SEARCH_IN : "Suche in Galaxie",
		SHOW_FROM_SYSTEM : "von System",
		SHOW_FROM_PLANET : "von Planetposition",
		SHOW_TO : "bis",
		SHOW_DESCRIPTION : "Bei den Spielernamen und Allytags sind * als Wildcards zulässig, so dass *name* alle Spieler findet die &quot;name&quot; in ihrem Spielernamen stehen haben.<br />Es müssen nicht alle Felder ausgefüllt werden, so ist eine Suche nur nach den Koordinaten einer Allianz möglich, aber ebenso eine Suche nach allen Monden der Allianz.",
		SHOW_SORT_BY : "Sortieren nach",
		SHOW_GALASYSTEM : "Galaxie/System",
		SHOW_ALLYNAME : "Allianzname",
		SHOW_SEARCHBUTTON : "Suchen",
		SHOW_ADDRESS : "Adresse",
		SHOW_ALLYSORT : "Allianz",
		SHOW_PLANET : "Planetname",
		SHOW_STATUS : "Status",
		SHOW_CURRENTNESS : "Aktualität",
		SHOW_PLAYER_STATUS : "Spielerstatus",
		SHOW_PLAYER_STATUS1 : "egal",
		SHOW_PLAYER_STATUS2 : "raidbar",
		SHOW_PLAYER_STATUS3 : "inaktiv",
		SHOW_HITS : "Ergebnisse",
		SHOW_OF : "von",
		SHOW_ASC : "aufsteigend",
		SHOW_DESC : "absteigend",
		SHOW_RESULTS : "Trefferanzeige",
		SHOW_MOON : "Mond",
		SHOW_UKMOONSIZE : "unbekannt",
		SHOW_DF : "TF",
		SHOW_DF_LONG : "Trümmerfeld",
		SHOW_METAL : "M",
		SHOW_METAL_LONG : "Metall",
		SHOW_CRYSTAL : "K",
		SHOW_CRYSTAL_LONG : "Kristall",
		SHOW_BOTH : "zusammen",
		SHOW_AT_LEAST : "(mind.)",
		SHOW_DATE : "Datum",
		SHOW_DATE_0 : "egal",
		SHOW_DATE_1 : "älter als",
		SHOW_DATE_2 : "neuer als",
		SHOW_RANK : "Platz",
		SHOW_FRANK : "Flottenplatz",
		SHOW_MEMBERS : "Mitglieder",
		SHOW_NOTRANKED : "Keine Daten vorhanden",
		SHOW_NOTICERES : "Notizen",
		SHOW_REPORTS : "Zeige nur Planeten mit Reports",
		SHOW_REPORTS_SHORT : "Spionage",
		SHOW_NOTHING : "Keine Einträge gefunden",
		SHOW_ALLIANCE_STATUS : "Allianzstatus",
		SHOW_NO_STATUS : "kein Status",
		SHOW_NAP : "NAP",
		SHOW_ALLIED : "Verbündet",
		SHOW_WAR : "Krieg",
		SHOW_BOYCOTT : "Boykott",
		SHOW_NEUTRAL : "Neutral",
		SHOW_OWN : "Eigene Ally",
		SHOW_WING : "Wing",
		SHOW_EXT_OPTIONS1 : "Reichweitensuche, Rangsuche, Datumssuche sowie Trümmerfeldsuche.",
		SHOW_EXT_OPTIONS2 : "Zeige die erweiterten Suchoptionen für die Suche nach Kolonieplätzen, Monden, Reports, Notizen, Spielerstatus oder Diplomatiestatus.",
		SHOW_EXT_OPTIONS3 : "Zeige die erweiterten Optionen für die Sortierung der Suchergebnisse.",
		SHOW_EXTENDED : "erweiterte Suche",
		SHOW_MOON_SELECTION : "Planet mit Mond",
		SHOW_REPORT_SELECTION : "Planet mit Spionagebericht",
		SHOW_FILTER_BY : "von den Suchergebnissen ausschließen",
		SHOW_FILTER_NONE : "keine",
		SHOW_PLAYERS_WITHOUT_PROGRESS : "Zeige Spieler ohne Punkteänderung innerhalb der letzten Tage",
		STATUS_TITLE : "OGame Galaxietool - Statusseite",
		STATUS_DB_STATUS : "Status der Datenbank",
		STATUS_COLOR : "Farbe",
		STATUS_AGE1 : "Eintrag ein Tag alt.",
		STATUS_AGE2 : "Eintrag 2 - 4 Tage alt.",
		STATUS_AGE3 : "Eintrag 4 - 7 Tage alt.",
		STATUS_AGE4 : "Eintrag 1 - 2 Wochen alt.",
		STATUS_AGE5 : "Eintrag 2 - 4 Wochen alt.",
		STATUS_AGE6 : "Eintrag älter als 1 Monat!",
		STATUS_AGE7 : "Noch kein Eintrag vorhanden.",
		STATUS_ON : "am",
		STYLES_COLOR1 : "Farbe1",
		STYLES_COLOR2 : "Farbe2",
		STYLES_COLOR3 : "Farbe3",
		STYLES_COLOR4 : "Farbe4",
		STYLES_COLOR5 : "Farbe5",
		STYLES_COLOR6 : "Farbe6",
		STYLES_COLOR7 : "Farbe7",
		STATUS_DB_LEGEND : "Legende",
		STATUS_GALAXY : "Galaxieübersicht",
		USER_TITLE : "OGame Galaxietool - Benutzerverwaltung",
		USER_NAMES : "Benutzer",
		USER_ERROR : "Fehler",
		USER_NEWUSER : "Neuer Benutzer",
		USER_OPTIONS : "Einstellungen",
		USER_USERNAME : "Nutzername",
		USER_PASSWORD : "Passwort",
		USER_PASSWORD_CONFIRM : "Passwort wiederholen",
		USER_GALAXY : "Galaxie",
		USER_SEARCH : "Suchen",
		USER_INSERT : "Eintragen",
		USER_DELETE : "löschen",
		USER_DELETE_ENTRY : "Willst du den folgenden Spieler wirklich löschen: ",
		USER_STATUS : "Statusansicht",
		USER_STYLES : "Layout anpassen",
		USER_SUBMIT : "Abschicken",
		USER_RESET : "Reset",
		USER_YES : "Ja",
		USER_NO : "Nein",
		USER_STYLEPATH : "Pfad zur styles.css",
		USER_PROBES : "Spioberichte",
		USER_EMAIL : "E-Mail",
		USER_ERROR1 : "Passwort falsch oder E-Mail-Adresse ungültig.",
		USER_ERROR2 : "E-Mail-Adresse ungültig.",
		USER_INGAME : "Ingame-Name",
		USER_ALLYTAG : "Allytag",
		USER_ALLYHISTORY : "zeitliche Übersichten",
		USER_DIPLOMATIC : "Diplomat",
		USER_STATSPAGE : "Anzahl Einträge auf der Statistikseite",
		USER_LINKS : "Links",
		USER_LINKS2 : "Format:<br>text;url<br>text2;url2<br>text3;url3",
		USER_EXPORT_TITLE : "Exportfarben (BB Codes)",
		USER_BB_COORDINATES : "Koordinaten",
		USER_BB_MOON : "Mond",
		USER_BB_DEBRIS : "Trümmerfeld",
		USER_BB_ALLY : "Allianzname",
		USER_BB_ALLYDETAILS : "Allianzdetails",
		USER_BB_PLAYERNAME : "Spielername",
		USER_BB_BANNED : "Gesperrt",
		USER_BB_VACATION : "Urlaubsmodus",
		USER_BB_NOOB : "Noobschutz",
		USER_BB_INACTIVE : "Inaktiv",
		USER_BB_LONGINACTIVE : "lange Inaktiv",
		USER_DELETION : "Löschen",
		USER_FLEETINFO : "Flottenbewegungen",
		USER_ACTIVITIES : "Spieleraktivitäten",
		USER_MAINTENANCE : "Wartungsmaßnahmen",
		USER_MANAGEMENT : "Benutzerverwaltung",
		USER_DELETE_MY_COMBAT_REPORTS : "Lösche meine Kampfberichte",
		USER_DELETE_MY_MESSAGES : "Lösche meine Spielernachrichten",
		USER_DELETE_MY_FLEETMOVES : "Lösche meine Flottenbewegungen",
		USER_DELETE_MY_COMBAT_REPORTS_LIMITED : "Lösche meine Kampfberichte die älter als &1 Tage sind",
		USER_DELETE_MY_MESSAGES_LIMITED : "Lösche meine Spielernachrichten die älter als &1 Tage sind",
		USER_TABLE_ENTRIES : "Anzahl von Suchergebnissen pro Seite",
		USER_EXISTS : "Es existiert bereits ein Benutzer mit diesem Namen",
		USER_BB_OUTLAW : "Vogelfrei",
		USER_INVALID_URL : "Die Adresse &1 scheint ungültig zu sein. Bitte anpassen, sonst wird sie ignoriert.",
		VIEW_TITLE : "OGame Galaxietool - Galaxieansicht",
		VIEW_NODATA : "Keine Daten vorhanden.",
		VIEW_GALAXY : "Galaxie",
		VIEW_SYSTEM : "Sonnensystem",
		VIEW_POSITION : "Pos.",
		VIEW_PLANET : "Planet",
		VIEW_MOON : "Mond",
		VIEW_TF : "TF",
		VIEW_PLAYER : "Spieler",
		VIEW_PLAYER_ADD : "(Status)",
		VIEW_ALLY : "Allianz",
		VIEW_ALLY_ADD : "",
		VIEW_METAL : "M",
		VIEW_CRYSTAL : "K",
		VIEW_COLONISED : "Planeten besiedelt",
		VIEW_UKMOONSIZE : "unbekannt",
		VIEW_BACK : "zurück",
		VIEW_NOTICE : "Notizen",
		VIEW_REPORTS : "Spionage",
		VIEW_MOONPHALANX : "Folgende Monde haben dieses System in der Phalanx",
		VIEW_NOMOONS : "Keine Monde gefunden",
		VIEW_IRAKS : "Folgende Planeten haben dieses System in Reichweite ihrer Interplanetarraketen",
		VIEW_NOIRAKS : "Keine Iraks gefunden",
		VIEW_MOON_DESTROY_CHANCE : "Mondzerstörungschancen",
		VIEW_CHANCE_WITH_ONE : "Chance mit einem Todesstern",
		VIEW_CHANCE_WITH_N : "Chance mit ",
		VIEW_DEATH_STARS : "Todessternen",
		VIEW_DS_DESTROY_CHANCE : "Todesstern Verlustchance",
		VIEW_TOP : "Top",
		VIEW_GO : "go",
		VIEW_DIAMETER : "Durchmesser",
		PW_TITLE : "OGame Galaxietool - Passwort ändern",
		OLD_PASSWORD : "Altes Passwort",
		NEW_PASSWORD : "Neues Passwort",
		CONFIRM_NEW_PASSWORD : "Neues Passwort wiederholen",
		PW_MISMATCH : "Die beiden Passwörter stimmten nicht überein!",
		PW_ERROR : "Das alte Passwort war nicht korrekt!",
		UPDATE_DONE : "Update erfolgt.",
		TIMEZONE_OFFSET : "Zeitabweichung zum Server",
		DELETE_ACCOUNT : "Diesen Galaxietoolaccount löschen",
		DELETE_ACCOUNT_SAFETY_REQUEST : "Den Account wirklich löschen?",
		CH_PASSWD_AUTHORIZATION : "Berechtigungen",
		CH_PASSWD_ADMIN : "Admin",
		TIMEZONE_OGAME_OFFSET : "Zeitabweichung zum OGame Server",
		CH_PASSWD_USER_LANGUAGE : "Wechsel zu dieser Sprache nach dem Logon",
		CH_PASSWD_USER_LANGUAGE_NO_CHANGE : "kein Wechsel",
		CH_PASSWD_EXPAND : "Sichtbar",
		CH_PASSWD_COLLAPSE : "Eingeklappt",
		CH_PASSWD_HIDDEN : "Nicht sichtbar",
		CH_PASSWD_GETTING_STARTED : "Zeige Einführungsinformationen auf der Startseite",
		CH_PASSWD_PLUGIN : "Zeige Plugininformationen auf der Startseite",
		NOTICE_TITLE : "OGame Galaxietool - Notizen",
		NOTICE_HEADER : "Notiz bearbeiten",
		NOTICE_HEADER2 : "Eigene Notizen bearbeiten",
		NOTICE_PUBLIC : "Sichtbar für andere?",
		NOTICE_YES : "ja",
		NOTICE_NO : "nein",
		NOTICE_TEXT : "Notiz Text",
		NOTICE_SAVE : "Speichern",
		NOTICE_DELETED : "Eintrag gelöscht",
		NOTICE_SAVED : "Eintrag gespeichert.",
		NOTICE_RESULTS : "Alle Einträge",
		NOTICE_USER : "Benutzer",
		NOTICE_DATE : "Datum",
		NOTICE_EDIT : "Bearbeiten",
		NOTICE_DELETE : "Löschen",
		NOTICE_NEW : "Eigenen Eintrag erstellen",
		NOTICE_NOTPUBLIC : "Notiz nicht öffentlich.",
		NOTICE_ALL : "alle",
		NOTICE_NONE : "keine",
		NOTICE_SEARCH : "Notizen durchsuchen",
		NOTICE_SEARCH_SHORT : "Suchen",
		NOTICE_HITS : "Ergebnisse",
		NOTICE_SHOWRESULTS : "Treffer pro Seite",
		NOTICE_OF : "von",
		NOTICE_NOTHING : "Keine Einträge gefunden.",
		NOTICE_CHARS : "Zeichen",
		NOTICE_PLAYERNAME : "Spieler",
		NOTICE_SHOWALL : "Zeige alle Notizen.",
		REPORTS_TITLE : "OGame Galaxietool - Spionageberichte",
		REPORTS_RESOURCES : "Rohstoffe",
		REPORTS_FLEET : "Flotten",
		REPORTS_DEFENCE : "Verteidigung",
		REPORTS_BUILDINGS : "Gebäude",
		REPORTS_TECHNOLOGY : "Forschung",
		REPORTS_MOON : "Mond",
		REPORTS_SEARCH : "Spionageberichte durchsuchen",
		REPORTS_SEARCH_SHORT : "Suchen",
		REPORTS_HITS : "Ergebnisse",
		REPORTS_NOTHING : "Keine Einträge gefunden.",
		REPORTS_ADDRESS : "Adresse",
		REPORTS_CURRENTNESS : "Aktualität",
		REPORTS_PLAYERNAME : "Spielername",
		REPORTS_ALLY : "Allianz",
		REPORTS_VIEW : "Report ansehen",
		REPORTS_SEARCH_IN : "Suche in Galaxie",
		REPORTS_FROM_SYSTEM : "von System",
		REPORTS_TO : "bis",
		REPORTS_DELETE : "löschen",
		REPORTS_DELETED : "Eintrag gelöscht.",
		REPORTS_RESULTS : "Treffer pro Seite",
		REPORTS_OF : "von",
		REPORTS_DATE : "Datum",
		REPORTS_DATE_0 : "egal",
		REPORTS_DATE_1 : "älter als",
		REPORTS_DATE_2 : "neuer als",
		REPORTS_NOTICES : "Notizen",
		REPORTS_AT_LEAST_RESOURCES : "Gesamtressourcen (mind.)",
		REPORTS_SEARCH_EXTENDED : "erweiterte Suche",
		REPORTS_FLEET_RESIS : "Flotten- punkte",
		REPORTS_DEFENCE_RESIS : "Verteidigungs- punkte",
		REPORTS_ALL_RESIS : "gesamt Punktverlust",
		REPORTS_TECHS : "Techs",
		REPORTS_UNKNOWN_ENTRIES : "unbekannte Einträge",
		REPORTS_PARTLY_INSERTED : "teilweise eingetragen",
		REPORTS_FOR_ALL_RES : "Für alle raidbaren Ressourcen",
		REPORTS_FOR_TF : "Für das TF",
		REPORTS_KT : "Kleine Transporter",
		REPORTS_GT : "Große Transporter",
		REPORTS_SS : "Schlachtschiffe",
		REPORTS_REC : "Recycler",
		REPORTS_RAIDABLE : "Nur raidbare Ziele",
		REPORTS_ALL_RESOURCES : "gesamte Ressourcen",
		REPORTS_STUFF : "Sonstiges",
		REPORTS_SPEEDSIM : "Simulieren mit Speedsim",
		REPORTS_DRAGOSIM : "Simulieren mit Dragosim",
		REPORTS_STATUS : "Status",
		REPORTS_ERROR : "Es ist ein Fehler aufgetreten.",
		REPORTS_OWN_REPORTS : "Nur eigene Reports",
		REPORTS_UPLOAD_BY : "Report eingetragen durch",
		REPORTS_DEPTH : "Reporttiefe",
		REPORTS_FLEET_SCORE : "Flottenpunkte",
		REPORTS_DEFENCE_SCORE : "Verteidigungspunkte",
		REPORTS_HOURS : "Stunden",
		REPORTS_MAX_RESULTS_HIT : "Die Suchanfrage lieferte mehr als &1 Ergebnisse. Es werden nur die ersten &1 Ergebnisse dargstellt. Bitte Suchparameter anpassen um weniger Ergebnisse zu erhalten.",
		REPORTS_OSIMULATE : "Simulieren mit OSimulate",
		REPORTS_SHOW_ONLY : "Zeige nur",
		REPORTS_SHOW_PLANETS : "Planeten",
		REPORTS_SHOW_MOONS : "Monde",
		REPORTS_OWNER : "Spionageberichte von",
		STATS_TITLE : "OGame Galaxietool - Statistiken",
		STATS_TBLHEAD : "Statistiken",
		STATS_RANK : "Platz",
		STATS_PLAYERNAME : "Spielername",
		STATS_SCORE : "Punkte",
		STATS_FLEET : "Flotte",
		STATS_RESEARCH : "Forschung",
		STATS_ALLYNAME : "Allytag",
		STATS_MEMBERS : "Mitglieder",
		STATS_STATUS : "Status",
		STATS_NOTHING : "kein Status",
		STATS_NAP : "NAP",
		STATS_ALLIED : "Verbündet",
		STATS_WAR : "Krieg",
		STATS_BOYCOTT : "Boykott",
		STATS_NEUTRAL : "Neutral",
		STATS_OWN : "Eigene Ally",
		STATS_WING : "Wing",
		STATS_UPDATE : "Daten vom",
		STATS_PLAYERSTATS : "Spielerstatistik",
		STATS_ALLYSTATS : "Allianzstatistik",
		STATS_DELETE : "Eintrag entfernen",
		STATS_CONFIRM_DELETE : "Eintrag wirklich entfernen?",
		STATS_CHANGE_PLAYER_STATUS : "Spieler Status",
		STATS_CHANGE_ALLIANCE_STATUS : "Allianz Status",
		STATS_CHANGE_ALLIANCE_STATUS_HINT : "Alle Spieler der Allianz bekommen den ausgewählten Status. Ein eventuell vorhandener Status wird dabei überschrieben. Es ist aber möglich, einzelnen Spielern der Allianz danach einen anderen Status zuzuweisen.",
		STATS_UNKNOWN : "Rest",
		STATS_DETAILS : "Details für",
		STATS_PLAYERSTATUS : "Spielerstatus",
		STATS_IGNORE_STATUS : "egal",
		STATS_ACTIVE : "aktiv",
		STATS_INACTIVE : "Inaktiv",
		STATS_BANNED : "Gesperrt",
		STATS_VACATION : "Urlaubsmodus",
		STATS_NOOB : "Noobschutz",
		STATS_YES : "Ja",
		STATS_NO : "Nur Planeten mit Notizen suchen",
		STATS_SEARCH : "Suchen",
		STATS_SHOW_GRAPH : "Details zur Punkteverteilung",
		STATS_LONG_INACTIVE : "lange Inaktiv",
		STATS_STANDARD : "Standardpunkte",
		STATS_MILITARY : "Militärpunkte",
		STATS_ECONOMY : "Ökonomie",
		STATS_HONOUR : "Ehrenpunkte",
		STATS_MILITARY_BUILD : "gebautes Militär",
		STATS_MILITARY_DESTROYED : "zerstörtes Militär",
		STATS_MILITARY_LOST : "verlorenes Militär",
		REGISTER_REGISTRATE : "Registrieren",
		REGISTER_LOGINNAME : "Login-Name",
		REGISTER_PASSWORD : "Passwort",
		REGISTER_PASSWORD_CONFIRM : "Passwort wiederholen",
		REGISTER_EMAIL : "E-Mail",
		REGISTER_INGAME : "Ingame-Name",
		REGISTER_ALLYTAG : "Allytag",
		REGISTER_EMAILVERIFICATION : "E-Mail-Check",
		REGISTER_EMAILTEXT : "Bitte klicke auf den folgenden Link um die Anmeldung am Galaxietool zu beenden.",
		REGISTER_ERROR1 : "Der Login-Benutzername ist bereits vergeben!",
		REGISTER_ERROR2 : "Fehler beim Versuch eine E-Mail abzuschicken! Bitte nimm Kontakt mit dem Serveradministrator auf.",
		REGISTER_ERROR3 : "Fehler bei der Datenbankabfrage!",
		REGISTER_INFO1 : "Der Account wurde erstellt.",
		REGISTER_INFO2 : "Bitte klicke nun auf den Link in der E-Mail um die Anmeldung abzuschließen.",
		REGISTER_INFO3 : "Account bestätigt. Jetzt muss nur noch der Admin den Account freischalten.",
		REGISTER_BUTTON : "Zurück zur Startseite",
		REGISTER_NEW_SUBJECT : "Neuer Benutzer am Galaxietool registriert",
		REGISTER_NEW_MAILTEXT : "Ein neuer Benutzer hat sich am Galaxietool registriert.",
		REGISTER_BACK : "Zurück zur Startseite",
		REGISTER_MISSING_FIELDS : "Bitte alle Felder füllen",
		REGISTER_ERROR4 : "E-Mail-Adresse ist nicht gültig.",
		REGISTER_ERROR5 : "Passwörter stimmen nicht überein.",
		REGISTER_PWS : "Passwortstärke",
		REGISTER_PWS0 : "sehr schwach",
		REGISTER_PWS1 : "schwach",
		REGISTER_PWS2 : "gut",
		REGISTER_PWS3 : "stark",
		REGISTER_PWS4 : "sehr stark",
		REGISTER_EMAIL_USED : "E-Mail Adresse wird bereits verwendet",
		LOSTPW_TITLE : "Passwort vergessen",
		LOSTPW_INFO2 : "Das neue Passwort wurde generiert und an die entsprechende E-Mail-Adresse veschickt.",
		LOSTPW_BUTTON1 : "Passwort anfordern",
		LOSTPW_BUTTON2 : "Zurück zur Startseite",
		LOSTPW_LOGINNAME : "Login-Name",
		LOSTPW_EMAIL : "E-Mail",
		LOSTPW_ERROR1 : "Fehler bei der Datenbankabfrage!",
		LOSTPW_ERROR2 : "Es wurde kein passender Eintrag gefunden!",
		LOSTPW_ERROR3 : "Fehler beim Versuch eine E-Mail abzuschicken! Bitte nimm Kontakt mit dem Serveradministrator auf.",
		LOSTPW_EMAIL_SUBJECT : "Passwortanforderung",
		LOSTPW_EMAIL_TEXT1 : "Hier die angeforderten Logindaten für das Galaxietool",
		LOSTPW_EMAIL_TEXT2 : "Nutzername",
		LOSTPW_EMAIL_TEXT3 : "Passwort",
		LOSTPW_INFO1 : "Du erhälst nun eine E-Mail zur Bestätigung um das Passwort zurückzusetzen.",
		LOSTPW_CONFIRM_RESET_SUBJECT : "Passwort vergessen?",
		LOSTPW_CONFIRM_RESET_MESSAGE : "Hallo,\n\ndu hast das Zurücksetzen deines Passworts beim Galaxytool beantragt. Um ein neues Passwort zu generieren, klicke bitte auf folgenden Link:",
		USERINFO_TITLE : "OGame Galaxietool - Benutzerinformationen",
		USERINFO_NAMES : "Alle Benutzer des Tools",
		USERINFO_DETAIL : "Detaillierte Informationen über",
		USERINFO_ERROR1 : "Kein Benutzer unter dieser ID bekannt!",
		USERINFO_USERNAME : "Loginname",
		USERINFO_INGAME : "Ingamename",
		USERINFO_EMAIL : "E-Mail",
		USERINFO_ALLYTAG : "Allianz",
		USERINFO_STYLEPATH : "Skin",
		USERINFO_STATUS : "Status",
		USERINFO_ACTIVATE : "Spieler freischalten",
		USERINFO_LOGINS : "Anzahl Logins",
		USERINFO_LASTLOGIN : "Letzter Login",
		USERINFO_DATA : "Informationen über eingebrachte Systeme",
		USERINFO_NODATA : "Der User hat bisher keine Daten hochgeladen!",
		USERINFO_GALAXY : "Galaxie",
		USERINFO_SYSTEMS : "Anzahl Systeme",
		USERINFO_IP : "IP Adresse",
		USERINFO_LOGINTIME : "Loginzeitpunkt",
		USERINFO_NOLOGIN : "Bisher nie eingeloggt.",
		USERINFO_LAST_GALAXYUPDATE : "Letzte Galaxieansicht eingebracht am",
		USERINFO_LAST_PUBLIC_NOTICE : "Letzte öffentliche Notiz am",
		USERINFO_LAST_PRIVATE_NOTICE : "Letzte private Notiz am",
		USERINFO_NUMBEROF_PUBLIC_NOTICE : "Anzahl öffentlicher Notizen",
		USERINFO_NUMBEROF_PRIVATE_NOTICE : "Anzahl privater Notizen",
		USERINFO_ACTIVATED : "Account aktiviert",
		USERINFO_ACTIVATIONTEXT : "Der Admin des Galaxietools hat deinen Account aktiviert.\n\nViel Spaß mit dem Galaxietool!",
		USERINFO_LAST_SUBMIT : "Letzte Datenübertragung",
		ALLYHISTORY_TITLE : "OGame Galaxietool - zeitliche Statistiken",
		ALLYHISTORY_TBLHEAD : "Zeitliche Übersicht",
		ALLYHISTORY_PLAYERNAME : "Spielername",
		ALLYHISTORY_ALLYNAME : "Allianz",
		ALLYHISTORY_LASTMONTH : "letzte 30 Tage",
		ALLYHISTORY_ALL_DATA : "alle verfügbaren Daten",
		ALLYHISTORY_SHOW : "zeige Statistik",
		ALLYHISTORY_TIMESPAN : "Zeitraum",
		ALLYHISTORY_PROGESS : "Fortschritt",
		ALLYHISTORY_SCORE : "Punkte",
		ALLYHISTORY_FSCORE : "Flottenpunkte",
		ALLYHISTORY_RSCORE : "Forschungspunkte",
		ALLYHISTORY_MEMBER : "Mitglieder",
		ALLYHISTORY_NOTHING : "Keine Einträge gefunden",
		ALLYHISTORY_DETAILS : "Details",
		ALLYHISTORY_SHOW_ADDRESS : "Koordinaten",
		ALLYHISTORY_ESCORE : "Ökonomie",
		ALLYHISTORY_MSCORE : "Militärpunkte",
		DETAILEDINFO_PLAYERINFO_TITLE : "Spielerinformationen",
		DETAILEDINFO_ALLYINFO_TITLE : "Allianzinformationen",
		DETAILEDINFO_PLAYERINFO_TBLHEAD : "Detaillierte Informationen zum Spieler",
		DETAILEDINFO_ALLYINFO_TBLHEAD : "Detaillierte Informationen zur Allianz",
		DETAILEDINFO_NO_ALLIANCE : "keine",
		DETAILEDINFO_SCORE : "Punktestatistik",
		DETAILEDINFO_FLEET : "Flottenstatistik",
		DETAILEDINFO_RESEARCH : "Forschungsstatistik",
		DETAILEDINFO_RANK : "Platz",
		DETAILEDINFO_POINTS : "Punkte",
		DETAILEDINFO_KNOWN_PLANETS : "bekannte Planeten",
		DETAILEDINFO_MOONS : "bekannte Monde",
		DETAILEDINFO_PHALANX_AREA : "Phalanxbereiche",
		DETAILEDINFO_NO_PHALANX_AREA : "keine Phalanxen gefunden",
		DETAILEDINFO_NOTICES : "Notizen",
		DETAILEDINFO_NO_NOTICES : "keine Notizen vorhanden",
		DETAILEDINFO_PREVIOUS_ALLIANCES : "bekannte Allianzzugehörigkeiten",
		DETAILEDINFO_RESOURCES_PER_HOUR : "Ressourcen pro Stunde",
		DETAILEDINFO_RESOURCES_PER_DAY : "Ressourcen pro Tag",
		DETAILEDINFO_RESOURCES_PER_WEEK : "Ressourcen pro Woche",
		DETAILEDINFO_RESOURCES_PER_MONTH : "Ressourcen pro Monat (30 Tage)",
		DETAILEDINFO_METAL : "Metall",
		DETAILEDINFO_CRYSTAL : "Kristall",
		DETAILEDINFO_DEUTERIUM : "Deuterium",
		DETAILEDINFO_UNKNOWN : "unbekannt",
		DETAILEDINFO_SCORE_DISTRIBUTION : "Punkteverteilung",
		DETAILEDINFO_GENERAL : "Details",
		DETAILEDINFO_MEMBERS : "Mitglieder",
		DETAILEDINFO_GRAPHS : "Diagramme",
		DETAILEDINFO_RESOURCES : "Ressourcen",
		DETAILEDINFO_FLEET_TAB : "Flotte",
		DETAILEDINFO_TECH : "Forschung",
		DETAILEDINFO_FLEET_DETAIL : "Entspricht der Summe / (Spielerdurchschnitt) aus allen verfügbaren Reports",
		DETAILEDINFO_TECH_DETAIL : "Entspricht dem Durchschnitt aller vefügbaren Spielerinformationen",
		DETAILEDINFO_PLANET_TAB : "Planeten",
		DETAILEDINFO_MOON_TAB : "Monde",
		DETAILEDINFO_ACTIVITIES : "Aktivitäten",
		DETAILEDINFO_NODATA : "Keine Daten vorhanden.",
		DETAILEDINFO_ACTIVITY_DESCRIPTION : "Zeige Aktivitäten von &1 im Zeitraum:",
		DETAILEDINFO_GALAXYVIEWS : "Galaxieansichten",
		DETAILEDINFO_SCANS : "Spionageaktionen",
		DETAILEDINFO_MESSAGES : "Spielernachrichten",
		DETAILEDINFO_COMBATS : "Kampfberichte",
		DETAILEDINFO_ALLYPAGE : "Allianzübersicht",
		DETAILEDINFO_MANUAL : "Manuelle Eingaben",
		DETAILEDINFO_START : "Anfang",
		DETAILEDINFO_TO : "bis",
		DETAILEDINFO_TODAY : "Heute",
		DETAILEDINFO_DATA_RESTRICTION : "eingeschränkt auf:",
		DETAILEDINFO_WEEKDAY_WEEKEND : "Wochenende",
		DETAILEDINFO_WEEKDAY_WORKINGDAY : "Wochentag",
		DETAILEDINFO_WEEKDAY_MONDAY : "Montag",
		DETAILEDINFO_WEEKDAY_TUESDAY : "Dienstag",
		DETAILEDINFO_WEEKDAY_WEDNESDAY : "Mittwoch",
		DETAILEDINFO_WEEKDAY_THURSDAY : "Donnerstag",
		DETAILEDINFO_WEEKDAY_FRIDAY : "Freitag",
		DETAILEDINFO_WEEKDAY_SATURDAY : "Samstag",
		DETAILEDINFO_WEEKDAY_SUNDAY : "Sonntag",
		DETAILEDINFO_WEEKDAY_SHORTLENGTH : 2,
		DETAILEDINFO_PLAYER_CURRENTLY_ACTIVE : "Der Spieler ist derzeit aktiv",
		DETAILEDINFO_PLAYER_MESSAGES : "vorhandene Spielernachrichten",
		DETAILEDINFO_SHOW : "anzeigen",
		DETAILEDINFO_NONE : "keine vorhanden",
		DETAILEDINFO_ENTER_MANUALLY : "Erfasse weitere Onlinezeiten dieses Spielers",
		DETAILEDINFO_PLAYER_SEEN_ON : "Spieler war online am",
		DETAILEDINFO_INSERT : "Eintragen",
		DETAILEDINFO_OGAME_SERVERTIMES : "Hinweis: Alle hier erfassten Zeiten beziehen sich auf die OGame Serverzeiten!",
		DETAILEDINFO_DAY_VIEW : "24-Stunden-Ansicht",
		DETAILEDINFO_WEEK_VIEW : "Wochenansicht",
		DETAILEDINFO_HOME_PLANET : "Heimatplanet",
		DETAILEDINFO_PLANETNAME : "Name",
		DETAILEDINFO_DEFENCE_SCORE : "Verteidigungspunkte",
		DETAILEDINFO_DEFENCE_SCORE_TOOLTIP : "Verteidigungspunkte berechnen sich aus Flottenpunkten - Gesamtpunkte + Ökonomie + Forschung<br/>All diese Statistiken müssen aktuell sein um ein sinnvolles Ergebnis zu erhalten!",
		DETAILEDINFO_SCORE_PER_SHIP : "Punkte pro Schiff",
		DETAILEDINFO_SHIPS : "Anzahl Schiffe",
		DETAILEDINFO_DATE_IN_FUTURE : "Bitte keine Zeiten in der Zukunft erfassen.",
		ADMIN_TITLE : "Administration des Galaxietools",
		ADMIN_DISCLAMER : "Achtung: Das Ausführen dieser Skripte erfolgt auf eigene Gefahr. Die meisten dieser Skripte löschen Daten unwiderruflich!",
		ADMIN_INCONSISTENCIES : "Inkonsistenzen im Galaxietool",
		ADMIN_PLANETS : "Planeten auf Position 0 oder größer als 15 löschen",
		ADMIN_GALAXIES : "Galaxien größer als &1 löschen",
		ADMIN_PLAYERS : "Entferne Spieler ohne OGame ID - führte häufig zu doppelten Spielereinträgen",
		ADMIN_REPORTS : "Spionageberichte löschen, zu denen kein Planet mehr existiert",
		ADMIN_MISC : "Sonstiges",
		ADMIN_RESET : "Reset des Galaxietools (nur Benutzertabelle und IP Tabelle bleiben erhalten!)",
		ADMIN_OLD_PLAYERS : "Spielereinträge älter als &1 Tage löschen",
		ADMIN_OLD_REPORTS : "Reports älter als &1 Tage löschen",
		ADMIN_LOADING : "Fenster erst schließen nachdem die Seite geladen wurde!",
		ADMIN_STATUS : "Status der einzelnen Anfragen",
		ADMIN_SELECTION : "Mindestens einen Eintrag auswählen",
		ADMIN_SAFETY : "Wirklich durchführen?",
		ADMIN_DONE : "fertig",
		ADMIN_NOTBD : "nichts zu tun",
		ADMIN_OLD_GALAXIES : "Entferne Galaxieansichten, die älter als &1 Tage sind",
		ADMIN_UNUSED_PLAYERS : "Entferne Spieler, die in keiner Galaxieansicht mehr vorkommen",
		ADMIN_OLD_ACTIVITIES : "Entferne Spieleraktivitäten, die älter als &1 Tage sind",
		ADMIN_OLD_COMBATS : "Entferne Kampfberichte, die älter als &1 Tage sind",
		ADMIN_OLD_INGAME_MSG : "Entferne Spielernachrichten, die älter als &1 Tage sind",
		ADMIN_OGAME_API : "Lade verfügbare Daten aus OGame ins Galaxietool",
		ADMIN_OGAME_ALL_DATA : "alle verfügbaren Daten",
		ADMIN_OGAME_GALAXY_DATA : "Galaxieansicht",
		ADMIN_OGAME_STATISTICS_DATA : "Statistiken",
		ERRORPAGE_PAGEFORWARD : "Sollte der Browser keine Weiterleitung unterstützen, klicke bitte hier.",
		ERRORPAGE_PERMISSION_DENIED : "Du hast nicht die benötigten Rechte diese Seite zu betreten. Klicke hier um zurück zu gelangen.",
		FLEETS_TITLE : "OGame Galaxietool - Flottenbewegungen",
		FLEETS_ACTUAL_FLEETS : "aktuelle Flottenbewegungen",
		FLEETS_YES : "Ja",
		FLEETS_NO : "Nur Planeten mit Notizen suchen",
		FLEETS_DETAILS : "Flottendetails",
		FLEETS_MISSION_EXPEDITION : "Expedition",
		FLEETS_MISSION_COLONIZATION : "Kolonisieren",
		FLEETS_MISSION_RECYCLE : "Abbauen",
		FLEETS_MISSION_TRANSPORT : "Transport",
		FLEETS_MISSION_DEPLOYMENT : "Stationieren",
		FLEETS_MISSION_ESPIONAGE : "Spionage",
		FLEETS_MISSION_ACS_DEFEND : "AKS Verteidigung",
		FLEETS_MISSION_ATTACK : "Angriff",
		FLEETS_MISSION_ACS_ATTACK : "AKS Angriff",
		FLEETS_MISSION_MOON_DESTRUCTION : "Mondzerstörung",
		FLEETS_MISSION_MISSILE_ATTACK : "Raketenangriff",
		FLEETS_NO_DATA : "Keine Informationen vorhanden",
		FLEETS_FLEET : "Flotte",
		FLEETS_ALL_FLEETS : "zeige alle Flottenbewegungen",
		COMBAT_REPORT_OUDATED_GALAXYVIEW : "Die Galaxieansichten sind veraltet. Bitte zuerst die Galaxieansichten der Angreifer und Verteidiger besuchen.",
		MESSAGES_TITLE : "OGame Galaxietool - OGame Nachrichten",
		MESSAGES_PLAYERNAME : "Spielername",
		MESSAGES_SUBJECT : "Betreff",
		MESSAGES_DATE : "Datum",
		MESSAGES_FILTER : "Filter",
		MESSAGES_DELETE : "Nachricht löschen",
		MESSAGES_PUBLISH_DETAIL : "Die Nachricht veröffentlichen, indem der Nachrichteninhalt an die Notizen des Spielers angefügt wird.",
		MESSAGES_PUBLISH_HEADER : "&sender hat &recipient am &date folgende Nachricht gesendet:\n\n &message",
		MESSAGES_PLAYER_FILTER : "Nachrichten von Spieler:",
		MESSAGES_CONTENT : "Inhalt",
		COMBATS_TITLE : "OGame Galaxietool - Kampfberichte",
		COMBATS_ATTACKER : "Angreifer",
		COMBATS_DEFENDER : "Verteidiger",
		COMBATS_DATE : "Datum",
		COMBATS_OWNER : "Besitzer",
		COMBATS_WINNER : "Gewinner",
		COMBATS_COMBATREPORT : "Kampfbericht",
		COMBATS_COMBAT_AT : "Schlacht um",
		COMBATS_LOST_UNITS : "Einheiten verloren",
		COMBATS_LOOT : "Beute",
		COMBATS_DEBRIS : "Trümmerfeld",
		COMBATS_AND : "und",
		COMBATS_PUBLISH : "Kampfbericht veröffentlichen",
		COMBATS_UNPUBLISH : "Kampfberichtveröffentlichung zurücknehmen (wieder auf privat stellen)",
		COMBATS_DELETE : "Kampfbericht löschen",
		COMBATS_CHECK_ALL : "Alle auswählen",
		COMBATS_UNCHECK_ALL : "Alle abwählen",
		COMBATS_WITH_SELECTED : "Mit Auswahl",
		COMBATS_PUBLIC_REPORTS : "Öffentliche KBs",
		COMBATS_YES : "Ja",
		COMBATS_NO : "Nur Planeten mit Notizen suchen",
		COMBATS_SEARCH_OPTIONS : "Suchparameter",
		COMBATS_SEARCH : "Suchen",
		COMBATS_RESET : "Zurücksetzen",
		COMBATS_COORDINATES : "Koordinaten",
		COMBATS_INVALID_GALAXY_ENTERED : "Ungültige Galaxie angegeben",
		COMBATS_INVALID_SYSTEM_ENTERED : "Ungültiges System angegeben",
		COMBATS_INVALID_PLANET_ENTERED : "Ungültigen Planeten angegeben",
		COMBATS_GALAXY_FROM_TO : "Galaxie",
		COMBATS_SYSTEM_FROM_TO : "System",
		COMBATS_PLANET_FROM_TO : "Planet",
		COMBATS_APPLY : "Übernehmen",
		COMBATS_COMBAT_SUMMARY : "Kampfberichtszusammenfassung",
		COMBATS_DOWNLOAD_CSV : "Als CSV Datei herunterladen",
		REPORT_ARCHIVE_TITLE : "Scanberichtsarchiv",
		REPORT_ARCHIVE_COORDINATES : "Koordinaten",
		REPORT_ARCHIVE_SCANTIME : "Scanzeitpunkt",
		REPORT_ARCHIVE_DELETE : "Einträge entfernen",
		REPORT_ARCHIVE_CONFIRM_DELETE : "Einträge wirklich entfernen?",
		REPORT_ARCHIVE_GALAXY : "Galaxie",
		REPORT_ARCHIVE_SYSTEM : "System",
		REPORT_ARCHIVE_PLANET : "Planet",
		REPORT_ARCHIVE_MOON : "Mond",
		REPORT_ARCHIVE_DETAILS : "Details",
		REPORT_ARCHIVE_RESOURCES : "Ressourcen pro Stunde",
		REPORT_ARCHIVE_HEADER_RESOURCES : "Rohstoffe",
		REPORT_ARCHIVE_DETAILS_FOR : "Scanberichtsarchiv für &1 [&2] (&3)",
		REPORT_ARCHIVE_FLEET_CARGO : "Ladakapazität der Flotte",
		REPORT_ARCHIVE_IRAK_RANGE : "Interplanetarraketenreichweite",
		REPORT_ARCHIVE_CHART_TYPE : "Diagrammart",
		INSTALL_TITLE : "Installation der Galaxietool Version",
		INSTALL_PROGRESS : "Installationsfortschritt",
		INSTALL_STEP : "Schritt",
		INSTALL_CONTINUE : "Weiter",
		INSTALL_VALIDATE : "Prüfen",
		INSTALL_STEP1 : "Willkommen",
		INSTALL_STEP2 : "Schreibbarkeitsprüfung",
		INSTALL_STEP3 : "Datenbankeinstellungen",
		INSTALL_STEP4 : "OGame Einstellungen",
		INSTALL_STEP5 : "Galaxietool Einstellungen",
		INSTALL_STEP6 : "Admin Passwort",
		INSTALL_STEP7 : "Installation des Galaxietools",
		INSTALL_STEP8 : "Abschluss der Installation",
		INSTALL_FILE_DELETE_CHECK : "Bitte lösche die install.php und update.php von deinem Webserver.",
		INSTALL_STEP1_PHP_FAILED : "Deine PHP Version &1 ist nicht kompatibel zu dieser Galaxietoolversion",
		INSTALL_STEP1_FOPEN_FAILED : "Deine PHP Version erlaubt nicht das Öffnen anderer Webseiten mit dem FOPEN() Befehl. Diese Funktionalität wird benötigt um das OGame API zu nutzen.",
		INSTALL_STEP1_WELCOME : "Willkommen bei der Installation des Galaxietools. Du wirst schrittweise durch die Installation geführt werden und bei einzelnen Schritten gibt es Links zu weiterführenden Informationen.",
		INSTALL_STEP2_DESCRIPTION : "Bitte stell sicher, dass die config.php und attributes.php Dateien durch den Webserver beschreibbar sind.",
		INSTALL_STEP2_DESCRIPTION2 : "Solltest du nicht genau wissen wie du die Dateien oder das Verzeichnis fürs Schreiben freigeben kannst, schau bitte hier: &1",
		INSTALL_STEP2_FILE_NOT_WRITEABLE : "Datei ist nicht beschreibbar",
		INSTALL_STEP3_SERVER : "Datenbankserver",
		INSTALL_STEP3_USERNAME : "Nutzername",
		INSTALL_STEP3_PASSWORD : "Passwort",
		INSTALL_STEP3_DBNAME : "Datenbankname",
		INSTALL_STEP3_PREFIX : "Prefix für Tabellennamen",
		INSTALL_STEP3_ENTER_PREFIX : "z.B. MeinTool1_",
		INSTALL_STEP3_ENTER_SERVER : "Server Adresse, frage deinen Systemadministrator falls nötig. Typischerweise ist localhost der korrekte Wert.",
		INSTALL_STEP3_ENTER_USERNAME : "Nutzername für den Datenbankzugang",
		INSTALL_STEP3_ENTER_PASSWORD : "Passwort für den Datenbankzugang",
		INSTALL_STEP3_ENTER_DBNAME : "Name der Datenbank, in die das Galaxietool installiert werden soll. (muss existieren)",
		INSTALL_STEP3_CONNECT_FAILED : "Verbindung zum Datenbankserver konnte nicht hergestellt werden.",
		INSTALL_STEP3_DB_FAILED : "Datenbank &1 nicht gefunden",
		INSTALL_STEP3_MYSQL_VERSION_FAILED : "MySQL Version &1 ist nicht kompatibel zu dieser Galaxietoolversion",
		INSTALL_STEP4_URL : "OGame URL",
		OGAME_URL_DETAILS : "Bitte füge hier eine Internetadresse deines OGame Servers ein. Dazu kannst du die Adresse einer beliebigen Seite verwenden, sobald du bei OGame eingeloggt bist. Basierend auf dieser Adresse wird das Galaxietool die OGame API Adresse ableiten, mit der das Galaxietool auch ohne die Galaxietoolbar gefüllt werden kann. Das API wurde mit OGame Version 4.1 eingeführt.",
		INSTALL_STEP4_UNIVERSE : "OGame Universum",
		INSTALL_STEP4_DEF_TO_DEBRIS : "Verteidigung geht ins Trümmerfeld",
		INSTALL_STEP4_DEBRIS_RATE : "Trümmerfeldrate",
		INSTALL_STEP4_SPEED_RATE : "Geschwindigkeitsfaktor",
		INSTALL_STEP4_ENTER_UNIVERSE : "Bitte trage hier den Namen es Universums ein. Bei älteren Unis ist das nur eine Zahl. (Achte auf Groß- und Kleinschreibung)",
		INSTALL_STEP4_UNIVERSE_MISSING : "Das Universum fehlt",
		INSTALL_STEP4_ENTER_URL : "Bitte trage die URL des deines OGame Servers ein",
		INSTALL_STEP4_URL_MISSING : "Die OGame URL fehlt",
		INSTALL_STEP4_URL_CHECK_FAILED : "Konnte die OGame APIs nicht finden unter &1",
		INSTALL_STEP4_GETSETTINGS : "Einstellungen laden",
		INSTALL_STEP5_TOOLNAME : "Galaxietool Name",
		INSTALL_STEP5_ENTER_TOOLNAME : "Dieser Name wird auf der Startseite deines Galaxietools zu sehen sein.",
		INSTALL_STEP5_LANGUAGE : "Standardsprache",
		INSTALL_STEP5_EMAIL_TO : "E-Mail-Empfänger",
		INSTALL_STEP5_ENTER_EMAIL_TO : "An diese E-Mail-Adresse werden Nachrichten über neu registrierte Mitglieder geschickt.",
		INSTALL_STEP5_EMAIL_FROM : "Emailabsender",
		INSTALL_STEP5_ENTER_EMAIL_FROM : "Diese E-Mail-Adresse wird als Absender aller E-Mails des Galaxietools angezeigt",
		INSTALL_STEP5_USE_PHPMAILER : "Nutze PHPMailer",
		INSTALL_STEP5_MAXSHOUTS : "Maximale Anzahl von Einträgen in der Nachrichtenbox",
		INSTALL_STEP5_ENTER_USE_PHPMAILER : "Nutze den PHPMailer falls dein Server keine Unterstützung für das Versenden von E-Mails via PHP hat.",
		INSTALL_PHPMAILER_HOST : "SMPT Host",
		INSTALL_PHPMAILER_HOST_EXAMPLE : "z.B. smtp.provider.de",
		INSTALL_PHPMAILER_USER : "SMPT Nutzername",
		INSTALL_PHPMAILER_USER_EXAMPLE : "z.B. user@provider.de",
		INSTALL_PHPMAILER_PASS : "SMPT Passwort",
		INSTALL_PHPMAILER_SECURE : "Authentifizierungsmethode, z.B. ssl",
		INSTALL_PHPMAILER_PORT : "SMTP Port",
		INSTALL_STEP6_INTRO : "Bitte lege ein Passwort für den <strong>admin</strong> Account fest, mit dem du dich nach der Installation am Galaxietool anmelden musst.",
		INSTALL_STEP7_CONFIG : "Konfigurationsdatei wurde erzeugt",
		INSTALL_STEP7_CONFIG_FAILED : "Konfigurationsdatei wurde nicht erzeugt",
		INSTALL_STEP7_ATTRIBUTES : "Attributdatei wurde erzeugt",
		INSTALL_STEP7_ATTRIBUTES_FAILED : "Attributdatei wurde nicht erzeugt",
		INSTALL_STEP7_CREATED_TABLES : "Datenbanktabellen wurde erzeugt",
		INSTALL_STEP8_INTRO : "Du hast die Installation des Galaxietools erfolgreich abgeschlossen!",
		INSTALL_STEP8_LOAD_DATA : "Importieren der OGame Daten via OGame API ...",
		INSTALL_STEP8_LOAD_DATA_FINISHED : "Import der OGame Daten abgeschlossen",
		INSTALL_STEP8_DELETE_FILE : "Du solltest jetzt die Installationsdateien install.php sowie update.php von deinem Webserver löschen.",
		INSTALL_STEP8_LOGON : "Bitte melde dich nun mit dem <strong>admin</strong> Nutzer und dem zuvor festgelegten Passwort an.",
		UPDATE_START : "Beginne das Update auf Version &1",
		UPDATE_STEP_DONE : "Erledigt",
		UPDATE_TITLE : "Galaxietoolupdate für Version",
		UPDATE_STEP1_WELCOME : "Willkommen beim Updateassistenten für das Galaxietool. Du wirst ab hier durch das Update des Galaxietools geleitet.",
		UPDATE_STEP1_BACKUP_FILES : "Erstelle als erstes eine Sicherheitskopie des <strong>config</strong> Verzeichnisses! Im Falle von Fehlern musst du diese jederzeit wiederherstellen können.",
		UPDATE_STEP1_BACKUP_DB : "Danach erstelle eine <a href=\"http://doku.wpde.org/Backup_der_Datenbank/phpMyAdmin\">Sicherheitskopie</a> der Datenbankdaten.",
		UPDATE_STEP1_PROCEED : "Nachdem alle Sicherheitskopien erzeugt wurden, kann das Update fortgesetzt werden.",
		UPDATE_STEP1 : "Willkommen",
		UPDATE_STEP2 : "Galaxietool Einstellungen",
		UPDATE_STEP2_OLD_VERSION : "Vorherige Galaxietool Version",
		UPDATE_STEP3 : "Update des Galaxietools",
		UPDATE_STEP3_UPDATE_RUNNING : "Update läuft. Bitte warten...",
		UPDATE_STEP4 : "Update abschließen",
		UPDATE_STEP4_INTRO : "Du hast das Update erfolgreich abgeschlossen!",
		UPDATE_STEP4_UPDATE_DONE : "Alle Updateschritte abgeschlossen.",
		UPDATE_FAILED : "Update fehlgeschlagen.",
		GALAXYTOOL_DUMMY_TEXT : "dummy"
	})
);