define(
	({
		REPORT_WHEN : "на",
		RESOURCES_ON : "Ресурси на",
		PLAYER_BANNED : "б",
		PLAYER_VACATION_MODE : "в",
		PLAYER_NOOB : "н",
		PLAYER_INACTIVE : "i",
		PLAYER_LONG_INACTIVE : "I",
		PLAYER_OUTLAW : "o",
		L_USERNAME : "Потребителско име",
		L_PASSWORD : "Парола",
		L_LOGINFAILURE : "Потребителското име или паролата са погрешни, или акаунтът Ви още не е активиран.",
		L_TOKENFAILURE : "Ключът Ви за влизане е погрешен или акаунтът Ви още не е активиран.",
		L_LOGINTEXT : "Моля, регистрирайте се.",
		L_LANGUAGE : "Достъпни езици:",
		L_TIMEOUT : "Времето на сесията е изтекло!",
		L_REGISTER : "Регистриране",
		L_PWLOST : "Изгубена парола",
		INDEX_TITLE : "OGame Galaxietool - Изглед",
		INDEX_INFO : "Информация",
		INDEX_ENTRIES : "Общ брой звездни системи",
		INDEX_ENTRIES_LASTWEEK : "Нови звездни системи за тази седмица",
		INDEX_ENTRIES_TO_OLD : "Звездни системи по-стари от месец",
		INDEX_REGISTERED_USERS : "Регистрирани потребители",
		INDEX_PAGEFORWARD : "Ако броузерът Ви не поддържа пренасочване на страници, моля цъкнете тук.",
		INDEX_NOTICES : "Бележки",
		INDEX_PLAYERS : "Статистики за играчите",
		INDEX_ALLIES : "Статистики за съюзите",
		INDEX_REPORTS : "Шпионски доклади",
		INDEX_VERSION : "Най-нова версия за изтегляне",
		INDEX_LATEST_VERSION : "Няма по-нова версия",
		INDEX_SHOUTBOX : "Място за обявления",
		INDEX_NOENTRY : "Все още няма обявления",
		INDEX_COMMENT : "Вашето обявление",
		INDEX_INSERT : "Добави",
		INDEX_UMOD : "Играчи във ваканционен режим",
		INDEX_NO_MOONS : "Брой луни",
		INDEX_NO_EMPTY_SYSTEMS : "Брой празни звездни системи",
		INDEX_NO_FULL_SYSTEMS : "Брой напълно запълнени системи",
		INDEX_NO_TARGETS : "Брой възможни цели",
		INDEX_USERINFO : "Брой потребители",
		INDEX_ONLINE : "На линия в момента",
		INDEX_TODAY : "На линия днес",
		INDEX_ALL : "Общ брой влизания",
		GENERAL_LOAD_FORM : "Зареждане на данните за формата",
		GENERAL_SAVE_FORM : "Запазване на данните за формата",
		GENERAL_SAVE_AS_TEXT : "Запазване като",
		GENERAL_SAVE : "Запазване",
		INDEX_USERMANAGEMENT : "Активиране",
		INDEX_NEEDADMIN : "Акаунти за отключване",
		INDEX_NEEDEMAIL : "Невалидирани акаунти",
		INDEX_TOOLBAR_INFO : "Информация за плъгина за Galaxytool",
		INDEX_TOOLBAR_URL : "Galaxytool URL",
		INDEX_TOOLBAR_VERSION_REQUIRED : "Минимална изисквана версия на плъгина за Galaxytool",
		INDEX_TOOLBAR_INSTALL_GUIDE : "Инструкции за инсталиране на плъгина",
		INDEX_TOOLBAR_TOKEN : "Ключ за влизане",
		INDEX_TOOLBAR_NEW_TOKEN : "Получаване на нов ключ",
		INDEX_PLAYERS_WITH_N_PLANETS : "Играчи с повече от &1 планети",
		INDEX_GETTING_STARTED : "Започване на работа с Galaxytool",
		INDEX_GETTING_STARTED1 : "Добре дошли в Galaxytool!",
		INDEX_GETTING_STARTED2 : "Galaxytool ще Ви помогне да анализирате какво става във вашата OGame вселена &1",
		INDEX_GETTING_STARTED3 : "Преди да можете да анализирате данните, първо трябва да ги въведете. За това Ви е необходим плъгин за броузера, като например &1 за Firefox.",
		INDEX_GETTING_STARTED4 : "След като сте инсталирали плъгина, разглеждайте страниците на OGame както обикновено и ще виждате малко статус-прозорче всеки път, когато нещо бъде изпратено на Galaxytool.",
		INDEX_GETTING_STARTED5 : "След като плъгинът е добавил данните в Galaxytool, можете да започнете да анализирате къде играчите имат планети, колко планети имат, какви шпионски доклади има за тях и кога са най-активни.",
		INDEX_GETTING_STARTED6 : "Също така, Galaxytool ще Ви помогне да определите как се развивате, ако сравните себе си със своите конкуренти или като анализирате докладите си от битките, за да видите колко сте заграбили през последните дни или седмици.",
		INDEX_GETTING_WIKIPAGE : "Galaxytool има още много възможности.",
		INDEX_GETTING_WIKIPAGE2 : "Разгледайте описанието му на нашата wiki страница.",
		INDEX_GETTING_BOARD : "За забележки и идеи можете да използвате нашия форум:",
		INDEX_GETTING_CHAT1 : "Или ни посетете в стаята за разговори:",
		INDEX_GETTING_CHAT2 : "Не сме на линия денонощно, но прекарваме голяма част от свободното си време там, така че бъдете търпеливи.",
		INDEX_CLOSE : "Затваряне",
		INDEX_LOGIN : "Влизане",
		GENERAL_REQUIRED_FIELDS : "Моля, попълнете всички задължителни полета",
		INDEX_MESSAGES : "Съобщения",
		INDEX_EXAMPLE : "Пример",
		INDEX_INVALID_DATA : "Невалидни данни",
		GENERAL_COLUMN_HIDE_TITLE : "Управление видимостта на колонките",
		GENERAL_COLUMN_HIDE_INFO : "Моля, изберете кои колонки искате да се виждат в таблицата.",
		GENERAL_ENTRIES_DELETED : "&1 изтрити",
		GENERAL_APPLY : "Прилагане",
		STARTPAGE_GALAXYTOOL_DESCR : "<em>Galaxytool</em> е инструмент за броузерната игра OGame.",
		GENERAL_OVERWRITE : "Презапис върху дублирани данни",
		GENERAL_OVERWRITE_QUESTION : "Презапис?",
		INDEX_OWN_LOGINS : "Вашите влизания",
		GENERAL_OPEN_IN_NEW_WINDOW : "Отваряне в нов прозорец",
		GENERAL_UNIT_OF_MEASURE_DAYS : "Days",
		PROGRAM_NAME : "OGame Galaxytool",
		SHORTNAME : "Galaxytool",
		BACK_INDEX : "Към главната страница",
		UNIVERSE : "Вселена",
		MENU_INFO_LINKS : "Информация",
		MENU_PAGE : "Изглед",
		MENU_DB_SEARCH : "Търсене в базата данни",
		MENU_DB_NOTICES : "Търсене в бележките",
		MENU_DB_REPORTS : "Търсене в шпионските доклади",
		MENU_GALAXYVIEW : "Преглед на галактиката",
		MENU_STATISTICS : "Статистика",
		MENU_ALLYHISTORY : "Исторически преглед",
		MENU_FLEET_MOVEMENTS : "Местене на флота",
		MENU_COMBAT_REPORTS : "Доклади от битките",
		MENU_MESSAGES : "Игрови съобщения",
		MENU_OPTION_LINKS : "Опции",
		MENU_DB_REFRESH : "Добавяне към базата данни",
		MENU_NOTICES : "Бележки",
		MENU_DB_STATUS : "Статус на базата данни",
		MENU_USEROPTIONS : "Управление на потребителите",
		MENU_USEROPTIONS2 : "Опции на текущия потребител",
		MENU_USEROPTIONS3 : "Информация за потребителите",
		MENU_ADMIN : "Администрация",
		MENU_LOGOUT : "Излизане",
		MENU_STUFF : "Разни",
		MENU_FORUM_THREAD : "Форум на разработчиците",
		MENU_DOWNLOADPAGE : "Страница за изтегляне на програмата",
		MENU_LANGUAGE : "Език",
		MENU_HELP : "Помощ",
		MENU_TOOLOPTIONS : "Опции за Galaxytool",
		PARSER_INFO1 : " беше добавен в базата данни",
		PARSER_ERROR1 : "Грешка при опит за добавяне на следните координати:",
		PARSER_ERROR2 : "Базата данни не може да бъде намерена!",
		PARSER_ERROR3 : "Сърверът за базата данни не може да бъде намерен!",
		PARSER_WRONG_UNIVERSE : "Погрешна вселена - намерена: \"&1\" очаквана: \"&2\"",
		SHOW_TITLE : "OGame Galaxytool - Търсене",
		SHOW_SEARCH : "Търсене в базата данни",
		SHOW_ALLYSYMBOL : "Таг на съюза",
		SHOW_PLAYERNAME : "Име на играч",
		SHOW_MOONS : "Само планети с луна",
		SHOW_NOTICES : "Само планети с бележки",
		SHOW_COLONIES : "Само планети, годни за колонизиране",
		SHOW_YES : "Да",
		SHOW_NO : "Не",
		SHOW_SEARCHRANGE : "Диапазон",
		SHOW_SEARCH_IN : "Търсене в галактиката",
		SHOW_FROM_SYSTEM : "от звездна система",
		SHOW_FROM_PLANET : "от позиция на планетата",
		SHOW_TO : "до",
		SHOW_DESCRIPTION : "Можете да използвате * в имената на играчите и съюзите. Така можете да намерите всички имена, съдържащи указания низ.<br />Попълнете само полетата, които искате да бъдат използвани.",
		SHOW_SORT_BY : "Подреждане според",
		SHOW_GALASYSTEM : "Галактика/Звездна система",
		SHOW_ALLYNAME : "Име на съюз",
		SHOW_SEARCHBUTTON : "Търсене",
		SHOW_ADDRESS : "Координати",
		SHOW_ALLYSORT : "Съюз",
		SHOW_PLANET : "Име на планета",
		SHOW_STATUS : "Статус",
		SHOW_CURRENTNESS : "Последно обновявано",
		SHOW_PLAYER_STATUS : "Статус на играча",
		SHOW_PLAYER_STATUS1 : "всички",
		SHOW_PLAYER_STATUS2 : "Възможни цели",
		SHOW_PLAYER_STATUS3 : "Неактивни",
		SHOW_HITS : "Намерени",
		SHOW_OF : "от общо",
		SHOW_ASC : "нарастващо",
		SHOW_DESC : "намаляващо",
		SHOW_RESULTS : "Брой намерени на страница",
		SHOW_MOON : "Луна",
		SHOW_UKMOONSIZE : "неизвестен",
		SHOW_DF : "ПО",
		SHOW_DF_LONG : "Поле отломки",
		SHOW_METAL : "М",
		SHOW_METAL_LONG : "Метал",
		SHOW_CRYSTAL : "К",
		SHOW_CRYSTAL_LONG : "Кристали",
		SHOW_BOTH : "Общо",
		SHOW_AT_LEAST : "(поне)",
		SHOW_DATE : "Дата",
		SHOW_DATE_0 : "без значение",
		SHOW_DATE_1 : "по-стари от",
		SHOW_DATE_2 : "по-нови от",
		SHOW_RANK : "Ранг",
		SHOW_FRANK : "Ранг флот",
		SHOW_MEMBERS : "Членове",
		SHOW_NOTRANKED : "няма данни",
		SHOW_NOTICERES : "Бележки",
		SHOW_REPORTS : "Само шпионирани планети",
		SHOW_REPORTS_SHORT : "Шпионски доклади",
		SHOW_NOTHING : "Не е намерено",
		SHOW_ALLIANCE_STATUS : "Статус на съюза",
		SHOW_NO_STATUS : "няма статус",
		SHOW_NAP : "ПНН",
		SHOW_ALLIED : "Съюзник",
		SHOW_WAR : "Война",
		SHOW_BOYCOTT : "Бойкот",
		SHOW_NEUTRAL : "Неутрален",
		SHOW_OWN : "Собствен съюз",
		SHOW_WING : "Помагач",
		SHOW_EXT_OPTIONS1 : "Показване на още опции за търсене според данните за диапазон, ранг, дата или поле отломки.",
		SHOW_EXT_OPTIONS2 : "Показване на още опции за търсене на колонии, луни, шпионски доклади, бележки, статус на играча или дипломатически статус.",
		SHOW_EXT_OPTIONS3 : "Показване на още опции за сортиране на резултатите от търсенето.",
		SHOW_EXTENDED : "комплексно търсене",
		SHOW_MOON_SELECTION : "Планета с луна",
		SHOW_REPORT_SELECTION : "Планета с доклади",
		SHOW_FILTER_BY : "Изключване от списъка",
		SHOW_FILTER_NONE : "нито една",
		SHOW_PLAYERS_WITHOUT_PROGRESS : "Show players without score changes within the last few days",
		STATUS_TITLE : "OGame Galaxytool - Статус",
		STATUS_DB_STATUS : "Статус на базата данни",
		STATUS_COLOR : "Цвят",
		STATUS_AGE1 : "Данните са от преди 1 ден.",
		STATUS_AGE2 : "Данните са от преди 2 - 4 дена.",
		STATUS_AGE3 : "Данните са от преди 4 - 7 дена.",
		STATUS_AGE4 : "Данните са от преди 1 - 2 седмици.",
		STATUS_AGE5 : "Данните са от преди 2 - 4 седмици.",
		STATUS_AGE6 : "Данните са по-стари от 1 месец!",
		STATUS_AGE7 : "Няма данни.",
		STATUS_ON : "на",
		STYLES_COLOR1 : "Цвят1",
		STYLES_COLOR2 : "Цвят2",
		STYLES_COLOR3 : "Цвят3",
		STYLES_COLOR4 : "Цвят4",
		STYLES_COLOR5 : "Цвят5",
		STYLES_COLOR6 : "Цвят6",
		STYLES_COLOR7 : "Цвят7",
		STATUS_DB_LEGEND : "Легенда",
		STATUS_GALAXY : "Статус на Галактиката",
		USER_TITLE : "Управление на потребителите",
		USER_NAMES : "Потребител",
		USER_ERROR : "Грешка",
		USER_NEWUSER : "Нов потребител",
		USER_OPTIONS : "Опции",
		USER_USERNAME : "Потребителско име",
		USER_PASSWORD : "Парола",
		USER_PASSWORD_CONFIRM : "Потвърдете паролата",
		USER_GALAXY : "Галактика",
		USER_SEARCH : "Търсене",
		USER_INSERT : "Добавяне",
		USER_DELETE : "Изтриване",
		USER_DELETE_ENTRY : "Искате ли да изтриете потребителя: ",
		USER_STATUS : "Преглед на статистиката",
		USER_STYLES : "Промяна на подредбата",
		USER_SUBMIT : "Изпрати",
		USER_RESET : "Изчистване",
		USER_YES : "Да",
		USER_NO : "Не",
		USER_STYLEPATH : "Път до styles.css",
		USER_PROBES : "Разглеждане/Изпращане на шпионски доклади",
		USER_EMAIL : "Електронна поща",
		USER_ERROR1 : "Паролата е прогрешна или адресът на електронната поща е невалиден.",
		USER_ERROR2 : "Адресът на електронната поща е невалиден.",
		USER_INGAME : "Име в играта",
		USER_ALLYTAG : "Таг на съюза",
		USER_ALLYHISTORY : "Исторически преглед",
		USER_DIPLOMATIC : "Промяна на дипломатическия статус",
		USER_STATSPAGE : "Брой данни на страницата със статистиките",
		USER_LINKS : "Връзки",
		USER_LINKS2 : "Формат:<br>текст1;url1<br>текст2;url2<br>текст3;url3",
		USER_EXPORT_TITLE : "Експорт на цветовете (BB код)",
		USER_BB_COORDINATES : "Координати",
		USER_BB_MOON : "Луна",
		USER_BB_DEBRIS : "Поле отломки",
		USER_BB_ALLY : "Име на съюз",
		USER_BB_ALLYDETAILS : "Данни за съюза",
		USER_BB_PLAYERNAME : "Име на играч",
		USER_BB_BANNED : "наказан",
		USER_BB_VACATION : "ваканционен режим",
		USER_BB_NOOB : "новак",
		USER_BB_INACTIVE : "Неактивен",
		USER_BB_LONGINACTIVE : "Неактивен отдавна",
		USER_DELETION : "Изтриване",
		USER_FLEETINFO : "Местене на флота",
		USER_ACTIVITIES : "Активности на играча",
		USER_MAINTENANCE : "Поддръжка на Galaxytool",
		USER_MANAGEMENT : "Управление на потребителите",
		USER_DELETE_MY_COMBAT_REPORTS : "Изтриване на моите доклади от битки",
		USER_DELETE_MY_MESSAGES : "Изтриване на моите съобщения",
		USER_DELETE_MY_FLEETMOVES : "Изтриване на моите движения на флоти",
		USER_DELETE_MY_COMBAT_REPORTS_LIMITED : "Изтриване на бойните доклади, по-стари от &1 дена",
		USER_DELETE_MY_MESSAGES_LIMITED : "Изтриване на съобщенията, по-стари от &1 дена",
		USER_TABLE_ENTRIES : "Брой резултати (от търсенето) на страница",
		USER_EXISTS : "Потребителят вече съществува",
		USER_BB_OUTLAW : "Извън закона",
		USER_INVALID_URL : "Линкът &1 изглежда невалиден - ще бъде игнориран",
		VIEW_TITLE : "OGame Galaxytool - Изглед на Галактиката",
		VIEW_NODATA : "Липсват данни.",
		VIEW_GALAXY : "Галактика",
		VIEW_SYSTEM : "Звездна система",
		VIEW_POSITION : "Поз.",
		VIEW_PLANET : "Планета",
		VIEW_MOON : "Луна",
		VIEW_TF : "ПО",
		VIEW_PLAYER : "Играч",
		VIEW_PLAYER_ADD : "(Ранг / Статус)",
		VIEW_ALLY : "Съюз",
		VIEW_ALLY_ADD : "(Ранг / Член)",
		VIEW_METAL : "М",
		VIEW_CRYSTAL : "К",
		VIEW_COLONISED : "Колонизирани планети",
		VIEW_UKMOONSIZE : "неизвестен",
		VIEW_BACK : "назад",
		VIEW_NOTICE : "Бележки",
		VIEW_REPORTS : "Доклади",
		VIEW_MOONPHALANX : "Следните луни могат да сканират тази система",
		VIEW_NOMOONS : "Не са намерени луни",
		VIEW_IRAKS : "Следните планети могат да достигнат тази система с междупланетни ракети",
		VIEW_NOIRAKS : "Не са намерени междупланетни ракети",
		VIEW_MOON_DESTROY_CHANCE : "Вероятност за разрушаване на луната",
		VIEW_CHANCE_WITH_ONE : "Вероятност с една Звезда на смъртта",
		VIEW_CHANCE_WITH_N : "Вероятност с ",
		VIEW_DEATH_STARS : "Звезди на смъртта",
		VIEW_DS_DESTROY_CHANCE : "Вероятност за загуба на звездите на смъртта",
		VIEW_TOP : "в горните",
		VIEW_GO : "go",
		VIEW_DIAMETER : "Диаметър",
		PW_TITLE : "OGame Galaxytool - промяна на парола",
		OLD_PASSWORD : "Стара парола",
		NEW_PASSWORD : "Нова парола",
		CONFIRM_NEW_PASSWORD : "Потвърдете паролата",
		PW_MISMATCH : "Паролите не съвпадат!",
		PW_ERROR : "Старата парола беше неправилна!",
		UPDATE_DONE : "Промяната беше успешна.",
		TIMEZONE_OFFSET : "Времева зона на сървера",
		DELETE_ACCOUNT : "Изтриване на този Galaxytool акаунт",
		DELETE_ACCOUNT_SAFETY_REQUEST : "Наистина ли искате да изтриете този Galaxytool акаунт?",
		CH_PASSWD_AUTHORIZATION : "Права",
		CH_PASSWD_ADMIN : "Admin",
		TIMEZONE_OGAME_OFFSET : "Часова разлика спрямо сървера на OGame",
		CH_PASSWD_USER_LANGUAGE : "Преминаване на този език след влизане",
		CH_PASSWD_USER_LANGUAGE_NO_CHANGE : "Без промяна",
		CH_PASSWD_EXPAND : "Разширена",
		CH_PASSWD_COLLAPSE : "Свита",
		CH_PASSWD_HIDDEN : "Скрита",
		CH_PASSWD_GETTING_STARTED : "Показване на информацията за начинаещи при влизане",
		CH_PASSWD_PLUGIN : "Показване на информацията за плъгина при влизане",
		NOTICE_TITLE : "OGame Galaxytool - Бележки",
		NOTICE_HEADER : "редактиране на бележката",
		NOTICE_HEADER2 : "Редактиране на собствените бележки",
		NOTICE_PUBLIC : "Достъпни за другите?",
		NOTICE_YES : "да",
		NOTICE_NO : "не",
		NOTICE_TEXT : "Текст на бележката",
		NOTICE_SAVE : "Сапази",
		NOTICE_DELETED : "Изтрито.",
		NOTICE_SAVED : "Запазено.",
		NOTICE_RESULTS : "Всички резултати",
		NOTICE_USER : "Потребител",
		NOTICE_DATE : "Дата",
		NOTICE_EDIT : "Редактиране",
		NOTICE_DELETE : "Изтриване",
		NOTICE_NEW : "Създаване на собствена бележка",
		NOTICE_NOTPUBLIC : "Бележката не е обществено достъпна.",
		NOTICE_ALL : "всички",
		NOTICE_NONE : "нито една",
		NOTICE_SEARCH : "Търсене сред бележките",
		NOTICE_SEARCH_SHORT : "Търсене",
		NOTICE_HITS : "Резултати",
		NOTICE_SHOWRESULTS : "Резултати на страница",
		NOTICE_OF : "от",
		NOTICE_NOTHING : "Нищо не е намерено",
		NOTICE_CHARS : "Знака",
		NOTICE_PLAYERNAME : "Играч",
		NOTICE_SHOWALL : "Покажи всички бележки",
		REPORTS_TITLE : "OGame Galaxytool - Шпионски доклади",
		REPORTS_RESOURCES : "Ресурси",
		REPORTS_FLEET : "Флоти",
		REPORTS_DEFENCE : "Защита",
		REPORTS_BUILDINGS : "Сгради",
		REPORTS_TECHNOLOGY : "Проучвания",
		REPORTS_MOON : "Луна",
		REPORTS_SEARCH : "Търсене в шпионските доклади",
		REPORTS_SEARCH_SHORT : "Търсене",
		REPORTS_HITS : "Намерени",
		REPORTS_NOTHING : "Нищо не е намерено",
		REPORTS_ADDRESS : "Адрес",
		REPORTS_CURRENTNESS : "Текущност",
		REPORTS_PLAYERNAME : "Име на играч",
		REPORTS_ALLY : "Съюз",
		REPORTS_VIEW : "виж доклада",
		REPORTS_SEARCH_IN : "Търсене в галактиката",
		REPORTS_FROM_SYSTEM : "от звездна система",
		REPORTS_TO : "до",
		REPORTS_DELETE : "Изтриване",
		REPORTS_DELETED : "Изтрито",
		REPORTS_RESULTS : "Резултати на страница",
		REPORTS_OF : "от",
		REPORTS_DATE : "Дата",
		REPORTS_DATE_0 : "без значение",
		REPORTS_DATE_1 : "по-стари от",
		REPORTS_DATE_2 : "по-нови от",
		REPORTS_NOTICES : "Бележки",
		REPORTS_AT_LEAST_RESOURCES : "Ресурси (поне)",
		REPORTS_SEARCH_EXTENDED : "Разширено търсене",
		REPORTS_FLEET_RESIS : "Флоти - сума",
		REPORTS_DEFENCE_RESIS : "Защити - сума",
		REPORTS_ALL_RESIS : "Обща сума",
		REPORTS_TECHS : "Технологии",
		REPORTS_UNKNOWN_ENTRIES : "неизвестно",
		REPORTS_PARTLY_INSERTED : "частично добавено",
		REPORTS_FOR_ALL_RES : "За всички ресурси",
		REPORTS_FOR_TF : "за полето отломки",
		REPORTS_KT : "Малки транспортьори",
		REPORTS_GT : "Големи транспортьори",
		REPORTS_SS : "Бойни кораби",
		REPORTS_REC : "Рециклатор",
		REPORTS_RAIDABLE : "Само нападаеми цели",
		REPORTS_ALL_RESOURCES : "Всички ресурси",
		REPORTS_STUFF : "Разни",
		REPORTS_SPEEDSIM : "Симулиране със Speedsim",
		REPORTS_DRAGOSIM : "Симулиране със Dragosim",
		REPORTS_STATUS : "Статус",
		REPORTS_ERROR : "Възникна грешка",
		REPORTS_OWN_REPORTS : "Само моите доклади",
		REPORTS_UPLOAD_BY : "Докладът е изпратен от",
		REPORTS_DEPTH : "Пълнота на доклада",
		REPORTS_FLEET_SCORE : "Точки от флот (макс.)",
		REPORTS_DEFENCE_SCORE : "Точки от защити (макс.)",
		REPORTS_HOURS : "часове",
		REPORTS_MAX_RESULTS_HIT : "Заявката Ви върна повече от &1 резултата. Показани са само първите &1 резултата. Моля, настройте заяката си за търсене така, че да се получат по-малко резултати.",
		REPORTS_OSIMULATE : "Симулиране с OSimulate",
		REPORTS_SHOW_ONLY : "Показване само на",
		REPORTS_SHOW_PLANETS : "Планети",
		REPORTS_SHOW_MOONS : "Луни",
		REPORTS_OWNER : "Докладите качени от",
		STATS_TITLE : "OGame Galaxytool - Статистики",
		STATS_TBLHEAD : "Статистика",
		STATS_RANK : "Ранг",
		STATS_PLAYERNAME : "Име на играч",
		STATS_ALLYNAME : "Таг на съюз",
		STATS_SCORE : "Точки",
		STATS_FLEET : "Флоти",
		STATS_RESEARCH : "Проучвания",
		STATS_MEMBERS : "Членове",
		STATS_STATUS : "Статус",
		STATS_NOTHING : "няма статус",
		STATS_NAP : "ПНН",
		STATS_ALLIED : "Съюз",
		STATS_WAR : "Война",
		STATS_BOYCOTT : "Бойкот",
		STATS_NEUTRAL : "Неутрален",
		STATS_OWN : "Собствен съюз",
		STATS_WING : "Помагач",
		STATS_UPDATE : "От",
		STATS_PLAYERSTATS : "Статистика на играчите",
		STATS_ALLYSTATS : "Статистика на съюзите",
		STATS_DELETE : "Искате ли да изтриете това?",
		STATS_CONFIRM_DELETE : "Наистина ли искате да изтриете това?",
		STATS_CHANGE_PLAYER_STATUS : "Статус на играча",
		STATS_CHANGE_ALLIANCE_STATUS : "Статус на съюза",
		STATS_CHANGE_ALLIANCE_STATUS_HINT : "Всички членове на този съюз получават избрания статус. Предишният им статус ще бъде изгубен. По-късно можете да промените статуса само на някои играчи.",
		STATS_UNKNOWN : "Останалите",
		STATS_DETAILS : "Подробности за",
		STATS_PLAYERSTATUS : "Статус на играча",
		STATS_IGNORE_STATUS : "всички",
		STATS_ACTIVE : "активен",
		STATS_INACTIVE : "Неактивен",
		STATS_BANNED : "наказан",
		STATS_VACATION : "ваканционен режим",
		STATS_NOOB : "новак",
		STATS_YES : "Да",
		STATS_NO : "Само планети с бележки",
		STATS_SEARCH : "Търсене",
		STATS_SHOW_GRAPH : "Показване на подробностите при разпределението на точките",
		STATS_LONG_INACTIVE : "Неактивен отдавна",
		STATS_STANDARD : "Стандартни точки",
		STATS_MILITARY : "Военни точки",
		STATS_ECONOMY : "Икономика",
		STATS_HONOUR : "Точки на честта",
		STATS_MILITARY_BUILD : "Построени военни точки",
		STATS_MILITARY_DESTROYED : "Унищожени военни точки",
		STATS_MILITARY_LOST : "Изгубени военни точки",
		REGISTER_REGISTRATE : "Регистриране",
		REGISTER_LOGINNAME : "Потребителско име",
		REGISTER_PASSWORD : "Парола",
		REGISTER_PASSWORD_CONFIRM : "Потвърдете паролата",
		REGISTER_EMAIL : "Адрес на електронната поща",
		REGISTER_INGAME : "Име в играта",
		REGISTER_ALLYTAG : "Таг на съюза",
		REGISTER_EMAILVERIFICATION : "Провека на адреса на електронната поща",
		REGISTER_EMAILTEXT : "Моля, посетете следния URL за да потвърдите регистрацията си за GalaxyTool.",
		REGISTER_ERROR1 : "Това потребителско име е вече заето.",
		REGISTER_ERROR2 : "Възникна грешка при опита да се изпрати електронна поща. Моля, свържете се с администратора си.",
		REGISTER_ERROR3 : "Възникна грешка при опита да се изпрати информация в базата данни!",
		REGISTER_INFO1 : "Акаунтът Ви беше създаден.",
		REGISTER_INFO2 : "Моля, посетете URL-а, получен по електронната пощам за да to потвърдите регистрацията си.",
		REGISTER_INFO3 : "Акаунтът е потвърден. Сега администраторът Ви трябва да го активира.",
		REGISTER_BUTTON : "Назад към главната страница",
		REGISTER_NEW_SUBJECT : "Нов потребител се регистрира в GalaxyTool",
		REGISTER_NEW_MAILTEXT : "Нов потребител се регистрира.",
		REGISTER_BACK : "Назад към първата страница",
		REGISTER_MISSING_FIELDS : "Попълнете всички необходими полета",
		REGISTER_ERROR4 : "Адресът за електронна поща е невалиден.",
		REGISTER_ERROR5 : "Паролите не съвпадат.",
		REGISTER_PWS : "Качество на паролата",
		REGISTER_PWS0 : "много слабо",
		REGISTER_PWS1 : "слабо",
		REGISTER_PWS2 : "приемливо",
		REGISTER_PWS3 : "добро",
		REGISTER_PWS4 : "много добро",
		REGISTER_EMAIL_USED : "Този адрес за електронна поща вече е използван",
		LOSTPW_TITLE : "Изгубена парола",
		LOSTPW_INFO2 : "Нова парола беше генерирана и изпратена на адреса на електронната Ви поща.",
		LOSTPW_BUTTON1 : "получаване на нова парола",
		LOSTPW_BUTTON2 : "Назад към главната страница",
		LOSTPW_LOGINNAME : "Потребителско име",
		LOSTPW_EMAIL : "Адрес на електронната поща",
		LOSTPW_ERROR1 : "Възникна грешка при опита да се изпратят данни в базата данни!",
		LOSTPW_ERROR2 : "Не е намерено такова!",
		LOSTPW_ERROR3 : "Възникна грешка при опита да се изпрати електронна поща. Моля, свържете се със системния си администратор.",
		LOSTPW_EMAIL_SUBJECT : "Новата парола, която поискахте",
		LOSTPW_EMAIL_TEXT1 : "Ето новата Ви регистрация за Galaxytool",
		LOSTPW_EMAIL_TEXT2 : "Потребителско име",
		LOSTPW_EMAIL_TEXT3 : "Парола",
		LOSTPW_INFO1 : "Ще получите съобщение по електронната поща, за да потвърдите заявката си за нова парола.",
		LOSTPW_CONFIRM_RESET_SUBJECT : "Забравена парола?",
		LOSTPW_CONFIRM_RESET_MESSAGE : "Здравейте,\n\nВие поискахте нова парола за Galaxytool. За да Ви бъде генерирана нова парола, цъкнете следния линк:",
		USERINFO_TITLE : "OGame Galaxytool - Информация за потребителите",
		USERINFO_NAMES : "Всички потребители",
		USERINFO_DETAIL : "Подробна информация за",
		USERINFO_ERROR1 : "Няма такъв потребител!",
		USERINFO_USERNAME : "Потребителско име",
		USERINFO_INGAME : "Име в играта",
		USERINFO_EMAIL : "Електронна поща",
		USERINFO_ALLYTAG : "Съюз",
		USERINFO_STYLEPATH : "Скин",
		USERINFO_STATUS : "Статус",
		USERINFO_ACTIVATE : "Активиране на потребителя",
		USERINFO_LOGINS : "Брой влизания",
		USERINFO_LASTLOGIN : "Последно влизане",
		USERINFO_DATA : "Информация за въведените звездни системи",
		USERINFO_NODATA : "Този потребител още не е въвел никакви звездни системи!",
		USERINFO_GALAXY : "Галактика",
		USERINFO_SYSTEMS : "Брой звездни системи",
		USERINFO_IP : "IP адрес",
		USERINFO_LOGINTIME : "Време на влизане",
		USERINFO_NOLOGIN : "Този потребител никога не е влизал.",
		USERINFO_LAST_GALAXYUPDATE : "Последен добавен изглед Галактика",
		USERINFO_LAST_PUBLIC_NOTICE : "Последна общественодостъпна бележка",
		USERINFO_LAST_PRIVATE_NOTICE : "Последна лична бележка",
		USERINFO_NUMBEROF_PUBLIC_NOTICE : "Брой общественодостъпни бележки",
		USERINFO_NUMBEROF_PRIVATE_NOTICE : "Брой лични бележки",
		USERINFO_ACTIVATED : "Акаунтът е активиран",
		USERINFO_ACTIVATIONTEXT : "Администраторът на Galaxytool е активирал акаунта Ви.\n\nПриятно използване на Galaxytool!",
		USERINFO_LAST_SUBMIT : "Последно въведени данни",
		ALLYHISTORY_TITLE : "OGame Galaxytool - История на съюза",
		ALLYHISTORY_TBLHEAD : "Преглед на историята",
		ALLYHISTORY_PLAYERNAME : "Име на играч",
		ALLYHISTORY_ALLYNAME : "Съюз",
		ALLYHISTORY_LASTMONTH : "Миналия месец",
		ALLYHISTORY_ALL_DATA : "Цялата налична информация",
		ALLYHISTORY_SHOW : "Показване на статистиката",
		ALLYHISTORY_TIMESPAN : "Времеви диапазон",
		ALLYHISTORY_PROGESS : "Развитие",
		ALLYHISTORY_SCORE : "Класация",
		ALLYHISTORY_FSCORE : "Флоти",
		ALLYHISTORY_RSCORE : "Проучвания",
		ALLYHISTORY_MEMBER : "Членове",
		ALLYHISTORY_NOTHING : "Нищо не е намерено",
		ALLYHISTORY_DETAILS : "Подробности",
		ALLYHISTORY_SHOW_ADDRESS : "Координати",
		ALLYHISTORY_ESCORE : "Икономика",
		ALLYHISTORY_MSCORE : "Военни точки",
		DETAILEDINFO_PLAYERINFO_TITLE : "Информация за играча",
		DETAILEDINFO_ALLYINFO_TITLE : "Информация за съюза",
		DETAILEDINFO_PLAYERINFO_TBLHEAD : "Подробна информация за играча",
		DETAILEDINFO_ALLYINFO_TBLHEAD : "Подробна информация за съюза",
		DETAILEDINFO_NO_ALLIANCE : "няма",
		DETAILEDINFO_SCORE : "Статистика точки",
		DETAILEDINFO_FLEET : "Статистика флот",
		DETAILEDINFO_RESEARCH : "Статистика проучвания",
		DETAILEDINFO_RANK : "Ранг",
		DETAILEDINFO_POINTS : "Точки",
		DETAILEDINFO_KNOWN_PLANETS : "Известни планети",
		DETAILEDINFO_MOONS : "Известни луни",
		DETAILEDINFO_PHALANX_AREA : "Обхват на фронталния сензор",
		DETAILEDINFO_NO_PHALANX_AREA : "Няма фронтален сензор",
		DETAILEDINFO_NOTICES : "Бележки",
		DETAILEDINFO_NO_NOTICES : "Няма бележки",
		DETAILEDINFO_PREVIOUS_ALLIANCES : "Предишни съюзи",
		DETAILEDINFO_RESOURCES_PER_HOUR : "Ресурси на час",
		DETAILEDINFO_RESOURCES_PER_DAY : "Ресурси на ден",
		DETAILEDINFO_RESOURCES_PER_WEEK : "Ресурси на седмица",
		DETAILEDINFO_RESOURCES_PER_MONTH : "Ресурси на месец (30 дена)",
		DETAILEDINFO_METAL : "Метал",
		DETAILEDINFO_CRYSTAL : "Кристали",
		DETAILEDINFO_DEUTERIUM : "Деутериум",
		DETAILEDINFO_UNKNOWN : "неизвестно",
		DETAILEDINFO_SCORE_DISTRIBUTION : "Разпределение на точките",
		DETAILEDINFO_GENERAL : "Подробности",
		DETAILEDINFO_MEMBERS : "Членове",
		DETAILEDINFO_GRAPHS : "Графики",
		DETAILEDINFO_RESOURCES : "Ресурси",
		DETAILEDINFO_FLEET_TAB : "Флоти",
		DETAILEDINFO_TECH : "Проучвания",
		DETAILEDINFO_FLEET_DETAIL : "Сума / (средното за играча) от всички налични доклади",
		DETAILEDINFO_TECH_DETAIL : "Средното от всичката налична информация за играча",
		DETAILEDINFO_PLANET_TAB : "Планети",
		DETAILEDINFO_MOON_TAB : "Луни",
		DETAILEDINFO_ACTIVITIES : "Активности",
		DETAILEDINFO_NODATA : "Липсват данни.",
		DETAILEDINFO_ACTIVITY_DESCRIPTION : "Показване на активностите за &1, събрани от:",
		DETAILEDINFO_GALAXYVIEWS : "Преглед на Галактиката",
		DETAILEDINFO_SCANS : "Шпионажна активност",
		DETAILEDINFO_MESSAGES : "Съобщения от играча",
		DETAILEDINFO_COMBATS : "Доклади от битки",
		DETAILEDINFO_ALLYPAGE : "Страница на съюза",
		DETAILEDINFO_MANUAL : "Ръчни добавяния",
		DETAILEDINFO_START : "От",
		DETAILEDINFO_TO : "до",
		DETAILEDINFO_TODAY : "Днес",
		DETAILEDINFO_DATA_RESTRICTION : "само от:",
		DETAILEDINFO_WEEKDAY_WEEKEND : "уикенда",
		DETAILEDINFO_WEEKDAY_WORKINGDAY : "работни дни",
		DETAILEDINFO_WEEKDAY_MONDAY : "понеделник",
		DETAILEDINFO_WEEKDAY_TUESDAY : "вторник",
		DETAILEDINFO_WEEKDAY_WEDNESDAY : "сряда",
		DETAILEDINFO_WEEKDAY_THURSDAY : "четвъртък",
		DETAILEDINFO_WEEKDAY_FRIDAY : "петък",
		DETAILEDINFO_WEEKDAY_SATURDAY : "събота",
		DETAILEDINFO_WEEKDAY_SUNDAY : "неделя",
		DETAILEDINFO_WEEKDAY_SHORTLENGTH : 3,
		DETAILEDINFO_PLAYER_CURRENTLY_ACTIVE : "Играчът е активен в момента",
		DETAILEDINFO_PLAYER_MESSAGES : "Налични съобщения на играча",
		DETAILEDINFO_SHOW : "Показване",
		DETAILEDINFO_NONE : "Няма налични",
		DETAILEDINFO_ENTER_MANUALLY : "Въвеждане на активности за играча",
		DETAILEDINFO_PLAYER_SEEN_ON : "Играчът е бил на линия на",
		DETAILEDINFO_INSERT : "Добавяне",
		DETAILEDINFO_OGAME_SERVERTIMES : "Внимание: Всички дати и времена са по сърверно време !",
		DETAILEDINFO_DAY_VIEW : "24-часов изглед",
		DETAILEDINFO_WEEK_VIEW : "седмичен изглед",
		DETAILEDINFO_HOME_PLANET : "Родна планета",
		DETAILEDINFO_PLANETNAME : "Име",
		DETAILEDINFO_DEFENCE_SCORE : "Защитни точки",
		DETAILEDINFO_DEFENCE_SCORE_TOOLTIP : "Защитни точки = Флот - Точки + Изследвания + Икономика.<br/>Всички тези статистики трябва да са обновени, за да получите смислен резултат!",
		DETAILEDINFO_SCORE_PER_SHIP : "Точки на кораб",
		DETAILEDINFO_SHIPS : "Брой кораби",
		DETAILEDINFO_DATE_IN_FUTURE : "Не запазвай данни от миналото.",
		ADMIN_TITLE : "Администриране на Galaxytool",
		ADMIN_DISCLAMER : "Внимание: Използването на тези програми е на Ваша отговорност! Повечето от тях изтриват данни.",
		ADMIN_INCONSISTENCIES : "Несъответствия в базата данни",
		ADMIN_PLANETS : "Планети на позиция 0 или по-голяма от 15",
		ADMIN_GALAXIES : "Изтриване на галактиките с номер по-голям от &1 ",
		ADMIN_PLAYERS : "Изтриване на играчите без име в OGame - води то дуплицирани имена на играчи",
		ADMIN_REPORTS : "Изтриване на докладите, ако планетата, за която се отнасят, вече не съществува",
		ADMIN_MISC : "Разни",
		ADMIN_RESET : "Изчистване на Galaxytool (само потребителите и таблицата на IP адреси няма да бъдат изтрити)",
		ADMIN_OLD_PLAYERS : "Изтриване на данните за играчи, ако са по-стари от &1 дена",
		ADMIN_OLD_REPORTS : "Изтриване на докладите, които са по-стари от &1 дена",
		ADMIN_LOADING : "Не затваряйте този прозорец докато страницата се зарежда.",
		ADMIN_STATUS : "Статус на заявките Ви",
		ADMIN_SELECTION : "Поне едно нещо трябва да бъде избрано",
		ADMIN_SAFETY : "Сигурен ли сте, че искате да изпълните това?",
		ADMIN_DONE : "готово",
		ADMIN_NOTBD : "няма нищо за правене",
		ADMIN_OLD_GALAXIES : "Премахване на изгледи от режим Галактика, ако са по-стари от &1 дена",
		ADMIN_UNUSED_PLAYERS : "Премахване на играчите, които ги няма в никой изглед от режим Галактика",
		ADMIN_OLD_ACTIVITIES : "Премахване на активности на играчите, по-стари от &1 дена",
		ADMIN_OLD_COMBATS : "Изтриване на бойните доклади, по-стари от &1 дена",
		ADMIN_OLD_INGAME_MSG : "Изтриване на съобщенията, по-стари от &1 дена",
		ADMIN_OGAME_API : "Зареждане на общодостъпните данни от OGame в Galaxytool",
		ADMIN_OGAME_ALL_DATA : "Цялата налична информация",
		ADMIN_OGAME_GALAXY_DATA : "Преглед на галактиката",
		ADMIN_OGAME_STATISTICS_DATA : "Статистика",
		ERRORPAGE_PAGEFORWARD : "Цъкнете тук, ако броузерът Ви не поддържа автоматично препращане към друга страница.",
		ERRORPAGE_PERMISSION_DENIED : "Нямате права за достъп до тази страница. Цъкнете тук, за да се върнете.",
		FLEETS_TITLE : "OGame Galaxytool - местене на флота",
		FLEETS_ACTUAL_FLEETS : "Текущи движения на флоти",
		FLEETS_YES : "Да",
		FLEETS_NO : "Само планети с бележки",
		FLEETS_DETAILS : "Подробности",
		FLEETS_MISSION_EXPEDITION : "Експедиция",
		FLEETS_MISSION_COLONIZATION : "Колонизация",
		FLEETS_MISSION_RECYCLE : "Рециклирай",
		FLEETS_MISSION_TRANSPORT : "Транспортирай",
		FLEETS_MISSION_DEPLOYMENT : "Стационирай",
		FLEETS_MISSION_ESPIONAGE : "Шпионирай",
		FLEETS_MISSION_ACS_DEFEND : "СБС Защита",
		FLEETS_MISSION_ATTACK : "Атака",
		FLEETS_MISSION_ACS_ATTACK : "СБС Атака",
		FLEETS_MISSION_MOON_DESTRUCTION : "Разрушаване на луна",
		FLEETS_MISSION_MISSILE_ATTACK : "Ракетна атака",
		FLEETS_NO_DATA : "Няма данни",
		FLEETS_FLEET : "Флот",
		FLEETS_ALL_FLEETS : "Показване на всички движения на флоти",
		COMBAT_REPORT_OUDATED_GALAXYVIEW : "Данните Ви за Галактиката са остарели. Моля, погледнете първо координатите на началната точка и на целта на атаката!",
		MESSAGES_TITLE : "OGame Galaxytool - Игрови съобщения",
		MESSAGES_PLAYERNAME : "Име на играча",
		MESSAGES_SUBJECT : "Тема",
		MESSAGES_DATE : "Дата",
		MESSAGES_FILTER : "Филтър",
		MESSAGES_DELETE : "Изтриване на съобщението",
		MESSAGES_PUBLISH_DETAIL : "Публикуване на съобщението чрез добавяне на съдържанието му към текста на бележката за играча.",
		MESSAGES_PUBLISH_HEADER : "&sender изпрати съобщение на &recipient на &date:\n\n &message",
		MESSAGES_PLAYER_FILTER : "Съобщения за играча:",
		MESSAGES_CONTENT : "Съдържание",
		COMBATS_TITLE : "OGame Galaxytool - Доклади от битките",
		COMBATS_ATTACKER : "Нападател",
		COMBATS_DEFENDER : "Защитник",
		COMBATS_DATE : "Дата",
		COMBATS_OWNER : "Собственик",
		COMBATS_WINNER : "Победител",
		COMBATS_COMBATREPORT : "Доклад от битката",
		COMBATS_COMBAT_AT : "Битка на координати",
		COMBATS_LOST_UNITS : "Общи загуби",
		COMBATS_LOOT : "Плячка",
		COMBATS_DEBRIS : "Рециклаж",
		COMBATS_AND : "и",
		COMBATS_PUBLISH : "Направи този доклад общодостъпен",
		COMBATS_UNPUBLISH : "Премахване на общодостъпния статус на доклада",
		COMBATS_DELETE : "Изтриване на доклада",
		COMBATS_CHECK_ALL : "Избор на всички",
		COMBATS_UNCHECK_ALL : "Избор на никои",
		COMBATS_WITH_SELECTED : "С избраните",
		COMBATS_PUBLIC_REPORTS : "Общодостъпни доклади",
		COMBATS_YES : "Да",
		COMBATS_NO : "Само планети с бележки",
		COMBATS_SEARCH_OPTIONS : "Опции на търсенето",
		COMBATS_SEARCH : "Изпълнение",
		COMBATS_RESET : "Изчистване",
		COMBATS_COORDINATES : "Координати",
		COMBATS_INVALID_GALAXY_ENTERED : "Невалиден номер на Галактика",
		COMBATS_INVALID_SYSTEM_ENTERED : "Невалиден номер на Система",
		COMBATS_INVALID_PLANET_ENTERED : "Невалидна позиция на Планета",
		COMBATS_GALAXY_FROM_TO : "Галактика",
		COMBATS_SYSTEM_FROM_TO : "Система",
		COMBATS_PLANET_FROM_TO : "Планета",
		COMBATS_APPLY : "Прилагане",
		COMBATS_COMBAT_SUMMARY : "Резюме на доклада от битката",
		COMBATS_DOWNLOAD_CSV : "Сваляне като CSV файл",
		REPORT_ARCHIVE_TITLE : "Архив доклади",
		REPORT_ARCHIVE_COORDINATES : "Координати",
		REPORT_ARCHIVE_SCANTIME : "Време на шпиониране",
		REPORT_ARCHIVE_DELETE : "Изтриване на тези доклади",
		REPORT_ARCHIVE_CONFIRM_DELETE : "Наистина ли искате да изтриете тези доклади?",
		REPORT_ARCHIVE_GALAXY : "Галактика",
		REPORT_ARCHIVE_SYSTEM : "Система",
		REPORT_ARCHIVE_PLANET : "Планета",
		REPORT_ARCHIVE_MOON : "Луна",
		REPORT_ARCHIVE_DETAILS : "Подробности",
		REPORT_ARCHIVE_RESOURCES : "Ресурси на час",
		REPORT_ARCHIVE_HEADER_RESOURCES : "Ресурси",
		REPORT_ARCHIVE_DETAILS_FOR : "Архив доклади за &1 [&2] (&3)",
		REPORT_ARCHIVE_FLEET_CARGO : "Товароподемност на флота",
		REPORT_ARCHIVE_IRAK_RANGE : "Обхват на междупланетните ракети",
		REPORT_ARCHIVE_CHART_TYPE : "Вид на графиката",
		INSTALL_TITLE : "Инсталиране на Galaxytool версия",
		INSTALL_PROGRESS : "Общ прогрес",
		INSTALL_STEP : "Стъпка",
		INSTALL_CONTINUE : "Продължение",
		INSTALL_VALIDATE : "Валидиране",
		INSTALL_STEP1 : "Добре дошли",
		INSTALL_STEP2 : "Проверка за писане",
		INSTALL_STEP3 : "Настройки на базата данни",
		INSTALL_STEP4 : "Настройки за OGame",
		INSTALL_STEP5 : "Настройки за Galaxytool",
		INSTALL_STEP6 : "Парола на администратора",
		INSTALL_STEP7 : "Инсталиране на Galaxytool",
		INSTALL_STEP8 : "Завършване на инсталирането",
		INSTALL_FILE_DELETE_CHECK : "Моля, изтрийте файловете install.php и update.php от сървера си.",
		INSTALL_STEP1_PHP_FAILED : "Вашата версия на PHP (&1) не работи с тази версия на Galaxytool",
		INSTALL_STEP1_FOPEN_FAILED : "Вашата версия на PHP не позволява отварянето на уеб страници чрез командата FOPEN(). А това е необходимо за използването на OGame API.",
		INSTALL_STEP1_WELCOME : "Добре дошли в инсталирането на Galaxytool. Ще бъдете ръководени в процеса на инсталиране на Galaxytool.",
		INSTALL_STEP2_DESCRIPTION : "Погрижете се файловете ви config.php и attributes.php да са достъпни за запис.",
		INSTALL_STEP2_DESCRIPTION2 : "Ако не знаете как да постигнете това, моля погледнете тук: &1",
		INSTALL_STEP2_FILE_NOT_WRITEABLE : "Файлът не е достъпен за запис",
		INSTALL_STEP3_SERVER : "Сървер за базата данни",
		INSTALL_STEP3_USERNAME : "Потребителско име",
		INSTALL_STEP3_PASSWORD : "Парола",
		INSTALL_STEP3_DBNAME : "Име на базата данни",
		INSTALL_STEP3_PREFIX : "Префикс за името на таблицата",
		INSTALL_STEP3_ENTER_PREFIX : "Напр. mytool_",
		INSTALL_STEP3_ENTER_SERVER : "Въведете адреса на сървера. Свържете се със системния си администратор, ако е необходимо. Обикновено правилната стойност е localhost.",
		INSTALL_STEP3_ENTER_USERNAME : "Въведете името на потребителя за достъп до базата данни",
		INSTALL_STEP3_ENTER_PASSWORD : "Въведете паролата за достъп до базата данни",
		INSTALL_STEP3_ENTER_DBNAME : "Въведете името на базата данни, която да бъде използвана за инсталирането (трябва да съществува)",
		INSTALL_STEP3_CONNECT_FAILED : "Не можах да установя връзка със сървера за базата данни",
		INSTALL_STEP3_DB_FAILED : "Базата данни &1 не беше намерена",
		INSTALL_STEP3_MYSQL_VERSION_FAILED : "MySQL версия &1 не работи с тази версия на Galaxytool",
		INSTALL_STEP4_URL : "Линк към OGame",
		OGAME_URL_DETAILS : "Моля, въведете кой да е линк, който виждате, когато сте влезли в OGame. Въз основата на този линк, Galaxytool ще установи адреса на OGame API, който може да се използва за обновяване на Galaxytool без Galaxytoolbar. Това API беше въведено в OGame версия 4.1.",
		INSTALL_STEP4_UNIVERSE : "OGame Вселена",
		INSTALL_STEP4_DEF_TO_DEBRIS : "Защитите дават отломки",
		INSTALL_STEP4_DEBRIS_RATE : "Процент на отломките",
		INSTALL_STEP4_SPEED_RATE : "Ускорение",
		INSTALL_STEP4_ENTER_UNIVERSE : "Въведете името или номера на вашата OGame вселена (големи или малки букви имат значение!).",
		INSTALL_STEP4_UNIVERSE_MISSING : "Трябва да определите вселената си",
		INSTALL_STEP4_ENTER_URL : "Въведете адреса на вашата OGame вселена",
		INSTALL_STEP4_URL_MISSING : "Трябва да определите адреса на вашата OGame вселена",
		INSTALL_STEP4_URL_CHECK_FAILED : "Не можах да намеря OGame API на &1",
		INSTALL_STEP4_GETSETTINGS : "Fetch settings",
		INSTALL_STEP5_TOOLNAME : "Име на Galaxytool",
		INSTALL_STEP5_ENTER_TOOLNAME : "Това е името, което ще се показва на страницата за влизане, за да идентифицира Вашия Galaxytool",
		INSTALL_STEP5_LANGUAGE : "Език по подразбиране",
		INSTALL_STEP5_EMAIL_TO : "Електронна поща до",
		INSTALL_STEP5_ENTER_EMAIL_TO : "Въведете адреса на електронната поща, където бихте искали да получавате нотификации за заявки за регистриране",
		INSTALL_STEP5_EMAIL_FROM : "Електронна поща от",
		INSTALL_STEP5_ENTER_EMAIL_FROM : "Този адрес на електронна поща се поставя като адрес за отговор на всички съобщения, изпратени от Galaxytool",
		INSTALL_STEP5_USE_PHPMAILER : "Използване на PHPMailer",
		INSTALL_STEP5_MAXSHOUTS : "Максимален брой съобшения на дъската за обявления",
		INSTALL_STEP5_ENTER_USE_PHPMAILER : "Използване на PHPMailer ако сърверът Ви не поддържа по подразбиране изпращане на съобщения по електронната поща",
		INSTALL_PHPMAILER_HOST : "SMPT хост",
		INSTALL_PHPMAILER_HOST_EXAMPLE : "напр. smtp.provider.com",
		INSTALL_PHPMAILER_USER : "SMPT потребителско име",
		INSTALL_PHPMAILER_USER_EXAMPLE : "напр. user@provider.dcom",
		INSTALL_PHPMAILER_PASS : "SMPT парола",
		INSTALL_PHPMAILER_SECURE : "Метод за аутентификация (напр. ssl)",
		INSTALL_PHPMAILER_PORT : "SMTP порт",
		INSTALL_STEP6_INTRO : "Моля, въведете парола за акаунта <strong>admin</strong>, който трябва да използвате при първо влизане в Galaxytool след инсталирането.",
		INSTALL_STEP7_CONFIG : "Конфигурационният файл е създаден",
		INSTALL_STEP7_CONFIG_FAILED : "Конфигурационният файл не беше създаден",
		INSTALL_STEP7_ATTRIBUTES : "Файлът с атрибутите беше създаден",
		INSTALL_STEP7_ATTRIBUTES_FAILED : "Файлът с атрибутите не беше създаден",
		INSTALL_STEP7_CREATED_TABLES : "Таблиците в базата данни бяха създадени",
		INSTALL_STEP8_INTRO : "Вие инсталирахте Galaxytool успешно!",
		INSTALL_STEP8_LOAD_DATA : "Сваляне на данните от OGame...",
		INSTALL_STEP8_LOAD_DATA_FINISHED : "Салянето на данните от OGame е завършено",
		INSTALL_STEP8_DELETE_FILE : "Сега би трябвало да изтриете инсталационните файлове install.php и update.php от уеб сървера си.",
		INSTALL_STEP8_LOGON : "Моля, влезте с потребителското име <strong>admin</strong> и с административната парола, която въведохте по-рано.",
		UPDATE_START : "Започване на обновяване до версия &1",
		UPDATE_STEP_DONE : "Готово",
		UPDATE_TITLE : "Galaxytool обновяване за версия",
		UPDATE_STEP1_WELCOME : "Добре дошли в механизма за обновяване на Galaxytool. Ще бъдете насочван в процеса на обновяване на Galaxytool.",
		UPDATE_STEP1_BACKUP_FILES : "Като първа стъпка, направете резервно копие на вашата директория <strong>config</strong>! Ще трябва да възстановите съдържанието на конфигурацията, в случай че възникнат грешки.",
		UPDATE_STEP1_BACKUP_DB : "След това направете <a href=\"http://www.ehow.com/how_2036600_create-database-php.html\">резервно копие</a> на базата си данни.",
		UPDATE_STEP1_PROCEED : "След като резервното копие е готово, можете да продължите с обновяването.",
		UPDATE_STEP1 : "Добре дошли",
		UPDATE_STEP2 : "Настройки за Galaxytool",
		UPDATE_STEP2_OLD_VERSION : "Предишна версия на Galaxytool",
		UPDATE_STEP3 : "Обновяване на Galaxytool",
		UPDATE_STEP3_UPDATE_RUNNING : "Обновяване, моля изчакайте...",
		UPDATE_STEP4 : "Завършване на обновяването",
		UPDATE_STEP4_INTRO : "Galaxytool беше обновен успешно!",
		UPDATE_STEP4_UPDATE_DONE : "Етапите на обновяването бяха изпълнени.",
		UPDATE_FAILED : "Обновяването беше неуспешно.",
		GALAXYTOOL_DUMMY_TEXT : "dummy"
	})
);