define(
	({
		REPORT_WHEN : "ekkor:",
		RESOURCES_ON : "Nyersanyagok itt:",
		PLAYER_BANNED : "b",
		PLAYER_VACATION_MODE : "v",
		PLAYER_NOOB : "n",
		PLAYER_INACTIVE : "i",
		PLAYER_LONG_INACTIVE : "I",
		PLAYER_OUTLAW : "tk",
		L_USERNAME : "Felhasználónév",
		L_PASSWORD : "Jelszó",
		L_LOGINFAILURE : "A felhasználónév vagy a jelszó hibás, vagy a felhasználóneved még nincs aktiválva.",
		L_TOKENFAILURE : "Your logon key is wrong or your account is not activated yet.",
		L_LOGINTEXT : "Kérlek jelentkezz be.",
		L_LANGUAGE : "Elérhető nyelvek:",
		L_TIMEOUT : "Időtúllépés!",
		L_REGISTER : "Regisztráció",
		L_PWLOST : "Elfelejtett jelszó",
		INDEX_TITLE : "OGame Galaxietool - Áttekintés",
		INDEX_INFO : "Információ",
		INDEX_ENTRIES : "Összes rendszer:",
		INDEX_ENTRIES_LASTWEEK : "Új rendszerek múlt héten",
		INDEX_ENTRIES_TO_OLD : "Egy hónapnál régebbi rendszerek",
		INDEX_REGISTERED_USERS : "Regisztrált felhasználók",
		INDEX_PAGEFORWARD : "Ha a böngésződ nem támogatja a továbbirányítást, kérlek kattints ide.",
		INDEX_NOTICES : "Megjegyzések",
		INDEX_PLAYERS : "Játékos statisztikák",
		INDEX_ALLIES : "Szövetség statisztikák",
		INDEX_REPORTS : "Kémjelentések",
		INDEX_VERSION : "Utolsó letölthető verzió",
		INDEX_LATEST_VERSION : "Nincs újabb verzió",
		INDEX_SHOUTBOX : "Üzenőfal",
		INDEX_NOENTRY : "Nincs még üzenet",
		INDEX_COMMENT : "Üzeneted",
		INDEX_INSERT : "Elküldés",
		INDEX_UMOD : "Játékos vakáció módban",
		INDEX_NO_MOONS : "Holdak száma",
		INDEX_NO_EMPTY_SYSTEMS : "Üres rendszerek száma",
		INDEX_NO_FULL_SYSTEMS : "Teljesen kolonizált rendszerek száma",
		INDEX_NO_TARGETS : "Lehetséges célpontok száma",
		INDEX_USERINFO : "Felhasználók",
		INDEX_ONLINE : "Most online",
		INDEX_TODAY : "Ma online",
		INDEX_ALL : "Összes bejelentkezés",
		GENERAL_LOAD_FORM : "Adatok betöltése",
		GENERAL_SAVE_FORM : "Adatok mentése",
		GENERAL_SAVE_AS_TEXT : "Mentés mint",
		GENERAL_SAVE : "Mentés",
		INDEX_USERMANAGEMENT : "Activation Overview",
		INDEX_NEEDADMIN : "Accounts to unlock",
		INDEX_NEEDEMAIL : "Unvalidated Accounts",
		INDEX_TOOLBAR_INFO : "Galaxytool plugin information",
		INDEX_TOOLBAR_URL : "Galaxytool URL",
		INDEX_TOOLBAR_VERSION_REQUIRED : "Requires at least Galaxytool plugin version",
		INDEX_TOOLBAR_INSTALL_GUIDE : "Installation instructions for plugin",
		INDEX_TOOLBAR_TOKEN : "Logon key",
		INDEX_TOOLBAR_NEW_TOKEN : "Get new key",
		INDEX_PLAYERS_WITH_N_PLANETS : "Players with more than &1 planets",
		INDEX_GETTING_STARTED : "Getting started with the Galaxytool",
		INDEX_GETTING_STARTED1 : "Welcome to the Galaxytool!",
		INDEX_GETTING_STARTED2 : "The Galaxytool will help you to analyze what is going on in your OGame universe &1",
		INDEX_GETTING_STARTED3 : "Before you can actually analyze data you have to insert it first. For this you require a browser plugin like the &1 for Firefox.",
		INDEX_GETTING_STARTED4 : "After you installed the plugin, you navigate through your OGame pages as usual and you will see a small status window whenever something was sent to your Galaxytool.",
		INDEX_GETTING_STARTED5 : "Once the plugin inserted data into the Galaxytool, you can start to analyze where the players have their colonies, how many colonies they have, what reports exist or when they are active the most.",
		INDEX_GETTING_STARTED6 : "But it will also help you to analyze how you are progressing if you compare yourself against your competitors or by analyzing your combat reports to see how much you raided during the last days or weeks.",
		INDEX_GETTING_WIKIPAGE : "There are many more features within the Galaxytool.",
		INDEX_GETTING_WIKIPAGE2 : "Check them out at our wiki page.",
		INDEX_GETTING_BOARD : "For feedback or ideas you can use our board:",
		INDEX_GETTING_CHAT1 : "Or visit us at the chatroom:",
		INDEX_GETTING_CHAT2 : "We are not online 24/7 but spare a lot of our free time there, so be patient.",
		INDEX_CLOSE : "Close",
		INDEX_LOGIN : "Login",
		GENERAL_REQUIRED_FIELDS : "Please fill all required fields",
		INDEX_MESSAGES : "Messages",
		INDEX_EXAMPLE : "Example",
		INDEX_INVALID_DATA : "Invalid data",
		GENERAL_COLUMN_HIDE_TITLE : "Manage columns",
		GENERAL_COLUMN_HIDE_INFO : "Please select which columns you want to see in the table.",
		GENERAL_ENTRIES_DELETED : "&1 entries deleted",
		GENERAL_APPLY : "Apply",
		STARTPAGE_GALAXYTOOL_DESCR : "<em>Galaxytool</em> is a tool for the browser game OGame.",
		GENERAL_OVERWRITE : "Overwrite duplicate entry",
		GENERAL_OVERWRITE_QUESTION : "Overwrite?",
		INDEX_OWN_LOGINS : "Your logins",
		GENERAL_OPEN_IN_NEW_WINDOW : "Megnyitás új ablakban",
		GENERAL_UNIT_OF_MEASURE_DAYS : "Days",
		PROGRAM_NAME : "OGame Galaxytool",
		SHORTNAME : "Galaxytool",
		BACK_INDEX : "Vissza a főoldalra",
		UNIVERSE : "Univerzum",
		MENU_INFO_LINKS : "Információ",
		MENU_PAGE : "Áttekintés",
		MENU_DB_SEARCH : "Keresés az adatbázisban",
		MENU_DB_NOTICES : "Keresés a megjegyzésekben",
		MENU_DB_REPORTS : "Keresés a jelentésekben",
		MENU_GALAXYVIEW : "Galaxis megtekintése",
		MENU_STATISTICS : "Statisztikák",
		MENU_ALLYHISTORY : "Történelmi áttekintés",
		MENU_FLEET_MOVEMENTS : "Fleet movements",
		MENU_COMBAT_REPORTS : "Combat reports",
		MENU_MESSAGES : "Ingame messages",
		MENU_OPTION_LINKS : "Beállítások",
		MENU_DB_REFRESH : "Adatbázisba beillesztés",
		MENU_NOTICES : "Megjegyzések",
		MENU_DB_STATUS : "Adatbázis állapota",
		MENU_USEROPTIONS : "Felhasználó menedzselése",
		MENU_USEROPTIONS2 : "Felhasználói beállítások",
		MENU_USEROPTIONS3 : "Felhasználói információ",
		MENU_ADMIN : "Adminisztráció",
		MENU_LOGOUT : "Kijelentkezés",
		MENU_STUFF : "Egyebek",
		MENU_FORUM_THREAD : "Fejlesztői fórum",
		MENU_DOWNLOADPAGE : "Letöltés",
		MENU_LANGUAGE : "Nyelv",
		MENU_HELP : "Segítség",
		MENU_TOOLOPTIONS : "Galaxytool beállítások",
		PARSER_INFO1 : " be volt illesztve az adatbázisba",
		PARSER_ERROR1 : "Hiba a következő koordináták beillestésekor:",
		PARSER_ERROR2 : "Nem található az adatbazis!",
		PARSER_ERROR3 : "Nem található az adatbazis szerver!",
		PARSER_WRONG_UNIVERSE : "Rossz univerzum - aktuális: \"&1\" elvárt: \"&2\"",
		SHOW_TITLE : "OGame Galaxytool - Keresés",
		SHOW_SEARCH : "Keresés az adatbázisban",
		SHOW_ALLYSYMBOL : "Szövetség rövidítése",
		SHOW_PLAYERNAME : "Felhasználónév",
		SHOW_MOONS : "Csak a holddal rendelkező bolygók",
		SHOW_NOTICES : "Csak a megjegyzéssel rendelkező bolygók",
		SHOW_COLONIES : "Csak kolonizálható bolygók",
		SHOW_YES : "Igen",
		SHOW_NO : "Nem",
		SHOW_SEARCHRANGE : "Hely",
		SHOW_SEARCH_IN : "Keresés a galaxisban",
		SHOW_FROM_SYSTEM : "kezdő naprendszer",
		SHOW_FROM_PLANET : "kezdő bolygóhely",
		SHOW_TO : "addig",
		SHOW_DESCRIPTION : "Használhatod a *-ot helyettesítésnek a felhasználó vagy szövetség nevekben. Tehát megtalálhatod a játékosokat a nevük töredékével is.<br />Azokat a mezőket tölsd ki, amelyekre szűkiteni akarod a keresést.",
		SHOW_SORT_BY : "Rendezés módja",
		SHOW_GALASYSTEM : "Galaxis/Rendszer",
		SHOW_ALLYNAME : "Szövetség név",
		SHOW_SEARCHBUTTON : "Keresés",
		SHOW_ADDRESS : "Koordináták",
		SHOW_ALLYSORT : "Szövetség",
		SHOW_PLANET : "Bolygónév",
		SHOW_STATUS : "Státusz",
		SHOW_CURRENTNESS : "Utolsó felfrissítés",
		SHOW_PLAYER_STATUS : "Játékos státusz",
		SHOW_PLAYER_STATUS1 : "mind",
		SHOW_PLAYER_STATUS2 : "lehetséges célpont",
		SHOW_PLAYER_STATUS3 : "inaktív",
		SHOW_HITS : "Találatok",
		SHOW_OF : "az összesből",
		SHOW_ASC : "növekvő",
		SHOW_DESC : "csökkenő",
		SHOW_RESULTS : "Találatok oldalanként",
		SHOW_MOON : "Hold",
		SHOW_UKMOONSIZE : "ismeretlen",
		SHOW_DF : "DF",
		SHOW_DF_LONG : "Törmelékmező",
		SHOW_METAL : "F",
		SHOW_METAL_LONG : "Fém",
		SHOW_CRYSTAL : "K",
		SHOW_CRYSTAL_LONG : "Kristály",
		SHOW_BOTH : "a kettő együtt",
		SHOW_AT_LEAST : "(legalább)",
		SHOW_DATE : "Dátum",
		SHOW_DATE_0 : "bármikor",
		SHOW_DATE_1 : "régebbi mint",
		SHOW_DATE_2 : "újabb mint",
		SHOW_RANK : "Helyezés",
		SHOW_FRANK : "Flotta helyezés",
		SHOW_MEMBERS : "Tagok",
		SHOW_NOTRANKED : "Nincs a ranglistán.",
		SHOW_NOTICERES : "Megjegyzések",
		SHOW_REPORTS : "Csak jelentéssel rendelkező bolygók",
		SHOW_REPORTS_SHORT : "Jelentések",
		SHOW_NOTHING : "Nincs találat",
		SHOW_ALLIANCE_STATUS : "Szövetség státusz",
		SHOW_NO_STATUS : "Nincs státusz",
		SHOW_NAP : "M.N.T",
		SHOW_ALLIED : "Szövetség",
		SHOW_WAR : "Háború",
		SHOW_BOYCOTT : "Bojkott",
		SHOW_NEUTRAL : "Semleges",
		SHOW_OWN : "Saját szövetség",
		SHOW_WING : "Al-szövetség",
		SHOW_EXT_OPTIONS1 : "Több opció mutatása helyezés, helyzet, dátum vagy törmelékmező szerint.",
		SHOW_EXT_OPTIONS2 : "Több opció mutatása kolóniák, holdak, jelentések, megjegyzések, játékos vagy diplomáciai státusz szerint.",
		SHOW_EXT_OPTIONS3 : "Több opció mutatása a találatok rendezésére.",
		SHOW_EXTENDED : "advanced search",
		SHOW_MOON_SELECTION : "Planet with moon",
		SHOW_REPORT_SELECTION : "Planet with report",
		SHOW_FILTER_BY : "Exclude from the list",
		SHOW_FILTER_NONE : "egyik sem",
		SHOW_PLAYERS_WITHOUT_PROGRESS : "Show players without score changes within the last few days",
		STATUS_TITLE : "OGame Galaxytool - Státusz",
		STATUS_DB_STATUS : "Adatbázis státusz",
		STATUS_COLOR : "Szín",
		STATUS_AGE1 : "Adat 1 napos.",
		STATUS_AGE2 : "Adat 2 - 4 napos.",
		STATUS_AGE3 : "Adat 4 - 7 napos.",
		STATUS_AGE4 : "Adat 1 - 2 hetes.",
		STATUS_AGE5 : "Adat 2 - 4 hetes.",
		STATUS_AGE6 : "Adat régebbi egy honapnál!",
		STATUS_AGE7 : "Nincs adat.",
		STATUS_ON : "ideje",
		STYLES_COLOR1 : "Szín1",
		STYLES_COLOR2 : "Szín2",
		STYLES_COLOR3 : "Szín3",
		STYLES_COLOR4 : "Szín4",
		STYLES_COLOR5 : "Szín5",
		STYLES_COLOR6 : "Szín6",
		STYLES_COLOR7 : "Szín7",
		STATUS_DB_LEGEND : "Legend",
		STATUS_GALAXY : "Galaxy Overview",
		USER_TITLE : "Felhasználó menedzselés",
		USER_NAMES : "Felhazsnáló",
		USER_ERROR : "Hiba",
		USER_NEWUSER : "Új felhasználó",
		USER_OPTIONS : "Beállítások",
		USER_USERNAME : "Felhasználónév",
		USER_PASSWORD : "Jelszó",
		USER_PASSWORD_CONFIRM : "Jelszó megerősítése",
		USER_GALAXY : "Galaxis",
		USER_SEARCH : "Keresés",
		USER_INSERT : "Beillesztés",
		USER_DELETE : "Törlés",
		USER_DELETE_ENTRY : "Akarod törölni ezt a felhasználót?: ",
		USER_STATUS : "Statisztikák megtekintése",
		USER_STYLES : "Kinézet módosítása",
		USER_SUBMIT : "Elfogad",
		USER_RESET : "Nulláz",
		USER_YES : "Igen",
		USER_NO : "Nem",
		USER_STYLEPATH : "styles.css elérési útja",
		USER_PROBES : "Kémjelentés megtekintése/feltöltése",
		USER_EMAIL : "Email",
		USER_ERROR1 : "A jelszó rossz vagy az email cím hibás.",
		USER_ERROR2 : "Email-cím hibás.",
		USER_INGAME : "Játékbeli név",
		USER_ALLYTAG : "Szövetség rövidítése",
		USER_ALLYHISTORY : "Történelmi nézet megtekintése",
		USER_DIPLOMATIC : "Diplomáciai státusz megváltoztatása",
		USER_STATSPAGE : "Bejegyzések száma a statisztikák oldalán",
		USER_LINKS : "Linkek",
		USER_LINKS2 : "Formátum:<br>szöveg;url<br>szöveg2;url2<br>szöveg3;url3",
		USER_EXPORT_TITLE : "Színek exportálása (BB kódok)",
		USER_BB_COORDINATES : "Koordináták",
		USER_BB_MOON : "Hold",
		USER_BB_DEBRIS : "Törmelékmező",
		USER_BB_ALLY : "Szövetség neve",
		USER_BB_ALLYDETAILS : "Szövetség részletei",
		USER_BB_PLAYERNAME : "Játékos neve",
		USER_BB_BANNED : "Bannolt",
		USER_BB_VACATION : "Vakáció mód",
		USER_BB_NOOB : "Kezdő",
		USER_BB_INACTIVE : "Inaktív",
		USER_BB_LONGINACTIVE : "Régóta inaktív",
		USER_DELETION : "Delete",
		USER_FLEETINFO : "Fleet movements",
		USER_ACTIVITIES : "Player activities",
		USER_MAINTENANCE : "Galaxytool maintenance",
		USER_MANAGEMENT : "Felhasználó menedzselése",
		USER_DELETE_MY_COMBAT_REPORTS : "Delete my combat reports",
		USER_DELETE_MY_MESSAGES : "Delete my messages",
		USER_DELETE_MY_FLEETMOVES : "Delete my fleet movements",
		USER_DELETE_MY_COMBAT_REPORTS_LIMITED : "Delete my combat reports older than &1 days",
		USER_DELETE_MY_MESSAGES_LIMITED : "Delete my messages older than &1 days",
		USER_TABLE_ENTRIES : "Number of search results for each page",
		USER_EXISTS : "User already exists",
		USER_BB_OUTLAW : "Outlaw",
		USER_INVALID_URL : "URL &1 seems to be invalid - URL will be ignored",
		VIEW_TITLE : "OGame Galaxytool - Galaxis nézet",
		VIEW_NODATA : "Nincs elérhető adat.",
		VIEW_GALAXY : "Galaxis",
		VIEW_SYSTEM : "Naprendszer",
		VIEW_POSITION : "Poz.",
		VIEW_PLANET : "Bolygó",
		VIEW_MOON : "Hold",
		VIEW_TF : "DF",
		VIEW_PLAYER : "Játékos",
		VIEW_PLAYER_ADD : "(Rang / Státusz)",
		VIEW_ALLY : "Szövetség",
		VIEW_ALLY_ADD : "(Rank / Member)",
		VIEW_METAL : "F",
		VIEW_CRYSTAL : "K",
		VIEW_COLONISED : "kolonizált bolygó",
		VIEW_UKMOONSIZE : "ismeretlen",
		VIEW_BACK : "vissza",
		VIEW_NOTICE : "Megjegyzések",
		VIEW_REPORTS : "Jelentések",
		VIEW_MOONPHALANX : "A következő holdakról szkennelhető ez a naprendszer",
		VIEW_NOMOONS : "Nincs ilyen hold",
		VIEW_IRAKS : "Az alábbi bolygókról érhető el bolygóközi rakétákkal ez a naprendszer",
		VIEW_NOIRAKS : "Nincs ilyen bolygó",
		VIEW_MOON_DESTROY_CHANCE : "Esély a hold megsemmisítésére",
		VIEW_CHANCE_WITH_ONE : "Esély egy halálcsillaggal",
		VIEW_CHANCE_WITH_N : "Esély ",
		VIEW_DEATH_STARS : "halálcsillaggal",
		VIEW_DS_DESTROY_CHANCE : "Esély a halálcsillag(ok) elvesztésére",
		VIEW_TOP : "Fel",
		VIEW_GO : "mehet",
		VIEW_DIAMETER : "Diameter",
		PW_TITLE : "OGame Galaxytool - Jelszó változtatás",
		OLD_PASSWORD : "Régi jelszó",
		NEW_PASSWORD : "Új jelszó",
		CONFIRM_NEW_PASSWORD : "Új jelszó megerősítése",
		PW_MISMATCH : "A jelszavak nem egyeznek!",
		PW_ERROR : "Régi jelszó hibás!",
		UPDATE_DONE : "Változtatás megtörtént.",
		TIMEZONE_OFFSET : "Idoeltolódás a s szervertol",
		DELETE_ACCOUNT : "Galaxytool felhasználó törlése",
		DELETE_ACCOUNT_SAFETY_REQUEST : "Tényleg törölni akarod a felhasználót?",
		CH_PASSWD_AUTHORIZATION : "Engedélyek",
		CH_PASSWD_ADMIN : "Admin",
		TIMEZONE_OGAME_OFFSET : "Timezone offset to OGame server",
		CH_PASSWD_USER_LANGUAGE : "Change to this language after logon",
		CH_PASSWD_USER_LANGUAGE_NO_CHANGE : "No change",
		CH_PASSWD_EXPAND : "Expanded",
		CH_PASSWD_COLLAPSE : "Collapsed",
		CH_PASSWD_HIDDEN : "Hidden",
		CH_PASSWD_GETTING_STARTED : "Show Getting Started Info after logon",
		CH_PASSWD_PLUGIN : "Show Plugin Info after logon",
		NOTICE_TITLE : "OGame Galaxytool - Megjegyzések",
		NOTICE_HEADER : "Megjegyzés módosítása",
		NOTICE_HEADER2 : "Saját megjegyzések módosítása",
		NOTICE_PUBLIC : "Hozzáférhető másnak is?",
		NOTICE_YES : "igen",
		NOTICE_NO : "nem",
		NOTICE_TEXT : "Megjegyzés szövege",
		NOTICE_SAVE : "Mentés",
		NOTICE_DELETED : "Megjegyzés eltörölve",
		NOTICE_SAVED : "Megjegyzés elmentve",
		NOTICE_RESULTS : "Összes találat",
		NOTICE_USER : "Felhasználó",
		NOTICE_DATE : "Dátum",
		NOTICE_EDIT : "Módosítá",
		NOTICE_DELETE : "Törlés",
		NOTICE_NEW : "Saját megjegyzés létrehozása",
		NOTICE_NOTPUBLIC : "Megjegyzése nem nyilvános.",
		NOTICE_ALL : "mindegyik",
		NOTICE_NONE : "egyik sem",
		NOTICE_SEARCH : "Keresés a Megjegyzések között",
		NOTICE_SEARCH_SHORT : "Keresés",
		NOTICE_HITS : "Találatok",
		NOTICE_SHOWRESULTS : "Találatok oldalanként",
		NOTICE_OF : "az összesből",
		NOTICE_NOTHING : "Nincs találat",
		NOTICE_CHARS : "Karakterek",
		NOTICE_PLAYERNAME : "Játékos",
		NOTICE_SHOWALL : "Minden megjegyzés mutatása",
		REPORTS_TITLE : "OGame Galaxytool - Kémjelentések",
		REPORTS_RESOURCES : "Erőforrások",
		REPORTS_FLEET : "Flották",
		REPORTS_DEFENCE : "Védelem",
		REPORTS_BUILDINGS : "Épületek",
		REPORTS_TECHNOLOGY : "Kutatás",
		REPORTS_MOON : "Hold",
		REPORTS_SEARCH : "Keresés a kémjelentésekben",
		REPORTS_SEARCH_SHORT : "Keresés",
		REPORTS_HITS : "Találatok",
		REPORTS_NOTHING : "Nincs találat",
		REPORTS_ADDRESS : "Koordináták",
		REPORTS_CURRENTNESS : "Frissítés ideje",
		REPORTS_PLAYERNAME : "Játékos neve",
		REPORTS_ALLY : "Szövetség",
		REPORTS_VIEW : "Jelentés megtekintése",
		REPORTS_SEARCH_IN : "Keresés a Galaxisban",
		REPORTS_FROM_SYSTEM : "attól a naprendszertől",
		REPORTS_TO : "addig",
		REPORTS_DELETE : "törlés",
		REPORTS_DELETED : "Jelentés eltörölve",
		REPORTS_RESULTS : "találat oldalanként",
		REPORTS_OF : "az összesből",
		REPORTS_DATE : "Dátum",
		REPORTS_DATE_0 : "bármikor",
		REPORTS_DATE_1 : "régebbi mint",
		REPORTS_DATE_2 : "újabb mint",
		REPORTS_NOTICES : "Megjegyzések",
		REPORTS_AT_LEAST_RESOURCES : "Erőforrások (legalább)",
		REPORTS_SEARCH_EXTENDED : "kiterjesztett keresés",
		REPORTS_FLEET_RESIS : "Flotta pontok",
		REPORTS_DEFENCE_RESIS : "Védelem pontok",
		REPORTS_ALL_RESIS : "összes pontok",
		REPORTS_TECHS : "Technológiák",
		REPORTS_UNKNOWN_ENTRIES : "ismeretlen bejegyzések",
		REPORTS_PARTLY_INSERTED : "részlegesen beillesztve",
		REPORTS_FOR_ALL_RES : "az összes erőforrásokra",
		REPORTS_FOR_TF : "a DF-re",
		REPORTS_KT : "Kis szállító",
		REPORTS_GT : "Nagy Szállító",
		REPORTS_SS : "Csatahajó",
		REPORTS_REC : "Szemetes",
		REPORTS_RAIDABLE : "Csak a támadható célok",
		REPORTS_ALL_RESOURCES : "összes erőforrások",
		REPORTS_STUFF : "Egyebek",
		REPORTS_SPEEDSIM : "Szimuláció Speedsim",
		REPORTS_DRAGOSIM : "Szimuláció Dragosim",
		REPORTS_STATUS : "Státusz",
		REPORTS_ERROR : "Hiba történt",
		REPORTS_OWN_REPORTS : "Csak a saját jelentéseimet",
		REPORTS_UPLOAD_BY : "Általa feltöltött jelentések",
		REPORTS_DEPTH : "Jelentés \"mélysége\"",
		REPORTS_FLEET_SCORE : "Flottapont",
		REPORTS_DEFENCE_SCORE : "Védelmi pont",
		REPORTS_HOURS : "hours",
		REPORTS_MAX_RESULTS_HIT : "Your query returned more than &1 hits. Only the first &1 results are show. Please adjust your search request to get less results.",
		REPORTS_OSIMULATE : "Simulate with OSimulate",
		REPORTS_SHOW_ONLY : "Show only",
		REPORTS_SHOW_PLANETS : "Bolygók",
		REPORTS_SHOW_MOONS : "Holdak",
		REPORTS_OWNER : "Reports owned by",
		STATS_TITLE : "OGame Galaxytool - Statisztikák",
		STATS_TBLHEAD : "Statisztikák",
		STATS_RANK : "Helyezés",
		STATS_PLAYERNAME : "Játékos neve",
		STATS_ALLYNAME : "Szövetség rövidítése",
		STATS_SCORE : "Pontok",
		STATS_FLEET : "Flotta",
		STATS_RESEARCH : "Kutatás",
		STATS_MEMBERS : "Tagok",
		STATS_STATUS : "Státusz",
		STATS_NOTHING : "nincs Státusz",
		STATS_NAP : "M.N.T",
		STATS_ALLIED : "Szövetség",
		STATS_WAR : "Háború",
		STATS_BOYCOTT : "Bojkott",
		STATS_NEUTRAL : "Neutral",
		STATS_OWN : "Saját Szövetség",
		STATS_WING : "Al-szövetség",
		STATS_UPDATE : "Bejegyzés dátuma",
		STATS_PLAYERSTATS : "Játékos statisztikák",
		STATS_ALLYSTATS : "Szövetség statiszikák",
		STATS_DELETE : "Akarod-e törölni ezt a bejegyzést?",
		STATS_CONFIRM_DELETE : "Valóban törölni akarod ezt a bejegyzést?",
		STATS_CHANGE_PLAYER_STATUS : "Játékos státusza",
		STATS_CHANGE_ALLIANCE_STATUS : "Szövetség státusza",
		STATS_CHANGE_ALLIANCE_STATUS_HINT : "A szövetségben az összes játékos kapja a kiválasztott státuszt. Bármilyen előbbi státusz felül van írva. Utána még mindig tudod módosítani a játékosok egyéni státuszát.",
		STATS_UNKNOWN : "Nincs státusz",
		STATS_DETAILS : "Részletek",
		STATS_PLAYERSTATUS : "Játékos státusz",
		STATS_IGNORE_STATUS : "mind",
		STATS_ACTIVE : "aktív",
		STATS_INACTIVE : "Inaktív",
		STATS_BANNED : "Bannolt",
		STATS_VACATION : "Vakáció mód",
		STATS_NOOB : "Kezdő",
		STATS_YES : "Igen",
		STATS_NO : "Csak a megjegyzéssel rendelkező bolygók",
		STATS_SEARCH : "Keresés",
		STATS_SHOW_GRAPH : "Show details for score distribution",
		STATS_LONG_INACTIVE : "Régóta inaktív",
		STATS_STANDARD : "Standard Points",
		STATS_MILITARY : "Military Points",
		STATS_ECONOMY : "Economy",
		STATS_HONOUR : "Honour points",
		STATS_MILITARY_BUILD : "Military build",
		STATS_MILITARY_DESTROYED : "Military destroyed",
		STATS_MILITARY_LOST : "Military lost",
		REGISTER_REGISTRATE : "Regisztráció",
		REGISTER_LOGINNAME : "Felhasználónév",
		REGISTER_PASSWORD : "Jelszó",
		REGISTER_PASSWORD_CONFIRM : "Jelszó megerősítése",
		REGISTER_EMAIL : "Email",
		REGISTER_INGAME : "Játékbeli név",
		REGISTER_ALLYTAG : "Szövetség rövidítése",
		REGISTER_EMAILVERIFICATION : "Email megerősítő",
		REGISTER_EMAILTEXT : "Kérlek kattints a következő linkre, hogy megerősítsd a regisztrációdat a galaxistoolban.",
		REGISTER_ERROR1 : "Felhasználónév foglalt.",
		REGISTER_ERROR2 : "Hiba az email küldése során. Kérlek lépj kapcsolatba az adminnal.",
		REGISTER_ERROR3 : "Hiba az adatbázishoz valo csatlakozás során!",
		REGISTER_INFO1 : "A felhasználóneved elkészült.",
		REGISTER_INFO2 : "Kérlek kattints a linkre a kapott email-ben, hogy megerősítsd a regisztrációt.",
		REGISTER_INFO3 : "Regisztráció megerősítve. Mostmár csak az adminnak kell aktiválnia.",
		REGISTER_BUTTON : "Vissza a főoldalra",
		REGISTER_NEW_SUBJECT : "Új felhasználó regisztrált a galaxytoolban",
		REGISTER_NEW_MAILTEXT : "Új felhasználó regisztrált.",
		REGISTER_BACK : "Vissza az elso oldalra",
		REGISTER_MISSING_FIELDS : "Tölts ki minden mezot",
		REGISTER_ERROR4 : "Email address is not valid.",
		REGISTER_ERROR5 : "Passwords don't match.",
		REGISTER_PWS : "Password strength",
		REGISTER_PWS0 : "very weak",
		REGISTER_PWS1 : "weak",
		REGISTER_PWS2 : "good",
		REGISTER_PWS3 : "strong",
		REGISTER_PWS4 : "very strong",
		REGISTER_EMAIL_USED : "Email Address is already used",
		LOSTPW_TITLE : "Elvesztett jelszó",
		LOSTPW_INFO2 : "Új jelszó létrehozva és elküldve az email címedre.",
		LOSTPW_BUTTON1 : "új jelszó kérése",
		LOSTPW_BUTTON2 : "Vissza a főoldalra",
		LOSTPW_LOGINNAME : "Felhasználónév",
		LOSTPW_EMAIL : "Email",
		LOSTPW_ERROR1 : "Hiba az adatbázishoz való csatlakozáskor!",
		LOSTPW_ERROR2 : "Nem található a kérésének megfelelő bejegyzés!",
		LOSTPW_ERROR3 : "Hiba email küldésekor. Kérlek lépj kapcsolatba az adminnal.",
		LOSTPW_EMAIL_SUBJECT : "Új jelszavad",
		LOSTPW_EMAIL_TEXT1 : "Itt az új bejelentkezési információ a Galaxytoolra",
		LOSTPW_EMAIL_TEXT2 : "Felhasználóneved",
		LOSTPW_EMAIL_TEXT3 : "Jelszavad",
		LOSTPW_INFO1 : "You will receive an email to verify your password reset request.",
		LOSTPW_CONFIRM_RESET_SUBJECT : "Lost password?",
		LOSTPW_CONFIRM_RESET_MESSAGE : "Hello,\n\nyou requested a password reset for the Galaxytool. To generate a new password, click the following link:",
		USERINFO_TITLE : "OGame Galaxytool - Felhasználó információ",
		USERINFO_NAMES : "Az összes felhasználó",
		USERINFO_DETAIL : "Részletes adatok róla:",
		USERINFO_ERROR1 : "Nincs ilyen azonosítójú felhasználó!",
		USERINFO_USERNAME : "Felhasználónév",
		USERINFO_INGAME : "Játékbeli név",
		USERINFO_EMAIL : "Email",
		USERINFO_ALLYTAG : "Szövetség",
		USERINFO_STYLEPATH : "Skin",
		USERINFO_STATUS : "Státusz",
		USERINFO_ACTIVATE : "Felhasználó aktiválása",
		USERINFO_LOGINS : "Bejelentkezések",
		USERINFO_LASTLOGIN : "Utolsó bejelentkezés",
		USERINFO_DATA : "Beillesztett naprendszerek",
		USERINFO_NODATA : "Ez a felhasználó még nem illesztett be naprendszereket!",
		USERINFO_GALAXY : "Galaxis",
		USERINFO_SYSTEMS : "Naprendszerek",
		USERINFO_IP : "IP cím",
		USERINFO_LOGINTIME : "Bejelentkezés",
		USERINFO_NOLOGIN : "Ez a felhasználó még soha sem lépett be.",
		USERINFO_LAST_GALAXYUPDATE : "Utolsó beillesztett galaxis",
		USERINFO_LAST_PUBLIC_NOTICE : "Utolsó nyilvános megjegyzés",
		USERINFO_LAST_PRIVATE_NOTICE : "Utolsó magán megjegyzés",
		USERINFO_NUMBEROF_PUBLIC_NOTICE : "Összes nyilvános megjegyzés",
		USERINFO_NUMBEROF_PRIVATE_NOTICE : "Összes magán megjegyzés",
		USERINFO_ACTIVATED : "Felhasználó aktiválva",
		USERINFO_ACTIVATIONTEXT : "A Galaxytool adminja aktiválta a felhasználóneved.\n\nHasználd egészséggel a Galaxytool-t!",
		USERINFO_LAST_SUBMIT : "Inserted last data",
		ALLYHISTORY_TITLE : "OGame Galaxytool - Szövetség történelem",
		ALLYHISTORY_TBLHEAD : "Történelmi áttekintés",
		ALLYHISTORY_PLAYERNAME : "Játékos neve",
		ALLYHISTORY_ALLYNAME : "Szövetség",
		ALLYHISTORY_LASTMONTH : "Múlt hónap",
		ALLYHISTORY_ALL_DATA : "Minden elérhető információ",
		ALLYHISTORY_SHOW : "Statisztikák megjelenítése",
		ALLYHISTORY_TIMESPAN : "Időtartomány",
		ALLYHISTORY_PROGESS : "Haladás",
		ALLYHISTORY_SCORE : "Pontok",
		ALLYHISTORY_FSCORE : "Flotta pontok",
		ALLYHISTORY_RSCORE : "Kutatás pontok",
		ALLYHISTORY_MEMBER : "Tagok",
		ALLYHISTORY_NOTHING : "Nem találhato bejegyzés",
		ALLYHISTORY_DETAILS : "Részletek",
		ALLYHISTORY_SHOW_ADDRESS : "Koordináták",
		ALLYHISTORY_ESCORE : "Economy",
		ALLYHISTORY_MSCORE : "Military Points",
		DETAILEDINFO_PLAYERINFO_TITLE : "Játékos információ",
		DETAILEDINFO_ALLYINFO_TITLE : "Szövetség információ",
		DETAILEDINFO_PLAYERINFO_TBLHEAD : "Részletes információ a jatékosról",
		DETAILEDINFO_ALLYINFO_TBLHEAD : "Részletes információ a szövetségről",
		DETAILEDINFO_NO_ALLIANCE : "nincs",
		DETAILEDINFO_SCORE : "Pont helyezés",
		DETAILEDINFO_FLEET : "Flotta helyezés",
		DETAILEDINFO_RESEARCH : "Kutatás helyezés",
		DETAILEDINFO_RANK : "Rang",
		DETAILEDINFO_POINTS : "Pontok",
		DETAILEDINFO_KNOWN_PLANETS : "ismert bolygó",
		DETAILEDINFO_MOONS : "ismert hold",
		DETAILEDINFO_PHALANX_AREA : "Phalanx övezet",
		DETAILEDINFO_NO_PHALANX_AREA : "nem található Phalanx",
		DETAILEDINFO_NOTICES : "Megjegyzések",
		DETAILEDINFO_NO_NOTICES : "Nem találhato megjegyzés",
		DETAILEDINFO_PREVIOUS_ALLIANCES : "előző Szövetségek",
		DETAILEDINFO_RESOURCES_PER_HOUR : "Erőforrások óránként",
		DETAILEDINFO_RESOURCES_PER_DAY : "Erőforrások naponként",
		DETAILEDINFO_RESOURCES_PER_WEEK : "Erőforrások hetenként",
		DETAILEDINFO_RESOURCES_PER_MONTH : "Erőforrások havonként (30 naponként)",
		DETAILEDINFO_METAL : "Fém",
		DETAILEDINFO_CRYSTAL : "Kristály",
		DETAILEDINFO_DEUTERIUM : "Deutérium",
		DETAILEDINFO_UNKNOWN : "ismeretlen",
		DETAILEDINFO_SCORE_DISTRIBUTION : "Pontok elosztása",
		DETAILEDINFO_GENERAL : "Adatlap",
		DETAILEDINFO_MEMBERS : "Felhasználó",
		DETAILEDINFO_GRAPHS : "Grafikonok",
		DETAILEDINFO_RESOURCES : "Eroforrások",
		DETAILEDINFO_FLEET_TAB : "Flotta",
		DETAILEDINFO_TECH : "Kutatások",
		DETAILEDINFO_FLEET_DETAIL : "Összesen / (játékos átlagok) minden elérheto jelentés alapján",
		DETAILEDINFO_TECH_DETAIL : "Az összes információ átlaga",
		DETAILEDINFO_PLANET_TAB : "Bolygók",
		DETAILEDINFO_MOON_TAB : "Holdak",
		DETAILEDINFO_ACTIVITIES : "Activities",
		DETAILEDINFO_NODATA : "Nincs elérhető adat.",
		DETAILEDINFO_ACTIVITY_DESCRIPTION : "Show activities of &1 collected from:",
		DETAILEDINFO_GALAXYVIEWS : "Galaxy views",
		DETAILEDINFO_SCANS : "Espionage actions",
		DETAILEDINFO_MESSAGES : "Player messages",
		DETAILEDINFO_COMBATS : "Combat reports",
		DETAILEDINFO_ALLYPAGE : "Alliance overview",
		DETAILEDINFO_MANUAL : "Manual insertions",
		DETAILEDINFO_START : "Beginning",
		DETAILEDINFO_TO : "to",
		DETAILEDINFO_TODAY : "Today",
		DETAILEDINFO_DATA_RESTRICTION : "restricted to:",
		DETAILEDINFO_WEEKDAY_WEEKEND : "Weekend",
		DETAILEDINFO_WEEKDAY_WORKINGDAY : "Weekday",
		DETAILEDINFO_WEEKDAY_MONDAY : "Monday",
		DETAILEDINFO_WEEKDAY_TUESDAY : "Tuesday",
		DETAILEDINFO_WEEKDAY_WEDNESDAY : "Wednesday",
		DETAILEDINFO_WEEKDAY_THURSDAY : "Thursday",
		DETAILEDINFO_WEEKDAY_FRIDAY : "Friday",
		DETAILEDINFO_WEEKDAY_SATURDAY : "Saturday",
		DETAILEDINFO_WEEKDAY_SUNDAY : "Sunday",
		DETAILEDINFO_WEEKDAY_SHORTLENGTH : 3,
		DETAILEDINFO_PLAYER_CURRENTLY_ACTIVE : "The player is currently active",
		DETAILEDINFO_PLAYER_MESSAGES : "available player messages",
		DETAILEDINFO_SHOW : "show",
		DETAILEDINFO_NONE : "none available",
		DETAILEDINFO_ENTER_MANUALLY : "Enter activities for this player",
		DETAILEDINFO_PLAYER_SEEN_ON : "Player was online on",
		DETAILEDINFO_INSERT : "Insert",
		DETAILEDINFO_OGAME_SERVERTIMES : "Please note: All dates and times refer to OGame server times !",
		DETAILEDINFO_DAY_VIEW : "24 hours view",
		DETAILEDINFO_WEEK_VIEW : "weekly view",
		DETAILEDINFO_HOME_PLANET : "Homeworld",
		DETAILEDINFO_PLANETNAME : "Name",
		DETAILEDINFO_DEFENCE_SCORE : "Defence score",
		DETAILEDINFO_DEFENCE_SCORE_TOOLTIP : "Defence score = Fleet - Score + Research + Economy.<br/>All those statistics must be up to date to have a meaningful result!",
		DETAILEDINFO_SCORE_PER_SHIP : "Scores per ship",
		DETAILEDINFO_SHIPS : "Number of ships",
		DETAILEDINFO_DATE_IN_FUTURE : "Do not maintain times which are not in the past.",
		ADMIN_TITLE : "Galaxytool adminisztráció",
		ADMIN_DISCLAMER : "Figyelem: Csak saját felelosségre futtasd! Többségük adattörlésre való.",
		ADMIN_INCONSISTENCIES : "Adatbázis összeegyezhetetlenségek",
		ADMIN_PLANETS : "Bolygók a 0 vagy 15-nél nagyobb pozíciókon",
		ADMIN_GALAXIES : "Törölj e feletti galaxisokat &1",
		ADMIN_PLAYERS : "Törölj OGame felhasználónév nélküli felhasználókat - dupla felhasználói bejegyzésekhez vezethet",
		ADMIN_REPORTS : "Töröld a már nem létezo bolygók jelentéseit",
		ADMIN_MISC : "Egyebek",
		ADMIN_RESET : "Galaxytool ürítése (csak a felhasználók és az IP címek maradnak meg)",
		ADMIN_OLD_PLAYERS : "A &1 napnál régebbi felhasználók törlése",
		ADMIN_OLD_REPORTS : "A &1 napnál régebbi jelentések törlése",
		ADMIN_LOADING : "Ne zárd be ezt az ablakot míg be nem töltodik teljesen.",
		ADMIN_STATUS : "Lekérdezéseid státusza",
		ADMIN_SELECTION : "Legalább egy bejegyzést ki kell jelölnöd",
		ADMIN_SAFETY : "Biztos, hogy lefuttatod ezeket a scripteket?",
		ADMIN_DONE : "kész",
		ADMIN_NOTBD : "nem kellett semmit tenni",
		ADMIN_OLD_GALAXIES : "Törölj &1 napnál régebbi galaxis nézeteket",
		ADMIN_UNUSED_PLAYERS : "Töröld azokat a felhasználókat melyek nem jelennek meg egy galaxis nézetben sem.",
		ADMIN_OLD_ACTIVITIES : "Remove player activities older than &1 days",
		ADMIN_OLD_COMBATS : "Remove combat reports older than &1 days",
		ADMIN_OLD_INGAME_MSG : "Remove ingame messages older than &1 days",
		ADMIN_OGAME_API : "Load public data from OGame into the Galaxytool",
		ADMIN_OGAME_ALL_DATA : "Minden elérhető információ",
		ADMIN_OGAME_GALAXY_DATA : "Galaxis megtekintése",
		ADMIN_OGAME_STATISTICS_DATA : "Statisztikák",
		ERRORPAGE_PAGEFORWARD : "Kattints ide ha a böngésződ nem támogatja az átirányítást",
		ERRORPAGE_PERMISSION_DENIED : "Nincs jogosultságod megtekinteni ezt az oldalt. Kattints, hogy lépj vissza.",
		FLEETS_TITLE : "OGame Galaxytool - Fleet movements",
		FLEETS_ACTUAL_FLEETS : "Current fleet movements",
		FLEETS_YES : "Igen",
		FLEETS_NO : "Csak a megjegyzéssel rendelkező bolygók",
		FLEETS_DETAILS : "Details",
		FLEETS_MISSION_EXPEDITION : "Expedition",
		FLEETS_MISSION_COLONIZATION : "Colonize",
		FLEETS_MISSION_RECYCLE : "Harvest",
		FLEETS_MISSION_TRANSPORT : "Transport",
		FLEETS_MISSION_DEPLOYMENT : "Deploy",
		FLEETS_MISSION_ESPIONAGE : "Espionage",
		FLEETS_MISSION_ACS_DEFEND : "ACS Defend",
		FLEETS_MISSION_ATTACK : "Attack",
		FLEETS_MISSION_ACS_ATTACK : "ACS Attack",
		FLEETS_MISSION_MOON_DESTRUCTION : "Moon Destruction",
		FLEETS_MISSION_MISSILE_ATTACK : "Missile Attack",
		FLEETS_NO_DATA : "No applicable data found",
		FLEETS_FLEET : "Fleet",
		FLEETS_ALL_FLEETS : "Show all fleet movements",
		COMBAT_REPORT_OUDATED_GALAXYVIEW : "Your galaxy data is outdated. Please visit combat origin and target coordinates first!",
		MESSAGES_TITLE : "OGame Galaxytool - OGame Messages",
		MESSAGES_PLAYERNAME : "Playername",
		MESSAGES_SUBJECT : "Subject",
		MESSAGES_DATE : "Date",
		MESSAGES_FILTER : "Filter",
		MESSAGES_DELETE : "Delete message",
		MESSAGES_PUBLISH_DETAIL : "Publish message by adding the message content to notice text of that player.",
		MESSAGES_PUBLISH_HEADER : "&sender sent a message to &recipient on &date:\n\n &message",
		MESSAGES_PLAYER_FILTER : "Messages for player:",
		MESSAGES_CONTENT : "Content",
		COMBATS_TITLE : "OGame Galaxytool - Combat reports",
		COMBATS_ATTACKER : "Attacker",
		COMBATS_DEFENDER : "Defender",
		COMBATS_DATE : "Date",
		COMBATS_OWNER : "Owner",
		COMBATS_WINNER : "Winner",
		COMBATS_COMBATREPORT : "Combat Report",
		COMBATS_COMBAT_AT : "Combat at",
		COMBATS_LOST_UNITS : "Lost units",
		COMBATS_LOOT : "Loot",
		COMBATS_DEBRIS : "Debris",
		COMBATS_AND : "and",
		COMBATS_PUBLISH : "Make this report public",
		COMBATS_UNPUBLISH : "Unshare this report (makes it private again)",
		COMBATS_DELETE : "Delete report",
		COMBATS_CHECK_ALL : "Check All",
		COMBATS_UNCHECK_ALL : "Uncheck All",
		COMBATS_WITH_SELECTED : "With selected",
		COMBATS_PUBLIC_REPORTS : "Public reports",
		COMBATS_YES : "Igen",
		COMBATS_NO : "Csak a megjegyzéssel rendelkező bolygók",
		COMBATS_SEARCH_OPTIONS : "Search options",
		COMBATS_SEARCH : "Go",
		COMBATS_RESET : "Reset",
		COMBATS_COORDINATES : "Koordináták",
		COMBATS_INVALID_GALAXY_ENTERED : "Invalid Galaxy entered",
		COMBATS_INVALID_SYSTEM_ENTERED : "Invalid System entered",
		COMBATS_INVALID_PLANET_ENTERED : "Invalid Planet entered",
		COMBATS_GALAXY_FROM_TO : "Galaxy",
		COMBATS_SYSTEM_FROM_TO : "System",
		COMBATS_PLANET_FROM_TO : "Planet",
		COMBATS_APPLY : "Apply",
		COMBATS_COMBAT_SUMMARY : "Combat report summary",
		COMBATS_DOWNLOAD_CSV : "Download as CSV file",
		REPORT_ARCHIVE_TITLE : "Report archive",
		REPORT_ARCHIVE_COORDINATES : "Coordinates",
		REPORT_ARCHIVE_SCANTIME : "Scan time",
		REPORT_ARCHIVE_DELETE : "Delete these entries",
		REPORT_ARCHIVE_CONFIRM_DELETE : "Do you really want to delete these entries?",
		REPORT_ARCHIVE_GALAXY : "Galaxy",
		REPORT_ARCHIVE_SYSTEM : "System",
		REPORT_ARCHIVE_PLANET : "Planet",
		REPORT_ARCHIVE_MOON : "Moon",
		REPORT_ARCHIVE_DETAILS : "Details",
		REPORT_ARCHIVE_RESOURCES : "Erőforrások óránként",
		REPORT_ARCHIVE_HEADER_RESOURCES : "Erőforrások",
		REPORT_ARCHIVE_DETAILS_FOR : "Report archive for &1 [&2] (&3)",
		REPORT_ARCHIVE_FLEET_CARGO : "Fleet cargo capacity",
		REPORT_ARCHIVE_IRAK_RANGE : "Interplanetary Missiles range",
		REPORT_ARCHIVE_CHART_TYPE : "Chart type",
		INSTALL_TITLE : "Galaxytool installation for version",
		INSTALL_PROGRESS : "Overall progress",
		INSTALL_STEP : "Step",
		INSTALL_CONTINUE : "Continue",
		INSTALL_VALIDATE : "Validate",
		INSTALL_STEP1 : "Welcome",
		INSTALL_STEP2 : "Writeable check",
		INSTALL_STEP3 : "Database settings",
		INSTALL_STEP4 : "OGame settings",
		INSTALL_STEP5 : "Galaxytool settings",
		INSTALL_STEP6 : "Admin password",
		INSTALL_STEP7 : "Install Galaxytool",
		INSTALL_STEP8 : "Finalize install",
		INSTALL_FILE_DELETE_CHECK : "Please delete install.php and update.php from your webserver.",
		INSTALL_STEP1_PHP_FAILED : "Your PHP version &1 is not working with this Galaxytool version",
		INSTALL_STEP1_FOPEN_FAILED : "Your PHP version does not allow to open webpages with FOPEN() command. This is required to consume the OGame API.",
		INSTALL_STEP1_WELCOME : "Welcome to the installation wizard of the Galaxytool. You will be guided through the installation of the Galaxytool.",
		INSTALL_STEP2_DESCRIPTION : "Make sure your config.php and attributes.php files have write permissions enabled.",
		INSTALL_STEP2_DESCRIPTION2 : "If you don't know, how to achieve this, please take a look here: &1",
		INSTALL_STEP2_FILE_NOT_WRITEABLE : "File is not writeable",
		INSTALL_STEP3_SERVER : "Database server",
		INSTALL_STEP3_USERNAME : "Felhasználónév",
		INSTALL_STEP3_PASSWORD : "Jelszó",
		INSTALL_STEP3_DBNAME : "Database name",
		INSTALL_STEP3_PREFIX : "Tablename prefix",
		INSTALL_STEP3_ENTER_PREFIX : "E.g. mytool_",
		INSTALL_STEP3_ENTER_SERVER : "Enter the server address. Contact your system admin if necessary. Usually the correct value is localhost.",
		INSTALL_STEP3_ENTER_USERNAME : "Enter the username for database access",
		INSTALL_STEP3_ENTER_PASSWORD : "Enter the password for database access",
		INSTALL_STEP3_ENTER_DBNAME : "Enter the database name which shall be used for installation (must exist)",
		INSTALL_STEP3_CONNECT_FAILED : "Could not establish connection to database server",
		INSTALL_STEP3_DB_FAILED : "Database &1 not found",
		INSTALL_STEP3_MYSQL_VERSION_FAILED : "MySQL version &1 is not working with this Galaxytool version",
		INSTALL_STEP4_URL : "OGame URL",
		OGAME_URL_DETAILS : "Please enter any URL you see when you are logged on to OGame. Based on that URL the tool will derive the OGame API address which can be used to fill data into the Galaxytool without the Galaxytoolbar. This API was introduced with OGame version 4.1.",
		INSTALL_STEP4_UNIVERSE : "OGame Universe",
		INSTALL_STEP4_DEF_TO_DEBRIS : "Defense to debris",
		INSTALL_STEP4_DEBRIS_RATE : "Debris rate",
		INSTALL_STEP4_SPEED_RATE : "Speed rate",
		INSTALL_STEP4_ENTER_UNIVERSE : "Enter your OGame universe name or number (case sensitive).",
		INSTALL_STEP4_UNIVERSE_MISSING : "You must define your universe",
		INSTALL_STEP4_ENTER_URL : "Enter your OGame universe address",
		INSTALL_STEP4_URL_MISSING : "You must define your OGame address",
		INSTALL_STEP4_URL_CHECK_FAILED : "Could not find OGame API at &1",
		INSTALL_STEP4_GETSETTINGS : "Fetch settings",
		INSTALL_STEP5_TOOLNAME : "Galaxytool name",
		INSTALL_STEP5_ENTER_TOOLNAME : "This is the name which will be shown at logon page to identify your Galaxytool",
		INSTALL_STEP5_LANGUAGE : "Default language",
		INSTALL_STEP5_EMAIL_TO : "Email To",
		INSTALL_STEP5_ENTER_EMAIL_TO : "Enter the email address where you would like to receive notifications about registrations",
		INSTALL_STEP5_EMAIL_FROM : "Email From",
		INSTALL_STEP5_ENTER_EMAIL_FROM : "This email address is shown as REPLY for all mails sent from the Galaxytool",
		INSTALL_STEP5_USE_PHPMAILER : "Use PHPMailer",
		INSTALL_STEP5_MAXSHOUTS : "Maximum number of shoutbox entries",
		INSTALL_STEP5_ENTER_USE_PHPMAILER : "Use PHPMailer if your server does not support sending emails by default",
		INSTALL_PHPMAILER_HOST : "SMPT Host",
		INSTALL_PHPMAILER_HOST_EXAMPLE : "e.g. smtp.provider.com",
		INSTALL_PHPMAILER_USER : "SMPT Username",
		INSTALL_PHPMAILER_USER_EXAMPLE : "e.g. user@provider.dcom",
		INSTALL_PHPMAILER_PASS : "SMPT password",
		INSTALL_PHPMAILER_SECURE : "Authentification method (e.g. ssl)",
		INSTALL_PHPMAILER_PORT : "SMTP Port",
		INSTALL_STEP6_INTRO : "Please define a password for the <strong>admin</strong> account which you have to use for your first logon to the Galaxytool after the installation.",
		INSTALL_STEP7_CONFIG : "Configuration file created",
		INSTALL_STEP7_CONFIG_FAILED : "Configuration file not created",
		INSTALL_STEP7_ATTRIBUTES : "Attributes file created",
		INSTALL_STEP7_ATTRIBUTES_FAILED : "Attributes file not created",
		INSTALL_STEP7_CREATED_TABLES : "Database tables created",
		INSTALL_STEP8_INTRO : "You have successfully installed the Galaxytool!",
		INSTALL_STEP8_LOAD_DATA : "Downloading OGame data ...",
		INSTALL_STEP8_LOAD_DATA_FINISHED : "Download of OGame data finished",
		INSTALL_STEP8_DELETE_FILE : "You should now delete the installation files install.php and update.php from your webserver.",
		INSTALL_STEP8_LOGON : "Please logon with the <strong>admin</strong> user and the password you defined earlier.",
		UPDATE_START : "Starting update to version &1",
		UPDATE_STEP_DONE : "Done",
		UPDATE_TITLE : "Galaxytool update for version",
		UPDATE_STEP1_WELCOME : "Welcome to the update wizard of the Galaxytool. You will be guided through the update of the Galaxytool.",
		UPDATE_STEP1_BACKUP_FILES : "As a first step, make a backup of your <strong>config</strong> folder! You will have to replace the configuration content in case of errors.",
		UPDATE_STEP1_BACKUP_DB : "Then make a <a href=\"http://www.ehow.com/how_2036600_create-database-php.html\">backup</a> of your database.",
		UPDATE_STEP1_PROCEED : "Once the backups have been done, you can proceed with your update.",
		UPDATE_STEP1 : "Welcome",
		UPDATE_STEP2 : "Galaxytool settings",
		UPDATE_STEP2_OLD_VERSION : "Previous Galaxytool version",
		UPDATE_STEP3 : "Update Galaxytool",
		UPDATE_STEP3_UPDATE_RUNNING : "Update running, please wait...",
		UPDATE_STEP4 : "Finalize Update",
		UPDATE_STEP4_INTRO : "You have successfully updated the Galaxytool!",
		UPDATE_STEP4_UPDATE_DONE : "Update steps performed.",
		UPDATE_FAILED : "Update failed.",
		GALAXYTOOL_DUMMY_TEXT : "dummy"
	})
);