define(
	({
		REPORT_WHEN : "在",
		PLAYER_BANNED : "b",
		PLAYER_VACATION_MODE : "u",
		PLAYER_NOOB : "n",
		PLAYER_INACTIVE : "i",
		PLAYER_LONG_INACTIVE : "I",
		PLAYER_OUTLAW : "o",
		L_USERNAME : "账号",
		L_PASSWORD : "密码",
		L_LOGINFAILURE : "账号或密码错误，或者你的账号没有启用。",
		L_TOKENFAILURE : "登录密钥错误或者你的账号没有启用。",
		L_LOGINTEXT : "请登录。",
		L_LANGUAGE : "可选择的语言(Available languages)：",
		L_TIMEOUT : "等待时间过久！",
		L_REGISTER : "注册",
		L_PWLOST : "找回密码",
		INDEX_TITLE : "OGame Galaxietool - 概览",
		INDEX_INFO : "数据库信息",
		INDEX_ENTRIES : "太阳系数目",
		INDEX_ENTRIES_LASTWEEK : "最近一周更新的太阳系",
		INDEX_ENTRIES_TO_OLD : "一个月前更新的太阳系",
		INDEX_REGISTERED_USERS : "注册的用户数目",
		INDEX_PAGEFORWARD : "如果你的浏览器无法自动进入下一页, 请点击这里！",
		INDEX_NOTICES : "讯息数目",
		INDEX_PLAYERS : "玩家数目",
		INDEX_ALLIES : "联盟数目",
		INDEX_REPORTS : "间谍报告数目",
		INDEX_VERSION : "下载最新的版本！",
		INDEX_LATEST_VERSION : "你使用的已是最新版本！",
		INDEX_SHOUTBOX : "留言簿",
		INDEX_NOENTRY : "没有留言！",
		INDEX_COMMENT : "输入你的留言",
		INDEX_INSERT : "提交",
		INDEX_UMOD : "假期模式中的玩家",
		INDEX_NO_MOONS : "月球的数目",
		INDEX_NO_EMPTY_SYSTEMS : "空白太阳系数",
		INDEX_NO_FULL_SYSTEMS : "全部占满的太阳系数",
		INDEX_NO_TARGETS : "可以被攻击的星球",
		INDEX_USERINFO : "用户数量",
		INDEX_ONLINE : "在线人数",
		INDEX_TODAY : "今天登录的用户",
		INDEX_ALL : "总登录次数",
		GENERAL_LOAD_FORM : "从数据载入",
		GENERAL_SAVE_FORM : "保存到数据",
		GENERAL_SAVE_AS_TEXT : "另存为",
		GENERAL_SAVE : "保存",
		INDEX_USERMANAGEMENT : "活动概览",
		INDEX_NEEDADMIN : "需要解锁的账号",
		INDEX_NEEDEMAIL : "不可用的账号",
		INDEX_TOOLBAR_INFO : "Galaxytool 插件信息",
		INDEX_TOOLBAR_URL : "Galaxytool URL",
		INDEX_TOOLBAR_VERSION_REQUIRED : "Galaxytool插件至少需要版本",
		INDEX_TOOLBAR_INSTALL_GUIDE : "插件安装引导",
		INDEX_TOOLBAR_TOKEN : "登录密钥",
		INDEX_TOOLBAR_NEW_TOKEN : "获取新密钥",
		INDEX_PLAYERS_WITH_N_PLANETS : "至少有 &1 个球的玩家",
		INDEX_GETTING_STARTED : "Galaxytool 入门指南",
		INDEX_GETTING_STARTED1 : "欢迎来到 Galaxytool!",
		INDEX_GETTING_STARTED2 : "Galaxytool能帮助你分析在OGame 宇宙&1上正在发生的事",
		INDEX_GETTING_STARTED3 : "你需要先插入数据，才能分析数据。适用于Firefox的请到这里 &1 下载",
		INDEX_GETTING_STARTED4 : "安装完插件，你可以像平常一样在OGame浏览银河系，当有数据发送到Galaxytool时，你会看到一个小小的状态窗口",
		INDEX_GETTING_STARTED5 : "一旦数据汇入了Galaxytool, 你就可以分析玩家在哪里有殖民地，有几个，间谍报告，以及他的在线纪录",
		INDEX_GETTING_STARTED6 : "她还能帮助你分析你的战斗报告，看最近几天后几周抢劫了多少资源，或者如果你有一个竞争对手，可以看到你自己实力的进步。",
		INDEX_GETTING_WIKIPAGE : "还有更多Galaxytool功能等您体验",
		INDEX_GETTING_WIKIPAGE2 : "去我们的wiki看看吧",
		INDEX_GETTING_BOARD : "反馈及新想法，可以发到论坛：",
		INDEX_GETTING_CHAT1 : "或访问聊天室：",
		INDEX_GETTING_CHAT2 : "我们不是7×24小时提供服务，只是腾出一些闲暇时间在线，所以请不要着急",
		INDEX_CLOSE : "关闭",
		INDEX_LOGIN : "登录",
		GENERAL_REQUIRED_FIELDS : "请填写所有必填项",
		INDEX_MESSAGES : "消息",
		INDEX_EXAMPLE : "例子",
		INDEX_INVALID_DATA : "无效数据",
		GENERAL_COLUMN_HIDE_TITLE : "管理列",
		GENERAL_COLUMN_HIDE_INFO : "请选择你想在列表中看到的列",
		GENERAL_ENTRIES_DELETED : "已删除 &1 个项目",
		GENERAL_APPLY : "应用",
		STARTPAGE_GALAXYTOOL_DESCR : "<em>Galaxytool</em> 是网页游戏的 OGame 的一个浏览器。",
		GENERAL_OVERWRITE : "覆盖重复的项目",
		GENERAL_OVERWRITE_QUESTION : "覆盖？",
		INDEX_OWN_LOGINS : "你的登录",
		GENERAL_OPEN_IN_NEW_WINDOW : "在新窗口中打开",
		INDEX_NO_REG : "不开放注册",
		GENERAL_UNIT_OF_MEASURE_DAYS : "Days",
		PROGRAM_NAME : "OGame Galaxytool",
		SHORTNAME : "Galaxytool",
		BACK_INDEX : "回到首页",
		UNIVERSE : "宇宙",
		MENU_INFO_LINKS : "信息",
		MENU_PAGE : "总览",
		MENU_DB_SEARCH : "查找玩家或联盟",
		MENU_DB_NOTICES : "查找讯息",
		MENU_DB_REPORTS : "查找间谍报告",
		MENU_GALAXYVIEW : "查看星系",
		MENU_STATISTICS : "排名统计",
		MENU_ALLYHISTORY : "历史总览",
		MENU_FLEET_MOVEMENTS : "舰队移动记录",
		MENU_COMBAT_REPORTS : "战斗报告",
		MENU_MESSAGES : "游戏内消息",
		MENU_OPTION_LINKS : "选项",
		MENU_DB_REFRESH : "汇入数据",
		MENU_NOTICES : "公告",
		MENU_DB_STATUS : "数据库状况",
		MENU_USEROPTIONS : "管理用户",
		MENU_USEROPTIONS2 : "个人选项",
		MENU_USEROPTIONS3 : "账号信息",
		MENU_ADMIN : "管理维护",
		MENU_LOGOUT : "登出",
		MENU_STUFF : "杂项",
		MENU_FORUM_THREAD : "GalaxyTool开发论坛",
		MENU_DOWNLOADPAGE : "下载点",
		MENU_LANGUAGE : "语言",
		MENU_HELP : "求助",
		MENU_TOOLOPTIONS : "Galaxytool 个人选项",
		PARSER_INFO1 : " 被汇入数据库",
		PARSER_ERROR1 : "插入以下坐标时发生错误:",
		PARSER_ERROR2 : "无法找到数据库！",
		PARSER_ERROR3 : "无法找到数据库服务器！",
		PARSER_WRONG_UNIVERSE : "宇宙不匹配 - 当前: \"&1\"  预期: \"&2\"",
		SHOW_TITLE : "OGame Galaxytool - 搜索页",
		SHOW_SEARCH : "查找玩家或联盟",
		SHOW_ALLYSYMBOL : "联盟",
		SHOW_PLAYERNAME : "玩家",
		SHOW_MOONS : "有月球的星球",
		SHOW_NOTICES : "有讯息的星球",
		SHOW_COLONIES : "依星球位置",
		SHOW_YES : "是",
		SHOW_NO : "否",
		SHOW_SEARCHRANGE : "范围",
		SHOW_SEARCH_IN : "查找银河系(1~9)",
		SHOW_FROM_SYSTEM : "从太阳系(1~499)",
		SHOW_FROM_PLANET : "从星球(1~15)",
		SHOW_TO : "到",
		SHOW_DESCRIPTION : "你可以在联盟或玩家栏使用通配符&quot;*&quot;. 这样你可以找到所有名字相似的玩家！<br />可以只填入你感兴趣的查询条件.",
		SHOW_SORT_BY : "排列标准",
		SHOW_GALASYSTEM : "银河系/太阳系",
		SHOW_ALLYNAME : "联盟名",
		SHOW_SEARCHBUTTON : "开始查找",
		SHOW_ADDRESS : "位置",
		SHOW_ALLYSORT : "联盟",
		SHOW_PLANET : "星球名",
		SHOW_STATUS : "状态",
		SHOW_CURRENTNESS : "更新时间",
		SHOW_PLAYER_STATUS : "玩家状态",
		SHOW_PLAYER_STATUS1 : "全部",
		SHOW_PLAYER_STATUS2 : "可被攻击的",
		SHOW_PLAYER_STATUS3 : "Ｉ羊",
		SHOW_HITS : "共",
		SHOW_OF : "于",
		SHOW_ASC : "升序排列",
		SHOW_DESC : "降序排列",
		SHOW_RESULTS : "一页显示几笔数据",
		SHOW_MOON : "月球",
		SHOW_UKMOONSIZE : "大小未知",
		SHOW_DF : "残骸",
		SHOW_DF_LONG : "残骸",
		SHOW_METAL : "金属",
		SHOW_METAL_LONG : "金属",
		SHOW_CRYSTAL : "晶",
		SHOW_CRYSTAL_LONG : "晶体",
		SHOW_BOTH : "两者一起",
		SHOW_AT_LEAST : "(至少)",
		SHOW_DATE : "日期",
		SHOW_DATE_0 : "不介意",
		SHOW_DATE_1 : "之后",
		SHOW_DATE_2 : "之前",
		SHOW_RANK : "排名",
		SHOW_FRANK : "舰队数排名",
		SHOW_MEMBERS : "盟员",
		SHOW_NOTRANKED : "没有找到数据",
		SHOW_NOTICERES : "公告",
		SHOW_REPORTS : "有间谍报告的星球",
		SHOW_REPORTS_SHORT : "间谍报告",
		SHOW_NOTHING : "没有找到数据",
		SHOW_ALLIANCE_STATUS : "联盟关系",
		SHOW_NO_STATUS : "无关系",
		SHOW_NAP : "互不侵犯",
		SHOW_ALLIED : "结盟",
		SHOW_WAR : "宣战",
		SHOW_BOYCOTT : "抵制",
		SHOW_NEUTRAL : "中立",
		SHOW_OWN : "所在联盟",
		SHOW_WING : "子盟",
		SHOW_EXT_OPTIONS1 : "显示更多的查找选项（范围、排名、日期或残骸）",
		SHOW_EXT_OPTIONS2 : "显示更多的查找选项（位置、月球、间谍报告、讯息、玩家状况或外交状况）",
		SHOW_EXT_OPTIONS3 : "显示更多的查找选项（排列规则）",
		SHOW_EXTENDED : "高级搜索",
		SHOW_MOON_SELECTION : "有月的球",
		SHOW_REPORT_SELECTION : "有报告的球",
		SHOW_FILTER_BY : "从列表里排除",
		SHOW_FILTER_NONE : "无",
		SHOW_PLAYERS_WITHOUT_PROGRESS : "Show players without score changes within the last few days",
		STATUS_TITLE : "OGame Galaxytool - 状态",
		STATUS_DB_STATUS : "数据库状态",
		STATUS_COLOR : "颜色",
		STATUS_AGE1 : "1 天内更新.",
		STATUS_AGE2 : "2 - 4 天内更新.",
		STATUS_AGE3 : "4 - 7 天内更新.",
		STATUS_AGE4 : "1 - 2 星期内更新.",
		STATUS_AGE5 : "2 - 4 星期内更新.",
		STATUS_AGE6 : "1个月前更新的!",
		STATUS_AGE7 : "从未记录过.",
		STATUS_ON : "在线",
		STYLES_COLOR1 : "颜色1",
		STYLES_COLOR2 : "颜色2",
		STYLES_COLOR3 : "颜色3",
		STYLES_COLOR4 : "颜色4",
		STYLES_COLOR5 : "颜色5",
		STYLES_COLOR6 : "颜色6",
		STYLES_COLOR7 : "颜色7",
		STATUS_DB_LEGEND : "图例",
		STATUS_GALAXY : "银河系总览",
		USER_TITLE : "用户管理",
		USER_NAMES : "账号",
		USER_ERROR : "错误",
		USER_NEWUSER : "新用户",
		USER_OPTIONS : "个人设置",
		USER_USERNAME : "账号",
		USER_PASSWORD : "密码",
		USER_PASSWORD_CONFIRM : "密码确认",
		USER_GALAXY : "银河系",
		USER_SEARCH : "查找权",
		USER_INSERT : "数据汇入权",
		USER_DELETE : "删除",
		USER_DELETE_ENTRY : "你确定要删除用户： ",
		USER_STATUS : "查看所有状况权",
		USER_STYLES : "修改布局",
		USER_SUBMIT : "提交",
		USER_RESET : "重新输入",
		USER_YES : "是",
		USER_NO : "否",
		USER_STYLEPATH : "styles.css路径",
		USER_PROBES : "观看/输入间谍报告",
		USER_EMAIL : "E-mail",
		USER_ERROR1 : "密码错误 或 无效的E-mail！",
		USER_ERROR2 : "无效的E-mail！",
		USER_INGAME : "OGame的账号",
		USER_ALLYTAG : "联盟",
		USER_ALLYHISTORY : "历史概览",
		USER_DIPLOMATIC : "更改外交状态",
		USER_STATSPAGE : "状况页数据数目设定",
		USER_LINKS : "链接（将显示在左下方）",
		USER_LINKS2 : "格式:<br>text;url<br>text2;url2<br>text3;url3",
		USER_EXPORT_TITLE : "颜色设定 (BB Codes)",
		USER_BB_COORDINATES : "坐标",
		USER_BB_MOON : "月球",
		USER_BB_DEBRIS : "残骸",
		USER_BB_ALLY : "联盟",
		USER_BB_ALLYDETAILS : "联盟详细资料",
		USER_BB_PLAYERNAME : "玩家名称",
		USER_BB_BANNED : "被封的玩家",
		USER_BB_VACATION : "假期模式",
		USER_BB_NOOB : "实力弱的玩家",
		USER_BB_INACTIVE : "Ｉ羊",
		USER_BB_LONGINACTIVE : "Ｉｉ羊",
		USER_DELETION : "删除",
		USER_FLEETINFO : "舰队移动记录",
		USER_ACTIVITIES : "玩家活跃纪录",
		USER_MAINTENANCE : "Galaxytool 维护",
		USER_MANAGEMENT : "管理用户",
		USER_DELETE_MY_COMBAT_REPORTS : "删除我的战斗报告",
		USER_DELETE_MY_MESSAGES : "删除我的消息",
		USER_DELETE_MY_FLEETMOVES : "删除我移动中的舰队",
		USER_DELETE_MY_COMBAT_REPORTS_LIMITED : "删除我 &1 天前的战斗报告",
		USER_DELETE_MY_MESSAGES_LIMITED : "删除我 &1 天前的消息",
		USER_TABLE_ENTRIES : "每页显示结果数",
		USER_EXISTS : "用户已存在",
		USER_BB_OUTLAW : "违纪",
		USER_INVALID_URL : "URL &1 似乎已经失效 - 此 URL 会被忽略",
		VIEW_TITLE : "OGame Galaxytool - 银河系",
		VIEW_NODATA : "没有数据输入！",
		VIEW_GALAXY : "银河系",
		VIEW_SYSTEM : "太阳系",
		VIEW_POSITION : "位置",
		VIEW_PLANET : "星球",
		VIEW_MOON : "月球",
		VIEW_TF : "残骸",
		VIEW_PLAYER : "玩家",
		VIEW_PLAYER_ADD : "(排名 / 状况)",
		VIEW_ALLY : "联盟",
		VIEW_ALLY_ADD : "(排名 / 人数)",
		VIEW_METAL : "金属",
		VIEW_CRYSTAL : "晶体",
		VIEW_COLONISED : "星球有人居住",
		VIEW_UKMOONSIZE : "未知",
		VIEW_BACK : "返回",
		VIEW_NOTICE : "讯息",
		VIEW_REPORTS : "间谍报告",
		VIEW_MOONPHALANX : "下列的月能扫到这个太阳系",
		VIEW_NOMOONS : "暂未知晓",
		VIEW_IRAKS : "下列星球能用星级导弹打到这个太阳系",
		VIEW_NOIRAKS : "暂未知晓",
		VIEW_MOON_DESTROY_CHANCE : "毁灭月球的机率",
		VIEW_CHANCE_WITH_ONE : "当派一颗死星时",
		VIEW_CHANCE_WITH_N : "派 ",
		VIEW_DEATH_STARS : "死星时",
		VIEW_DS_DESTROY_CHANCE : "死星毁灭的机率",
		VIEW_TOP : "TOP",
		VIEW_GO : "走你！",
		VIEW_DIAMETER : "直径",
		PW_TITLE : "OGame Galaxytool - 个人选项",
		OLD_PASSWORD : "目前密码",
		NEW_PASSWORD : "新密码",
		CONFIRM_NEW_PASSWORD : "确认新密码",
		PW_MISMATCH : "两次输入的密码不同！",
		PW_ERROR : "目前密码不正确！",
		UPDATE_DONE : "修改成功！",
		TIMEZONE_OFFSET : "相对于服务器的时区偏移量",
		DELETE_ACCOUNT : "删除这个Galaxytool账号",
		DELETE_ACCOUNT_SAFETY_REQUEST : "真的要删除这个Galaxytool账号吗?",
		CH_PASSWD_AUTHORIZATION : "已获得权限",
		CH_PASSWD_ADMIN : "管理员",
		TIMEZONE_OGAME_OFFSET : "相对于OGame服务器的时区偏移量",
		CH_PASSWD_USER_LANGUAGE : "登陆后切换到这个语言",
		CH_PASSWD_USER_LANGUAGE_NO_CHANGE : "不改变",
		CH_PASSWD_EXPAND : "展开",
		CH_PASSWD_COLLAPSE : "收起",
		CH_PASSWD_HIDDEN : "隐藏",
		CH_PASSWD_GETTING_STARTED : "登录后显示入门指南",
		CH_PASSWD_PLUGIN : "登录后显示插件信息",
		NOTICE_TITLE : "OGame Galaxytool - 注记",
		NOTICE_HEADER : "编辑注记",
		NOTICE_HEADER2 : "编辑自己的注记",
		NOTICE_PUBLIC : "对别人公开 ?",
		NOTICE_YES : "是",
		NOTICE_NO : "否",
		NOTICE_TEXT : "注记文本",
		NOTICE_SAVE : "储存",
		NOTICE_DELETED : "已删除",
		NOTICE_SAVED : "已储存.",
		NOTICE_RESULTS : "所有结果",
		NOTICE_USER : "用户",
		NOTICE_DATE : "日期",
		NOTICE_EDIT : "编辑",
		NOTICE_DELETE : "删除",
		NOTICE_NEW : "创建我的项目",
		NOTICE_NOTPUBLIC : "注记未公开.",
		NOTICE_ALL : "所有",
		NOTICE_NONE : "无",
		NOTICE_SEARCH : "查找讯息",
		NOTICE_SEARCH_SHORT : "开始查找",
		NOTICE_HITS : "共",
		NOTICE_SHOWRESULTS : "显示的数据笔数",
		NOTICE_OF : "于",
		NOTICE_NOTHING : "没有找到符合的！",
		NOTICE_CHARS : "字符",
		NOTICE_PLAYERNAME : "玩家",
		NOTICE_SHOWALL : "显示所有注记",
		REPORTS_TITLE : "OGame Galaxytool - 间谍报告",
		REPORTS_RESOURCES : "资源",
		REPORTS_FLEET : "舰队",
		REPORTS_DEFENCE : "防御",
		REPORTS_BUILDINGS : "建筑",
		REPORTS_TECHNOLOGY : "科技",
		REPORTS_MOON : "月球",
		REPORTS_SEARCH : "查找间谍报告",
		REPORTS_SEARCH_SHORT : "开始查找",
		REPORTS_HITS : "共",
		REPORTS_NOTHING : "没有找到符合的！",
		REPORTS_ADDRESS : "位置",
		REPORTS_CURRENTNESS : "更新时间",
		REPORTS_PLAYERNAME : "玩家名称",
		REPORTS_ALLY : "联盟",
		REPORTS_VIEW : "间谍报告",
		REPORTS_SEARCH_IN : "查找银河系(1~9)",
		REPORTS_FROM_SYSTEM : "从太阳系",
		REPORTS_TO : "到",
		REPORTS_DELETE : "删除",
		REPORTS_DELETED : "已删除",
		REPORTS_RESULTS : "显示的数据笔数",
		REPORTS_OF : "于",
		REPORTS_DATE : "日期",
		REPORTS_DATE_0 : "不介意",
		REPORTS_DATE_1 : "之前",
		REPORTS_DATE_2 : "之后",
		REPORTS_NOTICES : "讯息",
		REPORTS_AT_LEAST_RESOURCES : "资源(至少)",
		REPORTS_SEARCH_EXTENDED : "查找后展开",
		REPORTS_FLEET_RESIS : "舰队分",
		REPORTS_DEFENCE_RESIS : "防御分",
		REPORTS_ALL_RESIS : "总积分",
		REPORTS_TECHS : "三围",
		REPORTS_UNKNOWN_ENTRIES : "未知项",
		REPORTS_PARTLY_INSERTED : "数据不完整",
		REPORTS_FOR_ALL_RES : "所有资源需",
		REPORTS_FOR_TF : "残骸需",
		REPORTS_KT : "小型运输船",
		REPORTS_GT : "大型运输船",
		REPORTS_SS : "战列舰",
		REPORTS_REC : "回收船",
		REPORTS_RAIDABLE : "只显示能打劫的目标",
		REPORTS_ALL_RESOURCES : "所有资源",
		REPORTS_STUFF : "杂项",
		REPORTS_SPEEDSIM : "在线战斗模拟器 Speedsim",
		REPORTS_DRAGOSIM : "在线战斗模拟器 Dragosim",
		REPORTS_STATUS : "状态",
		REPORTS_ERROR : "发生了错误",
		REPORTS_OWN_REPORTS : "只看我的报告",
		REPORTS_UPLOAD_BY : "上报者",
		REPORTS_DEPTH : "报告精确度",
		REPORTS_FLEET_SCORE : "舰队分数",
		REPORTS_DEFENCE_SCORE : "防御分数",
		REPORTS_HOURS : "小时",
		REPORTS_MAX_RESULTS_HIT : "你的请求匹配多于 &1 个结果s. 只显示前 &1 个结果. 请调整搜索条件以得到更少数据.",
		REPORTS_OSIMULATE : "在线战斗模拟器 OSimulate",
		REPORTS_SHOW_ONLY : "只显示",
		REPORTS_SHOW_PLANETS : "星球",
		REPORTS_SHOW_MOONS : "月球",
		REPORTS_OWNER : "报告拥有者",
		STATS_TITLE : "OGame Galaxytool - 排名统计",
		STATS_TBLHEAD : "排名统计",
		STATS_RANK : "排名",
		STATS_PLAYERNAME : "玩家名称",
		STATS_ALLYNAME : "联盟",
		STATS_SCORE : "分数",
		STATS_FLEET : "舰队数",
		STATS_RESEARCH : "科技等级",
		STATS_MEMBERS : "盟员",
		STATS_STATUS : "状态",
		STATS_NOTHING : "无关系",
		STATS_NAP : "互不侵犯",
		STATS_ALLIED : "结盟",
		STATS_WAR : "宣战",
		STATS_BOYCOTT : "抵制",
		STATS_NEUTRAL : "中立",
		STATS_OWN : "所在联盟",
		STATS_WING : "子盟",
		STATS_UPDATE : "资料由",
		STATS_PLAYERSTATS : "玩家积分",
		STATS_ALLYSTATS : "联盟积分",
		STATS_DELETE : "删除设定",
		STATS_CONFIRM_DELETE : "你确定要删除吗？",
		STATS_CHANGE_PLAYER_STATUS : "玩家的外交",
		STATS_CHANGE_ALLIANCE_STATUS : "联盟的外交",
		STATS_CHANGE_ALLIANCE_STATUS_HINT : "该联盟的所有成员将使用这个关系设定！任何个人的关系设定将会被覆盖！之后你必需去更改其它玩家的关系设定！",
		STATS_UNKNOWN : "其他",
		STATS_DETAILS : "详情",
		STATS_PLAYERSTATUS : "玩家状态",
		STATS_IGNORE_STATUS : "全部",
		STATS_ACTIVE : "活动",
		STATS_INACTIVE : "Ｉ羊",
		STATS_BANNED : "被封的玩家",
		STATS_VACATION : "假期模式",
		STATS_NOOB : "实力弱的玩家",
		STATS_YES : "是",
		STATS_NO : "有讯息的星球",
		STATS_SEARCH : "搜索",
		STATS_SHOW_GRAPH : "Show details for score distribution",
		STATS_LONG_INACTIVE : "Ｉｉ羊",
		STATS_STANDARD : "标准分数",
		STATS_MILITARY : "军事分数",
		STATS_ECONOMY : "经济",
		STATS_HONOUR : "荣誉分数",
		STATS_MILITARY_BUILD : "军事建造",
		STATS_MILITARY_DESTROYED : "军事摧毁",
		STATS_MILITARY_LOST : "军事损失",
		REGISTER_REGISTRATE : "注册",
		REGISTER_LOGINNAME : "账号",
		REGISTER_PASSWORD : "密码",
		REGISTER_PASSWORD_CONFIRM : "确认密码",
		REGISTER_EMAIL : "E-mail",
		REGISTER_INGAME : "OGame的账号",
		REGISTER_ALLYTAG : "联盟",
		REGISTER_EMAILVERIFICATION : "E-mail查询",
		REGISTER_EMAILTEXT : "请点击这个链接来确认你在 GalaxyTool 的注册！",
		REGISTER_ERROR1 : "注册的账号已被使用。",
		REGISTER_ERROR2 : "传送E-mail时发生错误！请连络管理者！",
		REGISTER_ERROR3 : "数据传送到数据库时发生错误！",
		REGISTER_INFO1 : "你的账号已经建立。",
		REGISTER_INFO2 : "请查看你的E-mai并点击链接来确认你的申请。",
		REGISTER_INFO3 : "账号已被确认！但你仍需等GalaxyTool的管理者帮你开通！",
		REGISTER_BUTTON : "回到首页",
		REGISTER_NEW_SUBJECT : "一个新用户注册到GalaxyTool",
		REGISTER_NEW_MAILTEXT : "一个新用户已经自己注册",
		REGISTER_BACK : "返回第一页",
		REGISTER_MISSING_FIELDS : "输入所有必填项",
		REGISTER_ERROR4 : "Email地址无效.",
		REGISTER_ERROR5 : "两次密码不匹配.",
		REGISTER_PWS : "密码强度",
		REGISTER_PWS0 : "非常弱",
		REGISTER_PWS1 : "若",
		REGISTER_PWS2 : "一般",
		REGISTER_PWS3 : "强",
		REGISTER_PWS4 : "非常强",
		REGISTER_EMAIL_USED : "Email地址已被占用",
		LOSTPW_TITLE : "密码遗失",
		LOSTPW_INFO2 : "新的密码已产生，并已寄到你的E-mail！",
		LOSTPW_BUTTON1 : "取得新密码",
		LOSTPW_BUTTON2 : "回首页",
		LOSTPW_LOGINNAME : "账号",
		LOSTPW_EMAIL : "E-mail",
		LOSTPW_ERROR1 : "数据传送到数据库时发生错误！",
		LOSTPW_ERROR2 : "没有找到符答的数据！",
		LOSTPW_ERROR3 : "传送E-mail时发生错误！请连络管理者！",
		LOSTPW_EMAIL_SUBJECT : "你申请的新密码",
		LOSTPW_EMAIL_TEXT1 : "这是 GalaxyTool 新的登录资料",
		LOSTPW_EMAIL_TEXT2 : "账号",
		LOSTPW_EMAIL_TEXT3 : "密码",
		LOSTPW_INFO1 : "你会收到一封重置么吗的确认信.",
		LOSTPW_CONFIRM_RESET_SUBJECT : "找回密码?",
		LOSTPW_CONFIRM_RESET_MESSAGE : "Hello,\n\n你请求重置Galaxytool密码. 点击下列连接重置:",
		USERINFO_TITLE : "OGame Galaxytool - 用户信息",
		USERINFO_NAMES : "GalaxyTool的所有用户",
		USERINFO_DETAIL : "用户详细数据",
		USERINFO_ERROR1 : "用户ID不存在!",
		USERINFO_USERNAME : "账号",
		USERINFO_INGAME : "OGame的账号",
		USERINFO_EMAIL : "E-mail",
		USERINFO_ALLYTAG : "联盟",
		USERINFO_STYLEPATH : "使用的面版",
		USERINFO_STATUS : "状态",
		USERINFO_ACTIVATE : "开通",
		USERINFO_LOGINS : "登录次数",
		USERINFO_LASTLOGIN : "最近一次的登录时间",
		USERINFO_DATA : "汇入的数据",
		USERINFO_NODATA : "该用户没有汇入任何数据！",
		USERINFO_GALAXY : "银河系",
		USERINFO_SYSTEMS : "资料数",
		USERINFO_IP : "IP 位置",
		USERINFO_LOGINTIME : "登录时间",
		USERINFO_NOLOGIN : "这个用户重未登录！",
		USERINFO_LAST_GALAXYUPDATE : "最后汇入数据的时间",
		USERINFO_LAST_PUBLIC_NOTICE : "最后公共消息",
		USERINFO_LAST_PRIVATE_NOTICE : "最后私人消息",
		USERINFO_NUMBEROF_PUBLIC_NOTICE : "公共消息数目",
		USERINFO_NUMBEROF_PRIVATE_NOTICE : "私人消息数目",
		USERINFO_ACTIVATED : "注册的账号已被启用",
		USERINFO_ACTIVATIONTEXT : "Galaxytool的管理者已开通你的账号！\n\n祝你使用Galaxytool愉快 !",
		USERINFO_LAST_SUBMIT : "最后插入数据",
		ALLYHISTORY_TITLE : "OGame Galaxytool - 联盟历史",
		ALLYHISTORY_TBLHEAD : "历史概览",
		ALLYHISTORY_PLAYERNAME : "玩家",
		ALLYHISTORY_ALLYNAME : "联盟",
		ALLYHISTORY_LASTMONTH : "上个月",
		ALLYHISTORY_ALL_DATA : "全部信息",
		ALLYHISTORY_SHOW : "查看排名统计",
		ALLYHISTORY_TIMESPAN : "Timespan",
		ALLYHISTORY_PROGESS : "进度",
		ALLYHISTORY_SCORE : "分数",
		ALLYHISTORY_FSCORE : "舰队数",
		ALLYHISTORY_RSCORE : "科技等级",
		ALLYHISTORY_MEMBER : "盟员",
		ALLYHISTORY_NOTHING : "未找到符合的",
		ALLYHISTORY_DETAILS : "详情",
		ALLYHISTORY_SHOW_ADDRESS : "坐标",
		ALLYHISTORY_ESCORE : "经济",
		ALLYHISTORY_MSCORE : "军事分数",
		DETAILEDINFO_PLAYERINFO_TITLE : "玩家信息",
		DETAILEDINFO_ALLYINFO_TITLE : "联盟信息",
		DETAILEDINFO_PLAYERINFO_TBLHEAD : "玩家详细信息",
		DETAILEDINFO_ALLYINFO_TBLHEAD : "联盟详细信息",
		DETAILEDINFO_NO_ALLIANCE : "无",
		DETAILEDINFO_SCORE : "分数",
		DETAILEDINFO_FLEET : "舰队数",
		DETAILEDINFO_RESEARCH : "科技等级",
		DETAILEDINFO_RANK : "排名",
		DETAILEDINFO_POINTS : "分数",
		DETAILEDINFO_KNOWN_PLANETS : "已知的星球",
		DETAILEDINFO_MOONS : "已知的月球",
		DETAILEDINFO_PHALANX_AREA : "感应范围",
		DETAILEDINFO_NO_PHALANX_AREA : "未知或没有感应范围",
		DETAILEDINFO_NOTICES : "讯息",
		DETAILEDINFO_NO_NOTICES : "没有讯息",
		DETAILEDINFO_PREVIOUS_ALLIANCES : "先前的联盟",
		DETAILEDINFO_RESOURCES_PER_HOUR : "每小时的资源量",
		DETAILEDINFO_RESOURCES_PER_DAY : "每天的资源量",
		DETAILEDINFO_RESOURCES_PER_WEEK : "每周的资源量",
		DETAILEDINFO_RESOURCES_PER_MONTH : "每30天的资源量",
		DETAILEDINFO_METAL : "金属",
		DETAILEDINFO_CRYSTAL : "晶体",
		DETAILEDINFO_DEUTERIUM : "重氢",
		DETAILEDINFO_UNKNOWN : "未知",
		DETAILEDINFO_SCORE_DISTRIBUTION : "分数分布图",
		DETAILEDINFO_GENERAL : "详情",
		DETAILEDINFO_MEMBERS : "成员",
		DETAILEDINFO_GRAPHS : "图表",
		DETAILEDINFO_RESOURCES : "资源",
		DETAILEDINFO_FLEET_TAB : "舰队",
		DETAILEDINFO_TECH : "科技",
		DETAILEDINFO_FLEET_DETAIL : "总数 / 所有报告的平均值",
		DETAILEDINFO_TECH_DETAIL : "所有玩家的平均值",
		DETAILEDINFO_PLANET_TAB : "星球",
		DETAILEDINFO_MOON_TAB : "月球",
		DETAILEDINFO_ACTIVITIES : "活跃情况",
		DETAILEDINFO_NODATA : "没有数据输入！",
		DETAILEDINFO_ACTIVITY_DESCRIPTION : "从以下方面显示 &1 的活跃情况：",
		DETAILEDINFO_GALAXYVIEWS : "银河系视图",
		DETAILEDINFO_SCANS : "间谍活动",
		DETAILEDINFO_MESSAGES : "玩家消息",
		DETAILEDINFO_COMBATS : "战斗报告",
		DETAILEDINFO_ALLYPAGE : "联盟概览",
		DETAILEDINFO_MANUAL : "手工输入",
		DETAILEDINFO_START : "从",
		DETAILEDINFO_TO : "到",
		DETAILEDINFO_TODAY : "今天",
		DETAILEDINFO_DATA_RESTRICTION : "限制在:",
		DETAILEDINFO_WEEKDAY_WEEKEND : "周末",
		DETAILEDINFO_WEEKDAY_WORKINGDAY : "工作日",
		DETAILEDINFO_WEEKDAY_MONDAY : "周一",
		DETAILEDINFO_WEEKDAY_TUESDAY : "周二",
		DETAILEDINFO_WEEKDAY_WEDNESDAY : "周三",
		DETAILEDINFO_WEEKDAY_THURSDAY : "周四",
		DETAILEDINFO_WEEKDAY_FRIDAY : "周五",
		DETAILEDINFO_WEEKDAY_SATURDAY : "周六",
		DETAILEDINFO_WEEKDAY_SUNDAY : "周日",
		DETAILEDINFO_WEEKDAY_SHORTLENGTH : 4,
		DETAILEDINFO_PLAYER_CURRENTLY_ACTIVE : "他现在在线",
		DETAILEDINFO_PLAYER_MESSAGES : "可用玩家消息",
		DETAILEDINFO_SHOW : "显示",
		DETAILEDINFO_NONE : "没有可用信息",
		DETAILEDINFO_ENTER_MANUALLY : "手工输入活跃情况",
		DETAILEDINFO_PLAYER_SEEN_ON : "玩家在线于",
		DETAILEDINFO_INSERT : "插入",
		DETAILEDINFO_OGAME_SERVERTIMES : "请留意: 所有数据和时间都来源于OGame服务器!",
		DETAILEDINFO_DAY_VIEW : "24小时视图",
		DETAILEDINFO_WEEK_VIEW : "周视图",
		DETAILEDINFO_HOME_PLANET : "母星",
		DETAILEDINFO_PLANETNAME : "名称",
		DETAILEDINFO_DEFENCE_SCORE : "防御分数",
		DETAILEDINFO_DEFENCE_SCORE_TOOLTIP : "防御分数 = 舰队 - 分数（？） + 科技 + 经济.<br/>所有统计排名信息数据需要最新的，才能反映真实状况!",
		DETAILEDINFO_SCORE_PER_SHIP : "单船分数",
		DETAILEDINFO_SHIPS : "舰队数量",
		DETAILEDINFO_DATE_IN_FUTURE : "Do not maintain times which are not in the past.",
		ADMIN_TITLE : "Galaxytool系统管理",
		ADMIN_DISCLAMER : "注意:运行下列脚本后果自负! .",
		ADMIN_INCONSISTENCIES : "数据库不一致性",
		ADMIN_PLANETS : "删除非法位置（小于0或大于15）",
		ADMIN_GALAXIES : "删除比 &1 大的银河系",
		ADMIN_PLAYERS : "删除没有关联OGame游戏账号的用户 - 这会清除重复用户",
		ADMIN_REPORTS : "删除不再存在的星球的报告",
		ADMIN_MISC : "杂项",
		ADMIN_RESET : "重置Galaxytool (只保留用户表和ip表)",
		ADMIN_OLD_PLAYERS : "删除 &1 天前的玩家数据",
		ADMIN_OLD_REPORTS : "删除 &1 天前的间谍报告",
		ADMIN_LOADING : "正在载入，请不要关闭此窗口.",
		ADMIN_STATUS : "你请求的状态",
		ADMIN_SELECTION : "必须选择一项",
		ADMIN_SAFETY : "你确定要运行脚本吗 ?",
		ADMIN_DONE : "完成",
		ADMIN_NOTBD : "无事可做",
		ADMIN_OLD_GALAXIES : "删除 &1 天前的星图",
		ADMIN_UNUSED_PLAYERS : "删除不在星图中的玩家（在游戏中已删号）",
		ADMIN_OLD_ACTIVITIES : "删除 &1 天前的玩家活跃状况",
		ADMIN_OLD_COMBATS : "删除 &1 天前的战斗报告",
		ADMIN_OLD_INGAME_MSG : "删除 &1 天前的游戏内信息",
		ADMIN_OGAME_API : "从OGame载入公开数据到Galaxytool",
		ADMIN_OGAME_ALL_DATA : "全部信息",
		ADMIN_OGAME_GALAXY_DATA : "更新银河系数据",
		ADMIN_OGAME_STATISTICS_DATA : "更新排名统计数据",
		ERRORPAGE_PAGEFORWARD : "如果你的浏览器没有自动跳转功能，请点击这里",
		ERRORPAGE_PERMISSION_DENIED : "你没有权限访问这个功能.点击后退.",
		FLEETS_TITLE : "OGame Galaxytool - 舰队移动",
		FLEETS_ACTUAL_FLEETS : "当前舰队移动",
		FLEETS_YES : "是",
		FLEETS_NO : "有讯息的星球",
		FLEETS_DETAILS : "详情",
		FLEETS_MISSION_EXPEDITION : "远征探索",
		FLEETS_MISSION_COLONIZATION : "殖民",
		FLEETS_MISSION_RECYCLE : "回收",
		FLEETS_MISSION_TRANSPORT : "运输",
		FLEETS_MISSION_DEPLOYMENT : "部署",
		FLEETS_MISSION_ESPIONAGE : "间谍",
		FLEETS_MISSION_ACS_DEFEND : "ACS防御",
		FLEETS_MISSION_ATTACK : "攻击",
		FLEETS_MISSION_ACS_ATTACK : "ACS攻击",
		FLEETS_MISSION_MOON_DESTRUCTION : "摧毁月球",
		FLEETS_MISSION_MISSILE_ATTACK : "星际导弹攻击",
		FLEETS_NO_DATA : "无可用数据",
		FLEETS_FLEET : "舰队",
		FLEETS_ALL_FLEETS : "显示所有舰队移动",
		COMBAT_REPORT_OUDATED_GALAXYVIEW : "你的星系资料凹凸了.请先访问战斗发起和目标坐标!",
		MESSAGES_TITLE : "OGame Galaxytool - OGame消息",
		MESSAGES_PLAYERNAME : "玩家姓名",
		MESSAGES_SUBJECT : "主题",
		MESSAGES_DATE : "数据",
		MESSAGES_FILTER : "过滤器",
		MESSAGES_DELETE : "删除消息",
		MESSAGES_PUBLISH_DETAIL : "Publish message by adding the message content to notice text of that player.",
		MESSAGES_PUBLISH_HEADER : "&sender 于 &date 发送了一条消息给 &recipient ：\n\n &message",
		MESSAGES_PLAYER_FILTER : "来自玩家:",
		MESSAGES_CONTENT : "内容",
		COMBATS_TITLE : "OGame Galaxytool - 战斗报告",
		COMBATS_ATTACKER : "攻击方",
		COMBATS_DEFENDER : "防御方",
		COMBATS_DATE : "日期",
		COMBATS_OWNER : "所有者",
		COMBATS_WINNER : "获胜者",
		COMBATS_COMBATREPORT : "战斗报告",
		COMBATS_COMBAT_AT : "战斗地点",
		COMBATS_LOST_UNITS : "损失单位数",
		COMBATS_LOOT : "掠夺",
		COMBATS_DEBRIS : "废墟",
		COMBATS_AND : "和",
		COMBATS_PUBLISH : "公开这个报告",
		COMBATS_UNPUBLISH : "不共享这个报告(再次变为私有)",
		COMBATS_DELETE : "删除报告",
		COMBATS_CHECK_ALL : "全选",
		COMBATS_UNCHECK_ALL : "全不选",
		COMBATS_WITH_SELECTED : "With selected",
		COMBATS_PUBLIC_REPORTS : "公开的报告",
		COMBATS_YES : "是",
		COMBATS_NO : "有讯息的星球",
		COMBATS_SEARCH_OPTIONS : "搜索选项",
		COMBATS_SEARCH : "走你！",
		COMBATS_RESET : "清空",
		COMBATS_COORDINATES : "坐标",
		COMBATS_INVALID_GALAXY_ENTERED : "银河系输入不正确",
		COMBATS_INVALID_SYSTEM_ENTERED : "太阳系输入不正确",
		COMBATS_INVALID_PLANET_ENTERED : "星球输入不正确",
		COMBATS_GALAXY_FROM_TO : "银河系",
		COMBATS_SYSTEM_FROM_TO : "太阳系",
		COMBATS_PLANET_FROM_TO : "星球",
		COMBATS_APPLY : "应用",
		COMBATS_COMBAT_SUMMARY : "战斗报告摘要",
		COMBATS_DOWNLOAD_CSV : "下载为CSV文件",
		REPORT_ARCHIVE_TITLE : "报告存档",
		REPORT_ARCHIVE_COORDINATES : "坐标",
		REPORT_ARCHIVE_SCANTIME : "扫描时间",
		REPORT_ARCHIVE_DELETE : "删除这些项",
		REPORT_ARCHIVE_CONFIRM_DELETE : "确定要删除这些项?",
		REPORT_ARCHIVE_GALAXY : "银河系",
		REPORT_ARCHIVE_SYSTEM : "太阳系",
		REPORT_ARCHIVE_PLANET : "星球",
		REPORT_ARCHIVE_MOON : "月球",
		REPORT_ARCHIVE_DETAILS : "详情",
		REPORT_ARCHIVE_RESOURCES : "每小时的资源量",
		REPORT_ARCHIVE_HEADER_RESOURCES : "资源",
		REPORT_ARCHIVE_DETAILS_FOR : " &1 [&2] (&3)的报告存档",
		REPORT_ARCHIVE_FLEET_CARGO : "运输船容量",
		REPORT_ARCHIVE_IRAK_RANGE : "星际导弹射程",
		REPORT_ARCHIVE_CHART_TYPE : "图表类型",
		INSTALL_TITLE : "Galaxytool 安装程序  版本",
		INSTALL_PROGRESS : "总体进度",
		INSTALL_STEP : "步骤",
		INSTALL_CONTINUE : "继续",
		INSTALL_VALIDATE : "验证",
		INSTALL_STEP1 : "欢迎",
		INSTALL_STEP2 : "写权限检测",
		INSTALL_STEP3 : "数据库设置",
		INSTALL_STEP4 : "OGame设置",
		INSTALL_STEP5 : "Galaxytool设置",
		INSTALL_STEP6 : "管理员密码",
		INSTALL_STEP7 : "安装Galaxytool",
		INSTALL_STEP8 : "正在结束安装",
		INSTALL_FILE_DELETE_CHECK : "请在网页服务器上删除install.php和update.php.",
		INSTALL_STEP1_PHP_FAILED : "您的PHP版本 &1  不适合安装 Galaxytool 的这个版本",
		INSTALL_STEP1_FOPEN_FAILED : "您的PHP不允许使用 FOPEN() 命令. 这将不能访问 OGame API.",
		INSTALL_STEP1_WELCOME : "欢迎来到 Galaxytool 安装向导.请跟随指引完成安装",
		INSTALL_STEP2_DESCRIPTION : "请确认config目录下的文件config.php和attributes.php可以写入.",
		INSTALL_STEP2_DESCRIPTION2 : "如果你不知道怎样完成，请看这里: &1",
		INSTALL_STEP2_FILE_NOT_WRITEABLE : "文件不可写入",
		INSTALL_STEP3_SERVER : "数据库服务器",
		INSTALL_STEP3_USERNAME : "账号",
		INSTALL_STEP3_PASSWORD : "密码",
		INSTALL_STEP3_DBNAME : "数据库名称",
		INSTALL_STEP3_PREFIX : "表明前缀",
		INSTALL_STEP3_ENTER_PREFIX : "比如 mytool_",
		INSTALL_STEP3_ENTER_SERVER : "输入服务器地址. 如果需要可以联系你的系统管理员. 通常正确的地址是 localhost.",
		INSTALL_STEP3_ENTER_USERNAME : "输入访问数据库需要用到的用户名",
		INSTALL_STEP3_ENTER_PASSWORD : "输入访问数据库需要用到的密码",
		INSTALL_STEP3_ENTER_DBNAME : "输入将要安装到的数据库名 (必须已经存在。如果不存在，你可以去新建一个)",
		INSTALL_STEP3_CONNECT_FAILED : "连接到数据库服务器失败",
		INSTALL_STEP3_DB_FAILED : "没有找到数据库 &1 ",
		INSTALL_STEP3_MYSQL_VERSION_FAILED : "MySQL 版本 &1 不适合用于安装Galaxytool",
		INSTALL_STEP4_URL : "OGame URL",
		OGAME_URL_DETAILS : "你可以输入任何一个在你登录进游戏后看到的地址. 基于这个URL，可以得到OGame API的地址，这可以用于直接导入数据而不用 Galaxytoolbar. 这个 API 最低适用于OGame 4.1.",
		INSTALL_STEP4_UNIVERSE : "OGame 宇宙",
		INSTALL_STEP4_DEF_TO_DEBRIS : "防御产生废墟",
		INSTALL_STEP4_DEBRIS_RATE : "废墟比例",
		INSTALL_STEP4_SPEED_RATE : "宇宙速率",
		INSTALL_STEP4_ENTER_UNIVERSE : "请输入宇宙名称或(如果是数字命名的)宇宙编号.",
		INSTALL_STEP4_UNIVERSE_MISSING : "你必须定义宇宙名称",
		INSTALL_STEP4_ENTER_URL : "输入你的OGame宇宙地址",
		INSTALL_STEP4_URL_MISSING : "你必须定义OGame宇宙地址",
		INSTALL_STEP4_URL_CHECK_FAILED : "不能在 &1 找到 OGame API",
		INSTALL_STEP4_GETSETTINGS : "Fetch settings",
		INSTALL_STEP5_TOOLNAME : "Galaxytool 名称",
		INSTALL_STEP5_ENTER_TOOLNAME : "这个名字会显示在登录页面，一次可以分辨出你的 Galaxytool",
		INSTALL_STEP5_LANGUAGE : "默认语言",
		INSTALL_STEP5_EMAIL_TO : "Email 收件人",
		INSTALL_STEP5_ENTER_EMAIL_TO : "这个Email用来接收提醒和注册请求",
		INSTALL_STEP5_EMAIL_FROM : "Email 发件人",
		INSTALL_STEP5_ENTER_EMAIL_FROM : "这个Email被当做 Galaxytool 的默认发件人",
		INSTALL_STEP5_USE_PHPMAILER : "使用 PHPMailer",
		INSTALL_STEP5_MAXSHOUTS : "最大信箱容量",
		INSTALL_STEP5_ENTER_USE_PHPMAILER : "如果你的服务器默认不支持发送邮件，请使用PHPMailer",
		INSTALL_PHPMAILER_HOST : "SMPT 服务器",
		INSTALL_PHPMAILER_HOST_EXAMPLE : "比如 smtp.provider.com",
		INSTALL_PHPMAILER_USER : "SMPT 用户名",
		INSTALL_PHPMAILER_USER_EXAMPLE : "比如 user@provider.dcom",
		INSTALL_PHPMAILER_PASS : "SMPT 密码",
		INSTALL_PHPMAILER_SECURE : "身份验证方法 (比如 ssl)",
		INSTALL_PHPMAILER_PORT : "SMTP 端口",
		INSTALL_STEP6_INTRO : "请设置 <strong>admin</strong> 账号密码。这是你安装后第一次登陆用到的密码.",
		INSTALL_STEP7_CONFIG : "配置文件创建成功",
		INSTALL_STEP7_CONFIG_FAILED : "配置文件创建失败",
		INSTALL_STEP7_ATTRIBUTES : "属性文件创建成功",
		INSTALL_STEP7_ATTRIBUTES_FAILED : "属性文件创建失败",
		INSTALL_STEP7_CREATED_TABLES : "数据表创建成功",
		INSTALL_STEP8_INTRO : "你已经成功安装了 Galaxytool!",
		INSTALL_STEP8_LOAD_DATA : "正在下载OGame数据...（如果长时间没有反应，请进入系统管理再次导入数据）",
		INSTALL_STEP8_LOAD_DATA_FINISHED : "下载OGame数据完成",
		INSTALL_STEP8_DELETE_FILE : "你现在请从网页服务器删除文件 install.php和update.php.",
		INSTALL_STEP8_LOGON : "你可以使用 <strong>admin</strong> 和你刚才设置的密码登陆.",
		UPDATE_START : "开始升级到版本 &1",
		UPDATE_STEP_DONE : "完成",
		UPDATE_TITLE : "Galaxytool 升级到版本",
		UPDATE_STEP1_WELCOME : "欢迎来到 Galaxytool 升级向导. 请跟随指引完成升级.",
		UPDATE_STEP1_BACKUP_FILES : "首先，请备份<strong>config</strong>目录。一旦发生错误，可以以此恢复.",
		UPDATE_STEP1_BACKUP_DB : "然后备份数据库。 <a href=\"http://www.ehow.com/how_2036600_create-database-php.html\">向导（英文）</a>.",
		UPDATE_STEP1_PROCEED : "数据库备份完成后，你就可以开始升级流程.",
		UPDATE_STEP1 : "欢迎",
		UPDATE_STEP2 : "Galaxytool设置",
		UPDATE_STEP2_OLD_VERSION : "现存Galaxytool版本",
		UPDATE_STEP3 : "升级 Galaxytool",
		UPDATE_STEP3_UPDATE_RUNNING : "正在升级，请稍等...",
		UPDATE_STEP4 : "正在完成升级",
		UPDATE_STEP4_INTRO : "你成功升级了Galaxytool!",
		UPDATE_STEP4_UPDATE_DONE : "升级已完成.",
		UPDATE_FAILED : "升级失败.",
		GALAXYTOOL_DUMMY_TEXT : "dummy"
	})
);