define(
	({
		REPORT_WHEN : "Отчет на",
		RESOURCES_ON : "Сырьё на",
		PLAYER_BANNED : "з",
		PLAYER_VACATION_MODE : "РО",
		PLAYER_NOOB : "н",
		PLAYER_INACTIVE : "i",
		PLAYER_LONG_INACTIVE : "I",
		PLAYER_OUTLAW : "o",
		L_USERNAME : "Логин",
		L_PASSWORD : "Пароль",
		L_LOGINFAILURE : "Твой логин или пароль введён неправильно или аккаунт ещё не активирован.",
		L_TOKENFAILURE : "Ваш ключ авторизации неверен или аккаунт не активирован",
		L_LOGINTEXT : "Введи пользовательские данные.",
		L_LANGUAGE : "Доступные языки:",
		L_TIMEOUT : "Время сессии истекло",
		L_REGISTER : "Регистрация",
		L_PWLOST : "Забыл пароль",
		INDEX_TITLE : "Обзор",
		INDEX_INFO : "Информация",
		INDEX_ENTRIES : "Всего систем",
		INDEX_ENTRIES_LASTWEEK : "Системы, добавленные в течение последней недели",
		INDEX_ENTRIES_TO_OLD : "Системы старше месяца",
		INDEX_REGISTERED_USERS : "Зарегистрированные пользователи",
		INDEX_PAGEFORWARD : "Нажмите здесь, если ваш браузер не поддерживает редирект.",
		INDEX_NOTICES : "Заметки",
		INDEX_PLAYERS : "Статистика игроков",
		INDEX_ALLIES : "Статистика альянсов",
		INDEX_REPORTS : "Шпионские доклады",
		INDEX_VERSION : "Скачать новую версию",
		INDEX_LATEST_VERSION : "У вас самая новая версия",
		INDEX_SHOUTBOX : "Последние сообщения",
		INDEX_NOENTRY : "Пока нет сообщений",
		INDEX_COMMENT : "Твоё сообщение",
		INDEX_INSERT : "Добавить",
		INDEX_UMOD : "Игроков в РО",
		INDEX_NO_MOONS : "Кол-во лун",
		INDEX_NO_EMPTY_SYSTEMS : "Кол-во пустых систем",
		INDEX_NO_FULL_SYSTEMS : "Кол-во полностью заполненных систем",
		INDEX_NO_TARGETS : "Кол-во планет, на которые можно напасть",
		INDEX_USERINFO : "Информация о пользователях",
		INDEX_ONLINE : "Сейчас онлайн",
		INDEX_TODAY : "Сегодня онлайн",
		INDEX_ALL : "Всего посещений",
		GENERAL_LOAD_FORM : "Форма загрузки данных",
		GENERAL_SAVE_FORM : "Форма сохранения данных",
		GENERAL_SAVE_AS_TEXT : "Сохранить как",
		GENERAL_SAVE : "Сохранить",
		INDEX_USERMANAGEMENT : "Обзор активации",
		INDEX_NEEDADMIN : "Аккаунты для разблокировки",
		INDEX_NEEDEMAIL : "Неактивированные аккаунты",
		INDEX_TOOLBAR_INFO : "Информация о плагине Galaxytool",
		INDEX_TOOLBAR_URL : "Ссылка на Galaxytool",
		INDEX_TOOLBAR_VERSION_REQUIRED : "Требуется хотя бы версия Galaxytool ",
		INDEX_TOOLBAR_INSTALL_GUIDE : "Инструкции установки для плагина",
		INDEX_TOOLBAR_TOKEN : "Ключ авторизации",
		INDEX_TOOLBAR_NEW_TOKEN : "Авторизуйтесь заново",
		INDEX_PLAYERS_WITH_N_PLANETS : "Игроки имеющие более чем &1 планет",
		INDEX_GETTING_STARTED : "Первые шаги с Galaxytool",
		INDEX_GETTING_STARTED1 : "Добро пожаловать в Galaxytool!",
		INDEX_GETTING_STARTED2 : "Galaxytool поможет Вам узнать, что происходит в Вашей ОГейм вселенной &1",
		INDEX_GETTING_STARTED3 : "Перед тем как Вы сможете анализировать информацию, Вам сначала нужно добавить её. Для этого Вам нужен плагин браузера &1 для Firefox.",
		INDEX_GETTING_STARTED4 : "После установки плагина, Вы проходите по страничкам ОГейма как обычно и сможете заметить небольшое окошко, которое появляется каждый раз когда какая-то информация отсылается в Ваш Galaxytool.",
		INDEX_GETTING_STARTED5 : "Когда плагин отошлет информацию в Galaxytool, Вы сможете начать анализировать, где у игроков есть колонии, сколько колоний, какие есть шпионские доклады и в какое время суток игроки активны.",
		INDEX_GETTING_STARTED6 : "Вы также сможете посмотреть, как быстро прогрессируете, сравнив свой рост с ростом оппонентов или проанализировав бои за последние дни и недели.",
		INDEX_GETTING_WIKIPAGE : "У Galaxytool много возможностей.",
		INDEX_GETTING_WIKIPAGE2 : "Изучите их на нашей wiki странице.",
		INDEX_GETTING_BOARD : "Для предложений и замечаний используйте наш форум:",
		INDEX_GETTING_CHAT1 : "Или посетите наш чат:",
		INDEX_GETTING_CHAT2 : "Мы не онлайн 24/7, имейте терпение.",
		INDEX_CLOSE : "Закрыть",
		INDEX_LOGIN : "Войти",
		GENERAL_REQUIRED_FIELDS : "Заполните все требуемые поля",
		INDEX_MESSAGES : "Сообщения",
		INDEX_EXAMPLE : "Пример",
		INDEX_INVALID_DATA : "Неверная информация",
		GENERAL_COLUMN_HIDE_TITLE : "Редактирование столбцов",
		GENERAL_COLUMN_HIDE_INFO : "Выберите, какие столбцы вы хотите поместить в таблицу",
		GENERAL_ENTRIES_DELETED : "&1 записей выбрано",
		GENERAL_APPLY : "Применить",
		STARTPAGE_GALAXYTOOL_DESCR : "<em>Galaxytool</em> - это утилита для игры OGame.",
		GENERAL_OVERWRITE : "Заменить повторяющуюся запись",
		GENERAL_OVERWRITE_QUESTION : "Заменить?",
		INDEX_OWN_LOGINS : "Ваши логины",
		GENERAL_OPEN_IN_NEW_WINDOW : "Открыть в новом окне",
		GENERAL_UNIT_OF_MEASURE_DAYS : "Days",
		PROGRAM_NAME : "OGame Galaxytool",
		SHORTNAME : "Galaxytool",
		BACK_INDEX : "Обратно на стартовую",
		UNIVERSE : "Вселенная",
		MENU_INFO_LINKS : "Информация",
		MENU_PAGE : "Обзор",
		MENU_DB_SEARCH : "Искать в базе данных",
		MENU_DB_NOTICES : "Искать в заметках",
		MENU_DB_REPORTS : "Искать в шпионских докладах",
		MENU_GALAXYVIEW : "Обзор галактики",
		MENU_STATISTICS : "Статистика",
		MENU_ALLYHISTORY : "Статистика по времени",
		MENU_FLEET_MOVEMENTS : "Передвижения флотов",
		MENU_COMBAT_REPORTS : "Боевые доклады",
		MENU_MESSAGES : "Игровые сообщения",
		MENU_OPTION_LINKS : "Установки",
		MENU_DB_REFRESH : "Обновить базу данных",
		MENU_NOTICES : "заметки",
		MENU_DB_STATUS : "Статус базы данных",
		MENU_USEROPTIONS : "Управление пользователями",
		MENU_USEROPTIONS2 : "Настройки аккаунта",
		MENU_USEROPTIONS3 : "Информация об аккаунтах",
		MENU_ADMIN : "Администрирование",
		MENU_LOGOUT : "Выход",
		MENU_STUFF : "Прочее",
		MENU_FORUM_THREAD : "Форум разработчиков",
		MENU_DOWNLOADPAGE : "Скачать",
		MENU_LANGUAGE : "Выбор языка",
		MENU_HELP : "Справка",
		MENU_TOOLOPTIONS : "Установки Galaxytool",
		PARSER_INFO1 : "Добавлено в базу данных",
		PARSER_ERROR1 : "Ошибка при попытке добавить координаты:",
		PARSER_ERROR2 : "Не удалось выбрать базу данных!",
		PARSER_ERROR3 : "Не удалось найти базу данных!",
		PARSER_WRONG_UNIVERSE : "Неверная вселенная - отправлено: \"&1\", ожидалось: \"&2\"",
		SHOW_TITLE : "OGame Galaxytool - Страница просмотра данных",
		SHOW_SEARCH : "Искать в базе данных",
		SHOW_ALLYSYMBOL : "Аббревиатура альянса",
		SHOW_PLAYERNAME : "Имя игрока",
		SHOW_MOONS : "Искать только луны",
		SHOW_NOTICES : "Искать только планеты с заметками",
		SHOW_COLONIES : "Только планеты под колонизацию",
		SHOW_YES : "Да",
		SHOW_NO : "Нет",
		SHOW_SEARCHRANGE : "Радиус поиска",
		SHOW_SEARCH_IN : "Искать в галактике",
		SHOW_FROM_SYSTEM : "от системы",
		SHOW_FROM_PLANET : "от номера планеты",
		SHOW_TO : "до",
		SHOW_DESCRIPTION : "При поиске игроков или альянсов допустимо использование символа *, например *nick* найдёт всех игроков, у которых в имени есть &quot;nick&quot;.<br />Не обязательно заполнять все поля, можно искать не только координаты планет альянса, но также и все луны того или иного альянса.",
		SHOW_SORT_BY : "Сортировать по",
		SHOW_GALASYSTEM : "Галактике/системе",
		SHOW_ALLYNAME : "Названию альянса",
		SHOW_SEARCHBUTTON : "Поиск",
		SHOW_ADDRESS : "Адрес",
		SHOW_ALLYSORT : "Альянс",
		SHOW_PLANET : "Название планеты",
		SHOW_STATUS : "Статус",
		SHOW_CURRENTNESS : "Актуальность",
		SHOW_PLAYER_STATUS : "Статус игрока",
		SHOW_PLAYER_STATUS1 : "все",
		SHOW_PLAYER_STATUS2 : "Можно нападать",
		SHOW_PLAYER_STATUS3 : "Неактивный",
		SHOW_HITS : "Результаты",
		SHOW_OF : "от",
		SHOW_ASC : "по возрастанию",
		SHOW_DESC : "по убыванию",
		SHOW_RESULTS : "Результаты",
		SHOW_MOON : "Луна",
		SHOW_UKMOONSIZE : "неизвестно",
		SHOW_DF : "обломки",
		SHOW_DF_LONG : "Поле обломков",
		SHOW_METAL : "М",
		SHOW_METAL_LONG : "Металл",
		SHOW_CRYSTAL : "К",
		SHOW_CRYSTAL_LONG : "Кристалл",
		SHOW_BOTH : "всего",
		SHOW_AT_LEAST : "(мин.)",
		SHOW_DATE : "Дата",
		SHOW_DATE_0 : "все",
		SHOW_DATE_1 : "старше",
		SHOW_DATE_2 : "новее",
		SHOW_RANK : "Место",
		SHOW_FRANK : "Место по флотам",
		SHOW_MEMBERS : "Члены",
		SHOW_NOTRANKED : "Не в топ-1500.",
		SHOW_NOTICERES : "Заметки",
		SHOW_REPORTS : "Показать только планеты с шп. докладами",
		SHOW_REPORTS_SHORT : "Шпионаж",
		SHOW_NOTHING : "Ничего не удалось найти",
		SHOW_ALLIANCE_STATUS : "Статус альянса",
		SHOW_NO_STATUS : "нет статуса",
		SHOW_NAP : "Пакт",
		SHOW_ALLIED : "Союзник",
		SHOW_WAR : "Война",
		SHOW_BOYCOTT : "Бойкот",
		SHOW_NEUTRAL : "Нейтрально",
		SHOW_OWN : "Свой альянс",
		SHOW_WING : "Крыло",
		SHOW_EXT_OPTIONS1 : "Показать доп. опции для радиуса поиска, поиска по месту, дате и поиску обломков.",
		SHOW_EXT_OPTIONS2 : "Показать доп. опции для поиска места для колонии, лун, докладов, заметок, статуса игрока или дипломатии.",
		SHOW_EXT_OPTIONS3 : "Показать доп. опции для сортировки результатов поиска.",
		SHOW_EXTENDED : "расширенный поиск",
		SHOW_MOON_SELECTION : "Планета с луной",
		SHOW_REPORT_SELECTION : "Планета с отчетом",
		SHOW_FILTER_BY : "Исключить из списка",
		SHOW_FILTER_NONE : "ничего",
		SHOW_PLAYERS_WITHOUT_PROGRESS : "Show players without score changes within the last few days",
		STATUS_TITLE : "OGame Galaxytool - Страница статуса",
		STATUS_DB_STATUS : "Статус базы данных",
		STATUS_COLOR : "Цвет",
		STATUS_AGE1 : "Возраст данных 1 день.",
		STATUS_AGE2 : "Актуальность 2 - 4 дня.",
		STATUS_AGE3 : "Актуальность 4 - 7 дней.",
		STATUS_AGE4 : "Актуальность 1 - 2 недели.",
		STATUS_AGE5 : "Актуальность 2 - 4 недели.",
		STATUS_AGE6 : "Данные старше месяца!",
		STATUS_AGE7 : "Ещё нет данных.",
		STATUS_ON : "",
		STYLES_COLOR1 : "Цвет1",
		STYLES_COLOR2 : "Цвет2",
		STYLES_COLOR3 : "Цвет3",
		STYLES_COLOR4 : "Цвет4",
		STYLES_COLOR5 : "Цвет5",
		STYLES_COLOR6 : "Цвет6",
		STYLES_COLOR7 : "Цвет7",
		STATUS_DB_LEGEND : "Легенда",
		STATUS_GALAXY : "Обзор галактики",
		USER_TITLE : "OGame Galaxytool - Управление пользователями",
		USER_NAMES : "Пользователь",
		USER_ERROR : "Ошибка",
		USER_NEWUSER : "Добавить пользователя",
		USER_OPTIONS : "Установки",
		USER_USERNAME : "Имя пользователя",
		USER_PASSWORD : "Пароль",
		USER_PASSWORD_CONFIRM : "Повторить пароль",
		USER_GALAXY : "Галактика",
		USER_SEARCH : "Искать",
		USER_INSERT : "Добавить",
		USER_DELETE : "Удалить",
		USER_DELETE_ENTRY : "Вы действительно хотите удалить этого игрока?: ",
		USER_STATUS : "Статус",
		USER_STYLES : "Настроить стиль",
		USER_SUBMIT : "Отправить",
		USER_RESET : "Отменить",
		USER_YES : "Да",
		USER_NO : "Нет",
		USER_STYLEPATH : "Путь к файлу styles.css",
		USER_PROBES : "Шпионские доклады",
		USER_EMAIL : "E-mail",
		USER_ERROR1 : "Пароль неверный или адрес E-mail недействителен.",
		USER_ERROR2 : "Адрес E-mail недействителен.",
		USER_INGAME : "Имя в игре",
		USER_ALLYTAG : "Аббревиатура альянса",
		USER_ALLYHISTORY : "История альянса",
		USER_DIPLOMATIC : "Дипломат",
		USER_STATSPAGE : "Кол-во записей на странице статистики",
		USER_LINKS : "Ссылки",
		USER_LINKS2 : "Формат:<br>текст;url<br>текст2;url2<br>текст3;url3",
		USER_EXPORT_TITLE : "Экспортируемые цвета (BB Codes)",
		USER_BB_COORDINATES : "Координаты",
		USER_BB_MOON : "Луна",
		USER_BB_DEBRIS : "Поле обломков",
		USER_BB_ALLY : "Название альянса",
		USER_BB_ALLYDETAILS : "Подробности альянса",
		USER_BB_PLAYERNAME : "Имя игрока",
		USER_BB_BANNED : "Заблокирован",
		USER_BB_VACATION : "Режим отпуска",
		USER_BB_NOOB : "Защита новичков",
		USER_BB_INACTIVE : "неактивный",
		USER_BB_LONGINACTIVE : "неактивный 4 недели",
		USER_DELETION : "Удалить",
		USER_FLEETINFO : "Передвижения флотов",
		USER_ACTIVITIES : "Активность игроков",
		USER_MAINTENANCE : "Поддержка Galaxytool",
		USER_MANAGEMENT : "Управление пользователями",
		USER_DELETE_MY_COMBAT_REPORTS : "Удалить мои логи",
		USER_DELETE_MY_MESSAGES : "Удалить мои сообщения",
		USER_DELETE_MY_FLEETMOVES : "Удалить информацию о передвижении моих флотов",
		USER_DELETE_MY_COMBAT_REPORTS_LIMITED : "Удалить мои боевые доклады старше &1 дней",
		USER_DELETE_MY_MESSAGES_LIMITED : "Удалить мои сообщения старше &1 дней",
		USER_TABLE_ENTRIES : "Количество результатов поиска для каждой страницы.",
		USER_EXISTS : "Пользователь уже существует",
		USER_BB_OUTLAW : "Бандит",
		USER_INVALID_URL : "Указанный URL &1 неверный - он будет пропущен",
		VIEW_TITLE : "OGame Galaxytool - Обзор подробностей",
		VIEW_NODATA : "Пока нет данных.",
		VIEW_GALAXY : "Галактика",
		VIEW_SYSTEM : "Солнечная система",
		VIEW_POSITION : "Поз.",
		VIEW_PLANET : "Планета",
		VIEW_MOON : "Луна",
		VIEW_TF : "Обломки",
		VIEW_PLAYER : "Игрок",
		VIEW_PLAYER_ADD : "(Статус)",
		VIEW_ALLY : "Альянс",
		VIEW_ALLY_ADD : "",
		VIEW_METAL : "М",
		VIEW_CRYSTAL : "К",
		VIEW_COLONISED : "Планет заселено",
		VIEW_UKMOONSIZE : "неизвестно",
		VIEW_BACK : "Назад",
		VIEW_NOTICE : "Заметки",
		VIEW_REPORTS : "Шпионаж",
		VIEW_MOONPHALANX : "Фаланги следующих лун достают до этой системы:",
		VIEW_NOMOONS : "Луны не найдены",
		VIEW_IRAKS : "Межпланетные ракеты следующих планет достают до этой системы",
		VIEW_NOIRAKS : "Не удалось найти МПР",
		VIEW_MOON_DESTROY_CHANCE : "Вероятности уничтожения луны",
		VIEW_CHANCE_WITH_ONE : "Вероятность с одной ЗС",
		VIEW_CHANCE_WITH_N : "Вероятность с ",
		VIEW_DEATH_STARS : "ЗС",
		VIEW_DS_DESTROY_CHANCE : "Вероятность потери ЗС",
		VIEW_TOP : "ТОП",
		VIEW_GO : "перейти",
		VIEW_DIAMETER : "Диаметр",
		PW_TITLE : "OGame Galaxytool - Смена пароля",
		OLD_PASSWORD : "Старый пароль",
		NEW_PASSWORD : "Новый пароль",
		CONFIRM_NEW_PASSWORD : "Повторить новый пароль",
		PW_MISMATCH : "Введёные новые пароли не одинаковы!",
		PW_ERROR : "Старый пароль неверен!",
		UPDATE_DONE : "Готово.",
		TIMEZONE_OFFSET : "Разница времени с сервером",
		DELETE_ACCOUNT : "Удалить аккаунт в Galaxytool",
		DELETE_ACCOUNT_SAFETY_REQUEST : "Вы действительно хотите удалить данный аккаунт в Galaxytool?",
		CH_PASSWD_AUTHORIZATION : "Разрешения",
		CH_PASSWD_ADMIN : "Админ",
		TIMEZONE_OGAME_OFFSET : "Часовой пояс для сервера OGame",
		CH_PASSWD_USER_LANGUAGE : "Поменять на этот язык после нового логина",
		CH_PASSWD_USER_LANGUAGE_NO_CHANGE : "Оставить без изменений",
		CH_PASSWD_EXPAND : "Растянуть",
		CH_PASSWD_COLLAPSE : "Сжать",
		CH_PASSWD_HIDDEN : "Скрыто",
		CH_PASSWD_GETTING_STARTED : "Показывать \"Первые шаги\" после авторизации",
		CH_PASSWD_PLUGIN : "Показывать информацию о плагине после авторизации",
		NOTICE_TITLE : "OGame Galaxytool - Заметки",
		NOTICE_HEADER : "Редактировать заметку",
		NOTICE_HEADER2 : "Редактировать свои заметки",
		NOTICE_PUBLIC : "Сделать видимым для всех?",
		NOTICE_YES : "да",
		NOTICE_NO : "нет",
		NOTICE_TEXT : "Текст заметки",
		NOTICE_SAVE : "Сохранить",
		NOTICE_DELETED : "Запись удалена.",
		NOTICE_SAVED : "Запись сохранена.",
		NOTICE_RESULTS : "Все заметки",
		NOTICE_USER : "Пользователь",
		NOTICE_DATE : "Дата",
		NOTICE_EDIT : "Редактировать",
		NOTICE_DELETE : "Удалить",
		NOTICE_NEW : "Удалить свою запись",
		NOTICE_NOTPUBLIC : "Заметка не общедоступна.",
		NOTICE_ALL : "все",
		NOTICE_NONE : "ничего",
		NOTICE_SEARCH : "Искать в заметках",
		NOTICE_SEARCH_SHORT : "Поиск",
		NOTICE_HITS : "Результаты",
		NOTICE_SHOWRESULTS : "Результатов на страницу",
		NOTICE_OF : "из",
		NOTICE_NOTHING : "Поиск не дал результатов.",
		NOTICE_CHARS : "Знаки",
		NOTICE_PLAYERNAME : "Игрок",
		NOTICE_SHOWALL : "Показать все заметки.",
		REPORTS_TITLE : "OGame Galaxytool - Шпионские доклады",
		REPORTS_RESOURCES : "Сырьё",
		REPORTS_FLEET : "Флоты",
		REPORTS_DEFENCE : "Оборона",
		REPORTS_BUILDINGS : "Постройки",
		REPORTS_TECHNOLOGY : "Исследования",
		REPORTS_MOON : "Луна",
		REPORTS_SEARCH : "Искать в докладах",
		REPORTS_SEARCH_SHORT : "Поиск",
		REPORTS_HITS : "Результаты",
		REPORTS_NOTHING : "Поиск не дал результатов.",
		REPORTS_ADDRESS : "Адрес",
		REPORTS_CURRENTNESS : "Актуальность",
		REPORTS_PLAYERNAME : "Имя игрока",
		REPORTS_ALLY : "Альянс",
		REPORTS_VIEW : "Просмотреть доклад",
		REPORTS_SEARCH_IN : "Искать в галактике",
		REPORTS_FROM_SYSTEM : "от системы",
		REPORTS_TO : "до",
		REPORTS_DELETE : "удалить",
		REPORTS_DELETED : "Запись удалена",
		REPORTS_RESULTS : "Результатов на страницу",
		REPORTS_OF : "из",
		REPORTS_DATE : "дата",
		REPORTS_DATE_0 : "все",
		REPORTS_DATE_1 : "старше чем",
		REPORTS_DATE_2 : "новее чем",
		REPORTS_NOTICES : "заметки",
		REPORTS_AT_LEAST_RESOURCES : "Всего ресурсов (мин.)",
		REPORTS_SEARCH_EXTENDED : "расширенный поиск",
		REPORTS_FLEET_RESIS : "Очки во флоте",
		REPORTS_DEFENCE_RESIS : "Очки в защите",
		REPORTS_ALL_RESIS : "всего потеря очков",
		REPORTS_TECHS : "Технологии",
		REPORTS_UNKNOWN_ENTRIES : "неизвестные записи",
		REPORTS_PARTLY_INSERTED : "вставлено частично",
		REPORTS_FOR_ALL_RES : "Для всех ресурсов",
		REPORTS_FOR_TF : "Для обломков",
		REPORTS_KT : "Малый транспорт",
		REPORTS_GT : "Большой транспорт",
		REPORTS_SS : "Линкоры",
		REPORTS_REC : "Переработчики",
		REPORTS_RAIDABLE : "Только цели, которые можно грабить",
		REPORTS_ALL_RESOURCES : "Всего ресурсов",
		REPORTS_STUFF : "Другое",
		REPORTS_SPEEDSIM : "Симулировать в Websim",
		REPORTS_DRAGOSIM : "Симулировать в Dragosim",
		REPORTS_STATUS : "Статус",
		REPORTS_ERROR : "Возникла ошибка",
		REPORTS_OWN_REPORTS : "Только мои доклады",
		REPORTS_UPLOAD_BY : "Доклады, загруженные",
		REPORTS_DEPTH : "Глубина докладов",
		REPORTS_FLEET_SCORE : "Очки во флотах",
		REPORTS_DEFENCE_SCORE : "Очки в обороне",
		REPORTS_HOURS : "часов",
		REPORTS_MAX_RESULTS_HIT : "Ваш запрос вернул более &1 записей. Только первые &1 записей будут отображены. Измените ваш запрос, чтобы он вернул меньшее число записей.",
		REPORTS_OSIMULATE : "Симуляция с помощью OSimulate",
		REPORTS_SHOW_ONLY : " Показать только",
		REPORTS_SHOW_PLANETS : "Планеты",
		REPORTS_SHOW_MOONS : "Луны",
		REPORTS_OWNER : "Отчеты принадлежат",
		STATS_TITLE : "OGame Galaxytool - Статистика",
		STATS_TBLHEAD : "Статистика",
		STATS_RANK : "Место",
		STATS_PLAYERNAME : "Игрок",
		STATS_SCORE : "Очки",
		STATS_FLEET : "Флот",
		STATS_RESEARCH : "Исследования",
		STATS_ALLYNAME : "Альянс",
		STATS_MEMBERS : "Члены",
		STATS_STATUS : "Статус",
		STATS_NOTHING : "без статуса",
		STATS_NAP : "Пакт",
		STATS_ALLIED : "Союзник",
		STATS_WAR : "Война",
		STATS_BOYCOTT : "Бойкот",
		STATS_NEUTRAL : "Нейтр. отношения",
		STATS_OWN : "Свой альянс",
		STATS_WING : "Крыло",
		STATS_UPDATE : "Данные от",
		STATS_PLAYERSTATS : "Статистика игроков",
		STATS_ALLYSTATS : "Статистика альянсов",
		STATS_DELETE : "удалить игрока",
		STATS_CONFIRM_DELETE : "Действительно удалить игрока из статистики?",
		STATS_CHANGE_PLAYER_STATUS : "Статус игрока",
		STATS_CHANGE_ALLIANCE_STATUS : "Статус альянса",
		STATS_CHANGE_ALLIANCE_STATUS_HINT : "Все игроки этого альянса получат выбранный статус. Предыдущий статус будет заменён. Но возможно после этого дать игрокам отдельный статус.",
		STATS_UNKNOWN : "Остальные",
		STATS_DETAILS : "Подробности для",
		STATS_PLAYERSTATUS : "Статус игрока",
		STATS_IGNORE_STATUS : "все",
		STATS_ACTIVE : "активный",
		STATS_INACTIVE : "неактивный",
		STATS_BANNED : "Заблокирован",
		STATS_VACATION : "Режим отпуска",
		STATS_NOOB : "Защита новичков",
		STATS_YES : "Да",
		STATS_NO : "Искать только планеты с заметками",
		STATS_SEARCH : "Искать",
		STATS_SHOW_GRAPH : "Отображать детали",
		STATS_LONG_INACTIVE : "неактивный 4 недели",
		STATS_STANDARD : "По очкам",
		STATS_MILITARY : "Боевой рейтинг",
		STATS_ECONOMY : "Экономика",
		STATS_HONOUR : "Очки чести",
		STATS_MILITARY_BUILD : "Боевых очков набрано",
		STATS_MILITARY_DESTROYED : "Боевых очков уничтожено",
		STATS_MILITARY_LOST : "Боевых очков потеряно",
		REGISTER_REGISTRATE : "Регистрация",
		REGISTER_LOGINNAME : "Логин",
		REGISTER_PASSWORD : "Пароль",
		REGISTER_PASSWORD_CONFIRM : "Повторить пароль",
		REGISTER_EMAIL : "E-mail",
		REGISTER_INGAME : "Имя в игре",
		REGISTER_ALLYTAG : "Аббревиатура альянса",
		REGISTER_EMAILVERIFICATION : "Проверка адреса E-mail",
		REGISTER_EMAILTEXT : "Нажмите на эту ссылку, чтобы завершить регистрацию на Galaxytool:",
		REGISTER_ERROR1 : "Этот логин уже занят.",
		REGISTER_ERROR2 : "Ошибка при отправлении письма! Свяжитесь с администратором.",
		REGISTER_ERROR3 : "Ошибка при связи с базой данных!",
		REGISTER_INFO1 : "Аккаунт успешно создан.",
		REGISTER_INFO2 : "Нажмите теперь на ссылку в регистрационном E-mail чтобы завершить регистрацию.",
		REGISTER_INFO3 : "Адрес E-mail подтверждён, теперь только админ должен активировать аккаунт.",
		REGISTER_BUTTON : "Обратно на стартовую",
		REGISTER_NEW_SUBJECT : "Зарегистрирован новый пользователь",
		REGISTER_NEW_MAILTEXT : "Новый пользователь зарегистрировался в Galaxytool.",
		REGISTER_BACK : "Вернуться на первую страницу",
		REGISTER_MISSING_FIELDS : "Заполните все обязательные поля",
		REGISTER_ERROR4 : "Email адрес не действителен.",
		REGISTER_ERROR5 : "Пароли не совпадают.",
		REGISTER_PWS : "Устойчивость пароля",
		REGISTER_PWS0 : "Очень слабый",
		REGISTER_PWS1 : "Слабый",
		REGISTER_PWS2 : "Хороший",
		REGISTER_PWS3 : "Сильный",
		REGISTER_PWS4 : "Очень сильный",
		REGISTER_EMAIL_USED : "Указанный E-mail уже используется",
		LOSTPW_TITLE : "Восстановление пароля",
		LOSTPW_INFO2 : "Новый пароль был создан и выслан на указанный адрес.",
		LOSTPW_BUTTON1 : "Запросить пароль",
		LOSTPW_BUTTON2 : "Обратно на стартовую",
		LOSTPW_LOGINNAME : "Логин",
		LOSTPW_EMAIL : "E-mail",
		LOSTPW_ERROR1 : "Ошибка при запросе базы данных!",
		LOSTPW_ERROR2 : "Подходящая запись не найдена!",
		LOSTPW_ERROR3 : "Ошибка при отправлении письма! Свяжитесь с администратором.",
		LOSTPW_EMAIL_SUBJECT : "Восстановление пароля",
		LOSTPW_EMAIL_TEXT1 : "Запрошенные данные для логина в Galaxytool",
		LOSTPW_EMAIL_TEXT2 : "Логин",
		LOSTPW_EMAIL_TEXT3 : "Пароль",
		LOSTPW_INFO1 : "На ваш E-mail было отправлено письмо, для подтверждения сброса пароля.",
		LOSTPW_CONFIRM_RESET_SUBJECT : "Забыли пароль?",
		LOSTPW_CONFIRM_RESET_MESSAGE : "Привет,\n\nвы запросили сброс пароля для Galaxytool. Чтобы получить новый пароль нажми на следующую ссылку:",
		USERINFO_TITLE : "OGame Galaxytool - Пользовательская информация",
		USERINFO_NAMES : "Все пользователи сайта",
		USERINFO_DETAIL : "Подробности о",
		USERINFO_ERROR1 : "Пользователь с таким ID неизвестен!",
		USERINFO_USERNAME : "Логин",
		USERINFO_INGAME : "Ник в игре",
		USERINFO_EMAIL : "E-mail",
		USERINFO_ALLYTAG : "Альянс",
		USERINFO_STYLEPATH : "Скин",
		USERINFO_STATUS : "Статус",
		USERINFO_ACTIVATE : "Активировать пользователя",
		USERINFO_LOGINS : "Кол-во входов на сайт",
		USERINFO_LASTLOGIN : "Последний Вход в систему",
		USERINFO_DATA : "Информация о занесённых системах",
		USERINFO_NODATA : "Пользователь ещё не вносил данных!",
		USERINFO_GALAXY : "Галактика",
		USERINFO_SYSTEMS : "Кол-во систем",
		USERINFO_IP : "Адрес IP",
		USERINFO_LOGINTIME : "Время входа в систему",
		USERINFO_NOLOGIN : "Пользователь ещё не логинился.",
		USERINFO_LAST_GALAXYUPDATE : "Последний внос обзора галактики",
		USERINFO_LAST_PUBLIC_NOTICE : "Последняя общественная заметка",
		USERINFO_LAST_PRIVATE_NOTICE : "Последняя личная заметка",
		USERINFO_NUMBEROF_PUBLIC_NOTICE : "Кол-во общественных заметок",
		USERINFO_NUMBEROF_PRIVATE_NOTICE : "Кол-во личных заметок",
		USERINFO_ACTIVATED : "Аккаунт активирован",
		USERINFO_ACTIVATIONTEXT : "Администратор Galaxytools активировал твой аккаунт.\n\n Удачи при использовании Galaxytool!",
		USERINFO_LAST_SUBMIT : "Добавлена последняя информация",
		ALLYHISTORY_TITLE : "OGame Galaxytool - Статистика по времени",
		ALLYHISTORY_TBLHEAD : "Обзор",
		ALLYHISTORY_PLAYERNAME : "Игрок",
		ALLYHISTORY_ALLYNAME : "Альянс",
		ALLYHISTORY_LASTMONTH : "Актуальный месяц",
		ALLYHISTORY_ALL_DATA : "Все имеющиеся данные",
		ALLYHISTORY_SHOW : "показать статистику",
		ALLYHISTORY_TIMESPAN : "Продолжительность",
		ALLYHISTORY_PROGESS : "Прирост",
		ALLYHISTORY_SCORE : "Очки",
		ALLYHISTORY_FSCORE : "Очки по флотам",
		ALLYHISTORY_RSCORE : "Очки по исследованиям",
		ALLYHISTORY_MEMBER : "Члены",
		ALLYHISTORY_NOTHING : "Не удалось ничего найти",
		ALLYHISTORY_DETAILS : "Подробности",
		ALLYHISTORY_SHOW_ADDRESS : "Координаты",
		ALLYHISTORY_ESCORE : "Экономика",
		ALLYHISTORY_MSCORE : "Боевой рейтинг",
		DETAILEDINFO_PLAYERINFO_TITLE : "Информация об игроках",
		DETAILEDINFO_ALLYINFO_TITLE : "Информация об альянсах",
		DETAILEDINFO_PLAYERINFO_TBLHEAD : "Подробная информация об игроке",
		DETAILEDINFO_ALLYINFO_TBLHEAD : "Подробная информация об альянсе",
		DETAILEDINFO_NO_ALLIANCE : "нет",
		DETAILEDINFO_SCORE : "Статистика по очкам",
		DETAILEDINFO_FLEET : "Статистика по флотам",
		DETAILEDINFO_RESEARCH : "Статистика по исследованиям",
		DETAILEDINFO_RANK : "Место",
		DETAILEDINFO_POINTS : "Очки",
		DETAILEDINFO_KNOWN_PLANETS : "Известные планеты",
		DETAILEDINFO_MOONS : "Известные луны",
		DETAILEDINFO_PHALANX_AREA : "Доклады фаланг",
		DETAILEDINFO_NO_PHALANX_AREA : "Не удалось найти фалангу",
		DETAILEDINFO_NOTICES : "Заметки",
		DETAILEDINFO_NO_NOTICES : "Нет заметок",
		DETAILEDINFO_PREVIOUS_ALLIANCES : "Известные альянсы игрока",
		DETAILEDINFO_RESOURCES_PER_HOUR : "Ресурсов в час",
		DETAILEDINFO_RESOURCES_PER_DAY : "Ресурсов в день",
		DETAILEDINFO_RESOURCES_PER_WEEK : "Ресурсов за неделю",
		DETAILEDINFO_RESOURCES_PER_MONTH : "Ресурсов за  месяц (30 дней)",
		DETAILEDINFO_METAL : "Металла",
		DETAILEDINFO_CRYSTAL : "Кристалла",
		DETAILEDINFO_DEUTERIUM : "Дейтерия",
		DETAILEDINFO_UNKNOWN : "неизвестно",
		DETAILEDINFO_SCORE_DISTRIBUTION : "Распределение очков",
		DETAILEDINFO_GENERAL : "Подробно",
		DETAILEDINFO_MEMBERS : "Члены",
		DETAILEDINFO_GRAPHS : "Графики",
		DETAILEDINFO_RESOURCES : "Ресурсы",
		DETAILEDINFO_FLEET_TAB : "Флоты",
		DETAILEDINFO_TECH : "Исследования",
		DETAILEDINFO_FLEET_DETAIL : "Итог / (среднее по игрокам) среди всех доступных докладов",
		DETAILEDINFO_TECH_DETAIL : "Среднее по всей доступной информации по игрокам",
		DETAILEDINFO_PLANET_TAB : "Планеты",
		DETAILEDINFO_MOON_TAB : "Луны",
		DETAILEDINFO_ACTIVITIES : "Активность",
		DETAILEDINFO_NODATA : "Пока нет данных.",
		DETAILEDINFO_ACTIVITY_DESCRIPTION : "Показать активность &1 собранную с:",
		DETAILEDINFO_GALAXYVIEWS : "Просмотры галактики",
		DETAILEDINFO_SCANS : "Шпионаж",
		DETAILEDINFO_MESSAGES : "Сообщения",
		DETAILEDINFO_COMBATS : "Боевые доклады",
		DETAILEDINFO_ALLYPAGE : "Просмотры страницы альянса",
		DETAILEDINFO_MANUAL : "Информацию добавленную вручную",
		DETAILEDINFO_START : "Начало",
		DETAILEDINFO_TO : "до",
		DETAILEDINFO_TODAY : "Конец",
		DETAILEDINFO_DATA_RESTRICTION : "включая:",
		DETAILEDINFO_WEEKDAY_WEEKEND : "Выходной день",
		DETAILEDINFO_WEEKDAY_WORKINGDAY : "Рабочий день",
		DETAILEDINFO_WEEKDAY_MONDAY : "Пн.",
		DETAILEDINFO_WEEKDAY_TUESDAY : "Вт.",
		DETAILEDINFO_WEEKDAY_WEDNESDAY : "Ср.",
		DETAILEDINFO_WEEKDAY_THURSDAY : "Чт.",
		DETAILEDINFO_WEEKDAY_FRIDAY : "Пт.",
		DETAILEDINFO_WEEKDAY_SATURDAY : "Сб.",
		DETAILEDINFO_WEEKDAY_SUNDAY : "Вс.",
		DETAILEDINFO_WEEKDAY_SHORTLENGTH : 3,
		DETAILEDINFO_PLAYER_CURRENTLY_ACTIVE : "Игрок активен в данный момент",
		DETAILEDINFO_PLAYER_MESSAGES : "доступные сообщение игрока",
		DETAILEDINFO_SHOW : "показать",
		DETAILEDINFO_NONE : "недоступно",
		DETAILEDINFO_ENTER_MANUALLY : "Добавить информацию об активности этого игрока",
		DETAILEDINFO_PLAYER_SEEN_ON : "Игрок был онлайн во время",
		DETAILEDINFO_INSERT : "Вставить",
		DETAILEDINFO_OGAME_SERVERTIMES : "Внимание: Информация о дате и времени соответствует времени серверов OGame !",
		DETAILEDINFO_DAY_VIEW : "обзор за 24 часа",
		DETAILEDINFO_WEEK_VIEW : "недельный обзор",
		DETAILEDINFO_HOME_PLANET : "Главная планета",
		DETAILEDINFO_PLANETNAME : "Название",
		DETAILEDINFO_DEFENCE_SCORE : "Очки обороны",
		DETAILEDINFO_DEFENCE_SCORE_TOOLTIP : "Очки обороны = Флот - Очки + Исследования + Экономика.<br/>Вся указанная статистика должна быть свежей, чтобы иметь хоть какое-то значение!",
		DETAILEDINFO_SCORE_PER_SHIP : "Очков на единицу флота",
		DETAILEDINFO_SHIPS : "Количество флота",
		DETAILEDINFO_DATE_IN_FUTURE : "Укажите время из прошлого.",
		ADMIN_TITLE : "Администрирование Galaxytool",
		ADMIN_DISCLAMER : "Внимание: Запускайте любой из этих скриптов крайне аккуратно! Почти все из них удаляют данные.",
		ADMIN_INCONSISTENCIES : "Несоответствие данных в базе данных",
		ADMIN_PLANETS : "Планеты на позициях 0 или больших 15",
		ADMIN_GALAXIES : "Удалить галактики с номером больше чем &1 ",
		ADMIN_PLAYERS : "Удалить игроков без игрового идентификатора, его отсутствие приводит к дублированию в списке игроков",
		ADMIN_REPORTS : "Удалить доклады для больше не существующих планет",
		ADMIN_MISC : "Разное",
		ADMIN_RESET : "Очистка Galaxytool (не удалятся только таблицы с пользователями и IP адресами)",
		ADMIN_OLD_PLAYERS : "Удалить записи игроков старше чем &1 дней",
		ADMIN_OLD_REPORTS : "Удалить доклады старше чем &1 дней",
		ADMIN_LOADING : "Не закрывайте данное окно, пока выполняется скрипт.",
		ADMIN_STATUS : "Состояние ваших запросов",
		ADMIN_SELECTION : "Хотя бы один пункт должен быть выбран",
		ADMIN_SAFETY : "Вы уверены, что хотите запустить данный(-е) скрипт(ы)?",
		ADMIN_DONE : "выполнено",
		ADMIN_NOTBD : "не выполнено",
		ADMIN_OLD_GALAXIES : "Удалить обзоры галактик старше, чем &1 дней",
		ADMIN_UNUSED_PLAYERS : "Удалить игроков, не встречающихся ни в одном обзоре галактик",
		ADMIN_OLD_ACTIVITIES : "Удалить информацию об активности старше, чем &1 дней",
		ADMIN_OLD_COMBATS : "Удалить боевые доклады старше &1 дней",
		ADMIN_OLD_INGAME_MSG : "Удалить игровые сообщения старше &1 дней",
		ADMIN_OGAME_API : "Загрузить информацию из OGame API в Galaxytool",
		ADMIN_OGAME_ALL_DATA : "Все имеющиеся данные",
		ADMIN_OGAME_GALAXY_DATA : "Обзор галактики",
		ADMIN_OGAME_STATISTICS_DATA : "Статистика",
		ERRORPAGE_PAGEFORWARD : "Нажмите здесь, если ваш браузер не поддерживает перенаправление",
		ERRORPAGE_PERMISSION_DENIED : "У вас нет прав перехода на эту страницу. Нажмите для перехода назад.",
		FLEETS_TITLE : "OGame Galaxytool - Передвижения флотов",
		FLEETS_ACTUAL_FLEETS : "Текущие передвижения флотов",
		FLEETS_YES : "Да",
		FLEETS_NO : "Искать только планеты с заметками",
		FLEETS_DETAILS : "Подробности",
		FLEETS_MISSION_EXPEDITION : "Экспедиция",
		FLEETS_MISSION_COLONIZATION : "Колонизировать",
		FLEETS_MISSION_RECYCLE : "Переработать",
		FLEETS_MISSION_TRANSPORT : "Транспорт",
		FLEETS_MISSION_DEPLOYMENT : "Оставить",
		FLEETS_MISSION_ESPIONAGE : "Шпионаж",
		FLEETS_MISSION_ACS_DEFEND : "САБ Защите",
		FLEETS_MISSION_ATTACK : "Атаковать",
		FLEETS_MISSION_ACS_ATTACK : "САБ Атака",
		FLEETS_MISSION_MOON_DESTRUCTION : "Уничтожить",
		FLEETS_MISSION_MISSILE_ATTACK : "Ракетная атака",
		FLEETS_NO_DATA : "Данные не найдены",
		FLEETS_FLEET : "Флот",
		FLEETS_ALL_FLEETS : "Отобразить все передвижения флота",
		COMBAT_REPORT_OUDATED_GALAXYVIEW : "Ваши данные о галактике устарели. Пожалуйста сначала откройте координаты боя и боевой доклад!",
		MESSAGES_TITLE : "OGame Galaxytool - OGame Сообщения",
		MESSAGES_PLAYERNAME : "Игрок",
		MESSAGES_SUBJECT : "Тема",
		MESSAGES_DATE : "Дата",
		MESSAGES_FILTER : "Фильтр",
		MESSAGES_DELETE : "Удалить сообщение",
		MESSAGES_PUBLISH_DETAIL : "Опубликовать сообщение, добавив его содержимое к заметкам об этом игроке.",
		MESSAGES_PUBLISH_HEADER : "&sender послал сообщение &recipient &date:\n\n &message",
		MESSAGES_PLAYER_FILTER : "Сообщение для игрока:",
		MESSAGES_CONTENT : "Содержание",
		COMBATS_TITLE : "OGame Galaxytool - Боевые доклады",
		COMBATS_ATTACKER : "Атакующий",
		COMBATS_DEFENDER : "Защитник",
		COMBATS_DATE : "Дата",
		COMBATS_OWNER : "Владелец",
		COMBATS_WINNER : "Победитель",
		COMBATS_COMBATREPORT : "Боевой доклад",
		COMBATS_COMBAT_AT : "Битва на",
		COMBATS_LOST_UNITS : "Потеряно кораблей",
		COMBATS_LOOT : "Получено",
		COMBATS_DEBRIS : "Поле обломков",
		COMBATS_AND : "и",
		COMBATS_PUBLISH : "Опубликовать этот доклад",
		COMBATS_UNPUBLISH : "Отменить публикацию",
		COMBATS_DELETE : "Удалить доклад",
		COMBATS_CHECK_ALL : "Выделить всё",
		COMBATS_UNCHECK_ALL : "Отменить выделение",
		COMBATS_WITH_SELECTED : "С выбранными",
		COMBATS_PUBLIC_REPORTS : "Опубликованные доклады",
		COMBATS_YES : "Да",
		COMBATS_NO : "Искать только планеты с заметками",
		COMBATS_SEARCH_OPTIONS : "Опции поиска",
		COMBATS_SEARCH : "Вперёд",
		COMBATS_RESET : "Сбросить",
		COMBATS_COORDINATES : "Координаты",
		COMBATS_INVALID_GALAXY_ENTERED : "Выбрана неверная Галактика",
		COMBATS_INVALID_SYSTEM_ENTERED : "Выбрана неверная Система",
		COMBATS_INVALID_PLANET_ENTERED : "Выбрана неверная Планета",
		COMBATS_GALAXY_FROM_TO : "Галактика",
		COMBATS_SYSTEM_FROM_TO : "Система",
		COMBATS_PLANET_FROM_TO : "Планета",
		COMBATS_APPLY : "Применить",
		COMBATS_COMBAT_SUMMARY : "Итог боевых докладов",
		COMBATS_DOWNLOAD_CSV : "Скачать в качестве CSV файла",
		REPORT_ARCHIVE_TITLE : "Архив сканов",
		REPORT_ARCHIVE_COORDINATES : "Координаты",
		REPORT_ARCHIVE_SCANTIME : "Время скана",
		REPORT_ARCHIVE_DELETE : "Удалить эти записи",
		REPORT_ARCHIVE_CONFIRM_DELETE : "Вы действительно ходите удалить эти записи?",
		REPORT_ARCHIVE_GALAXY : "Галактика",
		REPORT_ARCHIVE_SYSTEM : "Система",
		REPORT_ARCHIVE_PLANET : "Планета",
		REPORT_ARCHIVE_MOON : "Луна",
		REPORT_ARCHIVE_DETAILS : "Детали",
		REPORT_ARCHIVE_RESOURCES : "Ресурсов в час",
		REPORT_ARCHIVE_HEADER_RESOURCES : "Сырьё",
		REPORT_ARCHIVE_DETAILS_FOR : "Архив сканов &1 [&2] (&3)",
		REPORT_ARCHIVE_FLEET_CARGO : "Вместимость транспортов",
		REPORT_ARCHIVE_IRAK_RANGE : "Радиус МПР",
		REPORT_ARCHIVE_CHART_TYPE : "Тип Чарта",
		INSTALL_TITLE : "Установка Galaxytool версии",
		INSTALL_PROGRESS : "Общий прогресс",
		INSTALL_STEP : "Шаг",
		INSTALL_CONTINUE : "Продолжить",
		INSTALL_VALIDATE : "Проверка",
		INSTALL_STEP1 : "Добро пожаловать",
		INSTALL_STEP2 : "Проверка на запись",
		INSTALL_STEP3 : "Настройки базы данных",
		INSTALL_STEP4 : "Настройки OGame",
		INSTALL_STEP5 : "Настройки Galaxytool",
		INSTALL_STEP6 : "Пароль администратора",
		INSTALL_STEP7 : "Установка Galaxytool",
		INSTALL_STEP8 : "Завершение установки",
		INSTALL_FILE_DELETE_CHECK : "Пожалуйста, удалите install.php и update.php с вашего веб-сервера.",
		INSTALL_STEP1_PHP_FAILED : "Ваша версия PHP &1 не поддерживается Galaxytool",
		INSTALL_STEP1_FOPEN_FAILED : "Ваша версия PHP не позволяет открывать страницу с помощью команды FOPEN(). Это требуется для работы с OGame API.",
		INSTALL_STEP1_WELCOME : "Добро пожаловать в мастер установки Galaxytool. Сейчас вам надо будет выполнить все этапы установки Galaxytool. Мастер установки вам в этом поможет.",
		INSTALL_STEP2_DESCRIPTION : "Убедитесь, что файлы config.php и attributes.php имеют права на запись.",
		INSTALL_STEP2_DESCRIPTION2 : "Если вы не знаете, как достичь этого, поищите здесь: &1",
		INSTALL_STEP2_FILE_NOT_WRITEABLE : "Файл не записываем",
		INSTALL_STEP3_SERVER : "Сервер баз данных",
		INSTALL_STEP3_USERNAME : "Логин",
		INSTALL_STEP3_PASSWORD : "Пароль",
		INSTALL_STEP3_DBNAME : "Имя базы данных",
		INSTALL_STEP3_PREFIX : "Префикс таблиц БД",
		INSTALL_STEP3_ENTER_PREFIX : "Напр., mytool_",
		INSTALL_STEP3_ENTER_SERVER : "Введите адрес сервера. Если потребуется, узнайте это у вашего системного администратора. Обычно эта настройка имеет значение localhost.",
		INSTALL_STEP3_ENTER_USERNAME : "Введите имя пользователя БД",
		INSTALL_STEP3_ENTER_PASSWORD : "Введите пароль пользователя БД",
		INSTALL_STEP3_ENTER_DBNAME : "Введите имя базы данных, которая будет использована (должна существовать)",
		INSTALL_STEP3_CONNECT_FAILED : "Не смог установить соединение с сервером баз данных!",
		INSTALL_STEP3_DB_FAILED : "База данных &1 не найдена",
		INSTALL_STEP3_MYSQL_VERSION_FAILED : "Версия MySQL &1 не поддерживается Galaxytool",
		INSTALL_STEP4_URL : "OGame URL",
		OGAME_URL_DETAILS : "Введите любой URL, который вы видите сразу после входа в OGame. Основываясь на этом URL Galaxytool найдет URL OGame API, который можно использовать для получения данных для Galaxytool без использования Galaxytoolbar. API было введено в OGame версии 4.1.",
		INSTALL_STEP4_UNIVERSE : "Вселенная OGame",
		INSTALL_STEP4_DEF_TO_DEBRIS : "Оборона в обломки",
		INSTALL_STEP4_DEBRIS_RATE : "Процент флота в обломки",
		INSTALL_STEP4_SPEED_RATE : "Множитель скорости",
		INSTALL_STEP4_ENTER_UNIVERSE : "Введите имя или номер вашей вселенной OGame (регистрозависимо).",
		INSTALL_STEP4_UNIVERSE_MISSING : "Вы должны указать вселенную",
		INSTALL_STEP4_ENTER_URL : "Введите адрес вашей вселенной OGame",
		INSTALL_STEP4_URL_MISSING : "Вы должны указать адрес вселенной OGame",
		INSTALL_STEP4_URL_CHECK_FAILED : "Не смог найти OGame API в &1",
		INSTALL_STEP4_GETSETTINGS : "Fetch settings",
		INSTALL_STEP5_TOOLNAME : "Название Galaxytool",
		INSTALL_STEP5_ENTER_TOOLNAME : "Это название будет отображено на главной странице вашей Galaxytool",
		INSTALL_STEP5_LANGUAGE : "Язык по-умолчанию",
		INSTALL_STEP5_EMAIL_TO : "Отправлять на",
		INSTALL_STEP5_ENTER_EMAIL_TO : "Введите E-mail адрес на который вы хотели бы получать уведомления о новых регистрация в вашей Galaxytool",
		INSTALL_STEP5_EMAIL_FROM : "Отправлять от",
		INSTALL_STEP5_ENTER_EMAIL_FROM : "Этот E-mail адрес используется в качестве отправителя, когда Galaxytool отправляет какие-либо письма.",
		INSTALL_STEP5_USE_PHPMAILER : "Использовать PHPMailer",
		INSTALL_STEP5_MAXSHOUTS : "Максимальное количество сообщений",
		INSTALL_STEP5_ENTER_USE_PHPMAILER : "Используйте PHPMailer, если ваш сервер не умеет отправлять письма сам.",
		INSTALL_PHPMAILER_HOST : "Сервер SMPT",
		INSTALL_PHPMAILER_HOST_EXAMPLE : "например, smtp.provider.com",
		INSTALL_PHPMAILER_USER : "Имя пользователя SMPT",
		INSTALL_PHPMAILER_USER_EXAMPLE : "например, user@provider.dcom",
		INSTALL_PHPMAILER_PASS : "Пароль пользователя SMPT",
		INSTALL_PHPMAILER_SECURE : "Способ авторизации (например, ssl)",
		INSTALL_PHPMAILER_PORT : "Порт SMPT",
		INSTALL_STEP6_INTRO : "Укажите пароль для аккаунта <strong>admin</strong>, который вам нужно будет использовать для первого входа в  Galaxytool, после установки.",
		INSTALL_STEP7_CONFIG : "Файл конфигурации создан",
		INSTALL_STEP7_CONFIG_FAILED : "Файл конфигурации не был создан",
		INSTALL_STEP7_ATTRIBUTES : "Файл параметров создан",
		INSTALL_STEP7_ATTRIBUTES_FAILED : "Файл параметров не был создан",
		INSTALL_STEP7_CREATED_TABLES : "Таблицы в базе данных созданы",
		INSTALL_STEP8_INTRO : "Вы успешно установили Galaxytool!",
		INSTALL_STEP8_LOAD_DATA : "Загрузка данных OGame ...",
		INSTALL_STEP8_LOAD_DATA_FINISHED : "Загрузка данных OGame завершена",
		INSTALL_STEP8_DELETE_FILE : "Теперь вам нужно удалить установочные файлы install.php и update.php с вашего веб-сервера.",
		INSTALL_STEP8_LOGON : "Войдите как <strong>admin</strong>, с помощью пароля, который вы указали при установке.",
		UPDATE_START : "Начинаю обновление до версии &1",
		UPDATE_STEP_DONE : "Выполнено",
		UPDATE_TITLE : "Обновление Galaxytool до версии",
		UPDATE_STEP1_WELCOME : "Добро пожаловать в мастер обновления Galaxytool. Сейчас вам надо будет выполнить все этапы обновления Galaxytool. Мастер обновлени поможет вам в этом.",
		UPDATE_STEP1_BACKUP_FILES : "В качестве первого шага, сделайте резервную копию папки <strong>config</strong>! Вам придется заменить настройки, в случае ошибок.",
		UPDATE_STEP1_BACKUP_DB : "Затем сделайте <a href=\"http://www.ehow.com/how_2036600_create-database-php.html\">резервную копию</a> вашей базы данных.",
		UPDATE_STEP1_PROCEED : "Как только резервные копии сделаны, вы можете продолжить обновление.",
		UPDATE_STEP1 : "Добро пожаловать",
		UPDATE_STEP2 : "Настройки Galaxytool",
		UPDATE_STEP2_OLD_VERSION : "Предыдущая версия Galaxytoo",
		UPDATE_STEP3 : "Обновить Galaxytool",
		UPDATE_STEP3_UPDATE_RUNNING : "Обновление, подождите...",
		UPDATE_STEP4 : "Завершить обновление",
		UPDATE_STEP4_INTRO : "Вы успешно обновили Galaxytool!",
		UPDATE_STEP4_UPDATE_DONE : "Все этапы обновления завершены.",
		UPDATE_FAILED : "Обновление не удалось.",
		GALAXYTOOL_DUMMY_TEXT : "dummy"
	})
);