define(
	({
		REPORT_WHEN : "",
		RESOURCES_ON : "Resurser på",
		PLAYER_BANNED : "b",
		PLAYER_VACATION_MODE : "s",
		PLAYER_NOOB : "k",
		PLAYER_INACTIVE : "i",
		PLAYER_LONG_INACTIVE : "I",
		PLAYER_OUTLAW : "o",
		L_USERNAME : "Användarnamn",
		L_PASSWORD : "Lösenord",
		L_LOGINFAILURE : "Felaktigt användarnamn eller lösenord eller så är ditt konto inte aktiverat än.",
		L_TOKENFAILURE : "Din inloggningsnyckel är felaktig eller så är dit konto inte aktiverat.",
		L_LOGINTEXT : "Vänligen logga in.",
		L_LANGUAGE : "Tillgängliga språk:",
		L_TIMEOUT : "Sessionen är ej längre giltig!",
		L_REGISTER : "Registrera",
		L_PWLOST : "glömt lösenord",
		INDEX_TITLE : "Översikt",
		INDEX_INFO : "Information",
		INDEX_ENTRIES : "Totalt antal system",
		INDEX_ENTRIES_LASTWEEK : "Nya system senaste veckan",
		INDEX_ENTRIES_TO_OLD : "System äldre än en månad",
		INDEX_REGISTERED_USERS : "Registrerade användare",
		INDEX_PAGEFORWARD : "Om din webbläsare inte stöder vidarebefordring, klicka här",
		INDEX_NOTICES : "Notiser",
		INDEX_PLAYERS : "Spelarstatistik",
		INDEX_ALLIES : "Alliansstatistik",
		INDEX_REPORTS : "Spionagerapporter",
		INDEX_VERSION : "Senaste version tillgänglig för nedladdning",
		INDEX_LATEST_VERSION : "Ingen nyare version tillgänglig",
		INDEX_SHOUTBOX : "Shoutbox",
		INDEX_NOENTRY : "Inga shouts än",
		INDEX_COMMENT : "Ditt Shout",
		INDEX_INSERT : "Lägg till",
		INDEX_UMOD : "Spelare i semesterläge",
		INDEX_NO_MOONS : "Antal månar",
		INDEX_NO_EMPTY_SYSTEMS : "Antal tomma system",
		INDEX_NO_FULL_SYSTEMS : "Antal fulla system",
		INDEX_NO_TARGETS : "Antal möjliga mål",
		INDEX_USERINFO : "Användarantal",
		INDEX_ONLINE : "Inloggade nu",
		INDEX_TODAY : "Inloggade idag",
		INDEX_ALL : "Totalt antal inloggningar",
		GENERAL_LOAD_FORM : "Ladda data",
		GENERAL_SAVE_FORM : "Spara data",
		GENERAL_SAVE_AS_TEXT : "Spara som",
		GENERAL_SAVE : "Spara",
		INDEX_USERMANAGEMENT : "Aktiveringsöversikt",
		INDEX_NEEDADMIN : "Konton att aktivera",
		INDEX_NEEDEMAIL : "Ej aktiverade konton",
		INDEX_TOOLBAR_INFO : "Galaxverktyg plugin information",
		INDEX_TOOLBAR_URL : "Galaxverktyg URL",
		INDEX_TOOLBAR_VERSION_REQUIRED : "Kräver lägst Galaxverktyg-plugin version ",
		INDEX_TOOLBAR_INSTALL_GUIDE : "Installationsguide för plugin",
		INDEX_TOOLBAR_TOKEN : "Login nyckel",
		INDEX_TOOLBAR_NEW_TOKEN : "Skapa ny nyckel",
		INDEX_PLAYERS_WITH_N_PLANETS : "Spelare med fler än &1 planeter",
		INDEX_GETTING_STARTED : "Kom igång med Galaxverktyget",
		INDEX_GETTING_STARTED1 : "Välkommen till Galaxverktyget!",
		INDEX_GETTING_STARTED2 : "Galaxverktyget hjälper dig analysera vad som händer i ditt OGame universum &1",
		INDEX_GETTING_STARTED3 : "Innan du kan analysera data behöver du importera den. Det gör du med ett plugin &1 till webbläsaren FireFox.",
		INDEX_GETTING_STARTED4 : "Efter pluginet installerats spelar du OGame som vanligt, du kommer att se ett litet fönster så fort data skickas till ditt Galaxverktyg.",
		INDEX_GETTING_STARTED5 : "När pluginet skickat data till ditt Galaxverktyg kan du börja analysera informationen, till exempel var spelare har sina kolonier, hur många kolonier en spelare har, titta på rapporter eller när spelare är mest aktiva.",
		INDEX_GETTING_STARTED6 : "Men det kommer också att hjälpa dig att analysera hur du utvecklas i jämförelse med dina konkurrenter eller genom att analysera dina krigsrapporter för att se hur mycket du plundrade under de senaste dagarna eller veckorna.",
		INDEX_GETTING_WIKIPAGE : "Det finns många fler funktioner i Galaxverktyget.",
		INDEX_GETTING_WIKIPAGE2 : "Läs mer om dem på vår wiki.",
		INDEX_GETTING_BOARD : "För feedback eller idéer kan du använda vårt forum:",
		INDEX_GETTING_CHAT1 : "Eller besök oss på chatten:",
		INDEX_GETTING_CHAT2 : "Vi är inte online 24/7, så ha tålamod.",
		INDEX_CLOSE : "Close",
		INDEX_LOGIN : "Login",
		GENERAL_REQUIRED_FIELDS : "Please fill all required fields",
		INDEX_MESSAGES : "Messages",
		INDEX_EXAMPLE : "Example",
		INDEX_INVALID_DATA : "Invalid data",
		GENERAL_COLUMN_HIDE_TITLE : "Manage columns",
		GENERAL_COLUMN_HIDE_INFO : "Please select which columns you want to see in the table.",
		GENERAL_ENTRIES_DELETED : "&1 entries deleted",
		GENERAL_APPLY : "Tillämpa",
		STARTPAGE_GALAXYTOOL_DESCR : "<em>Galaxytool</em> is a tool for the browser game OGame.",
		GENERAL_OVERWRITE : "Overwrite duplicate entry",
		GENERAL_OVERWRITE_QUESTION : "Overwrite?",
		INDEX_OWN_LOGINS : "Your logins",
		GENERAL_OPEN_IN_NEW_WINDOW : "Öppna länk i nytt fönster",
		GENERAL_UNIT_OF_MEASURE_DAYS : "Days",
		PROGRAM_NAME : "OGame Galaxverktyg",
		SHORTNAME : "Galaxverktyg",
		BACK_INDEX : "Tillbaka till huvudsidan",
		UNIVERSE : "Universum",
		MENU_INFO_LINKS : "Information",
		MENU_PAGE : "Översikt",
		MENU_DB_SEARCH : "Sök i databasen",
		MENU_DB_NOTICES : "Sök i notiser",
		MENU_DB_REPORTS : "Sök i rapporter",
		MENU_GALAXYVIEW : "Titta på galaxen",
		MENU_STATISTICS : "Statistik",
		MENU_ALLYHISTORY : "Allianshistoria",
		MENU_FLEET_MOVEMENTS : "Flottrörelser",
		MENU_COMBAT_REPORTS : "Krigsrapporter",
		MENU_MESSAGES : "Spelarmeddelanden",
		MENU_OPTION_LINKS : "Inställningar",
		MENU_DB_REFRESH : "Lägg till i databasen",
		MENU_NOTICES : "Notiser",
		MENU_DB_STATUS : "Status för Databasen",
		MENU_USEROPTIONS : "Hantera användare",
		MENU_USEROPTIONS2 : "Användarinställningar",
		MENU_USEROPTIONS3 : "Användarinformation",
		MENU_ADMIN : "Administration",
		MENU_LOGOUT : "Logout",
		MENU_STUFF : "Övrigt",
		MENU_FORUM_THREAD : "Utvecklarforum",
		MENU_DOWNLOADPAGE : "Nedladdningssida",
		MENU_LANGUAGE : "Språk",
		MENU_HELP : "Hjälp",
		MENU_TOOLOPTIONS : "Inställningar för Galaxverktyget",
		PARSER_INFO1 : " blev inlagd i databasen",
		PARSER_ERROR1 : "Fel vid försök att införa följande koordinater:",
		PARSER_ERROR2 : "Kan inte hitta databasen!",
		PARSER_ERROR3 : "Kan inte hitta databasservern!",
		PARSER_WRONG_UNIVERSE : "Fel Universum - Aktuell: \"&1\" förväntad: \"&2\"",
		SHOW_TITLE : "OGame Galaxverktyg - Söksida",
		SHOW_SEARCH : "Sök i databasen",
		SHOW_ALLYSYMBOL : "Allianstag",
		SHOW_PLAYERNAME : "Spelarnamn",
		SHOW_MOONS : "Endast planeter med måne",
		SHOW_NOTICES : "Endast planeter med notiser",
		SHOW_COLONIES : "Endast platser lediga för kolonisering",
		SHOW_YES : "Ja",
		SHOW_NO : "Nej",
		SHOW_SEARCHRANGE : "Spann",
		SHOW_SEARCH_IN : "Sök i galax",
		SHOW_FROM_SYSTEM : "Från system",
		SHOW_FROM_PLANET : "Från planetposition",
		SHOW_TO : "till",
		SHOW_DESCRIPTION : "Du kan använda wildcards * för spelare och alliansnamn så att du kan hitta alla spelare med &quot;namn&quot; i sitt namn.<br />Fyll endast i de fält du vill söka i.",
		SHOW_SORT_BY : "Sortera efter",
		SHOW_GALASYSTEM : "Galax/System",
		SHOW_ALLYNAME : "Alliansnamn",
		SHOW_SEARCHBUTTON : "Sök",
		SHOW_ADDRESS : "Koordinater",
		SHOW_ALLYSORT : "Allians",
		SHOW_PLANET : "Planetnamn",
		SHOW_STATUS : "Status",
		SHOW_CURRENTNESS : "Senast Uppdaterad",
		SHOW_PLAYER_STATUS : "Spelarstatus",
		SHOW_PLAYER_STATUS1 : "Alla",
		SHOW_PLAYER_STATUS2 : "Möjliga mål",
		SHOW_PLAYER_STATUS3 : "Inaktiva",
		SHOW_HITS : "Träffar",
		SHOW_OF : "Av",
		SHOW_ASC : "Stigande",
		SHOW_DESC : "Fallande",
		SHOW_RESULTS : "Träffar per sida",
		SHOW_MOON : "Måne",
		SHOW_UKMOONSIZE : "Okänd",
		SHOW_DF : "VF",
		SHOW_DF_LONG : "Vrakfält",
		SHOW_METAL : "M",
		SHOW_METAL_LONG : "Metall",
		SHOW_CRYSTAL : "K",
		SHOW_CRYSTAL_LONG : "Kristall",
		SHOW_BOTH : "Båda tillsammans",
		SHOW_AT_LEAST : "(Minst)",
		SHOW_DATE : "Datum",
		SHOW_DATE_0 : "ignorera",
		SHOW_DATE_1 : "äldre än",
		SHOW_DATE_2 : "nyare än",
		SHOW_RANK : "Rank",
		SHOW_FRANK : "Flottrank",
		SHOW_MEMBERS : "Medlemmar",
		SHOW_NOTRANKED : "Inte bland de första 1500.",
		SHOW_NOTICERES : "Notiser",
		SHOW_REPORTS : "Endast planeter med rapporter",
		SHOW_REPORTS_SHORT : "Rapporter",
		SHOW_NOTHING : "Hittade inga poster",
		SHOW_ALLIANCE_STATUS : "Alliansstatus",
		SHOW_NO_STATUS : "ingen Status",
		SHOW_NAP : "NAP",
		SHOW_ALLIED : "Allierad",
		SHOW_WAR : "Krig",
		SHOW_BOYCOTT : "Bojkott",
		SHOW_NEUTRAL : "Neutral",
		SHOW_OWN : "Egen Allians",
		SHOW_WING : "Vinge",
		SHOW_EXT_OPTIONS1 : "Visa fler sökalternativ för spann, rank, datum eller vrakfältssökning.",
		SHOW_EXT_OPTIONS2 : "Visa fler sökalternativ för kolonier, månar, rapporter, notiser, spelarstatus eller diplomatisk status.",
		SHOW_EXT_OPTIONS3 : "Visa fler sökalternativ för sortering av sökresultat.",
		SHOW_EXTENDED : "advanced search",
		SHOW_MOON_SELECTION : "Planet with moon",
		SHOW_REPORT_SELECTION : "Planet with report",
		SHOW_FILTER_BY : "Exclude from the list",
		SHOW_FILTER_NONE : "inga",
		SHOW_PLAYERS_WITHOUT_PROGRESS : "Show players without score changes within the last few days",
		STATUS_TITLE : "OGame Galaxverktyg - Statussida",
		STATUS_DB_STATUS : "Status för Databasen",
		STATUS_COLOR : "Färg",
		STATUS_AGE1 : "Post 1 dag gammal.",
		STATUS_AGE2 : "Post 2 - 4 dagar gammal.",
		STATUS_AGE3 : "Post 4 - 7 dagar gammal.",
		STATUS_AGE4 : "Post 1 - 2 veckor gammal.",
		STATUS_AGE5 : "Post 2 - 4 veckor gammal.",
		STATUS_AGE6 : "Post äldre än 1 månad!",
		STATUS_AGE7 : "Inga poster tillgängliga.",
		STATUS_ON : "den",
		STYLES_COLOR1 : "Färg1",
		STYLES_COLOR2 : "Färg2",
		STYLES_COLOR3 : "Färg3",
		STYLES_COLOR4 : "Färg4",
		STYLES_COLOR5 : "Färg5",
		STYLES_COLOR6 : "Färg6",
		STYLES_COLOR7 : "Färg7",
		STATUS_DB_LEGEND : "Förklaring",
		STATUS_GALAXY : "Galaxöversikt",
		USER_TITLE : "Hantering av användare",
		USER_NAMES : "Användare",
		USER_ERROR : "Fel",
		USER_NEWUSER : "Ny Användare",
		USER_OPTIONS : "Alternativ",
		USER_USERNAME : "Användarnamn",
		USER_PASSWORD : "Lösenord",
		USER_PASSWORD_CONFIRM : "Bekräfta Lösenord",
		USER_GALAXY : "Galax",
		USER_SEARCH : "Söka",
		USER_INSERT : "Lägga till",
		USER_DELETE : "Radera",
		USER_DELETE_ENTRY : "Vill du radera användaren? ",
		USER_STATUS : "Se statistik",
		USER_STYLES : "Modifiera layout",
		USER_SUBMIT : "Skicka in",
		USER_RESET : "Återställ",
		USER_YES : "Ja",
		USER_NO : "Nej",
		USER_STYLEPATH : "Sökväg till styles.css",
		USER_PROBES : "Se/Skicka in spionagerapporter",
		USER_EMAIL : "Email",
		USER_ERROR1 : "Fel lösenord eller ogiltig email.",
		USER_ERROR2 : "Ogiltig email.",
		USER_INGAME : "Spelarnamn",
		USER_ALLYTAG : "Allianstag",
		USER_ALLYHISTORY : "Se/Skicka in Allianshistoria",
		USER_DIPLOMATIC : "Ändra diplomatisk status",
		USER_STATSPAGE : "Antal rader på statistiksidan",
		USER_LINKS : "Länkar",
		USER_LINKS2 : "Format:<br>text;url<br>text2;url2<br>text3;url3",
		USER_EXPORT_TITLE : "Exportfärger (BB Koder)",
		USER_BB_COORDINATES : "Koordinater",
		USER_BB_MOON : "Måne",
		USER_BB_DEBRIS : "Vrakfält",
		USER_BB_ALLY : "Alliansnamn",
		USER_BB_ALLYDETAILS : "Alliansdetaljer",
		USER_BB_PLAYERNAME : "Spelarnamn",
		USER_BB_BANNED : "Bannad",
		USER_BB_VACATION : "Semesterläge",
		USER_BB_NOOB : "Nybörjare",
		USER_BB_INACTIVE : "Inaktiv",
		USER_BB_LONGINACTIVE : "Länge inaktiv",
		USER_DELETION : "Borttagning",
		USER_FLEETINFO : "Flottrörelser",
		USER_ACTIVITIES : "Spelar aktivitet",
		USER_MAINTENANCE : "Galaxverktyg underhåll",
		USER_MANAGEMENT : "Hantera användare",
		USER_DELETE_MY_COMBAT_REPORTS : "Radera mina krigsrapporter",
		USER_DELETE_MY_MESSAGES : "Radera mina meddelanden",
		USER_DELETE_MY_FLEETMOVES : "Radera mina flottrörelser",
		USER_DELETE_MY_COMBAT_REPORTS_LIMITED : "Radera mina krigsrapporter äldre än &1 dagar",
		USER_DELETE_MY_MESSAGES_LIMITED : "Radera mina meddelanden äldre än &1 dagar",
		USER_TABLE_ENTRIES : "Antalet sökresultat per sida",
		USER_EXISTS : "User already exists",
		USER_BB_OUTLAW : "Outlaw",
		USER_INVALID_URL : "URL &1 seems to be invalid - URL will be ignored",
		VIEW_TITLE : "OGame Galaxverktyg - Detaljer",
		VIEW_NODATA : "Ingen data tillgänglig.",
		VIEW_GALAXY : "Galax",
		VIEW_SYSTEM : "System",
		VIEW_POSITION : "Pos.",
		VIEW_PLANET : "Planet",
		VIEW_MOON : "Måne",
		VIEW_TF : "VF",
		VIEW_PLAYER : "Spelare",
		VIEW_PLAYER_ADD : "(Rank / Status)",
		VIEW_ALLY : "Allians",
		VIEW_ALLY_ADD : "(Rank / Medlem)",
		VIEW_METAL : "M",
		VIEW_CRYSTAL : "K",
		VIEW_COLONISED : "Befolkade planeter",
		VIEW_UKMOONSIZE : "okänd",
		VIEW_BACK : "tillbaka",
		VIEW_NOTICE : "Notiser",
		VIEW_REPORTS : "Rapporter",
		VIEW_MOONPHALANX : "Följande månar kan skanna det här systemet",
		VIEW_NOMOONS : "Inga månar med radarstation hittade",
		VIEW_IRAKS : "Följande planeter kan nå det här systemet med interplanetära missiler",
		VIEW_NOIRAKS : "Inga interplanetära missiler hittade",
		VIEW_MOON_DESTROY_CHANCE : "Chans att förstöra en måne",
		VIEW_CHANCE_WITH_ONE : "Chans med en dödsstjärna",
		VIEW_CHANCE_WITH_N : "Chans med ",
		VIEW_DEATH_STARS : "dödsstjärnor",
		VIEW_DS_DESTROY_CHANCE : "Chans att förlora dödsstjärnan(orna)",
		VIEW_TOP : "Topp",
		VIEW_GO : "Visa",
		VIEW_DIAMETER : "Diameter",
		PW_TITLE : "OGame Galaxverktyg - ändra lösenord",
		OLD_PASSWORD : "Gammalt lösenord",
		NEW_PASSWORD : "Nytt lösenord",
		CONFIRM_NEW_PASSWORD : "Bekräfta nytt lösenord",
		PW_MISMATCH : "Lösenorden matchade inte!",
		PW_ERROR : "Det gamla lösenordet var fel!",
		UPDATE_DONE : "Uppdatering lyckad.",
		TIMEZONE_OFFSET : "Tidsskillnad mot server",
		DELETE_ACCOUNT : "Radera kontot",
		DELETE_ACCOUNT_SAFETY_REQUEST : "Vill du verkligen radera kontot?",
		CH_PASSWD_AUTHORIZATION : "Rättigheter",
		CH_PASSWD_ADMIN : "Admin",
		TIMEZONE_OGAME_OFFSET : "Tidszonen är ställd mot OGame server",
		CH_PASSWD_USER_LANGUAGE : "Ändra språk efter inloggning",
		CH_PASSWD_USER_LANGUAGE_NO_CHANGE : "Ingen förändring",
		CH_PASSWD_EXPAND : "Expanderad",
		CH_PASSWD_COLLAPSE : "Komprimerad",
		CH_PASSWD_HIDDEN : "Gömd",
		CH_PASSWD_GETTING_STARTED : "Visa kom igång information efter inloggning",
		CH_PASSWD_PLUGIN : "Visa plugin information efter inloggning",
		NOTICE_TITLE : "OGame Galaxverktyg - Notiser",
		NOTICE_HEADER : "editera notis",
		NOTICE_HEADER2 : "Editera egna notiser",
		NOTICE_PUBLIC : "Tillgänglig för andra?",
		NOTICE_YES : "ja",
		NOTICE_NO : "nej",
		NOTICE_TEXT : "Notistext",
		NOTICE_SAVE : "Spara",
		NOTICE_DELETED : "Post raderad",
		NOTICE_SAVED : "Post sparad.",
		NOTICE_RESULTS : "Alla resultat",
		NOTICE_USER : "Användare",
		NOTICE_DATE : "Datum",
		NOTICE_EDIT : "Editera",
		NOTICE_DELETE : "Radera",
		NOTICE_NEW : "Skapa en egen post",
		NOTICE_NOTPUBLIC : "Notis ej publik.",
		NOTICE_ALL : "alla",
		NOTICE_NONE : "inga",
		NOTICE_SEARCH : "Sök i Notiser",
		NOTICE_SEARCH_SHORT : "Sök",
		NOTICE_HITS : "Träffar",
		NOTICE_SHOWRESULTS : "Träffar per sida",
		NOTICE_OF : "av",
		NOTICE_NOTHING : "Inga poster hittade",
		NOTICE_CHARS : "Tecken",
		NOTICE_PLAYERNAME : "Spelare",
		NOTICE_SHOWALL : "Visa alla notiser",
		REPORTS_TITLE : "OGame Galaxverktyg - Spionagerapporter",
		REPORTS_RESOURCES : "Resurser",
		REPORTS_FLEET : "Flottor",
		REPORTS_DEFENCE : "Försvar",
		REPORTS_BUILDINGS : "Byggnader",
		REPORTS_TECHNOLOGY : "Forskning",
		REPORTS_MOON : "Måne",
		REPORTS_SEARCH : "Sök i spionagerapporter",
		REPORTS_SEARCH_SHORT : "Sök",
		REPORTS_HITS : "Träffar",
		REPORTS_NOTHING : "Inga poster hittade",
		REPORTS_ADDRESS : "Adress",
		REPORTS_CURRENTNESS : "Aktuellhet",
		REPORTS_PLAYERNAME : "Spelarnamn",
		REPORTS_ALLY : "Allierad",
		REPORTS_VIEW : "Se Rapport",
		REPORTS_SEARCH_IN : "Sök i Galax",
		REPORTS_FROM_SYSTEM : "från System",
		REPORTS_TO : "till",
		REPORTS_DELETE : "Radera",
		REPORTS_DELETED : "Post raderad",
		REPORTS_RESULTS : "Träffar per sida",
		REPORTS_OF : "av",
		REPORTS_DATE : "Datum",
		REPORTS_DATE_0 : "Ignorera",
		REPORTS_DATE_1 : "Äldre än",
		REPORTS_DATE_2 : "Nyare än",
		REPORTS_NOTICES : "Notiser",
		REPORTS_AT_LEAST_RESOURCES : "Resurser (minst)",
		REPORTS_SEARCH_EXTENDED : "Utökad sökning",
		REPORTS_FLEET_RESIS : "Flottpoäng",
		REPORTS_DEFENCE_RESIS : "Försvarspoäng",
		REPORTS_ALL_RESIS : "Summerade poäng",
		REPORTS_TECHS : "Teknologier",
		REPORTS_UNKNOWN_ENTRIES : "Okända poster",
		REPORTS_PARTLY_INSERTED : "Delvis inlagd",
		REPORTS_FOR_ALL_RES : "för alla resurser",
		REPORTS_FOR_TF : "för vrakfältet",
		REPORTS_KT : "Små transportskepp",
		REPORTS_GT : "Stora transportskepp",
		REPORTS_SS : "Slagskepp",
		REPORTS_REC : "Återvinnare",
		REPORTS_RAIDABLE : "Endast raidbara mål",
		REPORTS_ALL_RESOURCES : "Alla resurser",
		REPORTS_STUFF : "Övrigt",
		REPORTS_SPEEDSIM : "Simulera med Speedsim",
		REPORTS_DRAGOSIM : "Simulera med Dragosim",
		REPORTS_STATUS : "Status",
		REPORTS_ERROR : "Ett fel har inträffat",
		REPORTS_OWN_REPORTS : "Endast mina rapporter",
		REPORTS_UPLOAD_BY : "Rapport upladdad av",
		REPORTS_DEPTH : "Rapportdjup",
		REPORTS_FLEET_SCORE : "Flottpoäng",
		REPORTS_DEFENCE_SCORE : "Försvarspoäng",
		REPORTS_HOURS : "hours",
		REPORTS_MAX_RESULTS_HIT : "Your query returned more than &1 hits. Only the first &1 results are show. Please adjust your search request to get less results.",
		REPORTS_OSIMULATE : "Simulate with OSimulate",
		REPORTS_SHOW_ONLY : "Show only",
		REPORTS_SHOW_PLANETS : "Planeter",
		REPORTS_SHOW_MOONS : "Månar",
		REPORTS_OWNER : "Reports owned by",
		STATS_TITLE : "OGame Galaxverktyg - Statistik",
		STATS_TBLHEAD : "Statistik",
		STATS_RANK : "Rank",
		STATS_PLAYERNAME : "Spelarnamn",
		STATS_ALLYNAME : "Allianstag",
		STATS_SCORE : "Poäng",
		STATS_FLEET : "Flotta",
		STATS_RESEARCH : "Forskning",
		STATS_MEMBERS : "Medlemmar",
		STATS_STATUS : "Status",
		STATS_NOTHING : "ingen Status",
		STATS_NAP : "NAP",
		STATS_ALLIED : "Allierad",
		STATS_WAR : "Krig",
		STATS_BOYCOTT : "Bojkott",
		STATS_NEUTRAL : "Neutral",
		STATS_OWN : "Egen Allians",
		STATS_WING : "Vinge",
		STATS_UPDATE : "Post från",
		STATS_PLAYERSTATS : "Spelarstatistik",
		STATS_ALLYSTATS : "Alliansstatistik",
		STATS_DELETE : "Vill du ta bort den här posten?",
		STATS_CONFIRM_DELETE : "Vill du verkligen radera den här spelarposten?",
		STATS_CHANGE_PLAYER_STATUS : "Spelarstatus",
		STATS_CHANGE_ALLIANCE_STATUS : "Alliansstatus",
		STATS_CHANGE_ALLIANCE_STATUS_HINT : "Alla medlemmar av den här alliansen får den valda statusen. Tidigare status kommer att skrivas över. Du kan ändra status på enskilda spelare i efterhand.",
		STATS_UNKNOWN : "Resten",
		STATS_DETAILS : "Detaljer för",
		STATS_PLAYERSTATUS : "Spelarstatus",
		STATS_IGNORE_STATUS : "Alla",
		STATS_ACTIVE : "Aktiva",
		STATS_INACTIVE : "Inaktiv",
		STATS_BANNED : "Bannad",
		STATS_VACATION : "Semesterläge",
		STATS_NOOB : "Nybörjare",
		STATS_YES : "Ja",
		STATS_NO : "Endast planeter med notiser",
		STATS_SEARCH : "Söka",
		STATS_SHOW_GRAPH : "Visa detaljer för poängfördelning",
		STATS_LONG_INACTIVE : "Länge inaktiv",
		STATS_STANDARD : "Standard Points",
		STATS_MILITARY : "Military Points",
		STATS_ECONOMY : "Economy",
		STATS_HONOUR : "Honour points",
		STATS_MILITARY_BUILD : "Military build",
		STATS_MILITARY_DESTROYED : "Military destroyed",
		STATS_MILITARY_LOST : "Military lost",
		REGISTER_REGISTRATE : "Registrera",
		REGISTER_LOGINNAME : "Inloggningsnamn",
		REGISTER_PASSWORD : "Lösenord",
		REGISTER_PASSWORD_CONFIRM : "Bekräfta Lösenord",
		REGISTER_EMAIL : "Email",
		REGISTER_INGAME : "Spelnamn",
		REGISTER_ALLYTAG : "Allianstag",
		REGISTER_EMAILVERIFICATION : "E-postkontroll",
		REGISTER_EMAILTEXT : "Vänligen klicka på länken för att bekräfta din registrering på Galaxverktyget.",
		REGISTER_ERROR1 : "Inloggningsnamn upptaget.",
		REGISTER_ERROR2 : "Fel vid försök att skicka e-post. Kontakta din administratör.",
		REGISTER_ERROR3 : "Fel vid försök att skicka data till databasen!",
		REGISTER_INFO1 : "Ditt konto är skapat.",
		REGISTER_INFO2 : "Vänligen klicka på länken i ditt email för att bekräfta registreringen.",
		REGISTER_INFO3 : "Konto bekräftat. Din admin måste bara aktivera det.",
		REGISTER_BUTTON : "Tillbaka till huvudsidan",
		REGISTER_NEW_SUBJECT : "En ny registrerad användare av Galaxverktyget",
		REGISTER_NEW_MAILTEXT : "En ny användare registrerade sig.",
		REGISTER_BACK : "Tillbaka till förstasidan",
		REGISTER_MISSING_FIELDS : "Fyll i alla begärda fält",
		REGISTER_ERROR4 : "E-postadress finns inte.",
		REGISTER_ERROR5 : "Lösenord matchar inte.",
		REGISTER_PWS : "Lösenordsstyrka",
		REGISTER_PWS0 : "Mycket svagt",
		REGISTER_PWS1 : "Svagt",
		REGISTER_PWS2 : "Bra",
		REGISTER_PWS3 : "Starkt",
		REGISTER_PWS4 : "Mycket starkt",
		REGISTER_EMAIL_USED : "Email Address is already used",
		LOSTPW_TITLE : "Glömt mitt Lösenord",
		LOSTPW_INFO2 : "Ett nytt lösenord har genererats och skickats till din emailadress.",
		LOSTPW_BUTTON1 : "Hämta nytt lösenord",
		LOSTPW_BUTTON2 : "Tillbaka till huvudsidan",
		LOSTPW_LOGINNAME : "Inloggningsnamn",
		LOSTPW_EMAIL : "Email",
		LOSTPW_ERROR1 : "Fel vid försök att skicka data till databasen!",
		LOSTPW_ERROR2 : "Ingen matchande post hittad!",
		LOSTPW_ERROR3 : "Fel vid försök att skicka ett email. Kontakta din admin.",
		LOSTPW_EMAIL_SUBJECT : "Det nya lösenordet du begärde",
		LOSTPW_EMAIL_TEXT1 : "Här är dina nya inloggningsuppgifter för Galaxverktyget",
		LOSTPW_EMAIL_TEXT2 : "Användarnamn",
		LOSTPW_EMAIL_TEXT3 : "Lösenord",
		LOSTPW_INFO1 : "You will receive an email to verify your password reset request.",
		LOSTPW_CONFIRM_RESET_SUBJECT : "Lost password?",
		LOSTPW_CONFIRM_RESET_MESSAGE : "Hello,\n\nyou requested a password reset for the Galaxytool. To generate a new password, click the following link:",
		USERINFO_TITLE : "OGame Galaxverktyg - Användarinformation",
		USERINFO_NAMES : "Alla användare av verktyget",
		USERINFO_DETAIL : "detaljerad information om",
		USERINFO_ERROR1 : "Ingen känd användare med detta ID!",
		USERINFO_USERNAME : "Inloggningsnamn",
		USERINFO_INGAME : "Spelarnamn",
		USERINFO_EMAIL : "Email",
		USERINFO_ALLYTAG : "Allians",
		USERINFO_STYLEPATH : "Tema",
		USERINFO_STATUS : "Status",
		USERINFO_ACTIVATE : "Aktivera Spelare",
		USERINFO_LOGINS : "Antal Inloggningar",
		USERINFO_LASTLOGIN : "Senaste Inloggning",
		USERINFO_DATA : "Information om inlagda system",
		USERINFO_NODATA : "Den användaren har inte lagt in några system än!",
		USERINFO_GALAXY : "Galax",
		USERINFO_SYSTEMS : "Antal System",
		USERINFO_IP : "IP-adress",
		USERINFO_LOGINTIME : "Loggade in",
		USERINFO_NOLOGIN : "Spelaren har aldrig loggat in.",
		USERINFO_LAST_GALAXYUPDATE : "Senast inlagda galaxvy",
		USERINFO_LAST_PUBLIC_NOTICE : "Senaste publika notis",
		USERINFO_LAST_PRIVATE_NOTICE : "Senaste privata notis",
		USERINFO_NUMBEROF_PUBLIC_NOTICE : "Antal publika notiser",
		USERINFO_NUMBEROF_PRIVATE_NOTICE : "Antal privata notiser",
		USERINFO_ACTIVATED : "Konto aktiverat",
		USERINFO_ACTIVATIONTEXT : "Galaxverktygets administratör har aktiverat ditt konto.\n\nHa det så kul med Galaxverktyget!",
		USERINFO_LAST_SUBMIT : "Senast inlagda uppgifter",
		ALLYHISTORY_TITLE : "OGame Galaxverktyg - Allianshistoria",
		ALLYHISTORY_TBLHEAD : "Historisk Översikt",
		ALLYHISTORY_PLAYERNAME : "Spelarnamn",
		ALLYHISTORY_ALLYNAME : "Allians",
		ALLYHISTORY_LASTMONTH : "Senaste månaden",
		ALLYHISTORY_ALL_DATA : "all tillgänglig information",
		ALLYHISTORY_SHOW : "Visa statistik",
		ALLYHISTORY_TIMESPAN : "Tidsperiod",
		ALLYHISTORY_PROGESS : "Framsteg",
		ALLYHISTORY_SCORE : "Poäng",
		ALLYHISTORY_FSCORE : "Flottpoäng",
		ALLYHISTORY_RSCORE : "Forskningspoäng",
		ALLYHISTORY_MEMBER : "Medlemmar",
		ALLYHISTORY_NOTHING : "no entries found",
		ALLYHISTORY_DETAILS : "Detaljer",
		ALLYHISTORY_SHOW_ADDRESS : "Koordinater",
		ALLYHISTORY_ESCORE : "Economy",
		ALLYHISTORY_MSCORE : "Military Points",
		DETAILEDINFO_PLAYERINFO_TITLE : "Spelarinformation",
		DETAILEDINFO_ALLYINFO_TITLE : "Alliansinformation",
		DETAILEDINFO_PLAYERINFO_TBLHEAD : "Detaljerad information om spelare",
		DETAILEDINFO_ALLYINFO_TBLHEAD : "Detaljerad information om allians",
		DETAILEDINFO_NO_ALLIANCE : "ingen",
		DETAILEDINFO_SCORE : "Poängstatistik",
		DETAILEDINFO_FLEET : "Flottstatistik",
		DETAILEDINFO_RESEARCH : "Forskningsstatistik",
		DETAILEDINFO_RANK : "Rank",
		DETAILEDINFO_POINTS : "Poäng",
		DETAILEDINFO_KNOWN_PLANETS : "Kända planeter",
		DETAILEDINFO_MOONS : "Kända månar",
		DETAILEDINFO_PHALANX_AREA : "Radarstations-area",
		DETAILEDINFO_NO_PHALANX_AREA : "ingen Radarstation hittad",
		DETAILEDINFO_NOTICES : "Notiser",
		DETAILEDINFO_NO_NOTICES : "Inga Notiser hittade",
		DETAILEDINFO_PREVIOUS_ALLIANCES : "Tidigare Allianser",
		DETAILEDINFO_RESOURCES_PER_HOUR : "Resurser per timme",
		DETAILEDINFO_RESOURCES_PER_DAY : "Resurser per dag",
		DETAILEDINFO_RESOURCES_PER_WEEK : "Resurser per vecka",
		DETAILEDINFO_RESOURCES_PER_MONTH : "Resurser per månad (30 dagar)",
		DETAILEDINFO_METAL : "Metall",
		DETAILEDINFO_CRYSTAL : "Kristall",
		DETAILEDINFO_DEUTERIUM : "Deuterium",
		DETAILEDINFO_UNKNOWN : "okänd",
		DETAILEDINFO_SCORE_DISTRIBUTION : "Poängfördelning",
		DETAILEDINFO_GENERAL : "Detaljer",
		DETAILEDINFO_MEMBERS : "Medlemmar",
		DETAILEDINFO_GRAPHS : "Grafer",
		DETAILEDINFO_RESOURCES : "Resurser",
		DETAILEDINFO_FLEET_TAB : "Flotta",
		DETAILEDINFO_TECH : "Forskning",
		DETAILEDINFO_FLEET_DETAIL : "Total flotta i alla rapporter",
		DETAILEDINFO_TECH_DETAIL : "Känd forskning",
		DETAILEDINFO_PLANET_TAB : "Planeter",
		DETAILEDINFO_MOON_TAB : "Månar",
		DETAILEDINFO_ACTIVITIES : "Aktiverades",
		DETAILEDINFO_NODATA : "Ingen data tillgänglig.",
		DETAILEDINFO_ACTIVITY_DESCRIPTION : "Visa aktivitet av &1 mottagna från:",
		DETAILEDINFO_GALAXYVIEWS : "Galaxvy",
		DETAILEDINFO_SCANS : "Fientlig spionaktivitet",
		DETAILEDINFO_MESSAGES : "Spelarmedelande",
		DETAILEDINFO_COMBATS : "Krigsrapport",
		DETAILEDINFO_ALLYPAGE : "Alians överblick",
		DETAILEDINFO_MANUAL : "Manuella inställningar",
		DETAILEDINFO_START : "Början",
		DETAILEDINFO_TO : "Till",
		DETAILEDINFO_TODAY : "Idag",
		DETAILEDINFO_DATA_RESTRICTION : "Begränsad till",
		DETAILEDINFO_WEEKDAY_WEEKEND : "Helgen",
		DETAILEDINFO_WEEKDAY_WORKINGDAY : "Vardag",
		DETAILEDINFO_WEEKDAY_MONDAY : "Måndag",
		DETAILEDINFO_WEEKDAY_TUESDAY : "Tisdag",
		DETAILEDINFO_WEEKDAY_WEDNESDAY : "Onsdag",
		DETAILEDINFO_WEEKDAY_THURSDAY : "Torsdag",
		DETAILEDINFO_WEEKDAY_FRIDAY : "Fredag",
		DETAILEDINFO_WEEKDAY_SATURDAY : "Lördag",
		DETAILEDINFO_WEEKDAY_SUNDAY : "Söndag",
		DETAILEDINFO_WEEKDAY_SHORTLENGTH : 3,
		DETAILEDINFO_PLAYER_CURRENTLY_ACTIVE : "Spelaren är nu aktiv",
		DETAILEDINFO_PLAYER_MESSAGES : "Tillgängliga spelarmeddelanden",
		DETAILEDINFO_SHOW : "Visa",
		DETAILEDINFO_NONE : "Inga tillgängliga",
		DETAILEDINFO_ENTER_MANUALLY : "Skriv in aktiviteter för den här spelaren manuellt",
		DETAILEDINFO_PLAYER_SEEN_ON : "Spelaren är aktiv",
		DETAILEDINFO_INSERT : "Infoga",
		DETAILEDINFO_OGAME_SERVERTIMES : "Snälla notera: Alla tider och datum refereras till OGame servertid!",
		DETAILEDINFO_DAY_VIEW : "24h visning",
		DETAILEDINFO_WEEK_VIEW : "Veckovis",
		DETAILEDINFO_HOME_PLANET : "Hemplanet",
		DETAILEDINFO_PLANETNAME : "Name",
		DETAILEDINFO_DEFENCE_SCORE : "Defence score",
		DETAILEDINFO_DEFENCE_SCORE_TOOLTIP : "Defence score = Fleet - Score + Research + Economy.<br/>All those statistics must be up to date to have a meaningful result!",
		DETAILEDINFO_SCORE_PER_SHIP : "Scores per ship",
		DETAILEDINFO_SHIPS : "Number of ships",
		DETAILEDINFO_DATE_IN_FUTURE : "Do not maintain times which are not in the past.",
		ADMIN_TITLE : "Administrera Galaxytool",
		ADMIN_DISCLAMER : "Observera: Kör dessa scripts på egen risk! De flesta av dem raderar data.",
		ADMIN_INCONSISTENCIES : "Fel i databasen",
		ADMIN_PLANETS : "Planeter på position 0 eller högre än 15",
		ADMIN_GALAXIES : "Radera galaxer högre än &1 ",
		ADMIN_PLAYERS : "Radera spelare utan OGame användarid - leder till dubletter",
		ADMIN_REPORTS : "Radera rapporter där planeten saknas",
		ADMIN_MISC : "Övrigt",
		ADMIN_RESET : "Nollställ Galaxytool (Endast användar och IP behålls)",
		ADMIN_OLD_PLAYERS : "Radera spelarrapporter äldre än &1 dagar",
		ADMIN_OLD_REPORTS : "Radera rapporter äldre än &1 dagar",
		ADMIN_LOADING : "Stäng inte detta fönster medans sidan laddas.",
		ADMIN_STATUS : "Status för dina order",
		ADMIN_SELECTION : "Minst en uppgift måste väljas",
		ADMIN_SAFETY : "Är du säker att du vill köra dessa script(s) ?",
		ADMIN_DONE : "Klar",
		ADMIN_NOTBD : "Inget att utföra",
		ADMIN_OLD_GALAXIES : "Ta bort galaxvyar äldre än &1 dagar",
		ADMIN_UNUSED_PLAYERS : "Radera spelare som inte förekommer i någon galaxvy",
		ADMIN_OLD_ACTIVITIES : "Radera spelaraktiviter som är äldre än &1 dag(ar)",
		ADMIN_OLD_COMBATS : "Radera krigsrapporter äldre än &1 dagar",
		ADMIN_OLD_INGAME_MSG : "Radera spelarmeddelanden äldre än &1 dagar",
		ADMIN_OGAME_API : "Load public data from OGame into the Galaxytool",
		ADMIN_OGAME_ALL_DATA : "all tillgänglig information",
		ADMIN_OGAME_GALAXY_DATA : "Titta på galaxen",
		ADMIN_OGAME_STATISTICS_DATA : "Statistik",
		ERRORPAGE_PAGEFORWARD : "Klicka här om din webläsare inte stödjer vidarebefordring",
		ERRORPAGE_PERMISSION_DENIED : "Du har inte tillstånd att gå in på denna sidan. Klicka för att gå tillbaka.",
		FLEETS_TITLE : "OGame Galaxytool – Flottrörelser",
		FLEETS_ACTUAL_FLEETS : "Nuvarande flottrörelser",
		FLEETS_YES : "Ja",
		FLEETS_NO : "Endast planeter med notiser",
		FLEETS_DETAILS : "Antal skepp",
		FLEETS_MISSION_EXPEDITION : "Expeditions uppdrag",
		FLEETS_MISSION_COLONIZATION : "Kolonisera",
		FLEETS_MISSION_RECYCLE : "Återvinna",
		FLEETS_MISSION_TRANSPORT : "Transportera",
		FLEETS_MISSION_DEPLOYMENT : "Utplacera",
		FLEETS_MISSION_ESPIONAGE : "Spionera",
		FLEETS_MISSION_ACS_DEFEND : "ACS Försvara",
		FLEETS_MISSION_ATTACK : "Attackera",
		FLEETS_MISSION_ACS_ATTACK : "ACS Attack",
		FLEETS_MISSION_MOON_DESTRUCTION : "Månförstörelse",
		FLEETS_MISSION_MISSILE_ATTACK : "Misil Attack",
		FLEETS_NO_DATA : "Ingen tillgänglig data hittades",
		FLEETS_FLEET : "Fleet",
		FLEETS_ALL_FLEETS : "Show all fleet movements",
		COMBAT_REPORT_OUDATED_GALAXYVIEW : "Galaxyvyns data är för gammal var god uppdatera källans kordinater och målets kordinater!",
		MESSAGES_TITLE : "OGame Galaxytool - OGame Meddelanden",
		MESSAGES_PLAYERNAME : "Spelar namn",
		MESSAGES_SUBJECT : "Ämne",
		MESSAGES_DATE : "Datum",
		MESSAGES_FILTER : "Filter",
		MESSAGES_DELETE : "Raderade medelanden",
		MESSAGES_PUBLISH_DETAIL : "Publicera meddelandet genom att lägga till meddelandets innehåll i spelarens notis.",
		MESSAGES_PUBLISH_HEADER : "&sender har skickat ett meddelande till &recipient på &date:\n\n &message",
		MESSAGES_PLAYER_FILTER : "Meddelanden från spelare:",
		MESSAGES_CONTENT : "Content",
		COMBATS_TITLE : "OGame Galaxytool - Krigsrapport",
		COMBATS_ATTACKER : "Attakerande spelare",
		COMBATS_DEFENDER : "Försvarare",
		COMBATS_DATE : "Datum",
		COMBATS_OWNER : "Ägare",
		COMBATS_WINNER : "Vinnare",
		COMBATS_COMBATREPORT : "Krigsrapport",
		COMBATS_COMBAT_AT : "Attakerad på",
		COMBATS_LOST_UNITS : "Förlorade enheter",
		COMBATS_LOOT : "Byte",
		COMBATS_DEBRIS : "Vrakfält",
		COMBATS_AND : "och",
		COMBATS_PUBLISH : "Publisera denna rapport",
		COMBATS_UNPUBLISH : "Gör rapporten privat.",
		COMBATS_DELETE : "Raderad rapport",
		COMBATS_CHECK_ALL : "markera alla",
		COMBATS_UNCHECK_ALL : "avmarkera alla",
		COMBATS_WITH_SELECTED : "Valt slag",
		COMBATS_PUBLIC_REPORTS : "Offentlig rapport",
		COMBATS_YES : "Ja",
		COMBATS_NO : "Endast planeter med notiser",
		COMBATS_SEARCH_OPTIONS : "Sök inställningar",
		COMBATS_SEARCH : "Gå",
		COMBATS_RESET : "Återställ",
		COMBATS_COORDINATES : "Koordinater",
		COMBATS_INVALID_GALAXY_ENTERED : "Ogiltig Galax",
		COMBATS_INVALID_SYSTEM_ENTERED : "Ogiltigt System",
		COMBATS_INVALID_PLANET_ENTERED : "Ogiltig Planet",
		COMBATS_GALAXY_FROM_TO : "Galax",
		COMBATS_SYSTEM_FROM_TO : "System",
		COMBATS_PLANET_FROM_TO : "Planet",
		COMBATS_APPLY : "Tillämpa",
		COMBATS_COMBAT_SUMMARY : "Sammanfattning av krigsrapport",
		COMBATS_DOWNLOAD_CSV : "Ladda ned krigsrapport som CSV fil",
		REPORT_ARCHIVE_TITLE : "Rapportarkiv",
		REPORT_ARCHIVE_COORDINATES : "Koordinater",
		REPORT_ARCHIVE_SCANTIME : "Scannad klockan",
		REPORT_ARCHIVE_DELETE : "Radera dessa poster",
		REPORT_ARCHIVE_CONFIRM_DELETE : "Vill du verkligen radera dessa poster?",
		REPORT_ARCHIVE_GALAXY : "Galax",
		REPORT_ARCHIVE_SYSTEM : "System",
		REPORT_ARCHIVE_PLANET : "Planet",
		REPORT_ARCHIVE_MOON : "Måne",
		REPORT_ARCHIVE_DETAILS : "Detaljer",
		REPORT_ARCHIVE_RESOURCES : "Resurser per timme",
		REPORT_ARCHIVE_HEADER_RESOURCES : "Resurser",
		REPORT_ARCHIVE_DETAILS_FOR : "Rapportarkiv för &1 [&2] (&3)",
		REPORT_ARCHIVE_FLEET_CARGO : "Flottans lastkapacitet",
		REPORT_ARCHIVE_IRAK_RANGE : "Räckvidd för interplanetära missiler",
		REPORT_ARCHIVE_CHART_TYPE : "Tabelltyp",
		INSTALL_TITLE : "Galaxytool installation for version",
		INSTALL_PROGRESS : "Overall progress",
		INSTALL_STEP : "Step",
		INSTALL_CONTINUE : "Continue",
		INSTALL_VALIDATE : "Validate",
		INSTALL_STEP1 : "Welcome",
		INSTALL_STEP2 : "Writeable check",
		INSTALL_STEP3 : "Database settings",
		INSTALL_STEP4 : "OGame settings",
		INSTALL_STEP5 : "Galaxytool settings",
		INSTALL_STEP6 : "Admin password",
		INSTALL_STEP7 : "Install Galaxytool",
		INSTALL_STEP8 : "Finalize install",
		INSTALL_FILE_DELETE_CHECK : "Please delete install.php and update.php from your webserver.",
		INSTALL_STEP1_PHP_FAILED : "Your PHP version &1 is not working with this Galaxytool version",
		INSTALL_STEP1_FOPEN_FAILED : "Your PHP version does not allow to open webpages with FOPEN() command. This is required to consume the OGame API.",
		INSTALL_STEP1_WELCOME : "Welcome to the installation wizard of the Galaxytool. You will be guided through the installation of the Galaxytool.",
		INSTALL_STEP2_DESCRIPTION : "Make sure your config.php and attributes.php files have write permissions enabled.",
		INSTALL_STEP2_DESCRIPTION2 : "If you don't know, how to achieve this, please take a look here: &1",
		INSTALL_STEP2_FILE_NOT_WRITEABLE : "File is not writeable",
		INSTALL_STEP3_SERVER : "Database server",
		INSTALL_STEP3_USERNAME : "Användarnamn",
		INSTALL_STEP3_PASSWORD : "Lösenord",
		INSTALL_STEP3_DBNAME : "Database name",
		INSTALL_STEP3_PREFIX : "Tablename prefix",
		INSTALL_STEP3_ENTER_PREFIX : "E.g. mytool_",
		INSTALL_STEP3_ENTER_SERVER : "Enter the server address. Contact your system admin if necessary. Usually the correct value is localhost.",
		INSTALL_STEP3_ENTER_USERNAME : "Enter the username for database access",
		INSTALL_STEP3_ENTER_PASSWORD : "Enter the password for database access",
		INSTALL_STEP3_ENTER_DBNAME : "Enter the database name which shall be used for installation (must exist)",
		INSTALL_STEP3_CONNECT_FAILED : "Could not establish connection to database server",
		INSTALL_STEP3_DB_FAILED : "Database &1 not found",
		INSTALL_STEP3_MYSQL_VERSION_FAILED : "MySQL version &1 is not working with this Galaxytool version",
		INSTALL_STEP4_URL : "OGame URL",
		OGAME_URL_DETAILS : "Please enter any URL you see when you are logged on to OGame. Based on that URL the tool will derive the OGame API address which can be used to fill data into the Galaxytool without the Galaxytoolbar. This API was introduced with OGame version 4.1.",
		INSTALL_STEP4_UNIVERSE : "OGame Universe",
		INSTALL_STEP4_DEF_TO_DEBRIS : "Defense to debris",
		INSTALL_STEP4_DEBRIS_RATE : "Debris rate",
		INSTALL_STEP4_SPEED_RATE : "Speed rate",
		INSTALL_STEP4_ENTER_UNIVERSE : "Enter your OGame universe name or number (case sensitive).",
		INSTALL_STEP4_UNIVERSE_MISSING : "You must define your universe",
		INSTALL_STEP4_ENTER_URL : "Enter your OGame universe address",
		INSTALL_STEP4_URL_MISSING : "You must define your OGame address",
		INSTALL_STEP4_URL_CHECK_FAILED : "Could not find OGame API at &1",
		INSTALL_STEP4_GETSETTINGS : "Fetch settings",
		INSTALL_STEP5_TOOLNAME : "Galaxytool name",
		INSTALL_STEP5_ENTER_TOOLNAME : "This is the name which will be shown at logon page to identify your Galaxytool",
		INSTALL_STEP5_LANGUAGE : "Default language",
		INSTALL_STEP5_EMAIL_TO : "Email To",
		INSTALL_STEP5_ENTER_EMAIL_TO : "Enter the email address where you would like to receive notifications about registrations",
		INSTALL_STEP5_EMAIL_FROM : "Email From",
		INSTALL_STEP5_ENTER_EMAIL_FROM : "This email address is shown as REPLY for all mails sent from the Galaxytool",
		INSTALL_STEP5_USE_PHPMAILER : "Use PHPMailer",
		INSTALL_STEP5_MAXSHOUTS : "Maximum number of shoutbox entries",
		INSTALL_STEP5_ENTER_USE_PHPMAILER : "Use PHPMailer if your server does not support sending emails by default",
		INSTALL_PHPMAILER_HOST : "SMPT Host",
		INSTALL_PHPMAILER_HOST_EXAMPLE : "e.g. smtp.provider.com",
		INSTALL_PHPMAILER_USER : "SMPT Username",
		INSTALL_PHPMAILER_USER_EXAMPLE : "e.g. user@provider.dcom",
		INSTALL_PHPMAILER_PASS : "SMPT password",
		INSTALL_PHPMAILER_SECURE : "Authentification method (e.g. ssl)",
		INSTALL_PHPMAILER_PORT : "SMTP Port",
		INSTALL_STEP6_INTRO : "Please define a password for the <strong>admin</strong> account which you have to use for your first logon to the Galaxytool after the installation.",
		INSTALL_STEP7_CONFIG : "Configuration file created",
		INSTALL_STEP7_CONFIG_FAILED : "Configuration file not created",
		INSTALL_STEP7_ATTRIBUTES : "Attributes file created",
		INSTALL_STEP7_ATTRIBUTES_FAILED : "Attributes file not created",
		INSTALL_STEP7_CREATED_TABLES : "Database tables created",
		INSTALL_STEP8_INTRO : "You have successfully installed the Galaxytool!",
		INSTALL_STEP8_LOAD_DATA : "Downloading OGame data ...",
		INSTALL_STEP8_LOAD_DATA_FINISHED : "Download of OGame data finished",
		INSTALL_STEP8_DELETE_FILE : "You should now delete the installation files install.php and update.php from your webserver.",
		INSTALL_STEP8_LOGON : "Please logon with the <strong>admin</strong> user and the password you defined earlier.",
		UPDATE_START : "Starting update to version &1",
		UPDATE_STEP_DONE : "Done",
		UPDATE_TITLE : "Galaxytool update for version",
		UPDATE_STEP1_WELCOME : "Welcome to the update wizard of the Galaxytool. You will be guided through the update of the Galaxytool.",
		UPDATE_STEP1_BACKUP_FILES : "As a first step, make a backup of your <strong>config</strong> folder! You will have to replace the configuration content in case of errors.",
		UPDATE_STEP1_BACKUP_DB : "Then make a <a href=\"http://www.ehow.com/how_2036600_create-database-php.html\">backup</a> of your database.",
		UPDATE_STEP1_PROCEED : "Once the backups have been done, you can proceed with your update.",
		UPDATE_STEP1 : "Welcome",
		UPDATE_STEP2 : "Galaxytool settings",
		UPDATE_STEP2_OLD_VERSION : "Previous Galaxytool version",
		UPDATE_STEP3 : "Update Galaxytool",
		UPDATE_STEP3_UPDATE_RUNNING : "Update running, please wait...",
		UPDATE_STEP4 : "Finalize Update",
		UPDATE_STEP4_INTRO : "You have successfully updated the Galaxytool!",
		UPDATE_STEP4_UPDATE_DONE : "Update steps performed.",
		UPDATE_FAILED : "Update failed.",
		GALAXYTOOL_DUMMY_TEXT : "dummy"
	})
);