define(
	({
		REPORT_WHEN : "정보:",
		RESOURCES_ON : "의 자원",
		PLAYER_BANNED : "b",
		PLAYER_VACATION_MODE : "v",
		PLAYER_NOOB : "n",
		PLAYER_INACTIVE : "i",
		PLAYER_LONG_INACTIVE : "I",
		PLAYER_OUTLAW : "o",
		L_USERNAME : "아이디",
		L_PASSWORD : "비밀번호",
		L_LOGINFAILURE : "아이디 또는 비밀번호가 틀리거나 등록하신 아이디가 아직 활성화 되지 않았습니다.",
		L_TOKENFAILURE : "인증 키가 틀렸거나 당신의 계정이 활성화되지 않았습니다.",
		L_LOGINTEXT : "로그인 해주세요.",
		L_LANGUAGE : "언어 선택:",
		L_TIMEOUT : "세션 유효시간이 경과했습니다!",
		L_REGISTER : "가입하기",
		L_PWLOST : "비밀번호 분실",
		INDEX_TITLE : "개요",
		INDEX_INFO : "정보",
		INDEX_ENTRIES : "등록된 총 행성계",
		INDEX_ENTRIES_LASTWEEK : "지난주에 새로 등록된 행성계",
		INDEX_ENTRIES_TO_OLD : "등록된지 한달 이상 된 행성계",
		INDEX_REGISTERED_USERS : "등록한 유저",
		INDEX_PAGEFORWARD : "브라우저가 페이지 변환을 지원하지 않을 경우, 여기를 클릭 하세요.",
		INDEX_NOTICES : "메모",
		INDEX_PLAYERS : "유저 통계",
		INDEX_ALLIES : "동맹 통계",
		INDEX_REPORTS : "정탐 보고서",
		INDEX_VERSION : "다운로드 가능한 최신 버전",
		INDEX_LATEST_VERSION : "새 버전 없음",
		INDEX_SHOUTBOX : "외침",
		INDEX_NOENTRY : "외침 없음",
		INDEX_COMMENT : "새 외침",
		INDEX_INSERT : "외치기",
		INDEX_UMOD : "휴가 모드인 유저",
		INDEX_NO_MOONS : "달",
		INDEX_NO_EMPTY_SYSTEMS : "아무도 없는 행성계",
		INDEX_NO_FULL_SYSTEMS : "빈 자리가 없는 행성계",
		INDEX_NO_TARGETS : "공격 가능한 목표",
		INDEX_USERINFO : "접속자 현황",
		INDEX_ONLINE : "현재 접속중",
		INDEX_TODAY : "오늘 접속함",
		INDEX_ALL : "총 로그인 수",
		GENERAL_LOAD_FORM : "검색 양식 불러오기",
		GENERAL_SAVE_FORM : "검색 양식 저장",
		GENERAL_SAVE_AS_TEXT : "다른 이름으로 저장",
		GENERAL_SAVE : "저장",
		INDEX_USERMANAGEMENT : "활동 내역",
		INDEX_NEEDADMIN : "계정 잠금 해제",
		INDEX_NEEDEMAIL : "확인되지 않은 계정",
		INDEX_TOOLBAR_INFO : "겔툴 플러그인 정보",
		INDEX_TOOLBAR_URL : "겔툴 URL",
		INDEX_TOOLBAR_VERSION_REQUIRED : "최신 겔럭시툴바 버전.",
		INDEX_TOOLBAR_INSTALL_GUIDE : "플러그인에 대한 설치 방법",
		INDEX_TOOLBAR_TOKEN : "인증 키",
		INDEX_TOOLBAR_NEW_TOKEN : "새로운 인증 키",
		INDEX_PLAYERS_WITH_N_PLANETS : "&1 개 이상 행성을 가진 플레이어 조회",
		INDEX_GETTING_STARTED : "겔럭시툴 시작하기",
		INDEX_GETTING_STARTED1 : "겔럭시툴에 오신 것을 환영합니다!",
		INDEX_GETTING_STARTED2 : "겔럭시 툴은 &1 은하에서 일어난 일을 분석하는데 도움을 줄 것입니다.",
		INDEX_GETTING_STARTED3 : "분석을 위해서 정보를 입력해야 하며, 입력을 위해  Firefox 용 플러그인 &1 이 필요합니다.",
		INDEX_GETTING_STARTED4 : "플러그인을 설치 후, 당신은 평소와 같이 오게임 페이지를 탐색하면 작은 윈도우창이 보이며 겔럭시툴로 정보가 보내집니다.",
		INDEX_GETTING_STARTED5 : "갤럭시툴에 자료를 입력하면, 플레이어의 행성 좌표나 갯수, 행성의 정보나 가장 많이 활동한 시간대를 분석할 수 있습니다.",
		INDEX_GETTING_STARTED6 : "뿐만 아니라, 당신의 경쟁자와 당신을 비교하고, 과거의 전투기록을 토대로 당신의 발전 방향을 분석하는데 도움을 줄 것입니다",
		INDEX_GETTING_WIKIPAGE : "겔럭시툴은 이외에도 더 많은 기능이 있습니다.",
		INDEX_GETTING_WIKIPAGE2 : "위키백과를 참고해 보세요.",
		INDEX_GETTING_BOARD : "불편사항이나 새로운 아이디어가 있으면 게시판을 통해 알려주세요.:",
		INDEX_GETTING_CHAT1 : "또는 우리의 대화방을 이용하실 수도 있습니다.:",
		INDEX_GETTING_CHAT2 : "저희가 자릴 비울 경우도 있겠지만, 최대한의 빠른 답변을 드리겠습니다.",
		INDEX_CLOSE : "닫기",
		INDEX_LOGIN : "로그인",
		GENERAL_REQUIRED_FIELDS : "모든 필수 입력란을 모두 채우세요.",
		INDEX_MESSAGES : "메시지",
		INDEX_EXAMPLE : "예",
		INDEX_INVALID_DATA : "잘못된 데이터",
		GENERAL_COLUMN_HIDE_TITLE : "칼럼 관리",
		GENERAL_COLUMN_HIDE_INFO : "테이블에 표시할 열을 선택합니다.",
		GENERAL_ENTRIES_DELETED : "&1 항목이 삭제됩니다.",
		GENERAL_APPLY : "허가",
		STARTPAGE_GALAXYTOOL_DESCR : "<em>겔럭시툴</em> 은 웹게임 오게임을 위한 툴입니다.",
		GENERAL_OVERWRITE : "항목을 중복 덮어쓰기",
		GENERAL_OVERWRITE_QUESTION : "덮어쓰시겠습니까?",
		INDEX_OWN_LOGINS : "귀하의 로그인 횟수",
		GENERAL_OPEN_IN_NEW_WINDOW : "새 창에 링크 열기",
		GENERAL_UNIT_OF_MEASURE_DAYS : "Days",
		PROGRAM_NAME : "오게임 은하 도구",
		SHORTNAME : "은하 도구",
		BACK_INDEX : "초기 화면으로",
		UNIVERSE : "우주",
		MENU_INFO_LINKS : "정보",
		MENU_PAGE : "통계",
		MENU_DB_SEARCH : "DB 검색",
		MENU_DB_NOTICES : "메모 검색",
		MENU_DB_REPORTS : "보고서 검색",
		MENU_GALAXYVIEW : "은하",
		MENU_STATISTICS : "순위",
		MENU_ALLYHISTORY : "동맹 기록",
		MENU_FLEET_MOVEMENTS : "함대 현황",
		MENU_COMBAT_REPORTS : "전투 보고서",
		MENU_MESSAGES : "받은 메시지",
		MENU_OPTION_LINKS : "옵션",
		MENU_DB_REFRESH : "DB 추가",
		MENU_NOTICES : "메모",
		MENU_DB_STATUS : "DB 상태",
		MENU_USEROPTIONS : "유저 관리",
		MENU_USEROPTIONS2 : "유저 옵션",
		MENU_USEROPTIONS3 : "유저 정보",
		MENU_ADMIN : "관리자",
		MENU_LOGOUT : "로그아웃",
		MENU_STUFF : "기타",
		MENU_FORUM_THREAD : "개발자 포럼",
		MENU_DOWNLOADPAGE : "다운로드",
		MENU_LANGUAGE : "언어",
		MENU_HELP : "도움말",
		MENU_TOOLOPTIONS : "은하 도구 옵션",
		PARSER_INFO1 : " 가 DB에 입력되었습니다.",
		PARSER_ERROR1 : "다음 좌표를 입력 중에 오류 발생:",
		PARSER_ERROR2 : "DB를 찾을 수 없습니다!",
		PARSER_ERROR3 : "DB 서버를 찾을 수 없습니다!",
		PARSER_WRONG_UNIVERSE : "잘못된 은하 설정 - 현재: \"&1\" 설정된 은하: \"&2\"",
		SHOW_TITLE : "오게임 은하 도구 - 검색",
		SHOW_SEARCH : "DB 검색",
		SHOW_ALLYSYMBOL : "동맹 태그",
		SHOW_PLAYERNAME : "아이디",
		SHOW_MOONS : "달이 있는 행성만",
		SHOW_NOTICES : "메모가 있는 행성만",
		SHOW_COLONIES : "이민 할 수 있는 행성만",
		SHOW_YES : "예",
		SHOW_NO : "아니요",
		SHOW_SEARCHRANGE : "사정거리",
		SHOW_SEARCH_IN : "은하 검색",
		SHOW_FROM_SYSTEM : "행성계",
		SHOW_FROM_PLANET : "행성번호",
		SHOW_TO : "부터",
		SHOW_DESCRIPTION : "아이디나 동맹태그에서 와일드카드 * 를 사용 할 수 있습니다. 따라서 &quot;name&quot;이 아이디에 포함된 모든 유저를 찾을 수 있습니다.<br/>정확히 원하는 정보만 채우세요.",
		SHOW_SORT_BY : "정렬 방법",
		SHOW_GALASYSTEM : "은하/행성계",
		SHOW_ALLYNAME : "동맹 이름",
		SHOW_SEARCHBUTTON : "찾기",
		SHOW_ADDRESS : "좌표",
		SHOW_ALLYSORT : "동맹",
		SHOW_PLANET : "행성 이름",
		SHOW_STATUS : "상태",
		SHOW_CURRENTNESS : "마지막 수정",
		SHOW_PLAYER_STATUS : "유저 상태",
		SHOW_PLAYER_STATUS1 : "모두",
		SHOW_PLAYER_STATUS2 : "공격 가능",
		SHOW_PLAYER_STATUS3 : "비접속",
		SHOW_HITS : "결과수",
		SHOW_OF : "/",
		SHOW_ASC : "오름차순",
		SHOW_DESC : "내림차순",
		SHOW_RESULTS : "페이지당 표시",
		SHOW_MOON : "달",
		SHOW_UKMOONSIZE : "알 수 없음",
		SHOW_DF : "파편",
		SHOW_DF_LONG : "파편지대",
		SHOW_METAL : "M",
		SHOW_METAL_LONG : "메탈",
		SHOW_CRYSTAL : "C",
		SHOW_CRYSTAL_LONG : "크리스탈",
		SHOW_BOTH : "메탈+크리스탈",
		SHOW_AT_LEAST : "(최소)",
		SHOW_DATE : "날짜",
		SHOW_DATE_0 : "신경 안씀",
		SHOW_DATE_1 : "다음 날짜 이전의",
		SHOW_DATE_2 : "다음 날짜 이후의",
		SHOW_RANK : "순위",
		SHOW_FRANK : "함대 순위",
		SHOW_MEMBERS : "회원",
		SHOW_NOTRANKED : "상위1500위에 없음",
		SHOW_NOTICERES : "메모",
		SHOW_REPORTS : "메모가 있는 행성만",
		SHOW_REPORTS_SHORT : "보고서",
		SHOW_NOTHING : "검색 결과 없음",
		SHOW_ALLIANCE_STATUS : "동맹 상태",
		SHOW_NO_STATUS : "상태 없음",
		SHOW_NAP : "불가침",
		SHOW_ALLIED : "동맹",
		SHOW_WAR : "전쟁중",
		SHOW_BOYCOTT : "배척",
		SHOW_NEUTRAL : "중립",
		SHOW_OWN : "자치 동맹",
		SHOW_WING : "우군",
		SHOW_EXT_OPTIONS1 : "세부 검색 옵션, 범위, 순위, 날짜 또는 파편 필드를 참조를 표시합니다.",
		SHOW_EXT_OPTIONS2 : "추가 검색 옵션 식민지, 달, 보고서, 메모, 플레이어 상태 또는 외교 상태를 표시합니다.",
		SHOW_EXT_OPTIONS3 : "검색 결과 정렬에 대한 더 많은 옵션을 표시합니다.",
		SHOW_EXTENDED : "고급 검색",
		SHOW_MOON_SELECTION : "달이 있는 행성",
		SHOW_REPORT_SELECTION : "보고서가 있는 행성",
		SHOW_FILTER_BY : "목록에서 제외",
		SHOW_FILTER_NONE : "모두 비선택",
		SHOW_PLAYERS_WITHOUT_PROGRESS : "Show players without score changes within the last few days",
		STATUS_TITLE : "오게임 은하 도구 - 상태",
		STATUS_DB_STATUS : "DB 상태",
		STATUS_COLOR : "색깔",
		STATUS_AGE1 : "1 일 경과",
		STATUS_AGE2 : "2 - 4 일 경과",
		STATUS_AGE3 : "4 - 7 일 경과",
		STATUS_AGE4 : "1 - 2 주 경과",
		STATUS_AGE5 : "2 - 4 주 경과",
		STATUS_AGE6 : "1 달 이상 경과!",
		STATUS_AGE7 : "정보 없음",
		STATUS_ON : "가<br>",
		STYLES_COLOR1 : "색깔1",
		STYLES_COLOR2 : "색깔2",
		STYLES_COLOR3 : "색깔3",
		STYLES_COLOR4 : "색깔4",
		STYLES_COLOR5 : "색깔5",
		STYLES_COLOR6 : "색깔6",
		STYLES_COLOR7 : "색깔7",
		STATUS_DB_LEGEND : "DB 범례",
		STATUS_GALAXY : "은하계 개요",
		USER_TITLE : "유저 관리",
		USER_NAMES : "유저",
		USER_ERROR : "오류",
		USER_NEWUSER : "새 유저",
		USER_OPTIONS : "옵션",
		USER_USERNAME : "아이디",
		USER_PASSWORD : "비밀번호",
		USER_PASSWORD_CONFIRM : "비밀번호 확인",
		USER_GALAXY : "은하",
		USER_SEARCH : "검색",
		USER_INSERT : "추가",
		USER_DELETE : "삭제",
		USER_DELETE_ENTRY : "삭제하시겠습니까: ",
		USER_STATUS : "상태 보기",
		USER_STYLES : "구성 변경",
		USER_SUBMIT : "확인",
		USER_RESET : "초기화",
		USER_YES : "예",
		USER_NO : "아니요",
		USER_STYLEPATH : "styles.css 경로",
		USER_PROBES : "정탐 보고서 보기/추가",
		USER_EMAIL : "이메일",
		USER_ERROR1 : "비밀번호 또는 이메일 오류",
		USER_ERROR2 : "이메일 오류",
		USER_INGAME : "게임 아이디",
		USER_ALLYTAG : "동맹 태그",
		USER_ALLYHISTORY : "동맹 정보 보기/추가",
		USER_DIPLOMATIC : "외교 상태 변경",
		USER_STATSPAGE : "통계에서 보여줄 항목 수",
		USER_LINKS : "링크",
		USER_LINKS2 : "방식:<br>내용;url<br>내용2;url2<br>내용3;url3",
		USER_EXPORT_TITLE : "색 내보내기 (BB 코드)",
		USER_BB_COORDINATES : "주소",
		USER_BB_MOON : "달",
		USER_BB_DEBRIS : "암석지대",
		USER_BB_ALLY : "동맹 이름",
		USER_BB_ALLYDETAILS : "동맹 설명",
		USER_BB_PLAYERNAME : "유저",
		USER_BB_BANNED : "밴",
		USER_BB_VACATION : "휴가 모드",
		USER_BB_NOOB : "뉴비",
		USER_BB_INACTIVE : "비접속",
		USER_BB_LONGINACTIVE : "장기 비접속",
		USER_DELETION : "삭제",
		USER_FLEETINFO : "확인된 밀집 함대",
		USER_ACTIVITIES : "유저 활성화",
		USER_MAINTENANCE : "겔럭시툴 유지 보수",
		USER_MANAGEMENT : "유저 관리",
		USER_DELETE_MY_COMBAT_REPORTS : "나의 전투기록 삭제",
		USER_DELETE_MY_MESSAGES : "나의 저장된 메시지 삭제",
		USER_DELETE_MY_FLEETMOVES : "나의 함대 현황 삭제",
		USER_DELETE_MY_COMBAT_REPORTS_LIMITED : "&1 일보다 오래된 내 전투 기록 삭제",
		USER_DELETE_MY_MESSAGES_LIMITED : "&1 일보다 오래된 내 메시지 삭제",
		USER_TABLE_ENTRIES : "각 페이지에 대한 검색 결과의 갯수",
		USER_EXISTS : "사용자가 이미 존재합니다.",
		USER_BB_OUTLAW : "뉴비해적",
		USER_INVALID_URL : "&1 URL은 잘못된 것입니다 - URL 은 무시됩니다.",
		VIEW_TITLE : "오게임 은하 도구 - 상세정보",
		VIEW_NODATA : "정보가 없습니다.",
		VIEW_GALAXY : "은하계",
		VIEW_SYSTEM : "시스템",
		VIEW_POSITION : "위치",
		VIEW_PLANET : "행성",
		VIEW_MOON : "달",
		VIEW_TF : "암석",
		VIEW_PLAYER : "유저",
		VIEW_PLAYER_ADD : "(순위/멤버)",
		VIEW_ALLY : "동맹",
		VIEW_ALLY_ADD : "(순위/멤버)",
		VIEW_METAL : "M",
		VIEW_CRYSTAL : "C",
		VIEW_COLONISED : " 개의 행성이 존재합니다.",
		VIEW_UKMOONSIZE : "알 수 없음",
		VIEW_BACK : "뒤로",
		VIEW_NOTICE : "메모",
		VIEW_REPORTS : "보고서",
		VIEW_MOONPHALANX : "이 행성계를 탐색할 수 있는 달",
		VIEW_NOMOONS : "검색된 달 없음",
		VIEW_IRAKS : "이 행성계가 IPM 사정거리에 있는 행성",
		VIEW_NOIRAKS : "검색된 IPM 없음",
		VIEW_MOON_DESTROY_CHANCE : "달 파괴 확율",
		VIEW_CHANCE_WITH_ONE : "죽음의 별 1기로 가능한 확율",
		VIEW_CHANCE_WITH_N : "죽음의 별 ",
		VIEW_DEATH_STARS : "기로 가능한 확율",
		VIEW_DS_DESTROY_CHANCE : "죽음의 별이 파괴될 확율",
		VIEW_TOP : "순위 제한",
		VIEW_GO : "보기",
		VIEW_DIAMETER : "지름",
		PW_TITLE : "오게임 은하 도구 - 비밀번호 변경",
		OLD_PASSWORD : "기존 비밀번호",
		NEW_PASSWORD : "새 비밀번호",
		CONFIRM_NEW_PASSWORD : "새 비밀번호 확인",
		PW_MISMATCH : "비밀번호가 일치하지 않습니다!",
		PW_ERROR : "기존 비밀번호가 틀립니다!",
		UPDATE_DONE : "변경 완료",
		TIMEZONE_OFFSET : "시간대를 서버에 맞춤",
		DELETE_ACCOUNT : "이 겔럭시툴 계정을 삭제",
		DELETE_ACCOUNT_SAFETY_REQUEST : "당신의 겔럭시툴을 삭제하시겠습니가?",
		CH_PASSWD_AUTHORIZATION : "승인",
		CH_PASSWD_ADMIN : "운영자",
		TIMEZONE_OGAME_OFFSET : "시간대를 오게임 서버에 맞춤",
		CH_PASSWD_USER_LANGUAGE : "이 언어로 다음부터 로그온",
		CH_PASSWD_USER_LANGUAGE_NO_CHANGE : "바꾸지않기",
		CH_PASSWD_EXPAND : "항상 보기",
		CH_PASSWD_COLLAPSE : "접어놓기",
		CH_PASSWD_HIDDEN : "메뉴 숨김",
		CH_PASSWD_GETTING_STARTED : "로그인 후 시작정보 보기",
		CH_PASSWD_PLUGIN : "로그인 후 플러그인 메뉴보기",
		NOTICE_TITLE : "오게임 은하 도구 - 메모",
		NOTICE_HEADER : "메모 수정",
		NOTICE_HEADER2 : "개인 메모 수정",
		NOTICE_PUBLIC : "공개?",
		NOTICE_YES : "예",
		NOTICE_NO : "아니요",
		NOTICE_TEXT : "메모",
		NOTICE_SAVE : "저장",
		NOTICE_DELETED : "삭제 완료",
		NOTICE_SAVED : "저장 완료",
		NOTICE_RESULTS : "모든 결과",
		NOTICE_USER : "유저",
		NOTICE_DATE : "날짜",
		NOTICE_EDIT : "수정",
		NOTICE_DELETE : "삭제",
		NOTICE_NEW : "새 메모 작성",
		NOTICE_NOTPUBLIC : "비공개 메모",
		NOTICE_ALL : "모두 선택",
		NOTICE_NONE : "모두 비선택",
		NOTICE_SEARCH : "메모에서 검색",
		NOTICE_SEARCH_SHORT : "검색",
		NOTICE_HITS : "결과수",
		NOTICE_SHOWRESULTS : "화면에 표시할 결과수",
		NOTICE_OF : "of",
		NOTICE_NOTHING : "검색 결과 없음",
		NOTICE_CHARS : "기호",
		NOTICE_PLAYERNAME : "유저",
		NOTICE_SHOWALL : "모두 보기",
		REPORTS_TITLE : "오게임 은하 도구 - 정찰 보고서",
		REPORTS_RESOURCES : "자원",
		REPORTS_FLEET : "함대",
		REPORTS_DEFENCE : "방어",
		REPORTS_BUILDINGS : "건물",
		REPORTS_TECHNOLOGY : "연구",
		REPORTS_MOON : "달",
		REPORTS_SEARCH : "정찰 보고서에서 검색",
		REPORTS_SEARCH_SHORT : "검색",
		REPORTS_HITS : "결과수 ",
		REPORTS_NOTHING : "검색 결과 없음",
		REPORTS_ADDRESS : "좌표",
		REPORTS_CURRENTNESS : "갱신된 날짜",
		REPORTS_PLAYERNAME : "아이디",
		REPORTS_ALLY : "동맹",
		REPORTS_VIEW : "보고서 보기",
		REPORTS_SEARCH_IN : "은하:행성계",
		REPORTS_FROM_SYSTEM : ":",
		REPORTS_TO : "부터",
		REPORTS_DELETE : "삭제",
		REPORTS_DELETED : "삭제 완료",
		REPORTS_RESULTS : "화면에 표시할 결과수",
		REPORTS_OF : "/",
		REPORTS_DATE : "보고서 등록일",
		REPORTS_DATE_0 : "신경 안씀",
		REPORTS_DATE_1 : "부터",
		REPORTS_DATE_2 : "까지",
		REPORTS_NOTICES : "메모",
		REPORTS_AT_LEAST_RESOURCES : "자원 (최소)",
		REPORTS_SEARCH_EXTENDED : "확장 검색",
		REPORTS_FLEET_RESIS : "함대",
		REPORTS_DEFENCE_RESIS : "방시",
		REPORTS_ALL_RESIS : "합계",
		REPORTS_TECHS : "무보장",
		REPORTS_UNKNOWN_ENTRIES : "알 수 없는 항목",
		REPORTS_PARTLY_INSERTED : "부분 입력",
		REPORTS_FOR_ALL_RES : "총 자원",
		REPORTS_FOR_TF : "파편 지대",
		REPORTS_KT : "소형 화물선",
		REPORTS_GT : "대형 화물선",
		REPORTS_SS : "순양함",
		REPORTS_REC : "수확선",
		REPORTS_RAIDABLE : "공격 가능한 행성만",
		REPORTS_ALL_RESOURCES : "모든 자원",
		REPORTS_STUFF : "기타",
		REPORTS_SPEEDSIM : "스피드심 돌리기",
		REPORTS_DRAGOSIM : "Dragosim",
		REPORTS_STATUS : "상태",
		REPORTS_ERROR : "오류 발생",
		REPORTS_OWN_REPORTS : "내 리포트",
		REPORTS_UPLOAD_BY : "정찰자",
		REPORTS_DEPTH : "상세한 리포트 ",
		REPORTS_FLEET_SCORE : "함대 스코어",
		REPORTS_DEFENCE_SCORE : "방어 점수",
		REPORTS_HOURS : "시간",
		REPORTS_MAX_RESULTS_HIT : "쿼리 & 1 이상의 조회수를 반환했습니다. 첫 번째 & 1의 결과에만 나타납니다. 다음과 같은 결과를 얻기 위해 검색 요청을 정렬하십시오.",
		REPORTS_OSIMULATE : "OSimulate 시뮬레이션",
		REPORTS_SHOW_ONLY : "이것만 표시",
		REPORTS_SHOW_PLANETS : "행성",
		REPORTS_SHOW_MOONS : "달",
		REPORTS_OWNER : "보고서 작성자",
		STATS_TITLE : "오게임 은하 도구 - 통계",
		STATS_TBLHEAD : "순위",
		STATS_RANK : "순위",
		STATS_PLAYERNAME : "아이디",
		STATS_ALLYNAME : "동맹 태그",
		STATS_SCORE : "점수",
		STATS_FLEET : "함대",
		STATS_RESEARCH : "연구",
		STATS_MEMBERS : "멤버",
		STATS_STATUS : "상태",
		STATS_NOTHING : "상태 없음",
		STATS_NAP : "뉴비",
		STATS_ALLIED : "동맹",
		STATS_WAR : "전쟁중",
		STATS_BOYCOTT : "배척",
		STATS_NEUTRAL : "중립",
		STATS_OWN : "자치 동맹",
		STATS_WING : "우군",
		STATS_UPDATE : "수정 날짜",
		STATS_PLAYERSTATS : "유저 통계",
		STATS_ALLYSTATS : "동맹 통계",
		STATS_DELETE : "이 항목을 지우겠습니까?",
		STATS_CONFIRM_DELETE : "이 유저를 지우겠습니까?",
		STATS_CHANGE_PLAYER_STATUS : "유저 상태",
		STATS_CHANGE_ALLIANCE_STATUS : "동맹 상태",
		STATS_CHANGE_ALLIANCE_STATUS_HINT : "이 동맹의 모든 동맹원의 상태가 변경됩니다. 기존의 상태는 지워집니다. 그 다음 개인의 상태를 변경하세요.",
		STATS_UNKNOWN : "정보 없음",
		STATS_DETAILS : "상세 정보",
		STATS_PLAYERSTATUS : "유저 상태",
		STATS_IGNORE_STATUS : "모두",
		STATS_ACTIVE : "활동",
		STATS_INACTIVE : "비접속",
		STATS_BANNED : "밴",
		STATS_VACATION : "휴가 모드",
		STATS_NOOB : "뉴비",
		STATS_YES : "예",
		STATS_NO : "메모가 있는 행성만",
		STATS_SEARCH : "검색",
		STATS_SHOW_GRAPH : "점수 분포의 세부 정보로 표시",
		STATS_LONG_INACTIVE : "장기 비접속",
		STATS_STANDARD : "표준 점수",
		STATS_MILITARY : "군사 점수",
		STATS_ECONOMY : "경제",
		STATS_HONOUR : "명예 점수",
		STATS_MILITARY_BUILD : "종합 군사 점수",
		STATS_MILITARY_DESTROYED : "군사 파괴 점수",
		STATS_MILITARY_LOST : "잃은 군사 점수",
		REGISTER_REGISTRATE : "가입하기",
		REGISTER_LOGINNAME : "아이디",
		REGISTER_PASSWORD : "비밀번호",
		REGISTER_PASSWORD_CONFIRM : "비밀번호 확인",
		REGISTER_EMAIL : "이메일",
		REGISTER_INGAME : "게임 아이디",
		REGISTER_ALLYTAG : "동맹태그",
		REGISTER_EMAILVERIFICATION : "이메일 확인",
		REGISTER_EMAILTEXT : "은하 도구 가입을 완료하려면 링크를 클릭 해주세요.",
		REGISTER_ERROR1 : "사용중인 아이디입니다.",
		REGISTER_ERROR2 : "이메일을 보내는 중 오류 발생. 관리자에게 연락하세요.",
		REGISTER_ERROR3 : "DB로 정보를 보내는 중 오류 발생!",
		REGISTER_INFO1 : "아이디가 생성되었습니다.",
		REGISTER_INFO2 : "가입을 완료하려면 이메일로 보내진 링크를 클릭 해주세요.",
		REGISTER_INFO3 : "관리자의 확인 후 가입이 완료 됩니다.",
		REGISTER_BUTTON : "초기화면으로",
		REGISTER_NEW_SUBJECT : "은하 도구에 새 사용자가 가입 했습니다.",
		REGISTER_NEW_MAILTEXT : "새 사용자가 가입했습니다. 확인 필요.",
		REGISTER_BACK : "첫페이지로 돌아가기",
		REGISTER_MISSING_FIELDS : "모든 정보를 기입해주세요.",
		REGISTER_ERROR4 : "Email 주소가 올바르지 않습니다.",
		REGISTER_ERROR5 : "비밀번호가 맞지 않습니다.",
		REGISTER_PWS : "비밀번호 안전성",
		REGISTER_PWS0 : "매우 쉬움",
		REGISTER_PWS1 : "쉬움",
		REGISTER_PWS2 : "보통",
		REGISTER_PWS3 : "안전함",
		REGISTER_PWS4 : "매우 안전함",
		REGISTER_EMAIL_USED : "이미 사용 중인 이메일입니다.",
		LOSTPW_TITLE : "비밀번호 분실",
		LOSTPW_INFO2 : "새 비밀번호를 생성하여 해당 이메일 주소로 전송되었습니다.",
		LOSTPW_BUTTON1 : "새 비밀번호 발급",
		LOSTPW_BUTTON2 : "초기화면으로",
		LOSTPW_LOGINNAME : "아이디",
		LOSTPW_EMAIL : "이메일",
		LOSTPW_ERROR1 : "DB로 정보를 보내는 중 오류 발생!",
		LOSTPW_ERROR2 : "일치된 정보를 찾을 수 없음!",
		LOSTPW_ERROR3 : "이메일을 보내는 중 오류 발생. 관리자에게 문의하세요.",
		LOSTPW_EMAIL_SUBJECT : "요청하신 새 비밀 번호입니다",
		LOSTPW_EMAIL_TEXT1 : "다음 정보로 은하 툴에 로그인 하세요",
		LOSTPW_EMAIL_TEXT2 : "아이디",
		LOSTPW_EMAIL_TEXT3 : "비밀번호",
		LOSTPW_INFO1 : "당신이 가입한 이메일 주소로 재설정된 비밀번호를 받으실 수 있습니다.",
		LOSTPW_CONFIRM_RESET_SUBJECT : "비밀번호을 잊으셨습니까?",
		LOSTPW_CONFIRM_RESET_MESSAGE : "안녕하세요,\n\n당신은 겔럭시툴에 대한 암호 재설정을 요청하였습니다. 새로운 암호를 생성하려면 다음 링크를 누르십시오:",
		USERINFO_TITLE : "오게임 은하 도구 - 유저 정보",
		USERINFO_NAMES : "등록된 모든 유저",
		USERINFO_DETAIL : "상세 정보",
		USERINFO_ERROR1 : "이 아이디를 가진 유저가 없습니다!",
		USERINFO_USERNAME : "아이디",
		USERINFO_INGAME : "게임 아이디",
		USERINFO_EMAIL : "이메일",
		USERINFO_ALLYTAG : "동맹",
		USERINFO_STYLEPATH : "스킨",
		USERINFO_STATUS : "상태",
		USERINFO_ACTIVATE : "계정 활성화",
		USERINFO_LOGINS : "로그인 수",
		USERINFO_LASTLOGIN : "마지막 로그인",
		USERINFO_DATA : "추가한 행성계에 대한 정보",
		USERINFO_NODATA : "아직 행성계를 추가 하지 않았습니다!",
		USERINFO_GALAXY : "은하",
		USERINFO_SYSTEMS : "등록 갯수",
		USERINFO_IP : "IP 주소",
		USERINFO_LOGINTIME : "로그인 시간",
		USERINFO_NOLOGIN : "로그인 한적이 없습니다.",
		USERINFO_LAST_GALAXYUPDATE : "마지막 은하 등록",
		USERINFO_LAST_PUBLIC_NOTICE : "마지막 공개 메모",
		USERINFO_LAST_PRIVATE_NOTICE : "마지막 비공개 메모",
		USERINFO_NUMBEROF_PUBLIC_NOTICE : "공개 메모 수",
		USERINFO_NUMBEROF_PRIVATE_NOTICE : "비공개 메모 수",
		USERINFO_ACTIVATED : "계정 활성화 완료",
		USERINFO_ACTIVATIONTEXT : "은하 도구 관리자가 당신의 계정을 활성화 했습니다.\n\n마음껏 사용하세요!",
		USERINFO_LAST_SUBMIT : "최근 등록일",
		ALLYHISTORY_TITLE : "오게임 은하 도구 - 동맹 기록",
		ALLYHISTORY_TBLHEAD : "전체 개요",
		ALLYHISTORY_PLAYERNAME : "유저",
		ALLYHISTORY_ALLYNAME : "동맹",
		ALLYHISTORY_LASTMONTH : "지난 달",
		ALLYHISTORY_ALL_DATA : "모든 정보",
		ALLYHISTORY_SHOW : "통계 보기",
		ALLYHISTORY_TIMESPAN : "기간",
		ALLYHISTORY_PROGESS : "변화",
		ALLYHISTORY_SCORE : "점수",
		ALLYHISTORY_FSCORE : "함대 점수",
		ALLYHISTORY_RSCORE : "연구 점수",
		ALLYHISTORY_MEMBER : "멤버",
		ALLYHISTORY_NOTHING : "검색 결과 없음",
		ALLYHISTORY_DETAILS : "상세 정보",
		ALLYHISTORY_SHOW_ADDRESS : "주소",
		ALLYHISTORY_ESCORE : "경제",
		ALLYHISTORY_MSCORE : "군사 점수",
		DETAILEDINFO_PLAYERINFO_TITLE : "유저 정보",
		DETAILEDINFO_ALLYINFO_TITLE : "동맹 정보",
		DETAILEDINFO_PLAYERINFO_TBLHEAD : "유저 상세 정보",
		DETAILEDINFO_ALLYINFO_TBLHEAD : "동맹 상세 정보",
		DETAILEDINFO_NO_ALLIANCE : "동맹 없음",
		DETAILEDINFO_SCORE : "점수 순위",
		DETAILEDINFO_FLEET : "함대 순위",
		DETAILEDINFO_RESEARCH : "연구 순위",
		DETAILEDINFO_RANK : "순위",
		DETAILEDINFO_POINTS : "점수",
		DETAILEDINFO_KNOWN_PLANETS : "알려진 행성",
		DETAILEDINFO_MOONS : "알려진 달",
		DETAILEDINFO_PHALANX_AREA : "밀집센서 지역",
		DETAILEDINFO_NO_PHALANX_AREA : "밀집센서 없음",
		DETAILEDINFO_NOTICES : "메모",
		DETAILEDINFO_NO_NOTICES : "메모 없음",
		DETAILEDINFO_PREVIOUS_ALLIANCES : "이전 동맹",
		DETAILEDINFO_RESOURCES_PER_HOUR : "시간당 자원",
		DETAILEDINFO_RESOURCES_PER_DAY : "일일 자원",
		DETAILEDINFO_RESOURCES_PER_WEEK : "한주 자원",
		DETAILEDINFO_RESOURCES_PER_MONTH : "한달 자원(30일)",
		DETAILEDINFO_METAL : "메탈",
		DETAILEDINFO_CRYSTAL : "크리스탈",
		DETAILEDINFO_DEUTERIUM : "듀테륨",
		DETAILEDINFO_UNKNOWN : "정보 없음",
		DETAILEDINFO_SCORE_DISTRIBUTION : "점수 분포",
		DETAILEDINFO_GENERAL : "세부사항",
		DETAILEDINFO_MEMBERS : "회원",
		DETAILEDINFO_GRAPHS : "그래프",
		DETAILEDINFO_RESOURCES : "자원",
		DETAILEDINFO_FLEET_TAB : "함대",
		DETAILEDINFO_TECH : "연구",
		DETAILEDINFO_FLEET_DETAIL : "합 / (유저 평균) 사용 가능한 모든 보고서",
		DETAILEDINFO_TECH_DETAIL : "사용 가능한 모든정보 중 플레이어의 평균에 해당",
		DETAILEDINFO_PLANET_TAB : "행성",
		DETAILEDINFO_MOON_TAB : "달",
		DETAILEDINFO_ACTIVITIES : "접률 현황",
		DETAILEDINFO_NODATA : "정보가 없습니다.",
		DETAILEDINFO_ACTIVITY_DESCRIPTION : "&1 의 활동 시간대 수집 기록:",
		DETAILEDINFO_GALAXYVIEWS : "겔럭시 보기",
		DETAILEDINFO_SCANS : "정찰 활동",
		DETAILEDINFO_MESSAGES : "유저 메시지",
		DETAILEDINFO_COMBATS : "전투 기록",
		DETAILEDINFO_ALLYPAGE : "동맹 개요",
		DETAILEDINFO_MANUAL : "수동 항목",
		DETAILEDINFO_START : "시작",
		DETAILEDINFO_TO : "부터",
		DETAILEDINFO_TODAY : "오늘",
		DETAILEDINFO_DATA_RESTRICTION : "까지:",
		DETAILEDINFO_WEEKDAY_WEEKEND : "주말",
		DETAILEDINFO_WEEKDAY_WORKINGDAY : "평일",
		DETAILEDINFO_WEEKDAY_MONDAY : "월",
		DETAILEDINFO_WEEKDAY_TUESDAY : "화",
		DETAILEDINFO_WEEKDAY_WEDNESDAY : "수",
		DETAILEDINFO_WEEKDAY_THURSDAY : "목",
		DETAILEDINFO_WEEKDAY_FRIDAY : "금",
		DETAILEDINFO_WEEKDAY_SATURDAY : "토",
		DETAILEDINFO_WEEKDAY_SUNDAY : "일",
		DETAILEDINFO_WEEKDAY_SHORTLENGTH : 3,
		DETAILEDINFO_PLAYER_CURRENTLY_ACTIVE : "현재 유저는 활동 중",
		DETAILEDINFO_PLAYER_MESSAGES : "유저 메시지",
		DETAILEDINFO_SHOW : "보기",
		DETAILEDINFO_NONE : "사용할 수 없음",
		DETAILEDINFO_ENTER_MANUALLY : "유저의 활동 시간을 입력하세요",
		DETAILEDINFO_PLAYER_SEEN_ON : "유저 활동 시간",
		DETAILEDINFO_INSERT : "기입",
		DETAILEDINFO_OGAME_SERVERTIMES : "참고 사항: 모든 날짜와 시간은 오게임 서버 시간으로 나타내시오.",
		DETAILEDINFO_DAY_VIEW : "24시간 활동",
		DETAILEDINFO_WEEK_VIEW : "주간 활동",
		DETAILEDINFO_HOME_PLANET : "본성",
		DETAILEDINFO_PLANETNAME : "이름",
		DETAILEDINFO_DEFENCE_SCORE : "방어시설 점수",
		DETAILEDINFO_DEFENCE_SCORE_TOOLTIP : "방어시설 점수 = 함대 - 점수 + 연구 + 경제.<br/>모든 통계가 최신이며, 유효한 정보가 포함되어야 합니다!",
		DETAILEDINFO_SCORE_PER_SHIP : "점수 / 함대",
		DETAILEDINFO_SHIPS : "함대의 수",
		DETAILEDINFO_DATE_IN_FUTURE : "과거에 존재하지 않는 시간을 유지하지 마십시오",
		ADMIN_TITLE : "겔럭시툴 관리",
		ADMIN_DISCLAMER : "주의 :이 스크립트를 실행하는 것의 위험은 사용자 본인이 감수해야 합니다. 이러한 스크립트의 대부분은 영구적으로 데이터를 삭제합니다!",
		ADMIN_INCONSISTENCIES : "데이터베이스에서의 데이터 불일치",
		ADMIN_PLANETS : "0이나 15번 이상의 행성을 삭제",
		ADMIN_GALAXIES : "&1보다 큰 겔럭시 삭제",
		ADMIN_PLAYERS : "플레이한 적 없는 플레이어 삭제 - 중복된 플레이어 항목 읽기",
		ADMIN_REPORTS : "존재하지 않는 행성의 보고서를 삭제",
		ADMIN_MISC : "여러가지 잡다한 항목 삭제",
		ADMIN_RESET : "겔럭시툴 초기화 (사용자와 ip table 은 삭제되지 않습니다)",
		ADMIN_OLD_PLAYERS : "&1 일 보다 오래된 플레이어를 삭제.",
		ADMIN_OLD_REPORTS : "&1 일 보다 오래된 보고서를 삭제.",
		ADMIN_LOADING : "페이지가 로드되는 동안 이 창을 닫지 마십시오.",
		ADMIN_STATUS : "당신의 요청 사항 확인",
		ADMIN_SELECTION : "하나 이상의 항목이 선택되어야 합니다.",
		ADMIN_SAFETY : "당신은 정말로 이 스크립트를 실행하시겠습니까?",
		ADMIN_DONE : "완료",
		ADMIN_NOTBD : "처리 할 것이 없습니다.",
		ADMIN_OLD_GALAXIES : "&1 일 보다 오래된 겔럭시를 삭제",
		ADMIN_UNUSED_PLAYERS : "겔럭시내 존재 하지 않는 플레이어 삭제",
		ADMIN_OLD_ACTIVITIES : "&1 일 보다 오래된 유저를 삭제(겔럭시툴유저)",
		ADMIN_OLD_COMBATS : "&1 일 보다 오래된 전투 보고서 삭제",
		ADMIN_OLD_INGAME_MSG : "&1 일 보다 오래된 게임내 메시지 삭제",
		ADMIN_OGAME_API : "겔럭시툴로 오게임의 공개 데이터를 로드합니다.",
		ADMIN_OGAME_ALL_DATA : "모든 정보",
		ADMIN_OGAME_GALAXY_DATA : "은하",
		ADMIN_OGAME_STATISTICS_DATA : "순위",
		ERRORPAGE_PAGEFORWARD : "브라우저가 페이지 변환을 지원 하지 않는 경우, 여기를 클릭하세요.",
		ERRORPAGE_PERMISSION_DENIED : "당신은 이 페이지를 접근할 권한이 없습니다. 클릭하면 뒤로 이동합니다.",
		FLEETS_TITLE : "오게임 겔럭시툴 - 함대 현황",
		FLEETS_ACTUAL_FLEETS : "현재 함대 현황",
		FLEETS_YES : "예",
		FLEETS_NO : "메모가 있는 행성만",
		FLEETS_DETAILS : "자세히",
		FLEETS_MISSION_EXPEDITION : "원정",
		FLEETS_MISSION_COLONIZATION : "식민지",
		FLEETS_MISSION_RECYCLE : "수확선",
		FLEETS_MISSION_TRANSPORT : "운송",
		FLEETS_MISSION_DEPLOYMENT : "배치",
		FLEETS_MISSION_ESPIONAGE : "정찰",
		FLEETS_MISSION_ACS_DEFEND : "ACS 방어",
		FLEETS_MISSION_ATTACK : "공격",
		FLEETS_MISSION_ACS_ATTACK : "ACS 공격",
		FLEETS_MISSION_MOON_DESTRUCTION : "달 파괴",
		FLEETS_MISSION_MISSILE_ATTACK : "미사일 공격",
		FLEETS_NO_DATA : "해당 데이터를 찾을 수 없습니다.",
		FLEETS_FLEET : "함대",
		FLEETS_ALL_FLEETS : "모든 함대의 움직임을 보이기",
		COMBAT_REPORT_OUDATED_GALAXYVIEW : "당신의 겔툴 정보가 오래 되었다. 전투가 이뤄진 좌표와 대상을 업데이트 하라!",
		MESSAGES_TITLE : "오게임 겔럭시툴 - 오게임 메시지",
		MESSAGES_PLAYERNAME : "플레이어 이름",
		MESSAGES_SUBJECT : "제목",
		MESSAGES_DATE : "날짜",
		MESSAGES_FILTER : "필터",
		MESSAGES_DELETE : "메시지 삭제",
		MESSAGES_PUBLISH_DETAIL : "플레이어의 주의사항을 추가하여 메시지를 공개",
		MESSAGES_PUBLISH_HEADER : "&sender 님이 &recipient 에게 메시지 보내기 &date:\n\n &message",
		MESSAGES_PLAYER_FILTER : "플레이어의 메시지:",
		MESSAGES_CONTENT : "내용",
		COMBATS_TITLE : "오게임 겔럭시툴 - 전투 보고서",
		COMBATS_ATTACKER : "공격자",
		COMBATS_DEFENDER : "방어자",
		COMBATS_DATE : "날짜",
		COMBATS_OWNER : "올린이",
		COMBATS_WINNER : "승리자",
		COMBATS_COMBATREPORT : "전투 보고서",
		COMBATS_COMBAT_AT : "전투에서",
		COMBATS_LOST_UNITS : "잃은 유닛수",
		COMBATS_LOOT : "약탈한 자원",
		COMBATS_DEBRIS : "잔해",
		COMBATS_AND : "과",
		COMBATS_PUBLISH : "보고서를 공개합니다.",
		COMBATS_UNPUBLISH : " 보고서 공유 취소 (비공개로 전환)",
		COMBATS_DELETE : "보고서 삭제",
		COMBATS_CHECK_ALL : "모두 선택",
		COMBATS_UNCHECK_ALL : "모두 선택 취소",
		COMBATS_WITH_SELECTED : "공유 설정",
		COMBATS_PUBLIC_REPORTS : "공개 보고서",
		COMBATS_YES : "예",
		COMBATS_NO : "메모가 있는 행성만",
		COMBATS_SEARCH_OPTIONS : "검색 옵션",
		COMBATS_SEARCH : "GO",
		COMBATS_RESET : "RESET",
		COMBATS_COORDINATES : "주소",
		COMBATS_INVALID_GALAXY_ENTERED : "잘못된 은하계 입력",
		COMBATS_INVALID_SYSTEM_ENTERED : "잘못된 시스텝 입력",
		COMBATS_INVALID_PLANET_ENTERED : "잘못된 행성 입력",
		COMBATS_GALAXY_FROM_TO : "은하계",
		COMBATS_SYSTEM_FROM_TO : "시스템",
		COMBATS_PLANET_FROM_TO : "행성",
		COMBATS_APPLY : "허가",
		COMBATS_COMBAT_SUMMARY : "전투 보고서 요약",
		COMBATS_DOWNLOAD_CSV : " CSV 파일로 다운받기",
		REPORT_ARCHIVE_TITLE : "보고서 보관함",
		REPORT_ARCHIVE_COORDINATES : "좌표",
		REPORT_ARCHIVE_SCANTIME : "정탐 시간",
		REPORT_ARCHIVE_DELETE : "이 항목 삭제",
		REPORT_ARCHIVE_CONFIRM_DELETE : "정말로 이 항목을 삭제하시겠습니까?",
		REPORT_ARCHIVE_GALAXY : "은하계",
		REPORT_ARCHIVE_SYSTEM : "시스템",
		REPORT_ARCHIVE_PLANET : "행성",
		REPORT_ARCHIVE_MOON : "달",
		REPORT_ARCHIVE_DETAILS : "자세히",
		REPORT_ARCHIVE_RESOURCES : "시간당 자원",
		REPORT_ARCHIVE_HEADER_RESOURCES : "자원",
		REPORT_ARCHIVE_DETAILS_FOR : "(&3)의  &1 행성 [&2]정탐 보관함  ",
		REPORT_ARCHIVE_FLEET_CARGO : "함대 화물 용량",
		REPORT_ARCHIVE_IRAK_RANGE : "IPM 미사일 범위",
		REPORT_ARCHIVE_CHART_TYPE : "도표 유형",
		INSTALL_TITLE : "Galaxytool 버전 설치",
		INSTALL_PROGRESS : "전체 진행",
		INSTALL_STEP : "단계",
		INSTALL_CONTINUE : "계속",
		INSTALL_VALIDATE : "인증",
		INSTALL_STEP1 : "환영합니다",
		INSTALL_STEP2 : "쓰기 검사",
		INSTALL_STEP3 : "데이터베이스 설정",
		INSTALL_STEP4 : "오게임 설정",
		INSTALL_STEP5 : "겔럭시툴 설정",
		INSTALL_STEP6 : "관리자 비밀번호",
		INSTALL_STEP7 : "겔럭시툴 설치",
		INSTALL_STEP8 : "설치 완료",
		INSTALL_FILE_DELETE_CHECK : "웹 서버의 install.php 와 update.php를 삭제하시기 바랍니다.",
		INSTALL_STEP1_PHP_FAILED : "귀하의 PHP &1 버전이 Galaxytool 버전에서 작동하지 않습니다.",
		INSTALL_STEP1_FOPEN_FAILED : "당신의 PHP 버전이 FONPEN() 명령을 사용하여 웹 페이지를 열 수 없습니다. 이것은 OGAME API가 필요합니다.",
		INSTALL_STEP1_WELCOME : "Galaxytool의 설치 마법사 시작, 당신에게 Galaxytool 설치에 대한 정보를 제공합니다.",
		INSTALL_STEP2_DESCRIPTION : "귀하의 config.php 및 attributes.php 파일은 쓰기 권한이 설정 되어 있는지 확인 하십시오.",
		INSTALL_STEP2_DESCRIPTION2 : "당신이 모르는 경우, 여기서 보고 해결해보세요: &1",
		INSTALL_STEP2_FILE_NOT_WRITEABLE : "파일을 쓰기 불가능합니다.",
		INSTALL_STEP3_SERVER : "데이터베이스 서버",
		INSTALL_STEP3_USERNAME : "아이디",
		INSTALL_STEP3_PASSWORD : "비밀번호",
		INSTALL_STEP3_DBNAME : "데이터베이스 이름",
		INSTALL_STEP3_PREFIX : "Tablename prefix",
		INSTALL_STEP3_ENTER_PREFIX : "예를 들어 mytool_",
		INSTALL_STEP3_ENTER_SERVER : "서버 주소를 입력하십시오. 필요에 따라 시스템 관리자에게 문의하십시오. 일반적으로 정상 값은 localhost입니다.",
		INSTALL_STEP3_ENTER_USERNAME : "데이터베이스 액세스에 사용 할 사용자 이름을 입력하십시오.",
		INSTALL_STEP3_ENTER_PASSWORD : "데이터베이스 액세스에 사용 할 사용자 암호를 입력하십시오.",
		INSTALL_STEP3_ENTER_DBNAME : "Enter the database name which shall be used for installation (must exist)",
		INSTALL_STEP3_CONNECT_FAILED : "데이터베이스 서버에 연결할 수 없습니다.",
		INSTALL_STEP3_DB_FAILED : "데이터베이스 &1을 찾을 수 없습니다.",
		INSTALL_STEP3_MYSQL_VERSION_FAILED : "MySQL version &1 이 겔럭시툴 버전에서 작동하지 않습니다.",
		INSTALL_STEP4_URL : "OGame의 URL",
		OGAME_URL_DETAILS : "당신 오게임 로그온했을 때 표시되는 URL을 입력합니다. 해당 URL을 바탕으로 오게임 API에서 겔럭시툴 정보를 검색합니다. 이것은 갤럭시 툴바 를 사용하지 않고 데이터베이스를 로드하는데 사용할 수 있습니다. 이 API는 오게임 4.1 버전부터 도입되었습니다.",
		INSTALL_STEP4_UNIVERSE : "OGame 은하",
		INSTALL_STEP4_DEF_TO_DEBRIS : "방어시설 데브리화",
		INSTALL_STEP4_DEBRIS_RATE : "데브리 비율",
		INSTALL_STEP4_SPEED_RATE : "서버 속도",
		INSTALL_STEP4_ENTER_UNIVERSE : "당신의 우주 이름(대소문자 구분) 또는 번호를 입력합니다.",
		INSTALL_STEP4_UNIVERSE_MISSING : "당신의 우주를 입력해야 합니다.",
		INSTALL_STEP4_ENTER_URL : "당신의 오게임 우주 URL을 입력하십시오.",
		INSTALL_STEP4_URL_MISSING : "오게임 URL를 입력해야 합니다.",
		INSTALL_STEP4_URL_CHECK_FAILED : "OGame API 를 찾을 수 없습니다. &1",
		INSTALL_STEP4_GETSETTINGS : "Fetch settings",
		INSTALL_STEP5_TOOLNAME : "겔럭시툴 이름",
		INSTALL_STEP5_ENTER_TOOLNAME : "이것은 겔럭시툴의 로그인 페이지에 표시되는 이름입니다.",
		INSTALL_STEP5_LANGUAGE : "기본 언어",
		INSTALL_STEP5_EMAIL_TO : "에게 이메일 보내기",
		INSTALL_STEP5_ENTER_EMAIL_TO : "당신의 등록에 대한 정보를 담은 메일을 수신할 이메일 주소를 입력하세요.",
		INSTALL_STEP5_EMAIL_FROM : "이메일의 보낸사람",
		INSTALL_STEP5_ENTER_EMAIL_FROM : "해당 이메일 주소가 Galaxytool에서 보내는 모든 메일들에 대한 회신메일로 표시됩니다",
		INSTALL_STEP5_USE_PHPMAILER : "PHPMailer 사용",
		INSTALL_STEP5_MAXSHOUTS : "외침박스 최대 항목 수",
		INSTALL_STEP5_ENTER_USE_PHPMAILER : "서버가 기본적으로 이메일을 보내기를 지원하지 않는 경우 PHPMailer를 사용하십시오.",
		INSTALL_PHPMAILER_HOST : "SMPT 호스트",
		INSTALL_PHPMAILER_HOST_EXAMPLE : "예: smtp.provider.com",
		INSTALL_PHPMAILER_USER : "SMPT 사용자명",
		INSTALL_PHPMAILER_USER_EXAMPLE : "예: user@provider.dcom",
		INSTALL_PHPMAILER_PASS : "SMPT 비밀번호",
		INSTALL_PHPMAILER_SECURE : "인증 방법 (예 : SSL)",
		INSTALL_PHPMAILER_PORT : "SMTP Port",
		INSTALL_STEP6_INTRO : "당신이 겔럭시툴을 설치한 후에 처음으로 로그온을 위해 사용해야하는 <strong>관리자<strong> 계정에 대한 암호를 설정하십시오.",
		INSTALL_STEP7_CONFIG : "Configuration 파일이 작성되었습니다.",
		INSTALL_STEP7_CONFIG_FAILED : "Configuration 파일을 만들 수 없습니다. ",
		INSTALL_STEP7_ATTRIBUTES : "Attributes 파일이 작성되었습니다.",
		INSTALL_STEP7_ATTRIBUTES_FAILED : "Attributes 파일을 만들 수 없습니다.",
		INSTALL_STEP7_CREATED_TABLES : "데이터베이스 테이블이 생성되었습니다.",
		INSTALL_STEP8_INTRO : "당신은 성공적으로 겔럭시툴을 설치하였습니다!",
		INSTALL_STEP8_LOAD_DATA : "오게임 데이터 다운로드 中...",
		INSTALL_STEP8_LOAD_DATA_FINISHED : "오게임 데이터 다운로드가 완료되었습니다.",
		INSTALL_STEP8_DELETE_FILE : "지금, 당신의 Web 서버에서 설치 파일 install.php와 update.php를 삭제해야합니다.",
		INSTALL_STEP8_LOGON : "<strong>admin</strong> 이전에 사용자가 설정한 비밀번호로 로그인하십시오.",
		UPDATE_START : "&1 버전 업데이트 시작",
		UPDATE_STEP_DONE : "완료",
		UPDATE_TITLE : "Galaxytool의 업데이트 버전",
		UPDATE_STEP1_WELCOME : "겔럭시툴 업데이트 마법사에 오신 것을 환영합니다. 당신은 겔럭시툴의 안내에 따라 업데이트를 진행하게 됩니다.",
		UPDATE_STEP1_BACKUP_FILES : "첫번째 단계로,당신의 <strong>config</strong> 폴더를 백업해야 합니다! 폴더 오류가 발생할 경우에 당신의 설정파일을 대체할 수 있 습니다.",
		UPDATE_STEP1_BACKUP_DB : "다음 데이터베이스의 백업은 <a href=\"http://www.ehow.com/how_2036600_create-database-php.html\">에서</a> 백업을 만들수 있습니다.",
		UPDATE_STEP1_PROCEED : "백업파일이 만들어 졌습니다. 업데이트를 진행할 수 있습니다.",
		UPDATE_STEP1 : "환영합니다",
		UPDATE_STEP2 : "겔럭시툴 설정",
		UPDATE_STEP2_OLD_VERSION : "겔럭시툴 구버전",
		UPDATE_STEP3 : "겔럭시툴을 업데이트",
		UPDATE_STEP3_UPDATE_RUNNING : "업데이트 진행 중, 잠시 기다려 주십시오...",
		UPDATE_STEP4 : "업데이트 완료",
		UPDATE_STEP4_INTRO : "겔럭시툴이 성공적으로 업데이트 되었습니다!",
		UPDATE_STEP4_UPDATE_DONE : "업데이트를 실행합니다.",
		UPDATE_FAILED : "업데이트가 실패하였습니다.",
		GALAXYTOOL_DUMMY_TEXT : "dummy"
	})
);