define(
	({
		REPORT_WHEN : "em",
		RESOURCES_ON : "Recursos em",
		PLAYER_BANNED : "b",
		PLAYER_VACATION_MODE : "m",
		PLAYER_NOOB : "f",
		PLAYER_INACTIVE : "i",
		PLAYER_LONG_INACTIVE : "I",
		PLAYER_OUTLAW : "o",
		L_USERNAME : "Utilizador",
		L_PASSWORD : "Senha",
		L_LOGINFAILURE : "Nome de Utilizador ou Senha incorrectos ou a conta ainda não foi activada.",
		L_TOKENFAILURE : "Palavra passe incorrecta ou a conta ainda não está activada.",
		L_LOGINTEXT : "Introduza o nome de Utilizador e Senha por favor.",
		L_LANGUAGE : "Idiomas disponíveis:",
		L_TIMEOUT : "A sessão expirou!",
		L_REGISTER : "Registar-se",
		L_PWLOST : "Perdeste a Senha?",
		INDEX_TITLE : "Vista Geral",
		INDEX_INFO : "Informação",
		INDEX_ENTRIES : "Total de sistemas",
		INDEX_ENTRIES_LASTWEEK : "Novos sistemas na última semana",
		INDEX_ENTRIES_TO_OLD : "Sistemas com mais de um mês",
		INDEX_REGISTERED_USERS : "Utilizadores registados",
		INDEX_PAGEFORWARD : "Se o seu browser não suportar o redireccionamento de páginas, clique aqui.",
		INDEX_NOTICES : "Notas",
		INDEX_PLAYERS : "Estatísticas do Jogador",
		INDEX_ALLIES : "Estatísticas da Aliança",
		INDEX_REPORTS : "Relatórios de Espionagem",
		INDEX_VERSION : "Nova versão disponível para download",
		INDEX_LATEST_VERSION : "Versão em utilização actualizada",
		INDEX_SHOUTBOX : "Mensagens",
		INDEX_NOENTRY : "Sem entradas",
		INDEX_COMMENT : "Escrever mensagem",
		INDEX_INSERT : "Inserir",
		INDEX_UMOD : "Jogadores em Modo de Férias",
		INDEX_NO_MOONS : "Número de luas",
		INDEX_NO_EMPTY_SYSTEMS : "Número de sistemas vazios",
		INDEX_NO_FULL_SYSTEMS : "Número de sistemas completamente cheios",
		INDEX_NO_TARGETS : "Número de possíveis alvos",
		INDEX_USERINFO : "Estatísticas",
		INDEX_ONLINE : "Ligados",
		INDEX_TODAY : "Ligados Hoje",
		INDEX_ALL : "Número Total de Ligações",
		GENERAL_LOAD_FORM : "Carregar para o formulário",
		GENERAL_SAVE_FORM : "Guardar a partir do formulário",
		GENERAL_SAVE_AS_TEXT : "Guardar como",
		GENERAL_SAVE : "Guardar",
		INDEX_USERMANAGEMENT : "Activation Overview",
		INDEX_NEEDADMIN : "Contas a desbloquear",
		INDEX_NEEDEMAIL : "Contas não validadas",
		INDEX_TOOLBAR_INFO : "Informação do Galaxytool plugin",
		INDEX_TOOLBAR_URL : "Galaxytool URL",
		INDEX_TOOLBAR_VERSION_REQUIRED : "Requer pelo menos a versão do Galaxytool plugin ",
		INDEX_TOOLBAR_INSTALL_GUIDE : "Instrução de instalação para o plugin",
		INDEX_TOOLBAR_TOKEN : "Palavra Passe",
		INDEX_TOOLBAR_NEW_TOKEN : "Nova Palavra passe",
		INDEX_PLAYERS_WITH_N_PLANETS : "Jogadores com mais de &1 planetas",
		INDEX_GETTING_STARTED : "Iniciando com oGalaxytool",
		INDEX_GETTING_STARTED1 : "Bem-Vindo ao Galaxytool!",
		INDEX_GETTING_STARTED2 : "O Galaxytool ajudar te-á a analisar o que se passa com o teu universo de OGame &1",
		INDEX_GETTING_STARTED3 : "Antes de conseguires analisar os dados terás de os inserir. Para isso é necessário um plugin para o &1 Firefox.",
		INDEX_GETTING_STARTED4 : "Depois de instalares o plugin, deverás navegar normalmente pelas páginas de OGame e e verás uma pequena janela a enviar informações para o Galaxytool.",
		INDEX_GETTING_STARTED5 : "Uma vez que o plugin inseriu os dados no Galaxytool, poderás começar a ver onde os jogadores têm as colónias, quantas colónias têm, que relatórios existem e ainda quando eles são mais activos.",
		INDEX_GETTING_STARTED6 : "Também te ajudará a comparar com os teus adversários ou analisando os teus relatórios de combate de forma a ver quantos ataques fizestes nos ultimos dias ou semanas.",
		INDEX_GETTING_WIKIPAGE : "Existem muitas características no Galaxytool.",
		INDEX_GETTING_WIKIPAGE2 : "Vê-as na nossa página wiki.",
		INDEX_GETTING_BOARD : "Para comentários ou sugestões utiliza o nosso fórum:",
		INDEX_GETTING_CHAT1 : "Visita-nos na nossa sala de chat:",
		INDEX_GETTING_CHAT2 : "Estamos online 24 horas por dia mas gastamos muito do nosso tempo livre lá, portanto sê paciente.",
		INDEX_CLOSE : "Fechar",
		INDEX_LOGIN : "Login",
		GENERAL_REQUIRED_FIELDS : "Por favor preencha todos os espaços obrigatórios",
		INDEX_MESSAGES : "Mensagens",
		INDEX_EXAMPLE : "Exemplo",
		INDEX_INVALID_DATA : "Dados inválidos",
		GENERAL_COLUMN_HIDE_TITLE : "Gerir colunas",
		GENERAL_COLUMN_HIDE_INFO : "Por favor escolha as colunas que deseja ver na tabela.",
		GENERAL_ENTRIES_DELETED : "&1 entradas apagadas",
		GENERAL_APPLY : "Aplicar",
		STARTPAGE_GALAXYTOOL_DESCR : "<em>Galaxytool</em> é uma ferramenta para o jogo de browser OGame.",
		GENERAL_OVERWRITE : "Subistituir entrada dupla",
		GENERAL_OVERWRITE_QUESTION : "Substituir?",
		INDEX_OWN_LOGINS : "Os seus dados de login",
		GENERAL_OPEN_IN_NEW_WINDOW : "Abrir a ligação numa nova janela",
		GENERAL_UNIT_OF_MEASURE_DAYS : "Days",
		PROGRAM_NAME : "OGame Galaxytool",
		SHORTNAME : "Galaxytool",
		BACK_INDEX : "Voltar à página principal",
		UNIVERSE : "Universo",
		MENU_INFO_LINKS : "Informações",
		MENU_PAGE : "Vista Geral",
		MENU_DB_SEARCH : "Procurar na Base de Dados",
		MENU_DB_NOTICES : "Procurar Notas",
		MENU_DB_REPORTS : "Procurar Rel. de Espionagem",
		MENU_GALAXYVIEW : "Ver Sistema Solar",
		MENU_STATISTICS : "Estatísticas",
		MENU_ALLYHISTORY : "Evolução",
		MENU_FLEET_MOVEMENTS : "Movimento de Frotas",
		MENU_COMBAT_REPORTS : "Relatórios de Combate",
		MENU_MESSAGES : "Mensagens Ingame",
		MENU_OPTION_LINKS : "Opções",
		MENU_DB_REFRESH : "Inserir na Base de Dados",
		MENU_NOTICES : "As minhas Notas",
		MENU_DB_STATUS : "Ver Universo",
		MENU_USEROPTIONS : "Gestão de Utilizadores",
		MENU_USEROPTIONS2 : "Opções de Utilizador",
		MENU_USEROPTIONS3 : "Informação de Utilizadores",
		MENU_ADMIN : "Administração",
		MENU_LOGOUT : "Sair",
		MENU_STUFF : "Vários",
		MENU_FORUM_THREAD : "Fórum Galaxytool",
		MENU_DOWNLOADPAGE : "Página de download",
		MENU_LANGUAGE : "Idioma",
		MENU_HELP : "Ajuda",
		MENU_TOOLOPTIONS : "Opções do Galaxytool",
		PARSER_INFO1 : " foi inserido com <b>sucesso</b> na Base de Dados!",
		PARSER_ERROR1 : "Erro ao tentar inserir as seguintes coordenadas:",
		PARSER_ERROR2 : "Não se encontrou a Base de Dados!",
		PARSER_ERROR3 : "Não se encontrou o servidor da Base de Dados!",
		PARSER_WRONG_UNIVERSE : "Universo errado - actuar: \"&1\" esperado: \"&2\"",
		SHOW_TITLE : "OGame Galaxytool - Procurar",
		SHOW_SEARCH : "Procurar na Base de Dados",
		SHOW_ALLYSYMBOL : "TAG da Aliança",
		SHOW_PLAYERNAME : "Nome do Jogador",
		SHOW_MOONS : "Só Planetas com Lua",
		SHOW_NOTICES : "Só Planetas com Notas",
		SHOW_COLONIES : "Só Planetas possíveis de colonizar",
		SHOW_YES : "Sim",
		SHOW_NO : "Não",
		SHOW_SEARCHRANGE : "Intervalo",
		SHOW_SEARCH_IN : "Procurar na Galáxia",
		SHOW_FROM_SYSTEM : "do Sistema",
		SHOW_FROM_PLANET : "da posição",
		SHOW_TO : "até",
		SHOW_DESCRIPTION : "Pode usar o asterisco (*) para os nomes de Jogadores ou Alianças. Asim poderá encontrar todos os Jogadores com &quot;nome&quot; no seu nome.<br />Apenas preencha os campos que quer especificar.",
		SHOW_SORT_BY : "Ordenar por",
		SHOW_GALASYSTEM : "Galáxia/Sistema",
		SHOW_ALLYNAME : "Aliança",
		SHOW_SEARCHBUTTON : "Procurar",
		SHOW_ADDRESS : "Coordenadas",
		SHOW_ALLYSORT : "Aliança",
		SHOW_PLANET : "Planeta",
		SHOW_STATUS : "Estado",
		SHOW_CURRENTNESS : "Última actualização",
		SHOW_PLAYER_STATUS : "Estado do Jogador",
		SHOW_PLAYER_STATUS1 : "Todos",
		SHOW_PLAYER_STATUS2 : "Possíveis alvos",
		SHOW_PLAYER_STATUS3 : "Inactivos",
		SHOW_HITS : "Resultados",
		SHOW_OF : "de",
		SHOW_ASC : "Ordem crescente",
		SHOW_DESC : "Ordem decrescente",
		SHOW_RESULTS : "Resultados por página",
		SHOW_MOON : "Lua",
		SHOW_UKMOONSIZE : "desconhecido",
		SHOW_DF : "Destroços",
		SHOW_DF_LONG : "Campo de Destroços",
		SHOW_METAL : "M",
		SHOW_METAL_LONG : "Metal",
		SHOW_CRYSTAL : "C",
		SHOW_CRYSTAL_LONG : "Cristal",
		SHOW_BOTH : "Ambos",
		SHOW_AT_LEAST : "(pelo menos)",
		SHOW_DATE : "Data",
		SHOW_DATE_0 : "Não interessa",
		SHOW_DATE_1 : "Anteriores a",
		SHOW_DATE_2 : "Posteriores a",
		SHOW_RANK : "Rank",
		SHOW_FRANK : "Rank da frota",
		SHOW_MEMBERS : "Membros",
		SHOW_NOTRANKED : "Fora do Top 1500.",
		SHOW_NOTICERES : "Notas",
		SHOW_REPORTS : "Só Planetas com Relatórios de Espionagem",
		SHOW_REPORTS_SHORT : "R. Esp.",
		SHOW_NOTHING : "Sem resultados.",
		SHOW_ALLIANCE_STATUS : "Estado da Aliança",
		SHOW_NO_STATUS : "Não definido",
		SHOW_NAP : "PNA",
		SHOW_ALLIED : "Aliança",
		SHOW_WAR : "Em Guerra",
		SHOW_BOYCOTT : "Boicote",
		SHOW_NEUTRAL : "Neutral",
		SHOW_OWN : "Própria Aliança",
		SHOW_WING : "Recruta",
		SHOW_EXT_OPTIONS1 : "Mostra mais opções para definir intervalos, estatísticas, data ou destroços.",
		SHOW_EXT_OPTIONS2 : "Mostra mais opções para colónias, luas, rel. de espionagem, notas, estado do jogador ou estado da aliança.",
		SHOW_EXT_OPTIONS3 : "Mostra mais opções para a ordenação dos resultados.",
		SHOW_EXTENDED : "pesquisa avançada",
		SHOW_MOON_SELECTION : "Planeta com lua",
		SHOW_REPORT_SELECTION : "Planet com Relatório de Espionagem",
		SHOW_FILTER_BY : "Excluir dos resultados",
		SHOW_FILTER_NONE : "Nenhuma",
		SHOW_PLAYERS_WITHOUT_PROGRESS : "Show players without score changes within the last few days",
		STATUS_TITLE : "OGame Galaxytool - Ver Universo",
		STATUS_DB_STATUS : "Informação de Galáxias/Sistemas Solares disponíveis na Base de Dados",
		STATUS_COLOR : "Cor",
		STATUS_AGE1 : "Última actualização: < 1 dia.",
		STATUS_AGE2 : "Última actualização: 2 - 4 dias.",
		STATUS_AGE3 : "Última actualização: 4 - 7 dias.",
		STATUS_AGE4 : "Última actualização: 1 - 2 semanas.",
		STATUS_AGE5 : "Última actualização: 2 - 4 semanas.",
		STATUS_AGE6 : "Última actualização: > 1 mês!",
		STATUS_AGE7 : "Sem informação na Base de Dados.",
		STATUS_ON : "(ligado)",
		STYLES_COLOR1 : "Verde claro",
		STYLES_COLOR2 : "Verde",
		STYLES_COLOR3 : "Verde escuro",
		STYLES_COLOR4 : "Amarelo",
		STYLES_COLOR5 : "Laranja",
		STYLES_COLOR6 : "Vermelho",
		STYLES_COLOR7 : "Azul",
		STATUS_DB_LEGEND : "Legenda",
		STATUS_GALAXY : "Vista da Galáxia",
		USER_TITLE : "Gestão de Utilizadores",
		USER_NAMES : "Utilizador",
		USER_ERROR : "Erro",
		USER_NEWUSER : "Novo Utilizador",
		USER_OPTIONS : "Opções",
		USER_USERNAME : "Nome de Utilizador",
		USER_PASSWORD : "Senha",
		USER_PASSWORD_CONFIRM : "Confirmar Senha",
		USER_GALAXY : "Galáxia",
		USER_SEARCH : "Permitir Procuras",
		USER_INSERT : "Permitir Inserções",
		USER_DELETE : "Apagar",
		USER_DELETE_ENTRY : "Quer mesmo apagar o Utilizador: ",
		USER_STATUS : "Ver Estatísticas",
		USER_STYLES : "Modificar layout",
		USER_SUBMIT : "Enviar",
		USER_RESET : "Limpar",
		USER_YES : "Sim",
		USER_NO : "Não",
		USER_STYLEPATH : "Caminho para styles.css",
		USER_PROBES : "Ver/Inserir Relatórios de Espionagem",
		USER_EMAIL : "E-mail",
		USER_ERROR1 : "Senha errada ou e-mail inválido.",
		USER_ERROR2 : "E-mail inválido.",
		USER_INGAME : "Nome dentro do OGame",
		USER_ALLYTAG : "TAG da Aliança",
		USER_ALLYHISTORY : "Ver/Inserir Histórico de Alianças",
		USER_DIPLOMATIC : "Muda estado Diplomático das Alianças",
		USER_STATSPAGE : "Número de resultados na página das estatísticas",
		USER_LINKS : "Links",
		USER_LINKS2 : "Format:<br>text;url<br>text2;url2<br>text3;url3",
		USER_EXPORT_TITLE : "Cores para exportação de dados (BB Codes)",
		USER_BB_COORDINATES : "Coordenadas",
		USER_BB_MOON : "Lua",
		USER_BB_DEBRIS : "Campo de Destroços",
		USER_BB_ALLY : "Nome da Aliança",
		USER_BB_ALLYDETAILS : "Detalhes da Aliança",
		USER_BB_PLAYERNAME : "Nome do Jogador",
		USER_BB_BANNED : "Banido",
		USER_BB_VACATION : "Modo de Férias",
		USER_BB_NOOB : "Fraco",
		USER_BB_INACTIVE : "Inactivo (i)",
		USER_BB_LONGINACTIVE : "Inactivo (I)",
		USER_DELETION : "Apagar",
		USER_FLEETINFO : "Movimento de Frotas",
		USER_ACTIVITIES : "Actividade do Jogador",
		USER_MAINTENANCE : "Manutenção do Galaxytool",
		USER_MANAGEMENT : "Gestão de Utilizadores",
		USER_DELETE_MY_COMBAT_REPORTS : "Apagar os meus Relatórios de Combate",
		USER_DELETE_MY_MESSAGES : "Apagar as minhas mensagens",
		USER_DELETE_MY_FLEETMOVES : "Apagar os meus movimentos de frota",
		USER_DELETE_MY_COMBAT_REPORTS_LIMITED : "Apagar os meus relatórios de combate com mais de &1 dias",
		USER_DELETE_MY_MESSAGES_LIMITED : "Apagar as minhas mensagens com mais de &1 dias",
		USER_TABLE_ENTRIES : "Número de resultados de pesquisa por página",
		USER_EXISTS : "Utilizador já em uso",
		USER_BB_OUTLAW : "Fora-da-Lei",
		USER_INVALID_URL : "URL &1 não é válido - o URL será ignorado",
		VIEW_TITLE : "OGame Galaxytool - Ver Sistema Solar",
		VIEW_NODATA : "Sem informação.",
		VIEW_GALAXY : "Galáxia",
		VIEW_SYSTEM : "Sistema Solar",
		VIEW_POSITION : "Pos",
		VIEW_PLANET : "Planeta",
		VIEW_MOON : "Lua",
		VIEW_TF : "Destroços",
		VIEW_PLAYER : "Jogador",
		VIEW_PLAYER_ADD : "(Rank / Estado)",
		VIEW_ALLY : "Aliança",
		VIEW_ALLY_ADD : "(Rank / Membros)",
		VIEW_METAL : "M",
		VIEW_CRYSTAL : "C",
		VIEW_COLONISED : "Planetas habitados",
		VIEW_UKMOONSIZE : "n/d",
		VIEW_BACK : "Voltar atrás",
		VIEW_NOTICE : "Notas",
		VIEW_REPORTS : "R. Esp.",
		VIEW_MOONPHALANX : "Luas que podem espiar este sistema",
		VIEW_NOMOONS : "Não existem Luas",
		VIEW_IRAKS : "Planetas que podem enviar mísseis interplanetários",
		VIEW_NOIRAKS : "Não foram encontrados Mísseis Interplanetários",
		VIEW_MOON_DESTROY_CHANCE : "Probabilidade de destruição da Lua",
		VIEW_CHANCE_WITH_ONE : "Probabilidade com apenas uma Estrela da Morte",
		VIEW_CHANCE_WITH_N : "Probabilidade com ",
		VIEW_DEATH_STARS : "Estrelas da Morte",
		VIEW_DS_DESTROY_CHANCE : "Probabilidade de perder a(s) Estrela(s) da Morte",
		VIEW_TOP : "Top",
		VIEW_GO : "Ir",
		VIEW_DIAMETER : "Diâmetro",
		PW_TITLE : "OGame Galaxytool - Mudar a Senha",
		OLD_PASSWORD : "Senha antiga",
		NEW_PASSWORD : "Senha nova",
		CONFIRM_NEW_PASSWORD : "Confirmar a Senha nova",
		PW_MISMATCH : "As Senhas não coincidem!",
		PW_ERROR : "A Senha antiga não está correcta!",
		UPDATE_DONE : "Actualizada com sucesso!",
		TIMEZONE_OFFSET : "Diferença do Fuso horário para o Servidor",
		DELETE_ACCOUNT : "apagar esta conta do Galaxytool",
		DELETE_ACCOUNT_SAFETY_REQUEST : "quer mesmo apagar esta conta deste Galaxytool?",
		CH_PASSWD_AUTHORIZATION : "Autorizações",
		CH_PASSWD_ADMIN : "Admin",
		TIMEZONE_OGAME_OFFSET : "Diferença do Fuso horário para o Servidor OGame",
		CH_PASSWD_USER_LANGUAGE : "Mudar linguagem após entrada",
		CH_PASSWD_USER_LANGUAGE_NO_CHANGE : "Não mudar",
		CH_PASSWD_EXPAND : "Expandido",
		CH_PASSWD_COLLAPSE : "Minimizado",
		CH_PASSWD_HIDDEN : "Escondido",
		CH_PASSWD_GETTING_STARTED : "Mostrar informação sobre como iniciar após entrada",
		CH_PASSWD_PLUGIN : "Mostrar Informação de Plugin após entrada",
		NOTICE_TITLE : "OGame Galaxytool - Notas",
		NOTICE_HEADER : "Editar Nota",
		NOTICE_HEADER2 : "Editar Notas próprias",
		NOTICE_PUBLIC : "Visível aos outros?",
		NOTICE_YES : "Sim",
		NOTICE_NO : "Não",
		NOTICE_TEXT : "Texto",
		NOTICE_SAVE : "Guardar",
		NOTICE_DELETED : "Nota apagada.",
		NOTICE_SAVED : "Nota guardada.",
		NOTICE_RESULTS : "Todos os resultados",
		NOTICE_USER : "Utilizador",
		NOTICE_DATE : "Data",
		NOTICE_EDIT : "Editar",
		NOTICE_DELETE : "[ Apagar ]",
		NOTICE_NEW : "Criar uma nota",
		NOTICE_NOTPUBLIC : "Nota privada.",
		NOTICE_ALL : "Todas",
		NOTICE_NONE : "Nenhuma",
		NOTICE_SEARCH : "Procurar Notas",
		NOTICE_SEARCH_SHORT : "Procurar",
		NOTICE_HITS : "Resultados",
		NOTICE_SHOWRESULTS : "Resultados por página",
		NOTICE_OF : "de",
		NOTICE_NOTHING : "Sem resultados",
		NOTICE_CHARS : "Caracteres",
		NOTICE_PLAYERNAME : "Jogadores",
		NOTICE_SHOWALL : "Mostra todas as Notas",
		REPORTS_TITLE : "OGame Galaxytool - Relatórios de Espionagem",
		REPORTS_RESOURCES : "Recursos",
		REPORTS_FLEET : "Frotas",
		REPORTS_DEFENCE : "Sistemas de defesas",
		REPORTS_BUILDINGS : "Edifícios",
		REPORTS_TECHNOLOGY : "Pesquisas",
		REPORTS_MOON : "Lua",
		REPORTS_SEARCH : "Procurar Relatórios de Espionagem",
		REPORTS_SEARCH_SHORT : "Procurar",
		REPORTS_HITS : "Resultados",
		REPORTS_NOTHING : "Não existem resultados para a pesquisa efectuada",
		REPORTS_ADDRESS : "Coordenadas",
		REPORTS_CURRENTNESS : "Última actualização",
		REPORTS_PLAYERNAME : "Jogador",
		REPORTS_ALLY : "Aliança",
		REPORTS_VIEW : "Ver Relatório",
		REPORTS_SEARCH_IN : "Procurar na Galáxia",
		REPORTS_FROM_SYSTEM : "desde o Sistema",
		REPORTS_TO : "até ao",
		REPORTS_DELETE : "[ Apagar ]",
		REPORTS_DELETED : "Relatório apagado!",
		REPORTS_RESULTS : "Resultados por página",
		REPORTS_OF : "de",
		REPORTS_DATE : "Data",
		REPORTS_DATE_0 : "Não interessa",
		REPORTS_DATE_1 : "Desde",
		REPORTS_DATE_2 : "até",
		REPORTS_NOTICES : "Notas",
		REPORTS_AT_LEAST_RESOURCES : "Recursos (pelo menos)",
		REPORTS_SEARCH_EXTENDED : "Procura Estendida",
		REPORTS_FLEET_RESIS : "Pontos da frota",
		REPORTS_DEFENCE_RESIS : "Pontos da defesa",
		REPORTS_ALL_RESIS : "Soma de pontos",
		REPORTS_TECHS : "Tecnologias",
		REPORTS_UNKNOWN_ENTRIES : "entradas desconhecidas",
		REPORTS_PARTLY_INSERTED : "parcialmente inserido",
		REPORTS_FOR_ALL_RES : "para todos os recursos",
		REPORTS_FOR_TF : "para o campo de destroços",
		REPORTS_KT : "Cargueiros Pequenos",
		REPORTS_GT : "Cargueiros Grandes",
		REPORTS_SS : "Naves de batalha",
		REPORTS_REC : "Reciclador",
		REPORTS_RAIDABLE : "Somente possíveis alvos",
		REPORTS_ALL_RESOURCES : "Todos Recursos",
		REPORTS_STUFF : "Vários",
		REPORTS_SPEEDSIM : "Simular com Speedsim",
		REPORTS_DRAGOSIM : "Simular com Dragosim",
		REPORTS_STATUS : "Estado",
		REPORTS_ERROR : "Ocorreu um erro",
		REPORTS_OWN_REPORTS : "So os meus relatórios",
		REPORTS_UPLOAD_BY : "Relatório enviado por",
		REPORTS_DEPTH : "profundidade do relatório",
		REPORTS_FLEET_SCORE : "Pontuação de Frotas",
		REPORTS_DEFENCE_SCORE : "Pontuação de Defesas",
		REPORTS_HOURS : "horas",
		REPORTS_MAX_RESULTS_HIT : "A sua pesquisa retornou mais do que &1 resultados. Somente os primeiros &1 resultados serão mostrados. Por favor ajuste as restrições da sua pesquisa para obeter menos resultados.",
		REPORTS_OSIMULATE : "Simule com OSimulate",
		REPORTS_SHOW_ONLY : "Apenas mostrar",
		REPORTS_SHOW_PLANETS : "Planetas",
		REPORTS_SHOW_MOONS : "Luas",
		REPORTS_OWNER : "Dono dos Relatórios",
		STATS_TITLE : "OGame Galaxytool - Estatísticas",
		STATS_TBLHEAD : "Estatísticas",
		STATS_RANK : "Rank",
		STATS_PLAYERNAME : "Jogador",
		STATS_ALLYNAME : "TAG da Aliança",
		STATS_SCORE : "Pontos",
		STATS_FLEET : "Frota",
		STATS_RESEARCH : "Pesquisas",
		STATS_MEMBERS : "Membros",
		STATS_STATUS : "Diplomacia",
		STATS_NOTHING : "Não definido",
		STATS_NAP : "PNA",
		STATS_ALLIED : "Aliada",
		STATS_WAR : "Em Guerra",
		STATS_BOYCOTT : "Boicote",
		STATS_NEUTRAL : "Neutral",
		STATS_OWN : "Própria Aliança",
		STATS_WING : "Recruta",
		STATS_UPDATE : "Entrada de",
		STATS_PLAYERSTATS : "Estatísticas do Jogador",
		STATS_ALLYSTATS : "Estatísticas da Aliança",
		STATS_DELETE : "Quer mesmo apagar este registo?",
		STATS_CONFIRM_DELETE : "Tem a certeza que quer apagar?",
		STATS_CHANGE_PLAYER_STATUS : "Estatísticas do Jogador",
		STATS_CHANGE_ALLIANCE_STATUS : "Estatísticas da Aliança",
		STATS_CHANGE_ALLIANCE_STATUS_HINT : "Todos os membros desta Aliança vão adquirir a situação Diplomática escolhida. Qualquer situação anterior vai ser anulada. Pode mudar o estado Diplomático de algum jogador à posteriori.",
		STATS_UNKNOWN : "Restante",
		STATS_DETAILS : "Detalhes para",
		STATS_PLAYERSTATUS : "Estado do Jogador",
		STATS_IGNORE_STATUS : "Todos",
		STATS_ACTIVE : "Activo",
		STATS_INACTIVE : "Inactivo (i)",
		STATS_BANNED : "Banido",
		STATS_VACATION : "Modo de Férias",
		STATS_NOOB : "Fraco",
		STATS_YES : "Sim",
		STATS_NO : "Só Planetas com Notas",
		STATS_SEARCH : "Permitir Procuras",
		STATS_SHOW_GRAPH : "Mostras detalhes oara resultados de distribuição",
		STATS_LONG_INACTIVE : "Inactivo (I)",
		STATS_STANDARD : "Pontos",
		STATS_MILITARY : "Pontos Militares",
		STATS_ECONOMY : "Pontos da Economia",
		STATS_HONOUR : "Pontos de Honra",
		STATS_MILITARY_BUILD : "Pontos Militares construídos",
		STATS_MILITARY_DESTROYED : "Pontos Militares destruídos",
		STATS_MILITARY_LOST : "Pontos Militares perdidos",
		REGISTER_REGISTRATE : "Registar",
		REGISTER_LOGINNAME : "Utilizador",
		REGISTER_PASSWORD : "Senha",
		REGISTER_PASSWORD_CONFIRM : "Confirme a Senha",
		REGISTER_EMAIL : "E-mail",
		REGISTER_INGAME : "Nome no OGame",
		REGISTER_ALLYTAG : "TAG da Aliança",
		REGISTER_EMAILVERIFICATION : "Verificação de E-mail",
		REGISTER_EMAILTEXT : "Por favor visite o seguinte link para confirmar o registo na Galaxytool.",
		REGISTER_ERROR1 : "Nome de Utilizador já escolhido.",
		REGISTER_ERROR2 : "Erro ao tentar enviar o e-mail. Por favor contacte o admin!",
		REGISTER_ERROR3 : "Ocorreu um erro enquanto envia os dados!",
		REGISTER_INFO1 : "A sua conta foi criada.",
		REGISTER_INFO2 : "Por favor visite o link no seu e-mail para confirmar o registo.",
		REGISTER_INFO3 : "Registo confirmado. Resta apenas a activação que será feita pelo admin.",
		REGISTER_BUTTON : "Voltar à página principal",
		REGISTER_NEW_SUBJECT : "Um novo Utilizador registou-se na Galaxytool",
		REGISTER_NEW_MAILTEXT : "Um novo Utilizador registou-se.",
		REGISTER_BACK : "Voltar a primeira pagina",
		REGISTER_MISSING_FIELDS : "preencher todos os campos obrigatórios",
		REGISTER_ERROR4 : "Endereço de Email não é válido.",
		REGISTER_ERROR5 : "Palavras Passe não são iguais.",
		REGISTER_PWS : "Força da Palavra Passe",
		REGISTER_PWS0 : "Muito Fraco",
		REGISTER_PWS1 : "Fraco",
		REGISTER_PWS2 : "Bom",
		REGISTER_PWS3 : "Forte",
		REGISTER_PWS4 : "Muito Forte",
		REGISTER_EMAIL_USED : "Endereço de Email em uso",
		LOSTPW_TITLE : "Perdi a minha Senha",
		LOSTPW_INFO2 : "Uma nova Senha foi gerada e enviada para o seu e-mail.",
		LOSTPW_BUTTON1 : "Receber nova Senha",
		LOSTPW_BUTTON2 : "Voltar à página principal",
		LOSTPW_LOGINNAME : "Nome de Utilizador",
		LOSTPW_EMAIL : "E-mail",
		LOSTPW_ERROR1 : "Erro ao tentar enviar informação para a Base de Dados!",
		LOSTPW_ERROR2 : "Nenhuma entrada encontrada!",
		LOSTPW_ERROR3 : "Erro ao tentar enviar o e-mail. Por favor contacte o admin.",
		LOSTPW_EMAIL_SUBJECT : "Nova Senha Galaxytool",
		LOSTPW_EMAIL_TEXT1 : "O seu novo login para o Galaxytool é",
		LOSTPW_EMAIL_TEXT2 : "Utilizador",
		LOSTPW_EMAIL_TEXT3 : "Senha",
		LOSTPW_INFO1 : "Receberá um email para verificar o seu pedido de nova Palavra-Passe.",
		LOSTPW_CONFIRM_RESET_SUBJECT : "Perdeu a Palavra-Passe?",
		LOSTPW_CONFIRM_RESET_MESSAGE : "Olá,\n\nPediu uma palavra-passe nova. Para gerar uma palavra-passe nova, carregue no seguinte link:",
		USERINFO_TITLE : "OGame Galaxytool - Informação de Utilizadores",
		USERINFO_NAMES : "Todos os Utilizadores",
		USERINFO_DETAIL : "Informação detalhada sobre",
		USERINFO_ERROR1 : "Não existe nenhum Utilizador com este ID!",
		USERINFO_USERNAME : "Utilizador",
		USERINFO_INGAME : "Nome no OGame",
		USERINFO_EMAIL : "E-mail",
		USERINFO_ALLYTAG : "Aliança",
		USERINFO_STYLEPATH : "Skin",
		USERINFO_STATUS : "Estado",
		USERINFO_ACTIVATE : "Activar Jogador",
		USERINFO_LOGINS : "Número de Acessos",
		USERINFO_LASTLOGIN : "Último Acesso em",
		USERINFO_DATA : "Informação sobre os Sistemas Solares inseridos",
		USERINFO_NODATA : "Nunca inseriu um Sistema Solar!</center>",
		USERINFO_GALAXY : "Galáxia",
		USERINFO_SYSTEMS : "Número de Sistemas Solares",
		USERINFO_IP : "Endereço IP",
		USERINFO_LOGINTIME : "Acesso em",
		USERINFO_NOLOGIN : "O Utilizador nunca se ligou.",
		USERINFO_LAST_GALAXYUPDATE : "Inseriu o último Sistema Solar em",
		USERINFO_LAST_PUBLIC_NOTICE : "Última Nota pública em",
		USERINFO_LAST_PRIVATE_NOTICE : "Última Nota privada em",
		USERINFO_NUMBEROF_PUBLIC_NOTICE : "Número de Notas públicas",
		USERINFO_NUMBEROF_PRIVATE_NOTICE : "Número de Notas privadas",
		USERINFO_ACTIVATED : "Conta activada- Deve dar as Permissões",
		USERINFO_ACTIVATIONTEXT : "O administrador do Galaxytool activou a tua conta.\n\nDivirta-se com o Galaxytool!",
		USERINFO_LAST_SUBMIT : "Últimos dados inseridos",
		ALLYHISTORY_TITLE : "OGame Galaxytool - Evolução",
		ALLYHISTORY_TBLHEAD : "Evolução",
		ALLYHISTORY_PLAYERNAME : "Jogador",
		ALLYHISTORY_ALLYNAME : "Aliança",
		ALLYHISTORY_LASTMONTH : "Último mês",
		ALLYHISTORY_ALL_DATA : "Toda a informação disponível",
		ALLYHISTORY_SHOW : "Mostra Evolução",
		ALLYHISTORY_TIMESPAN : "Duração",
		ALLYHISTORY_PROGESS : "Progresso",
		ALLYHISTORY_SCORE : "Pontos",
		ALLYHISTORY_FSCORE : "Frota",
		ALLYHISTORY_RSCORE : "Pesquisas",
		ALLYHISTORY_MEMBER : "Membros",
		ALLYHISTORY_NOTHING : "Não existem dados",
		ALLYHISTORY_DETAILS : "Detalhes",
		ALLYHISTORY_SHOW_ADDRESS : "Coordenadas",
		ALLYHISTORY_ESCORE : "Pontos da Economia",
		ALLYHISTORY_MSCORE : "Pontos Militares",
		DETAILEDINFO_PLAYERINFO_TITLE : "Informações de Jogador",
		DETAILEDINFO_ALLYINFO_TITLE : "Informações de Aliança",
		DETAILEDINFO_PLAYERINFO_TBLHEAD : "Informações detalhadas de Jogador",
		DETAILEDINFO_ALLYINFO_TBLHEAD : "Informações detalhadas de Aliança",
		DETAILEDINFO_NO_ALLIANCE : "Nenhuma",
		DETAILEDINFO_SCORE : "Estatísticas por Pontos",
		DETAILEDINFO_FLEET : "Estatísticas Por Frota",
		DETAILEDINFO_RESEARCH : "Estatísticas por Pesquisas",
		DETAILEDINFO_RANK : "Rank",
		DETAILEDINFO_POINTS : "Pontos:",
		DETAILEDINFO_KNOWN_PLANETS : "Planetas conhecidos",
		DETAILEDINFO_MOONS : "Luas conhecidas",
		DETAILEDINFO_PHALANX_AREA : "Alcance Phalanx",
		DETAILEDINFO_NO_PHALANX_AREA : "Sem Phalanx ou não existem dados.",
		DETAILEDINFO_NOTICES : "Notas",
		DETAILEDINFO_NO_NOTICES : "Não existem Notas",
		DETAILEDINFO_PREVIOUS_ALLIANCES : "Alianças anteriores",
		DETAILEDINFO_RESOURCES_PER_HOUR : "Produção Horária",
		DETAILEDINFO_RESOURCES_PER_DAY : "Produção Diária",
		DETAILEDINFO_RESOURCES_PER_WEEK : "Produção Semanal",
		DETAILEDINFO_RESOURCES_PER_MONTH : "Produção Mensal (30 dias)",
		DETAILEDINFO_METAL : "Metal",
		DETAILEDINFO_CRYSTAL : "Cristal",
		DETAILEDINFO_DEUTERIUM : "Deutério",
		DETAILEDINFO_UNKNOWN : "Sem Dados",
		DETAILEDINFO_SCORE_DISTRIBUTION : "Distribuição de Pontos",
		DETAILEDINFO_GENERAL : "Detalhe",
		DETAILEDINFO_MEMBERS : "Membros",
		DETAILEDINFO_GRAPHS : "Gráficos",
		DETAILEDINFO_RESOURCES : "Recursos",
		DETAILEDINFO_FLEET_TAB : "Frota",
		DETAILEDINFO_TECH : "Pesquisas",
		DETAILEDINFO_FLEET_DETAIL : "Soma / (media de jogador) disponível nos relatórios",
		DETAILEDINFO_TECH_DETAIL : "Media de todos jogadores disponíveis",
		DETAILEDINFO_PLANET_TAB : "Planetas",
		DETAILEDINFO_MOON_TAB : "Luas",
		DETAILEDINFO_ACTIVITIES : "Atividade",
		DETAILEDINFO_NODATA : "Sem informação.",
		DETAILEDINFO_ACTIVITY_DESCRIPTION : "Ver atividade em &1 recolhidas de:",
		DETAILEDINFO_GALAXYVIEWS : "Vista de Galaxia",
		DETAILEDINFO_SCANS : "Acções de Espionagem",
		DETAILEDINFO_MESSAGES : "Mensagem de Jogadores",
		DETAILEDINFO_COMBATS : "Relatório de Combate",
		DETAILEDINFO_ALLYPAGE : "Vista Geral da Aliança",
		DETAILEDINFO_MANUAL : "Inserir Manualmente",
		DETAILEDINFO_START : "Iniciar",
		DETAILEDINFO_TO : "Para",
		DETAILEDINFO_TODAY : "Hoje",
		DETAILEDINFO_DATA_RESTRICTION : "Restrito para:",
		DETAILEDINFO_WEEKDAY_WEEKEND : "Fim de Semana",
		DETAILEDINFO_WEEKDAY_WORKINGDAY : "Dia de Semana",
		DETAILEDINFO_WEEKDAY_MONDAY : "Segunda",
		DETAILEDINFO_WEEKDAY_TUESDAY : "Terça",
		DETAILEDINFO_WEEKDAY_WEDNESDAY : "Quarta",
		DETAILEDINFO_WEEKDAY_THURSDAY : "Quinta",
		DETAILEDINFO_WEEKDAY_FRIDAY : "Sexta",
		DETAILEDINFO_WEEKDAY_SATURDAY : "Sabado",
		DETAILEDINFO_WEEKDAY_SUNDAY : "Domingo",
		DETAILEDINFO_WEEKDAY_SHORTLENGTH : 3,
		DETAILEDINFO_PLAYER_CURRENTLY_ACTIVE : "O Jogador esta activo no momento",
		DETAILEDINFO_PLAYER_MESSAGES : "Memsagens de Jogadores disponiveis",
		DETAILEDINFO_SHOW : "Ver",
		DETAILEDINFO_NONE : "Nenhum disponivel",
		DETAILEDINFO_ENTER_MANUALLY : "inserir actividade para este jogador",
		DETAILEDINFO_PLAYER_SEEN_ON : "jogadores que estavam online em",
		DETAILEDINFO_INSERT : "Inserir",
		DETAILEDINFO_OGAME_SERVERTIMES : "Nota: todas as datas têm como referência a hora do servidor do OGame !",
		DETAILEDINFO_DAY_VIEW : "Vista de 24 horas",
		DETAILEDINFO_WEEK_VIEW : "Vista Semanal",
		DETAILEDINFO_HOME_PLANET : "Planeta Principal",
		DETAILEDINFO_PLANETNAME : "Nome",
		DETAILEDINFO_DEFENCE_SCORE : "Pontos de defesa",
		DETAILEDINFO_DEFENCE_SCORE_TOOLTIP : "Pontos de defesa = Pontos de frota - Pontos totais + Pontos de Pesquisa + Pontos de Economia.<br/>Todas as estatísticas devem estar actualizadas para obter resultados fiáveis!",
		DETAILEDINFO_SCORE_PER_SHIP : "Pontos por nave",
		DETAILEDINFO_SHIPS : "Número de naves",
		DETAILEDINFO_DATE_IN_FUTURE : "Não adicione actividades que ainda não aconteceram.",
		ADMIN_TITLE : "Administração do Galaxytool",
		ADMIN_DISCLAMER : "Atenção: Corre qualquer um destes scripts a teu risco! A maior parte deles vão apagar informação",
		ADMIN_INCONSISTENCIES : "inconsistências na base de dados",
		ADMIN_PLANETS : "Planetas na posição 0 ou mais do que 15",
		ADMIN_GALAXIES : "Apagar galáxias maiores que &1 ",
		ADMIN_PLAYERS : "Apagar jogadores sem (playerid)- causa os jogadores duplicados",
		ADMIN_REPORTS : "Apagar relatórios onde já não existe planetas ",
		ADMIN_MISC : "Miscellaneous",
		ADMIN_RESET : "Reset Galaxytool (Só utilizadores e tabela de ip’s não é apagada)",
		ADMIN_OLD_PLAYERS : " Apagar dados inserido por jogadores com mais de &1 dias",
		ADMIN_OLD_REPORTS : "Apagar relatórios com mais de &1 dias",
		ADMIN_LOADING : "Não fechar esta janela ate a pagina estar carregada.",
		ADMIN_STATUS : "Estado do teu pedido ",
		ADMIN_SELECTION : "No mínimo 1 entrada tem de ser seleccionada",
		ADMIN_SAFETY : "Tem a certeza que quer correr este script(s) ?",
		ADMIN_DONE : "feito",
		ADMIN_NOTBD : "nada para fazer",
		ADMIN_OLD_GALAXIES : "Remove vista da galáxias com mais de &1 dias",
		ADMIN_UNUSED_PLAYERS : "Remove jogadores que não estejam em nenhuma vista de galáxia",
		ADMIN_OLD_ACTIVITIES : "Apagar Atividades de jogadores com mais de &1 dias",
		ADMIN_OLD_COMBATS : "Remover relatórios de combate com mais de &1 dias",
		ADMIN_OLD_INGAME_MSG : "Remover mensagens do jogo com mais de &1 dias",
		ADMIN_OGAME_API : "Carregar dados públicos do OGame para a Galaxytool",
		ADMIN_OGAME_ALL_DATA : "Toda a informação disponível",
		ADMIN_OGAME_GALAXY_DATA : "Ver Sistema Solar",
		ADMIN_OGAME_STATISTICS_DATA : "Estatísticas",
		ERRORPAGE_PAGEFORWARD : "Click aqui se o seu browser não suportar pagina seguinte",
		ERRORPAGE_PERMISSION_DENIED : "Tu não tens permissões para entrar nesta pagina. Click em voltar a traz.",
		FLEETS_TITLE : "OGame Galaxytool - Movimento de Frotas",
		FLEETS_ACTUAL_FLEETS : "Movimento de Frotas atual",
		FLEETS_YES : "Sim",
		FLEETS_NO : "Só Planetas com Notas",
		FLEETS_DETAILS : "Detalhe",
		FLEETS_MISSION_EXPEDITION : "Expedição",
		FLEETS_MISSION_COLONIZATION : "Colonizar",
		FLEETS_MISSION_RECYCLE : "Reciclar",
		FLEETS_MISSION_TRANSPORT : "Transportar",
		FLEETS_MISSION_DEPLOYMENT : "Transferir",
		FLEETS_MISSION_ESPIONAGE : "Espionar",
		FLEETS_MISSION_ACS_DEFEND : "Manter Possição",
		FLEETS_MISSION_ATTACK : "Atacar",
		FLEETS_MISSION_ACS_ATTACK : "Ataque em ACS",
		FLEETS_MISSION_MOON_DESTRUCTION : "Destruir Lua",
		FLEETS_MISSION_MISSILE_ATTACK : "Ataque de Misseis",
		FLEETS_NO_DATA : "Não foram encontrados dados",
		FLEETS_FLEET : "Frota",
		FLEETS_ALL_FLEETS : "Mostrar todos os movimentos de frota",
		COMBAT_REPORT_OUDATED_GALAXYVIEW : "Sua Galáxia está desatualizada. Por favor viste as coordenadas do atacante e do defensor primeiro!",
		MESSAGES_TITLE : "OGame Galaxytool - Mensagens do OGame",
		MESSAGES_PLAYERNAME : "Nome do Jogador",
		MESSAGES_SUBJECT : "Assunto",
		MESSAGES_DATE : "Data",
		MESSAGES_FILTER : "Filtro",
		MESSAGES_DELETE : "Apagar Mensagem",
		MESSAGES_PUBLISH_DETAIL : "Publicar o conteúdo da mensagem para o jogador.",
		MESSAGES_PUBLISH_HEADER : "&sender enviou mensagem para &recipient em &date:\n\n &message",
		MESSAGES_PLAYER_FILTER : "Mensagens para o Jogador:",
		MESSAGES_CONTENT : "Conteúdo das mensagens",
		COMBATS_TITLE : "OGame Galaxytool - Relatórios de Combate",
		COMBATS_ATTACKER : "Atacante",
		COMBATS_DEFENDER : "Defensor",
		COMBATS_DATE : "Data",
		COMBATS_OWNER : "Dono",
		COMBATS_WINNER : "Vencedor",
		COMBATS_COMBATREPORT : "Relatório de Combate",
		COMBATS_COMBAT_AT : "Combat em:",
		COMBATS_LOST_UNITS : "Unidades Perdidas",
		COMBATS_LOOT : "Roubo",
		COMBATS_DEBRIS : "Campo de Destroços",
		COMBATS_AND : "e",
		COMBATS_PUBLISH : "Tornar este relatório publico",
		COMBATS_UNPUBLISH : "Despartilhar este relatório (torna-o privido novamente)",
		COMBATS_DELETE : "Apagar Relatório",
		COMBATS_CHECK_ALL : "Marcar todos",
		COMBATS_UNCHECK_ALL : "Desmarcar todos",
		COMBATS_WITH_SELECTED : "Com os Marcados",
		COMBATS_PUBLIC_REPORTS : "Relatórios Publicos",
		COMBATS_YES : "Sim",
		COMBATS_NO : "Só Planetas com Notas",
		COMBATS_SEARCH_OPTIONS : "Opções de Busca",
		COMBATS_SEARCH : "IR",
		COMBATS_RESET : "Limpar",
		COMBATS_COORDINATES : "Coordenadas",
		COMBATS_INVALID_GALAXY_ENTERED : "Galáxia inserida inválida",
		COMBATS_INVALID_SYSTEM_ENTERED : "Sistema inserido invalido",
		COMBATS_INVALID_PLANET_ENTERED : "Planeta inserido inválido",
		COMBATS_GALAXY_FROM_TO : "Galáxia",
		COMBATS_SYSTEM_FROM_TO : "Sistema",
		COMBATS_PLANET_FROM_TO : "Planeta",
		COMBATS_APPLY : "Aplicar",
		COMBATS_COMBAT_SUMMARY : "Resumo de relatório de combate",
		COMBATS_DOWNLOAD_CSV : "Fazer download como ficheiro CSV",
		REPORT_ARCHIVE_TITLE : "Arquivo de Relatório",
		REPORT_ARCHIVE_COORDINATES : "Coordenadas",
		REPORT_ARCHIVE_SCANTIME : "Tempo de pesquisa",
		REPORT_ARCHIVE_DELETE : "Apagar estas entradas",
		REPORT_ARCHIVE_CONFIRM_DELETE : "Quer mesmo apagar estas entradas??",
		REPORT_ARCHIVE_GALAXY : "Galáxia",
		REPORT_ARCHIVE_SYSTEM : "Sistema",
		REPORT_ARCHIVE_PLANET : "Planeta",
		REPORT_ARCHIVE_MOON : "Lua",
		REPORT_ARCHIVE_DETAILS : "Detalhes",
		REPORT_ARCHIVE_RESOURCES : "Produção Horária",
		REPORT_ARCHIVE_HEADER_RESOURCES : "Recursos",
		REPORT_ARCHIVE_DETAILS_FOR : "Arquivo de relatório para &1 [&2] (&3)",
		REPORT_ARCHIVE_FLEET_CARGO : "Capacidade de carga da frota",
		REPORT_ARCHIVE_IRAK_RANGE : "Alcançe dos Misseis Interplanetários",
		REPORT_ARCHIVE_CHART_TYPE : "Tipo de gráfico",
		INSTALL_TITLE : "Instalação da Galaxytool para a versão",
		INSTALL_PROGRESS : "Progresso total",
		INSTALL_STEP : "Passo",
		INSTALL_CONTINUE : "Continuar",
		INSTALL_VALIDATE : "Validar",
		INSTALL_STEP1 : "Bem-vindo",
		INSTALL_STEP2 : "Confirmado como ficheiros de escrita",
		INSTALL_STEP3 : "Configuração da Base de dados",
		INSTALL_STEP4 : "Configurações do OGame",
		INSTALL_STEP5 : "Configurações da Galaxytool",
		INSTALL_STEP6 : "Palavra-Passe do Administrador",
		INSTALL_STEP7 : "Instalar Galaxytool",
		INSTALL_STEP8 : "Acabar a Instalação",
		INSTALL_FILE_DELETE_CHECK : "Por favor elimine os ficheiros install.php e update.php do seu servidor.",
		INSTALL_STEP1_PHP_FAILED : "A versão PHP &1 não funciona com esta versão da Galaxytool",
		INSTALL_STEP1_FOPEN_FAILED : "A sua versão PHP não deixa abrir páginas com o comando FOPEN(). Isto é necessário para o OGame API.",
		INSTALL_STEP1_WELCOME : "Bem-vindo ao guia de instalção da Galaxytool. Será guiado pela instalação da Galaxytool.",
		INSTALL_STEP2_DESCRIPTION : "Confirme que os seus ficheiros config.php e attributes.php tem permissões de escrita.",
		INSTALL_STEP2_DESCRIPTION2 : "Se não sabe como conseguir isto por favor veja aqui como: &1",
		INSTALL_STEP2_FILE_NOT_WRITEABLE : "Ficheiro sem permissão de escrita",
		INSTALL_STEP3_SERVER : "Servidor da base de dados",
		INSTALL_STEP3_USERNAME : "Utilizador",
		INSTALL_STEP3_PASSWORD : "Senha",
		INSTALL_STEP3_DBNAME : "Nome da base de dados",
		INSTALL_STEP3_PREFIX : "Prefixo do nome da tabela",
		INSTALL_STEP3_ENTER_PREFIX : "Ex. aminhaferramenta_",
		INSTALL_STEP3_ENTER_SERVER : "Insira o endereço de servidor. Contacte o administrador do servidor se neccesário. Normalmente o valor correcto é localhost.",
		INSTALL_STEP3_ENTER_USERNAME : "Insira o nome de utilizador para acesso à base de dados",
		INSTALL_STEP3_ENTER_PASSWORD : "Insira a palavra-passe para acesso à base de dados",
		INSTALL_STEP3_ENTER_DBNAME : "Insira o nome da base dados, o qual será usado para a instalação (obrigatório)",
		INSTALL_STEP3_CONNECT_FAILED : "Não foi possível contactar o sevidor da base de dados",
		INSTALL_STEP3_DB_FAILED : "Base de dados &1 não encontrada",
		INSTALL_STEP3_MYSQL_VERSION_FAILED : "Versão MySQL  &1 não funciona com esta versão da Galaxytool",
		INSTALL_STEP4_URL : "URL do OGame",
		OGAME_URL_DETAILS : "Por favor insira o URL que aparece quando está logado no OGame. Baseado no URL a ferramenta irá obter o endereço OGame API que pode ser usado para preencher os dados na Galaxytool sem usar a Galaxytoolbar. O API for introduzido com a versão 4.1 do OGame.",
		INSTALL_STEP4_UNIVERSE : "Universo do OGame",
		INSTALL_STEP4_DEF_TO_DEBRIS : "Defesa para destroços",
		INSTALL_STEP4_DEBRIS_RATE : "Taxa de destroços",
		INSTALL_STEP4_SPEED_RATE : "Velocidade",
		INSTALL_STEP4_ENTER_UNIVERSE : "Insira o nome ou número do seu Universo (sensível a Maiúsculas).",
		INSTALL_STEP4_UNIVERSE_MISSING : "Tem de definir o seu universo",
		INSTALL_STEP4_ENTER_URL : "Insira o endereço do Universo",
		INSTALL_STEP4_URL_MISSING : "Tem de inserir o enderço do Universo",
		INSTALL_STEP4_URL_CHECK_FAILED : "Não foi possível encontrar o OGame API em &1",
		INSTALL_STEP4_GETSETTINGS : "Fetch settings",
		INSTALL_STEP5_TOOLNAME : "Nome da Galaxytool",
		INSTALL_STEP5_ENTER_TOOLNAME : "Este é o nome na página de log in para identificar a sua Galaxytool",
		INSTALL_STEP5_LANGUAGE : "Língua por defeito",
		INSTALL_STEP5_EMAIL_TO : "Email para",
		INSTALL_STEP5_ENTER_EMAIL_TO : "Insira o endereço de email onde gostava de receber notificações sobre registos",
		INSTALL_STEP5_EMAIL_FROM : "Email de",
		INSTALL_STEP5_ENTER_EMAIL_FROM : "Este email será visto como o dono dos mails enviados da Galaxytool",
		INSTALL_STEP5_USE_PHPMAILER : "Use PHPMailer",
		INSTALL_STEP5_MAXSHOUTS : "Máximo número de mensagens na caixa de avisos",
		INSTALL_STEP5_ENTER_USE_PHPMAILER : "Use PHPMailer se o seu servidor não suportar enviar emails por defeito",
		INSTALL_PHPMAILER_HOST : "SMPT Host",
		INSTALL_PHPMAILER_HOST_EXAMPLE : "ex. smtp.provider.com",
		INSTALL_PHPMAILER_USER : "Nome de utilizador SMPT",
		INSTALL_PHPMAILER_USER_EXAMPLE : "ex. user@provider.dcom",
		INSTALL_PHPMAILER_PASS : "Palavra-Passe SMPT",
		INSTALL_PHPMAILER_SECURE : "Método de Autenticação (ex. ssl)",
		INSTALL_PHPMAILER_PORT : "Porta SMTP",
		INSTALL_STEP6_INTRO : "Por favor defina uma palavra-passe para o nome de utilizador <strong>admin</strong>  com o qual tem que fazer o seu primeiro acesso à Galaxytool a seguir à instalação.",
		INSTALL_STEP7_CONFIG : "Ficheiro configuration criado",
		INSTALL_STEP7_CONFIG_FAILED : "Ficheiro configuration nao criado",
		INSTALL_STEP7_ATTRIBUTES : "Ficheiro attributes criado",
		INSTALL_STEP7_ATTRIBUTES_FAILED : "Ficheiro attributes não criado",
		INSTALL_STEP7_CREATED_TABLES : "Tabelas da base de dados criadas",
		INSTALL_STEP8_INTRO : "Instalou com sucesso a Galaxytool!",
		INSTALL_STEP8_LOAD_DATA : "A fazer download dos dados do OGame ...",
		INSTALL_STEP8_LOAD_DATA_FINISHED : "O download dos dados do OGame terminou",
		INSTALL_STEP8_DELETE_FILE : "Agora deve apagar os ficheiros de instalção install.php e update.php do seu servidor.",
		INSTALL_STEP8_LOGON : "Por favor entre com o nome de utilizador <strong>admin</strong> e a palavra-passe que definiu anteriormente.",
		UPDATE_START : "Iniciando actualização para a versão &1",
		UPDATE_STEP_DONE : "Concluído",
		UPDATE_TITLE : "Actualizção da Galaxytool para a versão",
		UPDATE_STEP1_WELCOME : "Bem-vindo ao guia de actualização da Galaxytool. Será guiado pela actualização da Galaxytool.",
		UPDATE_STEP1_BACKUP_FILES : "Em primeiro, faça uma cópia de segurança da sua pasta <strong>config</strong>! Terá que substituir as configurações no caso de erros.",
		UPDATE_STEP1_BACKUP_DB : "A seguir faça uma <a href=\"http://www.cybernetfx.com/clientes/knowledgebase.php?action=displayarticle&id=66/\">cópia de segurança</a> da sua base de dados.",
		UPDATE_STEP1_PROCEED : "Assim que as suas cópias de segurança estejam feitas pode continuar com a actualização.",
		UPDATE_STEP1 : "Bem-vindo",
		UPDATE_STEP2 : "Configurações da Galaxytool",
		UPDATE_STEP2_OLD_VERSION : "Versão anterior da Galaxytool",
		UPDATE_STEP3 : "Actualizar a Galaxytool",
		UPDATE_STEP3_UPDATE_RUNNING : "Actualização a correr, por favor aguarde...",
		UPDATE_STEP4 : "Concluir Actualização",
		UPDATE_STEP4_INTRO : "Actualizou com sucesso a Galaxytool!",
		UPDATE_STEP4_UPDATE_DONE : "Passos de actualização realizados.",
		UPDATE_FAILED : "A actualização falhou.",
		GALAXYTOOL_DUMMY_TEXT : "dummy"
	})
);