define(
	({
		REPORT_WHEN : "дана",
		RESOURCES_ON : "Ресурси на",
		PLAYER_BANNED : "б",
		PLAYER_VACATION_MODE : "о",
		PLAYER_NOOB : "с",
		PLAYER_INACTIVE : "и",
		PLAYER_LONG_INACTIVE : "И",
		PLAYER_OUTLAW : "o",
		L_USERNAME : "Корисничко име",
		L_PASSWORD : "Шифра",
		L_LOGINFAILURE : "Корисничко име или Шифра су погрешни или Ваш налог није јос активиран.",
		L_TOKENFAILURE : "Your logon key is wrong or your account is not activated yet.",
		L_LOGINTEXT : "Улогујте се.",
		L_LANGUAGE : "Могући језици:",
		L_TIMEOUT : "Сесија истекла!",
		L_REGISTER : "Региструј се",
		L_PWLOST : "Заборављена шифра",
		INDEX_TITLE : "OGame Galaxietool - Преглед",
		INDEX_INFO : "Информације",
		INDEX_ENTRIES : "Укупан број система",
		INDEX_ENTRIES_LASTWEEK : "Системи стари 1 недељу",
		INDEX_ENTRIES_TO_OLD : "Системи старији од месец дана",
		INDEX_REGISTERED_USERS : "Регистровани корисници",
		INDEX_PAGEFORWARD : "Ако Ваш броусер не подржава page forwarding, кликните овде.",
		INDEX_NOTICES : "Напомене",
		INDEX_PLAYERS : "Статистике играча",
		INDEX_ALLIES : "Статистике Савеѕа",
		INDEX_REPORTS : "Шпијунски извештаји",
		INDEX_VERSION : "Последња верзија за download",
		INDEX_LATEST_VERSION : "Не постоји новија верзија",
		INDEX_SHOUTBOX : "Огласна табла",
		INDEX_NOENTRY : "No shouts yet",
		INDEX_COMMENT : "Your Shout",
		INDEX_INSERT : "Убаци",
		INDEX_UMOD : "Играч у статусу одсуства",
		INDEX_NO_MOONS : "Број месеца",
		INDEX_NO_EMPTY_SYSTEMS : "Број празних система",
		INDEX_NO_FULL_SYSTEMS : "Број комплетно попунјених система",
		INDEX_NO_TARGETS : "Број потенцијалних мета",
		INDEX_USERINFO : "Број корисника",
		INDEX_ONLINE : "Трнутно активних корисника",
		INDEX_TODAY : "Данас активни корисници",
		INDEX_ALL : "Укупан број приступа",
		GENERAL_LOAD_FORM : "Load form data",
		GENERAL_SAVE_FORM : "Сачувај форму",
		GENERAL_SAVE_AS_TEXT : "Сачувај као",
		GENERAL_SAVE : "Сачувај",
		INDEX_USERMANAGEMENT : "Activation Overview",
		INDEX_NEEDADMIN : "Accounts to unlock",
		INDEX_NEEDEMAIL : "Unvalidated Accounts",
		INDEX_TOOLBAR_INFO : "Galaxytool plugin information",
		INDEX_TOOLBAR_URL : "Galaxytool URL",
		INDEX_TOOLBAR_VERSION_REQUIRED : "Requires at least Galaxytool plugin version",
		INDEX_TOOLBAR_INSTALL_GUIDE : "Installation instructions for plugin",
		INDEX_TOOLBAR_TOKEN : "Logon key",
		INDEX_TOOLBAR_NEW_TOKEN : "Get new key",
		INDEX_PLAYERS_WITH_N_PLANETS : "Players with more than &1 planets",
		INDEX_GETTING_STARTED : "Getting started with the Galaxytool",
		INDEX_GETTING_STARTED1 : "Welcome to the Galaxytool!",
		INDEX_GETTING_STARTED2 : "The Galaxytool will help you to analyze what is going on in your OGame universe &1",
		INDEX_GETTING_STARTED3 : "Before you can actually analyze data you have to insert it first. For this you require a browser plugin like the &1 for Firefox.",
		INDEX_GETTING_STARTED4 : "After you installed the plugin, you navigate through your OGame pages as usual and you will see a small status window whenever something was sent to your Galaxytool.",
		INDEX_GETTING_STARTED5 : "Once the plugin inserted data into the Galaxytool, you can start to analyze where the players have their colonies, how many colonies they have, what reports exist or when they are active the most.",
		INDEX_GETTING_STARTED6 : "But it will also help you to analyze how you are progressing if you compare yourself against your competitors or by analyzing your combat reports to see how much you raided during the last days or weeks.",
		INDEX_GETTING_WIKIPAGE : "There are many more features within the Galaxytool.",
		INDEX_GETTING_WIKIPAGE2 : "Check them out at our wiki page.",
		INDEX_GETTING_BOARD : "For feedback or ideas you can use our board:",
		INDEX_GETTING_CHAT1 : "Or visit us at the chatroom:",
		INDEX_GETTING_CHAT2 : "We are not online 24/7 but spare a lot of our free time there, so be patient.",
		INDEX_CLOSE : "Close",
		INDEX_LOGIN : "Login",
		GENERAL_REQUIRED_FIELDS : "Please fill all required fields",
		INDEX_MESSAGES : "Messages",
		INDEX_EXAMPLE : "Example",
		INDEX_INVALID_DATA : "Invalid data",
		GENERAL_COLUMN_HIDE_TITLE : "Manage columns",
		GENERAL_COLUMN_HIDE_INFO : "Please select which columns you want to see in the table.",
		GENERAL_ENTRIES_DELETED : "&1 entries deleted",
		GENERAL_APPLY : "Apply",
		STARTPAGE_GALAXYTOOL_DESCR : "<em>Galaxytool</em> is a tool for the browser game OGame.",
		GENERAL_OVERWRITE : "Overwrite duplicate entry",
		GENERAL_OVERWRITE_QUESTION : "Overwrite?",
		INDEX_OWN_LOGINS : "Your logins",
		GENERAL_OPEN_IN_NEW_WINDOW : "Open Link in New Window",
		GENERAL_UNIT_OF_MEASURE_DAYS : "Days",
		PROGRAM_NAME : "OGame Galaxytool",
		SHORTNAME : "Galaxytool",
		BACK_INDEX : "Повратак на главну страну",
		UNIVERSE : "Галаксија",
		MENU_INFO_LINKS : "Информације",
		MENU_PAGE : "Преглед",
		MENU_DB_SEARCH : "Тражи у бази",
		MENU_DB_NOTICES : "Тражи у напоменама",
		MENU_DB_REPORTS : "Тражи у извештајима",
		MENU_GALAXYVIEW : "Преглед галаксије",
		MENU_STATISTICS : "Статистике",
		MENU_ALLYHISTORY : "Преглед претходних промена",
		MENU_FLEET_MOVEMENTS : "Fleet movements",
		MENU_COMBAT_REPORTS : "Combat reports",
		MENU_MESSAGES : "Ingame messages",
		MENU_OPTION_LINKS : "Опције",
		MENU_DB_REFRESH : "Унеси у базу",
		MENU_NOTICES : "Напомене",
		MENU_DB_STATUS : "Статус баѕе",
		MENU_USEROPTIONS : "Управљање корисницима",
		MENU_USEROPTIONS2 : "Корисничке опције",
		MENU_USEROPTIONS3 : "User information",
		MENU_ADMIN : "Администрација",
		MENU_LOGOUT : "Logout",
		MENU_STUFF : "Разно",
		MENU_FORUM_THREAD : "Форум развојног тима",
		MENU_DOWNLOADPAGE : "Страна за download ",
		MENU_LANGUAGE : "Избор језика",
		MENU_HELP : "Помоћ",
		MENU_TOOLOPTIONS : "Опције Galaxytool-а",
		PARSER_INFO1 : " убачено је у базу података.",
		PARSER_ERROR1 : "Грешка при покушају уноса следећих координата:",
		PARSER_ERROR2 : "Не може да пронађе баз података!",
		PARSER_ERROR3 : "Не може да пронађе сервер базе података!",
		PARSER_WRONG_UNIVERSE : "Wrong universe - actual: \"&1\"  expected: \"&2\"",
		SHOW_TITLE : "OGame Galaxytool - Страна ѕа претрагу",
		SHOW_SEARCH : "Тражи у бази",
		SHOW_ALLYSYMBOL : "Савеѕни Таг",
		SHOW_PLAYERNAME : "Име играча",
		SHOW_MOONS : "Планете које имају месец",
		SHOW_NOTICES : "Планете са напоменама",
		SHOW_COLONIES : "Планете ѕа колонизацију",
		SHOW_YES : "Да",
		SHOW_NO : "Не",
		SHOW_SEARCHRANGE : "Од-до",
		SHOW_SEARCH_IN : "Преглед галаксије",
		SHOW_FROM_SYSTEM : "од система",
		SHOW_FROM_PLANET : "од позиције планете",
		SHOW_TO : "до",
		SHOW_DESCRIPTION : "You can use wildcards * for player or alliance names. So you can find all players with &quot;name&quot; in their name.<br />Only fill those fields you want to specify.",
		SHOW_SORT_BY : "Групиши по",
		SHOW_GALASYSTEM : "Галаксија/Систем",
		SHOW_ALLYNAME : "Име Савеза",
		SHOW_SEARCHBUTTON : "Претражи",
		SHOW_ADDRESS : "Адреса",
		SHOW_ALLYSORT : "Савез",
		SHOW_PLANET : "Име Планете",
		SHOW_STATUS : "Статус",
		SHOW_CURRENTNESS : "Последнји пут ажурирано",
		SHOW_PLAYER_STATUS : "Статус Играча",
		SHOW_PLAYER_STATUS1 : "сви",
		SHOW_PLAYER_STATUS2 : "могуће мете",
		SHOW_PLAYER_STATUS3 : "неактиван",
		SHOW_HITS : "Hits",
		SHOW_OF : "of",
		SHOW_ASC : "растући",
		SHOW_DESC : "опадајући",
		SHOW_RESULTS : "hits per page",
		SHOW_MOON : "Месецn",
		SHOW_UKMOONSIZE : "непознат",
		SHOW_DF : "DF",
		SHOW_DF_LONG : "Рушевине",
		SHOW_METAL : "M",
		SHOW_METAL_LONG : "Метал",
		SHOW_CRYSTAL : "К",
		SHOW_CRYSTAL_LONG : "Кристал",
		SHOW_BOTH : "заједно",
		SHOW_AT_LEAST : "(најманје)",
		SHOW_DATE : "Датум",
		SHOW_DATE_0 : "небитно",
		SHOW_DATE_1 : "старије од",
		SHOW_DATE_2 : "није старије од",
		SHOW_RANK : "Ранк",
		SHOW_FRANK : "Ранк флоте",
		SHOW_MEMBERS : "Чланови",
		SHOW_NOTRANKED : "Подаци недоступни",
		SHOW_NOTICERES : "Напомене",
		SHOW_REPORTS : "Само планете са извештајима",
		SHOW_REPORTS_SHORT : "Извештаји",
		SHOW_NOTHING : "Нема пронађених података.",
		SHOW_ALLIANCE_STATUS : "Статус Савеза",
		SHOW_NO_STATUS : "без статуса",
		SHOW_NAP : "NAP",
		SHOW_ALLIED : "Савезник",
		SHOW_WAR : "Рат",
		SHOW_BOYCOTT : "Бојкот",
		SHOW_NEUTRAL : "Неутрални",
		SHOW_OWN : "твој савез",
		SHOW_WING : "твој винг",
		SHOW_EXT_OPTIONS1 : "Show more search options for range, rank, date or debrisfield search.",
		SHOW_EXT_OPTIONS2 : "Show more search options for colonies, moons, reports, notices, playerstatus or diplomatic status.",
		SHOW_EXT_OPTIONS3 : "Show more search options for sorting of search results.",
		SHOW_EXTENDED : "advanced search",
		SHOW_MOON_SELECTION : "Planet with moon",
		SHOW_REPORT_SELECTION : "Planet with report",
		SHOW_FILTER_BY : "Exclude from the list",
		SHOW_FILTER_NONE : "нико",
		SHOW_PLAYERS_WITHOUT_PROGRESS : "Show players without score changes within the last few days",
		STATUS_TITLE : "OGame Galaxytool - Statuspage",
		STATUS_DB_STATUS : "Status of Database",
		STATUS_COLOR : "Боја",
		STATUS_AGE1 : "подаци 1 дан стари.",
		STATUS_AGE2 : "подаци 2 - 4 дана стари.",
		STATUS_AGE3 : "подаци 4 - 7 дана стари.",
		STATUS_AGE4 : "подаци 1 - 2 недеље стари.",
		STATUS_AGE5 : "подаци 2 - 4 недеље стари.",
		STATUS_AGE6 : "подаци старији од 1 месеца!",
		STATUS_AGE7 : "Нема доступних података.",
		STATUS_ON : "on",
		STYLES_COLOR1 : "Боја1",
		STYLES_COLOR2 : "Боја2",
		STYLES_COLOR3 : "Боја3",
		STYLES_COLOR4 : "Боја4",
		STYLES_COLOR5 : "Боја5",
		STYLES_COLOR6 : "Боја6",
		STYLES_COLOR7 : "Боја7",
		STATUS_DB_LEGEND : "Legend",
		STATUS_GALAXY : "Galaxy Overview",
		USER_TITLE : "Управљање корисницима",
		USER_NAMES : "Корисник",
		USER_ERROR : "Грешка",
		USER_NEWUSER : "Нови корисник",
		USER_OPTIONS : "Опције",
		USER_USERNAME : "Корисничко име",
		USER_PASSWORD : "Шифра",
		USER_PASSWORD_CONFIRM : "Потврди Шифру",
		USER_GALAXY : "Галаксија",
		USER_SEARCH : "Тражи",
		USER_INSERT : "Убаци",
		USER_DELETE : "Обриши",
		USER_DELETE_ENTRY : "Да ли желите да обришете корисника? ",
		USER_STATUS : "Погледај статистике",
		USER_STYLES : "Измени приказ",
		USER_SUBMIT : "Прихвати",
		USER_RESET : "Ресетуј",
		USER_YES : "Да",
		USER_NO : "Не",
		USER_STYLEPATH : "Адреса до styles.css",
		USER_PROBES : "Погледај/Додај извештаје о шпијунажи",
		USER_EMAIL : "Email",
		USER_ERROR1 : "Погрешна шифра или погрешан email.",
		USER_ERROR2 : "Email погрешан.",
		USER_INGAME : "In-game Име",
		USER_ALLYTAG : "Савезни таг",
		USER_ALLYHISTORY : "Преглед промена",
		USER_DIPLOMATIC : "Измени дипломатски статус",
		USER_STATSPAGE : "Број измена на статистичкој страници",
		USER_LINKS : "Линкови",
		USER_LINKS2 : "Format:<br>text;url<br>text2;url2<br>text3;url3",
		USER_EXPORT_TITLE : "Експорт боја (BB Codes)",
		USER_BB_COORDINATES : "Координате",
		USER_BB_MOON : "Месец",
		USER_BB_DEBRIS : "Рушевине",
		USER_BB_ALLY : "Име Савеѕа",
		USER_BB_ALLYDETAILS : "Деталји савеза",
		USER_BB_PLAYERNAME : "Име Играча",
		USER_BB_BANNED : "banned",
		USER_BB_VACATION : "мод одсуства",
		USER_BB_NOOB : "noob",
		USER_BB_INACTIVE : "Неактиван",
		USER_BB_LONGINACTIVE : "Дуго неактиван",
		USER_DELETION : "Delete",
		USER_FLEETINFO : "Fleet movements",
		USER_ACTIVITIES : "Player activities",
		USER_MAINTENANCE : "Galaxytool maintenance",
		USER_MANAGEMENT : "Управљање корисницима",
		USER_DELETE_MY_COMBAT_REPORTS : "Delete my combat reports",
		USER_DELETE_MY_MESSAGES : "Delete my messages",
		USER_DELETE_MY_FLEETMOVES : "Delete my fleet movements",
		USER_DELETE_MY_COMBAT_REPORTS_LIMITED : "Delete my combat reports older than &1 days",
		USER_DELETE_MY_MESSAGES_LIMITED : "Delete my messages older than &1 days",
		USER_TABLE_ENTRIES : "Number of search results for each page",
		USER_EXISTS : "User already exists",
		USER_BB_OUTLAW : "Outlaw",
		USER_INVALID_URL : "URL &1 seems to be invalid - URL will be ignored",
		VIEW_TITLE : "OGame Galaxytool - Преглед Галаксије",
		VIEW_NODATA : "Подаци недоступни.",
		VIEW_GALAXY : "Галаксија",
		VIEW_SYSTEM : "Систем",
		VIEW_POSITION : "Поз.",
		VIEW_PLANET : "Планета",
		VIEW_MOON : "Месец",
		VIEW_TF : "DF",
		VIEW_PLAYER : "Играч",
		VIEW_PLAYER_ADD : "(Ранк / Статус)",
		VIEW_ALLY : "Савез",
		VIEW_ALLY_ADD : "(Ранк / Члан)",
		VIEW_METAL : "M",
		VIEW_CRYSTAL : "К",
		VIEW_COLONISED : "Насељене планете",
		VIEW_UKMOONSIZE : "непознато",
		VIEW_BACK : "назад",
		VIEW_NOTICE : "Напомене",
		VIEW_REPORTS : "Извештаји",
		VIEW_MOONPHALANX : "Ови месеци могу скенирати овај систем:",
		VIEW_NOMOONS : "Месеци не постоје.",
		VIEW_IRAKS : "Следећа планета може дохватити овај систем са Интерпланетарним ракетама:",
		VIEW_NOIRAKS : "Интерпланетарне ракете не постоје.",
		VIEW_MOON_DESTROY_CHANCE : "Шанса за уништење месеца",
		VIEW_CHANCE_WITH_ONE : "Шанса са једном звездом",
		VIEW_CHANCE_WITH_N : "Шанса са ",
		VIEW_DEATH_STARS : "звезда смрти",
		VIEW_DS_DESTROY_CHANCE : "Шанса за губтак звезде(а)",
		VIEW_TOP : "Врх",
		VIEW_GO : "go",
		VIEW_DIAMETER : "Diameter",
		PW_TITLE : "OGame Galaxytool - Промена шифре",
		OLD_PASSWORD : "стара шифра",
		NEW_PASSWORD : "нова шифра",
		CONFIRM_NEW_PASSWORD : "потврди нову шифру",
		PW_MISMATCH : "Шифра се не слаже!",
		PW_ERROR : "Унета стара шифра се не слаже!",
		UPDATE_DONE : "Ажурирање успешно.",
		TIMEZONE_OFFSET : "Временска зона сервера",
		DELETE_ACCOUNT : "Обриши овај Galaxytool налог",
		DELETE_ACCOUNT_SAFETY_REQUEST : "Да ли заиста желите да обришете овај Galaxytool налог?",
		CH_PASSWD_AUTHORIZATION : "Ауторизација",
		CH_PASSWD_ADMIN : "Админ",
		TIMEZONE_OGAME_OFFSET : "Timezone offset to OGame server",
		CH_PASSWD_USER_LANGUAGE : "Change to this language after logon",
		CH_PASSWD_USER_LANGUAGE_NO_CHANGE : "No change",
		CH_PASSWD_EXPAND : "Expanded",
		CH_PASSWD_COLLAPSE : "Collapsed",
		CH_PASSWD_HIDDEN : "Hidden",
		CH_PASSWD_GETTING_STARTED : "Show Getting Started Info after logon",
		CH_PASSWD_PLUGIN : "Show Plugin Info after logon",
		NOTICE_TITLE : "OGame Galaxytool - Напомене",
		NOTICE_HEADER : "измени напомену",
		NOTICE_HEADER2 : "Измени наше напомене",
		NOTICE_PUBLIC : "Доступно осталима ?",
		NOTICE_YES : "да",
		NOTICE_NO : "не",
		NOTICE_TEXT : "Текст напомене",
		NOTICE_SAVE : "Сачувај",
		NOTICE_DELETED : "Запис обрисан",
		NOTICE_SAVED : "Запис сачуван.",
		NOTICE_RESULTS : "Сви резултати",
		NOTICE_USER : "Корисник",
		NOTICE_DATE : "Датум",
		NOTICE_EDIT : "Измени",
		NOTICE_DELETE : "Обриши",
		NOTICE_NEW : "Креирај свој запис",
		NOTICE_NOTPUBLIC : "Напомена није за јавност .",
		NOTICE_ALL : "сви",
		NOTICE_NONE : "нико",
		NOTICE_SEARCH : "Тражи у напоменама",
		NOTICE_SEARCH_SHORT : "Тражи",
		NOTICE_HITS : "Hits",
		NOTICE_SHOWRESULTS : "hits per page",
		NOTICE_OF : "of",
		NOTICE_NOTHING : "Нема записа",
		NOTICE_CHARS : "Карактери",
		NOTICE_PLAYERNAME : "Играч",
		NOTICE_SHOWALL : "Прикази све напомене",
		REPORTS_TITLE : "OGame Galaxytool - Итвештаји шпијунаже",
		REPORTS_RESOURCES : "Ресурси",
		REPORTS_FLEET : "Флота",
		REPORTS_DEFENCE : "Одбрана",
		REPORTS_BUILDINGS : "Зграде",
		REPORTS_TECHNOLOGY : "Истраживање",
		REPORTS_MOON : "Месец",
		REPORTS_SEARCH : "Тражу у извештајима шпијунаже",
		REPORTS_SEARCH_SHORT : "Тражи",
		REPORTS_HITS : "Hits",
		REPORTS_NOTHING : "Нема података",
		REPORTS_ADDRESS : "Адреса",
		REPORTS_CURRENTNESS : "Currentness",
		REPORTS_PLAYERNAME : "Име играча",
		REPORTS_ALLY : "Савезник",
		REPORTS_VIEW : "погледај Извештај",
		REPORTS_SEARCH_IN : "Тражи у галаксији",
		REPORTS_FROM_SYSTEM : "од Система",
		REPORTS_TO : "до",
		REPORTS_DELETE : "обриши",
		REPORTS_DELETED : "Запис обрисан",
		REPORTS_RESULTS : "hits per page",
		REPORTS_OF : "од",
		REPORTS_DATE : "Датум",
		REPORTS_DATE_0 : "није битно",
		REPORTS_DATE_1 : "старије од",
		REPORTS_DATE_2 : "није старије од",
		REPORTS_NOTICES : "Напомене",
		REPORTS_AT_LEAST_RESOURCES : "Ресурси (најманје)",
		REPORTS_SEARCH_EXTENDED : "проширена претрага",
		REPORTS_FLEET_RESIS : "Флота- резултат",
		REPORTS_DEFENCE_RESIS : "Одбрана- резултат",
		REPORTS_ALL_RESIS : "ѕбир",
		REPORTS_TECHS : "Techs",
		REPORTS_UNKNOWN_ENTRIES : "непоѕнати уноси",
		REPORTS_PARTLY_INSERTED : "делимично унето",
		REPORTS_FOR_ALL_RES : "for all raidable resources",
		REPORTS_FOR_TF : "за све рушевине",
		REPORTS_KT : "Мали транспортери",
		REPORTS_GT : "Велики транспортери",
		REPORTS_SS : "Борбени брод",
		REPORTS_REC : "Рециклер",
		REPORTS_RAIDABLE : "Only raidable targets",
		REPORTS_ALL_RESOURCES : "Сви ресурси",
		REPORTS_STUFF : "Разно",
		REPORTS_SPEEDSIM : "Симулирај са Speedsim",
		REPORTS_DRAGOSIM : "Симулирај са Dragosim",
		REPORTS_STATUS : "Статус",
		REPORTS_ERROR : "Грешка",
		REPORTS_OWN_REPORTS : "Само моји извештаји",
		REPORTS_UPLOAD_BY : "Извештај убацио у базу:",
		REPORTS_DEPTH : "Report depth",
		REPORTS_FLEET_SCORE : "износ флоте",
		REPORTS_DEFENCE_SCORE : "износ одбране",
		REPORTS_HOURS : "hours",
		REPORTS_MAX_RESULTS_HIT : "Your query returned more than &1 hits. Only the first &1 results are show. Please adjust your search request to get less results.",
		REPORTS_OSIMULATE : "Simulate with OSimulate",
		REPORTS_SHOW_ONLY : "Show only",
		REPORTS_SHOW_PLANETS : "Планете",
		REPORTS_SHOW_MOONS : "Месеци",
		REPORTS_OWNER : "Reports owned by",
		STATS_TITLE : "OGame Galaxytool - Статистике",
		STATS_TBLHEAD : "Статистике",
		STATS_RANK : "Ранг",
		STATS_PLAYERNAME : "Име Играча",
		STATS_ALLYNAME : "Савезни Таг",
		STATS_SCORE : "Износ",
		STATS_FLEET : "Флота",
		STATS_RESEARCH : "Истраживанје",
		STATS_MEMBERS : "Чланови",
		STATS_STATUS : "Статус",
		STATS_NOTHING : "нема статус",
		STATS_NAP : "NAP",
		STATS_ALLIED : "Савезник",
		STATS_WAR : "Рат",
		STATS_BOYCOTT : "Бојкот",
		STATS_NEUTRAL : "Неутрални",
		STATS_OWN : "Твој савез",
		STATS_WING : "Твој wing",
		STATS_UPDATE : "Убаци податке са",
		STATS_PLAYERSTATS : "Статус играча",
		STATS_ALLYSTATS : "Статус савеза",
		STATS_DELETE : "Да ли желите да обришете овај запис ?",
		STATS_CONFIRM_DELETE : "Да ли заиста желите да обришете овај запис?",
		STATS_CHANGE_PLAYER_STATUS : "Статус играча",
		STATS_CHANGE_ALLIANCE_STATUS : "Статус савеза",
		STATS_CHANGE_ALLIANCE_STATUS_HINT : "Сви чланови овог савеза добијају изабрани статус. Any previous status will be overwritten. You may change the status of some players afterwards.",
		STATS_UNKNOWN : "Rest",
		STATS_DETAILS : "Details for",
		STATS_PLAYERSTATUS : "Статус Играча",
		STATS_IGNORE_STATUS : "сви",
		STATS_ACTIVE : "active",
		STATS_INACTIVE : "Неактиван",
		STATS_BANNED : "banned",
		STATS_VACATION : "мод одсуства",
		STATS_NOOB : "noob",
		STATS_YES : "Да",
		STATS_NO : "Планете са напоменама",
		STATS_SEARCH : "Тражи",
		STATS_SHOW_GRAPH : "Show details for score distribution",
		STATS_LONG_INACTIVE : "Дуго неактиван",
		STATS_STANDARD : "Standard Points",
		STATS_MILITARY : "Military Points",
		STATS_ECONOMY : "Economy",
		STATS_HONOUR : "Honour points",
		STATS_MILITARY_BUILD : "Military build",
		STATS_MILITARY_DESTROYED : "Military destroyed",
		STATS_MILITARY_LOST : "Military lost",
		REGISTER_REGISTRATE : "Register",
		REGISTER_LOGINNAME : "Login-Name",
		REGISTER_PASSWORD : "Шифра",
		REGISTER_PASSWORD_CONFIRM : "Confirm Шифра",
		REGISTER_EMAIL : "Email",
		REGISTER_INGAME : "Ingame-Name",
		REGISTER_ALLYTAG : "Allytag",
		REGISTER_EMAILVERIFICATION : "Emailcheck",
		REGISTER_EMAILTEXT : "Please visit the following link to confirm your registration at the Galaxytool.",
		REGISTER_ERROR1 : "Login-Корисничко име already used.",
		REGISTER_ERROR2 : "Error while trying to send an email. Please contact your admin.",
		REGISTER_ERROR3 : "Error while trying to send data to the database!",
		REGISTER_INFO1 : "Your account was created.",
		REGISTER_INFO2 : "Please visit the link in your email to confirm the registration.",
		REGISTER_INFO3 : "Account confirmed. Your admin needs to activate it now.",
		REGISTER_BUTTON : "Back to main page",
		REGISTER_NEW_SUBJECT : "A new user registered at the Galaxytool",
		REGISTER_NEW_MAILTEXT : "A new user registered himself.",
		REGISTER_BACK : "Back to first page",
		REGISTER_MISSING_FIELDS : "Enter all required Fields",
		REGISTER_ERROR4 : "Email address is not valid.",
		REGISTER_ERROR5 : "Passwords don't match.",
		REGISTER_PWS : "Password strength",
		REGISTER_PWS0 : "very weak",
		REGISTER_PWS1 : "weak",
		REGISTER_PWS2 : "good",
		REGISTER_PWS3 : "strong",
		REGISTER_PWS4 : "very strong",
		REGISTER_EMAIL_USED : "Email Address is already used",
		LOSTPW_TITLE : "Lost my Шифра",
		LOSTPW_INFO2 : "A new Шифра was generated and send to your email address.",
		LOSTPW_BUTTON1 : "get new Шифра",
		LOSTPW_BUTTON2 : "Back to main page",
		LOSTPW_LOGINNAME : "Login-Name",
		LOSTPW_EMAIL : "Email",
		LOSTPW_ERROR1 : "Error while trying to send data to the database!",
		LOSTPW_ERROR2 : "No matching entry found!",
		LOSTPW_ERROR3 : "Error while trying to send an email. Please contact your admin.",
		LOSTPW_EMAIL_SUBJECT : "Your new Шифра you requested",
		LOSTPW_EMAIL_TEXT1 : "Here is your new login for the Galaxytool",
		LOSTPW_EMAIL_TEXT2 : "Корисничко име",
		LOSTPW_EMAIL_TEXT3 : "Шифра",
		LOSTPW_INFO1 : "You will receive an email to verify your password reset request.",
		LOSTPW_CONFIRM_RESET_SUBJECT : "Lost password?",
		LOSTPW_CONFIRM_RESET_MESSAGE : "Hello,\n\nyou requested a password reset for the Galaxytool. To generate a new password, click the following link:",
		USERINFO_TITLE : "OGame Galaxytool - Корисничке информације",
		USERINFO_NAMES : "Сви корисници овог алата",
		USERINFO_DETAIL : "детаљне информације о",
		USERINFO_ERROR1 : "Не постоји корисник са овим ID!",
		USERINFO_USERNAME : "Корисничко име",
		USERINFO_INGAME : "In-game име",
		USERINFO_EMAIL : "Email",
		USERINFO_ALLYTAG : "Савез",
		USERINFO_STYLEPATH : "Маска",
		USERINFO_STATUS : "Статус",
		USERINFO_ACTIVATE : "Активни играч",
		USERINFO_LOGINS : "Број приступа",
		USERINFO_LASTLOGIN : "Последнји Приступ",
		USERINFO_DATA : "Информације о унетим системима",
		USERINFO_NODATA : "Овај корисник још није унео ниједан систем!",
		USERINFO_GALAXY : "Галаксија",
		USERINFO_SYSTEMS : "Број система",
		USERINFO_IP : "ИП адреса",
		USERINFO_LOGINTIME : "Login",
		USERINFO_NOLOGIN : "Играч се није никада улоговао.",
		USERINFO_LAST_GALAXYUPDATE : "Последњи приказ галаксије убачен",
		USERINFO_LAST_PUBLIC_NOTICE : "Последња званичних напомена",
		USERINFO_LAST_PRIVATE_NOTICE : "Последња приватна напомена",
		USERINFO_NUMBEROF_PUBLIC_NOTICE : "Број званичних напомена",
		USERINFO_NUMBEROF_PRIVATE_NOTICE : "Број приватних напомена",
		USERINFO_ACTIVATED : "Налог активан",
		USERINFO_ACTIVATIONTEXT : "Galaxytool админ је активирао Ваш налог.\n\nУживајте са Galaxytool-ом!",
		USERINFO_LAST_SUBMIT : "Inserted last data",
		ALLYHISTORY_TITLE : "OGame Galaxytool - Историја савеза",
		ALLYHISTORY_TBLHEAD : "Преглед претходних промена",
		ALLYHISTORY_PLAYERNAME : "Име играча",
		ALLYHISTORY_ALLYNAME : "Савез",
		ALLYHISTORY_LASTMONTH : "Последњи месец",
		ALLYHISTORY_ALL_DATA : "све доступне информације",
		ALLYHISTORY_SHOW : "прикази статистике",
		ALLYHISTORY_TIMESPAN : "Временски размак",
		ALLYHISTORY_PROGESS : "НАпредак",
		ALLYHISTORY_SCORE : "Поени",
		ALLYHISTORY_FSCORE : "Флота поени",
		ALLYHISTORY_RSCORE : "Истраживање Поени",
		ALLYHISTORY_MEMBER : "Чланови",
		ALLYHISTORY_NOTHING : "нема пронађених података",
		ALLYHISTORY_DETAILS : "Детаљи",
		ALLYHISTORY_SHOW_ADDRESS : "Координате",
		ALLYHISTORY_ESCORE : "Economy",
		ALLYHISTORY_MSCORE : "Military Points",
		DETAILEDINFO_PLAYERINFO_TITLE : "Информације о играчу",
		DETAILEDINFO_ALLYINFO_TITLE : "Информације о савезу",
		DETAILEDINFO_PLAYERINFO_TBLHEAD : "Детаљне информације о играчу",
		DETAILEDINFO_ALLYINFO_TBLHEAD : "Детаљнe информације о савезу",
		DETAILEDINFO_NO_ALLIANCE : "ништа",
		DETAILEDINFO_SCORE : "Позиција ранг",
		DETAILEDINFO_FLEET : "Статистика флоте",
		DETAILEDINFO_RESEARCH : "Статистика истраживања",
		DETAILEDINFO_RANK : "Ранг",
		DETAILEDINFO_POINTS : "Поени",
		DETAILEDINFO_KNOWN_PLANETS : " познате планете",
		DETAILEDINFO_MOONS : "познати месеци",
		DETAILEDINFO_PHALANX_AREA : "Фаланга домет",
		DETAILEDINFO_NO_PHALANX_AREA : "Нема фаланге",
		DETAILEDINFO_NOTICES : "Напомене",
		DETAILEDINFO_NO_NOTICES : "Нема напомена",
		DETAILEDINFO_PREVIOUS_ALLIANCES : "Претходни савези",
		DETAILEDINFO_RESOURCES_PER_HOUR : "Ресурси на сат",
		DETAILEDINFO_RESOURCES_PER_DAY : "Ресурси на дан",
		DETAILEDINFO_RESOURCES_PER_WEEK : "Ресурси недељно",
		DETAILEDINFO_RESOURCES_PER_MONTH : "Ресурси месечно (30 дана)",
		DETAILEDINFO_METAL : "Метал",
		DETAILEDINFO_CRYSTAL : "Кристал",
		DETAILEDINFO_DEUTERIUM : "Деутеријум",
		DETAILEDINFO_UNKNOWN : "непознато",
		DETAILEDINFO_SCORE_DISTRIBUTION : "Score distribution",
		DETAILEDINFO_GENERAL : "Детаљи",
		DETAILEDINFO_MEMBERS : "Чланови",
		DETAILEDINFO_GRAPHS : "Graphs",
		DETAILEDINFO_RESOURCES : "Ресурси",
		DETAILEDINFO_FLEET_TAB : "Флота",
		DETAILEDINFO_TECH : "Истраживање",
		DETAILEDINFO_FLEET_DETAIL : "Збир / (просек играча) у свим доступним извештајима",
		DETAILEDINFO_TECH_DETAIL : " Просек свих доступних информација о играчима",
		DETAILEDINFO_PLANET_TAB : "Планете",
		DETAILEDINFO_MOON_TAB : "Месеци",
		DETAILEDINFO_ACTIVITIES : "Activities",
		DETAILEDINFO_NODATA : "Подаци недоступни.",
		DETAILEDINFO_ACTIVITY_DESCRIPTION : "Show activities of &1 collected from:",
		DETAILEDINFO_GALAXYVIEWS : "Galaxy views",
		DETAILEDINFO_SCANS : "Espionage actions",
		DETAILEDINFO_MESSAGES : "Player messages",
		DETAILEDINFO_COMBATS : "Combat reports",
		DETAILEDINFO_ALLYPAGE : "Alliance overview",
		DETAILEDINFO_MANUAL : "Manual insertions",
		DETAILEDINFO_START : "Beginning",
		DETAILEDINFO_TO : "to",
		DETAILEDINFO_TODAY : "Today",
		DETAILEDINFO_DATA_RESTRICTION : "restricted to:",
		DETAILEDINFO_WEEKDAY_WEEKEND : "Weekend",
		DETAILEDINFO_WEEKDAY_WORKINGDAY : "Weekday",
		DETAILEDINFO_WEEKDAY_MONDAY : "Monday",
		DETAILEDINFO_WEEKDAY_TUESDAY : "Tuesday",
		DETAILEDINFO_WEEKDAY_WEDNESDAY : "Wednesday",
		DETAILEDINFO_WEEKDAY_THURSDAY : "Thursday",
		DETAILEDINFO_WEEKDAY_FRIDAY : "Friday",
		DETAILEDINFO_WEEKDAY_SATURDAY : "Saturday",
		DETAILEDINFO_WEEKDAY_SUNDAY : "Sunday",
		DETAILEDINFO_WEEKDAY_SHORTLENGTH : 3,
		DETAILEDINFO_PLAYER_CURRENTLY_ACTIVE : "The player is currently active",
		DETAILEDINFO_PLAYER_MESSAGES : "available player messages",
		DETAILEDINFO_SHOW : "show",
		DETAILEDINFO_NONE : "none available",
		DETAILEDINFO_ENTER_MANUALLY : "Enter activities for this player",
		DETAILEDINFO_PLAYER_SEEN_ON : "Player was online on",
		DETAILEDINFO_INSERT : "Insert",
		DETAILEDINFO_OGAME_SERVERTIMES : "Please note: All dates and times refer to OGame server times !",
		DETAILEDINFO_DAY_VIEW : "24 hours view",
		DETAILEDINFO_WEEK_VIEW : "weekly view",
		DETAILEDINFO_HOME_PLANET : "Homeworld",
		DETAILEDINFO_PLANETNAME : "Name",
		DETAILEDINFO_DEFENCE_SCORE : "Defence score",
		DETAILEDINFO_DEFENCE_SCORE_TOOLTIP : "Defence score = Fleet - Score + Research + Economy.<br/>All those statistics must be up to date to have a meaningful result!",
		DETAILEDINFO_SCORE_PER_SHIP : "Scores per ship",
		DETAILEDINFO_SHIPS : "Number of ships",
		DETAILEDINFO_DATE_IN_FUTURE : "Do not maintain times which are not in the past.",
		ADMIN_TITLE : "Администрација Galaxytool-а",
		ADMIN_DISCLAMER : "Упозорење: Покретање било које од ових скрипти на сопствену одговорност! Највећи број је намењен брисању података.",
		ADMIN_INCONSISTENCIES : "Неповезаност у бази",
		ADMIN_PLANETS : "Обрисати планете на позицији 0 или веће од 15",
		ADMIN_GALAXIES : "Обрисати галаксије веће од &1 ",
		ADMIN_PLAYERS : "Обрисати играче без огаме налога - води дуплиранима подацима о корисницима",
		ADMIN_REPORTS : "Обрисати извештаје тамо где планете више не постоје",
		ADMIN_MISC : "Разно",
		ADMIN_RESET : "РЕсетуј Galaxytool (само корисници и ИП адресе се не бришу)",
		ADMIN_OLD_PLAYERS : "Обриши податке које корисници уносе старије од  &1 дана",
		ADMIN_OLD_REPORTS : "Обриши извештаје старије од &1 дана",
		ADMIN_LOADING : "НЕ затварати овај прозор док се страна не учита.",
		ADMIN_STATUS : "Стаус Ваших захтева",
		ADMIN_SELECTION : "Најмање један податак мора бити обележен",
		ADMIN_SAFETY : "Да ли сте сигурни да желите да покренете ову скрипту(е) ?",
		ADMIN_DONE : "готово",
		ADMIN_NOTBD : "нема шта да се уради",
		ADMIN_OLD_GALAXIES : "Уклони прегледе галаксија старије од &1 дана",
		ADMIN_UNUSED_PLAYERS : "Уклони играче који се не појављују ни у једном прегледу галаксије",
		ADMIN_OLD_ACTIVITIES : "Remove player activities older than &1 days",
		ADMIN_OLD_COMBATS : "Remove combat reports older than &1 days",
		ADMIN_OLD_INGAME_MSG : "Remove ingame messages older than &1 days",
		ADMIN_OGAME_API : "Load public data from OGame into the Galaxytool",
		ADMIN_OGAME_ALL_DATA : "све доступне информације",
		ADMIN_OGAME_GALAXY_DATA : "Преглед галаксије",
		ADMIN_OGAME_STATISTICS_DATA : "Статистике",
		ERRORPAGE_PAGEFORWARD : "Кликни овде уколико Ваш броусер не подржава page forwarding",
		ERRORPAGE_PERMISSION_DENIED : "Немате дозвољен приступ овој страници. Кликни овде да се вратите назад.",
		FLEETS_TITLE : "OGame Galaxytool - Fleet movements",
		FLEETS_ACTUAL_FLEETS : "Current fleet movements",
		FLEETS_YES : "Да",
		FLEETS_NO : "Планете са напоменама",
		FLEETS_DETAILS : "Details",
		FLEETS_MISSION_EXPEDITION : "Expedition",
		FLEETS_MISSION_COLONIZATION : "Colonize",
		FLEETS_MISSION_RECYCLE : "Harvest",
		FLEETS_MISSION_TRANSPORT : "Transport",
		FLEETS_MISSION_DEPLOYMENT : "Deploy",
		FLEETS_MISSION_ESPIONAGE : "Espionage",
		FLEETS_MISSION_ACS_DEFEND : "ACS Defend",
		FLEETS_MISSION_ATTACK : "Attack",
		FLEETS_MISSION_ACS_ATTACK : "ACS Attack",
		FLEETS_MISSION_MOON_DESTRUCTION : "Moon Destruction",
		FLEETS_MISSION_MISSILE_ATTACK : "Missile Attack",
		FLEETS_NO_DATA : "No applicable data found",
		FLEETS_FLEET : "Fleet",
		FLEETS_ALL_FLEETS : "Show all fleet movements",
		COMBAT_REPORT_OUDATED_GALAXYVIEW : "Your galaxy data is outdated. Please visit combat origin and target coordinates first!",
		MESSAGES_TITLE : "OGame Galaxytool - OGame Messages",
		MESSAGES_PLAYERNAME : "Playername",
		MESSAGES_SUBJECT : "Subject",
		MESSAGES_DATE : "Date",
		MESSAGES_FILTER : "Filter",
		MESSAGES_DELETE : "Delete message",
		MESSAGES_PUBLISH_DETAIL : "Publish message by adding the message content to notice text of that player.",
		MESSAGES_PUBLISH_HEADER : "&sender sent a message to &recipient on &date:\n\n &message",
		MESSAGES_PLAYER_FILTER : "Messages for player:",
		MESSAGES_CONTENT : "Content",
		COMBATS_TITLE : "OGame Galaxytool - Combat reports",
		COMBATS_ATTACKER : "Attacker",
		COMBATS_DEFENDER : "Defender",
		COMBATS_DATE : "Date",
		COMBATS_OWNER : "Owner",
		COMBATS_WINNER : "Winner",
		COMBATS_COMBATREPORT : "Combat Report",
		COMBATS_COMBAT_AT : "Combat at",
		COMBATS_LOST_UNITS : "Lost units",
		COMBATS_LOOT : "Loot",
		COMBATS_DEBRIS : "Debris",
		COMBATS_AND : "and",
		COMBATS_PUBLISH : "Make this report public",
		COMBATS_UNPUBLISH : "Unshare this report (makes it private again)",
		COMBATS_DELETE : "Delete report",
		COMBATS_CHECK_ALL : "Check All",
		COMBATS_UNCHECK_ALL : "Uncheck All",
		COMBATS_WITH_SELECTED : "With selected",
		COMBATS_PUBLIC_REPORTS : "Public reports",
		COMBATS_YES : "Да",
		COMBATS_NO : "Планете са напоменама",
		COMBATS_SEARCH_OPTIONS : "Search options",
		COMBATS_SEARCH : "Go",
		COMBATS_RESET : "Reset",
		COMBATS_COORDINATES : "Координате",
		COMBATS_INVALID_GALAXY_ENTERED : "Invalid Galaxy entered",
		COMBATS_INVALID_SYSTEM_ENTERED : "Invalid System entered",
		COMBATS_INVALID_PLANET_ENTERED : "Invalid Planet entered",
		COMBATS_GALAXY_FROM_TO : "Galaxy",
		COMBATS_SYSTEM_FROM_TO : "System",
		COMBATS_PLANET_FROM_TO : "Planet",
		COMBATS_APPLY : "Apply",
		COMBATS_COMBAT_SUMMARY : "Combat report summary",
		COMBATS_DOWNLOAD_CSV : "Download as CSV file",
		REPORT_ARCHIVE_TITLE : "Report archive",
		REPORT_ARCHIVE_COORDINATES : "Coordinates",
		REPORT_ARCHIVE_SCANTIME : "Scan time",
		REPORT_ARCHIVE_DELETE : "Delete these entries",
		REPORT_ARCHIVE_CONFIRM_DELETE : "Do you really want to delete these entries?",
		REPORT_ARCHIVE_GALAXY : "Galaxy",
		REPORT_ARCHIVE_SYSTEM : "System",
		REPORT_ARCHIVE_PLANET : "Planet",
		REPORT_ARCHIVE_MOON : "Moon",
		REPORT_ARCHIVE_DETAILS : "Details",
		REPORT_ARCHIVE_RESOURCES : "Ресурси на сат",
		REPORT_ARCHIVE_HEADER_RESOURCES : "Ресурси",
		REPORT_ARCHIVE_DETAILS_FOR : "Report archive for &1 [&2] (&3)",
		REPORT_ARCHIVE_FLEET_CARGO : "Fleet cargo capacity",
		REPORT_ARCHIVE_IRAK_RANGE : "Interplanetary Missiles range",
		REPORT_ARCHIVE_CHART_TYPE : "Chart type",
		INSTALL_TITLE : "Galaxytool installation for version",
		INSTALL_PROGRESS : "Overall progress",
		INSTALL_STEP : "Step",
		INSTALL_CONTINUE : "Continue",
		INSTALL_VALIDATE : "Validate",
		INSTALL_STEP1 : "Welcome",
		INSTALL_STEP2 : "Writeable check",
		INSTALL_STEP3 : "Database settings",
		INSTALL_STEP4 : "OGame settings",
		INSTALL_STEP5 : "Galaxytool settings",
		INSTALL_STEP6 : "Admin password",
		INSTALL_STEP7 : "Install Galaxytool",
		INSTALL_STEP8 : "Finalize install",
		INSTALL_FILE_DELETE_CHECK : "Please delete install.php and update.php from your webserver.",
		INSTALL_STEP1_PHP_FAILED : "Your PHP version &1 is not working with this Galaxytool version",
		INSTALL_STEP1_FOPEN_FAILED : "Your PHP version does not allow to open webpages with FOPEN() command. This is required to consume the OGame API.",
		INSTALL_STEP1_WELCOME : "Welcome to the installation wizard of the Galaxytool. You will be guided through the installation of the Galaxytool.",
		INSTALL_STEP2_DESCRIPTION : "Make sure your config.php and attributes.php files have write permissions enabled.",
		INSTALL_STEP2_DESCRIPTION2 : "If you don't know, how to achieve this, please take a look here: &1",
		INSTALL_STEP2_FILE_NOT_WRITEABLE : "File is not writeable",
		INSTALL_STEP3_SERVER : "Database server",
		INSTALL_STEP3_USERNAME : "Корисничко име",
		INSTALL_STEP3_PASSWORD : "Шифра",
		INSTALL_STEP3_DBNAME : "Database name",
		INSTALL_STEP3_PREFIX : "Tablename prefix",
		INSTALL_STEP3_ENTER_PREFIX : "E.g. mytool_",
		INSTALL_STEP3_ENTER_SERVER : "Enter the server address. Contact your system admin if necessary. Usually the correct value is localhost.",
		INSTALL_STEP3_ENTER_USERNAME : "Enter the username for database access",
		INSTALL_STEP3_ENTER_PASSWORD : "Enter the password for database access",
		INSTALL_STEP3_ENTER_DBNAME : "Enter the database name which shall be used for installation (must exist)",
		INSTALL_STEP3_CONNECT_FAILED : "Could not establish connection to database server",
		INSTALL_STEP3_DB_FAILED : "Database &1 not found",
		INSTALL_STEP3_MYSQL_VERSION_FAILED : "MySQL version &1 is not working with this Galaxytool version",
		INSTALL_STEP4_URL : "OGame URL",
		OGAME_URL_DETAILS : "Please enter any URL you see when you are logged on to OGame. Based on that URL the tool will derive the OGame API address which can be used to fill data into the Galaxytool without the Galaxytoolbar. This API was introduced with OGame version 4.1.",
		INSTALL_STEP4_UNIVERSE : "OGame Universe",
		INSTALL_STEP4_DEF_TO_DEBRIS : "Defense to debris",
		INSTALL_STEP4_DEBRIS_RATE : "Debris rate",
		INSTALL_STEP4_SPEED_RATE : "Speed rate",
		INSTALL_STEP4_ENTER_UNIVERSE : "Enter your OGame universe name or number (case sensitive).",
		INSTALL_STEP4_UNIVERSE_MISSING : "You must define your universe",
		INSTALL_STEP4_ENTER_URL : "Enter your OGame universe address",
		INSTALL_STEP4_URL_MISSING : "You must define your OGame address",
		INSTALL_STEP4_URL_CHECK_FAILED : "Could not find OGame API at &1",
		INSTALL_STEP4_GETSETTINGS : "Fetch settings",
		INSTALL_STEP5_TOOLNAME : "Galaxytool name",
		INSTALL_STEP5_ENTER_TOOLNAME : "This is the name which will be shown at logon page to identify your Galaxytool",
		INSTALL_STEP5_LANGUAGE : "Default language",
		INSTALL_STEP5_EMAIL_TO : "Email To",
		INSTALL_STEP5_ENTER_EMAIL_TO : "Enter the email address where you would like to receive notifications about registrations",
		INSTALL_STEP5_EMAIL_FROM : "Email From",
		INSTALL_STEP5_ENTER_EMAIL_FROM : "This email address is shown as REPLY for all mails sent from the Galaxytool",
		INSTALL_STEP5_USE_PHPMAILER : "Use PHPMailer",
		INSTALL_STEP5_MAXSHOUTS : "Maximum number of shoutbox entries",
		INSTALL_STEP5_ENTER_USE_PHPMAILER : "Use PHPMailer if your server does not support sending emails by default",
		INSTALL_PHPMAILER_HOST : "SMPT Host",
		INSTALL_PHPMAILER_HOST_EXAMPLE : "e.g. smtp.provider.com",
		INSTALL_PHPMAILER_USER : "SMPT Username",
		INSTALL_PHPMAILER_USER_EXAMPLE : "e.g. user@provider.dcom",
		INSTALL_PHPMAILER_PASS : "SMPT password",
		INSTALL_PHPMAILER_SECURE : "Authentification method (e.g. ssl)",
		INSTALL_PHPMAILER_PORT : "SMTP Port",
		INSTALL_STEP6_INTRO : "Please define a password for the <strong>admin</strong> account which you have to use for your first logon to the Galaxytool after the installation.",
		INSTALL_STEP7_CONFIG : "Configuration file created",
		INSTALL_STEP7_CONFIG_FAILED : "Configuration file not created",
		INSTALL_STEP7_ATTRIBUTES : "Attributes file created",
		INSTALL_STEP7_ATTRIBUTES_FAILED : "Attributes file not created",
		INSTALL_STEP7_CREATED_TABLES : "Database tables created",
		INSTALL_STEP8_INTRO : "You have successfully installed the Galaxytool!",
		INSTALL_STEP8_LOAD_DATA : "Downloading OGame data ...",
		INSTALL_STEP8_LOAD_DATA_FINISHED : "Download of OGame data finished",
		INSTALL_STEP8_DELETE_FILE : "You should now delete the installation files install.php and update.php from your webserver.",
		INSTALL_STEP8_LOGON : "Please logon with the <strong>admin</strong> user and the password you defined earlier.",
		UPDATE_START : "Starting update to version &1",
		UPDATE_STEP_DONE : "Done",
		UPDATE_TITLE : "Galaxytool update for version",
		UPDATE_STEP1_WELCOME : "Welcome to the update wizard of the Galaxytool. You will be guided through the update of the Galaxytool.",
		UPDATE_STEP1_BACKUP_FILES : "As a first step, make a backup of your <strong>config</strong> folder! You will have to replace the configuration content in case of errors.",
		UPDATE_STEP1_BACKUP_DB : "Then make a <a href=\"http://www.ehow.com/how_2036600_create-database-php.html\">backup</a> of your database.",
		UPDATE_STEP1_PROCEED : "Once the backups have been done, you can proceed with your update.",
		UPDATE_STEP1 : "Welcome",
		UPDATE_STEP2 : "Galaxytool settings",
		UPDATE_STEP2_OLD_VERSION : "Previous Galaxytool version",
		UPDATE_STEP3 : "Update Galaxytool",
		UPDATE_STEP3_UPDATE_RUNNING : "Update running, please wait...",
		UPDATE_STEP4 : "Finalize Update",
		UPDATE_STEP4_INTRO : "You have successfully updated the Galaxytool!",
		UPDATE_STEP4_UPDATE_DONE : "Update steps performed.",
		UPDATE_FAILED : "Update failed.",
		GALAXYTOOL_DUMMY_TEXT : "dummy"
	})
);