define(
	({
		REPORT_WHEN : "dana",
		RESOURCES_ON : "Resursi na",
		PLAYER_BANNED : "k",
		PLAYER_VACATION_MODE : "o",
		PLAYER_NOOB : "s",
		PLAYER_INACTIVE : "i",
		PLAYER_LONG_INACTIVE : "I",
		PLAYER_OUTLAW : "o",
		L_USERNAME : "Korisničko ime",
		L_PASSWORD : "Šifra",
		L_LOGINFAILURE : "Korisničko ime ili šifra su pogrešni ili vaš račun nije još aktiviran.",
		L_TOKENFAILURE : "Your logon key is wrong or your account is not activated yet.",
		L_LOGINTEXT : "Molimo vas prijavite se.",
		L_LANGUAGE : "Dostupni jezici:",
		L_TIMEOUT : "Sesija je istekla!",
		L_REGISTER : "Registracija",
		L_PWLOST : "Zaboravljena šifra",
		INDEX_TITLE : "Pregled",
		INDEX_INFO : "Informacije",
		INDEX_ENTRIES : "Broj svih sistema",
		INDEX_ENTRIES_LASTWEEK : "Novi sistemi od prošlog tjedna",
		INDEX_ENTRIES_TO_OLD : "Sistemi stariji od mjesec dana",
		INDEX_REGISTERED_USERS : "Registrirani korisnici",
		INDEX_PAGEFORWARD : "Ako vaš preglednik ne podržava automatsko preusmjeravanje stranica molim vas kliknite ovdje.",
		INDEX_NOTICES : "Objave",
		INDEX_PLAYERS : "Statistike igrača",
		INDEX_ALLIES : "Statistike saveza",
		INDEX_REPORTS : "Izvještaji špijunaže",
		INDEX_VERSION : "Zadnja dostupna verzija za download",
		INDEX_SHOUTBOX : "Shoutbox",
		INDEX_NOENTRY : "Trenutno nema poruka",
		INDEX_COMMENT : "Vaša poruka",
		INDEX_INSERT : "Unesi",
		INDEX_UMOD : "Igrač u modusu odsustva",
		INDEX_LATEST_VERSION : "Nema novije dostupne verzije",
		INDEX_NO_MOONS : "Broj mjeseci",
		INDEX_NO_EMPTY_SYSTEMS : "Broj praznih sistema",
		INDEX_NO_FULL_SYSTEMS : "Broj potpuno punih sistema",
		INDEX_NO_TARGETS : "Broj mogućih meta",
		INDEX_USERINFO : "Broj korisnika",
		INDEX_ONLINE : "Trenutno online",
		INDEX_TODAY : "Danas online",
		INDEX_ALL : "Ukupan broj prijava",
		GENERAL_LOAD_FORM : "Učitaj podatke",
		GENERAL_SAVE_FORM : "Spremi podatke",
		GENERAL_SAVE_AS_TEXT : "Spremi kao",
		GENERAL_SAVE : "Spremi",
		INDEX_USERMANAGEMENT : "Activation Overview",
		INDEX_NEEDADMIN : "Accounts to unlock",
		INDEX_NEEDEMAIL : "Unvalidated Accounts",
		INDEX_TOOLBAR_INFO : "Galaxytool plugin information",
		INDEX_TOOLBAR_URL : "Galaxytool URL",
		INDEX_TOOLBAR_VERSION_REQUIRED : "Requires at least Galaxytool plugin version",
		INDEX_TOOLBAR_INSTALL_GUIDE : "Installation instructions for plugin",
		INDEX_TOOLBAR_TOKEN : "Logon key",
		INDEX_TOOLBAR_NEW_TOKEN : "Get new key",
		INDEX_PLAYERS_WITH_N_PLANETS : "Players with more than &1 planets",
		INDEX_GETTING_STARTED : "Getting started with the Galaxytool",
		INDEX_GETTING_STARTED1 : "Welcome to the Galaxytool!",
		INDEX_GETTING_STARTED2 : "The Galaxytool will help you to analyze what is going on in your OGame universe &1",
		INDEX_GETTING_STARTED3 : "Before you can actually analyze data you have to insert it first. For this you require a browser plugin like the &1 for Firefox.",
		INDEX_GETTING_STARTED4 : "After you installed the plugin, you navigate through your OGame pages as usual and you will see a small status window whenever something was sent to your Galaxytool.",
		INDEX_GETTING_STARTED5 : "Once the plugin inserted data into the Galaxytool, you can start to analyze where the players have their colonies, how many colonies they have, what reports exist or when they are active the most.",
		INDEX_GETTING_STARTED6 : "But it will also help you to analyze how you are progressing if you compare yourself against your competitors or by analyzing your combat reports to see how much you raided during the last days or weeks.",
		INDEX_GETTING_WIKIPAGE : "There are many more features within the Galaxytool.",
		INDEX_GETTING_WIKIPAGE2 : "Check them out at our wiki page.",
		INDEX_GETTING_BOARD : "For feedback or ideas you can use our board:",
		INDEX_GETTING_CHAT1 : "Or visit us at the chatroom:",
		INDEX_GETTING_CHAT2 : "We are not online 24/7 but spare a lot of our free time there, so be patient.",
		INDEX_CLOSE : "Close",
		INDEX_LOGIN : "Login",
		GENERAL_REQUIRED_FIELDS : "Please fill all required fields",
		INDEX_MESSAGES : "Messages",
		INDEX_EXAMPLE : "Example",
		INDEX_INVALID_DATA : "Invalid data",
		GENERAL_COLUMN_HIDE_TITLE : "Manage columns",
		GENERAL_COLUMN_HIDE_INFO : "Please select which columns you want to see in the table.",
		GENERAL_ENTRIES_DELETED : "&1 entries deleted",
		GENERAL_APPLY : "Apply",
		STARTPAGE_GALAXYTOOL_DESCR : "<em>Galaxytool</em> is a tool for the browser game OGame.",
		GENERAL_OVERWRITE : "Overwrite duplicate entry",
		GENERAL_OVERWRITE_QUESTION : "Overwrite?",
		INDEX_OWN_LOGINS : "Your logins",
		GENERAL_OPEN_IN_NEW_WINDOW : "Otvori poveznicu u novom prozoru",
		GENERAL_UNIT_OF_MEASURE_DAYS : "Days",
		PROGRAM_NAME : "OGame Galaxytool",
		SHORTNAME : "Galaxytool",
		BACK_INDEX : "Nazad na početnu stranicu",
		UNIVERSE : "Univerzum",
		MENU_INFO_LINKS : "Informacije",
		MENU_PAGE : "Pregled",
		MENU_DB_SEARCH : "Traži u bazi",
		MENU_DB_NOTICES : "Traži u objavama",
		MENU_DB_REPORTS : "Traži u izvještajima",
		MENU_GALAXYVIEW : "Pregled galaksije",
		MENU_STATISTICS : "Statistike",
		MENU_ALLYHISTORY : "Povijest saveza",
		MENU_FLEET_MOVEMENTS : "Fleet movements",
		MENU_COMBAT_REPORTS : "Combat reports",
		MENU_MESSAGES : "Ingame messages",
		MENU_OPTION_LINKS : "Opcije",
		MENU_DB_REFRESH : "Ubaci u bazu",
		MENU_NOTICES : "Objave",
		MENU_DB_STATUS : "Stanje baze",
		MENU_USEROPTIONS : "Upravljanje korisnicima",
		MENU_USEROPTIONS2 : "Opcije korisnika",
		MENU_USEROPTIONS3 : "Informacije o korisniku",
		MENU_ADMIN : "Administracija",
		MENU_LOGOUT : "Odjava",
		MENU_STUFF : "Ostalo",
		MENU_FORUM_THREAD : "Forum razvojnog tima",
		MENU_DOWNLOADPAGE : "Stranica za download",
		MENU_LANGUAGE : "Jezik",
		MENU_HELP : "Pomoć",
		MENU_TOOLOPTIONS : "Galaxytool opcije",
		PARSER_INFO1 : " je ubačeno u bazu",
		PARSER_ERROR1 : "Greška prilikom ubacivanja ovih koordinata u bazu:",
		PARSER_ERROR2 : "Baza nije pronađena!",
		PARSER_ERROR3 : "Server baze nije pronađen!",
		PARSER_WRONG_UNIVERSE : "Wrong universe - actual: \"&1\"  expected: \"&2\"",
		SHOW_TITLE : "OGame Galaxytool - Stranica za pretragu",
		SHOW_SEARCH : "Traži u bazi",
		SHOW_ALLYSYMBOL : "Tag saveza",
		SHOW_PLAYERNAME : "Ime igrača",
		SHOW_MOONS : "Samo planete sa mjesecom",
		SHOW_NOTICES : "Samo planete sa objavama",
		SHOW_COLONIES : "Samo planete za kolonizaciju",
		SHOW_YES : "Da",
		SHOW_NO : "Ne",
		SHOW_SEARCHRANGE : "Domet",
		SHOW_SEARCH_IN : "Traži u galaksiji",
		SHOW_FROM_SYSTEM : "od sistema",
		SHOW_FROM_PLANET : "od pozicije planete",
		SHOW_TO : "do",
		SHOW_DESCRIPTION : "Možete koristiti * za imena igrača i saveza. <br />Popunite samo ona polja koja želite specifirati.",
		SHOW_SORT_BY : "Sortiraj po ",
		SHOW_GALASYSTEM : "Galaksija/Sistem",
		SHOW_ALLYNAME : "Ime saveza",
		SHOW_SEARCHBUTTON : "Traži",
		SHOW_ADDRESS : "Koordiante",
		SHOW_ALLYSORT : "Savez",
		SHOW_PLANET : "Ime planete",
		SHOW_STATUS : "Status",
		SHOW_CURRENTNESS : "Starost",
		SHOW_PLAYER_STATUS : "Status igrača",
		SHOW_PLAYER_STATUS1 : "svi",
		SHOW_PLAYER_STATUS2 : "moguće mete",
		SHOW_PLAYER_STATUS3 : "inaktivni",
		SHOW_HITS : "Rezultata",
		SHOW_OF : "od",
		SHOW_ASC : "abecedni poredak",
		SHOW_DESC : "obrnuti abecedni poredak",
		SHOW_RESULTS : "Rezultata po stranici",
		SHOW_MOON : "Mjesec",
		SHOW_UKMOONSIZE : "nepoznato",
		SHOW_DF : "RU",
		SHOW_DF_LONG : "Ruševina",
		SHOW_METAL : "M",
		SHOW_METAL_LONG : "Metal",
		SHOW_CRYSTAL : "K",
		SHOW_CRYSTAL_LONG : "Kristal",
		SHOW_BOTH : "oboje zajedno",
		SHOW_AT_LEAST : "(najmanje)",
		SHOW_DATE : "Datum",
		SHOW_DATE_0 : "nije važno",
		SHOW_DATE_1 : "starije od",
		SHOW_DATE_2 : "novije od",
		SHOW_RANK : "Mjesto",
		SHOW_FRANK : "Mjesto Flote",
		SHOW_MEMBERS : "Članovi",
		SHOW_NOTRANKED : "Nije u top 1500",
		SHOW_NOTICERES : "Objave",
		SHOW_REPORTS : "Samo planete sa izvještajima",
		SHOW_REPORTS_SHORT : "Izvještaji",
		SHOW_NOTHING : "Nema rezultata",
		SHOW_ALLIANCE_STATUS : "Status saveza",
		SHOW_NO_STATUS : "bez Statusa",
		SHOW_NAP : "NAP",
		SHOW_ALLIED : "Savezni",
		SHOW_WAR : "Rat",
		SHOW_BOYCOTT : "Bojkotirati",
		SHOW_NEUTRAL : "Neutralni",
		SHOW_OWN : "Vlastiti Savez",
		SHOW_WING : "Wing",
		SHOW_EXT_OPTIONS1 : "Prikaži više opcija za tražiti domet, rang, datum ili ruševine.",
		SHOW_EXT_OPTIONS2 : "Prikaži više opcija za tražiti kolonije, mjesece, izvještaje, bilješke, statistike igrača ili diplomatski status.",
		SHOW_EXT_OPTIONS3 : "Prikaži više opcija za tražiti sortirano od pretraživanih rezultata.",
		SHOW_EXTENDED : "advanced search",
		SHOW_MOON_SELECTION : "Planet with moon",
		SHOW_REPORT_SELECTION : "Planet with report",
		SHOW_FILTER_BY : "Exclude from the list",
		SHOW_FILTER_NONE : "nijedna",
		SHOW_PLAYERS_WITHOUT_PROGRESS : "Show players without score changes within the last few days",
		STATUS_TITLE : "OGame Galaxytool - statusna stranica",
		STATUS_DB_STATUS : "Status baze",
		STATUS_COLOR : "Boja",
		STATUS_AGE1 : "Unos 1 dan star.",
		STATUS_AGE2 : "Unos 2 - 4 dana star.",
		STATUS_AGE3 : "Unos 4 - 7 dana star.",
		STATUS_AGE4 : "Unos 1 - 2 tjedna star.",
		STATUS_AGE5 : "Unos 2 - 4 tjedna star.",
		STATUS_AGE6 : "Unos stariji od 1 mjeseca!",
		STATUS_AGE7 : "Unos nije dostupan.",
		STATUS_ON : "uključeno",
		STYLES_COLOR1 : "Boja1",
		STYLES_COLOR2 : "Boja2",
		STYLES_COLOR3 : "Boja3",
		STYLES_COLOR4 : "Boja4",
		STYLES_COLOR5 : "Boja5",
		STYLES_COLOR6 : "Boja6",
		STYLES_COLOR7 : "Boja7",
		STATUS_DB_LEGEND : "Legend",
		STATUS_GALAXY : "Galaxy Overview",
		USER_TITLE : "OGame Galaxytool - upravljanje korisnicima",
		USER_NAMES : "Korisnik",
		USER_ERROR : "Greška",
		USER_NEWUSER : "Novi korisnik",
		USER_GALAXY : "Galaksija",
		USER_OPTIONS : "Opcije",
		USER_USERNAME : "Korisničko ime",
		USER_PASSWORD : "Šifra",
		USER_PASSWORD_CONFIRM : "Potvrdi šifru",
		USER_SEARCH : "Pretraga",
		USER_INSERT : "Unosi",
		USER_DELETE : "obriši",
		USER_DELETE_Unos : "Da li želite izbrisati korisnika: ",
		USER_STATUS : "Vidi statistiku",
		USER_STYLES : "Izmjeni izgled",
		USER_SUBMIT : "Pošalji",
		USER_RESET : "Poništi",
		USER_YES : "Da",
		USER_NO : "Ne",
		USER_STYLEPATH : "Putanja do styles.css",
		USER_PROBES : "Pregledaj/Pošalji izvještaj špijunaže",
		USER_EMAIL : "Email",
		USER_ERROR1 : "Šifra netočna ili je Email neispravan.",
		USER_ERROR2 : "Email neispravan.",
		USER_INGAME : "Ime u igri",
		USER_ALLYTAG : "Savez",
		USER_ALLYHISTORY : "Pregledaj/Pošalji povijest saveza",
		USER_DIPLOMATIC : "Promijeni diplomatski status",
		USER_STATSPAGE : "Broj unosa na statistici",
		USER_LINKS : "Linkovi",
		USER_LINKS2 : "Format:<br>text;url<br>text2;url2<br>text3;url3",
		USER_EXPORT_TITLE : "Izvezi boje (BB Kodove)",
		USER_BB_COORDINATES : "Koordinate",
		USER_BB_MOON : "Mjesec",
		USER_BB_DEBRIS : "Ruševine",
		USER_BB_ALLY : "Ime saveza",
		USER_BB_ALLYDETAILS : "Detalji saveza",
		USER_BB_PLAYERNAME : "Igrač",
		USER_BB_BANNED : "kažnjen",
		USER_BB_VACATION : "modus odsustva",
		USER_BB_NOOB : "noob",
		USER_BB_INACTIVE : "Inaktivan",
		USER_BB_LONGINACTIVE : "Dugo inaktivan",
		USER_DELETION : "Delete",
		USER_FLEETINFO : "Fleet movements",
		USER_ACTIVITIES : "Player activities",
		USER_MAINTENANCE : "Galaxytool maintenance",
		USER_MANAGEMENT : "Upravljanje korisnicima",
		USER_DELETE_MY_COMBAT_REPORTS : "Delete my combat reports",
		USER_DELETE_MY_MESSAGES : "Delete my messages",
		USER_DELETE_MY_FLEETMOVES : "Delete my fleet movements",
		USER_DELETE_MY_COMBAT_REPORTS_LIMITED : "Delete my combat reports older than &1 days",
		USER_DELETE_MY_MESSAGES_LIMITED : "Delete my messages older than &1 days",
		USER_TABLE_ENTRIES : "Number of search results for each page",
		USER_EXISTS : "User already exists",
		USER_BB_OUTLAW : "Outlaw",
		USER_INVALID_URL : "URL &1 seems to be invalid - URL will be ignored",
		VIEW_TITLE : "OGame Galaxytool - detalji",
		VIEW_NODATA : "Podaci nisu dostupni.",
		VIEW_GALAXY : "Galaksija",
		VIEW_SYSTEM : "Solarni sistem",
		VIEW_POSITION : "Pozicija",
		VIEW_PLANET : "Planeta",
		VIEW_MOON : "Mjesec",
		VIEW_TF : "RU",
		VIEW_PLAYER : "Igrač",
		VIEW_PLAYER_ADD : "(Mjesto / Status)",
		VIEW_ALLY : "Savez",
		VIEW_ALLY_ADD : "(Mjesto / Članova)",
		VIEW_METAL : "M",
		VIEW_CRYSTAL : "K",
		VIEW_COLONISED : "Planeta naseljena",
		VIEW_UKMOONSIZE : "nepoznato",
		VIEW_BACK : "nazad",
		VIEW_NOTICE : "Objave",
		VIEW_REPORTS : "Izvještaji",
		VIEW_MOONPHALANX : "Slijedeći mjeseci mogu skenirati ovaj sistem",
		VIEW_NOMOONS : "Nema mjeseca",
		VIEW_IRAKS : "Slijdeće planete mogu dosegnuti ovaj sistem sa Interplanetarnim raketama",
		VIEW_NOIRAKS : "Nije pronađena ni jedna Interplanetarna raketa",
		VIEW_MOON_DESTROY_CHANCE : "Šansa za uništiti mjesec",
		VIEW_CHANCE_WITH_ONE : "Šansa sa jednom zvijezdom smrti",
		VIEW_CHANCE_WITH_N : "Šansa sa ",
		VIEW_DEATH_STARS : "zvijezda smrti",
		VIEW_DS_DESTROY_CHANCE : "Šanse za izgubiti zvijezdu(e) smrti",
		VIEW_TOP : "Top",
		VIEW_GO : "go",
		VIEW_DIAMETER : "Diameter",
		PW_TITLE : "OGame Galaxytool - promjena šifre",
		OLD_PASSWORD : "stara šifra",
		NEW_PASSWORD : "nova šifra",
		CONFIRM_NEW_PASSWORD : "potvrdi novu šifru",
		PW_MISMATCH : "Šifre se ne poklapaju!",
		PW_ERROR : "Stara šifra nije točna!",
		UPDATE_DONE : "Update uspješan.",
		TIMEZONE_OFFSET : "Pomak vremenske zone na server",
		DELETE_ACCOUNT : "Izbriši ovaj Galaxytool račun",
		DELETE_ACCOUNT_SAFETY_REQUEST : "Dali zaista želite izbrisati ovaj Galaxytool račun?",
		CH_PASSWD_AUTHORIZATION : "Autorizacija",
		CH_PASSWD_ADMIN : "Admin",
		TIMEZONE_OGAME_OFFSET : "Timezone offset to OGame server",
		CH_PASSWD_USER_LANGUAGE : "Change to this language after logon",
		CH_PASSWD_USER_LANGUAGE_NO_CHANGE : "No change",
		CH_PASSWD_EXPAND : "Expanded",
		CH_PASSWD_COLLAPSE : "Collapsed",
		CH_PASSWD_HIDDEN : "Hidden",
		CH_PASSWD_GETTING_STARTED : "Show Getting Started Info after logon",
		CH_PASSWD_PLUGIN : "Show Plugin Info after logon",
		NOTICE_TITLE : "OGame Galaxytool - objave",
		NOTICE_HEADER : "izmjena objava",
		NOTICE_HEADER2 : "Izmjeni svoje objave",
		NOTICE_PUBLIC : "Dostupno drugima ?",
		NOTICE_YES : "da",
		NOTICE_NO : "ne",
		NOTICE_TEXT : "Tekst objave",
		NOTICE_SAVE : "Spremi",
		NOTICE_DELETED : "Unos obrisan",
		NOTICE_SAVED : "Unos spremljen",
		NOTICE_RESULTS : "Svi rezultati",
		NOTICE_USER : "Korisnik",
		NOTICE_DATE : "Datum",
		NOTICE_EDIT : "Izmjeni",
		NOTICE_DELETE : "Obriši",
		NOTICE_NEW : "Kreiraj novi unos",
		NOTICE_NOTPUBLIC : "Objava nije javna.",
		NOTICE_ALL : "sve",
		NOTICE_NONE : "nijedna",
		NOTICE_SEARCH : "Traži u objavama",
		NOTICE_SEARCH_SHORT : "Traži",
		NOTICE_HITS : "Rezultati",
		NOTICE_SHOWRESULTS : "Rezultata po stranici",
		NOTICE_OF : "od",
		NOTICE_NOTHING : "Ni jedan rezultat nije pronađen",
		NOTICE_CHARS : "Znakovi",
		NOTICE_PLAYERNAME : "Igrač",
		NOTICE_SHOWALL : "Prikaži sve objave",
		REPORTS_TITLE : "OGame Galaxytool - Izvještaj špijunaže",
		REPORTS_RESOURCES : "Resursi",
		REPORTS_FLEET : "Flote",
		REPORTS_DEFENCE : "Obrana",
		REPORTS_BUILDINGS : "Zgrade",
		REPORTS_TECHNOLOGY : "Istraživanje",
		REPORTS_MOON : "Mjesec",
		REPORTS_SEARCH : "Traži u izvještajima špijunaže",
		REPORTS_SEARCH_SHORT : "Traži",
		REPORTS_HITS : "Rezultata",
		REPORTS_NOTHING : "Unos nije pronađen",
		REPORTS_ADDRESS : "Adresa",
		REPORTS_CURRENTNESS : "Starost",
		REPORTS_PLAYERNAME : "Ime igrača",
		REPORTS_ALLY : "Savez",
		REPORTS_VIEW : "Pogledaj izvještaj",
		REPORTS_SEARCH_IN : "Traži u galaksiji",
		REPORTS_FROM_SYSTEM : "od sistema",
		REPORTS_TO : "do",
		REPORTS_DELETE : "obriši",
		REPORTS_DELETED : "Unos izbrisan",
		REPORTS_RESULTS : "Rezultata po stranici",
		REPORTS_OF : "od",
		REPORTS_DATE : "Datum",
		REPORTS_DATE_0 : "nije važno",
		REPORTS_DATE_1 : "starije od",
		REPORTS_DATE_2 : "novije od",
		REPORTS_NOTICES : "Objave",
		REPORTS_AT_LEAST_RESOURCES : "Resursi (barem)",
		REPORTS_SEARCH_EXTENDED : "Prošireno pretraživanje",
		REPORTS_FLEET_RESIS : "Bodovi flote",
		REPORTS_DEFENCE_RESIS : "Bodovi obrane",
		REPORTS_ALL_RESIS : "ukupno bodova",
		REPORTS_TECHS : "Tehnologije",
		REPORTS_UNKNOWN_ENTRIES : "nepoznati unosi",
		REPORTS_PARTLY_INSERTED : "djelomično unešeno",
		REPORTS_FOR_ALL_RES : "za sve resurse",
		REPORTS_FOR_TF : "za ruševine",
		REPORTS_KT : "Mali transporter",
		REPORTS_GT : "Veliki transporter",
		REPORTS_SS : "Borbeni brodovi",
		REPORTS_REC : "Recikler",
		REPORTS_RAIDABLE : "Jedino mete za raid",
		REPORTS_ALL_RESOURCES : "svi resursi",
		REPORTS_STUFF : "Ostalo",
		REPORTS_SPEEDSIM : "Simuliraj sa Speedsimom",
		REPORTS_DRAGOSIM : "Simuliraj sa Dragosim",
		REPORTS_STATUS : "Status",
		REPORTS_ERROR : "Greška",
		REPORTS_OWN_REPORTS : "Samo moji izvještaji",
		REPORTS_UPLOAD_BY : "Izvještaj unio",
		REPORTS_DEPTH : "Detaljnost izvještaja",
		REPORTS_FLEET_SCORE : "Bodovi flote",
		REPORTS_DEFENCE_SCORE : "Bodovi obrane",
		REPORTS_HOURS : "hours",
		REPORTS_MAX_RESULTS_HIT : "Your query returned more than &1 hits. Only the first &1 results are show. Please adjust your search request to get less results.",
		REPORTS_OSIMULATE : "Simulate with OSimulate",
		REPORTS_SHOW_ONLY : "Show only",
		REPORTS_SHOW_PLANETS : "Planeta",
		REPORTS_SHOW_MOONS : "Mjesec",
		REPORTS_OWNER : "Reports owned by",
		STATS_TITLE : "OGame Galaxytool - Statistike",
		STATS_TBLHEAD : "Statistike",
		STATS_RANK : "Mjesto",
		STATS_PLAYERNAME : "Ime igrača",
		STATS_ALLYNAME : "Tag saveza",
		STATS_SCORE : "Bodovi",
		STATS_FLEET : "Flota",
		STATS_RESEARCH : "Istraživanje",
		STATS_MEMBERS : "Članovi",
		STATS_STATUS : "Status",
		STATS_NOTHING : "Nema statusa",
		STATS_NAP : "NAP",
		STATS_ALLIED : "Saveznik",
		STATS_WAR : "Rat",
		STATS_BOYCOTT : "Bojkot",
		STATS_NEUTRAL : "Neutralan",
		STATS_OWN : "Vlastiti Savez",
		STATS_WING : "Wing",
		STATS_UPDATE : "Unos od",
		STATS_PLAYERSTATS : "Statistika igrača",
		STATS_ALLYSTATS : "Statistika saveza",
		STATS_DELETE : "Da li želite izbrisati ovaj unos?",
		STATS_CONFIRM_DELETE : "Da li stvarno želite izbrisati ovaj igračev unos?",
		STATS_CHANGE_PLAYER_STATUS : "Statistika igrača",
		STATS_CHANGE_ALLIANCE_STATUS : "Statistika saveza",
		STATS_CHANGE_ALLIANCE_STATUS_HINT : "Svi članovi ovog saveza dobivaju izabrani status. Svaki prijašnji status će biti promijenjen. Možete promijeniti status nekih igrača naknadno.",
		STATS_UNKNOWN : "Ostatak",
		STATS_DETAILS : "Detalji za",
		STATS_PLAYERSTATUS : "Status igrača",
		STATS_IGNORE_STATUS : "svi",
		STATS_ACTIVE : "active",
		STATS_INACTIVE : "Inaktivan",
		STATS_BANNED : "kažnjen",
		STATS_VACATION : "modus odsustva",
		STATS_NOOB : "noob",
		STATS_YES : "Da",
		STATS_NO : "Samo planete sa objavama",
		STATS_SEARCH : "Pretraga",
		STATS_SHOW_GRAPH : "Show details for score distribution",
		STATS_LONG_INACTIVE : "Dugo inaktivan",
		STATS_STANDARD : "Standard Points",
		STATS_MILITARY : "Military Points",
		STATS_ECONOMY : "Economy",
		STATS_HONOUR : "Honour points",
		STATS_MILITARY_BUILD : "Military build",
		STATS_MILITARY_DESTROYED : "Military destroyed",
		STATS_MILITARY_LOST : "Military lost",
		REGISTER_REGISTRATE : "Registracija",
		REGISTER_LOGINNAME : "Korisničko Ime",
		REGISTER_PASSWORD : "Šifra",
		REGISTER_PASSWORD_CONFIRM : "Potvrdi šifru",
		REGISTER_EMAIL : "Email",
		REGISTER_INGAME : "Ime u igri",
		REGISTER_ALLYTAG : "Tag saveza",
		REGISTER_EMAILVERIFICATION : "Provjera emaila",
		REGISTER_EMAILTEXT : "Molimo vas da otvorite ovu stranicu kako bi potvrdili vaš Email na Galaxietool-u.",
		REGISTER_ERROR1 : "Korisničko ime se već koristi!",
		REGISTER_ERROR2 : "Greška prilikom slanja Emaila! Molimo vas da kontaktirate administratora.",
		REGISTER_ERROR3 : "Greška prilikom slanja podataka u bazu!",
		REGISTER_INFO1 : "Vaš račun je uspješno kreiran.",
		REGISTER_INFO2 : "Molimo vas otvorite link u vašem mailu da završite registraciju.",
		REGISTER_INFO3 : "Account je potvrđen, vaš administrator ga sada mora aktivirati!",
		REGISTER_BUTTON : "Nazad na početnu stranicu",
		REGISTER_NEW_SUBJECT : "Novi korisnik registriran na galaxytoolu",
		REGISTER_NEW_MAILTEXT : "Novi korisnik se registrirao.",
		REGISTER_BACK : "Nazad na prvu stranicu",
		REGISTER_MISSING_FIELDS : "Ispuni sva tražena polja",
		REGISTER_ERROR4 : "Email address is not valid.",
		REGISTER_ERROR5 : "Passwords don't match.",
		REGISTER_PWS : "Password strength",
		REGISTER_PWS0 : "very weak",
		REGISTER_PWS1 : "weak",
		REGISTER_PWS2 : "good",
		REGISTER_PWS3 : "strong",
		REGISTER_PWS4 : "very strong",
		REGISTER_EMAIL_USED : "Email Address is already used",
		LOSTPW_TITLE : "Šifra zaboravljena",
		LOSTPW_INFO2 : "Nova šifra je generirana i poslana na vaš mail!",
		LOSTPW_BUTTON1 : "napravi novu šifru",
		LOSTPW_BUTTON2 : "Nazad na početnu stranicu",
		LOSTPW_LOGINNAME : "Korisničko ime",
		LOSTPW_EMAIL : "Email",
		LOSTPW_ERROR1 : "Greška prilikom slanja podataka u bazu!",
		LOSTPW_ERROR2 : "Krivo uneseni podaci!",
		LOSTPW_ERROR3 : "Greška prilikom slanja Emaila! Molimo vas da kontaktirate administratora",
		LOSTPW_EMAIL_SUBJECT : "Vaša nova šifra koju ste zatražili",
		LOSTPW_EMAIL_TEXT1 : "Vaš novi login za Galaxytool",
		LOSTPW_EMAIL_TEXT2 : "Korisničko ime",
		LOSTPW_EMAIL_TEXT3 : "Šifra",
		LOSTPW_INFO1 : "You will receive an email to verify your password reset request.",
		LOSTPW_CONFIRM_RESET_SUBJECT : "Lost password?",
		LOSTPW_CONFIRM_RESET_MESSAGE : "Hello,\n\nyou requested a password reset for the Galaxytool. To generate a new password, click the following link:",
		USERINFO_TITLE : "OGame Galaxietool - informacije o korisniku",
		USERINFO_NAMES : "Svi korisnici",
		USERINFO_DETAIL : "detaljne informacije o",
		USERINFO_ERROR1 : "Ne postoji korisnik sa ovim ID!",
		USERINFO_USERNAME : "Korisničko ime",
		USERINFO_INGAME : "Ime u igri",
		USERINFO_EMAIL : "Email",
		USERINFO_ALLYTAG : "Savez",
		USERINFO_STYLEPATH : "Skin",
		USERINFO_STATUS : "Status",
		USERINFO_ACTIVATE : "Aktiviraj igrača",
		USERINFO_LOGINS : "Broj prijava",
		USERINFO_LASTLOGIN : "Zadnja prijava",
		USERINFO_DATA : "Informacije o sistemima koje je korisnik unio",
		USERINFO_NODATA : "Ovaj korisnik još uvjek nije unio niti jedan sistem!",
		USERINFO_GALAXY : "Galaksija",
		USERINFO_SYSTEMS : "Broj sistema",
		USERINFO_IP : "IP adresa",
		USERINFO_LOGINTIME : "Prijava",
		USERINFO_NOLOGIN : "Ovaj korisnik se do sada nije nikada prijavio.",
		USERINFO_LAST_GALAXYUPDATE : "Zadnji unos u izgled galaksije",
		USERINFO_LAST_PUBLIC_NOTICE : "Zadnja javna objava",
		USERINFO_LAST_PRIVATE_NOTICE : "Zadnja privatna objava",
		USERINFO_NUMBEROF_PUBLIC_NOTICE : "Broj javnih objava",
		USERINFO_NUMBEROF_PRIVATE_NOTICE : "Broj privatnih objava",
		USERINFO_ACTIVATED : "Korisnički račun aktiviran",
		USERINFO_ACTIVATIONTEXT : "Galaxytool administrator je aktivirao vaš korisnički račun. Uživajte u Galaxytool-u!",
		USERINFO_LAST_SUBMIT : "Inserted last data",
		ALLYHISTORY_TITLE : "OGame Galaxytool - povijest Saveza",
		ALLYHISTORY_TBLHEAD : "Povijesni pregled",
		ALLYHISTORY_PLAYERNAME : "Igrač",
		ALLYHISTORY_ALLYNAME : "Savez",
		ALLYHISTORY_LASTMONTH : "Prošli mjesec",
		ALLYHISTORY_ALL_DATA : "sve dostupne informacije",
		ALLYHISTORY_SHOW : "prikaži statistiku",
		ALLYHISTORY_TIMESPAN : "Vremenski Interval",
		ALLYHISTORY_PROGESS : "Napredak",
		ALLYHISTORY_SCORE : "Bodovi",
		ALLYHISTORY_FSCORE : "Bodovi Flote",
		ALLYHISTORY_RSCORE : "Bodovi Istraživanja",
		ALLYHISTORY_MEMBER : "Članovi",
		ALLYHISTORY_NOTHING : "ništa nije pronađeno",
		ALLYHISTORY_DETAILS : "Detalji",
		ALLYHISTORY_SHOW_ADDRESS : "Koordinate",
		ALLYHISTORY_ESCORE : "Economy",
		ALLYHISTORY_MSCORE : "Military Points",
		DETAILEDINFO_PLAYERINFO_TITLE : "Informacije igrača",
		DETAILEDINFO_ALLYINFO_TITLE : "Informacije saveza",
		DETAILEDINFO_PLAYERINFO_TBLHEAD : "Detaljne informacije o igraču",
		DETAILEDINFO_ALLYINFO_TBLHEAD : "Detaljne informacije o savezu",
		DETAILEDINFO_NO_ALLIANCE : "ništa",
		DETAILEDINFO_SCORE : "Statistike bodova",
		DETAILEDINFO_FLEET : "Statistike flote",
		DETAILEDINFO_RESEARCH : "Statistike istraživanja",
		DETAILEDINFO_RANK : "Pozicija",
		DETAILEDINFO_POINTS : "Bodovi",
		DETAILEDINFO_KNOWN_PLANETS : "poznate planete",
		DETAILEDINFO_MOONS : "poznati mjeseci",
		DETAILEDINFO_PHALANX_AREA : "Područje za falangiranje",
		DETAILEDINFO_NO_PHALANX_AREA : "Falanga nije pronađena",
		DETAILEDINFO_NOTICES : "Objave",
		DETAILEDINFO_NO_NOTICES : "Nema pronađenih objava",
		DETAILEDINFO_PREVIOUS_ALLIANCES : "prošli savez",
		DETAILEDINFO_RESOURCES_PER_HOUR : "Resursa po satu",
		DETAILEDINFO_RESOURCES_PER_DAY : "Resursa na dan",
		DETAILEDINFO_RESOURCES_PER_WEEK : "Resursa na tjedan",
		DETAILEDINFO_RESOURCES_PER_MONTH : "Resursa na mjesec (30 dana)",
		DETAILEDINFO_METAL : "Metal",
		DETAILEDINFO_CRYSTAL : "Kristal",
		DETAILEDINFO_DEUTERIUM : "Deuterij",
		DETAILEDINFO_UNKNOWN : "nepoznato",
		DETAILEDINFO_SCORE_DISTRIBUTION : "Raspodjela Bodova",
		DETAILEDINFO_GENERAL : "Detalji",
		DETAILEDINFO_MEMBERS : "Članovi",
		DETAILEDINFO_GRAPHS : "Grafovi",
		DETAILEDINFO_RESOURCES : "Resursi",
		DETAILEDINFO_FLEET_TAB : "Flote",
		DETAILEDINFO_TECH : "Istraživanja",
		DETAILEDINFO_FLEET_DETAIL : "Suma / (prosječan igrač) kroz sve dostupne izvještaje",
		DETAILEDINFO_TECH_DETAIL : "Prosjek svih dostupnih informacija o igračima",
		DETAILEDINFO_PLANET_TAB : "Planeta",
		DETAILEDINFO_MOON_TAB : "Mjesec",
		DETAILEDINFO_ACTIVITIES : "Activities",
		DETAILEDINFO_NODATA : "Podaci nisu dostupni.",
		DETAILEDINFO_ACTIVITY_DESCRIPTION : "Show activities of &1 collected from:",
		DETAILEDINFO_GALAXYVIEWS : "Galaxy views",
		DETAILEDINFO_SCANS : "Espionage actions",
		DETAILEDINFO_MESSAGES : "Player messages",
		DETAILEDINFO_COMBATS : "Combat reports",
		DETAILEDINFO_ALLYPAGE : "Alliance overview",
		DETAILEDINFO_MANUAL : "Manual insertions",
		DETAILEDINFO_START : "Beginning",
		DETAILEDINFO_TO : "to",
		DETAILEDINFO_TODAY : "Today",
		DETAILEDINFO_DATA_RESTRICTION : "restricted to:",
		DETAILEDINFO_WEEKDAY_WEEKEND : "Weekend",
		DETAILEDINFO_WEEKDAY_WORKINGDAY : "Weekday",
		DETAILEDINFO_WEEKDAY_MONDAY : "Monday",
		DETAILEDINFO_WEEKDAY_TUESDAY : "Tuesday",
		DETAILEDINFO_WEEKDAY_WEDNESDAY : "Wednesday",
		DETAILEDINFO_WEEKDAY_THURSDAY : "Thursday",
		DETAILEDINFO_WEEKDAY_FRIDAY : "Friday",
		DETAILEDINFO_WEEKDAY_SATURDAY : "Saturday",
		DETAILEDINFO_WEEKDAY_SUNDAY : "Sunday",
		DETAILEDINFO_WEEKDAY_SHORTLENGTH : 3,
		DETAILEDINFO_PLAYER_CURRENTLY_ACTIVE : "The player is currently active",
		DETAILEDINFO_PLAYER_MESSAGES : "available player messages",
		DETAILEDINFO_SHOW : "show",
		DETAILEDINFO_NONE : "none available",
		DETAILEDINFO_ENTER_MANUALLY : "Enter activities for this player",
		DETAILEDINFO_PLAYER_SEEN_ON : "Player was online on",
		DETAILEDINFO_INSERT : "Insert",
		DETAILEDINFO_OGAME_SERVERTIMES : "Please note: All dates and times refer to OGame server times !",
		DETAILEDINFO_DAY_VIEW : "24 hours view",
		DETAILEDINFO_WEEK_VIEW : "weekly view",
		DETAILEDINFO_HOME_PLANET : "Homeworld",
		DETAILEDINFO_PLANETNAME : "Name",
		DETAILEDINFO_DEFENCE_SCORE : "Defence score",
		DETAILEDINFO_DEFENCE_SCORE_TOOLTIP : "Defence score = Fleet - Score + Research + Economy.<br/>All those statistics must be up to date to have a meaningful result!",
		DETAILEDINFO_SCORE_PER_SHIP : "Scores per ship",
		DETAILEDINFO_SHIPS : "Number of ships",
		DETAILEDINFO_DATE_IN_FUTURE : "Do not maintain times which are not in the past.",
		ADMIN_TITLE : "Administracija Galaxytool-a",
		ADMIN_DISCLAMER : "Upozorenje: Pokrenite ove skripte na vlastiti rizik! Večina od njih briše podatke.",
		ADMIN_INCONSISTENCIES : "Nekonzistentnost baze",
		ADMIN_PLANETS : "Planeti na poziciji 0 ili većoj od 15",
		ADMIN_GALAXIES : "Izbriši galaksije veće od &1 ",
		ADMIN_PLAYERS : "Izbriši igrače bez OGame oznake igrača - dovodi do dupih unosa igrača",
		ADMIN_REPORTS : "Izbriši izvještaje za planete koji više ne postoje",
		ADMIN_MISC : "Razno",
		ADMIN_RESET : "Reset Galaxytool (samo se korisnici i ip tablica neće izbrisati)",
		ADMIN_OLD_PLAYERS : "Izbriši unose igrača starije od &1 dana",
		ADMIN_OLD_REPORTS : "Izbriši izvještaje starije od &1 dana",
		ADMIN_LOADING : "Ne zatvaraj ovaj prozor dok se stranica ne učita.",
		ADMIN_STATUS : "Status vaših zahtjeva",
		ADMIN_SELECTION : "Najmanje jedan unos mora biti označen",
		ADMIN_SAFETY : "Dali ste sigurni da želite pokrenuti ove skripte?",
		ADMIN_DONE : "Izvršeno",
		ADMIN_NOTBD : "Ništa za izvršiti",
		ADMIN_OLD_GALAXIES : "Odstrani preglede galaksije starije od &1 dana",
		ADMIN_UNUSED_PLAYERS : "Odstrani igrače koji se ne pojavljuju u nijednom pregledu galaksije",
		ADMIN_OLD_ACTIVITIES : "Remove player activities older than &1 days",
		ADMIN_OLD_COMBATS : "Remove combat reports older than &1 days",
		ADMIN_OLD_INGAME_MSG : "Remove ingame messages older than &1 days",
		ADMIN_OGAME_API : "Load public data from OGame into the Galaxytool",
		ADMIN_OGAME_ALL_DATA : "sve dostupne informacije",
		ADMIN_OGAME_GALAXY_DATA : "Pregled galaksije",
		ADMIN_OGAME_STATISTICS_DATA : "Statistike",
		ERRORPAGE_PAGEFORWARD : "Click here if your browser does not support page forwarding",
		ERRORPAGE_PERMISSION_DENIED : "You don't have the permission to enter this page. Click to go back.",
		FLEETS_TITLE : "OGame Galaxytool - Fleet movements",
		FLEETS_ACTUAL_FLEETS : "Current fleet movements",
		FLEETS_YES : "Da",
		FLEETS_NO : "Samo planete sa objavama",
		FLEETS_DETAILS : "Details",
		FLEETS_MISSION_EXPEDITION : "Expedition",
		FLEETS_MISSION_COLONIZATION : "Colonize",
		FLEETS_MISSION_RECYCLE : "Harvest",
		FLEETS_MISSION_TRANSPORT : "Transport",
		FLEETS_MISSION_DEPLOYMENT : "Deploy",
		FLEETS_MISSION_ESPIONAGE : "Espionage",
		FLEETS_MISSION_ACS_DEFEND : "ACS Defend",
		FLEETS_MISSION_ATTACK : "Attack",
		FLEETS_MISSION_ACS_ATTACK : "ACS Attack",
		FLEETS_MISSION_MOON_DESTRUCTION : "Moon Destruction",
		FLEETS_MISSION_MISSILE_ATTACK : "Missile Attack",
		FLEETS_NO_DATA : "No applicable data found",
		FLEETS_FLEET : "Fleet",
		FLEETS_ALL_FLEETS : "Show all fleet movements",
		COMBAT_REPORT_OUDATED_GALAXYVIEW : "Your galaxy data is outdated. Please visit combat origin and target coordinates first!",
		MESSAGES_TITLE : "OGame Galaxytool - OGame Messages",
		MESSAGES_PLAYERNAME : "Playername",
		MESSAGES_SUBJECT : "Subject",
		MESSAGES_DATE : "Date",
		MESSAGES_FILTER : "Filter",
		MESSAGES_DELETE : "Delete message",
		MESSAGES_PUBLISH_DETAIL : "Publish message by adding the message content to notice text of that player.",
		MESSAGES_PUBLISH_HEADER : "&sender sent a message to &recipient on &date:\n\n &message",
		MESSAGES_PLAYER_FILTER : "Messages for player:",
		MESSAGES_CONTENT : "Content",
		COMBATS_TITLE : "OGame Galaxytool - Combat reports",
		COMBATS_ATTACKER : "Attacker",
		COMBATS_DEFENDER : "Defender",
		COMBATS_DATE : "Date",
		COMBATS_OWNER : "Owner",
		COMBATS_WINNER : "Winner",
		COMBATS_COMBATREPORT : "Combat Report",
		COMBATS_COMBAT_AT : "Combat at",
		COMBATS_LOST_UNITS : "Lost units",
		COMBATS_LOOT : "Loot",
		COMBATS_DEBRIS : "Debris",
		COMBATS_AND : "and",
		COMBATS_PUBLISH : "Make this report public",
		COMBATS_UNPUBLISH : "Unshare this report (makes it private again)",
		COMBATS_DELETE : "Delete report",
		COMBATS_CHECK_ALL : "Check All",
		COMBATS_UNCHECK_ALL : "Uncheck All",
		COMBATS_WITH_SELECTED : "With selected",
		COMBATS_PUBLIC_REPORTS : "Public reports",
		COMBATS_YES : "Da",
		COMBATS_NO : "Samo planete sa objavama",
		COMBATS_SEARCH_OPTIONS : "Search options",
		COMBATS_SEARCH : "Go",
		COMBATS_RESET : "Reset",
		COMBATS_COORDINATES : "Koordinate",
		COMBATS_INVALID_GALAXY_ENTERED : "Invalid Galaxy entered",
		COMBATS_INVALID_SYSTEM_ENTERED : "Invalid System entered",
		COMBATS_INVALID_PLANET_ENTERED : "Invalid Planet entered",
		COMBATS_GALAXY_FROM_TO : "Galaxy",
		COMBATS_SYSTEM_FROM_TO : "System",
		COMBATS_PLANET_FROM_TO : "Planet",
		COMBATS_APPLY : "Apply",
		COMBATS_COMBAT_SUMMARY : "Combat report summary",
		COMBATS_DOWNLOAD_CSV : "Download as CSV file",
		REPORT_ARCHIVE_TITLE : "Report archive",
		REPORT_ARCHIVE_COORDINATES : "Coordinates",
		REPORT_ARCHIVE_SCANTIME : "Scan time",
		REPORT_ARCHIVE_DELETE : "Delete these entries",
		REPORT_ARCHIVE_CONFIRM_DELETE : "Do you really want to delete these entries?",
		REPORT_ARCHIVE_GALAXY : "Galaxy",
		REPORT_ARCHIVE_SYSTEM : "System",
		REPORT_ARCHIVE_PLANET : "Planet",
		REPORT_ARCHIVE_MOON : "Moon",
		REPORT_ARCHIVE_DETAILS : "Details",
		REPORT_ARCHIVE_RESOURCES : "Resursa po satu",
		REPORT_ARCHIVE_HEADER_RESOURCES : "Resursi",
		REPORT_ARCHIVE_DETAILS_FOR : "Report archive for &1 [&2] (&3)",
		REPORT_ARCHIVE_FLEET_CARGO : "Fleet cargo capacity",
		REPORT_ARCHIVE_IRAK_RANGE : "Interplanetary Missiles range",
		REPORT_ARCHIVE_CHART_TYPE : "Chart type",
		INSTALL_TITLE : "Galaxytool installation for version",
		INSTALL_PROGRESS : "Overall progress",
		INSTALL_STEP : "Step",
		INSTALL_CONTINUE : "Continue",
		INSTALL_VALIDATE : "Validate",
		INSTALL_STEP1 : "Welcome",
		INSTALL_STEP2 : "Writeable check",
		INSTALL_STEP3 : "Database settings",
		INSTALL_STEP4 : "OGame settings",
		INSTALL_STEP5 : "Galaxytool settings",
		INSTALL_STEP6 : "Admin password",
		INSTALL_STEP7 : "Install Galaxytool",
		INSTALL_STEP8 : "Finalize install",
		INSTALL_FILE_DELETE_CHECK : "Please delete install.php and update.php from your webserver.",
		INSTALL_STEP1_PHP_FAILED : "Your PHP version &1 is not working with this Galaxytool version",
		INSTALL_STEP1_FOPEN_FAILED : "Your PHP version does not allow to open webpages with FOPEN() command. This is required to consume the OGame API.",
		INSTALL_STEP1_WELCOME : "Welcome to the installation wizard of the Galaxytool. You will be guided through the installation of the Galaxytool.",
		INSTALL_STEP2_DESCRIPTION : "Make sure your config.php and attributes.php files have write permissions enabled.",
		INSTALL_STEP2_DESCRIPTION2 : "If you don't know, how to achieve this, please take a look here: &1",
		INSTALL_STEP2_FILE_NOT_WRITEABLE : "File is not writeable",
		INSTALL_STEP3_SERVER : "Database server",
		INSTALL_STEP3_USERNAME : "Korisničko ime",
		INSTALL_STEP3_PASSWORD : "Šifra",
		INSTALL_STEP3_DBNAME : "Database name",
		INSTALL_STEP3_PREFIX : "Tablename prefix",
		INSTALL_STEP3_ENTER_PREFIX : "E.g. mytool_",
		INSTALL_STEP3_ENTER_SERVER : "Enter the server address. Contact your system admin if necessary. Usually the correct value is localhost.",
		INSTALL_STEP3_ENTER_USERNAME : "Enter the username for database access",
		INSTALL_STEP3_ENTER_PASSWORD : "Enter the password for database access",
		INSTALL_STEP3_ENTER_DBNAME : "Enter the database name which shall be used for installation (must exist)",
		INSTALL_STEP3_CONNECT_FAILED : "Could not establish connection to database server",
		INSTALL_STEP3_DB_FAILED : "Database &1 not found",
		INSTALL_STEP3_MYSQL_VERSION_FAILED : "MySQL version &1 is not working with this Galaxytool version",
		INSTALL_STEP4_URL : "OGame URL",
		OGAME_URL_DETAILS : "Please enter any URL you see when you are logged on to OGame. Based on that URL the tool will derive the OGame API address which can be used to fill data into the Galaxytool without the Galaxytoolbar. This API was introduced with OGame version 4.1.",
		INSTALL_STEP4_UNIVERSE : "OGame Universe",
		INSTALL_STEP4_DEF_TO_DEBRIS : "Defense to debris",
		INSTALL_STEP4_DEBRIS_RATE : "Debris rate",
		INSTALL_STEP4_SPEED_RATE : "Speed rate",
		INSTALL_STEP4_ENTER_UNIVERSE : "Enter your OGame universe name or number (case sensitive).",
		INSTALL_STEP4_UNIVERSE_MISSING : "You must define your universe",
		INSTALL_STEP4_ENTER_URL : "Enter your OGame universe address",
		INSTALL_STEP4_URL_MISSING : "You must define your OGame address",
		INSTALL_STEP4_URL_CHECK_FAILED : "Could not find OGame API at &1",
		INSTALL_STEP4_GETSETTINGS : "Fetch settings",
		INSTALL_STEP5_TOOLNAME : "Galaxytool name",
		INSTALL_STEP5_ENTER_TOOLNAME : "This is the name which will be shown at logon page to identify your Galaxytool",
		INSTALL_STEP5_LANGUAGE : "Default language",
		INSTALL_STEP5_EMAIL_TO : "Email To",
		INSTALL_STEP5_ENTER_EMAIL_TO : "Enter the email address where you would like to receive notifications about registrations",
		INSTALL_STEP5_EMAIL_FROM : "Email From",
		INSTALL_STEP5_ENTER_EMAIL_FROM : "This email address is shown as REPLY for all mails sent from the Galaxytool",
		INSTALL_STEP5_USE_PHPMAILER : "Use PHPMailer",
		INSTALL_STEP5_MAXSHOUTS : "Maximum number of shoutbox entries",
		INSTALL_STEP5_ENTER_USE_PHPMAILER : "Use PHPMailer if your server does not support sending emails by default",
		INSTALL_PHPMAILER_HOST : "SMPT Host",
		INSTALL_PHPMAILER_HOST_EXAMPLE : "e.g. smtp.provider.com",
		INSTALL_PHPMAILER_USER : "SMPT Username",
		INSTALL_PHPMAILER_USER_EXAMPLE : "e.g. user@provider.dcom",
		INSTALL_PHPMAILER_PASS : "SMPT password",
		INSTALL_PHPMAILER_SECURE : "Authentification method (e.g. ssl)",
		INSTALL_PHPMAILER_PORT : "SMTP Port",
		INSTALL_STEP6_INTRO : "Please define a password for the <strong>admin</strong> account which you have to use for your first logon to the Galaxytool after the installation.",
		INSTALL_STEP7_CONFIG : "Configuration file created",
		INSTALL_STEP7_CONFIG_FAILED : "Configuration file not created",
		INSTALL_STEP7_ATTRIBUTES : "Attributes file created",
		INSTALL_STEP7_ATTRIBUTES_FAILED : "Attributes file not created",
		INSTALL_STEP7_CREATED_TABLES : "Database tables created",
		INSTALL_STEP8_INTRO : "You have successfully installed the Galaxytool!",
		INSTALL_STEP8_LOAD_DATA : "Downloading OGame data ...",
		INSTALL_STEP8_LOAD_DATA_FINISHED : "Download of OGame data finished",
		INSTALL_STEP8_DELETE_FILE : "You should now delete the installation files install.php and update.php from your webserver.",
		INSTALL_STEP8_LOGON : "Please logon with the <strong>admin</strong> user and the password you defined earlier.",
		UPDATE_START : "Starting update to version &1",
		UPDATE_STEP_DONE : "Done",
		UPDATE_TITLE : "Galaxytool update for version",
		UPDATE_STEP1_WELCOME : "Welcome to the update wizard of the Galaxytool. You will be guided through the update of the Galaxytool.",
		UPDATE_STEP1_BACKUP_FILES : "As a first step, make a backup of your <strong>config</strong> folder! You will have to replace the configuration content in case of errors.",
		UPDATE_STEP1_BACKUP_DB : "Then make a <a href=\"http://www.ehow.com/how_2036600_create-database-php.html\">backup</a> of your database.",
		UPDATE_STEP1_PROCEED : "Once the backups have been done, you can proceed with your update.",
		UPDATE_STEP1 : "Welcome",
		UPDATE_STEP2 : "Galaxytool settings",
		UPDATE_STEP2_OLD_VERSION : "Previous Galaxytool version",
		UPDATE_STEP3 : "Update Galaxytool",
		UPDATE_STEP3_UPDATE_RUNNING : "Update running, please wait...",
		UPDATE_STEP4 : "Finalize Update",
		UPDATE_STEP4_INTRO : "You have successfully updated the Galaxytool!",
		UPDATE_STEP4_UPDATE_DONE : "Update steps performed.",
		UPDATE_FAILED : "Update failed.",
		GALAXYTOOL_DUMMY_TEXT : "dummy"
	})
);