define(
	({
		REPORT_WHEN : "dňa",
		RESOURCES_ON : "Zdroje na",
		PLAYER_BANNED : "b",
		PLAYER_VACATION_MODE : "v",
		PLAYER_NOOB : "n",
		PLAYER_INACTIVE : "i",
		PLAYER_LONG_INACTIVE : "I",
		PLAYER_OUTLAW : "o",
		L_USERNAME : "Užívateľské meno",
		L_PASSWORD : "Heslo",
		L_LOGINFAILURE : "Užívateľské meno alebo heslo je nesprávne, alebo doposiaľ nemáte aktivovaný účet.",
		L_TOKENFAILURE : "Váš prihlasovací kľúč je nesprávny alebo Váš účet ešte nebol potvrdený.",
		L_LOGINTEXT : "Prihláste sa prosím.",
		L_LANGUAGE : "Dostupné jazyky:",
		L_TIMEOUT : "Čas spojenia vypršal!",
		L_REGISTER : "Registrácia",
		L_PWLOST : "Zabudnuté heslo",
		INDEX_TITLE : "OGame Galaxietool - Prehľad",
		INDEX_INFO : "Informácie",
		INDEX_ENTRIES : "Počet všetkých systémov",
		INDEX_ENTRIES_LASTWEEK : "Nové systémy za minulý týždeň",
		INDEX_ENTRIES_TO_OLD : "Systémy staršie ako jeden mesiac",
		INDEX_REGISTERED_USERS : "Registrovaní užívatelia",
		INDEX_PAGEFORWARD : "Ak Váš prehliadač nepodporuje presmerovanie, kliknite prosím sem.",
		INDEX_NOTICES : "Poznámky",
		INDEX_PLAYERS : "Štatistika hráčov",
		INDEX_ALLIES : "Štatistika spojencov",
		INDEX_REPORTS : "Špionážne správy",
		INDEX_VERSION : "Kontrola novej verzie na stiahnutie",
		INDEX_LATEST_VERSION : "Novšia verzia nie je dostupná",
		INDEX_SHOUTBOX : "Shoutbox",
		INDEX_NOENTRY : "Žiaden odkaz",
		INDEX_COMMENT : "Váš odkaz",
		INDEX_INSERT : "Vložiť",
		INDEX_UMOD : "Hráčov s zmrazeným účtom",
		INDEX_NO_MOONS : "Počet Mesiacov",
		INDEX_NO_EMPTY_SYSTEMS : "Počet prázdnych systémov",
		INDEX_NO_FULL_SYSTEMS : "Počet úplne zaplnených systémov",
		INDEX_NO_TARGETS : "Počet možných cieľov",
		INDEX_USERINFO : "Užívatelia",
		INDEX_ONLINE : "Momentálne online",
		INDEX_TODAY : "Dnes online",
		INDEX_ALL : "Celkový počet prihlásení",
		GENERAL_LOAD_FORM : "Načítať údaje formulára",
		GENERAL_SAVE_FORM : "Uložiť údaje formulára",
		GENERAL_SAVE_AS_TEXT : "Uložiť ako",
		GENERAL_SAVE : "Uložiť",
		INDEX_USERMANAGEMENT : "Prehľad aktivácie",
		INDEX_NEEDADMIN : "Účty na odomknutie",
		INDEX_NEEDEMAIL : "Nepotvrdené účty",
		INDEX_TOOLBAR_INFO : "Galaxytool plugin informácie",
		INDEX_TOOLBAR_URL : "Galaxytool URL adresa",
		INDEX_TOOLBAR_VERSION_REQUIRED : "Vyžaduje verziu Galaxytool pluginu aspoň",
		INDEX_TOOLBAR_INSTALL_GUIDE : "Inštrukcie pre inštaláciu pluginu",
		INDEX_TOOLBAR_TOKEN : "Prihlasovací kľúč",
		INDEX_TOOLBAR_NEW_TOKEN : "Získať nový kľúč",
		INDEX_PLAYERS_WITH_N_PLANETS : "Hráči s viac než &1 planétami",
		INDEX_GETTING_STARTED : "Začíname s Galaxytool",
		INDEX_GETTING_STARTED1 : "Vitajte v Galaxytool!",
		INDEX_GETTING_STARTED2 : "Galaxytool Vám pomôže analyzovať čo sa deje vo Vašom OGame vesmíre &1",
		INDEX_GETTING_STARTED3 : "Predtým, ako môžete analyzovať dáta, ich musíte najskôr vložiť. Na to potrebujete plugin pre prehliadač ako &1 pre Firefox.",
		INDEX_GETTING_STARTED4 : "Po nainštalovaní pluginu sa pohybujte v OGame stránkach ako zvyčajne a v ľavom hornom rohu uvidíte informačné okno vždy, keď sa posielajú dáta do Galaxytoolu.",
		INDEX_GETTING_STARTED5 : "Akonáhle plugin vloží dáta do Galaxytoolu, môžete začať analyzovať, kde majú hráči kolónie, koľko ich majú, aké správy o nich existujú alebo kedy sú najčastejšie aktívne.",
		INDEX_GETTING_STARTED6 : "Ale pomôže Vám to aj analyzovať ako postupujete ak sa porovnáte so svojími protivníkmi alebo analýzou Vaších bojových správ aby ste videli, koľko ste ulúpili za posledné dni alebo týždne.",
		INDEX_GETTING_WIKIPAGE : "Galaxytool poskytuje mnoho ďalších funkcií.",
		INDEX_GETTING_WIKIPAGE2 : "Pozrite si ich na našej wiki stránke.",
		INDEX_GETTING_BOARD : "Pre spätnú väzbu alebo návrhy môžete použiť naše fórum:",
		INDEX_GETTING_CHAT1 : "Alebo nás navštíviť v chatovacej miestnosti:",
		INDEX_GETTING_CHAT2 : "Nie sme online 24/7 ale trávime tam veľa nášho voľného času, tak buďte trpezlivý.",
		INDEX_CLOSE : "Zavrieť",
		INDEX_LOGIN : "Prihlásiť",
		GENERAL_REQUIRED_FIELDS : "Prosím, vyplňte všetky požadované polia",
		INDEX_MESSAGES : "Správy",
		INDEX_EXAMPLE : "Príklad",
		INDEX_INVALID_DATA : "Neplatné dáta",
		GENERAL_COLUMN_HIDE_TITLE : "Spravovať stĺpce",
		GENERAL_COLUMN_HIDE_INFO : "Prosím, vyberte, ktoré stĺpce chcete vidieť v tabuľke.",
		GENERAL_ENTRIES_DELETED : "&1 záznamov vymazaných",
		GENERAL_APPLY : "Použiť",
		STARTPAGE_GALAXYTOOL_DESCR : "<em>Galaxytool</em> je nástroj na prehliadačovú hru OGame.",
		GENERAL_OVERWRITE : "Prepísať duplicitný záznam",
		GENERAL_OVERWRITE_QUESTION : "Prepísať?",
		INDEX_OWN_LOGINS : "Vaše prihlásenia",
		GENERAL_OPEN_IN_NEW_WINDOW : "Otvoriť odkaz v novom okne",
		GENERAL_UNIT_OF_MEASURE_DAYS : "Days",
		PROGRAM_NAME : "OGame Galaxytool",
		SHORTNAME : "Galaxytool",
		BACK_INDEX : "Späť na hlavnú stranu",
		UNIVERSE : "Vesmír",
		MENU_INFO_LINKS : "Informácie",
		MENU_PAGE : "Prehľad",
		MENU_DB_SEARCH : "Vyhľadať v databáze",
		MENU_DB_NOTICES : "Vyhľadať v poznámkach",
		MENU_DB_REPORTS : "Vyhľadať v správach",
		MENU_GALAXYVIEW : "Prezrieť Galaxiu",
		MENU_STATISTICS : "Štatistiky",
		MENU_ALLYHISTORY : "Historický prehľad",
		MENU_FLEET_MOVEMENTS : "Pohyby flotily",
		MENU_COMBAT_REPORTS : "Bojové správy",
		MENU_MESSAGES : "Správy z hry",
		MENU_OPTION_LINKS : "Možnosti",
		MENU_DB_REFRESH : "Vložiť do databázy",
		MENU_NOTICES : "Poznámky",
		MENU_DB_STATUS : "Stav databázy",
		MENU_USEROPTIONS : "Správa užívateľov",
		MENU_USEROPTIONS2 : "Užívateľské voľby",
		MENU_USEROPTIONS3 : "Informácie o užívateľovi",
		MENU_ADMIN : "Administrácia",
		MENU_LOGOUT : "Odhlásiť",
		MENU_STUFF : "Rôzne",
		MENU_FORUM_THREAD : "Vývojárske fórum",
		MENU_DOWNLOADPAGE : "Stiahnuť",
		MENU_LANGUAGE : "Jazyk",
		MENU_HELP : "Pomoc",
		MENU_TOOLOPTIONS : "Voľby Galaxytool",
		PARSER_INFO1 : " bolo vložené do databázy",
		PARSER_ERROR1 : "Nepodarilo sa vložiť nasledujúce súradnice:",
		PARSER_ERROR2 : "Nedá sa nájsť v databáze!",
		PARSER_ERROR3 : "Nedá sa nájsť databázový server!",
		PARSER_WRONG_UNIVERSE : "Nesprávny vesmír - aktuálny: \"&1\"  očakávané: \"&2\"",
		SHOW_TITLE : "OGame Galaxytool - Vyhľadávanie",
		SHOW_SEARCH : "Vyhľadať v databáze",
		SHOW_ALLYSYMBOL : "Aliančná značka",
		SHOW_PLAYERNAME : "Meno hráča",
		SHOW_MOONS : "Iba planéty s Mesiacom",
		SHOW_NOTICES : "Iba planéty s poznámkami",
		SHOW_COLONIES : "Iba planéty vhodné ku kolonizácii",
		SHOW_YES : "Áno",
		SHOW_NO : "Nie",
		SHOW_SEARCHRANGE : "Vzdialenosť",
		SHOW_SEARCH_IN : "Vyhľadať v galaxii",
		SHOW_FROM_SYSTEM : "od systému",
		SHOW_FROM_PLANET : "od pozície planéty",
		SHOW_TO : "do",
		SHOW_DESCRIPTION : "Môžete použiť zástupné znaky pre mená aliancií a hráčov. Tak môžete vyhľadať všetkých hráčov, ktorých meno obsahuje &quot;názov&quot; .<br />Vyplňte iba tie polia, ktoré potrebujete.",
		SHOW_SORT_BY : "Zotriediť podľa",
		SHOW_GALASYSTEM : "Galaxie/Systému",
		SHOW_ALLYNAME : "Názvov Aliancií",
		SHOW_SEARCHBUTTON : "Vyhľadať",
		SHOW_ADDRESS : "Adresa",
		SHOW_ALLYSORT : "Aliancie",
		SHOW_PLANET : "Meno planéty",
		SHOW_STATUS : "Stav",
		SHOW_CURRENTNESS : "Posledná aktualizácia",
		SHOW_PLAYER_STATUS : "Stav hráča",
		SHOW_PLAYER_STATUS1 : "všetko",
		SHOW_PLAYER_STATUS2 : "možné ciele",
		SHOW_PLAYER_STATUS3 : "neaktívny",
		SHOW_HITS : "Záznamov",
		SHOW_OF : "z",
		SHOW_ASC : "vzostupne",
		SHOW_DESC : "zostupne",
		SHOW_RESULTS : "záznamov na stránku",
		SHOW_MOON : "Mesiac",
		SHOW_UKMOONSIZE : "neznáma",
		SHOW_DF : "DF",
		SHOW_DF_LONG : "Pole trosiek",
		SHOW_METAL : "M",
		SHOW_METAL_LONG : "Kov",
		SHOW_CRYSTAL : "C",
		SHOW_CRYSTAL_LONG : "Kryštály",
		SHOW_BOTH : "oboje dohromady",
		SHOW_AT_LEAST : "(najmenej)",
		SHOW_DATE : "Dátum",
		SHOW_DATE_0 : "nezáleží",
		SHOW_DATE_1 : "starší než",
		SHOW_DATE_2 : "novší než",
		SHOW_RANK : "Poradie",
		SHOW_FRANK : "Poradie flotily",
		SHOW_MEMBERS : "Členovia",
		SHOW_NOTRANKED : "Nieje medzi prvými 1500.",
		SHOW_NOTICERES : "Poznámky",
		SHOW_REPORTS : "Iba planéty so správami",
		SHOW_REPORTS_SHORT : "Správy",
		SHOW_NOTHING : "Žiaden záznam nenájdený.",
		SHOW_ALLIANCE_STATUS : "Stav Aliancie",
		SHOW_NO_STATUS : "Stav nieje k dispozícii",
		SHOW_NAP : "NAP",
		SHOW_ALLIED : "Spojenec",
		SHOW_WAR : "Vojna",
		SHOW_BOYCOTT : "Bojkot",
		SHOW_NEUTRAL : "Neutrál",
		SHOW_OWN : "Vlastná Aliancia",
		SHOW_WING : "Wing",
		SHOW_EXT_OPTIONS1 : "Ukázať viac možností pre vyhľadávanie podľa vzdialenosti, poradia, dátumu alebo poľa trosiek.",
		SHOW_EXT_OPTIONS2 : "Ukázať viac možností pre vyhľadávanie podľa kolónií, Mesiacov, správ, poznámok, stavu hráčov a diplomacie.",
		SHOW_EXT_OPTIONS3 : "Ukázať viac možností pre triedenie nájdených výsledkov.",
		SHOW_EXTENDED : "rozšírené vyhľadávanie",
		SHOW_MOON_SELECTION : "Planéta s mesiacom",
		SHOW_REPORT_SELECTION : "Planéta so správou",
		SHOW_FILTER_BY : "Vylúčiť zo zoznamu",
		SHOW_FILTER_NONE : "nič",
		SHOW_PLAYERS_WITHOUT_PROGRESS : "Show players without score changes within the last few days",
		STATUS_TITLE : "OGame Galaxytool - Stav",
		STATUS_DB_STATUS : "Stav databázy",
		STATUS_COLOR : "Farba",
		STATUS_AGE1 : "Záznamy 1 deň staré.",
		STATUS_AGE2 : "Záznamy 2 - 4 dni staré.",
		STATUS_AGE3 : "Záznamy 4 - 7 dní staré.",
		STATUS_AGE4 : "Záznamy 1 - 2 týždne staré.",
		STATUS_AGE5 : "Záznamy 2 - 4 týždne staré.",
		STATUS_AGE6 : "Záznamy staršie než 1 mesiac!",
		STATUS_AGE7 : "Žiadne dostupné záznamy.",
		STATUS_ON : "on",
		STYLES_COLOR1 : "Farba 1",
		STYLES_COLOR2 : "Farba 2",
		STYLES_COLOR3 : "Farba 3",
		STYLES_COLOR4 : "Farba 4",
		STYLES_COLOR5 : "Farba 5",
		STYLES_COLOR6 : "Farba 6",
		STYLES_COLOR7 : "Farba 7",
		STATUS_DB_LEGEND : "Legenda",
		STATUS_GALAXY : "Prehľad galaxie",
		USER_TITLE : "Správa užívateľov",
		USER_NAMES : "Užívateľ",
		USER_ERROR : "Chyba",
		USER_NEWUSER : "Nový užívateľ",
		USER_OPTIONS : "Voľby",
		USER_USERNAME : "Užívateľské meno",
		USER_PASSWORD : "Heslo",
		USER_PASSWORD_CONFIRM : "Potvrdiť heslo",
		USER_GALAXY : "Galaxia",
		USER_SEARCH : "Vyhľadať",
		USER_INSERT : "Vložiť",
		USER_DELETE : "Zmazať",
		USER_DELETE_ENTRY : "Chcete zmazať užívateľa: ",
		USER_STATUS : "Prezrieť štatistiky",
		USER_STYLES : "Upraviť vzhľad",
		USER_SUBMIT : "Odoslať",
		USER_RESET : "Resetovať",
		USER_YES : "Áno",
		USER_NO : "Nie",
		USER_STYLEPATH : "Cesta k styles.css",
		USER_PROBES : "Prezrieť/Odoslať špionážne správy",
		USER_EMAIL : "Email",
		USER_ERROR1 : "Chybné heslo alebo neplatný email.",
		USER_ERROR2 : "Neplatný Email.",
		USER_INGAME : "Meno v hre",
		USER_ALLYTAG : "Aliančná značka",
		USER_ALLYHISTORY : "Historický prehľad",
		USER_DIPLOMATIC : "Zmeniť Diplomatický stav",
		USER_STATSPAGE : "počet záznamov na štatistickej stránke",
		USER_LINKS : "Odkazy",
		USER_LINKS2 : "Formát:<br>text;url<br>text2;url2<br>text3;url3",
		USER_EXPORT_TITLE : "Export farieb (BB Codes)",
		USER_BB_COORDINATES : "Súradnice",
		USER_BB_MOON : "Mesiac",
		USER_BB_DEBRIS : "Pole trosiek",
		USER_BB_ALLY : "Aliančné meno",
		USER_BB_ALLYDETAILS : "Detaily Aliancie",
		USER_BB_PLAYERNAME : "Meno hráča",
		USER_BB_BANNED : "bann",
		USER_BB_VACATION : "zmrazený účet",
		USER_BB_NOOB : "noob",
		USER_BB_INACTIVE : "Neaktívny",
		USER_BB_LONGINACTIVE : "Dlho neaktívny",
		USER_DELETION : "Vymazať",
		USER_FLEETINFO : "Pohyby flotily",
		USER_ACTIVITIES : "Aktivity hráča",
		USER_MAINTENANCE : "Údržba Galaxytoolu",
		USER_MANAGEMENT : "Správa užívateľov",
		USER_DELETE_MY_COMBAT_REPORTS : "Vymazať moje bojové správy",
		USER_DELETE_MY_MESSAGES : "Vymazať moje správy",
		USER_DELETE_MY_FLEETMOVES : "Vymazať moje pohyby flotily",
		USER_DELETE_MY_COMBAT_REPORTS_LIMITED : "Vymazať moje bojové správy staršie ako &1 dní",
		USER_DELETE_MY_MESSAGES_LIMITED : "Vymazať moje správy staršie než &1 dní",
		USER_TABLE_ENTRIES : "Počet výsledkov vyhľadávania pre každú stranu",
		USER_EXISTS : "Používateľ už existuje",
		USER_BB_OUTLAW : "Bandita",
		USER_INVALID_URL : "URL adresa &1 za zdá byť neplatná - URL bude ignorovaná",
		VIEW_TITLE : "OGame Galaxytool - Prehľad Galaxie",
		VIEW_NODATA : "Údaje nie sú dostupné.",
		VIEW_GALAXY : "Galaxia",
		VIEW_SYSTEM : "Systém",
		VIEW_POSITION : "Poz.",
		VIEW_PLANET : "Planéta",
		VIEW_MOON : "Mesiac",
		VIEW_TF : "DF",
		VIEW_PLAYER : "Hráč",
		VIEW_PLAYER_ADD : "(Poradie / Stav)",
		VIEW_ALLY : "Aliancia",
		VIEW_ALLY_ADD : "(Poradie / Člen)",
		VIEW_METAL : "M",
		VIEW_CRYSTAL : "C",
		VIEW_COLONISED : "Planét obsadených",
		VIEW_UKMOONSIZE : "neznáme",
		VIEW_BACK : "späť",
		VIEW_NOTICE : "Poznámky",
		VIEW_REPORTS : "Správy",
		VIEW_MOONPHALANX : "Nasledujúce mesiace môžu skenovať tento systém",
		VIEW_NOMOONS : "Žiaden mesiac nebol nájdený",
		VIEW_IRAKS : "Nasledujúce planéty môžu byť zasiahnuté medziplanetárnymi raketami",
		VIEW_NOIRAKS : "Žiadne medziplanetárne rakety neboli nájdené",
		VIEW_MOON_DESTROY_CHANCE : "Šanca na zničenie Mesiaca",
		VIEW_CHANCE_WITH_ONE : "Šanca s jednou Hviezdou smrti",
		VIEW_CHANCE_WITH_N : "Šanca s",
		VIEW_DEATH_STARS : "Hviezda smrti",
		VIEW_DS_DESTROY_CHANCE : "Šanca na stratu Hviezdy smrti",
		VIEW_TOP : "Nahor",
		VIEW_GO : "go",
		VIEW_DIAMETER : "Priemer",
		PW_TITLE : "OGame Galaxytool - zmena hesla",
		OLD_PASSWORD : "staré heslo",
		NEW_PASSWORD : "nové heslo",
		CONFIRM_NEW_PASSWORD : "potvrdiť nové heslo",
		PW_MISMATCH : "Heslá sa nezhodujú!",
		PW_ERROR : "Staré heslo bolo chybne zadané!",
		UPDATE_DONE : "Zmena úspešná.",
		TIMEZONE_OFFSET : "Posun časovej zóny voči serveru",
		DELETE_ACCOUNT : "Zmaž tento Galaxytool účet",
		DELETE_ACCOUNT_SAFETY_REQUEST : "Skutočne si želáte zmazať tento Galaxytool účet?",
		CH_PASSWD_AUTHORIZATION : "Autorizácia",
		CH_PASSWD_ADMIN : "Admin",
		TIMEZONE_OGAME_OFFSET : "Rozdiel od časovej zóny OGame servera",
		CH_PASSWD_USER_LANGUAGE : "Zmeniť na tento jazyk po prihlásení",
		CH_PASSWD_USER_LANGUAGE_NO_CHANGE : "Žiadna zmena",
		CH_PASSWD_EXPAND : "Rozbalené",
		CH_PASSWD_COLLAPSE : "Zbalené",
		CH_PASSWD_HIDDEN : "Skryté",
		CH_PASSWD_GETTING_STARTED : "Zobraziť 'Začíname' informácie po prihlásení",
		CH_PASSWD_PLUGIN : "Zobraziť informácie o plugine po prihlásení",
		NOTICE_TITLE : "OGame Galaxytool - Poznámky",
		NOTICE_HEADER : "upraviť poznámky",
		NOTICE_HEADER2 : "Upraviť vlastné poznámky",
		NOTICE_PUBLIC : "Prístupné pre ostatných?",
		NOTICE_YES : "áno",
		NOTICE_NO : "nie",
		NOTICE_TEXT : "Text poznámky",
		NOTICE_SAVE : "Uložiť",
		NOTICE_DELETED : "Záznam zmazaný",
		NOTICE_SAVED : "Záznam uložený.",
		NOTICE_RESULTS : "Všetky výsledky",
		NOTICE_USER : "Užívateľ",
		NOTICE_DATE : "Dátum",
		NOTICE_EDIT : "Upraviť",
		NOTICE_DELETE : "Zmazať",
		NOTICE_NEW : "Vytvoriť vlastný záznam",
		NOTICE_NOTPUBLIC : "Poznámka nie je verejná.",
		NOTICE_ALL : "vštko",
		NOTICE_NONE : "nič",
		NOTICE_SEARCH : "Vyhľadať v Poznámkach",
		NOTICE_SEARCH_SHORT : "Vyhľadať",
		NOTICE_HITS : "Záznamov",
		NOTICE_SHOWRESULTS : "záznamov na stránku",
		NOTICE_OF : "vyp",
		NOTICE_NOTHING : "Žiadny záznam nebol nájdený",
		NOTICE_CHARS : "Znakov",
		NOTICE_PLAYERNAME : "Hráč",
		NOTICE_SHOWALL : "Zobraziť všetky poznámky",
		REPORTS_TITLE : "OGame Galaxytool - Špionážne správy",
		REPORTS_RESOURCES : "Suroviny",
		REPORTS_FLEET : "Flotily",
		REPORTS_DEFENCE : "Obrana",
		REPORTS_BUILDINGS : "Budovy",
		REPORTS_TECHNOLOGY : "Výskum",
		REPORTS_MOON : "Mesiac",
		REPORTS_SEARCH : "Vyhľadať v špionážnych správach",
		REPORTS_SEARCH_SHORT : "Vyhľadať",
		REPORTS_HITS : "Záznamov",
		REPORTS_NOTHING : "Žiadny záznam nebol nájdený",
		REPORTS_ADDRESS : "Adresa",
		REPORTS_CURRENTNESS : "Aktualizácia",
		REPORTS_PLAYERNAME : "Meno hráča",
		REPORTS_ALLY : "Aliancia",
		REPORTS_VIEW : "Prezrieť správu",
		REPORTS_SEARCH_IN : "Vyhľadať v Galaxii",
		REPORTS_FROM_SYSTEM : "od Systému",
		REPORTS_TO : "do",
		REPORTS_DELETE : "Zmazať",
		REPORTS_DELETED : "Záznam zmazaný",
		REPORTS_RESULTS : "záznamov na stránku",
		REPORTS_OF : "z",
		REPORTS_DATE : "Dátum",
		REPORTS_DATE_0 : "nezáleží",
		REPORTS_DATE_1 : "starší než",
		REPORTS_DATE_2 : "novší než",
		REPORTS_NOTICES : "Poznámky",
		REPORTS_AT_LEAST_RESOURCES : "Suroviny (najmenej)",
		REPORTS_SEARCH_EXTENDED : "rozšírené vyhľadávanie",
		REPORTS_FLEET_RESIS : "Flotila - skóre",
		REPORTS_DEFENCE_RESIS : "Obrana - skóre",
		REPORTS_ALL_RESIS : "celkom skóre",
		REPORTS_TECHS : "Technológie",
		REPORTS_UNKNOWN_ENTRIES : "neznámý záznam",
		REPORTS_PARTLY_INSERTED : "čiastočně vložené",
		REPORTS_FOR_ALL_RES : "pre všetky suroviny",
		REPORTS_FOR_TF : "pre pole trosiek",
		REPORTS_KT : "Malých transportérov",
		REPORTS_GT : "Veľkých transportérov",
		REPORTS_SS : "Bojových lodí",
		REPORTS_REC : "Recyklátorov",
		REPORTS_RAIDABLE : "iba ciele vhodné na útok",
		REPORTS_ALL_RESOURCES : "všetky suroviny",
		REPORTS_STUFF : "Rôzne",
		REPORTS_SPEEDSIM : "Simulácia pomocou Speedsim",
		REPORTS_DRAGOSIM : "Simulácia pomocou Dragosim",
		REPORTS_STATUS : "Stav",
		REPORTS_ERROR : "Vyskytla sa chyba",
		REPORTS_OWN_REPORTS : "Iba moje správy",
		REPORTS_UPLOAD_BY : "Správu nahral",
		REPORTS_DEPTH : "Hĺbka správy",
		REPORTS_FLEET_SCORE : "Skóre flotily",
		REPORTS_DEFENCE_SCORE : "Skóre obrany",
		REPORTS_HOURS : "hodín",
		REPORTS_MAX_RESULTS_HIT : "Vaše hľadanie vrátilo viac, než &1 výsledkov. Zobrazuje sa iba prvých &1 výsledkov. Pre získanie menej výsledkov upravte Vašu vyhľadávaciu požiadavku.",
		REPORTS_OSIMULATE : "Simulovať s OSimulate",
		REPORTS_SHOW_ONLY : "Ukáazať iba",
		REPORTS_SHOW_PLANETS : "Planéty",
		REPORTS_SHOW_MOONS : "Mesiace",
		REPORTS_OWNER : "Správy, ktoré vlastní",
		STATS_TITLE : "OGame Galaxytool - Štatistiky",
		STATS_TBLHEAD : "Štatistiky",
		STATS_RANK : "Poradie",
		STATS_PLAYERNAME : "Meno hráča",
		STATS_ALLYNAME : "Aliančná značka",
		STATS_SCORE : "Skóre",
		STATS_FLEET : "Flotila",
		STATS_RESEARCH : "Výskum",
		STATS_MEMBERS : "Členovia",
		STATS_STATUS : "Stav",
		STATS_NOTHING : "Stav nie je k dispozícii",
		STATS_NAP : "NAP",
		STATS_ALLIED : "Spojenec",
		STATS_WAR : "Vojna",
		STATS_BOYCOTT : "Bojkot",
		STATS_NEUTRAL : "Neutrál",
		STATS_OWN : "Vlastná Aliancia",
		STATS_WING : "Wing",
		STATS_UPDATE : "Záznam z",
		STATS_PLAYERSTATS : "Stav hráča",
		STATS_ALLYSTATS : "Stav Aliancie",
		STATS_DELETE : "Chcete zmazať tento záznam?",
		STATS_CONFIRM_DELETE : "Skutočne chcete zmazať tento záznam?",
		STATS_CHANGE_PLAYER_STATUS : "Stav hráča",
		STATS_CHANGE_ALLIANCE_STATUS : "Stav Aliancie",
		STATS_CHANGE_ALLIANCE_STATUS_HINT : "Všetkým členom tejto alinacie bol vybraný rovnaký stav. Akýkoľvek predchodzí stav bude zmenený. Stav jednotlivých hráčov môžete meniť dodatočne.",
		STATS_UNKNOWN : "Zbytok",
		STATS_DETAILS : "Detaily pre",
		STATS_PLAYERSTATUS : "Stav hráča",
		STATS_IGNORE_STATUS : "všetko",
		STATS_ACTIVE : "aktívny",
		STATS_INACTIVE : "Neaktívny",
		STATS_BANNED : "bann",
		STATS_VACATION : "zmrazený účet",
		STATS_NOOB : "noob",
		STATS_YES : "Áno",
		STATS_NO : "Iba planéty s poznámkami",
		STATS_SEARCH : "Vyhľadať",
		STATS_SHOW_GRAPH : "Zobraziť detaily rozdelenia bodov",
		STATS_LONG_INACTIVE : "Dlho neaktívny",
		STATS_STANDARD : "Štandardné body",
		STATS_MILITARY : "Armádne body",
		STATS_ECONOMY : "Ekonomika",
		STATS_HONOUR : "Body cti",
		STATS_MILITARY_BUILD : "Získané vojenské body",
		STATS_MILITARY_DESTROYED : "Zničené vojenské body",
		STATS_MILITARY_LOST : "Stratené vojenské body",
		REGISTER_REGISTRATE : "Registrácia",
		REGISTER_LOGINNAME : "Prihlasovacie meno",
		REGISTER_PASSWORD : "Heslo",
		REGISTER_PASSWORD_CONFIRM : "Potvrdenie hesla",
		REGISTER_EMAIL : "Email",
		REGISTER_INGAME : "Meno v hre",
		REGISTER_ALLYTAG : "Aliančná značka",
		REGISTER_EMAILVERIFICATION : "Kontrola Emailu",
		REGISTER_EMAILTEXT : "Prosím kliknite na tento odkaz k potvrdeniu Vašej registrácie do programu Galaxytool.",
		REGISTER_ERROR1 : "Prihlasovacie meno už niekto používa.",
		REGISTER_ERROR2 : "Chyba pri zasielaní emailu. Prosím, kontaktujte administrátora.",
		REGISTER_ERROR3 : "Chyba pri zasielaní údajov do databázy!",
		REGISTER_INFO1 : "Váš účet bol vytvorený.",
		REGISTER_INFO2 : "Kliknite prosím na odkaz v emaili pre potvrdenie Vašej registríácie.",
		REGISTER_INFO3 : "Zriadenie účtu potvrdené. Administrátor Vám ho v dohľadnej dobe aktivuje.",
		REGISTER_BUTTON : "Späť na hlavnú stranu",
		REGISTER_NEW_SUBJECT : "Bol zaregistrovaný nový užívateľ.",
		REGISTER_NEW_MAILTEXT : "Nový užívateľ sa zaregistroval.",
		REGISTER_BACK : "Späť na prvú stranu",
		REGISTER_MISSING_FIELDS : "Zadajte všetky požadované údaje",
		REGISTER_ERROR4 : "Emailová adresa je neplatná.",
		REGISTER_ERROR5 : "Heslá sa nezhodujú.",
		REGISTER_PWS : "Sila hesla",
		REGISTER_PWS0 : "veľmi slabé",
		REGISTER_PWS1 : "slabé",
		REGISTER_PWS2 : "dobré",
		REGISTER_PWS3 : "silné",
		REGISTER_PWS4 : "veľmi silné",
		REGISTER_EMAIL_USED : "Emailová adresa sa už používa",
		LOSTPW_TITLE : "Zabudnuté heslo",
		LOSTPW_INFO2 : "Nové heslo bolo vygenerované a zaslané na Váš email.",
		LOSTPW_BUTTON1 : "dostať nové heslo",
		LOSTPW_BUTTON2 : "Späť na hlavnú stranu",
		LOSTPW_LOGINNAME : "Prihlasovacie meno",
		LOSTPW_EMAIL : "Email",
		LOSTPW_ERROR1 : "Chyba pri zasielaní údajov do databázy.",
		LOSTPW_ERROR2 : "Nebol nájdený žiaden zhodný záznam.",
		LOSTPW_ERROR3 : "Chyba pri zasielaní emailu. Prosím, kontaktujte administrátora.",
		LOSTPW_EMAIL_SUBJECT : "Vyžaduje sa Vaše nové heslo",
		LOSTPW_EMAIL_TEXT1 : "Toto sú Vaše nové prihlasovacie údaje do Galaxytool",
		LOSTPW_EMAIL_TEXT2 : "Užívateľské meno",
		LOSTPW_EMAIL_TEXT3 : "Heslo",
		LOSTPW_INFO1 : "Obdržíte email na potvrdenie požiadavky o resetovanie hesla.",
		LOSTPW_CONFIRM_RESET_SUBJECT : "Stratené heslo?",
		LOSTPW_CONFIRM_RESET_MESSAGE : "Ahoj,\n\nPožiadali ste o resetovanie hesla pre Galaxytool. Pre vygenerovanie nového hesla kliknite na následovný link:",
		USERINFO_TITLE : "OGame Galaxytool - Informácie o užívateľovi",
		USERINFO_NAMES : "Všetci užívatelia tohto nástroja",
		USERINFO_DETAIL : "detailné informácie o",
		USERINFO_ERROR1 : "Žiaden užívateľ s týmto ID!",
		USERINFO_USERNAME : "Prihlasovacie meno",
		USERINFO_INGAME : "Meno v hre",
		USERINFO_EMAIL : "Email",
		USERINFO_ALLYTAG : "Aliancia",
		USERINFO_STYLEPATH : "Skin",
		USERINFO_STATUS : "Stav",
		USERINFO_ACTIVATE : "Aktivovať hráča",
		USERINFO_LOGINS : "Počet prihlásení",
		USERINFO_LASTLOGIN : "Posledné prihlásenie",
		USERINFO_DATA : "Informácie o zadaných Systémoch",
		USERINFO_NODATA : "Tento užívateľ zatiaľ nevložil žiadny Systém!",
		USERINFO_GALAXY : "Galaxia",
		USERINFO_SYSTEMS : "Počet Systémov",
		USERINFO_IP : "IP adresa",
		USERINFO_LOGINTIME : "prihlásenie",
		USERINFO_NOLOGIN : "Užívateľ sa zatiaľ neprihlásil.",
		USERINFO_LAST_GALAXYUPDATE : "Posledný vložený Prehľad Galaxie",
		USERINFO_LAST_PUBLIC_NOTICE : "Posledná verejná poznámka",
		USERINFO_LAST_PRIVATE_NOTICE : "Posledná súkromná poznámka",
		USERINFO_NUMBEROF_PUBLIC_NOTICE : "Počet verejných poznámok",
		USERINFO_NUMBEROF_PRIVATE_NOTICE : "Počet súkromných poznámok",
		USERINFO_ACTIVATED : "Aktivovaných účtov",
		USERINFO_ACTIVATIONTEXT : "Administrátor Galaxytool aktivoval Váš účet.\n\nUžijte si nástroj Galaxytool!",
		USERINFO_LAST_SUBMIT : "Posledné vloženie informácie",
		ALLYHISTORY_TITLE : "OGame Galaxytool - História Aliancie",
		ALLYHISTORY_TBLHEAD : "Historický prehľad",
		ALLYHISTORY_PLAYERNAME : "Meno hráča",
		ALLYHISTORY_ALLYNAME : "Aliancia",
		ALLYHISTORY_LASTMONTH : "Posledný mesiac",
		ALLYHISTORY_ALL_DATA : "Všetky dostupné informácie",
		ALLYHISTORY_SHOW : "Zobraziť štatistiky",
		ALLYHISTORY_TIMESPAN : "Obdobie",
		ALLYHISTORY_PROGESS : "Vývoj",
		ALLYHISTORY_SCORE : "Body",
		ALLYHISTORY_FSCORE : "Bodov za flotily",
		ALLYHISTORY_RSCORE : "Bodov za výzkum",
		ALLYHISTORY_MEMBER : "Členovia",
		ALLYHISTORY_NOTHING : "žiadne záznamy",
		ALLYHISTORY_DETAILS : "Detaily",
		ALLYHISTORY_SHOW_ADDRESS : "Súradnice",
		ALLYHISTORY_ESCORE : "Ekonomika",
		ALLYHISTORY_MSCORE : "Armádne body",
		DETAILEDINFO_PLAYERINFO_TITLE : "Informácie o hráčoch",
		DETAILEDINFO_ALLYINFO_TITLE : "Informácie o aliancii",
		DETAILEDINFO_PLAYERINFO_TBLHEAD : "Detailné informácie o hráčovi",
		DETAILEDINFO_ALLYINFO_TBLHEAD : "Detailné informácie o aliancii",
		DETAILEDINFO_NO_ALLIANCE : "nič",
		DETAILEDINFO_SCORE : "Štatistika bodov",
		DETAILEDINFO_FLEET : "Štatistika flotily",
		DETAILEDINFO_RESEARCH : "Štatistika výskumu",
		DETAILEDINFO_RANK : "Poradie",
		DETAILEDINFO_POINTS : "Body",
		DETAILEDINFO_KNOWN_PLANETS : "známe planéty",
		DETAILEDINFO_MOONS : "známych Mesiacov",
		DETAILEDINFO_PHALANX_AREA : "Oblasť Falangy",
		DETAILEDINFO_NO_PHALANX_AREA : "Senzor Falangy nenájdený",
		DETAILEDINFO_NOTICES : "Poznámky",
		DETAILEDINFO_NO_NOTICES : "Žiadna poznámka nebola nájdená",
		DETAILEDINFO_PREVIOUS_ALLIANCES : "predchádzajúca Aliancia",
		DETAILEDINFO_RESOURCES_PER_HOUR : "Surovín za hodinu",
		DETAILEDINFO_RESOURCES_PER_DAY : "Surovín za deň",
		DETAILEDINFO_RESOURCES_PER_WEEK : "Surovín za týždeň",
		DETAILEDINFO_RESOURCES_PER_MONTH : "Surovín za mesiac (30 dní)",
		DETAILEDINFO_METAL : "Kov",
		DETAILEDINFO_CRYSTAL : "Kryštály",
		DETAILEDINFO_DEUTERIUM : "Deutérium",
		DETAILEDINFO_UNKNOWN : "neznáme",
		DETAILEDINFO_SCORE_DISTRIBUTION : "Rozdelenie bodov",
		DETAILEDINFO_GENERAL : "Detaily",
		DETAILEDINFO_MEMBERS : "Členovia",
		DETAILEDINFO_GRAPHS : "Grafy",
		DETAILEDINFO_RESOURCES : "Zdroje",
		DETAILEDINFO_FLEET_TAB : "Flotila",
		DETAILEDINFO_TECH : "Výskum",
		DETAILEDINFO_FLEET_DETAIL : "Spolu / (priemer hráčov) zo všetkých dostupných záznamov",
		DETAILEDINFO_TECH_DETAIL : "Priemer zo všetkých dostupných informácií o hráčoch",
		DETAILEDINFO_PLANET_TAB : "Planéty",
		DETAILEDINFO_MOON_TAB : "Mesiace",
		DETAILEDINFO_ACTIVITIES : "Activities",
		DETAILEDINFO_NODATA : "Údaje nie sú dostupné.",
		DETAILEDINFO_ACTIVITY_DESCRIPTION : "Show activities of &1 collected from:",
		DETAILEDINFO_GALAXYVIEWS : "Galaxy views",
		DETAILEDINFO_SCANS : "Espionage actions",
		DETAILEDINFO_MESSAGES : "Player messages",
		DETAILEDINFO_COMBATS : "Combat reports",
		DETAILEDINFO_ALLYPAGE : "Alliance overview",
		DETAILEDINFO_MANUAL : "Manual insertions",
		DETAILEDINFO_START : "Beginning",
		DETAILEDINFO_TO : "to",
		DETAILEDINFO_TODAY : "Today",
		DETAILEDINFO_DATA_RESTRICTION : "restricted to:",
		DETAILEDINFO_WEEKDAY_WEEKEND : "Weekend",
		DETAILEDINFO_WEEKDAY_WORKINGDAY : "Weekday",
		DETAILEDINFO_WEEKDAY_MONDAY : "Monday",
		DETAILEDINFO_WEEKDAY_TUESDAY : "Tuesday",
		DETAILEDINFO_WEEKDAY_WEDNESDAY : "Wednesday",
		DETAILEDINFO_WEEKDAY_THURSDAY : "Thursday",
		DETAILEDINFO_WEEKDAY_FRIDAY : "Friday",
		DETAILEDINFO_WEEKDAY_SATURDAY : "Saturday",
		DETAILEDINFO_WEEKDAY_SUNDAY : "Sunday",
		DETAILEDINFO_WEEKDAY_SHORTLENGTH : 3,
		DETAILEDINFO_PLAYER_CURRENTLY_ACTIVE : "The player is currently active",
		DETAILEDINFO_PLAYER_MESSAGES : "available player messages",
		DETAILEDINFO_SHOW : "show",
		DETAILEDINFO_NONE : "none available",
		DETAILEDINFO_ENTER_MANUALLY : "Enter activities for this player",
		DETAILEDINFO_PLAYER_SEEN_ON : "Player was online on",
		DETAILEDINFO_INSERT : "Insert",
		DETAILEDINFO_OGAME_SERVERTIMES : "Please note: All dates and times refer to OGame server times !",
		DETAILEDINFO_DAY_VIEW : "24 hours view",
		DETAILEDINFO_WEEK_VIEW : "weekly view",
		DETAILEDINFO_HOME_PLANET : "Homeworld",
		DETAILEDINFO_PLANETNAME : "Name",
		DETAILEDINFO_DEFENCE_SCORE : "Defence score",
		DETAILEDINFO_DEFENCE_SCORE_TOOLTIP : "Defence score = Fleet - Score + Research + Economy.<br/>All those statistics must be up to date to have a meaningful result!",
		DETAILEDINFO_SCORE_PER_SHIP : "Scores per ship",
		DETAILEDINFO_SHIPS : "Number of ships",
		DETAILEDINFO_DATE_IN_FUTURE : "Do not maintain times which are not in the past.",
		ADMIN_TITLE : "Správa nástroja Glaxytool",
		ADMIN_DISCLAMER : "Upozornenie: Spustenie týchto skriptov je len na vlastné riziko! Väčšina z nich maže údaje.",
		ADMIN_INCONSISTENCIES : "Nezrovnalosti v databáze",
		ADMIN_PLANETS : "Planéty na pozícii 0 alebo väčšej ako 15",
		ADMIN_GALAXIES : "Vymaž galaxie väčšie ako &1 ",
		ADMIN_PLAYERS : "Vymaž hráčov bez OGame hráčskeho ID - vedie k duplikátnym hráčskym záznamom",
		ADMIN_REPORTS : "Zmaž reporty kde už viac neexistujú žiadne planéty",
		ADMIN_MISC : "Rôzne",
		ADMIN_RESET : "Reset Galaxytool (len tabuľky užívateľov a IP adries nebudú zmazané)",
		ADMIN_OLD_PLAYERS : "Zmaž záznamy hráča staršie ako &1 dní",
		ADMIN_OLD_REPORTS : "Zmaž správy staršie ako &1 dní",
		ADMIN_LOADING : "Nezatvárajte toto okno dokiaľ sa stránka nenačíta.",
		ADMIN_STATUS : "Stav Vaších požiadaviek",
		ADMIN_SELECTION : "Musí byť označený minimálne jeden záznam",
		ADMIN_SAFETY : "Ste si itý, že chcete spustiť tieto skripty?",
		ADMIN_DONE : "Hotovo",
		ADMIN_NOTBD : "Nie je čo vykonať",
		ADMIN_OLD_GALAXIES : "Odstráň náhľady galaxie staršie ako &1 dní",
		ADMIN_UNUSED_PLAYERS : "Odstráň hráčov, ktorý sa neobjavili v žiadnom náhľade na galaxiu",
		ADMIN_OLD_ACTIVITIES : "Remove player activities older than &1 days",
		ADMIN_OLD_COMBATS : "Remove combat reports older than &1 days",
		ADMIN_OLD_INGAME_MSG : "Remove ingame messages older than &1 days",
		ADMIN_OGAME_API : "Load public data from OGame into the Galaxytool",
		ADMIN_OGAME_ALL_DATA : "Všetky dostupné informácie",
		ADMIN_OGAME_GALAXY_DATA : "Prezrieť Galaxiu",
		ADMIN_OGAME_STATISTICS_DATA : "Štatistiky",
		ERRORPAGE_PAGEFORWARD : "Kliknite sem, pokiaľ tvoj prehliadač nepodporuje presmerovanie.",
		ERRORPAGE_PERMISSION_DENIED : "Nemáte oprávnenie vstúpiť na tútu stránku. kliknite späť.",
		FLEETS_TITLE : "OGame Galaxytool - Fleet movements",
		FLEETS_ACTUAL_FLEETS : "Current fleet movements",
		FLEETS_YES : "Áno",
		FLEETS_NO : "Iba planéty s poznámkami",
		FLEETS_DETAILS : "Details",
		FLEETS_MISSION_EXPEDITION : "Expedition",
		FLEETS_MISSION_COLONIZATION : "Colonize",
		FLEETS_MISSION_RECYCLE : "Harvest",
		FLEETS_MISSION_TRANSPORT : "Transport",
		FLEETS_MISSION_DEPLOYMENT : "Deploy",
		FLEETS_MISSION_ESPIONAGE : "Espionage",
		FLEETS_MISSION_ACS_DEFEND : "ACS Defend",
		FLEETS_MISSION_ATTACK : "Attack",
		FLEETS_MISSION_ACS_ATTACK : "ACS Attack",
		FLEETS_MISSION_MOON_DESTRUCTION : "Moon Destruction",
		FLEETS_MISSION_MISSILE_ATTACK : "Missile Attack",
		FLEETS_NO_DATA : "No applicable data found",
		FLEETS_FLEET : "Fleet",
		FLEETS_ALL_FLEETS : "Show all fleet movements",
		COMBAT_REPORT_OUDATED_GALAXYVIEW : "Your galaxy data is outdated. Please visit combat origin and target coordinates first!",
		MESSAGES_TITLE : "OGame Galaxytool - OGame Messages",
		MESSAGES_PLAYERNAME : "Playername",
		MESSAGES_SUBJECT : "Subject",
		MESSAGES_DATE : "Date",
		MESSAGES_FILTER : "Filter",
		MESSAGES_DELETE : "Delete message",
		MESSAGES_PUBLISH_DETAIL : "Publish message by adding the message content to notice text of that player.",
		MESSAGES_PUBLISH_HEADER : "&sender sent a message to &recipient on &date:\n\n &message",
		MESSAGES_PLAYER_FILTER : "Messages for player:",
		MESSAGES_CONTENT : "Content",
		COMBATS_TITLE : "OGame Galaxytool - Combat reports",
		COMBATS_ATTACKER : "Attacker",
		COMBATS_DEFENDER : "Defender",
		COMBATS_DATE : "Date",
		COMBATS_OWNER : "Owner",
		COMBATS_WINNER : "Winner",
		COMBATS_COMBATREPORT : "Combat Report",
		COMBATS_COMBAT_AT : "Combat at",
		COMBATS_LOST_UNITS : "Lost units",
		COMBATS_LOOT : "Loot",
		COMBATS_DEBRIS : "Debris",
		COMBATS_AND : "and",
		COMBATS_PUBLISH : "Make this report public",
		COMBATS_UNPUBLISH : "Unshare this report (makes it private again)",
		COMBATS_DELETE : "Delete report",
		COMBATS_CHECK_ALL : "Check All",
		COMBATS_UNCHECK_ALL : "Uncheck All",
		COMBATS_WITH_SELECTED : "With selected",
		COMBATS_PUBLIC_REPORTS : "Public reports",
		COMBATS_YES : "Áno",
		COMBATS_NO : "Iba planéty s poznámkami",
		COMBATS_SEARCH_OPTIONS : "Search options",
		COMBATS_SEARCH : "Go",
		COMBATS_RESET : "Reset",
		COMBATS_COORDINATES : "Súradnice",
		COMBATS_INVALID_GALAXY_ENTERED : "Invalid Galaxy entered",
		COMBATS_INVALID_SYSTEM_ENTERED : "Invalid System entered",
		COMBATS_INVALID_PLANET_ENTERED : "Invalid Planet entered",
		COMBATS_GALAXY_FROM_TO : "Galaxy",
		COMBATS_SYSTEM_FROM_TO : "System",
		COMBATS_PLANET_FROM_TO : "Planet",
		COMBATS_APPLY : "Použiť",
		COMBATS_COMBAT_SUMMARY : "Combat report summary",
		COMBATS_DOWNLOAD_CSV : "Download as CSV file",
		REPORT_ARCHIVE_TITLE : "Report archive",
		REPORT_ARCHIVE_COORDINATES : "Coordinates",
		REPORT_ARCHIVE_SCANTIME : "Scan time",
		REPORT_ARCHIVE_DELETE : "Delete these entries",
		REPORT_ARCHIVE_CONFIRM_DELETE : "Do you really want to delete these entries?",
		REPORT_ARCHIVE_GALAXY : "Galaxy",
		REPORT_ARCHIVE_SYSTEM : "System",
		REPORT_ARCHIVE_PLANET : "Planet",
		REPORT_ARCHIVE_MOON : "Moon",
		REPORT_ARCHIVE_DETAILS : "Details",
		REPORT_ARCHIVE_RESOURCES : "Surovín za hodinu",
		REPORT_ARCHIVE_HEADER_RESOURCES : "Suroviny",
		REPORT_ARCHIVE_DETAILS_FOR : "Report archive for &1 [&2] (&3)",
		REPORT_ARCHIVE_FLEET_CARGO : "Fleet cargo capacity",
		REPORT_ARCHIVE_IRAK_RANGE : "Interplanetary Missiles range",
		REPORT_ARCHIVE_CHART_TYPE : "Chart type",
		INSTALL_TITLE : "Galaxytool installation for version",
		INSTALL_PROGRESS : "Overall progress",
		INSTALL_STEP : "Step",
		INSTALL_CONTINUE : "Continue",
		INSTALL_VALIDATE : "Validate",
		INSTALL_STEP1 : "Welcome",
		INSTALL_STEP2 : "Writeable check",
		INSTALL_STEP3 : "Database settings",
		INSTALL_STEP4 : "OGame settings",
		INSTALL_STEP5 : "Galaxytool settings",
		INSTALL_STEP6 : "Admin password",
		INSTALL_STEP7 : "Install Galaxytool",
		INSTALL_STEP8 : "Finalize install",
		INSTALL_FILE_DELETE_CHECK : "Please delete install.php and update.php from your webserver.",
		INSTALL_STEP1_PHP_FAILED : "Your PHP version &1 is not working with this Galaxytool version",
		INSTALL_STEP1_FOPEN_FAILED : "Your PHP version does not allow to open webpages with FOPEN() command. This is required to consume the OGame API.",
		INSTALL_STEP1_WELCOME : "Welcome to the installation wizard of the Galaxytool. You will be guided through the installation of the Galaxytool.",
		INSTALL_STEP2_DESCRIPTION : "Make sure your config.php and attributes.php files have write permissions enabled.",
		INSTALL_STEP2_DESCRIPTION2 : "If you don't know, how to achieve this, please take a look here: &1",
		INSTALL_STEP2_FILE_NOT_WRITEABLE : "File is not writeable",
		INSTALL_STEP3_SERVER : "Database server",
		INSTALL_STEP3_USERNAME : "Užívateľské meno",
		INSTALL_STEP3_PASSWORD : "Heslo",
		INSTALL_STEP3_DBNAME : "Database name",
		INSTALL_STEP3_PREFIX : "Tablename prefix",
		INSTALL_STEP3_ENTER_PREFIX : "E.g. mytool_",
		INSTALL_STEP3_ENTER_SERVER : "Enter the server address. Contact your system admin if necessary. Usually the correct value is localhost.",
		INSTALL_STEP3_ENTER_USERNAME : "Enter the username for database access",
		INSTALL_STEP3_ENTER_PASSWORD : "Enter the password for database access",
		INSTALL_STEP3_ENTER_DBNAME : "Enter the database name which shall be used for installation (must exist)",
		INSTALL_STEP3_CONNECT_FAILED : "Could not establish connection to database server",
		INSTALL_STEP3_DB_FAILED : "Database &1 not found",
		INSTALL_STEP3_MYSQL_VERSION_FAILED : "MySQL version &1 is not working with this Galaxytool version",
		INSTALL_STEP4_URL : "OGame URL",
		OGAME_URL_DETAILS : "Please enter any URL you see when you are logged on to OGame. Based on that URL the tool will derive the OGame API address which can be used to fill data into the Galaxytool without the Galaxytoolbar. This API was introduced with OGame version 4.1.",
		INSTALL_STEP4_UNIVERSE : "OGame Universe",
		INSTALL_STEP4_DEF_TO_DEBRIS : "Defense to debris",
		INSTALL_STEP4_DEBRIS_RATE : "Debris rate",
		INSTALL_STEP4_SPEED_RATE : "Speed rate",
		INSTALL_STEP4_ENTER_UNIVERSE : "Enter your OGame universe name or number (case sensitive).",
		INSTALL_STEP4_UNIVERSE_MISSING : "You must define your universe",
		INSTALL_STEP4_ENTER_URL : "Enter your OGame universe address",
		INSTALL_STEP4_URL_MISSING : "You must define your OGame address",
		INSTALL_STEP4_URL_CHECK_FAILED : "Could not find OGame API at &1",
		INSTALL_STEP4_GETSETTINGS : "Fetch settings",
		INSTALL_STEP5_TOOLNAME : "Galaxytool name",
		INSTALL_STEP5_ENTER_TOOLNAME : "This is the name which will be shown at logon page to identify your Galaxytool",
		INSTALL_STEP5_LANGUAGE : "Default language",
		INSTALL_STEP5_EMAIL_TO : "Email To",
		INSTALL_STEP5_ENTER_EMAIL_TO : "Enter the email address where you would like to receive notifications about registrations",
		INSTALL_STEP5_EMAIL_FROM : "Email From",
		INSTALL_STEP5_ENTER_EMAIL_FROM : "This email address is shown as REPLY for all mails sent from the Galaxytool",
		INSTALL_STEP5_USE_PHPMAILER : "Use PHPMailer",
		INSTALL_STEP5_MAXSHOUTS : "Maximum number of shoutbox entries",
		INSTALL_STEP5_ENTER_USE_PHPMAILER : "Use PHPMailer if your server does not support sending emails by default",
		INSTALL_PHPMAILER_HOST : "SMPT Host",
		INSTALL_PHPMAILER_HOST_EXAMPLE : "e.g. smtp.provider.com",
		INSTALL_PHPMAILER_USER : "SMPT Username",
		INSTALL_PHPMAILER_USER_EXAMPLE : "e.g. user@provider.dcom",
		INSTALL_PHPMAILER_PASS : "SMPT password",
		INSTALL_PHPMAILER_SECURE : "Authentification method (e.g. ssl)",
		INSTALL_PHPMAILER_PORT : "SMTP Port",
		INSTALL_STEP6_INTRO : "Please define a password for the <strong>admin</strong> account which you have to use for your first logon to the Galaxytool after the installation.",
		INSTALL_STEP7_CONFIG : "Configuration file created",
		INSTALL_STEP7_CONFIG_FAILED : "Configuration file not created",
		INSTALL_STEP7_ATTRIBUTES : "Attributes file created",
		INSTALL_STEP7_ATTRIBUTES_FAILED : "Attributes file not created",
		INSTALL_STEP7_CREATED_TABLES : "Database tables created",
		INSTALL_STEP8_INTRO : "You have successfully installed the Galaxytool!",
		INSTALL_STEP8_LOAD_DATA : "Downloading OGame data ...",
		INSTALL_STEP8_LOAD_DATA_FINISHED : "Download of OGame data finished",
		INSTALL_STEP8_DELETE_FILE : "You should now delete the installation files install.php and update.php from your webserver.",
		INSTALL_STEP8_LOGON : "Please logon with the <strong>admin</strong> user and the password you defined earlier.",
		UPDATE_START : "Starting update to version &1",
		UPDATE_STEP_DONE : "Done",
		UPDATE_TITLE : "Galaxytool update for version",
		UPDATE_STEP1_WELCOME : "Welcome to the update wizard of the Galaxytool. You will be guided through the update of the Galaxytool.",
		UPDATE_STEP1_BACKUP_FILES : "As a first step, make a backup of your <strong>config</strong> folder! You will have to replace the configuration content in case of errors.",
		UPDATE_STEP1_BACKUP_DB : "Then make a <a href=\"http://www.ehow.com/how_2036600_create-database-php.html\">backup</a> of your database.",
		UPDATE_STEP1_PROCEED : "Once the backups have been done, you can proceed with your update.",
		UPDATE_STEP1 : "Welcome",
		UPDATE_STEP2 : "Galaxytool settings",
		UPDATE_STEP2_OLD_VERSION : "Previous Galaxytool version",
		UPDATE_STEP3 : "Update Galaxytool",
		UPDATE_STEP3_UPDATE_RUNNING : "Update running, please wait...",
		UPDATE_STEP4 : "Finalize Update",
		UPDATE_STEP4_INTRO : "You have successfully updated the Galaxytool!",
		UPDATE_STEP4_UPDATE_DONE : "Update steps performed.",
		UPDATE_FAILED : "Update failed.",
		GALAXYTOOL_DUMMY_TEXT : "dummy"
	})
);