define(
	({
		REPORT_WHEN : "",
		RESOURCES_ON : "Resursų",
		PLAYER_BANNED : "b",
		PLAYER_VACATION_MODE : "v",
		PLAYER_NOOB : "n",
		PLAYER_INACTIVE : "i",
		PLAYER_LONG_INACTIVE : "I",
		PLAYER_OUTLAW : "o",
		L_USERNAME : "Vartotojas",
		L_PASSWORD : "Slaptažodis",
		L_LOGINFAILURE : "Vartotojo vardas arba slaptažodis neteisingi arba vartotojas neaktyvuotas",
		L_TOKENFAILURE : "Your logon key is wrong or your account is not activated yet.",
		L_LOGINTEXT : "Prašome prisijungti.",
		L_LANGUAGE : "Galimos kalbos:",
		L_TIMEOUT : "Sesija pasibaigė!",
		L_REGISTER : "Registruotis",
		L_PWLOST : "prarastas slaptažodis",
		INDEX_TITLE : "OGame Galaxytool - Peržiūra",
		INDEX_INFO : "Informacija",
		INDEX_ENTRIES : "Iš viso sistemų",
		INDEX_ENTRIES_LASTWEEK : "Naujos sistemos iš praeitos savaitės",
		INDEX_ENTRIES_TO_OLD : "Sistemos senesnės nei mėnuo",
		INDEX_REGISTERED_USERS : "Užsiregistravę vartotojai",
		INDEX_PAGEFORWARD : "Jei jūsų naršyklė nepalaiko page forwarding, spauskite čia.",
		INDEX_NOTICES : "Žinutės",
		INDEX_PLAYERS : "Žaidėjų statistika",
		INDEX_ALLIES : "Aljansų statistika",
		INDEX_REPORTS : "Špionažo ataskaitos",
		INDEX_VERSION : "Atsisiųsti naujausią versiją",
		INDEX_LATEST_VERSION : "Nėra naujesnės versijos",
		INDEX_SHOUTBOX : "ShoutBox",
		INDEX_NOENTRY : "Nėra įrašų",
		INDEX_COMMENT : "Tavo įrašas",
		INDEX_INSERT : "Siųsti",
		INDEX_UMOD : "Žaidėjas atostogų režime",
		INDEX_NO_MOONS : "Mėnuliai",
		INDEX_NO_EMPTY_SYSTEMS : "Tuščios sistemos",
		INDEX_NO_FULL_SYSTEMS : "Pilnos sistemos",
		INDEX_NO_TARGETS : "Potencialiūs taikiniai	",
		INDEX_USERINFO : "Vartotojų statistika",
		INDEX_ONLINE : "Dabar online",
		INDEX_TODAY : "Šiandien online",
		INDEX_ALL : "Iš viso prisijungimų",
		GENERAL_LOAD_FORM : "Load form data",
		GENERAL_SAVE_FORM : "Save form data",
		GENERAL_SAVE_AS_TEXT : "Save as",
		GENERAL_SAVE : "Save",
		INDEX_USERMANAGEMENT : "Activation Overview",
		INDEX_NEEDADMIN : "Accounts to unlock",
		INDEX_NEEDEMAIL : "Unvalidated Accounts",
		INDEX_TOOLBAR_INFO : "Galaxytool plugin information",
		INDEX_TOOLBAR_URL : "Galaxytool URL",
		INDEX_TOOLBAR_VERSION_REQUIRED : "Requires at least Galaxytool plugin version",
		INDEX_TOOLBAR_INSTALL_GUIDE : "Installation instructions for plugin",
		INDEX_TOOLBAR_TOKEN : "Logon key",
		INDEX_TOOLBAR_NEW_TOKEN : "Get new key",
		INDEX_PLAYERS_WITH_N_PLANETS : "Players with more than &1 planets",
		INDEX_GETTING_STARTED : "Getting started with the Galaxytool",
		INDEX_GETTING_STARTED1 : "Welcome to the Galaxytool!",
		INDEX_GETTING_STARTED2 : "The Galaxytool will help you to analyze what is going on in your OGame universe &1",
		INDEX_GETTING_STARTED3 : "Before you can actually analyze data you have to insert it first. For this you require a browser plugin like the &1 for Firefox.",
		INDEX_GETTING_STARTED4 : "After you installed the plugin, you navigate through your OGame pages as usual and you will see a small status window whenever something was sent to your Galaxytool.",
		INDEX_GETTING_STARTED5 : "Once the plugin inserted data into the Galaxytool, you can start to analyze where the players have their colonies, how many colonies they have, what reports exist or when they are active the most.",
		INDEX_GETTING_STARTED6 : "But it will also help you to analyze how you are progressing if you compare yourself against your competitors or by analyzing your combat reports to see how much you raided during the last days or weeks.",
		INDEX_GETTING_WIKIPAGE : "There are many more features within the Galaxytool.",
		INDEX_GETTING_WIKIPAGE2 : "Check them out at our wiki page.",
		INDEX_GETTING_BOARD : "For feedback or ideas you can use our board:",
		INDEX_GETTING_CHAT1 : "Or visit us at the chatroom:",
		INDEX_GETTING_CHAT2 : "We are not online 24/7 but spare a lot of our free time there, so be patient.",
		INDEX_CLOSE : "Close",
		INDEX_LOGIN : "Login",
		GENERAL_REQUIRED_FIELDS : "Please fill all required fields",
		INDEX_MESSAGES : "Messages",
		INDEX_EXAMPLE : "Example",
		INDEX_INVALID_DATA : "Invalid data",
		GENERAL_COLUMN_HIDE_TITLE : "Manage columns",
		GENERAL_COLUMN_HIDE_INFO : "Please select which columns you want to see in the table.",
		GENERAL_ENTRIES_DELETED : "&1 entries deleted",
		GENERAL_APPLY : "Apply",
		STARTPAGE_GALAXYTOOL_DESCR : "<em>Galaxytool</em> is a tool for the browser game OGame.",
		GENERAL_OVERWRITE : "Overwrite duplicate entry",
		GENERAL_OVERWRITE_QUESTION : "Overwrite?",
		INDEX_OWN_LOGINS : "Your logins",
		GENERAL_OPEN_IN_NEW_WINDOW : "Atverti saistomą objektą naujame lange",
		GENERAL_UNIT_OF_MEASURE_DAYS : "Days",
		PROGRAM_NAME : "OGame Galaxytool",
		SHORTNAME : "Galaxytool",
		BACK_INDEX : "Atgal į pagrindinį",
		UNIVERSE : "Visata",
		MENU_INFO_LINKS : "Informacija",
		MENU_PAGE : "Peržiūra",
		MENU_DB_SEARCH : "Ieškoti duomenų bazėj",
		MENU_DB_NOTICES : "Ieškoti žinutėse",
		MENU_DB_REPORTS : "Ieškoti ataskaitose",
		MENU_GALAXYVIEW : "Žiūrėti sistemą",
		MENU_STATISTICS : "Statistika",
		MENU_ALLYHISTORY : "Istorinė peržiūra",
		MENU_FLEET_MOVEMENTS : "Fleet movements",
		MENU_COMBAT_REPORTS : "Combat reports",
		MENU_MESSAGES : "Ingame messages",
		MENU_OPTION_LINKS : "Nustatymai",
		MENU_DB_REFRESH : "Įrašyti į duomenų bazę",
		MENU_NOTICES : "Žinutės",
		MENU_DB_STATUS : "Duomenų bazės būklė",
		MENU_USEROPTIONS : "Vartotojų tvarkymas",
		MENU_USEROPTIONS2 : "Vartotojų nustatymai",
		MENU_USEROPTIONS3 : "Vartotojų informacija",
		MENU_ADMIN : "Valdymas",
		MENU_LOGOUT : "Logout",
		MENU_STUFF : "Įvairūs",
		MENU_FORUM_THREAD : "Kūrėjų forumas",
		MENU_DOWNLOADPAGE : "Parsisiuntimas",
		MENU_LANGUAGE : "Kalba",
		MENU_HELP : "Pagalba",
		MENU_TOOLOPTIONS : "Galaxytool nustatymai",
		PARSER_INFO1 : " įrašyta į duomenų bazę",
		PARSER_ERROR1 : "Klaida bandant įrašyti šias koordinates",
		PARSER_ERROR2 : "Nerasta duomenų bazės!",
		PARSER_ERROR3 : "Nerastas duomenų bazės serveris!",
		PARSER_WRONG_UNIVERSE : "Wrong universe - actual: \"&1\"  expected: \"&2\"",
		SHOW_TITLE : "OGame Galaxytool - Paieška",
		SHOW_SEARCH : "Ieškoti duomenų bazėj",
		SHOW_ALLYSYMBOL : "Aljanso etiketė",
		SHOW_PLAYERNAME : "Žaidėjas",
		SHOW_MOONS : "Tik planetos su palydovais",
		SHOW_NOTICES : "Tik planetos su žinutėm",
		SHOW_COLONIES : "Tik planetos kolonizacijai",
		SHOW_YES : "Taip",
		SHOW_NO : "Ne",
		SHOW_SEARCHRANGE : "Apimtis",
		SHOW_SEARCH_IN : "Ieškoti sistemoje",
		SHOW_FROM_SYSTEM : "nuo sistemos pozicijoje",
		SHOW_FROM_PLANET : "nuo planetos pozicijoje",
		SHOW_TO : "iki",
		SHOW_DESCRIPTION : "Galite naudoti <i>wildcards</i> * žaidėjų vardams arba aljansų pavadinimams. Pavyzdžiui, ieškant &quot;*vardas*&quot; bus surasti visi žaidėjai kurių varduose yra tekstas &quot;vardas&quot;<br />Nebūtina užpildyti visus laukelius",
		SHOW_SORT_BY : "Rikiuoti pagal",
		SHOW_GALASYSTEM : "Galaktiką/Sistemą",
		SHOW_ALLYNAME : "Aljanso pavadinimą",
		SHOW_SEARCHBUTTON : "Ieškoti",
		SHOW_ADDRESS : "Koordinatės",
		SHOW_ALLYSORT : "Aljansas",
		SHOW_PLANET : "Planeta",
		SHOW_STATUS : "Statusas",
		SHOW_CURRENTNESS : "Atnaujinta",
		SHOW_PLAYER_STATUS : "Žaidėjo statusas",
		SHOW_PLAYER_STATUS1 : "visi",
		SHOW_PLAYER_STATUS2 : "potencialūs taikiniai",
		SHOW_PLAYER_STATUS3 : "neaktyvus",
		SHOW_HITS : "Rezultatai",
		SHOW_OF : "iš",
		SHOW_ASC : "didėjantys",
		SHOW_DESC : "mažėjantys",
		SHOW_RESULTS : "Rezultatų per puslapį",
		SHOW_MOON : "Palydovas",
		SHOW_UKMOONSIZE : "nežinoma",
		SHOW_DF : "DF",
		SHOW_DF_LONG : "Atliekos",
		SHOW_METAL : "M",
		SHOW_METAL_LONG : "Metalas",
		SHOW_CRYSTAL : "K",
		SHOW_CRYSTAL_LONG : "Kristalai",
		SHOW_BOTH : "kartu sudėjus",
		SHOW_AT_LEAST : "(bent)",
		SHOW_DATE : "Data",
		SHOW_DATE_0 : "nesvarbu",
		SHOW_DATE_1 : "senesni nei",
		SHOW_DATE_2 : "naujesni nei",
		SHOW_RANK : "Rangas",
		SHOW_FRANK : "Flotilės rangas",
		SHOW_MEMBERS : "Nariai",
		SHOW_NOTRANKED : "Nėra duomenų",
		SHOW_NOTICERES : "Žinutės",
		SHOW_REPORTS : "Planetos tik su ataskaitom",
		SHOW_REPORTS_SHORT : "Ataskaitos",
		SHOW_NOTHING : "Nerasta įrašo",
		SHOW_ALLIANCE_STATUS : "Aljanso diplomatinis statusas",
		SHOW_NO_STATUS : "nėra",
		SHOW_NAP : "NAP",
		SHOW_ALLIED : "Sąjunga",
		SHOW_WAR : "Karas",
		SHOW_BOYCOTT : "Boikotas",
		SHOW_NEUTRAL : "Neutralus",
		SHOW_OWN : "Savas ",
		SHOW_WING : "Sparnas",
		SHOW_EXT_OPTIONS1 : "Patikslinti, rangą, datą arba nuolaužų lauką",
		SHOW_EXT_OPTIONS2 : "Patikslinti kolonijas, palydovus, ataskaitas, žaidėjų statusą arba diplomatinį statusą",
		SHOW_EXT_OPTIONS3 : "Keisti paieškos rezultatų rikiavimo nustatymus",
		SHOW_EXTENDED : "advanced search",
		SHOW_MOON_SELECTION : "Planet with moon",
		SHOW_REPORT_SELECTION : "Planet with report",
		SHOW_FILTER_BY : "Exclude from the list",
		SHOW_FILTER_NONE : "jokių",
		SHOW_PLAYERS_WITHOUT_PROGRESS : "Show players without score changes within the last few days",
		STATUS_TITLE : "OGame Galaxytool - Statusas",
		STATUS_DB_STATUS : "Duomenų bazės statusas",
		STATUS_COLOR : "Spalva",
		STATUS_AGE1 : "Įrašas 1 dienos senumo.",
		STATUS_AGE2 : "Įrašas 2-4 dienų senumo.",
		STATUS_AGE3 : "Įrašas 4-7 dienų senumo.",
		STATUS_AGE4 : "Įrašas 1-2 savaičių senumo.",
		STATUS_AGE5 : "Įrašas 2-4 savaičių senumo.",
		STATUS_AGE6 : "Įrašas senesnis nei 1 mėnuo!",
		STATUS_AGE7 : "Nėra įrašų.",
		STATUS_ON : "w",
		STYLES_COLOR1 : "Spalva1",
		STYLES_COLOR2 : "Spalva2",
		STYLES_COLOR3 : "Spalva3",
		STYLES_COLOR4 : "Spalva4",
		STYLES_COLOR5 : "Spalva5",
		STYLES_COLOR6 : "Spalva6",
		STYLES_COLOR7 : "Spalva7",
		STATUS_DB_LEGEND : "Legend",
		STATUS_GALAXY : "Galaxy Overview",
		USER_TITLE : "Vartotojų tvarkymas",
		USER_NAMES : "Vartotojas",
		USER_ERROR : "Klaida",
		USER_NEWUSER : "Naujas vartotojas",
		USER_OPTIONS : "Nustatymai",
		USER_USERNAME : "Vartotojas",
		USER_PASSWORD : "Slaptažodis",
		USER_PASSWORD_CONFIRM : "Patvirtinkite slaptažodį",
		USER_GALAXY : "Galaktika",
		USER_SEARCH : "Ieškoti",
		USER_INSERT : "Pridėti įrašą",
		USER_DELETE : "Trinti",
		USER_DELETE_ENTRY : "Ar norite ištrinti vartotoją: ",
		USER_STATUS : "Žiūrėti statistiką",
		USER_STYLES : "Keisti išvaizdą",
		USER_SUBMIT : "Patvirtinti",
		USER_RESET : "Trinti",
		USER_YES : "Taip",
		USER_NO : "Ne",
		USER_STYLEPATH : "Kelias į styles.css",
		USER_PROBES : "Špionažo ataskaitos",
		USER_EMAIL : "Email",
		USER_ERROR1 : "Neteisingas slaptažodis arba email",
		USER_ERROR2 : "Neteisingas email.",
		USER_INGAME : "Vardas žaidime",
		USER_ALLYTAG : "Aljanso Etiketė",
		USER_ALLYHISTORY : "Istorijos peržiūra",
		USER_DIPLOMATIC : "Pakeisti diplomatinį statusą",
		USER_STATSPAGE : "Įrašų statistikos puslapyje",
		USER_LINKS : "Nuorodos",
		USER_LINKS2 : "Formatas:<br>text;url<br>text2;url2<br>text3;url3",
		USER_EXPORT_TITLE : "Eksportuoti spalvas (BB Code)",
		USER_BB_COORDINATES : "Koordinatės",
		USER_BB_MOON : "Palydovas",
		USER_BB_DEBRIS : "Nuolaužos",
		USER_BB_ALLY : "Aljanso pavadinimas",
		USER_BB_ALLYDETAILS : "Aljanso informacija",
		USER_BB_PLAYERNAME : "Žaidėjas",
		USER_BB_BANNED : "pašalintas",
		USER_BB_VACATION : "atostogų režimas",
		USER_BB_NOOB : "Noob",
		USER_BB_INACTIVE : "neaktyvus 7d.",
		USER_BB_LONGINACTIVE : "neaktyvus 28d.",
		USER_DELETION : "Delete",
		USER_FLEETINFO : "Fleet movements",
		USER_ACTIVITIES : "Player activities",
		USER_MAINTENANCE : "Galaxytool maintenance",
		USER_MANAGEMENT : "Vartotojų tvarkymas",
		USER_DELETE_MY_COMBAT_REPORTS : "Delete my combat reports",
		USER_DELETE_MY_MESSAGES : "Delete my messages",
		USER_DELETE_MY_FLEETMOVES : "Delete my fleet movements",
		USER_DELETE_MY_COMBAT_REPORTS_LIMITED : "Delete my combat reports older than &1 days",
		USER_DELETE_MY_MESSAGES_LIMITED : "Delete my messages older than &1 days",
		USER_TABLE_ENTRIES : "Number of search results for each page",
		USER_EXISTS : "User already exists",
		USER_BB_OUTLAW : "Outlaw",
		USER_INVALID_URL : "URL &1 seems to be invalid - URL will be ignored",
		VIEW_TITLE : "OGame Galaxytool - Sistema",
		VIEW_NODATA : "Nėra duomenų	.",
		VIEW_GALAXY : "Galaktika",
		VIEW_SYSTEM : "Sistema",
		VIEW_POSITION : "Vieta",
		VIEW_PLANET : "Planeta",
		VIEW_MOON : "Palydovas",
		VIEW_TF : "DF",
		VIEW_PLAYER : "Žaidėjas",
		VIEW_PLAYER_ADD : "(Rangas / Statusas)",
		VIEW_ALLY : "Aljansas",
		VIEW_ALLY_ADD : "(Rangas / Statusas)",
		VIEW_METAL : "M",
		VIEW_CRYSTAL : "K",
		VIEW_COLONISED : "Užimos planetos",
		VIEW_UKMOONSIZE : "nežinoma",
		VIEW_BACK : "atgal",
		VIEW_NOTICE : "Žinutės",
		VIEW_REPORTS : "Ataskaitos",
		VIEW_MOONPHALANX : "Šie mėnuliai gali nuskaityti šią sistemą",
		VIEW_NOMOONS : "Nerasta mėnulių",
		VIEW_IRAKS : "Ši planeta gali pasiekti šią sistemą su Tarpplanetinėm Raketom",
		VIEW_NOIRAKS : "Nerasta tarpplanetinių Raketų",
		VIEW_MOON_DESTROY_CHANCE : "Tikimybė sunaikinti palydovą",
		VIEW_CHANCE_WITH_ONE : "Tikimybė sunaikinti su viena Mirties Žvaigde",
		VIEW_CHANCE_WITH_N : "Tikimybė su ",
		VIEW_DEATH_STARS : "Mirties Žvaigždėm",
		VIEW_DS_DESTROY_CHANCE : "Tikimybė prarasti Mirties Žvaigždė(es)",
		VIEW_TOP : "Top",
		VIEW_GO : "go",
		VIEW_DIAMETER : "Diameter",
		PW_TITLE : "OGame Galaxytool - Keisti slaptažodį",
		OLD_PASSWORD : "senas slaptažodis",
		NEW_PASSWORD : "naujas slaptažodis",
		CONFIRM_NEW_PASSWORD : "Pakartokite naują slaptažodį",
		PW_MISMATCH : "Slaptažodžiai nesutampa",
		PW_ERROR : "Senas slaptažodis neteisingas!",
		UPDATE_DONE : "Pakeista.",
		TIMEZONE_OFFSET : "Laiko skirtumas nuo serverio laiko",
		DELETE_ACCOUNT : "Trinti šį vartotoją",
		DELETE_ACCOUNT_SAFETY_REQUEST : "Ar tikrai norite ištrinti šį vartotoją?",
		CH_PASSWD_AUTHORIZATION : "Authorizations",
		CH_PASSWD_ADMIN : "Admin",
		TIMEZONE_OGAME_OFFSET : "Timezone offset to OGame server",
		CH_PASSWD_USER_LANGUAGE : "Change to this language after logon",
		CH_PASSWD_USER_LANGUAGE_NO_CHANGE : "No change",
		CH_PASSWD_EXPAND : "Expanded",
		CH_PASSWD_COLLAPSE : "Collapsed",
		CH_PASSWD_HIDDEN : "Hidden",
		CH_PASSWD_GETTING_STARTED : "Show Getting Started Info after logon",
		CH_PASSWD_PLUGIN : "Show Plugin Info after logon",
		NOTICE_TITLE : "OGame Galaxytool - Žinutės",
		NOTICE_HEADER : "keisti žinutę",
		NOTICE_HEADER2 : "keisti savo žinutes",
		NOTICE_PUBLIC : "Matoma kitų?",
		NOTICE_YES : "taip",
		NOTICE_NO : "ne",
		NOTICE_TEXT : "Žinutės tekstas",
		NOTICE_SAVE : "Saugoti",
		NOTICE_DELETED : "Įrašas ištrintas",
		NOTICE_SAVED : "Įrašas išsaugotas.",
		NOTICE_RESULTS : "Visi įrašai",
		NOTICE_USER : "Vartotojas",
		NOTICE_DATE : "Data",
		NOTICE_EDIT : "Keisti",
		NOTICE_DELETE : "Trinti",
		NOTICE_NEW : "Kurti naują",
		NOTICE_NOTPUBLIC : "Privati žinutė",
		NOTICE_ALL : "Visos",
		NOTICE_NONE : "jokių",
		NOTICE_SEARCH : "Ieškoti žinutėse",
		NOTICE_SEARCH_SHORT : "Ieškoti",
		NOTICE_HITS : "Rezultatų",
		NOTICE_SHOWRESULTS : "Rezultatų puslapyje",
		NOTICE_OF : "iš",
		NOTICE_NOTHING : "Nerasta įrašo",
		NOTICE_CHARS : "ženklai",
		NOTICE_PLAYERNAME : "Žaidėjas",
		NOTICE_SHOWALL : "Rodyti visas žinutes",
		REPORTS_TITLE : "OGame Galaxytool - Špionažo Ataskaitos",
		REPORTS_RESOURCES : "Resursai",
		REPORTS_FLEET : "Flotilės",
		REPORTS_DEFENCE : "Gynyba",
		REPORTS_BUILDINGS : "Pastatai",
		REPORTS_TECHNOLOGY : "Išradimai",
		REPORTS_MOON : "Palydovas",
		REPORTS_SEARCH : "Ieškoti špionažo ataskaitose",
		REPORTS_SEARCH_SHORT : "Ieškoti",
		REPORTS_HITS : "Rezultatų",
		REPORTS_NOTHING : "Nerasta įrašo",
		REPORTS_ADDRESS : "Koordinatės",
		REPORTS_CURRENTNESS : "Senumas",
		REPORTS_PLAYERNAME : "Žaidėjas",
		REPORTS_ALLY : "Aljansas",
		REPORTS_VIEW : "rodyti ataskaitą",
		REPORTS_SEARCH_IN : "Ieškoti galaktikoje",
		REPORTS_FROM_SYSTEM : "nuo sistemos",
		REPORTS_TO : "iki",
		REPORTS_DELETE : "trinti",
		REPORTS_DELETED : "Įrašas ištrintas",
		REPORTS_RESULTS : "Rezultatų puslapyje",
		REPORTS_OF : "iš",
		REPORTS_DATE : "Data",
		REPORTS_DATE_0 : "nesvarbu",
		REPORTS_DATE_1 : "senesni nei",
		REPORTS_DATE_2 : "naujesni nei",
		REPORTS_NOTICES : "Žinutės",
		REPORTS_AT_LEAST_RESOURCES : "Resursai (mažiausiai)",
		REPORTS_SEARCH_EXTENDED : "išplėsta paieška",
		REPORTS_FLEET_RESIS : "Flotilė - taškai",
		REPORTS_DEFENCE_RESIS : "Gynyba - taškai",
		REPORTS_ALL_RESIS : "suma",
		REPORTS_TECHS : "Technologijos",
		REPORTS_UNKNOWN_ENTRIES : "nežinomi įrašai",
		REPORTS_PARTLY_INSERTED : "nepilnai įterpti",
		REPORTS_FOR_ALL_RES : "visiem resursam",
		REPORTS_FOR_TF : "nuolaužom",
		REPORTS_KT : "Maži Krovininiai Laivai",
		REPORTS_GT : "Dideli Krovininiai Laivai",
		REPORTS_SS : "Šarvuotlaiviai",
		REPORTS_REC : "Perdirbėjas",
		REPORTS_RAIDABLE : "Tik potencialūs taikiniai",
		REPORTS_ALL_RESOURCES : "visi resursai",
		REPORTS_STUFF : "Įvairūs",
		REPORTS_SPEEDSIM : "Simuliuoti su Speedsim",
		REPORTS_DRAGOSIM : "Simuliuoti su Dragosim",
		REPORTS_STATUS : "Statusas",
		REPORTS_ERROR : "Įvyko klaida",
		REPORTS_OWN_REPORTS : "Tik mano ataskaitos",
		REPORTS_UPLOAD_BY : "Report uploaded by",
		REPORTS_DEPTH : "Report depth",
		REPORTS_FLEET_SCORE : "Fleet score",
		REPORTS_DEFENCE_SCORE : "Defence score",
		REPORTS_HOURS : "hours",
		REPORTS_MAX_RESULTS_HIT : "Your query returned more than &1 hits. Only the first &1 results are show. Please adjust your search request to get less results.",
		REPORTS_OSIMULATE : "Simulate with OSimulate",
		REPORTS_SHOW_ONLY : "Show only",
		REPORTS_SHOW_PLANETS : "Planetos",
		REPORTS_SHOW_MOONS : "Palydovai",
		REPORTS_OWNER : "Reports owned by",
		STATS_TITLE : "OGame Galaxytool - Statistika",
		STATS_TBLHEAD : "Statistika",
		STATS_RANK : "Rangas",
		STATS_PLAYERNAME : "Žaidėjo vardas",
		STATS_ALLYNAME : "Aljanso Etiketė",
		STATS_SCORE : "Taškai",
		STATS_FLEET : "Flotilė",
		STATS_RESEARCH : "Išradimai",
		STATS_MEMBERS : "Nariai",
		STATS_STATUS : "Statusas",
		STATS_NOTHING : "nėra",
		STATS_NAP : "NAP",
		STATS_ALLIED : "Sąjunga",
		STATS_WAR : "Karas",
		STATS_BOYCOTT : "Boikotas",
		STATS_NEUTRAL : "Neutralus",
		STATS_OWN : "Savas",
		STATS_WING : "Sparnas",
		STATS_UPDATE : "Įrašas iš",
		STATS_PLAYERSTATS : "Žaidėjų statistika",
		STATS_ALLYSTATS : "Aljansų statistika",
		STATS_DELETE : "Ar norite ištrinti šį įrašą?",
		STATS_CONFIRM_DELETE : "Ar tikrai norite ištrinti šį įrašą?",
		STATS_CHANGE_PLAYER_STATUS : "Žaidėjo statusas",
		STATS_CHANGE_ALLIANCE_STATUS : "Aljanso statusas",
		STATS_CHANGE_ALLIANCE_STATUS_HINT : "Visi šio aljanso nariai gaus šį statusa. Paskui galite pakeisti individualių narių statusą.",
		STATS_UNKNOWN : "Kiti",
		STATS_DETAILS : "Informacija",
		STATS_PLAYERSTATUS : "Žaidėjo statusas",
		STATS_IGNORE_STATUS : "visi",
		STATS_ACTIVE : "active",
		STATS_INACTIVE : "neaktyvus 7d.",
		STATS_BANNED : "pašalintas",
		STATS_VACATION : "atostogų režimas",
		STATS_NOOB : "Noob",
		STATS_YES : "Taip",
		STATS_NO : "Tik planetos su žinutėm",
		STATS_SEARCH : "Ieškoti",
		STATS_SHOW_GRAPH : "Show details for score distribution",
		STATS_LONG_INACTIVE : "neaktyvus 28d.",
		STATS_STANDARD : "Standard Points",
		STATS_MILITARY : "Military Points",
		STATS_ECONOMY : "Economy",
		STATS_HONOUR : "Honour points",
		STATS_MILITARY_BUILD : "Military build",
		STATS_MILITARY_DESTROYED : "Military destroyed",
		STATS_MILITARY_LOST : "Military lost",
		REGISTER_REGISTRATE : "Registruotis",
		REGISTER_LOGINNAME : "Žaidėjas",
		REGISTER_PASSWORD : "Slaptažodis",
		REGISTER_PASSWORD_CONFIRM : "Pakartoti slaptažodį",
		REGISTER_EMAIL : "Email",
		REGISTER_INGAME : "Ingame-Name",
		REGISTER_ALLYTAG : "Aljanso etiketė",
		REGISTER_EMAILVERIFICATION : "El. pašto patikrinimas",
		REGISTER_EMAILTEXT : "Prašome paspausti ant šios nuorodos kad patvirtinti jūsų galaxytool registraciją.",
		REGISTER_ERROR1 : "Šis prisijungimo vardas jau naudojamas.",
		REGISTER_ERROR2 : "Error while trying to send an email. Please contact your admin.",
		REGISTER_ERROR3 : "Error while trying to send data to the database!",
		REGISTER_INFO1 : "Jūs užregistruotas.",
		REGISTER_INFO2 : "Prašome paspausti ant nuorodos laiške kad patvirtinti jūsų galaxytool registraciją.",
		REGISTER_INFO3 : "Registracija patvirtinta. Laukite kol administratorius jus aktyvuos.",
		REGISTER_BUTTON : "Atgal į pagrindinį",
		REGISTER_NEW_SUBJECT : "Vartotojas užregistruotas galaxytool",
		REGISTER_NEW_MAILTEXT : "Naujas vartotojas užregistruotas galaxytool sistemoje.",
		REGISTER_BACK : "Atgal į pagrindinį",
		REGISTER_MISSING_FIELDS : "Enter all required Fields",
		REGISTER_ERROR4 : "Email address is not valid.",
		REGISTER_ERROR5 : "Passwords don't match.",
		REGISTER_PWS : "Password strength",
		REGISTER_PWS0 : "very weak",
		REGISTER_PWS1 : "weak",
		REGISTER_PWS2 : "good",
		REGISTER_PWS3 : "strong",
		REGISTER_PWS4 : "very strong",
		REGISTER_EMAIL_USED : "Email Address is already used",
		LOSTPW_TITLE : "Lost my Password",
		LOSTPW_INFO2 : "A new password was generated and send to your email address.",
		LOSTPW_BUTTON1 : "get new password",
		LOSTPW_BUTTON2 : "Back to main page",
		LOSTPW_LOGINNAME : "Login-Name",
		LOSTPW_EMAIL : "Email",
		LOSTPW_ERROR1 : "Error while trying to send data to the database!",
		LOSTPW_ERROR2 : "No matching entry found!",
		LOSTPW_ERROR3 : "Error while trying to send an email. Please contact your admin.",
		LOSTPW_EMAIL_SUBJECT : "Your new password you requested",
		LOSTPW_EMAIL_TEXT1 : "Here is your new login for the Galaxytool",
		LOSTPW_EMAIL_TEXT2 : "Username",
		LOSTPW_EMAIL_TEXT3 : "Password",
		LOSTPW_INFO1 : "You will receive an email to verify your password reset request.",
		LOSTPW_CONFIRM_RESET_SUBJECT : "Lost password?",
		LOSTPW_CONFIRM_RESET_MESSAGE : "Hello,\n\nyou requested a password reset for the Galaxytool. To generate a new password, click the following link:",
		USERINFO_TITLE : "OGame Galaxytool - Vartotojų informacija",
		USERINFO_NAMES : "Visi vartotojai",
		USERINFO_DETAIL : "detali informacija apie",
		USERINFO_ERROR1 : "Nerasta žaidėjo su šiuo ID",
		USERINFO_USERNAME : "Nazwa użytkownika",
		USERINFO_INGAME : "Žaidėjas",
		USERINFO_EMAIL : "Email",
		USERINFO_ALLYTAG : "Aljansas",
		USERINFO_STYLEPATH : "Skin'as",
		USERINFO_STATUS : "Būsena",
		USERINFO_ACTIVATE : "Aktivuoti vartotoją",
		USERINFO_LOGINS : "Prisijungimų skaičius",
		USERINFO_LASTLOGIN : "Paskutinis prisijungimas",
		USERINFO_DATA : "Informacija apie įvestas sistemas",
		USERINFO_NODATA : "Šis žaidėjas dar neįrašė jokios informacijos!",
		USERINFO_GALAXY : "Sistema",
		USERINFO_SYSTEMS : "Sistemų",
		USERINFO_IP : "IP adresas",
		USERINFO_LOGINTIME : "Prisijungta",
		USERINFO_NOLOGIN : "Šis žaidėjas niekada neprisijungė.",
		USERINFO_LAST_GALAXYUPDATE : "Paskutinis įdėtas galaktikos puslapis",
		USERINFO_LAST_PUBLIC_NOTICE : "Paskutinė vieša žinutė",
		USERINFO_LAST_PRIVATE_NOTICE : "Paskutinė privati žinutė",
		USERINFO_NUMBEROF_PUBLIC_NOTICE : "Viešų žinučių:",
		USERINFO_NUMBEROF_PRIVATE_NOTICE : "Privačių žinučių",
		USERINFO_ACTIVATED : "Vartotojas sukurtas",
		USERINFO_ACTIVATIONTEXT : "Galaxytool administratorius aktyvavo jūsų vartotoją.</ br>sėkmės naudojant Galaxytool!",
		USERINFO_LAST_SUBMIT : "Inserted last data",
		ALLYHISTORY_TITLE : "OGame Galaxytool - Aljanso istorija",
		ALLYHISTORY_TBLHEAD : "Istorinė peržiūra",
		ALLYHISTORY_PLAYERNAME : "Žaidėjas",
		ALLYHISTORY_ALLYNAME : "Aljansas",
		ALLYHISTORY_LASTMONTH : "Praeitas mėnuo",
		ALLYHISTORY_ALL_DATA : "visa įmanoma informacija",
		ALLYHISTORY_SHOW : "rodyti statistiką",
		ALLYHISTORY_TIMESPAN : "Laikas",
		ALLYHISTORY_PROGESS : "Progresas",
		ALLYHISTORY_SCORE : "Taškai",
		ALLYHISTORY_FSCORE : "Flotilės",
		ALLYHISTORY_RSCORE : "Išradimai",
		ALLYHISTORY_MEMBER : "Nariai",
		ALLYHISTORY_NOTHING : "nerasta įrašų",
		ALLYHISTORY_DETAILS : "Detalės",
		ALLYHISTORY_SHOW_ADDRESS : "Koordinatės",
		ALLYHISTORY_ESCORE : "Economy",
		ALLYHISTORY_MSCORE : "Military Points",
		DETAILEDINFO_PLAYERINFO_TITLE : "Informacija apie žaidėją",
		DETAILEDINFO_ALLYINFO_TITLE : "Informacija apie aljansą",
		DETAILEDINFO_PLAYERINFO_TBLHEAD : "Išsami informacija apie žaidėją",
		DETAILEDINFO_ALLYINFO_TBLHEAD : "Išsami informacija apie aljansą",
		DETAILEDINFO_NO_ALLIANCE : "joks",
		DETAILEDINFO_SCORE : "Taškų statistika",
		DETAILEDINFO_FLEET : "Flotilių statistika",
		DETAILEDINFO_RESEARCH : "Išradimų statistika",
		DETAILEDINFO_RANK : "Rangas",
		DETAILEDINFO_POINTS : "Taškai",
		DETAILEDINFO_KNOWN_PLANETS : "žinomos planetos",
		DETAILEDINFO_MOONS : "žinomi palydovai",
		DETAILEDINFO_PHALANX_AREA : "Falangų zona",
		DETAILEDINFO_NO_PHALANX_AREA : "nerasta Falangų",
		DETAILEDINFO_NOTICES : "Žinutės",
		DETAILEDINFO_NO_NOTICES : "Nerasta žinučių",
		DETAILEDINFO_PREVIOUS_ALLIANCES : "ankstesni Aljansai",
		DETAILEDINFO_RESOURCES_PER_HOUR : "Resursų per valandą",
		DETAILEDINFO_RESOURCES_PER_DAY : "Resursų per dieną",
		DETAILEDINFO_RESOURCES_PER_WEEK : "Resursų per savaitę",
		DETAILEDINFO_RESOURCES_PER_MONTH : "Resursų per mėnesį (30 dienų)",
		DETAILEDINFO_METAL : "Metalas",
		DETAILEDINFO_CRYSTAL : "Kristalai",
		DETAILEDINFO_DEUTERIUM : "Deuteris",
		DETAILEDINFO_UNKNOWN : "nežinomi",
		DETAILEDINFO_SCORE_DISTRIBUTION : "Taškų pasiskirstymas",
		DETAILEDINFO_GENERAL : "Detalės",
		DETAILEDINFO_MEMBERS : "Nariai",
		DETAILEDINFO_GRAPHS : "Grafikai",
		DETAILEDINFO_RESOURCES : "Resursai",
		DETAILEDINFO_FLEET_TAB : "Flotilė",
		DETAILEDINFO_TECH : "Išradimai",
		DETAILEDINFO_FLEET_DETAIL : "Suma / (žaidėjų vidurkis) iš visų ataskaitų",
		DETAILEDINFO_TECH_DETAIL : "Visų žaidėjų informacijos vidurkis",
		DETAILEDINFO_PLANET_TAB : "Planetos",
		DETAILEDINFO_MOON_TAB : "Palydovai",
		DETAILEDINFO_ACTIVITIES : "Activities",
		DETAILEDINFO_NODATA : "Nėra duomenų	.",
		DETAILEDINFO_ACTIVITY_DESCRIPTION : "Show activities of &1 collected from:",
		DETAILEDINFO_GALAXYVIEWS : "Galaxy views",
		DETAILEDINFO_SCANS : "Espionage actions",
		DETAILEDINFO_MESSAGES : "Player messages",
		DETAILEDINFO_COMBATS : "Combat reports",
		DETAILEDINFO_ALLYPAGE : "Alliance overview",
		DETAILEDINFO_MANUAL : "Manual insertions",
		DETAILEDINFO_START : "Beginning",
		DETAILEDINFO_TO : "to",
		DETAILEDINFO_TODAY : "Today",
		DETAILEDINFO_DATA_RESTRICTION : "restricted to:",
		DETAILEDINFO_WEEKDAY_WEEKEND : "Weekend",
		DETAILEDINFO_WEEKDAY_WORKINGDAY : "Weekday",
		DETAILEDINFO_WEEKDAY_MONDAY : "Monday",
		DETAILEDINFO_WEEKDAY_TUESDAY : "Tuesday",
		DETAILEDINFO_WEEKDAY_WEDNESDAY : "Wednesday",
		DETAILEDINFO_WEEKDAY_THURSDAY : "Thursday",
		DETAILEDINFO_WEEKDAY_FRIDAY : "Friday",
		DETAILEDINFO_WEEKDAY_SATURDAY : "Saturday",
		DETAILEDINFO_WEEKDAY_SUNDAY : "Sunday",
		DETAILEDINFO_WEEKDAY_SHORTLENGTH : 3,
		DETAILEDINFO_PLAYER_CURRENTLY_ACTIVE : "The player is currently active",
		DETAILEDINFO_PLAYER_MESSAGES : "available player messages",
		DETAILEDINFO_SHOW : "show",
		DETAILEDINFO_NONE : "none available",
		DETAILEDINFO_ENTER_MANUALLY : "Enter activities for this player",
		DETAILEDINFO_PLAYER_SEEN_ON : "Player was online on",
		DETAILEDINFO_INSERT : "Insert",
		DETAILEDINFO_OGAME_SERVERTIMES : "Please note: All dates and times refer to OGame server times !",
		DETAILEDINFO_DAY_VIEW : "24 hours view",
		DETAILEDINFO_WEEK_VIEW : "weekly view",
		DETAILEDINFO_HOME_PLANET : "Homeworld",
		DETAILEDINFO_PLANETNAME : "Name",
		DETAILEDINFO_DEFENCE_SCORE : "Defence score",
		DETAILEDINFO_DEFENCE_SCORE_TOOLTIP : "Defence score = Fleet - Score + Research + Economy.<br/>All those statistics must be up to date to have a meaningful result!",
		DETAILEDINFO_SCORE_PER_SHIP : "Scores per ship",
		DETAILEDINFO_SHIPS : "Number of ships",
		DETAILEDINFO_DATE_IN_FUTURE : "Do not maintain times which are not in the past.",
		ADMIN_TITLE : "Galaxytool administracija",
		ADMIN_DISCLAMER : "Dėmesio! Jūs atsakote už šių skriptų naudojimo pasekmes. Dauguma jų trina duomenis.",
		ADMIN_INCONSISTENCIES : "Duomenų bazės nesuderinamumas",
		ADMIN_PLANETS : "Planetos pozicijoj 0 arba didesnėj nei 15",
		ADMIN_GALAXIES : "Trinti galaktikas didesnes nei &1 ",
		ADMIN_PLAYERS : "Trinti žaidėjus be OGame playerid. Pasekmė - sudvejinti žaidėjų įrašai",
		ADMIN_REPORTS : "Ištrinti ataskaitas kuriuose yra nebeegzistuojančių planetų",
		ADMIN_MISC : "Įvairūs",
		ADMIN_RESET : "Ištrinti duomenis (liks tik vartotojų ir IP duomenys)",
		ADMIN_OLD_PLAYERS : "Ištrinti senesnę nei &1 dienos informaciją apie žaidėjus ",
		ADMIN_OLD_REPORTS : "Ištrinti senesnies nei &1 dienos ataskaitas",
		ADMIN_LOADING : "Neuždarykite šio lango kol nepasikrovė puslapis.",
		ADMIN_STATUS : "Tavo prašymų būsena",
		ADMIN_SELECTION : "Turi būti pasirinktas bent vienas įrašas",
		ADMIN_SAFETY : "Ar tikrai norite ištrinti šį(iuos) skriptą(us) ?",
		ADMIN_DONE : "atlikta",
		ADMIN_NOTBD : "nėra ką atlikti",
		ADMIN_OLD_GALAXIES : "Ištrinti galaktikos puslapius senesnius nei &1 dienų",
		ADMIN_UNUSED_PLAYERS : "Ištrinti žaidėjus kurių nėra galaktikos puslapiuose",
		ADMIN_OLD_ACTIVITIES : "Remove player activities older than &1 days",
		ADMIN_OLD_COMBATS : "Remove combat reports older than &1 days",
		ADMIN_OLD_INGAME_MSG : "Remove ingame messages older than &1 days",
		ADMIN_OGAME_API : "Load public data from OGame into the Galaxytool",
		ADMIN_OGAME_ALL_DATA : "visa įmanoma informacija",
		ADMIN_OGAME_GALAXY_DATA : "Žiūrėti sistemą",
		ADMIN_OGAME_STATISTICS_DATA : "Statistika",
		ERRORPAGE_PAGEFORWARD : "Click here if your browser does not support page forwarding",
		ERRORPAGE_PERMISSION_DENIED : "You don't have the permission to enter this page. Click to go back.",
		FLEETS_TITLE : "OGame Galaxytool - Fleet movements",
		FLEETS_ACTUAL_FLEETS : "Current fleet movements",
		FLEETS_YES : "Taip",
		FLEETS_NO : "Tik planetos su žinutėm",
		FLEETS_DETAILS : "Details",
		FLEETS_MISSION_EXPEDITION : "Expedition",
		FLEETS_MISSION_COLONIZATION : "Colonize",
		FLEETS_MISSION_RECYCLE : "Harvest",
		FLEETS_MISSION_TRANSPORT : "Transport",
		FLEETS_MISSION_DEPLOYMENT : "Deploy",
		FLEETS_MISSION_ESPIONAGE : "Espionage",
		FLEETS_MISSION_ACS_DEFEND : "ACS Defend",
		FLEETS_MISSION_ATTACK : "Attack",
		FLEETS_MISSION_ACS_ATTACK : "ACS Attack",
		FLEETS_MISSION_MOON_DESTRUCTION : "Moon Destruction",
		FLEETS_MISSION_MISSILE_ATTACK : "Missile Attack",
		FLEETS_NO_DATA : "No applicable data found",
		FLEETS_FLEET : "Fleet",
		FLEETS_ALL_FLEETS : "Show all fleet movements",
		COMBAT_REPORT_OUDATED_GALAXYVIEW : "Your galaxy data is outdated. Please visit combat origin and target coordinates first!",
		MESSAGES_TITLE : "OGame Galaxytool - OGame Messages",
		MESSAGES_PLAYERNAME : "Playername",
		MESSAGES_SUBJECT : "Subject",
		MESSAGES_DATE : "Date",
		MESSAGES_FILTER : "Filter",
		MESSAGES_DELETE : "Delete message",
		MESSAGES_PUBLISH_DETAIL : "Publish message by adding the message content to notice text of that player.",
		MESSAGES_PUBLISH_HEADER : "&sender sent a message to &recipient on &date:\n\n &message",
		MESSAGES_PLAYER_FILTER : "Messages for player:",
		MESSAGES_CONTENT : "Content",
		COMBATS_TITLE : "OGame Galaxytool - Combat reports",
		COMBATS_ATTACKER : "Attacker",
		COMBATS_DEFENDER : "Defender",
		COMBATS_DATE : "Date",
		COMBATS_OWNER : "Owner",
		COMBATS_WINNER : "Winner",
		COMBATS_COMBATREPORT : "Combat Report",
		COMBATS_COMBAT_AT : "Combat at",
		COMBATS_LOST_UNITS : "Lost units",
		COMBATS_LOOT : "Loot",
		COMBATS_DEBRIS : "Debris",
		COMBATS_AND : "and",
		COMBATS_PUBLISH : "Make this report public",
		COMBATS_UNPUBLISH : "Unshare this report (makes it private again)",
		COMBATS_DELETE : "Delete report",
		COMBATS_CHECK_ALL : "Check All",
		COMBATS_UNCHECK_ALL : "Uncheck All",
		COMBATS_WITH_SELECTED : "With selected",
		COMBATS_PUBLIC_REPORTS : "Public reports",
		COMBATS_YES : "Taip",
		COMBATS_NO : "Tik planetos su žinutėm",
		COMBATS_SEARCH_OPTIONS : "Search options",
		COMBATS_SEARCH : "Go",
		COMBATS_RESET : "Reset",
		COMBATS_COORDINATES : "Koordinatės",
		COMBATS_INVALID_GALAXY_ENTERED : "Invalid Galaxy entered",
		COMBATS_INVALID_SYSTEM_ENTERED : "Invalid System entered",
		COMBATS_INVALID_PLANET_ENTERED : "Invalid Planet entered",
		COMBATS_GALAXY_FROM_TO : "Galaxy",
		COMBATS_SYSTEM_FROM_TO : "System",
		COMBATS_PLANET_FROM_TO : "Planet",
		COMBATS_APPLY : "Apply",
		COMBATS_COMBAT_SUMMARY : "Combat report summary",
		COMBATS_DOWNLOAD_CSV : "Download as CSV file",
		REPORT_ARCHIVE_TITLE : "Report archive",
		REPORT_ARCHIVE_COORDINATES : "Coordinates",
		REPORT_ARCHIVE_SCANTIME : "Scan time",
		REPORT_ARCHIVE_DELETE : "Delete these entries",
		REPORT_ARCHIVE_CONFIRM_DELETE : "Do you really want to delete these entries?",
		REPORT_ARCHIVE_GALAXY : "Galaxy",
		REPORT_ARCHIVE_SYSTEM : "System",
		REPORT_ARCHIVE_PLANET : "Planet",
		REPORT_ARCHIVE_MOON : "Moon",
		REPORT_ARCHIVE_DETAILS : "Details",
		REPORT_ARCHIVE_RESOURCES : "Resursų per valandą",
		REPORT_ARCHIVE_HEADER_RESOURCES : "Resursai",
		REPORT_ARCHIVE_DETAILS_FOR : "Report archive for &1 [&2] (&3)",
		REPORT_ARCHIVE_FLEET_CARGO : "Fleet cargo capacity",
		REPORT_ARCHIVE_IRAK_RANGE : "Interplanetary Missiles range",
		REPORT_ARCHIVE_CHART_TYPE : "Chart type",
		INSTALL_TITLE : "Galaxytool installation for version",
		INSTALL_PROGRESS : "Overall progress",
		INSTALL_STEP : "Step",
		INSTALL_CONTINUE : "Continue",
		INSTALL_VALIDATE : "Validate",
		INSTALL_STEP1 : "Welcome",
		INSTALL_STEP2 : "Writeable check",
		INSTALL_STEP3 : "Database settings",
		INSTALL_STEP4 : "OGame settings",
		INSTALL_STEP5 : "Galaxytool settings",
		INSTALL_STEP6 : "Admin password",
		INSTALL_STEP7 : "Install Galaxytool",
		INSTALL_STEP8 : "Finalize install",
		INSTALL_FILE_DELETE_CHECK : "Please delete install.php and update.php from your webserver.",
		INSTALL_STEP1_PHP_FAILED : "Your PHP version &1 is not working with this Galaxytool version",
		INSTALL_STEP1_FOPEN_FAILED : "Your PHP version does not allow to open webpages with FOPEN() command. This is required to consume the OGame API.",
		INSTALL_STEP1_WELCOME : "Welcome to the installation wizard of the Galaxytool. You will be guided through the installation of the Galaxytool.",
		INSTALL_STEP2_DESCRIPTION : "Make sure your config.php and attributes.php files have write permissions enabled.",
		INSTALL_STEP2_DESCRIPTION2 : "If you don't know, how to achieve this, please take a look here: &1",
		INSTALL_STEP2_FILE_NOT_WRITEABLE : "File is not writeable",
		INSTALL_STEP3_SERVER : "Database server",
		INSTALL_STEP3_USERNAME : "Vartotojas",
		INSTALL_STEP3_PASSWORD : "Slaptažodis",
		INSTALL_STEP3_DBNAME : "Database name",
		INSTALL_STEP3_PREFIX : "Tablename prefix",
		INSTALL_STEP3_ENTER_PREFIX : "E.g. mytool_",
		INSTALL_STEP3_ENTER_SERVER : "Enter the server address. Contact your system admin if necessary. Usually the correct value is localhost.",
		INSTALL_STEP3_ENTER_USERNAME : "Enter the username for database access",
		INSTALL_STEP3_ENTER_PASSWORD : "Enter the password for database access",
		INSTALL_STEP3_ENTER_DBNAME : "Enter the database name which shall be used for installation (must exist)",
		INSTALL_STEP3_CONNECT_FAILED : "Could not establish connection to database server",
		INSTALL_STEP3_DB_FAILED : "Database &1 not found",
		INSTALL_STEP3_MYSQL_VERSION_FAILED : "MySQL version &1 is not working with this Galaxytool version",
		INSTALL_STEP4_URL : "OGame URL",
		OGAME_URL_DETAILS : "Please enter any URL you see when you are logged on to OGame. Based on that URL the tool will derive the OGame API address which can be used to fill data into the Galaxytool without the Galaxytoolbar. This API was introduced with OGame version 4.1.",
		INSTALL_STEP4_UNIVERSE : "OGame Universe",
		INSTALL_STEP4_DEF_TO_DEBRIS : "Defense to debris",
		INSTALL_STEP4_DEBRIS_RATE : "Debris rate",
		INSTALL_STEP4_SPEED_RATE : "Speed rate",
		INSTALL_STEP4_ENTER_UNIVERSE : "Enter your OGame universe name or number (case sensitive).",
		INSTALL_STEP4_UNIVERSE_MISSING : "You must define your universe",
		INSTALL_STEP4_ENTER_URL : "Enter your OGame universe address",
		INSTALL_STEP4_URL_MISSING : "You must define your OGame address",
		INSTALL_STEP4_URL_CHECK_FAILED : "Could not find OGame API at &1",
		INSTALL_STEP4_GETSETTINGS : "Fetch settings",
		INSTALL_STEP5_TOOLNAME : "Galaxytool name",
		INSTALL_STEP5_ENTER_TOOLNAME : "This is the name which will be shown at logon page to identify your Galaxytool",
		INSTALL_STEP5_LANGUAGE : "Default language",
		INSTALL_STEP5_EMAIL_TO : "Email To",
		INSTALL_STEP5_ENTER_EMAIL_TO : "Enter the email address where you would like to receive notifications about registrations",
		INSTALL_STEP5_EMAIL_FROM : "Email From",
		INSTALL_STEP5_ENTER_EMAIL_FROM : "This email address is shown as REPLY for all mails sent from the Galaxytool",
		INSTALL_STEP5_USE_PHPMAILER : "Use PHPMailer",
		INSTALL_STEP5_MAXSHOUTS : "Maximum number of shoutbox entries",
		INSTALL_STEP5_ENTER_USE_PHPMAILER : "Use PHPMailer if your server does not support sending emails by default",
		INSTALL_PHPMAILER_HOST : "SMPT Host",
		INSTALL_PHPMAILER_HOST_EXAMPLE : "e.g. smtp.provider.com",
		INSTALL_PHPMAILER_USER : "SMPT Username",
		INSTALL_PHPMAILER_USER_EXAMPLE : "e.g. user@provider.dcom",
		INSTALL_PHPMAILER_PASS : "SMPT password",
		INSTALL_PHPMAILER_SECURE : "Authentification method (e.g. ssl)",
		INSTALL_PHPMAILER_PORT : "SMTP Port",
		INSTALL_STEP6_INTRO : "Please define a password for the <strong>admin</strong> account which you have to use for your first logon to the Galaxytool after the installation.",
		INSTALL_STEP7_CONFIG : "Configuration file created",
		INSTALL_STEP7_CONFIG_FAILED : "Configuration file not created",
		INSTALL_STEP7_ATTRIBUTES : "Attributes file created",
		INSTALL_STEP7_ATTRIBUTES_FAILED : "Attributes file not created",
		INSTALL_STEP7_CREATED_TABLES : "Database tables created",
		INSTALL_STEP8_INTRO : "You have successfully installed the Galaxytool!",
		INSTALL_STEP8_LOAD_DATA : "Downloading OGame data ...",
		INSTALL_STEP8_LOAD_DATA_FINISHED : "Download of OGame data finished",
		INSTALL_STEP8_DELETE_FILE : "You should now delete the installation files install.php and update.php from your webserver.",
		INSTALL_STEP8_LOGON : "Please logon with the <strong>admin</strong> user and the password you defined earlier.",
		UPDATE_START : "Starting update to version &1",
		UPDATE_STEP_DONE : "Done",
		UPDATE_TITLE : "Galaxytool update for version",
		UPDATE_STEP1_WELCOME : "Welcome to the update wizard of the Galaxytool. You will be guided through the update of the Galaxytool.",
		UPDATE_STEP1_BACKUP_FILES : "As a first step, make a backup of your <strong>config</strong> folder! You will have to replace the configuration content in case of errors.",
		UPDATE_STEP1_BACKUP_DB : "Then make a <a href=\"http://www.ehow.com/how_2036600_create-database-php.html\">backup</a> of your database.",
		UPDATE_STEP1_PROCEED : "Once the backups have been done, you can proceed with your update.",
		UPDATE_STEP1 : "Welcome",
		UPDATE_STEP2 : "Galaxytool settings",
		UPDATE_STEP2_OLD_VERSION : "Previous Galaxytool version",
		UPDATE_STEP3 : "Update Galaxytool",
		UPDATE_STEP3_UPDATE_RUNNING : "Update running, please wait...",
		UPDATE_STEP4 : "Finalize Update",
		UPDATE_STEP4_INTRO : "You have successfully updated the Galaxytool!",
		UPDATE_STEP4_UPDATE_DONE : "Update steps performed.",
		UPDATE_FAILED : "Update failed.",
		GALAXYTOOL_DUMMY_TEXT : "dummy"
	})
);