define(
	({
		REPORT_WHEN : "il",
		RESOURCES_ON : "Risorse su",
		PLAYER_BANNED : "b",
		PLAYER_VACATION_MODE : "v",
		PLAYER_NOOB : "d",
		PLAYER_INACTIVE : "i",
		PLAYER_LONG_INACTIVE : "I",
		PLAYER_OUTLAW : "o",
		L_USERNAME : "Username",
		L_PASSWORD : "Password",
		L_LOGINFAILURE : "L’username o la password sono errate oppure il tuo account non e’ stato ancora attivato.",
		L_TOKENFAILURE : "La tua logon key è errata o il tuo account non è ancora stato attivato",
		L_LOGINTEXT : "Per favore Logga.",
		L_LANGUAGE : "Lingue disponibili:",
		L_TIMEOUT : "Sessione in timed out!",
		L_REGISTER : "Registrati",
		L_PWLOST : "Password smarrita",
		INDEX_TITLE : "Anteprima",
		INDEX_INFO : "Informazioni",
		INDEX_ENTRIES : "Numero di tutti i Sistemi Solari",
		INDEX_ENTRIES_LASTWEEK : "Nuovi Sistemi Solari dell’ultima settimana",
		INDEX_ENTRIES_TO_OLD : "Sistemi vecchi di oltre un mese",
		INDEX_REGISTERED_USERS : "Utenti registrati",
		INDEX_PAGEFORWARD : "Se il tuo browser non supporta il reindirezionamento, clicca qui.",
		INDEX_NOTICES : "Note",
		INDEX_PLAYERS : "Statistiche Giocatore",
		INDEX_ALLIES : "Statistiche Alleanza",
		INDEX_REPORTS : "Rapporti di spionaggio",
		INDEX_VERSION : "Scarica l’ultima versione",
		INDEX_LATEST_VERSION : "Nessun aggiornamento disponibile",
		INDEX_SHOUTBOX : "Box messaggi",
		INDEX_NOENTRY : "Nessun mesaggio al momento",
		INDEX_COMMENT : "Tuoi messaggi",
		INDEX_INSERT : "Inserisci",
		INDEX_UMOD : "Utenti in modalita’ vacanza",
		INDEX_NO_MOONS : "Numero di Lune",
		INDEX_NO_EMPTY_SYSTEMS : "Numero di Sistemi vuoti",
		INDEX_NO_FULL_SYSTEMS : "Numero di Sistemi Completamente Pieni",
		INDEX_NO_TARGETS : "Numero di Possibili Obiettivi",
		INDEX_USERINFO : "Attivita’ utenti",
		INDEX_ONLINE : "Attivi ora",
		INDEX_TODAY : "Attivi oggi",
		INDEX_ALL : "Numero complessivo di login",
		GENERAL_LOAD_FORM : "Carica dati modulo",
		GENERAL_SAVE_FORM : "Salva dati modulo",
		GENERAL_SAVE_AS_TEXT : "Salva come",
		GENERAL_SAVE : "Salva",
		INDEX_USERMANAGEMENT : "Panoramica nuove registrazioni",
		INDEX_NEEDADMIN : "Accounts da sbloccare",
		INDEX_NEEDEMAIL : "Accounts da confermare",
		INDEX_TOOLBAR_INFO : "Informazioni per plugin di Galaxytool",
		INDEX_TOOLBAR_URL : "Galaxytool URL",
		INDEX_TOOLBAR_VERSION_REQUIRED : "Versione minima richiesta per Plugin di Galaxytool",
		INDEX_TOOLBAR_INSTALL_GUIDE : "Istruzioni per l'installazione del plugin",
		INDEX_TOOLBAR_TOKEN : "Chiave d'accesso",
		INDEX_TOOLBAR_NEW_TOKEN : "Genera una nuova chiave",
		INDEX_PLAYERS_WITH_N_PLANETS : "Giocatori con più di &1 pianeti",
		INDEX_GETTING_STARTED : "Introduzione a Galaxytool",
		INDEX_GETTING_STARTED1 : "Benvenuti nel Galaxytool!",
		INDEX_GETTING_STARTED2 : "Galaxytool vi aiuterà ad analizzare tutto ciò che succede nell'universo OGame nel quale giocate, ovvero l'universo &1 ",
		INDEX_GETTING_STARTED3 : "Affinchè possiate analizzare dei dati, dovete prima di tutto averli inseriti. Per questa operazione è necessario usare un plugin quale ad esempio &1 per Firefox.",
		INDEX_GETTING_STARTED4 : "Una volta completata l'installazione del plugin, vedrete apparire una piccola finestra di stato ogniqualvolta un dato viene inviato al vostro galaxytool. Voi dovete solo navigare per le pagine di OGame, e il plugin lavorerà in automatico.",
		INDEX_GETTING_STARTED5 : "Dopo che il plugin avrà inserito tutti i dati, potrete vedere quante e quali colonie hanno i vari giocatori, dove sono situate, quali rapporti esistono, e quando sono più attivi.",
		INDEX_GETTING_STARTED6 : "Vi aiuterà anche ad analizzare il vostro andamento se confrontate i vostri risultati con quelli dei vostri avversari, oppure con  l'analisi dei vostri rapporti di combattimento per vedere quanto avete razziato i giorni o le settimane precedenti.",
		INDEX_GETTING_WIKIPAGE : "Galaxytool contiene molti altri strumenti.",
		INDEX_GETTING_WIKIPAGE2 : "Per sapere come usarli visita il nostro wiki.",
		INDEX_GETTING_BOARD : "Per darci dei riscontri o proporci nuove idee puoi usare il nostro forum:",
		INDEX_GETTING_CHAT1 : "O visitare la nostra chatroom:",
		INDEX_GETTING_CHAT2 : "Non saremo online 24 ore su 24, ma per molto del nostro tempo libero. Siate pazienti.",
		INDEX_CLOSE : "Chiudi",
		INDEX_LOGIN : "Accedi",
		GENERAL_REQUIRED_FIELDS : "Per favore, compila tutti i campi",
		INDEX_MESSAGES : "Messaggi",
		INDEX_EXAMPLE : "Esempio",
		INDEX_INVALID_DATA : "Dato non valido",
		GENERAL_COLUMN_HIDE_TITLE : "Gestione Colonne",
		GENERAL_COLUMN_HIDE_INFO : "Per favore, selezione le colonne che vuoi vedere nella tabella",
		GENERAL_ENTRIES_DELETED : "&1 dati cancellati",
		GENERAL_APPLY : "Applica",
		STARTPAGE_GALAXYTOOL_DESCR : "<em>Galaxytool</em> è un tool per OGame.",
		GENERAL_OVERWRITE : "Sovrascrivi dati doppi",
		GENERAL_OVERWRITE_QUESTION : "Sovrascrivi?",
		INDEX_OWN_LOGINS : "Accessi Effettuati",
		GENERAL_OPEN_IN_NEW_WINDOW : "Apri in nuova finestra",
		GENERAL_UNIT_OF_MEASURE_DAYS : "Days",
		PROGRAM_NAME : "OGame Galaxytool",
		SHORTNAME : "Galaxytool",
		BACK_INDEX : "Torna alla pagina principale",
		UNIVERSE : "Universo",
		MENU_INFO_LINKS : "Informazioni",
		MENU_PAGE : "Anteprima",
		MENU_DB_SEARCH : "Cerca nel Database",
		MENU_DB_NOTICES : "Cerca nelle Note",
		MENU_DB_REPORTS : "Cerca nei Rapporti",
		MENU_GALAXYVIEW : "Visione Galassia",
		MENU_STATISTICS : "Statistiche",
		MENU_ALLYHISTORY : "Storia Alleanza",
		MENU_FLEET_MOVEMENTS : "Movimenti Flotta",
		MENU_COMBAT_REPORTS : "Rapporti di combattimento",
		MENU_MESSAGES : "Messaggi gioco",
		MENU_OPTION_LINKS : "Opzioni",
		MENU_DB_REFRESH : "Inserisci nel Database",
		MENU_NOTICES : "Note",
		MENU_DB_STATUS : "Status del database",
		MENU_USEROPTIONS : "Gestione utente",
		MENU_USEROPTIONS2 : "Opzioni utente",
		MENU_USEROPTIONS3 : "Informazioni Utente",
		MENU_ADMIN : "Administration",
		MENU_LOGOUT : "Esci",
		MENU_STUFF : "Varie",
		MENU_FORUM_THREAD : "Forum Developer",
		MENU_DOWNLOADPAGE : "Pagina di Download",
		MENU_LANGUAGE : "Lingua",
		MENU_HELP : "Aiuto",
		MENU_TOOLOPTIONS : "Opzioni Galaxytool",
		PARSER_INFO1 : "E’ stato gia’ inserito nel database",
		PARSER_ERROR1 : "Errore mentre si tentava di inserire le seguenti cordinate.",
		PARSER_ERROR2 : "Impossibile trovare il database!",
		PARSER_ERROR3 : "Impossibile trovare il database server!",
		PARSER_WRONG_UNIVERSE : "Universo sbagliato - presente: \"&1\"  atteso: \"&2\"",
		SHOW_TITLE : "OGame Galaxytool - Pagina di Ricerca",
		SHOW_SEARCH : "Ricerca nel database",
		SHOW_ALLYSYMBOL : "Tag Alleanza",
		SHOW_PLAYERNAME : "Nome Giocatore",
		SHOW_MOONS : "Solo pianeti con Luna",
		SHOW_NOTICES : "Solo pianeti con Note",
		SHOW_COLONIES : "Solo pianeti per colonizzazione",
		SHOW_YES : "Si",
		SHOW_NO : "No",
		SHOW_SEARCHRANGE : "Distanza",
		SHOW_SEARCH_IN : "Cerca nella galassia",
		SHOW_FROM_SYSTEM : "dal sistema",
		SHOW_FROM_PLANET : "dalla posizione del pianeta",
		SHOW_TO : "fino",
		SHOW_DESCRIPTION : "Puoi usare i * per i Giocatori o per le alleanze. Così puoi trovare tutti i Giocatori con &quot;name&quot; nel loro nome.<br/>Compila questo campo solo se lo vuoi specificare.",
		SHOW_SORT_BY : "Creato da",
		SHOW_GALASYSTEM : "Galassia/Sistema",
		SHOW_ALLYNAME : "Nome Alleanza",
		SHOW_SEARCHBUTTON : "Cerca",
		SHOW_ADDRESS : "Indirizzo",
		SHOW_ALLYSORT : "Alleanza",
		SHOW_PLANET : "Nome pianeta",
		SHOW_STATUS : "Status",
		SHOW_CURRENTNESS : "Ultimo Aggiornamento",
		SHOW_PLAYER_STATUS : "Status Giocatore",
		SHOW_PLAYER_STATUS1 : "Tutto",
		SHOW_PLAYER_STATUS2 : "Possibili Obiettivi",
		SHOW_PLAYER_STATUS3 : "Inattivi",
		SHOW_HITS : "Risultati",
		SHOW_OF : "di",
		SHOW_ASC : "Salita",
		SHOW_DESC : "Discesa",
		SHOW_RESULTS : "Risultati per pagina",
		SHOW_MOON : "Luna",
		SHOW_UKMOONSIZE : "Sconosciuto",
		SHOW_DF : "DF",
		SHOW_DF_LONG : "Campo detriti",
		SHOW_METAL : "M",
		SHOW_METAL_LONG : "Metallo",
		SHOW_CRYSTAL : "C",
		SHOW_CRYSTAL_LONG : "Cristallo",
		SHOW_BOTH : "Entrambi",
		SHOW_AT_LEAST : "(Almeno)",
		SHOW_DATE : "Data",
		SHOW_DATE_0 : "lascia perdere",
		SHOW_DATE_1 : "più vecchio di ",
		SHOW_DATE_2 : "più nuovo di",
		SHOW_RANK : "Rank",
		SHOW_FRANK : "Posizione Flotta",
		SHOW_MEMBERS : "Membri",
		SHOW_NOTRANKED : "Non dentro i top 1500.",
		SHOW_NOTICERES : "Note",
		SHOW_REPORTS : "Solo pianeti con Rapporto",
		SHOW_REPORTS_SHORT : "Rapporto",
		SHOW_NOTHING : "Nessuna voce immessa",
		SHOW_ALLIANCE_STATUS : "Status Alleanza",
		SHOW_NO_STATUS : "Nessuno Stato",
		SHOW_NAP : "NAP",
		SHOW_ALLIED : "Alleato",
		SHOW_WAR : "Guerra",
		SHOW_BOYCOTT : "Boicottato",
		SHOW_NEUTRAL : "Neutrale",
		SHOW_OWN : "Propria Alleanza",
		SHOW_WING : "Forte",
		SHOW_EXT_OPTIONS1 : "Visualizza altre opzioni di ricerca per range di sistemi, punteggio, data o campi detriti.",
		SHOW_EXT_OPTIONS2 : "Visualizza altre opzioni di ricerca per colonie, lune, rapporti, note, stato del giocatore o situazione diplomatica.",
		SHOW_EXT_OPTIONS3 : "Visualizza altre opzioni di ricerca per l’ordinamento dei risultati.",
		SHOW_EXTENDED : "Ricerca Avanzata",
		SHOW_MOON_SELECTION : "Pianeti con luna",
		SHOW_REPORT_SELECTION : "Planeti con rapporti di spionaggio",
		SHOW_FILTER_BY : "Escludi dalla lista",
		SHOW_FILTER_NONE : "Nessuna",
		SHOW_PLAYERS_WITHOUT_PROGRESS : "Show players without score changes within the last few days",
		STATUS_TITLE : "OGame Galaxytool - Pagina dello Status",
		STATUS_DB_STATUS : "Status del Database",
		STATUS_COLOR : "Colore",
		STATUS_AGE1 : "Dati non più vecchi di 1 giorno.",
		STATUS_AGE2 : "Dati vecchi 2/4 giorni.",
		STATUS_AGE3 : "Dati vecchi 4/7 giorni.",
		STATUS_AGE4 : "Dati vecchi 1/2 settimane.",
		STATUS_AGE5 : "Dati vecchi 2/4 settimane.",
		STATUS_AGE6 : "Dati più vecchi di un Mese!",
		STATUS_AGE7 : "Dati non disponibili.",
		STATUS_ON : "Attivo",
		STYLES_COLOR1 : "Colore 1",
		STYLES_COLOR2 : "Colore 2",
		STYLES_COLOR3 : "Colore 3",
		STYLES_COLOR4 : "Colore 4",
		STYLES_COLOR5 : "Colore 5",
		STYLES_COLOR6 : "Colore 6",
		STYLES_COLOR7 : "Colore 7",
		STATUS_DB_LEGEND : "Legenda",
		STATUS_GALAXY : "Visuale Galassie",
		USER_TITLE : "OGame Galaxytool - Gestione Utente",
		USER_NAMES : "Utente",
		USER_ERROR : "Errore",
		USER_NEWUSER : "Nuovo Utente",
		USER_OPTIONS : "Opzioni",
		USER_USERNAME : "Username",
		USER_PASSWORD : "Password",
		USER_PASSWORD_CONFIRM : "Conferma password",
		USER_GALAXY : "Galassia",
		USER_SEARCH : "Ricerche",
		USER_INSERT : "Inserisci",
		USER_DELETE : "Cancella",
		USER_DELETE_ENTRY : "Do you want to delete user ",
		USER_STATUS : "Vedi le Statistiche",
		USER_STYLES : "Modifica layout",
		USER_SUBMIT : "Immetti",
		USER_RESET : "Resetta",
		USER_YES : "Si",
		USER_NO : "No",
		USER_STYLEPATH : "Incollato allo styles.css",
		USER_PROBES : "Rapporti di spionaggio",
		USER_EMAIL : "Email",
		USER_ERROR1 : "Password non corretta o Email non valida.",
		USER_ERROR2 : "Email non valida.",
		USER_INGAME : "Nome-In gioco",
		USER_ALLYTAG : "Tag Alleanza",
		USER_ALLYHISTORY : "Storia Alleanza",
		USER_DIPLOMATIC : "diplomatico",
		USER_STATSPAGE : "Numero di righe per la pagina statistiche",
		USER_LINKS : "Collegamenti",
		USER_LINKS2 : "Formato:<br>text;url<br>text2;url2<br>text3;url3",
		USER_EXPORT_TITLE : "Esporta colori (BB Codes)",
		USER_BB_COORDINATES : "Coordinate",
		USER_BB_MOON : "Luna",
		USER_BB_DEBRIS : "Campo detriti",
		USER_BB_ALLY : "Nome alleanza",
		USER_BB_ALLYDETAILS : "Dettagli alleanza",
		USER_BB_PLAYERNAME : "Nome giocatore",
		USER_BB_BANNED : "Bannato",
		USER_BB_VACATION : "Vacanza",
		USER_BB_NOOB : "Debole",
		USER_BB_INACTIVE : "Inattivo",
		USER_BB_LONGINACTIVE : "Inattivo da molto tempo",
		USER_DELETION : "Cancella",
		USER_FLEETINFO : "Movimenti Flotta",
		USER_ACTIVITIES : "Attività Giocatore",
		USER_MAINTENANCE : "Manutenzione Galaxytool",
		USER_MANAGEMENT : "Gestione utente",
		USER_DELETE_MY_COMBAT_REPORTS : "Cancella i miei rapporti di combattimento",
		USER_DELETE_MY_MESSAGES : "Cancella i miei messaggi",
		USER_DELETE_MY_FLEETMOVES : "Cancella i miei movimenti flotte",
		USER_DELETE_MY_COMBAT_REPORTS_LIMITED : "Cancella i miei rapporti di combattimento più vecchi di &1 giorni",
		USER_DELETE_MY_MESSAGES_LIMITED : "Cancella i miei messaggi più vecchi di &1 giorni",
		USER_TABLE_ENTRIES : "Numero di elementi per pagina",
		USER_EXISTS : "Utente già esistente",
		USER_BB_OUTLAW : "Bandito",
		USER_INVALID_URL : "L'indirizzo &1 sembra non essere valido - sarà ignorato",
		VIEW_TITLE : "OGame Galaxytool - Dettagli",
		VIEW_NODATA : "Nessun dato disponibile.",
		VIEW_GALAXY : "Galassia",
		VIEW_SYSTEM : "Sistema solare",
		VIEW_POSITION : "Posizione",
		VIEW_PLANET : "Pianeta",
		VIEW_MOON : "Luna",
		VIEW_TF : "DF",
		VIEW_PLAYER : "Giocatore",
		VIEW_PLAYER_ADD : "(Rank / Status)",
		VIEW_ALLY : "Alleanza",
		VIEW_ALLY_ADD : "(Rank / Membro)",
		VIEW_METAL : "M",
		VIEW_CRYSTAL : "C",
		VIEW_COLONISED : "Pianeta/i Abitato/i",
		VIEW_UKMOONSIZE : "Sconosciuto",
		VIEW_BACK : "Indietro",
		VIEW_NOTICE : "Note",
		VIEW_REPORTS : "Rapporti",
		VIEW_MOONPHALANX : "La seguente Luna può scansionare questo Sistema Solare",
		VIEW_NOMOONS : "Nessuna Luna trovata",
		VIEW_IRAKS : "Il seguente pianeta può con i Missili Interplanetari arrivare a questo Sistema Solare",
		VIEW_NOIRAKS : "Nessun Missile Interplanetario trovato",
		VIEW_MOON_DESTROY_CHANCE : "Possibilita’ di distruggere la luna",
		VIEW_CHANCE_WITH_ONE : "Possibilita’ con una Morte Nera",
		VIEW_CHANCE_WITH_N : "Possibilita’ con ",
		VIEW_DEATH_STARS : "Morti Nere",
		VIEW_DS_DESTROY_CHANCE : "Possibilita’ di perdere la/le Morte/i Nera/e",
		VIEW_TOP : "Top",
		VIEW_GO : "go",
		VIEW_DIAMETER : "Diametro",
		PW_TITLE : "OGame Galaxytool - Cambia Password",
		OLD_PASSWORD : "Vecchia password",
		NEW_PASSWORD : "Nuova password",
		CONFIRM_NEW_PASSWORD : "Conferma nuova password",
		PW_MISMATCH : "Password non collegata",
		PW_ERROR : "La vecchia passord non era corretta",
		UPDATE_DONE : "Update avvenuto con successo.",
		TIMEZONE_OFFSET : "Imposta Timezone in base al server",
		DELETE_ACCOUNT : "Cancella questo account Galaxytool",
		DELETE_ACCOUNT_SAFETY_REQUEST : "Vuoi davvero cancellare questo account Galaxytool?",
		CH_PASSWD_AUTHORIZATION : "Autorizzazioni",
		CH_PASSWD_ADMIN : "Amministratore",
		TIMEZONE_OGAME_OFFSET : "Imposta timezone in base al server OGame",
		CH_PASSWD_USER_LANGUAGE : "Imposta questa lingua all'accesso",
		CH_PASSWD_USER_LANGUAGE_NO_CHANGE : "Non cambiare",
		CH_PASSWD_EXPAND : "Espanso",
		CH_PASSWD_COLLAPSE : "Ridotto",
		CH_PASSWD_HIDDEN : "Nascosto",
		CH_PASSWD_GETTING_STARTED : "Mostra introduzione a galaxytool all'accesso",
		CH_PASSWD_PLUGIN : "Mostra informazioni plugin all'accesso",
		NOTICE_TITLE : "OGame Galaxytool - Note",
		NOTICE_HEADER : "Modifica Note",
		NOTICE_HEADER2 : "Modifica le proprie note",
		NOTICE_PUBLIC : "Accessibile per gli altri?",
		NOTICE_YES : "si",
		NOTICE_NO : "no",
		NOTICE_TEXT : "Testo nota",
		NOTICE_SAVE : "Salva",
		NOTICE_DELETED : "Campo eliminato",
		NOTICE_SAVED : "Campo salvato.",
		NOTICE_RESULTS : "Tutti i risultati",
		NOTICE_USER : "Utente",
		NOTICE_DATE : "Data",
		NOTICE_EDIT : "Modifica",
		NOTICE_DELETE : "Cancella",
		NOTICE_NEW : "Crea una propria immissione",
		NOTICE_NOTPUBLIC : "Note non pubbliche.",
		NOTICE_ALL : "Tutte",
		NOTICE_NONE : "Nessuna",
		NOTICE_SEARCH : "Cerca nella note",
		NOTICE_SEARCH_SHORT : "Cerca",
		NOTICE_HITS : "Risultati",
		NOTICE_SHOWRESULTS : "Risultati per pagina",
		NOTICE_OF : "di",
		NOTICE_NOTHING : "Nessuna immissione trovata",
		NOTICE_CHARS : "Caratteristiche",
		NOTICE_PLAYERNAME : "Giocatore",
		NOTICE_SHOWALL : "Visualizza tutte le note",
		REPORTS_TITLE : "OGame Galaxytool - Rapporti di Spionaggio",
		REPORTS_RESOURCES : "Risorse",
		REPORTS_FLEET : "Flotta",
		REPORTS_DEFENCE : "Difese",
		REPORTS_BUILDINGS : "Strutture",
		REPORTS_TECHNOLOGY : "Ricerche",
		REPORTS_MOON : "Luna",
		REPORTS_SEARCH : "Cerca nei Rapporti di spionaggio",
		REPORTS_SEARCH_SHORT : "Cerca",
		REPORTS_HITS : "Risultati",
		REPORTS_NOTHING : "Nessuna immissione trovata",
		REPORTS_ADDRESS : "Indirizzo",
		REPORTS_CURRENTNESS : "Currentness",
		REPORTS_PLAYERNAME : "Nome Giocatore",
		REPORTS_ALLY : "Alleanza",
		REPORTS_VIEW : "Mostra Rapporto",
		REPORTS_SEARCH_IN : "Cerca nella Galassia",
		REPORTS_FROM_SYSTEM : "dal sistema",
		REPORTS_TO : "a",
		REPORTS_DELETE : "Cancella",
		REPORTS_DELETED : "Immissione cancellata",
		REPORTS_RESULTS : "Risultati per pagina",
		REPORTS_OF : "di",
		REPORTS_DATE : "Data",
		REPORTS_DATE_0 : "lascia stare",
		REPORTS_DATE_1 : "più vecchio di",
		REPORTS_DATE_2 : "più nuovo di",
		REPORTS_NOTICES : "Avvisi",
		REPORTS_AT_LEAST_RESOURCES : "Risorse (almeno)",
		REPORTS_SEARCH_EXTENDED : "Ricerca Estesa",
		REPORTS_FLEET_RESIS : "Flotta- Punteggio",
		REPORTS_DEFENCE_RESIS : "Difesa- Punteggio",
		REPORTS_ALL_RESIS : "Somma Punteggi",
		REPORTS_TECHS : "Tecnologie",
		REPORTS_UNKNOWN_ENTRIES : "Immissioni sconosciute",
		REPORTS_PARTLY_INSERTED : "Parzialmente Inserito",
		REPORTS_FOR_ALL_RES : "per tutte le risorse",
		REPORTS_FOR_TF : "per il campo detriti",
		REPORTS_KT : "Carghi Leggeri",
		REPORTS_GT : "Carghi Pesanti",
		REPORTS_SS : "Navi da Guerra",
		REPORTS_REC : "Reciclatrici",
		REPORTS_RAIDABLE : "Solo obbiettivi per RAID",
		REPORTS_ALL_RESOURCES : "tutte le risorse",
		REPORTS_STUFF : "Varie",
		REPORTS_SPEEDSIM : "Simula con SpeedSim",
		REPORTS_DRAGOSIM : "Simula con Dragosim",
		REPORTS_STATUS : "Stato",
		REPORTS_ERROR : "Si e’ verificato un’errore",
		REPORTS_OWN_REPORTS : "Solo i miei Report",
		REPORTS_UPLOAD_BY : "Report inviati da",
		REPORTS_DEPTH : "Accuratezza Report",
		REPORTS_FLEET_SCORE : "Punti Flotte",
		REPORTS_DEFENCE_SCORE : "Punti Difese",
		REPORTS_HOURS : "Ore",
		REPORTS_MAX_RESULTS_HIT : "La tua ricerca mostra più di &1 risultati. Solo i primi &1 risultati saranno mostrati. Per favore, correggi le impostazioni di ricerca al fine di ridurre il numero di risultati ottenibili.",
		REPORTS_OSIMULATE : "Simula con OSimulate",
		REPORTS_SHOW_ONLY : "Visualizza",
		REPORTS_SHOW_PLANETS : "Pianeti",
		REPORTS_SHOW_MOONS : "Lune",
		REPORTS_OWNER : "Proprietario",
		STATS_TITLE : "OGame Galaxytool - Statistiche",
		STATS_TBLHEAD : "Statistiche",
		STATS_RANK : "Rank",
		STATS_PLAYERNAME : "Nome Giocatore",
		STATS_ALLYNAME : "Tag Alleanza",
		STATS_SCORE : "Punteggio",
		STATS_FLEET : "Flotta",
		STATS_RESEARCH : "Ricerca",
		STATS_MEMBERS : "Membri",
		STATS_STATUS : "Status",
		STATS_NOTHING : "Nessuno Status",
		STATS_NAP : "NAP",
		STATS_ALLIED : "Alleato",
		STATS_WAR : "Guerra",
		STATS_BOYCOTT : "Boicottato",
		STATS_NEUTRAL : "Neutrale",
		STATS_OWN : "Propria Alleanza",
		STATS_WING : "Forte",
		STATS_UPDATE : "Immesso da",
		STATS_PLAYERSTATS : "Stats Giocatore",
		STATS_ALLYSTATS : "Stats Alleanza",
		STATS_DELETE : "Vuoi cancellare questo inserimento?",
		STATS_CONFIRM_DELETE : "Vuoi davvero cancellare questo giocatore?",
		STATS_CHANGE_PLAYER_STATUS : "Stato del giocatore",
		STATS_CHANGE_ALLIANCE_STATUS : "Stato dell’alleanza",
		STATS_CHANGE_ALLIANCE_STATUS_HINT : "Tutti i membri dell'alleanza otterranno lo status selezionato. Qualsiasi status preesistente verrà sovrascritto. Sarà possibile in seguito modificare lo status dei giocatori.",
		STATS_UNKNOWN : "Rest",
		STATS_DETAILS : "Dettagli per",
		STATS_PLAYERSTATUS : "Status Giocatore",
		STATS_IGNORE_STATUS : "Tutto",
		STATS_ACTIVE : "attivo",
		STATS_INACTIVE : "Inattivo",
		STATS_BANNED : "Bannato",
		STATS_VACATION : "Vacanza",
		STATS_NOOB : "Debole",
		STATS_YES : "Si",
		STATS_NO : "Solo pianeti con Note",
		STATS_SEARCH : "Ricerche",
		STATS_SHOW_GRAPH : "Mostra dettagli per categoria di punteggio",
		STATS_LONG_INACTIVE : "Inattivo da molto tempo",
		STATS_STANDARD : "Punteggio",
		STATS_MILITARY : "Punti Esercito",
		STATS_ECONOMY : "Economia",
		STATS_HONOUR : "Punti Onore",
		STATS_MILITARY_BUILD : "Punti Esercito Costruiti",
		STATS_MILITARY_DESTROYED : "Punti Esercito Distrutti",
		STATS_MILITARY_LOST : "Punti Esercito Persi",
		REGISTER_REGISTRATE : "Registra",
		REGISTER_LOGINNAME : "Nome-Login",
		REGISTER_PASSWORD : "Password",
		REGISTER_PASSWORD_CONFIRM : "Conferma Password",
		REGISTER_EMAIL : "Email",
		REGISTER_INGAME : "Nome-In Gioco",
		REGISTER_ALLYTAG : "Tag Alleanza",
		REGISTER_EMAILVERIFICATION : "Controlla Email",
		REGISTER_EMAILTEXT : "Visita il seguente link per confermare la tua registrazione a Galaxytool.",
		REGISTER_ERROR1 : "Login-Username gia’ usato.",
		REGISTER_ERROR2 : "Errore mentre si tentava di inviare la mail. Contattare il tuo admin.",
		REGISTER_ERROR3 : "Errore mentre si tentava di inviare dati al database",
		REGISTER_INFO1 : "Il tuo account è stato creato.",
		REGISTER_INFO2 : "Per favore, clicca sul link nella tua email per confermare la registrazione.",
		REGISTER_INFO3 : "Account confermato. Il tuo admin deve attivare la registrazione.",
		REGISTER_BUTTON : "Torna alla main page",
		REGISTER_NEW_SUBJECT : "Nuovo Utente registrato a Galaxytool",
		REGISTER_NEW_MAILTEXT : "Nuovo Utente si e’ Registrato.",
		REGISTER_BACK : "Torna indietro alla prima pagina",
		REGISTER_MISSING_FIELDS : "Compila tutti i campi necessari!",
		REGISTER_ERROR4 : "Indirizzo email non valido",
		REGISTER_ERROR5 : "Password errata",
		REGISTER_PWS : "Efficacia password",
		REGISTER_PWS0 : "molto bassa",
		REGISTER_PWS1 : "bassa",
		REGISTER_PWS2 : "buona",
		REGISTER_PWS3 : "alta",
		REGISTER_PWS4 : "molto alta",
		REGISTER_EMAIL_USED : "Questo indirizzo email è già in uso",
		LOSTPW_TITLE : "Ho perso la mia Password",
		LOSTPW_INFO2 : "Una nuova password e’ stata generata e inviata al tuo indirizzo Email.",
		LOSTPW_BUTTON1 : "Prendi la nuova password",
		LOSTPW_BUTTON2 : "Torna alla Pagina Principale",
		LOSTPW_LOGINNAME : "Nome-Login",
		LOSTPW_EMAIL : "Email",
		LOSTPW_ERROR1 : "Errore mentre tentava di inviare dati al database",
		LOSTPW_ERROR2 : "Nessuna immissione corrispondente trovata!",
		LOSTPW_ERROR3 : "Errore mentra tantava di inviare l’email. Contatta il tuo admin.",
		LOSTPW_EMAIL_SUBJECT : "La nuova password che hai richiesto",
		LOSTPW_EMAIL_TEXT1 : "Qui il tuo nuovo login per Galaxytool",
		LOSTPW_EMAIL_TEXT2 : "Username",
		LOSTPW_EMAIL_TEXT3 : "Password",
		LOSTPW_INFO1 : "A breve riceverai un'email con un link di verifica della tua richiesta",
		LOSTPW_CONFIRM_RESET_SUBJECT : "Password smarrita?",
		LOSTPW_CONFIRM_RESET_MESSAGE : "Ciao,\n\nqui puoi resettare la password del Galaxytool. Per generare una nuova password, clicca sul seguente link:",
		USERINFO_TITLE : "OGame Galaxytool - Informazioni Utente",
		USERINFO_NAMES : "Tutti gli utenti di questo tool",
		USERINFO_DETAIL : "Informazioni dettagliate di",
		USERINFO_ERROR1 : "Nessun utente conosciuto con questo ID!",
		USERINFO_USERNAME : "Nome Login",
		USERINFO_INGAME : "Nome in Gioco",
		USERINFO_EMAIL : "Email",
		USERINFO_ALLYTAG : "Alleanza",
		USERINFO_STYLEPATH : "Skin",
		USERINFO_STATUS : "Status",
		USERINFO_ACTIVATE : "Attiva Account",
		USERINFO_LOGINS : "Numero di Login",
		USERINFO_LASTLOGIN : "Ultimo Login",
		USERINFO_DATA : "Informazioni sul sistema immesso",
		USERINFO_NODATA : "Questo utente non ha ancora inserito nessun Sistema!",
		USERINFO_GALAXY : "Galassia",
		USERINFO_SYSTEMS : "Numero di Sistemi",
		USERINFO_IP : "Indirizzo IP",
		USERINFO_LOGINTIME : "Login",
		USERINFO_NOLOGIN : "Il giocatore non ha mai loggato da solo.",
		USERINFO_LAST_GALAXYUPDATE : "Inserita l’ultima Visuale della Galassia",
		USERINFO_LAST_PUBLIC_NOTICE : "L’ultima Nota Pubblica",
		USERINFO_LAST_PRIVATE_NOTICE : "L’ultima Nota Privata",
		USERINFO_NUMBEROF_PUBLIC_NOTICE : "Numero di Note Pubbliche",
		USERINFO_NUMBEROF_PRIVATE_NOTICE : "Numero di Note Private",
		USERINFO_ACTIVATED : "Account attivato",
		USERINFO_ACTIVATIONTEXT : "L'Admin di GalaxyTool ha attivato il tuo account.\n\nBuon divertimento con GalaxyTool!",
		USERINFO_LAST_SUBMIT : "Ultimo inserimento",
		ALLYHISTORY_TITLE : "OGame Galaxietool - Visione Storica dell’Alleanza",
		ALLYHISTORY_TBLHEAD : "Visione Storica",
		ALLYHISTORY_PLAYERNAME : "Nome Giocatore",
		ALLYHISTORY_ALLYNAME : "Alleanza",
		ALLYHISTORY_LASTMONTH : "Ultimo mese",
		ALLYHISTORY_ALL_DATA : "tutte le informazioni disponibili",
		ALLYHISTORY_SHOW : "visualizza statistica",
		ALLYHISTORY_TIMESPAN : "Timespan",
		ALLYHISTORY_PROGESS : "Progresso",
		ALLYHISTORY_SCORE : "Punteggi",
		ALLYHISTORY_FSCORE : "Punteggio Flotta",
		ALLYHISTORY_RSCORE : "Punteggio Ricerca",
		ALLYHISTORY_MEMBER : "Membri",
		ALLYHISTORY_NOTHING : "nessuna immissione trovata",
		ALLYHISTORY_DETAILS : "Dettagli",
		ALLYHISTORY_SHOW_ADDRESS : "Coordinate",
		ALLYHISTORY_ESCORE : "Economia",
		ALLYHISTORY_MSCORE : "Punti Esercito",
		DETAILEDINFO_PLAYERINFO_TITLE : "Informazioni giocatore",
		DETAILEDINFO_ALLYINFO_TITLE : "Informazioni alleanza",
		DETAILEDINFO_PLAYERINFO_TBLHEAD : "Informazioni dettagliate del giocatore",
		DETAILEDINFO_ALLYINFO_TBLHEAD : "Informazioni dettagliate dell’alleanza",
		DETAILEDINFO_NO_ALLIANCE : "nessuna",
		DETAILEDINFO_SCORE : "Statistiche punteggio",
		DETAILEDINFO_FLEET : "Statistiche flotta",
		DETAILEDINFO_RESEARCH : "Statistiche ricerca",
		DETAILEDINFO_RANK : "Posizione",
		DETAILEDINFO_POINTS : "Punteggio",
		DETAILEDINFO_KNOWN_PLANETS : "Colonie conosciute",
		DETAILEDINFO_MOONS : "Lune conosciute",
		DETAILEDINFO_PHALANX_AREA : "Area della falange",
		DETAILEDINFO_NO_PHALANX_AREA : "Nessuna falange trovata",
		DETAILEDINFO_NOTICES : "Note",
		DETAILEDINFO_NO_NOTICES : "Nessuna nota trovata",
		DETAILEDINFO_PREVIOUS_ALLIANCES : "Alleanza precedente",
		DETAILEDINFO_RESOURCES_PER_HOUR : "Risorse prodotte in un ora",
		DETAILEDINFO_RESOURCES_PER_DAY : "Risorse prodotte in 24h",
		DETAILEDINFO_RESOURCES_PER_WEEK : "Risorse prodotte in 7 giorni",
		DETAILEDINFO_RESOURCES_PER_MONTH : "Risorse prodotte in un mese (30 giorni)",
		DETAILEDINFO_METAL : "Metallo",
		DETAILEDINFO_CRYSTAL : "Cristallo",
		DETAILEDINFO_DEUTERIUM : "Deuterio",
		DETAILEDINFO_UNKNOWN : "sconosciuto",
		DETAILEDINFO_SCORE_DISTRIBUTION : "Distribuzione del punteggio",
		DETAILEDINFO_GENERAL : "Dettagli",
		DETAILEDINFO_MEMBERS : "Membri",
		DETAILEDINFO_GRAPHS : "Grafici",
		DETAILEDINFO_RESOURCES : "Risorse",
		DETAILEDINFO_FLEET_TAB : "Flotta",
		DETAILEDINFO_TECH : "Ricerche",
		DETAILEDINFO_FLEET_DETAIL : "Somma / (Media Giocatori) fra tutti i Report disponibili",
		DETAILEDINFO_TECH_DETAIL : "Media di tutte le informazioni giocatore disponibili",
		DETAILEDINFO_PLANET_TAB : "Pianeti",
		DETAILEDINFO_MOON_TAB : "Lune",
		DETAILEDINFO_ACTIVITIES : "Attività",
		DETAILEDINFO_NODATA : "Nessun dato disponibile.",
		DETAILEDINFO_ACTIVITY_DESCRIPTION : "Mostra attività di &1 raccolta da:",
		DETAILEDINFO_GALAXYVIEWS : "Visione Galassia",
		DETAILEDINFO_SCANS : "Azioni di spionaggio",
		DETAILEDINFO_MESSAGES : "Messaggi giocatore",
		DETAILEDINFO_COMBATS : "Rapporti di combattimento",
		DETAILEDINFO_ALLYPAGE : "Visione Allenaza",
		DETAILEDINFO_MANUAL : "Inserimenti manuali",
		DETAILEDINFO_START : "Inizio",
		DETAILEDINFO_TO : "ad",
		DETAILEDINFO_TODAY : "Oggi",
		DETAILEDINFO_DATA_RESTRICTION : "ristretto da:",
		DETAILEDINFO_WEEKDAY_WEEKEND : "Weekend",
		DETAILEDINFO_WEEKDAY_WORKINGDAY : "Feriale",
		DETAILEDINFO_WEEKDAY_MONDAY : "Lunedì",
		DETAILEDINFO_WEEKDAY_TUESDAY : "Martedì",
		DETAILEDINFO_WEEKDAY_WEDNESDAY : "Mercoledì",
		DETAILEDINFO_WEEKDAY_THURSDAY : "Giovedì",
		DETAILEDINFO_WEEKDAY_FRIDAY : "Venerdì",
		DETAILEDINFO_WEEKDAY_SATURDAY : "Sabato",
		DETAILEDINFO_WEEKDAY_SUNDAY : "Domenica",
		DETAILEDINFO_WEEKDAY_SHORTLENGTH : 3,
		DETAILEDINFO_PLAYER_CURRENTLY_ACTIVE : "Il giocatore è al momento attivo",
		DETAILEDINFO_PLAYER_MESSAGES : "messaggi giocatore disponibili",
		DETAILEDINFO_SHOW : "mostra",
		DETAILEDINFO_NONE : "non disponibile",
		DETAILEDINFO_ENTER_MANUALLY : "Immetti attività per questo giocatore",
		DETAILEDINFO_PLAYER_SEEN_ON : "Il player era online alle",
		DETAILEDINFO_INSERT : "Inserire",
		DETAILEDINFO_OGAME_SERVERTIMES : "Attenzione: tutte le date e gli orari fanno riferimento all'ora del server di OGame !",
		DETAILEDINFO_DAY_VIEW : "Visuale 24 ore",
		DETAILEDINFO_WEEK_VIEW : "Visuale Settimana",
		DETAILEDINFO_HOME_PLANET : "Pianeta Madre",
		DETAILEDINFO_PLANETNAME : "Nome",
		DETAILEDINFO_DEFENCE_SCORE : "Punteggio difesa",
		DETAILEDINFO_DEFENCE_SCORE_TOOLTIP : "Punteggio difesa = Flotta - Punteggio + Ricerca + Economia.<br/>Tutte queste classifiche devono essere sempre aggiornate per averre un risultato attendibile!",
		DETAILEDINFO_SCORE_PER_SHIP : "Punteggio per nave",
		DETAILEDINFO_SHIPS : "Numero di navi",
		DETAILEDINFO_DATE_IN_FUTURE : "Non inserire date o orari che non siano nel passato. Non verranno memorizzati.",
		ADMIN_TITLE : "Gestione Galaxytool",
		ADMIN_DISCLAMER : "Attenzione: L'esecuzione della maggior parte di questi script comporta la cancellazione di dati",
		ADMIN_INCONSISTENCIES : "Incongruenze nel database",
		ADMIN_PLANETS : "Pianeti in pos 0 o maggiore di 15",
		ADMIN_GALAXIES : "Cancella galassie maggiori di &1 ",
		ADMIN_PLAYERS : "Cancella giocatori senza playerid OGame - Elimina i dati duplicati dei player ",
		ADMIN_REPORTS : "Cancella i report se un pianeta non esiste più",
		ADMIN_MISC : "Varie",
		ADMIN_RESET : "Reset Galaxytool (utenti e tabella ip non vengono cancellati)",
		ADMIN_OLD_PLAYERS : "Cancella i dati più vecchi di &1 giorni",
		ADMIN_OLD_REPORTS : "Cancella report più vecchi di &1 giorni",
		ADMIN_LOADING : "Non chiudere questa finestra durante il caricamento della pagina.",
		ADMIN_STATUS : "Status della richiesta",
		ADMIN_SELECTION : "Selezionare almeno una voce",
		ADMIN_SAFETY : "Sei sicuro di voler eseguire questi script ?",
		ADMIN_DONE : "Eseguito",
		ADMIN_NOTBD : "Niente da eseguire",
		ADMIN_OLD_GALAXIES : "Rimuovi visioni galassia più vecchie di &1 giorni",
		ADMIN_UNUSED_PLAYERS : "Rimuovi players che non compaiono nella visione galassia",
		ADMIN_OLD_ACTIVITIES : "Rimuovi le attività giocatore più vecchie di &1 giorni",
		ADMIN_OLD_COMBATS : "Elimina i rapporti di combattimento più vecchi di &1 giorni",
		ADMIN_OLD_INGAME_MSG : "Elimina i messaggi più vecchi di &1 giorni",
		ADMIN_OGAME_API : "Carica nel galaxytool i dati pubblici di OGame",
		ADMIN_OGAME_ALL_DATA : "tutte le informazioni disponibili",
		ADMIN_OGAME_GALAXY_DATA : "Visione Galassia",
		ADMIN_OGAME_STATISTICS_DATA : "Statistiche",
		ERRORPAGE_PAGEFORWARD : "Clicca qui se il tuo browser non supporta il reindirizzamento",
		ERRORPAGE_PERMISSION_DENIED : "Non hai il permesso di accedere a questa pagina. Clicca qui per tornare indietro.",
		FLEETS_TITLE : "OGame Galaxytool - Movimenti flotta",
		FLEETS_ACTUAL_FLEETS : "Movimenti di flotta correnti",
		FLEETS_YES : "Si",
		FLEETS_NO : "Solo pianeti con Note",
		FLEETS_DETAILS : "Dettagli",
		FLEETS_MISSION_EXPEDITION : "Spedizione",
		FLEETS_MISSION_COLONIZATION : "Colonizzazione",
		FLEETS_MISSION_RECYCLE : "Raccolta",
		FLEETS_MISSION_TRANSPORT : "Trasporto",
		FLEETS_MISSION_DEPLOYMENT : "Schieramento",
		FLEETS_MISSION_ESPIONAGE : "Spionaggio",
		FLEETS_MISSION_ACS_DEFEND : "ACS stazionamento",
		FLEETS_MISSION_ATTACK : "Attacco",
		FLEETS_MISSION_ACS_ATTACK : "ACS Attacco",
		FLEETS_MISSION_MOON_DESTRUCTION : "Distruzione Luna",
		FLEETS_MISSION_MISSILE_ATTACK : "Attacco missilistico",
		FLEETS_NO_DATA : "Nessun dato trovato",
		FLEETS_FLEET : "Flotta",
		FLEETS_ALL_FLEETS : "Visualizza tutti i movimenti flotta",
		COMBAT_REPORT_OUDATED_GALAXYVIEW : "I tuoi dati galassia sono vecchi. Aggiorna le coordinate del target!",
		MESSAGES_TITLE : "OGame Galaxytool - OGame Messaggi",
		MESSAGES_PLAYERNAME : "Nome",
		MESSAGES_SUBJECT : "Oggetto",
		MESSAGES_DATE : "Data",
		MESSAGES_FILTER : "Filtro",
		MESSAGES_DELETE : "Cancella messaggio",
		MESSAGES_PUBLISH_DETAIL : "Pubblica il messaggio aggiungendone il testo per evidenziare il testo del giocatore.",
		MESSAGES_PUBLISH_HEADER : "&mittente inviato un messaggio a &destinatario il &giorno:\n\n &messaggio",
		MESSAGES_PLAYER_FILTER : "Messaggi al giocatore:",
		MESSAGES_CONTENT : "Contenuto",
		COMBATS_TITLE : "OGame Galaxytool - Rapporti di combattimento",
		COMBATS_ATTACKER : "Attaccante",
		COMBATS_DEFENDER : "Difensore",
		COMBATS_DATE : "Data",
		COMBATS_OWNER : "Proprietario",
		COMBATS_WINNER : "Vincitore",
		COMBATS_COMBATREPORT : "Rapporto di combattimento",
		COMBATS_COMBAT_AT : "Combattimento a",
		COMBATS_LOST_UNITS : "Unità perse",
		COMBATS_LOOT : "Bottino",
		COMBATS_DEBRIS : "Detriti",
		COMBATS_AND : "e",
		COMBATS_PUBLISH : "Rendi pubblico questo report",
		COMBATS_UNPUBLISH : "Ritira questo rapporto (lo rende di nuovo privato)",
		COMBATS_DELETE : "Cancella report",
		COMBATS_CHECK_ALL : "Seleziona tutti",
		COMBATS_UNCHECK_ALL : "Deseleziona All",
		COMBATS_WITH_SELECTED : "Selezionati",
		COMBATS_PUBLIC_REPORTS : "Report pubblici",
		COMBATS_YES : "Si",
		COMBATS_NO : "Solo pianeti con Note",
		COMBATS_SEARCH_OPTIONS : "Opzioni ricerca",
		COMBATS_SEARCH : "Vai",
		COMBATS_RESET : "Reset",
		COMBATS_COORDINATES : "Coordinate",
		COMBATS_INVALID_GALAXY_ENTERED : "Dati galassia non validi",
		COMBATS_INVALID_SYSTEM_ENTERED : "Dati sistema non validi",
		COMBATS_INVALID_PLANET_ENTERED : "Dati pianeta non validi",
		COMBATS_GALAXY_FROM_TO : "Galassia",
		COMBATS_SYSTEM_FROM_TO : "Systema",
		COMBATS_PLANET_FROM_TO : "Pianeta",
		COMBATS_APPLY : "Applica",
		COMBATS_COMBAT_SUMMARY : "Riassunto del combattimento",
		COMBATS_DOWNLOAD_CSV : "Scarica file CSV",
		REPORT_ARCHIVE_TITLE : "Archivio Rapporti",
		REPORT_ARCHIVE_COORDINATES : "Coordinate",
		REPORT_ARCHIVE_SCANTIME : "Orario analisi",
		REPORT_ARCHIVE_DELETE : "Cancella questi inserimenti",
		REPORT_ARCHIVE_CONFIRM_DELETE : "Sei sicuro di voler cancellare questi inserimenti?",
		REPORT_ARCHIVE_GALAXY : "Galassia",
		REPORT_ARCHIVE_SYSTEM : "Sistema Solare",
		REPORT_ARCHIVE_PLANET : "Pianeta",
		REPORT_ARCHIVE_MOON : "Luna",
		REPORT_ARCHIVE_DETAILS : "Dettagli",
		REPORT_ARCHIVE_RESOURCES : "Risorse prodotte in un ora",
		REPORT_ARCHIVE_HEADER_RESOURCES : "Risorse",
		REPORT_ARCHIVE_DETAILS_FOR : "Archivio rapporti per &1 [&2] (&3)",
		REPORT_ARCHIVE_FLEET_CARGO : "Capienza navi cargo",
		REPORT_ARCHIVE_IRAK_RANGE : "Portata missili interplanetari",
		REPORT_ARCHIVE_CHART_TYPE : "Tipologia di grafico",
		INSTALL_TITLE : "Installazione Galaxytool versione",
		INSTALL_PROGRESS : "Stato installazione",
		INSTALL_STEP : "Passo",
		INSTALL_CONTINUE : "Continua",
		INSTALL_VALIDATE : "Convalida",
		INSTALL_STEP1 : "Benvenuto",
		INSTALL_STEP2 : "Permessi di scrittura",
		INSTALL_STEP3 : "Impostazioni Database",
		INSTALL_STEP4 : "Impostazioni OGame",
		INSTALL_STEP5 : "Impostazioni Galaxytool",
		INSTALL_STEP6 : "Password Admin",
		INSTALL_STEP7 : "Installa Galaxytool",
		INSTALL_STEP8 : "Concludi installazione",
		INSTALL_FILE_DELETE_CHECK : "Per favore, cancella install.php e update.php da tuo server web",
		INSTALL_STEP1_PHP_FAILED : "La versione &1 di php non è compatibile con questa versione di Galaxytool",
		INSTALL_STEP1_FOPEN_FAILED : "La versione di php in uso non consentel'apertura delle pagine web con il comando FOPEN(), indispensabile per poter usufruire di OGame API.",
		INSTALL_STEP1_WELCOME : "Benvenuto all'installazione guidata di Galaxytool. Sarai affiancato e aiutato ad installare Galaxytool.",
		INSTALL_STEP2_DESCRIPTION : "Assicurati di essere abilitato alla modifica dei file config.php and attributes.php",
		INSTALL_STEP2_DESCRIPTION2 : "Se non sai come fare, dai un'occhiata qui: &1",
		INSTALL_STEP2_FILE_NOT_WRITEABLE : "Il file è impostato come sola lettura",
		INSTALL_STEP3_SERVER : "Server del Database",
		INSTALL_STEP3_USERNAME : "Username",
		INSTALL_STEP3_PASSWORD : "Password",
		INSTALL_STEP3_DBNAME : "Nome del Database",
		INSTALL_STEP3_PREFIX : "Prefisso delle Tabelle",
		INSTALL_STEP3_ENTER_PREFIX : "Es. miotool_",
		INSTALL_STEP3_ENTER_SERVER : "Inserisci l'indirizzo del server del database. Se necessario contatta l'amministratore di sistema. Di solito l'impostazione corretta è localhost",
		INSTALL_STEP3_ENTER_USERNAME : "Inserisci il nome utente del database",
		INSTALL_STEP3_ENTER_PASSWORD : "Inserisci la password per l'accesso al database",
		INSTALL_STEP3_ENTER_DBNAME : "Inserisci il nome del database che sarà usato per l'installazione (deve esistere)",
		INSTALL_STEP3_CONNECT_FAILED : "Impossibile stabilire una connessione col server del database",
		INSTALL_STEP3_DB_FAILED : "Database &1 non trovato",
		INSTALL_STEP3_MYSQL_VERSION_FAILED : "La versione &1 di MySQL non è compatibile con questa versione di Galaxytool",
		INSTALL_STEP4_URL : "Indirizzo di OGame",
		OGAME_URL_DETAILS : "Per favore, dopo aver effettuato l'accesso a OGame, inserisci qui l'indirizzo che vedi nella barra. Quell'indirizzo servirà al galaxytool per ricavare l'indirizzo dell'API di OGame la quale serve a inserire alcuni dati nel Galaxytool senza avere bisogno della GalaxyToolbar. Questa API è stata introdotta dalla versione 4.1.0 di OGame",
		INSTALL_STEP4_UNIVERSE : "Universo OGame",
		INSTALL_STEP4_DEF_TO_DEBRIS : "Difese nei detriti",
		INSTALL_STEP4_DEBRIS_RATE : "Percentuale di detriti",
		INSTALL_STEP4_SPEED_RATE : "Velocità",
		INSTALL_STEP4_ENTER_UNIVERSE : "Inserisci il nome o il numero dell'universo OGame nel quale giochi (case sensitive).",
		INSTALL_STEP4_UNIVERSE_MISSING : "Devi definire l'universo in cui giochi",
		INSTALL_STEP4_ENTER_URL : "Inserisci l'indirizzo dell'universo OGame nel quale giochi",
		INSTALL_STEP4_URL_MISSING : "Devi definire l'indirizzo dell'universo in cui giochi",
		INSTALL_STEP4_URL_CHECK_FAILED : "Impossibile trovare l'indirizzo dell'API di OGame a &1",
		INSTALL_STEP4_GETSETTINGS : "Fetch settings",
		INSTALL_STEP5_TOOLNAME : "Nome del Galaxytool",
		INSTALL_STEP5_ENTER_TOOLNAME : "Questo è il nome che verrà mostrato nella pagina di accesso per identificare il tuo Galaxytool",
		INSTALL_STEP5_LANGUAGE : "Lingua di default",
		INSTALL_STEP5_EMAIL_TO : "Email a",
		INSTALL_STEP5_ENTER_EMAIL_TO : "Inserisci l'indirizzo email nel quale vuoi che siano inviate le notifiche riguardo le nuove registrazioni",
		INSTALL_STEP5_EMAIL_FROM : "Email Da",
		INSTALL_STEP5_ENTER_EMAIL_FROM : "Questo indirizzo email verrà indicato come indirizzo al quale rispondere alle email inviate dal galaxytool",
		INSTALL_STEP5_USE_PHPMAILER : "Usa il PHPMailer",
		INSTALL_STEP5_MAXSHOUTS : "Massimo numero di messaggi nel box dei messaggi",
		INSTALL_STEP5_ENTER_USE_PHPMAILER : "Usa il PHPMailer se il tuo server non è in grado di inviare email autonomamente",
		INSTALL_PHPMAILER_HOST : "SMPT",
		INSTALL_PHPMAILER_HOST_EXAMPLE : "es. smtp.provider.com",
		INSTALL_PHPMAILER_USER : "Nome utente dell'SMPT",
		INSTALL_PHPMAILER_USER_EXAMPLE : "es. user@provider.dcom",
		INSTALL_PHPMAILER_PASS : "Password per l'SMPT",
		INSTALL_PHPMAILER_SECURE : "Metodo di autenticazione (es. ssl)",
		INSTALL_PHPMAILER_PORT : "Porta SMTP",
		INSTALL_STEP6_INTRO : "Per favore, scegli una password per l'account <strong>admin</strong> la quale dovrà essere usata per il primo accesso al galaxytool",
		INSTALL_STEP7_CONFIG : "File config creato con successo",
		INSTALL_STEP7_CONFIG_FAILED : "Impossibile creare file config",
		INSTALL_STEP7_ATTRIBUTES : "File attributes creato con successo",
		INSTALL_STEP7_ATTRIBUTES_FAILED : "Impossibile creare file attributes",
		INSTALL_STEP7_CREATED_TABLES : "Tabelle del database create con successo",
		INSTALL_STEP8_INTRO : "L'installazione del Galaxytool è andata a buon fine!",
		INSTALL_STEP8_LOAD_DATA : "Caricamento dati da OGame ...",
		INSTALL_STEP8_LOAD_DATA_FINISHED : "Caricamento Completato",
		INSTALL_STEP8_DELETE_FILE : "Ora devi cancellare i file install.php e update.php dal tuo server web",
		INSTALL_STEP8_LOGON : "Per favore, accedi con il nome utente <strong>admin</strong> e la password che hai scelto poco fa",
		UPDATE_START : "Inizio aggiornamento alla versione",
		UPDATE_STEP_DONE : "Fatto",
		UPDATE_TITLE : "Aggiornamento Galaxytool per la versione",
		UPDATE_STEP1_WELCOME : "Benvenuto all'aggiornamento guidato di Galaxytool. Sarai affiancato e aiutato ad aggiornare Galaxytool.",
		UPDATE_STEP1_BACKUP_FILES : "Come prima cosa, fai un backup della cartella <strong>config</strong>! Dovrai ripristinarne il contenuto in caso di errori.",
		UPDATE_STEP1_BACKUP_DB : "Poi esegui un <a href=\"http://www.ehow.com/how_2036600_create-database-php.html\">backup</a> del database.",
		UPDATE_STEP1_PROCEED : "Una volta effettuato il backup puoi cominciare con la procedura di aggiornamento.",
		UPDATE_STEP1 : "Benvenuto",
		UPDATE_STEP2 : "Impostazioni Galaxytool",
		UPDATE_STEP2_OLD_VERSION : "Precedente versione di Galaxytool",
		UPDATE_STEP3 : "Aggiorna Galaxytool",
		UPDATE_STEP3_UPDATE_RUNNING : "Aggiornamento in corso, attendere...",
		UPDATE_STEP4 : "Concludi l'aggiornamento",
		UPDATE_STEP4_INTRO : "L'aggiornamento si è concluso con successo!",
		UPDATE_STEP4_UPDATE_DONE : "Aggiornamento effettuato.",
		UPDATE_FAILED : "Aggiornamento fallito.",
		GALAXYTOOL_DUMMY_TEXT : "dummy"
	})
);