define(
	({
		REPORT_WHEN : "em",
		RESOURCES_ON : "Recursos no",
		PLAYER_BANNED : "b",
		PLAYER_VACATION_MODE : "m",
		PLAYER_NOOB : "n",
		PLAYER_INACTIVE : "i",
		PLAYER_LONG_INACTIVE : "I",
		PLAYER_OUTLAW : "o",
		L_USERNAME : "Usuário",
		L_PASSWORD : "Senha",
		L_LOGINFAILURE : "Nome de Usuário ou Senha incorretos ou conta ainda não ativada",
		L_TOKENFAILURE : "Sua Chave de Login está errada ou sua conta ainda não esta ativada.",
		L_LOGINTEXT : "Introduza o nome de Usuário e Senha por favor",
		L_LANGUAGE : "Idiomas disponíveis:",
		L_TIMEOUT : "A sessão expirou",
		L_REGISTER : "Registar-se",
		L_PWLOST : "Esqueceu a Senha?",
		INDEX_TITLE : "Visão Geral",
		INDEX_INFO : "Informação",
		INDEX_ENTRIES : "Total de sistemas",
		INDEX_ENTRIES_LASTWEEK : "Novos sistemas na última semana",
		INDEX_ENTRIES_TO_OLD : "Sistemas com mais de um mês",
		INDEX_REGISTERED_USERS : "Usuários registados",
		INDEX_PAGEFORWARD : "Se o seu browser não suportar o redireccionamento de páginas, clique aqui.",
		INDEX_NOTICES : "Notas",
		INDEX_PLAYERS : "Estatísticas do Jogador",
		INDEX_ALLIES : "Estatísticas da Aliança",
		INDEX_REPORTS : "Relatórios de Espionagem",
		INDEX_VERSION : "Última versão disponivel para download",
		INDEX_LATEST_VERSION : "Nenhuma versão nova disponível",
		INDEX_SHOUTBOX : "Mensagens",
		INDEX_NOENTRY : "Sem mensagens",
		INDEX_COMMENT : "Escrever mensagem",
		INDEX_INSERT : "Inserir",
		INDEX_UMOD : "Jogadores em Modo de Férias",
		INDEX_NO_MOONS : "Número de luas",
		INDEX_NO_EMPTY_SYSTEMS : "Número de sistemas vazios",
		INDEX_NO_FULL_SYSTEMS : "Número de sistemas completamente cheios",
		INDEX_NO_TARGETS : "Número de possíveis alvos",
		INDEX_USERINFO : "Número de Usuários",
		INDEX_ONLINE : "Online agora",
		INDEX_TODAY : "Online hoje",
		INDEX_ALL : "Total de logins",
		GENERAL_LOAD_FORM : "Carregar parâmetros do formulário",
		GENERAL_SAVE_FORM : "Salvar parâmetros do formulário",
		GENERAL_SAVE_AS_TEXT : "Salvar como",
		GENERAL_SAVE : "Salvar",
		INDEX_USERMANAGEMENT : "Vista Geral de ativações",
		INDEX_NEEDADMIN : "Contas para Aprovar",
		INDEX_NEEDEMAIL : "Contas não Validadas",
		INDEX_TOOLBAR_INFO : "Informação do Galaxytool Plugin",
		INDEX_TOOLBAR_URL : "Galaxytool URL",
		INDEX_TOOLBAR_VERSION_REQUIRED : "Requer pelo menos Galaxytool plugin versão",
		INDEX_TOOLBAR_INSTALL_GUIDE : "Instruções de instalação para o plugin",
		INDEX_TOOLBAR_TOKEN : "Chave de Login",
		INDEX_TOOLBAR_NEW_TOKEN : "Obter nova chave",
		INDEX_PLAYERS_WITH_N_PLANETS : "Jogadores com mais de &1 planetas",
		INDEX_GETTING_STARTED : "Começando com o Galaxytool",
		INDEX_GETTING_STARTED1 : "Benvindo ao Galaxytool!",
		INDEX_GETTING_STARTED2 : "O Galaxytool vai ajudar você a analisar o que está acontecendo em seu OGame universo &1",
		INDEX_GETTING_STARTED3 : "Antes de começar a analisar seus dados, você precisa coleta-los primeiro. Para isso você precisa de um plugin para seu navedaor, como &1 para o Firefox.",
		INDEX_GETTING_STARTED4 : "Depois de instalado o plugin, você deve naveguer através de suas páginas no OGame como de costume e você verá uma janela de status pequena sempre que for enviado novos dados ao seu Galaxytool.",
		INDEX_GETTING_STARTED5 : "Assim que o plugin enviar conteúdo para o seu Galaxytool, você pode começar a analizar jogadores e suas colonias, onde estão, como estão desenvolvidas, que relatórios tem sobre ele e até mesmo sua atividade.",
		INDEX_GETTING_STARTED6 : "Mas você também vai poder acompanhar a sua evolução em relação a outros jogadores ou analisando seus relatórios de combate para ver o quanto Você acumulou nos últimos dias ou semanas.",
		INDEX_GETTING_WIKIPAGE : "Há muitos outros recursos dentro do Galaxytool.",
		INDEX_GETTING_WIKIPAGE2 : "Venha vê-los em nossa página wiki.",
		INDEX_GETTING_BOARD : "Para feedback ou ideias você pode usar o nosso Forum:",
		INDEX_GETTING_CHAT1 : "Ou visite-nos no nosso Chat:",
		INDEX_GETTING_CHAT2 : "Nós não estamos no ar 24/7, mas sempre que podemos estamos lá para ajudar, por favor tenha paciência.",
		INDEX_CLOSE : "Fechar",
		INDEX_LOGIN : "Login",
		GENERAL_REQUIRED_FIELDS : "Por favor, preencha todos os campos obrigatórios",
		INDEX_MESSAGES : "Mensagens",
		INDEX_EXAMPLE : "Exemplo",
		INDEX_INVALID_DATA : "Dados inválidos",
		GENERAL_COLUMN_HIDE_TITLE : "gerenciar colunas",
		GENERAL_COLUMN_HIDE_INFO : "Por favor, selecione as colunas que você quer ver na tabela.",
		GENERAL_ENTRIES_DELETED : "&1 dados deletados",
		GENERAL_APPLY : "Aplicar",
		STARTPAGE_GALAXYTOOL_DESCR : "<em>Galaxytool</em> é uma ferramenta para o jogo de browser OGame.",
		GENERAL_OVERWRITE : "Substituir entrada duplicada",
		GENERAL_OVERWRITE_QUESTION : "Substituir?",
		INDEX_OWN_LOGINS : "Seus logins",
		GENERAL_OPEN_IN_NEW_WINDOW : "Abrir em nova janela",
		GENERAL_UNIT_OF_MEASURE_DAYS : "Days",
		PROGRAM_NAME : "OGame Galaxytool",
		SHORTNAME : "Galaxytool",
		BACK_INDEX : "Voltar à página principal",
		UNIVERSE : "Universo",
		MENU_INFO_LINKS : "Informações",
		MENU_PAGE : "Vista Geral",
		MENU_DB_SEARCH : "Procurar no GalaxyTool",
		MENU_DB_NOTICES : "Procurar Notas",
		MENU_DB_REPORTS : "Procurar Rel. de Espi.",
		MENU_GALAXYVIEW : "Ver Sistema Solar",
		MENU_STATISTICS : "Estatísticas",
		MENU_ALLYHISTORY : "Histórico da Aliança",
		MENU_FLEET_MOVEMENTS : "Movimento de frota",
		MENU_COMBAT_REPORTS : "Relatório de combate",
		MENU_MESSAGES : "Mensagens no jogo",
		MENU_OPTION_LINKS : "Opções",
		MENU_DB_REFRESH : "Inserir no Banco de Dados",
		MENU_NOTICES : "Minhas Anotações",
		MENU_DB_STATUS : "Ver Universo",
		MENU_USEROPTIONS : "Gestão de Usuários",
		MENU_USEROPTIONS2 : "Opções de Usuário",
		MENU_USEROPTIONS3 : "Informação de Usuários",
		MENU_ADMIN : "Administração",
		MENU_LOGOUT : "Sair",
		MENU_STUFF : "Variados",
		MENU_FORUM_THREAD : "Fórum",
		MENU_DOWNLOADPAGE : "Página de download",
		MENU_LANGUAGE : "Idioma",
		MENU_HELP : "Ajuda",
		MENU_TOOLOPTIONS : "Opções do Galaxytool",
		PARSER_INFO1 : " foi inserido com <b>sucesso</b> no Banco de Dados!",
		PARSER_ERROR1 : "Erro ao tentar inserir as seguintes coordenadas:",
		PARSER_ERROR2 : "Não foi possível encontrar o Banco de Dados!",
		PARSER_ERROR3 : "Não foi possível encontrar o servidor do Banco de Dados!",
		PARSER_WRONG_UNIVERSE : "Universo errado - actuar: \"&1\" esperado: \"&2\"",
		SHOW_TITLE : "OGame Galaxytool - Procurar",
		SHOW_SEARCH : "Procurar no Banco de Dados",
		SHOW_ALLYSYMBOL : "TAG da Aliança",
		SHOW_PLAYERNAME : "Nome do Jogador",
		SHOW_MOONS : "Só entre Planetas com Lua",
		SHOW_NOTICES : "Só entre Planetas com Notas",
		SHOW_COLONIES : "Só entre Planetas possíveis de colonizar",
		SHOW_YES : "Sim",
		SHOW_NO : "Não",
		SHOW_SEARCHRANGE : "Intervalo",
		SHOW_SEARCH_IN : "Procurar na Galaxia",
		SHOW_FROM_SYSTEM : "do Sistema",
		SHOW_FROM_PLANET : "da posição",
		SHOW_TO : "até",
		SHOW_DESCRIPTION : "Pode-se usar o asterístico (*) nos campos TAG da Aliança e Nome do jogador. Assim poderás encontrar jogadores com *nome* em seu nome.<br /><br />Apenas preencha os campos que quer especificar.",
		SHOW_SORT_BY : "Ordenar por",
		SHOW_GALASYSTEM : "Galaxia/Sistema",
		SHOW_ALLYNAME : "Aliança",
		SHOW_SEARCHBUTTON : "Procurar",
		SHOW_ADDRESS : "Localização",
		SHOW_ALLYSORT : "Aliança",
		SHOW_PLANET : "Planeta",
		SHOW_STATUS : "Estado",
		SHOW_CURRENTNESS : "Última atualização",
		SHOW_PLAYER_STATUS : "Estado do Jogador",
		SHOW_PLAYER_STATUS1 : "Todos",
		SHOW_PLAYER_STATUS2 : "Possíveis alvos",
		SHOW_PLAYER_STATUS3 : "Inativos",
		SHOW_HITS : "Resultados",
		SHOW_OF : "de",
		SHOW_ASC : "Ordem crescente",
		SHOW_DESC : "Ordem decrescente",
		SHOW_RESULTS : "Resultados por página",
		SHOW_MOON : "Lua",
		SHOW_UKMOONSIZE : "desconhecido",
		SHOW_DF : "Destroços",
		SHOW_DF_LONG : "Campo de Destroços",
		SHOW_METAL : "M",
		SHOW_METAL_LONG : "Metal",
		SHOW_CRYSTAL : "C",
		SHOW_CRYSTAL_LONG : "Cristal",
		SHOW_BOTH : "Ambos",
		SHOW_AT_LEAST : "(pelo menos)",
		SHOW_DATE : "Data",
		SHOW_DATE_0 : "Não interessa",
		SHOW_DATE_1 : "Anteriores a",
		SHOW_DATE_2 : "Posteriores a",
		SHOW_RANK : "Rank",
		SHOW_FRANK : "Rank da frota",
		SHOW_MEMBERS : "Membros",
		SHOW_NOTRANKED : "Fora do Top 1500.",
		SHOW_NOTICERES : "Notas",
		SHOW_REPORTS : "Só entre Planetas com Relatórios de Espionagem",
		SHOW_REPORTS_SHORT : "R. Esp.",
		SHOW_NOTHING : "Sem resultados.",
		SHOW_ALLIANCE_STATUS : "Status da Aliança",
		SHOW_NO_STATUS : "no Status",
		SHOW_NAP : "PNA",
		SHOW_ALLIED : "Aliado",
		SHOW_WAR : "Em Guerra",
		SHOW_BOYCOTT : "Boicote",
		SHOW_NEUTRAL : "Neutro",
		SHOW_OWN : "Própria Aliança",
		SHOW_WING : "Forte",
		SHOW_EXT_OPTIONS1 : "Mostrar opções de busca para rank, data ou pesquisa de destroços.",
		SHOW_EXT_OPTIONS2 : "Mostrar opções de busca para colônias, luas, relatórios, notas, status do joagdor ou status diplomatico.",
		SHOW_EXT_OPTIONS3 : "Mostrar opções de busca para classificar os resultados.",
		SHOW_EXTENDED : "Busca avançada",
		SHOW_MOON_SELECTION : "Planeta com Lua",
		SHOW_REPORT_SELECTION : "Planeta com relatório",
		SHOW_FILTER_BY : "Excluir da lista",
		SHOW_FILTER_NONE : "Nenhuma",
		SHOW_PLAYERS_WITHOUT_PROGRESS : "Show players without score changes within the last few days",
		STATUS_TITLE : "OGame Galaxytool - Ver Universo",
		STATUS_DB_STATUS : "Informação de Galáxias/Sistemas Solares disponiveis no Banco de Dados",
		STATUS_COLOR : "Cor ",
		STATUS_AGE1 : "Última atualização: < 1 dia.",
		STATUS_AGE2 : "Última atualização: 2 - 4 dias.",
		STATUS_AGE3 : "Última atualização: 4 - 7 dias.",
		STATUS_AGE4 : "Última atualização: 1 - 2 semanas.",
		STATUS_AGE5 : "Última atualização: 2 - 4 semanas.",
		STATUS_AGE6 : "Última atualização: > 1 mês!",
		STATUS_AGE7 : "Sem informação no Banco de Dados.",
		STATUS_ON : "(ligado)",
		STYLES_COLOR1 : "Verde claro",
		STYLES_COLOR2 : "Verde",
		STYLES_COLOR3 : "Verde escuro",
		STYLES_COLOR4 : "Amarelo",
		STYLES_COLOR5 : "Laranja",
		STYLES_COLOR6 : "Vermelho",
		STYLES_COLOR7 : "Azul",
		STATUS_DB_LEGEND : "Legenda",
		STATUS_GALAXY : "Vista Geral da Galaxia",
		USER_TITLE : "Gestão de Usuários",
		USER_NAMES : "Usuário",
		USER_ERROR : "Erro",
		USER_NEWUSER : "Novo Usuário",
		USER_OPTIONS : "Opções",
		USER_USERNAME : "Nome de Usuario",
		USER_PASSWORD : "Senha",
		USER_PASSWORD_CONFIRM : "Confirmar Senha",
		USER_GALAXY : "Galáxia",
		USER_SEARCH : "Permitir Consultas",
		USER_INSERT : "Permitir Inserções",
		USER_DELETE : "Apagar",
		USER_DELETE_ENTRY : "Tem certeza que quer deletar o usuário: ",
		USER_STATUS : "Ver Estatísticas",
		USER_STYLES : "Modificar Skin",
		USER_SUBMIT : "Enviar",
		USER_RESET : "Limpar",
		USER_YES : "Sim",
		USER_NO : "Não",
		USER_STYLEPATH : "Caminho para styles.css",
		USER_PROBES : "Inserir Relatórios de Espionagem",
		USER_EMAIL : "E-mail",
		USER_ERROR1 : "Senha errada ou e-mail inválido.",
		USER_ERROR2 : "E-mail inválido.",
		USER_INGAME : "Nome dentro do OGame",
		USER_ALLYTAG : "TAG da Aliança",
		USER_ALLYHISTORY : "Histórico da Aliança",
		USER_DIPLOMATIC : "Diplomacia",
		USER_STATSPAGE : "Número de entradas na página de estatísticas",
		USER_LINKS : "Links",
		USER_LINKS2 : "Formato:<br>texto;url<br>texto2;url2<br>texto3;url3",
		USER_EXPORT_TITLE : "Estilo de Exportação (BB Codes)",
		USER_BB_COORDINATES : "Coordenadas",
		USER_BB_MOON : "Lua",
		USER_BB_DEBRIS : "Destroços",
		USER_BB_ALLY : "Nome da aliança",
		USER_BB_ALLYDETAILS : "Detalhes da aliança",
		USER_BB_PLAYERNAME : "Nome do jogador",
		USER_BB_BANNED : "Jogador banido",
		USER_BB_VACATION : "Modo de Férias",
		USER_BB_NOOB : "Jogador Fraco (noob)",
		USER_BB_INACTIVE : "7 dias inativo",
		USER_BB_LONGINACTIVE : "28 dias inativo",
		USER_DELETION : "Apagar",
		USER_FLEETINFO : "Movimento de frota",
		USER_ACTIVITIES : "Atividade do jogador",
		USER_MAINTENANCE : "Manutenção do Galaxytool",
		USER_MANAGEMENT : "Gestão de Usuários",
		USER_DELETE_MY_COMBAT_REPORTS : "Apagar meus relatórios de combate",
		USER_DELETE_MY_MESSAGES : "Apagar minhas mensagens",
		USER_DELETE_MY_FLEETMOVES : "Apagar meu movimento de frotas",
		USER_DELETE_MY_COMBAT_REPORTS_LIMITED : "Apagar meus relatórios de combate com mais de &1 dias",
		USER_DELETE_MY_MESSAGES_LIMITED : "Apagar minhas mensagens com mais de &1 dias",
		USER_TABLE_ENTRIES : "Quantidade de resultado de busca por página",
		USER_EXISTS : "Usuário já existente",
		USER_BB_OUTLAW : "Fora da Lei",
		USER_INVALID_URL : "URL &1 parece ser inválido - URL será ignorado",
		VIEW_TITLE : "OGame Galaxytool - Ver Sistema Solar",
		VIEW_NODATA : "Sem informação",
		VIEW_GALAXY : "Galáxia",
		VIEW_SYSTEM : "Sistema Solar",
		VIEW_POSITION : "#",
		VIEW_PLANET : "Planeta",
		VIEW_MOON : "Lua",
		VIEW_TF : "Destroços",
		VIEW_PLAYER : "Jogador",
		VIEW_PLAYER_ADD : "(Rank/Estado)",
		VIEW_ALLY_ADD : "(Rank/Membros)",
		VIEW_METAL : "M",
		VIEW_CRYSTAL : "C",
		VIEW_COLONISED : "Planetas habitados",
		VIEW_UKMOONSIZE : "n/d",
		VIEW_BACK : "Voltar",
		VIEW_NOTICE : "Notas",
		VIEW_REPORTS : "R. Esp.",
		VIEW_MOONPHALANX : "A(s) seguinte(s) lua(s) pode(m) escanear este sistema",
		VIEW_NOMOONS : "Não foram encontradas luas",
		VIEW_IRAKS : "O(s)seguinte(s) planeta(s) pode(m) alcançar este sistema com mísseis interplanetários",
		VIEW_NOIRAKS : "Não foram encontrados mísseis interplanetários",
		VIEW_ALLY : "Aliança",
		VIEW_MOON_DESTROY_CHANCE : "Chance de destruir lua",
		VIEW_CHANCE_WITH_ONE : "Chance com uma estrela da morte",
		VIEW_CHANCE_WITH_N : "Chance com ",
		VIEW_DEATH_STARS : "estrelas da morte",
		VIEW_DS_DESTROY_CHANCE : "Chance de perder estrela(s) da morte",
		VIEW_TOP : "Top",
		VIEW_GO : "go",
		VIEW_DIAMETER : "Diâmetro",
		PW_TITLE : "OGame Galaxytool - Mudar a Senha",
		OLD_PASSWORD : "Senha antiga",
		NEW_PASSWORD : "Senha nova",
		CONFIRM_NEW_PASSWORD : "Confirmar a Senha nova",
		PW_MISMATCH : "As Senhas não coincidem!",
		PW_ERROR : "A Senha antiga não está correcta!",
		UPDATE_DONE : "Atualizada com sucesso!",
		TIMEZONE_OFFSET : "Diferença de horas para o servidor",
		DELETE_ACCOUNT : "Apagar esta conta do Galaxytool",
		DELETE_ACCOUNT_SAFETY_REQUEST : "Tem certeza que quer apagar esta conta do Galaxytool?",
		CH_PASSWD_AUTHORIZATION : "Autorizações",
		CH_PASSWD_ADMIN : "Admin",
		TIMEZONE_OGAME_OFFSET : "Diferença de horas para o servidor do OGame",
		CH_PASSWD_USER_LANGUAGE : "Mude para este idioma no próximo login",
		CH_PASSWD_USER_LANGUAGE_NO_CHANGE : "Sem mudança",
		CH_PASSWD_EXPAND : "Expandido",
		CH_PASSWD_COLLAPSE : "Fechado",
		CH_PASSWD_HIDDEN : "Escondido",
		CH_PASSWD_GETTING_STARTED : "Mostrar informações dos Primeiros passos depois de logar",
		CH_PASSWD_PLUGIN : "Mostrar informações do Plugin depois de logar",
		NOTICE_TITLE : "OGame Galaxytool - As minhas Notas",
		NOTICE_HEADER : "Editar Nota",
		NOTICE_HEADER2 : "Editar Notas próprias",
		NOTICE_PUBLIC : "Visível aos outros?",
		NOTICE_YES : "Sim",
		NOTICE_NO : "Não",
		NOTICE_TEXT : "Texto",
		NOTICE_SAVE : "Salvar",
		NOTICE_DELETED : "Nota apagada.",
		NOTICE_SAVED : "Nota salva.",
		NOTICE_RESULTS : "Todos os resultados",
		NOTICE_USER : "Usuário",
		NOTICE_DATE : "Data",
		NOTICE_EDIT : "Editar",
		NOTICE_DELETE : "[ Apagar ]",
		NOTICE_NEW : "Criar uma nota",
		NOTICE_NOTPUBLIC : "Nota privada.",
		NOTICE_ALL : "Todas",
		NOTICE_NONE : "Nenhuma",
		NOTICE_SEARCH : "Procurar Notas",
		NOTICE_SEARCH_SHORT : "Procurar",
		NOTICE_HITS : "Resultados",
		NOTICE_SHOWRESULTS : "Resultados por página",
		NOTICE_OF : "de",
		NOTICE_NOTHING : "Sem resultados",
		NOTICE_CHARS : "Caracteres",
		NOTICE_PLAYERNAME : "Jogador",
		NOTICE_SHOWALL : "Mostrar todas Anotações",
		REPORTS_TITLE : "OGame Galaxietool - Relatórios de Espionagem",
		REPORTS_RESOURCES : "Recursos",
		REPORTS_FLEET : "Frotas",
		REPORTS_DEFENCE : "Sistemas de defesas",
		REPORTS_BUILDINGS : "Edifícios",
		REPORTS_TECHNOLOGY : "Pesquisas",
		REPORTS_MOON : "Lua",
		REPORTS_SEARCH : "Procurar Relatórios de Espionagem",
		REPORTS_SEARCH_SHORT : "Procurar",
		REPORTS_HITS : "Resultados",
		REPORTS_NOTHING : "Sem resultados",
		REPORTS_ADDRESS : "Localização",
		REPORTS_CURRENTNESS : "Última atualização",
		REPORTS_PLAYERNAME : "Jogador",
		REPORTS_ALLY : "Aliança",
		REPORTS_VIEW : "Ver Relatório",
		REPORTS_SEARCH_IN : "Procurar na Galáxia",
		REPORTS_FROM_SYSTEM : "desde o Sistema",
		REPORTS_TO : "até ao",
		REPORTS_DELETE : "[ Apagar ]",
		REPORTS_DELETED : "Relatório apagado!",
		REPORTS_RESULTS : "Resultados por página",
		REPORTS_OF : "de",
		REPORTS_DATE : "Data",
		REPORTS_DATE_0 : "Não interessa",
		REPORTS_DATE_1 : "Desde",
		REPORTS_DATE_2 : "até",
		REPORTS_NOTICES : "Notas",
		REPORTS_AT_LEAST_RESOURCES : "Recursos (pelo menos)",
		REPORTS_SEARCH_EXTENDED : "Busca avançada",
		REPORTS_FLEET_RESIS : "Pontos da frota",
		REPORTS_DEFENCE_RESIS : "Pontos da defesa",
		REPORTS_ALL_RESIS : "Soma de pontos",
		REPORTS_TECHS : "Tecnologias",
		REPORTS_UNKNOWN_ENTRIES : "entradas desconhecidas",
		REPORTS_PARTLY_INSERTED : "parcialmente inserido",
		REPORTS_FOR_ALL_RES : "para todos os recursos",
		REPORTS_FOR_TF : "para o campo de destroços",
		REPORTS_KT : "Naves pequenas de carga",
		REPORTS_GT : "Naves grandes de carga",
		REPORTS_SS : "Naves de batalha",
		REPORTS_REC : "Reciclador",
		REPORTS_RAIDABLE : "Only Raidable targets",
		REPORTS_ALL_RESOURCES : "Recursos Totais",
		REPORTS_STUFF : "Variados",
		REPORTS_SPEEDSIM : "Simular com Speedsim",
		REPORTS_DRAGOSIM : "Simular com Dragosim",
		REPORTS_STATUS : "Status",
		REPORTS_ERROR : "Um erro ocorreu",
		REPORTS_OWN_REPORTS : "Somente meus relatórios",
		REPORTS_UPLOAD_BY : "Relatório enviado por",
		REPORTS_DEPTH : "Profundidade do relatório",
		REPORTS_FLEET_SCORE : "Custo da frota",
		REPORTS_DEFENCE_SCORE : "Custo da defesa",
		REPORTS_HOURS : "horas",
		REPORTS_MAX_RESULTS_HIT : "Sua consulta resultou mais de &1 . Somente os &1 resultados estão sendo mostrados. Por favor ajuste o seu pedido de busca para obter resultados mais preciso.",
		REPORTS_OSIMULATE : "Simular com OSimulate",
		REPORTS_SHOW_ONLY : "Mostrar só",
		REPORTS_SHOW_PLANETS : "Planetas",
		REPORTS_SHOW_MOONS : "Luas",
		REPORTS_OWNER : "Relatórios pertencentes a",
		STATS_TITLE : "OGame Galaxytool - Estatísticas",
		STATS_TBLHEAD : "Estatísticas",
		STATS_RANK : "Rank",
		STATS_PLAYERNAME : "Jogador",
		STATS_ALLYNAME : "TAG da Aliança",
		STATS_SCORE : "Pontos",
		STATS_FLEET : "Frota",
		STATS_RESEARCH : "Pesquisas",
		STATS_MEMBERS : "Membros",
		STATS_STATUS : "Status",
		STATS_NOTHING : "Não definido",
		STATS_NAP : "PNA",
		STATS_ALLIED : "Aliança",
		STATS_WAR : "Em Guerra",
		STATS_BOYCOTT : "Boicote",
		STATS_NEUTRAL : "Neutro",
		STATS_OWN : "Própria Aliança",
		STATS_WING : "Ala da Aliança",
		STATS_UPDATE : "Entrada de",
		STATS_PLAYERSTATS : "Estatísticas do Jogador",
		STATS_ALLYSTATS : "Estatísticas da Aliança",
		STATS_DELETE : "Você deseja apagar este conteúdo?",
		STATS_CONFIRM_DELETE : "Tem certeza que quer deletar esta entrada?",
		STATS_CHANGE_PLAYER_STATUS : "Status do Jogador",
		STATS_CHANGE_ALLIANCE_STATUS : "Status da Aliança",
		STATS_CHANGE_ALLIANCE_STATUS_HINT : "Todos membros desta aliança recebem o Status escolhido. Qualquer status anterior será sobrescrito. Você poderá¡ mudar o status de alguns jogadores depois.",
		STATS_UNKNOWN : "Outros",
		STATS_DETAILS : "Detalhes para",
		STATS_PLAYERSTATUS : "Estado do Jogador",
		STATS_IGNORE_STATUS : "Todos",
		STATS_ACTIVE : "Ativo",
		STATS_INACTIVE : "7 dias inativo",
		STATS_BANNED : "Jogador banido",
		STATS_VACATION : "Modo de Férias",
		STATS_NOOB : "Jogador Fraco (noob)",
		STATS_YES : "Sim",
		STATS_NO : "Só entre Planetas com Notas",
		STATS_SEARCH : "Permitir Consultas",
		STATS_SHOW_GRAPH : "Mostrar detalhes para a distribuição de pontuação",
		STATS_LONG_INACTIVE : "28 dias inativo",
		STATS_STANDARD : "Pontos",
		STATS_MILITARY : "Pontos Militares",
		STATS_ECONOMY : "Economia",
		STATS_HONOUR : "Pontos de Honra",
		STATS_MILITARY_BUILD : "Militares construídos",
		STATS_MILITARY_DESTROYED : "Militares destruídos",
		STATS_MILITARY_LOST : "Militares perdidos",
		REGISTER_REGISTRATE : "Registar",
		REGISTER_LOGINNAME : "Usuário",
		REGISTER_PASSWORD : "Senha",
		REGISTER_PASSWORD_CONFIRM : "Confirme a Senha",
		REGISTER_EMAIL : "E-mail",
		REGISTER_INGAME : "Nome no OGame",
		REGISTER_ALLYTAG : "TAG da Aliança",
		REGISTER_EMAILVERIFICATION : "Verificação de E-mail",
		REGISTER_EMAILTEXT : "Por favor visite o seguinte link para confirmar o registo no GalaxyTool.",
		REGISTER_ERROR1 : "Nome de Usuário já escolhido.",
		REGISTER_ERROR2 : "Erro ao tentar enviar o e-mail. Por favor contacte o admin.",
		REGISTER_ERROR3 : "Erro ao tentar enviar informação para o Banco de Dados!",
		REGISTER_INFO1 : "A sua conta foi criada.",
		REGISTER_INFO2 : "Por favor visite o link no seu e-mail para confirmar o registo.",
		REGISTER_INFO3 : "Registo confirmado. Resta apenas a ativação que será feita pelo admin.",
		REGISTER_BUTTON : "Voltar à página principal",
		REGISTER_NEW_SUBJECT : "Um novo Usuário registou-se no galaxytool",
		REGISTER_NEW_MAILTEXT : "Um novo Usuário registrou-se.",
		REGISTER_BACK : "Voltar para primeira página",
		REGISTER_MISSING_FIELDS : "Preencha todos os campos solicitados",
		REGISTER_ERROR4 : "Este Email não é valido.",
		REGISTER_ERROR5 : "Senha não confere.",
		REGISTER_PWS : "Qualidade da senha",
		REGISTER_PWS0 : "Muito fraca",
		REGISTER_PWS1 : "Fraca",
		REGISTER_PWS2 : "Boa",
		REGISTER_PWS3 : "Forte",
		REGISTER_PWS4 : "Muito forte",
		REGISTER_EMAIL_USED : "Este Email já esta sendo utilizado ",
		LOSTPW_TITLE : "Perdi a minha Senha",
		LOSTPW_INFO2 : "Uma nova Senha foi gerada e enviada para o seu e-mail.",
		LOSTPW_BUTTON1 : "Receber nova Senha",
		LOSTPW_BUTTON2 : "Voltar à página principal",
		LOSTPW_LOGINNAME : "Nome de Usuário",
		LOSTPW_EMAIL : "E-mail",
		LOSTPW_ERROR1 : "Erro ao tentar enviar informação para o Banco de Dados!",
		LOSTPW_ERROR2 : "Nenhuma entrada encontrada!",
		LOSTPW_ERROR3 : "Erro ao tentar enviar o e-mail. Por favor contacte o admin.",
		LOSTPW_EMAIL_SUBJECT : "Nova Senha Galaxytool",
		LOSTPW_EMAIL_TEXT1 : "O seu novo login para o galaxytool é",
		LOSTPW_EMAIL_TEXT2 : "Usuário",
		LOSTPW_EMAIL_TEXT3 : "Senha",
		LOSTPW_INFO1 : "Você receberá um e-mail para confirmar o seu pedido de reposição de senha.",
		LOSTPW_CONFIRM_RESET_SUBJECT : "Esqueceu a senha?",
		LOSTPW_CONFIRM_RESET_MESSAGE : "Ola,\n\n você solicitou uma redefinição de senha para o Galaxytool. Para gerar uma nova senha, clique no seguinte link:",
		USERINFO_TITLE : "OGame Galaxytool - Informação de Usuários",
		USERINFO_NAMES : "Todos os Usuários",
		USERINFO_DETAIL : "Informação detalhada sobre",
		USERINFO_ERROR1 : "Não existe nenhum Usuário com este ID!",
		USERINFO_USERNAME : "Usuário",
		USERINFO_INGAME : "Nome no OGame",
		USERINFO_EMAIL : "E-mail",
		USERINFO_ALLYTAG : "Aliança",
		USERINFO_STYLEPATH : "Skin",
		USERINFO_STATUS : "Estado",
		USERINFO_ACTIVATE : "Activar Jogador",
		USERINFO_LOGINS : "Número de Acessos",
		USERINFO_LASTLOGIN : "Último Acesso em",
		USERINFO_DATA : "Informação sobre os Sistemas Solares inseridos",
		USERINFO_NODATA : "<center>Nunca inseriu um Sistema Solar</center>",
		USERINFO_GALAXY : "Galáxia",
		USERINFO_SYSTEMS : "Número de Sistemas Solares",
		USERINFO_IP : "Endereço IP",
		USERINFO_LOGINTIME : "Acesso em",
		USERINFO_NOLOGIN : "O Usuário nunca se ligou.",
		USERINFO_LAST_GALAXYUPDATE : "Inseriu o último Sistema Solar em",
		USERINFO_LAST_PUBLIC_NOTICE : "Última Nota pública em",
		USERINFO_LAST_PRIVATE_NOTICE : "Última Nota privada em",
		USERINFO_NUMBEROF_PUBLIC_NOTICE : "Número de Notas públicas",
		USERINFO_NUMBEROF_PRIVATE_NOTICE : "Número de Notas privadas",
		USERINFO_ACTIVATED : "Conta activada",
		USERINFO_ACTIVATIONTEXT : "O administrador do Galaxytool ativou a sua conta.\n\Diverta-se com o Galaxytool!",
		USERINFO_LAST_SUBMIT : "Inserido últimos dados",
		ALLYHISTORY_TITLE : "OGame Galaxietool - Histórico da Aliança",
		ALLYHISTORY_TBLHEAD : "Histórico da Aliança",
		ALLYHISTORY_PLAYERNAME : "Jogador",
		ALLYHISTORY_ALLYNAME : "Aliança",
		ALLYHISTORY_LASTMONTH : "Ultimo Mês",
		ALLYHISTORY_ALL_DATA : "Todas as informações diponíveis",
		ALLYHISTORY_SHOW : "Mostrar Estatística",
		ALLYHISTORY_TIMESPAN : "Duração",
		ALLYHISTORY_PROGESS : "Progresso",
		ALLYHISTORY_SCORE : "Pontuação",
		ALLYHISTORY_FSCORE : "Frotas",
		ALLYHISTORY_RSCORE : "Pesquisas",
		ALLYHISTORY_MEMBER : "Membros",
		ALLYHISTORY_NOTHING : "nenhuma entrada encontrada",
		ALLYHISTORY_DETAILS : "Detalhes",
		ALLYHISTORY_SHOW_ADDRESS : "Localização",
		ALLYHISTORY_ESCORE : "Economia",
		ALLYHISTORY_MSCORE : "Pontos Militares",
		DETAILEDINFO_PLAYERINFO_TITLE : "Informação do Jogador",
		DETAILEDINFO_ALLYINFO_TITLE : "Informação da Aliança",
		DETAILEDINFO_PLAYERINFO_TBLHEAD : "Informação detalhada sobre o Jogador",
		DETAILEDINFO_ALLYINFO_TBLHEAD : "Informação detalhada sobre Aliança",
		DETAILEDINFO_NO_ALLIANCE : "nenhum",
		DETAILEDINFO_SCORE : "Estatísitca de Contagem",
		DETAILEDINFO_FLEET : "Estatísitca de Frota",
		DETAILEDINFO_RESEARCH : "Estatísitca de Pesquisa",
		DETAILEDINFO_RANK : "Rank",
		DETAILEDINFO_POINTS : "Pontos",
		DETAILEDINFO_KNOWN_PLANETS : "Planetas conhecidos",
		DETAILEDINFO_MOONS : "Luas conhecidas",
		DETAILEDINFO_PHALANX_AREA : "Area da Phalanx",
		DETAILEDINFO_NO_PHALANX_AREA : "Phalanx não encontrada",
		DETAILEDINFO_NOTICES : "Notas",
		DETAILEDINFO_NO_NOTICES : "Sem anotações",
		DETAILEDINFO_PREVIOUS_ALLIANCES : "Alianças anteriores",
		DETAILEDINFO_RESOURCES_PER_HOUR : "Recursos por hora",
		DETAILEDINFO_RESOURCES_PER_DAY : "Recursos por dia",
		DETAILEDINFO_RESOURCES_PER_WEEK : "Recursos por semana",
		DETAILEDINFO_RESOURCES_PER_MONTH : "Resousos por mÃªs (30 dias)",
		DETAILEDINFO_METAL : "Metal",
		DETAILEDINFO_CRYSTAL : "Cristal",
		DETAILEDINFO_DEUTERIUM : "Deutério",
		DETAILEDINFO_UNKNOWN : "Desconhecido",
		DETAILEDINFO_SCORE_DISTRIBUTION : "Distribuição de pontos",
		DETAILEDINFO_GENERAL : "Detalhes",
		DETAILEDINFO_MEMBERS : "Membros",
		DETAILEDINFO_GRAPHS : "Gráfico",
		DETAILEDINFO_RESOURCES : "Recursos",
		DETAILEDINFO_FLEET_TAB : "Frota",
		DETAILEDINFO_TECH : "Tecnologia",
		DETAILEDINFO_FLEET_DETAIL : "Soma / (média dos jogadores) junto com todos os relatórios disponíveis",
		DETAILEDINFO_TECH_DETAIL : "Média de toda informação disponível do jogador",
		DETAILEDINFO_PLANET_TAB : "Planetas",
		DETAILEDINFO_MOON_TAB : "Luas",
		DETAILEDINFO_ACTIVITIES : "Atividades",
		DETAILEDINFO_NODATA : "VER_SEMDADOS",
		DETAILEDINFO_ACTIVITY_DESCRIPTION : "Mostrar atividades em &1 coletadas de:",
		DETAILEDINFO_GALAXYVIEWS : "Visão da Galaxia",
		DETAILEDINFO_SCANS : "Ações de Espionagem",
		DETAILEDINFO_MESSAGES : "Mensagens de jogadores",
		DETAILEDINFO_COMBATS : "Relatório de combate",
		DETAILEDINFO_ALLYPAGE : "Overview da Aliança",
		DETAILEDINFO_MANUAL : "Inserido manualmente",
		DETAILEDINFO_START : "Começando",
		DETAILEDINFO_TO : "Para",
		DETAILEDINFO_TODAY : "Hoje",
		DETAILEDINFO_DATA_RESTRICTION : "Retrito para:",
		DETAILEDINFO_WEEKDAY_WEEKEND : "Final de semana",
		DETAILEDINFO_WEEKDAY_WORKINGDAY : "Dia da Semana",
		DETAILEDINFO_WEEKDAY_MONDAY : "Segunda",
		DETAILEDINFO_WEEKDAY_TUESDAY : "Terça",
		DETAILEDINFO_WEEKDAY_WEDNESDAY : "Quarta",
		DETAILEDINFO_WEEKDAY_THURSDAY : "Quinta",
		DETAILEDINFO_WEEKDAY_FRIDAY : "Sexta",
		DETAILEDINFO_WEEKDAY_SATURDAY : "Sábado",
		DETAILEDINFO_WEEKDAY_SUNDAY : "Domingo",
		DETAILEDINFO_WEEKDAY_SHORTLENGTH : 3,
		DETAILEDINFO_PLAYER_CURRENTLY_ACTIVE : "O Jogador está ativo no momento",
		DETAILEDINFO_PLAYER_MESSAGES : "Mensagens de jogadores ativos",
		DETAILEDINFO_SHOW : "Mostrar",
		DETAILEDINFO_NONE : "nenhum disponível",
		DETAILEDINFO_ENTER_MANUALLY : "Inserir atividade para este jogador",
		DETAILEDINFO_PLAYER_SEEN_ON : "Jogador estava online em",
		DETAILEDINFO_INSERT : "Inserir",
		DETAILEDINFO_OGAME_SERVERTIMES : "Por favor note: Todas as datas e horários se referem ao servidor OGame!",
		DETAILEDINFO_DAY_VIEW : "visão 24 horas",
		DETAILEDINFO_WEEK_VIEW : "visão semanal",
		DETAILEDINFO_HOME_PLANET : "Planeta Principal",
		DETAILEDINFO_PLANETNAME : "Nome",
		DETAILEDINFO_DEFENCE_SCORE : "Pontos de Defesa",
		DETAILEDINFO_DEFENCE_SCORE_TOOLTIP : "Pontos de Defesa = Frota - Pontos + Pesquisa + Economia.<br/>Todas essas estatísticas devem ser atualizados para ter um resultado significativo!",
		DETAILEDINFO_SCORE_PER_SHIP : "Pontos por nave",
		DETAILEDINFO_SHIPS : "Numero de naves",
		DETAILEDINFO_DATE_IN_FUTURE : "Não insira atividades com datas passadas.",
		ADMIN_TITLE : "Administração do Galaxytool",
		ADMIN_DISCLAMER : "Atenção: Execute qualquer um destes scripts sob o seu próprio risco! A maioria deles apaga dados.",
		ADMIN_INCONSISTENCIES : "Banco de dados inconsistente",
		ADMIN_PLANETS : "Planetas na posição 0 ou maior que 15",
		ADMIN_GALAXIES : "Apagar galaxias maiores que &1",
		ADMIN_PLAYERS : "Apagar jogadores sem OGame playerid - Leva a entrada duplicada de jogadores",
		ADMIN_REPORTS : "Apagar relatórios onde os planetas não existem mais",
		ADMIN_MISC : "Miscellania",
		ADMIN_RESET : "Reset Galaxytool (Somente usuário e tabela ip não são deletadas)",
		ADMIN_OLD_PLAYERS : "Apague entradas de jogador com mais de &1 dias",
		ADMIN_OLD_REPORTS : "Apagar relatórios com mais de &1 dias",
		ADMIN_LOADING : "Não feche esta pagina enquanto ela estive carregando.",
		ADMIN_STATUS : "Status da sua solicitação",
		ADMIN_SELECTION : "Pelo menos uma solicitação deve ser selecionada",
		ADMIN_SAFETY : "Você tem certeza que quer rodar este(s) script(s) ?",
		ADMIN_DONE : "Feito",
		ADMIN_NOTBD : "Nada para ser feito",
		ADMIN_OLD_GALAXIES : "Remova vista de galaxias com mais de &1 dias",
		ADMIN_UNUSED_PLAYERS : "Remova jogadores que não estão em nenhuma vista de galaxia",
		ADMIN_OLD_ACTIVITIES : "Remova atividades de jogadores com mais de &1 dias",
		ADMIN_OLD_COMBATS : "Remover relatório de combate com mais de &1 dia/s",
		ADMIN_OLD_INGAME_MSG : "Remover mensagens ingane com mais de &1 dia/s",
		ADMIN_OGAME_API : "Carregar dados públicos do OGame para a Galaxytool",
		ADMIN_OGAME_ALL_DATA : "Todas as informações diponíveis",
		ADMIN_OGAME_GALAXY_DATA : "Ver Sistema Solar",
		ADMIN_OGAME_STATISTICS_DATA : "Estatísticas",
		ERRORPAGE_PAGEFORWARD : "Click aqui caso seu navegador não suporte encaminhamento de página",
		ERRORPAGE_PERMISSION_DENIED : "Você não tem permissão para acessar esta página. Click em voltar.",
		FLEETS_TITLE : "OGame Galaxytool - Movimento de frotas",
		FLEETS_ACTUAL_FLEETS : "Atual movimento de frotas",
		FLEETS_YES : "Sim",
		FLEETS_NO : "Só entre Planetas com Notas",
		FLEETS_DETAILS : "Detalhes",
		FLEETS_MISSION_EXPEDITION : "Expedição",
		FLEETS_MISSION_COLONIZATION : "Colonizar",
		FLEETS_MISSION_RECYCLE : "Reciclar",
		FLEETS_MISSION_TRANSPORT : "Transportar",
		FLEETS_MISSION_DEPLOYMENT : "Transferir",
		FLEETS_MISSION_ESPIONAGE : "Espionar",
		FLEETS_MISSION_ACS_DEFEND : "Defender em ACS",
		FLEETS_MISSION_ATTACK : "Atacar",
		FLEETS_MISSION_ACS_ATTACK : "Atacar em ACS",
		FLEETS_MISSION_MOON_DESTRUCTION : "Destruir Lua",
		FLEETS_MISSION_MISSILE_ATTACK : "Ataque de míssil",
		FLEETS_NO_DATA : "Não foram encontrados dados",
		FLEETS_FLEET : "Frota",
		FLEETS_ALL_FLEETS : "Mostrar todos os movimentos da frota",
		COMBAT_REPORT_OUDATED_GALAXYVIEW : "Sua Galáxia está desatualizada. Por favor viste as coordenadas do atacante e do defensor primeiro!",
		MESSAGES_TITLE : "OGame Galaxytool - Mensagens do OGame",
		MESSAGES_PLAYERNAME : "Nome do Jogador",
		MESSAGES_SUBJECT : "Assunto",
		MESSAGES_DATE : "Data",
		MESSAGES_FILTER : "Filtro",
		MESSAGES_DELETE : "Apagar mensagem",
		MESSAGES_PUBLISH_DETAIL : "Publicar o conteúdo da mensagem para o jogador.",
		MESSAGES_PUBLISH_HEADER : "&sender enviou mensagem para &recipient em &date:\n\n &message",
		MESSAGES_PLAYER_FILTER : "Mensagens do jogador:",
		MESSAGES_CONTENT : "Content",
		COMBATS_TITLE : "OGame Galaxytool - Relatório de combate",
		COMBATS_ATTACKER : "Atacante",
		COMBATS_DEFENDER : "Defensor",
		COMBATS_DATE : "Data",
		COMBATS_OWNER : "Dono",
		COMBATS_WINNER : "Vencedor",
		COMBATS_COMBATREPORT : "Relatório de combate",
		COMBATS_COMBAT_AT : "Combate em",
		COMBATS_LOST_UNITS : "Unidades perdidas",
		COMBATS_LOOT : "Roubou",
		COMBATS_DEBRIS : "Campo de destroços",
		COMBATS_AND : "e",
		COMBATS_PUBLISH : "Marcar como publico este relatório",
		COMBATS_UNPUBLISH : "Marcar como privado (torna particular novamente)",
		COMBATS_DELETE : "Apagar relatório",
		COMBATS_CHECK_ALL : "Selecionar Todos",
		COMBATS_UNCHECK_ALL : "deselecionar Todos",
		COMBATS_WITH_SELECTED : "Com as selecionadas",
		COMBATS_PUBLIC_REPORTS : "Relatórios públicos",
		COMBATS_YES : "Sim",
		COMBATS_NO : "Só entre Planetas com Notas",
		COMBATS_SEARCH_OPTIONS : "Opções de busca",
		COMBATS_SEARCH : "Ir",
		COMBATS_RESET : "Resetar",
		COMBATS_COORDINATES : "Coordenadas",
		COMBATS_INVALID_GALAXY_ENTERED : "Galaxy inválida",
		COMBATS_INVALID_SYSTEM_ENTERED : "Systema inválido",
		COMBATS_INVALID_PLANET_ENTERED : "Planeta inválido",
		COMBATS_GALAXY_FROM_TO : "Galaxia",
		COMBATS_SYSTEM_FROM_TO : "Systema",
		COMBATS_PLANET_FROM_TO : "Planeta",
		COMBATS_APPLY : "Aplicar",
		COMBATS_COMBAT_SUMMARY : "Resumo do relatório de combate",
		COMBATS_DOWNLOAD_CSV : "Download do arquivo CSV",
		REPORT_ARCHIVE_TITLE : "Arquivar relatório",
		REPORT_ARCHIVE_COORDINATES : "Coordenadas",
		REPORT_ARCHIVE_SCANTIME : "Data do Scan",
		REPORT_ARCHIVE_DELETE : "Apagar estes dados",
		REPORT_ARCHIVE_CONFIRM_DELETE : "Você quer mesmo apagar estes dados?",
		REPORT_ARCHIVE_GALAXY : "Galaxia",
		REPORT_ARCHIVE_SYSTEM : "Systema",
		REPORT_ARCHIVE_PLANET : "Planeta",
		REPORT_ARCHIVE_MOON : "Lua",
		REPORT_ARCHIVE_DETAILS : "Detalhes",
		REPORT_ARCHIVE_RESOURCES : "Recursos por hora",
		REPORT_ARCHIVE_HEADER_RESOURCES : "Recursos",
		REPORT_ARCHIVE_DETAILS_FOR : "Arquivar relatório por &1 [&2] (&3)",
		REPORT_ARCHIVE_FLEET_CARGO : "Capacidade de transporte da frota",
		REPORT_ARCHIVE_IRAK_RANGE : "Alcance do Míssil Interplanetário",
		REPORT_ARCHIVE_CHART_TYPE : "Tipo de gráfico",
		INSTALL_TITLE : "Instalar o Galaxytool, versão",
		INSTALL_PROGRESS : "Progresso",
		INSTALL_STEP : "Passo",
		INSTALL_CONTINUE : "Continue",
		INSTALL_VALIDATE : "Validar",
		INSTALL_STEP1 : "Benvindo",
		INSTALL_STEP2 : "Gravável check",
		INSTALL_STEP3 : "Configurações do Banco de Dados",
		INSTALL_STEP4 : "Configurações  OGame",
		INSTALL_STEP5 : "Configurações  Galaxytool",
		INSTALL_STEP6 : "Admin senha",
		INSTALL_STEP7 : "Instalar Galaxytool",
		INSTALL_STEP8 : "Finalize instalar",
		INSTALL_FILE_DELETE_CHECK : "Porfavor, apagueos arquivos install.php e update.php do seu servidor.",
		INSTALL_STEP1_PHP_FAILED : "Seu PHP version &1 não esta funcionando com o Galaxytool versão",
		INSTALL_STEP1_FOPEN_FAILED : "Seu PHP versão não permite abrir páginas da Web com o comando FOPEN(). Isto é necessário para consumir o OGame API.",
		INSTALL_STEP1_WELCOME : "Bem-vindo ao assistente de instalação do Galaxytool. Você será guiado através da instalação do Galaxytool.",
		INSTALL_STEP2_DESCRIPTION : "Verifique se seus arquivos config.php e attributes.php tem permissões de gravação habilitado.",
		INSTALL_STEP2_DESCRIPTION2 : "Se você não sabe, como conseguir isso, por favor dê uma olhada aqui: &1",
		INSTALL_STEP2_FILE_NOT_WRITEABLE : "O arquivo não é gravável",
		INSTALL_STEP3_SERVER : "Servidor de banco de dados",
		INSTALL_STEP3_USERNAME : "Usuário",
		INSTALL_STEP3_PASSWORD : "Senha",
		INSTALL_STEP3_DBNAME : "Nome do Banco de dados",
		INSTALL_STEP3_PREFIX : "Prefixo Tablename",
		INSTALL_STEP3_ENTER_PREFIX : "E.x. meutool_",
		INSTALL_STEP3_ENTER_SERVER : "Digite o endereço do servidor. Contacte o seu administrador do sistema, se necessário. Normalmente, o valor correto é localhost.",
		INSTALL_STEP3_ENTER_USERNAME : "Digite o nome do usuário para acesso ao banco de dados",
		INSTALL_STEP3_ENTER_PASSWORD : "Digite a senha do usuário para acesso ao bancos de dados",
		INSTALL_STEP3_ENTER_DBNAME : "Digite o nome do banco que será utilizado para instalação (deve existir)",
		INSTALL_STEP3_CONNECT_FAILED : "Não foi possível estabelecer conexão com o servidor de banco de dados",
		INSTALL_STEP3_DB_FAILED : "Banco de dados &1 não encontrado",
		INSTALL_STEP3_MYSQL_VERSION_FAILED : "MySQL versão &1 não esta funcionando com esta versão do Galaxytool",
		INSTALL_STEP4_URL : "OGame URL",
		OGAME_URL_DETAILS : "Porfavor entre qualquer URL que você ver quando logado no OGame. Com base nesta URL a ferramente irá derivar o endereço API OGame com o qual será possivel inserir dados no Galaxytool sem a nescessidade do Galaxytoolbar. Esta API foi introduzina no OGame versão 4.1.",
		INSTALL_STEP4_UNIVERSE : "OGame Universo",
		INSTALL_STEP4_DEF_TO_DEBRIS : "Defesa para detritos",
		INSTALL_STEP4_DEBRIS_RATE : "Taxa de Detritos",
		INSTALL_STEP4_SPEED_RATE : "Velocidade",
		INSTALL_STEP4_ENTER_UNIVERSE : "Digite o nome ou numero do seu Universo OGame (case sensitive).",
		INSTALL_STEP4_UNIVERSE_MISSING : "Você deve definir o seu universo",
		INSTALL_STEP4_ENTER_URL : "Entre com o endereço do universo OGame",
		INSTALL_STEP4_URL_MISSING : "Você deve definir o seu endereço de OGame",
		INSTALL_STEP4_URL_CHECK_FAILED : "Não foi possível encontrar OGame API em &1",
		INSTALL_STEP4_GETSETTINGS : "Fetch settings",
		INSTALL_STEP5_TOOLNAME : "Nome Galaxytool",
		INSTALL_STEP5_ENTER_TOOLNAME : "Este é o nome que será mostrado na página de logon para identificar o seu Galaxytool",
		INSTALL_STEP5_LANGUAGE : "Idioma padrão",
		INSTALL_STEP5_EMAIL_TO : "Email para",
		INSTALL_STEP5_ENTER_EMAIL_TO : "Digite o endereço de e-mail onde você gostaria de receber notificações sobre registros",
		INSTALL_STEP5_EMAIL_FROM : "Email De",
		INSTALL_STEP5_ENTER_EMAIL_FROM : "Este endereço de e-mail é mostrado como a resposta para todos os e-mails enviados a partir do Galaxytool",
		INSTALL_STEP5_USE_PHPMAILER : "Use PHPMailer",
		INSTALL_STEP5_MAXSHOUTS : "O número máximo de entradas shoutbox",
		INSTALL_STEP5_ENTER_USE_PHPMAILER : "Use PHPMailer se o servidor não suporta o envio e-mails por padrão",
		INSTALL_PHPMAILER_HOST : "SMPT Host",
		INSTALL_PHPMAILER_HOST_EXAMPLE : "e.x. smtp.provider.com",
		INSTALL_PHPMAILER_USER : "SMPT Username",
		INSTALL_PHPMAILER_USER_EXAMPLE : "e.x. user@provider.dcom",
		INSTALL_PHPMAILER_PASS : "SMPT senha",
		INSTALL_PHPMAILER_SECURE : "Método de autenticação (e.x. ssl)",
		INSTALL_PHPMAILER_PORT : "SMTP Port",
		INSTALL_STEP6_INTRO : "Por favor, defina uma senha para a conta <strong>admin</strong> que você tem que usar para o seu primeiro logon para o Galaxytool após a instalação.",
		INSTALL_STEP7_CONFIG : "Arquivo de configuração criado",
		INSTALL_STEP7_CONFIG_FAILED : "Arquivo de configuração não criado",
		INSTALL_STEP7_ATTRIBUTES : "Arquivo de Atributos criado",
		INSTALL_STEP7_ATTRIBUTES_FAILED : "Arquivo de Atributos Não criado",
		INSTALL_STEP7_CREATED_TABLES : "Tabelas de banco de dados criado",
		INSTALL_STEP8_INTRO : "Você instalou com sucesso o Galaxytool!",
		INSTALL_STEP8_LOAD_DATA : "Downloading dados do OGame ...",
		INSTALL_STEP8_LOAD_DATA_FINISHED : "Download dos dados do OGame terminou",
		INSTALL_STEP8_DELETE_FILE : "Você deve agora apagar os arquivos install.php e update.php do servidor.",
		INSTALL_STEP8_LOGON : "Porfavor logue com o usuário <strong>admin</strong> e senha que você definiu anteriormente.",
		UPDATE_START : "Iniciando a atualização para a versão &1",
		UPDATE_STEP_DONE : "Feito",
		UPDATE_TITLE : "Update da versão do Galaxytool",
		UPDATE_STEP1_WELCOME : "Bem-vindo ao assistente de atualização do Galaxytool. Você será guiado através da atualização doGalaxytool.",
		UPDATE_STEP1_BACKUP_FILES : "Como primeiro passo, faça um backup da sua pasta <strong>config</strong>! Você terá que substituir o conteúdo de configuração em caso de erros.",
		UPDATE_STEP1_BACKUP_DB : "Então faça uma <a href=\"http://www.ehow.com/how_2036600_create-database-php.html\">backup</a> do seu banco de dados",
		UPDATE_STEP1_PROCEED : "Uma vez que os backups foram feitos, você pode prosseguir com a sua atualização.",
		UPDATE_STEP1 : "Benvindo",
		UPDATE_STEP2 : "Configurações  Galaxytool",
		UPDATE_STEP2_OLD_VERSION : "Versão antiga do Galaxytool",
		UPDATE_STEP3 : "Update Galaxytool",
		UPDATE_STEP3_UPDATE_RUNNING : "Atualize execução, por favor aguarde ...",
		UPDATE_STEP4 : "Update finalizado",
		UPDATE_STEP4_INTRO : "Você atualizou com êxito o Galaxytool!",
		UPDATE_STEP4_UPDATE_DONE : "Etapas da atualização realizada.",
		UPDATE_FAILED : "Update não realizado.",
		GALAXYTOOL_DUMMY_TEXT : "dummy"
	})
);